### ISSUE TITLE
WebUI random feedback

### ISSUE THREAD

**Issue by ffd8** [invoke-ai/InvokeAI#1002]
Amazing work on this repo + WebUI! 
Here's a few random feedbacks to share of things I've run into (latest dev) - just some random user feedback:
- `CTRL + ENTER` doesn't work when adjusting the values of `Steps` or `CFG Scale`, (was also true a week ago, when it was just 'Enter'.. thus requires an extra click with the mouse to de-focus the input box, but i love tweaking the numbers via keyboard then would be great to 'invoke' (using `CTRL + ENTER` or also simply `ENTER`.
- A week+ ago, after `Invoking`, the focus was returned to the input text box, which was great to allow one to just hit `enter` again, or adjust the prompt via keyboard and again hit enter.. at the moment, one has to constantly use the mouse to re-set the focus.
- The UI a week+ ago, was a little more helpful, with fewer options being hidden/toggled-away.. playing with the `seed` doesn't seem like an advanced feature, since it's so necessary when refining a prompt, and `seamless` is now tucked under `other`, whereas it could just be a toggle right under the size. Just to re-consider how much needs to be tucked away and available all the time. The overall size of elements causes a lot of scrolling to see all UI options, which wasn't the case a week+ ago.
- For Img2Img, (perhaps icon hints should instead say `txt2img` and `img2img` to stay in SD lingo), the UI a week ago seemed more helpful, allowing both an input image and a mask.. with the new large side by side, I can't find the mask option.. and clicking on `Image to Image`, only reveals one additional UI options (+ the big thumbnail), whereas it doesn't seem to need a dedicated button and was helpful when it was just available all the time with an easy toggle on/off. A week+ ago it was also easier to trash the input image (and mask) with an easy to find button right next to the image.. now one has to search the UI at top for the trash can, which is far from the image, one also has to trash before uploading a new one (wasn't necessary before). But again, this new big side by side takes up lots of retail space, not to mention I can't see the output image unless making the aspect ratio really wide and short (due to it tracking the `vh`).
- The gallery (invokations) should probably start 75-100px from the top, since it currently covers up the UI elements for settings/info/etc. Is probably helpful to have it open by default, and collapsable on demand.
- Expanding the gallery works really well! The main displayed image, however isn't centered between the left UI and the gallery.. nor does it scale down to always remain visible when the gallery gets bigger.
- It would be helpful if each section of the UI could be reset, rather than the entire thing.. ie, next to the collapse icon, one could `recycle` or `trash` icon for resetting it..
- In this latest version, the progress bar at the top is quite hard to see, thin and not such a high-contrast. I'd suggest making the bar a little thicker and brighter in dark mode, darker in lightmode.
- It's been mentioned in another thread, but it would be really helpful to have the `info` for a previous item be visible all the time without overlaying, so I could quickly see what settings one had while still working.
- One thing that could be added to the `info`, is the complete prompt, as the CLI received it. One can grab this from the log, but it would be awesome to just be an easy `copy to clipboard` from that info panel.. why? It's nice to use the UI to experiment and test an idea, then use that tweak a CLI command with some javascript to create a text file to process in batch. ie. batch processing frames of input images or lots of frames with variations etc.

**Comment by blessedcoolant** [comment]
Thanks for the feedback. Here are my thoughts on it.
 
> * `CTRL + ENTER` doesn't work when adjusting the values of `Steps` or `CFG Scale`, (was also true a week ago, when it was just 'Enter'.. thus requires an extra click with the mouse to de-focus the input box, but i love tweaking the numbers via keyboard then would be great to 'invoke' (using `CTRL + ENTER` or also simply `ENTER`.

I agree. I guess just elevating the hotkey to the top level should fix this issue even if other elements are in focus. I'll look ino it.

> * A week+ ago, after `Invoking`, the focus was returned to the input text box, which was great to allow one to just hit `enter` again, or adjust the prompt via keyboard and again hit enter.. at the moment, one has to constantly use the mouse to re-set the focus.

Are you sure? As long as I'm not changing the focus from the prompt box after pressing Enter, I am being returned there as expected.

> * The UI a week+ ago, was a little more helpful, with fewer options being hidden/toggled-away.. playing with the `seed` doesn't seem like an advanced feature, since it's so necessary when refining a prompt, and `seamless` is now tucked under `other`, whereas it could just be a toggle right under the size. Just to re-consider how much needs to be tucked away and available all the time. The overall size of elements causes a lot of scrolling to see all UI options, which wasn't the case a week+ ago.

This was a design choice that was made intentional to facilitate beginners. The main panel has options that are absolutely essential for controlling the image generation. The reason seed is tucked away inside advanced options is because most users just expect a new image each time. Which is the functionality by default. And if they find themselves trying to edit the seed manually, then I feel that falls under the realm of advanced setting changes.

Having more and more options right out there will overwhelm some users who are unfamiliar with how all of this works. I feel right now we have a good trade between what is primarily visible and what is right there for accessibility.



> * For Img2Img, (perhaps icon hints should instead say `txt2img` and `img2img` to stay in SD lingo), the UI a week ago seemed more helpful, allowing both an input image and a mask.. with the new large side by side, I can't find the mask option.. and clicking on `Image to Image`, only reveals one additional UI options (+ the big thumbnail), whereas it doesn't seem to need a dedicated button and was helpful when it was just available all the time with an easy toggle on/off. A week+ ago it was also easier to trash the input image (and mask) with an easy to find button right next to the image.. now one has to search the UI at top for the trash can, which is far from the image, one also has to trash before uploading a new one (wasn't necessary before). But again, this new big side by side takes up lots of retail space, not to mention I can't see the output image unless making the aspect ratio really wide and short (due to it tracking the `vh`).

Masking is not a part of img2img. That actually falls under inpainting. So we removed it. We are working on a dedicated inpainting UI that lets you paint a mask directly in the UI. So having a mask feature in img2img serves no purpose. We'll have the inpainting UI up and running soon.

> * The gallery (invokations) should probably start 75-100px from the top, since it currently covers up the UI elements for settings/info/etc. Is probably helpful to have it open by default, and collapsable on demand.

This has already been fixed. How the gallery is displayed has been changed with other changes to it. Did you try it out yet?

> * It would be helpful if each section of the UI could be reset, rather than the entire thing.. ie, next to the collapse icon, one could `recycle` or `trash` icon for resetting it..

Hmm. Will add it to my list of notes to consider adding. I would like a reset to default value too for each field.

> * In this latest version, the progress bar at the top is quite hard to see, thin and not such a high-contrast. I'd suggest making the bar a little thicker and brighter in dark mode, darker in lightmode.

Will work it out.

> * It's been mentioned in another thread, but it would be really helpful to have the `info` for a previous item be visible all the time without overlaying, so I could quickly see what settings one had while still working.

What do you mean? You can currently select an image in the gallery and the info for that would show up as long as the metadata is open. Which you can enable by pressing I. Not sure what you mean by previous item info should be visible? 


> * One thing that could be added to the `info`, is the complete prompt, as the CLI received it. One can grab this from the log, but it would be awesome to just be an easy `copy to clipboard` from that info panel.. why? It's nice to use the UI to experiment and test an idea, then use that tweak a CLI command with some javascript to create a text file to process in batch. ie. batch processing frames of input images or lots of frames with variations etc.

You can recall the prompt from any image using the metadata viewer and copy paste that?

**Comment by psychedelicious** [comment]
> > One thing that could be added to the info, is the complete prompt, as the CLI received it. One can grab this from the log, but it would be awesome to just be an easy copy to clipboard from that info panel.. why? It's nice to use the UI to experiment and test an idea, then use that tweak a CLI command with some javascript to create a text file to process in batch. ie. batch processing frames of input images or lots of frames with variations etc.
> 
> You can recall the prompt from any image using the metadata viewer and copy paste that?

Actually I don't think it is displayed, this got removed at some point, can't remember why. Will need to fix that. Also I'll just note UI is not interacting with the CLI - it interacts with the internal generation system directly, like the CLI does. While it's not one-to-one, we can provide CLI commands for at least txt2img/img2img.

**Comment by blessedcoolant** [comment]
> Actually I don't think it is displayed, this got removed at some point, can't remember why. Will need to fix that. Also I'll just note UI is not interacting with the CLI - it interacts with the internal generation system directly, like the CLI does. While it's not one-to-one, we can provide CLI commands for at least txt2img/img2img.

![firefox_3AtKbZasxE](https://user-images.githubusercontent.com/54517381/194788976-9751ceba-410c-4ed7-a238-b4d65e541e46.png)

Are we not talking about this? Or am I misunderstanding this.

**Comment by ffd8** [comment]
Thanks for the quick thorough replies. Just loaded the laaaatest dev and a handful of remarks above were indeed fixed.. haha next time i'll be sure to load the dev of the day to be sure. Regarding a few points that still remain:

>> A week+ ago, after Invoking, the focus was returned to the input text box, which was great to allow one to just hit enter again, or adjust the prompt via keyboard and again hit enter.. at the moment, one has to constantly use the mouse to re-set the focus.
> _Are you sure? As long as I'm not changing the focus from the prompt box after pressing Enter, I am being returned there as expected._
Yup, at least a week+ ago, when you hit just `enter` while in the prompt window, after the image was done, the text cursor was still active within the prompt input (focused), so one could just tap left/right arrows, adjust prompt and hit `enter` again. At the moment, the focus is lost.. I think it's helpful when it returns once the image is done (maybe only if it was the last thing focused upon hitting `enter`??)

>> It's been mentioned in another thread, but it would be really helpful to have the info for a previous item be visible all the time without overlaying, so I could quickly see what settings one had while still working.
_What do you mean? You can currently select an image in the gallery and the info for that would show up as long as the metadata is open. Which you can enable by pressing I. Not sure what you mean by previous item info should be visible?_
While one can quickly just hit `i` to toggle this on and off all the time.. throw a vote towards it being useful to have a dedicated panel/space (between main image and gallery?) where this info could always be left visible while still seeing the main image. The overlay is nice if rarely looking at those values, but in the way if experimenting a lot with things like CFG/steps and wanting to double check values between outputs (while seeing them clearly)

Lastly, my comment about getting the CLI prompt/command within the info metadata, indeed, what I meant was not the prompt which is there, but the CLI command, as found within the `logs.txt` document (and seems to be the complete thing?). Perhaps the metadata could scrape what gets written to that log? It might help folks experiment within the UI, then continue experimenting with CLI (or in my selfish case, use that full command for scripting with variables). Current workflow is fine, just close/reopen the logs file – but with all the other great metadata shown/stored, this might be helpful (and listed as `Command` or `CLI Command`).

**Comment by ffd8** [comment]
@blessedcoolant re:
> CTRL + ENTER doesn't work when adjusting the values of Steps or CFG Scale, (was also true a week ago, when it was just 'Enter'.. thus requires an extra click with the mouse to de-focus the input box, but i love tweaking the numbers via keyboard then would be great to 'invoke' (using CTRL + ENTER or also simply ENTER.
_I agree. I guess just elevating the hotkey to the top level should fix this issue even if other elements are in focus. I'll look ino it._

Indeed, upon more testing, if any UI element is focused (toggle button, input box), then the `CTRL + ENTER` doesn't work.. so it should move up to a window listener. As mentioned above, it would be helpful if pressing `CNTRL + ENTER` quickly stored which element was focused (if any) then returned focus to it.. so if one is adjusting `Perlin Noise` values, they can constantly tweak, test, tweak, test, without the mouse.

**Comment by psychedelicious** [comment]
If there are still requested features in this issue that you want to see, please open an issue for each individual feature request.
