### ISSUE TITLE
WebUI performance issues (memory leak?)

### ISSUE THREAD

**Issue by griffwill** [invoke-ai/InvokeAI#1004]
**Describe your environment**
- GPU: mps
- VRAM: 64 GB
- CPU arch: ARM
- OS: macOS
- Python: anaconda
- Branch: Development
- Commit: 3170c83d8de7189fae3aa6df555bd40abc2d0328

**Describe the bug**
pulled latest dev branch this morning and webUI seems very slow to respond/very laggy. Taking a look at memory usage, I am seeing python consuming 12GB of RAM at idle. When running just dream.py without `--web`, idle memory usage is 4.5 GB of RAM. when starting the web server, it starts at 4.5, after generating one image in the UI, that goes up to 7.2, it appears that usage may be climbing with each subsequent image generation
**To Reproduce**
launch dream.py with --web and --host flags, generate a few images. general usage of the webUI on Mac

**Additional context**
not sure if this is Mac specific or how to isolate further. I did reset the webUI as well as clearing the output directory incase this was trying to load up all of the image previews in gallery and issue persisted

**Comment by griffwill** [comment]
doing some regression through previous commits, and it looks like the breaking commit was 1b02074 - Smaller Gallery Images.

other info when testing in this specific commit: when trying to click on image thumbnails in the gallery drawer, the CPU usage for the webpage spikes to 30%-100% CPU usage

**Comment by lstein** [comment]
I haven't been able to confirm this on a CUDA system. Performance and memory usage seem about the same as they were prior to commit in question.

I've asked our resident web and Mac experts to take a look.

**Comment by lstein** [comment]
Reported by another user on the Discussion thread. This seems to be a Safari-specific bug, which is why I wasn't able to reproduce it.

**Comment by griffwill** [comment]
thought it may be safari specific. @blessedcoolant and @Any-Winter-4079, let me know if there’s any additional information or logs I can provide if more debug info is needed

**Comment by Any-Winter-4079** [comment]
I'll try to check later tonight.

**Comment by Any-Winter-4079** [comment]
Checked. Yeah, it's terrible.

**Comment by Any-Winter-4079** [comment]
One thing is I don't think it's about RAM. I have 64GB and the process at most takes about 10GB.

**Comment by lstein** [comment]
This seems to be a Safari-specific issue. I have backed out PR #1000 , which is the last one before this issue appeared. Could you check out `main` and see if the problem has resolved?

**Comment by Any-Winter-4079** [comment]
@blessedcoolant @lstein The problem seems to be the Gallery.
<img width="90" alt="Screenshot 2022-10-10 at 00 33 22" src="https://user-images.githubusercontent.com/50542132/194782515-ed46b06f-f5ae-4cec-98b6-12b4ca3bb89d.png">

Collapsing it makes the website behave well and fluid. @griffwill can you test this?

**Comment by Any-Winter-4079** [comment]
No JS log (so no error reported) opening it. Just makes the site almost freeze / slow to a crawl.

**Comment by Any-Winter-4079** [comment]
There is definitely a big difference here.
Brave.
<img width="638" alt="Screenshot 2022-10-10 at 00 38 04" src="https://user-images.githubusercontent.com/50542132/194782700-41084e45-34f9-4721-92c3-b93ab2e8d035.png">
Safari.
<img width="1644" alt="Screenshot 2022-10-10 at 00 38 20" src="https://user-images.githubusercontent.com/50542132/194782709-708a95e3-fa96-4fea-bb7f-28af8144f3aa.png">

**Comment by Any-Winter-4079** [comment]
Currently checking out `main`.

**Comment by hipsterusername** [comment]
@griffwill - can you test https://github.com/blessedcoolant/InvokeAI/tree/webui-safari-lag-fix ? @blessedcoolant is trying to isolate where the issue is being introduced

**Comment by Any-Winter-4079** [comment]
@hipsterusername Can I check out that repo without downloading a duplicate codebase additional to this one?

**Comment by Vargol** [comment]
As I posted somewhere else, problem the release-canidate-2 thread, it seems to kick in as images show up in the gallery, no images, gives decent response even with the gallery visible. It may even be more images in the gallery the slower it gets
but my crappy 8Gb is not fast enough for me to generate the images in any sensible time to test that properly

**Comment by Vargol** [comment]
Still slow using this... 

(InvokeAI) InvokeAI % git show
commit 0d11f19e0fa851b42b5223e1ac4534e45cb770f6 (HEAD -> webui-safari-lag-fix, origin/webui-safari-lag-fix)
Author: blessedcoolant <54517381+blessedcoolant@users.noreply.github.com>
Date:   Mon Oct 10 11:51:15 2022 +1300

**Comment by blessedcoolant** [comment]
We're isolating the issue. Hopefully we'll have a fix soon.

**Comment by blessedcoolant** [comment]
@psychedelicious Seems to have isolated the bug. It's some stupid CSS related issue. He'll deploy a fix soon.

**Comment by blessedcoolant** [comment]
Please try out #1009 and see if it resolves this issue.

**Comment by Any-Winter-4079** [comment]
The PR seems to fix the issue!
