### ISSUE TITLE
WebUI - some values are not modified by Use All and Use All Parameters

### ISSUE THREAD

**Issue by Vargol** [invoke-ai/InvokeAI#1007]
**Describe your environment**

Invoke running on..
- GPU: MPS
- VRAM: 8Gb unified memory
- CPU arch: arm64
- OS: macOS
- Python: venv and pip
- Branch: release-candidate-2
- Commit: HEAD

Web Browser details.
Firefox 105.0.3 on macOs 11.7 x64 processor 

**Describe the bug**
Couple of web issues I'm seeing with using 'Use All' and 'Use All Parameters'

They do not seem to set the Images count, nor disable Restore Face and Upscale where it wasn't used
When using an image where Upscale and Restore Face where used they do not update the values

**To Reproduce**
Generate a number of images, use Restore Face and Upscale for some of them
Change the image, Restore Face and Upscale values
Choose the image where Upscale and Restore Face where used, then use the Use All option or Use All Parameters option for the Gallery.
Note the values do not go back to the ones used for the image.
Choose and image where Upscale and Restore Face where NOT used, then use the Use All option or Use All Parameters option for the Gallery.
Note the Upscale and Restore Face do not Disable, and the image value goes not change back to the value used to generate the image.

**Expected behavior**
In the first example the values should be update to the ones used to generate the image.
In the second example Upscale and Restore Face  should be disabled as they where not used to generate the image.

**Comment by Vargol** [comment]
Add variations to the list, if the image does not have variations it disables variations if enabled, but  if an image has variations it does not update 'Variation Amount'

**Comment by i3oc9i** [comment]
variation restoration seems to be taken into accoun in the main brach.
