### ISSUE TITLE
Matrices and negative prompts?

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#1008]
Greetings,

Negative prompts would be a nice addition: 

great results:
https://www.reddit.com/r/promptcraft/comments/xwyi2v/stable_diffusion_negative_prompt_experiments/

inspiration:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Negative-prompt

What about: 
portrait of chuck Norris fighting super man | bill gates | sponge bob -n3
result: generates an image with each hero

or alike?

thank you,

**Comment by lstein** [comment]
Put any number of terms in square brackets to have their concepts excluded from the image. See <a href="https://github.com/invoke-ai/InvokeAI/blob/main/docs/features/PROMPTS.md#negative-and-unconditioned-prompts">Negative and Unconditioned Prompts</a>

**Comment by Neosettler** [comment]
That is marvelous, thank you [lstein](https://github.com/lstein)! | operator would be a very nice complement though.

**Comment by i3oc9i** [comment]
Personally i'm not a fun of the '|' operator, it make the prompt diffcult to read, also it will non easy to limit its scope. Indeeed, If used at the begining of the prompt or in the middle, we need to introduce some kind of scope delimither, like curly brackets for example.

**Comment by Neosettler** [comment]
good point [i3oc9i](https://github.com/i3oc9i), while "difficult to read" remains subjective, where does the effect of the | ends is quite real. any of these would work but comma delimiter should be just fine:
[super man | bill gates | sponge bob]
(super man | bill gates | sponge bob)
{super man | bill gates | sponge bob}
, super man | bill gates | sponge bob,

**Comment by Neosettler** [comment]
Thinking about it, having a consensus would be beneficial. The way I discovered about negative prompt was from a posted image with embed prompt in the metadata of the image on discord. To automate the retrieval of the prompt (while drag and drop into UI), I have to parse every single convention out there because there is no standard. Just saying, we might want to reach out and coordinate rather then make another standard.

**Comment by i3oc9i** [comment]
may be comma is not the best option. Thinking to something like this:

`An old man walking in the middle of a  (forest | city | canyon), photo realistic, in the style of ( author1, author2, author3 )`

This prompt should generate 9 images

**Comment by Neosettler** [comment]
I guess you meant:

`An old man walking in the middle of a (forest | city | canyon), photo realistic, in the style of (author1 | author2 | author3)
`
That would work beautifully!

**Comment by i3oc9i** [comment]
> `An old man walking in the middle of a (forest | city | canyon), photo realistic, in the style of (author1 | author2 | author3) 

Yes, wrting in the metro with a phone it is somethime complicated..... :)

**Comment by 19wolf** [comment]
Automatic1111 uses the convention of `{1, 2, 3}` for matrix prompts, perhaps it's best to stick with that here as well?

**Comment by Neosettler** [comment]
as much as I prefer (forest | city | canyon), I think [19wolf](https://github.com/19wolf) is right.

**Comment by Neosettler** [comment]
Taking into consideration that Automatic1111 is sailing quite nicely among the community. It might be a good idea to mimic it's convention all together. Not super noble but it seems like a smart move.

**Comment by Neosettler** [comment]
This box:sphere:0.5 [feature ](https://www.youtube.com/watch?v=WwX_7HIJBTM) is quite nice!

**Comment by Neosettler** [comment]
Just checking on progress... is there any hope for | operator in  next release?
