### ISSUE TITLE
Prompts in the output' files names

### ISSUE THREAD

**Issue by netsvetaev** [invoke-ai/InvokeAI#1010]
All output files are saved with number.seed.png names. I want to save them with prompts inside the names. How?

Use case is: I need ~1000 images for articles. Each article has a title, so I'll try to put it in the prompt with additions, and save with that prompt as a title.

**Comment by n00mkrad** [comment]
You can try my GUI if you're running windows, it has this as an option, is open source, and based on InvokeAI.

https://nmkd.itch.io/t2i-gui

**Comment by i3oc9i** [comment]
probably the prompt can be quite long and it can contains illegal characters to be used into a file name, but explicitly name the output file can be useful, I agree

**Comment by netsvetaev** [comment]
> You can try my GUI if you're running windows, it has this as an option, is open source, and based on InvokeAI.
> 
> https://nmkd.itch.io/t2i-gui

I’m on mac :-)

**Comment by netsvetaev** [comment]
> probably the prompt can be quite long and it can contains illegal characters to be used into a file name, but explicitly name the output file can be useful, I agree

@i3oc9i I thought about that. But it's okay to trim the prompt in some place, after 128 characters or so, remove illegal characters, etc. And I'm thinking maybe I can do it with some external script. Files names are already in the log file with the prompts, so I just need to take them from there and change the names according to the log.

**Comment by lstein** [comment]
The prompt is also located inside each file's metadata. The scripts `image2prompt.py` and `sd-metadata.py` will retrieve the prompt and other generation arguments.

There's also a CLI command-line switch `--prompt_as_dir` which will store each image into a directory named after the prompt used to generate it.
