### ISSUE TITLE
ANNOUNCEMENT - InvokeAI 2.0.0 is released!

### ISSUE THREAD

**Issue by lstein** [invoke-ai/InvokeAI#1012]
Hey everyone! The invoke-ai team and I are happy to announce the release of *InvokeAI 2.0 - A Stable Diffusion Toolkit*, a project that aims to provide enthusiasts and professionals both a suite of robust image creation tools. Optimized for efficiency, InvokeAI needs only ~3.5GB of VRAM to generate a 512x768 image (and less for smaller images), and is compatible with Windows/Linux/Mac (M1 & M2).

InvokeAI was one of the earliest forks off of the core CompVis repo (formerly lstein/stable-diffusion), and recently evolved into a full-fledged community driven and open source stable diffusion toolkit titled InvokeAI. The new version of the tool introduces an entirely new WebUI Front-end with a Desktop mode, and an optimized back-end server that can be interacted with via CLI or extended with your own fork.

This version of the app improves in-app workflows leveraging GFPGAN and Codeformer for face restoration, and RealESRGAN upscaling - Additionally, the CLI also supports a large variety of features:
- Inpainting 
- Outpainting
- Prompt Unconditioning
- Textual Inversion
- Improved Quality for Hi-Resolution Images (Embiggen, Hi-res Fixes, etc.)
- And more...

Future updates planned included UI driven outpainting/inpainting, robust Cross Attention support, and an advanced node workflow for automating and sharing your workflows with the community. To learn more, head over to https://github.com/invoke-ai/InvokeAI
lstein

**Comment by n00mkrad** [comment]
Details on "Hi-res Fixes"? Any commits to refer to?

**Comment by easp** [comment]
Just noticed that in the install docs

`conda activate ldm`

should instead be 

`conda activate invokeai`

**Comment by psychedelicious** [comment]
We are on to 2.0.2 by now!
