### ISSUE TITLE
Infinite Installing Pip Dependencies

### ISSUE THREAD

**Issue by Bored-Anarchist** [invoke-ai/InvokeAI#1015]
When updating to 2.0 and running `conda env update`, installing pip dependencies is stuck and continues going forever. I have the default settings on everything. Please send advice. Thanks.

**Comment by Bored-Anarchist** [comment]
Got it, thanks.

**Comment by TheBarret** [comment]
Tried the /src to /src.backup but it just gets stuck again. No idea how to fix this.

**Comment by Bored-Anarchist** [comment]
> Tried the /src to /src.backup but it just gets stuck again. No idea how to fix this.
> 
> Also tried it manually but i get tons of errors. `ERROR: Could not find a version that satisfies the requirement basicsr>=1.3.3.11 (from realesrgan) (from versions: 1.3.1, 1.3.2, 1.3.3, 1.3.3.1, 1.3.3.3, 1.3.3.4, 1.3.3.5, 1.3.3.6, 1.3.3.7, 1.3.3.8, 1.3.3.9, 1.3.3.10, 1.3.3.11, 1.3.4.0, 1.3.4.1, 1.3.4.2, 1.3.4.3, 1.3.4.4, 1.3.4.6, 1.3.4.7, 1.3.4.8, 1.3.4.9, 1.3.5, 1.4.0, 1.4.1, 1.4.2) ERROR: No matching distribution found for basicsr>=1.3.3.11`

This issue is closed. Start a new issue to discuss your issue or get on the discord and bring it up.

**Comment by Bored-Anarchist** [comment]
Or do both

**Comment by phineas-pta** [comment]
why is this issue closed? the solution should also be added to installation instruction
