### ISSUE TITLE
1 leaked semaphore objects to clean up at shutdown

### ISSUE THREAD

**Issue by michaelezra** [invoke-ai/InvokeAI#1016]
**Describe your environment**
- GPU: [cuda/amd/mps/cpu] M1 Max 64 GB 32 GPU
- CPU arch: [x86/arm] arm
- OS: [Linux/Windows/macOS] Mac OS 12.6
- Python: miniforge3/bin/python3  3.9
- Branch:  main,  v2.0.0

**Describe the bug**
I could not resist and tried generating image in larger resolution.
There appear to be 1 leaked semaphore objects to clean up at shutdown
Please see the console log below:

>> Image generation requested: {'prompt': 'dreamy landscape', 'iterations': 1, 'steps': 5, 'cfg_scale': 7.5, 'threshold': 0, 'perlin': 0, 'height': 2048, 'width': 1024, 'sampler_name': 'k_lms', 'seed': 953554622, 'seamless': False, 'progress_images': False, 'variation_amount': 0}
ESRGAN parameters: False
GFPGAN parameters: False
Generating:   0%|                                                                                                                                                                            | 0/1 [00:00<?, ?it/s]>> Sampling with k_lms starting at step 0 of 5 (5 new sampling steps)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [01:45<00:00, 21.05s/it]
/AppleInternal/Library/BuildRoots/a0876c02-1788-11ed-b9c4-96898e02b808/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:705: failed assertion `[MPSTemporaryNDArray initWithDevice:descriptor:] Error: product of dimension sizes > 2**31'
zsh: abort      python3 ./scripts/invoke.py --web
(ldm) michaelezra@Michaels-MBP stable-diffusion % /Users/michaelezra/miniforge3/envs/ldm/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: **There appear to be 1 leaked semaphore objects to clean up at shutdown**
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by Any-Winter-4079** [comment]
Seems to be a problem when saving the file (?)
>> Sampling with k_lms starting at step 0 of 5 (5 new sampling steps)
`100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [01:56<00:00, 23.21s/it]`

I managed to get to 100% (max 27GB RAM) but it crashed afterwards.

**Comment by Any-Winter-4079** [comment]
Tried with `if psutil.virtual_memory().available / (1024**3) < 24:` vs. `if psutil.virtual_memory().available / (1024**3) < 12`: which made me go to the else route -initially there for @Vargol and 8GB RAM- as I had 20824997888 available at that point, but still, it failed.
```
else:
            print(psutil.virtual_memory().available)
            if psutil.virtual_memory().available / (1024**3) < 24:
                slice_size = 1
            else:
                slice_size = min(q.shape[1], math.floor(2**30 / (q.shape[0] * q.shape[1])))
```
This time RAM did not jump above 20GB even after 100% on Activity Monitor, but the error remains the same.

It'd be interesting to test vs. an older version, to see if some change was introduced, or the error was always there.
PS: 1024x1024 worked fine.

**Comment by michaelezra** [comment]
Good news, I was able to render 1920x1920px image!

**Comment by Any-Winter-4079** [comment]
@michaelezra I could generate a 1920x1920 too.

**Comment by lstein** [comment]
Do we need a PR?

**Comment by Any-Winter-4079** [comment]
1920x1920 works, while 2048x1024 fails, which is a bit odd, since the larger one (1920x1920) works. It seems 2048 > 1920 has more importance than size.

In general, I'm pretty sure most (reasonably) large size combinations work, so I don't think a PR is urgently needed.

Nevertheless, it'd be interesting to see if this problem has always been there or was introduced recently.

**Comment by Vargol** [comment]
> 1920x1920 works, while 2048x1024 fails,

Just out of interest does 1024x2048 work, perhaps something based on row size ?

**Comment by Any-Winter-4079** [comment]
I think the problem is here
```
slice_size 2048                                                                                                                                                                                        | 0/1 [00:00<?, ?it/s]
slice_size 2048
slice_size 2048
slice_size 2048
slice_size 8192
slice_size 8192
slice_size 8192
slice_size 8192
slice_size 8192
slice_size 8192
slice_size 8192
slice_size 8192
slice_size 8192
slice_size 8192
slice_size 2048
slice_size 2048
slice_size 2048
slice_size 2048
slice_size 2048
slice_size 2048
100%|| 1/1 [00:20<00:00, 20.94s/it]
slice_size2 32768
```

slice_size is in `attention.py` and slice_size2 `model.py`

**Comment by Any-Winter-4079** [comment]
Actually, no, the error is not there.

**Comment by Any-Winter-4079** [comment]
@Vargol In what file did you see this?

> At some point the code wants to create a temporary tensor with more than 2,147,483,648 values
> note if the values are 32bit floats that would be 64 GB tensor.

**Comment by Vargol** [comment]
> @Vargol In what file did you see this?
> 
> > At some point the code wants to create a temporary tensor with more than 2,147,483,648 values
> > note if the values are 32bit floats that would be 64 GB tensor.

Sorry this wasn't in a file as such just the  deduction, its what the error message means in none technical language

**Comment by Any-Winter-4079** [comment]
`return h3` this line runs in `model.py`.
But I'm not sure what gets called next.

**Comment by Vargol** [comment]
It'll return to whence it came, where that call to model.forward came from , if you don't know where that is
you could print the backtrace before the return.

import traceback

traceback.print_stack()
return h3

**Comment by Any-Winter-4079** [comment]
Awesome! I learn something new every day in this repo :)
I think here's where it's failing
```
for i_level in reversed(range(self.num_resolutions)):
            for i_block in range(self.num_res_blocks+1):
                h = self.up[i_level].block[i_block](h, temb)
                if len(self.up[i_level].attn) > 0:
                    h = self.up[i_level].attn[i_block](h)
            if i_level != 0:
                h = self.up[i_level].upsample(h)
```

**Comment by Any-Winter-4079** [comment]
It gets to `i_level` 3 2 1 and then fails
`Error: product of dimension sizes > 2**31`

**Comment by Any-Winter-4079** [comment]
In particular, it fails on
`h = self.up[i_level].upsample(h)` when `i_level` is 1.

**Comment by Any-Winter-4079** [comment]
Here's some extra info.
h tensor sizes before and after
`h = self.up[i_level].upsample(h)`

`-W2048 -H1024` (fails)
```
in torch.Size([1, 512, 128, 256])
out torch.Size([1, 512, 256, 512])
in torch.Size([1, 512, 256, 512])
out torch.Size([1, 512, 512, 1024])
in torch.Size([1, 256, 512, 1024])
fails
```

`-W1920 -H1920` (succeeds)
```
in torch.Size([1, 512, 240, 240])
out torch.Size([1, 512, 480, 480])
in torch.Size([1, 512, 480, 480])
out torch.Size([1, 512, 960, 960])
in torch.Size([1, 256, 960, 960])
out torch.Size([1, 256, 1920, 1920])
```

**Comment by Vargol** [comment]
okay, that seems to call

class Upsample(nn.Module):
    def __init__(self, in_channels, with_conv):
        super().__init__()
        self.with_conv = with_conv
        if self.with_conv:
            self.conv = torch.nn.Conv2d(in_channels,
                                        in_channels,
                                        kernel_size=3,
                                        stride=1,
                                        padding=1)

    def forward(self, x):
        x = torch.nn.functional.interpolate(x, scale_factor=2.0, mode="nearest")
        if self.with_conv:
            x = self.conv(x)
        return x

specifically forward if I'm getting the hang of nn.Modules, I assume torch.nn.functional.interpolate scales the size of the tensor x by two, interpolating the new values.

Worth sticking print of the tensor shape before and after the call to torch.nn.functional.interpolate ?

**Comment by Vargol** [comment]
Darn too slow :-)

**Comment by Vargol** [comment]
1,  256, 512, 1024
so that would come out
512 x 1024 x 2048 = 1073741824

so 1 G values, half of the 2 G values it fails at. I wonder if the conv function doubles it again while calculating

1, 256 x 1920x 1920 is just under 1G,  943,718,400 values

**Comment by Any-Winter-4079** [comment]
Following
`-W1920 -H1920` (succeeds)
```
in torch.Size([1, 512, 240, 240])
out torch.Size([1, 512, 480, 480])
in torch.Size([1, 512, 480, 480])
out torch.Size([1, 512, 960, 960])
in torch.Size([1, 256, 960, 960])
out torch.Size([1, 256, 1920, 1920])
```
wouldn't this come out
`-W2048 -H1024` (fails)
```
in torch.Size([1, 512, 128, 256])
out torch.Size([1, 512, 256, 512])
in torch.Size([1, 512, 256, 512])
out torch.Size([1, 512, 512, 1024])
in torch.Size([1, 256, 512, 1024])
in torch.Size([1, 256, 1024, 2048]) <--- prediction
```

instead of 512 x 1024 x 2048 =  1073741824?

**Comment by Vargol** [comment]
Yep, sorry for some reason I thought it was doubling the last  three values.

**Comment by Any-Winter-4079** [comment]
It's weird because `1920x1920` is larger than `2048x1024`. And it's not like there's something special about 2048.
`-W2048 -H512` (succeeds)
```
in torch.Size([1, 512, 64, 256])
out torch.Size([1, 512, 128, 512])
in torch.Size([1, 512, 128, 512])
out torch.Size([1, 512, 256, 1024])
in torch.Size([1, 256, 256, 1024])
out torch.Size([1, 256, 512, 2048])
```

**Comment by Any-Winter-4079** [comment]
`torch.Size([1, 256, 512, 2048])` is exactly 2^28 and succeeds
`torch.Size([1, 256, 1024, 2048])` is exactly 2^29 and fails

Since we're approximating 2^31 I wonder if there's some operation as you say that makes it scale even more and fails for exact powers of 2.

`torch.Size([1, 256, 1920, 1920])` works and it's larger but it's not an exact power of 2.

I tried `-W4096 -H512` and it failed, so it behaves the same way as `-W2048 -H1024`. Both exact powers of 2.

**Comment by Vargol** [comment]
I've dumbed it down...

```
import torch

mps_device = torch.device("mps")

ix = torch.zeros(1, 256, 960, 960, device=mps_device)
iy = torch.nn.functional.interpolate(ix, scale_factor=2.0, mode="nearest")

print(str(iy.device))
print(str(iy.shape))

ix = torch.zeros(1, 256, 512, 1024, device=mps_device)
iy = torch.nn.functional.interpolate(ix, scale_factor=2.0, mode="nearest")

print(str(iy.device))
print(str(iy.shape))

```
Which crashes 

% python test.py
mps:0
torch.Size([1, 256, 1920, 1920])
/AppleInternal/Library/BuildRoots/a0876c02-1788-11ed-b9c4-96898e02b808/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:705: failed assertion `[MPSTemporaryNDArray initWithDevice:descriptor:] Error: product of dimension sizes > 2**31'
zsh: abort      python test.py

**Comment by Vargol** [comment]
Unsurprisingly works on the CPU

(Dev_InvokeAI) davidburnett@Davids-Mac-mini InvokeAI % time python test.py
cpu
torch.Size([1, 256, 1920, 1920])
cpu
torch.Size([1, 256, 1024, 2048])

**Comment by Any-Winter-4079** [comment]
@Vargol maybe we can check if perfect power of 2 and >= 2^29 and then send to CPU (or always send to CPU -depending on performance)

**Comment by Vargol** [comment]
Yep, I'm beginning to think that might be a solution

Just tried a few sizes and its only powers of two that break so far.

I think there's a issue raised on the torch GitHub for this, so similar I'm dig it out tomorrow and add this to the list.

**Comment by Birch-san** [comment]
https://github.com/pytorch/pytorch/issues/84039#issuecomment-1238777659

**Comment by Vargol** [comment]
Thanks @Birth-san
I've added
https://github.com/pytorch/pytorch/issues/84039#issuecomment-1275804368

**Comment by Any-Winter-4079** [comment]
```

class Upsample(nn.Module):
    def __init__(self, in_channels, with_conv):
        super().__init__()
        self.with_conv = with_conv
        if self.with_conv:
            self.conv = torch.nn.Conv2d(in_channels,
                                        in_channels,
                                        kernel_size=3,
                                        stride=1,
                                        padding=1)

    def forward(self, x):
        x_size = x.size()
        if hasattr(torch.backends, 'mps') and torch.backends.mps.is_available() and (x_size[0] * x_size[1] * x_size[2] * x_size[3]) % 2**27 == 0:
            x = torch.nn.functional.interpolate(x.to('cpu'), scale_factor=2.0, mode="nearest")
            if self.with_conv:
                x = self.conv(x).to('mps')
        else:
            x = torch.nn.functional.interpolate(x, scale_factor=2.0, mode="nearest")
            if self.with_conv:
                x = self.conv(x)
        return x
```

**Comment by Any-Winter-4079** [comment]
But there is still `Error: product of dimension sizes > 2**31` later on.

**Comment by Any-Winter-4079** [comment]
So basically this is the code to reproduce it.
```
def forward(self, x, temb):
        x_size = x.size()
        if hasattr(torch.backends, 'mps') and torch.backends.mps.is_available() and (x_size[0] * x_size[1] * x_size[2] * x_size[3]) % 2**29 == 0:
            x = x.to('cpu')
        h = self.norm1(x) # <- fails
```

Additionally to
```
class Upsample(nn.Module):
    def __init__(self, in_channels, with_conv):
        super().__init__()
        self.with_conv = with_conv
        if self.with_conv:
            self.conv = torch.nn.Conv2d(in_channels,
                                        in_channels,
                                        kernel_size=3,
                                        stride=1,
                                        padding=1)

    def forward(self, x):
        x_size = x.size()
        if hasattr(torch.backends, 'mps') and torch.backends.mps.is_available() and (x_size[0] * x_size[1] * x_size[2] * x_size[3]) % 2**27 == 0:
            x = torch.nn.functional.interpolate(x.to('cpu'), scale_factor=2.0, mode="nearest")
            if self.with_conv:
                x = self.conv(x)
            x = x.to('mps')
        else:
            x = torch.nn.functional.interpolate(x, scale_factor=2.0, mode="nearest")
            if self.with_conv:
                x = self.conv(x)
        return x
```
Note below it's 2^27 because we've yet to upscale 2 items by 2. Above, we already have the tensor with size 2^29

**Comment by Any-Winter-4079** [comment]
Got it to work.

**Comment by Any-Winter-4079** [comment]
```
def forward(self, x, temb):
        if hasattr(torch.backends, 'mps') and torch.backends.mps.is_available():
            x_size = x.size()
            if (x_size[0] * x_size[1] * x_size[2] * x_size[3]) % 2**29 == 0:
                self.to('cpu')
                x = x.to('cpu')
            else:
                self.to('mps')
                x = x.to('mps')
        h = self.norm1(x)
        h = silu(h)
        h = self.conv1(h)
```

**Comment by skurovec** [comment]
After patch:

```"beautiful landscape" -s 15 -S 3972197351 -W 2048 -H 1024 -C 7.5 -A k_lms```
1 image(s) generated in 770.19s

![000586 3972197351](https://user-images.githubusercontent.com/2119229/195522323-83f8baa2-7dbe-40f2-b182-d00d0f31a280.png)

```"beautiful landscape" -s 50 -S 1962347883 -W 512 -H 512 -C 7.5 -A k_lms```

1 image(s) generated in 30.70s

![000585 1962347883](https://user-images.githubusercontent.com/2119229/195522347-c37bcd11-7944-4242-af6e-b7045a5531fa.png)

``` "beautiful landscape" -s 15 -S 3972197351 -W 1024 -H 1024 -C 7.5 -A k_lm```
1 image(s) generated in 111.11s

![000588 3972197351](https://user-images.githubusercontent.com/2119229/195523218-e7560bb3-031c-45df-b25e-f6623c2bfe05.png)


It is working. Only weird thing is that my small image is different...

Without patch 2048x1024 crashed on semaphore after more than hour.

**Comment by skurovec** [comment]
Created PR https://github.com/invoke-ai/InvokeAI/pull/1081, this time for correct branch

**Comment by Any-Winter-4079** [comment]
Yeah, sorry, copied the wrong seed!
<img width="150" alt="Screenshot 2022-10-13 at 12 44 45" src="https://user-images.githubusercontent.com/50542132/195576719-352549ca-c5d1-4877-a15f-5412c89cdc1f.png">

Well, this is looking good! I'll wait for @Vargol still because he has 8GB, just it make sure it also works there.
@skurovec Btw, do you have 32 or 64GB M1?

**Comment by skurovec** [comment]
32GB

**Comment by Any-Winter-4079** [comment]
Damn, your Mac is fast! Maybe M2?

**Comment by skurovec** [comment]
M1 Max 32GB

At this time I have problem only with textual inversion, so slow...

**Comment by Any-Winter-4079** [comment]
Oh, I remember. We routed 32GB - 64GB - 128GB M1 to use the code in `attention.py`, so that's why our times are so similar. Awesome!

Maybe open a new issue with the TI problems and we can compare performance there. It's code that has not been optimised for RAM size like `attention.py` has been, so maybe that's why it performs considerably worse.

**Comment by michaelezra** [comment]
Thank you!:)

**Comment by skurovec** [comment]
hmoss on discord pointed out that it is still doing it on 64x64 images, which i can confirm on patched branch

**Comment by Any-Winter-4079** [comment]
Maybe we do it for all powers of two?

**Comment by Any-Winter-4079** [comment]
64x64 fails <--
128x64 works
128x128 works
256x128 works
256x256 works
512x256 works
512x512 works
1024x512 works
1024x1024 works
2048x1024 works

**Comment by skurovec** [comment]
I don't know if it related, but small images on mac are just colorful noise, smallest somewhat meaningful image on mac I can produce is 320x192

128x128 banana sushi
![000595 3576531794](https://user-images.githubusercontent.com/2119229/195703056-1fea64d3-ae9e-4924-92d2-9e106928d248.png)

**Comment by Any-Winter-4079** [comment]
Not just that. If I specify 128x128
`"upper body photo of a gorgeous young woman in the style of stefan kostic, realistic, sharp focus, 8k high definition, insanely detailed, intricate, elegant, art by stanley lau and artgerm"   -C7.5 -Ak_lms -S1448898012 -W128 -W128`
I get
128x512
<img width="86" alt="Screenshot 2022-10-13 at 22 24 37" src="https://user-images.githubusercontent.com/50542132/195703406-b14a93ca-1327-41e0-b126-8645bd43dcab.png">

**Comment by skurovec** [comment]
ok, maybe we should try someone with cuda, if it is issue on mac or that model was trained on 512x512 and can't create such small images

**Comment by Any-Winter-4079** [comment]
If it really behaves this bad and it's not a fixable bug, maybe just do a 512x512 and then scale down the image to the desired size would be a fix.

**Comment by skurovec** [comment]
"upper body photo of a gorgeous young woman in the style of stefan kostic, realistic, sharp focus, 8k high definition, insanely detailed, intricate, elegant, art by stanley lau and artgerm" -C7.5 -Ak_lms -S1448898012 -W128 -H128

also I have different image with same seed, again

![000610 1448898012](https://user-images.githubusercontent.com/2119229/195704500-041ef46f-96f9-4984-9fe3-fdd6b83eac01.png)

**Comment by skurovec** [comment]
I have also sd 1.4, just double checked, but full ema

**Comment by Any-Winter-4079** [comment]
Do you have `self.sigmas = self.karras_sigmas`?

**Comment by skurovec** [comment]
ksampler 101? ```self.sigmas = self.karras_sigmas```

**Comment by Any-Winter-4079** [comment]
Yep, in `ksampler.py`
Well this looks interesting. Would a third M1 produce a third different result, or do we have a different codebase?

**Comment by skurovec** [comment]
pruned model is same as yours, interesting

![000612 1448898012](https://user-images.githubusercontent.com/2119229/195705750-8440aff1-f777-4d41-b05d-851f189afcf6.png)

**Comment by Any-Winter-4079** [comment]
Oh, interesting.
Is it the same for 512x512?

**Comment by skurovec** [comment]
all images I have produced in this issue are from full ema and are same as yours

**Comment by Any-Winter-4079** [comment]
So at 512x512 both behave the same way, but at lower sizes they don't?

**Comment by skurovec** [comment]
I'll try, give me a sec

**Comment by skurovec** [comment]
No, they are different all the time, just the differences are so small that nobody noticed

Just more visible in smaller images

512x512 448x448 256x256

![000613 1962347883](https://user-images.githubusercontent.com/2119229/195707304-86f75bf9-d253-4cea-809b-ce524f9698ef.png)
![000614 1962347883](https://user-images.githubusercontent.com/2119229/195707315-9ea24157-3077-48d4-aaed-1b248a873670.png)
![000615 1962347883](https://user-images.githubusercontent.com/2119229/195707321-076d6252-c169-40be-8c41-194bb93eb709.png)
![000616 1962347883](https://user-images.githubusercontent.com/2119229/195707322-a67d31b8-a946-448b-a412-b50057e07fb5.png)
![000617 1962347883](https://user-images.githubusercontent.com/2119229/195707324-736eac61-8024-4498-8951-ae796f1b346d.png)
![000618 1962347883](https://user-images.githubusercontent.com/2119229/195707330-6fd6819c-dee7-49f5-8b5e-cd31ee352e8d.png)

**Comment by Vargol** [comment]
![image](https://user-images.githubusercontent.com/62868/195718573-cd6cb88d-6a14-4ab9-8566-a40d54ab55de.png)

I match @Any-Winter-4079 's and I'm using the pruned model cos the full ema one won't fit in my memory :-)

**Comment by Any-Winter-4079** [comment]
Someone with cuda, let us know if you see bad quality on e.g. 128x128

**Comment by Birch-san** [comment]
> I don't know if it related, but small images on mac are just colorful noise
> 
> 128x128 banana sushi ![000595 3576531794](https://user-images.githubusercontent.com/2119229/195703056-1fea64d3-ae9e-4924-92d2-9e106928d248.png)

think this is a known problem. @justinpinkney has a fine-tuned model for small images:  
https://twitter.com/Buntworthy/status/1580575210641960961

**Comment by Any-Winter-4079** [comment]
Not public yet, right?

**Comment by francescofarina** [comment]
Any updates on this issue? I just upgraded to 2.3.0 from 2.2.5 and the error appears if one of the dimensions is greater than 704. With 2.2.5 it was working well. I'm on a Mac M1 with 64GB ram.

**Comment by ChefQ** [comment]
Hey everyone, I recently got this same error.
Did anyone find a fix to it yet?
