### ISSUE TITLE
i have it running in my windows terminal....But how do i start the webui. 

### ISSUE THREAD

**Issue by Maki9009** [invoke-ai/InvokeAI#1020]
I dont see anything that point to how to start the webui for invoke?

**Comment by ffd8** [comment]
add `--web` to your terminal command, [see details here](https://github.com/invoke-ai/InvokeAI/blob/main/docs/features/WEB.md).

**Comment by Any-Winter-4079** [comment]
`python scripts/invoke.py --web` then visit `localhost:9090`
