### ISSUE TITLE
MacOSX 13 Ventura: oc("mps_multiply"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/4883e71d-37bd-11ed-b0ef-b25c5e9b9057/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":228:0)): error: input types 'tensor<2xf32>' and 'tensor<2xsi64>' are not broadcast compatible

### ISSUE THREAD

**Issue by michaeljanich** [invoke-ai/InvokeAI#1021]
**Describe your environment**
- GPU: CPU
- VRAM: n/a
- CPU arch: [x86]
- OS: [macOS Ventura Beta]
- Python: miniconda
- Branch: main
- Commit: Merge: e23dfef 2b9f8e7

**Describe the bug**
I can run "python scripts/dream.py", but when I type a "dream", I get this error:

>> Request to generate with prompt: house on the beach at sunset
/Users/massa/AI/stable-diffusion/ldm/modules/embedding_manager.py:153: UserWarning: The operator 'aten::nonzero' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at  /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  placeholder_idx = torch.where(
Generating:   0%|                                                                                                   | 0/4 [00:00<?, ?it/sloc("mps_multiply"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/4883e71d-37bd-11ed-b0ef-b25c5e9b9057/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":228:0)): error: input types 'tensor<2xf32>' and 'tensor<2xsi64>' are not broadcast compatible
LLVM ERROR: Failed to infer result type(s).

It seems it may be a problem with the new MacOSX and the MPS Metal Library. Does anyone know help? THANKS.

**To Reproduce**
1. python scripts/dream.py
2. "House on the beach at Sunset"
3. Error appears

**Comment by lstein** [comment]
Is this a new install or are you updating an older one? If it is an update, could you delete the previous environment and start from scratch with environment-mac.yml?

**Comment by michaeljanich** [comment]
New install. I have it running on my macPro in the office (macOS 12, late 2013) and wanted to run it on the iMac from 2020.
