### ISSUE TITLE
Do not disable prompt editing during generation

### ISSUE THREAD

**Issue by MarcusLlewellyn** [invoke-ai/InvokeAI#1027]
**Is your feature request related to a problem? Please describe.**
Not a problem, exactly. Just a nit pick.

**Describe the solution you'd like**
Leave the prompt textbox enabled during image generation.

**Describe alternatives you've considered**
Please don't disable the prompt textbox during generation.

**Additional context**
I can't speak for other users, but I often will watch image outputs, and make changes to the prompt and other parameters while generation is still going. I can change everything _except_ the prompt during generation at the moment.

**Comment by nguyenkm** [comment]
Yep, I often tweak the prompt while a batch is running.

**Comment by psychedelicious** [comment]
Fixed in #1187
