### ISSUE TITLE
Ability to bulk select and delete images in gallery

### ISSUE THREAD

**Issue by MarcusLlewellyn** [invoke-ai/InvokeAI#1028]
**Is your feature request related to a problem? Please describe.**
It is a little inconvenient to have to hit the "Delete Image" button repeatedly in an effort to keep a clean workspace.

**Describe the solution you'd like**
It would be really nice to be able to select images in the gallery (perhaps a small checkbox) and to be able to bulk delete.

**Describe alternatives you've considered**
Can't really think of any.

**Additional context**
There is a nice workflow here, but cruft can add up quickly. In addition, bulk actions could be eventually be useful for sending to img2img.

**Comment by michaelezra** [comment]
+1

**Comment by psychedelicious** [comment]
I'll expand this request to include favorites, tags and filters to the gallery. 

To accomplish this, we will need a backend gallery management system. 

I'm not sure how best to manage this, but I suspect there are libraries out there to do the hard work for us. Backend and front end contributors will need to collaborate here. 

This probably can wait until the SD feature set is built out.

**Comment by hipsterusername** [comment]
Bulk image management is in 3.0
