### ISSUE TITLE
merge conflict in IMG2IMG.md

### ISSUE THREAD

**Issue by paulirish** [invoke-ai/InvokeAI#1031]
https://invoke-ai.github.io/InvokeAI/features/IMG2IMG/#head
https://github.com/invoke-ai/InvokeAI/blob/main/docs/features/IMG2IMG.md#-head

**Comment by lstein** [comment]
Oh that's nasty. I'll fix it up.

**Comment by lstein** [comment]
Fixed. Thanks!
