### ISSUE TITLE
Allow running on CPUs (e.g. through OpenVino)

### ISSUE THREAD

**Issue by Timwi** [invoke-ai/InvokeAI#1035]
In order to allow users who do not have a GPU to run the software, consider allowing it to run on a CPU. The following (command line only) project has successfully enabled running Stable Diffusion on CPUs, perhaps you can adapt it:

https://github.com/bes-dev/stable_diffusion.openvino

**Comment by psychedelicious** [comment]
Hi @Timwi , as noted, InvokeAI does run on CPU. Have you tried and run into some issues? Please elaborate on what is needed to get you up and running.
