### ISSUE TITLE
invoke.py --web interface does not cleanly recover from CUDA out-of-memory error, although the script itself has not fatally crashed.

### ISSUE THREAD

**Issue by Perryman** [invoke-ai/InvokeAI#1036]
**Describe your environment**
- GPU: cuda
- VRAM: 12288
- CPU arch: x86
- OS: Arch
- Python: Anaconda
- Branch: On branch main
- Commit: 67ddba9cfff83c3c3baba970a773defc10783bd1

**Describe the bug**
When running `python scripts/invoke.py --web`, the web interface does not appear to cleanly recover from CUDA out of memory errors.

**To Reproduce**
1. run `python scripts/invoke.py --web`
2. load the web interface in image to image mode
3. use an image that is too large for your GPU (in my case 4096x4096 out-of-memorys reliably) 
4. Yellow "preparing" continues to be displayed and progress bar on top is still moving
5. Cancel does not fix the error either
6. Refreshing the web page successfully recovers the session, and new images can be generated, assuming something is selected that fits in ram
7. See error

7. See error

**Expected behavior**
- web UI should cleanly recover
- cancel button should also have recovered

**Expected behavior**
- web UI should cleanly recover
- cancel button should also have recovered

**Additional context**
example error excerpt on invoke.py CLI:
```
>> loaded input image of size 4096x4096 from /home/username/InvokeAI/outputs/img-samples/000262.1191354169.postprocessed.png

RuntimeError: CUDA out of memory. Tried to allocate 2.00 GiB (GPU 0; 11.78 GiB total capacity; 8.11 GiB already allocated; 1.40 GiB free; 9.14 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
>> Could not generate image.
>> Usage stats:
>>   0 image(s) generated in 0.63s
>>   Max VRAM used for this generation: 9.78G. Current VRAM utilization: 2.26G
>>   Max VRAM used since script start:  9.78G
>> Cancel processing requested
>> Cancel processing requested
>> System config requested
```

Also, the RAM on the GPU doesn't seem to de-allocate after the out-of-memory, though it appears to de-allocate when a new prompt is generated afterward in the same session.

**Comment by psychedelicious** [comment]
Thanks for logging this. 

Team, is it possible the runtimeerror isn't being raised as a normal exception? The server should catch it if so and ui handle it as expected. 

Internally, it looks like we need to handle freeing vram as well when this error occurs.

**Comment by Barafu** [comment]
It is still a problem. Just wanted to report this. CUDA out of memory error is unrecoverable, the only thing to do is to kill server. Can be a problem because some people try to share the server among a group, and users can't reboot it, and out of memory error is easy to create.

**Comment by psychedelicious** [comment]
New nodes backend handles this properly
