### ISSUE TITLE
Import Images and Metadata From Previous Versions

### ISSUE THREAD

**Issue by twopiearr** [invoke-ai/InvokeAI#1038]
**Is your feature request related to a problem? Please describe.**
I have generated close to a thousand images in 1.14. While I am delighted by all of the cool new features in 2.0, it doesn't appear that the metadata from those previous generations can be read into 2.0. I tried copying one image over and creating a new line for it in the Invoke log, copying the metadata settings from the old web log, but when I started the web interface for 2.0, the metadata didn't seem to appear anywhere. I would love to be able to retain this history for further exploration with the new features in 2.0.

**Describe the solution you'd like**
The following was shared with me in a chat on the Discord:
Metadata is stored in the image itself - the log is separate. We can parse the old style "dream prompt" into metadata, had it working some time ago but removed it after a major refactor. Can you please open a GH issue to request this
For full context, the link to the thread is: https://discord.com/channels/1020123559063990373/1029136516712243280

**Comment by psychedelicious** [comment]
A dream prompt is now reconstructed from the web UI parameters and included in metadata. Fixed in #1435
