### ISSUE TITLE
Black output from img2img

### ISSUE THREAD

**Issue by pksebben** [invoke-ai/InvokeAI#1045]
**Describe your environment**
- GPU: m1 max
- VRAM: ?
- CPU arch: arm
- OS: macOS
- Python: Miniconda, as per installation instructions number 2
- Branch: main
- Commit: 8954171eea30557ea8f8b9bc0575c34c3630d64e

**Describe the bug**
Black images in img2img generation 

**To Reproduce**
Run img2img a bunch, wait for black output.  See screencap for values used.

**Expected behavior**
Slightly brighter images.

**Screenshots**
![F580C3B2-DF49-4F3F-B308-07517196B5B1](https://user-images.githubusercontent.com/7000931/195008346-01e1c958-f509-44a7-85e4-5e6ae2c8958c.jpeg)
![9209349C-21B3-4D7B-8DF3-7108D56F3233_4_5005_c](https://user-images.githubusercontent.com/7000931/195008374-bc0cce31-38fb-4f30-a03a-8c10b90288d6.jpeg)

**Additional context**
Problem is rare & erratic.  Typically seen more when running with expensive parameters.

**Comment by skurovec** [comment]
I have maybe related issue, when generating using ddim, about 8 percent of images are black. When I recreate black images using same parameters, they are working. I have generated 300 images and 40 of them were black, same prompt, ddim, 512x768.

It was present on 1.14, but i think since 2.0 it is worse. But I hadn't this issue in rc-8.

Also M1 Max, 32GB.

**Comment by Any-Winter-4079** [comment]
I'm testing.

**Comment by Any-Winter-4079** [comment]
Here's a test with 48 images (512x512, `k_euler_a`, `-s50`, `-f0.75`) and no black images.
<img width="200" alt="image" src="https://user-images.githubusercontent.com/50542132/195071564-7a703cfe-be76-4c2a-814d-cbf8ab38c4cd.png">

It may be more specific to your settings (e.g. a problem only when using Perlin noise, etc.) than a general problem in `img2img`

**Comment by Any-Winter-4079** [comment]
I'm doing a test much closer to your screenshot now.
`an anime girl -I 000003.640511255.png -n50 -Ak_euler_a -f0.55 -v0.6 -W576 -H576 -C2 --perlin 1`

**Comment by Any-Winter-4079** [comment]
Finally could generate a black image

`"an anime girl" -s 50 -S 450100192 -W 576 -H 576 -C 2.0 --perlin 1.0 --threshold 8.1 -I 000003.640511255.png -A k_euler_a -f 0.55 -V 928613172:0.6`

<img width="143" alt="Screenshot 2022-10-11 at 13 50 21" src="https://user-images.githubusercontent.com/50542132/195082234-5a8bf9c8-300d-42b5-8608-784df2969939.png">

Re-running the same command for the image it's no longer black.
<img width="143" alt="Screenshot 2022-10-11 at 13 50 39" src="https://user-images.githubusercontent.com/50542132/195082291-f7fe892b-a1b2-491e-80a2-f28b8b2181a9.png">

**Comment by lstein** [comment]
> **Describe your environment**
> 
> * GPU: m1 max
> * VRAM: ?
> * CPU arch: arm
> * OS: macOS
> * Python: Miniconda, as per installation instructions number 2
> * Branch: main
> * Commit: [8954171](https://github.com/invoke-ai/InvokeAI/commit/8954171eea30557ea8f8b9bc0575c34c3630d64e)
> 
> **Describe the bug** Black images in img2img generation
> 
> **To Reproduce** Steps to reproduce the behavior: Run img2img a bunch, wait for black output. See screencap for values used.
> 
> **Expected behavior** Slightly brighter images.
> 
> **Screenshots** ![F580C3B2-DF49-4F3F-B308-07517196B5B1](https://user-images.githubusercontent.com/7000931/195008346-01e1c958-f509-44a7-85e4-5e6ae2c8958c.jpeg) ![9209349C-21B3-4D7B-8DF3-7108D56F3233_4_5005_c](https://user-images.githubusercontent.com/7000931/195008374-bc0cce31-38fb-4f30-a03a-8c10b90288d6.jpeg)
> 
> **Additional context** Problem is rare & erratic. Typically seen more when running with expensive parameters.

You have Perlin noise turned way up (to 1.0). This will cause the dark brown images you are seeing, but shouldn't be causing the black ones. Turn Perlin down to 0.0 and try again.

**Comment by pksebben** [comment]
I've run this more, and found that at higher resolutions, the black output is more reliable.
![001132 491355176](https://user-images.githubusercontent.com/7000931/195250315-a7e7d178-8455-4a90-a4ff-2e58cb288af5.png)
using this image as a source, with below settings...
![09558A51-E5A8-4BD3-B6A0-ED6AF36BC7F5](https://user-images.githubusercontent.com/7000931/195250539-928e5206-1f06-4aa5-8c47-fc398a902afa.jpeg)
anything above 704px^2 seems to output black.

Perlin noise turned down as recommended.

I will admit that I am fumbling to a degree here, as I'm no expert in either machine learning nor image recognition.  Certainly feels like this is bound to memory, though - as the occurrence of black boxes correlates to more memory-intensive procedures.

**Comment by pksebben** [comment]
addendum:  @704px^2 black is output ~50% of the time.
![8A1B9F81-4D70-462D-B539-092E4006366D_4_5005_c](https://user-images.githubusercontent.com/7000931/195251144-1d2295bb-83f4-40aa-9057-221924356daa.jpeg)

**Comment by pksebben** [comment]
Also, problem seems correlated with heat.  When I'm getting most of these black tiles, you could fry an egg on this laptop.  I'm gonna let it cool for a minute and see if the problem goes away.

Might be limitation in the hardware.

**Comment by skurovec** [comment]
Please try latest master, there was some M1 specific code missing after merge.
