### ISSUE TITLE
2.0 - No such file or directory

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#1046]
error while dreaming:

```
IndexError: string index out of range
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "\ldm\lib\site-packages\pyreadline3\rlmain.py", line 180, in write_history_file
    self.mode._history.write_history_file(filename)
  File "\ldm\lib\site-packages\pyreadline3\lineeditor\history.py", line 100, in write_history_file
    fp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/img-samples\\.invoke_history'
```

Seems like a file path is getting mingled. Any idea?

**Comment by lstein** [comment]
@blessedcoolant This is one of those Windows backslash/forward slash confusion problems. Could you have a look? It isn't clear to me why this one user is being affected and others not.

**Comment by blessedcoolant** [comment]
Not able to reproduce this error on my end. Does python have read/write permissions to this folder on your system?

**Comment by Neosettler** [comment]
perhaps the history better be in the "outputs" folder anyways. Also, consider adding subDurName arg to give control over the naming convention.

**Comment by Neosettler** [comment]
[blessedcoolant](https://github.com/blessedcoolant) In the mean time, any quick workaround that could skip the error? Like no history or something around those lines?

**Comment by Neosettler** [comment]
the error magickly disappeared and cant reproduce it anymore. Strange... In any case, the bug can be scratched off the board.

**Comment by OriBengal** [comment]
I'm actually having the same error. Tried creating the folders manually - still getting the errors.  Will try a reboot, maybe that will make my errors mysteriously disappear.
