### ISSUE TITLE
Easy Peasy Windows Guide not updated?

### ISSUE THREAD

**Issue by diwako** [invoke-ai/InvokeAI#1048]
**Describe your environment**
- GPU: cuda
- VRAM: 8
- CPU arch: x86
- OS: Windows
- Python: pyenv
- Branch: main
- Commit: add steps for updating environment 8954171e

**Describe the bug**
Updated to V2 and noticed it just did not want to work right. I did some digging to get it back to work. I was following the 
[Easy Peasy Windows  Install Guide](https://github.com/invoke-ai/InvokeAI/wiki/Easy-peasy-Windows-install) as I did in previous releases.
The error message was that there were missing modules. I compared the latest `requirements.txt` file with what is given in the guide and noticed that several modules are missing:
- pyreadline3
- flaskwebgui
- send2trash
- realesrgan

I fixed it by merging the readme given in the main branch with the guide's list and substituting the bottom part of it as given. I would create a PR but I am not a python dev, nor am I too involved in this project, other than using the result for my own amusement, thus no idea which of the modules are actually needed.

**To Reproduce**
1. Check out main on a windows machine
2. Follow the guide
3. Fail at step 8

**Expected behavior**
Step 8 boots up invoke ai and allows for prompt input, or allows to use the web interface using `--web`

**Comment by lstein** [comment]
@tildebyte Can you update the easy-peasy install guide?

**Comment by psychedelicious** [comment]
The easy-peasy guide is now deprecated.

**Comment by tildebyte** [comment]
Instead, use the installer named 'InvokeAI-windows.zip' from the Releases page
