### ISSUE TITLE
python scripts/dream.py   error

### ISSUE THREAD

**Issue by Cyx-0** [invoke-ai/InvokeAI#1050]
ImportError: dlopen(/Users/jc/miniforge3/envs/invokeai/lib/python3.9/site-packages/greenlet/_greenlet.cpython-39-darwin.so, 0x0002): tried: '/Users/jc/miniforge3/envs/invokeai/lib/python3.9/site-packages/greenlet/_greenlet.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))

**Comment by Any-Winter-4079** [comment]
Try creating a new environment using `arm` from the start. Switching your environment to use arm once you have some packages installed for x86 seems to give problems.

**Comment by lstein** [comment]
This will clean up the conda environment for a fresh install. Do not remove `ldm` if you are using it for another distribution! I included it in case you have a leftover environment from an earlier `InvokeAI` install.

~~~
conda deactivate
conda env remove -n invokeai
conda env remove -n ldm
conda clean --all --yes
~~~

**Comment by Coreusa** [comment]
Tried the above. When done it still says `ldm`.

![image](https://user-images.githubusercontent.com/706874/195161539-f6119d1a-1719-4822-bd7b-4fe3055ef4e9.png)

**Comment by psychedelicious** [comment]
@Cyx-0, please let us know if, after trying the troubleshooting suggested, you still have this problem.

@Coreusa, it's not clear what your problem is. Can you please elaborate?

**Comment by Coreusa** [comment]
@psychedelicious The docs states this:
![image](https://user-images.githubusercontent.com/706874/197418089-2fb3fc8a-71b9-41e9-8a67-6d887cf0a57c.png)

_Now refer to what's stated above_

**Comment by psychedelicious** [comment]
@Coreusa I think you are using an old version of the repo. Please run `git pull` from the invokeai folder and try the steps again. 

If this does not work, please open a new issue and fill out the details requested in the new issue form.

**Comment by psychedelicious** [comment]
No response, closing
