### ISSUE TITLE
System Requirements in readme are inaccurate (disk space)

### ISSUE THREAD

**Issue by n00mkrad** [invoke-ai/InvokeAI#1052]
The readme states:

> At least 6 GB of free disk space for the machine learning model, Python, and all its dependencies.

However, the conda environment is about 6 GB alone, the SD 1.4 model takes up 4 GB, and other models and files that will be downloaded/cached take up 1-2 GB.

So I think the readme should be updated to state **12 GB of disk space.**

Also, it should be mentioned that some dependencies will be installed to C:/ by default (%USERPROFILE%/.cache, etc.).

**Comment by lstein** [comment]
Thank you. I'll update the README.
