### ISSUE TITLE
WebUI - gallery refresh performance

### ISSUE THREAD

**Issue by michaelezra** [invoke-ai/InvokeAI#1053]
With the recent major update to WebUI I noticed a lag in how thumbnails are being refreshed in the gallery section. Prior to this update thumbnails for new images would be instantly added to the web, without any noticeable flickering or delay. Refresh is very laggy in the new version.

MacOS M1 max 64GB 32 GPU

**Comment by blessedcoolant** [comment]
Are you talking about it on page refresh? Or even when a new item gets added?

**Comment by michaelezra** [comment]
Refresh of the "your Invocations" section when new items are added

**Comment by FreeBlues** [comment]
I got the same issue. When I try to open the gallery, it appears very slow.

Macbook Pro 2020/ Intel CPU/ 32G ram / outside eGPU Radeon RX 6600XT 8G

**Comment by michaelezra** [comment]
Forgot to mention, I am using Safari browser.

**Comment by 19wolf** [comment]
I'm also having this issue. Gallery images don't seem to load at all when a prompt is running.

**Comment by psychedelicious** [comment]
I think we should revert the masonry layout stuff to improve the situation for our Safari users. Also, I find it makes it hard to judge the sequence of images.

**Comment by blessedcoolant** [comment]
I agree. I feel we need to rethink the gallery design a bit more. What we have now works well but I'm not a huge fan of it. Especially as an image management tool.

**Comment by psychedelicious** [comment]
This is resolved by #1198.

**Comment by michaelezra** [comment]
Thank you!
