### ISSUE TITLE
CUDA out of memory only when GFPGAN is selected for a batch

### ISSUE THREAD

**Issue by nguyenkm** [invoke-ai/InvokeAI#1054]
**Describe your environment**
- GPU: NVIDIA 1070Ti
- VRAM: 8GB
- CPU arch: Intel Core i7 5930K @ 3.50GHz
- OS: Windows 10
- Python: Anaconda
- Branch: 2.0.0 release
- Commit:

**Describe the bug**
Brand new fresh installation of 2.0.0, starting from git clone and env create.
When **Restore Face** is selected in the Web UI for a large batch, the batch eventually encounters CUDA out of memory errors.
K_lms, k_euler, k_euler_a were used, at 512X512 and 512X768, and 15 steps and 50 steps; all combination exhibits the same behavior.

**To Reproduce**
1. Using the web UI
2. Set **Images** to a high number
3. Select **Restore Face**
4. Enter any prompt,
5. Press **Invoke**

**Expected behavior**
All images would be generated.

**Additional context: full trace from a fresh start**
(invokeai) C:\stable-diffusion\InvokeAI>python scripts\invoke.py --web
* Initializing, be patient...

>> GFPGAN Initialized
>> CodeFormer Initialized
>> ESRGAN Initialized
>> Loading model from models/ldm/stable-diffusion-v1/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
NOTE: Redirects are currently not supported in Windows or MacOs.
>> Using faster float16 precision
>> Model loaded in 20.05s
>> Max VRAM used to load the model: 2.17G
>> Current VRAM usage:2.17G
>> Setting Sampler to k_lms

* --web was specified, starting web server...
>> Started Invoke AI Web Server!
>> Default host address now 127.0.0.1 (localhost). Use --host 0.0.0.0 to bind any address.
>> Point your browser at http://127.0.0.1:9090
>> System config requested
>> System config requested
>> System config requested
>> Image generation requested: {'prompt': 'Cat', 'iterations': 50, 'steps': 15, 'cfg_scale': 7.5, 'threshold': 0, 'perlin': 0, 'height': 512, 'width': 512, 'sampler_name': 'k_lms', 'seed': 3950314710, 'seamless': False, 'progress_images': False, 'variation_amount': 0}
ESRGAN parameters: False
GFPGAN parameters: {'strength': 0.8}
Generating:   0%|                                                                               | 0/50 [00:00<?, ?it/s]>> Sampling with k_lms starting at step 0 of 15 (15 new sampling steps)
100%|██████████████████████████████████████████████████████████████████████████████████| 15/15 [00:07<00:00,  2.04it/s]
>> GFPGAN - Restoring Faces for image seed:3950314710██████████████████████████████████| 15/15 [00:07<00:00,  2.12it/s]
>> Image generated: "C:\stable-diffusion\InvokeAI\outputs\img-samples\000026.3950314710.postprocessed.png"

[snip... for brevity]

Generating:  68%|███████████████████████████████████████████████▌                      | 34/50 [05:54<02:51, 10.70s/it]>> Sampling with k_lms starting at step 0 of 15 (15 new sampling steps)
100%|██████████████████████████████████████████████████████████████████████████████████| 15/15 [00:07<00:00,  2.13it/s]
>> GFPGAN - Restoring Faces for image seed:3378879192██████████████████████████████████| 15/15 [00:07<00:00,  2.02it/s]
        Failed inference for GFPGAN: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 8.00 GiB total capacity; 7.02 GiB already allocated; 0 bytes free; 7.25 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF.
>> Image generated: "C:\stable-diffusion\InvokeAI\outputs\img-samples\000060.3378879192.postprocessed.png"
Generating:  70%|█████████████████████████████████████████████████                     | 35/50 [06:05<02:43, 10.89s/it]>> Sampling with k_lms starting at step 0 of 15 (15 new sampling steps)
100%|██████████████████████████████████████████████████████████████████████████████████| 15/15 [00:07<00:00,  2.13it/s]
Generating:  70%|█████████████████████████████████████████████████                     | 35/50 [06:13<02:40, 10.68s/it]
Traceback (most recent call last):
  File "d:\dropbox\programming\ai\stable-diffusion\invokeai\ldm\generate.py", line 370, in prompt2image
    results = generator.generate(
  File "d:\dropbox\programming\ai\stable-diffusion\invokeai\ldm\invoke\generator\base.py", line 78, in generate
    image = make_image(x_T)
  File "C:\Users\khain\anaconda3\envs\invokeai\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "d:\dropbox\programming\ai\stable-diffusion\invokeai\ldm\invoke\generator\txt2img.py", line 54, in make_image
    return self.sample_to_image(samples)
  File "d:\dropbox\programming\ai\stable-diffusion\invokeai\ldm\invoke\generator\base.py", line 90, in sample_to_image
    x_samples = self.model.decode_first_stage(samples)
  File "C:\Users\khain\anaconda3\envs\invokeai\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "d:\dropbox\programming\ai\stable-diffusion\invokeai\ldm\models\diffusion\ddpm.py", line 1117, in decode_first_stage
    return self.first_stage_model.decode(z)
  File "d:\dropbox\programming\ai\stable-diffusion\invokeai\ldm\models\autoencoder.py", line 421, in decode
    dec = self.decoder(z)
  File "C:\Users\khain\anaconda3\envs\invokeai\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "d:\dropbox\programming\ai\stable-diffusion\invokeai\ldm\modules\diffusionmodules\model.py", line 599, in forward
    h = self.up[i_level].block[i_block](h, temb)
  File "C:\Users\khain\anaconda3\envs\invokeai\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "d:\dropbox\programming\ai\stable-diffusion\invokeai\ldm\modules\diffusionmodules\model.py", line 120, in forward
    h = self.norm1(x)
  File "C:\Users\khain\anaconda3\envs\invokeai\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\khain\anaconda3\envs\invokeai\lib\site-packages\torch\nn\modules\normalization.py", line 268, in forward
    return F.group_norm(
  File "C:\Users\khain\anaconda3\envs\invokeai\lib\site-packages\torch\nn\functional.py", line 2499, in group_norm
    return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 0; 8.00 GiB total capacity; 6.70 GiB already allocated; 0 bytes free; 7.26 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

>> Could not generate image.
>> Usage stats:
>>   0 image(s) generated in 374.29s
>>   Max VRAM used for this generation: 7.61G. Current VRAM utilization: 2.21G
>>   Max VRAM used since script start:  7.61G

**Comment by ArDiouscuros** [comment]
Could you please try to use option --free_gpu_mem and check if it makes difference?

**Comment by nguyenkm** [comment]
> Could you please try to use option --free_gpu_mem and check if it makes difference?

Using "invoke.py --free_gpu_mem --web"  produces the same result.
"an old woman" 512X512, k_euler, cfg 7.5, Restore Face:
5 steps -- fails at around 30 images consistently
50 steps -- fails at around 50 images consistently

I don't know if --free_gpu_mem is being processed when --web is also specified, but I see no change in behavior.

**Comment by lstein** [comment]
This sounds like it may be a memory leak. To help isolate whether it is in the Web GUI or the underlying libraries, could you please try your generation with the command-line interface?

~~~
python scripts\invoke.py
invoke> an old woman -s5 -n50 -G0.8 -Ak_euler
~~~

This should generate 50 face reconstructed images using 5 steps each

**Comment by nguyenkm** [comment]
> python scripts\invoke.py
> invoke> an old woman -s5 -n50 -G0.8 -Ak_euler

It completed all 50, and applied to GFPGAN to all 50 with no error.
>> Usage stats:
>>   50 image(s) generated in 283.57s
>>   Max VRAM used for this generation: 3.90G. Current VRAM utilization: 2.21G
>>   Max VRAM used since script start:  4.72G

The code path is different.  The Web UI applies GFPGAN after each image is generated before the next image begins.  The CI waits until all images are done and does a batch operation of GFPGAN on all the images.

I've noticed that during the GFPGAN batch operation through the CI the memory usage starts at 4.1GB goes up to 5.1GB for each image, and always returned to 4.1GB after each image was processed.  The GFPGAN through web UI does not behave this cleanly, I can see it slowly retaining more and more memory until it runs out.

**Comment by huntfx** [comment]
I have the exact same issue also with a fresh installation, here's a screenshot of my vram, each image adds about 200mb (I restarted the server at the end).

![image](https://user-images.githubusercontent.com/10235666/196295542-7d455545-3129-44c9-b40b-bd8bd82da610.png)

In comparison here is with restore faces disabled

![image](https://user-images.githubusercontent.com/10235666/196295859-84b08204-2352-498e-b32d-5d815025713f.png)

**Comment by psychedelicious** [comment]
Thanks for the investigation, we will need to dig in to the web UI server code to fix this.

**Comment by blessedcoolant** [comment]
Basically just need to apply the same solution I did for the CLI when I added face restoration.

No matter how optimized our SD generator has become, this will be an issue with batch processing. I thought that maybe with all optmizations we can run post processing right after the image is generated but this shows that there will eventually be a memory overload. And it is always the most ideal solution to do post processing after the batch has been fully generated,

**Comment by psychedelicious** [comment]
Maybe we make a setting to do post-processing in a batch or individually. Would require a bit of fanagling of the server bc it always calls postprocessing individually. 

I'll have a look at the restoration code at some point to see the solution

**Comment by psychedelicious** [comment]
We are transitioning to a new server and backend, where this should no longer be a problem.
