### ISSUE TITLE
Modules missing after putting computer to sleep: ModuleNotFoundError No module named 'PIL'

### ISSUE THREAD

**Issue by borlak** [invoke-ai/InvokeAI#1061]
**Describe your environment**
- GPU: Nvidia 3070
- VRAM: 8gb
- CPU arch: i5
- OS: Windows
- Python: I don't know, whatever is in your default windows installation walkthrough
- Branch: main
- Commit: [run `git show` and paste the line that starts with "Merge" here]

**Describe the bug**
When I  run invoke I get "ModuleNotFoundError: No module named 'PIL'"
If I install pillow, then it just goes to the next module, "torch".  This is where I stopped as I am not even a beginner with python.

I got everything installed and working first try.  I first played with command line, then stopped that, and ran invoke via --web and made images with the web UI.  After a while, I put the computer to sleep, and when I came back the next day, invoke is not working and gives the error mentioned above.

**To Reproduce**
I don't know if it's reproduceable, don't feel like going through the whole process again, but I'll give the steps anyway.

1. Install on windows as described in the docs
2. Make some images with command line, then exit out
3. Run invoke with --web and make images with the web editor
4. Close powershell.
5. Put computer to sleep
6. Open powershell and cd to InvokeAI
7. Try to run invoke again with --web

**Expected behavior**
For invoke to run every time normally.

**Screenshots**
![2022-10-11 17_58_22-Windows PowerShell](https://user-images.githubusercontent.com/1967460/195224907-78c6caf1-05bf-4d97-9567-501c07431e67.png)

**Additional context**

**Comment by borlak** [comment]
I went ahead and tried to pip install all the missing modules as they showed up, but I ran into a problem here:

![2022-10-11 18_02_55-Windows PowerShell](https://user-images.githubusercontent.com/1967460/195225390-844ce77e-6313-4de6-967d-c3d801f8315a.png)

**Comment by cwallen** [comment]
I'm not on windows, but if it can find packages that it had earlier, my guess is that you dropped out of your conda environment. Try:
```
conda activate invokeai
```

**Comment by lstein** [comment]
This sounds like what is going on. Please try the `conda activate invokeai` command referenced above.

**Comment by borlak** [comment]
I decided to do a fresh install.  When going to the windows installation, I initially used the whole manual "pip" install process found here: https://github.com/invoke-ai/InvokeAI/wiki/Easy-peasy-Windows-install

and **not** the anaconda one.  I'm doing the anaconda one this time.

**Comment by psychedelicious** [comment]
Hi @borlak , did the fresh install resolve this issue?

**Comment by borlak** [comment]
Yes @psychedelicious , I did the other install this time (anaconda) and it worked first time and continues working.  Also, with the manual pip install, some features were broken out of the box like the face upgrade and other things, which are working now.  So maybe the manual one needs some tweaking.

**Comment by psychedelicious** [comment]
We've vastly improved the setup process as of v2.1, with further improvements in v2.2. Sorry you had such a hard time getting everything working initially and glad it is working now.
