### ISSUE TITLE
python scripts/preload_models.py  warning     python scripts/dream.py    error

### ISSUE THREAD

**Issue by Cyx-0** [invoke-ai/InvokeAI#1064]
/Users/jc/miniforge3/envs/invokeai/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
/Users/jc/miniforge3/envs/invokeai/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)

    from ._greenlet import _C_API # pylint:disable=no-name-in-module
ImportError: dlopen(/Users/jc/miniforge3/envs/invokeai/lib/python3.9/site-packages/greenlet/_greenlet.cpython-39-darwin.so, 0x0002): tried: '/Users/jc/miniforge3/envs/invokeai/lib/python3.9/site-packages/greenlet/_greenlet.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))

**Comment by lstein** [comment]
The deprecation warnings are annoying but not a fatal problem. The bad part is the ImportError, which appears to be a broken python and/or system library install. There are two libraries built for different architectures fighting each other.

**Comment by Any-Winter-4079** [comment]
It looks like some libraries are x86. Did you update the existing environment to arm64 or did you create a new environment from scratch?

**Comment by Any-Winter-4079** [comment]
@nickraimondi There is a similar issue here https://github.com/invoke-ai/InvokeAI/issues/730#issuecomment-1254903003
Maybe `pip cache purge` would help, but if you got it to work, I wouldn't want to mess around and try :)
Anyway, glad it's solved!

**Comment by psychedelicious** [comment]
While the resolution isn't clear, the issue is indeed resolved; closing.

**Comment by mikealche** [comment]
Had the same issue, managed to solve it in the same way as @nickraimondi
Just go over that process a few times.
I also included `pip cache purge` as @Any-Winter-4079 suggests
