### ISSUE TITLE
Meta data optional

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#1074]
Please, consider making save metadata to image (legacy and new) and history optional. 

maybe arguments would be nice:
--metadata
--history
 
While history is quite easy to turn off in the code base, the metadata flow logic is way too invasive to be turn off elegantly. While these are a nice features, they should be optional.

**Comment by Neosettler** [comment]
adding to pngwriter.py:

    # saves image named _image_ to outdir/name
    # returns full path of output
    def save_image(self, image, name):
        path = os.path.join(self.outdir, name)
        image.save(path, 'PNG')
        return path

invoke.py at write image + grid
if opt.metadata:
    save_image_and_prompt_to_png
else:
    save_image

something around those lines would do the trick!

**Comment by lstein** [comment]
Sure, I could turn metadata saving off. Any particular reason you need this?

**Comment by Neosettler** [comment]
Hi [lstein](https://github.com/lstein), thank you for considering the proposal. As it's stands, the metadata is only relevant to InvokeAI because it does not follow any standard regarding read/write accessibility. Which outside InvokeAI (or custom tools) has no utilities and may leaves unwanted footprints for some users.

**Comment by psychedelicious** [comment]
The metadata is used for some core features of the web UI - that is, recalling generation parameters. But I agree that an option to store nothing except the image itself would be nice.
