### ISSUE TITLE
`scripts/preload_models.py` issue on M1 Max

### ISSUE THREAD

**Issue by lhunath** [invoke-ai/InvokeAI#1076]
Following the instructions for installing on an M1 MacBook Pro, the process fails at:
```
$ python scripts/preload_models.py
```
Due to:
```
  File "/Users/lhunath/.pyenv/versions/anaconda3-2022.05/envs/invokeai/lib/python3.9/site-packages/tokenizers/__init__.py", line 79, in <module>
    from .tokenizers import (
ImportError: dlopen(/Users/lhunath/.pyenv/versions/anaconda3-2022.05/envs/invokeai/lib/python3.9/site-packages/tokenizers/tokenizers.cpython-39-darwin.so, 0x0002): tried: '/Users/lhunath/.pyenv/versions/anaconda3-2022.05/envs/invokeai/lib/python3.9/site-packages/tokenizers/tokenizers.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/lhunath/.pyenv/versions/anaconda3-2022.05/envs/invokeai/lib/python3.9/site-packages/tokenizers/tokenizers.cpython-39-darwin.so' (no such file), '/Users/lhunath/.pyenv/versions/anaconda3-2022.05/envs/invokeai/lib/python3.9/site-packages/tokenizers/tokenizers.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```
This dependency was installed by the previous:
```
$ PIP_EXISTS_ACTION=w CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac.yml
```
It appears several of the dependencies were installed for the wrong architecture:
```
$ find /Users/lhunath/.pyenv/versions/anaconda3-2022.05/envs/invokeai/lib/python3.9 -name '*.so' -exec file {} \; | grep -c arm
506
$ find /Users/lhunath/.pyenv/versions/anaconda3-2022.05/envs/invokeai/lib/python3.9 -name '*.so' -exec file {} \; | grep -vc arm
10
$ find /Users/lhunath/.pyenv/versions/anaconda3-2022.05/envs/invokeai/lib/python3.9 -name '*.so' -exec file {} \; | grep -v arm
/Users/lhunath/.pyenv/versions/anaconda3-2022.05/envs/invokeai/lib/python3.9/site-packages/tokenizers/tokenizers.cpython-39-darwin.so: Mach-O 64-bit dynamically linked shared library x86_64
/Users/lhunath/.pyenv/versions/anaconda3-2022.05/envs/invokeai/lib/python3.9/site-packages/setproctitle/_setproctitle.cpython-39-darwin.so (for architecture x86_64):	Mach-O 64-bit bundle x86_64
/Users/lhunath/.pyenv/versions/anaconda3-2022.05/envs/invokeai/lib/python3.9/site-packages/torch/_dl.cpython-39-darwin.so: Mach-O 64-bit bundle x86_64
/Users/lhunath/.pyenv/versions/anaconda3-2022.05/envs/invokeai/lib/python3.9/site-packages/lmdb/cpython.cpython-39-darwin.so: Mach-O 64-bit bundle x86_64
/Users/lhunath/.pyenv/versions/anaconda3-2022.05/envs/invokeai/lib/python3.9/site-packages/greenlet/tests/_test_extension.cpython-39-darwin.so: Mach-O 64-bit bundle x86_64
/Users/lhunath/.pyenv/versions/anaconda3-2022.05/envs/invokeai/lib/python3.9/site-packages/greenlet/tests/_test_extension_cpp.cpython-39-darwin.so: Mach-O 64-bit bundle x86_64
/Users/lhunath/.pyenv/versions/anaconda3-2022.05/envs/invokeai/lib/python3.9/site-packages/greenlet/_greenlet.cpython-39-darwin.so: Mach-O 64-bit bundle x86_64
/Users/lhunath/.pyenv/versions/anaconda3-2022.05/envs/invokeai/lib/python3.9/site-packages/dependency_injector/containers.cpython-39-darwin.so: Mach-O 64-bit bundle x86_64
/Users/lhunath/.pyenv/versions/anaconda3-2022.05/envs/invokeai/lib/python3.9/site-packages/dependency_injector/_cwiring.cpython-39-darwin.so: Mach-O 64-bit bundle x86_64
/Users/lhunath/.pyenv/versions/anaconda3-2022.05/envs/invokeai/lib/python3.9/site-packages/dependency_injector/providers.cpython-39-darwin.so: Mach-O 64-bit bundle x86_64
```
Kindly advise on how to proceed or diagnose further.

**Comment by marklr** [comment]
did you install conda from miniforge?

**Comment by mauwii** [comment]
@lhunath: for me it looks like you have a installed a x86_64 python in pyenv:

`ImportError: dlopen(/Users/lhunath/.pyenv/versions/anaconda3-2022.05/envs/invokeai/lib/python3.9/site-packages/tokenizers/tokenizers.cpython-39-darwin.so, 0x0002): tried: '/Users/lhunath/.pyenv/versions/anaconda3-2022.05/envs/invokeai/lib/python3.9/site-packages/tokenizers/tokenizers.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/lhunath/.pyenv/versions/anaconda3-2022.05/envs/invokeai/lib/python3.9/site-packages/tokenizers/tokenizers.cpython-39-darwin.so' (no such file), '/Users/lhunath/.pyenv/versions/anaconda3-2022.05/envs/invokeai/lib/python3.9/site-packages/tokenizers/tokenizers.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))`

What is confusing me most is this part:

`/System/Volumes/Preboot/Cryptexes/OS/Users/lhunath/.pyenv/versions/anaconda3-2022.05/envs/invokeai/lib/python3.9/site-packages/tokenizers/tokenizers.cpython-39-darwin.so (no such file)`

So I am not sure where in the installation process your error origins, but I would advise you to start with a fresh Installation of pyenv and when it works properly start to make a fresh installation of InvokeAI

**Comment by PeterHaughie** [comment]
I've been having the same issue. It's incredibly frustrating trying to work out how to tell the system that it's not running on an intel device.

I'm pretty sure that if you run `uname -p` you'll get something like `i386` instead of `arm64`.

If *anyone* has any advice on how to tell conda or the env to pull the right binaries I'm all ears.

**Comment by mauwii** [comment]
not sure who you mean with the `uname -p` assumption, but on my machine(s) the return of this command is `arm`, while `uname -m` returns `arm64` :godmode:

**Comment by PeterHaughie** [comment]
My mistake. I presumed you were having the same issues as me.

**Comment by mauwii** [comment]
I tried to help @lhunath by pointing at a strange output in the logs he provided, for me InvokeAI is working like a charm 🙈

**Comment by PeterHaughie** [comment]
I've got it running fine on a MBP M1 where the only difference in the environment I can discern is the env architecture that's being reported. It's been driving me mad all day.

**Comment by mauwii** [comment]
Uhhhh - sorry, then it's my mistake - I also "only" use a MacBook Air/Pro with M1, but it sounds pretty strange that a M1 Max would use i386 in environment. Are you sure that there is nothing in use like rosettaterm? Or maybe a Bash Installation from a legacy brew installation which was set to x86 instead of the new one? (unfortunatelly I do not have access to one myself, so cannot compare 😞)

**Comment by TimLaue91** [comment]
I have a similar issue, except for me it's greenlet:

`ImportError: dlopen(/Users/username/miniconda3/envs/invokeai/lib/python3.9/site-packages/greenlet/_greenlet.cpython-39-darwin.so, 0x0002): tried: '/Users/username/miniconda3/envs/invokeai/lib/python3.9/site-packages/greenlet/_greenlet.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))`

I'm working on an M1 Mac using [these instructions](https://github.com/invoke-ai/InvokeAI/blob/9910a0b004b26ab45769c3a9a4b361b30eb13b02/docs/installation/INSTALL_MAC.md) (choosing the "Standalone" option for setting up the Python environment). The above error occurs after activating the conda environment, navigating to the project root directory and then running

`python ./scripts/invoke.py`

The location of my Python executable appears to be set correctly, since `which python` returns `/Users/username/miniconda3/envs/invokeai/bin/python`. I have tried updating brew, reinstalling miniconda, and setting up the environment with various flags.

**Comment by PeterHaughie** [comment]
I fixed my issue when I realised my Tmux session was reporting my arch as i386 rather than arm64. When I dropped out to my normal terminal it worked fine.

**Comment by TimLaue91** [comment]
Thank you for your reply @mauwii. I actually did that, since it said so in the M1-specific instructions.

`brew config` output:

```
HOMEBREW_VERSION: 3.6.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: fb52a12144e80118c112ea744ab65ab6ca997d67
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 78cc46dac4b63f5d1f467f98d054e37a3a3164f2
Core tap last commit: 21 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-arm64
CLT: 14.0.0.0.1.1661618636
Xcode: 14.0.1
Rosetta 2: false
```

`conda info` output:

```
     active environment : None
            shell level : 0
       user config file : /Users/username/.condarc
 populated config files : /Users/username/.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __osx=12.6=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/username/miniconda3  (writable)
      conda av data dir : /Users/username/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/username/miniconda3/pkgs
                          /Users/username/.conda/pkgs
       envs directories : /Users/username/miniconda3/envs
                          /Users/username/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.12 Darwin/21.6.0 OSX/12.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

`arch`output:

```
arm64
```

**Comment by mauwii** [comment]
On first sight this looks good, but unfortunatelly doesn't explain the error 🤔 

did you try to do the [debug steps](https://invoke-ai.github.io/InvokeAI/installation/INSTALL_MAC/#doesnt-work-anymore) from the docs already? (like updating conda, reinstalling the env, ...)?

**Comment by TimLaue91** [comment]
I did several reinstalls of miniconda, and I recreated the environment  at least as many times. My suspicion is that this has something to do with the Python versions I have installed on my system (which was mentioned in this thread before and [the debugging page touches on as well](https://invoke-ai.github.io/InvokeAI/installation/INSTALL_MAC/#how-many-snakes-are-living-in-your-computer)). I'm unsure how to test that theory though.

**Comment by mauwii** [comment]
when I run `python -c 'import platform; print(platform.processor())'`from a Terminal it returns `arm`, while running it like `arch -arch x86_64 python -c 'import platform; print(platform.processor())'` returns i386. So by using the first command you could at least find out if is running native or if it makes use of rosetta 2

**Comment by TimLaue91** [comment]
Excellent tip, this uncovered some weirdness:

Running `python -c 'import platform; print(platform.processor())'` returned an error since `python` doesn't point anywhere on my system. `python3 -c 'import platform; print(platform.processor())'`, however, works and returns `i386`.

`which python3` returns `/Library/Frameworks/Python.framework/Versions/3.8/bin/python3`.

So I'll just go and reinstall Python now...?

**Comment by mauwii** [comment]
I think you should first run this command in the conda environment itself, but the fact that `python3 -c 'import platform; print(platform.processor())'` returns i386 is indeed very weird 😵‍💫

**Comment by mikealche** [comment]
I'm also having the issue with greenlet
```
ImportError: dlopen(/Users/mike/miniconda3/envs/invokeai/lib/python3.9/site-packages/greenlet/_greenlet.cpython-39-darwin.so, 0x0002): tried: 
'/Users/mike/miniconda3/envs/invokeai/lib/python3.9/site-packages/greenlet/_greenlet.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture 
(have 'x86_64', need 'arm64')), 
```

And for me both commands 
```
python3 -c 'import platform; print(platform.processor())'
```
and 
```
python -c 'import platform; print(platform.processor())'
```
return "arm".

```
(invokeai) ➜  InvokeAI git:(main) conda info                  

     active environment : invokeai
    active env location : /Users/mike/miniconda3/envs/invokeai
            shell level : 2
       user config file : /Users/mike/.condarc
 populated config files : 
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __osx=13.0=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/mike/miniconda3  (writable)
      conda av data dir : /Users/mike/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/mike/miniconda3/pkgs
                          /Users/mike/.conda/pkgs
       envs directories : /Users/mike/miniconda3/envs
                          /Users/mike/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.12 Darwin/22.1.0 OSX/13.0
                UID:GID : 501:20
             netrc file : None
           offline mode : False
           ```

```
(invokeai) ➜  InvokeAI git:(main) brew config                     
HOMEBREW_VERSION: 3.6.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6a7eac25e167a1eb2d49e13c8cc530a3188af995
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2cc17eb6487b116ea1edb9557fc7da8f941c3276
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.32.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0-arm64
CLT: N/A
Xcode: 13.4.1
Rosetta 2: false
```

**Comment by mikealche** [comment]
Managed to fix it by cleaning everything and reinstalling. As noted here: 
https://github.com/invoke-ai/InvokeAI/issues/1064#issuecomment-1295645482

**Comment by woolfel** [comment]
I had similar install issues. This thread helped figure out my problem was because LLVM wasn't installed. After I installed LLVM, creating the env worked.  If your config shows CLang isn't installed, you'll get an error lmdb couldn't install.

**Comment by psychedelicious** [comment]
Close as all users have resolved the install issues. One key quirk is that tmux reported the system architecture as different, causing some platform-detection logic to fail to detect the actual platform.
