### ISSUE TITLE
show aspect ratio overlay for img2img in webui

### ISSUE THREAD

**Issue by whosawhatsis** [invoke-ai/InvokeAI#1079]
When using the img2img webui, it would be useful to have an overlay on the initial image that shows the aspect ratio of the designated width/height settings.

It would also be useful to have a crop tool, so that you can select only part of the original image to use as your initial image.

**Comment by netsvetaev** [comment]
I think, crop, along with other edit features, is on the way, more or less.

I also want to have different aspects presets, like buttons 3:2, 1:1, 2:3 to just change resolution of an output.  
<img width="295" alt="image" src="https://user-images.githubusercontent.com/83028930/195598034-b3d3f8e7-c4e5-49f8-b4b8-389b3d133977.png">
But don’t know if this useful for anyone other.

**Comment by psychedelicious** [comment]
We have indirectly resolved this in the upcoming v2.2 release, which features a canvas and a bounding box to save and/or operate on specific regions of an image.
