### ISSUE TITLE
Weighted prompts feature gives unexpected results

### ISSUE THREAD

**Issue by spezialspezial** [invoke-ai/InvokeAI#1080]
Not sure if I'm missing something but when trying to use weighted prompts it seems whole concepts get removed. For testing I'm using this prompt from the internets as it makes it clear to see due to the green cucumber coloring.

First try vanilla (w:448, h:640, euler_a, 25 steps, cfg:8):

_full body shot, benedict cumberbatch as a cucumber knight, intricate, highly detailed, digital painting, artstation, concept art, art by artgerm and greg rutkowski and alphonse mucha, full body shot_

This should produce very green knights of house cucumber

Now try:

_full body shot, benedict cumberbatch as a`:1.0` cucumber`:1.1` knight, intricate, highly detailed, digital painting, artstation, concept art, art by artgerm and greg rutkowski and alphonse mucha, full body shot_

or even:

_full body shot, benedict cumberbatch as a`:1.0` cucumber`:1.0` knight, intricate, highly detailed, digital painting, artstation, concept art, art by artgerm and greg rutkowski and alphonse mucha, full body shot_

The green is gone and cumbersnitches face is missing.

Can someone reproduce this? User error? I'm basing the syntax on the Weighted Prompts section from the features other markdown

**Expected behavior**
I would expect a weighting of :1.0 not to change anything at all

**Environment**
- GPU: cuda
- VRAM: 24GiB
- CPU arch: x86
- OS: Linux
- Python: miniconda, Python 3.9
- Branch: main
- Commit: 698d30

**Comment by jasonlevine** [comment]
Hi Spezialspezial, its unclear to me what you are trying to achieve, but I don't think you are using prompt weighting correctly.    If you want to weight how much Benedict is a cucumber vs a knight, I would try something like:
_benedict cumberbatch as a cucumber: 0.5 benedict cumberbatch as a knight: 0.5_

**Comment by spezialspezial** [comment]
I'm trying to put emphasis on the cucumber part, making it more cucumbery, but something seems off.

Like in the docs: tell the sampler to attach different levels of priority to them, by adding :<percent> to the end of the section you wish to up- or downweight.

**Comment by psychedelicious** [comment]
@spezialspezial , the syntax is confusing and we have a lot of work ongoing to improve it add a number of other features. Our current prompt weighting (more accurately, prompt blending) is intended to blend whole prompts, not individual tokens. So you do need to use it like this `benedict cumberbatch as a cucumber: 0.5 benedict cumberbatch as a knight: 0.5`.

**Comment by spezialspezial** [comment]
Oh, okay, got it
