### ISSUE TITLE
Noisy image with high step count

### ISSUE THREAD

**Issue by db3000** [invoke-ai/InvokeAI#1083]
**Describe your environment**
- GPU: 3060
- VRAM: 12GB
- CPU arch: x86
- OS: Linux
- Python: miniconda
- Branch: main/development
- Commit: Any commit past or including
   ```
   commit 7541c7cf5d4d3d325e293c873f0904c4d0048fd0 (HEAD)
   Author: Lincoln Stein <lincoln.stein@gmail.com>
   Date:   Thu Oct 6 18:31:04 2022 -0400

       fix k_samplers in img2img - probably correct now
   ```

**Describe the bug**
Running prompts with a high step count results in noisy images, while lower step counts do not (but produce different output). This seems to have been a regression between releases.

**To Reproduce**
Run prompt: `"sharp object" -s 200 -S 1705491283 -W 512 -H 512 -C 7.5 -A k_lms`

**Expected behavior**
On the commit before 7541c7cf5d4d3d325e293c873f0904c4d0048fd0 this prompt produces a sharp image of a knife blade on a red background with a white loop on it. Later commits produce a different image or the same image but much noisier. Lower step counts produce a non-noisy image but  with different content.

**Screenshots**

Commit: 440065f7f843da7751925825de65e4d0d0fe86a0 (parent of 7541c7cf5d4d3d325e293c873f0904c4d0048fd0)
Step Count: 50
![000037 1705491283](https://user-images.githubusercontent.com/4308379/195594379-2236c9aa-b878-40d8-b749-b144ff4bf29c.png)

Commit: 440065f7f843da7751925825de65e4d0d0fe86a0 (parent of 7541c7cf5d4d3d325e293c873f0904c4d0048fd0)
Step Count: 200
![000038 1705491283](https://user-images.githubusercontent.com/4308379/195594411-d5fb563e-a8c8-4557-8a36-55205e90a098.png)

Commit: 7541c7cf5d4d3d325e293c873f0904c4d0048fd0
Step Count: 50
![000039 1705491283](https://user-images.githubusercontent.com/4308379/195594453-1ee66564-8211-4f8d-9720-d26f3cdd4b68.png)

Commit: 7541c7cf5d4d3d325e293c873f0904c4d0048fd0
Step Count: 200
![000040 1705491283](https://user-images.githubusercontent.com/4308379/195594499-11ce64d3-c95f-4967-95b8-65dee4524ba5.png)

Commit: 94bad8555a8832eca01ed7da6797f65cf6bb9cfb (main)
Step Count: 50
![000041 1705491283](https://user-images.githubusercontent.com/4308379/195594523-12ff8314-1a12-4cec-90a4-c1bb80de1fed.png)

Commit: 94bad8555a8832eca01ed7da6797f65cf6bb9cfb (main)
Step Count: 200
![000042 1705491283](https://user-images.githubusercontent.com/4308379/195594565-4695c344-2976-4e4f-9c23-b164b95c580a.png)

Commit: 057fc95aa3c9a174a9893b8dfbb81cef2aeb6a57 (development)
Step Count: 50
![000043 1705491283](https://user-images.githubusercontent.com/4308379/195594581-490164bd-612d-4a80-abf7-456993028201.png)

Commit: 057fc95aa3c9a174a9893b8dfbb81cef2aeb6a57 (development)
Step Count: 200
![000044 1705491283](https://user-images.githubusercontent.com/4308379/195594600-9acb605d-b545-4218-a88f-94f507573f6f.png)

**Additional context**
Other stable-diffusion forks work fine for me at high step count with the same prompt

**Comment by Any-Winter-4079** [comment]
Yesterday I experienced this too.

**Comment by Any-Winter-4079** [comment]
This is the way I experienced this on M1.
`"an anime girl" -s 999 -S 3836318353 -W 512 -H 512 -C 7.5 -I 000200.3031912972.png -A k_lms -f 0.01`
Source image
![000200 3031912972](https://user-images.githubusercontent.com/50542132/195599035-1cd7524a-6e7f-4c30-bbf7-b9c60542756e.png)
Result
<img width="334" alt="Screenshot 2022-10-13 at 14 47 04" src="https://user-images.githubusercontent.com/50542132/195600050-f2ed3c10-b8ee-4f1f-87d4-a5be62460f0f.png">

I had a command with -s2001 where it's more obvious
`"an anime girl" -s 2001 -S 3868303308 -W 512 -H 512 -C 7.5 -I 000200.3031912972.png -A k_lms -f 0.01`
<img width="338" alt="Screenshot 2022-10-13 at 14 48 27" src="https://user-images.githubusercontent.com/50542132/195600361-b1c0bace-654a-4586-9453-4f024c4e60a3.png">
Note to run that command beyond -s999 I was using a fix from an active (unless already merged) PR.

**Comment by Any-Winter-4079** [comment]
@db3000 The thing about getting a different image is separate. Using commit https://github.com/invoke-ai/InvokeAI/commit/7541c7cf5d4d3d325e293c873f0904c4d0048fd0 I also get another image, but it was using a technique that not backwards-compatible for reproducibility.
If you want that behaviour, I talked about it here: https://github.com/invoke-ai/InvokeAI/issues/998
`"sharp object" -s 200 -S 1705491283 -W 512 -H 512 -C 7.5 -A k_lms`
<img width="200" alt="Screenshot 2022-10-13 at 15 19 19" src="https://user-images.githubusercontent.com/50542132/195607551-c5b5297d-e713-46eb-a448-3e36b582c2a2.png">

**Comment by db3000** [comment]
Right, it wasn't the different image that concerned me as much as that being the first commit where I see a lot of noise at higher step levels.

**Comment by Any-Winter-4079** [comment]
Yes, the noise is definitely an issue. I can't reproduce it for txt2img on Mac so far, but maybe @lstein can on cuda.
I can reproduce the noise for img2img and high step counts and low strengths, though.

**Comment by lstein** [comment]
It seems like the denoising is missing a step at the very end. I'll take a look.

**Comment by lstein** [comment]
Try this patch. It reverses a switch from the model sigma schedule to the karras sigma schedule:

~~~
diff --git a/ldm/models/diffusion/ksampler.py b/ldm/models/diffusion/ksampler.py
index 0bc6ccd..830b485 100644
--- a/ldm/models/diffusion/ksampler.py
+++ b/ldm/models/diffusion/ksampler.py
@@ -98,7 +98,7 @@ class KSampler(Sampler):
             rho=7.,
             device=self.device,
         )
-        self.sigmas = self.karras_sigmas
+        self.sigmas = self.model_sigmas

     # ALERT: We are completely overriding the sample() method in the base class, which
     # means that inpainting will not work. To get this to work we need to be able to

~~~

**Comment by db3000** [comment]
@lstein, that patch fixes it.

With patch, step count = 200:
![000045 1705491283](https://user-images.githubusercontent.com/4308379/195625383-4f9c6d0b-3101-46b6-aa6e-a5da37a232f6.png)

**Comment by lstein** [comment]
It looks like the Karras noise schedule improves images at low step counts but fails at high step count. My preference would be to go back to the old noise schedule entirely, but an alternative would be to switch over at some threshold. Do you want to do a comparison of images at low and high step counts under both schedulers and let me know what you'd prefer?

**Comment by Any-Winter-4079** [comment]
Awesome! Note we should re-test `txt2img`, `img2img` and `-v `for both in case this causes some change.

**Comment by db3000** [comment]
Fixed now
