### ISSUE TITLE
PIP Being such ....headache.

### ISSUE THREAD

**Issue by TheBarret** [invoke-ai/InvokeAI#1084]
There was a closed thread/bug on this and I tried that method but it doesn't work.
  
Followed all the steps, but i can't go get beyond this step:
`conda env create`

![](https://i.imgur.com/xBTN6WR.png)

I also tried to update the old version, same problem.

**Comment by db3000** [comment]
Does the solution in https://github.com/invoke-ai/InvokeAI/issues/63#issuecomment-1227849008 work? This solved the issue for me. I wonder if there's a way to prevent these directory conflicts from arising though.

**Comment by TheBarret** [comment]
> Does the solution in [#63 (comment)](https://github.com/invoke-ai/InvokeAI/issues/63#issuecomment-1227849008) work? This solved the issue for me. I wonder if there's a way to prevent these directory conflicts from arising though.

Currently trying it manually, one by one. PIP is such a headache, always has been, and i do not blame SD or anybody of this repo for this btw. Im just very keen fixing this, coz im using SD in a project and this just threw in a wrench in that process.

**Comment by psychedelicious** [comment]
Issue was sorted, possible alternate solution provided as well.
