### ISSUE TITLE
Post-processing issues with API

### ISSUE THREAD

**Issue by shinomakoi** [invoke-ai/InvokeAI#1088]
Hello. Thanks for the good work on Invoke-AI. I'm trying to add the 2.0 features to my Invoke-AI GUI (https://github.com/shinomakoi/sd-dreamer) such as outcropping, face restore etc, but can't get the post-processing to work (apply_postprocessor in generate.py). Maybe I'm missing something or is a bug. Whenever I pass a command to apply_postprocessor (e.g. outcrop or gfpgan, codeformer face restore) like:

**To Reproduce**

```
results = g.apply_postprocessor(
    image_path=image_file,
    tool='gfpgan',
    gfpgan_strength=0.7,
)
```
I get:

`AttributeError: 'NoneType' object has no attribute 'skip_normalize'`

I try to pass skip_normalize=False is an option then it goes to 

`AttributeError: 'NoneType' object has no attribute 'log_tokenization'`

and so on.

**Expected behavior**
Just passing the image_path, tool, gfpgan_strength arguments should work.

Also more documentation on using the API would be helpful. Thanks.

**Comment by psychedelicious** [comment]
See here for loading the various restoration modules (CLI/WebUI initialization script): https://github.com/invoke-ai/InvokeAI/blob/f6191a4f125c7a47aa9e54eca97239fba3a903be/scripts/invoke.py#L653-L672

Once you have the `gfpgan, codeformer, esrgan` objects, you can use the `process` method of each, like this (web UI backend): https://github.com/invoke-ai/InvokeAI/blob/development/backend/invoke_ai_web_server.py#L312-L334

**Comment by psychedelicious** [comment]
No response, closing
