### ISSUE TITLE
Embiggen strength fixed at 0.4 / No alternative prompt

### ISSUE THREAD

**Issue by JPPhoto** [invoke-ai/InvokeAI#1089]
**Is your feature request related to a problem? Please describe.**
Embiggen strength is hardcoded at 0.4, which may not be suitable for all images. It also might be nice to have a different prompt for embiggen when invoked by `!fix`.

**Describe the solution you'd like**
Embiggen strength should be configurable by `--embiggen_strength` as it may differ from the other --strength parameter. It can still default to the present 0.4. It should also support `--embiggen_prompt` to represent an optional prompt that differs from that with which the image was created when using `!fix`.

**Describe alternatives you've considered**
There's no workaround in this case, as 0.4 is hardcoded in `ldm/generate.py` and the prompt is pulled from the source image.

**Additional context**
This could help to reduce strangeness in very large tiled images and/or to just add in detail.

**Comment by JPPhoto** [comment]
It looks like `--embiggen` now supports `--new_prompt`, so that part of this feature request is resolved!

**Comment by lstein** [comment]
The strength fix went into `development` just now.
