### ISSUE TITLE
M1 Mac: ModuleNotFoundError: No module named 'PIL' (I didn't forget conda activate invokeai.)

### ISSUE THREAD

**Issue by mgeduld** [invoke-ai/InvokeAI#1091]
**Describe your environment**
M1 Mac
- OS: MacOS
- Python: [Anaconda/miniconda/miniforge/pyenv/other (explain)]
- Commit: commit 94bad8555a8832eca01ed7da6797f65cf6bb9cfb (HEAD -> main, origin/main, origin/HEAD)

**Describe the bug**
When I run `python scripts/dream.py` I get this error:

python scripts/dream.py       
Traceback (most recent call last):
  File "/Users/MGeduld/code/InvokeAI/scripts/invoke.py", line 13, in <module>
    from ldm.invoke.readline import get_completer
  File "/Users/MGeduld/code/InvokeAI/./ldm/invoke/readline.py", line 14, in <module>
    from ldm.invoke.args import Args
  File "/Users/MGeduld/code/InvokeAI/./ldm/invoke/args.py", line 94, in <module>
    import ldm.invoke.pngwriter
  File "/Users/MGeduld/code/InvokeAI/./ldm/invoke/pngwriter.py", line 12, in <module>
    from PIL import PngImagePlugin, Image
ModuleNotFoundError: No module named 'PIL'

**Additional context**
- In a similar issue (for someone on Windows), comments suggested the user might have forgotten to activate the conda environment. I have definitely activated it. I see (invokeai) in my command prompt.
- The web ai works for me.
- I've tried manually running `pip install pill` and got this:

ERROR: Could not find a version that satisfies the requirement pil (from versions: none)
ERROR: No matching distribution found for pil

- I've tried `pip install pillow` which got me this:

Requirement already satisfied: pillow in /opt/homebrew/Caskroom/miniforge/base/envs/invokeai/lib/python3.9/site-packages (9.2.0)

**Comment by LouisSayers** [comment]
I also got this issue on Mac M1.

At first Invoke ran fine after following instructions. After stopping and going to run at a later time, I got the `ModuleNotFoundError: No module named 'PIL'` error.

Following online instructions I did `pip install pillow`, and now I am getting the error `ModuleNotFoundError: No module named 'torch'`.

It seems somethings not loading quite right, but I don't have enough Python experience to know what is going on.

**Comment by lstein** [comment]
Try running `python scripts/invoke.py`.

The name of the script has changed, and the `dream.py` that's in there is supposed to call `invoke.py` but isn't working right. This will be corrected in the next point release coming soon.

**Comment by mgeduld** [comment]
Is that supposed to open a GUI? 

It starts a process running in the terminal, but I don't see a GUI appear: 

> python scripts/invoke.py
* Initializing, be patient...

>> GFPGAN Initialized
>> CodeFormer Initialized
>> ESRGAN Initialized
>> Loading model from models/ldm/stable-diffusion-v1/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
NOTE: Redirects are currently not supported in Windows or MacOs.
>> Using more accurate float32 precision
>> Model loaded in 12.50s
>> Setting Sampler to k_lms

* Initialization done! Awaiting your command (-h for help, 'q' to quit)
invoke>

**Comment by Any-Winter-4079** [comment]
`python scripts/invoke.py --web`
Then open your browser and go to localhost:9090

**Comment by mgeduld** [comment]
Yes, as I wrote, I can use the browser version, but that doesn't include all the features. I especially want to use it for in and outpainting. 

Is there now way to get the desktop GUI on M1s currently?

**Comment by Any-Winter-4079** [comment]
@lstein may answer more accurately but we're adding in/out painting to the web. As for desktop GUI, Idk if there's set plans or dates for it yet. I assume at some point it'll be done, though.

**Comment by mgeduld** [comment]
Thanks.

**Comment by lstein** [comment]
A week for inpainting and out painting, I think. We’re very close.
