### ISSUE TITLE
CodeFomer and ESRGAN checkpoint location

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#1093]
Greetings,

Please consider adding:
--codeformer_model_path

for consistency and to allow to have all models under the 'models' folder.

Thank you,

**Comment by psychedelicious** [comment]
@lstein , with the upcoming changes to the directory structure, is this a more do-able request?

**Comment by Neosettler** [comment]
Please, consider adding support for other ESRGAN models as well:
https://upscale.wiki/wiki/Model_Database
