### ISSUE TITLE
High Res Optimization only using DDIM sampling for main generation in WebUI and CLI

### ISSUE THREAD

**Issue by PutUsernameHere** [invoke-ai/InvokeAI#1097]
**Describe your environment**
- GPU: cuda
- VRAM: 11GB
- CPU arch: x86
- OS: Windows
- Python: Anaconda
- Branch: Development
- Commit: ce5e57d8285aa21221c707ad5a2e92c4040a0d6a

**Describe the bug**

**To Reproduce**
1. Generate image in WebUI or CLI with a non-DDIM sampler with `--hires_fix` enabled
2. Watch your intended sampler being used for the lower-resolution image
3. See DDIM being used for primary image generation.

**Expected behavior**
My understanding is that since the K-samplers work in Img2Img, it should also work for Hires_fix. I might be misremembering, but I thought I had already seen the K-samplers being used in a slightly earlier implementation of Hires_fix

**Comment by lstein** [comment]
An earlier version used whatever sampler was currently chosen. However some of the k samplers (I'm looking at **you**, `k_euler_a`) are too creative and are altering the image between the low-res step and the high-res step. DDIM does a pretty good job at keeping the highres image compatible with the lowres one.

If you like, I'll make a branch for you that restores the floating sampler behavior and you can compare. I'm not adverse to making this a user-configurable option.

**Comment by PutUsernameHere** [comment]
If it's not too much trouble that would be great. I agree that some of the k samplers can deviate further, but that's some of the appeal of choosing them to me (especially `k_euler_a`). Using DDIM for final sampling certainly reduces the deviation, but it also makes the differences in the samplers less noticeable. Minor variations in an image is something I'd rather do with `-V`.

**Comment by lstein** [comment]
Checkout branch `hires-fix-native-sampler`. In this version, the same sampler you use for generation is also used for upscaling. I'm not sure it's working quite right -- in my opinion the upscaled images are washed out when using the k* samplers.

**Comment by PutUsernameHere** [comment]
Here's some test images I generated. First row is DDIM, second is k_lms, and third is k_euler_a. The first is with DDIM as secondary.
![SetSampler-Lowres_DDIM-Hires (Custom)](https://user-images.githubusercontent.com/37318355/196009778-72850f4e-c3e2-4d6e-be2c-580963407ac4.png)
This one is with the native samplers:
![SetSampler-Lowres_SetSampler-Hires (Custom)](https://user-images.githubusercontent.com/37318355/196009767-ef0c4a5a-497e-4326-884d-c37642143e11.png)
There does seem to be some loss of contrast and I think that the first one looks better (using DDIM).
My only concern is that as of right now the DDIM sampler makes the most sense for secondary sampling, but that might not always be the case and the current metadata doesn't declare anything besides the initial sampler. There could be some insane optimization to k_lms or even a new sampler that makes sense to be the default over DDIM, and the current metadata wouldn't have enough information to maintain backwards compatibility, which seems to be a big focus of this repo.

I'm not much of a programmer or I'd try to implement this myself, but it seems to me that storing both samplers used in the metadata and giving an advanced option to set the secondary sampler from its default of DDIM (maybe as a dropdown below the hires option in the interface and an equivalent flag in the CLI) would be the best way to allow for changes in the future, and recording all of the settings that led to the image being generated.
 
None of this is necessary if DDIM is always going to be the best choice, but it strikes me as something that could cause more trouble in the future.

**Comment by JPPhoto** [comment]
@PutUsernameHere Are you getting radically different images with the same parameters (adjusting to get the same initial image size) with and without `--hires_fix`? I'm seeing that and wondering if it's this branch only.

**Comment by discordinated** [comment]
I'm seeing big changes depending on the image and sampler selected, sometimes I prefer the DDIM version, other times I prefer the selected sampler version with this branch. Some samplers like K_lms I see very little difference for others like k_eular_a and k_huen the difference is more pronounced if using the same sampler for the high_res part.  

Would love to have the option to select which one to use in the UX.

**Comment by psychedelicious** [comment]
@lstein 
> Checkout branch hires-fix-native-sampler. In this version, the same sampler you use for generation is also used for upscaling. I'm not sure it's working quite right -- in my opinion the upscaled images are washed out when using the k* samplers.

I can't find this branch - if this is integrated, is this available as a flag/kwarg for Generate()?

**Comment by psychedelicious** [comment]
HRO is not implemented in v3.0
