### ISSUE TITLE
In invoke web UI, pressing "Use All" on a txt2img does not change web UI state to indicate change to txt2img

### ISSUE THREAD

**Issue by Perryman** [invoke-ai/InvokeAI#1102]
**Describe your environment**
- GPU: cuda
- VRAM: 12G
- CPU arch: x64
- OS: Linux
- Python: Anaconda
- Branch: On branch main
- Commit: 194d4c75b39b09a48d5facdeb1b1a7e5de972203

**Describe the bug**
If you're in the invoke web UI and you're doing img2img work, then you click on an image and click "use all," the state of the pending command changes based on whether the image you picked was img2img or txt2img. The web UI does not switch back to txt2img, but the output command and output are txt2img.

**To Reproduce**
1. Run invoke.py --web
2. Have at least 1 txt2img generated (any parameters)
3. Send any image to img2img
4. Select any previously generated txt2img output using the right pane
5. Click "Use All" on the top bar
6. Invoke the image
7. Observe that the output is "txt2img" and the web UI still indicates img2img mode

**Expected behavior**
I saw the img2img UI, so I expected to be in img2img mode.
If "Use All" is intended to use the mode, then it should change the web UI.
If "Use All" isn't intended to change the mode, then the option slicer logic might be wrong.

**Screenshots**

**Additional context**
https://github.com/invoke-ai/InvokeAI/blob/194d4c75b39b09a48d5facdeb1b1a7e5de972203/frontend/src/features/options/optionsSlice.ts#L191-L198

**Comment by psychedelicious** [comment]
Hmm, I'm not sure we actually want to change this. What if you want to use all parameters in img2img? 

@blessedcoolant , related to the bug you just found, what do you think?

**Comment by Perryman** [comment]
I think the core thing I’m reporting here is that the state of the web UI should match the state. If it were

**Comment by psychedelicious** [comment]
Ahh, I misunderstood the issue at first. I see what is happening. An assumption made a while ago is no longer correct. Fixed in #1198.
