### ISSUE TITLE
What happened to the --device flag?

### ISSUE THREAD

**Issue by vexyuwu** [invoke-ai/InvokeAI#1104]
I am on the main branch (commit 194d4c7) on Ubuntu 22.04.1, and the `--device cuda:x` flag doesn't work. it just gives this error:
`invoke.py: error: unrecognized arguments: --device cuda:0`
I looked for information on this, but the only thing I could find was issue #743, which only applies to the experimental branch.
Was this removed without being mentioned in the changelog? If so, why would it still be listed in `CLI.md`?

**Comment by marklr** [comment]
Can you share the exact command you're running and if possible the full stack trace?

**Comment by n00mkrad** [comment]
Use the environment variable to set the GPU.

`SET CUDA_VISIBLE_DEVICES=0,1` to use your first and second GPU, etc.

**Comment by lstein** [comment]
I think `--device` was taken out during a reorganization of how autocasting and precision are determined. I'll see what's involved in putting it back in.

**Comment by freshlesh3** [comment]
> Use the environment variable to set the GPU.
> 
> `SET CUDA_VISIBLE_DEVICES=0,1` to use your first and second GPU, etc.

Sorry very much a civilian, but how do you set this? Is this still an option, would love to use both GPUs when generating images.
