### ISSUE TITLE
2.0.1: _pickle.UnpicklingError: unpickling stack underflow

### ISSUE THREAD

**Issue by ParityError** [invoke-ai/InvokeAI#1105]
**Describe your environment**
- GPU: Apple Silicon
- VRAM: -
- CPU arch: arm64
- OS: macOS
- Python: pyenv > anaconda 
- Commit: 194d4c75b39b09a48d5facdeb1b1a7e5de972203

**The Bug**
After installing v2.0.1 and successfully installing I get the following error after executing `python scripts/invoke.py --web` or `python scripts/invoke.py`:

```
% python scripts/invoke.py      
* Initializing, be patient...

>> GFPGAN Initialized
>> CodeFormer Initialized
>> ESRGAN Initialized
>> Loading model from models/ldm/stable-diffusion-v1/model.ckpt
>> Calculating sha256 hash of weights file
>> sha256 = 4a4c7bd07d95fb4fcf06198bd39f9f185365db435a23a892549ae04370b8f2e0 (0.00s)
Traceback (most recent call last):
  File "/Users/Me/InvokeAI/scripts/invoke.py", line 586, in <module>
    main()
  File "/Users/Me/InvokeAI/scripts/invoke.py", line 107, in main
    gen.load_model()
  File "/Users/Me/InvokeAI/ldm/generate.py", line 660, in load_model
    model = self._load_model_from_config(self.config, self.weights)
  File "/Users/Me/InvokeAI/ldm/generate.py", line 799, in _load_model_from_config
    pl_sd = torch.load(io.BytesIO(weight_bytes), map_location='cpu')
  File "/Users/Me/.pyenv/versions/anaconda3-2022.05/envs/invokeai/lib/python3.9/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/Me/.pyenv/versions/anaconda3-2022.05/envs/invokeai/lib/python3.9/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: unpickling stack underflow
```

**To Reproduce**
Install the latest version and it just happens. There was also no directory `stable-diffusion-v1` in `models/ldm`, so I needed to create it. 

**Expected behavior**
It used to work, not sure why not now.

**Screenshots**
N/A

**Additional context**
If you need additional info let me know.

**Comment by ParityError** [comment]
**Update:** I seem to have found the issue. Before I was using a symlink to the `model.ckpt`. When I executed the `preload_models.py`I happened to notice this warning:

```
NOTE: Redirects are currently not supported in Windows or MacOs.
```
This should say `WARNING`, not `NOTE`, and check that the model is not symlinked.

**_Why did this change?_** It's quite inconvenient to copy whatever .ckpt I need to use into the directory each time (since I use several different .ckpt files). The symlinked way works much better for those who use multiple .ckpts and need them in a customized location other than the cloned repo's.

**Comment by TemperoTengu** [comment]
> It's quite inconvenient to copy whatever .ckpt I need to use into the directory each time

Please note that the issue lies with the handling of symlinks, not with paths. You can just write full path in `models.yaml`, e.g. 

```
sd14:
    config:  configs/stable-diffusion/v1-inference.yaml
    weights: /Users/username/ML/ckpts/sd14.ckpt
    width: 512
    height: 512
```

This is still inconvenient but less annoying than moving checkpoints around.

**Comment by tildebyte** [comment]
The really weird thing to me here, is that I still use a model symlink on Windows (created with [symlinker](https://github.com/amd989/symlinker)), still get the note, but it just works...

**Comment by psychedelicious** [comment]
Closing as this does not apply to current release
