### ISSUE TITLE
Ability to use the terminal while the webui is running

### ISSUE THREAD

**Issue by 19wolf** [invoke-ai/InvokeAI#1124]
**Is your feature request related to a problem? Please describe.**
Until all the features available in terminal are usable in webui, I'd like to be able to use the terminal while the webui is running.

**Describe the solution you'd like**
I'd like to be able to use the terminal while the webui is running.

**Describe alternatives you've considered**
Running two instances is an option but requires extra system resources and can cause conflicts if both try to use the gpu at the same time

**Additional context**
Perhaps a way to enter terminal commands in the webui directly is another option

**Comment by psychedelicious** [comment]
Entering invoke REPL commands in the web UI would be pretty cool and, I believe, fairly straightforward to implement - we can parse the command and send it to the generator just like we do currently with the web ui parameters. Error handling could be tricky, though...

**Comment by hipsterusername** [comment]
Have been thinking about this, and if we do it, I think the one "UX" feature we'd want to include would be a command "starter" - Basically, copy whatever settings/info I have in the WebUI into the CLI command, which I can then edit/add to.

Very useful in cases where a CLI feature hasn't been made available in the WebGUI yet, and prevents having to retype everything

**Comment by psychedelicious** [comment]
I found an older issue #543 with a similar request and a good idea - add a checkbox that runs the prompt as a REPL command.

Unfortunately, if we just parsed the REPL command and passed the parameters to the web UI's server, we would still be limited to features supported by the web UI. So I think making this work in a useful way (i.e. exposing CLI-only features on the UI) this is a bit trickier than I imagined initially.

**Comment by 19wolf** [comment]
It doesn't necessarily need to be available in the webui, though I understand why we'd want that. But my original thought was to just have the command line `invoke> ` remain available in the terminal while the webui is running

**Comment by psychedelicious** [comment]
Right. I'm going to take the coward's way out and say this is beyond the scope of the current server, and ask @Kyle0654  to consider this for the WIP backend.

**Comment by Kyle0654** [comment]
I've considered it 🙂. I think it would end up being a CLI that uses the web API though, otherwise we risk service conflicts in the new architecture.

**Comment by vionwinnie** [comment]
I would like to use the Invoke AI model as a serving for API calls - so this feature would be super helpful to interact with the backend.
