### ISSUE TITLE
2.0 to 2.0.1 issue

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#1130]
Greetings,

@lstein I've managed to generate a few hundreds images with 2.0 and comparing the result with 2.0.1. It seems that some prompts in 2.0 took far less steps to achieved a descent result. Is that related to the noise generation issue? To my surprise, one prompt didn't get close to good quality at 50 steps and took about a 100 steps to get to parity with 2.0... what's going on?

![_Tests-2022-10-16-173814-427801153](https://user-images.githubusercontent.com/4521415/196059769-a701a8cf-4924-420c-ac57-e0443ac40dc6.png)
![Carbon Based-2022-10-13-153334-427801153](https://user-images.githubusercontent.com/4521415/196059772-04daf9e6-3d2b-4c96-9e77-0bea5b3f0ec3.png)

**Comment by db3000** [comment]
Likely related to https://github.com/invoke-ai/InvokeAI/pull/1086, where the Karras noise schedule used in 2.0 was reverted in 2.0.1 as it produced very noisy images at high step counts. See also https://github.com/invoke-ai/InvokeAI/issues/1083

@lstein is it worth implementing something like your suggestion in https://github.com/invoke-ai/InvokeAI/issues/1083#issuecomment-1277717115 to have a threshold at which this switches off?

**Comment by db3000** [comment]
I wonder if there's a point of continuity that can be found between the noise schedules where the switch could be done. Can try generate images at each step count with both until you get basically the same image, and use that step count as a constant at which to switch over.

**Comment by michaelezra** [comment]
I noticed this issue ad hoc at 20 iterations using k_lms sampler. It did not occur with other sampler for me.

**Comment by lstein** [comment]
It makes sense to switch over from one noise schedule to the other at a certain threshold, but I'm not convinced that the issue with non-convergent images at high step counts with the Karras noise schedule isn't a bug in how Karras is implemented. Could @neosettler share the prompt of the noisy first image they posted? The metadata seems to have been stripped during uploading.

**Comment by Neosettler** [comment]
Sent prompt on discord. Playing around with --save_intermediates, I'm noticing that image 50, at 50 steps, is not the same as image 50, at 100 steps. What am I missing?

**Comment by Neosettler** [comment]
Also, the intermediates last image have a lot of noise compare to the final result.  I was under the impression that the intermediate images would have been usable but it seems like they aren't ready for prime time, what's the catch?

**Comment by lstein** [comment]
This is a property of the diffusers. They remain noisy for a long time and
then coalesce near the end. Also, if you are only showing every 5th o,age,
you may be missing the intermediate steps.

In fact, when you run 100 steps, the algorithm stretches out the schedule
it uses to add noise, so that it adds less noise to step 49/50 than step
49/100.

Lincoln

**Comment by Neosettler** [comment]
Thank you for your comment [lstein](https://github.com/lstein), is there a way to save intermediates as if every image was the final result? The idea would be to allow choosing what images looks best. As it is now, only the final image looks decent so the whole intermediates output has not much of a use from an artistic stand point.

**Comment by psychedelicious** [comment]
@damian0815 , a while ago you shared a branch that did what @Neosettler is asking for (sample images at every step), can you please link us to that? I think it'd be a cool feature, understanding that it dramatically increases processing time.

**Comment by Neosettler** [comment]
Totally, I'd be a big fan for that one [psychedelicious](https://github.com/psychedelicious)!!! @lstein Would that require to start from step 0 for every iteration?

**Comment by damian0815** [comment]
@psychedelicious @Neosettler i have [show-latent-steps](https://github.com/damian0815/InvokeAI/tree/show-latent-steps) which is way behind development - it seems in the meantime a `--save-intermediates` has made its way into `development`. mine saves every latent step, and has the advantage of being super-fast because it's approximating RGB from the low-res latents directly, rather than doing a lengthy upscale. probably it would be good to have both?

**Comment by psychedelicious** [comment]
We support showing both of these now in the web UI, at a user-chosen interval (I think it won't be in main until v2.2 release, can't remember). I'll close this but please let me know if this isn't what you were asking for @Neosettler .
