### ISSUE TITLE
Has anyone tried using textual inversion to custom train a model?

### ISSUE THREAD

**Issue by VincentLu91** [invoke-ai/InvokeAI#1134]
**Describe your environment**
- GPU: cuda
- VRAM: 24 GPU RAM (I use RTX3090 GPU)
- CPU arch: [x86/arm] - N/A
- OS: Linux
- Python: used a GPU-enabled notebook for training so no conda required, just pip install of requirements.txt
- Branch: [if `git status` says anything other than "On branch main" paste it here] - N/A
- Commit: [run `git show` and paste the line that starts with "Merge" here] - N/A

**Describe the bug**
Got an AttributeError: 'int' object has no attribute 'strip' when attempting to train a model on a data set with textual inversion 

**To Reproduce**
I've been having trouble custom training a model using textual inversion. Based on the example in

https://github.com/rinongal/textual_inversion

I tried the following on a notebook:
` python main.py --debug --base ./configs/stable-diffusion/v1-finetune.yaml -t --actual_resume ./models/ldm/stable-diffusion-v1/model.ckpt -n my_key --gpus 0, --data_root /path/to/directory/with/images`

Instead I got:
```
Traceback (most recent call last):
  File "/opt/trainml/models/main.py", line 921, in <module>
Unexpected Keys: ['model_ema.decay', 'model_ema.num_updates']
Monitoring val/loss_simple_ema as checkpoint metric.
Merged modelckpt-cfg: 
    ngpu = len(lightning_config.trainer.gpus.strip(',').split(','))
AttributeError: 'int' object has no attribute 'strip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/trainml/models/main.py", line 985, in <module>
{'target': 'pytorch_lightning.callbacks.ModelCheckpoint', 'params': {'dirpath': 'logs/input2022-10-17T02-37-48_my_key/checkpoints', 'filename': '{epoch:06}', 'verbose': True, 'save_last': True, 'monitor': 'val/loss_simple_ema', 'save_top_k': 1, 'every_n_train_steps': 500}}
#### Data #####
train, PersonalizedBase, 500
validation, PersonalizedBase, 5
    debugger.post_mortem()
  File "/opt/conda/lib/python3.9/site-packages/pudb/__init__.py", line 217, in post_mortem
    dbg.interaction(tb.tb_frame, exc_info)
  File "/opt/conda/lib/python3.9/site-packages/pudb/debugger.py", line 290, in interaction
    self.ui.call_with_ui(self.ui.interaction, exc_tuple,
  File "/opt/conda/lib/python3.9/site-packages/pudb/debugger.py", line 1901, in call_with_ui
    self.show()
  File "/opt/conda/lib/python3.9/site-packages/pudb/debugger.py", line 1892, in show
    self.screen.start()
  File "/opt/conda/lib/python3.9/site-packages/urwid/display_common.py", line 813, in start
    self._start(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/urwid/curses_display.py", line 111, in _start
    self.s = curses.initscr()
  File "/opt/conda/lib/python3.9/curses/__init__.py", line 29, in initscr
    setupterm(term=_os.environ.get("TERM", "unknown"),
_curses.error: setupterm: could not find terminal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/trainml/models/main.py", line 993, in <module>
    os.rename(logdir, dst)
FileNotFoundError: [Errno 2] No such file or directory: 'logs/input2022-10-17T02-37-48_my_key' -> 'logs/debug_runs/input2022-10-17T02-37-48_my_key'
Exiting...
```

**Expected behavior**
The training should finish with the appropriate model checkpoints, config, images, and testtube folders created under /log in the root folder with no errors encountered

**Comment by Any-Winter-4079** [comment]
> _curses.error: setupterm: could not find terminal

Is this error for not using a Terminal?

**Comment by lstein** [comment]
The —gpu argument is being parsed incorrectly but it looks ok on the command line.

**Comment by Any-Winter-4079** [comment]
I'm training right now, using
`python3 ./main.py --base ./configs/stable-diffusion/v1-m1-finetune.yaml -t --actual_resume ./models/ldm/stable-diffusion-v1/model.ckpt --data_root myself50photos -n myself50photos --gpus 0, --no_test`
By the way, I think the `no_test` is ignored.

**Comment by VincentLu91** [comment]
Okay I'm able to get the training to work, but it stopped at epoch 13 due to the "No `test_dataloader()` method defined to run `Trainer.test`." I'll raise a new issue for this error.
