### ISSUE TITLE
Hires options

### ISSUE THREAD

**Issue by cwallen** [invoke-ai/InvokeAI#1142]
**Is your feature request related to a problem? Please describe.**
When using `--hires_fix` It would be nice to be able to control the settings of each pass independently. 

While hires does seem to help the large image repeat problems, I still get a fair amount of artifacts and would like to play around to see if there are combinations of strength and steps that might work better.
Also thinking that a very small number of steps on the first generation might be good enough since it's getting img2img after anyway.

**Describe the solution you'd like**
Same pattern as `-U`, be able to specify `--hires_fix <steps> <strength>` to set steps and strength for the img2img pass. 

**Describe alternatives you've considered**
I could script it with mutiple operations for experimentation, but it would be nice to have it built in once I have values I want.

**Additional context**
I also was trying to use `--save_original` with `--hires_fix` to keep the first pass image but that didn't work.

**Comment by ArDiouscuros** [comment]
You could use option ````-f```` with ````--hires_fix```` to control how many steps/strengths you will apply on second step
