### ISSUE TITLE
Web UI "Use All" (with weighted inputs) to return original input

### ISSUE THREAD

**Issue by Perryman** [invoke-ai/InvokeAI#1145]
When pressing Use All on the web UI of invoke.py, if weights were given, the normalized weights are returned rather than what the user input.

I'd prefer to get the input I gave as the most expected outcome.

If there was a toggle or a clearer indication of what was happening or why, that could work too.

Example:

Original prompt:
`"cat":0.9 "bat":0.1 "Halloween"`
Prompt when pressing "Use All" on above output:
`"cat":0.45 "bat":0.05 "Halloween":0.5`

I expected to get the same input I typed in rather than the normalized weights, and both are stored in the exifdata in the output folder.

Thanks!

**Comment by psychedelicious** [comment]
Resolved in PR #1165, thanks @Perryman .

**Comment by psychedelicious** [comment]
PR merged.
