### ISSUE TITLE
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'

### ISSUE THREAD

**Issue by calvin200001** [invoke-ai/InvokeAI#1148]
Hello, I am on Mojave on an intel mac and am getting this error. I ran all the code and am using the standalone version. Any ideas why this might happen?

**Comment by 19wolf** [comment]
Post in the bugs and support section of Discord, this likely isn't a bug.

**Comment by calvin200001** [comment]
> Post in the bugs and support section of Discord, this likely isn't a bug.

Can you send me an invite link?

**Comment by psychedelicious** [comment]
You may need to run `conda init <YOUR_SHELL>`, e.g. on macOS with zsh as the default shell, `conda init zsh`.

You can see what shell you are using by running `echo $SHELL` in a Terminal window. 

Here's discord the invite link: https://discord.gg/TWjSVjt2

**Comment by psychedelicious** [comment]
This is an issue with the end-user's conda setup
