### ISSUE TITLE
Textual inversion embeddings can't be used to render images

### ISSUE THREAD

**Issue by rhinoid** [invoke-ai/InvokeAI#1153]
**Describe your environment**
- GPU: [m1]
- VRAM: [32GB]
- CPU arch: [arm]
- OS: [macOS]
- Python: [miniconda]
- Branch: []
- Commit: [commit ca6385e6fa3e2b53239bc68f19762ce566b60de6]

**Describe the bug**
After training a concept with the 'textual inversion' module. If I then use that embedding in stable-diffusion it won't use it. Running 'a photo of *' gives plain weirdness. 

**To Reproduce**
- create folder with training images etc
- add some init words in the configs/stable-diffusion/v1-finetune.yaml under: initializer_words
- start training with something like: ```python3 ./main.py --base ./configs/stable-diffusion/v1-finetune.yaml --train --actual_resume ./models/ldm/stable-diffusion-v1/model.ckpt --data_root /Users/username/Desktop/trainingimages --no-test```
- Wait for 6000+ iterations. 
- In the logs/.../images folder you see training images which look more and more like the trained material. SO this seems to work.
- Then stop training and start the web frontend with the embedding file as extra parameter as such:
```python scripts/invoke.py --web --embedding_path logs/.../checkpoints/embedding.pt```
- then create an image like this: a photo of *  

**Expected behavior**
You would want to see the trained object/face/thing at least a bit. However it produces weirdness. Also combining it with other concepts doesn't show the trained thing.

**Screenshots**
Screenshot attached of a 'photo of *' generation.
![000066 2264866706](https://user-images.githubusercontent.com/2438289/196509992-a5a47094-7464-48b3-8c5e-8ac72f47143b.png)

**Additional context**
Some extra info: if I change: num_vectors_per_token in the file configs/stable-diffusion/v1-inference.yaml to something higher than 1 I do see the trainings material start to appear. However this is NOT a fix because if I combine it with anything else on the prompt it only shows the training material without any hint of other concepts on the prompt

**Comment by rhinoid** [comment]
Additional additional context:   I reverted the repo back to '2.0.0-rc8' and there it does work

**Comment by FreeBlues** [comment]
I got the same issue when I try to use this prompt: `a photo of *`.

When I try to specify an explicit model name, it works

The prompt is: `a photo of <lofa>`, you can try it.

**Comment by rhinoid** [comment]
That's a .bin file. These indeed work, and you als see that they have a specific name when the app boots (its in the console output).
However the .pt file it generates doesn't work. In the console you only see '*' as new term. And that one doesn't work

**Comment by lstein** [comment]
Has there been any change in the status of this bug?

**Comment by FreeBlues** [comment]
@rhinoid @lstein How about the progress? 

Yesterday on my macOS(Intel  x86+ RX 6600XT) I trained in invokeai and got a file `embeddings.pt`, the `init_word` is `myEm`.  The same issue as yours. It can not be used in `invokeai`, I tried different prompt in `invokeai`:

```
a photo of *
a photo of <*>
a photo of <myEm>
a photo of myEm
a photo of <embeddings>
a photo of embeddings
```

None of them can work.

Then I tried use it in `AUTOMATIC1111-webui`, found one of them can work, others can not, the only  working one is:

```
a photo of embeddings
```

**Comment by 18242988489** [comment]
> That's a .bin file. These indeed work, and you als see that they have a specific name when the app boots (its in the console output). However the .pt file it generates doesn't work. In the console you only see '*' as new term. And that one doesn't work


Please, what changes did you make in the end?

**Comment by 18242988489** [comment]
> Additional additional context: I reverted the repo back to '2.0.0-rc8' and there it does work

I have the same problem as you, what did you change to solve?
