### ISSUE TITLE
cli option for the web base path or use relative paths

### ISSUE THREAD

**Issue by steverweber** [invoke-ai/InvokeAI#1159]
When using invokeai in --web mode the html uses paths like `/assets/index.58175ea1.css` the issue is the base path is different because under a proxy. In my case users are using Jupyter with the jupyter-server-proxy module and have a path like `https://jupyter.xxx/user/myid/proxy/9090/`

**Describe the solution you'd like**

perhaps a CLI switch like `--web_basepath=`. So `--web_basepath=/user/myid/proxy/9090/`

**Describe alternatives you've considered**

Or perhaps relative paths will work best if it's a single page application `assets/index.58175ea1.css`

**Comment by steverweber** [comment]
might also be some wonky stuff around `socket.io`

**Comment by psychedelicious** [comment]
Hi @steverweber , I've changed the frontend bulid to use relative asset paths in #1185.

Can you please give this a go? Hopefully that's all that is needed.

**Comment by steverweber** [comment]
sure feel free to close. I just assume there is still some more bugs. But someone else can report that and the complete fix can be reiterated on.

**Comment by steverweber** [comment]
your patch looks good. however still have issue with socket.io path because it's set to `/socket.io`

Perhaps file string:
[rontend/vite.config.ts](https://github.com/invoke-ai/InvokeAI/blob/4b95c422bde493bf7eb3068c6d3473b0e85a1179/frontend/vite.config.ts)

could be changed to `./socket.io`

**Comment by psychedelicious** [comment]
The config in that file is only used when running the frontend development server, so it wouldn't affect your use case. 

I'm not sure how to fix the socket.io routing issue, hmm. @blessedcoolant , can you please review when you have time?

**Comment by steverweber** [comment]
ah yes ic.

a shot in the dark..

https://github.com/invoke-ai/InvokeAI/blob/899ba975a6663528d120af2061c053a8cf6d7524/frontend/src/app/socketio/middleware.ts#L27
```
  const { origin } = new URL(window.location.href);
  const socketio = io(origin, {
    timeout: 60000,
    path: window.location.pathname + 'socket.io',
  });
```

**Comment by psychedelicious** [comment]
Well, that seems reasonable and it doesn't appear to break anything in my brief testing. I've updated the frontend bundle in the #1185  if you'd like to test it.

**Comment by psychedelicious** [comment]
Nice! No worries, we will get it merged into development soon.
