### ISSUE TITLE
ModuleNotFoundError: No module named 'clipseg'

### ISSUE THREAD

**Issue by mickr777** [invoke-ai/InvokeAI#1160]
**Describe your environment**
- GPU: cuda
- VRAM: 12gb
- CPU arch: x86
- OS: Windows
- Python: miniconda
- Branch: Development
- Commit: 9b3ac92

**Describe the bug**
While Running preload_model.py:

Loading clipseq model for text-based masking...Error installing clipseg model:
Traceback (most recent call last):
  File "C:\Users\user\InvokeAI\scripts\preload_models.py", line 120, in <module>
    from clipseg import CLIPDensePredT
ModuleNotFoundError: No module named 'clipseg'

When Starting invoke.py:

Traceback (most recent call last):
  File "C:\Users\user\InvokeAI\scripts\invoke.py", line 708, in <module>
    main()
  File "C:\Users\user\InvokeAI\scripts\invoke.py", line 36, in main
    from ldm.generate import Generate
  File "c:\users\user\invokeai\ldm\generate.py", line 37, in <module>
    from ldm.invoke.txt2mask import Txt2Mask, SegmentedGrayscale
  File "c:\users\user\invokeai\ldm\invoke\txt2mask.py", line 32, in <module>
    from clipseg import CLIPDensePredT
ModuleNotFoundError: No module named 'clipseg'

**Comment by gfosco** [comment]
this latest commit on `development` breaks it for me as well.. https://github.com/invoke-ai/InvokeAI/commit/9b3ac92c24b4623e5e52d72b844d9c72f7416760

with this change undone, it works.

**Comment by mickr777** [comment]
Working now with commit on development 62dd3b7

**Comment by swankwc** [comment]
I'm still getting this and it won't let me open the web ui unless I fix it. I'm not really sure if I follow your fixes. 

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /Users/wesley/Desktop/stable-diffusion-project/invokeai/scripts/scripts/invo │
│ ke.py:884 in <module>                                                        │
│                                                                              │
│   881 ######################################                                 │
│   882                                                                        │
│   883 if __name__ == '__main__':                                             │
│ ❱ 884 │   main()                                                             │
│   885                                                                        │
│                                                                              │
│ /Users/wesley/Desktop/stable-diffusion-project/invokeai/scripts/scripts/invo │
│ ke.py:50 in main                                                             │
│                                                                              │
│    47 │   │   │   args.max_loaded_models = 1                                 │
│    48 │                                                                      │
│    49 │   print('* Initializing, be patient...')                             │
│ ❱  50 │   from ldm.generate import Generate                                  │
│    51 │                                                                      │
│    52 │   # these two lines prevent a horrible warning message from appearin │
│    53 │   # when the frozen CLIP tokenizer is imported                       │
│                                                                              │
│ /Users/wesley/Documents/InvokeAI/InvokeAI/ldm/generate.py:40 in <module>     │
│                                                                              │
│     37 from ldm.invoke.conditioning import get_uc_and_c_and_ec               │
│     38 from ldm.invoke.model_cache import ModelCache                         │
│     39 from ldm.invoke.seamless import configure_model_padding               │
│ ❱   40 from ldm.invoke.txt2mask import Txt2Mask, SegmentedGrayscale          │
│     41                                                                       │
│     42 def fix_func(orig):                                                   │
│     43 │   if hasattr(torch.backends, 'mps') and torch.backends.mps.is_avail │
│                                                                              │
│ /Users/wesley/Documents/InvokeAI/InvokeAI/ldm/invoke/txt2mask.py:32 in       │
│ <module>                                                                     │
│                                                                              │
│    29                                                                        │
│    30 import torch                                                           │
│    31 import numpy as  np                                                    │
│ ❱  32 from clipseg_models.clipseg import CLIPDensePredT                      │
│    33 from einops import rearrange, repeat                                   │
│    34 from PIL import Image, ImageOps                                        │
│    35 from torchvision import transforms                                     │
╰──────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'clipseg_models'
