### ISSUE TITLE
Unable to generate image larger than 640x640 - RuntimeError: Invalid buffer size: 3.57 GB

### ISSUE THREAD

**Issue by alessandro893** [invoke-ai/InvokeAI#1166]
**Describe your environment**
- GPU: [mps]
- VRAM: [8GB]
- RAM: [48GB]
- CPU arch: [x86]
- OS: [macOS]
- Python: [miniforge]
- Branch: [Main]

**Describe the bug**
Unable to generate image larger than 640x640.

**To Reproduce**
1. Go to 'web interface'
2. Select resolution larger than '640x640'
3. Press invoke

**Expected behavior**
Generating image with specified size

**Screenshots**
![error](https://user-images.githubusercontent.com/4077478/196648235-af668b24-12de-4271-916c-28f2872e9834.jpg)

**Comment by psychedelicious** [comment]
This is definitely not a web UI bug - believe the error is exactly that is going wrong, you don't have enough VRAM.

It may be that your VRAM usage besides InvokeAI is high enough that generation cannot complete. Try restarting and then closing as many applications as you can to free up VRAM, then run a larger generation.

**Comment by alessandro893** [comment]
How many VRAM need for 1024x1024 image generation? Nvidia users claim that they can generate even larger images with 8GB VRAM. It's possible to store excess data in ram? 

P.S.  
Few times text2img generated 1024x1024 for me

**Comment by lstein** [comment]
How large an image you can generate depends both on how much VRAM InvokeAI is using and what else the GPU happens to be doing at the time. If you close any other programs that use accelerated graphics, you might be able to squeak a little bit more out of the GPU.

@psychedelicious would it be possible to add some VRAM usage diagnostics into the WebGUI, or a more informative error message? There is code in the CLI which monitors and reports how much VRAM is currently in use. Happy to adapt it for your purposes.

**Comment by alessandro893** [comment]
Behaviour always different. I made few changes in attention.py related to einsum and now it generates even 1280x1280, I'll test it futher.. (I have no background tasks using GPU memory)
