### ISSUE TITLE
Codeformer produces bad quality output

### ISSUE THREAD

**Issue by discordinated** [invoke-ai/InvokeAI#1167]
**Describe your environment**
- GPU: [mps]
- VRAM: [32GB]
- CPU arch: [arm]
- OS: [macOS]
- Python: [miniconda]
- Branch: [add-codeformer]
- Commit: [run `git show` and paste the line that starts with "Merge" here]

**Describe the bug**
InvokeAI's CodeFormer implementation is messed up and produces vastly different results to running CodeFormer natively. 

**To Reproduce**
1. Go to 'Use the add-codeformer PR or CLI option for Codeformer'
2. Click on '.Apply Codeformer to a file you have already created, also run Codeformer locally and run it with same values'
3. Compare the outputs
4. See errors, issues and smooshyness  all over :) 

**Expected behavior**

For InvokeAI's Codeformer to behave the same as native CodeFormer running natively. Ideally give user option to select from any of the face detection models "retinaface_resnet50, retinaface_mobile0.25, YOLOv5l, YOLOv5n"

The below is mostly copied from > https://github.com/invoke-ai/InvokeAI/pull/1151 reposted here as it seems unrelated to that PR - Happy to provide more sample or help test out fixes.

-----------------------

InvokeAI's implementation of Codeformer is producing some really ugly output compared to CodeFormer running on my Mac locally. 

Here's my initial test image:
![001818 660639083](https://user-images.githubusercontent.com/110998208/196669976-5600d387-388b-4ae5-957f-359bd61f0aea.png)

Here is the output from Invoke/CodeFormer with Strength 1 and Fidelity 0
_(if I understand this right and please correct me if I don't - 'strength' is the % Invoke blends the CF output with the original image, so 1 should be 100% CF output and 0% original - Fidelity is the w slider in CF,  w=0 should be the same as Fidelity 0 and should be best quality output but less coherent to the original source image)_
The poor girl has some serious jaundice going on, overall the face now looks compressed / upsampled and is smooshy
![001999 660639083 postprocessed](https://user-images.githubusercontent.com/110998208/196674179-d19cf3c9-2cb0-401f-a3ad-9cca24f937a8.png)

Here is the output from Invoke/CodeFormer with Strength 1 and Fidelity 1 for reference. 
Jaundice is gone but now it's very compressed / upsampled and smooshed looking
![002002 660639083 postprocessed](https://user-images.githubusercontent.com/110998208/196674284-6965c27b-e067-4e24-a142-5be21e8a55bb.png)

Here's my local CodeFormer output using a selection of w=0 values and all 4 face detection models. I can't seem to replicate what is happening with the InvokeAI CF instance at all. Perhaps the Invoke version of CF is using an old model, or doesn't include all the new additions specific to high res faces in CF now? I checked codeformer.pth and it's the same version as my local install.

First the 2 high res face detection models: retinaface_resnet50 and YOLOv5l at w 0, upscale= 1
001818.660639083-w0-retinaface_resnet50-faceupsample
![001818 660639083-w0-retinaface_resnet50-faceupsample](https://user-images.githubusercontent.com/110998208/196674599-2984603d-cff8-4fcf-bb18-49fa84c8eff3.png)

001818.660639083-w0-YOLOv5l-faceupsample
![001818 660639083-w0-YOLOv5l-faceupsample](https://user-images.githubusercontent.com/110998208/196675246-637011ca-8d77-4eae-adf2-fc8e6729b17f.png)

Then the 2 low res face detection models, again at w0 and upscale=1 
001818.660639083-w0-retinaface_mobile0.25_resnet-faceupsample
![001818 660639083-w0-retinaface_mobile0 25_resnet-faceupsample](https://user-images.githubusercontent.com/110998208/196674650-a5a715a8-e4a1-4029-b6ef-9615c227d00e.png)

001818.660639083-w0-YOLOv5n-faceupsample
![001818 660639083-w0-YOLOv5n-faceupsample](https://user-images.githubusercontent.com/110998208/196675394-17f487b6-e212-4690-856a-5acadd1622e8.png)

You may find it easier to download each image, or open in a new tab and cycle through them to see the differences. But all are visibly better than the InvokeAI CF output. Overall the results from the Invoke CF instance are not correct when compared to CF ran locally.  

Another slightly smaller face example, with a much more 'damaged' face:
Original
![001954 2305962182](https://user-images.githubusercontent.com/110998208/196679039-9e949749-0cb6-4b0a-a44f-45fc2e15494c.png)

Invoke CF Str 1, Fid 0 -  This does look better at first then you notice she's now badly cross-eyed. 
![002001 2305962182 postprocessed](https://user-images.githubusercontent.com/110998208/196679069-48f8237c-7e3e-484c-9be1-cfa1e69e902c.png)

And now 2 versions using resnet50 and YOLOv5l - both are a huge improvement over the InvokeAI implementation and neither has dramatically crossed her eyes. 

001954.2305962182-w0-retinaface_resnet50-faceupsample
![001954 2305962182-w0-retinaface_resnet50-faceupsample](https://user-images.githubusercontent.com/110998208/196679146-6eb18563-b233-4b5f-98c8-ca6ddcc7fbd9.png)

001954.2305962182-w0-YOLOv5l-faceupsample
![001954 2305962182-w0-YOLOv5l-faceupsample](https://user-images.githubusercontent.com/110998208/196679171-bbc27e3f-9925-47d9-b587-2ada34252dbb.png)

**Comment by discordinated** [comment]
Tagging @lstein at @hipsterusername request too!

**Comment by lstein** [comment]
@blessedcoolant, you're the person who understands the face restoration code the best. Could you look into this bug report when you have a chance? It must just be the matter of a missing parameter to the call to codeformer somewhere.

**Comment by psychedelicious** [comment]
I believe I have fixed this in https://github.com/invoke-ai/InvokeAI/pull/1175

**Comment by blessedcoolant** [comment]
> I believe I have fixed this in #1175

Yep. Seems good to go.

**Comment by psychedelicious** [comment]
We have a confirmation from JoshuaKimsey on discord that our results now match other implementations, cool! I am closing this as resolved as the issue was pretty clear-cut.

**Comment by sanaullah494** [comment]
![20240220_030609](https://github.com/invoke-ai/InvokeAI/assets/138400477/8a9cc75c-7fed-4bbe-9180-72b69d9e8c7b)
