### ISSUE TITLE
Useful error messages

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#1173]
Our error messages aren't particularly informative much of the time. Sometimes, we don't raise errors, but just print messages to the console, prevent consumers of our code from being able to catch the error and handle it. 

A really consistent system for dealing with error conditions will be very useful. This is probably a large project. Just making an issue while I'm thinking about it.

**Comment by damian0815** [comment]
this is going to be necessary for giving robust user feedback about prompt syntax errors or ambiguities (cf #1108)

**Comment by psychedelicious** [comment]
We've improved this substantially.
