### ISSUE TITLE
Can we obtain the prompt(s) clipseg would respond to for a given image?

### ISSUE THREAD

**Issue by Any-Winter-4079** [invoke-ai/InvokeAI#1180]
I have the following image, and I'm trying to replace the face (including hair) with a Textual Inversion embedding face (about which, by the way, I'll say clipseg seems to work much better for TI than txt2img and img2img -don't know the reason yet).

![000399 2535887212](https://user-images.githubusercontent.com/50542132/196815622-fcaf8400-323c-4523-aae1-228a22593081.png)

Anyway, I can replace either face or hair but not both (at the same time). I've also tried man, kid, boy, anime boy, etc. but in these cases `-tm` does not do anything and returns the initial image.

Is there a way to obtain what prompt would be required for clipseg to replace the entire character?

**Comment by psychedelicious** [comment]
I don't have an answer to the question for now, but in the future I would like to implement (txt2)mask compositing. So you provide "face" and "hair" and can stack the resultant masks into one.

**Comment by lstein** [comment]
Yes, I have just added a new CLI command called `!mask`. It will generate three different images that shows you what `clipseg` has identified and how it will be thresholded into a mask.

**Comment by Any-Winter-4079** [comment]
Testing the new feature, I get:
`!mask outputs/new/000427.2535887212.png -tm "face"`
Deselected | Masked | Selected
<img width="370" alt="image" src="https://user-images.githubusercontent.com/50542132/196968494-8d2790b1-b527-4026-be61-0a0a7123260b.png">
But I still need to guess `face` is the keyword I should pass to `-tm`, don't I?

PS: Reminder that `self.model.embedding_manager.load` is necessary to use embeddings. (vs not using `self`).

**Comment by lstein** [comment]
The deal here is that `clipseg` produces a continuous scale of confidence
scores for each patch. The confidence scores are mapped onto the alpha
channel of the semi-transparent images on the left and right. To convert
this into a mask for inpainting, you have to choose a threshold confidence
value. Patches that equal or exceed this value are then converted into
black for the inpaint mask.

It's annoying that you can't just pass this mask to inpainting directly and
have to run `clipseg` again, but the code doesn't currently accept a
monochrome image as the mask. This is pretty easy to fix and I'll implement
it over the next couple of days.

Lincoln

**Comment by lstein** [comment]
> PS: Reminder that self.model.embedding_manager.load is necessary to use
> embeddings. (vs not using self).
>

Is there an unmerged PR with this fix?

Lincoln

**Comment by lstein** [comment]
It's done.

**Comment by lstein** [comment]
> Testing the new feature, I get: `!mask outputs/new/000427.2535887212.png -tm "face"` Deselected | Masked | Selected <img alt="image" width="370" src="https://user-images.githubusercontent.com/50542132/196968494-8d2790b1-b527-4026-be61-0a0a7123260b.png"> But I still need to guess `face` is the keyword I should pass to `-tm`, don't I? For example, I still don't know what keyword (if any) can allow me to select the whole character (including hair) unless by trial and error.
> 
> PS: Reminder that using `self.model.embedding_manager.load` in `generate.py` is necessary to use embeddings. (vs not using `self`). This fix is on main but not on dev right now.

Yes, you have to guess what prompt to use to select the whole character. However, it is pretty good at language, and you can use fairly natural language such as "the boy", "the character" or "the background". For example, one of the clipseg demos selects a cup and a jar with the phrase "fluid containers"
