### ISSUE TITLE
Web UI: Unable to reach gallery buttons if image has no metadata

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#1182]
Demo:
https://user-images.githubusercontent.com/4822129/196907164-a34e8e91-ab8d-4f6d-9b5b-7cd4e229d1cd.mov

I don't really like the placement of the tooltip buttons, maybe we can re-design this better along the way.

The more I think about it, the more I like the idea of context menus. We can implement a long-press for those when we roll out mobile design, and then can fit more actions in the menu. For the gallery specifically, the delete button should hover in the corner of the image so you can rapidly delete many images, but the other functions can be behind a context menu.

**Comment by hipsterusername** [comment]
You just need to move your mouse faster! ;) 

Agree, I think there are a couple of redesign options. These buttons are particularly difficult to use at larger resolutions
