### ISSUE TITLE
Txt2Img generation error when using ksampler

### ISSUE THREAD

**Issue by wfng92** [invoke-ai/InvokeAI#1183]
**Describe your environment**
- GPU: [cuda]
- VRAM: [12GB]
- CPU arch: [x86]
- OS: [Linux]
- Python: [3.9 (via `pip install`)]
- Branch: [Main]
- Commit: [90d37eac034592cc3aed5a15a98971801b21988e (HEAD -> main, tag: v2.0.2, origin/main, origin/HEAD)]

**Describe the bug**
Multiple errors when running image generation concurrently.

**To Reproduce**
Use the following script to run image generation in threads:

```python
from ldm.generate import Generate
import concurrent.futures
import logging

# load model
gr = Generate('stable-diffusion-1.4')
gr.load_model()

PROMPTS = ['a photo of a dog', 'a beautiful landscape', 'a potrait of a woman']


def run_generation(prompt):
    results = gr.prompt2image(
        prompt=prompt,
        sampler_name='k_lms',
        steps=15,
        iterations=4,
        width=512,
        height=512
    )
    seeds = []

    for row in results:
        im   = row[0]
        seed = row[1]
        # im.save(f'{prompt}-{seed}.jpg')
        seeds.append(seed)

    return {'prompt': prompt, 'seeds': seeds}


with concurrent.futures.ThreadPoolExecutor(max_workers=3) as executor:
    future_func = {executor.submit(run_generation, prompt): prompt for prompt in PROMPTS}
    for future in concurrent.futures.as_completed(future_func):
        try:
            data = future.result()
            print(data)
        except Exception:
            logging.exception('Error')
```

**Expected behavior**

Generate images concurrently without error.

**Screenshots**

Here is the error log from my console:

```
Traceback (most recent call last):
  File "/stable-diffusion/./test.py", line 34, in inference
    predictions = self.t2i.prompt2image(**config_dict)
  File "/stable-diffusion/./ldm/generate.py", line 426, in prompt2image
    results = generator.generate(
  File "/stable-diffusion/./ldm/invoke/generator/base.py", line 79, in generate
    image = make_image(x_T)
  File "/usr/local/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/stable-diffusion/./ldm/invoke/generator/txt2img.py", line 37, in make_image
    samples, _ = sampler.sample(
  File "/usr/local/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/stable-diffusion/./ldm/models/diffusion/ksampler.py", line 207, in sample
    K.sampling.__dict__[f'sample_{self.schedule}'](
  File "/usr/local/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/stable-diffusion/src/k-diffusion/k_diffusion/sampling.py", line 187, in sample_lms
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/stable-diffusion/./ldm/models/diffusion/ksampler.py", line 41, in forward
    uncond, cond = self.inner_model(x_in, sigma_in, cond=cond_in).chunk(2)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/stable-diffusion/./ldm/models/diffusion/ddpm.py", line 1270, in forward
    return self.p_losses(x, c, t, *args, **kwargs)
TypeError: p_losses() got multiple values for argument 'cond'
```

Another issue in the log (occurred at different times)
```
Traceback (most recent call last):
  File "/stable-diffusion/./test.py", line 34, in inference
    predictions = self.t2i.prompt2image(**config_dict)
  File "/stable-diffusion/./ldm/generate.py", line 426, in prompt2image
    results = generator.generate(
  File "/stable-diffusion/./ldm/invoke/generator/base.py", line 79, in generate
    image = make_image(x_T)
  File "/usr/local/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/stable-diffusion/./ldm/invoke/generator/txt2img.py", line 35, in make_image
    sampler.make_schedule(ddim_num_steps=steps, ddim_eta=ddim_eta, verbose=False)
  File "/stable-diffusion/./ldm/models/diffusion/ksampler.py", line 82, in make_schedule
    self.model  = outer_model.inner_model
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LatentDiffusion' object has no attribute 'inner_model'
```

There is also another error related to sigma.

**Additional context**

**Comment by lstein** [comment]
I hope this doesn't turn out to be a problem with concurrency, but sounds like it might be. A couple questions:

- Is the web server running multiple concurrent threads or processes?
- Have you ever observed the behavior with one of the older samplers?
- There seem to be two types of error message in the log. Are these occurring together at the same time as you're showing, or were they occurring at different times in the log?

**Comment by wfng92** [comment]
* Is the web server running multiple concurrent threads or processes?
I am running a single instance of FastAPI server. I have a POST route with `def` instead of `async def`. If I understand correctly, FastAPI will run the application using threads:

> When you declare a path operation function with normal def instead of async def, it is run in an external threadpool that is then awaited, instead of being called directly (as it would block the server)

* Have you ever observed the behavior with one of the older samplers?
For version 1.4, I used `k_euler` for txt2img and `ddim` for img2img. There was no issue at all. From version 2 onward, I used `k_lms` for both txt2img and img2img. 

* There seem to be two types of error message in the log. Are these occurring together at the same time as you're showing, or were they occurring at different times in the log?
The errors occurred at different times in the log. I will edit the post above to reflect this.

The first error seems to be happens [when a keyword argument is specified that overwrites a positional argument](https://stackoverflow.com/a/21765286)

```python
def add(x, y):
    return x + y


print(add(1, 2))
# 3
print(add(1, 2, x=1))
# add() got multiple values for argument 'x'
print(add(1, 2, y=2))
# add() got multiple values for argument 'y'
print(add(1, x=1, y=2))
# add() got multiple values for argument 'x'
```

The second error seems to be about `outer_model` not having an attribute called `inner_model`. Is there any model/memory cleanup somewhere in the code? When porting to new version, I noticed that model caching mechanism and model switching are added in as new features. Not sure if they are related to the issues.

**Comment by lstein** [comment]
What is bothersome is that neither of these errors should be stochastic.
They either happen every time (due to a coding error), or they never
happen.  I don't know exactly how or why this would happen, but perhaps the
environment is contaminated with one or more modules from a previous
version of InvokeAI, and some threads are picking up the older version.

This will be a pain, but would you be willing to delete the `invokeai`
environment entirely and rebuild?

**Comment by wfng92** [comment]
Sure, I will rebuild the environment and do another round of test this weekend. So far, not able to reproduce the errors.

Upon digging through the code, I realized that under `ldm/models/diffusion/ddpm.py` file, there are two classes with the `p_losses` function that accepts different input parameters.

```python
class DDPM(pl.LightningModule):
    ...

    def p_losses(self, x_start, t, noise=None):


class LatentDiffusion(DDPM):
    ...

    def p_losses(self, x_start, cond, t, noise=None):
```

I guess the first error occurs in `ldm/models/diffusion/ksampler.py`, the code under the `CFGDenoiser` class (line 41)

```python
uncond, cond = self.inner_model(x_in, sigma_in, cond=cond_in).chunk(2)
```

will raise the multiple values for argument `cond` error as

```
x_in => x_start
sigma_in => cond
cond_in => cond (multiple values for argument `cond`)
```

**Comment by wfng92** [comment]
I have updated the top post with detailed explanation on the actual problem. I am now able to reproduce the error using the following script which run image generation using 3 workers in threads:

```python
from ldm.generate import Generate
import concurrent.futures
import logging

# load model
gr = Generate('stable-diffusion-1.4')
gr.load_model()

PROMPTS = ['a photo of a dog', 'a beautiful landscape', 'a potrait of a woman']


def run_generation(prompt):
    results = gr.prompt2image(
        prompt=prompt,
        sampler_name='k_lms',
        steps=15,
        iterations=4,
        width=512,
        height=512
    )
    seeds = []

    for row in results:
        im   = row[0]
        seed = row[1]
        # im.save(f'{prompt}-{seed}.jpg')
        seeds.append(seed)

    return {'prompt': prompt, 'seeds': seeds}


with concurrent.futures.ThreadPoolExecutor(max_workers=3) as executor:
    future_func = {executor.submit(run_generation, prompt): prompt for prompt in PROMPTS}
    for future in concurrent.futures.as_completed(future_func):
        try:
            data = future.result()
            print(data)
        except Exception:
            logging.exception('Error')
```

The script may work without issue sometimes. Run it a few times and you should see the same errors as above.
