### ISSUE TITLE
Threshold use case?

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#1188]
Hi, using WebUI, I don't see threshold doing anything... what would be a noticeable use case?

**Comment by psychedelicious** [comment]
Some reading material in the original PR: https://github.com/invoke-ai/InvokeAI/pull/395

And a summary here in the docs: https://invoke-ai.github.io/InvokeAI/features/OTHER/#thresholding-and-perlin-noise-initialization-options

@pbaylies , can you advise on reasonable threshold values? My understanding - likely far off base - is that it basically clamps the vectors in the latent space to certain ranges. So I am guessing that there is a range of useful values for this, and if you set it too far in one direction, few to none of the vectors ever are clamped, so it doesn't do anything.

**Comment by pbaylies** [comment]
@psychedelicious that's accurate; @Neosettler first, what optimizer are you using? In my experience this works best with k-euler-ancestral or k-dpm-2-a. If you look at the image in the docs, you can see that by the time you get up to a threshold of 100, it's doing very little, whereas I'd say a value of 1 or below is probably too extreme. Typically the sweet spot should be around 5 to 10, but it will depend on the other parameters as well.

**Comment by Neosettler** [comment]
@pbaylies thank you for your inputs, at time of testing I used kmls but I'll try the Euler sampler if that makes a difference. Note that the webui allows a [0-1000] range so I might have missed the spot by a big margin if the sweet spot is at 5-10.

**Comment by psychedelicious** [comment]
We plan to improve the web ui to indicate the typically useful values of each parameter, as well as the technically valid values, to help prevent situations like this were the vast majority of valid values are kinda irrelevant. 

@pbaylies , is the max value of threshold (1000) chosen because that matches the max magnitude value of the vectors?

**Comment by pbaylies** [comment]
@psychedelicious empirically at 100 it's sometimes still possible to see some differences between the thresholded value and no threshold; at 1000 typically you'll see no difference. This is a value that would probably make more intuitive sense on a logarithmic scale.

**Comment by psychedelicious** [comment]
@pbaylies Might adjust the presentation of the value to the end-user to be on a log scale - at least, will add a tooltip suggesting reasonable values. Thanks!
