### ISSUE TITLE
Can't !import_model: [WinError 183]

### ISSUE THREAD

**Issue by theRolento** [invoke-ai/InvokeAI#1191]
I'm trying to import the two new Runway SD 1.5 ckpts but unsuccessfully:

```
FileExistsError: [WinError 183] Impossibile creare un file, se il file esiste già: './configs\\new_config.tmp' ->
'./configs/models.yaml'
```
Translating: Impossible to create a file, if the file already exist.

**Comment by psychedelicious** [comment]
@theRolento Sorry for the late response here. I believe our updated model loading handles this sitaution.

@lstein , Do we correctly handle this situation now?

**Comment by theRolento** [comment]
> @theRolento Sorry for the late response here. I believe our updated model loading handles this sitaution.
> 
> @lstein , Do we correctly handle this situation now?

Don't worry, yeah as of today everything works correctly

**Comment by psychedelicious** [comment]
Good to hear, thanks for letting me know.
