### ISSUE TITLE
Where to keep models / .gitignore for models

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#1192]
Currently, I think most users are keeping their model files in whatever location on disk, and creating symlinks to the `models/ldm/something/` directory.

With the new model switching features and the 1.5 weights release, I suppose we need to provide either:
- clarity on where to store models if it's not within the repo directories
- a solution for .gitignore

Comments/questions:
- In the `models.yaml` file, can / should we specify absolute file paths? E.g. If I keep all my models in `/My/Model/Folder/` (an absolute path, outside the repo dirs), can / should I directly reference that? Or do I need symlinks?
- What if we had a dir `models/ldm/user/` or something like that, which is .gitignore'd, and all model-related files downloaded externally are put there?
- Now that we have a second official checkpoint, we need to help users to migrate to it, or add it as a secondary model.

**Comment by tildebyte** [comment]
Then there's the issue of custom 'models.yaml' and/or e.g. 'configs\stable-diffusion\v14-inference.yaml', which aren't in .gitignore

**Comment by psychedelicious** [comment]
This is more or less resolved by the recent changes to the repo folder structure.
