### ISSUE TITLE
Web UI: Handling for different models in UI

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#1193]
- The UI doesn't display the current model in the metadata viewer
- How do we handle using all parameters, if the model is different? Do we load the model? What if the model no longer exists? Hmm.

**Comment by blessedcoolant** [comment]
We try and load the model. If the model does not exist, maybe we should just throw an error ... ? Because I don't think defaulting to the standard sd 1.4 will work in all cases. Esp if the image was generated with something that wasn't based on sd 1.4?

**Comment by psychedelicious** [comment]
Model switching is implemented in #1225 but the metadata handling isn't updated. This is partially complete; WIP.

**Comment by psychedelicious** [comment]
The metadata part of this is fixed, but I don't think we take any action on model-switching on use all. The last thing I want is to click use all have to wait however long for a model to load every time. Closing as implemented.
