### ISSUE TITLE
Add Prompt-To-Prompt Image Editing funtion into pipeline?

### ISSUE THREAD

**Issue by xpeng** [invoke-ai/InvokeAI#1196]
Recently, [Prompt-to-Prompt Image Editing with Cross-Attention Control](https://prompt-to-prompt.github.io/) from Google Research has [opensourced](https://github.com/google/prompt-to-prompt/), this can make the edits are controlled by text only!

Also they implemented it on stable diffusion.

Let's move more closer to Tower of Babel.

**Comment by lstein** [comment]
We are already working hard on this.

**Comment by xpeng** [comment]
Haha, i knew it
