### ISSUE TITLE
outpaint   !fix 1.png --out_direction top 64   error

### ISSUE THREAD

**Issue by Cyx-0** [invoke-ai/InvokeAI#1197]
Traceback (most recent call last):
  File "/Users/jc/InvokeAI/scripts/invoke.py", line 516, in do_postprocess
    gen.apply_postprocessor(
  File "/Users/jc/InvokeAI/ldm/generate.py", line 517, in apply_postprocessor
    seed   = args.seed
AttributeError: 'NoneType' object has no attribute 'seed'

**Comment by lstein** [comment]
Sorry you've found a bug. Could you fill out the bug report template so I know what branch you experienced this on, the platform, and so forth?

**Comment by lstein** [comment]
I'm pretty sure that outcropping will not work as expected if the original prompt and seed cannot be recovered, because there won't be any guidance to fill in the missing parts. I will just end up generating an error message and refusing to proceed.

**Comment by psychedelicious** [comment]
@lstein I think you may be misunderstanding. The greater issue is that any !fix command tries to get a seed. Maybe it makes sense to bail out with outcropping if no seed is available. 

But Gfpgan, codeformer, esrgan all break if there is no seed in metadata or a number in the file name. They should not.

**Comment by lstein** [comment]
I addressed these issues in #1207 and #1204.
