### ISSUE TITLE
InvokeAI running off CPU by default instead of GPU, how to switch?

### ISSUE THREAD

**Issue by TheExodus90** [invoke-ai/InvokeAI#1202]
**Describe your environment**
- GPU: cuda
- VRAM: 8gb
- OS: Windows
- Python: Anaconda

I recently updated to version 2.02 I deleted my previous install and started fresh install with Anaconda which I think caused me more headaches than if I had just updated it but eventually got it to run however it seems to be running off my CPU by default. 

Is there a command or something that I can use to switch it to my GPU ?(Cuda, 1080ti) it was working fine in all previous versions.

* Initializing, be patient...
>> GFPGAN Initialized
>> CodeFormer Initialized
>> ESRGAN Initialized
>> Using device_type cpu
>> Loading stable-diffusion-1.4 from models/ldm/stable-diffusion-v1/model.ckpt

**Comment by TheExodus90** [comment]
OK I think I finally managed to fix this thanks to a comment by another helpful user, apparently something has gone wrong with pytorch installation during the setup so it needed to be removed and reinstalled. 

first I ran 

pip uninstall torch

than 
pew new --python 3.10 -r requirements-lin-win-colab-CUDA.txt invokeai

**Comment by THEGOLDENPRO** [comment]
I have the same problem but with my Rx570 are AMD cards not supported?
