### ISSUE TITLE
Settings not persisting between client reloads

### ISSUE THREAD

**Issue by Fortyseven** [invoke-ai/InvokeAI#1203]
**Describe your environment**
- GPU: Nvidia 3090
- VRAM: 24gb
- CPU arch: x86
- OS: Ubuntu 22.04
- Browser: Firefox 106.0
- Python: venv/3.10.6
- Branch: `development`
- Commit: `a127eef`

**Describe the bug**

On page refresh, all UI settings are lost. 

I noticed `redux-persist failed to create sync storage. falling back to noop storage.` in the console.

**Comment by psychedelicious** [comment]
Can you please try with a clean profile? https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles

**Comment by Fortyseven** [comment]
Good call. No error there. Settings save.

I'll dig deeper on my end and see what's going on. When it's solved, I'll report back in case... whatever it is... happens again to someone else. :P 

Closing this for now. :ok_hand:

**Comment by Fortyseven** [comment]
**UPDATE:** Looks like something got hosed in the localStorage json blobs, and instead of a more specific error, `redux-persist` just threw up it's hands and bailed, throwing the `failed to create sync storage` error.


For others who might have this happen to them, here's how to fix it on Firefox:

### OPTIONAL TO TRY:
- I wish I'd tried "**Reset Web UI**" in Settings before going nuclear, but I have a feeling it wouldn't have worked. (I attempted to recreate the bug and actually _try_ it, but no dice. :sweat_smile:)

### WHAT I _ACTUALLY_ DID:
- Open devtools (F12)
- Select the Storage tab
- Along the left side, open the "Local Storage" dropdown
- For me, it's the `http://localhost:9090` entry, YMMV, but right click on that and select "Delete All".
- Close devtools and reload the page
- Enjoy persistent settings

The procedure on Chrome is more or less the same thing. Use the force.

**Comment by Fortyseven** [comment]
**UPDATE:** Had this happen again after a recent push to `development` and no, the _Reset Web UI_ function does not fix the issue. Only clearing `localStorage` does the trick, as described.

**Comment by psychedelicious** [comment]
I had done some looking to figure out why this might happen, but most references to this error were related to React Native applications on iOS, which is not this app, or were bugs with previous versions of `redux-persist`.

I suspect that Reset Web UI doesn't work because it uses the library which is throwing the error (`redux-persist`) to clear localstorage. When that button *does* work, the end result is that localstorage is cleared out. 

I haven't heard any reports of this error before, and am not sure how to replicated it on my end; I'll have to do some looking again when I get some time for a deeper dive. Reopening.

**Comment by Fortyseven** [comment]
I've had it happen a couple times since; usually after syncing up with the latest `development`, but I'm not 100% sure about that.

When I check out the contents of localStorage the data that remains clearly was from an hour or two prior (and I just hadn't hit reload since then). When it happens again, I'll drill down into it and look for anything like errant quotes or whatever. I bet json serialized _inside of_ a parent json property probably has some weird edge cases. :smirk:  (Though you'd think that would have been tripped over long before I showed up.)

Anyway, I'll try and more proactively poke it with a sharp stick and see if I can narrow it down...

**Comment by psychedelicious** [comment]
@Fortyseven has this continued happening for you?

**Comment by Fortyseven** [comment]
@psychedelicious Only ever so rarely. Enough where I forget about it, and can't remember the last time it happened. 

Which sounds like a long way around to saying 'no', but I'm only committing about 99% to that response. I'll ping about if I notice it again. :sunglasses:
