### ISSUE TITLE
Kaoss-pad-like UI for tweening between and around prompts.

### ISSUE THREAD

**Issue by damian0815** [invoke-ai/InvokeAI#1205]
Sometimes the image you want is between two or more prompts. Or perhaps you just want to go for a wander in feature space without having to deal with language.

This is a feature request for a Kaoss-pad-like interface for exploring feature space. You first generate a collection images using different prompts but the same seed, CFG scale, size, and sampler. Select a subset (2-4) of these images in the gallery, activate the feature, and you get a square frame with your thumbnail versions of your selected images evenly positioned on it, and a dot somewhere indicating where you are. 

You can drag the dot to move it towards or away from the different prompts, triggering image generations for the point where the dot currently is, taking blend weights from the distance between the different images. Move the dot on top of image A and you get image A; move it halfway between image A and image B and you get a 50:50 blend of prompt A and prompt B. 

## Advanced:
* You can also move the dot beyond the plane/line defined by the tween to explore the latent space on either side and outside of it. 
* You can zoom in to move about in finer increments through a smaller region of the feature space. 
Probably the advanced stuff would require #993.

**Comment by psychedelicious** [comment]
I'm having trouble imagining how to do this with 4 images... wouldn't that need a 4D visualization?

**Comment by damian0815** [comment]
Depends on how the math is done. actually you might be right, perhaps best to restrict it to 3 - or just accept that it won't be possible to blend between the two points opposite each other on the plane.

**Comment by wawiesel** [comment]
Hi all, new to this project and subscribed and this looked interesting. Is it well-defined how to created a weighted image between an arbitrary number of prompts? If so, you can create an N dimensional space based on N+1 unique prompts. Another idea is to consider the base prompt the origin, and all other N prompts define a space using img2img where a 1 gets you the prompt at the end of the dimension and 0 gets you the origin. Order would matter, i.e. the first dimension is resolved first before moving along the second dimension.
