### ISSUE TITLE
sd-1.5 checkpoint is out

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#1206]
Definitely feels like Christmas!

Regarding the definitions below:

sd-v1-5.ckpt: Resumed from sd-v1-2.ckpt. 595k steps at resolution 512x512 on "laion-aesthetics v2 5+" and 10% dropping of the text-conditioning to improve classifier-free guidance sampling.

sd-v1-5-inpaint.ckpt: Resumed from sd-v1-2.ckpt. 595k steps at resolution 512x512 on "laion-aesthetics v2 5+" and 10% dropping of the text-conditioning to improve classifier-free guidance sampling. Then 440k steps of inpainting training at resolution 512x512 on “laion-aesthetics v2 5+” and 10% dropping of the text-conditioning. For inpainting, the UNet has 5 additional input channels (4 for the encoded masked-image and 1 for the mask itself) whose weights were zero-initialized after restoring the non-inpainting checkpoint. During training, we generate synthetic masks and in 25% mask everything.

First, is it fair to assume that there is no difference in using either of those checkpoints if not using inpainting?

Second, is there any additional work to be done to handle the UNet has 5 additional input channels? 

NOTE: Initial testing show error "missing keys" while loading the 1.5 inpainting model.

**Comment by lstein** [comment]
The sd-v1-5.ckpt will work. Just drop it in.

The inpaint version will not, because additional coding work is needed to accomodate the new channels. Offers of help gratefully accepted!

**Comment by db3000** [comment]
See https://github.com/invoke-ai/InvokeAI/issues/1184 for discussion of sd 1.5 inpainting model support.

**Comment by wescrockett** [comment]
Noob question... how do we download the ckpt file?

**Comment by psychedelicious** [comment]
@wescrockett Sorry for the late response - you have a few options for downloading ckpt files: https://invoke-ai.github.io/InvokeAI/installation/INSTALLING_MODELS/

If you have any issues, please hop onto our discord https://discord.gg/ZmtBAhwWhy for help
