### ISSUE TITLE
(WEB) Indicate configs such as model on web info on interface 

### ISSUE THREAD

**Issue by Perryman** [invoke-ai/InvokeAI#1219]
**Is your feature request related to a problem? Please describe.**
With the release of 1.5 and features coming such as https://github.com/invoke-ai/InvokeAI/pull/1216, there is no clear way to see or select what model something was generated on, without manually examining the exifdata of the generated photo.

**Describe the solution you'd like**
I would like the info display on the web interface to indicate what model or any other configurations you expect would be related, in order to clearly tell how each image was generated. Additionally, a means to change to different yaml configurations in the web interface is also desirable.

**Describe alternatives you've considered**
Looking in the exifdata on the command-line interface is the current workaround.

**Additional context**
Please consider future developments/evolution in models/weights/autoencoders

**Comment by psychedelicious** [comment]
Resolved in pending v2.2 release - we have a drop-down for model switching right on the app header now. Also model is in metadata viewer.
