### ISSUE TITLE
(WEB UI) no easy method to scroll through invocations

### ISSUE THREAD

**Issue by Perryman** [invoke-ai/InvokeAI#1220]
**Is your feature request related to a problem? Please describe.**
When using the web interface, I often have hundreds or thousands of variations that I'm scrolling through, but there doesn't seem to be a scroll-bar or other means to quickly navigate the pane.

**Describe the solution you'd like**
Ideally, there would be a thin scroll-bar on the right.

**Describe alternatives you've considered**
The mouse wheel works, but still takes a long time to get to the desired area.
Even when expanding the pane to have more images to show, it can still take 15-30 seconds to get to the image I want to click on.
Clicking the mouse wheel doesn't seem to activate a scroll feature.
Clicking in the background or on a picture then pressing pgup/pgdn doesn't seem to work.

**Additional context**
The only way I've fixed this is periodically cleaning up the folder and moving it to a sub-folder. Perhaps some sort of folder structure might be ideal, but I'm not sure what the best long-term ux goal would be.

**Comment by psychedelicious** [comment]
Currently the scrollbars are hidden because the different across OSes was making our UI redesign a pain.

We are brainstorming ideas for improving the gallery functionality at the UI level and will resolve this when we action that.
