### ISSUE TITLE
How to gr.prompt2png() with with REAL-esrgan upscaling

### ISSUE THREAD

**Issue by rc2000123** [invoke-ai/InvokeAI#1230]
I'm trying to pipeline my tasks of inputing a prompt -> generate image -> upscale with Real-esrgan. How do I do this in the code? I don't see any documentation for this.
Code as Follows:

from ldm.generate import Generate
gr = Generate('stable-diffusion-1.4')
# do the slow model initialization
gr.load_model()
results = gr.prompt2png(prompt   = "an astronaut riding a horse"
                           outdir   = "./outputs/", upscale = "??")

**Comment by rc2000123** [comment]
this is for the Simplified API section of the documentation

**Comment by lstein** [comment]
You need to do a little initialization of the Restoration module, and then you pass the returned `esrgan` object to `Generate()`:

~~~
from ldm.generate import Generate
from ldm.invoke.restoration import Restoration

gr  = Generate('stable-diffusion-1.5',
               esrgan = Restoration().load_esrgan(),
)		

gr.load_model()

results = gr.prompt2png(
    prompt = "an astronaut riding a horse",
    outdir = "./outputs/",
    upscale = [2,0.8]
)

print(results)
~~~

`upscale` takes a two element array. The first element is the scaling factor (e.g. 2 for 2x) and the second is the upscale strength.

**Comment by lstein** [comment]
I'd add that recipes for upscaling and face restoration should be added to the documentation.

**Comment by psychedelicious** [comment]
No response, closing
