### ISSUE TITLE
Github workflows failing

### ISSUE THREAD

**Issue by lstein** [invoke-ai/InvokeAI#1231]
Since Sunday Oct 23, the GitHub automated CI workflows have been failing for both Ubuntu and Mac. The error is:

~~~
Run # Note, can't "activate" via github action; specifying the env's python has the same effect
[14](https://github.com/invoke-ai/InvokeAI/actions/runs/3309855901/jobs/5463446055#step:11:15)
/home/runner/work/_temp/78d16a7c-349b-4408-a4be-9d0be15318b3.sh: line 9: /usr/share/miniconda/envs/ldm/bin/python: No such file or directory
~~~

Is this a transient problem?

**Comment by tildebyte** [comment]
[#1128](https://github.com/invoke-ai/InvokeAI/pull/1128) needs to be cherry-picked to 'development', for one thing.

**Comment by lstein** [comment]
There are >140 commits in #1128 . That's a lot of cherries to pick!

**Comment by lstein** [comment]
> Since Sunday Oct 23, the GitHub automated CI workflows have been failing for both Ubuntu and Mac. The error is:
> 
> ```
> Run # Note, can't "activate" via github action; specifying the env's python has the same effect
> [14](https://github.com/invoke-ai/InvokeAI/actions/runs/3309855901/jobs/5463446055#step:11:15)
> /home/runner/work/_temp/78d16a7c-349b-4408-a4be-9d0be15318b3.sh: line 9: /usr/share/miniconda/envs/ldm/bin/python: No such file or directory
> ```
> 
> Is this a transient problem?

Hi @mauwii, it looks like some of the fixes you applied to `main` need to be moved over to `development`. I wonder if there is a particular commit that will address this problem?

**Comment by mauwii** [comment]
@lstein sorry, but it was more like split into a lot of commits 🙈 PR can be found here #1128

**Comment by tildebyte** [comment]
@lstein; Honestly, given the history, the least stroke-inducing thing to do is just copy the content of the files in .github from 'main' to 'development'

**Comment by mauwii** [comment]
may I ask why there is this difference between development and main, I'm more used to dev beeing ahead of main and getting merged from time to time.
But the State of the main and dev here prevent some changes from beeing done to dev which is causing even more trouble then 🤔

**Comment by lstein** [comment]
If this won't break anything (copying .github) that's exactly what I'll do.

**Comment by mauwii** [comment]
why would you copy the whole .github folder, only copy `.github/test-invoke-conda.yml`

**Comment by tildebyte** [comment]
We have FR and Bug Report; some people literally delete all of the template and just type whatever.
