### ISSUE TITLE
My Mac's eGPU(RX 6600XT 8G)was performing poorly,  and iterating at the same speed as the other Win10(GTX 960M 4G)

### ISSUE THREAD

**Issue by FreeBlues** [invoke-ai/InvokeAI#1232]
My Mac's eGPU(RX 6600XT 8G)was performing poorly,  and iterating at the same speed as the other Win10(GTX 960M 4G)

**Describe your environment**
- GPU: [eGPU] eGPU Radeon Rx 6600xt
- VRAM: [8G]
- CPU arch: [x86] macbookpro 2020, Intel Core i5, 32G ram
- OS: [macOS] Monterey 12.6
- Python: [miniconda3]
- Branch: [main]
- Commit: [230de023]

**Describe the bug**
I have two old computer:
-    macbookpro 2020: Intel CPU, 32G Ram, eGPU(Rx6600XT 8G)
-    win10:Intel i7-6700HQ, 16G Ram, GeForce GTX 960M 4G

My Mac's eGPU(RX 6600XT)was performing poorly,  and iterating at the same speed as the other Win10(gtx960m)

The same task：to generate a 512*512 pic, ddim, 20 steps.
The speed of both machines is about 4~5 s/it.
On the win10, GPU usage can reach 100% ,
On the mac, GPU usage is basically less than 20%.

My guess is that there must be some bottleneck on the Mac that is affecting the performance of the GPU.

Has anyone had a similar problem?  Any suggestions  Thanks!

The log on mac:

```
>> Image generation requested: {'prompt': 'profile shot of rimuru tempest, sky blue straight hair, long bangs, gold eyes, wearing a black jacket with white stripes, high collar, ultra detailed, stunning visuals, digital painting, cinematic, wlop, artgerm, pixiv, yoshitaka amano, greg rutkowski, ilya kuvshinov, andy warhol ', 'iterations': 3, 'steps': 20, 'cfg_scale': 12, 'threshold': 0, 'perlin': 0, 'height': 512, 'width': 512, 'sampler_name': 'ddim', 'seed': [3035424052](tel:3035424052), 'seamless': False, 'progress_images': False, 'variation_amount': 0}
ESRGAN parameters: False
GFPGAN parameters: False
>> Setting Sampler to ddim
/Users/ppt/Github/InvokeAI/ldm/modules/embedding_manager.py:155: UserWarning: The operator 'aten::nonzero' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at  /Users/runner/miniforge3/conda-bld/pytorch-recipe_1660136156773/work/aten/src/ATen/mps/MPSFallback.mm:11.)
  placeholder_idx = torch.where(
DDIMSampler: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [01:31<00:00,  4.59s/it]
>> Image generated: "/Users/ppt/Github/InvokeAI/outputs/img-samples/001182.3035424052.png"███████████████████████| 20/20 [01:31<00:00,  4.85s/it]
DDIMSampler: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [01:33<00:00,  4.66s/it]
>> Image generated: "/Users/ppt/Github/InvokeAI/outputs/img-samples/001183.2687597253.png"███████████████████████| 20/20 [01:33<00:00,  4.96s/it]
DDIMSampler: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [01:35<00:00,  4.75s/it]
>> Image generated: "/Users/ppt/Github/InvokeAI/outputs/img-samples/001184.1405132977.png"███████████████████████| 20/20 [01:35<00:00,  4.79s/it]
Generating: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [04:42<00:00, 94.30s/it]
>> Usage stats:
>>   3 image(s) generated in 284.30s
```

**Comment by tildebyte** [comment]
Answer is right there in your initial output: "The operator 'aten::nonzero' is not currently supported on the MPS backend and will fall back to run on the CPU"

AFAIU, you should *not* be seeing the MPS backend in use, unless your GPU is not NVIDIA (which I suspect is the case here). 
AFAIU, there's no ROCM (i.e. AMD GPU) support for Intel macs (but I could be wrong).

**Comment by FreeBlues** [comment]
The weirder thing is: when I set the size to 256*256, the usage of GPU become 20%.


-    set size to 256*256

![E3AC5838-A77B-45D9-9B40-369D87ED39FF](https://user-images.githubusercontent.com/3386551/197583073-a114065b-3ad3-4d32-a28c-4b018def234f.jpeg)


```
>> Image generation requested: {'prompt': 'Emma watson, portrait, colorful and vibrant majestic, royal, open wide eyes, drops of tear with flowers on her hair, glowing light orbs, intricate concept art, elegant, digital painting, smooth, sharp focus, ethereal opalescent mist, outrun, vaporware, cyberpunk darksynth, ethereal, ominous, misty, 8 k, by ruan jia and miho hirano, rendered in octane ', 'iterations': 3, 'steps': 20, 'cfg_scale': 12, 'threshold': 0, 'perlin': 0, 'height': 256, 'width': 256, 'sampler_name': 'ddim', 'seed': [1270492392](tel:1270492392), 'seamless': False, 'progress_images': False, 'variation_amount': 0}
ESRGAN parameters: False
GFPGAN parameters: False
DDIMSampler: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:10<00:00,  1.94it/s]
>> Image generated: "/Users/ppt/Github/InvokeAI/outputs/img-samples/001206.1270492392.png"███████████████████████| 20/20 [00:10<00:00,  2.24it/s]
DDIMSampler: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:10<00:00,  1.97it/s]
>> Image generated: "/Users/ppt/Github/InvokeAI/outputs/img-samples/001207.1401410822.png"███████████████████████| 20/20 [00:10<00:00,  2.07it/s]
DDIMSampler: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:09<00:00,  2.07it/s]
>> Image generated: "/Users/ppt/Github/InvokeAI/outputs/img-samples/001208.2235104688.png"███████████████████████| 20/20 [00:09<00:00,  2.05it/s]
Generating: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:30<00:00, 10.32s/it]
>> Usage stats:
>>   3 image(s) generated in 31.60s
```

**Comment by FreeBlues** [comment]
> Answer is right there in your initial output: "The operator 'aten::nonzero' is not currently supported on the MPS backend and will fall back to run on the CPU"
> 
> AFAIU, you should _not_ be seeing the MPS backend in use, unless your GPU is not NVIDIA (which I suspect is the case here). AFAIU, there's no ROCM (i.e. AMD GPU) support for Intel macs (but I could be wrong).

Thank you for explaining that the `aten::nonzero` problem should be one of the bottlenecks. My external graphics card is AMD Radeon RX 6600XT, and it should be working, because if I don't use the external graphics card, just use the CPU, speed will be reduced by more than 50% , about 10~15 s/it.

I guess there are other bottlenecks besides `aten::nonzero`.

**Comment by Vargol** [comment]
You might want to see if you've been hit be the MPS tuning mostly being geared towards Apple Silicon Owners.

I suspect your 8gb VRAM may be being treated in the same way as a 8Gb M1..

In this file
`ldm/modules/attention.py`

around line 199 is this function 

```
    def einsum_op_mps_v2(self, q, k, v):
        if self.mem_total_gb > 8 and q.shape[1] <= 4096:
            return self.einsum_op_compvis(q, k, v)
        else:
            return self.einsum_op_slice_0(q, k, v, 1)

```
Try changing the 1 in the last line to a 2 and see what happens, it'll use more memory to do the same maths in less steps if it is being called. It will affect your ability to do higher resolutions as  side effect though. Potentially you should be calling einsum_op_mps_v1, bur that was designed for 32gb M1 and higher.

**Comment by FreeBlues** [comment]
@Vargol Thank you for your information. I changed the number to 2, but there is no change.
Your suggestion reminds me that I should take a closer look at the code so that it is possible to find an optimization.
