### ISSUE TITLE
Web UI invocations aspect ratio

### ISSUE THREAD

**Issue by whosawhatsis** [invoke-ai/InvokeAI#1237]
I just updated to the most recent development branch. Previously, the web UI showed the full images in the list of invocations, with portrait mode images taller and landscape ones smaller, so that the widths were all equal.

This sometimes led to weirdness with mixed aspect ratios, where older images could end up several rows higher than a newer one, depending on the aspect ratios of the images above. In the new version, all images are cropped to a square, often cutting off important details (like faces!).

While I understand the motivation behind the new behavior, I would really prefer to have the old one back. Could this perhaps be made an option in settings?

**Comment by psychedelicious** [comment]
We reverted this not only because it made there order off images difficult it discern but it also caused performance issues.

We can explore making it an option as we improve the gallery. 

The 2.1 release, which is just around the corner, includes the first round of gallery improvements.

**Comment by whosawhatsis** [comment]
I saw those performance issues in recent versions, but the performance didn't seem to be that bad in the earliest versions with the variable aspect ratio thumbnails.

Anyway, while I'd still like to be able to scroll through the list and be able to see the full images (and see what their aspect ratio is) as I scroll past, another idea would be to show the whole image (letting it expand to cover part of the adjacent images) on mouse-over.

**Comment by psychedelicious** [comment]
Have considered this - another option would be to, on hover, change the image into a kind of zoomed window into the image, where moving the mouse around in the square moves the displayed, zoomed portion of the image. 

Which would you prefer?

The problem with the aspect ratio maintaining layout (called a masonry style layout) is it uses JavaScript to calculate the sizes of things. This caused some lag in chromium and ff, but absolutely destroyed safari. It gets worse when you have thousands of images of course. 

That said, I figured out another performance impacting thing for safari and fixed it - so maybe the masonry library will work better now?

After the inpainting release I'll investigate.

**Comment by whosawhatsis** [comment]
Cool, thanks.

As to your question about preference, while the zoomed portion of the image idea would be an improvement in that it would make it possible to see the cropped-out portions, It doesn't solve the problem of seeing what the aspect ratio is. Personally, I would prefer to expand-out the image so that the whole thing is visible.

Another thought, while the masonry layout definitely looks nicer, just having an option to scale the images down to fit inside the thumbnails rather than cropping them to squares would be a useful improvement for my use case.

**Comment by psychedelicious** [comment]
The aspect ratio toggle is implemented in the 2.1 web UI branch. It's not masonry - will leave adding that as an option for a future.

**Comment by whosawhatsis** [comment]
Thanks for adding that option. I'm using it and appreciate it. One thing that might make it more usable, without needing to implement the masonry version, would be to make each image use the full width of the box (like in the masonry version), but just let the height of the tallest image in each row determine the height of that row. This way you would still have a grid (which, in some ways, makes it MORE useful than masonry), but the rows would be variable height, and each image would be as large as possible for the row width specified in the settings. Theoretically, it would only take a minor CSS tweak...

**Comment by psychedelicious** [comment]
Just added the single-column layout option. Will be released in v2.2.
