### ISSUE TITLE
--log_tokenization crashes when the prompt includes non-ASCII characters

### ISSUE THREAD

**Issue by n00mkrad** [invoke-ai/InvokeAI#1240]
**Describe the bug**
CLI crashes when `-t` aka `--log_tokenization` is used and certain foreign characters are in the prompt, for example `Dalí`.

**To Reproduce**
1. Start CLI
2. Generate using command `Dalí -t`
4. See error: `UnicodeEncodeError: 'charmap' codec can't encode character '\u0143' in position 57: character maps to <undefined>`

**Comment by damian0815** [comment]
thanks for the bug report. @lstein this is actually worse in current dev (`Dalí` will not even parse). fixed in 0ddb08a5d77b404ff61f1c426a8e72e98094487f on the `prompt-tweaks` branch.

**Comment by psychedelicious** [comment]
Fixed in #1276
