### ISSUE TITLE
Config file for default args

### ISSUE THREAD

**Issue by KerbalTheGathering** [invoke-ai/InvokeAI#1245]
**Is your feature request related to a problem? Please describe.**
I don't like needing to change the args on the command line.

**Describe the solution you'd like**
I'd like to be able to set default args in a config file.

**Describe alternatives you've considered**
Copy/pasting in and out of a Visual Studio Code window.

**Comment by lstein** [comment]
Yes, it's on the list of small quality of life enhancements.

**Comment by psychedelicious** [comment]
We now have this :)
