### ISSUE TITLE
Images have slightly changed (txt2img)

### ISSUE THREAD

**Issue by Any-Winter-4079** [invoke-ai/InvokeAI#1254]
We should investigate and discover when this change was introduced (and what was changed) now that it is recent. Whether we revert back or not the samplers behavior, this affects reproducibility, so I think it's important to at least know what was modified (and document it).

Example:

### 1.4
`!switch stable-diffusion-1.4`
`"an anime girl" -s 50 -S 3031912972 -W 512 -H 512 -C 7.5 --fnformat {prefix}.{seed}.png -A plms`
<img width="490" alt="image" src="https://user-images.githubusercontent.com/50542132/197848070-7043a8b1-70ab-4bc6-a0a7-9f8af9ff1938.png">

DDIM
`"an anime girl" -s 50 -S 3031912972 -W 512 -H 512 -C 7.5 --fnformat {prefix}.{seed}.png -A ddim`
<img width="493" alt="image" src="https://user-images.githubusercontent.com/50542132/197848159-26f99e3b-4ac5-4ac2-ad9f-17a3b52677b8.png">

Discovered in https://github.com/invoke-ai/InvokeAI/pull/1243#issuecomment-1290949456

**Comment by lstein** [comment]
Looks like a change in steps. Could you see if adding or removing a step converts a new image into an older one?  Have you tested the k samplers too?

**Comment by wfng92** [comment]
Not sure if related but the community solution PR to fix index out of bound for DDIM sampler #1137 will remove 1 step from the final `ddim_timesteps`. The error mostly happens when `num_ddim_timesteps % 3 == 0`. Perhaps the code can be further optimized and do removal only when (step is multiple of 3). However, I assume this only affects DDIM sampler and not the rest.

**Comment by Any-Winter-4079** [comment]
Indeed. https://github.com/invoke-ai/InvokeAI/pull/1137 is the PR that introduced this change.
<img width="634" alt="image" src="https://user-images.githubusercontent.com/50542132/198386126-2e421c2a-9760-4bac-80d6-f860eee792e0.png">
Personally, I am fine with the slightly modified behavior. But at least it was nice to know when this was introduced, and document it here, in case someone wants the old behavior.
