### ISSUE TITLE
"use prompt" button

### ISSUE THREAD

**Issue by whosawhatsis** [invoke-ai/InvokeAI#1260]
Along with the "use all" and "use seed" buttons in the webui, it would be nice to have a "use prompt" button that would copy only the prompt from the selected image.

I know I can click on details and dig the prompt out of the metadata, but it's annoying to do, and I often find myself clicking the "use all" button, then changing all of the settings below to what I was using before.

**Comment by whosawhatsis** [comment]
Context menu should be fine

**Comment by psychedelicious** [comment]
We have added this in 2.1, Use Prompt is now a main current-image button. It's also in the gallery image context menu.
