### ISSUE TITLE
outdir in websocket

### ISSUE THREAD

**Issue by svumme** [invoke-ai/InvokeAI#1263]
I am working on a UXP panel for photoshop, which connects via websocket, it would be very useful for me to have --outdir as a parameter and not at the start of the script.
Another question . Is it currently possible to use codeformer with the websocket? 
i used these parameters
var facefix= {type:'codeformer',strength:1,codeformer_fidelity:1}
but gfpgan is always used for face restore

**Comment by psychedelicious** [comment]
Hi @svumme , what branch are you on? Codeformer is supported but I don't think its in main yet. 

Regarding the API, we have a major overhaul on the way which will supersede the current socket.io API entirely. Your request would require a significant effort, so I don't think it's really feasible until the new API is released.

**Comment by svumme** [comment]
I'm running invoke.py with --web and then connecting with socket.io.client. I would like to know what the API changes will be about, to understand if it is I am doing useless work. My goal as I wrote to @hipsterusername   about the discord group is to release the plugin as part of invoke and make it free. But if for example you remove the server it is useless that I continue with this job

**Comment by psychedelicious** [comment]
I believe we continued this conversation on discord, please let me know if not.
