### ISSUE TITLE
Collapse invocations into stacks... ideas?

### ISSUE THREAD

**Issue by whosawhatsis** [invoke-ai/InvokeAI#1270]
When generating multiple images, I was thinking that it would be cool to have an option in the invocations panel to collapse images generated together into a folder or stack. This could make it easier to find old txt2img generations, but the real value it when generating variations or using img2img, both of which generate a lot of similar-looking images.

It's probably important to retain an option for the current flat, reverse chronological display, and that should likely remain the default. I don't have all of the answers about how this should look and feel, or what is the best way to display a thumbnail for these stacks. Maybe its a single thumbnail with a decoration that makes it looks like a pile of thumbnails (I'm envisioning something like the [stacks in macOS](https://www.macrumors.com/how-to/use-stacks-in-macos-mojave/), but something like a mini grid of the first 4 or 9 images might work better (similar to folders in iOS and Android) might work better.

Anyone else have ideas?

**Comment by psychedelicious** [comment]
@netsvetaev , a UX/UI designer and project contributor. Had this in prototype designs way back when I first started on the UI. I agree it's very useful, but this is almost a freebie with the node processing backend already, so I think it will wait until then.

**Comment by hipsterusername** [comment]
Boards in 3.0
