### ISSUE TITLE
masking to combine variations

### ISSUE THREAD

**Issue by whosawhatsis** [invoke-ai/InvokeAI#1271]
I was going to combine this with https://github.com/invoke-ai/InvokeAI/issues/1270, which would make it more useful, but I decided that they should really be considered and discussed separately.

This is also not something that I expect to happen on a short timescale, but it might be worth keeping in mind while developing some more immediate features, like inpainting.

A feature I would like to see is an interface for combining the best parts of different images when generating variations using the same seed, or when generating multiple images with an img2img prompt. I'm imagining layering two or more of these variations (which have identical compositions but different details) and using a soft masking brush to reveal parts of one behind the other. This would be useful, for example, for combining the subject in one variation with the background from another, or for quickly repairing a variation that sprouted an extra limb, but is otherwise superior to the others.

Now, the obvious way to do this is to take both images into Photoshop/GIMP, but they're kinda overkill for this use case. My computer also isn't the happiest about having both Photoshop and InvokeAI running at the same time, because both are extremely RAM-hungry. Most of the necessary stuff to make it work is already needed for the impainting interface, and it would be really convenient to be able to do it within the invokeai webui, then be able to drop that directly back to img2img to create new variations that will conceal the seams.

Thoughts?

**Comment by hipsterusername** [comment]
As variations have been removed, I'm going to close this one out.
