### ISSUE TITLE
!fix -c bottom 64 behaving poorly

### ISSUE THREAD

**Issue by Any-Winter-4079** [invoke-ai/InvokeAI#1275]
Can someone confirm this poor behavior? I recently pulled 7b46d5f823c39dbd9. Has it always been like this? Is it only on my Mac? Or has a bug been introduced recently?
`!fix outputs/new/000718.682777619.png -s 50 -S 682777619 -W 512 -H 512 -C 7.5 -A k_lms -c bottom 64`
Original (left) and two samples (right)
<img width="1619" alt="image" src="https://user-images.githubusercontent.com/50542132/198420294-0f94ed8b-ef54-48af-8287-fcd00741801e.png">

Working with a different model, it's even worse.
<img width="700" alt="image" src="https://user-images.githubusercontent.com/50542132/198420449-f0526c19-782e-4225-8113-de2fd5b912db.png">

Besides this, I get a `curly_extended.png` outside my output directory, which is not removed. This behavior comes from `outcrop.py` (line 114)

> extended_img.save('outputs/curly_extended.png')

<img width="458" alt="Screenshot 2022-10-28 at 02 13 37" src="https://user-images.githubusercontent.com/50542132/198420431-382a9b6c-b396-4357-8aef-656981cde71a.png">

**Comment by lstein** [comment]
I'll remove the unwanted debug statement (surprised you're the first person to notice the extra image), but may not have time for the next couple of days to improve the outcropping behavior.
