### ISSUE TITLE
Small heads up: Import time

### ISSUE THREAD

**Issue by spezialspezial** [invoke-ai/InvokeAI#1280]
Just a small heads up. I've noticed import times have gone up considerably when switching to the development branch. I did some tracing, maybe it's useful information.

main: invokeai -> 1.7702 s
development: invokeai -> 4.2775 s

a big chunk of this seems to be:

development: WeightedFrozenCLIPEmbedder -> 1.5763 s
development: CLIPTextModel -> 1.06 s

**Comment by Any-Winter-4079** [comment]
On M1, it has always taken me 5-6 seconds to load a model (caching the old one), except for 1.5 inpainting,  which takes around 15-17s.

**Comment by spezialspezial** [comment]
This was just pythonic library import timings. Loading the model comes on top of that with instantiate_from_config beeing the biggest chunk

OmegaConf.load(v1-inference.yaml)  ->  0.0166
read weights sd-v1-4.ckpt  ->  1.25
calc hash  ->  0.00238
torch.load weight_bytes  ->  1.13
instantiate_from_config LatentDiffusion  ->  5.76
model.load_state_dict  ->  0.289
model.to(self.device)  ->  0.373
model.eval()  ->  0.00193
Loading model took 8.828 seconds

The new model switching is kick ass btw.

**Comment by Vargol** [comment]
> On M1, it has always taken me 5-6 seconds to load a model

Something a get really jealous, it take a minute or so on my 8Gb.
