### ISSUE TITLE
InvokeAi Utilizes CPu instead of GPU on Google Cloud VM

### ISSUE THREAD

**Issue by SirToastalot** [invoke-ai/InvokeAI#1282]
**Describe your environment**
- GPU: Cuda 11.6, A100
- VRAM: 40GB
- CPU arch: [x86/arm]
- OS: Debian 10
- Python: Anaconda
- Branch: [if `git status` says anything other than "On branch main" paste it here]
- Commit: [run `git show` and paste the line that starts with "Merge" here]

**Describe the bug**
I am trying to run InvokeAI on Google Cloud VM. 
When setup the VM it asks if I want to install NVIDIA drivers, and installs 510.xx driver.
It then detects the card the Cuda and the driver version with the nvidia-smi command.

 nvidia-smi
Fri Oct 28 13:04:39 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P0    52W / 400W |      0MiB / 40960MiB |     27%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------

I then follow the instructions for installing InvokeAi.

When I launch InvokeAI I get this:

>> GFPGAN Initialized
>> CodeFormer Initialized
>> ESRGAN Initialized
>> Using device_type cpu
>> Loading stable-diffusion-1.4 from models/ldm/stable-diffusion-v1/model.ckpt
   | LatentDiffusion: Running in eps-prediction mode
   | DiffusionWrapper has 859.52 M params.
   | Making attention of type 'vanilla' with 512 in_channels
   | Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
   | Making attention of type 'vanilla' with 512 in_channels
   | Using more accurate float32 precision
>> Model loaded in 16.85s
>> Setting Sampler to k_lms

As you can see it starts on CPU instead of GPU. 

Could someone please help me fix this on a VM.
Runs fine on my desktop PC

**Comment by KeithDraws** [comment]
I have the same problem. IT was fine until I tried to install xformers. 
After pip install triton failed I uninstalled xfrmers since it would not work .
After this Invoke defaults to the CPU and even though I updated the drivers for the GPU  there is no change
