### ISSUE TITLE
[enhancement]: Pasting an initial image from clipboard

### ISSUE THREAD

**Issue by Fortyseven** [invoke-ai/InvokeAI#1286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

It would increase my workflow _immensely_ to be able to simply paste an image from the clipboard while on the _Image to Image_ tab. (And eventually with inpainting, etc.) 

This would make it easier to do quick one-off edits on images from the web without having to save to a temporary file.

**I would be willing to volunteer to work on this feature if nobody else is interested.** :sunglasses: 

### Alternatives

The current alternative is to save the image to a temporary file and load from the filesystem.

**Comment by psychedelicious** [comment]
Implemented in #1225

**Comment by Fortyseven** [comment]
I just might cry. Thank you. :smiling_face_with_tear: :beers:
