### ISSUE TITLE
[bug]: Using "-s 29" outputs "(steps > 29)"

### ISSUE THREAD

**Issue by ehammond** [invoke-ai/InvokeAI#1300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

n/a

### What happened?

On the latest `development` branch commit 39daa5a.

Using `-s 29`, output includes the following message even though 29 is not greater than 29:

```
>> Ksampler using model noise schedule (steps > 29)
>> Sampling with k_lms starting at step 0 of 29 (29 new sampling steps)
```

Note that `-s 28` does work correctly, so the problem is only with 29:

```
>> Ksampler using karras noise schedule (steps <= 29)
>> Sampling with k_lms starting at step 0 of 28 (28 new sampling steps)
```

Happy to provide more details about my environment, if needed.

**Comment by lstein** [comment]
Thanks for reporting the bug. I'm happy to see it is now fixed.
