### ISSUE TITLE
[bug]: Inpainting, unable to paint on touch devices

### ISSUE THREAD

**Issue by MarcusLlewellyn** [invoke-ai/InvokeAI#1311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24GB

### What happened?

When using the inpainting feature of the web UI, I am unable to draw the mask on a touch screen. It _does_ register a finger tap and draw a circle the size of the brush. But dragging a finger does not result in a paint stroke.

### Screenshots

![Screenshot_20221030-130711](https://user-images.githubusercontent.com/464056/198894335-1c8cc97e-ba2c-4f89-b8b4-e092fd221579.png)

### Additional context

I understand that mobile support is sort of on the back burner at the moment, but right now the web UI is pretty usable on tablets/chromebooks with touch screens. I tested this on the latest stable releases of Firefox and Chrome with identical results. 

### Contact Details

marcus.llewellyn#2923

**Comment by psychedelicious** [comment]
Shouldn't be a difficult addition, just need to think about edge cases a bit. I have an iPad to test it on so that makes it easier too.

**Comment by mikedg1** [comment]
Submitted this [PR](https://github.com/invoke-ai/InvokeAI/pulls)
If there's any specific edge cases to test, please let me know.

**Comment by Melodeiro** [comment]
> Submitted this [PR](https://github.com/invoke-ai/InvokeAI/pulls) If there's any specific edge cases to test, please let me know.

Link is not working anymore, and i don't have an installed dev version. Not sure how its implemented right now. Is it simple dragging? Double-tap then drag or tap and hold then drag might be good option. Or maybe a button to stop drawing. Up to you, ofc, just a reminder that on mobile devices (if thats eventually planned) you also need to scroll the page, and maybe drawing on a simple drag, will make scrolling troublesome. Especially if image is a vertical rectangle, and fills the whole screen:)

Btw right now its possible to use on mobile devices with small code adjustments, and unpinned side panels. A little bit tricky, but somehow works.
