### ISSUE TITLE
Does !fix work for images not generated by stable-diffusion

### ISSUE THREAD

**Issue by rc2000123** [invoke-ai/InvokeAI#1320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cpu

### What happened?

Is it possible to upscale images not generated by invokeai? I tried on an AI generated image and got good results, but when I used a image from an outside source I get this error:
Traceback (most recent call last):
  File "/stable-diffusion/scripts/invoke.py", line 516, in do_postprocess
    gen.apply_postprocessor(
  File "/stable-diffusion/ldm/generate.py", line 517, in apply_postprocessor
    seed   = args.seed
AttributeError: 'NoneType' object has no attribute 'seed'
### Screenshots

<img width="730" alt="image" src="https://user-images.githubusercontent.com/13386079/198964925-dbdcf4b9-fb01-4a52-99fa-80df0601afb0.png">

**Comment by FreeBlues** [comment]
I usually deal with the image with invokeai first, set the parameter to 0.01, then you can  get a highly similar image, now you can use !fix to upscale it.

As a suggestion: in the code of !fix, may add a procedure to check if the image is generated from invokeai or not:

-    true: do postprocess directly
-    false:
     -     use img2img to deal with it to get a highly similar image
     -     do postprocess

**Comment by psychedelicious** [comment]
Fixed by - I *think* - #1527 - maybe was a different PR.
