### ISSUE TITLE
[bug]: device_type defaulting to CPU instead of GPU

### ISSUE THREAD

**Issue by drzoidberg90** [invoke-ai/InvokeAI#1322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What happened?

Running default setup of invokeai using the Conda Install (https://invoke-ai.github.io/InvokeAI/installation/INSTALL_WINDOWS/).  Am able to successfully generate images but getting >>using device_type cpu.

```
(invokeai) C:\Users\user\InvokeAI>python scripts\invoke.py --web
* Initializing, be patient...
>> GFPGAN Initialized
>> CodeFormer Initialized
>> ESRGAN Initialized
**>> Using device_type cpu**
>> Loading stable-diffusion-1.4 from models/ldm/stable-diffusion-v1/model.ckpt
   | LatentDiffusion: Running in eps-prediction mode
   | DiffusionWrapper has 859.52 M params.
   | Making attention of type 'vanilla' with 512 in_channels
   | Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
   | Making attention of type 'vanilla' with 512 in_channels
NOTE: Redirects are currently not supported in Windows or MacOs.
   | Using more accurate float32 precision
>> Model loaded in 11.05s
>> Setting Sampler to k_lms
```

I have installed CUDA drivers from Nvidia, updated my GeForce to the latest drivers, and repulled from Git and rebuilt the environment after driver installation.  

Specs:

- Windows 11
- i7-10700k 
- 32GB RAM
- RTX 2070

**Comment by obgr** [comment]
I have the same issue. while following Arki's Guides.
https://stablediffusionguides.carrd.co/#invoke-ai

## OS
Windows
## GPU
cuda
## VRAM
8GB

Output:
```
$ python scripts/invoke.py --web
* Initializing, be patient...
>> GFPGAN Initialized
>> CodeFormer Initialized
>> ESRGAN Initialized
>> Using device_type cpu
>> Loading stable-diffusion-1.4 from models/ldm/stable-diffusion-v1/model.ckpt
   | LatentDiffusion: Running in eps-prediction mode
   | DiffusionWrapper has 859.52 M params.
   | Making attention of type 'vanilla' with 512 in_channels
   | Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
   | Making attention of type 'vanilla' with 512 in_channels
NOTE: Redirects are currently not supported in Windows or MacOs.
   | Using more accurate float32 precision
>> Model loaded in 10.47s
>> Setting Sampler to k_lms

* --web was specified, starting web server...
>> Started Invoke AI Web Server!
>> Default host address now 127.0.0.1 (localhost). Use --host 0.0.0.0 to bind any address.
>> Point your browser at http://127.0.0.1:9090
```

## Specs
Windows 11
Ryzen 5600x
32GB RAM
RTX 3070

**Comment by sveken** [comment]
Same issue here
Windows 11 22H2 
32GB RAM 
Ryzen 6900HS
Nvidia 3070 Ti 8GB

**Comment by UnicodeTreason** [comment]
Same root cause as https://github.com/invoke-ai/InvokeAI/issues/1264
Though the title on this Issue is superior.

I "fixed" mine by forcing the pip versions back to the known working ones:
https://github.com/invoke-ai/InvokeAI/issues/1264#issuecomment-1293572653

We need @mauwii or someone else to do a code change ;)

**Comment by phineas-pta** [comment]
> The #1264 method didn't work for me, but I am on Debian and could not find the file where I should replace SIGKILL, seems the file structure is different in linux?

for linux you have to find python library path, use `conda info --envs` to see path of the "invokeai" environment

you can then locate `lib/python3.10/site-packages/torch/distributed/elastic/timer/file_based_local_timer.py`

**Comment by sveken** [comment]
Can confirm the above work around worked, 
I had to delete and recreate the environment after but it is using cuda now.

**Comment by phineas-pta** [comment]
the newest commit fix the issue! tested on centos

**Comment by phineas-pta** [comment]
> You mean the new release?

the latest release just got out hours after my previous comment, you should try it

> Do I need to do a fresh reinstall of Invokeai?

for me yes, because i still got the problem in #1015

**Comment by psychedelicious** [comment]
lol glad it's working for you guys!
