### ISSUE TITLE
[bug]: Pytorch Lightning update error

### ISSUE THREAD

**Issue by cwallen** [invoke-ai/InvokeAI#1331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What happened?

On pip install this morning I'm getting:
`ImportError: cannot import name 'rank_zero_only' from 'pytorch_lightning.utilities.distributed'`

Looks related to the new release of pytorch lightning 1.8. 
We are pinned to 1.7.7 in environment.yml, adding that to requirements.txt as well seems to fix it.

I can make a PR later tonight if nobody beats me to it, but wanted to post incase someone else hits the same problem.

**Comment by lstein** [comment]
I'll just make the change. No need for a PR.

**Comment by Vargol** [comment]
Small issue, 
pytorch-lightning=1.7.7  is wrong should be pytorch-lightning==1.7.7
I'm creating a PR for requirements-mac-MPS-CPU.txt  
I'd had the fix in there if you like
