### ISSUE TITLE
[bug]: prompt weighting fails on high weight values

### ISSUE THREAD

**Issue by lstein** [invoke-ai/InvokeAI#1339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

32GB

### What happened?

"man picking (apricots)1.5" gives expected image of lots of apricots.

"man picking (apricots)5" gives noise

**Comment by lstein** [comment]
@damian0815 - is this a bug?

**Comment by damian0815** [comment]
you can think of it as turning the CFG up really high. 

it's not limited in the parser because at lower CFG the limit at which it breaks down is different.

**Comment by lstein** [comment]
Ok, then I'll close the issue
