### ISSUE TITLE
[bug]: Discord invite link on the website is invalid

### ISSUE THREAD

**Issue by virgildotcodes** [invoke-ai/InvokeAI#1346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### VRAM

Not relevant

### What happened?

This [Discord invite link](https://discord.com/invite/NwVCmKwY), found on [the website](https://invoke-ai.github.io/InvokeAI/), is invalid.

### Screenshots

<img width="993" alt="Screenshot 2022-11-02 at 3 44 57 AM" src="https://user-images.githubusercontent.com/16354900/199441695-02014576-80f0-4b99-9f87-fa38a3b62287.png">

**Comment by lstein** [comment]
The link is working for me, but I’m already a member.  Maybe it is a server config error?  Flagging @hipsterusername  for his attention.

**Comment by xan2622** [comment]
I confirm this "bug". The Discord link is invalid.
Maybe it has been created with a limit of the number people who can join ?

https://support.discord.com/hc/en-us/articles/208866998-Invites-101

**Comment by hipsterusername** [comment]
Someone updated the link from the original I posted. Should be correct from the in-app link as a short term. Will update readme shortly

**Comment by psychedelicious** [comment]
This is fixed.
