### ISSUE TITLE
[enhancement]: Moving to HuggingFace diffusers

### ISSUE THREAD

**Issue by bonlime** [invoke-ai/InvokeAI#1349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

First of all thanks for an impressive work of implementing so many features for SD generation. 

Right now your codebase uses origingal CompVis implementation. HuggingFace at the same time is rapidly developing their diffusers library which has better code quality than in CompVis, comes with tests and some performance improvements. For example they are almost done with FlashAttention PR which would greatly speed up SD up to 30%. Eventually it seems a better option to switch to a library being developed separately and continue building UI and features around it, rather than to try to incorporate all the features on your own. 

I've seen you mentioned @keturn being interested in moving to diffusers. Do you have it roadmap? If yes, what is the ETA? If no, how hard and large in your opinion would be the PR to move to diffusers?

**Comment by keturn** [comment]
There's a [discord thread](https://discord.com/channels/1020123559063990373/1031668022294884392) where we've been working out some of those details like where this goes on the roadmap.

I _think_ there's general agreement that we can start once 2.1 (currently in release-canditate phase) is released.

**Comment by bonlime** [comment]
Good news! Will close the issue then
