### ISSUE TITLE
[bug]: ResolvePackageNotFound: getpass_asterisk

### ISSUE THREAD

**Issue by DavidCWGA** [invoke-ai/InvokeAI#1354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### What happened?

The conda environment specifies a package called getpass_asterisk, which does not exist.

```
$ PIP_EXISTS_ACTION=w CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - getpass_asterisk
```

**Comment by heurihermilab** [comment]
Me too.  I've posted it to the Discord.

MacBook Pro 14", 16GB, M1 Pro CPU, using Conda on macOS Monterey (fully updated).

**Comment by emergel** [comment]
same

ResolvePackageNotFound: 
  - getpass_asterisk

**Comment by eelir** [comment]
Same here. Looks like the getpass_asterisk is not in conda repository. I tried to install it with pip and it did not work.

**Comment by shadowmint** [comment]
There's no issue with this from pip, it's just not in conda.

Apply the following diff and it'll work fine>

```
diff --git a/environment-mac.yml b/environment-mac.yml
index 0e0aae01..be2df480 100644
--- a/environment-mac.yml
+++ b/environment-mac.yml
@@ -1,4 +1,4 @@
-name: invokeai
+name: invokeai-dev3
 channels:
   - pytorch
   - conda-forge
@@ -22,7 +22,6 @@ dependencies:
   - diffusers=0.6.0
   - einops=0.4.1
   - grpcio=1.46.4
-  - getpass_asterisk
   - humanfriendly=10.0
   - imageio=2.21.2
   - imageio-ffmpeg=0.4.7
@@ -52,6 +51,7 @@ dependencies:
   - transformers=4.23.1
   - torch-fidelity=0.3.0
   - pip:
+      - getpass_asterisk
       - dependency_injector==4.40.0
       - realesrgan==0.2.5.0
       - test-tube==0.7.5
```

**Comment by eelir** [comment]
I can confirm @shadowmint 

I tried pip one more time and it did work.

**Comment by ventlam** [comment]
> There's no issue with this from pip, it's just not in conda.
> 
> Apply the following patch and it'll work fine.
> 
> ```
> diff --git a/environment-mac.yml b/environment-mac.yml
> index 0e0aae01..be2df480 100644
> --- a/environment-mac.yml
> +++ b/environment-mac.yml
> @@ -1,4 +1,4 @@
> -name: invokeai
> +name: invokeai-dev3
>  channels:
>    - pytorch
>    - conda-forge
> @@ -22,7 +22,6 @@ dependencies:
>    - diffusers=0.6.0
>    - einops=0.4.1
>    - grpcio=1.46.4
> -  - getpass_asterisk
>    - humanfriendly=10.0
>    - imageio=2.21.2
>    - imageio-ffmpeg=0.4.7
> @@ -52,6 +51,7 @@ dependencies:
>    - transformers=4.23.1
>    - torch-fidelity=0.3.0
>    - pip:
> +      - getpass_asterisk
>        - dependency_injector==4.40.0
>        - realesrgan==0.2.5.0
>        - test-tube==0.7.5
> ```

It works.

**Comment by lstein** [comment]
Sorry for that!  It is corrected in the latest commit. Please pull from main.
