### ISSUE TITLE
[bug]: Package Conflicts

### ISSUE THREAD

**Issue by wescrockett** [invoke-ai/InvokeAI#1364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

8GB

### What happened?

While compiling using docker, the following error occurs:

```
The conflict is caused by:
    realesrgan 0.3.0 depends on basicsr==1.4.1
    gfpgan 1.3.8 depends on basicsr>=1.4.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict


failed
Preloading Models....
Loading Python libraries...
```

I'm not sure where in the process this occurs (sorry, I am quite new to troubleshooting these types of issues.

### Screenshots

![image](https://user-images.githubusercontent.com/4974937/199825372-728d4cb6-8492-47b0-813e-83b46380c2b9.png)

### Additional context

Running as a Docker container on an Unraid server following this guide:
https://forums.unraid.net/topic/130172-guide-invokeai-fork-of-stable-diffusion-docker/

### Contact Details

wes.crockett@gmail.com

**Comment by lstein** [comment]
I believe this is fixed with the latest release. Could you pull from main and try again?

**Comment by wescrockett** [comment]
In looking at the other 2 repo's, they do appear to be looking for the same version. I wiped out my /env/ and /cache/ folders and am rebuilding now (though I have done this previously a few times in the past few hours. Will let you know asap.

**Comment by wescrockett** [comment]
Switched to non-dev branch and added a package to the dockerfile. now resolved.

**Comment by lstein** [comment]
I am making a PR with a revised requirements.txt file that may do the trick. I didn't read your post carefully enough and it escaped my attention that you were doing a docker build. Please advise when and if you test.

**Comment by wescrockett** [comment]
I can try spinning up a second instance on my machine and revert my dockerfile change. may help
