### ISSUE TITLE
[bug]: Attention parsing issue with hyphenated words

### ISSUE THREAD

**Issue by spezialspezial** [invoke-ai/InvokeAI#1366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

24

### What happened?

Attention modifier on hyphenated words like in **"detailed close-up+ portrait"** is not recognized during parsing. Not a big deal as **"detailed (close-up)+ portrait"** works as expected but good to know I guess.

**Comment by damian0815** [comment]
this has been fixed on the development branch in `e554c2607f00a5e51c03052acb9861ff21ec1c12`

**Comment by lstein** [comment]
The fix will also appear in point release 2.1.3, appearing in a day or two.
