### ISSUE TITLE
[bug]:Unable to run 'python scripts/invoke.py', SyntaxError: Missing parentheses in call to 'print' . Did you mean print(...)?

### ISSUE THREAD

**Issue by Ashes7154** [invoke-ai/InvokeAI#1370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What happened?

After I have followed all of the steps to install through conda, running the commands: `python scripts/invoke.py` or `python scripts/invoke.py --web` result in the following error:

> (invokeai) C:\Users\[My Name]\InvokeAI>python scripts/invoke.py
Traceback (most recent call last):
  File "C:\Users\[My Name]\InvokeAI\scripts\invoke.py", line 14, in <module>
    from ldm.invoke.prompt_parser import PromptParser
  File "C:\Users\[My Name]\AppData\Local\Programs\Python\Python310\lib\site-packages\ldm.py", line 20
    print self.face_rec_model_path
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

### Contact Details

devinppeterson@gmail.com

**Comment by damian0815** [comment]
@lstein any idea? looks to me as if user has a stale LDM (is that python 2 syntax?) no idea how to fix :/

**Comment by FreeBlues** [comment]
I got this error too, I think it is because of the Conda env of old version InvokeAI haven't cleaned correctly(maybe it assign the env name `invokeai` to something). You can try to use `conda remove --name yourOldEnv --all`, then your new version should work.

Or you use a different name of new env, not `invokeai`, it will disappear.

**Comment by Ashes7154** [comment]
> I got this error too, I think it is because of the Conda env of old version InvokeAI haven't cleaned correctly(maybe it assign the env name `invokeai` to something). You can try to use `conda remove --name yourOldEnv --all`, then your new version should work.
> 
> Or you use a different name of new env, not `invokeai`, the error will disappear.

It didn't seem to work, doing that just removed ldm and upon reinstalling it, the error came back.

**Comment by damian0815** [comment]
what happens if you do `PYTHONPATH=. python scripts/invoke.py`?

**Comment by Ashes7154** [comment]
> what happens if you do `PYTHONPATH=. python scripts/invoke.py`?

'PYTHONPATH' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Ashes7154** [comment]
As it turns out, my issue stemmed from the fact that while I was running the command `conda env create` I ran into an issue where chcp couldn't be found. To solve this, I had to edit the system environment variables, and add C:/Windows/System32 to my PATH. Once I did this, I deleted my InvokeAI directory and started the install process from the beginning, and everything works as intended
