### ISSUE TITLE
[bug]: Can't run web UI, model is a directory?

### ISSUE THREAD

**Issue by OrionFive** [invoke-ai/InvokeAI#1371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

I'm trying to run the web interface via Google Colab.

After entering
```
/content# cd InvokeAI
/content/InvokeAI# python scripts/invoke.py --web
```
I get the error you can see in the screenshot. It looks like it copies the model to the wrong place and then fails to find it. It did say the path was correct at the step where you enter the path.

### Screenshots

![image](https://user-images.githubusercontent.com/13980562/199974183-e926acfa-1fa6-4687-8632-cc40f2bac7cd.png)

**Comment by psychedelicious** [comment]
I don't think we support running the UI on Google Colab. It's a breach of their TOS. I'm not sure if we support the CLI either. Sorry, but I don't think we can help you here.

**Comment by OrionFive** [comment]
I just followed the link on your front page under features that says "Google Colab" and followed the instructions. I thought it couldn't get more official than that.

I didn't know Google's TOS didn't allow this, though.

**Comment by psychedelicious** [comment]
CLI is supported and that is what is in the instructions.

Our UI is requires you to run an HTTP/websocket server; it is against the TOS to run a server on Google Colab.

**Comment by OrionFive** [comment]
Ah, I see. Thanks for the explanation.
