### ISSUE TITLE
[enhancement]: Can I training Textual Inversion on Google Colab GPU?

### ISSUE THREAD

**Issue by TruongQuocTruong** [invoke-ai/InvokeAI#1375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

19522446@gm.uit.edu.vn

### What should this feature add?

The "Fine-tune Stable Diffusion using Textual Inversion" tutorial is very interesting. And now, I'm learning about the Latent Diffusion Models and trying to fine-tune styles; objects of Stable Diffusion. 
Unfortunately, I don't have enough hardware requirements for the training process. So, Can someone help me implement, and set up the environment on Google Colab to train Fine-tune? 
I appreciate that! Thanks a lot!

**Comment by psychedelicious** [comment]
@netsvetaev @damian0815 @hipsterusername 

Do any of you guys have any suggestions for running TI on colab?

**Comment by hipsterusername** [comment]
@psychedelicious - I think, generally, the advice for running Invoke's TI on colab would be "Wait until we update it". A number of users have had only unsuccessful attempts training, and there's active work going on to fix it.

@damian0815 would know better timeline for that

**Comment by netsvetaev** [comment]
I can try our notebook for dreambooth, and if it works in colab, will update docs. Maybe on Saturday.

**Comment by oxie** [comment]
Looking forward to using Colab as well with InvokeAI :) Can`t wait for the update as there is no other way for me to try InvokeAI UI
