### ISSUE TITLE
[Small bug]: copy link to image = wrong image

### ISSUE THREAD

**Issue by mickr777** [invoke-ai/InvokeAI#1379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12gb

### What happened?

Not a high priority  bug but thought I would mention:

- Using the new "copy link to image" always copies the link to the first image shown when the web ui was loaded, not the image you have selected. 

- If you create more images and then refresh the page the only image link it will copy again will be the first image that shows on the page after refreshing, irrelevant of what image you then select

- Tested on branch main and development

- Tested with chrome/edge on windows, chrome on android and firefox on linux

- Download image works as it should

**Comment by psychedelicious** [comment]
Thanks, the fix will be rolled out in #1355
