### ISSUE TITLE
[bug]: Downloading Weights Error, Bad Request

### ISSUE THREAD

**Issue by fartfartfarty** [invoke-ai/InvokeAI#1394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What happened?

I followed the [easy-peasy windows install](https://github.com/invoke-ai/InvokeAI/wiki/Easy-peasy-Windows-install). After running `python scripts/preload_models.py`, I followed the wizard, logged into my hugging face account, accepted the license agreements, and created a new token with role of read. After I paste my token into the installation wizard in powershell I get this output.
```
   Now copy the token to your clipboard and paste it here:
Password: *

** DOWNLOADING WEIGHTS **
** An error occurred during downloading v1-5-pruned-emaonly.ckpt: Bad Request
*** ERROR DOWNLOADING v1-5-pruned-emaonly.ckpt:
** An error occurred during downloading sd-v1-5-inpainting.ckpt: Bad Request
*** ERROR DOWNLOADING sd-v1-5-inpainting.ckpt:
** An error occurred during downloading vae-ft-mse-840000-ema-pruned.ckpt: Bad Request
*** ERROR DOWNLOADING vae-ft-mse-840000-ema-pruned.ckpt:


** There were errors downloading one or more files. **
Please double-check your license agreements, and your access token.
Press any key to try again. Type ^C to quit.
```
I tried creating another account, token, double checking that I agreed to the license but it doesn't work.

**Comment by FreeBlues** [comment]
Can you try it in a normal CMD, not powershell?
