### ISSUE TITLE
[enhancement]: Allow for mouse-wheel zooming when inpainting

### ISSUE THREAD

**Issue by Coreusa** [invoke-ai/InvokeAI#1395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

When the image is large, it's hard to paintbrush fine / smaller areas (i.e a face). It would be beneficial to support zooming of the image in question, so inpainting finer details is easier.

Apparently [there's a inprogress PR](https://github.com/invoke-ai/InvokeAI/pull/1126) implementing some of this, , but there aren't many updates.

Example:
![image](https://user-images.githubusercontent.com/706874/200186798-ac09a6b0-0a8f-4447-ae7c-d490aca859a6.png)
_large image, paint brush areas of replacing parts of the face is extremely hard to do or even see_

**Comment by psychedelicious** [comment]
This will be implemented in v2.2. #1355 is the PR to watch.
