### ISSUE TITLE
[enhancement]: Batch Generation?

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#1397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Greetings, 

if not already available out of the box, it would be a nice addition. 

[Sampler results](https://invoke-ai.github.io/InvokeAI/help/SAMPLER_CONVERGENCE/#sampler-results)

Note: Could anyone explain how to do those Sampler results/grid were made?

**Comment by psychedelicious** [comment]
I believe these were done manually. We have open requests for "matrix" outputs - I'll close this as a duplicate.
