### ISSUE TITLE
[enhancement]: Make inpainting on the CLI explicit with a flag

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#1401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Currently, inpainting is triggered when a check of the user's init image determines there are pixels with an alpha < 255.

This leads to unexpected situations where the init image has some partial transparency which is not obvious to the user when viewing the image. The user expects a standard img2img to happen, but instead, inpainting over the transparent areas occurs.

For example, a user had an image with 12 pixels that had alpha < 255. This resulted in img2img doing inpainting on those 12 pixels. The result was not distinguishable from the init image, so it appeared something was wrong.

A simple solution is to make inpainting explicit, and then instead of checking if the image has transparency, check to see if it does *not* have transparent areas, and alert the user if so (and there was no mask provided).

### Alternatives

Much much much more obvious warnings in the CLI when images have any transparency. This is not ideal because:
- if you want to do inpainting you already know that you have transparent areas
- terminal output is already pretty crowded and you may still miss it

**Comment by hipsterusername** [comment]
The other alternative would be to have an explicit argument that invoked w/ inpainting (similar to the above, but instead of just being a 'use inpainting' on an img2img invocation, completely separating the two into distinct args)

**Comment by n00mkrad** [comment]
+1

I really dislike how inpainting is automatically enabled/disabled right now.

**Comment by psychedelicious** [comment]
This is not relevant in v3
