### ISSUE TITLE
[bug]: RuntimeError: The size of tensor (on Development and release-candidate-2-1-3 Branch)

### ISSUE THREAD

**Issue by mickr777** [invoke-ai/InvokeAI#1403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12gb

### What happened?

starting with commit d05b1b3 on development and release-candidate-2-1-3 branch, on ubuntu 22.04 running cuda, it causes an error when using hires and fails to make image

happens just after the first smaller image its made as its about to change to the larger size it throw an error
(changing to the commit before this one it works normally)

Traceback (most recent call last):
File "/InvokeAI/ldm/generate.py", line 459, in prompt2image
results = generator.generate(
File "/InvokeAI/ldm/invoke/generator/base.py", line 90, in generate
image = make_image(x_T)
File "/opt/conda/envs/invokeai/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
return func(*args, **kwargs)
File "/InvokeAI/ldm/invoke/generator/txt2img2img.py", line 93, in make_image
z_enc = ddim_sampler.stochastic_encode(
File "/opt/conda/envs/invokeai/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
return func(*args, **kwargs)
File "/InvokeAI/ldm/models/diffusion/sampler.py", line 131, in stochastic_encode
extract_into_tensor(sqrt_alphas_cumprod, t, x0.shape) * x0
RuntimeError: The size of tensor a (88) must match the size of tensor b (96) at non-singleton dimension 3

**Comment by discordinated** [comment]
I was having this issue on Mac as well on the development branch. Main worked fine. I reinstalled from scratch and now have this issue too https://github.com/invoke-ai/InvokeAI/issues/1422

**Comment by discordinated** [comment]
In scripts/preload_models.py", line 503, and ldm/invoke/txt2mask.py , line 32

Swapped this line back

+ from clipseg_models.clipseg import CLIPDensePredT
- from clipseg.clipseg import CLIPDensePredT

And it seems to work again.

**Comment by lstein** [comment]
Is the bug still present? I cannot reproduce it.

**Comment by lstein** [comment]
Never mind. I was able to reproduce it on a different machine. I will revert the offending PR now.

**Comment by mickr777** [comment]
Fixed on development for me, but still happening on release-candidate-2-1-3

**Comment by tildebyte** [comment]
For posterity - this is not a MacOS issue; I have it on Windows as well

**Comment by lstein** [comment]
I've pulled the fix over from development into the release candidate and it will be OK for the release.
