### ISSUE TITLE
[bug]: models.yaml missing

### ISSUE THREAD

**Issue by krummrey** [invoke-ai/InvokeAI#1408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What happened?

When I try to start invoke.py or dream.py I get the following error:

```
* Initializing, be patient...
NOTE: Redirects are currently not supported in Windows or MacOs.
>> GFPGAN Initialized
>> CodeFormer Initialized
>> ESRGAN Initialized
[Errno 2] No such file or directory: '/Users/jan/Documents/ML/InvokeAI/configs/models.yaml'. Aborting.
```

### Additional context

Same error on main and development branch

**Comment by Vargol** [comment]
It's supposed to be written by the preload_models.py, but if you skip the hugging face stuff it doesn't.
I just rename the configs/models.yaml.example file

**Comment by krummrey** [comment]
It gets removed once I do a `git pull`. Maybe there's a better way to exclude it from the pull.

**Comment by lstein** [comment]
I do `git pull` a hundred times per day and have never lost the models.yaml file. Likely it only happened that once when updating from the previous revision, and a hundred apologies for this.
