### ISSUE TITLE
[enhancement]: Generate initial latents by running diffusion in reverse from an initial image (if metadata exists)

### ISSUE THREAD

**Issue by JPPhoto** [invoke-ai/InvokeAI#1413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

When doing img2img, add an option to generate initial latents by running diffusion in reverse from the initial image if metadata is present (or from a user-defined description).

See code in [`https://github.com/bloc97/CrossAttentionControl/blob/main/InverseCrossAttention_Release.ipynb`](https://github.com/bloc97/CrossAttentionControl/blob/main/InverseCrossAttention_Release.ipynb):

`gen_latents = inversestablediffusion(input_image, "a photo of a woman with blonde hair", refine_iterations=5, guidance_scale=4.0)`

The `inversestablediffusion` function has the magic sauce.

**Comment by damian0815** [comment]
this would make img2img considerably more usable for making refinements to an image - in intuitive terms the initial latent noise would be more inclined to cooperate with the user's intentions

**Comment by lstein** [comment]
How does one apply this in a workflow? Does it work like img2img except that there is an initial step of telling the inverse function what features of the initial image you're particular interested in keeping?

@damian0815 are you assigning yourself to work on this? Sounds like a handy feature.

**Comment by JPPhoto** [comment]
My take: I imagine this would be done just before the img2img step to create latents representing what the source image is of so they can be altered to something else via img2img. This is where we could lean on the metadata if the image were initially generated via InvokeAI or let the user type in `a Rastafarian cat` (for example) as the initial image text. I see all kinds of creative possibilities. _Note that it doesn't always make sense to do this step, which is why it should be optional in the img2img workflow._

**Comment by damian0815** [comment]
this is going to need UI support, as it functionally disables the seed and variations. perhaps that's where the prompt input would go? ping @blessedcoolant @psychedelicious

**Comment by psychedelicious** [comment]
I can't say I understand what this actually does, but it sounds cool.
