### ISSUE TITLE
[bug]: during generation, when using 'accurate' setting for image display, web UI crashes if cancel button is pressed

### ISSUE THREAD

**Issue by Perryman** [invoke-ai/InvokeAI#1416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What happened?

When using `accurate` setting for display in-progress images, the web UI crashes if the cancel button is pressed during generation.

### Screenshots

a black screen is generated. pressing refresh reloads the page

**Comment by lstein** [comment]
Thanks for the report. We'll look into it. The backend is still running after this crash and you just have to refresh the browser?

**Comment by Perryman** [comment]
yes, it just needs a refresh, similar to https://github.com/invoke-ai/InvokeAI/issues/1036

**Comment by psychedelicious** [comment]
Fix is integrated with v2.2 web ui.
