### ISSUE TITLE
[bug]: Mac Update Instructions for 2.1

### ISSUE THREAD

**Issue by wilsongoode** [invoke-ai/InvokeAI#1418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What happened?

The [update instructions](https://github.com/invoke-ai/InvokeAI/releases/tag/v2.1.2) for macOS currently include the following:
```
conda deactivate
git checkout main
git pull
rm -rf src
conda update -f environment-mac.yml
conda activate invokeai
python scripts/preload_models.py
```

This line fails: 
`conda update -f environment-mac.yml`

I believe it should be:
`conda env update -f environment-mac.yml`

I am not sure if this change should also be made for the other OSes.

**Comment by lstein** [comment]
This is fixed. Thank you for the report.
