### ISSUE TITLE
[bug]: ModuleNotFoundError: No module named 'clipseg' (commit 636620b Development Branch)

### ISSUE THREAD

**Issue by mickr777** [invoke-ai/InvokeAI#1422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12gb

### What happened?

the change in ldm/invoke/txt2mask.py on commit https://github.com/invoke-ai/InvokeAI/commit/636620b1d5e2466613d0dcc2a604522be12fa3a4 on ubuntu 22.04 for me
causes ModuleNotFoundError: No module named 'clipseg' again

```
- from clipseg_models.clipseg import CLIPDensePredT
+ from clipseg.clipseg import CLIPDensePredT
```
swaping it back made it work again for me.

**Comment by discordinated** [comment]
Same issue for me on Mac after a reinstall.

**Comment by FreeBlues** [comment]
@Any-Winter-4079 thank you! I changed the folder name and it is ok!
