### ISSUE TITLE
[enhancement]: Store output images to S3(-like) object storage

### ISSUE THREAD

**Issue by benqua** [invoke-ai/InvokeAI#1425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

It would be great to be able to store output images in a S3 object storage, like the one provided by AWS and other cloud providers.

**Comment by psychedelicious** [comment]
In the relatively near future, we will be migrating to a new backend and API which supports user-defined storage (or whatever) services. It is designed with exactly this kind of thing in mind. See #1047 for the current progress.
