### ISSUE TITLE
[bug]: Major performance regression (40% slower!) caused by an updated package

### ISSUE THREAD

**Issue by n00mkrad** [invoke-ai/InvokeAI#1426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24 GB

### What happened?

I synced my fork from 4104ac62709ab3ea2b5b2b876799a2b77592485f to 8b47c82992647d6caffe611305f5d30049fa8146.

I ran the exact same image generation test using CLI and found out the new/current code is much slower.

```
Old 2.21s => 0.4525 img/sec
New 3.58s => 0.2793 img/sec
```

This was the time to generate a single 512x512 image with k_euler_a, 30 steps, on an RTX 4090.

Will do further testing to see if the issue is an updated pip package or if the problem is on the repo side.

**Comment by n00mkrad** [comment]
Update - **Slowdown is caused by a package update, not by a repo commit!**

**Comment by n00mkrad** [comment]
I have not isolated the package yet, but it's one of the following updates:

`cudatoolkit 11.3 => 11.6`
`pytorch 1.11.0 => 1.12.1`
`torchvision 0.12.0 => 0.13.1`
`cudatoolkit 11.3 => 11.6`
`numpy 1.19.2 => 1.23.3`
`transformers 4.19.2 => 4.21.3`

**Comment by n00mkrad** [comment]
Problem seems to be caused by `cudatoolkit=11.6` instead of `11.3`.

**Comment by Fortyseven** [comment]
For what it's worth, I've also noticed this huge speed hit. I haven't been regularly updating packages when I pull down the latest `development` changes.  So if the version bump of that package had anything to do with it, that might be separate from what I'm experiencing.

I haven't had time to get too deep into it, but when I roll back **before** 178f0c7, it's as peppy as it used to be. Looks like that commit does quite a bit, including stuff related to VRAM usage.

So, for now, I'm pinning my local copy to 4b5a965 and I'll watch here and dip my toe into `development` once in a while until this gets resolved.

**Comment by lstein** [comment]
@damian0815 , if this is indeed an issue with high VRAM usage, could you have a look? I will investigate the cudatoolkit version issue.

**Comment by blessedcoolant** [comment]
Can confirm. There is definitely a huge slowdown in inference time on Windows. Trying to isolate the problem. Reverting the changes made by @damian0815 has not helped. Trying to downgrade Cudatoolkit to 11.3 without breaking everything else.

**Comment by blessedcoolant** [comment]
I've run some extensive tests. Neither @damian0815's PR nor reverting back to the old pytorch / cudatoolkit versions have show any considerable difference in the inference time. On my system I am lingering around 1.38/s per iteration at 512x768. There is no extra VRAM usage either.

Unfortunately I cannot recall how many iterations per second I used to get before. Apart from things "feeling" a tad bit slower, the numbers aren't matching up.

**Comment by Kyle0654** [comment]
My perf I think is about 4x slower than it used to be on my 3090. I only started hitting this today when I pulled the new UI branch that rebased on dev, so it should be something recent.

**Comment by blessedcoolant** [comment]
@damian0815 Disabling your recent VRAM PR gives me a slight boost in inference time. Went from 1.35 iterations / s to 1.5+/s

**Comment by Fortyseven** [comment]
For what it's worth, here's exactly what I'm seeing.

Commit: `4b5a965`:
```
>> Image generation requested: {'prompt': 'unclaimed tiny cluster of orange data floating in a crystal blue cyberspace, intricate detail, micro detailing, tron++ style cyberspace++++', 'iterations': 1, 'steps': 32, 'cfg_scale': 6, 'threshold': 0, 'perlin': 0, 'height': 512, 'width': 512, 'sampler_name': 'k_euler_a', 'seed': 2350822576, 'progress_images': False, 'progress_latents': True, 'save_intermediates': 1, 'seamless': False, 'hires_fix': False, 'variation_amount': 0}
>> Parsed prompt to FlattenedPrompt:[Fragment:'unclaimed tiny cluster of orange data floating in a crystal blue cyberspace, intricate detail, micro detailing,'@1.0, Fragment:'tron'@1.2100000000000002, Fragment:'style'@1.0, Fragment:'cyberspace'@1.4641000000000004]
Generating:   0%|                                                        | 0/1 [00:00<?, ?it/s]>> Ksampler using model noise schedule (steps >= 30)
>> Sampling with k_euler_ancestral starting at step 0 of 32 (32 new sampling steps)
100%|██████████████████████████████████████████████████████████| 32/32 [00:02<00:00, 12.61it/s]
>> Image generated: "/home/fortyseven/opt/ai/invoke-ai/outputs/img-samples/003168.ee389bd4.2350822576.png"
Generating: 100%|████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.76s/it]
>> Usage stats:
>>   1 image(s) generated in 2.82s
>>   Max VRAM used for this generation: 3.40G. Current VRAM utilization: 2.25G
>>   Max VRAM used since script start:  3.40G
```

Commit: `178f0c78`:

```
>> Image generation requested: {'prompt': 'unclaimed tiny cluster of orange data floating in a crystal blue cyberspace, intricate detail, micro detailing, tron++ style cyberspace++++', 'iterations': 1, 'steps': 32, 'cfg_scale': 6, 'threshold': 0, 'perlin': 0, 'height': 512, 'width': 512, 'sampler_name': 'k_euler_a', 'seed': 2350822576, 'progress_images': False, 'progress_latents': True, 'save_intermediates': 1, 'seamless': False, 'hires_fix': False, 'variation_amount': 0}
>> Setting Sampler to k_euler_a
>> Parsed prompt to FlattenedPrompt:[Fragment:'unclaimed tiny cluster of orange data floating in a crystal blue cyberspace, intricate detail, micro detailing,'@1.0, Fragment:'tron'@1.2100000000000002, Fragment:'style'@1.0, Fragment:'cyberspace'@1.4641000000000004]
Generating:   0%|                                                        | 0/1 [00:00<?, ?it/s]>> Ksampler using model noise schedule (steps >= 30)
>> Sampling with k_euler_ancestral starting at step 0 of 32 (32 new sampling steps)
100%|██████████████████████████████████████████████████████████| 32/32 [00:06<00:00,  5.01it/s]
>> Image generated: "/home/fortyseven/opt/ai/invoke-ai/outputs/img-samples/003169.7d10d9f3.2350822576.png"
Generating: 100%|████████████████████████████████████████████████| 1/1 [00:06<00:00,  6.59s/it]
>> Usage stats:
>>   1 image(s) generated in 7.03s
>>   Max VRAM used for this generation: 3.40G. Current VRAM utilization: 2.25G
>>   Max VRAM used since script start:  3.40G
```

**Comment by Kyle0654** [comment]
This line seems to be the culprit: https://github.com/invoke-ai/InvokeAI/blob/4b4111a802511d0916a1962a0dcbc456f5ebf2dd/ldm/modules/attention.py#L285

It doesn't impact the reported VRAM stats after generation if it's disabled (turning on the logging line, it didn't appear to impact memory much during generation either). I'm going to investigate a little further - I noticed some other lines that might be impacting perf... this already drops my generation time from 15s to 6s though.

**Comment by Kyle0654** [comment]
@damian0815 I noticed this, which moves things to cpu, but doesn't appear to be called anywhere in the code base:

https://github.com/invoke-ai/InvokeAI/blob/4b4111a802511d0916a1962a0dcbc456f5ebf2dd/ldm/models/diffusion/cross_attention_control.py#L156

There's also this, but I'm guessing it's necessary when you want to save things?

https://github.com/invoke-ai/InvokeAI/blob/4b4111a802511d0916a1962a0dcbc456f5ebf2dd/ldm/models/diffusion/cross_attention_control.py#L221

**Comment by Kyle0654** [comment]
Should be fixed now. Let @damian0815 or me know if performance still seems poor and we can look into it more.

**Comment by Fortyseven** [comment]
Much faster on this end. Excellent! Thanks! :beers:
