### ISSUE TITLE
[bug]: Image-2-Image generates black box

### ISSUE THREAD

**Issue by SirToastalot** [invoke-ai/InvokeAI#1428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

40GB

### What happened?

Very frustrated at this point: just got excited that not using CUDA issue was fixed and I could get some work done, and now Img-2-Img with the same prompts is generating a blank image.

Am I doing something wrong?

I am using stable diffusion 1.4

**Comment by SirToastalot** [comment]
So I installed and reinstalled on debian 10, with cuda 11.0. I am running the same settings as on my PC, with Stable Diffusion 1.4 and InvokeAI 2.1 (I made a fresh install of that too).
 Normal Text2img prompt works but Img2Img does not work on Linux! It does work perfectly on PC though. 
 
 Please help!

**Comment by lstein** [comment]
I'm confused. You're running both Stable Diffusion and InvokeAI 2.1. Does the black box bug appear on both? On one or not the other? 

What would help is for you to run `conda env list` on both the Windows machine on which it works, and the Linux machine on which it doesn't. Then paste the two listings (labeled, of course) into a comment.

After this, you could try changing the pytorch version on the machine that is having problems. After activating the `invokeai` environment, try each of the following incantations in turn:
```
conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116
pip3 install torch torchvision torchaudio
```

**Comment by SirToastalot** [comment]
Now you confused me: I can run both Stable Diffusion and InvokeAI 2.1? I thought I was running Stable Diffusion through InvokeAI! 
LMAO, this stuff is soo not obvious to me!
I was running InvokeAI on Google Cloud VM (A100) and on my PC(980ti), on the VM I was getting black boxes.

Turns out I need to enable float32 precision on VM utiolising A100 gpu!

So the fix is:  python scripts/invoke.py --precision float32

**Comment by psychedelicious** [comment]
Glad you got it sorted.
