### ISSUE TITLE
[enhancement]: populate WebUI from image metadata?

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#1429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

It does not seem to be implemented or maybe I overlooked it? What's is the main intent behind having metadata imbed in the images?

thank you,

**Comment by blessedcoolant** [comment]
You can press the Use All / Use Seed and etc to populate the options with the data from the metadata of the generation if it exists.
