### ISSUE TITLE
[enhancement]: Allow options to choose from in a prompt

### ISSUE THREAD

**Issue by Coreusa** [invoke-ai/InvokeAI#1430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

It would be both beneficial and interesting imo to add options to choose from in a prompt. This would save time since you wouldn't have to run all versions of a certain setting, you could just add them in the prompt and have the AI select any of the options ("at whim") and generate a result. There is no guarantee all versions of the prompt would run, but is more likely the higher the image count. This new feature would be called something like "an option block".

The options block in a prompt starts with, for example, a `{`, followed by each option inside separated by `|` and ends with a `}`. 

Like so: **`{blue|red|green}`**. However, whatever token sequence is fine, it's just a suggestion.

Here are some examples:

`A {beautiful|cyberpunk|serene} landscape `

Prompts this would generate (for the AI to choose from):
- A **beautiful** landscape
- A **cyberpunk** landscape
- A **serene** landscape

For this example, there would in total be 3 ways this prompt may turn out.

Of course, one could add these anywhere in the prompt. Here's a more advanced example:

`A {warrior|mage|bard} scouting from atop a tower at {sunset|dawn|dusk}`

Prompts this would generate (for the AI to choose from):
- A **warrior** scouting from atop a tower at **sunset**
- A **warrior** scouting from atop a tower at **dawn**
- A **warrior** scouting from atop a tower at **dusk**
- A **mage** scouting from atop a tower at **sunset**
- .... and so on

For this example, there would in total be 9 ways this prompt may turn out.

**Please note**
It's important to underline that not all permutations of all options will run. The AI would pick a random item from each option block and continue to the next to create a complete prompt. The results would also be limited by the number of images the user wants to create, not "all permutations of all options set in the prompt".

So, taken the example above ☝️  with an image limit of 3, you may get results created from these prompts:

- A **warrior** scouting from atop a tower at **sunset**
- A **warrior** scouting from atop a tower at **sunset**
- A **mage** scouting from atop a tower at **sunset**

If you run the generation again, different items from each option block may be selected, resulting in 3 new prompts and hence 3 new images, it's "random".

**Example prompt in UI**
![image](https://user-images.githubusercontent.com/706874/200907823-e6bbb421-1249-4155-8daa-c25669ac0ba5.png)

**Why is this useful?**
Consider wanting to create, say, a large collection of various adventure settings with different elements like "`a landscape with a castle and adventurers crossing a river`" and "`a landscape with majestic mountains and dragons in the sky`". Currently, you would need to run these two prompts independently. This grows exponentially difficult with more elements in the sentence. With the prompt options ability, you'd input 1 prompt with the parts that can change and let the AI choose one for each generation. It's adds some additional "magic" to what's already pretty incredible.

![magic](https://media.tenor.com/bxHQ4KcM8eMAAAAC/magic-meme.gif)

## Further thoughts: Option probability
_Note: These are suggestions only_

One can further expand on the options with weights on how probable it'll be that the AI chooses _that item_ from the options block. 

Options are followed by `:<Probability>`. Like so:

`A {large:0.5|small:0.3|huge:0.2} sword` 

The prompt above has a higher probability to be "`A large sword`" (50%) than "`A huge sword`" (20%). In cases of erronous calculations (where the options do not accumulate up to a 100%), each option falls back to a probability of `1/number of options`.

**Comment by damian0815** [comment]
also to consider, from jonathon pollock on Discord: being able to import words from a word list eg `portrait of a {adj.txt} man`, would generate one image for each line of adj.txt

**Comment by damian0815** [comment]
syntax would probably be more like `.oneOf("red", "yellow", "blue")` or `.oneOf(file="/path/to/file.txt")`.

**Comment by JPPhoto** [comment]
I see we have two related syntax modifiers - `.oneOf` and `.allOf` - and both should both take strings or a file. The syntax also feels a bit off here as other modifiers are after strings.

**Comment by Coreusa** [comment]
Remember that there's a difference between "All of the options" and "Have options to choose from". This feature would be the latter and limited by the number images set in the UI.

So "A wizard with a {green|red|blue} robe" and 3 images as output would not guarantee three different images, it's just options that _can_ be chosen from. You may still end up with three images with a wizard in blue robes.

**Comment by damian0815** [comment]
open to suggestions about how the syntax should be done. i'm not a fan of making `{}` meaningful in the way OP suggests - really want to find an imperative command-like way of activating this. does `("red", "yellow", "blue").oneOf()` make sense? and how would this look for file input?  

not quite sure what `.allOf()` is for though..?

**Comment by JPPhoto** [comment]
`.allOf()` would do one execution per term. So `a (red, yellow, "dark blue").allOf() chair` would iterate through the list and generate a total of three images.

**Comment by damian0815** [comment]
ah got it. thanks for the clarification @Coreusa

**Comment by Coreusa** [comment]
The suggestion has been updated, should be clearer now.

**Comment by lstein** [comment]
For something like this, it's probably best to prototype using a standalone script that takes in the templated prompt and puts out a file containing the expanded prompts. Then this expanded prompt list could be passed to the CLI using the `--from_file` argument. Once the syntax is firmed up, the new feature could be added to the built-in prompting syntax.

**Comment by psychedelicious** [comment]
This is now integrated into the app
