### ISSUE TITLE
[bug]: Sudden change in sizeof image after fast intermediates rendering (WebGUI)

### ISSUE THREAD

**Issue by lstein** [invoke-ai/InvokeAI#1443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

32GB

### What happened?

When using the web interface and the "fast" intermediate image displays, the final intermediate image is transiently replaced by a small 64x64 image before displaying the final full-size image.

Has anyone else experienced this? It is very reproducible on my end, and occurs on Linux, Windows and iPad browsers.

**Comment by mickr777** [comment]
Yes I get that too, I think that is the size it renders the fast intermates at but stretches them bigger  during render

**Comment by psychedelicious** [comment]
Resolved in #1435 (by https://github.com/invoke-ai/InvokeAI/pull/1435/commits/d8617eedddac5e801a3f78d40d3e07a8264365f5)
