### ISSUE TITLE
[bug]: Metadata privacy issues with GUI

### ISSUE THREAD

**Issue by JPPhoto** [invoke-ai/InvokeAI#1450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What happened?

InvokeAI's GUI writes metadata into images it creates that include all models available via `Sd-metadata`, potentially exposing model names, descriptions, and hashes that aren't public or that the image creator wishes to keep private. I see this as a privacy risk as well as potentially a security risk.

This information is not shared via `Sd-metadata` that the CLI writes.

I would imagine that the useful piece of the model information written is the actual model used for generating the image, and in that case perhaps all that's needed is the hash so it can be looked up later.

**Comment by psychedelicious** [comment]
I fixed the models, but seem to have introduced storing the whole, absolute filepath to images in the metadata now. This is clearly no good. I will need to revise this. Maybe also provide a no-metadata toggle in the UI for the v2.2 release.
