### ISSUE TITLE
[bug]: Mac M1: Face Restoration Failing

### ISSUE THREAD

**Issue by twopiearr** [invoke-ai/InvokeAI#1451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### VRAM

16 gig total system RAM

### What happened?

As recently as yesterday I have been able to use both gpfgan and codeformer face restoration. This morning using either gives the following error messages below. This is being done from the web GUI. 
```
>> GFPGAN - Restoring Faces for image seed:724057151/25 [01:11<00:00,  2.70s/it]
[W NNPACK.cpp:51] Could not initialize NNPACK! Reason: Unsupported hardware.
Intel MKL FATAL ERROR: This system does not meet the minimum requirements for use of the Intel(R) Math Kernel Library.
The processor must support the Intel(R) Supplemental Streaming SIMD Extensions 3 (Intel(R) SSSE3) instructions.
The processor must support the Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) instructions.
The processor must support the Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
```

```
>> CodeFormer - Restoring Faces for image seed:872852733[01:23<00:00,  2.43s/it]
Intel MKL FATAL ERROR: This system does not meet the minimum requirements for use of the Intel(R) Math Kernel Library.
The processor must support the Intel(R) Supplemental Streaming SIMD Extensions 3 (Intel(R) SSSE3) instructions.
The processor must support the Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) instructions.
The processor must support the Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
```

### Contact Details

richpizor@gmail.com

**Comment by psychedelicious** [comment]
Hi @twopiearr , sorry for the late response to this issue. 

I don't think we have seen this issue before, but I wonder if you have ended up with the wrong architecture of packages installed - strange that it is looking for Intel stuff. 

Did your installation change (e.g. did you update it) between those two days when the problem started?

**Comment by leedrake5** [comment]
Same exact issue here. Using the Mac-yml that's suppose to be optimized for MPS. It must be grabbing the wrong thing.

**Comment by psychedelicious** [comment]
@leedrake5 Can you please upload your environment-mac.yml here?

**Comment by psychedelicious** [comment]
Also - are you running the scripts from tmux or something similar?

**Comment by leedrake5** [comment]
I'm using the web version. I did find a fix - the problem is with the GFPGANv1.4.pth file, it requires intel MKL (and/or the line invoking it). Switching to codeformer for face restoration resolves the issue. 

environment-mac.yml attached here (extension changed to .txt). 
[environment-mac.txt](https://github.com/invoke-ai/InvokeAI/files/10072796/environment-mac.txt)

**Comment by leedrake5** [comment]
NVM, the third image I tried to generate triggered the same Intel MKL error. Something's up. 

`>> Sampling with k_lms starting at step 38 of 150 (112 new sampling steps)
100%|████████████████ 112/112 [00:31<00:00,  3.55it/s]
>> CodeFormer - Restoring Faces for image seed:2759682453████████████████████████████████████████████████| 112/112 [00:31<00:00,  3.60it/s]
Intel MKL FATAL ERROR: This system does not meet the minimum requirements for use of the Intel(R) Math Kernel Library.
The processor must support the Intel(R) Supplemental Streaming SIMD Extensions 3 (Intel(R) SSSE3) instructions.
The processor must support the Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) instructions.
The processor must support the Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
(invokeai) lee@Lees-Mac-Studio InvokeAI % /Users/lee/opt/anaconda3/envs/invokeai/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '`

**Comment by twopiearr** [comment]
> Hi @twopiearr , sorry for the late response to this issue.
> 
> I don't think we have seen this issue before, but I wonder if you have ended up with the wrong architecture of packages installed - strange that it is looking for Intel stuff.
> 
> Did your installation change (e.g. did you update it) between those two days when the problem started?

Not that I'm aware of. I do have an auto1111 install on the same machine, but they use different environments so I can't imagine changes in one could impact the other.

For whatever it's worth, I did a fresh install of 2.1.3 a few days ago and haven't had this error since.
