### ISSUE TITLE
pull model info from backend when opening webui settings panel 

### ISSUE THREAD

**Issue by whosawhatsis** [invoke-ai/InvokeAI#1453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I tend to leave a tab open for my webui, even when I stop the backend process to free up RAM. I've gotten unexpected results from this several times because when I start the process again, it doesn't load the model I was working with last.

This is clearly my fault for not checking that I was loading the model I thought I was. The annoying thing, though, is that when I open the settings panel, it still tells me that the model(s) loaded/cached are the ones from the last time I changed models using that panel. It would be nice if that panel checked with the backend to see what models are loaded/cached, rather than just remembering it in the browser.

I know I should really reload the webui when I restart the backend, but that doesn't always happen. I'm sure I'm not the only one. This would also come up if someone had the webui open in multiple tabs, or on another device. If you change models on one, then opened the panel in the other, it would show that you were using a different model from what it is actually using to generate images.

**Comment by lnorton89** [comment]
Until Websockets/Service Workers and modern front end tooling (React, Vue.js, etc) are implemented I don't see how that would be possible.

**Comment by psychedelicious** [comment]
I've resolved this (in v2.2) by querying the model list every time the UI connects to back end (e.g. after restarting the backend). Also, we display the model now in the site header. Thanks for the report.
