### ISSUE TITLE
[enhancement]: Support SD prompt format with a separate entry for negative prompts

### ISSUE THREAD

**Issue by spullara** [invoke-ai/InvokeAI#1454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Instead of having your own custom prompt format it would be great if prompts found on Reddit, etc could be pasted in and work.

**Comment by damian0815** [comment]
there are numerous different formats for prompts already out there, and for the different implementations of SD there are different techniques for implementing eg weighting. so it's doubtful this can be implemented as a "paste in random prompt and get the same output". 

it might be possible to have an "import from xxx format" option, but even then, weighting a word `0.9` in InvokeAI mathematically does different things to weighting it `0.9` in eg automatic. maybe this is ok, though?

**Comment by damian0815** [comment]
fwiw this is already a "negative prompt" functionality built in to InvokeAI, you just type the negative prompt in `[]` like `positive prompt, trending on teastation [bad art, poorly drawn, etc.]`

**Comment by spullara** [comment]
I'm aware the negative prompt functionality is in the system. It is just too bad that prompts aren't standardized so they can easily be shared without rewriting them. Your point about doing different things stands though. Not sure if sharing prompts works at all then.
