### ISSUE TITLE
[bug]: Error with size of input image (--initimg) in IMG2IMG task!

### ISSUE THREAD

**Issue by TruongQuocTruong** [invoke-ai/InvokeAI#1455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

24

### What happened?

I have a similar problem when I try to generate an image in the IMG2IMG task. It works with my input image of size (512, 346), in spite of not having size (512x512). But when I try to some another size (512, 372); (508, 677); (300, 512);... It has an error: " RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 10 but got size 9 for tensor number 1 in the list."
I appreciate it if someone supports me to fix it! Thank a lot!

### Screenshots

![image](https://user-images.githubusercontent.com/59196676/201454606-b4932021-b081-4bb4-b983-b8d27f785c62.png)

![image](https://user-images.githubusercontent.com/59196676/201454628-c0fbf2d9-ae28-47cf-837d-24968664947f.png)

### Contact Details

truong.quoc.truong242@gmail.com

**Comment by lstein** [comment]
I'm unable to reproduce this bug. I tried with both a 300x512 and a 512x372 image. Which version of the software are you using?
