### ISSUE TITLE
[enhancement]: Portable version part 2

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#1462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Greetings,

In the work of making a portable version (currently testing on Windows), meaning install/package once copy/extract the root folder to any other computer. Some files are preventing this feature from happening:

_userdirectory\.cache\clipViT-B-16.pt (seems not to be needed)
_userdirectory\.cache\huggingface\transformers\* (temp files that are somehow required)
_userdirectory\.cache\torch\hub\checkpoints\checkpoint_liberty_with_aug.pth (will be downloads when starting invoke.py if delete)

Having those files under invokeai root directory would be the last piece of the puzzle for a portable version. 

Would anyone know how to clean these up or even better, remove those dependencies?

thank you,

**Comment by lstein** [comment]
I can work on this. It is also on my list of things to do. The larger plan is to move models, configuration files, the end-user scripts and the outputs directory into an installation destination that is distinct from the GitHub repo.

**Comment by Neosettler** [comment]
Marvelous @lstein, 

I found a hack that seem to do the job for non-standard libraries:

invoke.py:
sys.path.append(os.path.join(os.path.dirname(__file__), ".."))
sys.path.append(os.path.join(os.path.dirname(__file__), "../src"))
sys.path.append(os.path.join(os.path.dirname(__file__), "../src/k-diffusion"))
sys.path.append(os.path.join(os.path.dirname(__file__), "../src/clipseg"))
sys.path.append(os.path.join(os.path.dirname(__file__), "../src/taming-transformers"))

Not my favorite but it works.

**Comment by Neosettler** [comment]
_userdirectory.cache\huggingface\transformers\*.*  is pretty much the only files remaining, which seems to require:
[clip-vit-large-patch14](https://huggingface.co/openai/clip-vit-large-patch14)

tried "local file only" flag to false but it doesn't get everything that is needed.
A workaround would be greatly appreciated.

**Comment by n00mkrad** [comment]
> _userdirectory.cache\huggingface\transformers*.* is pretty much the only files remaining, which seems to require: [clip-vit-large-patch14](https://huggingface.co/openai/clip-vit-large-patch14)
> 
> tried "local file only" to false but it doesn't get everything that is needed. A workaround would be greatly appreciated.

Set the following two environment variables to a directory in your portable folder:

`TRANSFORMERS_CACHE`
and
`TORCH_HOME``

This way you can avoid the usage of `%USERPROFILE%/.cache`.

**Comment by Neosettler** [comment]
thank you @n00mkrad,

invoke.py:
import os
os.environ["TRANSFORMERS_CACHE"] = "../envs/invokeai/.cache"
os.environ["TORCH_HOME"] = "../envs/invokeai/.cache"

.cache have been copied to the root folder,

If that is what you had in mind, it is not working as expected. Maybe the variable have to be set before installing everything?
