### ISSUE TITLE
[bug]: OpenSSL unavailable windows11 -- FIX!

### ISSUE THREAD

**Issue by ifiwasakid** [invoke-ai/InvokeAI#1463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6gb

### What happened?

Fresh install of Conda gives this error "CONDASSLError: OpenSSL appears to be unavailable"
after trawling the web, the answer was found here and a few other stackoverflow discussions:
https://github.com/conda/conda/issues/11795

VERIFIED WORKING SOLUTION:
Copy libcrypto-1_1-x64.dll and libssl-1_1-x64.dll
from C:\Users\username\miniconda3\Library\bin
to C:\Users\username\miniconda3\DLLs

**Comment by ifiwasakid** [comment]
I submitted the above so it can be ADDED TO DOCUMENTATION, since windows users are down to ONE INSTALL method given that the "easy peasy" method page is down, i'm assuming someone esle(s) had the same horrible problems i have had with it (never gotten it working) so conda is the only option, but it encounters this deal-stopper error. please affix this to the install doc page here so we can get on with our lives -- and look, i have a dual boot pc, i'm using photoshop alot these days so i prefer to stay in windows, even tho i didnt use it all last year, lol.

**Comment by ifiwasakid** [comment]
please. and thank you. please

**Comment by lstein** [comment]
I've added this fix to the manual. It will appear after code review.
