### ISSUE TITLE
[bug]: conda environment installation failing, fix included

### ISSUE THREAD

**Issue by veprogames** [invoke-ai/InvokeAI#1467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What happened?

When running `conda env create -f environments-and-requirements/environment-lin-cuda.yml`, the installation fails with
```
file://<project path>/environments-and-requirements (from -r <project path>/environments-and-requirements/condaenv.7w8aoe5f.requirements.txt (line 31)) does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```
This is probably a context from folder context, as it tries to do `pip install ./environments-and-requirements`

I fixed it by replacing `-e .` with `-e ../` in `environments-and-requirements/environment-lin-cuda.yml` (should be applied to others too)

**Comment by mickr777** [comment]
If your doing manual install for v2.1.3 you need to copy your appropriate yml to InvokeAI's top-level directory and rename it environment.yml
