### ISSUE TITLE
[bug]: Bounding box calculations are incorrect

### ISSUE THREAD

**Issue by JPPhoto** [invoke-ai/InvokeAI#1470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What happened?

I'm using `invoke.py` to do `img2img` with a source image of 512x512. I requested `-W 1024 -H 768 --fit` and I received the following output:
```
>> image will be resized to fit inside a box 1024x768 in size.
>> after adjusting image dimensions to be multiples of 64, init image is 1024x1024
```
I would imagine the image would be resized to 768x768 as that is the bounding box that a resized square image would fit in.

This behavior is correct if I swap the height and width (`-W 768 -H 1024 --fit`):
```
>> image will be resized to fit inside a box 768x1024 in size.
>> after adjusting image dimensions to be multiples of 64, init image is 768x768
```
This may be an issue in `InitImageResizer` in `ldm/invoke/image_util.py`.

**Comment by lstein** [comment]
Thanks for catching this long-standing bug! I will fix.

**Comment by lstein** [comment]
This is now fixed on the `development` branch.
