### ISSUE TITLE
[bug]: Tried to install "invokeAI-src-installer-mac" - immediately got the following error.

### ISSUE THREAD

**Issue by movinimage** [invoke-ai/InvokeAI#1500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

32GB

### What happened?

Tried to install "invokeAI-src-installer-mac" - immediately got the following error.

```
joe@MacBook-Pro-J-Max invokeAI % ./install.sh
Installing InvokeAI..

Downloading micromamba from https://micro.mamba.pm/api/micromamba/mac-arm64/latest to /Users/joe/invokeAI/installer_files/mamba/micromamba
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    50  100    50    0     0     32      0  0:00:01  0:00:01 --:--:--    32
tar: Error opening archive: Unrecognized archive format
Micromamba version:
Packages to install: conda
There was a problem while initializing micromamba. Cannot continue.
joe@MacBook-Pro-J-Max invokeAI % ```

**Comment by kevincoakley** [comment]
It looks like you might have an outdated version of the install.sh script. The download URL should be https://micro.mamba.pm/api/micromamba/osx-arm64/latest not https://micro.mamba.pm/api/micromamba/mac-arm64/latest . It appears the URLs were fixed in commit https://github.com/invoke-ai/InvokeAI/commit/1a8e007066a2577bc774805e127d016f46c96911

**Comment by lstein** [comment]
Actually it looks like the **source** installer still has this bug. Could you give this version a try?

[invokeAI-src-installer-mac.zip](https://github.com/invoke-ai/InvokeAI/files/10027756/invokeAI-src-installer-mac.zip)

**Comment by movinimage** [comment]
Thank you for looking into this! Now I get this error :)

```
joe@MBP-J-Max-93 ~ % /Users/joe/invokeAI/install.sh 
Installing InvokeAI..

Downloading micromamba from https://micro.mamba.pm/api/micromamba/osx-arm64/latest to /Users/joe/invokeAI/installer_files/mamba/micromamba
Downloading micromamba from https://micro.mamba.pm/api/micromamba/osx-arm64/latest to /Users/joe/invokeAI/installer_files/mamba/micromamba
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  3879    0  3879    0     0   3806      0 --:--:--  0:00:01 --:--:-- 79163
  2 4722k    2  118k    0     0  60228      0  0:01:20  0:00:02  0:01:18 60228x 100 4722k  100 4722k    0     0   551k      0  0:00:08  0:00:08 --:--:--  832k

tar: -O: Not found in archive
tar: Error exit delayed from previous errors.
Micromamba version:
Packages to install: conda
There was a problem while initializing micromamba. Cannot continue.
```

**Comment by lstein** [comment]
Thank you. I'll continue to work on this and post a new version for you to try later today.

**Comment by lstein** [comment]
If and when you have a chance, could you run this version of the installer and post the output? It outputs additional debugging information that will help me track down the problem.

[invokeAI-src-installer-mac.zip](https://github.com/invoke-ai/InvokeAI/files/10033093/invokeAI-src-installer-mac.zip)

**Comment by movinimage** [comment]
Here you go (and thank you!):
```
joe@MBP-J-Max-93 invokeAI % ./install.sh
Installing InvokeAI..

-----------------------------------------------------------------------------
DEBUG:
OS_NAME=osx, OS_ARCH=arm64, MAMBA_ARCH=arm64, PY_ARCH=aarch64
Micromamba download URL = https://micro.mamba.pm/api/micromamba/osx-arm64/latest
Packages to install =  conda
-----------------------------------------------------------------------------
Downloading micromamba from https://micro.mamba.pm/api/micromamba/osx-arm64/latest to /Users/joe/invokeAI/installer_files/mamba/micromamba
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  3823    0  3823    0     0   2595      0 --:--:--  0:00:01 --:--:-- 3733k
100 4722k  100 4722k    0     0  1635k      0  0:00:02  0:00:02 --:--:-- 6410k

tar: -O: Not found in archive
tar: Error exit delayed from previous errors.
Micromamba version:
Packages to install: conda
There was a problem while initializing micromamba. Cannot continue.
```

**Comment by kevincoakley** [comment]
Line 78 in the file what was uploaded by @lstein in https://github.com/invoke-ai/InvokeAI/issues/1500#issuecomment-1318834045 should be:

`curl -L "$MICROMAMBA_DOWNLOAD_URL" | tar -xvjO bin/micromamba > "$MAMBA_ROOT_PREFIX/micromamba"`

The `-O` is being interpreted as a file in the tar archive that is needing to be extracted, instead of directing `bin/micromamba` to stdout as I believe is desired. 

This is probably an issue because Linux uses GNU tar and macOS uses bsdtar and the `-O` option could behave differently in the two implementations of the tar command.

**Comment by movinimage** [comment]
@kevincoakley This worked. It installed and runs. Thank you!

**Comment by lstein** [comment]
The fix has now been merged into main. @kevincoakley thanks for the debugging! I was stumped.

**Comment by afrokick** [comment]
Any ETA for a new release with this fix?

**Comment by lstein** [comment]
We'll release a point release containing this fix by the end of the week.
In the meantime, I'll push a version of the zip file that contains the fix.

Lincoln
