### ISSUE TITLE
[enhancement]: Selective highres_fix

### ISSUE THREAD

**Issue by discordinated** [invoke-ai/InvokeAI#1508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

highres_fix is amazing I think we'd all agree, but it dramatically slows down image creation on images that I can see from the low res preview are not good. If it's a single file from the prompt this is not bad, you an stop Invoke and try again for a different seed, but if you want to render say 20 images for a prompt you have to either wait a long time or keep stopping and starting - which means sitting watching the job all the time. 

Would it be possible to have all the low res previews generated and then flag which ones to apply the highres_fix to? This would dramticaly speed up generation by only creating the large high res assets for the preselected best low res.

### Alternatives

It's possible to manually do this by generating low res assets then using Img>Img but this has to be done single file at a time.

**Comment by psychedelicious** [comment]
HRO is not directly implemented in v3 but you can use the node editor to do the same thing for specific images.
