### ISSUE TITLE
[bug]: Error during invoke launch after windows install

### ISSUE THREAD

**Issue by thraxus2000** [invoke-ai/InvokeAI#1509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12

### What happened?

After trying the new windows installer, much more progress was made than with my previous efforts to fix things manually. Two things seemed to happen which seemed 'wrong'

1) The inpainting 1.5 model was not downloaded, though the main model was.
2) The first time I ran the installer, it crashed because I didn't use the long names regedit thing

However, when I attempt to run invoke.bat, it seems to be loading things before failing with the below complaint, which turns into a much quicker final crash, but happens too fast for me to get a screenshot

### Screenshots

![image](https://user-images.githubusercontent.com/114209028/202630102-2fd83bb8-2886-4b24-85ee-0cdf49db6c3f.png)

**Comment by tildebyte** [comment]
If you're using 'InvokeAI-windows.zip', my suggestion would be to delete ALL installations and environments you can find, re-download 'InvokeAI-windows.zip', and start a new install from scratch.
