### ISSUE TITLE
[enhancement]: Support horizontal and/or vertical symmetry

### ISSUE THREAD

**Issue by JPPhoto** [invoke-ai/InvokeAI#1519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I'd love to see options to encourage generation of symmetrical images along one or both axes via `--hsymmetry [value]` and `--vsymmetry [value]` (and GUI equivalents) where the latents are flipped along the requested axis/axes and averaged with the existing latent for the first `value * total steps` steps of image generation (the result might have to be multiplied by some factor to maintain entropy.

**Comment by n00mkrad** [comment]
Already exists.

`--seamless` and `--seamless_axes`

**Comment by JPPhoto** [comment]
@n00mkrad That is seamless tiling, not symmetry.

**Comment by JPPhoto** [comment]
This feature is in Invoke 2.3.x. Closing.
