### ISSUE TITLE
[bug]: prompt blending does not work with `--model inpainting-1.5`

### ISSUE THREAD

**Issue by Perryman** [invoke-ai/InvokeAI#1530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What happened?

Prompt blending syntax does not work properly on the CLI interface of invoke.py.

Summary of prompts used:
```
cat:0 dog:1 -s 30 -S 11 -W 512 -H 512 -C 10 -A k_euler_a -t
cat:0.1 dog:0.9 -s 30 -S 11 -W 512 -H 512 -C 10 -A k_euler_a -t
cat:0.01 dog:0.99 -s 30 -S 11 -W 512 -H 512 -C 10 -A k_euler_a -t
cat:0.001 dog:0.999 -s 30 -S 11 -W 512 -H 512 -C 10 -A k_euler_a -t
cat:0.0001 dog:0.9999 -s 30 -S 11 -W 512 -H 512 -C 10 -A k_euler_a -t
```

Expected result: a dog-like picture should appear. The picture is always a cat, and was attempted with a variety of random seeds.
For example, using the web UI results in the following (correct) image:
![013945 c5722252 11](https://user-images.githubusercontent.com/7044121/203183431-aba6f673-9dcc-4b13-b811-122f0150da34.png)

### Screenshots

invoke> cat:0 dog:1 -s 30 -S 11 -W 512 -H 512 -C 10 -A k_euler_a -t

>> Tokens (blend part 1, weight=0.0) (1):
catx` 

>> Tokens (blend part 2, weight=1.0) (1):
dogx` 

>> Tokens (unconditioning) (0):

>> Ksampler using model noise schedule (steps >= 30)
Generating:   0%|                                                                              | 0/1 [00:00<?, ?it/s]>> Sampling with k_euler_ancestral starting at step 0 of 30 (30 new sampling steps)
100%|████████████████████████████████████████████████████████████████████████████████| 30/30 [00:02<00:00, 11.36it/s]
Generating: 100%|██████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.95s/it]
>> Usage stats:
>>   1 image(s) generated in 3.02s
>>   Max VRAM used for this generation: 5.19G. Current VRAM utilization: 4.03G
>>   Max VRAM used since script start:  5.19G
Outputs:
[1011] outputs/img-samples/013937.11.png: cat:0 dog:1 -s 30 -S 11 -W 512 -H 512 -C 10.0 -A k_euler_a
![013937 11](https://user-images.githubusercontent.com/7044121/203181909-cea63770-5a0b-4a19-aeaa-97bbfcbcb9fe.png)

invoke> cat:0.1 dog:0.9 -s 30 -S 11 -W 512 -H 512 -C 10 -A k_euler_a -t

>> Tokens (blend part 1, weight=0.1) (1):
catx` 

>> Tokens (blend part 2, weight=0.9) (1):
dogx` 

>> Tokens (unconditioning) (0):

>> Ksampler using model noise schedule (steps >= 30)
Generating:   0%|                                                                              | 0/1 [00:00<?, ?it/s]>> Sampling with k_euler_ancestral starting at step 0 of 30 (30 new sampling steps)
100%|████████████████████████████████████████████████████████████████████████████████| 30/30 [00:02<00:00, 11.34it/s]
Generating: 100%|██████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.95s/it]
>> Usage stats:
>>   1 image(s) generated in 3.01s
>>   Max VRAM used for this generation: 5.19G. Current VRAM utilization: 4.03G
>>   Max VRAM used since script start:  5.19G
Outputs:
[1012] outputs/img-samples/013938.11.png: cat:0.1 dog:0.9 -s 30 -S 11 -W 512 -H 512 -C 10.0 -A k_euler_a
![013938 11](https://user-images.githubusercontent.com/7044121/203181922-ddf3f5fe-4cad-4671-b0c1-53a8424fa4a3.png)

invoke> cat:0.01 dog:0.99 -s 30 -S 11 -W 512 -H 512 -C 10 -A k_euler_a -t

>> Tokens (blend part 1, weight=0.01) (1):
catx` 

>> Tokens (blend part 2, weight=0.99) (1):
dogx` 

>> Tokens (unconditioning) (0):

>> Ksampler using model noise schedule (steps >= 30)
Generating:   0%|                                                                              | 0/1 [00:00<?, ?it/s]>> Sampling with k_euler_ancestral starting at step 0 of 30 (30 new sampling steps)
100%|████████████████████████████████████████████████████████████████████████████████| 30/30 [00:02<00:00, 11.33it/s]
Generating: 100%|██████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.95s/it]
>> Usage stats:
>>   1 image(s) generated in 3.01s
>>   Max VRAM used for this generation: 5.19G. Current VRAM utilization: 4.03G
>>   Max VRAM used since script start:  5.19G
Outputs:
[1013] outputs/img-samples/013939.11.png: cat:0.01 dog:0.99 -s 30 -S 11 -W 512 -H 512 -C 10.0 -A k_euler_a
![013939 11](https://user-images.githubusercontent.com/7044121/203181941-f30a4041-99aa-45a4-8c55-ddcef8c511bd.png)

invoke> cat:0.001 dog:0.999 -s 30 -S 11 -W 512 -H 512 -C 10 -A k_euler_a -t

>> Tokens (blend part 1, weight=0.001) (1):
catx` 

>> Tokens (blend part 2, weight=0.999) (1):
dogx` 

>> Tokens (unconditioning) (0):

>> Ksampler using model noise schedule (steps >= 30)
Generating:   0%|                                                                              | 0/1 [00:00<?, ?it/s]>> Sampling with k_euler_ancestral starting at step 0 of 30 (30 new sampling steps)
100%|████████████████████████████████████████████████████████████████████████████████| 30/30 [00:02<00:00, 11.34it/s]
Generating: 100%|██████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.96s/it]
>> Usage stats:
>>   1 image(s) generated in 3.02s
>>   Max VRAM used for this generation: 5.19G. Current VRAM utilization: 4.03G
>>   Max VRAM used since script start:  5.19G
Outputs:
[1014] outputs/img-samples/013940.11.png: cat:0.001 dog:0.999 -s 30 -S 11 -W 512 -H 512 -C 10.0 -A k_euler_a
![013940 11](https://user-images.githubusercontent.com/7044121/203181959-f9365d9a-033b-444a-942e-ec92ddd9e2b9.png)

invoke> cat:0.0001 dog:0.9999 -s 30 -S 11 -W 512 -H 512 -C 10 -A k_euler_a -t

>> Tokens (blend part 1, weight=0.0001) (1):
catx` 

>> Tokens (blend part 2, weight=0.9999) (1):
dogx` 

>> Tokens (unconditioning) (0):

>> Ksampler using model noise schedule (steps >= 30)
Generating:   0%|                                                                              | 0/1 [00:00<?, ?it/s]>> Sampling with k_euler_ancestral starting at step 0 of 30 (30 new sampling steps)
100%|████████████████████████████████████████████████████████████████████████████████| 30/30 [00:02<00:00, 11.37it/s]
Generating: 100%|██████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.94s/it]
>> Usage stats:
>>   1 image(s) generated in 3.00s
>>   Max VRAM used for this generation: 5.19G. Current VRAM utilization: 4.03G
>>   Max VRAM used since script start:  5.19G
Outputs:
[1015] outputs/img-samples/013941.11.png: cat:0.0001 dog:0.9999 -s 30 -S 11 -W 512 -H 512 -C 10.0 -A k_euler_a
![013941 11](https://user-images.githubusercontent.com/7044121/203181984-63f2f7a4-0818-48e9-95eb-e6720f528b3f.png)

### Additional context

Additionally, the .blend syntax on invoke.py seems to produce a different unexpected result.
```
invoke> (cat,dog).blend(0.0001,0.9999) -s 30 -S 11 -W 512 -H 512 -C 10 -A k_euler_a -t

>> Tokens (blend part 1, weight=0.0001) (1):
catx` 

>> Tokens (blend part 2, weight=0.9999) (1):
dogx` 

>> Tokens (unconditioning) (0):

>> Ksampler using model noise schedule (steps >= 30)
Generating:   0%|                                                                              | 0/1 [00:00<?, ?it/s]>> Sampling with k_euler_ancestral starting at step 0 of 30 (30 new sampling steps)
100%|████████████████████████████████████████████████████████████████████████████████| 30/30 [00:02<00:00, 11.31it/s]
Generating: 100%|██████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.96s/it]
>> Usage stats:
>>   1 image(s) generated in 3.02s
>>   Max VRAM used for this generation: 5.19G. Current VRAM utilization: 4.03G
>>   Max VRAM used since script start:  5.19G
Outputs:
[1016] outputs/img-samples/013942.11.png: (cat,dog).blend(0.0001,0.9999) -s 30 -S 11 -W 512 -H 512 -C 10.0 -A k_euler_a
```
![013942 11](https://user-images.githubusercontent.com/7044121/203181847-cd256a2d-f666-4357-a245-05fdf92be439.png)

Initialization info:
```
❯ scripts/invoke.py --model inpainting-1.5 
* Initializing, be patient...
>> Initialization file /home/perryman/.invokeai not found. Applying default settings...
>> GFPGAN Initialized
>> CodeFormer Initialized
>> ESRGAN Initialized
>> Using device_type cuda
>> Current VRAM usage:  0.00G
>> Loading inpainting-1.5 from ./models/ldm/stable-diffusion-v1/sd-v1-5-inpainting.ckpt
   | LatentInpaintDiffusion: Running in eps-prediction mode
   | DiffusionWrapper has 859.54 M params.
   | Keeping EMAs of 688.
   | Making attention of type 'vanilla' with 512 in_channels
   | Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
   | Making attention of type 'vanilla' with 512 in_channels
   | Using faster float16 precision
   | Loading VAE weights from: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
>> Model loaded in 30.05s
>> Max VRAM used to load the model: 3.91G 
>> Current VRAM usage:3.91G
>> Setting Sampler to k_lms

* Initialization done! Awaiting your command (-h for help, 'q' to quit)
```

**Comment by Perryman** [comment]
@damian0815 per your request

**Comment by damian0815** [comment]
@Perryman i can't reproduce this (see attached)

Are you sure you're running the same model on web and CLI? All mine are from the non-inpainting model, and look like your "Web UI" output. See here: [gh-issue-1530-blend-test-runpod3090.zip](https://github.com/invoke-ai/InvokeAI/files/10069432/gh-issue-1530-blend-test-runpod3090.zip)

@blessedcoolant were you running the inpainting model on those tests you showed me? maybe the inpainting model is just weird?

**Comment by damian0815** [comment]
@Perryman before changing anything else can you try just running
```python scripts/invoke.py --from_file /path/to/catdog-legacy-s11.txt --outdir /tmp/catdog-legacy-s11``` and lmk what results you get?

**Comment by Perryman** [comment]
> @Perryman before changing anything else can you try just running
> 
> ```
> python scripts/invoke.py --from_file /path/to/catdog-legacy-s11.txt --outdir /tmp/catdog-legacy-s11
> ```
> 
> and lmk what results you get? `catdog-legacy-s11.txt` is in the zip attached to my previous comment

Results are as expected with your command, but my error is reproduced with `--model inpainting-1.5` added on. So this looks like something because of the model used.

**Comment by Perryman** [comment]
I double-checked, and the inpainting model produces this error on both web and CLI. Title of bug report changed to reflect.

**Comment by damian0815** [comment]
@lstein i was just reminded reading the docs that `.swap()` doesn't work with the inpainting model. is it possible that the same may be true for `.blend()`? blend isn't a different code-path, it just lerps between two feature vectors - i don't really understand why that would cause the seeming total lack of response that Perryman is seeing here.
