### ISSUE TITLE
[bug]: preload_models.py --no-interactive (Development branch)

### ISSUE THREAD

**Issue by mickr777** [invoke-ai/InvokeAI#1536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What happened?

On fresh install preload_models.py asks for user input on the outputs folder location while using --no-interactive.

If it helps i am using the --root argument as well

**Comment by mickr777** [comment]
cant seem to get it to do it now,

**Comment by ebr** [comment]
@mickr777 any reason you closed this? I think this is a very valid issue, did you find a workaround? The config script indeed does not have a fully non-interactive mode.

**Comment by damian0815** [comment]
I've reopened this, it's definitely something we want (although the script is now called `configure_invokeai.py`). @lstein if we get this in then we have one-click InvokeAI runpod deployment.

**Comment by lstein** [comment]
Add `--yes` to accept all the defaults and download (if needed) the recommended modules. Also see #1559 which has more ideas for improving the script. @ebr has graciously volunteered to work on these issues.

By the way, I didn't close this issue, but I did add the `--yes` option to address it.

**Comment by damian0815** [comment]
yeah i just saw that. awesome.
