### ISSUE TITLE
[bug]: Crash during model loading

### ISSUE THREAD

**Issue by serenityindeed** [invoke-ai/InvokeAI#1556]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

8GB

### What happened?

Trouble importing models using WSL (Debian) within Windows 10.

I'm trying to import the sd-v1-5-inpainting model using the instructions found here: https://invoke-ai.github.io/InvokeAI/installation/INSTALLING_MODELS/

Running the import command runs through some things then kicks me out back to Linux cli as shown in the second screenshot error.png.

This has happened to me trying a couple of different models, though some have managed to load correctly. I'm unsure what the issue is - in this instance it says "line 14:   369 Killed". It's always line 14, but the # Killed varies each attempt.

I used invokeAI-src-installer-linux to setup my environment.

### Screenshots

![import](https://user-images.githubusercontent.com/119036607/203928566-e6b27335-a502-4e11-bbe3-9e32358ebe5f.png)
![error](https://user-images.githubusercontent.com/119036607/203928615-8cf5c1e0-f500-461a-92d0-8b7367b7233a.png)

### Contact Details

serenity-indeed@hotmail.co.nz, Artemis#9261

**Comment by psychedelicious** [comment]
@blessedcoolant @lstein 
It seems like the crash is coming from deep within the model loading code. I've no clue how to proceed from here.
