### ISSUE TITLE
[bug]: invoke.py script runs while using PyTorch compiled for CPU, but not with PyTorch compiled with CUDA enabled

### ISSUE THREAD

**Issue by wpramos** [invoke-ai/InvokeAI#1558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

4GB

### What happened?

I manually install Invoke AI [using pip](https://invoke-ai.github.io/InvokeAI/installation/INSTALL_MANUAL/#pip-install). The requirements for my system [Windows with an NVIDA (CUDA) GPU] include the PyTorch package compiled with CUDA enabled, i.e. torch==1.12.1+cu116. The requirements are installed successfully, and all subsequent steps are followed without issue.
While launching the invoke.py script, during initialization, I run into this message:

```
** model stable-diffusion-1.5 could not be loaded: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 3.39 GiB already allocated; 0 bytes free; 3.45 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

The issue is similar to many on here raised by people using CUDA enabled 4GB GPU's - GTX 1650 or comparable - especially to issue #1208 . In that case the user is able to start invoke.py and the issue arises while attempting to generate images, with me the issue arises upon initialization. That is the only difference. The response to that issue is that a 4GB VRAM isn't sufficient. But here's the peculiar thing:

On my first attempt at setting up Invoke AI, I ran into issue #1409 , where PyTorch wasn't being installed during installation of requirements from requirements.txt. I had to preinstall PyTorch before I installed the other requirements. Here, I made a mistake. Instead of installing the PyTorch version that had been compiled with CUDA enabled as @addianto had mentioned [here](https://github.com/invoke-ai/InvokeAI/issues/1409#issuecomment-1319756723), I installed torch==1.12.1, the CPU version of PyTorch. The funny thing is, Invoke AI worked, despite me being on a system with only 8GB RAM.

I could generate images, but with each iteration taking ~10s, the entire process took over 500s. While looking for ways to speed up the process, I noticed that the 'device_type' is mentioned as 'cpu' during initialization, which is when I noticed my mistake of installing the wrong version of PyTorch. I created a fresh install with care taken to install the appropriate version of PyTorch hoping to speed up the process, but alas, I am unable to even load to script despite the additional benefit of having a CUDA enabled 4GB GPU.

I'd imagine that if the process can run without taking advantage of the GPU, it should be faster when provided the additional horsepower. But not only is it not faster, but the script doesn't load. I'm not sure why that is the case.

Also, AFAIK there are no other processes that are making use of the GPU. I have attached a screenshot for reference. I am not too experienced with the things that happen under the hood, so apologies if I have not provided sufficient/accurate information. If required, I will provide any additional information that may be needed.

The environment is similar to @jdries3 's from issue #1208, except that I did a pip install with Python 3.10.8.

### Screenshots

These are the results of the nvidia-smi command run while Invoke AI generates images in another PowerShell process:

![image](https://user-images.githubusercontent.com/63048465/203969709-fe442525-a498-4d0e-9627-f4ac17bee1cd.png)

**Comment by psychedelicious** [comment]
Hi, sorry for the late response.

What GPU do you have? Some, like the 1650, do not support fp16 operations (which reduce the VRAM needed) and are forced to run at full fp32. I wonder if that is the issue.

**Comment by wpramos** [comment]
> What GPU do you have? Some, like the 1650, do not support fp16 operations (which reduce the VRAM needed) and are forced to run at full fp32. I wonder if that is the issue.

Hi. Yes, my GPU is a GTX 1650. I had tried to run the script earlier with fp16, and the script loaded fine and generated images. But the output were just blank black images. So yes, I am having to run of full fp32.

But the issue that I have is mainly that I'm able to load the script without issue and also generate images if I install the torch package for CPU instead of the one compiled for CUDA 11.6. In that case, while I run invoke.py to generate images there is 0% usage of GPU, yet I am able to generate images. Each iteration takes close to 10s for a single output, which means that each image generation takes ~500s. But I'm at least able to get the script to work. I'm wondering... if it is possible to generate images without taking advantage of the GPU, then with the addition of that processing capacity the generation needs to happen faster, right..?

**Comment by psychedelicious** [comment]
@wpramos Fp32 needs more VRAM, but at 4GB you won't be able to load the models and/or generate images - so fp32 won't work. But fp16 also does not work on your card. So unfortunately, with the GTX 1650, your only option is to use CPU.

It's possible that other projects (e.g. Automatic1111) have memory optimizations that will help - have you tried that implementation?

Hopefully in the future we can introduce additional VRAM optimizations but we aren't quite there yet, sorry.

**Comment by addianto** [comment]
@psychedelicious Is it possible to reduce VRAM consumption by installing [`xformers`](https://github.com/facebookresearch/xformers) as part of InvokeAI's installation process?

**Comment by psychedelicious** [comment]
@addianto 
> @psychedelicious Is it possible to reduce VRAM consumption by installing [xformers](https://github.com/facebookresearch/xformers) as part of InvokeAI's installation process?

I don't think we have really looked into it just yet. I believe it is CUDA only, while we try to support all systems. Of course we are aware of it and want to provide it for CUDA users though.

**Comment by wpramos** [comment]
@psychedelicious Going by what you've said, it is expected behavior that the script is able to run on only CPU. I didn't realize that. I thought this is some odd behavior that the script is able to run and generate images without utilizing the GPU. If that's so, then I guess this isn't an issue at all.

Thank you for your response. Yeah, I've given basujindal's optimized script a go and I have been able to run that with GPU. I do hope optimizations come the way of Invoke AI too. I like the CLI environment offered here without the need to load the model multiple times.
