### ISSUE TITLE
[enhancement]: Add DPM Solver sampler

### ISSUE THREAD

**Issue by eeyrw** [invoke-ai/InvokeAI#1560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

The new sampler:https://github.com/LuChengTHU/dpm-solver accelerate image generation speed a lot. Only with 25 steps can achieve the 50 steps performance of old sampler.

**Comment by addianto** [comment]
I think it is currently WIP and you can check it out at PR https://github.com/invoke-ai/InvokeAI/pull/1389.

**Comment by eeyrw** [comment]
It seems quite complicated towards Apple ARM silicon users...
