### ISSUE TITLE
[bug]: Cross-Attention Control (prompt2prompt) does not do anything at all

### ISSUE THREAD

**Issue by n00mkrad** [invoke-ai/InvokeAI#1581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24 GB

### What happened?

I tried to use prompt2prompt, however, the `.swap()` prompt function does not do anything.
I proved this by running the following two commands:

`"a room filled with (water).swap(toxic glowing acid)" -n 1 -t -W 640 -H 512 -S 1 -C 8 -s 35 -I "init.png" -f 0.5`

`"a room filled with toxic glowing acid" -n 1 -t -W 640 -H 512 -S 1 -C 8 -s 35 -I "init.png" -f 0.5`

The init image used: https://i.imgur.com/ZL3fJM9.png

These two commands produced the exact same result, .swap() does not do anything.

The log implies that .swap gets applied to *the entire prompt* instead of just the word/phrase in the parentheses.

![image](https://user-images.githubusercontent.com/61149547/204145003-ef40a821-bafb-456e-b9a7-fab395018114.png)

**Comment by damian0815** [comment]
`.swap()` is difficult to use with img2img, it struggles outside of a few very concrete use cases and you often need to pass a higher value than the default for `s_end`. there's a couple of things to try but it is probably better done live on discord where i can help you try out different prompts one-by-one.

**Comment by n00mkrad** [comment]
> `.swap()` is difficult to use with img2img, it struggles outside of a few very concrete use cases and you often need to pass a higher value than the default for `s_end`. there's a couple of things to try but it is probably better done live on discord where i can help you try out different prompts one-by-one.

It would be helpful if the documentation had any examples with images. Right now I don't really understand how to use prompt2prompt.

**Comment by damian0815** [comment]
you make a good point, i'll open a new issue.

**Comment by damian0815** [comment]
#1582
