### ISSUE TITLE
[enhancement]: Model merge formulas

### ISSUE THREAD

**Issue by whosawhatsis** [invoke-ai/InvokeAI#1587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

This is related to my previous suggestion https://github.com/invoke-ai/InvokeAI/issues/1585, but I thought it should be separate.

I saw that there seems to be a model merge script, but it's not exposed in the interface yet. I've done a lot of model merging using automatic1111's interface (which I keep around almost exclusively for this purpose), but I would like to propose a different way of using the feature.

What I was thinking is that it would be nice to be able to do on-the-fly model merging... rather than having a bunch of models taking up hard drive space that are just various combinations of one another, it shouldn't slow things down much to just save the formula for merging them, then do the merge as the model is being loaded into RAM. I know that personally, this option would currently save me at least 100 gigs of SSD space, because I've been doing a lot of experiments with merging models at various ratios.

Since InvokeAI uses a .yaml file to store model data, saving these formulae would require an extension to that format, adding a secondary (and tertiary, for add difference, which is often the most useful mode) model, as well as a mixing ratio. This way, no new model file would need to be saved. A button to actually write out the merged model would be nice to have, but not necessary to use. This would make it much faster and easier to experiment with different model combinations.

This should also either provide a way for the formula to contain a sequence of merges or for one formula to reference the output of another, instead of a model file, so that you don't need to save intermediate model files when doing multi-model merges.

**Comment by whosawhatsis** [comment]
Btw, one of the best uses for this, in my opinion, would be taking dreambooth models and applying them to different base models (sort of like the github rebase option). I usually do this with the "add difference" mode, but being able to create a sub-formula (or even a file) for the difference so that I could easily just straight add it at 100% to another base model.

**Comment by whosawhatsis** [comment]
Formula syntax should probably be compatible with this existing script: https://github.com/bbc-mc/sdweb-merge-board

**Comment by victorca25** [comment]
I already do this with a script I use. For example, define model's paths and their base models: 
<img width="377" alt="Screenshot 2022-12-02 at 19 52 59" src="https://user-images.githubusercontent.com/41912303/205365226-f6a7ac73-e66a-4bee-bef9-afea702a67cd.png">

And then just run a "pipeline" of merging steps to save only the final result.

A consideration of doing it in the UI would be managing the VAE. Also, I think you are proposing two separate ideas, correct me if I'm wrong:
1) Merging models and using them on the fly
2) Saving merging pipelines in a YAML file and load these merged models in the interface as if they were a model on disk

The syntax of the extension seems overly complicated for what it does, doesn't it?

I can help if somebody wants to look into this.

**Comment by whosawhatsis** [comment]
The idea is to merge models on the fly, so that you can use them without ever needing to save the file, yes. Since the whole model needs to sit in RAM (VRAM I think, though on M1 it's the same thing), and the merging process doesn't seem to take much longer than reading the models from the disk into ram, it makes sense to save the disk space.

This would require somewhere to put the formula/pipeline, and extending config.yaml's syntax to allow it seems like as good a place as any. An alternative would be to leave config.yaml's syntax alone, and instead let it reference a formula file instead of a .ckpt file.

**Comment by xraxra** [comment]
@whosawhatsis @victorca25 have either of you gotten merged checkpoints from A1111 working correctly in InvokeAI ? 

On my end, with the same generation settings & VAE, it looks completely different to Automatic1111, not sure why

**Comment by whosawhatsis** [comment]
I have used checkpoints merged in a1111 in invoke. I do get different results with most of my prompts in invoke vs a1111, but that seems to be down to writing prompts that are too long. A1111 uses the whole thing, while invoke silently drops everything beyond 77 tokens, or whatever the limit is

**Comment by whosawhatsis** [comment]
See also: https://github.com/bmaltais/dehydrate

**Comment by hipsterusername** [comment]
@victorca25 this would be insanely cool. Doing just in time merges would be a huge space save, and more interestingly, accelerate the process of model experimentation.

let me know what you’d need support on to evaluate contributing!

**Comment by whosawhatsis** [comment]
Another use for this. Apparently, you can turn any model into an inpainting model using an add-difference merger. This feature would make it possible to use any model as an inpainting model without doubling the number of models you need to store. https://www.reddit.com/r/sdforall/comments/zyieht/how_to_turn_any_model_into_an_inpainting_model/

**Comment by hipsterusername** [comment]
@whosawhatsis very interesting find

**Comment by brucethemoose** [comment]
One potential issue with this idea is RAM usage. My 16GB laptop swaps when merging when a UI is open and python is keeping other stuff loaded in RAM, especially when merging FP32 models with VAEs.

**Comment by brucethemoose** [comment]
Also, perhaps the Node UI could be leveraged for this feature?

**Comment by whosawhatsis** [comment]
The whole model is normally stored in VRAM while it's loaded anyway, and you're not going to be generating images and loading models at the same time, so I don't see this being a problem...

**Comment by brucethemoose** [comment]
> The whole model is normally stored in VRAM while it's loaded anyway, and you're not going to be generating images and loading models at the same time, so I don't see this being a problem...

Yeah but when you merge, 2 models (and potentially their VAEs) are loaded into RAM, right? And thats on top of whatever Invoke and the system is using at idle

**Comment by whosawhatsis** [comment]
> > The whole model is normally stored in VRAM while it's loaded anyway, and you're not going to be generating images and loading models at the same time, so I don't see this being a problem...
> 
> Yeah but when you merge, 2 models (and potentially their VAEs) are loaded into RAM, right? And thats on top of whatever Invoke and the system is using at idle

Only during the merge. That RAM would have to be reclaimed before trying to do image generation.

It would be nice to have a reduction in the idle RAM/VRAM usage (not sure which it is, since I'm using unified RAM). Particularly, it seems to grab a chunk of it for each distinct size of image you generate, larger for larger images, of course, and not free it up when you generate a different size image, and it grabs a new chunk for that image size.

**Comment by brucethemoose** [comment]
On CUDA platforms, I think memory reclamation is "lazy" since transfers are so costly, but you can get it to be more aggressive with some env variables: https://pytorch.org/docs/stable/notes/cuda.html#memory-management

IDK about background RAM usage. Invoke takes up some of both when idle (though I can't see how much atm since I am having an issue with launching/installing it).
