### ISSUE TITLE
[bug]: When using the RunwayML inpainting model, negative prompts do not work at all, which is not documented

### ISSUE THREAD

**Issue by n00mkrad** [invoke-ai/InvokeAI#1590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24 GB

### What happened?

When trying to use a negative prompt (unconditioning) in combination with the RunwayML inpainting model, the words instead get picked up as part of the regular prompt.

To reproduce, run this for example:

`portrait photo [monochrome]`

SD 1.5 will never show a monochrome image, while SD 1.5 inpainting will always do as it interprets it as part of the prompt.

I assume this is an architectural limitation, however I did not find any mention of this in the documentation.

**Comment by damian0815** [comment]
@lstein any idea? i know the inpainting model runs a different code path, maybe somewhere in the hybrid conditioning the negative words are being mixed up

**Comment by yoniker** [comment]
I was about to open an issue exactly about that just now :)
Running 1.5 inpainting on a linux machine (so it's probably not the environment).

**Comment by n00mkrad** [comment]
I did some testing; this always happens with that model, doesn't matter if it's txt2img, img2img, or masked inpainting.

**Comment by n00mkrad** [comment]
Weighting also does not work - None of the prompt features do, it seems.

**Comment by yoniker** [comment]
@lstein I think that you might be busy with the 2.x models, is this a trivial fix or a time-consuming fix?

**Comment by mrbaca14** [comment]
I have the same issue confirmed.  Negative prompts with the inpainting 1.5 model does not work with the [brackets] for negative prompts.  Confirmed negative prompts work as intended with all OTHER models.
