### ISSUE TITLE
[bug]: Auto install fail

### ISSUE THREAD

**Issue by Zyluhc** [invoke-ai/InvokeAI#1591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cpu

### VRAM

16GB

### What happened?

Well nothing more classic, the installer faces an error : 
"FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\Zyluh\AppData\Local\Temp\pip-install-rp8jp814\basicsr_01eb55367168478e92aa382b83ca38e7\.eggs\torch-1.13.0-py3.10-win-amd64.egg\caffe2\python\serialized_test\data\operator_test\learning_rate_adaption_op_test.test_learning_rate_adaption_op_normalization.zip'"
"metadata-generation-failed"

Probably something I missed when installing, considering I had a similar bug with a more manual installation. Any help ?

### Contact Details

Zyluh#2389

**Comment by lstein** [comment]
I'm sorry to hear this. Could you please post a full log of the session, from the time you typed the first command?

Thanks

**Comment by Zyluhc** [comment]
Sure ! Fyi, I have both python 3.10,3.11 and Ananconda3 2021.11.

[InvokeAI Log.txt](https://github.com/invoke-ai/InvokeAI/files/10103769/InvokeAI.Log.txt)

Thanks for the ffast reply and for trying to help me !

**Comment by Zyluhc** [comment]
Bumping. I've seen someone running into the same issue on discord and we're both looking to work through it ^^"

**Comment by isisrae7** [comment]
OS
Windows

GPU
cpu

VRAM
8GB

Hello,

I am very new to this and I think I am having the same issue. I am just trying the easy install. I have already closed my session but saved this. I will save differently next time. 

InvalidArchiveError("Error with archive D:\\Users\\isisr\\Staging\\invokeAI-src-installer-2.2.3-windows\\invokeAI\\installer_files\\env\\pkgs\\pytorch-1.12.1-py3.10_cuda11.6_cudnn8_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message was:\n\nfailed with error: [Errno 2] No such file or directory: 'D:\\\\Users\\\\isisr\\\\Staging\\\\invokeAI-src-installer-2.2.3-windows\\\\invokeAI\\\\installer_files\\\\env\\\\pkgs\\\\pytorch-1.12.1-py3.10_cuda11.6_cudnn8_0\\\\Lib\\\\site packages\\\\torch\\\\include\\\\ATen\\\\ops\\\\fake_quantize_per_tensor_affine_cachemask_backward_compositeimplicitautograd_dispatch.h'")
""
"Something went wrong while installing Python libraries and cannot continue."
"See https://invoke-ai.github.io/InvokeAI/INSTALL_SOURCE#troubleshooting for troubleshooting"
"tips, or visit https://invoke-ai.github.io/InvokeAI/#installation for alternative" "installation methods"
Press any key to continue . . .

**Comment by wifiuk** [comment]
+1 for this issue with "[pytorch-1.12.1-py3.10_cuda11.6_cudnn8_0.tar.bz2]"

**Comment by 3nt3l** [comment]
I found a fix, you need to run the "WinLongPathsEnabled.reg" in the invoke ai folder

**Comment by isisrae7** [comment]
Thanks!
I am all set now! On to creation!
