### ISSUE TITLE
[bug]: It's not possible to pass an init strength of 0 when using RunwayML inpainting

### ISSUE THREAD

**Issue by n00mkrad** [invoke-ai/InvokeAI#1593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24 GB

### What happened?

When using the RunwayML inpainting model, init strength has no effect (as expected).

I would like to pass a strength of 0 for later metadata reference, to make clear that no traditional img2img/mask-based inpainting was used.

However, the code errors with `img2img and inpaint strength can only work with 0.0 < strength < 1.0`, even though strength value is not used at all with the RunwayML model.

**Comment by lstein** [comment]
Got it. The values are checked in the argument parsing routine. The easiest fix would be to allow strength to go all the way down to zero for all models, in which case it would be a null operation on the non-runway models. Hopefully this won't break anything.
