### ISSUE TITLE
[bug]: esrgan is disabled. Unable to upscale using prompt2image in Generate()

### ISSUE THREAD

**Issue by gvijqb** [invoke-ai/InvokeAI#1597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What happened?

I am using upscale=[2,0.75] as a kwarg in prompt2image on sending a request but when running it I get an error: 
**"ESRGAN is disabled. Image not upscaled."**

I have all the possible methods allowed in prompt2image but it is still returning this error. Is there a way to upscale the image when creating using rest API?

My code is as follows:

```
from ldm.generate import Generate
g   = Generate()
outputs = g.prompt2image(
            prompt         =    prompt,
            outdir         =    'outputs/img-samples',
            iterations     =    iterations,
            steps          =    steps,
            sampler_name   =    sampler,
            width          =    width,
            height         =    height,
            cfg_scale      =    cfg_scale,
            upscale        =    [2,0.75]
)
```

**Comment by gvijqb** [comment]
Can anyone help on this?

**Comment by psychedelicious** [comment]
Hi @gvijqb , sorry for the late response here. You mentioned REST API, but the code is interacting directly with the `Generate` class. 

In this case, you need to first load ESRGAN.

See the first line here and the block towards the bottom for setting up:
https://github.com/invoke-ai/InvokeAI/blob/development/ldm/invoke/CLI.py#L62-L102

And here is the function that is called to load the restoration modules:
https://github.com/invoke-ai/InvokeAI/blob/development/ldm/invoke/CLI.py#L837-L856

Once you do this, the instantiated `Generate` class will be able to do upscaling (and face correction if you also loaded GFPGAN/CodeFormer).

**Comment by gvijqb** [comment]
@psychedelicious Thanks this worked!
