### ISSUE TITLE
[bug]: patchmatch warning

### ISSUE THREAD

**Issue by mickr777** [invoke-ai/InvokeAI#1627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12gb

### What happened?

this warning may confuse the end user "warning - patchmatch failed to load or compile" when starting invoke.py

Dispite this warning it still initialises and works

**Comment by Gobiff87** [comment]
I have the same issue so I will be also watching this thread for any update solutions.

**Comment by guyalo** [comment]
Same issue, I also watching

**Comment by Lolagatorade** [comment]
Yeah same as of the 13'th, tried reinstalling it switching from opencv to opencv-cuda, and running update.sh or install.sh

**Comment by benbaarber** [comment]
I solved this by following the instructions here: https://invoke-ai.github.io/InvokeAI/installation/060_INSTALL_PATCHMATCH/?h=patchmatch

**Comment by Lolagatorade** [comment]
> I solved this by following the instructions here: https://invoke-ai.github.io/InvokeAI/installation/060_INSTALL_PATCHMATCH/?h=patchmatch

Thats literally the first thing to try, this page you linked is the regurgitation from the error. btw the official github page was pulled with a 404. same thing happpened about a week or two ago as only debian instructions were posted then 404 then it was added arch instructions...

from patchmatch import patch_match = nothing no response from python

https://github.com/invoke-ai/InvokeAI/blob/main/docs/installation/INSTALL_PATCHMATCH.md = 404 error

Starting the InvokeAI browser-based UI..
>> patchmatch.patch_match: WARNING - patchmatch failed to load or compile.
>> patchmatch.patch_match: WARNING - **Refer to https://github.com/invoke-ai/InvokeAI/blob/main/docs/installation/INSTALL_PATCHMATCH.md** for installation instructions.
>> Patchmatch not loaded (nonfatal)

**Comment by Lolagatorade** [comment]
> > I solved this by following the instructions here: https://invoke-ai.github.io/InvokeAI/installation/060_INSTALL_PATCHMATCH/?h=patchmatch
> 
> Thats literally the first thing to try, this page you linked is the regurgitation from the error. btw the official github page was pulled with a 404. same thing happpened about a week or two ago as only debian instructions were posted then 404 then it was added arch instructions...
> 
> from patchmatch import patch_match = nothing no response from python
> 
> https://github.com/invoke-ai/InvokeAI/blob/main/docs/installation/INSTALL_PATCHMATCH.md = 404 error
> 
> Starting the InvokeAI browser-based UI..
> 
> > > patchmatch.patch_match: WARNING - patchmatch failed to load or compile.
> > > patchmatch.patch_match: WARNING - **Refer to https://github.com/invoke-ai/InvokeAI/blob/main/docs/installation/INSTALL_PATCHMATCH.md** for installation instructions.
> > > Patchmatch not loaded (nonfatal)

Small update. reinstalled invokeai through pip instead of using the autoinstaller. New errors but no fix :(
