### ISSUE TITLE
[bug]: How do you update InvokeAI?

### ISSUE THREAD

**Issue by ninjasaid2k** [invoke-ai/InvokeAI#1644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What happened?

I've tried updating by git pull and it did not work, is there a good documentation or tutorial on how to update it?

`C:\Users\ninja\InvokeAI>git pull
fatal: not a git repository (or any of the parent directories): .git`

I'm not seeing any solution on the documentation.

**Comment by psychedelicious** [comment]
Hi @ninjasaid2k 

`git pull` will sync your local InvokeAI if and only if you initially installed it by running `git clone` and then making a venv e.g. via `conda`. Given the error message, I think you have installed via install script. In this case, you can update it by re-running the install script. 

However, we will have v2.2 releasing in the coming days (it is in a RC stage now). Suggest holding off for that to get the newest goodies.
