### ISSUE TITLE
[bug]: Expected conjunction 2.0

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#1648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

greetings,

prompt: (cube:0.15), (sphere:1.3) 
script error:
Server error: Expected {conjunction | implicit_conjunction}, found end of text (at char 5), (line:1, col:6)

**Comment by damian0815** [comment]
hi, are you trying to do weighting or a blend? in either case the syntax isn’t correct. please check https://invoke-ai.github.io/InvokeAI/features/PROMPTS/#masking-using-text

**Comment by Neosettler** [comment]
thank you @damian0815, in the spirit of having some kind of standard, importing automatic1111 preset parameters, prompt in this case, fails because of this. While this is a bit of a stretch you'd say, there is no legitimate reason why this would crash Invoke AI. Point in case: (red cube:0.15), (green sphere:1.3) seems intuitive and should be valid imo.

**Comment by damian0815** [comment]
> (red cube:0.15), (green sphere:1.3) seems intuitive and should be valid imo.

if you're trying to blend, the correct syntax is `red cube:0.15 green sphere:1.3` or `("red cube", "green sphere").blend(0.15, 1.3)`. if you're trying to weight, the correct syntax is `(red cube)0.13 (green sphere)1.3`. it's not at all clear which of those your prompt is intending!

**Comment by Neosettler** [comment]
Thank you [damian0815](https://github.com/damian0815), I'm not entirely sure how Automatic1111 handles blending but here is a common examples of parameters minus the negative prompt:

(illustration style:1.3), ((Vogue, Magasine Cover:0.25)), ((best quality)), ((masterpiece)), ((ultra-detailed)),((official art)),(an extremely delicate and beautiful), (beautiful detailed eyes),1girl, wearing sarashi on chest:1.3), (chest bandages:1.3, bandages covering breasts, a little blood splatter, wall covered in graffiti art, dynamic colours, vibrant colours, depth of field, natural scenery, spring leaves, god rays, dynamic lighting (illustration style:1.3)

My point is, when using Automatic1111 prompt as an Invoke AI prompt as is, not having the same result is one thing, having a crash is not acceptable. 

I believe Invoke AI should handle the blending as Automatic1111 to have some kind of standard with the current most popular API but that's just me.

**Comment by damian0815** [comment]
auto1111 doesn't support blending at all.

**Comment by Neosettler** [comment]
Again, let me clarify. 

This report is not about "blending" it's about fixing a crashing issue. Even thought the "blending" might not work as intended, (sphere:1.3) should not crash Invoke.py.
