### ISSUE TITLE
[bug]: Intermittent Unified Canvas masking bug

### ISSUE THREAD

**Issue by Fortyseven** [invoke-ai/InvokeAI#1649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

24gb

### What happened?

This is going to be vague, unfortunately, but I wanted to note a bug I'd just experienced, in case anyone else encounters it.

I was working over a project in the unified canvas and it'd been at least an ~hour or so straight of in and oupainting, masking in new items, etc.

But eventually I noticed behavior that seemed to suggest the masks and transparent areas were being ignored entirely, and the entire bounding box would be affected.

I'll try and trigger it again to see if I can flesh this report out a bit more...

**Comment by Fortyseven** [comment]
Additional vague note -- something relating to masking seemed to be interfering with txt2img results. 

Again, this sounds nuts, but I'll try and keep track of what I do... but it's so random. The only consistent element is that it happens after a long period of use.

**Comment by SolidLuigi** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### OS
> Linux
> 
> ### GPU
> cuda
> 
> ### VRAM
> 24gb
> 
> ### What happened?
> This is going to be vague, unfortunately, but I wanted to note a bug I'd just experienced, in case anyone else encounters it.
> 
> I was working over a project in the unified canvas and it'd been at least an ~hour or so straight of in and oupainting, masking in new items, etc.
> 
> But eventually I noticed behavior that seemed to suggest the masks and transparent areas were being ignored entirely, and the entire bounding box would be affected.
> 
> I'll try and trigger it again to see if I can flesh this report out a bit more...

Did you ever figure out what was causing this? I seem to be having the same issue at times. I'll try masking to change and masking to preserve and the unified canvas seems to ignore both. Other times, it seems to work fine. I can't figure out what would be causing this.. Thanks,

**Comment by Fortyseven** [comment]
Most of the issues I had, back around the time I filed this, aren't happening anymore. :disappointed: 

> The masking features only work when using the Inpaint 1.5 model ckpt. If I'm using any of the custom models I've downloaded or made myself the unified canvas will just regenerate the entire bounding box.

This definitely isn't the expected behavior. I rarely use the inpainting model and masking is integral to everything folks do on the canvas. Hopefully someone closer to the code has some thoughts on this!

**Comment by atix07** [comment]
This happened to me yesterday (04/08/2023) with the newest version. After adding so many new stuff (1-2 hour later), masked area was completely ignored and entire bounding box was re-generated. Tried clearing canvas, downloading the image and opening a new canvas with that image but it didn't seem to fix it.
