### ISSUE TITLE
[bug]: weights argument not supported in 2.0

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#1652]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

while the doc claims it works still, it doesn't. 

    if args.weights:
        print('--weights argument has been deprecated. Please edit ./configs/models.yaml, and select the weights using --model instead.')
        sys.exit(-1)

**Comment by lstein** [comment]
Thanks for filing this and the other bug reports. I will work through them systematically.

**Comment by Neosettler** [comment]
Consider removing it altogether as it's just dead code at this point.
