### ISSUE TITLE
[bug]: The preview function doesn't work for me

### ISSUE THREAD

**Issue by CreationStory** [invoke-ai/InvokeAI#1653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

4GB

### What happened?

No matter what I try, Display In-Progress Images and Save images every n steps have no effect. I am stuck  with a base preview of just noise for the first 90% of renders, then I get a few updates and then the full render.

Is anyone else not able to see their image being generated in the timesteps?

### Screenshots

![image](https://user-images.githubusercontent.com/83620116/204978335-2f1c45e6-36a1-4e3d-8cf8-d7e60585f332.png)

**Comment by blessedcoolant** [comment]
Do you have the same issue even with Fast mode on the display progress?

**Comment by CreationStory** [comment]
Yes and there doesnt seem to be any difference for any of the three options strangely. ~None will still show a noise image for 90% of the render, Fast does and so does Accurate. I wonder where this glitch is originating

**Comment by CreationStory** [comment]
No longer an issue in newest release
