### ISSUE TITLE
[bug]: from_file documentation is ambiguous

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#1654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

```
You may read a series of prompts from standard input by providing a filename of -:
(invokeai) ~/stable-diffusion$ echo "a beautiful day" | python3 scripts/invoke.py --from_file -
```
This example doesn't show how to provide several prompts. Does it need any other arguments?

A better example would start with:
(invokeai) ~/stable-diffusion$ echo "a beautiful day" | "a rainy day" python3 scripts/invoke.py --from_file - 

In addition, this feature requires to load the script/model every time it is being called. Not very practical. Consider migrating this to render group and/or implementing a proper render queue instead, which would tied up nicely with | operator/matrices

https://github.com/invoke-ai/InvokeAI/discussions/473
https://github.com/invoke-ai/InvokeAI/issues/566
https://github.com/invoke-ai/InvokeAI/issues/1008

**Comment by Neosettler** [comment]
Could anyone confirm how to use --from_file - with multiple prompts? Also, could this feature be used in interactive mode instead?

thank you,

**Comment by lstein** [comment]
Write a text file with one prompt per line. Name it `my-prompts.txt`. Then feed it into invoke.py like this:
```
invoke.py --from_file=my-prompts.txt
```

**Comment by Neosettler** [comment]
@lstein I'm talking about the other [from_file ](https://invoke-ai.github.io/InvokeAI/features/PROMPTS/?h=from_file#reading-prompts-from-a-file)function:

> You may read a series of prompts from standard input by providing a filename of -:
> (invokeai) ~/stable-diffusion$ echo "a beautiful day" | python3 scripts/invoke.py --from_file -
