### ISSUE TITLE
[bug]: installer fail

### ISSUE THREAD

**Issue by XanderBos** [invoke-ai/InvokeAI#1655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

11

### What happened?

When I run the installer it prompts: 

***** Installing InvokeAI.. *****
"USING development BRANCH. REMEMBER TO CHANGE TO main BEFORE RELEASE"
'#set' is not recognized as an internal or external command,
operable program or batch file.
'#' is not recognized as an internal or external command,
operable program or batch file.
'RELEASE_SOURCEBALL' is not recognized as an internal or external command,
operable program or batch file.
Could Not Find X:\InvokeAI-main\installer\micromamba.exe
Trying to download "https://github.com/invoke-ai/InvokeAI"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
----- InvokeAI source download failed -----
Press any key to continue . . .

I have no idea what it means. It would be great if someone can point me in the right direction.

### Screenshots

![asdasdasd](https://user-images.githubusercontent.com/8150949/205006609-c1eed0b3-53fc-4a2b-a693-66946d511b94.PNG)

### Contact Details

sandarbos@gmail.com

**Comment by illtellyoulater** [comment]
same here...

**Comment by lstein** [comment]
I have updated the installer files. The windows one is here: https://github.com/invoke-ai/InvokeAI/releases/download/2.2.0-rc2/invokeAI-src-installer-windows.zip

Apparently the AV software doesn't want you to install the `micromamba` or `git` packages and will need to be temporarily disabled. I don't know why this might be happening, but I've asked some of our Windows devs for help.

Which AV are folks using? In the short term I will update the installation documentation to flag this as a potential issue.

**Comment by jasonmhead** [comment]
Ran into this issue using AVG

**Comment by XanderBos** [comment]
I managed to get it to work by indeed turning my avast firewall off. thanks for the quick response :)
