### ISSUE TITLE
Error loading Voxel Art model

### ISSUE THREAD

**Issue by Venj-ADL** [invoke-ai/InvokeAI#1657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What happened?

When trying to load the Voxel Art model on a fresh install I get the following error:

 Loading voxel_art-1.0 from C:\Users\venjs\invokeai\models\ldm\stable-diffusion-v1\VoxelArt_v1.ckpt
   | LatentDiffusion: Running in eps-prediction mode
   | DiffusionWrapper has 859.52 M params.
   | Making attention of type 'vanilla' with 512 in_channels
   | Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
   | Making attention of type 'vanilla' with 512 in_channels
** model voxel_art-1.0 could not be loaded: Error(s) in loading state_dict for LatentDiffusion:
        size mismatch for embedding_manager.string_to_param_dict.*: copying a param with shape torch.Size([1, 768]) from checkpoint, the shape in current model is torch.Size([8, 768]).
        size mismatch for embedding_manager.initial_embeddings.*: copying a param with shape torch.Size([1, 768]) from checkpoint, the shape in current model is torch.Size([8, 768]).
Traceback (most recent call last):
  File "c:\users\venjs\documents\github\invokeai\ldm\invoke\model_cache.py", line 80, in get_model
    requested_model, width, height, hash = self._load_model(model_name)
  File "c:\users\venjs\documents\github\invokeai\ldm\invoke\model_cache.py", line 232, in _load_model
    model.load_state_dict(sd, strict=False)
  File "C:\Users\venjs\Documents\GitHub\invokeAI\installer_files\env\envs\invokeai\lib\site-packages\torch\nn\modules\module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LatentDiffusion:
        size mismatch for embedding_manager.string_to_param_dict.*: copying a param with shape torch.Size([1, 768]) from checkpoint, the shape in current model is torch.Size([8, 768]).
        size mismatch for embedding_manager.initial_embeddings.*: copying a param with shape torch.Size([1, 768]) from checkpoint, the shape in current model is torch.Size([8, 768]).

### Screenshots

![Screenshot_20221201_092005](https://user-images.githubusercontent.com/76688057/205034063-9992a449-159e-4aa8-9aa0-d6e150169694.png)

### Contact Details

venj.systems@gmail.com

**Comment by damian0815** [comment]
hmm. can you try something a bit hacky? can you go into `configs\stable-diffusion\v1-inference.yaml`, find `personalization_config:` and a few lines below that, change `num_vectors_per_token:` from `8` to `1`?

**Comment by Venj-ADL** [comment]
Yep I will do that as soon as the 1000 image batch i'm running finishes in 3 hours :P

**Comment by Venj-ADL** [comment]
Ok, yep that seems to have done the trick. Does this need to be set back to "8" for the standard models?

>> Scanning Model: voxel_art-1.0
>> Model Scanned. OK!!
>> Loading voxel_art-1.0 from C:\Users\venjs\invokeai\models\ldm\stable-diffusion-v1\VoxelArt_v1.ckpt
   | LatentDiffusion: Running in eps-prediction mode
   | DiffusionWrapper has 859.52 M params.
   | Making attention of type 'vanilla' with 512 in_channels
   | Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
   | Making attention of type 'vanilla' with 512 in_channels
   | Using faster float16 precision
   | Loading VAE weights from: C:\Users\venjs\invokeai\models\ldm\stable-diffusion-v1\vae-ft-mse-840000-ema-pruned.ckpt

**Comment by damian0815** [comment]
it should be fine to leave it at 1, this code is only used when there’s a textual inversion embedding being loaded, so it’s a bit weird that the voxel model uses it. i’ll have to investigate.

**Comment by Venj-ADL** [comment]
Excellent! thanks so much for the quick fix :)

**Comment by damian0815** [comment]
fixed by #1730
