### ISSUE TITLE
[bug]: Inconsistent basicsr, torch, torchvision version in the requirement files

### ISSUE THREAD

**Issue by addianto** [invoke-ai/InvokeAI#1663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6 GB

### What happened?

> EDIT: I was trying to re-install InvokeAI based on commit eba31e7caf20a915148fb11608eae09b772539c6.

Hi there. I noticed the versions of several packages listed in the requirement files used by the Windows installer script (i.e. in `installer` folder) and manual installation (i.e. the requirement files in `environments-and-requirements` folder) are not consistent.
Will it be okay to have different packages versions when installing the app using manual or automatic (script-based)?

I noted the packages in the following table, along with the version difference:

| Package | Manual Installation Version | Installer Version |
|--------- |-----------------------------|-----------------|
| `basicsr` | `1.4.1` | `1.4.2` |
| `torch` | `1.12.1` | `1.12.0+cu116` |
| `torchvision` | `0.13.1` | `0.13.0+cu116` |

I haven't checked the base dependencies and the dependencies for other platforms (Mac & Linux).

### Screenshots

The following is a screenshot that shows `basicsr` version in `requirements-win-colab-cuda.txt` is different from the version in `py3.10-windows-x86_64-cuda-reqs.txt`:

![image](https://user-images.githubusercontent.com/955505/205073140-1c009b5c-cccc-4bf8-a481-e91c43b65d81.png)

Similarly, `torch` and `torchvision` also listed with different versions in both installer and requirement files.

**Comment by damian0815** [comment]
the py3.10-*-reqs files are out of date, but the "binary" installer makes its own python virtual environment so there should be no versioning issues

**Comment by addianto** [comment]
I see. My concern is more toward the differences of packages listed in the binary installer (`./installer`) directory and the manual installer (`./environments-and-requirements`). I understand if the packages may still change because the ongoing 2.2 release process.

Anyway, I look forward to the 2.2 release. 👍
