### ISSUE TITLE
[bug]: #include <sys/types.h> - file not found

### ISSUE THREAD

**Issue by aitrailblazer** [invoke-ai/InvokeAI#1666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

16GB

### What happened?

conda env update    
Apple Silicon M1, 16GB, MacOS Ventura
sers/tisvr01-m1/miniconda/envs/invokeai/include -arch arm64 -fPIC -O2 -isystem /Users/tisvr01-m1/miniconda/envs/invokeai/include -arch arm64 -Ilib/py-lmdb -Ibuild/lib -I/Users/tisvr01-m1/miniconda/envs/invokeai/include/python3.10 -c build/lib/mdb.c -o build/temp.macosx-11.0-arm64-cpython-310/build/lib/mdb.o -DHAVE_PATCHED_LMDB=1 -UNDEBUG -w
      build/lib/mdb.c:65:10: fatal error: 'sys/types.h' file not found
      #include <sys/types.h>
               ^~~~~~~~~~~~~
      1 error generated.
      error: command '/Library/Developer/CommandLineTools/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lmdb

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

failed

CondaEnvException: Pip failed

**Comment by damian0815** [comment]
which installer are you using? (please post a link)

can you try reinstalling the Xcode Command Line Tools? in a terminal window: 
```
xcode-select --install
```

**Comment by aitrailblazer** [comment]
I'm using the following instructions:
https://github.com/invoke-ai/InvokeAI/blob/2.1.3-rc6/docs/installation/INSTALL_MANUAL.md

xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" in System Settings to install updates
