### ISSUE TITLE
[bug]: Invoke.bat not created in folder

### ISSUE THREAD

**Issue by samaBR85** [invoke-ai/InvokeAI#1672]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12Gb

### What happened?

The installer goes well but to the very end it stops at "installing invoke.bat". In the folder there're all files but invoke.bat.

### Screenshots

** Model Installation Successful **
You're all set! You may now launch InvokeAI using one of these two commands:
Web version:
    python scripts/invoke.py --web  (connect to http://localhost:9090)
Command-line version:
   python scripts/invoke.py

If you installed manually, remember to activate the 'invokeai'
environment before running invoke.py. If you installed using the
automated installation script, execute "invoke.sh" (Linux/Mac) or
"invoke.bat" (Windows) to start InvokeAI.

Have fun!

***** Finished downloading models *****
***** Installing invoke.bat ******
The system cannot find the file specified.
All done! Execute the file invoke.bat in this directory to start InvokeAI
Press any key to continue . . .

![Screenshot_10](https://user-images.githubusercontent.com/119633278/205170491-bca4315f-0f46-4657-9a4b-dfdb03327586.png)

**Comment by dhelonious** [comment]
Same issue for me

**Comment by Pierrot1969** [comment]
I have the same problem.

**Comment by Rogal80** [comment]
same here
![obraz](https://user-images.githubusercontent.com/112553453/205176493-837e367b-f5c4-47f9-8dd9-1813a963c1dc.png)

**Comment by rturner522** [comment]
Same

**Comment by Aksanya** [comment]
and now we wait

**Comment by ClickToConfirm** [comment]
Well, any updates on this issue?

**Comment by Niphion** [comment]
Same for me :(

**Comment by slizgi** [comment]
Same here...

**Comment by nickcychong** [comment]
Same here, no invoke.bat

**Comment by Aksanya** [comment]
I solved it by using this installer: [invokeAI-src-installer-windows.zip](https://github.com/invoke-ai/InvokeAI/releases/download/2.2.0-rc3/invokeAI-src-installer-windows.zip)

Note: On "Installing pip dependencies", it takes a while, it will eventually move on.

**Comment by Eprise1701e** [comment]
> I solved it by using this installer: [invokeAI-src-installer-windows.zip](https://github.com/invoke-ai/InvokeAI/releases/download/2.2.0-rc3/invokeAI-src-installer-windows.zip)
> 
> Note: On "Installing pip dependencies", it takes a while, it will eventually move on.

This is the zip I used to install, and no invoke.bat either. Tried installing again and no luck...

**Comment by Aksanya** [comment]
> 

You sure? The one I linked is not the same version as in the github page

**Comment by Pierrot1969** [comment]
It worked for me too. The .bat file has appeared.

**Comment by samaBR85** [comment]
> In the installer you can edit this line -
> 
> echo ***** Installing invoke.bat ****** change this line to this >>copy binary_installer\invoke.bat.in .\invoke.bat echo All done! Execute the file invoke.bat in this directory to start InvokeAI

thanks! it worked

**Comment by JAMadison** [comment]
> echo ***** Installing invoke.bat ******
copy installer\invoke.bat .\invoke.bat >> Change to "copy binary_installer\invoke.bat.in .\invoke.bat"
echo All done! Execute the file invoke.bat in this directory to start InvokeAI


Should work

**Comment by Niphion** [comment]
> I solved it by using this installer: [invokeAI-src-installer-windows.zip](https://github.com/invoke-ai/InvokeAI/releases/download/2.2.0-rc3/invokeAI-src-installer-windows.zip)
> 
> Note: On "Installing pip dependencies", it takes a while, it will eventually move on.

This worked for me too and I also did another thing wrong, I didn't make a new token and put it on "READ" I copied a token that I made a while ago, that was set to "WRITE" And I can imagine, this might be something that caused the issue.

**Comment by Eprise1701e** [comment]
> > > I solved it by using this installer: [invokeAI-src-installer-windows.zip](https://github.com/invoke-ai/InvokeAI/releases/download/2.2.0-rc3/invokeAI-src-installer-windows.zip)
> > > Note: On "Installing pip dependencies", it takes a while, it will eventually move on.
> > 
> > 
> > This is the zip I used to install, and no invoke.bat either. Tried installing again and no luck...
> 
> You sure? The one I linked is not the same version as in the github page

My apologies, I thought it was the same. Tried it and it worked. Much appreciated.

**Comment by rturner522** [comment]
Link is no longer valid... :(

Anyone have a copy I can have?

**Comment by FoneCheck** [comment]
I have the same problem and the link is no longer valid

**Comment by TheRealPhooney** [comment]
I had this problem too.  What I've ended up doing is taking the invoke.bat.in file from the binary_installer folder and copied it into the root folder where invoke.bat was supposed to go.  I then removed the .in file extension, leaving it as invoke.bat.

Ran it and it appears to work.  I haven't tried all features yet, so I don't know if there's some roadblock waiting for me but I did a test image and it generated just fine.

**Comment by RafuTH** [comment]
> I had this problem too. What I've ended up doing is taking the invoke.bat.in file from the binary_installer folder and copied it into the root folder where invoke.bat was supposed to go. I then removed the .in file extension, leaving it as invoke.bat.
> 
> Ran it and it appears to work. I haven't tried all features yet, so I don't know if there's some roadblock waiting for me but I did a test image and it generated just fine.

That did the trick for me, thanks!

**Comment by egormly** [comment]
I also copied the file, renamed and it ran, but I am stuck in a loop. I run it, it asks for model downloads, I skip that, it just closes the window.  I even tried downloading the models (again) and it still just closes and doesn't run.

**Comment by FoneCheck** [comment]
I have both the regular installation and the source code installation. This trick worked great for the source code installation but did not work for the regular installation. The regular installation starts but than cuts off.

**Comment by johnosbb** [comment]
Same issue here, just downloaded and installed, but no invoke.bat file created

**Comment by rturner522** [comment]
Still no update? Lame-sauce. 
Not trying to sound entitled I was just so excited to try this out.

**Comment by samaBR85** [comment]
Corrected in version 2.2.3

**Comment by FICOESBEJO** [comment]
The installer goes well but to the very end it stops at "installing invoke.bat". In the folder there're all files but invoke.bat.

**Comment by cwallace** [comment]
I'm having the same issue with 2.2.3. Copying invokeai.bat.in to the base folder and renaming does not work either producing the following error:

`The system cannot find the path specified.`
`'deactivate' is not recognized as an internal or external command,`
`operable program or batch file.`

**Comment by Mark-Artyniuk** [comment]
> I'm having the same issue with 2.2.3. Copying invokeai.bat.in to the base folder and renaming does not work either producing the following error:
> 
> `The system cannot find the path specified.` `'deactivate' is not recognized as an internal or external command,` `operable program or batch file.`

Exact Same issue here

**Comment by radimov** [comment]
I have the same problem, still haven't found a solution?

**Comment by PYur1970** [comment]
Tried installing Invoke AI using the 2.2.5 installer for windows on github. The install was completed, but like everyone else there is no .BAT file anywhere. Any ideas would be greatly appreciate.
