### ISSUE TITLE
[bug]: "Using recommended DDIM sampler for inpainting"

### ISSUE THREAD

**Issue by Neeqstock** [invoke-ai/InvokeAI#1679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What happened?

I saw that Web UI's Unified Canvas feature ignores the sampler selection (e.g. Euler_a), only letting me use DDIM. Why? At least, this is what the console says...

Is there a way to configure this?

### Screenshots

![2022-12-02_00-40](https://user-images.githubusercontent.com/15343295/205182052-435fcb04-ad06-46fd-a455-51090f545fcb.png)

**Comment by nelsonre** [comment]
I did some testing, It looks like when using the in-painting model in the unified canvas your sampler choice is respected. 
If you try to use any other model, your choice is ignored unless you use "ddim" , "plms"
It would nice to be able to use any sampler when in-painting with another model. Sometimes the inpainting model is not the best for all situations.
