### ISSUE TITLE
[enhancement]: Write prompt to a standard PNG EXIF field

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#1680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

We could write the prompt (with no other metadata) to a standard PNG EXIF e.g. Description. Then normal image viewers can at least see it.

**Comment by psychedelicious** [comment]
From NemesisFlux @ discord:
> Maybe just to help out people like me, a note could be put in the comments field, saying something like, "InvokeAI parameters for this image are stored in tEXt fields in the PNG file. You can examine them with the free third-party program, pngcheck."

**Comment by keturn** [comment]
Example implementation: https://gitlab.com/keturn/kikifusion/-/blob/890be52914713d33757c5b900b03ad91c735be21/src/qittnz6Lz/metadata.py#L77

`ImageIFD.ImageDescription` is probably the most widely-supported, but doesn't cope with multi-byte charsets like UTF-8 or UTF-16, so it's not great.

`ExifIFD.UserComment` does handle unicode and is supported by at least some applications.

I've noticed this request most often from Mac users. Is anyone able to point us to docs on which fields OS X displays in Finder and includes in its search index?
