### ISSUE TITLE
[enhancement]: Button to discard the current candidate image in the unified canvas

### ISSUE THREAD

**Issue by insanityfarm** [invoke-ai/InvokeAI#1681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I'm not sure what the terminology is that we're using, but suppose I'm in/outpainting and I generate 30 different images. There's a nice UI for me to page through them all, but I'd like a way to toss out the ones that are no good. This would make it easier for me to flip back and forth between the ones I like more, to decide which to keep. There's a "Discard All" button but I'd really like a "Discard This One" type of button too.

### Alternatives

An alternative would be to show all of the candidate images in a gallery, and allow the thumbnails to be selected/unselected with a bulk delete button. Even better if that UI allows them to be reordered as well, but this is probably major overkill.

**Comment by Void2258** [comment]
Yes this would be handy. I have taken to doing no more than 4 gens at a time because any more and I can't keep track to choose the best one. It's very hit or miss.
