### ISSUE TITLE
[bug]: PYTORCH_ENABLE_MPS_FALLBACK=1 is not set

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#1693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What happened?

`PYTORCH_ENABLE_MPS_FALLBACK=1` is not set. It needs to be set before `invoke.py` is run, for MPS systems specifically.

**Comment by damian0815** [comment]
it should be being set in the invoke.sh in the root of the repo (not the one in scripts). i think this is preferable to patching .venv/bin/activate , but open to differing opinions.

**Comment by Cybergate9** [comment]
temporary work-around for those getting 'could not generate image' type errors on console when running on M1 Mac was for me to add the PYTORCH_ENABLE_MPS_FALLBACK setting into invoke.sh as suggested above.
e.g.

```
#!/usr/bin/env sh

export PYTORCH_ENABLE_MPS_FALLBACK=1
set -eu

. .venv/bin/activate
```

**Comment by damian0815** [comment]
this isn’t happening because #1660, which contained my work to implement it, was “superseded” and closed
