### ISSUE TITLE
[bug]: Windows src installer fails on exfat partition

### ISSUE THREAD

**Issue by kryztoval** [invoke-ai/InvokeAI#1701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24GB

### What happened?

Tried to install the windows source 2.2.0 script and it fails to install with an error

### Screenshots

![image](https://user-images.githubusercontent.com/5733028/205260762-e61a6b89-2d38-49f1-ad23-8d79bc77f946.png)

### Additional context

This seems to happen only if the partition is formatted as exFAT. Made a virtual drive with NTFS on the same exFAT partition and the installation seems to be going normally. Also tried in a native NTFS drive and it worked. However any exFAT drive I could find failed to run the installer.

**Comment by lstein** [comment]
I'm afraid we didn't test exFAT filesystem installs and this is a surprise.

Does this happen when you double-click or when you run the command from within the shell, or both?

**Comment by kryztoval** [comment]
Both, nothing changes whether it is double clicked or ran from the cmd prompt.
