### ISSUE TITLE
Windows install error: requirements file copy failed

### ISSUE THREAD

**Issue by zvit** [invoke-ai/InvokeAI#1710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

10GB

### What happened?

Installed using Window installer.
After it installs pip, I get the following error:

```
Successfully installed pip-22.3.1
***** Updated pip *****
The system cannot find the path specified.
----- requirements file copy failed -----
Press any key to continue . . .
```

Seems to be coming from this part of the install.bat file:

```
set err_msg=----- requirements file copy failed -----
copy installer\py3.10-windows-x86_64-cuda-reqs.txt requirements.txt
if %errorlevel% neq 0 goto err_exit
```

I don't have an "installer" folder, only "binary_installer" folder where that file resides.
I will change this in the bat file, or change the folder name from binary_installer to installer, run it again, and update this case.

### Contact Details

ztwersky@gmail.com

**Comment by zvit** [comment]
UPDATE:

Installed, but little error at end:

```
***** Finished downloading models *****
***** Installing invoke.bat ******
The system cannot find the file specified.
All done! Execute the file invoke.bat in this directory to start InvokeAI
Press any key to continue . . .
```

Had to manually copy and rename invoke.bat to root folder.

The issue now is that it's showing me the HTML code instead of the GUI:

![chrome_0mxgFujwUP](https://user-images.githubusercontent.com/9898388/205322201-2d03697a-56a5-4ca5-9e5c-746b2f03f23f.png)

**Comment by zvit** [comment]
UPDATE: 

I noticed that invoke.bat was referring to a "python scripts"folder that didn't exist:
`.venv\Scripts\python scripts\invoke.py --web`

But even after fixing that by changing it to:
`.venv\Scripts\invoke.py --web`

I still have the same issue.

**Comment by shanebirley** [comment]
I am experiencing this as well.

**Comment by GiusTex** [comment]
I too have the requirement file copy failed error. The strange thing is that yesterday it was working (the installation), while today (I had to re-do it, long story) it doesn't work..

**Comment by zvit** [comment]
> I too have the requirement file copy failed error. The strange thing is that yesterday it was working (the installation), while today (I had to re-do it, long story) it doesn't work.. Edit: I "solved" using another installer: "invokeAi-src-installer-2.2.3-windows.zip" (you can find it here: https://invoke-ai.github.io/InvokeAI/installation/INSTALL_SOURCE/#walk-through and also under "assets" here at the main page https://github.com/invoke-ai/InvokeAI/releases/tag/v2.1.3p1)

Ok, so this installation went smooth with no errors. However, when running the invoke.bat, the http://127.0.0.1:9090/ page gives me the same HTML instead of the GUI.

![chrome_1GoLOOVgjk](https://user-images.githubusercontent.com/9898388/205492012-b89f4680-94e0-47c6-a648-8ba663e57bc2.png)
