### ISSUE TITLE
Better install for win[enhancement]: 

### ISSUE THREAD

**Issue by 2blackbar** [invoke-ai/InvokeAI#1714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Can we just input a path to folder with our ckpt files on install ? this will solve a lot of issues, newcomers will have a hard time getting this ui to work, first - you need hface token otherwise 1.5 wont download, i have a token, no idea where to put it and i dont want to know where cause its a pita and i dont wanrt others to go through that as well hence the request , just give us ability to use own path cause i have a lot ckpt files in folder, let me point to them.
So UI installed, model wasnt downoad, bat file closes after awhile and no info nothing.... this isnt good, i dont even know where i should put ckpt file manually , wheres readme for that ? readme is quite vague.
Also please never ever install on C user or on C at all, this is a partition that gets formatted when system craps down and needs space for various other stuff , ID say detect where we unpacked invoke and where install.bat file is placed then use that path.... 
Please add a model path for ckpt files to readme, this is a must really...  cause now i have to look into every folder, every assumed config file to see where the path should point to.... this is not fun.
Please stop asking about default samplers and step count on install, this is strange and stalls , it can be easily changed later.
After installing UI I accidentally clicked on install.bat again not invoke.bat... wow, it took spliut second to ruin whole install. man this is NO GOOD.Ask for confirmation before doing that.

**Comment by psychedelicious** [comment]
We support auto importing of models now.
