### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by moldred** [invoke-ai/InvokeAI#1726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cpu

### What happened?

The install always stops at 
==============================================
.\tests\dev_prompts.txt
.\tests\legacy_tests.sh
.\tests\preflight_prompts.txt
.\tests\pr_prompt.txt
.\tests\test_prompt_parser.py
.\tests\validate_pr_prompt.txt
689 File(s) copied
***** Unpacked InvokeAI source *****
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 34.8M  100 34.8M    0     0   9.8M      0  0:00:03  0:00:03 --:--:-- 10.0M
***** Unpacked python-build-standalone *****
***** Created Python virtual environment *****
We're running under
Python 3.10.7
Requirement already satisfied: pip in c:\windows\system32\.venv\lib\site-packages (22.2.2)
Collecting pip
  Downloading pip-22.3.1-py3-none-any.whl (2.1 MB)
     ---------------------------------------- 2.1/2.1 MB 32.4 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.2.2
    Uninstalling pip-22.2.2:
      Successfully uninstalled pip-22.2.2
Successfully installed pip-22.3.1
***** Updated pip *****
The system cannot find the path specified.
----- requirements file copy failed -----
++++++++++++++++++++++++++++++++++++++++++++++

What's wrong? 

### Additional context

.\tests\dev_prompts.txt
.\tests\legacy_tests.sh
.\tests\preflight_prompts.txt
.\tests\pr_prompt.txt
.\tests\test_prompt_parser.py
.\tests\validate_pr_prompt.txt
689 File(s) copied
***** Unpacked InvokeAI source *****
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 34.8M  100 34.8M    0     0   9.8M      0  0:00:03  0:00:03 --:--:-- 10.0M
***** Unpacked python-build-standalone *****
***** Created Python virtual environment *****
We're running under
Python 3.10.7
Requirement already satisfied: pip in c:\windows\system32\.venv\lib\site-packages (22.2.2)
Collecting pip
  Downloading pip-22.3.1-py3-none-any.whl (2.1 MB)
     ---------------------------------------- 2.1/2.1 MB 32.4 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.2.2
    Uninstalling pip-22.2.2:
      Successfully uninstalled pip-22.2.2
Successfully installed pip-22.3.1
***** Updated pip *****
The system cannot find the path specified.
----- requirements file copy failed -----

### Contact Details

discord  moldred#1360 - twitter Moldred -e-maill moldrad@gmail.com

**Comment by RuneW** [comment]
I get the exact same thing!

**Comment by beruth35** [comment]
Same error!
