### ISSUE TITLE
[bug]: the NSFW checker isn't being disabled

### ISSUE THREAD

**Issue by ninjasaid2k** [invoke-ai/InvokeAI#1729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What happened?

I tried to get Stable Diffusion to stop blurring some of my images, I checked the documentation for how to disable it and I tried '--nsfw_checker' and '--nsfw_checker' and '--no-nsfw_checker' but the command terminal could not recognize either of my commands by giving me this error:
```
invoke.py: error: unrecognized arguments: --no-nsfw_checker
invoke>
```

**Comment by lstein** [comment]
You are actually running InvokeAI 2.1. The `--no-nsfw_checker` argument was added in 2.2. If you don't provide any arguments, the safety checker should be turned off. Could you paste in `invoke.py`'s startup messages?

**Comment by ninjasaid2k** [comment]
I believe I am using Invoke 2.2 because I have the unified canvas on the webui

**Comment by EvgenyOvsov** [comment]
Same issue on Windows, version 2.2.3

Safety checker enabled by default, it causes 35-40% of all requests with words man/woman/human/etc blocked.
Docs says, 
```
...stored in the InvokeAI initialization file (usually
`.invokeai` in your home directory). You can change the default at any
time by opening this file in a text editor and commenting or
uncommenting the line `--nsfw_checker`.
```
But I haven't found such a file in HOME or InvokeAI file.

**Comment by FalxGod** [comment]
> Same issue on Windows, version 2.2.3
> 
> Safety checker enabled by default, it causes 35-40% of all requests with words man/woman/human/etc blocked. Docs says,
> 
> ```
> ...stored in the InvokeAI initialization file (usually
> `.invokeai` in your home directory). You can change the default at any
> time by opening this file in a text editor and commenting or
> uncommenting the line `--nsfw_checker`.
> ```
> 
> But I haven't found such a file in HOME or InvokeAI file.

For Windows the path is: C:\Users\[YOUR_USERNAME]\.invokeai

**Comment by ninjasaid2k** [comment]
> > Same issue on Windows, version 2.2.3
> > Safety checker enabled by default, it causes 35-40% of all requests with words man/woman/human/etc blocked. Docs says,
> > ```
> > ...stored in the InvokeAI initialization file (usually
> > `.invokeai` in your home directory). You can change the default at any
> > time by opening this file in a text editor and commenting or
> > uncommenting the line `--nsfw_checker`.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But I haven't found such a file in HOME or InvokeAI file.
> 
> For Windows the path is: C:\Users\[YOUR_USERNAME]\.invokeai Enable the setting that you can see hidden files to see files starting with a dot

How do I do a complete reset of InvokeAI? I deleted the files and tried to reinstall it an everything went wrong and commandline and webui doesn't open, citing that there's no ldm module.

**Comment by ninjasaid2k** [comment]
I think I finally got it from the discord server, thanks!

**Comment by pierre1618** [comment]
> 

it works for me on Linux, the file was invokeai.init in the folder home/user/invokeai, the same place where outputs are saved
