### ISSUE TITLE
[bug:] PC shuts down during an iteration 

### ISSUE THREAD

**Issue by TheBarret** [invoke-ai/InvokeAI#1737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

4GB

### What happened?

During an outpainting iteration, pc just shutdown (hard), i suspect its temperature issue, but it never happened before prior with InvokeAI.

I tried to sift in the Windows Event Manager or any memory dumps for as to why, but none i could find.

I have updated to InvokeAI to 2.2.0

**Comment by SanDiegoDude** [comment]
Make sure your power supply has enough power at peak for your video card. If you have ever upgraded your video card but not your power supply, it could be that your video card tried to draw more power than your power supply could handle, thus causing a hard shut down mid-iteration (when the video card is running at 100%). Power failures don't leave behind traces in the windows logs typically, which is why I'm suspecting this is your issue.

**Comment by TheBarret** [comment]
> Make sure your power supply has enough power at peak for your video card. If you have ever upgraded your video card but not your power supply, it could be that your video card tried to draw more power than your power supply could handle, thus causing a hard shut down mid-iteration (when the video card is running at 100%). Power failures don't leave behind traces in the windows logs typically, which is why I'm suspecting this is your issue.

I got a 650w power supply, using a lightweight nvida 1050ti, could this card really pull more then that ?

**Comment by SanDiegoDude** [comment]
> > Make sure your power supply has enough power at peak for your video card. If you have ever upgraded your video card but not your power supply, it could be that your video card tried to draw more power than your power supply could handle, thus causing a hard shut down mid-iteration (when the video card is running at 100%). Power failures don't leave behind traces in the windows logs typically, which is why I'm suspecting this is your issue.
> 
> I got a 650w power supply, using a lightweight nvida 1050ti, could this card really pull more then that ?

For a healthy power supply, no it shouldn’t. But when your system just cuts off in the middle of 100% load (which is what happens when it’s running steps), 9 times out of 10 it’s either an underpowered power supply, or a dying one.

**Comment by TheBarret** [comment]
> 

Well thanks Diego, i guess i'm off buying a new one power unit :P

**Comment by Lolagatorade** [comment]
> > 
> 
> Well thanks Diego, i guess i'm off buying a new power unit :P

you can run a stress test to identify if its 100% for sure power supply related or thermals, download furmark and find a way to look at thermals, both for cpu and gpu, keep a close watch,,, i reccomend furmark and run it at whatever settings stress out your card without going overboard

1050ti isnt too power hungry for the 10 series cards, if you baught your pc from a store they would have accounted for 100% load, if you built it yourself then its something you should have accounted for.

**Comment by TheBarret** [comment]
I already bought a 750w unit, just in case, and i did build this system myself.
I do believe its the peak power that poked the PSU a bit hard.
