### ISSUE TITLE
[bug]: Fails to run on macOS after running source installer

### ISSUE THREAD

**Issue by inktomi** [invoke-ai/InvokeAI#1747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### What happened?

After downloading the latest macOS source package, I ran `./install.sh` and chose "all" for the models to install. It completed and told me: 

```shell
** Model Installation Successful **
You're all set! You may now launch InvokeAI using one of these two commands:
Web version: 
    python scripts/invoke.py --web  (connect to http://localhost:9090)
Command-line version:
   python scripts/invoke.py

If you installed manually, remember to activate the 'invokeai'
environment before running invoke.py. If you installed using the
automated installation script, execute "invoke.sh" (Linux/Mac) or
"invoke.bat" (Windows) to start InvokeAI.

Have fun!

You can now start generating images by running invoke.sh (inside this folder), using ./invoke.sh
```

If, however, I run `./invoke.sh` I get the following: 

```shell
❯ ./invoke.sh
WARNING: overwriting environment variables set in the machine
overwriting variable {'PYTORCH_ENABLE_MPS_FALLBACK'}
/Users/.../Downloads/invokeAI/invoke.sh: line 14: syntax error near unexpected token `then'
/Users/.../Downloads/invokeAI/invoke.sh: line 14: `￼if [ "$(uname -s)" == "Darwin" ]; then'
```

If I follow the other directions and run using python, I get a different error: 

```shell
❯ python scripts/invoke.py --web
Traceback (most recent call last):
  File "/Users/inktomi/Downloads/invokeAI/scripts/invoke.py", line 3, in <module>
    import ldm.invoke.CLI
ModuleNotFoundError: No module named 'ldm'
```

**Comment by damian0815** [comment]
this code has been tested mostly on zsh - are you running a different shell?

**Comment by inktomi** [comment]
I’m using the fish shell. I will try zsh. On Dec 3, 2022, at 9:42 AM, Damian Stewart ***@***.***> wrote:﻿
this code has been tested mostly on zsh - are you running a different shell?

**Comment by inktomi** [comment]
Under zsh the same thing happens for me.

**Comment by inktomi** [comment]
I figured it out - the `if` that is complained about is slightly indented for some reason. Removing those indents lets the script run.

**Comment by damian0815** [comment]
i think there's a bug fix for this already merged into main - please close if it resolves your problem.

**Comment by appinteractive** [comment]
@damian0815 negative, same here on mac with zsh

**Comment by appinteractive** [comment]
for me the issue seems to appear when I move the install dir after installation. Is there a way to get it working again after moving?

**Comment by damian0815** [comment]
i think you can cd into the InvokeAI source root dir and run `pip install -e .` and that should update the paths.

**Comment by damian0815** [comment]
or perhaps just `pip install .` ?

**Comment by appinteractive** [comment]
I will try, thanks for the hint. For now I leave the installation in the cache folder.

**Comment by happyplacetraveler** [comment]
so I went to the containing folder listed above and tried both pip install -e.  and pip install . 
and I got
ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5
ERROR: Could not find a version that satisfies the requirement clipseg (from invokeai) (from versions: none)
ERROR: No matching distribution found for clipseg
I reinstalled Python and still receive that error.

**Comment by appinteractive** [comment]
@happyplacetraveler What OS/version? What does `python --version` say?

**Comment by appinteractive** [comment]
I had big trouble with installing in the wrong folders. Mac does somehow restrict stuff in system folders for example. On windows I heard you need to enable long paths in the regestry for a similar matter.

**Comment by damian0815** [comment]
> when I try pip install -e . I get this: <path...>/InvokeAI/source_installer/source_installer does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
> 
> when I try pip install . I get ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
> 
> any other suggestions I can try?

can you try doing this in the parent directory of `source_installer`? ie
```
cd <path...>/InvokeAI
pip install .
```

**Comment by happyplacetraveler** [comment]
Thanks for you reply..

python --version
zsh: command not found: python

python3 --version
Python 3.10.8

Looking forward to your reply. Thanks again.

**Comment by happyplacetraveler** [comment]
I manually installed Clipseg, trashed and reinstalled Invoke from scratch, and moved my models out to a different drive. I’ not sure which one did it but it is working great now.

Quick question - is there an easy way to point the Invoke ai to go look in a specific location for models or to add new models AFTER the install has been completed?

Thanks again!

**Comment by Cool-and-Deadly** [comment]
On Apple M2 MacOS 13.5 I also have the issue:
`ERROR: Directory '<PATH>/InvokeAI/installer[onnx]' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.` 
.. when running the installer downloaded at https://github.com/invoke-ai/InvokeAI/releases/tag/v3.1.1

Would you also suggest I do this?
> I manually installed Clipseg, trashed and reinstalled Invoke from scratch,
If yes, could please describe the steps needed? Thanks
