### ISSUE TITLE
[bug]: Deformed Images, Noise in final image when using karras samplers and high steps.

### ISSUE THREAD

**Issue by WhatsHacking** [invoke-ai/InvokeAI#1754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

8GB

### What happened?

After completing the instalation It seems to me there might be a problem regarding the denoising schedulers, and images come out with lots of noise when using k diffusion and high steps (<50)
I tried copying the Horse Image from the toolkit example page, and the result was this atrocity... 
![000035 6e335c14 1654590180](https://user-images.githubusercontent.com/108960001/205441666-7c60d79c-5d62-4828-b903-dae869302ba6.png)
I copied the entire prompt, seed, image size and cfg, but instead of a pony I got a albino chupakabra.
Also I tried asking for help in the discord but a bot kept flagging me for explicit language or imagery, so thats why im posting this here.

**Comment by lstein** [comment]
Which k sampler are you using?

**Comment by lstein** [comment]
I think that what's happened here is between the current release and the last one we did change the k-diffusion noise schedule to allow the samplers to work better at low (<30) step counts. It looks like for this specific prompt the `k_euler_a` sampler creates a monstrosity. Either increasing the step count modestly, or switching to another k-sampler returns a more acceptable image. If you are using the CLI, you can restore the original noise schedule by passing `--karras_max=0` at the `invoke>` line. Currently there is no easy way to do this on the Web side, but this was an oversight and I'm fixing it now.
