### ISSUE TITLE
This app can't run on your PC [bug]: This comes up while installing although I downloaded the correct version for Windows 11?? Any ideas?

### ISSUE THREAD

**Issue by tooranim** [invoke-ai/InvokeAI#1761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

16

### What happened?

I downloaded from the source and when trying to install I got the pop up mesage - "This app can't run on your PC"

### Screenshots

![Screenshot_20221203_094303](https://user-images.githubusercontent.com/113438505/205456771-1931253f-7b47-4da7-b4dc-4bf873b40a5b.png)

**Comment by lstein** [comment]
You have encountered an Antivirus warning. Temporarily disable your AV application and try again.

**Comment by BartaG512** [comment]
> You have encountered an Antivirus warning. Temporarily disable your AV application and try again.

Can you add it to the readme?
