### ISSUE TITLE
[diffusers]: EmbeddingManager

### ISSUE THREAD

**Issue by keturn** [invoke-ai/InvokeAI#1778]
Textual Inversion, concept embeddings, whatever we're calling it: that thing where a prompt can include some tokens that aren't included in the base model, and we load the vectors for them from some auxiliary data source and include them in the embeddings we pass to the model for conditioning.

[EmbeddingManager] has no direct counterpart in the diffusers model, nor do the [model configurations] for diffusers models have any `personalization_config` element.

[EmbeddingManager]: https://github.com/invoke-ai/InvokeAI/blob/c607d4fe6ccb0f13056d5fee5346989255fe3ccd/ldm/modules/embedding_manager.py#L47
[model configurations]: https://huggingface.co/CompVis/stable-diffusion-v1-4/blob/main/model_index.json

#1583 currently includes a [crude patch](https://github.com/invoke-ai/InvokeAI/pull/1583/commits/ca1f76b7ba04e1ebe0e473d7c178403aee082383) adding an EmbeddingManager, but I'm not sure if it is sufficient or appropriate.

We need, at the very least, some test cases we can use to evaluate whether that's working. They should include single-token/single-vector embeddings as well as the multi-token or multi-vector kind.

The good news is that both the legacy implementation and diffusers-flavored models use the same [CLIP models from _transformers_](https://huggingface.co/docs/transformers/model_doc/clip) for tokenizing and embedding, so none of this should require much new code.

Related reading:
- https://github.com/huggingface/diffusers/pull/661
- https://github.com/huggingface/diffusers/issues/799#issuecomment-1332672708

**Comment by damian0815** [comment]
🙋 i can do this.

**Comment by damian0815** [comment]
Work started in #2018

**Comment by damian0815** [comment]
done 💀💀💀💀💀💀💀💀💀💀💀
