### ISSUE TITLE
[bug]: I don't have a Invoke.bat file 

### ISSUE THREAD

**Issue by ninjasaid2k** [invoke-ai/InvokeAI#1783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What happened?

I've reinstalled ImvokeAI with the manual installation using anaconda3, I'm missing the InvokeAI folder and I'm only able to open it using anaconda3 by typing in 'conda activate invokeai' and 'python scripts\invoke.py --web' in order for it to open the webui.

**Comment by zvit** [comment]
Try this. Create an invoke.bat file and use this code:

`@echo off

call .venv\Scripts\activate.bat

echo Do you want to generate images using the
echo 1. command-line
echo 2. browser-based UI
echo OR
echo 3. open the developer console
set /p choice="Please enter 1, 2 or 3: "
if /i "%choice%" == "1" (
    echo Starting the InvokeAI command-line.
    .venv\Scripts\python scripts\invoke.py
) else if /i "%choice%" == "2" (
    echo Starting the InvokeAI browser-based UI.
    Scripts\invoke.py --web 
) else if /i "%choice%" == "3" (
    echo Developer Console
    echo Python command is:
    where python
    echo Python version is:
    python --version
    echo *************************
    echo You are now in the system shell, with the local InvokeAI Python virtual environment activated,
    echo so that you can troubleshoot this InvokeAI installation as necessary.
    echo *************************
    echo *** Type `exit` to quit this shell and deactivate the Python virtual environment ***
    call cmd /k
) else (
    echo Invalid selection
    pause
    exit /b
)

deactivate`

**Comment by ninjasaid2k** [comment]
> Try this. Create an invoke.bat file and use this code:

it doesn't work, it gives me this error
`Microsoft Windows [Version 10.0.19044.2251]
(c) Microsoft Corporation. All rights reserved.

C:\Users\ninja\InvokeAI>invoke.bat
The system cannot find the path specified.
Do you want to generate images using the
1. command-line
2. browser-based UI
OR
3. open the developer console
Please enter 1, 2 or 3: 2
Starting the InvokeAI browser-based UI.
Traceback (most recent call last):
  File "C:\Users\ninja\InvokeAI\Scripts\invoke.py", line 3, in <module>
    import ldm.invoke.CLI
ModuleNotFoundError: No module named 'ldm'
'deactivate' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\ninja\InvokeAI>
`
It only works on anaconda3 prompt.

**Comment by robindegen** [comment]
For some reason my clean install also did not provide any "invoke.bat". Why is this?

**Comment by toktoktheeo** [comment]
The same here. Cleaninstall, no invoke.bat :/ On windows 11.

**Comment by jimblug** [comment]
> For some reason my clean install also did not provide any "invoke.bat". Why is this?

I have the same problem, someone would have a solution? thank you!

**Comment by robindegen** [comment]
It looks like the script tries to copy 2 files, one of them being "source_installer\invoke.bat.in". But that directory doesn't exist at all.

You need to activate the environment in installer_files\env\envs\invokeai\

And then you can run with
python scripts/invoke.py --web

However this is ofcourse a bug that should be fixed in some way. Maybe just a documentation update

**Comment by mjugger** [comment]
> It looks like the script tries to copy 2 files, one of them being "source_installer\invoke.bat.in". But that directory doesn't exist at all.
> 
> You need to activate the environment in installer_files\env\envs\invokeai\
> 
> And then you can run with python scripts/invoke.py --web
> 
> However this is ofcourse a bug that should be fixed in some way. Maybe just a documentation update

@robindegen I'm super new to this but how do I "activate the environment" in the installer_files\env\envs\invokeai\ directory?

**Comment by robindegen** [comment]
> @robindegen I'm super new to this but how do I "activate the environment" in the installer_files\env\envs\invokeai\ directory?

I use powershell so i did the following (from where you installed):
```
.\installer_files\env\Scripts\conda init powershell
```

(restart powershell)

Then (from where you installed):
```
conda activate invokeai
python scripts/invoke.py --web
```

**Comment by mjugger** [comment]
I found that my problem was the environment had not been created (running `conda activate invokeai` produced an error that said the env `invokeai` not found). running `conda info --envs` revealed that there wasn't an env called `invokeai` only one called `base`. So I ran `conda env update` and then `conda activate invokeai` followed by `python scripts/invoke.py --web` which finally got it working.

**Comment by hansolocambo** [comment]
During the setup it's explained that you need to update pip. 
Run a cmd command prompt, type : 
python.exe -m pip install --upgrade pip

Then run the installer again. Install in the same folder as before. Read a bit what's explained while it's installing. 
This time it should ask you to create a huggingface token. And it'll install all models you want. 
At then you'll have this time an invoke.bat to run.

**Comment by mockinbirdy** [comment]
I mean I have a similar problem. According to the instruction, I should run this - 
```
python -m venv invokeai
source invokeai/bin/activate
```
It doesn't work. What should be in the place of **source** cause it doesn't work either way. 
Apparently, I also don't have bin folder. 
Pip updated, python 3.10. Clean install.
