### ISSUE TITLE
Something went wrong while installing Python libraries and cannot continue."

### ISSUE THREAD

**Issue by Tobe2d** [invoke-ai/InvokeAI#1788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24

### What happened?

I cant get it to install on my 2nd system. I had it installed perfictly on my laptop running on RTX 3070 and now when I try installing on my main PC with RTX 4090 I cant install as I get this error message:
"Something went wrong while installing Python libraries and cannot continue."

### Screenshots

        1 file(s) copied.
Collecting package metadata (repodata.json): failed

CondaSSLError: OpenSSL appears to be unavailable on this machine. OpenSSL is required to
download and install packages.

Exception: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /pytorch/win-64/repodata.json (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

""
"Something went wrong while installing Python libraries and cannot continue."
"See https://invoke-ai.github.io/InvokeAI/INSTALL_SOURCE#troubleshooting for troubleshooting"
"tips, or visit https://invoke-ai.github.io/InvokeAI/#installation for alternative"
"installation methods"
Press any key to continue . . .

### Additional context

I belive we need to see what are the prerequisites for the installation to be successful as I belive my both systems are identical accept the GPU

**Comment by 53jk1** [comment]
This error usually occurs when the OpenSSL library is not installed or is not accessible on your machine. To fix this issue, you should install the OpenSSL library on your machine and make sure it is accessible. Additionally, you should check that the correct version of OpenSSL is installed and that it is properly configured.

Alternatively, you can try other installation methods, such as using a pre-built Python distribution package or downloading the source code and building it yourself.

**Comment by Tobe2d** [comment]
Thanks @53jk1 so I installed openssl and it it move further without any warning about ssl, howveer now I stuck on:


To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - cmd.exe
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


Loading Python libraries...

Traceback (most recent call last):
  File "D:\InvokeAI\scripts\configure_invokeai.py", line 18, in <module>
    from omegaconf import OmegaConf
ModuleNotFoundError: No module named 'omegaconf'
""
"The configure script crashed or was cancelled."
"InvokeAI is not ready to run. To run preload_models.py again,"
"run the command 'update.bat' in this directory."
"Press any key to continue"
Press any key to continue . . .

**Comment by 53jk1** [comment]
This error message indicates that the module omegaconf is not installed. To fix this, you need to install the omegaconf module. You can do this by running the command 'pip install omegaconf' in the terminal. Once the module is installed, you can run the preload_models.py script again by running the command 'update.bat' in the directory.

**Comment by Tobe2d** [comment]
Thanks again @53jk1 

Now I have this error:



D:\_anaconda3_\lib\site-packages\numpy\__init__.py:143: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "D:\anaconda3_\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray
  File "D:\anaconda3_\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "D:\anaconda3_\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\InvokeAI\scripts\preload_models.py", line 8, in <module>
    import configure_invokeai
  File "D:\stable-diffusion_InvokeAI\scripts\configure_invokeai.py", line 23, in <module>
    from transformers import CLIPTokenizer, CLIPTextModel
  File "D:\anaconda3_\lib\site-packages\transformers\__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "D:\anaconda3_\lib\site-packages\transformers\dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "D:\anaconda3_\lib\site-packages\transformers\utils\__init__.py", line 34, in <module>
    from .generic import (
  File "D:\anaconda3_\lib\site-packages\transformers\utils\generic.py", line 27, in <module>
    import numpy as np
  File "D:\anaconda3_\lib\site-packages\numpy\__init__.py", line 145, in <module>
    from . import core
  File "D:\anaconda3_\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "D:\Ai__Project\_anaconda3_\python.exe"
  * The NumPy version is: "1.20.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.

"Press any key to continue"
Press any key to continue . . .

**Comment by 53jk1** [comment]
@Tobe2d the error you are seeing is likely due to an incompatibility between the version of Python you are using and the version of NumPy you have installed. It is recommended that you check the versions of both Python and NumPy to make sure they are compatible. Additionally, you can refer to the NumPy documentation for troubleshooting tips and advice on how to solve this issue: https://numpy.org/devdocs/user/troubleshooting-importerror.html.

**Comment by 53jk1** [comment]
Besides, I don't think it is a bug, you should change the title of Issue

**Comment by gateway** [comment]
I have the same issues.. is their a good conda manual install link that walks you though the conda env, python version, requirements.txt etc?

**Comment by 53jk1** [comment]
@gateway, try doing what I wrote above
