### ISSUE TITLE
[bug]: macOS: ModuleNotFoundError: No module named 'ldm'

### ISSUE THREAD

**Issue by jaycer** [invoke-ai/InvokeAI#1794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What happened?

New install, I get error `ModuleNotFoundError: No module named 'ldm'` when running `% python3 scripts/invoke.py --web`

> InvokeAI/invokeAI/scripts/invoke.py", line 3, in <module>
>     import ldm.invoke.CLI
> ModuleNotFoundError: No module named 'ldm'

I did try `% pip install -e .` but that gives me these errors 

> ERROR: Could not find a version that satisfies the requirement clipseg (from invokeai) (from versions: none)
> ERROR: No matching distribution found for clipseg

**Comment by petrasl1976** [comment]
run `./invoke.sh` from main `invokeAI` folder and choose `2`:
```
PL 21:26 ~/invokeAI $ ./invoke.sh
Do you want to generate images using the
1. command-line
2. browser-based UI
3. open the developer console
Please enter 1, 2, or 3: 2
```

**Comment by tangtang666** [comment]
On the macOS, I solve the problem by the following command 
```
pip install git+https://github.com/openai/CLIP.git@main#egg=clip
pip install git+https://github.com/Birch-san/k-diffusion.git@mps#egg=k-diffusion
pip install git+https://github.com/invoke-ai/clipseg.git@relaxed-python-requirement#egg=clipseg
pip install git+https://github.com/invoke-ai/GFPGAN@basicsr-1.4.2#egg=gfpgan
pip install git+https://github.com/invoke-ai/PyPatchMatch@0.1.4#egg=pypatchmatch
pip install -e .
```

**Comment by realenuf** [comment]
I have the same problem on Ubuntu 22.04, and the above didn't help.

**Comment by tjthejuggler** [comment]
> On the macOS, I solve the problem by the following command
> 
> ```
> pip install git+https://github.com/openai/CLIP.git@main#egg=clip
> pip install git+https://github.com/Birch-san/k-diffusion.git@mps#egg=k-diffusion
> pip install git+https://github.com/invoke-ai/clipseg.git@relaxed-python-requirement#egg=clipseg
> pip install git+https://github.com/invoke-ai/GFPGAN@basicsr-1.4.2#egg=gfpgan
> pip install git+https://github.com/invoke-ai/PyPatchMatch@0.1.4#egg=pypatchmatch
> pip install -e .
> ```

I tried this in Ubuntu 22.04 and all it did is download another 6 or 7 gigs of something and didn't help

**Comment by korrasam** [comment]
i had the same issue , and the fix was to run "conda activate invokeai" before running python scripts/invoke.py . 
hope this helps :)

**Comment by tangtang666** [comment]
> > On the macOS, I solve the problem by the following command
> > ```
> > pip install git+https://github.com/openai/CLIP.git@main#egg=clip
> > pip install git+https://github.com/Birch-san/k-diffusion.git@mps#egg=k-diffusion
> > pip install git+https://github.com/invoke-ai/clipseg.git@relaxed-python-requirement#egg=clipseg
> > pip install git+https://github.com/invoke-ai/GFPGAN@basicsr-1.4.2#egg=gfpgan
> > pip install git+https://github.com/invoke-ai/PyPatchMatch@0.1.4#egg=pypatchmatch
> > pip install -e .
> > ```
> 
> I tried this in Ubuntu 22.04 and all it did is download another 6 or 7 gigs of something and didn't help


I can run successfully in Ubuntu 16.04. In fact, the problem is that the dependency package is not installed properly, which has little to do with the system. Try the following command.

```
conda activate invokeai
conda env update -f environment.yml

```

**Comment by tjthejuggler** [comment]
Thanks, this conda advice got be further down the road, however now it is crashing with just 'Killed' when loading the 1.5 model, I made a separate issue for it though
https://github.com/invoke-ai/InvokeAI/issues/1858

**Comment by realenuf** [comment]
Same here! I now have the Conda invokeai instance, but running invoke.sh "terminates" when loading the 1.5 model. I'll jump over to your separate issue.

**Comment by sooolee** [comment]
I have the same issue trying in Linux. I'm using pip install and for configuring ran `scripts/invoke.py` and get the error: ModuleNotFoundError: No module named 'ldm'

Running `./invoke.sh` didn't work for me.  From reading other issues, this Idm module issue seems to occur in other steps too. Any updates on this issue?
