### ISSUE TITLE
[bug]: Unexpectet behavior, Params change while generating image

### ISSUE THREAD

**Issue by snimshchikov** [invoke-ai/InvokeAI#1796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cpu

### What happened?

Changed params apply to already started generation

Steps to reproduce:
1. Disable randomize seed
2. Generate image with any params
3. Start generating a new image with same params
4. Change params while generating steps
5. Get dfferent result

Expected:
Image is generating in background while I can safely change anything i want without waiting

**Comment by damian0815** [comment]
can you be more specific about which parameters you’re changing? and can you also check that variations is turned off or set to 0?

**Comment by snimshchikov** [comment]
Sorry, I was confused with ui and accidentally saved photo before starting a new promt, didn't test enough. Everything works as expected
