### ISSUE TITLE
[bug]: Custom models do not load, hits KeyError in state_dict

### ISSUE THREAD

**Issue by xraxra** [invoke-ai/InvokeAI#1797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12

### What happened?

following the guide for setting up custom models directly in models.yaml 
I added a custom ckpt based on Stable Diffusion 1.5

When invokeAI tries to load the model it just hits the following error 

** model custom could not be loaded: 'state_dict'
Traceback (most recent call last):
  File "c:\invokeai\ldm\invoke\model_cache.py", line 80, in get_model
    requested_model, width, height, hash = self._load_model(model_name)
  File "c:\invokeai\ldm\invoke\model_cache.py", line 230, in _load_model
    sd = sd['state_dict']
KeyError: 'state_dict'

from here, it either reverts to the default model (Stable Diffusion 1.5)  or in cases where no extra models are configured, it starts the misconfigured/missing models routine (configure_invokeai)

**Comment by damian0815** [comment]
looks like a dupe of #1766 ..?

**Comment by xraxra** [comment]
#1766 fixes it, thank you!
