### ISSUE TITLE
[bug]: Option to "enter token" after accepting license skips automatically to "password"

### ISSUE THREAD

**Issue by Emc2Tech** [invoke-ai/InvokeAI#1804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6gb

### What happened?

When pressing "enter" after accepting the licenses. It skips the "token" field and goes directly to "password" regardless of how I try. By pressing "enter" on the keyboard or numeric keyboard, try to right-click instead to paste to no avail. I tried several times and every time its the same thing and I just cancel the install remove all instances and start again in vain. I am at my wits end, also feeling a little ridiculous for this Shoutout, but please help a guy in need :)

### Contact Details

e.rollin77@gmail.com, discord : claricart#9835

**Comment by oyvindneu** [comment]
I pasted the token from huggingface.co into the password field and it worked fine, I thought this was just a double prompt and the one asking for Password was just a type of some sort.

Did you try pasting the Token into the Password prompt?

**Comment by Emc2Tech** [comment]
hi friend,

really i didn't want to try in case since the installation is long... I
will try and let you know, i will be laughing at myself if its the case...
too much stress these days to think straight lol.

**Comment by ebr** [comment]
The "password" field IS where you paste the token :) I'll close this, please reopen if you still have issues.

**Comment by anshuzy** [comment]
@ebr Yes I used the links provided during the installation but I couldn't find an accept button anywhere. There wasn't a popup to accept anything either.

**Comment by oyvindneu** [comment]
I couldn't find any "accept conditions button" either, so I assumed it was for your information.

The models downloaded fine without any explicit accept. It is more a link to the conditions and by downloading the model you are implicitly accepting them.

**Comment by anshuzy** [comment]
When I just pressed enter and tried to download the models anyways they didn't download and an error occured
