### ISSUE TITLE
[bug]:  You appear to have a missing or misconfigured model file(s).

### ISSUE THREAD

**Issue by Ulf3000** [invoke-ai/InvokeAI#1806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What happened?

i always get this error:

```
You appear to have a missing or misconfigured model file(s).
   The script will now exit and run configure_invokeai.py to help fix the problem.
   After reconfiguration is done, please relaunch invoke.py.
```

the model files are all in the model folder , i downloaded them through the script .. but it always fails to detect them and goes back to the model downloader

**Comment by JollyDevelopment** [comment]
@Ulf3000 check the ~/.invokeai file on your system.

When I set this up first I didn't realize how it would set the working directories and such in the initial wizard thing. So I had my models in one folder that I thought was correct, but the .invokeai was pointing at a different folder.

Once I got that straightened out I got the webui to work properly. I've even got it to load multiple checkpoints.

**Comment by DexeconGithub** [comment]
configure_invokeai.py
change wights_dir and add more info on the path
eg. if it says "ldm/stable-diffusion-v1/" change it to "models/ldm/stable-diffusion-v1" 
for some reason that worked

**Comment by DexeconGithub** [comment]
i'm getting this error, is that the same thing you're getting? 

model sd-v1-5-pruned could not be loaded: "filename 'storages' not found"

**Comment by DexeconGithub** [comment]
actually might be unrelated, i think my models got corrupted

**Comment by G710** [comment]
Hi Ulf,
like Jolly suggested you should check your `~/.invokeai` file for the paths to your data directory. 

Also there is currently a unexpected feature in the `configure_invokeai.py` where this file might not be created because the runtime directory already exists. see #1613 for details and a possible workaround until this is fixed.

**Comment by fedsol** [comment]
I had this issue, and as @G710 suggested, it was related to #1613 . I created a .invokeai file in c:\users\myname containing --root="path\to\invokeai" and it solved the problem.

**Comment by docmatthew** [comment]
i have this problem but my  ~/.invokeai is properly showing the right path. i dont know how to fix it. i tried seting it up again twice , i chose download all files instead of recommended ones, still no change. is there any possible reason for this error any hopefully another solution

**Comment by Neverdusk** [comment]
I've also been having the same error. My models load in Automatic but not here. My paths in model.yaml are also correct, so I don't know the problem. 

I wonder if it's a safetensors issue. The moment I swapped the default model to an older .ckpt model, everything started correctly.
