### ISSUE TITLE
[bug]: upscaling not work

### ISSUE THREAD

**Issue by steto123** [invoke-ai/InvokeAI#1810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What happened?

When i cjhoose upscaloe image there is a error. In the console i can find: local variable 'upsampler' referenced before assignment

Whats the problerm?

### Contact Details

steffen@sthomas.de

**Comment by pdsmike** [comment]
I had this problem too. Quick fix is to edit file -> \.venv\Lib\site-packages\ldm\invoke\restoration\realesrgan.py
and change 
`model_path = os.path.join(Globals.root,'models/realesrgan/realesr-general-x4v3.pth') `
to
`model_path = os.path.abspath('../../../../models/realesrgan/realesr-general-x4v3.pth') `
I know it shouldn't be like this, but this is a quick fix. Original code gives me
`'.\\models/realesrgan/realesr-general-x4v3.pth'` <- File not found, what leads to "local variable 'upsampler' referenced before assignment" on my Windows machine.

**Comment by Kiaana** [comment]
I have this problem too

**Comment by 925-Studio** [comment]
I had this problem but I just have figured it out. Download [this file](https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.5.0/realesr-general-x4v3.pth) then put it into `models/realesgran/` folder. It was an empty folder in my case now it's working without problem. Doesn't need to change any file.

**Comment by darth-veitcher** [comment]
Still exists in `2.3.4.post1` and the model already exists in the folder. Even hardcoding the absolute path in `realesrgan.py` doesn't fix the issue so I'm assuming it's to do with the way the pipeline is being called.
