### ISSUE TITLE
[enhancement]: Support safetensors model format

### ISSUE THREAD

**Issue by n00mkrad** [invoke-ai/InvokeAI#1813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

It would be helpful to support safetensors as an alternative to pickled ckpt files.

Details:

https://github.com/huggingface/safetensors

**Comment by keturn** [comment]
This will come with the  🧨diffusers integration: #1583 

diffusers will load safetensors by default when available. (Not sure if that's in diffusers 0.9.0, but it is in their current main branch, and I'm sure they will have that released in 0.10 by the time we finish 1583.)
