### ISSUE TITLE
[bug]: install error, need offline pack, no need install version pls

### ISSUE THREAD

**Issue by martjay** [invoke-ai/InvokeAI#1822]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What happened?

EnvironmentLocationNotFound: Not a conda environment: D:\ProgramData\Anaconda3\envs\invokeai

The system cannot find the path specified.

SpecNotFound: Can't process without a name

""
"Something went wrong while installing Python libraries and cannot continue."
"See https://invoke-ai.github.io/InvokeAI/INSTALL_SOURCE#troubleshooting for troubleshooting"
"tips, or visit https://invoke-ai.github.io/InvokeAI/#installation for alternative"
"installation methods"

**Comment by GaHub** [comment]
Same issue but on macOS Ventura. Help!
