### ISSUE TITLE
[bug]: Crashes on startup

### ISSUE THREAD

**Issue by githubUser01946** [invoke-ai/InvokeAI#1824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

4GB

### What happened?

Double click the invoke.bat and it does some stuff then closes.

### Screenshots

Not a screenshot but a video showing what happens.

https://user-images.githubusercontent.com/117453319/205927996-1654d6fe-9cea-48c2-b36c-ef18d38593ba.mp4

### Additional context

The install went right afaik and I had to create the \models\ldm\stable-diffusion-1 directory myself where I placed the ckpt files and also edited the models.yaml file.

I have also posted on the Invoke Discord.

### Contact Details

Quinnie#5379

**Comment by tondeee** [comment]
same ptoblem

**Comment by bigtree908** [comment]
I'm having this problem, what was the solution?

**Comment by vikgen19** [comment]
i am facing the same issue , how can i solve this? @githubUser01946 help me close this issue please.

**Comment by samusxaran** [comment]
Same issue with me. I installed it from 2.2.5 just yesterday Dec 10th.
