### ISSUE TITLE
[bug]: Install script doesn't work

### ISSUE THREAD

**Issue by timius100** [invoke-ai/InvokeAI#1830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What happened?

When I tried to run `install.bat`, I got this error. I also get 4 "This app can't run on your pc" errors.
edit: I also tried to run this as an administrator and with disabled av

```
"InvokeAI source installer..."
""
"Some of the installation steps take a long time to run. Please be patient."
"If the script appears to hang for more than 10 minutes, please interrupt with control-C and retry."
"<Press any key to start the install process>"
Press any key to continue . . .
""
"Downloading micromamba from https://github.com/cmdr2/stable-diffusion-ui/releases/download/v1.1/micromamba.exe to C:\image_generation\InvokeAI\installer_files\mamba\micromamba.exe"
A subdirectory or file C:\image_generation\InvokeAI\installer_files\mamba already exists.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Failure when receiving data from the peer
Micromamba version:
Access is denied.
Access is denied.
"Packages to install: conda"
Access is denied.
"There was a problem while installing conda using micromamba. Cannot continue."
Press any key to continue . . .
```

### Screenshots

![image](https://user-images.githubusercontent.com/74375674/205960394-b1eae78e-70f4-4596-bf8e-eaf91beadfbd.png)

**Comment by finefin** [comment]
I had this error, too. but somehow it installed after a few tries.

**Comment by koreney** [comment]
To fix edit the install.bat file.
locate the line:
call curl -L "%MICROMAMBA_DOWNLOAD_URL%" > "%MAMBA_ROOT_PREFIX%\micromamba.exe"
change it to:
call curl --ssl-no-revoke -L "%MICROMAMBA_DOWNLOAD_URL%" > "%MAMBA_ROOT_PREFIX%\micromamba.exe"
save and run. it should now work.

**Comment by timius100** [comment]
Yep, it seems to fix the issue, but why it's working and why it's not implemented in InvokeAI?
