### ISSUE TITLE
[bug]: Can't accept license terms and unable to download models

### ISSUE THREAD

**Issue by anshuzy** [invoke-ai/InvokeAI#1836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What happened?

There is nowhere to accept license terms on huggingface with the links that are provided. I have downloaded everything else but can't download the models since they need you to accept the terms to download. Anyone know how to accept the terms? I looked everywhere but still couldn't find it. 

### Additional context

I figured out how to make a token and made it through that part but I can't find where to accept the terms. 

### Contact Details

anshujadhav23@gmail.com

**Comment by horbgorbler** [comment]
I have the same issue.  I get through the whole Invoke AI installation to the point where I choose option 2 in the CMD window.  At this point I get the following message:
Do you want to generate images using the
1. command-line
2. browser-based UI
3. open the developer console
Please enter 1, 2 or 3: 2
Starting the InvokeAI browser-based UI..
>> Patchmatch initialized
* Initializing, be patient...
>> Initialization file C:\Users\goodw\invokeai\invokeai.init found. Loading...
>> InvokeAI runtime directory is "C:\Users\goodw\invokeai"
>> GFPGAN Initialized
>> CodeFormer Initialized
>> ESRGAN Initialized

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
   You appear to have a missing or misconfigured model file(s).
   The script will now exit and run configure_invokeai.py to help fix the problem.
   After reconfiguration is done, please relaunch invoke.py.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
configure_invokeai is launching....

Loading Python libraries...

Welcome to InvokeAI. This script will help download the Stable Diffusion weight files
and other large models that are needed for text to image generation. At any point you may interrupt
this program and resume later.

** DOWNLOADING DIFFUSION WEIGHTS **
You can download and configure the weights files manually or let this
script do it for you. Manual installation is described at:

https://github.com/invoke-ai/InvokeAI/blob/main/docs/installation/INSTALLING_MODELS.md

You may download the recommended models (about 10GB total), select a customized set, or
completely skip this step.

Download <r>ecommended models, <a>ll models, <c>ustomized list, or <s>kip this step? [r]: r
** LICENSE AGREEMENT FOR WEIGHT FILES **

To download the Stable Diffusion weight files from the official Hugging Face
repository, you need to read and accept the CreativeML Responsible AI license.

This involves a few easy steps.

1. If you have not already done so, create an account on Hugging Face's web site
   using the "Sign Up" button:

   https://huggingface.co/join

   You will need to verify your email address as part of the HuggingFace
   registration process.

2. Log into your Hugging Face account:

    https://huggingface.co/login

3. Accept the license terms located here:

   https://huggingface.co/runwayml/stable-diffusion-v1-5

   and here:

   https://huggingface.co/runwayml/stable-diffusion-inpainting

    (Yes, you have to accept two slightly different license agreements)

Press <enter> when you are ready to continue:


I have gone to Hugging Face and logged in but see no way to accept the license agreements.  Did you figure out how to do so?
