### ISSUE TITLE
[error handling]: REPL should catch and report exceptions instead of crashing the process

### ISSUE THREAD

**Issue by keturn** [invoke-ai/InvokeAI#1838]
If you manage to trigger some exception from the `invoke>` prompt, it currently prints the traceback and crashes the whole process.

It should act more like ipython does, where it shows you the exception but if it's at all possible, leave the process running and ready to accept a new command.

**Comment by lstein** [comment]
Mostly the CLI does catch exceptions that occur during the generation process, but it crashes out if it gets something truly unrecoverable like being unable to load any models. Please indicate how you got the crash and I'll address.
