### ISSUE TITLE
[bug]: Auto-switch to New Images stills working when disabled in options

### ISSUE THREAD

**Issue by sweetyshots123** [invoke-ai/InvokeAI#1839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What happened?

Auto-switch to New Images stills working when disabled in options

### Additional context

Running on runpod docker image: https://www.runpod.io/console/gpu-secure-cloud?template=vm19ukkycf

**Comment by ebr** [comment]
Right now you have to disable the auto-switching to new images AND disable progress previews for this to work. Thanks for the bug report, this could definitely be improved

**Comment by mauwii** [comment]
since there was no more respond I will close this.
