### ISSUE TITLE
[bug]: This app can't run on your pc

### ISSUE THREAD

**Issue by bach777** [invoke-ai/InvokeAI#1841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6

### What happened?

Downloading micromamba from https://github.com/cmdr2/stable-diffusion-ui/releases/download/v1.1/micromamba.exe to F:\invokeAI\installer_files\mamba\micromamba.exe"
A subdirectory or file F:\invokeAI\installer_files\mamba already exists.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
Micromamba version:
Access is denied.
Access is denied.
"Packages to install: conda"
Access is denied.
"There was a problem while installing conda using micromamba. Cannot continue."
Press any key to continue . . .

### Screenshots

![Screenshot (391)](https://user-images.githubusercontent.com/115612779/206090370-9fd09949-e214-4653-a472-1cd417cb2b7a.png)

### Additional context

I tried to install the content with the .bat file, but I get this error. I have tried to modify the windows permissions, I do have administrator permissions, but it won't let me install it. Any help would be appreciated.
I'm using Windows10, Gtx1660ti

**Comment by HashanUdara** [comment]
I have the same problem

**Comment by ebr** [comment]
If you are using a 3rd party antivirus (Kaspersky, Avast, etc), please disable it just for that step in the installation. We are aware of this issue and are working on solutions, but unfortunately at this point this is the only way.

**Comment by bionictoothpick** [comment]
From Yastarnaut on Discord (Confirmed works) Open the .bat file with a text editor >
change
call curl -L "%MICROMAMBA_DOWNLOAD_URL%" > "%MAMBA_ROOT_PREFIX%\micromamba.exe"
 to:
call curl --ssl-no-revoke -L "%MICROMAMBA_DOWNLOAD_URL%" > "%MAMBA_ROOT_PREFIX%\micromamba.exe"

**Comment by axisrow** [comment]
I tried this, but now have another error:
"There was a problem while installing conda git using micromamba. Cannot continue."

I'm using Windows 11

**Comment by VictorZakharov** [comment]
@ebr Sorry, that's not gonna happen.

**Comment by VictorZakharov** [comment]
Yep, InvokeAI 2.2.4 installed without issues for me.

**Comment by drpuc** [comment]
Копируйте файлы на диск C и начните установку
Copy files to C drive and start installation
