### ISSUE TITLE
[bug]: Multiple versions have failed to install with errors around symlinks and Conda

### ISSUE THREAD

**Issue by AdvaitaSprite** [invoke-ai/InvokeAI#1842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

4gb

### What happened?

I first tried with version 2.1.3 and had the same error; I was hoping that starting over with the new 2.2.3 installer would resolve this so I wouldn't need to post, but it didn't, so I'll do my best to recall and explain. And for the record, I'm on Windows 10 Home. 

So:

The first time around, the installer appeared to be running smoothly, except that early on I did notice a red error warning that said: 

> _critical libmamba symlink_status: The parameter is incorrect.: "F:\InvokeAI\invokeAI\installer_files\env\conda-meta"_

That first time through with the 2.1.3 installer, it ultimately failed saying that it couldn't find _git_ or recognize it as a command [asking if I was sure it was assigned to my PATH]... Which I do not understand whatsoever, because I already had git and git-bash installed & up to date, and I made sure it was added to both my user and system PATHs; it hasn't been a problem with most other programs/installers (I'm fairly new to juggling all this Conda/PIP/git-bash/shell/cmd prompt and I do get confused [it feels like version management has been made into a real morass across the board], so maybe I'm making a very simple error somewhere it'll be cake to fix, but I haven't been able to google up answers to this one). I don't know if it was supposed to automatically make an environment & install git in that conda environment and didn't, or what. 

At any rate, I tried over and over tinkering with adding different potentially-important git directory paths to my PATH, deleting the previous attempt, and rerunning the installer, but to no avail. Same warning about "critical libmamba" symlink status being incorrect, followed by the installer failing when it says it can't find or recognize _git_ every time. So eventually I gave up & went back to using the lovely cmdr2 StableDiffusionUI.

### Fast forward to today

I get inspired to try again, thinking maybe there's a new version with the kinks worked out.
It appears that there is, so I delete the old directory, download the new installer for 2.2.3... And the problem is different, but persistent.

It still has given me the same 

> _critical libmamba symlink_status: The parameter is incorrect.: "F:\InvokeAI\invokeAI\installer_files\env\conda-meta"_

error message, and I still don't know what to do about that exactly. I also already had to do the "add safe.directory" command to solve a "dubious ownership of repository" error, but I'm familiar with those by now so that was no problem. But where I'm at now is illustrated [in addition to the libmamba symlink_status error] by the following log:

>  "Packages to install: conda"
> 
>                                            __
>           __  ______ ___  ____ _____ ___  / /_  ____ _
>          / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
>         / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
>        / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
>       /_/
> 
> pkgs/main/noarch                                              No change
> pkgs/main/win-64                                              No change
> pkgs/r/win-64                                                 No change
> pkgs/msys2/win-64                                             No change
> pkgs/msys2/noarch                                             No change
> pkgs/r/noarch                                                 No change
> 'conda' is not recognized as an internal or external command,
> operable program or batch file.
> 'conda' is not recognized as an internal or external command,
> operable program or batch file.
> The system cannot find the path specified.
> 'conda' is not recognized as an internal or external command,
> operable program or batch file.
> ""
> "Something went wrong while installing Python libraries and cannot continue."
> "See https://invoke-ai.github.io/InvokeAI/INSTALL_SOURCE#troubleshooting for troubleshooting"
> "tips, or visit https://invoke-ai.github.io/InvokeAI/#installation for alternative"
> "installation methods"

Any assistance would be appreciated. Clearly something is going wrong with version management somewhere such that in some installers, they're failing to recognize or find git, and in others they're failing to recognize or find conda... Solutions/answers? 

Thanks.

**Comment by yurinativo** [comment]
Unfortunatelly, Conda is required, but not mentioned in the installation process.
Install Conda from here: https://docs.conda.io/en/latest/

**Comment by AdvaitaSprite** [comment]
I do have Conda installed.

**Comment by Royalkin** [comment]
I'm also experiencing this.
