### ISSUE TITLE
Problem running invoke.bat after install

### ISSUE THREAD

**Issue by CalBG** [invoke-ai/InvokeAI#1845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

After finishing install.bat I tried to run invoke.bat but it gave the below message. If I select option 2, nothing happens. Please assist.

'conda' is not recognized as an internal or external command,
operable program or batch file.
Do you want to generate images using the
1. command-line
2. browser-based UI
3. open the developer console
Please enter 1, 2 or 3:

### Screenshots

![image](https://user-images.githubusercontent.com/120020862/206183670-f8302537-7b09-4470-9a15-2f8e50965b8d.png)

### Additional context

The invoke.bat file wasnt automatically in the install directory I selected but all the other installed files were.
I searched and found the invoke.bat.in file in my System32 folder. I copied it to my installation folder and renamed to invoke.bat (to make it a batch file). When I run it from either folder I get the same message.

### Contact Details

callumbarnettgrant@gmail.com

**Comment by firesidefilmsla** [comment]
I have the same problem

**Comment by billeldjezzar** [comment]
i have the same problem. i press number 2 and nothing happened.
the window closed automatically after "have fun''

**Comment by Upponzella** [comment]
same here. setup worked without problems, but have only one templatefile, which is called so:
C:\Users\dmrad\OneDrive\invokeAI\installer\templates
invoke.bat.in

**Comment by gus-uktena** [comment]
> same here. setup worked without problems, but have only one templatefile, which is called so: C:\Users\dmrad\OneDrive\invokeAI\installer\templates invoke.bat.in

same here

**Comment by CalBG** [comment]
I managed to solve it by downloading and installing using the latest release here: https://github.com/invoke-ai/InvokeAI/releases/tag/v2.2.3

**Comment by Upponzella** [comment]
thanks i try. problems makes version 2.2.4

**Comment by gus-uktena** [comment]
> I managed to solve it by downloading and installing using the latest release here: https://github.com/invoke-ai/InvokeAI/releases/tag/v2.2.3

This is the exact version that I just installed. (all good during the process). It seems that the .bat file is not copied to the invoke ai folder at the end

**Comment by Upponzella** [comment]
not only. the file is also missing:
Scripts\activate.bat

it is not enough to make the file. but maybe with you:

@echo off

PUSHD "%~dp0"
setlocal

call .venv\Scripts\activate.bat
set INVOKEAI_ROOT=.

echo Do you want to generate images using the
echo 1. command-line
echo 2. browser-based UI
echo 3. open the developer console
set /P restore="Please enter 1, 2 or 3: "
IF /I "%restore%" == "1" (
    echo Starting the InvokeAI command-line..
    python .venv\Scripts\invoke.py %*
) ELSE IF /I "%restore%" == "2" (
    echo Starting the InvokeAI browser-based UI..
    python .venv\Scripts\invoke.py --web %*
) ELSE IF /I "%restore%" == "3" (
    echo Developer Console
    echo Python command is:
    where python
    echo Python version is:
    python --version
    echo *************************
    echo You are now in the system shell, with the local InvokeAI Python virtual environment activated,
    echo so that you can troubleshoot this InvokeAI installation as necessary.
    echo *************************
    echo *** Type `exit` to quit this shell and deactivate the Python virtual environment ***
    call cmd /k
) ELSE (
    echo Invalid selection
    pause
    exit /b
)
endlocal

**Comment by josephk387** [comment]
> same here. setup worked without problems, but have only one templatefile, which is called so: C:\Users\dmrad\OneDrive\invokeAI\installer\templates invoke.bat.in

same here

**Comment by nazeerPro** [comment]
> Did an update now. then the invokeai.bat file appears. but during the update now comes the following:
> 
> ERROR: Ignores the following versions that require a different Python version: 0.55.2 Requires-Python <3.5; 1.21.2 Requires-Python >=3.7,<3. 11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11 ERROR: Could not find a version that met the torch==1.12.1 requirement (from versions: none) ERROR: No matching distribution found for torch==1.12.1
> 
> have loaded the update via anaconda. but brings nothing. i then come back to the app when it also becomes installable for designers.

Install Any Version Of Python >3.10
