### ISSUE TITLE
[enhancement]: Series of suggestions

### ISSUE THREAD

**Issue by ARandomUserFromGithub** [invoke-ai/InvokeAI#1854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Hi, there are several features I would like to see in iAI: 
°The ability to add anchors to the canvas, to the txt2img and to img2img on which we could give instructions to the AI or indicate what is below the anchor. [replace river's water with honey] [This is a forest] [This is where I want to see a forest] [This is a rock, preserve it]
°Also it would be great if it could handle canvas rotation, and noise rotation whereas painting an upside down landscape is funny but unreliable with current state of SD. Rotating canvas would help inpaint some details that otherwise would be rendered incorrectly. Example: a bottle on the ground rotated 23° left. Majority of bottle photos are probably sitting straight on the shelf.
°It would be great if there was a noise selector where we could chose in a variety of noises corresponding to a section of a prompt and pick our favorite noises. Example: Grass field. I could pick long grass and every long grass that matches well together, pick some that shows flowers, some that shows stones. 
°A way to disable parts of a prompt temporarily which could be checkboxes or !--- tags or ## tags.  A large canvas is composed of different subjects. ##A mountain in the distance##, a flower field with freshly planted pine tree, ##A river##, ##rocks on the river bed## would concentrate only on the flower field with trees.
°Another nice feature would be the ability to load G'Mic filters inside the interface.
°Canvas should come with "High Res Optimization" so it can chop a render into tiles without losing precision or even work on the entire canvas and render it small, first, then sticks to seed and materials for the big picture. 

About noise rotation, with that capability, I assume that hands on characters would be much better

While I'm around, one more feature that I would really appreciate is the capability to render transparent backgrounds and also to embed "depth maps" as alpha channel whenever you can integrate custom scripts, hence the depthmap script!

Another idea here: The same marker to turn sections of prompts off, ##, could be used to set order of statements so they're reorganized in order when the render starts. #1 or #01 for an active first prompt, ##1 for inactive or ##0001 or any padding.

So ... #1 A table surrounded with chairs #1 (Here, the closing tag can be implicit and close with #2 if #1 closing tag is missing) #2 A floor with wooden tiles of various color #3 In the distance, a kitchen with shelves, a counter and an oven, fridge in the left corner" #4 Window on the rear wall and a door on the right side #4, (Here I compose with and without end tags... Maybe end tags aren't necessary as it's implicit), #5 On the floor, a brown dog chewing on a rope 

These tags could be used alongside with markers on the canvas, the anchor markers I mentioned earlier.

Another great thing that could be prompted is min, max coordinates... Example, adding m(x,y) M(x¹,y¹) in between any () [] ## prompts could move the focus of attention for the statement.

Another feature: It should be able to differentiate all caps, and all caps should be used for both embeddings and trained words lists, or any relevant such lists... And ignore capitalization if the file is missing, pass it as a normal expression.

Something that would simplify all these tasks would be to have a main prompt window, with a list of the prompts below with checkboxes inside the list. 
When you would press "add statement" it would add #n (Any number in order), in the main editor... And the new statements would have several checkboxes and weight sliders which already exists (statement:1.1)  which would become #1(statement:1.1) and display a new item in the checkbox list with its . So a statement could be ##3[clouds:1.1, m(0px, 123px) M(300px, 650px)] and clouds wouldn't be removed by the negative prompt in the area, but to activate it, removing 1 # would reenable it, which would actually remove clouds in the area, or not generate clouds in the area. In counterpart, adding a positive prompt next to it saying #4(clouds:0.5, m(600, 900) M(1000, 1000) would, if these coordinates makes sense, paint actual clouds in the given area. These could be automatically written with adding new anchors and placing them on the editor.

**Comment by hipsterusername** [comment]
Going to reply here to note that this feedback has been noted and preserved! We'll close it out for now as this falls under a lot of the things we're aiming to do on our roadmap, but wanting to make sure it's explicitly noted as "reviewed". :)
