### ISSUE TITLE
[bug]: Model Stable Diffusion 2.1 could not be loaded - Missing 'personalization_config'

### ISSUE THREAD

**Issue by LucasDash** [invoke-ai/InvokeAI#1857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What happened?

Hi, I tried manually installing Stable Diffusion 2.1 on InvokeAI, but appeared the problem in the screenshot in which I don't know the solution, there was a previous problem that was to update the configuration .yaml file to version 2 (v2-inference.yaml), I already did it, now appears this current error of missing 'personalization_config' that I do not understand. What can I do to fix it?

### Screenshots

![SD_error](https://user-images.githubusercontent.com/9156478/206401955-87057241-d324-40dd-9a06-2a9c45482107.png)

**Comment by Owyx** [comment]
InvokeAI 2.2.0 does not support the Stable Diffusion 2.0 model at the current time.

**Comment by LucasDash** [comment]
Oh, got it. I wasn't aware of that spec.

**Comment by hangingman** [comment]
It seems some people working for dealing with Stable Diffusion v2 here #1543
