### ISSUE TITLE
[bug]: Killed while loading 1.5

### ISSUE THREAD

**Issue by tjthejuggler** [invoke-ai/InvokeAI#1858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cpu

### What happened?

It says 'Killed' when I try to run invoke.py --web as seen below

(invokeai) lunkwill@Will-of-Lunk:~/Programs/stable-invoke/invokeAI$ python scripts/invoke.py --web
* Initializing, be patient...
>> Initialization file /home/lunkwill/.invokeai found. Loading...
>> InvokeAI runtime directory is "/home/lunkwill/invokeai"
>> Patchmatch initialized
>> GFPGAN Initialized
>> CodeFormer Initialized
>> ESRGAN Initialized
>> Using device_type cuda
>> Current VRAM usage:  0.00G
>> Scanning Model: stable-diffusion-1.5
>> Model Scanned. OK!!
>> Loading stable-diffusion-1.5 from /home/lunkwill/invokeai/models/ldm/stable-diffusion-v1/v1-5-pruned-emaonly.ckpt
   | LatentDiffusion: Running in eps-prediction mode
   | DiffusionWrapper has 859.52 M params.
   | Making attention of type 'vanilla' with 512 in_channels
   | Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
   | Making attention of type 'vanilla' with 512 in_channels
Killed

### Additional context

I have 16g normal RAM
and this is my GPU: Intel Corporation CometLake-U GT2
the laptop in an ASUS ZenBook running Ubuntu 22.04

**Comment by realenuf** [comment]
I now have the same issue on Ubuntu 22.04, with an rtx 3060.
>> Using device_type cuda
>> Current VRAM usage:  0.00G
>> Scanning Model: stable-diffusion-1.5
>> Model Scanned. OK!!
>> Loading stable-diffusion-1.5 from /media/iwoolf/BigDrive/Stable-diffusion/models/ldm/stable-diffusion-v1/v1-5-pruned-emaonly.ckpt
Terminated

**Comment by Thyself17** [comment]
I'm also getting this error while loading either 1.4 or 1.5.  I haven't yet tried any other models.  Same console output as OP.

I am running on Ubuntu 20.04 on WSL, 16GB memory.  Nvidia-smi correctly shows my rtx 3070.
