### ISSUE TITLE
[bug]: can't import new models

### ISSUE THREAD

**Issue by 2refocus** [invoke-ai/InvokeAI#1865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cuda

### VRAM

32

### What happened?

Importing new models didn't work. It didn't found the path.
The model is in the right folder. InvokeAi is started using the CLI. 

(I also tried with the complete path with the same result) 

from my terminal: 

invoke> !import_model models/ldm/stable-diffusion-v1/robo-diffusion-v1.ckpt
** models/ldm/stable-diffusion-v1/robo-diffusion-v1.ckpt: file not found

invoke> !import_model /Users/xxx/invokeai/models/ldm/stable-diffusion-v1/robo-diffusion-v1.ckpt
** /Users/xxx/invokeai/models/ldm/stable-diffusion-v1/robo-diffusion-v1.ckpt: file not found

**Comment by nelsonre** [comment]
The first thing to double check is whether the file is actually there.
In a terminal:
ls -l /Users/xxx/invokeai/models/ldm/stable-diffusion-v1/
and see if the robo file appears in the listing

**Comment by bach777** [comment]
Same problem....

**Comment by 2refocus** [comment]
> The first thing to double check is whether the file is actually there.
> 
> In a terminal:
> 
> ls -l /Users/xxx/invokeai/models/ldm/stable-diffusion-v1/
> 
> and see if the robo file appears in the listing

That's what i already said. It is there. I used a lot of different models in automatic 111 and stable diffusion without any problems. So there must be a different path / config / import problem. 

Thanks for taking time.

**Comment by nelsonre** [comment]
No worries. I was suggesting checking the directory because I also had a similar (file not found) issue. I just had the wrong path. I had mixed up models/ldm with ldm/models. But that doesn't sound like it was your issue.
