### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by Stanley050677** [invoke-ai/InvokeAI#1868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### What happened?

You can now start generating images by running invoke.sh (inside this folder), using ./invoke.sh
stanislawjanusz@Stanisaws-MacBook-Pro ~ % ./invoke.sh
zsh: no such file or directory: ./invoke.sh
stanislawjanusz@Stanisaws-MacBook-Pro ~ % /bin/bash "/Users/stanislawjanusz/invokeAAI/invokeAI/source_installer/invoke.sh.in"
/Users/stanislawjanusz/invokeAAI/invokeAI/source_installer/invoke.sh.in: line 8: conda: command not found
/Users/stanislawjanusz/invokeAAI/invokeAI/source_installer/invoke.sh.in: line 9: /etc/profile.d/conda.sh: No such file or directory
/Users/stanislawjanusz/invokeAAI/invokeAI/source_installer/invoke.sh.in: line 11: conda: command not found
Do you want to generate images using the
1. command-line
2. browser-based UI
3. open the developer console
Please enter 1, 2, or 3: 2

Starting the InvokeAI browser-based UI..
/Users/stanislawjanusz/invokeAAI/invokeAI/source_installer/invoke.sh.in: line 26: python: command not found
stanislawjanusz@Stanisaws-MacBook-Pro ~ %

**Comment by ebr** [comment]
Do not use the `invoke.sh.in` script. It's not meant to be run directly and will not work. You need to change to the directory where you installed `invokeai`. Likely this will be in your `Users/stanislawjanusz/invokeai` directory. Try to run `invoke.sh` from there.

**Comment by Stanley050677** [comment]
Thank You Eugene,
It helps and it is working now :)
Regards

**Comment by seefood** [comment]
Then please close the bug report?

**Comment by Stanley050677** [comment]
Done. :)
