### ISSUE TITLE
[bug]: DLL load failed while importing _lzma

### ISSUE THREAD

**Issue by GafferWiles** [invoke-ai/InvokeAI#1871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6Gb

### What happened?

When installing InvokeAI for the first time on my Windows 10 machine I get the following error

ImportError: DLL load failed while importing _lzma: the specified module could not be found.

It seems that there is a missing module and might be related to the following report https://github.com/pytorch/vision/issues/2921

I could find no instructions as to how to install or add this module in a Windows environment with anaconda or python.
![InvokeAIInstallError](https://user-images.githubusercontent.com/19478672/206571639-856faf5f-ee9c-401b-8280-c3541667b087.PNG)

### Contact Details

hamfast@bagshotrow.co.za

**Comment by KevinDenys** [comment]
same issue

**Comment by brunocerq** [comment]
Same issue here

**Comment by dmichura** [comment]
Same issue

**Comment by machismo** [comment]
Same issue - first time install Windows 11

**Comment by KevinDenys** [comment]
Fixed it by running the update.bat script

**Comment by brunocerq** [comment]
> Fixed it by running the update.bat script

I run the update.bat script and apparently it did success, but when I run the Invoke.bat and choose the webUi I get the following error:

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
   You appear to have a missing or misconfigured model file(s).
   The script will now exit and run configure_invokeai.py to help fix the problem.
   After reconfiguration is done, please relaunch invoke.py.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
configure_invokeai is launching....

Loading Python libraries...

An exception has occurred: DLL load failed while importing _lzma: The specified module could not be found.

So, the Lzma issue persists.

**Comment by joshwcorbett** [comment]
Encountered this issue when running `install.bat` on accident, tried running `update.bat` to fix but the terminal would close as soon as I run the web ui. After deciding to just do a fresh reinstall, all was going well until I ended up back where I started:
```
ImportError: DLL load failed while importing _lzma: the specified module could not be found.
```

**Comment by guixvieira** [comment]
It seems to be just a package issue. Found lots of fixes by installing other packages but could not replicate them on windows. Everything was focused on Mac/Linux. Any ideas?

**Comment by artistx81** [comment]
Same problem..

ImportError: DLL load failed while importing _lzma: The specified module could not be found.

tried update.bat but it didnt seem to solve the issue.

**Comment by Dextroo** [comment]
Same issue here, accidentally ran the "install.bat" and it began uninstalling packages, so I closed it as fast as I could, but seem to be stuck here now even after a clean install.

'ImportError: DLL load failed while importing _lzma: The specified module could not be found.'

**Comment by Schlumpikatze** [comment]
It's the same for me...

ImportError: DLL load failed while importing _lzma: The specified module could not be found.

Guessing it happened when an anti virus, which i dont even recall installing, interrupted the install.bat.

**Comment by joshwcorbett** [comment]
I just went through all the necessary steps to manually install, I got all the way up to step 8 when I ran
```
python scripts/configure_invokeai.py
```
But alas the result was the same... no change.

**Comment by joshwcorbett** [comment]
## UPDATE
I was able to install invokeAI AND run the webui by using the anaconda terminal to run `install.bat` and `invoke.bat` without issues

**Comment by Dextroo** [comment]
I was able to fix this by manually deleting the contents of installer_files and restarting my computer, then running install.bat again.

However, I would say that install.bat badly needs a Y/N confirmation to run, as it is right next to invoke.bat in the folder and is easy to mis-click if you're moving quickly. A script in the root directory shouldn't just begin uninstalling dependencies as soon as it is run, especially if it does not indicate it.

**Comment by brunocerq** [comment]
I deleted the contents of installer_files as @Dextroo did and run the install again, got a few more prompts but in the end the install was successful.

**Comment by Gnadri** [comment]
> anaconda terminal
launching it through there solved the issue for me
