### ISSUE TITLE
[enhancement]: Web Interface should support Collections for gallery and output location organization

### ISSUE THREAD

**Issue by dunkeroni** [invoke-ai/InvokeAI#1872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Outputs are not easily organized, particularly when accessing the server interface remotely. Some users separate outputs into themes, others cherry-pick favorites out of larger sets, but most would benefit from some sort of sub-folder control on their outputs directly from the interface.

To be fully flexible and accommodate most workflows, collections in the gallery should have the following basic features:
1. Create new subfolders in outputs with custom names. By default there should be "Favorites" or something similar.
2. View individual collection subfolders in the gallery panel rather than the base outputs folder.
3. "Send To Collection" option when right clicking an image in the gallery.
4. Set a collection as the output folder for the current generation. This should be a separate option from the currently viewed collection.
5. Batch select/move multiple images to a collection, or option to move the last 'n' outputs to a specified collection.

**Comment by whosawhatsis** [comment]
See also: https://github.com/invoke-ai/InvokeAI/issues/1270 and https://github.com/invoke-ai/InvokeAI/issues/1889

**Comment by psychedelicious** [comment]
Implanted in v3
