### ISSUE TITLE
[enhancement]: add the ability to select the aspect ratio 16:9, 9:16, 4:3, 3:4 etc.

### ISSUE THREAD

**Issue by Yanflint** [invoke-ai/InvokeAI#1879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Since the result depends on the aspect ratio, it is often necessary to set the desired aspect ratio, most often it is required, for example, 3:4 portrait or 16:9 full size.

I think choosing the aspect ratio right away would have made the setup process faster and more enjoyable.

Also, want a quick size multiplier option, like so:

1. I pressed the 16:9 button and the canvas size became 512x288
2. if I need more resolution, I just press the + button and the resolution increases one step higher

<img width="379" alt="UI" src="https://user-images.githubusercontent.com/120166015/206652593-43c91214-9a6a-486c-9e07-8c3ffe48983e.png">

**Comment by Void2258** [comment]
This would be handy, but would have to be set up to handle limitations in the usable sizes (such as a need for dimensions in multiple of 64). Alternatively, a box to display what the ratio is for the HxW you have selected could be a backup solution, to at least provide the information to the user.
