### ISSUE TITLE
[bug]: Installation - no module named tqdm

### ISSUE THREAD

**Issue by ReinerBforartists** [invoke-ai/InvokeAI#1880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

While installing the installation process hangs at the point to call the configure_invokeai.py file with the error ModuleNotFoundError: No module named 'tqdm'. Which means i am not able to finish the setup.

Setup done with invokeAI-src-installer-2.2.3-windows.zip

### Screenshots

![can't continue](https://user-images.githubusercontent.com/13919702/206667995-f47f75d0-7d02-482f-9dc4-fbbf977c2d69.jpg)

**Comment by osafaimal** [comment]
run conda init <name of the shell>
but i don't think that's the problem (i've the same and i don't find how solves it)

**Comment by ReinerBforartists** [comment]
Thanks for the advice, but i have uninstalled it for now ...
