### ISSUE TITLE
[enhancement]: Google Colab integration for SD2

### ISSUE THREAD

**Issue by nelohenriq** [invoke-ai/InvokeAI#1882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

herminiohenriques@gmail.com

### What should this feature add?

Can't install on Google Colab because of pypatchmatch error, seems like pypatchmatch needs python 3.9 and colab runs on 3.8, is there away to go around this?? I'd love to test InvokeAI on colab since i don't have a NVIDIA GPU on local machine

**Comment by oxie** [comment]
probably inside codelab you can create conda env with python 3.9, i think

**Comment by oxie** [comment]
oh actually check this one, its in russian/slavic language but someone manage to get it working 1 week ago- https://colab.research.google.com/github/peaashmeter/invoke-ai-gui-colab/blob/main/invoke_ai_gui_colab.ipynb

**Comment by ForceConstant** [comment]
I was wondering if this was ever going to be integrated into Invoke-AI repo itself? It would be great if there was a "colab" button right on the Readme.md to start Invoke-AI.

**Comment by renatokuipers** [comment]
> I was wondering if this was ever going to be integrated into Invoke-AI repo itself? It would be great if there was a "colab" button right on the Readme.md to start Invoke-AI.

I absolutely agree with this smart person :)

**Comment by Lycantant** [comment]
> I was wondering if this was ever going to be integrated into Invoke-AI repo itself? It would be great if there was a "colab" button right on the Readme.md to start Invoke-AI.

the colab version in this repo was never updated 😥

**Comment by Millu** [comment]
@CptanPanic [take a look at this notebook](https://colab.research.google.com/drive/1jThZ0VHfFmjVbiPOgm-B-KH6Li6pXMG9?usp=sharing). Should be working with all features to date for InvokeAI
