### ISSUE TITLE
[bug]: AnythingV3 returns black images from time to time

### ISSUE THREAD

**Issue by kryztoval** [invoke-ai/InvokeAI#1884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24GB

### What happened?

I keep trying to generate images with anythingv3 and sometimes it returns a black image. The generation shows promising steps in fast and in precise preview, but the final image is black. If I try to reduce the requested resolution it generates the image, sometimes if I change the cfg scale or the prompt it will generate an image, but most of the time it still fails. There are no errors displayed anywhere.

### Screenshots

![image](https://user-images.githubusercontent.com/5733028/206767793-b7b64196-9096-4e91-9c66-5b705531e9ab.png)

### Additional context

I tried using fp16, fp32, pruned and noema but the results were always erratic and the black images kept happening.

I understand this is a longshot because the model being used is not a standard model, but this error does not happen in a1111.

Is there a way to call the generation from the terminal to see if this happens there as well?

**Comment by kryztoval** [comment]
Here is the terminal view directly to the one image generated.

![image](https://user-images.githubusercontent.com/5733028/206768402-22436602-eef5-417d-8546-669ad7c05551.png)

**Comment by addianto** [comment]
Maybe the `safety_checker` (NSFW checker) kicked in at the last step of the image generation. Have you tried disabling it?

You can disable NSFW checker by adding `--no-nsfw_checker` option into `.invokeai` file in your user home directory, i.e. `C:\Users\<YOURNAME>\`.

**Comment by kryztoval** [comment]
It has never been enabled in my installation, so I am pretty sure that is not it. Any other ideas?

**Comment by bach777** [comment]
@addianto How can I load a downloaded model? I didn't download inpanting1.5 due to connection problems, but now I have it downloaded, I placed it in the folder invokeAI\models\ldm\stable-diffusion-v1, but it doesn't appear as a selectable option.

**Comment by jlcebrian** [comment]
I had the same problem and it was caused by adding the AnythingV3 VAE to the models config file. Once I removed that, the images that previously were black would show correctly (the seeds that worked would generate the same output, so I suspect that VAE file is not compatible with InvokeAI).

**Comment by kryztoval** [comment]
@jlcebrian Gracias! I am going to test that and see if that fixes it. Thank you very much.
