### ISSUE TITLE
Error: ModuleNotFoundError: No module named 'numpy', while trying to train Textual Inversion

### ISSUE THREAD

**Issue by joshdance** [invoke-ai/InvokeAI#1886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What happened?

On an M1 Mac, attempted to use the command mentioned here, https://github.com/invoke-ai/InvokeAI/pull/814, to start training using Textual Inversion 

This results in this error in the Terminal: 

```
Traceback (most recent call last):
  File "/Users/adminadmin/invokeAI/./main.py", line 2, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
zsh: command not found: --base
zsh: command not found: --actual_resume
zsh: command not found: --data_root
zsh: command not found: --gpus
zsh: command not found: --no_test
```

I used pip3 to install numpy and then ran it again. This time it gives the error `ModuleNotFoundError: No module named 'torch'`

Seems like I a missing dependencies to be able to run Textual Inversion. Is there a script to run to set it up? Or a list of dependencies that I could check? 

### Contact Details

Twitter @joshdance

**Comment by hades2510** [comment]
Are you using the `conda` env that was created when running installing InvokeAI?
I had a similar problem, but I was trying to use a different python version and .env wasn't configured for this.

**Comment by joshdance** [comment]
@hades2510 Not sure if I'm using the conda env that was created when running installing InvokeAI.

How would I check? I'm a bit rusty on command line techniques. :)
