### ISSUE TITLE
[bug]: segfault line 24 invoke.py and problem with patchmatch

### ISSUE THREAD

**Issue by osafaimal** [invoke-ai/InvokeAI#1888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

amd

### What happened?

i've installed invokeAI and when the installer tell me i can run the invoke.sh, i've run it and the invoke.py return a segfault at line 24.
i've installed patchmatch as https://invoke-ai.github.io/InvokeAI/installation/INSTALL_PATCHMATCH/ explains, but when i run invoke.sh it tell me it failed to load or compile.

thanks you for your help

### Screenshots

![image](https://user-images.githubusercontent.com/47930050/206790018-c6b130b1-4233-4e2c-9661-ae90887f4a2a.png)

**Comment by Lolagatorade** [comment]
Yup same issue. official page on github giving instructions gives error 404 mabe theyre changing some tings up. hopefully fixed by christmas i have some projects that will benefit from some infill
