### ISSUE TITLE
[enhancement]: Invokation search

### ISSUE THREAD

**Issue by whosawhatsis** [invoke-ai/InvokeAI#1889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Sorry if this is a duplicate. I did search, but the "I have searched the existing issues" line in the template made it return almost every issue ever posted.

The idea is to add a search box to the invokation list, to allow you to search/filter the list for images that used a particular set of terms in the prompt, and other details saved in the metadata. Bonus points for making it possible to save these searches (similar to the concept of smart folders/playlists) to run again when more files have been added. There are some other good ideas to ~~steal~~ ~~copy~~ learn from here: https://github.com/RupertAvery/DiffusionToolkit

Another thing that would be cool would be able to collapse images that have identical metadata except for specified fields (seed, for example) into a folder/stack in the panel, so that you don't have to scroll past dozens or hundreds of variations on one concept to find ones from a previous project. A custom "project" metadata tag might even be used to as a proxy for actual folders.

See also, https://github.com/invoke-ai/InvokeAI/issues/1270

**Comment by Millu** [comment]
Closing as a duplicate of #3943
