### ISSUE TITLE
[bug]: Cannot load anything but v1-5-pruned-emaonly.ckpt

### ISSUE THREAD

**Issue by githubUser01946** [invoke-ai/InvokeAI#1894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

I cannot load custom models or even the 1.5 inpainting model I have attached a screenshot, it is trained on 1.5. 

If I choose a different model from the dropdown menu it will say "Model Changed" but it hasn't. If I choose to load it via settings then it doesn't load, in CMD it gives an error which is in the screenshot.

The location for files match what is in the models.yaml file which itself is located in: `C:\Users\cpgsa\invokeai\configs`

Models.yaml is attached.

### Screenshots

![Screenshot 2022-12-10 143426](https://user-images.githubusercontent.com/117453319/206860930-1e1cb35a-083f-4831-9a6b-47af4c5e1b82.png)

### Additional context

models.yaml:

stable-diffusion-1.5:
  description: The newest Stable Diffusion version 1.5 weight file (4.27 GB)
  
 weights: models/ldm/stable-diffusion-v1/v1-5-pruned-emaonly.ckpt
  config: configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
  default: true

nutronicsteve-2:
  description: CUSTOM MODEL
  weights: models/ldm/stable-diffusion-v1/CUSTOMMODEL.ckpt
  width: 512
  height: 512

inpainting-1.5:
  weights: models/ldm/stable-diffusion-v1/sd-v1-5-inpainting.ckpt
  config: configs/stable-diffusion/v1-inpainting-inference.yaml
  vae: models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
  description: RunwayML SD 1.5 model optimized for inpainting

### Contact Details

[@nutronic@masto.ai](https://masto.ai/@nutronic)

**Comment by blessedcoolant** [comment]
You need to setup a config entry too for the model. If it is a 1.x model of SD, then you can just copy paste the config from the other examples. It'll 99% be the same one.

**Comment by githubUser01946** [comment]
> You need to setup a config entry too for the model. If it is a 1.x model of SD, then you can just copy paste the config from the other examples. It'll 99% be the same one.
> 
> ```
> nutronicsteve-2:
> description: CUSTOM MODEL
> weights: models/ldm/stable-diffusion-v1/CUSTOMMODEL.ckpt
> config: configs/stable-diffusion/v1-inpainting-inference.yaml
> width: 512
> height: 512
> ```

Ok I can do that, but what is stopping the inpainting model from loading?

**Comment by blessedcoolant** [comment]
> > You need to setup a config entry too for the model. If it is a 1.x model of SD, then you can just copy paste the config from the other examples. It'll 99% be the same one.
> > ```
> > nutronicsteve-2:
> > description: CUSTOM MODEL
> > weights: models/ldm/stable-diffusion-v1/CUSTOMMODEL.ckpt
> > config: configs/stable-diffusion/v1-inpainting-inference.yaml
> > width: 512
> > height: 512
> > ```
> 
> Ok I can do that, but what is stopping the inpainting model from loading?

Made a small correction to the config in the above reply.

What's the issue with the inpainting model? What error does it throw?

**Comment by githubUser01946** [comment]
> > > You need to setup a config entry too for the model. If it is a 1.x model of SD, then you can just copy paste the config from the other examples. It'll 99% be the same one.
> > > ```
> > > nutronicsteve-2:
> > > description: CUSTOM MODEL
> > > weights: models/ldm/stable-diffusion-v1/CUSTOMMODEL.ckpt
> > > config: configs/stable-diffusion/v1-inpainting-inference.yaml
> > > width: 512
> > > height: 512
> > > ```
> > 
> > 
> > Ok I can do that, but what is stopping the inpainting model from loading?
> 
> Made a small correction to the config in the above reply.
> 
> What's the issue with the inpainting model? What error does it throw?
Here you go:
![Screenshot 2022-12-10 163135](https://user-images.githubusercontent.com/117453319/206865136-56f57f73-6f1d-47e6-89a9-b88ed0f754eb.png)

**Comment by blessedcoolant** [comment]
@githubUser01946 That's actually a bug from our end. The inpainting config needs to have width and height defined.
Add width: 512 and height: 512 to that  and it'll work.

**Comment by githubUser01946** [comment]
> @githubUser01946 That's actually a bug from our end. The inpainting config needs to have width and height defined. Add width: 512 and height: 512 to that and it'll work.

> @githubUser01946 That's actually a bug from our end. The inpainting config needs to have width and height defined. Add width: 512 and height: 512 to that and it'll work.

Ok so my new models file looks like this:
![image](https://user-images.githubusercontent.com/117453319/206903171-cefd35f0-e54d-4919-9fe6-cc477259d154.png)

When I try to load the custom model this happens:
![image](https://user-images.githubusercontent.com/117453319/206903567-5c10a933-3a06-4e49-8a4e-47e7f36dce5f.png)

The models are present in the folder: `C:\Users\cpgsa\invokeai\models\ldm\stable-diffusion-v1` as this was what I was told on Discord.

I have updated today via the update bat file and moved the .invokeai file to C:\Users\cpgsa\invokeai as stated.

**Comment by blessedcoolant** [comment]
Hang in there for a bit. There's some pathing issues due to recent changes. We're resolving them right now.

**Comment by githubUser01946** [comment]
> Hang in there for a bit. There's some pathing issues due to recent changes. We're resolving them right now. Check once again after that and see if it works for you. I'll ping you when those changes are live so you can update.

Is this what I need to update to now using **update.bat**?

https://github.com/invoke-ai/InvokeAI/releases/tag/2.2.4-rc2

**Comment by githubUser01946** [comment]
I have ran the updater and it has done its thing but I notice .invoke file is still called that and not invokeai.init and I am still getting `[Errno 2] No such file or directory` as recent screenshots have shown yet the v1-5-pruned-emaonly.ckpt file is loading fine.

I have also noticed that there are extra `\' when its looking for the path i.e `'C:\\Users\\cpgsa\\invokeai\\models\\ldm\\stable-diffusion-v1\\` when it should obviously be `'C:\Users\cpgsa\invokeai\models\ldm\stable-diffusion-v1\`.

**Comment by githubUser01946** [comment]
Uninstalling invoke.

**Comment by blessedcoolant** [comment]
> I have ran the updater and it has done its thing. I have changed .invoke to invokeai.init and I am still getting `[Errno 2] No such file or directory` as recent screenshots have shown yet the v1-5-pruned-emaonly.ckpt file is loading fine.
> 
> I have also noticed that there are extra `\` when its looking for the path i.e `'C:\\Users\\cpgsa\\invokeai\\models\\ldm\\stable-diffusion-v1\\` when it should obviously be `'C:\Users\cpgsa\invokeai\models\ldm\stable-diffusion-v1\`.
> 
> I have changed the model locations in models.yaml to C:\Users\cpgsa\invokeai\models\ldm\stable-diffusion-v1\ as I was told to on Discord.

We've redone the install process. There's a new RC up. https://github.com/invoke-ai/InvokeAI/releases/tag/2.2.4-rc2

This should hopefully fix any pathing issues you have.
