### ISSUE TITLE
[bug]: 'CrossAttention' object has no attribute 'cached_mem_free_total'

### ISSUE THREAD

**Issue by Caio-Sc** [invoke-ai/InvokeAI#1896]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What happened?

Whenever I try to use any function to generate an image, I get this error "'CrossAttention' object has no attribute 'cached_mem_free_total'" (I'm using the browser-ui)

### Screenshots

2022-12-10T13:18:32-0300:

Image generation requested: {"prompt":"","iterations":1,"steps":50,"cfg_scale":7.5,"threshold":0,"perlin":0,"height":512,"width":512,"sampler_name":"k_lms","seed":2325424055,"progress_images":true,"progress_latents":false,"save_intermediates":5,"generation_mode":"txt2img","init_mask":"","seamless":false,"hires_fix":false,"variation_amount":0}

2022-12-10T13:18:32-0300:

Server error: 'CrossAttention' object has no attribute 'cached_mem_free_total'

**Comment by joncutrer** [comment]
I just experienced the same error!

OS
Windows 11

GPU
cuda (RTX 3070ti)

VRAM
8GB

**Comment by kindlyfire** [comment]
I am also experiencing the same error. On a new install, with all my installed models

**Comment by einthecorgi2** [comment]
Same. On same platform 3070 8Gb, i7

**Comment by addianto** [comment]
While waiting for the 'official' fix from the maintainers, there is a temporary solution for the error for the `cached_mem_free_total` problem:

1. Open `./ldm/models/diffusion/cross_attention_control.py` file using a text editor.
2. Go to line 187, add the following code: `self.cached_mem_free_total = None` below the other 4 lines that start with `self.`. For clarity, attached is the screenshot how the code should look like:
    
![image](https://user-images.githubusercontent.com/955505/206865265-600384b7-2758-4d07-b6f1-7bcbd78d5cf3.png)

3. Save the file and try restarting InvokeAI.
