### ISSUE TITLE
[bug]: Using Image to Image results in "Server error: list index out of range"

### ISSUE THREAD

**Issue by tone-milazzo** [invoke-ai/InvokeAI#1904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

24GB

### What happened?

Thanks to all developers involved with this project for all your hard work.
Just performed an update an hour ago.
Applied the hotfix for the CrossAttention bug: https://github.com/invoke-ai/InvokeAI/issues/1896
InvokeAI is on a local server and accessed over LAN from Laptop over WIfi
Error occurred both for image uploaded from laptop and from image generated on server and send to Image to Image.
InvokeAI can generate Text to Image just fine.

In the log, noticed the init_img entry has three periods at the end of the filename.

Full log for operation:
```
2022-12-10T11:24:35-0800:

Image generation requested: {"prompt":"professional, high-quality, black and white, charcoal drawing of a nude asian woman by Malcolm Liepke [background], [disfigured], [kitsch], [oversaturated], [grain], [low-res], [Deformed], [blurry], [bad anatomy], [disfigured], [poorly drawn face], [mutation], [mutated], [extra limb], [poorly drawn hands], [missing limb], [blurry], [floating limbs], [disconnected limbs], [malformed hands], [blur], [out of focus], [long neck], [long body], [disgusting], [poorly drawn], [childish], [mutilated], [mangled], [old], [surreal], [cross eyed], [text]\n","iterations":4,"steps":50,"cfg_scale":8,"threshold":0,"perlin":0,"height":512,"width":512,"sampler_name":"k_lms","seed":3046103082,"progress_images":false,"progress_latents":false,"save_intermediates":5,"generation_mode":"img2img","init_mask":"","seamless":false,"hires_fix":false,"init_img":"outputs/000036.f1fd78dc.3656908702.png...","strength":0.28,"fit":true,"variation_amount":0,"enable_image_debugging":true}

2022-12-10T11:24:37-0800:

Server error: list index out of range
```

**Comment by micsche** [comment]
Same issue here. 
Image to Image from Web.

OS
Windows 10

GPU
cuda

VRAM
8GB

Terminal output:
 Running DDIMSampler sampling starting at step 13 of 50 (37 new sampling steps)
Decoding image: 100%|██████████████████████████████████████████████████████████████████| 37/37 [00:23<00:00,  1.55it/s]
>> target t_enc is 7 steps█████████████████████████████████████████████████████████████| 37/37 [00:23<00:00,  1.56it/s]
>> Running DDIMSampler sampling starting at step 3 of 10 (7 new sampling steps)
Decoding image: 100%|████████████████████████████████████████████████████████████████████| 7/7 [00:04<00:00,  1.53it/s]
>> target t_enc is 37 steps██████████████████████████████████████████████████████████████| 7/7 [00:04<00:00,  1.55it/s]
Generating:   0%|                                                                                | 0/1 [00:38<?, ?it/s]
list index out of range


Traceback (most recent call last):
  File "d:\stablediffusion\invokeai\backend\invoke_ai_web_server.py", line 1124, in generate_images
    self.generate.prompt2image(
  File "d:\stablediffusion\invokeai\ldm\generate.py", line 488, in prompt2image
    results = generator.generate(
  File "d:\stablediffusion\invokeai\ldm\invoke\generator\base.py", line 106, in generate
    image_callback(image, seed, first_seed=first_seed, attention_maps_image=attention_maps_images[-1])
IndexError: list index out of range

Thank you all.

**Comment by micsche** [comment]
Maybe attention_maps_images makes use of get_make_image function. And that is not implemented in the same "generator\base.py"?

_# this is going to be overridden in img2img.py, txt2img.py and inpaint.py
    def get_make_image(self,prompt,**kwargs):
        """
        Returns a function returning an image derived from the prompt and the initial image
        Return value depends on the seed at the time you call it
        """
        raise NotImplementedError("image_iterator() must be implemented in a descendent class")_

**Comment by hankhan425** [comment]
Can see the same error on my M1 Mac. img2img worked fine before updating to the latest version today.

**Comment by damian0815** [comment]
appears fixed on latest main
