### ISSUE TITLE
[bug]: PNG compression help text goes to 0 to 9 for compression when 8 is the max

### ISSUE THREAD

**Issue by Fortyseven** [invoke-ai/InvokeAI#1912]
### What happened?

This is pretty trivial, but the help text in `invoke.py` says ` --png_compression` ranges from 0 to 9, when the argument itself is bound to a max of 8.

```
  --png_compression {0,1,2,3,4,5,6,7,8}, -z {0,1,2,3,4,5,6,7,8}
                        level of PNG compression, from 0 (none) to 9
                        (maximum). Default is 6.
```

Current as of 0439b51a

**Comment by n00mkrad** [comment]
`--png_compression` does not do anything at all, by the way.

https://github.com/invoke-ai/InvokeAI/issues/2945

**Comment by n00mkrad** [comment]
Not OP, but this is still an issue.

It goes from 0 to 10 right now.
