### ISSUE TITLE
[bug]: doesn't work on macOS M1 

### ISSUE THREAD

**Issue by taishi55** [invoke-ai/InvokeAI#1913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cuda

### VRAM

16GB

### What happened?

1. run `python3 scripts/invoke.py --web`
2. then error `ModuleNotFoundError: No module named 'ldm'` is displayed

### Additional context

#723 is closed, but I think the issue is not fixed yet

**Comment by psychedelicious** [comment]
@taishi55 
You should only run `python scripts/invoke.py --web` directly if you manually installed (`git clone`'d the repo, and set up a conda environment). 

And if you *did* manually install, you need to activate the conda environment first e.g. `conda activate invokeai`.

If you did not manually install, and instead used the automated installer, you need to instead run the `invoke.sh` script to start InvokeAI.

**Comment by GGGGGHT** [comment]
i'm clone'd the repo and typed `conda activate invokeai`, return: 
```
EnvironmentNameNotFound: Could not find conda environment: invokeai
You can list all discoverable environments with `conda info --envs`.
```

**Comment by mauwii** [comment]
> ### What happened?
> 1. run `python3 scripts/invoke.py --web`
> 2. then error `ModuleNotFoundError: No module named 'ldm'` is displayed

From where do you run this command? Did you activate the virtual environment beforehand?

maybe also follow the steps from the manual (https://invoke-ai.github.io/InvokeAI/installation/INSTALL_AUTOMATED/), this way you would not need to run python yourself and can just use invoke.sh ;)

**Comment by sutt** [comment]
I got this error when I create the conda env within the `environments-and-requirements` directory.

After copying the .yml out to root, (I deleted previous bad env) and I reran the env creation from root and it worked.

**Comment by taishi55** [comment]
> invoke.sh

I got this error `zsh: command not found: invoke.sh`

**Comment by mauwii** [comment]
> > invoke.sh
> 
> I got this error `zsh: command not found: invoke.sh`

I guess you entered `invoke.sh` into the Terminal. Try to write `./invoke.sh`, or double click `invoke.sh` to fix it.



> I got this error when I create the conda env within the `environments-and-requirements` directory.
> 
> After copying the .yml out to root, (I deleted previous bad env) and I reran the env creation from root and it worked.

This process is described here: https://invoke-ai.github.io/InvokeAI/installation/INSTALL_MANUAL/#conda-method

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/40327258/207254932-f52e91fc-269c-4aad-870a-8945871811c8.png">

**Comment by CJohnDesign** [comment]
@mauwii `./invoke.sh` worked for me - Thanks!
