### ISSUE TITLE
[bug]: Fresh install invoke.sh and update.sh links to ./source_installer broken, ./source_installer missing

### ISSUE THREAD

**Issue by tone-milazzo** [invoke-ai/InvokeAI#1931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

24GB

### What happened?

Previous install was working three days ago.
After running manually running "git pull", ./source_installer seems to have disappeared and links to scripts were broken.

Thinking I borked everything, I started over:
(still in the invokeai environment from before)
Moved all the existing folders to *.old and started a new install following these instructions: https://invoke-ai.github.io/InvokeAI/installation/INSTALL_SOURCE/#introduction
No errors during install.
./source_installer does not exist and links to invoke and update scripts point to files in missing folder

**Comment by maedu** [comment]
Got same issue on completely fresh install on OSX, installation went through without issues, but I do not have the ./source_installer folder as well.

**Comment by serginator** [comment]
Same here, you can bypass the issue running the following commandos:
```
conda activate invokeai
python scripts/invoke.py --web
```
