### ISSUE TITLE
[bug]:  I only see a shortcut of invokeai.sh file, and when I open the file it's giving the prompt "original file doesn't exist".

### ISSUE THREAD

**Issue by looper15** [invoke-ai/InvokeAI#1940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cuda

### What happened?

After completing the whole installation process, I only see a **shortcut of invokeai.sh**, and when I open the file it's giving the prompt "original file doesn't exist".

### Screenshots

<img width="489" alt="Screenshot 2022-12-12 at 3 25 15 AM" src="https://user-images.githubusercontent.com/106560207/206931283-83d586f0-28bf-473c-b778-70ce66894e12.png">
<img width="263" alt="Screenshot 2022-12-12 at 3 25 28 AM" src="https://user-images.githubusercontent.com/106560207/206931285-3e0567a8-5afc-4d9a-a613-5fa342cc7950.png">

**Comment by The-BreadCat** [comment]
same thing happed to me

**Comment by tomosuto** [comment]
I also had the same problem with v2.2.3, but I was able to install it without the issue with v2.2.4.
