### ISSUE TITLE
[bug]: cp949 codec error

### ISSUE THREAD

**Issue by cgndev** [invoke-ai/InvokeAI#1944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

when i install with install.bat appears cp949 error.

### Screenshots

PS C:\Users\kang\Downloads\InvokeAI-installer-2.2.4-windows\InvokeAI-Installer> .\install.bat
This script will install InvokeAI and its dependencies. Before you start,
        1개 파일이 복사되었습니다.
adding trusted host: 'https://download.pytorch.org' (from line 3 of requirements.txt)
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116
Collecting k-diffusion
  Using cached https://github.com/Birch-san/k-diffusion/archive/refs/heads/mps.zip (38 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pypatchmatch
  Using cached https://github.com/invoke-ai/PyPatchMatch/archive/refs/tags/0.1.4.zip (19 kB)
  Preparing metadata (setup.py) ... done
Collecting clip
  Using cached https://github.com/openai/CLIP/archive/eaa22acb90a5876642d0507623e859909230a52d.zip
  Preparing metadata (setup.py) ... done
Collecting clipseg
  Using cached https://github.com/invoke-ai/clipseg/archive/relaxed-python-requirement.zip (1.4 MB)
  Preparing metadata (setup.py) ... done
Collecting albumentations
  Using cached albumentations-1.3.0-py3-none-any.whl (123 kB)
Collecting dependency_injector==4.40.0
  Using cached dependency-injector-4.40.0.tar.gz (912 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\kang\AppData\Local\Temp\pip-install-s5l83_ea\dependency-injector_1f5595dca62448e69eff82ed9399ee9d\setup.py", line 15, in <module>
          description = readme_file.read()
                        ^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'cp949' codec can't decode byte 0xf0 in position 8665: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Installation of requirements failed. See above for errors and check https://invoke-ai.github.io/InvokeAI/installation/INSTALL_AUTOMATED/#troubleshooting for potential solutions.
The installer will exit now.
계속하려면 아무 키나 누르십시오 . . .

**Comment by polo13999** [comment]
I have some problem

**Comment by ebr** [comment]
Thanks for reporting the issue. We opened a PR to hopefully get a fix in the upstream library which causes `pip` to crash when installing it. But in the meantime. I would appreciate if any of those reporting this issue could please try a fix in an isolated environment, by following these steps in your CMD or Powershell:

```
python -m venv %temp%\tmp-venv
pip install https://github.com/ebr/python-dependency-injector/archive/refs/heads/fix-cp949-locale.zip
```

if this proceeds with no error, the upstream fix will likely work (and we might be able to merge a workaround in the meantime).

you should be able to delete the above temp directory with `del %temp%\tmp-venv` in your CMD or Powershell.

Thanks!

**Comment by HankResoplay** [comment]
> Thanks for reporting the issue. We opened a PR to hopefully get a fix in the upstream library which causes `pip` to crash when installing it. But in the meantime. I would appreciate if any of those reporting this issue could please try a fix in an isolated environment, by following these steps in your CMD or Powershell:
> 
> ```
> python -m venv %temp%\tmp-venv
> pip install https://github.com/ebr/python-dependency-injector/archive/refs/heads/fix-cp949-locale.zip
> ```
> 
> if this proceeds with no error, the upstream fix will likely work (and we might be able to merge a workaround in the meantime).
> 
> you should be able to delete the above temp directory with `del %temp%\tmp-venv` in your CMD or Powershell.
> 
> Thanks!

Same error but with cp1251, is it possible to fix?
