### ISSUE TITLE
[bug]: Linux installer 2.2.3 refers to non-existent directories.

### ISSUE THREAD

**Issue by CherepanovAV** [invoke-ai/InvokeAI#1947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What happened?

file install.sh contains in lines 124-127 a reference to the directory "source_installer", but such a directory does not exist.
This causes the invoke.sh and update.sh character links to fail

    ln -sf ./source_installer/invoke.sh.in ./invoke.sh
    ln -sf ./source_installer/update.sh.in ./update.sh
    chmod a+rx ./source_installer/invoke.sh.in
    chmod a+rx ./source_installer/update.sh.in

### Additional context

I use install.sh first time on ny pc
download link https://github.com/invoke-ai/InvokeAI/releases/download/v2.2.3/invokeAI-src-installer-2.2.3-linux.zip

**Comment by lstein** [comment]
The 2.2.3 installer will no longer work due to changes in the directory structure. Please either use the 2.2.4 installer to install 2.2.4 (recommended), or use one of the manual methods to install 2.2.3.

Sorry for the inconvenience!

**Comment by cfbauer** [comment]
For anyone else coming here from searching, you'll want to pay close attention to the "Everything now lives in the invokeai directory" section in the 2.2.4 release note here:

https://github.com/invoke-ai/InvokeAI/releases/tag/v2.2.4
