### ISSUE TITLE
[bug]: Missing key model

### ISSUE THREAD

**Issue by Nicolas-Formenton** [invoke-ai/InvokeAI#1955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What happened?

I've tried to install some .ckpt files to test, like stable-diffusion2.1-768, it all went correct using the ` invoke.py` script, but when I try to load those .ckpt files, it automatically restores to the `default stable-diffusion-1.5` and says `model [model] could not be loaded: Missing key model`. 

What is this? And what can I do about it? Really loving the invokeAI UI, but it seems to be confusing some times...

Appreciate any answer!

### Screenshots

![image](https://user-images.githubusercontent.com/81488809/207148859-f1dde99c-e2db-4fba-97b9-c3c4aff9b1f7.png)

**Comment by ebr** [comment]
We do not yet support SD2.x, but it is on the roadmap. Could you please try to remove it and see if the problem persists?

**Comment by Nicolas-Formenton** [comment]
It works properly with the 1.5 version, but even the other versions that are based on the 1.5 don't work. :/
