### ISSUE TITLE
[bug]: "TypeError: expected str, bytes or os.PathLike object, not NoneType" 

### ISSUE THREAD

**Issue by Malbathla** [invoke-ai/InvokeAI#1966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What happened?

After running update.bat, when I attempt to launch by running invoke.bat the above error is generated.  Thinking my install was broken, I downloaded the src install again and get the same error when running install.  This occurs after the 'Loading Python Libraries...' step

### Screenshots

![image](https://user-images.githubusercontent.com/84999459/207218951-75a14c95-1950-4182-943e-7cc85ea21737.png)

### Additional context

Occurs when in both user and administrator level CMD

**Comment by ebr** [comment]
likely introduced by https://github.com/invoke-ai/InvokeAI/pull/1948

**Comment by ebr** [comment]
Possibly fixed by https://github.com/invoke-ai/InvokeAI/pull/1954. @Malbathla could you please retry the source install *after pulling again from `main`*? (the installers aren't updated yet). Thank you!

**Comment by Malbathla** [comment]
@ebr 
I did a git pull and the launcher (invoke.bat) ran (some minor errors but it didnt crash the launch) and I could access the webUI .. however when I attempt to generate anything from text prompt - regardless of sampler, the cmd windows is getting a LOT of errors
eg
Traceback (most recent call last):
  File "e:\ai\invokeai\ldm\generate.py", line 492, in prompt2image
    results = generator.generate(
  File "e:\ai\invokeai\ldm\invoke\generator\base.py", line 98, in generate
    image = make_image(x_T)
  File "E:\AI\invokeAI\installer_files\env\envs\invokeai\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "e:\ai\invokeai\ldm\invoke\generator\txt2img.py", line 42, in make_image
    samples, _ = sampler.sample(
  File "E:\AI\invokeAI\installer_files\env\envs\invokeai\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "e:\ai\invokeai\ldm\models\diffusion\ksampler.py", line 226, in sample
    K.sampling.__dict__[f'sample_{self.schedule}'](
  File "E:\AI\invokeAI\installer_files\env\envs\invokeai
...
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
>> Could not generate image.

and of course no image generated. 

My Card: NVidia GeForce RTX 3060.

I also noted there was a 2.2.4 install which I have also tried, and while that ran fine it also throws the same error when attempting to generate images from text prompt

**Comment by ffdown** [comment]
Night update

![image](https://user-images.githubusercontent.com/95547131/207280176-411665ee-a2b8-45be-8066-87c8c059d31d.png)

**Comment by ffdown** [comment]
Update.bat now. All reinstalled, HUGIN token, model download, as first install... But all work.
