### ISSUE TITLE
[bug]: "[Winerror 267] The directory name is invalid while executing command Running setup.py install for jsonmerge"

### ISSUE THREAD

**Issue by AdvaitaSprite** [invoke-ai/InvokeAI#1967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

4gb

### What happened?

Well, this is the third version I've tried & failed to install. This time I'm getting the error message in the title:

> "ERROR: Error [WinError 267] The directory name is invalid while executing command Running setup.py install for jsonmerge
>   Running setup.py install for jsonmerge ... error
> error: legacy-install-failure
> 
> × Encountered error while trying to install package.
> ╰─> jsonmerge
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for output from the failure."

Here is a full transcript of the failed install:

> This script will install InvokeAI and its dependencies. Before you start,
> please make sure to do the following:
> 1. Install python 3.9 or higher.
> 2. Double-click on the file WinLongPathsEnabled.reg in order to
>    enable long path support on your system.
> 3. Some users have found they need to install the Visual C++ core
>    libraries or else they experience DLL loading problems at the end of the install.
>    Visual C++ is very likely already installed on your system, but if you get DLL
>    issues, please download and install the libraries by going to:
>    https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170
> 
> See https://invoke-ai.github.io/InvokeAI/installation/INSTALL_AUTOMATED/ for more details.
> 
> Press any key to continue . . .
> ***** Checking and Updating Python *****
> 
> Setting up requirements file for your system.
>         1 file(s) copied.
> Select the path to install InvokeAI's directory into [C:\Users\[USER]]: F:\Invoke2.4
> You have chosen to install InvokeAI into "F:\Invoke2.4\invokeai". OK? [Y/n]: y
> 
> *** Creating Runtime Directory F:\Invoke2.4\invokeai ***
> Successful.
> 
> ** Creating Virtual Environment for InvokeAI **
> Successful.
> 
> *** Installing InvokeAI Requirements ***
> Activating environment
> updating pip with "F:\Invoke2.4\invokeai\.venv\Scripts\python"
> Looking in links: c:\Users\[USER]\AppData\Local\Temp\tmpnx6cm3nh
> Requirement already satisfied: setuptools in f:\invoke2.4\invokeai\.venv\lib\site-packages (63.2.0)
> Requirement already satisfied: pip in f:\invoke2.4\invokeai\.venv\lib\site-packages (22.2.1)
>         1 file(s) copied.
> adding trusted host: 'https://download.pytorch.org' (from line 3 of requirements.txt)
> Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116
> Collecting k-diffusion
>   Downloading https://github.com/Birch-san/k-diffusion/archive/refs/heads/mps.zip (38 kB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Installing backend dependencies ... done
>   Preparing metadata (pyproject.toml) ... done
> Collecting pypatchmatch
>   Downloading https://github.com/invoke-ai/PyPatchMatch/archive/refs/tags/0.1.4.zip (19 kB)
>   Preparing metadata (setup.py) ... done
> Collecting clip
>   Downloading https://github.com/openai/CLIP/archive/eaa22acb90a5876642d0507623e859909230a52d.zip (4.3 MB)
>      ---------------------------------------- 4.3/4.3 MB 39.2 MB/s eta 0:00:00
>   Preparing metadata (setup.py) ... done
> Collecting clipseg
>   Downloading https://github.com/invoke-ai/clipseg/archive/relaxed-python-requirement.zip (1.4 MB)
>      ---------------------------------------- 1.4/1.4 MB 44.3 MB/s eta 0:00:00
>   Preparing metadata (setup.py) ... done
> Collecting albumentations
>   Downloading albumentations-1.3.0-py3-none-any.whl (123 kB)
>      ---------------------------------------- 123.5/123.5 kB 2.4 MB/s eta 0:00:00
> Collecting dependency_injector==4.40.0
>   Downloading dependency_injector-4.40.0-cp310-cp310-win_amd64.whl (538 kB)
>      ---------------------------------------- 538.6/538.6 kB 6.8 MB/s eta 0:00:00
> Collecting diffusers==0.10.*
>   Downloading diffusers-0.10.2-py3-none-any.whl (503 kB)
>      ---------------------------------------- 503.1/503.1 kB 10.5 MB/s eta 0:00:00
> Collecting einops
>   Downloading einops-0.6.0-py3-none-any.whl (41 kB)
>      ---------------------------------------- 41.6/41.6 kB ? eta 0:00:00
> Collecting eventlet
>   Downloading eventlet-0.33.2-py2.py3-none-any.whl (226 kB)
>      ---------------------------------------- 226.8/226.8 kB ? eta 0:00:00
> Collecting facexlib
>   Using cached facexlib-0.2.5-py3-none-any.whl (59 kB)
> Collecting flask==2.1.3
>   Downloading Flask-2.1.3-py3-none-any.whl (95 kB)
>      ---------------------------------------- 95.6/95.6 kB ? eta 0:00:00
> Collecting flask_cors==3.0.10
>   Downloading Flask_Cors-3.0.10-py2.py3-none-any.whl (14 kB)
> Collecting flask_socketio==5.3.0
>   Downloading Flask_SocketIO-5.3.0-py3-none-any.whl (17 kB)
> Collecting flaskwebgui==1.0.3
>   Downloading flaskwebgui-1.0.3-py3-none-any.whl (6.7 kB)
> Collecting getpass_asterisk
>   Downloading getpass_asterisk-1.0.1-py3-none-any.whl (6.8 kB)
> Collecting gfpgan==1.3.8
>   Using cached gfpgan-1.3.8-py3-none-any.whl (52 kB)
> Collecting huggingface-hub
>   Downloading huggingface_hub-0.11.1-py3-none-any.whl (182 kB)
>      ---------------------------------------- 182.4/182.4 kB ? eta 0:00:00
> Collecting imageio
>   Using cached imageio-2.22.4-py3-none-any.whl (3.4 MB)
> Collecting imageio-ffmpeg
>   Using cached imageio_ffmpeg-0.4.7-py3-none-win_amd64.whl (22.6 MB)
> Collecting kornia
>   Downloading kornia-0.6.8-py2.py3-none-any.whl (551 kB)
>      ---------------------------------------- 551.1/551.1 kB 11.5 MB/s eta 0:00:00
> Collecting numpy
>   Using cached numpy-1.23.5-cp310-cp310-win_amd64.whl (14.6 MB)
> Collecting omegaconf
>   Downloading omegaconf-2.3.0-py3-none-any.whl (79 kB)
>      ---------------------------------------- 79.5/79.5 kB ? eta 0:00:00
> Collecting opencv-python
>   Using cached opencv_python-4.6.0.66-cp36-abi3-win_amd64.whl (35.6 MB)
> Collecting picklescan
>   Downloading picklescan-0.0.6-py3-none-any.whl (10 kB)
> Collecting pillow
>   Using cached Pillow-9.3.0-cp310-cp310-win_amd64.whl (2.5 MB)
> Requirement already satisfied: pip>=22 in f:\invoke2.4\invokeai\.venv\lib\site-packages (from -r environments-and-requirements/requirements-base.txt (line 23)) (22.2.1)
> Collecting pudb
>   Downloading pudb-2014.1-py2.py3-none-any.whl (49 kB)
>      ---------------------------------------- 49.1/49.1 kB 2.6 MB/s eta 0:00:00
> Collecting pyreadline3
>   Downloading pyreadline3-3.4.1-py3-none-any.whl (95 kB)
>      ---------------------------------------- 95.2/95.2 kB ? eta 0:00:00
> Collecting pytorch-lightning==1.7.7
>   Downloading pytorch_lightning-1.7.7-py3-none-any.whl (708 kB)
>      ---------------------------------------- 708.1/708.1 kB 43.6 MB/s eta 0:00:00
> Collecting realesrgan
>   Using cached realesrgan-0.3.0-py3-none-any.whl (26 kB)
> Collecting requests==2.25.1
>   Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
> Collecting scikit-image>=0.19
>   Using cached scikit_image-0.19.3-cp310-cp310-win_amd64.whl (12.0 MB)
> Collecting send2trash
>   Downloading Send2Trash-1.8.0-py3-none-any.whl (18 kB)
> Collecting streamlit
>   Downloading streamlit-1.15.2-py2.py3-none-any.whl (9.2 MB)
>      ---------------------------------------- 9.2/9.2 MB 49.1 MB/s eta 0:00:00
> Collecting taming-transformers-rom1504
>   Downloading taming_transformers_rom1504-0.0.6-py3-none-any.whl (51 kB)
>      ---------------------------------------- 51.5/51.5 kB ? eta 0:00:00
> Collecting test-tube>=0.7.5
>   Downloading test_tube-0.7.5.tar.gz (21 kB)
>   Preparing metadata (setup.py) ... done
> Collecting torch-fidelity
>   Downloading torch_fidelity-0.3.0-py3-none-any.whl (37 kB)
> Collecting torchmetrics
>   Downloading torchmetrics-0.11.0-py3-none-any.whl (512 kB)
>      ---------------------------------------- 512.4/512.4 kB 31.4 MB/s eta 0:00:00
> Collecting transformers==4.25.*
>   Downloading transformers-4.25.1-py3-none-any.whl (5.8 MB)
>      ---------------------------------------- 5.8/5.8 MB 53.0 MB/s eta 0:00:00
> Collecting torch==1.12.1
>   Downloading https://download.pytorch.org/whl/cu116/torch-1.12.1%2Bcu116-cp310-cp310-win_amd64.whl (2388.4 MB)
>      ---------------------------------------- 2.4/2.4 GB 496.3 kB/s eta 0:00:00
> Collecting torchvision==0.13.1
>   Downloading https://download.pytorch.org/whl/cu116/torchvision-0.13.1%2Bcu116-cp310-cp310-win_amd64.whl (2.6 MB)
>      ---------------------------------------- 2.6/2.6 MB 40.7 MB/s eta 0:00:00
> Collecting six<=1.16.0,>=1.7.0
>   Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
> Collecting filelock
>   Downloading filelock-3.8.2-py3-none-any.whl (10 kB)
> Collecting regex!=2019.12.17
>   Using cached regex-2022.10.31-cp310-cp310-win_amd64.whl (267 kB)
> Collecting importlib-metadata
>   Downloading importlib_metadata-5.1.0-py3-none-any.whl (21 kB)
> Collecting itsdangerous>=2.0
>   Downloading itsdangerous-2.1.2-py3-none-any.whl (15 kB)
> Collecting Werkzeug>=2.0
>   Using cached Werkzeug-2.2.2-py3-none-any.whl (232 kB)
> Collecting click>=8.0
>   Using cached click-8.1.3-py3-none-any.whl (96 kB)
> Collecting Jinja2>=3.0
>   Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
> Collecting python-socketio>=5.0.2
>   Downloading python_socketio-5.7.2-py3-none-any.whl (56 kB)
>      ---------------------------------------- 56.7/56.7 kB 2.9 MB/s eta 0:00:00
> Collecting psutil==5.9.4
>   Using cached psutil-5.9.4-cp36-abi3-win_amd64.whl (252 kB)
> Collecting lmdb
>   Downloading lmdb-1.4.0-cp310-cp310-win_amd64.whl (100 kB)
>      ---------------------------------------- 100.1/100.1 kB ? eta 0:00:00
> Collecting scipy
>   Using cached scipy-1.9.3-cp310-cp310-win_amd64.whl (40.1 MB)
> Collecting pyyaml
>   Using cached PyYAML-6.0-cp310-cp310-win_amd64.whl (151 kB)
> Collecting yapf
>   Using cached yapf-0.32.0-py2.py3-none-any.whl (190 kB)
> Collecting tqdm
>   Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
> Collecting tb-nightly
>   Downloading tb_nightly-2.12.0a20221212-py3-none-any.whl (5.7 MB)
>      ---------------------------------------- 5.7/5.7 MB 51.5 MB/s eta 0:00:00
> Collecting basicsr>=1.4.2
>   Using cached basicsr-1.4.2.tar.gz (172 kB)
>   Preparing metadata (setup.py) ... done
> Collecting tensorboard>=2.9.1
>   Using cached tensorboard-2.11.0-py3-none-any.whl (6.0 MB)
> Collecting pyDeprecate>=0.3.1
>   Using cached pyDeprecate-0.3.2-py3-none-any.whl (10 kB)
> Collecting fsspec[http]!=2021.06.0,>=2021.05.0
>   Using cached fsspec-2022.11.0-py3-none-any.whl (139 kB)
> Collecting typing-extensions>=4.0.0
>   Using cached typing_extensions-4.4.0-py3-none-any.whl (26 kB)
> Collecting packaging>=17.0
>   Downloading packaging-22.0-py3-none-any.whl (42 kB)
>      ---------------------------------------- 42.6/42.6 kB 1.0 MB/s eta 0:00:00
> Collecting chardet<5,>=3.0.2
>   Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
> Collecting certifi>=2017.4.17
>   Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)
>      ---------------------------------------- 155.3/155.3 kB ? eta 0:00:00
> Collecting urllib3<1.27,>=1.21.1
>   Downloading urllib3-1.26.13-py2.py3-none-any.whl (140 kB)
>      ---------------------------------------- 140.6/140.6 kB 8.7 MB/s eta 0:00:00
> Collecting idna<3,>=2.5
>   Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
> Collecting tokenizers!=0.11.3,<0.14,>=0.11.1
>   Using cached tokenizers-0.13.2-cp310-cp310-win_amd64.whl (3.3 MB)
> Collecting qudida>=0.0.4
>   Downloading qudida-0.0.4-py3-none-any.whl (3.5 kB)
> Collecting opencv-python-headless>=4.1.1
>   Downloading opencv_python_headless-4.6.0.66-cp36-abi3-win_amd64.whl (35.5 MB)
>      ---------------------------------------- 35.5/35.5 MB 24.2 MB/s eta 0:00:00
> Collecting greenlet>=0.3
>   Downloading greenlet-2.0.1-cp310-cp310-win_amd64.whl (190 kB)
>      ---------------------------------------- 190.9/190.9 kB ? eta 0:00:00
> Collecting dnspython>=1.15.0
>   Downloading dnspython-2.2.1-py3-none-any.whl (269 kB)
>      ---------------------------------------- 269.1/269.1 kB 16.2 MB/s eta 0:00:00
> Collecting filterpy
>   Using cached filterpy-1.4.5.zip (177 kB)
>   Preparing metadata (setup.py) ... done
> Collecting numba
>   Using cached numba-0.56.4-cp310-cp310-win_amd64.whl (2.5 MB)
> Collecting antlr4-python3-runtime==4.9.*
>   Using cached antlr4_python3_runtime-4.9.3-py3-none-any.whl
> Collecting urwid>=1.1.1
>   Downloading urwid-2.1.2.tar.gz (634 kB)
>      ---------------------------------------- 634.6/634.6 kB 39.0 MB/s eta 0:00:00
>   Preparing metadata (setup.py) ... done
> Collecting pygments>=1.0
>   Using cached Pygments-2.13.0-py3-none-any.whl (1.1 MB)
> Collecting networkx>=2.2
>   Using cached networkx-2.8.8-py3-none-any.whl (2.0 MB)
> Collecting PyWavelets>=1.1.1
>   Using cached PyWavelets-1.4.1-cp310-cp310-win_amd64.whl (4.2 MB)
> Collecting tifffile>=2019.7.26
>   Using cached tifffile-2022.10.10-py3-none-any.whl (210 kB)
> Collecting python-dateutil
>   Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
> Collecting pyarrow>=4.0
>   Downloading pyarrow-10.0.1-cp310-cp310-win_amd64.whl (20.2 MB)
>      ---------------------------------------- 20.2/20.2 MB 31.2 MB/s eta 0:00:00
> Collecting toml
>   Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
> Collecting cachetools>=4.0
>   Using cached cachetools-5.2.0-py3-none-any.whl (9.3 kB)
> Collecting pandas>=0.21.0
>   Downloading pandas-1.5.2-cp310-cp310-win_amd64.whl (10.4 MB)
>      ---------------------------------------- 10.4/10.4 MB 38.6 MB/s eta 0:00:00
> Collecting pympler>=0.9
>   Downloading Pympler-1.0.1-py3-none-any.whl (164 kB)
>      ---------------------------------------- 164.8/164.8 kB 9.7 MB/s eta 0:00:00
> Collecting rich>=10.11.0
>   Using cached rich-12.6.0-py3-none-any.whl (237 kB)
> Collecting tzlocal>=1.1
>   Downloading tzlocal-4.2-py3-none-any.whl (19 kB)
> Collecting altair>=3.2.0
>   Downloading altair-4.2.0-py3-none-any.whl (812 kB)
>      ---------------------------------------- 812.8/812.8 kB 50.2 MB/s eta 0:00:00
> Collecting pydeck>=0.1.dev5
>   Downloading pydeck-0.8.0-py2.py3-none-any.whl (4.7 MB)
>      ---------------------------------------- 4.7/4.7 MB 49.9 MB/s eta 0:00:00
> Collecting validators>=0.2
>   Downloading validators-0.18.2-py3-none-any.whl (19 kB)
> Collecting semver
>   Downloading semver-2.13.0-py2.py3-none-any.whl (12 kB)
> Collecting blinker>=1.0.0
>   Downloading blinker-1.5-py2.py3-none-any.whl (12 kB)
> Collecting protobuf<4,>=3.12
>   Using cached protobuf-3.20.3-cp310-cp310-win_amd64.whl (904 kB)
> Collecting gitpython!=3.1.19
>   Downloading GitPython-3.1.29-py3-none-any.whl (182 kB)
>      ---------------------------------------- 182.5/182.5 kB 10.8 MB/s eta 0:00:00
> Collecting watchdog
>   Downloading watchdog-2.2.0-py3-none-win_amd64.whl (78 kB)
>      ---------------------------------------- 78.7/78.7 kB 4.6 MB/s eta 0:00:00
> Collecting tornado>=5.0
>   Downloading tornado-6.2-cp37-abi3-win_amd64.whl (425 kB)
>      ---------------------------------------- 425.3/425.3 kB 25.9 MB/s eta 0:00:00
> Collecting future
>   Using cached future-0.18.2.tar.gz (829 kB)
>   Preparing metadata (setup.py) ... done
> Collecting torchdiffeq
>   Using cached torchdiffeq-0.2.3-py3-none-any.whl (31 kB)
> Collecting clean-fid
>   Downloading clean_fid-0.1.34-py3-none-any.whl (26 kB)
> Collecting accelerate
>   Downloading accelerate-0.15.0-py3-none-any.whl (191 kB)
>      ---------------------------------------- 191.5/191.5 kB 12.1 MB/s eta 0:00:00
> Collecting wandb
>   Downloading wandb-0.13.6-py2.py3-none-any.whl (1.9 MB)
>      ---------------------------------------- 1.9/1.9 MB 58.9 MB/s eta 0:00:00
> Collecting resize-right
>   Using cached resize_right-0.0.2-py3-none-any.whl (8.9 kB)
> Collecting torchsde
>   Using cached torchsde-0.2.5-py3-none-any.whl (59 kB)
> Collecting jsonmerge
>   Downloading jsonmerge-1.9.0.tar.gz (32 kB)
>   Preparing metadata (setup.py) ... done
> Collecting ftfy
>   Using cached ftfy-6.1.1-py3-none-any.whl (53 kB)
> Collecting matplotlib
>   Using cached matplotlib-3.6.2-cp310-cp310-win_amd64.whl (7.2 MB)
> Collecting toolz
>   Downloading toolz-0.12.0-py3-none-any.whl (55 kB)
>      ---------------------------------------- 55.8/55.8 kB 2.8 MB/s eta 0:00:00
> Collecting entrypoints
>   Downloading entrypoints-0.4-py3-none-any.whl (5.3 kB)
> Collecting jsonschema>=3.0
>   Downloading jsonschema-4.17.3-py3-none-any.whl (90 kB)
>      ---------------------------------------- 90.4/90.4 kB ? eta 0:00:00
> Collecting addict
>   Using cached addict-2.4.0-py3-none-any.whl (3.8 kB)
> Collecting colorama
>   Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
> Collecting aiohttp!=4.0.0a0,!=4.0.0a1
>   Using cached aiohttp-3.8.3-cp310-cp310-win_amd64.whl (319 kB)
> Collecting gitdb<5,>=4.0.1
>   Downloading gitdb-4.0.10-py3-none-any.whl (62 kB)
>      ---------------------------------------- 62.7/62.7 kB 3.3 MB/s eta 0:00:00
> Collecting zipp>=0.5
>   Downloading zipp-3.11.0-py3-none-any.whl (6.6 kB)
> Collecting MarkupSafe>=2.0
>   Using cached MarkupSafe-2.1.1-cp310-cp310-win_amd64.whl (17 kB)
> Collecting pytz>=2020.1
>   Using cached pytz-2022.6-py2.py3-none-any.whl (498 kB)
> Collecting python-engineio>=4.3.0
>   Downloading python_engineio-4.3.4-py3-none-any.whl (52 kB)
>      ---------------------------------------- 52.9/52.9 kB 2.7 MB/s eta 0:00:00
> Collecting bidict>=0.21.0
>   Downloading bidict-0.22.0-py3-none-any.whl (36 kB)
> Collecting scikit-learn>=0.19.1
>   Downloading scikit_learn-1.2.0-cp310-cp310-win_amd64.whl (8.2 MB)
>      ---------------------------------------- 8.2/8.2 MB 52.8 MB/s eta 0:00:00
> Collecting commonmark<0.10.0,>=0.9.0
>   Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
> Collecting grpcio>=1.24.3
>   Downloading grpcio-1.51.1-cp310-cp310-win_amd64.whl (3.7 MB)
>      ---------------------------------------- 3.7/3.7 MB 47.7 MB/s eta 0:00:00
> Requirement already satisfied: setuptools>=41.0.0 in f:\invoke2.4\invokeai\.venv\lib\site-packages (from tensorboard>=2.9.1->pytorch-lightning==1.7.7->-r environments-and-requirements/requirements-base.txt (line 26)) (63.2.0)
> Collecting google-auth-oauthlib<0.5,>=0.4.1
>   Using cached google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
> Collecting tensorboard-data-server<0.7.0,>=0.6.0
>   Using cached tensorboard_data_server-0.6.1-py3-none-any.whl (2.4 kB)
> Collecting absl-py>=0.4
>   Using cached absl_py-1.3.0-py3-none-any.whl (124 kB)
> Collecting google-auth<3,>=1.6.3
>   Downloading google_auth-2.15.0-py2.py3-none-any.whl (177 kB)
>      ---------------------------------------- 177.0/177.0 kB 11.1 MB/s eta 0:00:00
> Collecting wheel>=0.26
>   Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
> Collecting tensorboard-plugin-wit>=1.6.0
>   Using cached tensorboard_plugin_wit-1.8.1-py3-none-any.whl (781 kB)
> Collecting markdown>=2.6.8
>   Using cached Markdown-3.4.1-py3-none-any.whl (93 kB)
> Collecting tzdata
>   Downloading tzdata-2022.7-py2.py3-none-any.whl (340 kB)
>      ---------------------------------------- 340.1/340.1 kB 20.6 MB/s eta 0:00:00
> Collecting pytz-deprecation-shim
>   Downloading pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
> Collecting decorator>=3.4.0
>   Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
> Collecting wcwidth>=0.2.5
>   Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
> Collecting contourpy>=1.0.1
>   Using cached contourpy-1.0.6-cp310-cp310-win_amd64.whl (163 kB)
> Collecting fonttools>=4.22.0
>   Using cached fonttools-4.38.0-py3-none-any.whl (965 kB)
> Collecting pyparsing>=2.2.1
>   Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
> Collecting cycler>=0.10
>   Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
> Collecting kiwisolver>=1.0.1
>   Using cached kiwisolver-1.4.4-cp310-cp310-win_amd64.whl (55 kB)
> Collecting llvmlite<0.40,>=0.39.0dev0
>   Using cached llvmlite-0.39.1-cp310-cp310-win_amd64.whl (23.2 MB)
> Collecting trampoline>=0.1.2
>   Using cached trampoline-0.1.2-py3-none-any.whl (5.2 kB)
> Collecting boltons>=20.2.1
>   Using cached boltons-21.0.0-py2.py3-none-any.whl (193 kB)
> Collecting setproctitle
>   Downloading setproctitle-1.3.2-cp310-cp310-win_amd64.whl (11 kB)
> Collecting promise<3,>=2.0
>   Downloading promise-2.3.tar.gz (19 kB)
>   Preparing metadata (setup.py) ... done
> Collecting sentry-sdk>=1.0.0
>   Downloading sentry_sdk-1.11.1-py2.py3-none-any.whl (168 kB)
>      ---------------------------------------- 169.0/169.0 kB 10.6 MB/s eta 0:00:00
> Collecting docker-pycreds>=0.4.0
>   Downloading docker_pycreds-0.4.0-py2.py3-none-any.whl (9.0 kB)
> Collecting pathtools
>   Downloading pathtools-0.1.2.tar.gz (11 kB)
>   Preparing metadata (setup.py) ... done
> Collecting shortuuid>=0.5.0
>   Downloading shortuuid-1.0.11-py3-none-any.whl (10 kB)
> Collecting attrs>=17.3.0
>   Using cached attrs-22.1.0-py2.py3-none-any.whl (58 kB)
> Collecting yarl<2.0,>=1.0
>   Downloading yarl-1.8.2-cp310-cp310-win_amd64.whl (56 kB)
>      ---------------------------------------- 56.1/56.1 kB ? eta 0:00:00
> Collecting multidict<7.0,>=4.5
>   Downloading multidict-6.0.3-cp310-cp310-win_amd64.whl (28 kB)
> Collecting aiosignal>=1.1.2
>   Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
> Collecting charset-normalizer<3.0,>=2.0
>   Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
> Collecting frozenlist>=1.1.1
>   Using cached frozenlist-1.3.3-cp310-cp310-win_amd64.whl (33 kB)
> Collecting async-timeout<5.0,>=4.0.0a3
>   Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
> Collecting smmap<6,>=3.0.1
>   Using cached smmap-5.0.0-py3-none-any.whl (24 kB)
> Collecting pyasn1-modules>=0.2.1
>   Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
> Collecting rsa<5,>=3.1.4
>   Using cached rsa-4.9-py3-none-any.whl (34 kB)
> Collecting requests-oauthlib>=0.7.0
>   Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
> Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
>   Using cached pyrsistent-0.19.2-cp310-cp310-win_amd64.whl (62 kB)
> Collecting joblib>=1.1.1
>   Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
> Collecting threadpoolctl>=2.0.0
>   Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
> Collecting pyasn1<0.5.0,>=0.4.6
>   Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
> Collecting oauthlib>=3.0.0
>   Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)
> Using legacy 'setup.py install' for test-tube, since package 'wheel' is not installed.
> Using legacy 'setup.py install' for pypatchmatch, since package 'wheel' is not installed.
> Using legacy 'setup.py install' for clip, since package 'wheel' is not installed.
> Using legacy 'setup.py install' for clipseg, since package 'wheel' is not installed.
> Using legacy 'setup.py install' for basicsr, since package 'wheel' is not installed.
> Using legacy 'setup.py install' for urwid, since package 'wheel' is not installed.
> Using legacy 'setup.py install' for filterpy, since package 'wheel' is not installed.
> Using legacy 'setup.py install' for future, since package 'wheel' is not installed.
> Using legacy 'setup.py install' for jsonmerge, since package 'wheel' is not installed.
> Using legacy 'setup.py install' for promise, since package 'wheel' is not installed.
> Using legacy 'setup.py install' for pathtools, since package 'wheel' is not installed.
> Building wheels for collected packages: k-diffusion
>   Building wheel for k-diffusion (pyproject.toml) ... done
>   Created wheel for k-diffusion: filename=k_diffusion-0.0.1-py3-none-any.whl size=25377 sha256=230b6ee262a3a3fa1f9426754fa4c660f3e55d3c287bdae8082cefbefc257265
>   Stored in directory: C:\Users\[USER]\AppData\Local\Temp\pip-ephem-wheel-cache-wd6w6gnf\wheels\2d\9d\9f\0872a4fcc1467aeec09a515aef1fcaeec35cd82262c2a04cb4
> Successfully built k-diffusion
> Installing collected packages: yapf, wcwidth, urwid, trampoline, tokenizers, tensorboard-plugin-wit, send2trash, resize-right, pytz, pyreadline3, pyasn1, pathtools, lmdb, getpass_asterisk, commonmark, boltons, antlr4-python3-runtime, addict, zipp, wheel, watchdog, urllib3, tzdata, typing-extensions, tornado, toolz, toml, threadpoolctl, tensorboard-data-server, smmap, six, shortuuid, setproctitle, semver, rsa, regex, pyyaml, python-engineio, pyrsistent, pyparsing, pympler, pygments, pyDeprecate, pyasn1-modules, psutil, protobuf, pillow, picklescan, packaging, oauthlib, numpy, networkx, multidict, MarkupSafe, markdown, llvmlite, kiwisolver, joblib, itsdangerous, imageio-ffmpeg, idna, grpcio, greenlet, future, ftfy, fsspec, frozenlist, fonttools, filelock, entrypoints, einops, dnspython, decorator, cycler, colorama, charset-normalizer, chardet, certifi, cachetools, blinker, bidict, attrs, async-timeout, absl-py, yarl, Werkzeug, validators, tqdm, torch, tifffile, sentry-sdk, scipy, rich, requests, PyWavelets, pytz-deprecation-shim, python-socketio, python-dateutil, pypatchmatch, pyarrow, pudb, promise, opencv-python-headless, opencv-python, omegaconf, numba, jsonschema, Jinja2, importlib-metadata, imageio, google-auth, gitdb, flaskwebgui, eventlet, docker-pycreds, dependency_injector, contourpy, click, aiosignal, tzlocal, torchvision, torchsde, torchmetrics, torchdiffeq, scikit-learn, scikit-image, requests-oauthlib, pydeck, pandas, matplotlib, kornia, jsonmerge, huggingface-hub, gitpython, flask, aiohttp, accelerate, wandb, transformers, torch-fidelity, qudida, google-auth-oauthlib, flask_socketio, flask_cors, filterpy, diffusers, clip, clean-fid, altair, tensorboard, tb-nightly, streamlit, k-diffusion, facexlib, clipseg, albumentations, test-tube, pytorch-lightning, basicsr, taming-transformers-rom1504, gfpgan, realesrgan
>   Running setup.py install for urwid ... done
>   Running setup.py install for pathtools ... done
>   Running setup.py install for future ... done
>   Running setup.py install for pypatchmatch ... done
>   Running setup.py install for promise ... done
>   ERROR: Error [WinError 267] The directory name is invalid while executing command Running setup.py install for jsonmerge
>   Running setup.py install for jsonmerge ... error
> error: legacy-install-failure
> 
> × Encountered error while trying to install package.
> ╰─> jsonmerge
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for output from the failure.
> 
> [notice] A new release of pip available: 22.2.1 -> 22.3.1
> [notice] To update, run: python.exe -m pip install --upgrade pip
> Requirements installation failed. See above for errors and check https://invoke-ai.github.io/InvokeAI/installation/INSTALL_AUTOMATED/#troubleshooting for potential solutions.
> The installer will exit now.
> Press any key to continue . . .

After that I tried to upgrade pip, as it recommended, but it gave me back this message saying I was already up to the most recent version which theautoresponse was recommending (so I don't know if the problem there is that the version of pip in the conda env it created isn't fully updated? Or whether that's relevant to the problem at hand, but here's the response when I tried to update it anyway):

"Requirement already satisfied: pip in c:\users\[USER]\appdata\local\programs\python\python310\lib\site-packages (22.3.1)"

So, any clue what's going on or how I can fix it, or it can be fixed on the back end, or whatever is necessary? When I searched nothing even came up related to jsonmerge, so I have no idea if this is a completely unique issue or what, but I feel like I followed the very simple install instructions quite precisely so I don't know why every version has failed so far.

Thanks for any assistance.

### Additional context

The other 2 versions I've tried to install are 2.2.2 and 2.2.3, and I'm on Windows 10 Home. cmdr2's UI and AUTOMATIC1111's webUI have worked fine for me, as have online outpainting sites & stuff-- although, I have had problems of various kinds with trying to install StableDreamfusion & some other Python based programs (if they problem has to do with Conda that wouldn't surprise me because I'm pretty new to juggling all these version management programs & terminals/consoles of various kinds). Not sure if any of that helps. Thanks again.

**Comment by lstein** [comment]
This is going to sound lame, but you might want to try to run `install.bat` again. Sometimes these library installs fail for mysterious reasons and work the second time you try them.

**Comment by lucasuniverse** [comment]
O diretório de instalação não pode ter espaço, e se o anti-vírus estiver ativado, vai bloquear o download dos arquivos!

**Comment by eranpm** [comment]
Have you found a workaround @AdvaitaSprite ?
Got exactly the same problem and I've already tried to run the installation again as suggested here only to see the same error message again.

**Comment by ramijames** [comment]
I've also encountered this issue. Simply gets stuck here during the install.

![image](https://user-images.githubusercontent.com/814302/213879809-7b7ea8ed-ebb1-46b6-a5ad-1b42f2ce5b84.png)

**Comment by hortom** [comment]
> I've also encountered this issue. Simply gets stuck here during the install.
> 
> ![image](https://user-images.githubusercontent.com/814302/213879809-7b7ea8ed-ebb1-46b6-a5ad-1b42f2ce5b84.png)

Same for me with auto installer 2.2.5 on Windows 10, Python 3.10.9, Pip 23.0.

**Comment by mauwii** [comment]
You could try to use the PyPI Verison (but make sure you activate a .venv beforehand):

`pip install --upgrade --use-pep517 InvokeAI`

**Comment by mauwii** [comment]
could this be closed?
