### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by ktsi** [invoke-ai/InvokeAI#1976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What happened?

Hi all. I installed on a base MacBook Air M1 |(8 GB of total RAM) via the automated script. All went smooth and I can start invokeAI. However it runs extremely slow (>10 mins for text2img) because somehow it fails to recognize the GPU.

I get the following message:

_/Users/myuser/invokeai/.venv/lib/python3.10/site-packages/ldm/modules/embedding_manager.py:166: UserWarning: The operator 'aten::nonzero' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at  /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)   placeholder_rows, placeholder_cols = torch.where(_

I am using python 3.10  (installed via universal Mac installer). DiffusionBee app is working fine on the same machine.

Any ideas? 

Thanks very much in advance and I am sorry if this has been already asked and I somehow missed it.

### Additional context

Do you want to generate images using the
1. command-line
2. browser-based UI
3. open the developer console
Please enter 1, 2, or 3: 2

Starting the InvokeAI browser-based UI..
>> patchmatch.patch_match: WARNING - patchmatch failed to load or compile.
>> patchmatch.patch_match: WARNING - Refer to https://github.com/invoke-ai/InvokeAI/blob/main/docs/installation/INSTALL_PATCHMATCH.md for installation instructions.
>> Patchmatch not loaded (nonfatal)
* Initializing, be patient...
>> Initialization file /Users/myuser/invokeai/invokeai.init found. Loading...
>> InvokeAI runtime directory is "/Users/myuser/invokeai"
## NOT FOUND: GFPGAN model not found at /Users/myuser/invokeai/models/gfpgan/GFPGANv1.4.pth
>> GFPGAN Disabled
## NOT FOUND: CodeFormer model not found at /Users/myuser/invokeai/models/codeformer/codeformer.pth
>> CodeFormer Disabled
>> ESRGAN Initialized
**>> Using device_type mps**
>> Current VRAM usage:  0.00G
>> Scanning Model: stable-diffusion-1.5
>> Model Scanned. OK!!
>> Loading stable-diffusion-1.5 from /Users/myuser/invokeai/models/ldm/stable-diffusion-v1/v1-5-pruned-emaonly.ckpt
   | LatentDiffusion: Running in eps-prediction mode
   | DiffusionWrapper has 859.52 M params.
   | Making attention of type 'vanilla' with 512 in_channels
   | Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
   | Making attention of type 'vanilla' with 512 in_channels
   | Using more accurate float32 precision
   | Loading VAE weights from: /Users/myuser/invokeai/models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
>> Model loaded in 84.44s
>> Current embedding manager terms: *
>> Setting Sampler to k_lms

* --web was specified, starting web server...
>> Initialization file /Users/myuser/invokeai/invokeai.init found. Loading...
>> Started Invoke AI Web Server!
>> Default host address now 127.0.0.1 (localhost). Use --host 0.0.0.0 to bind any address.
>> Point your browser at http://127.0.0.1:9090

**Comment by ktsi** [comment]
I have seen closed issue #728. That was 3 months ago, so I would assume PyTorch has fixed it.

**Comment by dondre** [comment]
I'm on 2.2.4 using Mac Air M2 and are experiencing this issue. It takes about 88 seconds per image.

**Comment by Gitterman69** [comment]
suddenly have this after reinstalling today again.... goddamnit! haha i had 3s/it before now its 26s/it again.... any idea how i can "rollback" the pytorch?
