### ISSUE TITLE
[bug]: HMR is not working for frontend dev

### ISSUE THREAD

**Issue by kasbah** [invoke-ai/InvokeAI#1982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cpu

### What happened?

I'm trying to set up a dev environment for the frontend. I've got it all working with `yarn dev`, it compiles, loads the web ui on `127.0.0.1:5173` and generating images :sunglasses:  

However when I want to use hot-module-reloading and make a valid change to a `.tsx` file, after first loading the page, it's not reloading and endlessly repeating this error in the browser console:

```
ReferenceError: can't access lexical declaration 'App' before initialization
```

I tried in Firefox and Chrome, with profiles loaded that don't have any extensions installed. Is HMR supposed to be working?

Edit: Have tried editing with Neovim and VS Code with the same result.

**Comment by hipsterusername** [comment]
Putting @psychedelicious and/or @blessedcoolant on the case to share his hot tips and tricks on the frontend dev environment, and looking forward to seeing your contributions 🖖

**Comment by psychedelicious** [comment]
Every once in a while I get this, especially when I try to do something related to poly filling nodejs modules for the browser. I think it's a vite thing. 

I wonder if upgrading to vite 4 will fix it? Our vite config is pretty straightforward so I expect upgrading will be simple.

**Comment by blessedcoolant** [comment]
> Every once in a while I get this, especially when I try to do something related to poly filling nodejs modules for the browser. I think it's a vite thing.
> 
> I wonder if upgrading to vite 4 will fix it? Our vite config is pretty straightforward so I expect upgrading will be simple.

I get it a lot really. And not just on this project but any Vite project I have. Been looking for a solution to fix it but haven't found any that actually work so far.

**Comment by blessedcoolant** [comment]
> Thanks for your input everyone. I tried updating to Vite 4 but it didn't fix it. (Didn't seem to introduce any new issues though so likely a painless update)
> 
> > The issue has been long reported and still there.
> 
> Could you link the issue @blessedcoolant? Closest thing I found is [vitejs/vite#4587](https://github.com/vitejs/vite/issues/4587) but that's been closed. I had a go at finding circular dependencies with eslint-plugin-import but ran into a lot of other issues there.
> 
> When I updated Vite I noticed I could actually read what it's looping on and it was outputing a lot of:
> 
> ```
> 13:20:51 [vite] hmr update /src/app/App.tsx (x2)
> 13:20:51 [vite] hmr update /src/features/system/components/SettingsModal/SettingsModal.tsx
> 13:20:51 [vite] hmr update /src/features/system/components/SettingsModal/SettingsModal.tsx
> 13:20:51 [vite] hmr update /src/features/system/components/SiteHeader.tsx                
> 13:20:51 [vite] hmr update /src/features/system/components/SiteHeader.tsx (x2)  
> ```
> 
> So I removed a `SettingsModal` import and it started working! When I added it back HMR is still working. 🤷‍♀️ Would still be good to try and fix this since it seems like it will come back.

I actually noticed this issue with SettingsModal too. I'll have a look in there and see if something is breaking HMR.

**Comment by kasbah** [comment]
By the way, while it's not happening in the initial folder anymore I can still reproduce this issue by doing a fresh clone.
