### ISSUE TITLE
[bug]: Update Linux installer documentation to include necessary dependencies

### ISSUE THREAD

**Issue by ebr** [invoke-ai/InvokeAI#1987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What happened?

A user [reports](https://discord.com/channels/1020123559063990373/1052095896659169360/1052453516427407462) in Discord:

![image](https://user-images.githubusercontent.com/2433541/207522262-36fcb007-cad4-4335-9ee3-d5d5197676b3.png)

`python3-opencv` requires the following libraries to be present:

```
apt update && apt install -y libglib2.0-0 libgl1-mesa-glx
```

we should either add this to the install script (but that will require interactivity and `sudo` from the user), or the docs

first investigate if other solutions also exist that don't require these libraries. maybe `python-opencv-headless` can be used, unless `python3-opencv` is a transitive dependency.

**Comment by SammCheese** [comment]
Theoretically possible, but not feasible with the amount of package managers out there.

You'd have to have a list of package managers like `pacman`, `dnf`, `dpkg`, `portage` and check which one is present. 
Depending on that use the one present, search for the needed packages (they are not always named the same for every Distro) and assemble a command to install them.

Thats a lot of room for error and mistakes, i feel like it would be better to just list the dependencies and let the user install them manually.

**Comment by ebr** [comment]
@SammCheese yes, agreed. Besides, throwing unexpected OS package installation at the user is kind of icky. We'll take the documentation route.
