### ISSUE TITLE
[diffusers]: model management (configure and pre-load)

### ISSUE THREAD

**Issue by keturn** [invoke-ai/InvokeAI#1997]
> _write config first and then download everything in config,_  
> _or download first and write config for downloads?_

The diffusers API is happy to load model weights on demand from the huggingface.co model hub. But we'd still like the `configure` script to download model weights ahead of time because (1) the web UI has no "download in progress" indicator, and (2) we want `invoke.py` to be able work offline even on its first run.

In its current state, #1583 has two model download functions: 
- one that takes some keys defined in INITIAL_MODELS, does some downloads, and then adds the successfully downloaded ones to the local models.yaml.
- another for diffusers, that looks for models in the local models.yaml and loads them to make sure they've been downloaded.

Having _both_ those approaches is a sign of internal confusion and makes it hard to figure out how to specify which things to load.

Since the diffusers API _can_ download models on-demand, I think we should assume it _will_ be used this way at least part of the time, so whatever pre-loading method the configure script uses should be compatible with that.

The most straightforward thing would be to do what `download_diffusers_in_config` does now: https://github.com/invoke-ai/InvokeAI/blob/23eb80b40421b2bb8f4b6d3dd30490d11c447b36/scripts/configure_invokeai.py#L428-L430

so there's never any difference in the download-cache-load code between the ModelCache and the configure script, but I'm not sure whether that offers the same set of functionality as `configure_invokeai`'s current download functions regarding progress indicators, behavior with interrupted downloads, etc.

There's still some uncertainty about what Invoke will do with ldm-flavored model files after our #1583 diffusers integration, but for new installations I think the configure process should get the diffusers flavored files.

There is a version of INITIAL_MODELS that's diffusers-friendly here: [`6e4dad6` (#1583)](https://github.com/invoke-ai/InvokeAI/pull/1583/commits/6e4dad60c866209001dda3dc55826e6b5a093991#diff-e06736b76e78174c1b5b63953266248b14e0e83820d6692ed03fcd6672ffc121)

(I didn't find a hosted version of the Trinart Characters models, so I left those out.)

**Comment by hipsterusername** [comment]
I'll also note, I think there is value in being able to boot the WebUI without a model. This would allow users to skip configure, download the support models, and then boot the WebUI to scan a folder and upload.

As far as ldm vs diffusers models, well... you know my opinion there.

**Comment by keturn** [comment]
done, configure script now gets diffusers-format models.
