### ISSUE TITLE
[bug]: "system cannot find specified file" after "installation successful"

### ISSUE THREAD

**Issue by krochlikmiov** [invoke-ai/InvokeAI#2006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

Followed the instructions, and stopped after downloading/installing the templates files. The next line says "The system cannot find the specified file" I'll attach a screenshot of the cmd window. First time installing, made sure to use the increased name .reg file.

### Screenshots

![image](https://user-images.githubusercontent.com/102648354/207743418-db9208a3-bdb1-4a2d-8dae-3b1042872233.png)

**Comment by Cemvegas** [comment]
same here

**Comment by krochlikmiov** [comment]
I did manage to solve it, the problem came from trying to input a file location at the start of the installation when it asks you to set a directory. 
Instead of adding a folder name, I just pressed enter and it installed into c:\\Users\[username]\invokeai.

As a side note, later on during the installation when it asked for file locations for configs or whatever it was (on windows 10), copying the file path, or drag and dropping the file onto the cmd window did not work. The solution to that problem was using a full path including the drive letter (C:\\Users\[username]\invokeai\etc.) AND replacing the \ with / for some reason. (C://Users/[username]/invokeai/etc.)

**Comment by caretaker0815** [comment]
same here

**Comment by justinraymondpark** [comment]
Thanks, using the default directory solved this for me.

**Comment by mateforfun** [comment]
Go to path you installed your invokeai int then in folder \invokeai\invokeai_2_3_0_standalone launch install_models.bat
For path reasons it works.
