### ISSUE TITLE
[bug]: Missing requirements.txt when trying to reinstall 2.24 from scratch

### ISSUE THREAD

**Issue by mcbexx** [invoke-ai/InvokeAI#2010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

Tried to re-install 2.24 from scratch to a different directory (first install went without a hitch), removed the old directory completely and ran install.bat again.

Got a "system could not find specified path" error followed by 

**ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt',** 

(see attached screenshot for full install log up to that point)

Where is the requirements.txt expected to reside?
Is there a different way to remove an existing installation of InvokeAI other then removing the directory?

The path "c:\Users\mcbex\AppData\Local\Temp\tmp8g72t793" that is referenced in the *** Installing InvokeAI Requirements *** section does not appear to exist.

I rebooted as well between numerous tries to do a fresh reinstall 

Basic steps to reproduce on my end: Delete the old Invoke 2.24 file directory, reboot Windows, run install.bat again.

### Screenshots

![grafik](https://user-images.githubusercontent.com/56156474/207771436-53dd93d1-627a-4cb8-9ec7-293224d369c6.png)

**Comment by Barafu** [comment]
Did you redownload the folder? Try downloading again from [here](https://invoke-ai.github.io/InvokeAI/installation/INSTALL_AUTOMATED/#walk-through) I had re-tested it right now to see that it works.

**Comment by mcbexx** [comment]
Redownloaded InvokeAI-installer-2.2.4-windows.zip just now, (same size as the one I downloaded and used both times yesterday) and running the install.bat appears to be working. No idea why, but it just wouldn't yesterday.
