### ISSUE TITLE
[bug]: WebUI, in Text2Image mode, does not scale the picture display properly

### ISSUE THREAD

**Issue by Barafu** [invoke-ai/InvokeAI#2013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8 gb

### What happened?

When using browser's overall zoom, the view of the generated picture does not scale properly.  It does scale, but does not follow the available panel size. It leads to wasted screen space and hard to see image. I've provided a screenshot below, and marked the lost space as red. 

I think the image should scale to fill all the available height, with a gap about 2cm wide, no matter what zoom setting is set in browser. 

### Screenshots

![Untitled](https://user-images.githubusercontent.com/6612364/207793549-bdad92bf-2439-4831-a7df-06f47002e4fd.png)

### Additional context

I am using Brave browser, and I've set 125% zoom in Windows settings too.

**Comment by hipsterusername** [comment]
This is not a bug, but an intentional design decision.

In fact, it used to scale, but because it did, would often leave the image looking pixelated. 

As models increasingly produce larger images, the available space will end up being filled completely.
