### ISSUE TITLE
[bug]: Installation fails on Windows 10 regarding Python versions

### ISSUE THREAD

**Issue by Helge666** [invoke-ai/InvokeAI#2014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12

### What happened?

Collecting transformers==4.25.*
  Using cached transformers-4.25.1-py3-none-any.whl (5.8 MB)
ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement torch==1.12.1 (from versions: none)
ERROR: No matching distribution found for torch==1.12.1

[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip
Requirements installation failed. See above for errors and check https://invoke-ai.github.io/InvokeAI/installation/INSTALL_AUTOMATED/#troubleshooting for potential solutions.
The installer will exit now.

### Additional context

automatic1111 is installed on this system, and I don't want to break it by manually trying to install packages. The provided error message (see above) is less than instructive w/regards to correcting the problem.

I did try: python.exe -m pip install --upgrade pip which results in:

Requirement already satisfied: pip in c:\users\helge\appdata\local\programs\python\python311\lib\site-packages (22.3.1)

### Contact Details

helge@helge.de

**Comment by Barafu** [comment]
The log is pretty clear in stating that the python you have is below 3.7, while only Python 3.9+ is supported by InvokeAI. 

Lets find out if you really have the Python so old. Open the terminal the same way you used for installation and run `python -V`

**Comment by wywywywy** [comment]
It looks like you may have Python 3.11. You need Python 3.10 on Windows to install torch.

You can have multiple versions of Python installed, and you can also install modules in a separate venv to isolate it from Automatic1111 (which should also have its own venv).

**Comment by wywywywy** [comment]
Or maybe just use the binary installer

**Comment by patrickmac110** [comment]
I'm running into the same error, should I uninstall Python 3.11 and install 3.10? or how do I get it to detect 3.10? or use the binary installer?

**Comment by FrederikSchack** [comment]
> The log is pretty clear in stating that the python you have is below 3.7, while only Python 3.9+ is supported by InvokeAI.
> 
> Lets find out if you really have the Python so old. Open the terminal the same way you used for installation and run `python -V`

Important, it´s not working with Python 3.11, as I understand it because it doesn´t have pythorch.

**Comment by patrickmac110** [comment]
uninstalling python11 fixed the issue for me
