### ISSUE TITLE
[bug]: model could not be loaded: Error(s) in loading state_dict for LatentInpaintDiffusion: size mismatch for model.diffusion_model.input_blocks.0.0.weight: copying a param with shape torch.Size([320, 4, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 9, 3, 3]).

### ISSUE THREAD

**Issue by Raz0rStorm** [invoke-ai/InvokeAI#2015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6gb

### What happened?

I wanted to add my dreambooth model manually to invokeai, I wrote as follows:
momoko:
  description: momoko finetune
  weights: models\mo_mk_a_13000.ckpt
  config: configs\stable-diffusion\v1-inpainting-inference.yaml
  width: 512
  height: 512
  vae: models\kl-f8-anime2.ckpt
  default: true
When I launched, it gave me error as such:
** model momoko could not be loaded: Error(s) in loading state_dict for LatentInpaintDiffusion:
        size mismatch for model.diffusion_model.input_blocks.0.0.weight: copying a param with shape torch.Size([320, 4, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 9, 3, 3]).
Traceback (most recent call last):
  File "D:\Games\InvAI\invokeai\.venv\lib\site-packages\ldm\invoke\model_cache.py", line 80, in get_model
    requested_model, width, height, hash = self._load_model(model_name)
  File "D:\Games\InvAI\invokeai\.venv\lib\site-packages\ldm\invoke\model_cache.py", line 234, in _load_model
    model.load_state_dict(sd, strict=False)
  File "D:\Games\InvAI\invokeai\.venv\lib\site-packages\torch\nn\modules\module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LatentInpaintDiffusion:
        size mismatch for model.diffusion_model.input_blocks.0.0.weight: copying a param with shape torch.Size([320, 4, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 9, 3, 3]).

### Screenshots

![image](https://user-images.githubusercontent.com/95212158/207845112-1ca8a316-76fc-40b3-9842-b5b3af4ca39c.png)

### Contact Details

discordname:Kingb4ker

**Comment by mickr777** [comment]
Replace v1-inpainting-inference.yaml with v1-inference.yaml and see if that fixes it
