### ISSUE TITLE
[bug]: have two video cards, always defaults to amd card

### ISSUE THREAD

**Issue by MordesMortes** [invoke-ai/InvokeAI#2022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

6GB

### What happened?

I commented out lines 168-171 and line 174 in the install script to get invoke AI to install and not try to use my AMD video card as it is a 590 and AMD has decided to drop ROCm support for it

![image](https://user-images.githubusercontent.com/59325226/207903486-718e5a7d-7ba7-448a-bebe-ee368871ed26.png)

during the install it fails at line 201
![image](https://user-images.githubusercontent.com/59325226/207904048-716bd7fb-1535-4581-a12f-e4c9f988b8c3.png)

with "hipErrorNoBinaryForGpu: Unable to find code object for all current devices!"

I'm just not finding where else I need to comment out so that I can use my nvidia card... I'm presenting this as a bug as I know having two video cards is an edge case but having the ability to select which video card to run on would be nice

### Contact Details

mordes@gmail.com

**Comment by mickr777** [comment]
I had this trouble with a nvidia card but amd cpu had an apu,  i think they can fix it by changing the lsmod command to only using amd is a nvidia card isnt present.

Eg like i did with lshw in my script for unraid 
if [[ $(lshw -C display | grep -i vendor) = *AMD* ]] && [[ $(lshw -C display | grep -i vendor) != *NVIDIA* ]]  ; then

**Comment by MordesMortes** [comment]
I got past the configure_invokeai.py issue as it was renamed Configure_invokeAI.py and that case issue was making it not show up for the script

**Comment by MordesMortes** [comment]
found the issue I ran 

inxi -G and got

Graphics:
  Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
    driver: amdgpu v: kernel
  Device-2: NVIDIA TU106 [GeForce RTX 2060 Rev. A] driver: vfio
    v: N/A
  Device-3: AMD Cezanne [Radeon Vega Series / Radeon Mobile Series]
    driver: vfio-pci v: N/A
  Device-4: Linux Foundation USB Webcam gadget type: USB
    driver: snd-usb-audio
  Display: x11 server: X.Org v: 21.1.6 driver: X: loaded: amdgpu,nvidia
    unloaded: modesetting,nouveau dri: radeonsi gpu: amdgpu
    resolution: 1920x1080~60Hz
  API: OpenGL v: 4.6 Mesa 22.3.1 renderer: AMD Radeon RX 590 Series
  
  went to /etc/mkinitcpio.conf and added nvidia in before vfio in the MODULES section rebuilt initramfs ( sudo mkinitcpio -P for me it might be update-initramfs -u for you ) rebooted and ran inxi -G again

 Device-2: NVIDIA TU106 [GeForce RTX 2060 Rev. A] driver: nvidia
    v: 525.60.11

ran invokeAI and it picked up my video card

hopefully this helps someone else get it working
