### ISSUE TITLE
[bug]: invokeai cant make high prompt. vram output error

### ISSUE THREAD

**Issue by Hsm2021** [invoke-ai/InvokeAI#2040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What happened?

**I don't know how to set vram value in app. Anyway, when I write a big prompt, the program gets an error.**

### Additional context

>> image generation requested: {'prompt': 'a vibrant professional studio portrait photography of a young, pale, goth, attractive, friendly, casual, delightful, intricate, gorgeous, female, piercing green eyes, wears a gold ankh necklace, femme fatale, nouveau, curated collection, annie leibovitz, nikon, award winning, breathtaking, groundbreaking, superb, outstanding, lensculture portrait awards, photoshopped, dramatic lighting, 8k', 'iterations': 1, 'steps': 15, 'cfg_scale': 7.5, 'threshold': 0, 'perlin': 0, 'height': 512, 'width': 512, 'sampler_name': 'k_lms', 'seed': 4128105304, 'progress_images': False, 'progress_latents': True, 'save_intermediates': 5, 'generation_mode': 'txt2img', 'init_mask': '...', 'seamless': False, 'hires_fix': False, 'variation_amount': 0}
ESRGAN parameters: False
Facetool parameters: {'type': 'gfpgan', 'strength': 1}
{'prompt': 'a vibrant professional studio portrait photography of a young, pale, goth, attractive, friendly, casual, delightful, intricate, gorgeous, female, piercing green eyes, wears a gold ankh necklace, femme fatale, nouveau, curated collection, annie leibovitz, nikon, award winning, breathtaking, groundbreaking, superb, outstanding, lensculture portrait awards, photoshopped, dramatic lighting, 8k', 'iterations': 1, 'steps': 15, 'cfg_scale': 7.5, 'threshold': 0, 'perlin': 0, 'height': 512, 'width': 512, 'sampler_name': 'k_lms', 'seed': 4128105304, 'progress_images': False, 'progress_latents': True, 'save_intermediates': 5, 'generation_mode': 'txt2img', 'init_mask': '', 'seamless': False, 'hires_fix': False, 'variation_amount': 0}
Generating:   0%|                                                                                | 0/1 [00:00<?, ?it/s]>> Ksampler using karras noise schedule (steps < 30)
>> Sampling with k_lms starting at step 0 of 15 (15 new sampling steps)

**and then display this :**

>>RuntimeError: CUDA error: device-side assert triggered
>>CUDA kernel errors might be asynchronously reported at some >>other API call,so the stacktrace below might be incorrect.
>>For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

>> Could not generate image.
>> Usage stats:
>>   0 image(s) generated in 0.96s
>>   Max VRAM used for this generation: 3.29G. Current VRAM utilization: 2.17G
>>   Max VRAM used since script start:  3.31G

**Comment by hipsterusername** [comment]
Fixed in #1999
