### ISSUE TITLE
[enhancement]: Add a hotkey for Zoom to the Canvas

### ISSUE THREAD

**Issue by Barafu** [invoke-ai/InvokeAI#2048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I tried to use canvas with the graphics tablet. Overall, it is rather convenient when used with keyboard hotkeys. However, it is not possible to zoom in and out. Currently, it seems, the only zoom binding is a mouse wheel, so I have to put down the pen and reach for the mouse every time I need to zoom. 

Please add a zoom hotkey. The most convenient implementation would be this: when the hotkey is pressed and held, the drawing of the pencil up or down (which registers as mouse drag) should zoom out (up) or in (down), centered on the point where the drag starts. This would allow both zoom and quick navigation over the large canvas, in 2 strokes. Releasing the hotkey stops zooming and reverts back to the previous tool.

If a hotkey that is held down is not possible, then zoom can be implemented as a tool on the same level as "move" and "brush".

**Comment by whosawhatsis** [comment]
Pinch-to-zoom would be a welcome addition too, both on tablets and on other devices that support it, like apple's trackpads. I actually sometimes wish I could turn off scroll-to-zoom entirely, and use pinch-to-zoom and scroll-to-pan instead on my trackpad. On a tablet without a keyboard, it almost has to work that way to be usable.

**Comment by Barafu** [comment]
Still needed.

**Comment by Barafu** [comment]
Still a good idea for 3.0.0.

**Comment by psychedelicious** [comment]
The canvas now supports a number of zoom hotkeys:
- Ctrl/Cmd + 1/2/3/4 to zoom to 100%,200%,400%, 800%
- Ctrl/Cmd + 0 to fit zoom
