### ISSUE TITLE
[bug]: Upscale Image doesn't work for me

### ISSUE THREAD

**Issue by if3lc** [invoke-ai/InvokeAI#2054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### VRAM

16

### What happened?

When I try to use "Upscale Image" I get an error. I'm getting a similar error in the "Restore Faces" section.

### Screenshots
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/830333/208256834-5c08a103-617e-49d5-bd9a-5f226b8b0edc.png">

Full response,
https://app.warp.dev/block/Gq5REEkhGLNU8J9VFeAKfX

**Comment by if3lc** [comment]
During this time I have uninstalled and reinstalled 4 times but I keep getting the same error.

**Comment by if3lc** [comment]
Unfortunately I keep getting the same error in version 2.2.5.

**Comment by kriptolix** [comment]
Ok, there are two relevant problems in the log, first the patchmatch installation, but for now it still doesn't work on Mac. Second, the script is not finding the corresponding files for GFPGAN and CodeFormer.

Please, check if the following files exist and can be read normally:

/Users/if3lc/invokeai/models/gfpgan/GFPGANv1.4.pth
/Users/if3lc/invokeai/models/codeformer/codeformer.pth

**Comment by if3lc** [comment]
I didn't have the files at the address you mentioned, after downloading the files and putting them in the relevant folders, the problem was fixed in the "Upscale Image" section, thank you 🙏

I still have the problem in the "Restore Face" section, I get exactly the output below.
https://app.warp.dev/block/0ckE8GKRS8FSfYqMqQVorV

**Comment by kriptolix** [comment]
Okay, this is an SSL certificate error, when invoke tries to download detection_Resnet50_Final.pth.

There is a way to solve this by changing an execution file, but I couldn't find the issue that explains which file. For now, you can try to install the openssl lib. If you use brew:

`$ brew install openssl`

**Comment by if3lc** [comment]
Thank you very much for your help :) I installed openssl but nothing changed, final result,
https://app.warp.dev/block/jE5ocNvBovYIdPdSQheyq0

**Comment by rdfrost** [comment]
Duplicate of #1810?

**Comment by kriptolix** [comment]
> Duplicate of #1810?

Yes, this is the issue that I was looking for.

**Comment by if3lc** [comment]
<img width="965" alt="image" src="https://user-images.githubusercontent.com/830333/212065718-31efd4eb-1d6e-4bc5-a50f-c64577d5c1ff.png">

I changed it this way but unfortunately it didn't work for me, returning the result,
https://app.warp.dev/block/prLRWO47oeS63Wzu9UqneW

**Comment by beber666** [comment]
Yes same issue there on Mac Mini M1, Upscaling doens't work (as well as Restore Face)
bertrand@Mac-Mini-M1 ~ % /Users/bertrand/invokeai/invoke.sh 
Do you want to generate images using the
1. command-line
2. browser-based UI
3. open the developer console
Please enter 1, 2, or 3: 2

Starting the InvokeAI browser-based UI..
* Initializing, be patient...
>> Initialization file /Users/bertrand/invokeai/invokeai.init found. Loading...
>> InvokeAI 2.2.5
>> InvokeAI runtime directory is "/Users/bertrand/invokeai"
## NOT FOUND: GFPGAN model not found at /Users/bertrand/invokeai/models/gfpgan/GFPGANv1.4.pth
>> GFPGAN Disabled
## NOT FOUND: CodeFormer model not found at /Users/bertrand/invokeai/models/codeformer/codeformer.pth
>> CodeFormer Disabled
>> ESRGAN Initialized
>> Using device_type mps
>> Current VRAM usage:  0.00G
>> Scanning Model: stable-diffusion-1.5
>> Model Scanned. OK!!
>> Loading stable-diffusion-1.5 from /Users/bertrand/invokeai/models/ldm/stable-diffusion-v1/v1-5-pruned-emaonly.ckpt
   | Forcing garbage collection prior to loading new model
   | LatentDiffusion: Running in eps-prediction mode
   | DiffusionWrapper has 859.52 M params.
   | Making attention of type 'vanilla' with 512 in_channels
   | Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
   | Making attention of type 'vanilla' with 512 in_channels
   | Using more accurate float32 precision
   | Loading VAE weights from: /Users/bertrand/invokeai/models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
>> Model loaded in 9.07s
>> Current embedding manager terms: *
>> Setting Sampler to k_lms

* --web was specified, starting web server...
* Initializing, be patient...
>> Initialization file /Users/bertrand/invokeai/invokeai.init found. Loading...
>> Started Invoke AI Web Server!
>> Default host address now 127.0.0.1 (localhost). Use --host 0.0.0.0 to bind any address.
>> Point your browser at http://10.0.0.39:9090
>> System config requested
>> patchmatch.patch_match: ERROR - patchmatch failed to load or compile (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>).
>> patchmatch.patch_match: INFO - Refer to https://github.com/invoke-ai/InvokeAI/blob/main/docs/installation/INSTALL_PATCHMATCH.md for installation instructions.
>> Patchmatch not loaded (nonfatal)
>> System config requested
>> Postprocessing requested for "outputs/000133.e5ecb56b.1598438217.png": {'type': 'esrgan', 'upscale': [4, 0.75]}
>> Error loading Real-ESRGAN:
Traceback (most recent call last):
  File "/Users/bertrand/invokeai/.venv/lib/python3.10/site-packages/ldm/invoke/restoration/realesrgan.py", line 50, in process
    upsampler = self.load_esrgan_bg_upsampler()
  File "/Users/bertrand/invokeai/.venv/lib/python3.10/site-packages/ldm/invoke/restoration/realesrgan.py", line 32, in load_esrgan_bg_upsampler
    bg_upsampler = RealESRGANer(
  File "/Users/bertrand/invokeai/.venv/lib/python3.10/site-packages/realesrgan/utils.py", line 63, in __init__
    loadnet = torch.load(model_path, map_location=torch.device('cpu'))
  File "/Users/bertrand/invokeai/.venv/lib/python3.10/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/bertrand/invokeai/.venv/lib/python3.10/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/bertrand/invokeai/.venv/lib/python3.10/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/bertrand/invokeai/.venv/models/realesrgan/realesr-general-x4v3.pth'

>> Real-ESRGAN Upscaling seed:1598438217 : scale:4x


Traceback (most recent call last):
  File "/Users/bertrand/invokeai/.venv/lib/python3.10/site-packages/backend/invoke_ai_web_server.py", line 682, in handle_run_postprocessing
    image = self.esrgan.process(
  File "/Users/bertrand/invokeai/.venv/lib/python3.10/site-packages/ldm/invoke/restoration/realesrgan.py", line 71, in process
    output, _ = upsampler.enhance(
UnboundLocalError: local variable 'upsampler' referenced before assignment
