### ISSUE TITLE
[bug]: Can´t run invokeai after install because of missing module ´ldm´

### ISSUE THREAD

**Issue by FrederikSchack** [invoke-ai/InvokeAI#2055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What happened?

After running invoke.bat I get this message:
** Model Installation Successful **
You're all set! You may now launch InvokeAI using one of these two commands:
Web version:
    python scripts/invoke.py --web  (connect to http://localhost:9090)
Command-line version:
   python scripts/invoke.py

If you installed manually, remember to activate the 'invokeai'
environment before running invoke.py. If you installed using the
automated installation script, execute "invoke.sh" (Linux/Mac) or
"invoke.bat" (Windows) to start InvokeAI.

Have fun!

------------------------------------------
http://localhost:9090 is not working
------------------------------------------
Then I run this:

(base) C:\invokeai>python .venv\Scripts\invoke.py --web

------------------------------------------
And get this error:
Traceback (most recent call last):
  File "C:\invokeai\.venv\Scripts\invoke.py", line 3, in <module>
    import ldm.invoke.CLI
ModuleNotFoundError: No module named 'ldm'

### Additional context

I´m not a developer, I do have basic understanding of Python.

I suspect that I should install stable diffusion seperately? If so, how should I make sure that the references are ok between invokeAI and stable diffusion?

**Comment by sutt** [comment]
I got this one I installed the conda env (from the yaml file) from within the `environments` directory. 

As the docs state somewhere, you need to copy the env.yml file that you want to the root of the repo and run the conda env create command at root.

When I did this, this error went away.

**Comment by FrederikSchack** [comment]
> I got this one I installed the conda env (from the yaml file) from within the `environments` directory.
> 
> As the docs state somewhere, you need to copy the env.yml file that you want to the root of the repo and run the conda env create command at root of this repo.
> 
> When I did this, this error went away.

Thanks! I just ran the installation another time and it solved the problem :)
