### ISSUE TITLE
[bug]: Emergency model reconfigure shouldn't kick in after an unrelated exception

### ISSUE THREAD

**Issue by ebr** [invoke-ai/InvokeAI#2059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

4GB

### What happened?

Found in one of the Discord threads. The user experienced a crash due to CUDA OOM (low-VRAM GPU). But because the crash happened on model load, the program kicks them into the emergency-model-reconfigure flow, even though it's an unrelated issue.

![image](https://user-images.githubusercontent.com/2433541/208264852-bba08801-3fc9-4542-b2e2-47562c692995.png)

**Comment by lstein** [comment]
I agree. This has already been fixed in the main branch and will appear in 2.2.5

**Comment by ebr** [comment]
@lstein thank you! just for my understanding - is [this](https://github.com/invoke-ai/InvokeAI/blob/main/ldm/invoke/CLI.py#L51-L56) the fix, or something else?

**Comment by ebr** [comment]
ah, no, i think it's this PR https://github.com/invoke-ai/InvokeAI/pull/2066/. Great!
