### ISSUE TITLE
Inpainting won't work[bug]: Says 0 images loaded? 

### ISSUE THREAD

**Issue by brunsonator3** [invoke-ai/InvokeAI#2074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

Whenever I try to use inpainting it doesn't work in the webui and I get disconnected. I am using model Anything-V3.0.

Though when I open the console I notice this:

2022-12-19T04:31:09-0600:

Image generation requested: {"prompt":"make part of outfit.","iterations":1,"steps":50,"cfg_scale":7.5,"threshold":0,"perlin":0,"height":768,"width":512,"sampler_name":"k_lms","seed":3992101658,"progress_images":false,"inpaint_replace":1,"init_img":"outputs/000456.a76cae78.2399474594.postprocessed.png","strength":0.85,"fit":false,"init_mask":"iVBORw0KGgoAAAANSUhE...","bounding_box":{"x":0,"y":0,"width":2048,"height":3072},"variation_amount":0,"level":4,"type":"gfpgan"}

2022-12-19T04:31:12-0600:

Disconnected from server

2022-12-19T04:31:13-0600:

Loaded 0 images

2022-12-19T04:31:13-0600:

Loaded 0 images

**Comment by VictorZakharov** [comment]
I don't get any errors, but inpainting doesn't work with 2.2.4.
Somebody needs to record a video and share on YT.
Maybe the workflow is too complex.
