### ISSUE TITLE
[Feature Request]: Image to Description Model

### ISSUE THREAD

**Issue by snapo** [invoke-ai/InvokeAI#2084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Through Github

### What should this feature add?

Is there are feature planned to automatically create descriptions of a image? (like the reverse of what users currently to from text to image)
Sometimes i have an original image and would like to get the same style as the image i already have and a description of the image to see what the AI thinks.
Would something like this be possible?
(I am not talking about style transfer image-to-image).... i would really be interested in image-to-text description that is as accurate as possible.

**Comment by n00mkrad** [comment]
CLIP Interrogator  
https://colab.research.google.com/github/pharmapsychotic/clip-interrogator/blob/main/clip_interrogator.ipynb

BLIP  
https://huggingface.co/spaces/Salesforce/BLIP

**Comment by snapo** [comment]
@n00mkrad thank you very very very much, i didnt know that such a model already exists... BLIP "image captioning" is exactly what i was looking for :-)

**Comment by ParisNeo** [comment]
Shouldn't this be integrated as a feature to  invokeAI?

**Comment by Randomblock1** [comment]
Still would be really nice to have, the other webui already has this feature as an extension. This should absolutely be a feature

**Comment by RadioactiveDeveloper** [comment]
Adding CLIP interrogator or BLIP would be an excellent addition as a Tab or feature to have directly implemented into the web interface.
