### ISSUE TITLE
[bug]: invoke.bat run with option 2 is not loading web GUI

### ISSUE THREAD

**Issue by nettems** [invoke-ai/InvokeAI#2089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cpu

### What happened?

invoke.bat run with option 2 is not loading web GUI, it's re-configuring and pointing to run python scripts/invoke.py --web as below

** Model Installation Successful **
You're all set! You may now launch InvokeAI using one of these two commands:
Web version:
    python scripts/invoke.py --web  (connect to http://localhost:9090)
Command-line version:
   python scripts/invoke.py

If you installed manually, remember to activate the 'invokeai'
environment before running invoke.py. If you installed using the
automated installation script, execute "invoke.sh" (Linux/Mac) or
"invoke.bat" (Windows) to start InvokeAI.

Have fun!

I tried to regenerate init file (as mentioned in https://invoke-ai.github.io/InvokeAI/installation/010_INSTALL_AUTOMATED/#corrupted-configuration-file) but no luck

**Comment by rp4k** [comment]
when running  invoke.bat  add  --host 

c:\blah\invokeai\invokeai\invoke.bat --host 192.168.0.100  

fill in whatever your local ip is  then in your browser go to 
192.168.0.100:9090

i found that if i didn't set my local ip  it would give me the same error.   


in the invoke.bat file you could add the --host 192.168.0.100  
under the option 2 if you wanted.

**Comment by AtomicRahul** [comment]
Facing the same issue. Please help.


** Model Installation Successful **
You're all set! You may now launch InvokeAI using one of these two commands:
Web version:
    python scripts/invoke.py --web  (connect to http://localhost:9090)
Command-line version:
   python scripts/invoke.py

If you installed manually, remember to activate the 'invokeai'
environment before running invoke.py. If you installed using the
automated installation script, execute "invoke.sh" (Linux/Mac) or
"invoke.bat" (Windows) to start InvokeAI.

Have fun!

"Press any key to continue"
Press any key to continue . . .

When I press any key, command prompt gets closed and nothing happens.
I also write this command (python scripts/invoke.py --web) after activating the activate.bat file. Cmd opens for a blink and then nothing happens. 

Tried uninstalling and installing several times. Even installed the windows again but still no results.

Please help :)

**Comment by WillyamBradberry** [comment]
> Facing the same issue. Please help.
> 
> ** Model Installation Successful ** You're all set! You may now launch InvokeAI using one of these two commands: Web version: python scripts/invoke.py --web (connect to http://localhost:9090) Command-line version: python scripts/invoke.py
> 
> If you installed manually, remember to activate the 'invokeai' environment before running invoke.py. If you installed using the automated installation script, execute "invoke.sh" (Linux/Mac) or "invoke.bat" (Windows) to start InvokeAI.
> 
> Have fun!
> 
> "Press any key to continue" Press any key to continue . . .
> 
> When I press any key, command prompt gets closed and nothing happens. I also write this command (python scripts/invoke.py --web) after activating the activate.bat file. Cmd opens for a blink and then nothing happens.
> 
> Tried uninstalling and installing several times. Even installed the windows again but still no results.
> 
> Please help :)

Some issue, did you find any help?

**Comment by Kryptonic83** [comment]
I had this problem after a fresh install of 2.2.5 but then tried running update.bat, let it do it's thing, then I was able to run invoke.bat without it auto closing.
