### ISSUE TITLE
[bug]: Every install method I try (outside of conda) results in the same error from the install script

### ISSUE THREAD

**Issue by ocalhoun6** [invoke-ai/InvokeAI#2094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

8GB

### What happened?

Ubuntu 20.04
Python 3.10 installed

I've tried the manual install, the automatic install, docker install, etc ... and *every* time, I end up getting the same error:

`./install.sh` --> `Error: Command '['/home/o4/Desktop/Files/Shell/AI/SD2/invokeai/.venv/bin/python3.10', '-m', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.`

`python3.10 -mvenv invokeai` --> `Error: Command '['/home/o/Files/Shell/AI/SD2/InvokeAI-main/installer/InvokeAI-Installer/invokeai/bin/python3.10', '-m', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.`

`/$ sudo python3.10 -mvenv invokeai` --> `Error: Command '['/invokeai/bin/python3.10', '-m', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.`

Exactly the same error ends up coming up, no matter what install method I try. (The automated installer is probably just hitting the same error when it tries to do the same thing automatically.)

-------

I have it running on CPU only through conda, and that works fine ... if slowly.
And for now ... I'll probably stick with that, unless the solution to the above error ends up being very simple and easy.
Planning on doing a whole OS fresh install once Ubuntu releases an LTS with the 6.0+ kernel, complete with new GPU hardware. Will try again then.

### Contact Details

7485697@gmail.com

**Comment by vmajor** [comment]
Same here, on Windows 10.

`Error: Command '['d:\\InvokeAI\\invokeai\\.venv\\Scripts\\python.exe', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.`

Install script is broken.

**Comment by vmajor** [comment]
Update. I got the installer to run by restarting the workstation and agreeing to a default directory as a target for installation.

**Comment by ocalhoun6** [comment]
> and agreeing to a default directory as a target for installation.

Hm... come to think of it, I *was* specifying a custom install location every time. I should try again sometime and let it choose the default ... even though its default location is *not* convenient for me, given the way I have my filesystems set up.

**Comment by mauwii** [comment]
I guess you where succesfull 🙈
