### ISSUE TITLE
[bug?]: CLI model import results in an error!

### ISSUE THREAD

**Issue by Cryptonyte67** [invoke-ai/InvokeAI#2098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12

### What happened?

Imported custom weights via the CLI import results in an error and defaults back to Stable Diffusion 1.5 Weight (model). 

### Screenshots

--web was specified, starting web server...
Initialization file D:\Stable Diffusion\Invoke Application\invokeai\invokeai.init found. Loading...
Started Invoke AI Web Server!
Default host address now 127.0.0.1 (localhost). Use --host 0.0.0.0 to bind any address.
Point your browser at http://127.0.0.1:9090/
System config requested
Model change requested: Stable_D
Current VRAM usage: 2.17G
Offloading stable-diffusion-1.5 to CPU
Scanning Model: Stable_D
Model Scanned. OK!!
Loading Stable_D from D:\Stable Diffusion\Invoke Application\invokeai\models\ldm\stable-diffusion-v1\v2-1_768-nonema-pruned.ckpt
** model Stable_D could not be loaded: LatentDiffusion.init() missing 1 required positional argument: 'personalization_config'
Traceback (most recent call last):
File "D:\Stable Diffusion\Invoke Application\invokeai.venv\lib\site-packages\ldm\invoke\model_cache.py", line 80, in get_model
requested_model, width, height, hash = self._load_model(model_name)
File "D:\Stable Diffusion\Invoke Application\invokeai.venv\lib\site-packages\ldm\invoke\model_cache.py", line 233, in _load_model
model = instantiate_from_config(omega_config.model)
File "D:\Stable Diffusion\Invoke Application\invokeai.venv\lib\site-packages\ldm\util.py", line 90, in instantiate_from_config
return get_obj_from_str(config['target'])(
TypeError: LatentDiffusion.init() missing 1 required positional argument: 'personalization_config'

** restoring stable-diffusion-1.5

Retrieving model stable-diffusion-1.5 from system RAM cache
Retrieving model stable-diffusion-1.5 from system RAM cache
Current embedding manager terms: *
Setting Sampler to k_lms

### Contact Details

cryptonyte67@gmail.com

**Comment by Barafu** [comment]
Can you provide the source where you get the weights file? Did you load other models? Maybe this model file contains errors

**Comment by wasyleque** [comment]
https://huggingface.co/stabilityai/stable-diffusion-2-1/blob/main/v2-1_768-nonema-pruned.ckpt

**Comment by Barafu** [comment]
Stable Diffusion 2 is not supported yet.
