### ISSUE TITLE
[enhancement]: Display image while generating next image

### ISSUE THREAD

**Issue by kasbah** [invoke-ai/InvokeAI#2101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I noticed while generating batches of images the web UI would show me the loading "intermediate" image rather than letting me take a look at the most recent fully generated image. I think in general it would be nice to keep looking at the latest fully generated image rather than watch the "intermediate" image being formed. It could be an option at the very least 

I went ahead and played around with implementing this but noticed when generating batches the server is completely blocked on generating the next image. It won't even respond to the http request to show the latest fully generated image. 

As far as I can tell the server first need to be made non-blocking. I would reach for either `multiprocessing` or `asyncio` to achieve that. Happy to hear any suggestions on this though.

**Comment by wbecher** [comment]
Hello @kasbah, have you checked the settings page? 

![image](https://user-images.githubusercontent.com/1504625/209134345-f65aa008-1f1d-4861-8544-5a478be15e8e.png)

I have disabled the option `Display In-Progress Images`, so the Web UI is always showing me the last image created now.

**Comment by kasbah** [comment]
Thanks, I hadn't seen that. That solves it for case when I am generating a single image. However there still seems to be a problem when generating a batch of images. Here I am generating a batch of 2 images:

![image](https://user-images.githubusercontent.com/206854/209146616-7906181f-8d7a-4d50-92a4-c734963d2f9b.png)

(Testing on a CPU, don't mind the low step count and blurry images.) 

When the first image is already on disk. It shows a blank image in the sidebar and doesn't switch to it. At this point I believe the server is not responding to the image request. 

![image](https://user-images.githubusercontent.com/206854/209146789-2ef17c61-6b5b-449b-aa46-87e59d494c86.png)

Only when both images are done can you see any of the new images:

![image](https://user-images.githubusercontent.com/206854/209147051-83fc1294-2198-4eac-a500-3fd7ede1e890.png)

**Comment by wbecher** [comment]
Well, that`s odd. For me, the new thumb image in the gallery only shows after the new image is generated. I do not see an empty square at any moment. Even when generating a batch of 10 images.

**Comment by kasbah** [comment]
Ah, it seems to have been because I was testing on my laptop CPU. I just tried it on a VPS with a GPU and it does indeed show the first image while the next one is processing. Thanks for your help!
