### ISSUE TITLE
[enhancement]: embedding selection UI

### ISSUE THREAD

**Issue by exeea** [invoke-ai/InvokeAI#2102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

playgroundai.com has an awesome select box for embeddings, would be great to have something similar also included in invokeAI, maybe with multi-selection.

![image](https://user-images.githubusercontent.com/48771891/209197684-7e371eaf-fa8e-4b6e-b1f1-0d8eb2f87d24.png)

**Comment by netsvetaev** [comment]
exactly what I imagine for styles and tags. Thank you for this reference!

**Comment by cchance27** [comment]
Another thing that should hopefully make it into the v3 branch being able to see a bit more from the very long lora lists would be nice even some form of square tooltip as your scrolling over the individual items
