### ISSUE TITLE
[bug]: Broken outpanting image

### ISSUE THREAD

**Issue by goodwin74** [invoke-ai/InvokeAI#2103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

4GB

### What happened?

Initially, everything worked, I used the "unified canvas" function where it is possible to expand the image with the drawing of the neural network (outpainting). Everything was fine at first, and then at one point an error occurred due to lack of VRAM memory. Now the neural network draws squares and something incomprehensible with a glitch. Restarting the terminal doesn't help :(

### Screenshots

![image](https://user-images.githubusercontent.com/15101984/209202183-3407d311-3f93-4748-a36e-4c651bd4b557.png)

**Comment by mickr777** [comment]
Double check your image to image strenght isnt below 0.70 that can cause issues like this in out painting

**Comment by goodwin74** [comment]
> Double check your image to image strength isnt below 0.70 that can cause issues like this in out painting

The reason was that the Bounding Box was 512x448. As soon as I made 512x512 everything started working. I think it's some kind of algorithm bug.
