### ISSUE TITLE
[bug]: *low priority* Docker install script issue

### ISSUE THREAD

**Issue by SloppyPuppy** [invoke-ai/InvokeAI#2105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

6

### What happened?

The install script kindly provided in the project and mentioned in the install guide uses the command "arch" to check the architecture which in my case doesn't work (archlinux), I am unsure if this is a package thats not shipped for only this distro or otherwise might be a common issue, but I've solved it replacing "arch" in ./docker-build/env.sh with "uname -m" which gives the same result in my experience and might be more compatible across the board.

**Comment by mauwii** [comment]
Thx for the info, I changed it ☺️
