### ISSUE TITLE
[bug]: reseting Fetching Hugging Face token 

### ISSUE THREAD

**Issue by nielswh** [invoke-ai/InvokeAI#2112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

32

### What happened?

I've moved to a different company and they require that I use their API token for hugging face. 

Where can I make the change on my computer to update the token?

**Comment by ebr** [comment]
HuggingFace caches the token in your home directory, under `~/.huggingface/token`. Deleting this file will reset the token. Also, you can use the `HUGGINGFACE_TOKEN` environment variable to switch tokens at any time, as needed.

**Comment by nielswh** [comment]
Thank you!

**Comment by JAKAMI99** [comment]
For everyone landing here while trying to get FLUX to install:
The token needs the "write"-permission!
