### ISSUE TITLE
[enhancement]: Clip Guidance Conditioning

### ISSUE THREAD

**Issue by sneccc** [invoke-ai/InvokeAI#2113]
Will you guys implement Clip Guidance feature like in dreamstudio?

**Comment by keturn** [comment]
DreamStudio and some other folks working on similar models have been pushing CLIP guidance pretty hard, so I expect we'll want the option.

There's an example we can look at here: https://github.com/huggingface/diffusers/blob/9be94d9c6659f7a0a804874f445291e3a84d61d4/examples/community/clip_guided_stable_diffusion.py#L113

It does look a **lot** more resource-hungry than the classifier-free guidance we've been using. Both in computation and memory.

**Comment by daniel5984** [comment]
> DreamStudio and some other folks working on similar models have been pushing CLIP guidance pretty hard, so I expect we'll want the option.
> 
> There's an example we can look at here: https://github.com/huggingface/diffusers/blob/9be94d9c6659f7a0a804874f445291e3a84d61d4/examples/community/clip_guided_stable_diffusion.py#L113
> 
> It does look a **lot** more resource-hungry than the classifier-free guidance we've been using. Both in computation and memory.

yeah it is resource hungy, but for people that rent gpus A6000,3090 etc it would be fine

**Comment by Euph0ria** [comment]
My RTX 3070 seems to hold up well enough as long as the resolutions aren't huge.  786^2 is the highest I can go.   Hope to see this feature as it can really make a difference in some creations, and it doesn't seem to have that much more overhead from what I can perceive.
