### ISSUE TITLE
[bug]: update link to patchmatch in cli

### ISSUE THREAD

**Issue by netsvetaev** [invoke-ai/InvokeAI#2116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What happened?

When patchmatch is disabled, cli point to the

`>> patchmatch.patch_match: WARNING - Refer to https://github.com/invoke-ai/InvokeAI/blob/main/docs/installation/INSTALL_PATCHMATCH.md for installation instructions.`

Should be:

`https://github.com/invoke-ai/InvokeAI/blob/main/docs/installation/060_INSTALL_PATCHMATCH.md`

**Comment by Gitterman69** [comment]
got exactly the same with the current version of invoke
