### ISSUE TITLE
[bug]: WebUI: has stopped working after crash, even after reboot.

### ISSUE THREAD

**Issue by Barafu** [invoke-ai/InvokeAI#2118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8

### What happened?

I was writing a report for bug #2117  and intentionally caused it to crash the backend several times. After the last time, I can't open WebUI anymore - I only get a white blank page. In the console, it writes ">> System config requested" per page refresh and nothing else.

Here is a list of actions that I took and they did NOT help:

- Rebooting the PC, obviously. 
- Checking the source folder - `git status` reports no changes
- Checking the user data folder - only changes in the output folder were noticed. I deleted the output folder contents. 
- Opening WebUI in another browser which was never used with it before, namely Firefox.

**Comment by whosawhatsis** [comment]
Have to tried switching ports? https://github.com/invoke-ai/InvokeAI/blob/main/docs/features/WEB.md#additional-options

**Comment by Barafu** [comment]
You were right, it started working again! But why? Why does it not work on port 9090 anymore? I tried switching back - does not work. Why backend still reacts to refreshes, meaning it isn't blocked completely?

**Comment by whosawhatsis** [comment]
I had a similar problem. It seemed that maybe something else was listening on that port and responding before invoke did? Changing ports gets around it.

It also causes the browser to see it as a different site, with its own set of cookies and such, which might have some effect, though switching browsers should also fix that problem.

**Comment by Kastor13** [comment]
> 

Hello, can you please describe how to switch port for dummies?
I`m having the same issue, and can`t figure out how to do this..

**Comment by Kastor13** [comment]
> Have to tried switching ports? https://github.com/invoke-ai/InvokeAI/blob/main/docs/features/WEB.md#additional-options

Hello, can you please describe how to switch port for dummies?
Im having the same issue, and cant figure out how to do this..

**Comment by Barafu** [comment]
I start interface like this: ` python .\scripts\invoke.py --web --port 24375`

**Comment by Kastor13** [comment]
> I start interface like this: ` python .\scripts\invoke.py --web --port 24375`

Thanks, but can you please be more specific, what do I need to do, step by step?
I am new to all this and a complete zero in coding :(

**Comment by Kastor13** [comment]
> I start interface like this: ` python .\scripts\invoke.py --web --port 24375`

I have try to do this. But it doesn't help. Still have blank screen instead web interface :(

**Comment by whosawhatsis** [comment]
For those having this problem with the 2.2.5 release candidate, try installing 2.2.4 instead. It seems the 2.2.5 installer sometimes misses some files.

**Comment by Barafu** [comment]
Closing the issue because major changes to backend made it irrelevant.
