### ISSUE TITLE
unified canvas doesn't extend when outpainting, creates random new picture

### ISSUE THREAD

**Issue by magaspah** [invoke-ai/InvokeAI#2123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12

### What happened?

Using unified canvas to outpaint and extend images.  I have been able to in the past just extend no problem.  Today I have been trying different pictures and outpaint just seems to create random pictures.  I  tried oupainting the top of dog ears, It would sometimes make a sign, other times another dogs face, etc.

On this pic, trying to get the top of the christmas hat, random stuff again.  It's set to inpaint 1.5.  I updated it a couple of days ago.
![Screenshot 2022-12-24 025202](https://user-images.githubusercontent.com/112981301/209432769-3fbd310d-ea55-493b-a1ee-1a3b04f20c35.png)

### Screenshots
![Screenshot 2022-12-24 025646](https://user-images.githubusercontent.com/112981301/209432851-b267a038-f8a1-419a-818e-b5683b8fa7ad.png)
![Screenshot 2022-12-24 025731](https://user-images.githubusercontent.com/112981301/209432853-0e4b6de4-5a9e-4c6c-9ebb-a490fc561991.png)

_No response_

### Contact Details

magas.pah@gmail.com

**Comment by Barafu** [comment]
I get this when I have fixed seed and low variations
