### ISSUE TITLE
[bug]: Stopped working after video card replacement

### ISSUE THREAD

**Issue by goodwin74** [invoke-ai/InvokeAI#2125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

6GB

### What happened?

When installing for the first time, I had a GTX 960 4gb video card and everything worked. The other day I installed gtx 1660 6gb and now, when generating, I always get an error that there is not enough video card memory. Why does this happen?

p/s/ free gpu mem doesn't help. Moreover, 960 worked without --free_gpu_mem

**Comment by kriptolix** [comment]
Hi, it's been a while since I last checked this, but there was a compatibility issue with the gtx 16XX series. According to this issue https://github.com/invoke-ai/InvokeAI/issues/775 the problem seems to have been resolved, but there may have been some sort of regression.

What version of invoke are you using?

**Comment by goodwin74** [comment]
> Hi, it's been a while since I last checked this, but there was a compatibility issue with the gtx 16XX series. According to this issue #775 the problem seems to have been resolved, but there may have been some sort of regression.
> 
> What version of invoke are you using?

InvokeAI 2.2.5. 

Yes, apparently this is somehow connected with the 16x version of the video card, since the previous 960 gtx worked fine, although there was less memory there.
Moreover, I note that the InvokeAI version for Windows works fine. Ubuntu also has other SD toolkits installed. For example "automatic" it works well on both Ubuntu and Windows.
I think this is related to how InvokeAI works in Ubuntu.
