### ISSUE TITLE
[bug]: 404 for link 

### ISSUE THREAD

**Issue by ForwardForward** [invoke-ai/InvokeAI#2141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

404 for such link. It shows then I use install.bat on Windows:

** DOWNLOADING DIFFUSION WEIGHTS **
You can download and configure the weights files manually or let this
script do it for you. Manual installation is described at:

https://github.com/invoke-ai/InvokeAI/blob/main/docs/installation/INSTALLING_MODELS.md

**Comment by kriptolix** [comment]
The link reference seems to be incorrect, I get the same error, The correct address is:

https://github.com/invoke-ai/InvokeAI/blob/main/docs/installation/050_INSTALLING_MODELS.md

With "050" before "INSTALLING_MODELS.md".
