### ISSUE TITLE
[bug]: ImportError: cannot import name 'login' from 'huggingface_hub'

### ISSUE THREAD

**Issue by OdysseasKar** [invoke-ai/InvokeAI#2149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What happened?

When running invoke.sh from cli and selecting web interface

### Screenshots

![image](https://user-images.githubusercontent.com/22063266/209589965-063052b1-54a1-4e8a-95cb-fb21ae9ff33f.png)

**Comment by williamchong** [comment]
Your huggingface_hub library is outdated
Try running `pip install -U huggingface_hub` to install latest version
