### ISSUE TITLE
[bug]: Scripts dir is not created, making install fail

### ISSUE THREAD

**Issue by sjoller** [invoke-ai/InvokeAI#2153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

The installer fails with several `The system cannot find the path specified.` messages in the `*** Installing InvokeAI Requirements ***` section. I had a look in the `install.bat` file, and it tries to access `...\invokeai\.venv\Scripts\activate.bat`, but the `Scripts` dir is not created, in the previous (successful) steps. Likewise the `...\invokeai\.venv\Scripts\python` is also missing, so the next steps in this section fails as well, making the script exit.

I made sure all the requirements were met, including installing python v3.11. I saw in another issue, that v3.11 were having some issues (with torch, as I recall), so I uninstalled v3.11 and installed v3.10 instead (as pointed out to be working, in the other issue), but to no avail.

**Comment by pdsmike** [comment]
Did you run the install from Command Prompt as Administrator? Maybe that helps.

**Comment by sjoller** [comment]
I tried running the script as administrator (by right-clicking) and from an admin terminal, but the `Scripts` dir is still missing.

**Comment by sjoller** [comment]
This is most like caused by having multiple python executables in my system. When setting up the virtual environment, it goes through the `PATH` until it finds a python executable - in my case it was in my Inkscape installation. I found old python bug reports going on, in length, about adding paths to a users `PATH` or not, when installing python. I guess they ended up not doing it.

I'm not well enough versed in python, to explain why that would be an issue, but after adding the newly installed python path to my `PATH`, *before* the Inkscape one, it created the virtual environment with the correct path for `home` in the `pyvenv.cfg` file and the installer now runs successfully.

Short of forcing the user to input the proper python path during installation, I don't think there's anything you can do about this issue - it's not really a bug in the installer script, so I'm closing this issue.
