### ISSUE TITLE
[enhancement]: from_file from interactive mode?

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#2161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Greetings,

Please consider enabling from_file to be use in interactive mode. Forcing invoke.py + model(s) reload makes this feature barely useful.

Thank you,

**Comment by Neosettler** [comment]
@lstein any chances for this to happen?

**Comment by psychedelicious** [comment]
We no longer support from file on the cli.
