### ISSUE TITLE
[bug]: ktinker not found

### ISSUE THREAD

**Issue by mickr777** [invoke-ai/InvokeAI#2162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12gb

### What happened?

For anyone getting "ktinker not found" on ubuntu after model manager was added and did a "git pull"

I had to run "apt-get install python3-tk" now it loads fine

**Comment by blessedcoolant** [comment]
This was because of a leftover line. I removed it now and will be shipped a part of #2136. Sorry about that.
