### ISSUE TITLE
[bug]: patchmatch.patch_match: ERROR 

### ISSUE THREAD

**Issue by jlcases** [invoke-ai/InvokeAI#2164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

0

### What happened?

when i try to invoke an image i get this message

patchmatch.patch_match: INFO - Compiling and loading c extensions from "/Users/jlcases/codigo/InvokeAI/InvokeAI/lib/python3.10/site-packages/patchmatch".
>> patchmatch.patch_match: ERROR - patchmatch failed to load or compile (Command 'make clean && make' returned non-zero exit status 2.).
>> patchmatch.patch_match: INFO - Refer to https://github.com/invoke-ai/InvokeAI/blob/main/docs/installation/INSTALL_PATCHMATCH.md for installation instructions.
>> Patchmatch not loaded (nonfatal)

**Comment by gogurtenjoyer** [comment]
Hello! Unfortunately, patchmatch isn't working on Mac at the moment, so that error is expected. More info here: https://invoke-ai.github.io/InvokeAI/installation/060_INSTALL_PATCHMATCH/#macintosh

**Comment by markojak** [comment]
I"m also experiencing this. Is it fair to say then that InvokeAI doens't work on MacOS m1 because of this?
I can't get a Web interface working without patchmatch

**Comment by gogurtenjoyer** [comment]
Nope, patchmatch is optional - everything else should work fine. Also, if you do want to use patchmatch on Mac, there's now some instructions here: https://github.com/invoke-ai/InvokeAI/discussions/1893

**Comment by stardeaf** [comment]
I'm getting the same error in Ubuntu, am I supposed to?
