### ISSUE TITLE
[bug]: 2.2.5 - I get an error when installing

### ISSUE THREAD

**Issue by if3lc** [invoke-ai/InvokeAI#2166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### What happened?

I get an error when installing.

### Screenshots
```
./install.sh
InvokeAI simple installer...

Some of the installation steps take a long time to run. Please be patient.
If the script appears to hang for more than 10 minutes, please interrupt with control-C and retry.
<Press any key to start the install>
Installing for osx-arm64
Python 3.10.2 found at /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10

Select your preferred location for the 'invokeai' directory [/Users/if3lc]:
./install.sh: line 124: python: command not found
```

### Additional context

In version 2.2.4 I was getting an error in the "Upscale Image" section, so I uninstalled it and did a clean reinstall and I get the above error during installation.

**Comment by mindnmattr** [comment]
same exact error. I'm running on mac osx

**Comment by torsial** [comment]
hi same problem, macbook m1 also imac, instaled python, installed xcode, certificates and same error :(

**Comment by CodeZombie** [comment]
The problem is likely that your python has been installed as the command `python3`, which the script can't detect.
If you edit the install.sh file at line 124 and change the `python` command to `python3`, this will likely fix the issue.

**Comment by N2bK** [comment]
How do I edit the install.sh file at line 124?

**Comment by if3lc** [comment]
Open install.sh with any text editing program, I use vscode and change the `python` command in line 124 to `python3`

After editing, line 124 should look exactly like this.
`ROOTDIR=$(python3 -c "from pathlib import Path; print(Path('${ROOTDIR}').expanduser().resolve())")`

**Comment by if3lc** [comment]
You can use any text editor, just find this code,
`ROOTDIR=$(python -c "from pathlib import Path; print(Path('${ROOTDIR}').expanduser().resolve())")`

And change like this,
`ROOTDIR=$(python3 -c "from pathlib import Path; print(Path('${ROOTDIR}').expanduser().resolve())")`

You can use "TextEdit" 😊

**Comment by N2bK** [comment]
> You can use any text editor, just find this code, `ROOTDIR=$(python -c "from pathlib import Path; print(Path('${ROOTDIR}').expanduser().resolve())")`
> 
> And change like this, `ROOTDIR=$(python3 -c "from pathlib import Path; print(Path('${ROOTDIR}').expanduser().resolve())")`
> 
> You can use "TextEdit" 😊

I tried that, and it didn't work, it says: "line 124: python3: unbound variable"

**Comment by if3lc** [comment]
Unfortunately I don't know much more about this, I hope someone can help you solve your problem.

**Comment by TheDarjeeling** [comment]
> Open install.sh with any text editing program, I use vscode and change the `python` command in line 124 to `python3`
> 
> After editing, line 124 should look exactly like this. `ROOTDIR=$(python3 -c "from pathlib import Path; print(Path('${ROOTDIR}').expanduser().resolve())")`

wow, thank you for posting this, this worked perfectly for me.
