### ISSUE TITLE
[bug]: index.e5f9e8aa.js:1 not found

### ISSUE THREAD

**Issue by DuckyBlender** [invoke-ai/InvokeAI#2169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What happened?

When I start the web interface using invoke.bat, the website is blank. The favicon loads tho

### Screenshots

![brave_iWDhtMaqTw](https://user-images.githubusercontent.com/42645784/209986982-4ada181a-ad1f-4ed8-b760-f85c931d60d7.png)

The website (i've changed the port in this one)

### Additional context

I've changed the ports, and the non webui version works without any issues, even on my GTX 1660 SUPER
I've also tried multiple different browsers with the same result

**Comment by bildillusiondesign** [comment]
Yup. Same here. Installation went fine. In the command window it says: ">> Started Invoke AI Web Server!" But in the browser (Chrome), there's a blank page. I have a RTX 3070ti, 8GB, should at least start the browser UI. Not happening yet. What can we do?

**Comment by DuckyBlender** [comment]
Fixed for me, probably because of #2180

**Comment by WillyamBradberry** [comment]
> Fixed for me, probably because of #2180

Ok, fixed for you, onluy for you, next keep it short without any explanation to others. Thank you.

**Comment by DuckyBlender** [comment]
> > Fixed for me, probably because of #2180
> 
> Ok, fixed for you, and for you only, so next keep it short without any explanation to others. Thank you.

I just git pulled the repo and it was fixed, then I read the release notes and it said the issue was fixed so I thought it was fixed for everyone. There is still another issue open about this if you want help :)
