### ISSUE TITLE
[enhancement]: Add released version number to web UI 

### ISSUE THREAD

**Issue by Alchete** [invoke-ai/InvokeAI#2172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Maybe I'm missing something completely obvious, but I'm wondering what version of Invoke I have (since I installed it a couple of weeks ago) and yet I don't see the version number anywhere in the web UI.  I also checked the various settings panels.

Given that, it would be nice for the version number to be readily visible.  I would suggest putting it to the right of the Invoke AI logo, that's in the upper left of the UI.

Anyway, thanks, love the tool!

### Aditional Content

![image](https://user-images.githubusercontent.com/4705189/209995518-56210671-267a-4238-91ea-09e17f52dbc5.png)

**Comment by laurentVeliscek** [comment]
you can get the version number overing the invoke.ai logo with your mouse...
<img width="285" alt="Capture d’écran 2024-05-13 à 08 44 46" src="https://github.com/invoke-ai/InvokeAI/assets/19191214/6e7454fa-99b2-42d4-9374-6f9bd991490e">
