### ISSUE TITLE
[bug]: Unable to switch to inpainting-1.5 model. Server crashes with no errors.

### ISSUE THREAD

**Issue by dholbrook86** [invoke-ai/InvokeAI#2181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

8GB RTX 4000

### What happened?

I have installed InvokeAi. No issues. No warnings. Everything went well. Python 3.10.
Regular generation works. Switching to other models works.

I just can not load the inpainting model. It was set up by the model downloader/installer.

This problem existed on InvokeAi v2.2.4 and so I tried upgrading to 2.2.5 and it is still not working.

I've searched every issue and tried every potential fix.

Is there a way to get an error rather than just having it crash?

Output
```
>> Model change requested: inpainting-1.5
>> Current VRAM usage:  2.17G
>> Cache limit (max=2) reached. Purging stable-diffusion-1.5
>> Offloading comic-diffusion-V2 to CPU
>> Scanning Model: inpainting-1.5
>> Model Scanned. OK!!
>> Loading inpainting-1.5 from /home/workspace/invokeai/models/ldm/stable-diffusion-v1/sd-v1-5-inpainting.ckpt
  | Forcing garbage collection prior to loading new model
   | LatentInpaintDiffusion: Running in eps-prediction mode
   | DiffusionWrapper has 859.54 M params.
./invoke.sh: line 24:  2409 Killed                  .venv/bin/python .venv/bin/invoke.py --web $*
```
I know this may be a tricky one, so I'm asking for help troubleshooting. What steps can I try to understand what the issue is so we can fix it?

**Comment by dholbrook86** [comment]
Finally able to solve this. For anyone else who runs into this issue.
You need more than 16GB of system memory. For some reason that is not enough to load the inpainting model.
Bumped the instance up to 20GB and we were able to switch to the inpainting model.

**Comment by riccardomorabito** [comment]
> 

Do you mean ram memory or gpu system memory?

**Comment by dholbrook86** [comment]
> Do you mean ram memory or gpu system memory?
> 
> > Finally able to solve this. For anyone else who runs into this issue. You need more than 16GB of system memory. For some reason that is not enough to load the inpainting model. Bumped the instance up to 20GB and we were able to switch to the inpainting model.

RAM memory. Not GPU VRAM.
Weird huh?
