### ISSUE TITLE
[bug]: python.exe - Bad Image: \invokeai\.venv\lib\site-packages\patchmat ch\opencv_world460.dll is either not designed to run on Windows or it contains an error.

### ISSUE THREAD

**Issue by cjcodepen** [invoke-ai/InvokeAI#2184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

amd

### VRAM

16GB

### What happened?

I get a python.exe - Bad Image

C:\Users\Cj\lnvokeAl\invokeai\.venv\lib\site-packages\patchmat
ch\opencv_world460.dll is either not designed to run on
Windows or it contains an error. Try installing the program
again using the original installation media or contact your
system administrator or the software vendor for support. Error
status Oxc000007b.

<img width="396" alt="yBrXHUAFxX" src="https://user-images.githubusercontent.com/101925017/210121403-daeaebee-7900-4de8-b827-a0227decb79c.png">

### Contact Details

cjsarreal07wfh@gmail.com

**Comment by metadreamx** [comment]
Im having this issue. What could the problem be?

**Comment by bani6809** [comment]
same issue here.

**Comment by hipsterusername** [comment]
This appears to be a patchmatch installation issue. It’s still being experienced in 3.0?
