### ISSUE TITLE
[bug]: All fields reset on page reload!

### ISSUE THREAD

**Issue by CreationStory** [invoke-ai/InvokeAI#2188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

N/A

### What happened?

When reloading the web UI interface, all fields are now wiped blank. Previously (before I last updated a few days ago), when the render crashed or even if you just needed to refresh the webpage, the prompt, all selected items and fields were kept perfectly. Now they ALL reset!

**Comment by mcbexx** [comment]
Not only the data entry fields, all settings (language, Display In-Progress Images, Confirm On Delete, Display Help Icons, Use Canvas Beta Layout) reset to defaults for me when I refresh the browser page. Tried to Reset WebUI from settings, restart InvokeAI, same effect when refreshing afterwards. v2.25, and it started happening suddenly when before it wasn't an issue within that same version.

**Comment by psychedelicious** [comment]
May need to forcibly reset the browser's `localStorage`:
- Run InvokeAI and open the app in your browser per usual
- Open your browser's javascript console as described here: https://www.coursera.support/s/article/learner-000001653-How-to-open-the-Javascript-console?language=en_US
- Paste this command and press enter: `localStorage.clear()`
- Refresh the page

Hopefully this sorts this issue.

**Comment by mcbexx** [comment]
> Hopefully this sorts this issue.

Yes, thank you, this indeed helped.
