### ISSUE TITLE
[bug]: Infill scaling does not scale the image to infill

### ISSUE THREAD

**Issue by Ghost---Shadow** [invoke-ai/InvokeAI#2189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What happened?

It seems to me that the infill scaling in the unified canvas does not upscale the bounding box before sending it to the model.

SD generations are pretty poor when asked to generate images smaller than 512x512 so if the bounding box for infilling in smaller than 512x512, it does not seem to upscale and downscale the image correctly. 

Proposed solution would be to do a simple bilinear upscaling of the pixels in the bounding box, passing it through the diffuser and a bilinear downscaling to the original patch size.

### Screenshots

Here is an example of the prompt "Dragon Flying in the sunset" with 256x256 resolution

![Dragon Flying in the sunset 256x256](https://user-images.githubusercontent.com/7743925/210141338-9267f84d-268b-4f00-9c06-2c57c5e26a1e.png)

Same prompt with 512x512

![merged_canvas de5e12e4](https://user-images.githubusercontent.com/7743925/210141383-5a638e4b-f824-4c40-aa31-7fa17f9425b7.png)

### Without rescaling
![merged_canvas 851c0786](https://user-images.githubusercontent.com/7743925/210141412-31a6846f-0c64-4844-8de4-db484af98f53.png)

### With rescaling
![merged_canvas 1865cc2f](https://user-images.githubusercontent.com/7743925/210141448-6ead7832-99a4-4c28-be5c-2daf97bcd885.png)

**Comment by jordanservice** [comment]
I seem to be having a similar issue.

**Comment by kyschouv** [comment]
Is this happening with inpainting, or with new image generation on the canvas? With inpainting, this should work (I just tested it and it works, though my branch is slightly out of date). I don't think there's code set up to do this for new generations though.

**Comment by Kyle0654** [comment]
Is this happening with inpainting, or with new image generation on the canvas? With inpainting, this should work (I just tested it and it works, though my branch is slightly out of date). I don't think there's code set up to do this for new generations though.

**Comment by Ghost---Shadow** [comment]
I am using the unified canvas

**Comment by psychedelicious** [comment]
If you manage to catch it in the act, please copy and paste your terminal output for the failed generation, starting from `>> Image generation requested`.

Also please let us know what version of invokeai you are running.

**Comment by Ghost---Shadow** [comment]
poo

**Comment by psychedelicious** [comment]
As requested previously, if this is a problem, please copy the output from the terminal window so we can see what exactly is happening. Also, please include a screenshot of the whole canvas, as this gives more useful info.
