### ISSUE TITLE
[bug]: GUI shows a "Page cannot be displayed" message

### ISSUE THREAD

**Issue by JP0045** [invoke-ai/InvokeAI#2191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What happened?

Succesfully installed InvokeAI
Launch Invoke.sh in Terminal
Select Option 2

It goes through the motions, always asks to install environments, regardless of which option I choose, it concludes and wishes me to have fun

Open browser to Localhost:9090

"Page cannot be displayed"

### Screenshots

[2022-12-31_15-01-36.zip](https://github.com/invoke-ai/InvokeAI/files/10327975/2022-12-31_15-01-36.zip)

### Additional context

A similir issue on a Windows machine suggested to update everything in the Frontend folder, I downloaded, extracted all items in the invokeai/.venv/frontend from https://github.com/invoke-ai/InvokeAI/tree/main/frontend,  Unfortunately, same issue persists

**Comment by psychedelicious** [comment]
Sorry for the late reply. The output from the video shows your system has run out of VRAM. Looks like its a 2GB VRAM system - unfortunately this is not enough to run InvokeAI.
