### ISSUE TITLE
[bug]: InvokeAI crash after changing Models

### ISSUE THREAD

**Issue by TheSirTigerr** [invoke-ai/InvokeAI#2195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What happened?

Hello, I have the problem that when I change the model in the webUI it just crashes and in the console I get the error that can be seen in the picture. 
Can someone help me please?

### Screenshots

![image](https://user-images.githubusercontent.com/96537622/210167270-e356b17a-ecae-4808-8481-602032b3c310.png)

**Comment by TheSirTigerr** [comment]
i have a Tesla T4 with 15109MiB of VRAM. i can load the basic Model and use it normaly but when i want to change the model it just crash.

**Comment by kriptolix** [comment]
I can confirm this, switching to the inpanting model sometimes causes the invoke to hang. Switching between models often seems to do the same thing too.

OS: Linux
VGA: Nvidia 1060 6gb
Ram: 16gb

**Comment by psychedelicious** [comment]
@lstein Any ideas?

**Comment by lstein** [comment]
The whole model loading system is changing with the release of 2.3 and maybe this issue will be solved by that.

In the meantime, how much system RAM do you have? The problem may not be running out of VRAM, but running out of RAM when the system attempts to cache the model into CPU. You can test this behavior by launching invoke.py with `--max_loaded_models=1`, which will prevent all caching.
