### ISSUE TITLE
[bug]: Deleting from gallery deletes multiple images

### ISSUE THREAD

**Issue by lopopoloco** [invoke-ai/InvokeAI#2197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

Deleting from gallery (by pressing delete from keyboard) sometimes deletes multiple images (can be 2+ images deleted at the same time), usually happens after pressing load more button.

**Comment by psychedelicious** [comment]
Are they actually deleted (they should be sent to Recycle Bin) or is it just a UI bug, in which case on refreshing the page they show up again?

**Comment by YulienPohl** [comment]
Can confirm this bug.
Navigate in the gallery + press Del, creates 2 delete messages. (sporadic)

Btw. accepting a deletion with enter would be great.
