### ISSUE TITLE
[bug]: installation on Ubuntu 22.10 does not work (install.sh: 18: set: Illegal option -o pipefail)

### ISSUE THREAD

**Issue by Lesani** [invoke-ai/InvokeAI#2198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

24

### What happened?

On Ubuntu 22.10 // Python 3.10.7

```
invokeAI$  sh install.sh
install.sh: 18: set: Illegal option -o pipefail
```

if I edit the install.sh and remove the "o" option I get:

```
invokeAI$ sh install.sh
install.sh: 21: function: not found
```

Line 21 is the "function _err_exit {"

**Comment by Baughn** [comment]
Try running it with `bash install.sh`

**Comment by Lesani** [comment]
indeed... "sh install.sh" did not work, bash does
