### ISSUE TITLE
[bug]: Unable to install Invoke AI 2.2.4 and 2.2.5 on Windows 10

### ISSUE THREAD

**Issue by eexpbh** [invoke-ai/InvokeAI#2200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cpu

### VRAM

6GB

### What happened?

I have got python version 3.11 installed. However, during the installation the installation is breaking doing with following message:
Collecting transformers==4.25.*
  Using cached transformers-4.25.1-py3-none-any.whl (5.8 MB)
ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement torch==1.12.1 (from versions: none)
ERROR: No matching distribution found for torch==1.12.1
Requirements installation failed. See above for errors and check https://invoke-ai.github.io/InvokeAI/installation/INSTALL_AUTOMATED/#troubleshooting for potential solutions.

Please suggest a remedy.

Thanks

### Contact Details

eexpbh@gmail.com

**Comment by Turkinolith** [comment]
+1, same error on windows 11.

**Comment by Turkinolith** [comment]
Looked into it a bit and in my environment I have Python 3.11.0 installed.
PyTorch on Windows only supports Python 3.7-3.9

**Comment by kadeshar** [comment]
I have python 3.10.8 and everything working.
There is issue for pytorch and python 3.11 https://github.com/pytorch/pytorch/issues/86566

**Comment by Turkinolith** [comment]
Yep, downgraded to 3.10.9 and it was able to install pytorch this time and run the installer for 2.2.5.

**Comment by eexpbh** [comment]
No luck! downgraded to 3.10.9 ran the installer. Things went fine, however, at the very end the installation broke with following message:

Successfully built InvokeAI
Installing collected packages: InvokeAI
Successfully installed InvokeAI-2.2.5
Installation successful.
.\templates\rootdir\configs\INITIAL_MODELS.yaml
.\templates\rootdir\configs\models.yaml.example
.\templates\rootdir\configs\sd-concepts.txt
.\templates\rootdir\configs\stable-diffusion\v1-finetune.yaml
.\templates\rootdir\configs\stable-diffusion\v1-finetune_style.yaml
.\templates\rootdir\configs\stable-diffusion\v1-inference.yaml
.\templates\rootdir\configs\stable-diffusion\v1-inpainting-inference.yaml
.\templates\rootdir\configs\stable-diffusion\v1-m1-finetune.yaml
8 File(s) copied
The system cannot find the path specified.
Configuration failed. See above for error messages and check https://invoke-ai.github.io/InvokeAI/installation/INSTALL_AUTOMATED/#troubleshooting for potential solutions.
The installer will exit now.

**Comment by Gitterman69** [comment]
i get this error on windows 10:

`[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip
Installation successful.
'xcopy' is not recognized as an internal or external command,
operable program or batch file.
Loading Python libraries...

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\domin\Desktop\InvokeAi\.venv\Scripts\configure_invokeai.py:44 in <module>               │
│                                                                                                  │
│    41 Default_config_file = './configs/models.yaml'                                              │
│    42 SD_Configs = './configs/stable-diffusion'                                                  │
│    43                                                                                            │
│ ❱  44 assert os.path.exists(Dataset_path),"The configs directory cannot be found. Please run t   │
│    45                                                                                            │
│    46 Datasets = OmegaConf.load(Dataset_path)                                                    │
│    47 completer = generic_completer(['yes','no'])                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError: The configs directory cannot be found. Please run this script from within the invokeai runtime
directory.
Configuration failed. See above for error messages and check https://invoke-ai.github.io/InvokeAI/installation/INSTALL_AUTOMATED/#troubleshooting for potential solutions.
The installer will exit now.
Press any key to continue . . .`

**Comment by andyvirt** [comment]
I have the same error @Gitterman69

**Comment by andyvirt** [comment]
@Gitterman69 - see https://github.com/invoke-ai/InvokeAI/discussions/2304

**Comment by eexpbh** [comment]
Issue still persist.

**Comment by yosun** [comment]
issue still exists.
