### ISSUE TITLE
[enhancement]: Emulate the automatic1111 remote API

### ISSUE THREAD

**Issue by apurtell** [invoke-ai/InvokeAI#2205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

There is an emerging ecosystem of integrations like https://github.com/tgiesselmann/gimp-stable-boy that use Automatic1111’s remote API (when it is launched with —api) to invoke Stable Diffusion. For artists who prefer InvokeAI but also use tools like GIMP or Krita or others (on a growing list of emerging plugins written against this API) in their usual workflow it would be ideal if the API could be emulated rather than requiring setup and care of two separate Stable Diffusion derivative installations.

**Comment by kozaluss** [comment]
My thoughts exactly. Bump!

**Comment by mroxso** [comment]
Bump! I also thought of this!

**Comment by lstein** [comment]
@CapableWeb , perhaps you'd be interested in working on this?

**Comment by montoulieu** [comment]
Yeah, this would be a solid addition.
Currently one of the reasons I'm relying on A1111.

**Comment by psychedelicious** [comment]
We are approaching migration to a new, far more powerful web API which will make development of plugins and additional clients much more straightforward. However, I do not see a future in which we emulate or provide compatibility with A1111 as we will be processing requests in a very different way.

**Comment by micahscopes** [comment]
@psychedelicious is this a REST API?  Or WebSocket based one?

The Blender dream-textures extension is currently using a fork of InvokeAI but it'd be cool if it could plug into an existing instance.  However I wasn't able to find web API documentation anywhere, I guess that's coming soon?

(See here for relevant dream-textures issue: https://github.com/carson-katri/dream-textures/issues/225)

**Comment by psychedelicious** [comment]
@micahscopes 

It's mostly HTTP with some signaling (like generation progress) done via socket.io. 

It uses a graph execution system, where you send json describing processing nodes and the links between them. See #1650 for detail. 

We will provide proper support and documentation for this new api (current one was built alongside the web ui and not intended for public consumption). 

I'm not sure of an eta but I am preparing the web app for migration to the new system now.

**Comment by micahscopes** [comment]
@psychedelicious 
Do these graphs more or less map directly to diffusers pipelines? The dream-textures library has switched to using diffusers directly and are passing around pipeline descriptions, so I'm curious to understand if their new execution system could be mapped to your upcoming API.

**Comment by psychedelicious** [comment]
@micahscopes 
No, the graphs are a layer or two above diffusers pipelines (in fact we have just migrated to using diffusers ourselves). 

A simple example graph is: `txt2img node` --> `img2img node` --> `showImage node`

In this simple case, they are linked serially, but so long as inputs and outputs are of the same type, any nodes can be linked. When this graph is executed, an image is generated via `txt2img` and its image output is fed into `img2img`, generating a new image, which then is fed into `showImage`, which shows the image to the user.
