### ISSUE TITLE
[enhancement]: Embed the command line for recreating an image as PNG comment

### ISSUE THREAD

**Issue by apurtell** [invoke-ai/InvokeAI#2206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

It would be very useful, for reproducing earlier work where the invoke log may not be available, such as after distribution or archival of a PNG format output sample, if the full effective invoke command line could be stored in the image file as a PNG comment (see section 4.3.2 of http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html). 

This should probably be a non-default option to avoid violating expectations that users may have that their prompt and settings are private and not distributed with an image.

**Comment by mickr777** [comment]
All info is saved in the png file already, if you use a program like exiftool you can read the data back or simply add back the the  image from your archive to your output folder and you can reuse the prompt and settings from it

**Comment by apurtell** [comment]
Pardon me, is this documented? I didn’t find it.

**Comment by mickr777** [comment]
> Pardon me, is this documented? I didn’t find it.

Sorry I'm not sure I haven't read the readme docs for a while, it should be as the user needs to know if they wish to remove it from there images before posting them somewhere

**Comment by apurtell** [comment]
Ah ok. I found it mentioned in the NSFW Checker page. That’s why I missed it. A minor suggestion would be to pull that discussion about watermarking out elsewhere. FWIW first place I checked was the Other page.
