### ISSUE TITLE
Doesn't work after updating (to 2.2.5); two errors ("detected .bin file masquerading as .pt file" and "KeyError: 'parameter name can\'t contain "."') [bug]: 

### ISSUE THREAD

**Issue by AdvaitaSprite** [invoke-ai/InvokeAI#2212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

10gb

### What happened?

I had other problems the first time I installed, but after multiple attempts finally got it working on a continue of a previous installation attempt. However, after that rocky start (on version 2.2.3 iirc?) I finally had InvokeAI up and running and I was enjoying it.

Fast forward not that far, and the new version (2.2.5) released. I attempted to use the updater. It failed. I attempted multiple more times, attempted uninstalling and installing a fresh version in a fresh directory. Still didn't work. I can't remember what the issues were before, because I've had so many, but currently these are the two errors I'm getting when I try to launch the current installation I've been working with (and iirc the errors on the last install of this version were the same). I type in "2" for the browser-based version (not interested in command line or developer), but the browser never launches (nor opens a new window if I have my browser, Firefox, open already). 

Unfortunately, it's extremely hard to catch the error prompts in a screencap because a bunch of pages worth of code flashes by and then the whole thing crashes and closes out of the command prompt window. But I caught the last page.

First, it concatenates a new line saying "Detected a .bin file masquerading as a .pt file," not once, not twice, but over and over until the whole command prompt is filled with this message... I have no idea what file it's referring to. I've looked all through the directory and can't find a single suspicious .pt or .bin file. No weird models that I haven't used plenty of times in other UIs, no custom VAE files that might be causing an issue... Not sure what it's about. Here's a pic of that screen.

![2022-12-29 18_46_14-invokeai](https://user-images.githubusercontent.com/100255822/210286413-6392b412-5a8a-4b14-b1db-2decef75fc46.png)

But then, the tons of code flashes by, ending with this error message:
"KeyError: 'parameter name can\'t contain "."'

The out of place "\" is part of the message so I included it, but I don't know what it's referring to either. Here is a screencap in case it will make sense to someone with more python knowledge.

![2022-12-29 18_46_44-C__WINDOWS_system32_cmd exe](https://user-images.githubusercontent.com/100255822/210286367-ed453a06-4277-4db5-b42f-5786a43366a4.png)

And to be clear, my first thought was that the issue could be the "." in the directory I was trying to install into, which ended in a folder named "InvokeAI2.4" when I thought that was the version I was trying to install. Since then I renamed it without any periods in it. Still gives the same error message.

It's frustrating that I had it working and then updating with what I thought ought to be a simple update script would make the program unusable again... But if anyone has any solutions or knows the errors, I'd love to get it up and running again, because I do very much like the UI when it works (and now the infinite outpainting on the other online UI I was using for it has introduced a credit system with very limited amounts of free credits, so Invoke had become the easiest way for me to access what had become one of my main workflows). I've already put a ridiculous amount of time into installing and reinstalling, so hopefully there's some very simple solution I have overlooked that might fix everything.

**Comment by Skynet1981** [comment]
I also got:  Detected .bin file masquerading as .pt file

After updating from 2.2.4>2,2,5
Though with a different following error message than OP.
