### ISSUE TITLE
[bug]: Installing on MacOS with M1 chip using automated install

### ISSUE THREAD

**Issue by Codzsters** [invoke-ai/InvokeAI#2213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### What happened?

Issue with install: 

 DEPRECATION: lmdb is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for lmdb ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for lmdb did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      py-lmdb: Using bundled liblmdb with py-lmdb patches; override with LMDB_FORCE_SYSTEM=1 or LMDB_PURE=1.
      patching file lmdb.h
      patching file mdb.c
      py-lmdb: Using CPython extension; override with LMDB_FORCE_CFFI=1.
      running install
      /Users/codysilby/Downloads/InvokeAI/.venv/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build/lib.macosx-11.0-arm64-cpython-310
      creating build/lib.macosx-11.0-arm64-cpython-310/lmdb
      copying lmdb/cffi.py -> build/lib.macosx-11.0-arm64-cpython-310/lmdb
      copying lmdb/__init__.py -> build/lib.macosx-11.0-arm64-cpython-310/lmdb
      copying lmdb/_config.py -> build/lib.macosx-11.0-arm64-cpython-310/lmdb
      copying lmdb/tool.py -> build/lib.macosx-11.0-arm64-cpython-310/lmdb
      copying lmdb/__main__.py -> build/lib.macosx-11.0-arm64-cpython-310/lmdb
      running build_ext
      building 'cpython' extension
      creating build/temp.macosx-11.0-arm64-cpython-310
      creating build/temp.macosx-11.0-arm64-cpython-310/build
      creating build/temp.macosx-11.0-arm64-cpython-310/build/lib
      creating build/temp.macosx-11.0-arm64-cpython-310/lmdb
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -mmacosx-version-min=11.0 -Wno-nullability-completeness -Wno-expansion-to-defined -Wno-undef-prefix -fPIC -I/var/folders/c8/z52g4gc5679gygt8z0dx0jqm0000gn/T/tmp1kfkgxcf/tools/deps/include -I/var/folders/c8/z52g4gc5679gygt8z0dx0jqm0000gn/T/tmp1kfkgxcf/tools/deps/include/ncursesw -I/var/folders/c8/z52g4gc5679gygt8z0dx0jqm0000gn/T/tmp1kfkgxcf/tools/deps/include/uuid -Werror=unguarded-availability-new -Ilib/py-lmdb -Ibuild/lib -I/Users/codysilby/Downloads/InvokeAI/.venv/include -I/Users/codysilby/Downloads/InvokeAI/python/include/python3.10 -c build/lib/mdb.c -o build/temp.macosx-11.0-arm64-cpython-310/build/lib/mdb.o -DHAVE_PATCHED_LMDB=1 -UNDEBUG -w
      xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lmdb

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

### Contact Details

Discord: Codzsters#1454 or email cody@silby.co.nz

**Comment by danflynndesign** [comment]
I am also having this issue on my M1 mac.
Have tried with Python 3.10.9, made alias for pip and python to work with pip3 and python3, and even tried installing lmdb separately before the install.

Any suggestions?

**Comment by gsreeves** [comment]
> I am also having this issue on my M1 mac... 
> Any suggestions?
I used pyenv to bring sanity to managing python for projects. Create a folder to contain InvokeAI, cd there, then set it and forget it with "pyenv local [the best version for installing this project]".
I followed this guide: [https://www.freecodecamp.org/news/python-version-on-mac-update/](url)
The source: [https://github.com/pyenv/pyenv](url)

**Comment by pdwl** [comment]
update `xcode-select --install`
