### ISSUE TITLE
[bug]: its impossible to select location for the 'invokeai' directory

### ISSUE THREAD

**Issue by Alexander181177** [invoke-ai/InvokeAI#2224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### What happened?

When I try to install with "install.sh" the terminal ask me to select a path to install. i do that. and then it shows me this:

Select your preferred location for the 'invokeai' directory [/Users/cudopalovaleksandr]: /Users/cudopalovaleksandr/InvokeAI
/Users/cudopalovaleksandr/Downloads/InvokeAI-Installer/install.sh: line 124: python: command not found
cudopalovaleksandr@MacBook-Pro-Cudopalov ~ %

What to do?

### Screenshots

Last login: Wed Jan  4 18:14:54 on ttys000
cudopalovaleksandr@MacBook-Pro-Cudopalov ~ % /Users/cudopalovaleksandr/Downloads/InvokeAI-Installer/install.sh 
InvokeAI simple installer...

Some of the installation steps take a long time to run. Please be patient.
If the script appears to hang for more than 10 minutes, please interrupt with control-C and retry.
<Press any key to start the install>
Installing for osx-arm64
Python 3.10.9 found at /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10

Select your preferred location for the 'invokeai' directory [/Users/cudopalovaleksandr]: /Users/cudopalovaleksandr/InvokeAI
/Users/cudopalovaleksandr/Downloads/InvokeAI-Installer/install.sh: line 124: python: command not found
cudopalovaleksandr@MacBook-Pro-Cudopalov ~ %

**Comment by michaeldll** [comment]
I have the same issue. If I type "python" into my terminal, there's no issue.

**Comment by DottorMIT** [comment]
Same here. running MacPro 2019 MacOS 13.0.1

**Comment by mickr777** [comment]
I had to change line 124, from: "ROOTDIR=$(python" to: "ROOTDIR=$(python3" in the install.sh to get it to install see if that helps

**Comment by imba-pericia** [comment]
lxc container with opensuse tumbleweed has a similar installation error.

**Comment by imba-pericia** [comment]
> I had to change line 124, from: "ROOTDIR=$(python" to: "ROOTDIR=$(python3" in the install.sh to get it to install see if that helps

It worked, thx.

**Comment by Alexander181177** [comment]
> I had to change line 124, from: "ROOTDIR=$(python" to: "ROOTDIR=$(python3" in the install.sh to get it to install see if that helps

WORX!!! OMG! THANK YOU!)

**Comment by sgtlighttree** [comment]
This worked. Thanks so much!
