### ISSUE TITLE
[bug]: Unable to detect Python on computer, 

### ISSUE THREAD

**Issue by Bstoik** [invoke-ai/InvokeAI#2225]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS

Windows

### GPU

cpu

### What happened?

Tried installing the invokeAI. Stats "No python was detected on your system. Please install Python version 3.9.0 or higher. We recommend Python 3.10.9 from https://www.python.org/downloads/release/python-3109/"

I have the latest version of Python 311.1 and it was unable to detect it. Reinstalled and still unable to detect it.
Downloaded Python 3.10.9 like it was recommended and it still indicates that I don't have Python. 

Was unable to find anything that might resolve this issue. 

*Restarted system as well. 

### Screenshots

<img width="662" alt="Detection" src="https://user-images.githubusercontent.com/121962588/210602089-2c5145ed-69fd-43ed-9519-2644ce1ca3bd.PNG">
<img width="615" alt="Python" src="https://user-images.githubusercontent.com/121962588/210602104-de06fe53-ec61-48ec-9466-6b593eb915ec.PNG">

**Comment by hardgore** [comment]
same thing happened to me
got me install and uninstall python 3.10.9 more than 10 times
i decided to step back until they make it useable
