### ISSUE TITLE
ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11 ERROR: Could not find a version that satisfies the requirement torch==1.12.1 (from versions: none) ERROR: No matching distribution found for torch==1.12.1[bug]: 

### ISSUE THREAD

**Issue by rockstar3504** [invoke-ai/InvokeAI#2232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

amd

### What happened?

ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement torch==1.12.1 (from versions: none)
ERROR: No matching distribution found for torch==1.12.1

### Screenshots

![2023-01-05](https://user-images.githubusercontent.com/121702572/210731466-3f7ddf31-54da-403c-8ff4-2d93cc2ff6a0.png)

### Contact Details

rockforever25@gmail.com

**Comment by mickr777** [comment]
Do you happen to have python 3.11 installed?

**Comment by ShaguarWKL** [comment]
i got same error. Have 3.11 installed. looks like have to revert versions.

**Comment by mickr777** [comment]
Try remo ing python 3.11 and installing python 3.10.9, it looks like torch is not compatible with python3.11 on windows

**Comment by ShaguarWKL** [comment]
@mickr777 no need. I got past torch by just installing 3.10.9 without uninstalling 3.11.

**Comment by rockstar3504** [comment]
thank you everyone for your help, its work now ......

**Comment by saseiler** [comment]
I am having the same issue. I uninstalled my py 3.11 and was able to activate my environment, but when running install requirements, I am now encountering a different error...
"Fatal error in launcher: unable to create process...."

**Comment by nhanlt1** [comment]
> @mickr777 no need. I got past torch by just installing 3.10.9 without uninstalling 3.11.

thank, it's working now

**Comment by Bastrabun** [comment]
I have a similar issue on linux, debian testing (Python 3.11.2)

```
(InvokeAI) user@machine:~/invokeai$ pip install InvokeAI --use-pep517 --extra-index-url https://download.pytorch.org/whl/rocm5.4.2
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/rocm5.4.2
ERROR: Ignored the following versions that require a different python version: 2.2.4.5 Requires-Python <3.11,>=3.9; 2.2.4.6 Requires-Python <3.11,>=3.9; 2.2.4.7 Requires-Python <3.11,>=3.9; 2.2.5 Requires-Python <3.11,>=3.9; 2.3.0 Requires-Python <3.11,>=3.9; 2.3.0a0 Requires-Python <3.11,>=3.9; 2.3.0a1 Requires-Python <3.11,>=3.9; 2.3.0a2 Requires-Python <3.11,>=3.9; 2.3.0a3 Requires-Python <3.11,>=3.9; 2.3.0rc3 Requires-Python <3.11,>=3.9; 2.3.0rc4 Requires-Python <3.11,>=3.9; 2.3.0rc5 Requires-Python <3.11,>=3.9; 2.3.0rc6 Requires-Python <3.11,>=3.9; 2.3.0rc7 Requires-Python <3.11,>=3.9; 2.3.1 Requires-Python <3.11,>=3.9; 2.3.1.post1 Requires-Python <3.11,>=3.9; 2.3.1.post2 Requires-Python <3.11,>=3.9; 2.3.1rc4 Requires-Python <3.11,>=3.9; 2.3.2 Requires-Python <3.11,>=3.9; 2.3.2.post1 Requires-Python <3.11,>=3.9; 2.3.3 Requires-Python <3.11,>=3.9; 2.3.3rc1 Requires-Python <3.11,>=3.9; 2.3.4 Requires-Python <3.11,>=3.9; 2.3.4.post1 Requires-Python <3.11,>=3.9; 2.3.4a0 Requires-Python <3.11,>=3.9; 2.3.4rc1 Requires-Python <3.11,>=3.9
ERROR: Could not find a version that satisfies the requirement InvokeAI (from versions: none)
ERROR: No matching distribution found for InvokeAI
```

**Comment by AzeeemArshad** [comment]
Try removing Python 3.11 an do install Python 3.10.9, it looks like Torch isn't compatible with Python 3.11 on Windows

**Comment by CptRossarian** [comment]
Hello. Having the same problem.
Funny because some videos about installing SD Automatic1111 webui suggest Python 3.10.xxxx which I had installed until now. I used A1111 very shortly before skipping it in favour of ComfyUI portable, which had some of it's own solution for Python. Now I have returned to use A1111, not having touched Python with a finger, and I come to learn that I must downgrade from that.
Will do that of course, the sunken cost so far was just too much. But this is irritating as heck.

**Comment by Lokisinaryblender** [comment]
> Hello. Having the same problem. Funny because some videos about installing SD Automatic1111 webui suggest Python 3.10.xxxx which I had installed until now. I used A1111 very shortly before skipping it in favour of ComfyUI portable, which had some of it's own solution for Python. Now I have returned to use A1111, not having touched Python with a finger, and I come to learn that I must downgrade from that. Will do that of course, the sunken cost so far was just too much. But this is irritating as heck.
> 
> > You just must choose a specific version for your project in the idm.
> 
> @Lokisinaryblender can you hint where that would be for Automatic1111 ?

I am not sure for A1111. i was talking about VS code for Blender. you can change the python version inside the vs code in bottom right corner by clicking the 3.10.xxx or 3.11.xxx whatever the version it is showing until the error is disappear.

**Comment by alsjdnh** [comment]
3.11不行吗？3.11版本试了好多遍都这个问题，换3.10.9版本可以解决吗

**Comment by Lokisinaryblender** [comment]
I discovered another solution for Blender. While attempting to install the bpy module using pip in vs code, I encountered a version error. However, using the command pip install fake-bpy-module-4.0 successfully installed the required functionality, even on the latest Python versions like 3.11. https://pypi.org/project/fake-bpy-module-latest/

**Comment by Ebrahim-Ramadan** [comment]
I tried to install each lib individually with the version number specified, like `pip install opencv-python numpy==1.21 matplotlib Pillow cvlib`, it worked fine.
Python 3.11.0 on windows11
