### ISSUE TITLE
i can't find ( invoke.bat) file in D:\InvokeAI\invokeAI-src-installer-2.2.3-windows\invokeAI folder 

### ISSUE THREAD

**Issue by rockstar3504** [invoke-ai/InvokeAI#2237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

i can't find ( invoke.bat) file in D:\InvokeAI\invokeAI-src-installer-2.2.3-windows\invokeAI folder 

### Screenshots

![2023-01-05 (1)](https://user-images.githubusercontent.com/121702572/210848157-c1f5e74b-e579-4bdf-a58e-6aaf83782416.png)

### Contact Details

banglaraadda@gmail.com

**Comment by blessedcoolant** [comment]
We are on version 2.2.5 now. Please try that. A ton of installer issues have been fixed since the 2.2.3 release.
https://github.com/invoke-ai/InvokeAI/releases/tag/v2.2.5

**Comment by rockstar3504** [comment]
last time i try new version 2.2.5 thi 

 ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11 ERROR: Could not find a version that satisfies the requirement torch==1.12.1 (from versions: none) ERROR: No matching distribution found for torch==1.12.1  come

**Comment by rockstar3504** [comment]
> We are on version 2.2.5 now. Please try that. A ton of installer issues have been fixed since the 2.2.3 release. https://github.com/invoke-ai/InvokeAI/releases/tag/v2.2.5

last time i try new version 2.2.5 thi

ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11 ERROR: Could not find a version that satisfies the requirement torch==1.12.1 (from versions: none) ERROR: No matching distribution found for torch==1.12.1 come
