### ISSUE TITLE
[bug]: When I run install.bat I get an error message "The system cannot find the path specified. updating pip with "C:\Program Files\invokeai\.venv\Scripts\python".  I looked in the in the invokeai.venv directory, and there is no Scripts folder there. The bat file exits after this.

### ISSUE THREAD

**Issue by ParallaxMaster** [invoke-ai/InvokeAI#2238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

I'm using the automated install for Windows. When I run install.bat I get an error message "The system cannot find the path specified. updating pip with "C:\Program Files\invokeai\.venv\Scripts\python".  I looked in the in the invokeai.venv directory, and there is no Scripts folder there. The bat file exits after this.

I believe I have the correct version of Python installed:
Microsoft Windows [Version 10.0.19044.2364]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Amado>python --version
**Python 3.9.10**

C:\Users\Amado>pip --version
**pip 22.2.1** from C:\Users\Amado\AppData\Local\Programs\Python\Python310\lib\site-packages\pip (python 3.10)

Attached is a copy of the batch file run.

C:\Users\Amado>
[Automated Invokeai install fails.txt](https://github.com/invoke-ai/InvokeAI/files/10355035/Automated.Invokeai.install.fails.txt)

### Contact Details

asantiago@cox.net

**Comment by sbrepo2022** [comment]
As a temporary solution, you can simply create a .venv/Scripts folder and copy the file python.exe from the folder .venv/bin to .venv/Scripts
