### ISSUE TITLE
invoke.bat Cmd window close automatically [bug]: 

### ISSUE THREAD

**Issue by rockstar3504** [invoke-ai/InvokeAI#2241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What happened?

after Instal all when I try to open invoke.bat cmd it asks me 1.2.3 number I take 2 after that download some more files and ask me a ticket number, Then I Access Tokens from Hugging Face,  after all, dan cmd window close automatically.

### Contact Details

banglaraadda@gmail.com

**Comment by rockstar3504** [comment]
You appear to have a missing or misconfigured model file(s).
   The script will now exit and run configure_invokeai.py to help fix the problem.
   After reconfiguration is done, please relaunch invoke.py.

**Comment by Enot-Racoon** [comment]
I have same problem on windows 10
