### ISSUE TITLE
[bug]: updater-v2.2.5 not install

### ISSUE THREAD

**Issue by Komachijh** [invoke-ai/InvokeAI#2245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What happened?

When I trying to install the updater -v2.2.5  I have this message

<'latest' is not a known branch name or tag. Please check the version and try again.
"Press any key to continue">

not sure what is my latest version, I think v.2.2.5-rc4

**Comment by Neverdusk** [comment]
Chiming in to say I have the same issue. I replaced the update file as instructed, but received the same error.

**Comment by Komachijh** [comment]
I solved just delete the invokeai dir an leave only my outputs and install
again as was the first time. Now works!

Il lun 9 gen 2023, 9:48 PM Neverdusk ***@***.***> ha scritto:
