### ISSUE TITLE
[bug]: Inpainting dont work whit all models whit images not generated by ai

### ISSUE THREAD

**Issue by 0TREV0R** [invoke-ai/InvokeAI#2247]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS

Windows

### GPU

cpu

### VRAM

8

### What happened?

I try to enlarge images and when I finish doing it the image comes out blurry and with a yellow and black exclamation mark and when I use the impainting model it hangs without doing anything
![merged_canvas be4ce213](https://user-images.githubusercontent.com/121357491/211064049-0096d91b-d07a-433b-b89a-018049544841.png)

### Screenshots

![merged_canvas be4ce213](https://user-images.githubusercontent.com/121357491/211064030-ffe5e6ec-d073-42f7-ab22-49ff97e6a4c8.png)

### Additional context

before it worked fine, i didn't touch anything
when i use the model of inpainting 1.5 in invoke.bat show this
Could not generate image.
>> Usage stats:
>>   0 image(s) generated in 1.97s
>>   Max VRAM used for this generation: 5.55G. Current VRAM utilization: 5.13G
>>   Max VRAM used since script start:  5.55G

**Comment by 0TREV0R** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### OS
> Windows
> 
> ### GPU
> cpu
> 
> ### VRAM
> 8
> 
> ### What happened?
> I try to enlarge images and when I finish doing it the image comes out blurry and with a yellow and black exclamation mark and when I use the impainting model it hangs without doing anything ![merged_canvas be4ce213](https://user-images.githubusercontent.com/121357491/211064049-0096d91b-d07a-433b-b89a-018049544841.png)
> 
> ### Screenshots
> ![merged_canvas be4ce213](https://user-images.githubusercontent.com/121357491/211064030-ffe5e6ec-d073-42f7-ab22-49ff97e6a4c8.png)
> 
> ### Additional context
> before it worked fine, i didn't touch anything
> 
> ### Contact Details
> _No response_

**Comment by martjay** [comment]
I have encountered this error many times, I do not know if the webui itself set up any underage mechanism, I want to know how to remove the restrictions, I do not want to see the yellow exclamation mark

**Comment by 0TREV0R** [comment]
the problem is active

**Comment by AAlmustafa** [comment]
I also have the same problem, which is occurring today a lot more frequently than before.

**Comment by martjay** [comment]
> I had the same problem. The reason it was happening to me is because i was using an image with an incorrect dimension. so i changed the image i was using for ( image to image, and unified canvas modes ) to be 512px by 512px and now everything is working just fine. ( no more yellow triangles ) @0TREV0R @martjay i hope this helps

Not all images are suitable for square composition. I have never encountered this strange problem when using SD webui

**Comment by nightt5879** [comment]
> I have encountered this error many times, I do not know if the webui itself set up any underage mechanism, I want to know how to remove the restrictions, I do not want to see the yellow exclamation mark

gays, Have you solved it now?

**Comment by egoegoegoegoego** [comment]
on the latest 3.0.1post3 it doesn't accept any inpainting models. normal models work fine but switching to an inpaint model and get this message:
[2023-08-05 03:47:39,756]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "C:\Users\TCS\invokeai\.venv\lib\site-packages\invokeai\app\services\processor.py", line 86, in __process
    outputs = invocation.invoke(
  File "C:\Users\TCS\invokeai\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\TCS\invokeai\.venv\lib\site-packages\invokeai\app\invocations\latent.py", line 334, in invoke
    unet_info = context.services.model_manager.get_model(
  File "C:\Users\TCS\invokeai\.venv\lib\site-packages\invokeai\app\services\model_manager_service.py", line 364, in get_model
    model_info = self.mgr.get_model(
  File "C:\Users\TCS\invokeai\.venv\lib\site-packages\invokeai\backend\model_management\model_manager.py", line 491, in get_model
    model_context = self.cache.get_model(
  File "C:\Users\TCS\invokeai\.venv\lib\site-packages\invokeai\backend\model_management\model_cache.py", line 200, in get_model
    model = model_info.get_model(child_type=submodel, torch_dtype=self.precision)
  File "C:\Users\TCS\invokeai\.venv\lib\site-packages\invokeai\backend\model_management\models\base.py", line 286, in get_model
    raise Exception(f"Failed to load {self.base_model}:{self.model_type}:{child_type} model")
Exception: Failed to load sd-1:main:unet model

[2023-08-05 03:47:39,761]::[InvokeAI]::ERROR --> Error while invoking:
Failed to load sd-1:main:unet model
