### ISSUE TITLE
[bug]: installer bat issue

### ISSUE THREAD

**Issue by Mremenar** [invoke-ai/InvokeAI#2253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

Win10 machine.  ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement torch==1.12.1 (from versions: none)
ERROR: No matching distribution found for torch==1.12.1
Requirements installation failed. See above for errors and check https://invoke-ai.github.io/InvokeAI/installation/INSTALL_AUTOMATED/#troubleshooting for potential solutions.
The installer will exit now.
Press any key to continue . . .

So I tried reinstalling 3.7.9, and then "repaired" 3.11.1.
Re-runnning the install.bat, I get:
***** Checking and Updating Python *****
Your version of Python is too low. You need at least 3.9.0 but you have 3.7.9. We recommend Python 3.10.9 from https://www.python.org/downloads/release/python-3109/
The installer will exit now.
Press any key to continue . . .

### Contact Details

marc.remenar@yahoo.com

**Comment by gogurtenjoyer** [comment]
InvokeAI isn't currently compatible with python 3.11 because of the pytorch version it's using (maybe other dependencies as well, I'm not sure).

Please try installing 3.10.9 from the link provided in what you've pasted above, making sure to check 'add python.exe to PATH' when doing so.

**Comment by Mremenar** [comment]
I did as requested, removing the latest Python and installing the 3.10.9. as requested.  
After much wrangling with the Huggingface tokens, the install appears to have completed, but the actual use will not.
When I run the "Unified Canvas" it will not ever complete the task.  The first attempt appeared to be asking too much, as did the second.  I scaled back the third attempt with a different picture.  I'm attempting to extend the bottom of a picture  by a third.

My Virtual Memory is 24.7 GB, My Video Card is a 16GB CUDA card, NVIDIA GeForce GTX 1660 Ti

OS Name	Microsoft Windows 10 Home
Version	10.0.19045 Build 19045
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	D5000
System Manufacturer	Micro-Star International Co., Ltd.
System Model	MS-7B79
System Type	x64-based PC
System SKU	To be filled by O.E.M.
Processor	AMD Ryzen 5 2600X Six-Core Processor, 3600 Mhz, 6 Core(s), 12 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. A.70, 1/23/2019
SMBIOS Version	2.8
Embedded Controller Version	255.255
BIOS Mode	Legacy
BaseBoard Manufacturer	Micro-Star International Co., Ltd.
BaseBoard Product	X470 GAMING PLUS (MS-7B79)
BaseBoard Version	2.0
Platform Role	Desktop
Secure Boot State	Unsupported
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume9
Locale	United States
Hardware Abstraction Layer	Version = "10.0.19041.2251"
User Name	DESTROYOBOT5000\Dad
Time Zone	Pacific Standard Time
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	15.9 GB
Available Physical Memory	7.28 GB
Total Virtual Memory	24.7 GB
Available Virtual Memory	3.93 GB
Page File Space	8.73 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Not enabled
Device Encryption Support	Reasons for failed automatic device encryption: TPM is not usable, PCR7 binding is not supported, Hardware Security Test Interface failed and device is not Modern Standby, Un-allowed DMA capable bus/device(s) detected, TPM is not usable
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	No
Hyper-V - Data Execution Protection	Yes

Do you want to generate images using the
1. command-line
2. browser-based UI
3. open the developer console
Please enter 1, 2 or 3: 2
Starting the InvokeAI browser-based UI..
>> Patchmatch initialized
* Initializing, be patient...
>> Initialization file C:\Users\Dad\InvokeAI\invokeai\invokeai.init found. Loading...
>> InvokeAI runtime directory is "C:\Users\Dad\InvokeAI\invokeai"
>> GFPGAN Initialized
>> CodeFormer Initialized
>> ESRGAN Initialized
>> Using device_type cuda
>> Current VRAM usage:  0.00G
>> Scanning Model: stable-diffusion-1.5
>> Model Scanned. OK!!
>> Loading stable-diffusion-1.5 from C:\Users\Dad\InvokeAI\invokeai\models\ldm\stable-diffusion-v1\v1-5-pruned-emaonly.ckpt
   | LatentDiffusion: Running in eps-prediction mode
   | DiffusionWrapper has 859.52 M params.
   | Making attention of type 'vanilla' with 512 in_channels
   | Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
   | Making attention of type 'vanilla' with 512 in_channels
   | Using more accurate float32 precision
   | Loading VAE weights from: C:\Users\Dad\InvokeAI\invokeai\models\ldm\stable-diffusion-v1\vae-ft-mse-840000-ema-pruned.ckpt
>> Model loaded in 26.34s
>> Max VRAM used to load the model: 4.28G
>> Current VRAM usage:4.28G
>> Current embedding manager terms: *
>> Setting Sampler to k_lms

* --web was specified, starting web server...
>> Initialization file C:\Users\Dad\InvokeAI\invokeai\invokeai.init found. Loading...
>> Started Invoke AI Web Server!
>> Default host address now 127.0.0.1 (localhost). Use --host 0.0.0.0 to bind any address.
>> Point your browser at http://127.0.0.1:9090
>> System config requested
>> Image generation requested: {'prompt': 'space pirate, digital art, elegant, ((intricate)), ((highly detailed)), (((depth of field))), ((professionally color graded)), highly intricate, concept art, award winning photograph, soft cinematic lighting, sharp focus, 8k resolution wallpaper, hyperrealistic, perfect composition, soft cinematic lighting, octane render, smooth, denoise, art by artgerm and greg rutkowski and alphonse mucha', 'iterations': 1, 'steps': 50, 'cfg_scale': 7.5, 'threshold': 0, 'perlin': 0, 'height': 512, 'width': 512, 'sampler_name': 'k_lms', 'seed': 534563495, 'progress_images': False, 'progress_latents': True, 'save_intermediates': 5, 'generation_mode': 'unifiedCanvas', 'init_mask': 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABAAAAAVACAYAAADWMi...', 'fit': False, 'strength': 0.75, 'invert_mask': False, 'bounding_box': {'x': 0, 'y': 0, 'width': 1024, 'height': 1344}, 'init_img': 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABAAAAAVACAYAAADWMi...', 'inpaint_width': 1024, 'inpaint_height': 1344, 'seam_size': 96, 'seam_blur': 16, 'seam_strength': 0.7, 'seam_steps': 10, 'tile_size': 32, 'infill_method': 'patchmatch', 'force_outpaint': False, 'variation_amount': 0}
ESRGAN parameters: False
Facetool parameters: False
{'prompt': 'space pirate, digital art, elegant, ((intricate)), ((highly detailed)), (((depth of field))), ((professionally color graded)), highly intricate, concept art, award winning photograph, soft cinematic lighting, sharp focus, 8k resolution wallpaper, hyperrealistic, perfect composition, soft cinematic lighting, octane render, smooth, denoise, art by artgerm and greg rutkowski and alphonse mucha', 'iterations': 1, 'steps': 50, 'cfg_scale': 7.5, 'threshold': 0, 'perlin': 0, 'height': 512, 'width': 512, 'sampler_name': 'k_lms', 'seed': 534563495, 'progress_images': False, 'progress_latents': True, 'save_intermediates': 5, 'generation_mode': 'unifiedCanvas', 'init_mask': <PIL.Image.Image image mode=RGBA size=1024x1344 at 0x15CD46B66B0>, 'fit': False, 'strength': 0.75, 'invert_mask': False, 'bounding_box': {'x': 0, 'y': 0, 'width': 1024, 'height': 1344}, 'init_img': <PIL.Image.Image image mode=RGBA size=1024x1344 at 0x15CD4748E50>, 'inpaint_width': 1024, 'inpaint_height': 1344, 'seam_size': 96, 'seam_blur': 16, 'seam_strength': 0.7, 'seam_steps': 10, 'tile_size': 32, 'infill_method': 'patchmatch', 'force_outpaint': False, 'variation_amount': 0}
>> using provided input image of size 1024x1344
>> This input is larger than your defaults. If you run out of memory, please use a smaller image.
>> using provided input image of size 1024x1344
>> Using recommended DDIM sampler for inpainting.
Traceback (most recent call last):
  File "C:\Users\Dad\InvokeAI\invokeai\.venv\lib\site-packages\ldm\generate.py", line 492, in prompt2image
    results = generator.generate(
  File "C:\Users\Dad\InvokeAI\invokeai\.venv\lib\site-packages\ldm\invoke\generator\base.py", line 61, in generate
    make_image = self.get_make_image(
  File "C:\Users\Dad\InvokeAI\invokeai\.venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Dad\InvokeAI\invokeai\.venv\lib\site-packages\ldm\invoke\generator\inpaint.py", line 268, in get_make_image
    self.model.encode_first_stage(init_image)
  File "C:\Users\Dad\InvokeAI\invokeai\.venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Dad\InvokeAI\invokeai\.venv\lib\site-packages\ldm\models\diffusion\ddpm.py", line 1250, in encode_first_stage
    return self.first_stage_model.encode(x)
  File "C:\Users\Dad\InvokeAI\invokeai\.venv\lib\site-packages\ldm\models\autoencoder.py", line 414, in encode
    h = self.encoder(x)
  File "C:\Users\Dad\InvokeAI\invokeai\.venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Dad\InvokeAI\invokeai\.venv\lib\site-packages\ldm\modules\diffusionmodules\model.py", line 497, in forward
    h = self.down[i_level].block[i_block](hs[-1], temb)
  File "C:\Users\Dad\InvokeAI\invokeai\.venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Dad\InvokeAI\invokeai\.venv\lib\site-packages\ldm\modules\diffusionmodules\model.py", line 134, in forward
    h = self.norm1(x)
  File "C:\Users\Dad\InvokeAI\invokeai\.venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Dad\InvokeAI\invokeai\.venv\lib\site-packages\torch\nn\modules\normalization.py", line 272, in forward
    return F.group_norm(
  File "C:\Users\Dad\InvokeAI\invokeai\.venv\lib\site-packages\torch\nn\functional.py", line 2516, in group_norm
    return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: CUDA out of memory. Tried to allocate 672.00 MiB (GPU 0; 6.00 GiB total capacity; 4.66 GiB already allocated; 0 bytes free; 4.77 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

>> Could not generate image.
>> Usage stats:
>>   0 image(s) generated in 54.96s
>>   Max VRAM used for this generation: 5.01G. Current VRAM utilization: 4.28G
>>   Max VRAM used since script start:  5.01G

**Comment by gogurtenjoyer** [comment]
Please check the hardware requirements in the documentation; unfortunately the GTX 1660 isn't recommended for InvokeAI.

**Comment by Mremenar** [comment]
If I understand what you're saying, it's a requirement to have a CUDA card, but you don't support one of the most popular CUDA cards manufactured?
I tried resizing the original image down to 512 x 704.  It's now producing results, albeit very weird results, but it is producing results.

**Comment by gogurtenjoyer** [comment]
There's currently either a hardware or driver bug with those cards; it has nothing to do with InvokeAI - essentially, they don't support FP16 properly, and since they have very low VRAM compared to newer cards, they run out of memory quite easily (as they have to use about twice as much with FP32). There's been talk over in the pytorch repo issues about the fault lying with cudnn, and there were supposedly updates to address it, but the results seem to be mixed. Things might work better with those cards and InvokeAI in the future, but nobody here can say for sure.

**Comment by Mremenar** [comment]
Is it the bug that makes the AI make the weird choices when extending a picture?  
(I'm trying to use InvokeAI to build out a picture of a women generated with a different AI that caused one of her legs to be severely deformed.  Clipping the deformation from the picture and running InvokeAI...well let's just say that Invoke doesn't seem to grasp human anatomy very well.  I've tried nine attempts so far with all of them creating weird mangrove root distortions where the other leg should be.  
If I was going for an acid-trip-hippy-picture-lost-in-Salvador-Dali-land, than all the results would be "groovy, man!"
But since I'm trying for photorealism-- not really hitting the mark, if you know what I mean.

**Comment by gogurtenjoyer** [comment]
Nope, unrelated.
