### ISSUE TITLE
[bug]: Web settings are not kept, resets on each new start

### ISSUE THREAD

**Issue by TheBarret** [invoke-ai/InvokeAI#2263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

4GB

### What happened?

The version 2.2.5 web front-end used to keep the settings of the last session, that is not the case any more.

**Comment by RadTechDad** [comment]
This is happening to me too on the Mac.

I had 2.2.4 installed, tried upgrading to 2.2.5, but it messed everything up. Deleted it all, did a clean install of 2.2.5, and now this happens.

I installed to "/Users/<username>/invokeai", However, every run after the initial run fails. I see the following error:
`Starting the InvokeAI browser-based UI..
* Initializing, be patient...
>> InvokeAI 2.2.5
>> InvokeAI runtime directory is "/Users/<username>/invokeai/invokeai"
## NOT FOUND: GFPGAN model not found at /Users/<username>/invokeai/invokeai/models/gfpgan/GFPGANv1.4.pth
>> GFPGAN Disabled
## NOT FOUND: CodeFormer model not found at /Users/<username>/invokeai/invokeai/models/codeformer/codeformer.pth
>> CodeFormer Disabled
>> ESRGAN Initialized

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
   You appear to have a missing or misconfigured model file(s).
   The script will now exit and run configure_invokeai.py to help fix the problem.
   After reconfiguration is done, please relaunch invoke.py.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
configure_invokeai is launching....

Loading Python libraries...

Welcome to InvokeAI. This script will help download the Stable Diffusion weight files
and other large models that are needed for text to image generation. At any point you may interrupt
this program and resume later.

** INITIALIZING INVOKEAI RUNTIME DIRECTORY **
Select the default directory for image outputs [invokeai/outputs]: invokeai/outputs
Goodbye! Come back soon.`

So it seems that somewhere an extra "invokeai" is being placed where it's not supposed to be.

**Comment by Aamir3d** [comment]
Happening to me with the 2.2.5 latest pull - even when you refresh the web GUI, the settings aren't saved.

**Comment by Aamir3d** [comment]
> Happening to me with the 2.2.5 latest update - even when you refresh the web GUI, the settings aren't saved.

@TheBarret 
Resolved this for Windows.
The WebUI settings would be saved in Edge, but not Chrome
On some digging, found that the Script Block extension for Chrome had a cache error with 127.0.0.1 - whitelisting again and saving it works in Chrome now.
Please check any extensions to see if the site or scripting is blocked.

**Comment by TheBarret** [comment]
> 

There was a moment where Firefox wouldn't load the page (blank) and then when i tried with edge, it did load but each time it reset the form fields. Im a bit puzzled.

**Comment by Aamir3d** [comment]
> > 
> 
> There was a moment where Firefox wouldn't load the page (blank) and then when i tried with edge, it did load but each time it reset the form fields. Im a bit puzzled.

Any extensions? What is the system RAM? I found that even 16GB isn't enough if you're swapping models.

**Comment by TheBarret** [comment]
I switched over to Automatic1111, never had the problem ever again.
