### ISSUE TITLE
[bug]: Building env in conda (latest miniconda) on colab and getting this error

### ISSUE THREAD

**Issue by matyugovich** [invoke-ai/InvokeAI#2264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

16

### What happened?

When building environment in miniconda on colab from environment-lin-cuda.yml i get this error.

Running command git clone --filter=blob:none --quiet https://github.com/invoke-ai/PyPatchMatch /tmp/pip-install-bjpfxgtd/pypatchmatch_cdb9d4b3f65d48de8c9a3e58222ebcb6
ERROR: file:///content/drive/MyDrive/InvokeAI/environments-and-requirements (from -r /content/drive/MyDrive/InvokeAI/environments-and-requirements/condaenv.v7l8ukul.requirements.txt (line 32)) does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.failed

CondaEnvException: Pip failed

**Comment by faraday** [comment]
This PR is relevant (to fix PyPatchMatch):
https://github.com/invoke-ai/PyPatchMatch/pull/7

You could temporarily use the PR branch to work around the issue.
