### ISSUE TITLE
[bug]: 'GFPGAN' object has no attribute 'gfpgan'

### ISSUE THREAD

**Issue by Hsm2021** [invoke-ai/InvokeAI#2265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

gfpgan and codformer not working

### Screenshots

![Shot 0006](https://user-images.githubusercontent.com/94809545/211169344-cfb3fce7-30cc-4944-9eba-c9e1a4fa2785.png)
![Shot 0007](https://user-images.githubusercontent.com/94809545/211169348-21cf7c35-3d1a-43fd-a86b-41c21f8e3ee6.png)
![Shot 0008](https://user-images.githubusercontent.com/94809545/211169349-14ade1d2-b724-432d-a303-46ef0c9dfd92.png)

### Additional context

i have gfpgan and codformer in models location and configure_invokeai.py says its installed but not working .
This problem happened after the last update 2.2.5

`2023-01-07T23:50:03+0330: Face restoration (gfpgan) requested: {"file":"outputs/000494.9ca3c7be.4151641189.postprocessed.png","facetool_strength":0.8}`

`2023-01-07T23:50:03+0330: Server error: 'GFPGAN' object has no attribute 'gfpgan'`

**Comment by Hsm2021** [comment]
pain

**Comment by dhlsam** [comment]
same problem

**Comment by DawidGut** [comment]
Same problem :)

**Comment by DawidGut** [comment]
@Hsm2021 How did you solve this problem? :)

**Comment by andyvirt** [comment]
Same issue - selecting gfpgan or codeformer in face restoration I just get an error.

**Comment by Zenshinzo** [comment]
same as well. any update?

**Comment by Hsm2021** [comment]
I closed it just because I thought no one would help me . i fixed this in old version I don't remember how , now i downloaded new version and i cant find Previous files and i gived this error again for ever :|
