### ISSUE TITLE
a problem with Protogen v2.2?

### ISSUE THREAD

**Issue by washinoboku** [invoke-ai/InvokeAI#2271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What happened?

> File "T:\IA\invokeai\.venv\lib\site-packages\eventlet\hubs\hub.py", line 476, in fire_timers
>     timer()
>   File "T:\IA\invokeai\.venv\lib\site-packages\eventlet\hubs\timer.py", line 59, in __call__
>     cb(*args, **kw)
>   File "T:\IA\invokeai\.venv\lib\site-packages\eventlet\greenthread.py", line 221, in main
>     result = function(*args, **kwargs)
>   File "T:\IA\invokeai\.venv\lib\site-packages\eventlet\wsgi.py", line 837, in process_request
>     proto.__init__(conn_state, self)
>   File "T:\IA\invokeai\.venv\lib\site-packages\eventlet\wsgi.py", line 352, in __init__
>     self.finish()
>   File "T:\IA\invokeai\.venv\lib\site-packages\eventlet\wsgi.py", line 751, in finish
>     BaseHTTPServer.BaseHTTPRequestHandler.finish(self)
>   File "C:\Users\Tu\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 811, in finish
>     self.wfile.close()
>   File "C:\Users\Tu\AppData\Local\Programs\Python\Python310\lib\socket.py", line 723, in write
>     return self._sock.send(b)
>   File "T:\IA\invokeai\.venv\lib\site-packages\eventlet\greenio\base.py", line 401, in send
>     return self._send_loop(self.fd.send, data, flags)
>   File "T:\IA\invokeai\.venv\lib\site-packages\eventlet\greenio\base.py", line 388, in _send_loop
>     return send_method(data, *args)
> **ConnectionAbortedError: [WinError 10053] Se ha anulado una conexión establecida por el software en su equipo host**
> 

Hey guys, I don't know much about coding, but I noticed something and I'm wondering if it could be a problem with Protogen v2.2.

### Additional context

.

**Comment by megachomba** [comment]
i have same issue
