### ISSUE TITLE
[bug]: High Res Optimization turns off after going in to img2img

### ISSUE THREAD

**Issue by NMitchell24** [invoke-ai/InvokeAI#2272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24gb

### What happened?

1. In WebUI turn on high Res Optimization
2. Generate an Image
3. Send to Img2Img
4. Run another generation
5. Go back to txt2img
6. High Res Optimization is now mysteriously turned off.

**Comment by n00mkrad** [comment]
Pretty sure High-Res Fix only works with txt2img, so img2img auto-disables it. Just my theory.
