### ISSUE TITLE
[bug]: Canvas Scale in the Unified Canvas getting stuck on strange values

### ISSUE THREAD

**Issue by StrawberryBunny** [invoke-ai/InvokeAI#2277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What happened?

When working with an image that doesn't fit inside the view area conformably the 'canvas scale' gets set to a percentage less than 100% and it gets stuck there.
You can still zoom in and out but mouse wheel returns to the original percentage, not to 100%.
Reset View also returns to the original percentage, not to 100%.

On a 1080p monitor with Chrome 
- a 512x768 image will set it to 98%
- a 512x832 image will set it to 92%

This happens when sending an image to the canvas or when you generate one in the canvas and then hit Reset View.

**Comment by psychedelicious** [comment]
This is the canvas viewing scale - it doesn't affect generation. The intention is that you can quickly reset the view to see the whole canvas.

In #2436, I've updated the button so that a double-click sets the view to 100%. 

I think this is the best of both worlds but happy for other suggestions.

**Comment by psychedelicious** [comment]
Yeah good suggestions. I'll get a number entry added and test some ways to do more precise zooming. 

The canvas was built on a laptop with trackpad which allows for very small scrolling adjustments - the stepped scroll intervals you get with a mouse never really crossed my mind.
