### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by Florencia007** [invoke-ai/InvokeAI#2280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### VRAM

4GB

### What happened?

Hi, I did all the installation with no problem but when running the browser version I get this error: Any idea how to fix it? Thanks

ImportError: dlopen(/Users/winter/invokeai/.venv/lib/python3.10/site-packages/cv2/cv2.abi3.so, 2): Symbol not found: _VTRegisterSupplementalVideoDecoderIfAvailable
  Referenced from: /Users/winter/invokeai/.venv/lib/python3.10/site-packages/cv2/.dylibs/libavcodec.59.37.100.dylib (which was built for Mac OS X 11.0)
  Expected in: /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
 in /Users/winter/invokeai/.venv/lib/python3.10/site-packages/cv2/.dylibs/libavcodec.59.37.100.dylib

**Comment by Florencia007** [comment]
I have MAC osx 10.15 catalina so that for sure can be the problem, but how do I fix it? I don't want to upgrade

**Comment by aidanhiggins** [comment]
I have the same problem. I assume the issue is that we don't meet the minimum requirements:
_An NVIDIA-based graphics card with 4 GB or more VRAM memory._

**Comment by schspa** [comment]
try this: the macos system seems too old for the new opencv package
`pip3 install opencv-python==4.6.0.66`

**Comment by aidanhiggins** [comment]
Thanks @schspa. I already had that version of opencv-python installed.

**Comment by HackWorldMoon** [comment]
> try this: the macos system seems too old for the new opencv package `pip3 install opencv-python==4.6.0.66`

This works ok for me in MAC OSX 10.15.7 Catalina

**Comment by cris-spreng** [comment]
This is how I solved it on Catalina 10.15.7 with Python 3.10

I had opencv 4.6.0.66 installed in /usr/local/lib/python3.10/site-packages/cv2/
And invokeAI was using version 4.7 located in /Users/myUser/invokeai/.venv/lib/python3.10/site-packages/cv2/
So I removed that version and copied the folder to invokeAI location

`$ rm -rf /Users/myUser/invokeai/.venv/lib/python3.10/site-packages/cv2
$ cp -r /usr/local/lib/python3.10/site-packages/cv2 /Users/myUser/invokeai/.venv/lib/python3.10/site-packages/`

And Voilà, works like a charm
Of course replace "myUser" with your user folder

**Comment by aidanhiggins** [comment]
@cris-spreng you are a legend!
That works perfectly for me. Thank you!

**Comment by Ahkari** [comment]
> This is how I solved it on Catalina 10.15.7 with Python 3.10
> 
> I had opencv 4.6.0.66 installed in /usr/local/lib/python3.10/site-packages/cv2/ And invokeAI was using version 4.7 located in /Users/myUser/invokeai/.venv/lib/python3.10/site-packages/cv2/ So I removed that version and copied the folder to invokeAI location
> 
> `$ rm -rf /Users/myUser/invokeai/.venv/lib/python3.10/site-packages/cv2 $ cp -r /usr/local/lib/python3.10/site-packages/cv2 /Users/myUser/invokeai/.venv/lib/python3.10/site-packages/`
> 
> And Voilà, works like a charm Of course replace "myUser" with your user folder

thank you, its workd!

**Comment by ShortCat100** [comment]
@cxpreng thanks so much. I can't believe it. I spent two weeks trying to figure out. and took 3 days on your post ..... as a totally none-IT girl.
I did it. you rock!
