### ISSUE TITLE
[bug]: invokeai/invoke.sh: line 24: 10946 Killed: 9               .venv/bin/python .venv/bin/invoke.py --web $*

### ISSUE THREAD

**Issue by sami196515** [invoke-ai/InvokeAI#2283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cuda

### What happened?

Trying to run invoke.sh in terminal but I get this error after it loads: invokeai/invoke.sh: line 24: 10946 Killed: 9               .venv/bin/python .venv/bin/invoke.py --web $*

Terminal ends after this.

MacOs 13.0 on Mac m1 8gb latest, python installed

**Comment by sami196515** [comment]
I deleted the invokeai.init file, how can I get it back? :D I thought it would come back after running invoke.sh but it didn't..

**Comment by lstein** [comment]
It should run fine without the file.
