### ISSUE TITLE
[enhancement]: Face Restoration/Upscaling files in folder

### ISSUE THREAD

**Issue by mcbexx** [invoke-ai/InvokeAI#2284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

This is probably already on the to do list for the postprocessing section of the WebUI, but in any case:

I can imagine a lot of users run prompts at a lower resolution first, select their favourites and then fix them up with ERSGAN/GFPGAN.

It would be great if batches of files or whole folders could be passed through the "fixing" process of either or/both applying face restoration and upscaling to existing files. Unless I am missing something, this currently needs to be done manually by either selecting a single image in the WebUI and clicking the required buttons at the top of the viewer OR by passing a single file to the !fix command in the CLI.

Using the WebUI for this would probably require a way to tag multiple files in the thumbnail panel. For the CLI, the !fix command would need to be able to either parse a textfile with the path/names of the files to be fixed, similar to "reading prompts from file", or be able to parse a folder path to all files in need of fixing and apply it to all files in the folder (with an optional output folder parameter).

**Comment by Aamir3d** [comment]
Good idea to the issue I posted to add upscalers, this can be part of the Post processing GUI
1. Post process batch of images
2. Img2Img batch of images, and run an add detail upscale to save time

https://github.com/invoke-ai/InvokeAI/issues/2254
