### ISSUE TITLE
[bug]: WebUI does not serve to the browser (ERR_EMPTY_RESPONSE)

### ISSUE THREAD

**Issue by Riccorbypro** [invoke-ai/InvokeAI#2285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

8GB

### What happened?

Last night, I was able to access my locally running InvokeAI instance (running through WSL2) both on the host PC and through the network. This morning, I get an `ERR_EMPTY_RESPONSE` from Chrome when trying to visit the WebUI. This is different from the error I would get if the WebUI was not running (`ERR_CONN_REFUSED`), so the UI is definitely at least being hit, but it returns nothing to display.

I am using InvokeAI to run a Discord bot ([ausbitbank/stable-diffusion-discord-bot](github.com/ausbitbank/stable-diffusion-discord-bot)) and its worth noting that when the bot receives a request and manually POSTs the `generateImage` endpoint, the system picks it up and renders out an image.

I have tried:
- restarting the WSL system
- restarting the host computer
- removing and re-adding the firewall exclusions on Windows' side (likely to not have an effect, but worth doing)
- removing `invokeai.init` and recreating it using `invoke.sh`
- removing the `--bind 0.0.0.0` and attempting to access through `localhost` instead

All of these still result in an `ERR_EMPTY_RESPONSE` being served from the WebUI. At this point I'd consider the nuclear option of deleting and reinstalling, but I'd rather not have to redownload all the models.

**Comment by leog91** [comment]
Did you have a windows update lately?
I think it's a problem related, firewall or something, I can't curl a web app from windows (localhost).

**Comment by Riccorbypro** [comment]
> Did you have a windows update lately?

That's an interesting thought. I do run my personal rig on the Windows 11 Insider Beta (I have run my personal machines on Insider previews since before Windows 8's release). So updates are pretty frequent, but its rare that an update others get on GA builds break stuff for me at that time, since I've typically been running on that update for months or more. But I did receive an update a few days ago. Will go look up the KB and see if maybe MS changed anything networking-related.

**Comment by Riccorbypro** [comment]
Interesting, so it seems that the update I received a few days ago was simply an enablement package for new features in testing. I'd been running build 22621 since last year, and I see the only difference between 22621 and 22623 is new cosmetic features. There were 3 potentially network-related fixes made, but those were consistent across releases apparently.

https://blogs.windows.com/windows-insider/2022/09/29/announcing-windows-11-insider-preview-build-22621-730-and-22623-730/

**Comment by IgnatBulychov** [comment]
I got this issue, when I run container in WSL. After I tryed remove container and volume (i have no any data earlear), turn on VPN and run docker again - and it works!

In container logs a saw line:

`Installing external dependencies of functions and tools...`

before it is not shown
