### ISSUE TITLE
[bug]: Ram Usage

### ISSUE THREAD

**Issue by NYCAri** [invoke-ai/InvokeAI#2286]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

64

### What happened?

I have a Nvidia RTX 4090 and 64 Gigs of Ram on my computer yet I am getting the following error, 

" Could not generate image.
>> Usage stats:
>>   0 image(s) generated in 0.32s
>>   Max VRAM used for this generation: 2.17G. Current VRAM utilization: 2.17G
>>   Max VRAM used since script start:  17.29G"

And the program just doesn't want to generate anything now. Also the generation is taking really slow despite running on a super computer, is there anyway I can set the program to take full advantage of my system?

### Contact Details

arielraaron@gmail.com

**Comment by aferlo78** [comment]
I have the same issue.

My graphic card is far more modest RTX3060 6GB.

Is good enough to do things with stable diffusion but i get truly stuck here.

Many thanks
