### ISSUE TITLE
[bug]: inpainting model won't load

### ISSUE THREAD

**Issue by Kivrar** [invoke-ai/InvokeAI#2288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What happened?

Error when loading the inpainting model for use in canvas window

**Comment by lstein** [comment]
@Kyle0654  can you take a look?

**Comment by lstein** [comment]
Please look at the console windows and report any errors you see there.

**Comment by dholbrook86** [comment]
@Kivrar How much physical memory do you have on the computer running this? Not VRAM but simply RAM?

I have invoke on my cloud servers and I had to bump my memory up from 16GB to 20GB before the inpainting model would load. Otherwise it was a straight crash with no error. Check your memory.
