### ISSUE TITLE
[enhancement]: List of Ideas

### ISSUE THREAD

**Issue by Kivrar** [invoke-ai/InvokeAI#2290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Ideas for improvement:

 - Standalone GUI that's more efficient than Webui
 - All files including compvis base models all part of single click installer (with all license agreement screen in one page)
 - Ability to graphically combine and control various weights of models
 - Ability to download models directly within the model manager
 - Ability to input multiple images for img-to-img generation
 - Make each image output has separate text file generated with info i.e prompt, seed, settings etc, rather than all output in one text file
 - Update to latest version function built into GUI
 - Ability to control precise allocation of VRAM for image generation via GUI
 - Ability to allow GPU and CPU run task simultaneously for one task
 - Incorporate an innovative Prompt Presets function under the prompting box, so the user can press any button of user saved presets (such as 4k, highly detailed, global illumination, photorealistic, trending on artstation etc etc) IN ADDITION to the words in the prompt box so the user don't have to type up repetitive quality maintenance prompts every time. Perhaps color coding can be useful for the prompt words. The same button can remove the entire preset as well.
 - Be better than all the features of Automatic1111 Webui  ;-)

**Comment by bloodsign** [comment]
Clean uninstall and reinstallation would be nice

**Comment by netsvetaev** [comment]
Some of them are already in plans :-)
Clean uninstall — just delete Invoke’s folder.

**Comment by mickr777** [comment]
> Some of them are already in plans :-) Clean uninstall — just delete Invoke’s folder.

Also good if your reinstalling  to clear pip cache folder python uses under c:\users\yourusername\appdata\Local\pip\cache\ if your on windows, as this has caused some rare install issues in the past with failed downloaded files

**Comment by psychedelicious** [comment]
There may be some good ideas here but please resubmit them as individual feature requests if you still want them.
