### ISSUE TITLE
[bug]: Error 404 while installing 2.2.5p1

### ISSUE THREAD

**Issue by farofa0** [invoke-ai/InvokeAI#2300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

amd

### VRAM

8

### What happened?

It happens during the installation process.

### Screenshots

*** Installing InvokeAI Modules and Executables ***
Collecting https://github.com/invoke-ai/InvokeAI/archive/refs/tags/v2.2.5p1.zip
  ERROR: HTTP error 404 while getting https://github.com/invoke-ai/InvokeAI/archive/refs/tags/v2.2.5p1.zip
ERROR: Could not install requirement https://github.com/invoke-ai/InvokeAI/archive/refs/tags/v2.2.5p1.zip because of HTTP error 404 Client Error: Not Found for url: https://codeload.github.com/invoke-ai/InvokeAI/zip/refs/tags/v2.2.5p1 for URL https://github.com/invoke-ai/InvokeAI/archive/refs/tags/v2.2.5p1.zip

**Comment by ccelikde** [comment]
the same happend to me

**Comment by GiGi45** [comment]
Same

**Comment by Owyx** [comment]
same

**Comment by andyg2** [comment]
I edited the installer to change `2.2.5p1` to `latest`

Linux (line 9) of `install.sh` 
`INVOKEAI_VERSION="latest"`


Windows (line 18) of `install.bat`
`set INVOKEAI_VERSION=latest`


This worked for me but there's probably a very good reason that `2.2.5p1` is specified in the installer and I have no idea what that is.

If it works for you too then great, your computer may explode any minute, if not then please ignore this hack.
