### ISSUE TITLE
[bug]: installation failed

### ISSUE THREAD

**Issue by AtomicLunch** [invoke-ai/InvokeAI#2301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What happened?

ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5
ERROR: Could not find a version that satisfies the requirement torch==1.13.1 (from versions: none)
ERROR: No matching distribution found for torch==1.13.1

upgraded to 3.10.9, which sadly didn't alter the error
My machine:
Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
64.0 GB RAM
Win 11 64bit OS
NVIDIA rtx 2080 with 6 Gb VRAM

Any help would be greatly appreciated
H

### Contact Details

hcserrano@icloud.com

**Comment by gogurtenjoyer** [comment]
Hi, when installing python 3.10.9, make sure to check the box labeled 'add python.exe to PATH' in the installer at the bottom of the window - you might need to uninstall and reinstall to see that.
