### ISSUE TITLE
 [bug]: Nach der Eingabe:   >> Point your browser at http://127.0.0.1:9090 öffnet sich der Google-Browser aber es kommt keine Verbindung zu invoke zustande. Nach kurzzeitigem deaktivieren des Virenschutzes klappte es dann. Ich denke die angegebene local Webadresse wird auch von anderen Programmen benutzt. Kann man das ändern?  

### ISSUE THREAD

**Issue by uhu12** [invoke-ai/InvokeAI#2302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

16GB

### What happened?

Nach der Eingabe:   >> Point your browser at http://127.0.0.1:9090 öffnet sich der Google-Browser aber es kommt keine Verbindung zu invoke zustande. Nach kurzzeitigem deaktivieren des Virenschutzes klappte es dann. Ich denke die angegebene local Webadresse wird auch von anderen Programmen benutzt. Kann man das ändern?  

### Contact Details

karl-ludwigniebes@web.de

**Comment by Pfannkuchensack** [comment]
Man kann den Port beim starten mit angeben: (Beispiel) invoke --web --port 8090
