### ISSUE TITLE
convenient output of models

### ISSUE THREAD

**Issue by VeyDlin** [invoke-ai/InvokeAI#2305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

There are really a lot of models.

It is difficult to remember everything by name only, it would be convenient to have a more advanced model selection interface, with a preview and description

For example , as in civitai.com , there is a title, several pictures and a description, you can add tags to the description that the model requires

In addition, the idea for the future may be to add nodes to the models, for example, post-processing or automatically adding tags to the text

**Comment by Millu** [comment]
There's a couple more recent duplicates of this - will be closing this one.
