### ISSUE TITLE
[bug]: Out of ram when changing model

### ISSUE THREAD

**Issue by QwertyITA** [invoke-ai/InvokeAI#2308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

amd

### VRAM

16GB

### What happened?

When changing the utilized model the usage i RAM spikes up and makes the program crash (with 16gb of ram)

>> Model change requested: inpainting-1.5
>> Current VRAM usage:  2.17G
>> Offloading stable-diffusion-1.5 to CPU
>> Scanning Model: inpainting-1.5
>> Model Scanned. OK!!
>> Loading inpainting-1.5 from /home/user/Documenti/InvokeAI/invokeai/invokeai/models/ldm/stable-diffusion-v1/sd-v1-5-inpainting.ckpt
   | LatentInpaintDiffusion: Running in eps-prediction mode
   | DiffusionWrapper has 859.54 M params.
   | Keeping EMAs of 688.
   | Making attention of type 'vanilla' with 512 in_channels
   | Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
   | Making attention of type 'vanilla' with 512 in_channels
./invokeai/invoke.sh: riga 24:  8612 Killed                  .venv/bin/python .venv/bin/invoke.py --web $*
python: can't open file '/home/user/Documenti/InvokeAI/scripts/invoke.py': [Errno 2] No such file or directory

### Additional context

Seems to happen only with less than 16GB or ram

**Comment by Aamir3d** [comment]
16GB isn't enough to load a larger model (if model caching is enabled) and you've got multiple applications open.
You'll run out of RAM - this happens on my system with 16 GB too.

Easy workaround - load the model from the webUI, and immediately close Chrome/browser, and wait for the model to load, it won't take as long.
Once loaded, reopen your web browser application.

**Comment by mickr777** [comment]
Also you can add this line --max_loaded_models 1 to your invokeai.init file, to disable model caching so the last model used isnt offloaded to system ram
