### ISSUE TITLE
[enhancement]: Read metadata from imported images (if available)

### ISSUE THREAD

**Issue by whosawhatsis** [invoke-ai/InvokeAI#2315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Reading metadata works well for generated images in the gallery, but imported images show nothing, even if they were produced by invoke, and have all the necessary tags. Being able to read the data from imported images would make it easier to share generation parameters, and to riff on someone else's shared images.

**Comment by Aamir3d** [comment]
Related to #2261

**Comment by FredericBabon** [comment]
You might have a look at my fork where i added this : "use metadata to add original filename as prefix for output images"
Fork (from tag v5.4.3rc1) available here : https://github.com/FredericBabon/InvokeAI/tree/fba_v5.4.3rc1
