### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by Odawgthat** [invoke-ai/InvokeAI#2316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What happened?

When I go to outpaint (any box size, any model, any sampler) it produces large pixels 80% of the time.

### Screenshots

![image](https://user-images.githubusercontent.com/122664491/212459704-56024e31-99da-403b-a5e3-c5f72e68c836.png)

### Additional context

Any help would be greatly appreciated :)

**Comment by mickr777** [comment]
When out painting make sure image to image strength is above atleast 7

**Comment by mickr777** [comment]
Make sure if you are using tile infile for out painting to use atleast a 0.7 in image to image strength

**Comment by Odawgthat** [comment]
Ok, so I changed tile to patchmatch and there seems to be no problems any more??? Is there a way to fix this for tile or will this be fixed in an upcoming update? If you could help me with understanding why tile isn't working 80% of the time I would be greatly appreciated!!!
