### ISSUE TITLE
[enhancement]: 

### ISSUE THREAD

**Issue by VOOM108** [invoke-ai/InvokeAI#2318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Just as with images the prompts are saved and can be reused, could there be metadata on which model was used and also be an option to restore the settings that led to the generation of that result? That would help a lot in producing similar results with a new prompt.

**Comment by gogurtenjoyer** [comment]
This is already possible, though it won't automatically switch models for you. There's a `*` button for 'use all' which uses all settings in a previous image, as well as a `</>` button that will show all metadata in the image, including all settings and model used.
