### ISSUE TITLE
[bug]: Upscale glitch

### ISSUE THREAD

**Issue by goodwin74** [invoke-ai/InvokeAI#2325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What happened?

Upscale any image ends with a glitch. A glitch is painting a part of an image with a dark color. The intensity of the fill depends on the "Strength" parameter.

### Screenshots

![image](https://user-images.githubusercontent.com/15101984/212561749-b3e3425d-ee9f-43c7-b93d-115a94bd1048.png)

![image](https://user-images.githubusercontent.com/15101984/212561686-13960daa-eced-4827-b5f1-052a082d2dfd.png)

![image](https://user-images.githubusercontent.com/15101984/212561585-d70cb4e9-d89d-41ec-9d2e-1c587d278224.png)

**Comment by Leozolt** [comment]
https://github.com/invoke-ai/InvokeAI/issues/939
