### ISSUE TITLE
[bug]: from_file | error: unrecognized arguments | prompts from a file

### ISSUE THREAD

**Issue by paccocino** [invoke-ai/InvokeAI#2332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What happened?

Hey there,
i already searched the forums, but couldn't find that already:

Using: InvokeAI 2.2.5

I start the invoke.bat > Choose: 1. command-line
Initialization finishes and prompting works fine, generates images.

trying to use --from_file with a prepaired text file:
`--from_file "C:\invokeai\invoketestbatch.txt"`

gives error: 
`invoke.py: error: unrecognized arguments: --from_file C:\invokeai\invoketestbatch.txt`

the -h help does not list the from_file arguments...
What did i do wrong?

greets, Paccocino

### Additional context

already tried to put the txt in different locations.

**Comment by BrizzleMcNizzle** [comment]
I am also wondering the answer to this!

**Comment by paccocino** [comment]
The issue is still there in the newest update. :-(

**Comment by LonelyBracket** [comment]
I'm also experiencing this issue on Mac.
