### ISSUE TITLE
[bug]: diffusers pipeline should run with autocast disabled

### ISSUE THREAD

**Issue by keturn** [invoke-ai/InvokeAI#2345]
We currently have some code in generator.base that turns on autocast when float16 is in use: https://github.com/invoke-ai/InvokeAI/blob/3a1724652e2d2d6ebf070f39664393fb2ffa3a15/ldm/invoke/devices.py#L24-L29

We do not want to be using autocast while executing the diffusers pipeline.

Ideally we can take that out entirely, but if it's required for some of the legacy `ckpt_generator` code, we may be able to work around it by either moving the autocast further down to that code, or protecting the diffusers code by wrapping it in `with autocast(enabled=False)`.

Code that fails with type errors when autocast is disabled (e.g. `Input type (float) and bias type (c10::Half) should be the same`) needs to be cleaned up so the tensors are their correct types. Preferably as early to their creation as possible, instead of converting them on every access.

### Additional context

This is related to and possibly blocking other issues:
- #2329
- #2336

**Comment by lstein** [comment]
I removed the autocast scoping and proceeded to fix all the `Input type (float) and bias type (c10::Half) should be the same` errors and am quite sure that the model is running with `torch.dtype==torch.fp16`. Unfortunately I'm still getting black images when running at half-precision on the SD-2.1 768 model.
