### ISSUE TITLE
[enhancement]: Web UI: Gallery navigation hotkeys (or "top"/"bottom") buttons

### ISSUE THREAD

**Issue by mcbexx** [invoke-ai/InvokeAI#2348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

After a while (anecdotal, at least for me), the gallery can fill up quite a lot after refreshing and loading in more thumbnails, and on more than one occasion I would have liked to be able to  jump quickly to the top or the bottom of the gallery grid. Currently there don't appear to be any hotkeys (PgDn, PgUp, Pos1, End) set up for scrolling through the gallery. Alternatively/supplementary, a small set of "to the top"/to the bottom" icons for mouse operation at the top of the gallery could prove helpful. 

Edit: Splitting the "Load more" button into "Load more" and "Load all" would also be great.

**Comment by psychedelicious** [comment]
We now have full directional gallery navigation, and you can use normal hotkeys to scroll to the top or bottom of the gallery.

I don't think we can really do a load all. That would kill the browser if you have a lot of images.

I'm closing this as I think we've addressed the core need to the scope we can reasonably address it
