### ISSUE TITLE
[bug]: Unable to install on Mac

### ISSUE THREAD

**Issue by pitneyw** [invoke-ai/InvokeAI#2354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

amd

### VRAM

2GB

### What happened?

I clicked and dragged the install.sh file into the Terminal, and it failed with the following module 'dns.rdtypes' has no attribute 'ANY'

a step by step fix would help my beginner brain

### Screenshots

![Screen Shot 2023-01-17 at 8 59 54 AM](https://user-images.githubusercontent.com/122834452/212933967-f2a94f6e-6058-401c-97c9-8b38b98972a9.png)

### Additional context

very similar to issue #2323 - but when I pasted "pip install dnspython==2.2.1" in the terminal (before running the instal again), nothing changed.

I've been following [this tutorial](https://www.youtube.com/watch?v=ac2F5-GuADA) and have gone through their Troubleshooting Guide
- Make sure Python 3 is Installed (ideally Python 3.10)
- Make sure your terminal is using your Python 3 installation by updating your PATH Variable.
- Add Python to PATH variable Guide

**Comment by hipsterusername** [comment]
Pasting FAQ on Discord -

> 
> The new 2.2.5p2 installer and updater should fix this issue: https://github.com/invoke-ai/InvokeAI/releases/tag/v2.2.5p2
> 
> If you still receive an error that looks like module 'dns.rdtypes' has no attribute 'ANY', you can downgrade to the working version of dnspython using the following procedure:
> 
> 1. activate the InvokeAI venv (easiest way would be selecting option 3 in the invokeai.sh/.bat)
> 2. type pip uninstall dnspython (then confirm)
> 3. then pip install dnspython==2.2.1
> 4. run invokeai.sh/.bat again, choosing option 1 or 2. This should cause the configuration script to run again.

**Comment by pitneyw** [comment]
> 

Thank you! 
I ran into the #2203 problem but after installing "xcode-select --install", I was able to add the 3 on line 124
