### ISSUE TITLE
Update Error: ModuleNotFoundError: No module named ' safetensors ' 

### ISSUE THREAD

**Issue by inck86** [invoke-ai/InvokeAI#2356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6 Gb

### What happened?

During update, have an error:
" Update Error: ModuleNotFoundError: No module named ' safetensors ' "

### Screenshots

![screen](https://user-images.githubusercontent.com/119116007/213014507-80a1d30d-8838-4581-b6c3-1b07dc2a7ed1.png)

### Contact Details

inck86@gmail.com

**Comment by daveisdigital** [comment]
If you activate the invokeai environment:

```
$ . .venv/bin/activate
```
Then install the 'safetensors' python package into the newly-activated environment:

```
$ pip install safetensors
```
That worked for me at least.

**Comment by nuckolsm** [comment]
I ran into the same error updating on a Mac, which I have yet to resolve.

**Comment by inck86** [comment]
> Then install the 'safetensors' python package into the newly-activated environment:
> 
> ```
> $ pip install safetensors
> ```

Thx, it helped!
