### ISSUE TITLE
[bug]: The "Download Image" button on the txt2img tab can be clicked only directly on the text

### ISSUE THREAD

**Issue by Barafu** [invoke-ai/InvokeAI#2383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

The "Download Image" button on the txt2img tab can be clicked only directly on the text. Clicking on the large empty area next to the text does nothing. Other buttons work: I can click on empty parts of the buttons. 

Brave browser, using 125% zoom.

**Comment by psychedelicious** [comment]
Thanks, fix upcoming in PR #2435
