### ISSUE TITLE
[bug]: Max seed value is too low

### ISSUE THREAD

**Issue by Lex-DRL** [invoke-ai/InvokeAI#2386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What happened?

There are plenty of prompts all over the internet with seeds much higher than what InvokeAI allows.

E.g., I tried this one:
- `112358132141`

It was truncated to:
- `4294967295`

Up-arrow icon next to the field is greyed out indicating limit is reached.
It seems, the issue appears with any sampler.

### Screenshots

![screenshot](https://user-images.githubusercontent.com/3897975/213885328-b05f8820-1a09-4147-8391-b20f7d681339.png)

**Comment by blessedcoolant** [comment]
Do we know whats the high end cap for seed values? If there is one.

**Comment by keturn** [comment]
looks like it's a 64-bit int: https://pytorch.org/docs/stable/generated/torch.manual_seed.html#torch.manual_seed

in decimal, that's 18,446,744,073,709,551,615

(Wolfram Alpha claims that's _less than_ the number of possible states of Rubik's cube, which seems hard to believe!)

**Comment by Lex-DRL** [comment]
In AUTOMATIC1111, I've tried to detect it from trial end error. Here are my findings:
- The field itself seems to be unlimited in size.
- But it behaves differently depending on what you've input there
  - a regular int or a float are both treated as a float
  - if you put any character stopping it to be a number, it seems to be treated as a stricng, shich is hashed in some way.
- The max raw seed value is `18446744073709519872`, i.e. `2^64`
- **HOWEVER**, all the generations starting from `18446744073709517824` (`2^64-2048`) give **almost** the same result. As well as 2048 seeds before them (witrh another image), As well as 2048 before them.. 
  - This behavior doesn't seem to depend on a model being used.
  - And it also hints that floats are used even with provided int seeds.

So, with these findings:
- I believe, the best solution would be replecate the same seed treatment as in A11's webui.
- If you don't agree, you should at least raise the max value to `18446744073709519872`.

**Comment by blessedcoolant** [comment]
So Typescript lets me know that  ...

`Numeric literals with absolute values equal to 2^53 or greater are too large to be represented accurately as integers.`

.. which means `9007199254740992` is the highest value I can set for the field.

**Comment by Lex-DRL** [comment]
The goal isn't to allow a user input anything, but to be able to re-generate other people's examples. So I guess, for now you should at least raise it to `9007199254740992` as a simple fix.

But in the future - yeah, I strongly believe generated images shouldn't be different depending on which UI you used to make them. So, yeah, the true solution is unfortunately "follow A11 since he sets the trend".

**Comment by Lex-DRL** [comment]
Also, 
> too large to be represented accurately as integers

Doesn't that mean you can also represent them as floats? A11 seems to do the same thing. It **SHOWS** a user whatever they have typed. But it **USES** these seeds as floats.

**Comment by blessedcoolant** [comment]
> The goal isn't to allow a user input anything, but to be able to re-generate other people's examples. So I guess, for now you should at least raise it to `9007199254740992` as a simple fix.
> 
> But in the future - yeah, I strongly believe generated images shouldn't be different depending on which UI you used to make them. So, yeah, the true solution is unfortunately "follow A11 since he sets the trend".

The main difference in the results is because of how each implementation handles the attention system. As long as that is not standardized, they will all end up having different results. Maybe some day we'll have a library that is so state of the art that everyone uses that and we get some sort of standardization but I don't think that's happening any time soon. The seed value is the smallest concern in that regard.

**Comment by Lex-DRL** [comment]
> I'd have to manually add a ton of checks to verify that the entire thing is a number
For now, as a simpler solution, you can:
- Keep it a number in the UI
- Raise the field max limit to `2^64` if possible, `9007199254740992` otherwise.
- Under the hood (in Python), convert those ints into floats.

> As long as that is not standardized, they will all end up having different results.
I understand that. But I believe it would be better if we at least try to **minimize** those differences.

> The seed value is the smallest concern in that regard.
I get somewhat different results in A11's UI and yours. I get it, different implementations. But being unable to replice someone else's result **AT ALL** seems like a huuuge turn of to any other newcomers (and somewhat to me, tbh).

**Comment by keturn** [comment]
> Numeric literals with absolute values equal to 2^53 or greater are too large to be represented accurately as integers.

Hypothetically you could use [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt), but I have no idea whether the input widget and validation methods are written for that.

**Comment by waffletower** [comment]
I strongly recommend promoting the seed to the largest integer the InvokeAI default latent generator algorithm can handle.  Unfortunately, InvokeAI uses a different latents generator algorithm than other stable diffusion implementations (such as the Replicate cogs which use a pytorch Generator seed:  https://github.com/replicate/cog-stable-diffusion/blob/38510524cf4f3dc679e5945ebb52feb40d52c1a9/predict.py#L106).  It would be great if these different latent generation algorithms were made pluggable within InvokeAI, such that artists migrating from other implementations could fully utilize InvokeAI.  Currently, the seeds are incompatible even if they are the have the same numeric scale (and using the "same" scheduler or CFG scale, and other parameters)

**Comment by waffletower** [comment]
I'll add a pull request soon.  I have increased the UI seed max to `2^53` as per Javascript precision limitations.  I will test and see if seeds are usable to `2^63` via CLI invocation with the seeding changes I made to the pipeline.  I have been able to utilize 53-bit seeds originally used with the standard diffusers StableDiffusionPipeline, and obtained perceptually identical results in InvokeAI.  I have also adjusted the minimum CFG value allowable in the InvokeAI UI as well.

**Comment by waffletower** [comment]
I opened this pull request which supports 53-bit seeds in the invokeai UI, and 63-bit (pytorch/numpy maximum) seeds via the invokeai CLI.

https://github.com/invoke-ai/InvokeAI/pull/2843

**Comment by waffletower** [comment]
> > Numeric literals with absolute values equal to 2^53 or greater are too large to be represented accurately as integers.
> 
> Hypothetically you could use [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt), but I have no idea whether the input widget and validation methods are written for that.

Unfortunately, using BigInt would forgo using the pytorch/numpy random number generator algorithm 63-bit limit:
https://pytorch.org/docs/stable/generated/torch.manual_seed.html

While it is possible to generate latents with larger seeds, it would prevent seed sharing between stable diffusion implementations that use the current tacitly agreed upon method.

**Comment by dfl** [comment]
I also noticed this problem of seed truncation and would like to reopen this issue if possible

**Comment by T-Wittich** [comment]
This problemstill exists in v6.02
