### ISSUE TITLE
[bug]: Summary of cross-attention related SD-2.1/xformers/swap  issues

### ISSUE THREAD

**Issue by lstein** [invoke-ai/InvokeAI#2387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What happened?

This is an attempt to summarize the interlocking issues related to diffusers, cross-attention and SD-2.1

| Issue                                 | main       | main+xformers | main with<br>monkeypatching disabled | PR #2365 (upcast attention) | PR #2335 (force float32 for SD2.1) | PR #2385 (non-monkeypatched cross-attention control) |
|---------------------------------------|------------|---------------|--------------------------------------|----------------------------|-----------------------------------|----------------------------------------------------|
| SD2.1 image generation                | **broken** | OK            | OK                                   | **broken**                 | OK                                | OK                                                 |
| SD2.1 excessive memory use            | OK         | OK            | OK                                   | **broken** (needs >12 GB)  | **broken** (needs >12 GB)         | Acceptable (8.75 GB)                               |
| Non-deterministic images (all models) | OK         | **broken**    | OK                                   | OK                         | OK                                | OK                                                 |
| swap() functionality                  | OK         | **NO**        | **NO**                               | OK                         | OK                                | OK                             |

**Comment by damian0815** [comment]
i dug into the `XFormersCrossAttnProcessor` in diffusers 0.12 and i'm 99% sure this will simply never work with cross-attention control
