### ISSUE TITLE
[bug]: Leaking blur/undesired filtering on Unified Canvas

### ISSUE THREAD

**Issue by Lex-DRL** [invoke-ai/InvokeAI#2391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What happened?

With each operation performed in `Unified Canvas` mode, the image gets blurred in tiny incremental steps, which add up over time. This happens across the canvas, even in areas which were kept intact. The only solution so far seem to be exporting the entire canvas to PhotoShop on a regular basis, manually combining the image from pieces and re-importing it back to Invoke.

A bug like this happens a lot in CG, if filtering is performed when it shouldn't be. Especially when image is resized multiple times. Probably, in InvokeAI it happens because a masked part is resized with the rest of canvas.

The easiest solution would be restoring source pixels by inverted mask after each operation.

### Screenshots

![screenshot](https://user-images.githubusercontent.com/3897975/213910898-520e3900-b9a2-4cae-b62c-390468c4981f.png)
![screenshot](https://user-images.githubusercontent.com/3897975/213910906-f7ab981c-20b5-4812-aa89-61e618eaf413.png)

**Comment by psychedelicious** [comment]
The invert-masked source image is indeed pasted back over the original. How are you exporting the image from the canvas?

**Comment by Lex-DRL** [comment]
By clicking the download image button. Tried merging layers or not, clearing canvas history or not, with the setting to export only the working area or not... the blur seems to occur either way, regardless.
It might be hard to notice just after a single in/out paint. But after, let's say, 5 of them - it's clearly visible.
