### ISSUE TITLE
[enhancement]: Simple Downscale feature

### ISSUE THREAD

**Issue by timdesrochers** [invoke-ai/InvokeAI#2394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Sometimes we get carried away, and end up working with a canvas that's too big for our GPU. Or maybe we upscaled and inpainted and added great detail, but need to bring things back down to earth for a cohesive last pass. 

This is a feature request for the implementation of a run-of-the-mill downscale option in the GUI. 

I know the core devs have much bigger fish to fry, so I intend on looking into this once I have some more free time in the (hopefully) next couple of weeks.

**Comment by hipsterusername** [comment]
Would love for a FE contributor to help make this (and other layer management features) real!

**Comment by hipsterusername** [comment]
To track in #4466 and #5767
