### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by JerryOver** [invoke-ai/InvokeAI#2402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cpu

### What happened?

I installed Invoke AI 2.2.5. I can generate text to images, but when I try to inpaint on an image (using stable diffusion 1.5), I get no noticeable change on my image, and the last line in my cmd window says, "system config requested". Also when I do imgtoimg, it will show me the image it generates, but it also says in the last line of the cmd "system config requested". The screenshot is my cmd of my inpainting.

If I knew what "system config requested" meant I would do it. Any suggestions?

### Screenshots

![INvokeai](https://user-images.githubusercontent.com/120525455/214102562-005db960-be13-4fab-ba89-5343a4a20f1a.png)

**Comment by Barafu** [comment]
It seems you are having seed value locked and variations off, and the same prompt, which means that inpaint generates exactly the same image every time. Try varying those thing. Also, check that Image To Image Strength is above 0.5.
