### ISSUE TITLE
[enhancement]: Allow for an optional AUTOMATIC1111 prompt style with positive and negative sections

### ISSUE THREAD

**Issue by vqt123** [invoke-ai/InvokeAI#2403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

[enhancement]: Allow for an optional AUTOMATIC1111 prompt style with positive and negative sections.

I appreciate you guys trying to explore the prompting user experience to try to make it better, but I would also really appreciate if there was a way to use the standard automatic1111 style prompting that most of the field is used to by now.

Almost all prompts on civitai, or in prompt tutorials use this format where there's a positive section and a negative section. These prompts are basically unusuable in the current version of invokeai which could be anon-starter for a lot of users looking to just copy and paste prompts they find on the web.

Exploring better prompting using the single field can still be the default, but would love an optional version to switch to a positive/negative automatic1111 format

**Comment by Lex-DRL** [comment]
> These prompts are basically unusuable
I wouldn't say that **SO** categorically. Technically, they're somewhat usable...
- but they require manual conversion
- and I'm not sure if I use `(this kind)1.2 of (weighted)1.25 (syntax)1.3` correctly (from [this help page](https://github.com/invoke-ai/InvokeAI/blob/main/docs/features/PROMPTS.md))
- ... since even after manual conversion, InvokeAI still produces different results from A11, with **ALL THE SAME** settings (non-default model tried, obviously).

But yeah, I totally agree with the described issue.

**Comment by brucethemoose** [comment]
>  since even after manual conversion, InvokeAI still produces different results from A11, with ALL THE SAME settings (non-default model tried, obviously).

The sd implementation and python packages are totally different, so I think this is to be expected.

**Comment by Alchete** [comment]
The prompting difference is the main thing that keeps me with A1111.  I vastly prefer the two fields and also prefer their tag system.  If Invoke had two fields as well as an A1111 alt-syntax style as an option, I think a number would switch to it.

**Comment by realstevewarner** [comment]
Definitely in the two separate fields camp and upvote that feature request.  It makes it much easier to differentiate the prompt from the negative prompt, but it's more than just a cosmetic change.  Negative prompts are crucial to good output.  A1111 lets you save a library of negative prompts.  We need the same here.  I keep images in my gallery simply so I can have a starting prompt.  It would be great to have a saved library that lets me just pick the negative prompt or parts of a positive prompt to start from.

**Comment by psychedelicious** [comment]
We have two prompt fields now, and a community member has created an A1111 to Compel* prompt translator: #3680

*Compel is the prompt parser used by InvokeAI

**Comment by AlejandroAkbal** [comment]
Hey, I have created a simple tool for this specific use case

I was tired of manually editing the prompts since I transitioned from Automatic1111's Stable Diffusion Web UI to InvokeAI

So here you have it, it's live on [https://polyprompter.com](https://polyprompter.com/)
