### ISSUE TITLE
[enhancement]: Pytorch 2.0 Support

### ISSUE THREAD

**Issue by brucethemoose** [invoke-ai/InvokeAI#2405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Add support for Pytorch 2.0 nightly, and possibly its new features like torch.compile() and the inductor (and/or various other) optimized backends. 

Its early, yes, but it would be nice to have the performance and compatibility improvements now, and InvokeAI compatibility (at least partially) ready to go when Pytorch 2.0 is officially released.

Currently it doesn't work with Invoke AI for me, but it does work with a vanilla Diffusers StableDiffusionImg2ImgPipeline. See the odd error I ran into here: https://github.com/invoke-ai/InvokeAI/issues/2396

See also the issues on the diffusers side, as well as a long discussion from Automatic's repo:
https://github.com/huggingface/diffusers/issues/1964
https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/6932

I would also be interested to see  if the current nightly build works for anyone, or if I am encountering some bizzare environment issue.

**Comment by patrickvonplaten** [comment]
Also see: https://github.com/huggingface/diffusers/pull/2303
