### ISSUE TITLE
outpainting option to skip infill method (patchmatch etc)

### ISSUE THREAD

**Issue by keturn** [invoke-ai/InvokeAI#2417]
> I'd like to explore the possibility of special-casing for inpainting models, which do pretty well (if not better) without the second pass used for inpainting and outpainting. Because of this I still keep the ckpt version of inpainting-1.5 around for my outpainting needs because it uses the legacy omnibus module and bypasses the inpainting code.

-- [lstein](https://discord.com/channels/1020123559063990373/1031668022294884392/1066959907829579826)

### Alternatives

We could continue to switch this based on the model, though I'd prefer adding an explicit "None" option to the infill selection options. This would allow comparison of the different infill approaches with different models more directly.

**Comment by Kyle0654** [comment]
If this can wait for nodes, I was thinking we could split out the infill into a separate node anyway. Then we could just use a different graph to outpaint for different models.

Also note that no infill is equivalent to a solid infill with whatever color PIL happens to use when outcropping.
