### ISSUE TITLE
[bug]: img2img (and inpainting) produces only terrible noise on Mac

### ISSUE THREAD

**Issue by keturn** [invoke-ai/InvokeAI#2418]
img2img and inpainting produces totally unrecognizable noise on Mac.

### Screenshots

from whosawhatsis:

![inpainted area is completely garbled](https://cdn.discordapp.com/attachments/1049495067846524939/1066859559773282355/Screenshot_2023-01-22_at_15.18.40.png)

**Comment by keturn** [comment]
Inpainting has a lot going on with the masking and everything, but if this also happens on plain img2img then there are fewer things to track down. The difference between img2img and txt2img isn't that big in our current pipeline.

Something is the wrong data type or some get_noise function doesn't do the mps-compatible generate-noise-on-cpu thing or the input image needs an extra `contiguous` on it or something?

**Comment by whosawhatsis** [comment]
The problem may be in the upstream diffusers library. I'm having similar problems getting img2img to work in my custom script.

**Comment by damian0815** [comment]
it is most likely a pytorch problem, in fact. ref https://github.com/pytorch/pytorch/issues/91617. if so then it's fixed in https://github.com/kulinseth/pytorch/pull/222 but no idea when this will make into pytorch nightly builds let alone release.

**Comment by damian0815** [comment]
(the gist of https://github.com/pytorch/pytorch/issues/91617 is that under certain conditions pytorch subtractions that look perfectly reasonable will return 0s or nonsense, and the "fix" is to `.clone()` the tensor before doing the operation. ie, `a - b` = (erroneously) 0, whereas `a - b.clone()` = correct result.)

**Comment by damian0815** [comment]
confirmed, running against a patched pytorch 2.0 that includes https://github.com/kulinseth/pytorch/pull/222, inpainting and img2img work fine
![Screen Sharing Picture 25  January 2023 at 22 51 16 CET](https://user-images.githubusercontent.com/144366/214699617-95882f40-6d52-4eb7-8d0f-afd5c3ee16d0.png)

**Comment by pbakaus** [comment]
@damian0815 running into the exact same issue. How did you install the patched pytorch? Tried today but ran into too many hiccups, getting a lot of package inconsistency warnings in conda (granted, I have little idea what I'm doing).

**Comment by keturn** [comment]
> (the gist of pytorch/pytorch#91617 is that under certain conditions pytorch subtractions that look perfectly reasonable will return 0s or nonsense, and the "fix" is to `.clone()` the tensor before doing the operation. ie, `a - b` = (erroneously) 0, whereas `a - b.clone()` = correct result.)

If we need to put that workaround somewhere, I think there are only a handful of places to experiment with, those that are used in img2img but not txt2img. 

- the noise functions in [img2img](https://github.com/invoke-ai/InvokeAI/blob/main/ldm/invoke/generator/img2img.py)
- [`non_noised_latents_from_image`](https://github.com/invoke-ai/InvokeAI/blob/07e03b31b7610a27d709b366a491e57085d9b393/ldm/invoke/generator/diffusers_pipeline.py#L581) in the pipeline

Those are the main places that look like they return a tensor that might later be used in some buggy operation. Try sprinkling a few `clones()` around and see if anything shows up.

**Comment by damian0815** [comment]
@pbakaus afaik the only way at this point is to compile it manually. i documented my process here https://medium.com/@damian0815/how-to-debug-native-mps-operations-in-pytorch-f094b7f4e8f0 but i wouldn't recommend it

**Comment by damian0815** [comment]
i've managed to isolate the problem to, i think,   `def non_noised_latents_from_image(self, init_image, *, device, dtype)` which works on CPU but returns rubbish on MPS. going to see if i can dig any further into why.

**Comment by damian0815** [comment]
img2img and inpainting both work in #2458
