### ISSUE TITLE
[enhancement]: Intergrate Instruct Pix2Pix

### ISSUE THREAD

**Issue by odragora** [invoke-ai/InvokeAI#2419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

A few days ago a new project has been released that allows to edit an image using text prompts without inpainting.

https://github.com/timothybrooks/instruct-pix2pix

Other Stable Diffusion UI already started to integrate it:
https://www.reddit.com/r/StableDiffusion/comments/10kbyro/nmkd_stable_diffusion_gui_190_is_out_now/

It would be incredible to have this functionality as a part of InvokeAI.

**Comment by Lycantant** [comment]
Do you have colab link for Pix2Pix? it looks interesting

**Comment by odragora** [comment]
This one should work:
https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/InstructPix2Pix_using_diffusers.ipynb

Also, the repo description has a link to the demo.

**Comment by Lycantant** [comment]
thanks 😁

**Comment by TheBarret** [comment]
that does look like a very convenient way to do things, simple and effective :D

**Comment by telles0808** [comment]
Is there any news?

**Comment by odragora** [comment]
Yes, implementation of this feature is still highly desirabe.

**Comment by BaddRadish** [comment]
yes please! <3

**Comment by strauzen** [comment]
Any update on this? It would indeed be awesome to have it working on InvokeAI
