### ISSUE TITLE
[bug]: dependencie error on Fedora Linux

### ISSUE THREAD

**Issue by Idcrafter** [invoke-ai/InvokeAI#2421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

24GB

### What happened?

after letting the installer run does it always throw the error in the screen-shot and after a bit of research did i notice that numba doesn't currently work on the python version that fedora currently has which is Python3.11.

### Screenshots

![grafik](https://user-images.githubusercontent.com/50270538/214698558-51d562f9-cc4c-4ebc-88f1-373a6cb5e318.png)

### Contact Details

my mastodon handle is: @Idcrafter@fosstodon.org

**Comment by gogurtenjoyer** [comment]
Yep, pytorch specifically doesn't have full support for python 3.11 right now, and there's probably a few more packages (like numba) that are similar. You should be able to install python 3.10 and use that, however (multiple versions of python can be installed on the same system).

**Comment by Idcrafter** [comment]
Thanks for the quick reply and for the information but how do i specify the correct Version of python for invoke ai? It allways seems to default to the newest Version

**Comment by liuzblieuhlieuzhfi** [comment]
sudo dnf install python310

**Comment by pedromuracchini** [comment]
> Thanks for the quick reply and for the information but how do i specify the correct Version of python for invoke ai? It allways seems to default to the newest Version

I seem to run on the exact same problem. How did you specify the version to use?

**Comment by airtonix** [comment]
you use asdf

**Comment by Idcrafter** [comment]
It is still the same issue but it now thinks that pip3 has a update which is already installed on my system and reports using a older Version

**Comment by Idcrafter** [comment]
> > Thanks for the quick reply and for the information but how do i specify the correct Version of python for invoke ai? It allways seems to default to the newest Version
> 
> I seem to run on the exact same problem. How did you specify the version to use?

I wasn't able to get it working it now spits out an error that pip3 has a update but it is one version older from which it want's to update even tho my system has the newest pip3 version
