### ISSUE TITLE
[bug]: readline error on Windows

### ISSUE THREAD

**Issue by SoftologyPro** [invoke-ai/InvokeAI#2422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24GB

### What happened?

*** Python 3.10.8
*** Windows 10
*** Created a new empty InvokeAITest directory and changed into it
*** Your instructions had to be tweaked to work under Windows as follows...

git clone https://github.com/invoke-ai/InvokeAI.git
python -m venv invokeai_venv
invokeai_venv\scripts\activate.bat
python -m ensurepip --upgrade
python -m pip install --upgrade pip
cd invokeai
copy environments-and-requirements\requirements-win-colab-cuda.txt requirements.txt
pip install .
python ldm\invoke\configure_invokeai.py --yes

Gives the following error...

```
Loading Python libraries...

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\invokeaitest\InvokeAI\ldm\invoke\configure_invokeai.py:58 in <module>                         │
│                                                                                                  │
│    55 assert os.path.exists(Dataset_path),"The configs directory cannot be found. Please run t   │
│    56                                                                                            │
│    57 Datasets = OmegaConf.load(Dataset_path)                                                    │
│ ❱  58 completer = generic_completer(['yes','no'])                                                │
│    59                                                                                            │
│    60 Config_preamble = '''# This file describes the alternative machine learning models         │
│    61 # available to InvokeAI script.                                                            │
│                                                                                                  │
│ D:\invokeaitest\invokeai_venv\lib\site-packages\ldm\invoke\readline.py:402 in generic_completer  │
│                                                                                                  │
│   399 def generic_completer(commands:list)->Completer:                                           │
│   400 │   if readline_available:                                                                 │
│   401 │   │   completer = Completer(commands,[])                                                 │
│ ❱ 402 │   │   readline.set_completer(completer.complete)                                         │
│   403 │   │   readline.set_pre_input_hook(completer._pre_input_hook)                             │
│   404 │   │   readline.set_completer_delims(' ')                                                 │
│   405 │   │   readline.parse_and_bind('tab: complete')                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: module 'readline' has no attribute 'set_completer'

(invokeai_venv) D:\invokeaitest\InvokeAI>
```

**Comment by mickr777** [comment]
Try

invokeai_venv\scripts\activate.bat
cd invokeai
pip install --use-pep517 .
python ldm\invoke\configure_invokeai.py --yes

**Comment by SoftologyPro** [comment]
No difference using --use-pep517

**Comment by mickr777** [comment]
is you prompt showing -  (invokeai_venv) PS C:\>  after activating the venv?

if not use invokeai_venv\scripts\activate
instead of invokeai_venv\scripts\activate.bat

**Comment by SoftologyPro** [comment]
Yes, the venv is activated and the prompt updates.

OK, using 
python scripts\preload_models.py --yes
and then 
python scripts/invoke.py --web
gets it working again.

The preload_models takes much longer though.  Is that doing an "all" download rather than a "recommended"?  Any easy way to do a recommended instead?

**Comment by mickr777** [comment]
--run should just download recommended models

**Comment by SoftologyPro** [comment]
OK, thanks for all your help.  It is working as expected again.
