### ISSUE TITLE
[bug]: InvokeAI taking years to generate on Version 2.3.0+a0

### ISSUE THREAD

**Issue by xNico013** [invoke-ai/InvokeAI#2429]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS

Windows

### GPU

amd

### VRAM

64GB

### What happened?

I tried using the new version 2.3.0+a0 to install some new custom models. But I have the issue that its taking years to generate images now. I got a good GPU and a lot of VRAM and normally it takes 6-7 seconds for 50 steps to generate 1 image. With version v2.2.5 everything generates smooth and quick but with this new version it takes about over an hour just for 1 image.

So why do I need to use 2.3.0+a0 and not just stay with the v2.2.5 version? 
In v2.2.5 a lot of custom models dont work. Like Deliberate for example. I tried everything to get it working but failed over and over again. In 2.3.0+a0 the custom model problem vanishes. I can use any model and even safetensor files work.

**Comment by Titanium2099** [comment]
same but on mac for me

**Comment by andreybukharov** [comment]
Same. I see that it's only loads the processor and don't use any of videochips. 
![YQAZa5y1jPo](https://user-images.githubusercontent.com/77421333/215021648-7aaad16a-deb5-41a0-a463-830191cbf1b8.jpg)

**Comment by codsec** [comment]
Same to me, and im using win11

**Comment by than0107** [comment]
where did you find 2.3.0 version please? Could you share with me? They don't have it in the latest release download page. I only found it in the guide book. I am looking for textual inversion and version 2.2.x don't have it.
