### ISSUE TITLE
[bug]: (WebUI) Using the [DEL] key sometimes deletes two images from gallery at once

### ISSUE THREAD

**Issue by mcbexx** [invoke-ai/InvokeAI#2437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8

### What happened?

InvokeAI 2.2.5, Windows 10, Tested in Firefox and Chrome (latest versions).

I noticed that after using the arrow keys to move between images, pressing the [DEL] key on an image in the gallery view will often delete the next image in line as well. The reproduction of the bug is a bit wonky, as it does not happen all the time (or I have not nailed down the exact conditions), but these steps should help to track down the issue:

1. "Confirm on Delete" needs to be turned off in the options
2. Use the arrow keys to move left or right between images (it seems the more rapidly you switch between images, the more likely an additional image will be deleted, as if an index is lagging behind?)
3. Press the DEL key. In most cases, the image previous to the image you're deleting will also be removed, depending on the direction you travelled through the gallery. 

I have attached a screen capture video to further document the behaviour (and also, that it's not happening reliably)

In the video, I am moving the cursor around with the arrow keys, stopping at the image "D", then hitting delete.
File "D" is deleted as expected.

As I move the cursor around some more, I am landing on "B". Pressing DEL once, both images "B" and "C" are deleted, "C" being the letter I "travelled over". Had I moved in the other direction, say, from A to C, C and B would have been deleted.

I hope this makes sense.

Edit: I just noticed you should also be able to see the additional Delete request pop up in the console window

### Screenshots

https://user-images.githubusercontent.com/56156474/215087642-cfcb60be-7693-4909-b502-439f7c172fcc.mp4

**Comment by dwlovell** [comment]
I experience this as well and I have to go into the recycle bin to recover some files as a result. I have started just deleting files from the file system outputs folder because I cannot trust the web ui anymore.
