### ISSUE TITLE
[bug]: frontend app crashes at start (empty screen)

### ISSUE THREAD

**Issue by remixer-dec** [invoke-ai/InvokeAI#2438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

32

### What happened?

After the server starts and I try to navigate to http://127.0.0.1:9090, I see an empty screen and an error in console.

<summary>Error in Chromium</summary>
<details>
<pre>
index.be0f03f1.js:formatted:5296 TypeError: Cannot read properties of undefined (reading 'description')
    at lt.memoizeOptions.resultEqualityCheck (index.be0f03f1.js:formatted:59670:18)
    at index.be0f03f1.js:formatted:34975:15
    at d (index.be0f03f1.js:formatted:34925:23)
    at index.be0f03f1.js:formatted:34981:26
    at d (index.be0f03f1.js:formatted:34925:23)
    at l (index.be0f03f1.js:formatted:57697:21)
    at index.be0f03f1.js:formatted:57714:20
    at Object.useSyncExternalStore (index.be0f03f1.js:formatted:5173:21)
    at rn.useSyncExternalStore (index.be0f03f1.js:formatted:479:23)
    at TG.useSyncExternalStoreWithSelector (index.be0f03f1.js:formatted:57721:1
</pre>
</details>

<summary>Error in Firefox</summary>
<details>
<pre>
TypeError: n[i] is undefined
    a_e index.be0f03f1.js:66171
    _ index.be0f03f1.js:38623
    d index.be0f03f1.js:38574
    T index.be0f03f1.js:38629
    d index.be0f03f1.js:38574
    l index.be0f03f1.js:63768
    o index.be0f03f1.js:63783
    useSyncExternalStore index.be0f03f1.js:4662
    useSyncExternalStore index.be0f03f1.js:422
    useSyncExternalStoreWithSelector index.be0f03f1.js:63795
    r8e index.be0f03f1.js:63835
    s_e index.be0f03f1.js:66191
    B_ index.be0f03f1.js:4177
    JF index.be0f03f1.js:7278
    XF index.be0f03f1.js:6976
    ine index.be0f03f1.js:6970
    s5 index.be0f03f1.js:6959
    $7 index.be0f03f1.js:6692
    qF index.be0f03f1.js:6631
    R index.be0f03f1.js:556
    te index.be0f03f1.js:590
    EventHandlerNonNull* index.be0f03f1.js:603
    <anonymous> index.be0f03f1.js:724
</pre>
</details>

### Additional context

Just updated today, to commit 1ceb7a60db8018502c560ba58a57d1981be54d3f

**Comment by remixer-dec** [comment]
If you cannot reproduce this issue, try using incognito mode. Possibly it is related to patchmatch initialization failure, since that module is enabled by default, and [import issues](https://github.com/invoke-ai/InvokeAI/blob/main/ldm/invoke/patchmatch.py#L26) are not [handled correctly](https://stackoverflow.com/a/3131251)

**Comment by psychedelicious** [comment]
Hi, you'll probably need to reset your browser's localStorage:
- Start invokeai and go to http://127.0.0.1:9090
- Open your browser's console and run `localStorage.clear()`

Note that this will reset the local parameters you have set, as well as canvas state.

**Comment by remixer-dec** [comment]
This bug appears in incognito mode, which means localStorage is already clean

**Comment by psychedelicious** [comment]
Ah, sorry, missed that. Maybe the frontend bundle needs to be rebuilt. I can do that tonight.

Just a heads up, main is not expected to be stable except for tagged releases.
