### ISSUE TITLE
[bug]: ERROR: Could not find a version that satisfies the requirement clipseg (from invokeai)

### ISSUE THREAD

**Issue by Exagram** [invoke-ai/InvokeAI#2446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

11GB

### What happened?

I am trying to run [Step 6. Run PIP](https://invoke-ai.github.io/InvokeAI/installation/020_INSTALL_MANUAL/#pip-install) but am getting error:
```
pip --python invokeai install --use-pep517 .
Processing /home/REDACTED/Documents/repos/InvokeAI
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting getpass-asterisk
  Downloading getpass_asterisk-1.0.1-py3-none-any.whl (6.8 kB)
Collecting test-tube
  Downloading test_tube-0.7.5.tar.gz (21 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting gfpgan
  Downloading gfpgan-1.3.8-py3-none-any.whl (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.2/52.2 kB 474.4 kB/s eta 0:00:00
Collecting imageio-ffmpeg
  Downloading imageio_ffmpeg-0.4.8-py3-none-manylinux2010_x86_64.whl (26.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.9/26.9 MB 8.2 MB/s eta 0:00:00
Collecting flask-cors
  Downloading Flask_Cors-3.0.10-py2.py3-none-any.whl (14 kB)
Collecting picklescan
  Downloading picklescan-0.0.7-py3-none-any.whl (10 kB)
Collecting torch-fidelity
  Using cached torch_fidelity-0.3.0-py3-none-any.whl (37 kB)
ERROR: Could not find a version that satisfies the requirement clipseg (from invokeai) (from versions: none)
ERROR: No matching distribution found for clipseg
```

```
python --version
Python 3.9.5
```

**Comment by lmcdougall** [comment]
I am having a similar issue on intel OSX Darwin Kernel Version 21.6.0: Mon Dec 19 20:44:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_X86_64.
ERROR: Ignored the following versions that require a different python version: 2.2.4.5 Requires-Python <3.11,>=3.9; 2.2.4.6 Requires-Python <3.11,>=3.9; 2.2.4.7 Requires-Python <3.11,>=3.9; 2.2.5 Requires-Python <3.11,>=3.9; 2.3.0 Requires-Python <3.11,>=3.9; 2.3.0a0 Requires-Python <3.11,>=3.9; 2.3.0a1 Requires-Python <3.11,>=3.9; 2.3.0a2 Requires-Python <3.11,>=3.9; 2.3.0a3 Requires-Python <3.11,>=3.9; 2.3.0rc3 Requires-Python <3.11,>=3.9; 2.3.0rc4 Requires-Python <3.11,>=3.9; 2.3.0rc5 Requires-Python <3.11,>=3.9; 2.3.0rc6 Requires-Python <3.11,>=3.9; 2.3.0rc7 Requires-Python <3.11,>=3.9
ERROR: Could not find a version that satisfies the requirement InvokeAI (from versions: none)
ERROR: No matching distribution found for InvokeAI


>python -V
Python 3.11.2

**Comment by y0himba** [comment]
Same issue here. Causes the update to fail. Windows 11, Python 3.10.9, nVidia 4070 Ti, all latest updates.

**Comment by y0himba** [comment]
![image](https://user-images.githubusercontent.com/11462603/224334302-6f56210c-4da1-449c-b8b7-5f831eedb877.png)

Anyone have anything on this?  Invoke is my go-to for AI imaging, it's frustrating not to be able to have the latest updates.

**Comment by aliasfoxkde** [comment]
Same issue for me on Windows 10 (10.0.19044.2604), and I tried Python 3.9.5 and the recommended 3.10.9, per:
https://invoke-ai.github.io/InvokeAI/installation/010_INSTALL_AUTOMATED/#introduction
