### ISSUE TITLE
[bug]:  pip install -e . on gcp virtual machine

### ISSUE THREAD

**Issue by BenGuse219** [invoke-ai/InvokeAI#2453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

16 GB GDDR6

### What happened?

installed the git repo. 
cd /InvokeAI/docker-build then run "make build"
Running make build on google cloud platform I get the error 

"executor failed running [/bin/sh -c cp environments-and-requirements/requirements-lin-cuda.txt requirements.txt &&     pip install -r requirements.txt &&    pip install -e .]: exit code: 1"

any help would be appreciated.

**Comment by lstein** [comment]
@mauwii Your assistance with this greatly appreciated.

**Comment by mauwii** [comment]
the `Dockerfile.cloud` wasn't updated for months and got removed along with the makefile.

**Comment by mauwii** [comment]
@BenGuse219 Did you try to sync your clone and run the build script (`./docker/build.sh`)?

**Comment by mauwii** [comment]
That's the purpose of the GitHub Issues. When you run into trouble, you can come here and ask ☺️

Did you use `git clone https://github.com/invoke-ai/InvokeAI.git`, or did you download the repo in a zip?

If you `git clone`'d it, just do a `git pull` to get the latest version and try it again to launch `./docker/build.sh`, which should then build the image.

Or if you are just interested in having a working Container, do a `docker pull mauwii/invokeai` 😅 (we well publish a container image soon ™️)

**Comment by BenGuse219** [comment]
@mauwii build.sh worked!! That's so awesome!! now I have other questions. I know that I'm supposed to open another issue. is there any way I could just PM you and you could help me out?

**Comment by mauwii** [comment]
Glad to hear that 👍🏻

If the question is related, just post it here, otherwise please close this Issue and open a new one.

The Problem with PMs would be, that maybe you are not the only one on the Internet having this problen, so solving it in a public space could be a benefit for others as well 🤓

**Comment by BenGuse219** [comment]
Awsome! thank you!
