### ISSUE TITLE
[bug]: Face Tool GFPGAN broken since 1.14.1

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#2454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

Still in version 2.2.5 release, GFPGAN is broken. A quick toggle between images reveals very sharp borders where the face restoration ends. While most people wont see it, I find this quite obvious unfortunately. It was working beautifully before 2.0 release. Please, consider patching 2.x before the big diffuser migration.

thank you,

### Screenshots

V2.0.2
![_Tests-2023-01-29-185021-2991851470](https://user-images.githubusercontent.com/4521415/215363856-a3adb261-a7cf-40c1-a2a3-e9198b008bf6.png)
![_Tests-2023-01-29-185021-2991851470_u](https://user-images.githubusercontent.com/4521415/215363859-73e4e4d3-e29a-4670-869e-80afb56d4791.png)

V2.1.2
![_Tests-2023-01-29-171659-4209212755](https://user-images.githubusercontent.com/4521415/215364044-4aecab8f-f13e-4e27-a594-53d5fdcfbf30.png)
![_Tests-2023-01-29-171659-4209212755_u](https://user-images.githubusercontent.com/4521415/215364046-73153160-51fc-45ee-8488-d9ee219d2d6f.png)

V2.2.5
![_Tests-2023-01-29-165657-105259063](https://user-images.githubusercontent.com/4521415/215364099-0f97313a-8d5e-446c-93a5-13329d658c90.png)
![_Tests-2023-01-29-165657-105259063_u](https://user-images.githubusercontent.com/4521415/215364102-e6606c94-a767-49ce-ac86-39d60a11969b.png)

**Comment by lstein** [comment]
This would be an upstream issue (problem with the GFPGAN library itself). We haven't changed the GFPGAN interface code for months.

**Comment by Neosettler** [comment]
Thank you for your support @lstein. As mentioned before, there is NO noticeable seams in version 1.14.1. Using the same dependencies and weights, invoke 2.x has introduced those seams. Could it be related to the optimization implementation?

**Comment by ResidentChief** [comment]
@lstein - GFPGAN hasn't had an update since Sept 16

**Comment by Neosettler** [comment]
Still considered as one of the biggest issue in InvokeAI to this date. Closing as it doesn't seem to bother anyone else.
