### ISSUE TITLE
[bug]: try to import model of SD_inpaint_v2.0 but having error of "is neither the path to a .ckpt file nor a diffusers repository id. can't import. "

### ISSUE THREAD

**Issue by jakeyahn** [invoke-ai/InvokeAI#2456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What happened?

downloaded "512-inpainting-ema.ckpt" from 
"https://huggingface.co/stabilityai/stable-diffusion-2-inpainting"

and following instruction from 
"https://invoke-ai.github.io/InvokeAI/installation/050_INSTALLING_MODELS/#installation-via-configure_invokeaipy"

but have the error as below. 
need some help!

### Screenshots

![image](https://user-images.githubusercontent.com/82705312/215448775-a5ddbfb6-3417-4471-8fc0-18c7d2dbe07f.png)

**Comment by lstein** [comment]
You can only use stable diffusion v2 models with the 2.3.0 release, and onlly the diffusers version. If you've got the current main version running, or the 2.3.0-rc2 pre-release, then the following should work:

`!import_model stabilityai/stable-diffusion-2-inpainting`

The nice thing is that you only have to indicate the HuggingFace repository ID. You don't have to download it manually. If you have difficulty with this, please post a comment.
