### ISSUE TITLE
[bug]:  "Using device_type cpu" on fresh Windows install (via pip), not able to use GPU

### ISSUE THREAD

**Issue by shalak** [invoke-ai/InvokeAI#2460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24

### What happened?

After following the [manual install via pip](https://invoke-ai.github.io/InvokeAI/installation/020_INSTALL_MANUAL/#introduction), the invokeai starts up with `Using device_type cpu`.

The instructions are not up-to-date with current `main` branch, there's no `.\environments-and-requirements\requirements-lin-win-colab-cuda.txt` file, so I copied the `.\environments-and-requirements\requirements-win-colab-cuda.txt` to `.\requirements.txt`

### Additional context

I have automatic1111's GUI on the same machine, it's pointing to the `invokeai-data\models\ldm\stable-diffusion-v1` model directory for models and it works correctly with GPU.

About a month ago, I was successfully running InvokeAI within WSL2 (using linux requirements file), but WSL2 networking is a nightmare on wheels, so I'm forced to use windows approach.

**Comment by Fabelwesen** [comment]
+1

Same here

**Comment by DrakenZA** [comment]
`for Anyone having the issue "xformers pytorch 1.13.1+cpu instead 1.13.1+cu117" after installing 2.3.0rcx.x or suddenly invoke is using the cpu
(WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for: PyTorch 1.13.1+cu117 with CUDA 1107 (you have 1.13.1+cpu))

Start invoke and choose "Developer Console" (number 6)

paste these comands:
pip uninstall torch (uninstalls pytorch cpu version)

pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117 (this can take a few minutes)

after that close the Terminal and restart Invoke

There will be a new error "Triton not found" or similar (triton is just optimization ~ 5-10% i think, but not available on pip for windows, only linux) it should still work fine 
`

found on discord by user Dschogo#0604

**Comment by BigBlueGX** [comment]
> `for Anyone having the issue "xformers pytorch 1.13.1+cpu instead 1.13.1+cu117" after installing 2.3.0rcx.x or suddenly invoke is using the cpu (WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for: PyTorch 1.13.1+cu117 with CUDA 1107 (you have 1.13.1+cpu))
> 
> Start invoke and choose "Developer Console" (number 6)
> 
> paste these comands: pip uninstall torch (uninstalls pytorch cpu version)
> 
> pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117 (this can take a few minutes)
> 
> after that close the Terminal and restart Invoke
> 
> There will be a new error "Triton not found" or similar (triton is just optimization ~ 5-10% i think, but not available on pip for windows, only linux) it should still work fine `
> 
> found on discord by user Dschogo#0604

I had this issue. Thanks

**Comment by shalak** [comment]
Huh, I believe @DrakenZA's suggestion fixed the issue for me (but I am not 100% sure if that was it :D) Nevertheless, I'm no longer experiencing this issue, let's close the ticket.
