### ISSUE TITLE
[bug]: Txt2Mask is missing initial downscale and uncrop transformation

### ISSUE THREAD

**Issue by spezialspezial** [invoke-ai/InvokeAI#2470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What happened?

The returned mask image is off due to a missing input transform.
The following change produces identical images to the old version on a quick check.
`
if type(image) is str:
    image = Image.open(image).convert('RGB')
    image = ImageOps.exif_transpose(image)
    
img = self._scale_and_crop(image)
#img = transform(img).unsqueeze(0)

inputs = self.processor(text=[prompt],
                        images=[img],  # Note img here
                        padding=True,
                        return_tensors='pt')
`

### Screenshots

old
![txt2mask-old](https://user-images.githubusercontent.com/75758219/216117351-b8e3797a-1d05-481b-aa7d-aab8339c8195.png)

new with fix
![txt2mask-new](https://user-images.githubusercontent.com/75758219/216117360-d4eaa8b6-3a40-4571-ba3f-fed53bbde84a.png)

**Comment by lstein** [comment]
Thanks for finding and fixing the bug! The fix is going into main now.
