### ISSUE TITLE
[bug]: python: command not found

### ISSUE THREAD

**Issue by NathanHazout** [invoke-ai/InvokeAI#2471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cuda

### What happened?

I tried using the `install.sh` script for macOS (M1).  
Even though I have python, it says it cannot find python:

```
xxx@yyy InvokeAI-Installer % which python       
python: aliased to /usr/bin/python3
xxx@yyy InvokeAI-Installer % pyenv version      
3.10.9 (set by /Users/hazout/.pyenv/version)
xxx@yyy InvokeAI-Installer % ./install.sh       
InvokeAI simple installer...

Some of the installation steps take a long time to run. Please be patient.
If the script appears to hang for more than 10 minutes, please interrupt with control-C and retry.
<Press any key to start the install>
Installing for osx-arm64
Python 3.9.6 found at /usr/bin/python3

Select your preferred location for the 'invokeai' directory [/Users/xxx]: /Users/xxx/Dev
./install.sh: line 124: python: command not found
```

Also notice how:
1. My zsh python is 3.10.9
2. The script detects the default macos python 3.9.6
3. But once it tries to execute it doesn't it at all

**Comment by mickr777** [comment]
On line 124 of the the install.sh 

Change
ROOTDIR=$(python -c "from pathlib import Path; print(Path('${ROOTDIR}').expanduser().resolve
to
 ROOTDIR=$(python3 -c "from pathlib import Path; print(Path('${ROOTDIR}').expanduser().resolve

And rerun it

**Comment by NathanHazout** [comment]
worked thanks
