### ISSUE TITLE
[bug]: Patchmatch not loaded

### ISSUE THREAD

**Issue by NathanHazout** [invoke-ai/InvokeAI#2476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

amd

### What happened?

During the first run after installing I got `Patchmatch not loaded`.
I followed the instructions here https://github.com/invoke-ai/InvokeAI/blob/main/docs/installation/060_INSTALL_PATCHMATCH.md and ran  
`brew install opencv` which installed sucessfully.

Still, `Patchmatch not loaded` at every run.

**Comment by lstein** [comment]
@mauwii , could you have a look at this issue? I know that the `brew` recipe has been working for you.

**Comment by mauwii** [comment]
@NathanHazout could you please open a terminal, execute `pkg-config --cflags opencv4` and post your output here?

**Comment by NathanHazout** [comment]
`-I/opt/homebrew/opt/opencv/include/opencv4`

**Comment by mauwii** [comment]
Ok, same for me, that's weird.

Your Verison of InvokeAI is up to date?

Which kind of Installation did you use?

When you write you followed [these](https://invoke-ai.github.io/InvokeAI/installation/060_INSTALL_PATCHMATCH/) instructions, have you done more than just `brew install opencv`?

**Comment by NathanHazout** [comment]
It was the latest available release at the time of the writing (how do I check InvokeAI version?). I am trying to now update to the latest release.

I used the automated install (invoke.sh), and did nothing more than the instructions.

Note however that, as mentioned in this issue https://github.com/invoke-ai/InvokeAI/issues/2723 , there is something strange with python ...

**Comment by NathanHazout** [comment]
(I am reinstalling everything. Both python and invokeai)

**Comment by NathanHazout** [comment]
I wonder if it's related to `opencv`. Notice how it installs 3.11

```
hazout@f4d48896053f invokeai % brew install opencv
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 1 tap (coursier/formulas).
==> Downloading https://formulae.brew.sh/api/formula.json
#=#=#                                                                         
==> Downloading https://formulae.brew.sh/api/cask.json
#=#=#                                                                         

You have 5 outdated formulae installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

==> Fetching dependencies for opencv: cmocka, libvpx, ffmpeg, python@3.11, qt@5 and vtk
```

**Comment by NathanHazout** [comment]
Reinstalling everything fixed the issue.

What changed:
- I installed Python through the official installer instead of pyenv
- I picked python 3.10 instead of 3.9
- Even though brew installed python as a dependency of opencv, it happened AFTER I has already installed a fresh python

**Comment by mauwii** [comment]
Brew is using it's own python environment and normaly you should also set up a alias for brew which is removing the pyenv shims from the PATH:

`alias brew='env PATH="${PATH//$(pyenv root)\/shims:/}" brew'`

[source](https://github.com/pyenv/pyenv#homebrew-in-macos)

But happy to hear that the problem got resolved!
