### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by y0himba** [invoke-ai/InvokeAI#2488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows 10

### GPU

cuda

### VRAM

12GB

### What happened?

Fresh install of Windows 10, fresh install of InvokeAI. After installer completes, I use the batch file to try and start InvokeAI, I get the error below. 

I have installed to the default path, and to C:\tools.  Python is in my path and accessible, 3.10.9. Redist is installed. I have tried manually creating `models.yaml` with no luck. 

```
** InvokeAI will now restart
* Initializing, be patient...
>> Initialization file C:\Tools\InvokeAI\invokeai.init found. Loading...
>> Internet connectivity is True
>> InvokeAI, version 2.3.0-rc1
>> InvokeAI runtime directory is "C:\Tools\InvokeAI"
## NOT FOUND: GFPGAN model not found at C:\Tools\InvokeAI\models\gfpgan\GFPGANv1.4.pth
>> GFPGAN Disabled
## NOT FOUND: CodeFormer model not found at C:\Tools\InvokeAI\models/codeformer\codeformer.pth
>> CodeFormer Disabled
>> ESRGAN Initialized
** An error occurred while attempting to initialize the model: "[Errno 2] No such file or directory: 'C:\\Tools\\InvokeAI\\configs\\models.yaml'"
** This can be caused by a missing or corrupted models file, and can sometimes be fixed by (re)installing the models.
Do you want to run invokeai-configure script to select and/or reinstall models? [y]
```

### Screenshots

See code above.  I can screenshot the DOS box if needed.

### Additional context

This is consistent and reproducible. 

### Contact Details

I am in the Discord y0himba#0001

**Comment by lstein** [comment]
Could you give a screenshot of the directory C:\Tools\InvokeAI\models ?

Thx

**Comment by y0himba** [comment]
![image](https://user-images.githubusercontent.com/11462603/216663740-a8b517e2-0bb7-43fc-8aad-6abb5ffd39d4.png)

This good enough?

**Comment by y0himba** [comment]
I also get the screen below if I choose NOT to reinstall models:
![image](https://user-images.githubusercontent.com/11462603/216664516-8014bef6-11fa-4ac8-9552-2369c145ae68.png)

**Comment by lstein** [comment]
Thanks, this is helpful. It looks like the configure script installed the models somewhere where they don't belong. There should be a file named `GFPGANv1.4.pth` somewhere on your system. Would it be possible for you to use the system's search function to locate it? This will help track down the error.

**Comment by y0himba** [comment]
The only one I can find is the one I have in my backup directory. I am using "Everything" for searching.

**Comment by y0himba** [comment]
System search takes a bit longer, of course. 
![image](https://user-images.githubusercontent.com/11462603/216703330-839602c4-764a-424b-bab4-da33e5e652da.png)

**Comment by y0himba** [comment]
I opened a dos box and ran it from there instead of double clicking.  This was the output at the tail of the install. Weird, because I have a shiny new 4070ti waiting to be abused. With the install batch, do I still need the nVidia SDK or dev kit, what ever it was called?

```
A problem occurred during initialization.
```
The error was: "torch.cuda.is_available() should be True but is False. xformers' memory efficient attention is only available for GPU "
Traceback (most recent call last):
  File "C:\Tools\InvokeAI\.venv\Lib\site-packages\ldm\invoke\config\configure_invokeai.py", line 995, in main
    errors.add(download_weights(opt))
  File "C:\Tools\InvokeAI\.venv\Lib\site-packages\ldm\invoke\config\configure_invokeai.py", line 767, in download_weights
    successfully_downloaded = download_weight_datasets(
  File "C:\Tools\InvokeAI\.venv\Lib\site-packages\ldm\invoke\config\configure_invokeai.py", line 381, in download_weight_datasets
    successful[mod] = _download_repo_or_file(
  File "C:\Tools\InvokeAI\.venv\Lib\site-packages\ldm\invoke\config\configure_invokeai.py", line 394, in _download_repo_or_file
    path = _download_diffusion_weights(mconfig, access_token, precision=precision)
  File "C:\Tools\InvokeAI\.venv\Lib\site-packages\ldm\invoke\config\configure_invokeai.py", line 427, in _download_diffusion_weights
    path = download_from_hf(
  File "C:\Tools\InvokeAI\.venv\Lib\site-packages\ldm\invoke\config\configure_invokeai.py", line 638, in download_from_hf
    model = model_class.from_pretrained(
  File "C:\Tools\InvokeAI\.venv\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 760, in from_pretrained
    model = pipeline_class(**init_kwargs)
  File "C:\Tools\InvokeAI\.venv\Lib\site-packages\ldm\invoke\generator\diffusers_pipeline.py", line 305, in __init__
    self._enable_memory_efficient_attention()
  File "C:\Tools\InvokeAI\.venv\Lib\site-packages\ldm\invoke\generator\diffusers_pipeline.py", line 313, in _enable_memory_efficient_attention
    self.enable_xformers_memory_efficient_attention()
  File "C:\Tools\InvokeAI\.venv\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 875, in enable_xformers_memory_efficient_attention
    self.set_use_memory_efficient_attention_xformers(True, attention_op)
  File "C:\Tools\InvokeAI\.venv\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 900, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "C:\Tools\InvokeAI\.venv\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 891, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "C:\Tools\InvokeAI\.venv\Lib\site-packages\diffusers\models\modeling_utils.py", line 208, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "C:\Tools\InvokeAI\.venv\Lib\site-packages\diffusers\models\modeling_utils.py", line 204, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\Tools\InvokeAI\.venv\Lib\site-packages\diffusers\models\modeling_utils.py", line 204, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\Tools\InvokeAI\.venv\Lib\site-packages\diffusers\models\modeling_utils.py", line 204, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\Tools\InvokeAI\.venv\Lib\site-packages\diffusers\models\modeling_utils.py", line 201, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "C:\Tools\InvokeAI\.venv\Lib\site-packages\diffusers\models\modeling_utils.py", line 208, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "C:\Tools\InvokeAI\.venv\Lib\site-packages\diffusers\models\modeling_utils.py", line 204, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\Tools\InvokeAI\.venv\Lib\site-packages\diffusers\models\modeling_utils.py", line 204, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\Tools\InvokeAI\.venv\Lib\site-packages\diffusers\models\modeling_utils.py", line 201, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "C:\Tools\InvokeAI\.venv\Lib\site-packages\diffusers\models\cross_attention.py", line 117, in set_use_memory_efficient_attention_xformers
    raise ValueError(
ValueError: torch.cuda.is_available() should be True but is False. xformers' memory efficient attention is only available for GPU

= was unexpected at this time.
```

**Comment by ebr** [comment]
@y0himba when you run Invoke using the `C:\Tools\InvokeAI\invoke.bat` script, could you please select "Developer Console", and then run `pip install torch torchvision --extra-index-url=https://download.pytorch.org/whl/cu117`. A proper fix is just about to be merged, but this should get you running without having to reinstall. Let me know how this works out for you.

**Comment by y0himba** [comment]
Requirements already met?

```
(.venv) C:\Tools\InvokeAI>pip install torch torchvision --extra-index-url=https://download.pytorch.org/whl/cu117
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu117
Requirement already satisfied: torch in c:\tools\invokeai\.venv\lib\site-packages (1.13.1)
Requirement already satisfied: torchvision in c:\tools\invokeai\.venv\lib\site-packages (0.14.1)
Requirement already satisfied: typing-extensions in c:\tools\invokeai\.venv\lib\site-packages (from torch) (4.4.0)
Requirement already satisfied: requests in c:\tools\invokeai\.venv\lib\site-packages (from torchvision) (2.28.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\tools\invokeai\.venv\lib\site-packages (from torchvision) (9.4.0)
Requirement already satisfied: numpy in c:\tools\invokeai\.venv\lib\site-packages (from torchvision) (1.23.5)
Requirement already satisfied: certifi>=2017.4.17 in c:\tools\invokeai\.venv\lib\site-packages (from requests->torchvision) (2022.12.7)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\tools\invokeai\.venv\lib\site-packages (from requests->torchvision) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\tools\invokeai\.venv\lib\site-packages (from requests->torchvision) (1.26.14)
Requirement already satisfied: idna<4,>=2.5 in c:\tools\invokeai\.venv\lib\site-packages (from requests->torchvision) (3.4)

[notice] A new release of pip available: 22.3.1 -> 23.0
[notice] To update, run: python.exe -m pip install --upgrade pip

(.venv) C:\Tools\InvokeAI>
```

**Comment by mikeingz** [comment]
From discord : 

```
Start invoke and choose "Developer Console" (number 6)

paste these comands:
pip uninstall torch (uninstalls pytorch cpu version)

pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117 (this can take a few minutes)

after that close the Terminal and restart Invoke

There will be a new error "Triton not found" or similar (triton is just optimization ~ 5-10% i think, but not available on pip for windows, only linux) it should still work fine
```

So yeah, uninstall pytorch first, then install it again.
It fixed everything for me, I was able to update the models and run invoke without any issue after that.

**Comment by y0himba** [comment]
pip uninstall?  I don't know the command to uninstall...sorry.

**Comment by mikeingz** [comment]
Just these 2 commands : 

pip uninstall torch
pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117

**Comment by y0himba** [comment]
Okay, just got home from work.  Was able to run the commands flawlessly, the page now loads, however it is blank. Tried in Firefox, Edge, and Chrome, incognito mode in all 3 to make sure it wasn't an extension causing the issue.

View source shows:

```
<html>
<body>
<!--StartFragment-->

  | <!DOCTYPE html>
-- | --
  | <html lang="en">
  | <head>
  | <script type="module" crossorigin src="./assets/polyfills.1ff60148.js"></script>
  |  
  | <meta charset="UTF-8" />
  | <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  | <title>InvokeAI - A Stable Diffusion Toolkit</title>
  | <link rel="shortcut icon" type="icon" href="./assets/favicon.0d253ced.ico" />
  | <script type="module" crossorigin src="./assets/index.92e1e2e8.js"></script>
  | <link rel="stylesheet" href="./assets/index.8badc8b4.css">
  | <script type="module">try{import.meta.url;import("_").catch(()=>1);}catch(e){}window.__vite_is_modern_browser=true;</script>
  | <script type="module">!function(){if(window.__vite_is_modern_browser)return;console.warn("vite: loading legacy build because dynamic import or import.meta.url is unsupported, syntax error above should be ignored");var e=document.getElementById("vite-legacy-polyfill"),n=document.createElement("script");n.src=e.src,n.onload=function(){System.import(document.getElementById('vite-legacy-entry').getAttribute('data-src'))},document.body.appendChild(n)}();</script>
  | </head>
  |  
  | <body>
  | <div id="root"></div>
  |  
  | <script nomodule>!function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",(function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")\|\|!n)return;e.preventDefault()}),!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();</script>
  | <script nomodule crossorigin id="vite-legacy-polyfill" src="./assets/polyfills-legacy-dde3a68a.js"></script>
  | <script nomodule crossorigin id="vite-legacy-entry" data-src="./assets/index-legacy-eaf1c1d4.js">System.import(document.getElementById('vite-legacy-entry').getAttribute('data-src'))</script>
  | </body>
  | </html>
  |  

<!--EndFragment-->
</body>
</html><!DOCTYPE html>
<html lang="en">
  <head>
    <script type="module" crossorigin src="[./assets/polyfills.1ff60148.js](http://localhost:9090/assets/polyfills.1ff60148.js)"></script>

    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>InvokeAI - A Stable Diffusion Toolkit</title>
    <link rel="shortcut icon" type="icon" href="[./assets/favicon.0d253ced.ico](http://localhost:9090/assets/favicon.0d253ced.ico)" />
    <script type="module" crossorigin src="[./assets/index.92e1e2e8.js](http://localhost:9090/assets/index.92e1e2e8.js)"></script>
    <link rel="stylesheet" href="[./assets/index.8badc8b4.css](http://localhost:9090/assets/index.8badc8b4.css)">
    <script type="module">try{import.meta.url;import("_").catch(()=>1);}catch(e){}window.__vite_is_modern_browser=true;</script>
    <script type="module">!function(){if(window.__vite_is_modern_browser)return;console.warn("vite: loading legacy build because dynamic import or import.meta.url is unsupported, syntax error above should be ignored");var e=document.getElementById("vite-legacy-polyfill"),n=document.createElement("script");n.src=e.src,n.onload=function(){System.import(document.getElementById('vite-legacy-entry').getAttribute('data-src'))},document.body.appendChild(n)}();</script>
  </head>

  <body>
    <div id="root"></div>
    
    <script nomodule>!function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",(function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()}),!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();</script>
    <script nomodule crossorigin id="vite-legacy-polyfill" src="[./assets/polyfills-legacy-dde3a68a.js](http://localhost:9090/assets/polyfills-legacy-dde3a68a.js)"></script>
    <script nomodule crossorigin id="vite-legacy-entry" data-src="./assets/index-legacy-eaf1c1d4.js">System.import(document.getElementById('vite-legacy-entry').getAttribute('data-src'))</script>
  </body>
</html>
```

**Comment by johnson-md** [comment]
@y0himba This has been fixed in https://github.com/invoke-ai/InvokeAI/files/10575654/InvokeAI-installer-v2.3.0-rc2.zip as released by @lstein on discord. Thanks @lstein!
