### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by TrigMan59** [invoke-ai/InvokeAI#2493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What happened?

Hi Folks,

I tried doing the automated installation and it failed telling me it couldn't find the requirements-base.txt file. So, I tried the Manual Installation guide. I installed the Anaconda app (I have Python 3.10 already loaded. I went to the Anaconda command prompt and after the Github installation changed to the InvokeAI directory. I ran the command rmdir src and got back file not found. I ran conda create -f environment-cuda.yml and got back file not found. I then tried activate conda activate invokeai and got a message about listing all discoverable environments. Any ideas what I'm possibly doing wrong here? I was using Stable Diffusion with another model with no problems after installation and setup. Thanks in advance for any and all help provided. I apologize for the newbie question and if I raised it in the wrong forum.

Roger

### Screenshots

![image](https://user-images.githubusercontent.com/124206250/216669514-0c7b3d1a-03cb-4110-a84e-753c1f3adbb3.png)

### Contact Details

roger.tregelles@gmail.com

**Comment by lstein** [comment]
The whole manual installation procedure has changed in 2.3.0. In particular, we no longer support conda. Please see https://github.com/invoke-ai/InvokeAI/blob/v2.3.0-rc2/docs/installation/020_INSTALL_MANUAL.md for the new recipes.

**Comment by TrigMan59** [comment]
Hi lstien,

Thanks so much for the reply to my installation problems. I went to the installation procedures link that you kindly provided. As soon as I read the first sentence, "!!! warning "This is for advanced Users" and then the second sentence. "**python experience is mandatory**" I stopped. I'm by means an Advanced User and have no python experience at this point (I am planning on taking a course in the future). Will the easier Installation Instructions and files found at https://invoke-ai.github.io/InvokeAI/ be updated to allow a complete novice like me to setup and install InvokeAI on my Windows 11 PC eventually? Please let me know, thanks.
