### ISSUE TITLE
[bug]: I cannot access the web based UI, because of WinErr10048.

### ISSUE THREAD

**Issue by mzplati** [invoke-ai/InvokeAI#2494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24GB

### What happened?

I cannot access the web based UI, because of WinErr10048.

### Screenshots

![2023-02-03 13_26_18-Window](https://user-images.githubusercontent.com/124389232/216671063-e2509df7-8fe5-41a6-aa67-260ed5d8e0ce.jpg)

### Contact Details

mzolcinski@platige.com

**Comment by lstein** [comment]
Is it possible that you have another instance of invokeai running on the same machine? This would cause conflicts when the new one tries to bind to the same socket as the current one is running on.

**Comment by psychedelicious** [comment]
InvokeAI uses port 9090 by default. Besides another instance of InvokeAI on the same machine, another web service could be using this port. 

If the issue persists after restarting your computer, and you aren't sure what is using port 9090, you have two options:
- Use a tool like [TCPView](https://learn.microsoft.com/en-us/sysinternals/downloads/tcpview), which is an official Microsoft tool, to figure out what is using port 9090 and stop it or change the port it uses
- Run InvokeAI on a different port e.g. `invokeai --web --port 1234`
