### ISSUE TITLE
[bug]: Loading v2.1 based checkpoints fails

### ISSUE THREAD

**Issue by jammynads** [invoke-ai/InvokeAI#2495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

10

### What happened?

Just installed InvokeAI 2.3.0-rc2, and i still can't load any SD v2.1 based  ckpt/safetensors model. The error is "missing personalization config."

Comparing the yaml files, i see that section seems to be missing from v2-inference-v.yaml so i tested by adding it from v1-inference.yaml but no luck. What should i add there?

All v1.4/v1.5 based models work fine as always.

**Comment by jammynads** [comment]
I also tried using the config file provided with the model(s) in question, resulting in the same error.

**Comment by lstein** [comment]
We only support the diffusers version of 2.X. You can use the `invokeai-configure` tool to download and install the diffusers version. Alternatively, you can launch the commandline tool and issue the command:
```
!import_model stabilityai/stable-diffusion-2-1
```

**Comment by lstein** [comment]
You can also try launching invokeai with the option `--ckpt_convert`, which will automatically convert the 2.1 checkpoint file into a diffusers model, without using extra space.

**Comment by jammynads** [comment]
Thanks, i must have missed that somewhere. Conversion worked, i can now load v2.1 based models again. I hope it will be possible to load them as ckpt/safetensors at some point too, because i don't think i have (yet) seen a single diffusers model available for download on CivitAI for example. Huggingface obviously offers them, but not even nearly all models are there.

Thank you to everyone involved in the project!

**Comment by Neosettler** [comment]
I'm on board with the OP. Please, consider support for 2.x ckpt/safetensors models.

**Comment by lstein** [comment]
You can import any 2.1 ckpt model from civitai or elsewhere using the web model manager, the CLI `!import` command, or the “install models “ option in the `invoke` launcher. It will be autoconverted into diffusers format for use.

**Comment by Neosettler** [comment]
I understand we'd like to turn the page on the legacy formats but given the amount of models available ckpt/safetensors, 2.1 models should be supported natively. How big of a project would that be, config files, what else? @lstein

**Comment by Neosettler** [comment]
btw: would converting to diffuser remove any possible threat from a ckpt?
