### ISSUE TITLE
[bug]: browser based UI is starting into a black screen

### ISSUE THREAD

**Issue by isuewo** [invoke-ai/InvokeAI#2497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

8GB

### What happened?

Using v2.3.0-rc2

I only have diffuser models in the manager and whenever I start the browser based UI I get a black screen. The log says this: 
`** "stable-diffusion-1.5" is not a known model name; falling back to stable-diffusion-1.5.`

It looks like it is trying to load Stable Diffusion 1.5 instead of the last model selected. I worked around this problem for now by renaming one of my diffuser models to stable-diffusion-1.5, which also fixes the black screen

**Comment by lstein** [comment]
You need to label at least one of your files as default...

oh,, I just saw your update. Great!
