### ISSUE TITLE
[canvas beta]: `preserve masked` indicator should stay visible

### ISSUE THREAD

**Issue by keturn** [invoke-ai/InvokeAI#2505]
I got real confused when outpainting and it was painting over the whole bounding box, not just the empty area.

Turns out that I had left "Preserve Mask" checked, but hadn't drawn a mask.

I think the "Preserve Masked" indicator should remain visible even when a non-painting tool (i.e. _Move_) is active.

**Comment by psychedelicious** [comment]
Good catch. I've added this to the canvas status display. It will be in the alert color if it is enabled.

![image](https://user-images.githubusercontent.com/4822129/217510228-f83c276d-2a71-42ef-aa48-149c3e74c2e1.png)
