### ISSUE TITLE
[bug]: documentation missing - 2.3.0-rc2 installation fails if command line tools are not installed

### ISSUE THREAD

**Issue by borderlineinteractive** [invoke-ai/InvokeAI#2509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What happened?

install.sh script based installation of 2.3.0-rc2 fails on macOS M1 if command line tools are not installed, generating a very long error message. The message does point to missing installation of command line tools, but as the message is very long and also states countless other problems, it is first difficult to see what the problem is. 

The problem can be easily solved by typing  "xcode-select --install" in the terminal window.

Proposed solution: The documentation should point out that installation of Xcode command line tools is a prerequisite for installing this version, and/or the script should check for the installation of command line tools and generate a brief, more informative error message.

**Comment by Adreitz** [comment]
If the script can check whether or not the command line tools are installed, then it should be able to just install them itself if they are missing. Less friction for the user.

**Comment by lstein** [comment]
We’ve put the Xcode advice in the welcome banner and the install walk thru. These fixes will be going live soon.

**Comment by mauwii** [comment]
Is this problem still persistent with the current version or can the issue be closed?
