### ISSUE TITLE
[bug]: The web based GUI isnt visible after installing 2.3.0-rc1

### ISSUE THREAD

**Issue by rutvik788845** [invoke-ai/InvokeAI#2511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6

### What happened?

it was installed successfully. (new install not upgrade)
I installed every required file but after launch, it fails to load.

### Screenshots

![image](https://user-images.githubusercontent.com/25553036/216780073-1233a4dd-c502-4330-aa40-2faf03e2de79.png)
![image](https://user-images.githubusercontent.com/25553036/216780091-7dac3eea-c032-4138-ad84-b314b5475859.png)
![image](https://user-images.githubusercontent.com/25553036/216780108-2e4d92bc-4596-4853-adf3-6b61d0257c13.png)

### Contact Details

rp788845@gmail.com

**Comment by lstein** [comment]
This is a known issue. Fixed in RC2-4.
