### ISSUE TITLE
Create Google Colab script 

### ISSUE THREAD

**Issue by NazarYermolenko** [invoke-ai/InvokeAI#2519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

The google colab script which will setup invoke ai web ui

### Alternatives

https://github.com/camenduru/stable-diffusion-webui-colab
Here we have examples of stable diffusion

**Comment by lstein** [comment]
Is the current Google Colab script not working?

**Comment by NazarYermolenko** [comment]
It doesn't allow to run web ui, if I understood correctly the script... I attached example of the script that runs stable-diffusion in colab with web ui link, also one more here for stable-diffusion-2.0 https://colab.research.google.com/github/qunash/stable-diffusion-2-gui/blob/main/stable_diffusion_2_0.ipynb#scrollTo=gId0-asCBVwL
