### ISSUE TITLE
[bug]: Getting Error Messages Installing

### ISSUE THREAD

**Issue by TrigMan59** [invoke-ai/InvokeAI#2520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What happened?

I have the latest versions of Python and the Visual C+ Libraries installed and ran the registry update. I start the install.bat file and I repeatedly get these errors.

*** Installing InvokeAI Requirements ***
Activating environment
updating pip with "C:\Users\roger\invokeai\.venv\Scripts\python"
Looking in links: c:\Users\roger\AppData\Local\Temp\tmpke9x_4a0
Requirement already satisfied: setuptools in c:\users\roger\invokeai\.venv\lib\site-packages (63.2.0)
Requirement already satisfied: pip in c:\users\roger\invokeai\.venv\lib\site-packages (22.2.1)
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'environments-and-requirements/requirements-base.txt'

[notice] A new release of pip available: 22.2.1 -> 23.0
[notice] To update, run: python.exe -m pip install --upgrade pip
Requirements installation failed. See above for errors and check https://invoke-ai.github.io/InvokeAI/installation/INSTALL_AUTOMATED/#troubleshooting for potential solutions.
The installer will exit now.

I already have PIP 23.0 installed. Lstien had kindly recommended in another post how to install InvokeAI manually - https://github.com/invoke-ai/InvokeAI/blob/v2.3.0-rc2/docs/installation/020_INSTALL_MANUAL.md. 

However, I replied that I went to the installation procedures link that he kindly provided. As soon as I read the first sentence, "!!! warning "This is for advanced Users" and then the second sentence. "python experience is mandatory" I stopped. I'm by means an Advanced User and have no python experience at this point (I am planning on taking a course in the future). Will the easier Installation Instructions and files found at https://invoke-ai.github.io/InvokeAI/ be updated to allow a complete novice like me to setup and install InvokeAI on my Windows 11 PC eventually? Please let me know, thanks.

### Screenshots

![image](https://user-images.githubusercontent.com/124206250/216798274-7a61e409-8c5d-4c9e-a92a-15c932146cb6.png)

### Contact Details

roger.tregelles@gmail.com

**Comment by lstein** [comment]
This is very weird. Is the `requirements-base.txt` file not there at all?

There is a new version about to come out. You can try the new installer: https://github.com/invoke-ai/InvokeAI/files/10671597/InvokeAI-installer-v2.3.0-rc6.zip

**Comment by TrigMan59** [comment]
Thanks so much for your reply and the new installer. I upgraded my 3 year old Gaming PC to Windows 11 last week and have had nothing but problems. Yesterday, I did a clean fresh install of Windows 10 from a USB drive. I'll try running the installer tomorrow and let you know if I have any problems getting it setup. Thanks again.
