### ISSUE TITLE
[bug]: WebUI: Del key does not work after aborting the generation.

### ISSUE THREAD

**Issue by Barafu** [invoke-ai/InvokeAI#2525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

If generation of a series of images is aborted, Del key does not work until the delete button is clicked with a mouse. 

1. Set Display In-Progress Images to None.
1. Start generating multiple images. 
1. After several images are generated, press Cancel button to stop mid-image. 
2. Press Del on the keyboard. Nothing happens. 
3. Click Delete button with mouse. Image is deleted.
4. Press Del again. Another image is deleted.

**Comment by psychedelicious** [comment]
@Barafu Thanks for the bug report. I've fixed the problem in #2525.
