### ISSUE TITLE
[bug]: Automated install (Mac) dies on line 124.

### ISSUE THREAD

**Issue by order661015** [invoke-ai/InvokeAI#2531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What happened?

The install dies at line 124, something to do with the root directory setting.  I attempted the manual install, but its at the root directory setting portion of the install that things begin to not work.

**Comment by jere76** [comment]
this might help > #2471

**Comment by lstein** [comment]
Which version are you seeing this bug in?
