### ISSUE TITLE
[bug]: AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by dangbert** [invoke-ai/InvokeAI#2548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cpu

### What happened?

When I ran `/invoke.sh` and choose the CLI, I tried running `--prompt "a student studying in a cyber cafe that's orbiting jupiter"`, and after 50 samples I got the error "AttributeError: 'NoneType' object has no attribute 'replace'", suggesting that the `prompt` variable was None (see screenshot).

I just setup invoke AI for the first time and got this error, so I'm not sure if I used it wrong?

### Screenshots

![image](https://user-images.githubusercontent.com/6439020/216968113-987107d1-0a7a-41fa-b1cc-7252adfd9c5c.png)

### Additional context

Running InvokeAI 2.2.5

**Comment by lstein** [comment]
This is happening from the `invoke>` prompt??

**Comment by lstein** [comment]
I have found and fixed the bug. The fix will appear in the next release candidate.
