### ISSUE TITLE
[bug]: Error on line 34 running configure_invokeai.py on a linux environment on google colab

### ISSUE THREAD

**Issue by MorpheusXX0** [invoke-ai/InvokeAI#2551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What happened?

Traceback (most recent call last) 
/content/drive/MyDrive/InvokeAI/ldm/invoke/config/configure_invokeai.py:34
 in <module>

   31 from transformers import (AutoProcessor, CLIPSegForImageSegmentation, 
    32 │   │   │   │   │   │     CLIPTextModel, CLIPTokenizer)
    33
 ❱ 34 import invokeai.configs as configs
   35 from ldm.invoke.devices import choose_precision, choose_torch_device
   36 from ldm.invoke.generator.diffusers_pipeline import \
   37 │   StableDiffusionGeneratorPipeline
ModuleNotFoundError: No module named invokeai

This error is occurring only after version 2.3 of invoke ai, any tips on how to solve it?

**Comment by lstein** [comment]
Which release candidate is this happening with?

**Comment by MorpheusXX0** [comment]
> Which release candidate is this happening with?

I am using the commit 8a21fc1c507e3b82fc18e6fa8bc885950a1e7f80 from version 2.3-rc6 of Invoke, I have a colab in version 2.2.5 that is working perfectly but from version 2.3 it is giving this error.
