### ISSUE TITLE
[bug]: Textual Inversions Produces Vastly Inferior Results to A1111

### ISSUE THREAD

**Issue by realstevewarner** [invoke-ai/InvokeAI#2554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

I used Automatic1111 to create a .pt embed.  The embed works as expected in Automatic1111.  When used in Invoke, the results are far inferior to what I get in A1111.  I would expect that with the same prompt, same size, same seed, same sampling steps, and same sampler, I would get comparable results.  Perhaps not identical, but comparable.  However this is not the case.  The results in Invoke are consistently worse - much worse - than A1111, indicating that something is happening in Invoke.  I have had similar results with other embeds, but having trained this one, I can say with confidence that it's not the embed.  It's Invoke.

### Screenshots

![image](https://user-images.githubusercontent.com/104595011/217039085-32950e04-0e64-4253-ab0c-24e4dfc4c3a0.png)
![image](https://user-images.githubusercontent.com/104595011/217039548-095a6079-f74c-4c41-992b-1963b4cc392c.png)
![image](https://user-images.githubusercontent.com/104595011/217040002-04e1ed6b-23c0-42ce-acc5-6fa099b4d737.png)
![image](https://user-images.githubusercontent.com/104595011/217040306-ce2ea04b-53ff-4973-b47d-792bdede0859.png)

### Additional context

A related but different issue is that I can't call the embed by using the file name.  I can only call it by using the name that appears in the command line interface.  In A1111, I can call the embed simply by using the file name or the name that appears in the Command Line.

Here's the embed if you'd like to try  it.
[memphis-style.zip](https://github.com/invoke-ai/InvokeAI/files/10667447/memphis-style.zip)

### Contact Details

steve@stevewarner.com, Steve Warner#1284 on Discord

**Comment by hugodopradofernandes** [comment]
About the filename, seems that this changed (filename != from prompt word) when the new embedding manager was implemented in 2.2.5. Now it gets the term from inside the embedding.... the issue is that when we use an intermediate file, if from auto1111 it includes the step (like myterm-20250) and then we have to use it in the prompts. 

Would be good to have an option to revert using the filename

**Comment by lstein** [comment]
Just so I understand, the issue is not with training with the IAI text inversion script but with the same embed file not producing decent results in IAI. Have you compared results using HF concepts files?

Also are you taking advantage of AUTO1111 hypernetworks or other features that we don’t currently support?

**Comment by realstevewarner** [comment]
Correct.   The issue is _not_ with the training, but with the embed not producing comparable results in IAI.  

This is not the only case where I've encountered embeds not performing well in Invoke.  Some came from HF.  Some came from Civit.  In most cases, they "work" meaning they produce some effect.  But the effect is either far less pronounced in Invoke than A1111 or it produces subpar results compared with A1111.  

An embed should produce comparable results (not necessarily identical, but at least aesthetically comparable) in both apps.  Especially when the same Sampler, Steps, CFG, etc. are used.  However the screengrabs above show that this is not the case.  This means the issue is with Invoke, as the .pt file works as expected in A1111.

**Comment by cmdeviant** [comment]
@realstevewarner are you sure you using same base model? In A1111 screenshot model is `v1.5-pruned-emaonly`, while on InvokeAI model is `stable-diffusion-1.5`

**Comment by realstevewarner** [comment]
I'm sure.  Here's a screenshot:

![image](https://user-images.githubusercontent.com/104595011/217576112-c86dcd8b-1f30-4c37-ac65-ba0e1bda4701.png)

In the image above, the Invoke command line shows the path that it's loading the .ckpt file from.  Below you can see a file explorer.  The left side of the explorer shows the file path and file name for the base 1.5 model install along with the file size and date.  On the right of the explorer, you can see the path to the A1111 install folder.  Same base model name, file size and date.  

I'm not sure why Invoke calls it that when A1111 gives the full ckpt file name, but they're definitely the same.
