### ISSUE TITLE
[bug]: Ctrl-C does not send terminate signal to Invoke.bat

### ISSUE THREAD

**Issue by ShaguarWKL** [invoke-ai/InvokeAI#2570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What happened?

Ctrl-C doesn't send termination signal to Invoke.bat for some reason so the only way to terminate Invoke.bat is to close the Terminal Window. CMD, Powershell, Powershell 7 all use the Ctrl-C for SIGINT like all popular shells bash, zsh, and tcsh.

### Screenshots

![WindowsTerminal_2023-02-07_22-57-23](https://user-images.githubusercontent.com/104881834/217296053-8d5768f2-44c4-4d97-a09f-a403bc23c651.png)

**Comment by blessedcoolant** [comment]
Actually does but it takes time to receive it between the polling interval that is required to keep the socketio connection to the frontend allow.

I'm looking into ways to make make the connection threaded somehow but it hasn't been a quick solution.

At the moment its not the biggest priority but if I think of a way to fix this, I'll do it.

**Comment by ShaguarWKL** [comment]
@blessedcoolant no rush. just putting it here. I haven't been able to kill the process in Powershell 7 with ctrl-C in 2.2.5 even if i spam ctrl-c. This is a really minor thing. Just figured I get off my behind and log this into Issues.

**Comment by mauwii** [comment]
Could it be that you need to press CTRL+Shift+C 🤔

**Comment by lstein** [comment]
When I ^C it works but takes a real long time.

**Comment by ShaguarWKL** [comment]
ok i just tested it. If I hold ctrl-c for about 20-30 secs, it works. spamming ctrl-c doesn't work (what I did before)

**Comment by blessedcoolant** [comment]
Another hack is, press Ctrl C and then refresh the frontend. This will reset the polling time releasing the backend and triggering the break signal.

**Comment by lstein** [comment]
I've experienced this issue too. It is very annoying. I'm hoping that
someone with better Windows .bat file programming skills can help out here.

**Comment by blessedcoolant** [comment]
I'm trying to isolate what is blocking it. No luck so far.

**Comment by ShaguarWKL** [comment]
> I'm trying to isolate what is blocking it. No luck so far.

I'm not sure if this will help but the Kohya_SS fork actually added text output when control-c is called in powershell and it is extremely fast to kill the process.

```
❯ aiko
Validating that requirements are satisfied.
All requirements satisfied.
The arguments passed to this script were: --inbrowser --server_port 7878
Load CSS...
Running on local URL:  http://127.0.0.1:7878

To create a public link, set `share=True` in `launch()`.
Keyboard interruption in main thread... closing server.
```

I assume looking for that "Keyboard Interupption" string might help to see how they did this?
[https://github.com/bmaltais/kohya_ss](url)

**Comment by blessedcoolant** [comment]
kohya uses Gradio so I guess gradio handles the exit loop. 

We're moving to FastAPI in our new migration. I expect this to get resolved with that change because then the FastAPI / Socket combination should handle the exception correctly. But if it still persists even after that, I'll probably need to add in a custom API end point that forces a proper shutdown of the app on Ctrl+C
