### ISSUE TITLE
[bug]: /config/models.yaml not being created in right folder

### ISSUE THREAD

**Issue by mickr777** [invoke-ai/InvokeAI#2577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What happened?

During fresh manual install and running - invokeai-configure --root="/userfiles/" --yes 
and after diffusers are download the configs/models.yaml file is not created

**Comment by lstein** [comment]
Is this with RC6?

**Comment by mickr777** [comment]
> Is this with RC6?

Latest git clone from main

> I have been unable to reproduce this on a Linux/CUDA system. Did the script run to completion or was it interrupted during the downloads? The models file doesn't get created until after all models are downloaded correctly. (This is probably a misfeature, actually.)

Yes it is completing the diffuser download and the other models and I am getting the have fun text

**Comment by mickr777** [comment]
@lstein 
ok they are getting created but under a folder /configs/ at root level not under my --root="/userfiles/"

**Comment by ebr** [comment]
@mickr777 :
- when you ran the installation, did you also select `/userfiles/` as the destination directory?
- what is the location of your virtual environment directory? I see a `/venv` in your screenshot - is there another one in `/userfiles`? how about the models - did they end up in `/userfiles/models`?
- could you please see if this still happens if you `export INVOKEAI_ROOT=/userfiles` before running `invokeai-configure`

@lstein i suspect this to be another case of #2064

**Comment by mickr777** [comment]
> * when you ran the installation, did you also select `/userfiles/` as the destination directory?

I used invokeai-configure --root="/userfiles/" --yes to set the root folder

> * what is the location of your virtual environment directory? I see a `/venv` in your screenshot - is there another one in `/userfiles`? how about the models - did they end up in `/userfiles/models`?

I setup the venv outside the userfiles folder so there is no venv folder in /userfiles
and yes all the models are in the /userfiles/models/

> * could you please see if this still happens if you `export INVOKEAI_ROOT=/userfiles` before running `invokeai-configure`

Will try this now

**Comment by ebr** [comment]
Thanks for confirming. The `--root` argument should be taking precedence in this case, but we are only considering the env vars instead. Definitely should be fixed. 

In the meantime, are you able to add the `INVOKEAI_ROOT` variable to your `.bashrc` file as a workaround?

**Comment by lstein** [comment]
> Thanks for confirming. The `--root` argument should be taking precedence in this case, but we are only considering the env vars instead. Definitely should be fixed.
> 
> In the meantime, are you able to add the `INVOKEAI_ROOT` variable to your `.bashrc` file as a workaround?

Do you think you can commit a quick fix tonight? I am done in from writing documentation.

**Comment by mickr777** [comment]
More info if it helps:
When not using export INVOKEAI_ROOT=/userfiles
only invokeai-configure has issues with the config folder location when using --root argument.

invoke.py follows the --root argument correctly and brings up error it cant find the models.yaml in the correct folder eg /userfile/config/, 

if i manually copy from /config/ to /userfiles/config/ invokepy loads fine

**Comment by ebr** [comment]
sorry for the delay on this, it fell off my radar. I'll try to get it sorted this week

**Comment by lstein** [comment]
@ebr we may have a related issue in #2779 .

**Comment by lstein** [comment]
@mickr777 Following up on this old issue, could you give the install process a try using the 2.3.1 release candidate? The instructions in manual install should still work, but you need to provide a specific version to PIP, viz:
```
pip install InvokeAI[xformers]==2.3.1-rc4 --use-pep517 --extra-index-url https://download.pytorch.org/whl/cu117
```

Thanks in advance!
-Lincoln

**Comment by mickr777** [comment]
For me it appears to place it in the right folder, but I used get clone main

> @mickr777 Following up on this old issue, could you give the install process a try using the 2.3.1 release candidate? The instructions in manual install should still work, but you need to provide a specific version to PIP, viz:
> 
> ```
> pip install InvokeAI[xformers]==2.3.1-rc4 --use-pep517 --extra-index-url https://download.pytorch.org/whl/cu117
> ```
> 
> Thanks in advance! -Lincoln

@lstein 

I did fresh manual install using my unraid docker image that uses git clone main and the config folder was created in the --root folder I set

I can try to install it via the pip install 2.3.1-rc4 if you would like

**Comment by lstein** [comment]
I think all should be good now. Thanks for your help.

Lincoln
