### ISSUE TITLE
[bug]: Use Seed and Use Prompt buttons not working on iPad

### ISSUE THREAD

**Issue by lstein** [invoke-ai/InvokeAI#2578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cuda

### What happened?

Recently, possibly since the addition of the negative prompt box, the three metadata retrieval buttons (use prompt, use seed and use all) have not been working on the iPad. The buttons highlight, but do nothing. Other buttons, such as restore faces, are working as expected.

Tested with both Chrome and Safari.

**Comment by blessedcoolant** [comment]
The Use Prompt and Use All were touched for the negative prompts but the Use Seed wasn't changed in anyway. Do the other buttons work? And is this only specific to the iPad?

**Comment by psychedelicious** [comment]
What commit are you on? Maybe something got borked in my big reorganisation commit.

**Comment by lstein** [comment]
I am on 67f892455f6cc0bf798a57ee82b9f0072c6cac17.

You are correct. Use Seed still works. The other buttons (Use Prompt and Use All) no longer work on the iPad, but do work on a desktop browser.

**Comment by psychedelicious** [comment]
Huh. Alright - I'll test on my iPad.
