### ISSUE TITLE
[enhancement]: Add hotkey to Universal Canvas to adjust brush size

### ISSUE THREAD

**Issue by noodlebox** [invoke-ai/InvokeAI#2586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Add a hotkey to allow resizing the brush without moving focus away from the canvas area.

For mouse users, a modifier+scroll wheel input should suffice, though pen/tablet users run into the same issue as mentioned in #2048. A different modifier key paired with a dragging motion as described in #2048 could work here as well. 

Another option is Blender's approach: the `F` hotkey draws a circle visualizing the size of the brush at the cursor, moving the pen/mouse toward or away from the center of that circle adjusts its radius, and tapping/clicking again confirms that new brush size.

**Comment by kenny-kvibe** [comment]
+1

Additionally I wish there was a `wheel-scroll` event on the "brush size slider" element (range/slider).
(And possibly "wheel-scroll" on other range/slider elements, like steps-slider, CFG-slider, width/height-sliders, ...)

**Comment by Millu** [comment]
@noodlebox @kenny-kvibe brush size hotkeys exist 

* "[" to decrease brush size
* "]" to increase brush size

**Comment by kenny-kvibe** [comment]
My keyboard:
"[" = ctrl+alt+F (doesn't work)
"]" = ctrl+alt+G (doesn't work)
