### ISSUE TITLE
[bug]: cant find output from          GPU_FLAGS=all ./docker/run.sh --outdir /data

### ISSUE THREAD

**Issue by BenGuse219** [invoke-ai/InvokeAI#2593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

16 GB GDDR6

### What happened?

looking for a little guidance. Reading through the documentation I can't find any output from running 

GPU_FLAGS=all ./docker/run.sh --outdir /data

the documentation says that default images are stored in (outputs/img-samples/) but since I put /data as the --ourdir I would have expected the output to be in the /data in the pwd. 

This is on a google cloud platform vm if that makes a difference.
Thank you.

**Comment by mauwii** [comment]
The Output is stored on a Docker Volume (name is shown when executing build.sh or run.sh) - but you just gave me the idea to improve this. Will soon™️ be added to #2595

**Comment by BenGuse219** [comment]
@mauwii thanks! I had to ask my buddy what exactly you meant. but I figured it out!! thank you so much! this is all super new to me and it's pretty awesome lol
