### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by livecleo** [invoke-ai/InvokeAI#2610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

32gb

### What happened?

Hi I cannot get this running.
SPECS
 Z690 Aorus Elite DDR4
i9-12900K CPU GPU Nvidea Gforce 3080ti

Python version
Python 3.11.2
3.11.2 Checked in command prompt confirmed
pip 22.3.1 from C:\ProgramFiles\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.752.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip (python 3.11) From command prompt
(( I have tried to instal Python 3.10.9 but unless i get it from the microsoft store Invoke cannot find it and I cannot find that exact version on the microsoft website only 3.10.10. ))

Issue
Batch file closes with option 1 (command line)
Closes with 2 (Browser based UI
Closes with 3 (Run textual inversion)

I am not good with computers but would love some help with this as it seams I have a numpy issue?
When I hit command line help I get below issue

Displaying command line help...
OpenCV bindings requires "numpy" package.
Install it via command:
    pip install numpy
Traceback (most recent call last):
  File "C:\Users\PC3\invokeai\.venv\Lib\site-packages\numpy\core\__init__.py", line 23, in <module>
    from . import multiarray
  File "C:\Users\PC3\invokeai\.venv\Lib\site-packages\numpy\core\multiarray.py", line 10, in <module>
    from . import overrides
  File "C:\Users\PC3\invokeai\.venv\Lib\site-packages\numpy\core\overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\PC3\invokeai\.venv\Scripts\invokeai.exe\__main__.py", line 4, in <module>
  File "C:\Users\PC3\invokeai\.venv\Lib\site-packages\ldm\invoke\CLI.py", line 15, in <module>
    from ldm.generate import Generate
  File "C:\Users\PC3\invokeai\.venv\Lib\site-packages\ldm\generate.py", line 15, in <module>
    import cv2
  File "C:\Users\PC3\invokeai\.venv\Lib\site-packages\cv2\__init__.py", line 11, in <module>
    import numpy
  File "C:\Users\PC3\invokeai\.venv\Lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import core
  File "C:\Users\PC3\invokeai\.venv\Lib\site-packages\numpy\core\__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "C:\Users\PC3\invokeai\.venv\Scripts\python.exe"
  * The NumPy version is: "1.23.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

Press any key to continue . . .

### Contact Details

livecleo@gmail.com

**Comment by gogurtenjoyer** [comment]
Hello!  Here's the latest version of python 3.10 to download - just scroll to the bottom, and select `Windows Installer (64 Bit)` with `Recommended` to the right of it. When you install, make sure to check 'add python.exe to PATH'.

**Comment by livecleo** [comment]
I did that but now it doesnt find it again when I check the version in CMD

**Comment by livecleo** [comment]
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

**Comment by livecleo** [comment]
For me only the ones downloaded from mictrosoft store are working. When I search I see others with this issue

**Comment by livecleo** [comment]
I dont know if this helps but when I try to run Python via command prompt "Python" it opens the microsft store as if I have not instaled it. But honestly I did instal it..

**Comment by livecleo** [comment]
I tried also instaling it there and now I get the version come up but I still get that error where it just closes no matter what I click

**Comment by livecleo** [comment]
Cmd - Python gets 
C:\Users\PC3>python
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

Why does it say CMD? I have Intel CPU and Nvidea GPU

**Comment by livecleo** [comment]
Dont worry it seams to be working now. I had to reinstal it after I resinstaled the correct python

**Comment by livecleo** [comment]
I think this is the only error im having now can anyone help?

Starting the InvokeAI browser-based UI..
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
