### ISSUE TITLE
[bug]: Web GUI Model Management

### ISSUE THREAD

**Issue by mile6919** [invoke-ai/InvokeAI#2619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What happened?

GUI (Model management) does not seem to see Safetensors models in my Models-folder. It sees only ckpt-files. How to overcome this?

### Screenshots

<img width="755" alt="ScreenShot 2023-02-10 at 20 31 03" src="https://user-images.githubusercontent.com/36359398/218170098-750e3b81-27a9-4ef5-a9b1-704955f92e2b.PNG">

**Comment by i3oc9i** [comment]
did you try to refresh the content of the folder using the refresh button ?

**Comment by thirstyhouseplant** [comment]
Please provide more detail. What is the pathname of the directory your `safetensors` are in? Which specific models *are* successfully appearing on refresh?
