### ISSUE TITLE
[bug]: OS X: 2.3.0 crash when attempting to generate any image

### ISSUE THREAD

**Issue by twopiearr** [invoke-ai/InvokeAI#2626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What happened?

I have only installed 1.5, 2.1 base, and inpainting 1.5. Attempting to generate an image with any of these models crashes Python with the following error:

>> Image Generation Parameters:

{'prompt': 'an astronaut riding a horse on the moon', 'iterations': 5, 'steps': 20, 'cfg_scale': 7.5, 'threshold': 0, 'perlin': 0, 'height': 768, 'width': 768, 'sampler_name': 'k_euler_a', 'seed': 53301818, 'progress_images': False, 'progress_latents': True, 'save_intermediates': 5, 'generation_mode': 'txt2img', 'init_mask': '...', 'seamless': False, 'hires_fix': False, 'variation_amount': 0}

>> ESRGAN Parameters: False
>> Facetool Parameters: False
>> Setting Sampler to k_euler_a (EulerAncestralDiscreteScheduler)
Generating:   0%|                                         | 0/5 [00:00<?, ?it/s]/Users/<user>/invokeai/.venv/lib/python3.10/site-packages/diffusers/schedulers/scheduling_euler_ancestral_discrete.py:263: UserWarning: The operator 'aten::nonzero' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  step_indices = [(schedule_timesteps == t).nonzero().item() for t in timesteps]
                                                                               /AppleInternal/Library/BuildRoots/5b8a32f9-5db2-11ed-8aeb-7ef33c48bc85/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:724: failed assertion `[MPSNDArray initWithDevice:descriptor:] Error: total bytes of NDArray > 2**32'
zsh: abort      ./invoke.sh
(base) <user>@MacBook-Air invokeai % /opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
<user>

**Comment by twopiearr** [comment]
after taking a closer look at the error, I turned "randomize seed" off and tried specifying a seed of 346 and running a generation, which worked. Then I hit the Shuffle button, let it pick one and tried again, which also worked. Finally I turned randomize seed back on, and it worked again. Not certain what to make of this.

**Comment by Adreitz** [comment]
Check out my bug report #2624. Is it possible that you were experiencing that? I didn't try 2.1 base in my testing, but it's possible that it would fail at 768x768 just as 1.5 does.

**Comment by i3oc9i** [comment]
I also reported this as #2444

as workaround don't use diffuser models for now, instead use .ckpt or .safetensors model

**Comment by twopiearr** [comment]
Thanks all for the feedback. Since this is a known issue I'm closing this report as redundant.
