### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by tanzim5** [invoke-ai/InvokeAI#2629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12 GB

### What happened?

Opening Invoke.bat shows this error and crashes.

Please enter 1, 2, 3, 14, 5, 6 or 7: [2] 2
Starting the InvokeAI browser—based I-Jl..
A matching Triton is not available, some optimizations will not be enabled .
Error caught was: No module named 'triton '
* Initializing, be patient. ..
>> Initialization file C:\Users\Tanzim\InvokeAI\invokeai.init found. Loading...
An exception has occurred: No closing quotation 

### Screenshots

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/13457096/218260247-724477b3-7b78-413c-b3c9-9bfb9ac4e4b8.gif)

**Comment by thirstyhouseplant** [comment]
Can you paste the full contents of your invokeai.init file? There's an error there about an unmatched quotation mark.
