### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by r6spy** [invoke-ai/InvokeAI#2631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24gb

### What happened?

When selecting Accurate instead of Fast preview, when going in larger resolutions then 768x768 (for example 1600x1600) the UI breaks and doesn't render the image, switching to Fast fixes the issue.

**Comment by thirstyhouseplant** [comment]
When you say the webui doesn't render the image, do you mean that it fails to generate an output entirely? Or does it simply fail to return the progress images?

**Comment by r6spy** [comment]
it completely doesn't render, it gives an error in the code








 >-------- Оригинално писмо --------

 >От: thirstyhouseplant ***@***.***

 >Относно: Re: [invoke-ai/InvokeAI] [bug]:  (Issue #2631)

 >До: invoke-ai/InvokeAI  

 >Изпратено на: 15.02.2023 08:17



 
 
  
  
  
When you say the webui doesn't render the image, do you mean that it fails to generate an output entirely? Or does it simply fail to return the progress images?
