### ISSUE TITLE
Do not download the NSFW filter model if the user disabled NSFW filter

### ISSUE THREAD

**Issue by mockinbirdy** [invoke-ai/InvokeAI#2634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

New installer:

`Do you want NSFW filter enabled by default? y/n -n`
`*proceeds to install NSFW filter*`

Just why? If I need this filter I can manually download it and install it (if it's not possible now it should be an option then). Why would invokeai do unnecessary downloads when I already told it I don't need nor want them. Just make it skip this step.

**Comment by ebr** [comment]
Could you please clarify - it does not *enable* the filter for you, but the issue is that it downloads the model?

**Comment by psychedelicious** [comment]
I noticed the same thing. Regardless of your selection when prompted to enable the nsfw checker - yes or no - the model is downloaded. It should probably not be downloaded if you say no.

**Comment by mockinbirdy** [comment]
> the issue is that it downloads the model

Yes, that is the issue.

> It should probably not be downloaded if you say no

My thoughts as well.

**Comment by ebr** [comment]
Thanks.
When implementing this we need to provide an option to install the nsfw filter model if the user decides to enable it at a later point.

**Comment by psychedelicious** [comment]
Still need to be addressed.

**Comment by psychedelicious** [comment]
Still need to be addressed.

**Comment by Kevin-Bourn** [comment]
STILL NEEDS TO BE ADDRESSED
