### ISSUE TITLE
am I missing something?[bug]: 

### ISSUE THREAD

**Issue by magaspah** [invoke-ai/InvokeAI#2635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12

### What happened?

I d/l the update files and completed it.

Yet I'm still missing the new additions as in t. inversion, new neg box, etc.
Can't even find which version this bad boy is running.

What am I missing?

Thank you

**Comment by ebr** [comment]
which version shows next to the InvokeAI logo when you're running the web UI?

I'd recommend installing a fresh copy - it seems the upgrade didn't work for you.

**Comment by magaspah** [comment]
There is no number next to the logo.  Just going to do a fresh install.  Thank you

![Screenshot 2023-02-14 035051](https://user-images.githubusercontent.com/112981301/218730302-b10ae126-893a-4526-9947-bc0a0ea92746.png)

**Comment by ebr** [comment]
@magaspah how did that work out for you?

**Comment by magaspah** [comment]
It worked like a charm! Thank you
