### ISSUE TITLE
[bug]: Installer can't find protobuf

### ISSUE THREAD

**Issue by ihauh** [invoke-ai/InvokeAI#2637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What happened?

Hello, I ran the new 2.3 install.sh to update an existing setup but it exits with the following errors. Protobuf is installed both inside the environment and outside.

```
File "/usr/local/lib/python3.10/dist-packages/tb_nightly-2.12.0a20221201-py3.10.egg/tensorboard/compat/proto/event_pb2.py", line 7, in <module>
    from google.protobuf.internal import enum_type_wrapper
ModuleNotFoundError: No module named 'google.protobuf'
```

Maybe it's a version problem, but I'm not able to figure it out.
Thank you for any help!

### Screenshots

![screen](https://user-images.githubusercontent.com/50181761/218308565-eb4a4a25-5387-4a31-a9c1-fb3e4bd6d782.png)

**Comment by ebr** [comment]
it seems you've got Torch installed in your global environment (`dist-packages`). I suspect this is throwing some kind of a wrench in the works. It's not a configuration we test for. Could you please try to `sudo pip uninstall torch` (while NOT in an active virtual env), and then re-run the installer?

**Comment by ihauh** [comment]
I did `sudo pip uninstall torch` and re-ran the installer, still error. I don' understand why it would still use the system python setup while inside the virtual env.
![screen2](https://user-images.githubusercontent.com/50181761/218693719-3ca7b9f4-a4d1-422c-a8d7-bf59e4b2f794.png)

**Comment by ihauh** [comment]
I should add that the installation and the resulting invoke.sh seems to be working "fine", I'm just not sure if those errors are affecting the setup.

**Comment by ebr** [comment]
Interesting, it seems the error is actually coming from `tensorboard`. You might want to try the same uninstall/reinstall step with that package. Ultimately you don't want any additional packages installed in your global system environment. But good to know that the application actually works for you despite the errors.

**Comment by ihauh** [comment]
According to pip tensorboard was not installed on my system, but I found a directory and removed it to be safe. Anyway the installation script now doesn't use other packages but it's the same error. (I also switched to the default directory in case it had anything to do with it, this was an attempt at a "clean" install.)

```

Loading Python libraries...

Traceback (most recent call last):
  File "/home/___/invokeai/.venv/lib/python3.10/site-packages/accelerate/tracking.py", line 41, in <module>
    from torch.utils import tensorboard
  File "/home/___/invokeai/.venv/lib/python3.10/site-packages/torch/utils/tensorboard/__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/home/___/invokeai/.venv/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py", line 9, in <module>
    from tensorboard.compat.proto.event_pb2 import SessionLog
  File "/home/___/invokeai/.venv/lib/python3.10/site-packages/tensorboard/compat/proto/event_pb2.py", line 5, in <module>
    from google.protobuf import enum_type_wrapper
ModuleNotFoundError: No module named 'google.protobuf'

```
