### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by ericwenger7** [invoke-ai/InvokeAI#2638]
### Is there an existing issue for this?
yes
- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What happened?

'k_dpm_2_a' sampling mode fails with the following message
Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.

**Comment by psychedelicious** [comment]
This is a known upstream issue with diffusers. There is a fix which we expect to be in the next diffusers release.
