### ISSUE TITLE
[bug]: Cannot Generate Image

### ISSUE THREAD

**Issue by DevoidSloth** [invoke-ai/InvokeAI#2640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What happened?

I tried to make a image using Stable Diffusion 2.1 768 and my it stopped at 100% saying "Could not generate image."  Are there any solutions for this?

**Comment by ebr** [comment]
what happens if you try again - are you able to reproduce the issue? is there any output in the logs you could copy and paste (or screenshot) to help troubleshoot?

**Comment by thirstyhouseplant** [comment]
Smells like a possible VRAM limitation. What dimensions were you trying to generate at, and with what model?

**Comment by JPPhoto** [comment]
I believe this is the same issue as #2672. After image generation is complete, you need a lot of memory for a brief period to decode the underlying representation into an image.
