### ISSUE TITLE
[enhancement]: Extract prompt from png files

### ISSUE THREAD

**Issue by DavidCWGA** [invoke-ai/InvokeAI#2643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

david@gloveraoki.net

### What should this feature add?

invokeai used to come with "images2prompt.py". This is gone in 2.3.0.

I'd like to request that it is returned, or, a similar feature is added.

**Comment by DavidCWGA** [comment]
Should feature requests expire?

**Comment by Void2258** [comment]
This is basically the functionality of the "PNG info" tab in A1111, and would be handy to have, both form CMD and in the UI. currently you have to import images into img2img to get the same basic effect, but this adds them to the imports folder, which may not be desirable for quickly checking things.
