### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by sunilw** [invoke-ai/InvokeAI#2654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

24GB

### What happened?

When attempting to install on linux, I hit two issues.

**Issue one**
The installation instructions for linux give this instruction:
`pip install InvokeAI[xformers] --use-pep517 --extra-index-url https://download.pytorch.org/whl/cu117`

Entering this command yields the following response:
`zsh: no matches found: InvokeAI[xformers]`

**Issue two**
Just to test, I ommitted '[xformers]' from the command.
As a result, the installation procedure ran, but errored out with this message:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 5.1.5 requires pyqt5<5.13, which is not installed.
spyder 5.1.5 requires pyqtwebengine<5.13, which is not installed.
conda-repo-cli 1.0.4 requires pathlib, which is not installed.
anaconda-project 0.10.2 requires ruamel-yaml, which is not installed.
```

The next line following the error output has this:
`Successfully installed InvokeAI-2.3.0...`

However, nothing is installed in the invokeAI directory.

**Comment by gogurtenjoyer** [comment]
With zsh you have to escape out [ and ] - so for example, try `pip install "InvokeAI[xformers]" --use-pep517 --extra-index-url https://download.pytorch.org/whl/cu117`
