### ISSUE TITLE
[bug]: Update using 2.3.0 update.bat fails

### ISSUE THREAD

**Issue by vestlink** [invoke-ai/InvokeAI#2662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12

### What happened?

First i tried to update an newly re/installed 2.3.0 using the update.bat, but I get the following error

```
This script will update InvokeAI and all its dependencies to "https://github.com/invoke-ai/InvokeAI/archive/latest.zip".
If you do not want to do this, press control-C now
Press any key to continue . . .
The system cannot find the path specified.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     63      0 --:--:-- --:--:-- --:--:--    63
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

[notice] A new release of pip available: 22.3.1 -> 23.0
[notice] To update, run: python.exe -m pip install --upgrade pip
Installation of requirements failed. See https://invoke-ai.github.io/InvokeAI/installation/INSTALL_AUTOMATED/#troubleshooting for suggestions.
Press any key to continue . . .

```

**Comment by Adreitz** [comment]
I don't think v.2.3.0 has an update.sh script. It's probably left over from 2.2.5 and does not work anymore. I got the same error when I tried. Delete that script and use the 2.3.0 installer instead.

**Comment by thirstyhouseplant** [comment]
If you have indeed installed v2.3.0 as stated, then there is nothing to update; that is the latest release.

**Comment by mauwii** [comment]
please download a new installer, docs can be found here: https://invoke-ai.github.io/InvokeAI/installation/010_INSTALL_AUTOMATED/

Feel free to close the issue 😅
