### ISSUE TITLE
[bug]: web UI keeps disconnecting for no reason

### ISSUE THREAD

**Issue by ethereak** [invoke-ai/InvokeAI#2664]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cpu

### What happened?

When using the web UI I use the text to image option and configure and enter the prompt I want. After about 30 seconds of nothing  I get this as the image preview (attached below) and then after about 3 minutes of that, the web UI says it has disconnected but on my console its still working and generating pictures. Any solutions?
![download](https://user-images.githubusercontent.com/43956463/218854874-de2447b7-9049-4299-a798-9d2b819da6ab.png)

**Comment by psychedelicious** [comment]
What version of invokeai are you on?

Has it ever worked correctly or did this just start happening randomly?

Also, try resetting the web ui from settings (gear icon at top right).

**Comment by thirstyhouseplant** [comment]
If you're on cpu only, image generation will take a *long time*, longer than the timeout window for the webui. It will reconnect once generation is complete. 

If you're stuck with cpu only (I was too, for a long time), I recommend using the command line interface. It won't necessarily be faster, but you will at least see feedback in the console.

**Comment by ethereak** [comment]
oh ok guess Theres nothing i can do then lmao thx for the help :)

**Comment by psychedelicious** [comment]
Closed as the issue was due to hardware specs.
