### ISSUE TITLE
[bug]: rand_perlin_2d() fails

### ISSUE THREAD

**Issue by JPPhoto** [invoke-ai/InvokeAI#2674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What happened?

Images no longer need to be a multiple of 64 wide/tall (it's 8 now). Requesting an image with some dimensions (e.g. 792x328) and perlin noise causes a crash in `rand_perlin_2d()` at `n00 = dot(tile_grads([0, -1], [0, -1]), [0,  0]).to(device)`.

**Comment by JPPhoto** [comment]
@pbaylies I'm happy to code up a fix if you can provide some insight. It's possible that the parameters passed in to the noise generator are no longer valid.

**Comment by pbaylies** [comment]
Personally I'd pad it to 64 and then crop it back :shrug:

**Comment by JPPhoto** [comment]
Not the worst solution. Is there something in your code that forces it to be a multiple of 64, and can we change that?

**Comment by pbaylies** [comment]
Yes, you could try lowering `res` - my thought is that not changing the generation should be more consistent and faster.

**Comment by JPPhoto** [comment]
Cropping it seems reasonable. I've also noticed that for wide or tall images, the perlin noise is stretched out. Is that something we can change?

**Comment by pbaylies** [comment]
So `res` is the period of the noise, you can change it as long as the size is a multiple of `res`.
