### ISSUE TITLE
[bug]: ValueError: invalid variable 'INVOKEAI_ROOT'

### ISSUE THREAD

**Issue by kable2k** [invoke-ai/InvokeAI#2684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

10gb

### What happened?

I tried running the Source Installer and this error popped up and stopped the installation:

"EnvironmentFileNotFound: 'G:\InvokeAI\environment.yml' file not found"

So I found a post that directed me to manually install instead, I followed the instructions with no issues up to step 6:
Install the InvokeAI Package. The --extra-index-url

"pip install InvokeAI[xformers] --use-pep517 --extra-index-url https://download.pytorch.org/whl/cu117"

This error pops up after waiting a while:

".py", line 613, in _expand_attrs
          val = subst_vars(val, self.config_vars)
        File "C:\Users\Roman\AppData\Local\Temp\pip-build-env-clewyotg\overlay\Lib\site-packages\setuptools\_distutils\util.py", line 214, in subst_vars
          raise ValueError(f"invalid variable {var}")
      ValueError: invalid variable 'INVOKEAI_ROOT'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pathtools
Failed to build test-tube npyscreen pudb basicsr urwid validators filterpy future jsonmerge urwid-readline pathtools
ERROR: Could not build wheels for test-tube, npyscreen, pudb, basicsr, urwid, validators, filterpy, future, jsonmerge, urwid-readline, pathtools, which is required to install pyproject.toml-based projects"

### Screenshots
![Screenshot 2023-02-17 013151](https://user-images.githubusercontent.com/90956864/219412215-d25d9b17-50e7-4965-ab45-46a8030735d2.png)

### Contact Details

discord: kable#6151

**Comment by psychedelicious** [comment]
Hi,

Something isn't quite right as we do not use `environment.yml` files any more. You must have an old install, or were using an old installer.

Also, it looks like you didn't activate the venv before installing.

If you are not comfortable with git and python, I strongly suggest using the automated installer: https://invoke-ai.github.io/InvokeAI/installation/010_INSTALL_AUTOMATED/#introduction

Probably best to delete any existing installation files first.
