### ISSUE TITLE
[contributing]: commit messages and quantity

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#2693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

As the project grows, I wonder if we might be interested in setting some guidelines for commit messages and commit quantity (squashing PRs down to a few meaningful commits).

A popular system is [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary). All commits messages must follow a particular format. The type of change may optionally be followed by its scope, before a description. The description should be written in such a way that it would fit after the words "If this commit was merged, it would...".

Here are a few examples:
- `feat(diffusers): add controlnet support`
- `build: exclude docs changes from actions`
- `chore(ui): build frontend bundle` :sweat_smile: 

This can be enforced, if desired, by a pre-commit hook.

We may also want to have some soft rules about commit quantity. That would probably mean making an effort to have a single commit for a unit of change. Small fixes would always have a single commit, while large features may have several. What should be avoided are commits like "wip" or "more whatevers".

Rules and guidelines like these could help our git history to be far more approachable and useful, but could make contributing a bit more tedious, especially for new contributors.

**Comment by hipsterusername** [comment]
I think anything and everything we can do to be clear about how to contribute is helpful. Cleaner commits will help with understanding changes as the project grows, and it also encourages other good hygiene elsewhere.

One 👍 here!

**Comment by JPPhoto** [comment]
I'm all in favor of increasing quality of commit messages but not a huge fan of enforcing a particular style of commit message through a pre-commit hook. I do like the "complete the sentence" *suggestion* for non-merging commits.
