### ISSUE TITLE
[bug]: not detecting python

### ISSUE THREAD

**Issue by kiingkiller** [invoke-ai/InvokeAI#2719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6

### What happened?

when i go to run the installer, it says that python is not installed but i uninstalled python and installed the version comended but i still get this error
"No python was detected on your system. Please install Python version 3.9.0 or higher. We recommend Python 3.10.9 from https://www.python.org/downloads/release/python-3109/
The installer will exit now."

**Comment by gogurtenjoyer** [comment]
Please make sure to check the box labelled 'add python.exe to PATH' when in the python installer.

**Comment by dogsitter1** [comment]
Same thing is happening to me. I have unstalled it and reinstalled it making sure the check mark is on add python.exe to PATH.
Is there a file I can copy the path on.

**Comment by jtoronto** [comment]
I tried everything, including adding it to the path manually, rebooting, etc... I had to install Python 3.10 from the Microsoft Store and now it seems to work.

**Comment by dogsitter1** [comment]
Jtoranato 
I finally got it after unistall of python and reinstall. I am so happy, I've been reading everything for days!

**Comment by Asfandyar-Khan-2022** [comment]
I've tried to uninstall and reinstall python. I've even changed the directory of the installation file and still nothing works :(

**Comment by Asfandyar-Khan-2022** [comment]
Just found the solution. You need to go to Settings > Manage App Execution Aliases and disable python.exe and python3.exe

**Comment by aromalsp** [comment]
[gogurtenjoyer](https://github.com/gogurtenjoyer) commented [on Feb 19, 2023](https://github.com/invoke-ai/InvokeAI/issues/2719#issuecomment-1435808318)
Please make sure to check the box labelled 'add python.exe to PATH' when in the python installer.

This worked for me! Thank you
