### ISSUE TITLE
[bug]: Can we change the using device type from CPU to CUDA / GPU for InvokeAI??

### ISSUE THREAD

**Issue by Shimaadakunn** [invoke-ai/InvokeAI#2735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

I have a NVIDIA GTX 1060 3Go and I installed InvokerAI via the installer.
When the installer asked me if I would either choose to run on my GPU or CPU, I have chosen the option "choose for me".
When I run the invoker.bat file, it's really slow and I checked the option and I saw that it was using CPU.
Is there any way to change the parameters and use GPU instead of CPU????

Will really help me
Thanks a lot for those who are willing to help me

### Screenshots

![image](https://user-images.githubusercontent.com/89693356/220003053-e086be72-b689-4370-9d75-06fadf7630bb.png)

### Contact Details

lcombaret@hotmail.co.jp

**Comment by ebr** [comment]
To answer the question: you can reinstall over the existing installation, and select the GPU option explicitly. The installer should uninstall the CPU version of `torch` and install the GPU version.

However, you will not have much luck generating images with your GPU, I'm afraid. 3GB is not enough VRAM.
