### ISSUE TITLE
[bug]: Delete image does not work inside docker container

### ISSUE THREAD

**Issue by SaberD** [invoke-ai/InvokeAI#2737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What happened?

When running InvokeAI in docker the delete image button generates an error:
```bash
>> System config requested
>> Delete requested "outputs/000001.c8936250.2677842585.png"


Traceback (most recent call last):
  File "/usr/src/InvokeAI/lib/python3.9/site-packages/invokeai/backend/invoke_ai_web_server.py", line 854, in handle_delete_image
    send2trash(path)
  File "/usr/src/InvokeAI/lib/python3.9/site-packages/send2trash/plat_other.py", line 211, in send2trash
    trash_move(path_b, dest_trash, topdir)
  File "/usr/src/InvokeAI/lib/python3.9/site-packages/send2trash/plat_other.py", line 117, in trash_move
    os.rename(src, op.join(filespath, destname))
OSError: [Errno 18] Invalid cross-device link: b'/data/outputs/000001.c8936250.2677842585.png' -> b'/data/.Trash-1000/files/000001.c8936250.2677842585 1.png'
```

my volume mounting points are:
```yaml
volumes:
      - ./volumes/data:/data
      - ./volumes/models:/data/models
      - ./volumes/outputs:/data/outputs
```

ref send2trash [issue 26](https://github.com/arsenetar/send2trash/issues/26)

My suggestion is just to catch this error and delete the file directly, and not send it to trash when inside docker.

**Comment by lstein** [comment]
Thanks for reporting this. @mauwii could you take a look

**Comment by mauwii** [comment]
> my volume mounting points are:
>
> ```yaml
> volumes:
>       - ./volumes/data:/data
>       - ./volumes/models:/data/models
>       - ./volumes/outputs:/data/outputs
> ```

I have some questions @SaberD:

- Which python image are you using?
- How is it getting built?
- How do you spin up the Container?

**Comment by SaberD** [comment]
The image is main-cuda built with the github action: https://github.com/invoke-ai/InvokeAI/blob/7fadd5e5c4fe1956c75d97ded02bcc42c04c4ae4/.github/workflows/build-container.yml

I use a fork with a docker compose file: https://github.com/SaberD/InvokeAI-docker/blob/c871be15456296840b78a6a4ed4f37e1aecc1ac9/docker-compose.yml#L4

But I also get this error when using the run.sh script: https://github.com/invoke-ai/InvokeAI/blob/7fadd5e5c4fe1956c75d97ded02bcc42c04c4ae4/docker/run.sh

**Comment by mauwii** [comment]
That's pretty strange, since I do not get this error (building the image with build.sh or using the prebuilt one, run it with run.sh) 🤔

The Docker-compose issue does imho not belong to our repository, but I can imagine that the way your docker compose created the volume is the problem in the end.

**Comment by SaberD** [comment]
Where is your .Trash0001 located in the docker container when its working. Is it then in `/data/.Trash-1000` or `/data/outputs/.Trash-1000`?

I see in the run.sh script that you delete .Trash* from outputs/ folder, but mine ends up in the data/ folder.

**Comment by SaberD** [comment]
Got it working.
Outputs folder has to be mounted as part of the data folder volume.
My working mouting points are
```yaml
volumes:
      - ./volumes/data:/data
      - ./volumes/models:/data/models
```

where the mounted data folder has a preexisting outputs folder.
