### ISSUE TITLE
[bug]: I want to change the default lauching model on Stable Diffusion

### ISSUE THREAD

**Issue by Shimaadakunn** [invoke-ai/InvokeAI#2740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What happened?

I want to Stable diffusion to run realisticVisionV13_v13.ckpt model instead of sd-v1-4.ckpt model when I launch the stable diffusion.
I search in the ui-config.json file but there is nowhere that specifies the lauching model 

I will greatful for your help

**Comment by lstein** [comment]
Find the `invokeai` folder. Within it there's a text file called `invokeai.init`. Using a text editor, open it up and add this line to the bottom:

```
--model realisticVisionV13_v13
```

If this isn't the short name for your model then change it appropriately.

Alternatively, you can launch the command-line client and type this command:
```
!edit_model realisticVisionV13_v13
```

It will ask you a series of questions ending with `Do you want to make this the default model?`
