### ISSUE TITLE
[bug]: error downloading all files

### ISSUE THREAD

**Issue by Mosch21** [invoke-ai/InvokeAI#2759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What happened?

While installing (second instance, first was on another drive and I didnt knew how to move it securely) this time I chose to download all models but it always gets an error when trying to download "models\diffusers\models--runwayml--stable-diffusion-v1-5\snapshots\39593d5650112b4cc580433f6b0435385882d819\text_encoder\pytorch_model.bin' at 'models\diffusers\models--runwayml--stable-diffusion-v1-5\snapshots\39593d5650112b4cc580433f6b0435385882d819\text_encoder\pytorch_model.bin"
Further down a few more errors happen, which I will show in the screenshots
![4](https://user-images.githubusercontent.com/126023306/220461070-f3ad543e-93b2-4630-9831-8b2df1edf216.PNG)
![3](https://user-images.githubusercontent.com/126023306/220461072-dc99274a-d09e-478f-ae76-7d644af091fa.PNG)
![2](https://user-images.githubusercontent.com/126023306/220461077-99105c95-8a1e-4359-b969-31e370688eb9.PNG)
![1](https://user-images.githubusercontent.com/126023306/220461080-82ae298b-50dd-41f0-af88-daa42dc6fae0.PNG)

### Additional context

I feel like the lower errors starting with "During handling of the above exception, another exception occurred:" appeared more often each time I tried the reinstallation.

### Contact Details

moritz@webwohnzimmer.de

**Comment by MeatHammmer** [comment]
So I'm not the only one
