### ISSUE TITLE
[bug]: Trojan identified by Windows Defender in vanilla InvokeAI installation (Codeformer.pth)

### ISSUE THREAD

**Issue by ThomasMetcalf** [invoke-ai/InvokeAI#2773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What happened?

Windows Defender is identifying a trojan in the Codeformer.pth module included in the default installations of InvokeAI. (it's also included in the default installation of Automatic1111 Webui).

Scanning the file itself does not return a result. However unarchiving the file and scanning the resulting folder flags up two files.

You can test this yourself by unarchiving the Codeformer.pth file, and scanning the extracted folder with Windows Defender. (using Windows 10 here)

Trojan:Win32/Sirefef!cfg

\models\codeformer\archive\data\94338023080784

\models\codeformer\archive\data\94338067080304

This issue has been replicated with at least one other user.

**Comment by psychedelicious** [comment]
Thanks for the report. Did the A1111 codeformer model also trigger the AV?

**Comment by hipsterusername** [comment]
Yes, it does (reported by another user this morning in Discord)

**Comment by ThomasMetcalf** [comment]
Yes, A111 also had exactly the same scan result (also a fresh install, the day before). The same two files identified.

**Comment by MeatHammmer** [comment]
so can one just go in there and delete them? or will that cause a bunch of problems?

**Comment by lstein** [comment]
You can delete the files, however don't try to use the "codeformer" face
restoration feature. It will crash without its models. You can use GFPGAN
if you need face restoration. Frankly, Stable Diffusion models do faces
really well now and I haven't had to use face restoration for some time.

Lincoln

**Comment by mickr777** [comment]
FYI

94338023080784
https://www.virustotal.com/gui/file/9cdbea152c4e9160dec5d922cd6b70cbd7c8c6b855d2b4bb87c64d11ac754f58?nocache=1

94338067080304
https://www.virustotal.com/gui/file/ced21996122c236d79a15bce8f249563291a5c281f50f870cfcf99ce65c6e833?nocache=1

**Comment by psychedelicious** [comment]
FWIW, the general consensus seems to be that this is a false positive.

It is not an InvokeAI-created file; it comes from a face restoration model called CodeFormer.

I don't have Windows available, but `clamav` (whose database is mostly windows virus definitions) does not detect anything:
```
Scanning /home/bat/invokeai/models/codeformer/codeformer.pth
/home/bat/invokeai/models/codeformer/codeformer.pth: OK

----------- SCAN SUMMARY -----------
Known viruses: 8653721
Engine version: 0.103.6
Scanned directories: 1
Scanned files: 1
Infected files: 0
Data scanned: 0.00 MB
Data read: 359.19 MB (ratio 0.00:1)
Time: 8.399 sec (0 m 8 s)
Start Date: 2023:02:25 10:28:47
End Date:   2023:02:25 10:28:55
```

Seems only Windows Defender detects this while other AV do not flag it.

I think users will need to decide for themselves if they want to have this file on their system or not. Deleting it means you cannot use CodeFormer for face restoration.

**Comment by CorwinCodes** [comment]
This is still an issue
