### ISSUE TITLE
[bug]: when 'scale before processing' is enabled, the console log warns that it's not

### ISSUE THREAD

**Issue by gogurtenjoyer** [invoke-ai/InvokeAI#2777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

16GB

### What happened?

In unified canvas, when inpainting with a mask in a bounding box and 'scale before processing' set to either Auto or Manual, I get a warning like this in the console:

```
>> using provided input image of size 192x192
>> WARNING: img2img and inpainting may produce unexpected results with initial images smaller than 512x512 in both dimensions
>> using provided input image of size 192x192
```

However, the unified canvas UI shows the 'scaled bounding box' label and it is set to the intended 512x512. In addition, it does actually scale the image, so this seems to be an incorrect warning.

<img width="203" alt="Screenshot 2023-02-23 at 1 43 42 PM" src="https://user-images.githubusercontent.com/36354352/221037166-0364dde8-2ca3-4eeb-917f-65dc16c047c1.png">

### Additional context

This was tested on main, updated today.

**Comment by psychedelicious** [comment]
@lstein 

Inpainting works correctly, it's just the user feedback in terminal session that needs to be corrected.

This message is displaying the init image size, but it should display `inpaint_width` and `inpaint_height` if those parameters were provided:
`>> using provided input image of size 192x192` 

This is an issue in `generate.py`: https://github.com/invoke-ai/InvokeAI/blob/f9a1afd09cbc0569ac55231a72b2b52240cf78e9/ldm/generate.py#L1197

I don't think we need to worry about fixing this though, it's not a big issue.
