### ISSUE TITLE
[bug]: New GUI for configure script breaks with windows paths

### ISSUE THREAD

**Issue by jordanramstad** [invoke-ai/InvokeAI#2783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

After updating to the latest in main invoke seems to be messing up the output paths set during configuration. Also if an extra `\` is added to the end, Invoke just breaks and will fail to load at all (which will happen when using the auto complete feature).

It with confused paths will still work, but it will put everything under the `ldm` folder with a folder name that is the full path with all `\` and drive letters stripped out.

**Comment by lstein** [comment]
I discovered this last night and pushed a fix for it. This should be fixed in RC3. Could you confirm which version you tried?

**Comment by jordanramstad** [comment]
Just what is latest on `main`, noticed it a few mins ago, and updated my branch to see if there was already a fix but didn't seem so.

If you are aware and there is a fix somewhere, then its likely fine, I can work with how it is, just wanted to make sure it didn't sneak into a release :P
