### ISSUE TITLE
Multi-Language Support 支援多國語系

### ISSUE THREAD

**Issue by wastu01** [invoke-ai/InvokeAI#2793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

larry1130.wang@gmail.com

### What should this feature add?

Can it support traditional language (Taiwan) in future ?

**Comment by psychedelicious** [comment]
Hi @wastu01 , 

We would thrilled to support Traditional characters for our users in Taiwan, Hong Kong, Macau, and anywhere else who uses it. Are you interested in working on the translation?

If so, please sign in to [Weblate](https://hosted.weblate.org/engage/invokeai/) with your GitHub account. Then you can work on the Chinese Traditional characters translation here, which I just added: https://hosted.weblate.org/projects/invokeai/web-ui/zh_Hant/

Your translation will be credited to your GitHub account.

**Comment by wastu01** [comment]
Got it

**Comment by psychedelicious** [comment]
We have traditional Chinese as a language now

**Comment by wastu01** [comment]
ok
