### ISSUE TITLE
VMWare Workstation fails 16GB Ram/8GB vRam

### ISSUE THREAD

**Issue by Tom-Neverwinter** [invoke-ai/InvokeAI#280]
```
(ldm) C:\Stable Diffusion\Stable-Diffusion-main\Stable-Diffusion-main>python scripts/dream.py
* Initializing, be patient...

Loading model from models/ldm/stable-diffusion-v1/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Using half precision math. Call with --full_precision to use more accurate but VRAM-intensive full precision.
>> Setting Sampler to k_lms
model loaded in 32.52s

* Initialization done! Awaiting your command (-h for help, 'q' to quit)
dream> machine god
Traceback (most recent call last):
  File "scripts/dream.py", line 543, in <module>
    main()
  File "scripts/dream.py", line 103, in main
    main_loop(t2i, opt.outdir, opt.prompt_as_dir, cmd_parser, infile)
  File "scripts/dream.py", line 230, in main_loop
    t2i.prompt2image(image_callback=image_writer, **vars(opt))
  File "c:\stable diffusion\stable-diffusion-main\stable-diffusion-main\ldm\simplet2i.py", line 282, in prompt2image
    torch.cuda.torch.cuda.reset_peak_memory_stats()
  File "C:\Users\Tom_N\anaconda3\envs\ldm\lib\site-packages\torch\cuda\memory.py", line 249, in reset_peak_memory_stats
    return torch._C._cuda_resetPeakMemoryStats(device)
RuntimeError: invalid argument to reset_peak_memory_stats
```

VMware SVGA 3D is probably not recognized {3D graphics acceleration support is turned on}

further research shows this is probably beyond the scope of this project and a limitation of pytorch

**Comment by lstein** [comment]
You could try commenting out the offending line (torch.cuda.torch.cuda.reset_peak_memory_stats()). This is just for performance reporting. I'm pretty sure it'll just crash somewhere else, though. You have the 3D graphics acceleration support turned on?

**Comment by tildebyte** [comment]
I can't imagine that the VMware SVGA 3D device will be usable in any way (although *maybe* CPU in virt will work... slowly...) - it is *literally* a virtualized SVGA-compliant 3D driver, no compute caps of any kind.

- **If** you have supported hardware on the *host*, you might be able to do device pass-through (I'm not *certain* that this is possible with VMWare)
- You obviously have virt working on the host, so another thing to try would be docker - device pass-through **definitely** works from a properly configured container

In any case, knowing your host environment (OS & version, GPU type & VRam amount at a minimum), and guest environment (same info) would be very helpful.

**Comment by tildebyte** [comment]
Your best bet for reasonable performance (i.e. using your GPU) is going to be a bare-metal [install on Windows](https://github.com/lstein/stable-diffusion/wiki/Easy-peasy-Windows-install)

**Comment by tildebyte** [comment]
There were a couple of egregious errors in that wiki page, which I found and fixed just now, so if you hit any errors - try starting again 😞
