### ISSUE TITLE
[bug]: UI not honoring vertical symmetry when no horizontal symmetry is applied

### ISSUE THREAD

**Issue by JPPhoto** [invoke-ai/InvokeAI#2802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What happened?

2.3.1 - The UI won't apply vertical symmetry when set if horizontal symmetry isn't also set.

**Comment by JPPhoto** [comment]
@psychedelicious Do you want to close this since the fix is *somewhere*? Or leave it open as a reminder?

**Comment by psychedelicious** [comment]
Hmm, it's fixed in main but not user-facing I think. I say close it since it was you who requested it and not a non-technical end-user

**Comment by JPPhoto** [comment]
Will do. Let's remember to make sure this works when 3.0's released.
