### ISSUE TITLE
[bug]: pip install command for 2.3.1 doesn't work

### ISSUE THREAD

**Issue by farisalamin** [invoke-ai/InvokeAI#2803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

32GB

### What happened?

`pip install --use- [InvokeAI-installer-v2.3.1+rc2.zip](https://github.com/invoke-ai/InvokeAI/files/10810720/InvokeAI-installer-v2.3.1%2Brc2.zip) pep517 --upgrade InvokeAI`

Command doesn't work, I'm no expert but I think somebody added a markdown link to it by accident. I used `pip install --upgrade --use-pep517 InvokeAI`.

**Comment by lstein** [comment]
I think this is in the release notes. I'll fix now.
