### ISSUE TITLE
[bug]: upsample causes error 

### ISSUE THREAD

**Issue by jhm235** [invoke-ai/InvokeAI#2805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12

### What happened?

UnboundLocalError: local variable 'upsampler' referenced before assignment , when trying to upsample image

### Screenshots

last image is shown and error message

### Additional context

repeatedly happened

**Comment by lstein** [comment]
Thanks for the bug report and sorry this is happening. Could you:

1. Indicate the version of InvokeAI you are using (upper left corner of the WebUI)
2. Post the upscaler parameters you are setting, including which algorithm to use, strength, scale and denoising
3. Is this happening when you do upscaling during generation (in the settings panel on the left), or after generating the image as a postprocessing operation (the expand button on the top)

**Comment by maxaudron** [comment]
I'm also running into this issue with `2.3.1.post1`, All default settings in the webui, 4x scaling, 0.75 denoise and strength, there is no selection for algorithm. It also happens both during and after image generation.
![upscaling panel](https://user-images.githubusercontent.com/10994794/221440621-931b4f6e-f610-4e34-94b5-c36d27d01b15.png)

**Comment by maxaudron** [comment]
The problem seems to be that the `realesrgan/realesr-general-wdn-x4v3.pth` does not get downloaded automaticly. After i rerun the configuration, it was downloaded and upscaling works again.

**Comment by jhm235** [comment]
after reconfigure and fully upload of all models the problem was solved . maybe it needs a special model to download during install for upscale. happened after updating to actual windows install zip file

**Comment by manessa** [comment]
>> ESRGAN Parameters: {'level': 2, 'denoise_str': 0.4, 'strength': 0.75}
>> Facetool Parameters: False
>> using provided input image of size 1920x1080
>> image will be resized to fit inside a box 1216x576 in size.
>> after adjusting image dimensions to be multiples of 64, init image is 1024x576
100%|██████████████████████████████████████████████████████████████████████████████████| 29/29 [00:06<00:00,  4.16it/s]
>> Error loading Real-ESRGAN:██████████████████████████████████████████████████████████| 29/29 [00:06<00:00,  4.18it/s]
Traceback (most recent call last):
  File "L:\invokeai2.3.5\.venv\lib\site-packages\ldm\invoke\restoration\realesrgan.py", line 52, in process
    upsampler = self.load_esrgan_bg_upsampler(denoise_str)
  File "L:\invokeai2.3.5\.venv\lib\site-packages\ldm\invoke\restoration\realesrgan.py", line 25, in load_esrgan_bg_upsampler
    from realesrgan.archs.srvgg_arch import SRVGGNetCompact
  File "L:\invokeai2.3.5\.venv\lib\site-packages\realesrgan\__init__.py", line 2, in <module>
    from .archs import *
  File "L:\invokeai2.3.5\.venv\lib\site-packages\realesrgan\archs\__init__.py", line 2, in <module>
    from basicsr.utils import scandir
ModuleNotFoundError: No module named 'basicsr'

>> Real-ESRGAN Upscaling seed:1031395378, scale:2x, tile:400, denoise:0.4
Generating:   0%|                                                                                | 0/1 [00:07<?, ?it/s]
local variable 'upsampler' referenced before assignment


Traceback (most recent call last):
  File "L:\invokeai2.3.5\.venv\lib\site-packages\invokeai\backend\invoke_ai_web_server.py", line 1344, in generate_images
    self.generate.prompt2image(
  File "L:\invokeai2.3.5\.venv\lib\site-packages\ldm\generate.py", line 565, in prompt2image
    results = generator.generate(
  File "L:\invokeai2.3.5\.venv\lib\site-packages\ldm\invoke\generator\base.py", line 124, in generate
    image_callback(image, seed, first_seed=first_seed, attention_maps_image=attention_maps_image)
  File "L:\invokeai2.3.5\.venv\lib\site-packages\invokeai\backend\invoke_ai_web_server.py", line 1191, in image_done
    image = self.esrgan.process(
  File "L:\invokeai2.3.5\.venv\lib\site-packages\ldm\invoke\restoration\realesrgan.py", line 73, in process
    output, _ = upsampler.enhance(
UnboundLocalError: local variable 'upsampler' referenced before assignment
