### ISSUE TITLE
[bug]: Server error: 'LatentDiffusion' object has no attribute 'inner_model'

### ISSUE THREAD

**Issue by telles0808** [invoke-ai/InvokeAI#2812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What happened?

After rising the steps accidentaly to 1000 and CFG to 200, this happened and now it's not working anymore.

2023-02-25T14:49:01-0300:

Image generation requested: {"prompt":"(telles0808 in a landscape (((scene of a guy holding a fish in amazon river)))), a fishing rod and a boat, digital painting art by Greg Rutkowski++ and antgerm++ and Gianluca Rolli++, trending on art station, 8k, anime style, very high detailed brown eye color, bigger eyes, very high detailed hair, high detailed, high quality, 64k, high detailed hands, bokeh, sharp colors, strong painting strokes [ugly, tiling, poorly drawn hands, poorly drawn feet, poorly drawn face, out of frame, mutation, mutated, extra limbs, extra legs, extra arms, disfigured, deformed, cross-eye, body out of frame, blurry, bad art, bad anatomy, blurred, text, watermark, grainy, adam's apple, furrow eyebrows, doppel, duplicated face, asian, asiatic, chinese]","iterations":1,"steps":150,"cfg_scale":75,"threshold":0,"perlin":0,"height":512,"width":512,"sampler_name":"k_dpmpp_2_a","seed":967315720,"progress_images":false,"progress_latents":true,"save_intermediates":5,"generation_mode":"txt2img","init_mask":"","hires_fix":false,"seamless":false,"variation_amount":0}

2023-02-25T14:49:04-0300:

Server error: 'LatentDiffusion' object has no attribute 'inner_model'

### Screenshots

![image](https://user-images.githubusercontent.com/2066086/221371965-ae73ffde-7820-4828-94b8-da098411b514.png)

### Additional context

2023-02-25T14:49:01-0300:

Image generation requested: {"prompt":"(telles0808 in a landscape (((scene of a guy holding a fish in amazon river)))), a fishing rod and a boat, digital painting art by Greg Rutkowski++ and antgerm++ and Gianluca Rolli++, trending on art station, 8k, anime style, very high detailed brown eye color, bigger eyes, very high detailed hair, high detailed, high quality, 64k, high detailed hands, bokeh, sharp colors, strong painting strokes [ugly, tiling, poorly drawn hands, poorly drawn feet, poorly drawn face, out of frame, mutation, mutated, extra limbs, extra legs, extra arms, disfigured, deformed, cross-eye, body out of frame, blurry, bad art, bad anatomy, blurred, text, watermark, grainy, adam's apple, furrow eyebrows, doppel, duplicated face, asian, asiatic, chinese]","iterations":1,"steps":150,"cfg_scale":75,"threshold":0,"perlin":0,"height":512,"width":512,"sampler_name":"k_dpmpp_2_a","seed":967315720,"progress_images":false,"progress_latents":true,"save_intermediates":5,"generation_mode":"txt2img","init_mask":"","hires_fix":false,"seamless":false,"variation_amount":0}

2023-02-25T14:49:04-0300:

Server error: 'LatentDiffusion' object has no attribute 'inner_model'

### Contact Details

telles.gabriel@gmail.com

**Comment by telles0808** [comment]
Restarting the UI returned it and now is working again.

**Comment by lstein** [comment]
Whewwww! Glad you got it figured out.
