### ISSUE TITLE
[enhancement]: Tool tips with breaf descriptions

### ISSUE THREAD

**Issue by telles0808** [invoke-ai/InvokeAI#2813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

telles.gabriel@gmail.com

### What should this feature add?

This feature aims to enhance the user experience in our software, making it more intuitive and easy to use. The idea is to add "tool tips" that appear when the user hovers over a button or software element with their mouse. These boxes should contain short and clear descriptions of what each button or element does, helping users to better understand the software's functionalities and use it more efficiently. We believe that this will reduce the learning curve for new users and help increase overall user satisfaction. The feature should be easily activated or deactivated in the software settings, so that users can choose whether they want to see the tool tips or not.

### Alternatives

short descriptions

**Comment by psychedelicious** [comment]
We started something like this but it never was fully fleshed out.

@blessedcoolant What do you think about just adding tooltips to every control UI element? Maybe on the element labels, bc some UI elements have other tooltips eg slider thumbs. Could do a 500ms delay to open to keep the UI clean and not have tooltips everywhere constantly.

**Comment by blessedcoolant** [comment]
Ye sounds good. A delayed opening for a longer description. Can try to implement it sometime.

**Comment by cchance27** [comment]
Sad that this has dropped down to an inactive issue, with v3.0.0 out, i'd love to see this taken up things like dynamic prompting I'm still not 100% sure what it does mousing over things should give a tooltip with a hint, it being expandable and maybe a markdown loaded to show further documentation would be great.

**Comment by Millu** [comment]
@cchance27 these have been since been added :)
