### ISSUE TITLE
[enhancement]: add a comment on when translations get merged

### ISSUE THREAD

**Issue by pixelicous** [invoke-ai/InvokeAI#2821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Hey,

First of thank you for your wonderful app and your contribution the community 🙏 

So, I've found your page about translation contribution yesterday and translated the whole hebrew strings for the UI.

I haven't found any mention on when you guys sync different languages or what is the approval process for getting that language in after it has been translated. Might worth mentioning for future cases.

There might have been a mention of it in the documentation but I couldnt find it :)

Thanks!

**Comment by pixelicous** [comment]
@psychedelicious maybe you can shade some light on this, love your username by the way ;)

**Comment by psychedelicious** [comment]
Hello fellow delicious internet person :) 

That's for the translation, I saw it the day you finished it. Currently we are in the middle of a migration to a new backend system, part of which involves freezing the UI except for hotfixes. I suspect we will have another patch release soon and will be able to include your translation. 

You'll be pleased to know also that we've prepared the app to support RTL languages, which will be immediately useful now that we have both Hebrew and Arabic translations!

I don't think the RTL support will be included until the migration is complete, though.

**Comment by pixelicous** [comment]
@psychedelicious Amazing, that's great news! Can't wait to see it merged, I'll be sharpening the translation till then 😃 
The translation system is really great by the way, integrates beautifully to git. Looking forward for all the new innovations we will see in the UI soon 🤘
