### ISSUE TITLE
[enhancement]: Name when selecting model

### ISSUE THREAD

**Issue by airton-git** [invoke-ai/InvokeAI#2825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Hello!

I'm loving using InvokeAI and today I upgraded to version 2.3.1

I would like to suggest a change.

To select the model, the name of the ckpt or diffuser file appears.

The suggestion is to appear in the selection box the Name of the Model, more friendly.

Example.

From: dreamlike-protoreal-2.0 -> To: *Dream Like Photo Real 2.0*
From: stable-diffusion-1.5 -> To: **Stable Diffusion 1.5**

**From:**
![print1](https://user-images.githubusercontent.com/82294435/221461130-34a2970e-de80-4bdb-9858-04fe4e3fe6c7.jpg)

**To:**
![print2](https://user-images.githubusercontent.com/82294435/221461131-f90c3cd4-09a9-409f-834b-54296645a801.jpg)

Thank you and until the next version.

**Comment by VeyDlin** [comment]
Oh, yes, I've already written about this, but it would be convenient to make a separate page for each model

A page with examples of images of this model, trigger words in the description and examples of prompts (Something similar to civitai)

I have more than 50 models, I no longer remember what each of them does and what it is for

**Comment by SkyrimLL** [comment]
Being able to rename models and sort the dropdown would allow us to group models by styles and make it a lot of more efficient to work with. Alternatively, the Description field for models could be used as a display name to show in the drop down menu and sort names with, while keeping the file name intact for updates of the models.

**Comment by Tywele** [comment]
Being able to rename models for the dropdown would be a very useful feature IMO

**Comment by ReyvanZA** [comment]
I would really like this too, and if feasible extend to Lora's and other interface items as well.

**Comment by Millu** [comment]
Models are able to be renamed in through the model manager UI. Select a model to bring up the model information and the name field is modifiable. 
<img width="1377" alt="Screenshot 2023-11-27 at 10 19 48 AM" src="https://github.com/invoke-ai/InvokeAI/assets/7254508/d186f9b4-d554-4dcb-8dbd-9c589e96e157">
