### ISSUE TITLE
[bug]: 2.3.1-post2 - VAE is not a valid JSON file

### ISSUE THREAD

**Issue by telles0808** [invoke-ai/InvokeAI#2830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What happened?

I'm having an issue with SAEs, it's giving this erro: vae-ft-mse-840000-ema-pruned.vae.pt' is not a valid JSON file
it's happening for any VAE I have, even .ckpt or .safetensors

### Screenshots

![image](https://user-images.githubusercontent.com/2066086/221683524-7f948271-9427-4929-a6f9-7207ad815aa1.png)
![image](https://user-images.githubusercontent.com/2066086/221683804-79ab830f-f3ae-438e-9c91-0bf1bb469058.png)

### Contact Details

telles.gabriel@gmail.com

**Comment by RasselFast** [comment]
Download this vae [https://drive.google.com/drive/folders/16fD4pU4dUPXktcSQt-uvxqyg1B401WB7?usp=share_link](url) directory, place it in the models\ directory, then specify the VAE Location path: models\vae\vae-ft-mse-840000-ema-pruned
This is the original converted model vae-ft-mse-840000-ema-pruned.ckpt.

**Comment by telles0808** [comment]
> [https://drive.google.com/drive/folders/16fD4pU4dUPXktcSQt-uvxqyg1B401WB7?usp=share_link](url)

thx!
