### ISSUE TITLE
[bug]: black images with--ckpt-convert in init when generating NSFW images

### ISSUE THREAD

**Issue by sammyf** [invoke-ai/InvokeAI#2836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

10GB

### What happened?

When the line 

--ckpt-convert 

is present in invokeai.init the image renders correctly, even high-res fix seems to work on the finished image, then only a a black image is saved to disk. The output doesn't differ from any other image. 

This seems to only happens with NSFW images and only with certain models. I was able to replicate the error with Seek_Art, Anything3.0 and Deliberate. SFW Images seem to work fine.

Commenting out --ckpt-convert fixes the issue.

To replicate the problem : 

- add --ckpt_convert to invokeai.init
- load the Seek_Art_Mega v1model
- prompt "a naked woman"  (warning! the remporary images are DEFINITELY NSFW!)

This issue might be related to #2580 or #2832 

### Contact Details

@socialnetwooky#4142 on Discord

**Comment by lstein** [comment]
What is the setting of `--nsfw_checker` vs `--no-nsfw_checker` ??

**Comment by maxdumas** [comment]
Can confirm similar behavior, even when `--no-nsfw_checker` is flagged. Issue does not occur with same inputs/model on AUTOMATIC1111.

**Comment by sammyf** [comment]
> What is the setting of `--nsfw_checker` vs `--no-nsfw_checker` ??

the nsfw-checker is disabled. That's my invokeai.init :

```
# InvokeAI initialization file
# This is the InvokeAI initialization file, which contains command-line default values.
# Feel free to edit. If anything goes wrong, you can re-initialize this file by deleting
# or renaming it and then running invokeai-configure again.
# Place  frequently-used startup commands here, one or more per line.
# Examples:
# --outdir=D:\data\images
# --no-nsfw_checker
# --steps=20
# -Ak_euler_a -C10.0

--web --host=0.0.0.0
--outdir=/media/GINTONIC/AIArtists/InvokeAI/outputs
--embedding_path=/media/GINTONIC/AIArtists/InvokeAI/invokeai/embeddings
--precision=auto
--max_loaded_models=2
--no-nsfw_checker
--xformers
#--no-ckpt_convert
```

with no-ckpt_convert commented out, as it is now, NSFW images are generated correctly.

**Comment by lstein** [comment]
Thanks. Definitely a bug related to automatic checkpoint conversion. The NSFW checker is supposed to be disabled at the time the models are imported so that the checker can be turned on and off later.

**Comment by EryX666** [comment]
Having the same bug,
used civitai realisticVisionV13_v13-inpainting model, same .init file pretty much.
the SD 1.5 works in txt2img sometimes, sometimes it doesn't(NSFW checker is off) and just outputs a black image...

sadly i cant use the suggested fix because of a limited VRAM(8GB), it just gives out of memory error when i do...

**Comment by briankendall** [comment]
I'm getting this issue too when running from the git repo with the latest commit in main. (Currently `76d5fa4`.) I can reproduce it with Trinart2 and Anything-v3. The NSFW checker is definitely turned off. I often get it with images that are SFW, but it's definitely easiest to reproduce with a prompt like "a naked woman".

Unfortunately at this point InvokeAI has disabled the `--no-ckpt_convert` option so there's nothing I can do to work around it!

**Comment by lstein** [comment]
Just to let you know that I'm actively working on this problem. @briankendall , I assume you're working with the `main` branch? Because `--no-ckpt_convert` is still there in the `2.3.1` branch.

**Comment by lstein** [comment]
@briankendall @sammyf -- Do you ever see the black image problem with ckpt models that have been converted to diffusers on disk? Is it only ones that are dynamically converted with `--ckpt_convert`?

**Comment by lstein** [comment]
NVM, I found and fixed the problem. If you are comfortable using Git, please `git checkout v2.3` and give it a try. 

Otherwise, you can update by launching `invoke.sh` / `invoke.bat`, choosing option [6], and then option [3]. When prompted for the tag to update to, type `v2.3`. This should do the trick.

**Comment by briankendall** [comment]
@lstein Correct, I'm working with the main branch. I gather then that this fix isn't merged into main yet?

**Comment by grewwwww** [comment]
Artificial intelligence (AI) has made great strides in recent years, especially when it comes to creating images. By analyzing patterns in existing data sets, AI can create completely original images that look like they were taken with a camera. Go to[ https://creativeimage.io](https://creativeimage.io/) to generate image by AI now!
