### ISSUE TITLE
[bug]: Disconnected 

### ISSUE THREAD

**Issue by Denver41** [invoke-ai/InvokeAI#2839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What happened?

I am getting frequent "Disconnected" notices when using "Unified Canvas". 
Graphics card is GeForce RTX 3060. 
This only started happening after updating to 2.3.1.post2

### Screenshots

![Disconnected](https://user-images.githubusercontent.com/126367720/222025591-e60d0350-5ffb-4f1c-8747-fd60110d24bc.jpg)

### Additional context

Only happens with this latest update.
2.3.1.post2

### Contact Details

Denver41@gmail.com

**Comment by Denver41** [comment]
I hope this is helpful:

Image Generation Parameters:

{'prompt': 'detailed beautiful eyes', 'iterations': 3, 'steps': 50, 'cfg_scale': 15, 'threshold': 20, 'perlin': 0, 'height': 512, 'width': 512, 'sampler_name': 'k_dpmpp_2', 'seed': 3176829463, 'progress_images': False, 'progress_latents': False, 'save_intermediates': 5, 'generation_mode': 'unifiedCanvas', 'init_mask': 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eN...', 'fit': False, 'strength': 0.88, 'invert_mask': True, 'bounding_box': {'x': 645, 'y': 435, 'width': 512, 'height': 512}, 'init_img': 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eN...', 'inpaint_width': 512, 'inpaint_height': 512, 'seam_size': 96, 'seam_blur': 16, 'seam_strength': 0.7, 'seam_steps': 30, 'tile_size': 32, 'infill_method': 'patchmatch', 'force_outpaint': False, 'variation_amount': 0.1, 'enable_image_debugging': True}

>> ESRGAN Parameters: False
>> Facetool Parameters: False
>> Setting Sampler to k_dpmpp_2 (DPMSolverMultistepScheduler)
>> using provided input image of size 512x512
>> using provided input image of size 512x512

**Comment by brainbent** [comment]
I'm now getting this regularly. Did you work out what was causing it?

**Comment by Denver41** [comment]
I am not really sure but I am glad it was not just me.
It has not happened in a while & I "think" it happened when I was using Mask on Unified Canvas. Further, it may have happened with I created a smaller boundary box than 512 x 512.
Let me know if you learn more.

**Comment by algj** [comment]
This is still an issue...

**Comment by algj** [comment]
@Denver41 @brainbent if you are behind a reverse proxy, such as Nginx, check for errors such as [413: request entity too large](https://stackoverflow.com/questions/69244766/nginx-giving-out-a-413-request-entity-too-large), that seemed to be the case for me, Nginx didn't accept large uploads :)
