### ISSUE TITLE
[enhancement]: allow app to run with no persistence and/or metadata

### ISSUE THREAD

**Issue by simonfuhrmann** [invoke-ai/InvokeAI#2842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What happened?

I have played around with InvokeAI for a couple days now. Even after a re-install, I was greeted with an old prompt. I thought this was a bit concerning from a privacy perspective. Then I investigated and found out that the InvokeAI web client stores a log of pretty much everything in `localStorage`.

Typing this in the JS console reveals the size of data stored: `{...localStorage}`. In particular, most of the data is in `localStorage.getItem('persist:root');`. In my case, I had a >10MB JSON string in there.

I'm not quite sure why this logging needs to exist in the client. There is `output/invoke_log.txt` which contains all the prompts, and even after clearing the `localStorage`, every prompt from previously generated images loaded fine. It would be great if this logging could be avoided.

Digging a little further, this seems to be related to the use of the `redux-persist` module.

**Comment by psychedelicious** [comment]
Most users of applications want their settings and history to be retained. We do our best to accommodate this. Images have generation metadata embedded. This kind of retention is necessary for the vast majority of workflows.

I'll convert this into a request for a "private" operation mode.

**Comment by simonfuhrmann** [comment]
Maybe I'm missing something but it seems the specific data I'm talking about is not required. The image generation history is stored in the log file. Even after clearing the localStorage, I was able to load old image seeds and settings fine.

**Comment by psychedelicious** [comment]
Click the button at the bottom left of the screen to see UI-level logging, which is wholly separate from what the backend does. I think that's what you are not seeing. 

Admittedly the logging situation isn't great, and probably nobody uses the UI log haha. Eventually we will consolidate the logging but there's no clear timeline.

**Comment by simonfuhrmann** [comment]
Okay I just discovered that log today for the first time. Yeah that log is cool, but I don't know if it justifies *megabytes* of locally stored data in the client... Thanks for investigating though, it's appreciated!
