### ISSUE TITLE
[enhancement]: add http Authorization username to Metadata JSON when available

### ISSUE THREAD

**Issue by bani6809** [invoke-ai/InvokeAI#2851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

When the Authorization header is available in http requests, it would be nice to tag the generated images Metadata JSON with the username. Maybe even show the username in the UI.

This would be useful in scenarios where an invokeai webserver is made available to multiple users behind an apache reverse proxy, using htaccess to limit access to authorized users. Such servers should also be running HTTPS of course.

### Alternatives

Unaware of any alternatives. 😊

### Aditional Content

http query contains this authorization header:

Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==

http basic authorization is base64 encoded  username:password and in this instance it decodes to:

Aladdin:open sesame

Resulting json would be something like:

Metadata JSON:
{
  "model": "stable diffusion",
  "model_weights": "imagine_10",
  "model_hash": "bd358aee6fff793276f7c7313b5284504175dbe616ba86b4433f489f24e47dce",
  "app_id": "invoke-ai/InvokeAI",
  "app_version": "2.3.0",
  "username": "Aladdin",
  "image": {
    "prompt": [
      {
        "prompt": "Apocalypse 1992 in the style of 2000 A.D. [missing limbs, missing hands, three legs, three arms, bad anatomy drawing, distorted body, poor lighting, bad pose, 3d render, texts, signature, words, bad hand anatomy, big breasts, buxom, disjointed]",
        "weight": 1
      }
    ],
    "steps": 50,
    "cfg_scale": 10,
    "threshold": 0,
    "perlin": 0,
    "height": 1024,
    "width": 1024,
    "seed": 1815788786,
    "seamless": false,
    "hires_fix": false,
    "type": "txt2img",
    "postprocessing": null,
    "sampler": "k_lms",
    "variations": []
  }
}

**Comment by psychedelicious** [comment]
Handling users like this is kind of in this awkward space between the original vision of an app you run at home for yourself, and the projects more mature vision, which accommodates a more sophisticated user/workspace. As we roll out a new web server and backend this kind of this becomes far simpler to implement. Stay tuned

**Comment by bani6809** [comment]
still active.
