### ISSUE TITLE
[bug]: No Imagery

### ISSUE THREAD

**Issue by yogotatara3** [invoke-ai/InvokeAI#2852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cuda

### What happened?

Somehow after my fist Image gen that produced a acctual Invoke only producing single colour box. Turned of NSFW etc. no results. I use a Mac M1Pro with Ventura, would be great if someone could help me. Thank u !!!

### Screenshots

<img width="1186" alt="Bildschirm­foto 2023-03-03 um 10 28 03" src="https://user-images.githubusercontent.com/126865816/222683614-795fa16c-28da-4c79-8496-793edab9b856.png">

### Contact Details

milan.kastenmueller@thjnk.de

**Comment by yogotatara3** [comment]
This is whats going on in the Terminal when the process finished 
>> Image Generation Parameters:

{'prompt': 'anime character', 'iterations': 1, 'steps': 50, 'cfg_scale': 7.5, 'threshold': 1, 'perlin': 0, 'height': 512, 'width': 512, 'sampler_name': 'k_lms', 'seed': 1, 'progress_images': False, 'progress_latents': True, 'save_intermediates': 3, 'generation_mode': 'txt2img', 'init_mask': '...', 'hires_fix': False, 'seamless': False, 'variation_amount': 0.5, 'enable_image_debugging': True}

>> ESRGAN Parameters: False
>> Facetool Parameters: False
100%|███████████████████████████████████████████| 50/50 [00:50<00:00,  1.01s/it]
100%|███████████████████████████████████████████| 50/50 [00:50<00:00,  1.03s/it]

>> Image generated: "/Users/milan.kastenmueller/invokeai/outputs/000001.c5d2d0cf.1.png"

Generating: 100%|█████████████████████████████████| 1/1 [00:51<00:00, 51.45s/it]

**Comment by Lolagatorade** [comment]
I had that issue before but it was because I changed too many parameters specifically perlin noise. Make sure everything's at default other than that I have no advice sorry 🤷🏼‍♂️ if your using auto installer maybe update to main? Or post2 if you haven't already.
