### ISSUE TITLE
[bug]: Scan folder

### ISSUE THREAD

**Issue by telles0808** [invoke-ai/InvokeAI#2860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6gb

### What happened?

After selection this option, InvokeAI will always scan the folder for new models, but there is no way to turn it off.

### Contact Details

telles.gabriel@gmail.com

**Comment by darth-veitcher** [comment]
I think you can just edit the `init` file and comment out the folder that was previously selected for auto scanning and importing of the found models.
