### ISSUE TITLE
[enhancement]: Display bounding box coordinates in unified canvas

### ISSUE THREAD

**Issue by mcbexx** [invoke-ai/InvokeAI#2881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Not sure if this is a general use case, but when I'm inpainting just a certain part of a larger image with a smaller bounding box (for adding detail via upscaling, for instance) and write the bounding box contents to file to insert it into an image editor for further processing, I often think it would be useful to know the coordinates of the bounding box' upper left corner to help with aligning the image snippet in the image editor. Right now I need to nudge it around to get it to cover the existing layer pixel perfectly, by knowing the coordinates of the bounding box in the unified canvas, I could just align it properly immediately.

The coordinate  info could be added to the little text info in the upper left corner of the canvas, along with the zoom factor and the bounding box size.

**Comment by blessedcoolant** [comment]
![msedge_0mJirCCOXW](https://user-images.githubusercontent.com/54517381/223696996-45ee8089-a340-410d-920f-ca7d4d7f5fb9.png)

We have additional stats. Enable them in the Canvas Settings. Last button the canvas toolbar.

**Comment by mcbexx** [comment]
This solves my issue. Fantastic.

I would suggest labeling the option "Additional Canvas Info" or something similar though.
Or even make this set of information the default display.

It never occured to me that this would be considered "Debug info", I never would have checked that option, as to me it implies containing information for the devs used when hunting down an problem.

**Comment by blessedcoolant** [comment]
That's understandable. Will make a note to rename it or retag it somewhere. @psychedelicious 

Glad it sorts your issue. Will close this for issue as resolved now.
