### ISSUE TITLE
[enhancement]: enable re-entry to images created with img2img

### ISSUE THREAD

**Issue by PeterMcLennan** [invoke-ai/InvokeAI#2887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

kootenaymoonshine@gmail.com

### What should this feature add?

![Pissarro Flowers and Village 1600 px](https://user-images.githubusercontent.com/126124431/223541213-e8855e76-d49d-42a7-a301-ae0f879a78e4.jpg)

### Alternatives

I imported a photo of mine by dragging it from File Explorer into the txt2img window. 

I then "shared" it to img2img and used img2img to generate a subsequent image.  

Now, a few days later, I want to reload that generated image with all the settings that I used to generate it so that I can continue working on it.  

When I do reload the PNG from the gallery, both the "</>" metadata and the "*" (use all) buttons are greyed out and the UI reports "No metadata available"  So, there appears to be no way I can recover the UI settings that were in place on that image after I moved on to other images.

"invoke.chat" users report that this is normal behaviour.  No metadata is available for img2img created files. I do see metadata in the file invoke_log.txt that lives in my outdir, but it is very large and attempts to manually enter the metadata into the UI failed.

Is there no way I can re-open an img2img-generated file with all the UI settings restored?

**Comment by simonfuhrmann** [comment]
The generated images usually have the seed in the filename, like `id.hash.seed.png`. If you have the seed, you can search invoke_log.txt for it. `cat invoke_log.txt | grep seed`.

**Comment by PeterMcLennan** [comment]
Thanks, Simon.  I did find the image's metadata in invoke_log.txt, but
failed at re-entering it back into the UI.  Some of the parameters are
difficult to identify for this newbie.
Having this metadata easily recoverable would be a great help in future
releases.

Again, thanks.  InvokeAI continues to astound this landscape photographer.

all the best
Peter

**Comment by psychedelicious** [comment]
Hi Peter, you definitely should be able to do this (I do it all the time). Do you mind sharing the generated image whose metadata you want to recall? Please drag and drop it into a reply to this issue.

**Comment by PeterMcLennan** [comment]
psychedelicious:

A user named "void" just gave me the answer to the question "where did my
metadata go?"  '
My use of the Unified Canvas in the editing process was the common
denominator.
I haven't tested this yet, but that definitely maps to my workflow in
those cases.

SD is the best thing to happen to my photography since I retired as a
Hollywood cinematographer over 20 years ago.

THANK YOU, DEVS!  :)
Peter

**Comment by Void2258** [comment]
It would still be useful to have the original generation parameters, even though the edits and such are lost. This is because often, for organizational/space purposes, you remove the pre-edit image (this may be less of a problem once we have more robust gallery management), which can lead to losing the parameters. The log file is insufficient in this case since, if you have deleted the original file, you won't know what to look for. 
Perhaps add an 'edited' flag in the metadata so the system can pop 'this image was edited' warning while still allowing you to get not lose the parameters.

**Comment by SeanBannister** [comment]
I was actually just searching for this. I have a similar workflow to @Void2258 It would be amazing if the images I edit on canvas could keep there original metadata.

**Comment by PeterMcLennan** [comment]
The more I work with img2img and InvokeIA, the more I wish for the ability to re-enter previously processed img2img images.  

In the fever of my early (delighted) experiences with IIA I didn't record what source images were used for gens.  Now, if I wish to try again IIA'ing an existing processed image with new knowledge and  skills, I can't.  I don't need all the brush strokes from the Unified Canvas, all I need is EXIF data in the gen that gives me the ID of the original source file and the adjustment parameters I used for that image.

Even though it's completely taken over my life, I'm still absolutely in love with this tool.  Can't wait for Version 3 and I can't wait to start paying so I can support your awesomeness.

**Comment by PeterMcLennan** [comment]
It is possible to copy the generation data from the Console into the "File Info" area of the generated image while working in Photoshop.  If you also manually input the source filename, it may be possible to re-enter a previously-created image and continue working.  Testing underway.
