### ISSUE TITLE
[bug]: Real-ESRGAN/releases/download/v0.2.5.0 is not available.

### ISSUE THREAD

**Issue by glight2000** [invoke-ai/InvokeAI#2906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

Command-Line Installation
6. invokeai-configure

This step will download from a 404 url `https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.5.0/realesr-general-x4v3.pth`.

### Screenshots

![image](https://user-images.githubusercontent.com/11830159/224132018-29f11e51-0457-44af-a463-f0336a9d3545.png)

### Additional context

anaconda latest
python 3.10

**Comment by lstein** [comment]
I just tested the download a few times and it is working fine in my hands. Could there be a problem on your end such as a disk full error?

**Comment by glight2000** [comment]
The link is good now.


> I just tested the download a few times and it is working fine in my hands. Could there be a problem on your end such as a disk full error?

Maybe network...
The link is good now. It shown 404 when opend in broswer.
Thank you for answering this question :）
