### ISSUE TITLE
[bug]: Can't load custom CKPT/PT VAE

### ISSUE THREAD

**Issue by n00mkrad** [invoke-ai/InvokeAI#2917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24 GB

### What happened?

I try to use this models.yaml entry:

```yaml
analog-diffusion-1.0.ckpt-animevae.pt:
    config: configs/stable-diffusion/v1-inference.yaml
    weights: "./models/analog-diffusion-1.0.ckpt"
    vae: "./models/vae/animevae.pt"
    width: 512
    height: 512
    default: true
```

It fails because it - for whatever reason - uses the default Diffusers VAE instead.

```
>> Loading analog-diffusion-1.0.ckpt-animevae.pt from D:/Code/GitHub/text2image-gui/StableDiffusionGui/bin/x64/Debug/Data/models/analog-diffusion-1.0.ckpt
>> Converting legacy checkpoint analog-diffusion-1.0.ckpt-animevae.pt into a diffusers model...
** Custom VAE "animevae" found, but corresponding diffusers model unknown
** Using "stabilityai/sd-vae-ft-mse"; If this isn't right, please edit the model config
  | Loading diffusers VAE from stabilityai/sd-vae-ft-mse
D:\Code\GitHub\text2image-gui\StableDiffusionGui\bin\x64\Debug\Data\venv\lib\site-packages\diffusers\models\modeling_utils.py:851: FutureWarning: You are loading the variant fp16 from stabilityai/sd-vae-ft-mse via `revision='fp16'`. This behavior is deprecated and will be removed in diffusers v1. One should use `variant='fp16'` instead. However, it appears that stabilityai/sd-vae-ft-mse currently does not have a diffusion_pytorch_model.safetensors file in the 'main' branch of stabilityai/sd-vae-ft-mse.
 The Diffusers team and community would be very grateful if you could open an issue: https://github.com/huggingface/diffusers/issues/new with the title 'stabilityai/sd-vae-ft-mse is missing diffusion_pytorch_model.safetensors' so that the correct variant file can be added.
  warnings.warn(
D:\Code\GitHub\text2image-gui\StableDiffusionGui\bin\x64\Debug\Data\venv\lib\site-packages\diffusers\models\modeling_utils.py:851: FutureWarning: You are loading the variant fp16 from stabilityai/sd-vae-ft-mse via `revision='fp16'`. This behavior is deprecated and will be removed in diffusers v1. One should use `variant='fp16'` instead. However, it appears that stabilityai/sd-vae-ft-mse currently does not have a diffusion_pytorch_model.bin file in the 'main' branch of stabilityai/sd-vae-ft-mse.
 The Diffusers team and community would be very grateful if you could open an issue: https://github.com/huggingface/diffusers/issues/new with the title 'stabilityai/sd-vae-ft-mse is missing diffusion_pytorch_model.bin' so that the correct variant file can be added.
  warnings.warn(
  | global_step key not found in model
  | Using external VAE specified in config
```

As the console output implies, I can't use my own VAE, it forces me to use `stabilityai/sd-vae-ft-mse`. Anything I can do to use custom ckpt/pt VAEs, like in the older versions?

**Comment by briankendall** [comment]
I'm having the same issue. I don't want to convert the model to diffusers on disk because I'm sharing models with other stable diffusion GUIs that still work with ckpt / safetensor files, and I have only so much available space on my drive.

That said, as an experiment I tried converting it to diffusers, and it still failed to use the vae I had specified for the model. During conversion it printed `Using checkpoint model's original VAE` instead of `Using external VAE specified in config`. So it looks like loading or converting models with external vae files is currently broken.

**Comment by lstein** [comment]
Is this with the `main` branch?

**Comment by lstein** [comment]
I'm officially on vacation, but I did spend a short time working on this and have a branch that **I think** will correctly convert and incorporate the VAE specified in `models.yaml` into the derived diffusers model. I wonder if @n00mkrad or @briankendall would be willing to check whether the results are as expected?

The branch is: `feat/use-custom-vaes` (https://github.com/invoke-ai/InvokeAI/tree/feat/use-custom-vaes). To test it, you'll have to manually create a model stanza containing the custom VAE, such as the example in the bug report. Then launch `invokeai` and load the model using the automatic checkpoint conversion facility. In addition, you can try converting the model and saving it to disk -- the VAE specified in the config file should be converted and saved to the derived diffusers model.

**Comment by n00mkrad** [comment]
Well the good news: Your code seems to work, looks like the VAE gets converted on the fly. I no longer get errors.

The bad news: VAE seems to be broken in general, there are no errors, but there is zero change in the images when trying 3 different VAEs.

**Comment by briankendall** [comment]
So far I've tested one vae, but I'm afraid that's enough to confirm it's not working either for me. In my case, using the vae does produce very mildly different results, but it does not have the effect it's supposed to have. If I load an older version of InvokeAI that doesn't convert ckpt / safetensors files to diffusers, I can see a clear and consistent difference between when I use the vae and when I don't. With `feat/use-custom-vaes` the difference is practically non-existent.

**Comment by lstein** [comment]
Ok. I was afraid it wouldn't be as easy as that. I'll try a different strategy and post it in a day or two.

**Comment by n00mkrad** [comment]
> Ok. I was afraid it wouldn't be as easy as that. I'll try a different strategy and post it in a day or two.

This was already the case previously though, when using the manual conversion script. I will do some more testing but I'm pretty sure VAEs generally don't work right now.

**Comment by lstein** [comment]
Sorry, I've been enjoying my vacation too much to code. I haven't forgotten this, but it will likely be a few more days before I work on this.

**Comment by briankendall** [comment]
> Sorry, I've been enjoying my vacation too much to code. I haven't forgotten this, but it will likely be a few more days before I work on this.

Please enjoy your vacation! There's no rush on this. In fact it seems silly to suggest that it ought to take precedence over having fun.

**Comment by lstein** [comment]
Please try it now. I had a stupid bug (missing tab) in the original code. There's also a PR for this at #3010

**Comment by n00mkrad** [comment]
@lstein 
It's still impossible to use a custom VAE.

Legacy model with legacy VAE:

``
** Custom VAE "animevae" found, but corresponding diffusers model unknown
** Using "stabilityai/sd-vae-ft-mse"; If this isn't right, please edit the model config
  | Loading diffusers VAE from stabilityai/sd-vae-ft-mse
  | global_step key not found in model
  | Using external VAE specified in config
 ```
It still uses the same `sd-vae-ft-mse` VAE even though it says it's using the external one.

And with Diffusers, it ignores the external VAE and always uses the VAE baked into the model:

```
>> Loading diffusers model from ..\models\Anything-V3.0-fp16.diff
  | Using faster float16 precision
  | Default image dimensions = 512 x 512
```

**Comment by n00mkrad** [comment]
Still does not work.
