### ISSUE TITLE
[bug]: Replacing a language JSON file in the main local repo doesn't update the Web UI

### ISSUE THREAD

**Issue by Harvester62** [invoke-ai/InvokeAI#2923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What happened?

I replaced the it.json file inside my local "repo root" in C:\InvokeAI_test\InvokeAI\invokeai\frontend\web\public\locales to review the recent translations I made, but after running the backend in C:\invokeai_23 (option 2) and then a "yarn dev" in the "repo root" in C:\InvokeAI_test\InvokeAI\invokeai\frontend\web the new translated labels didn't show up in the Web UI.

Furthermore, the first icon on top doesn't have or show any label. No error messages are displayed in the consoles (see screenshots below).

### Screenshots

![immagine](https://user-images.githubusercontent.com/29801031/224496169-df14bac5-66ee-4462-b364-0e5b293af0d0.png)

![immagine](https://user-images.githubusercontent.com/29801031/224496353-8500a648-5a53-47ed-9009-132cc6a8115f.png)

**Comment by Harvester62** [comment]
Just a brief update. The source of this issue is the file C:\InvokeAI_test\InvokeAI\invokeai\frontend\web\src\features\lightbox\components\ReactPanZoomButtons.tsx which needs to get the tooltip to be updated to point at the proper translated term. Below is just an example of the first occurrence in the file, and the related corrected version:

      <IAIIconButton
        icon={<BiZoomIn />}
        aria-label={t('accessibility.zoomIn')}
        tooltip="Zoom In"
        onClick={() => zoomIn()}
        fontSize={20}
      />
      
      <IAIIconButton
        icon={<BiZoomIn />}
        aria-label={t('accessibility.zoomIn')}
        tooltip={t('accessibility.zoomIn')}
        onClick={() => zoomIn()}
        fontSize={20}
      />

Unless other files need to be touched, the above correction seems to fix the problem.

**Comment by psychedelicious** [comment]
thanks :) fix in #3037
