### ISSUE TITLE
[bug]: File Not Found

### ISSUE THREAD

**Issue by y0himba** [invoke-ai/InvokeAI#2930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12gb

### What happened?

Upgraded to 2.3.2, when selecting option 2, start the browser based UI I get the following error and I am unable to start InvokeAI:

```
FileNotFoundError: [WinError 3] The system cannot find the path specified:
'C:\\Tools\\InvokeAI\\.venv\\lib\\site-packages\\invokeai\\configs\\stable-diffusion'
```
Screenshots show traceback. 

### Screenshots

![image](https://user-images.githubusercontent.com/11462603/224538720-4963c914-ad8c-47e1-ba09-640a0b20de3f.png)
![image](https://user-images.githubusercontent.com/11462603/224538766-6b2d0275-9924-4e54-8617-b261b146af96.png)

### Additional context

I tried option 7 to fix a broken install, then a fresh install, which gave the same error. 

### Contact Details

y0himba@gmail.com

**Comment by solidslave** [comment]
Have same error to on MacOS Ventura

**Comment by rhurta** [comment]
Same issue here on Win11

**Comment by gsreeves** [comment]
> Same issue here on Win11, but creating the foder and adding models.yaml and INITIAL_MODELS seems to fix this
> ![image](https://user-images.githubusercontent.com/326974/224568157-ca00f1de-96d8-438d-af87-b470337ea71a.png)

This fix also worked on Mac.
Now to find out why I can't even generate with defaults after upgrading...

**Comment by y0himba** [comment]
Where are you getting `models.yaml` and `INITIAL_MODELS.yaml`?

**Comment by rhurta** [comment]
> Mine is showing a path of `C:\\Tools\\InvokeAI\\.venv\\lib\\site-packages\\invokeai\\configs\\stable-diffusion`
> 
> EDIT: I see you copied them from `C:\\Tools\\InvokeAI\\.venv\\lib\\site-packages\\invokeai\\configs` ?

That's right. I copied from there

**Comment by rhurta** [comment]
> > Same issue here on Win11, but creating the foder and adding models.yaml and INITIAL_MODELS seems to fix this
> > ![image](https://user-images.githubusercontent.com/326974/224568157-ca00f1de-96d8-438d-af87-b470337ea71a.png)
> 
> This fix also worked on Mac. Now to find out why I can't even generate with defaults after upgrading...

I don't have any issue to generate on Win11, so it could be another issue

**Comment by y0himba** [comment]
> 

Okay, thank you, that worked perfectly and InvokeAI is working for me now.  

While I like being told an easy fix, I always have this need to know the why and how of it. 
Why did the error occur?  
How does this fix that error?  
Was it an issue with my system, long path names, or an issue with the installer?

Sorry for the questions, I'm old school and need to know what is going on behind the button, so to speak.

**Comment by lstein** [comment]
Sorry this happened to you all. Could you describe the exact series of steps that led to this issue? Did you:

1. Use the installer to install 2.3.2 on a fresh system?
2. Use the "update" option in `invoke.sh` ?
3. Something else?

Thanks

**Comment by lstein** [comment]
I've reproduced the problem and will issue a fix ASAP.

**Comment by lstein** [comment]
@ebr Could you have a look at this? It seems that `pyproject.toml` is not installing the `invokeai/configs/stable-diffusion` directory when doing a network install, and yet it works fine from the wheel or a local `pip install`.

I started a bug branch fix referenced above, but it isn't right.

**Comment by rhurta** [comment]
> Sorry this happened to you all. Could you describe the exact series of steps that led to this issue? Did you:
> 
> 1. Use the installer to install 2.3.2 on a fresh system?
> 2. Use the "update" option in `invoke.sh` ?
> 3. Something else?
> 
> Thanks

Hello!, thanks for your help. I updated using "update" option in invoke.sh
