### ISSUE TITLE
[bug]: Issue After Updating to 2.3.2

### ISSUE THREAD

**Issue by brainbent** [invoke-ai/InvokeAI#2941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

4GB

### What happened?

9**Starting the browser-based UI results in the following error:**

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\seren.CODEX-S\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in               │
│ _run_module_as_main                                                                              │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\seren.CODEX-S\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code      │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from ldm.invoke.CLI import main                                                              │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ D:\StableDiffusion AI\InvokeAI\.venv\lib\site-packages\ldm\invoke\CLI.py:69 in main              │
│                                                                                                  │
│     66 │   Globals.ckpt_convert = args.ckpt_convert                                              │
│     67 │                                                                                         │
│     68 │   # run any post-install patches needed                                                 │
│ ❱   69 │   run_patches()                                                                         │
│     70 │                                                                                         │
│     71 │   print(f">> Internet connectivity is {Globals.internet_available}")                    │
│     72                                                                                           │
│                                                                                                  │
│ D:\StableDiffusion AI\InvokeAI\.venv\lib\site-packages\ldm\invoke\CLI.py:1298 in run_patches     │
│                                                                                                  │
│   1295 │                                                                                         │
│   1296 │   root_configs = Path(global_config_dir(), 'stable-diffusion')                          │
│   1297 │   repo_configs = Path(conf.__path__[0], 'stable-diffusion')                             │
│ ❱ 1298 │   for src in repo_configs.iterdir():                                                    │
│   1299 │   │   dest = root_configs / src.name                                                    │
│   1300 │   │   if not dest.exists():                                                             │
│   1301 │   │   │   copyfile(src,dest)                                                            │
│                                                                                                  │
│ C:\Users\seren.CODEX-S\AppData\Local\Programs\Python\Python310\lib\pathlib.py:1017 in iterdir    │
│                                                                                                  │
│   1014 │   │   """Iterate over the files in this directory.  Does not yield any                  │
│   1015 │   │   result for the special paths '.' and '..'.                                        │
│   1016 │   │   """                                                                               │
│ ❱ 1017 │   │   for name in self._accessor.listdir(self):                                         │
│   1018 │   │   │   if name in {'.', '..'}:                                                       │
│   1019 │   │   │   │   # Yielding a path object for these makes little sense                     │
│   1020 │   │   │   │   continue                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\StableDiffusion
AI\\InvokeAI\\.venv\\lib\\site-packages\\invokeai\\configs\\stable-diffusion'

### Additional context

Getting around it by downgrading to 2.3.11.post2 for now... 

### Contact Details

serenity@brainbent.dev

**Comment by gsreeves** [comment]
This is a duplicate of #2930. Please search before checking "I have searched the existing issues".
See #2930 for fix.

**Comment by lstein** [comment]
I'm sorry the upgrade is not working properly. Could you describe how you did it?

**Comment by brainbent** [comment]
I used the option in the DOS launcher.

**Comment by brainbent** [comment]
Fixed it for now, using the @rhurta fix from here: https://github.com/invoke-ai/InvokeAI/issues/2930

**Comment by lstein** [comment]
This should be fixed now. Please try an upgrade to 2.3.2.post1 (default)
