### ISSUE TITLE
[bug]: I got ROCm loaded and running but the install.sh installer gives me a "hipErrorNoBinaryForGpu: Unable to find code object for all current devices!" error

### ISSUE THREAD

**Issue by piedrok** [invoke-ai/InvokeAI#2944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

amd

### VRAM

12GB

### What version did you experience this issue on?

2.3.2

### What happened?

Though I fixed all pip version errors as the installer script suggests - I still get the "NoBinaryForGPU" error that prevents me from using openCL. 

BTW: CPU use works fine but it's way to slow for productive work. 

As I am on openSUSE Tumbleweed and use a ATI RX 6700 XT graphics adapter I am fully aware that there might be issues (not officially supported by AMD). 

But I wonder which binary is missing or can't be found so that the install script breaks after installing successfully at the first step of the configuration process - right after "Loading python libraries..." 

ROCm kernel module is loaded, all development packages are installed (as recommended by AMD), and ROCm seems to be running ok:  

```
$ rocm-smi

======================= ROCm System Management Interface =======================
================================= Concise Info =================================
GPU  Temp (DieEdge)  AvgPwr  SCLK    MCLK     Fan  Perf  PwrCap  VRAM%  GPU%  
0    54.0c           32.0W   500Mhz  1000Mhz  0%   auto  186.0W   10%   1%    
================================================================================
============================= End of ROCm SMI Log ==============================
```

Binaries are located in `/opt/rocm-5.4.0/bin/`

Which code object does the installer expect? 

Thanks for your work - excellent software btw.!   

Cheers, 
p.  

### Additional context

Happens every time `install.sh` reaches the configuration stage right after `Loading Python libraries...`  

`"hipErrorNoBinaryForGpu: Unable to find code object for all current devices!"`

**Comment by piedrok** [comment]
After I used 

`export HSA_OVERRIDE_GFX_VERSION=10.3.0`

it works!!!

**Comment by lockemx** [comment]
I am leaving this note here in case someone needs it. Your system may vary, but when I used the HSA switch, it only caused InvokeAI to drop to CPU. I am on Arch, so the torch and torchvision libraries from the system were built with ROCM support. This wasn't documented anywhere, but you have to do a manual install and create the InvokeAI venv with the `--system-site-packages` switch. After you pip to install the "InvokeAI" package set, you would have to uninstall torch and torchvision, so that the system-built packages are used instead.
