### ISSUE TITLE
[bug]: Argument --png_compression has no effect

### ISSUE THREAD

**Issue by n00mkrad** [invoke-ai/InvokeAI#2945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24 GB

### What version did you experience this issue on?

c4d5a2d16440b7711927ac81a0f75dcaea148df9

### What happened?

Changing `--png_compression` does not have any effect.

Tested with 6, 4, and 0, file size is always exactly the same.

**Comment by n00mkrad** [comment]
Can be fixed by removing `default=6,` from the following block in `args.py`:

```py
render_group.add_argument(
    "--png_compression",
    "-z",
    type=int,
    default=6,
    choices=range(0, 10),
    dest="png_compression",
    help="level of PNG compression, from 0 (none) to 9 (maximum). [6]",
)
```

Somehow, default value is always used even when passing one manually.

**Comment by lstein** [comment]
That's weird. I'll fix.
