### ISSUE TITLE
"send to canvas" command not working. Image quality degrades after dragging image onto canvas[bug]: 

### ISSUE THREAD

**Issue by mydarkmatter1** [invoke-ai/InvokeAI#2947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8gb

### What version did you experience this issue on?

2.3.2

### What happened?

"send to canvas" command not working. Image quality degrades after dragging image onto canvas.  There were no problems with the previous version.

### Screenshots

![Screenshot 2023-03-14 011152](https://user-images.githubusercontent.com/127798721/224845393-6b1a8809-9e42-441c-a96d-a5471f69a79b.jpg)
![Screenshot 2023-03-14 011321](https://user-images.githubusercontent.com/127798721/224845401-2541323d-61b6-4818-857f-6fa5973c018b.jpg)

### Contact Details

vestnick87@mail.ru

**Comment by psychedelicious** [comment]
Please check the zoom setting of your browser. The canvas scales to match the zoom setting, and may result in the image *appearing* to have degraded quality. This is only the canvas view, and if you save the image, it should be the with perfect quality.

Please provide more detail if the saved image is degraded, by uploading before and after images. Thanks.

**Comment by mydarkmatter1** [comment]
> Please check the zoom setting of your browser. The canvas scales to match the zoom setting, and may result in the image _appearing_ to have degraded quality. This is only the canvas view, and if you save the image, it should be the with perfect quality.
> 
> Please provide more detail if the saved image is degraded, by uploading before and after images. Thanks.

That's right, the saved image has its original quality. Deteriorates on canvas at any canvas scale. Default browser zoom setting "100%" This issue has been resolved.
Thanks for the answer.

**Comment by psychedelicious** [comment]
You're welcome, we will get this fixed eventually but its not a high priority at the moment as we have a lot of other work in progress.
