### ISSUE TITLE
[bug]: WebUI Issues

### ISSUE THREAD

**Issue by blessedcoolant** [invoke-ai/InvokeAI#2948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

3.0 Alpha

### What happened?

- The AlertDialogModel closes immediately. Can check it by clicking any button that uses it. // [Fixed in #2974]
- Deleting images from the gallery inside the Lightbox deletes multiple (2) at the same time.

**Comment by psychedelicious** [comment]
Think I know the cause of both. Will get to it at some point this week
