### ISSUE TITLE
[bug]: Issue With Kotosmix Checkpoint

### ISSUE THREAD

**Issue by brainbent** [invoke-ai/InvokeAI#2956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

4GB

### What version did you experience this issue on?

2.3.2

### What happened?

This is my process (so far) in using this checkpoint:

1. Installed InvokeAI v2.3.1.post2 (my first version)
2. Installed the Kotos checkpoint, from my old installs of NMKD and Auto1111
3. Kotosmix working perfectly
4. Converted it to a Diffuser
5. Colour messed up in output images
6. Removed the Diffuser version and reinstalled the checkpoint
7. Output working!
8. Updated to InvokeAI v2.3.2 yesterday, to a different directory to fix an install issue I had
9. Redownloaded and reinstalled the Kotosmix checkpoint
10. Output now messed up again!

I've attached an image to demo the problem. It seems like there is a desaturation layer on to of all my outputs?

### Screenshots

![Kotosmix-Issue](https://user-images.githubusercontent.com/50431896/225113598-04e4e18f-d481-4217-9489-ff931a2a59fc.png)

### Contact Details

serenity@brainbent.dev

**Comment by mickr777** [comment]
I found this on some models after conversion 
What works for me was to add the vae stabilityai/sd-vae-ft-mse to repo id and press model update

![image](https://user-images.githubusercontent.com/115216705/225257107-f96f05be-c6ca-449a-aff9-59620145c712.png)

**Comment by brainbent** [comment]
> I found this on some models after conversion What works for me was to add the vae stabilityai/sd-vae-ft-mse to repo id, delete none from vae location (this comes back, but doesnt seem to work if i dont delete it) and press update model, in the model manager

You ABSOLUTE LEGEND! It fixed it! 😁 Thank you so much!
