### ISSUE TITLE
[bug]: Windows batch installer does not detect python

### ISSUE THREAD

**Issue by chris4d** [invoke-ai/InvokeAI#2963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

4GB

### What version did you experience this issue on?

2.3.2

### What happened?

On Win11 Pro. I installed Python 3.10.9 via WINGET package manager. Running the provided batch file to begin installation of InvokeAI results in an error message:  "file does not exist .tmp1", and then it acts like it can't find python. My rudimentary google search suggested that perhaps the batch file was not running in the correct working folder (%~dp0) but it looks like that is accounted for in the script. Anyway, I just deleted the entire section of the batch file that checks for python, and the rest of the process is going along without a hitch, so there's something going on in that section that was not funtioning as intended.

### Contact Details

chris@fords.cc

**Comment by cjpthatsme** [comment]
Just experienced this and wanted to add a fix to the topic. 
I was able to fix it by uninstalling and reinstalling python and making sure to add python to my PATH
