### ISSUE TITLE
[enhancement]: Direct install of models from civitai.com

### ISSUE THREAD

**Issue by xaroth8088** [invoke-ai/InvokeAI#2964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

The "install from a Huggingface repo" feature is awesome.  I'd love to have a similar flow for "install from a civitai.com URL", especially if it automatically converts the model into the diffusers format after downloading.

### Alternatives

Download the model, manually tell Invoke about it, tell it to convert to diffusers, remove the downloaded model.  So, not the worst, but also not the simplest user experience.

**Comment by cwallen** [comment]
On civitai, right click the download button and copy link, then you can paste that after `!import_model`

**Comment by hipsterusername** [comment]
@xaroth8088 - Thanks for the suggestion. Civit.ai does not currently support diffusers, which will be our default model format. If they elect to introduce that support, and also position themselves away from the current "NSFW Hub", we could definitely consider it though. Closing for now!

**Comment by Agiltech-com-au** [comment]
> @xaroth8088 - Thanks for the suggestion. Civit.ai does not currently support diffusers, which will be our default model format. If they elect to introduce that support, and also position themselves away from the current "NSFW Hub", we could definitely consider it though. Closing for now!

Hmmm.. NSFW models can be installed anyway. if any model you want for the most part can't be installed then no one will use the app. It seems manually import works fine for the most part. I don't see how adding a api key and link option makes the app suddenly NSFW. ideally an app should be for how people see fit to use it. well the good ones. as much freedom as possible. but I can also understand why they dont want to associate with the insane level of porn on civiatai and hentai. 

Oh well. cool app anyway. but if it goes paid and they implement some soft of block for civtai models that would kill it. Better to just have a baked SFW filter and let tinkerers who want to unlock, unlock it.

**Comment by hipsterusername** [comment]
> > @xaroth8088 - Thanks for the suggestion. Civit.ai does not currently support diffusers, which will be our default model format. If they elect to introduce that support, and also position themselves away from the current "NSFW Hub", we could definitely consider it though. Closing for now!
> 
> Hmmm.. NSFW models can be installed anyway. if any model you want for the most part can't be installed then no one will use the app. It seems manually import works fine for the most part. I don't see how adding a api key and link option makes the app suddenly NSFW. ideally an app should be for how people see fit to use it. well the good ones. as much freedom as possible. but I can also understand why they dont want to associate with the insane level of porn on civiatai and hentai.
> 
> Oh well. cool app anyway. but if it goes paid and they implement some soft of block for civtai models that would kill it. Better to just have a baked SFW filter and let tinkerers who want to unlock, unlock it.

You’re commenting on a nearly two year old thread. You can manually add API keys through your config - long solved.

**Comment by peterclemenko** [comment]
> > > @xaroth8088 - Thanks for the suggestion. Civit.ai does not currently support diffusers, which will be our default model format. If they elect to introduce that support, and also position themselves away from the current "NSFW Hub", we could definitely consider it though. Closing for now!
> > 
> > 
> > Hmmm.. NSFW models can be installed anyway. if any model you want for the most part can't be installed then no one will use the app. It seems manually import works fine for the most part. I don't see how adding a api key and link option makes the app suddenly NSFW. ideally an app should be for how people see fit to use it. well the good ones. as much freedom as possible. but I can also understand why they dont want to associate with the insane level of porn on civiatai and hentai.
> > Oh well. cool app anyway. but if it goes paid and they implement some soft of block for civtai models that would kill it. Better to just have a baked SFW filter and let tinkerers who want to unlock, unlock it.
> 
> You’re commenting on a nearly two year old thread. You can manually add API keys through your config - long solved.

I'm not having much luck with that, can you explain how to add it

**Comment by Agiltech-com-au** [comment]
> > > > @xaroth8088 - Thanks for the suggestion. Civit.ai does not currently support diffusers, which will be our default model format. If they elect to introduce that support, and also position themselves away from the current "NSFW Hub", we could definitely consider it though. Closing for now!
> > > 
> > > 
> > > Hmmm.. NSFW models can be installed anyway. if any model you want for the most part can't be installed then no one will use the app. It seems manually import works fine for the most part. I don't see how adding a api key and link option makes the app suddenly NSFW. ideally an app should be for how people see fit to use it. well the good ones. as much freedom as possible. but I can also understand why they dont want to associate with the insane level of porn on civiatai and hentai.
> > > Oh well. cool app anyway. but if it goes paid and they implement some soft of block for civtai models that would kill it. Better to just have a baked SFW filter and let tinkerers who want to unlock, unlock it.
> > 
> > You’re commenting on a nearly two year old thread. You can manually add API keys through your config - long solved.
> 
> I'm not having much luck with that, can you explain how to add it

Yeah that would be awesome. I saw YouTube video where he put in civtai url and it works but when I try to put in the url I get hug api key error.
