### ISSUE TITLE
[bug]: Negative prompt ENTER key behavior

### ISSUE THREAD

**Issue by Fortyseven** [invoke-ai/InvokeAI#2966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

3.x (current `main` branch)

### What happened?

The ENTER key behaves differently in the negative prompt box, versus the positive prompt box:
- ENTER pressed while focused in the **positive box** executes **image generation**.
- ENTER pressed while focused in the **negative box** issues a **carriage return and stays in the box**.

Unless there's a reason for that I'm unaware of, they should both probably behave the same way -- executing image generation.

**Comment by Barafu** [comment]
I agree with this. It should be consistent. Also, if "Enter starts generation" is chosen, please set Ctrl+Enter for newline. Currently, it starts generation when in positive box either.
