### ISSUE TITLE
[bug]: Base Brush won't work

### ISSUE THREAD

**Issue by Jaronce** [invoke-ai/InvokeAI#2969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

2.3.2

### What happened?

Can't use the Base Brush in Unified Canvas

### Additional context

Mask Brusk works perfectly but not base

**Comment by psychedelicious** [comment]
Can you please take a screen recording or screenshot to help us understand the issue?

**Comment by yinglee712** [comment]
Base Brush won't work.i use the invokeai_standalone.but when i want to use base brush, nothing will be happen.and so i cant use mask, so bad!cry
