### ISSUE TITLE
[bug]: Text to images generates exclusively "broken" images

### ISSUE THREAD

**Issue by karolisleipus** [invoke-ai/InvokeAI#2977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

10GB

### What version did you experience this issue on?

3.0.0+a0

### What happened?

Every time I use text to image, I get fragmented and scrambled generations. I tried changing models, settings, using different prompts and negative prompts, reinstalling the web UI etc. Nothing helped so far. It seems it only generates "broken" images. Any ideas what could be wrong?

### Screenshots

![000001 de3a9cd5 383200044](https://user-images.githubusercontent.com/30648770/226068968-ed32c477-576e-44c5-aa75-25ac0a7a13ea.png)
![000003 63039f51 2332623345](https://user-images.githubusercontent.com/30648770/226068970-24aa6d6d-95de-4430-bcf0-2bcf2acbda35.png)
![000004 f22f2c4e 4272760784](https://user-images.githubusercontent.com/30648770/226068971-49f86c4c-64ae-493f-ae51-bd98939647cd.png)
![000007 a99437b1 2854114704](https://user-images.githubusercontent.com/30648770/226068972-8456cc56-be9f-45ff-bcdf-3910cf50c2ad.png)
![000009 498ddf73 170848050](https://user-images.githubusercontent.com/30648770/226068973-909315a8-74a9-43fe-945d-6430cb8e6b2c.png)
![000011 d0c12eaf 698981877](https://user-images.githubusercontent.com/30648770/226068974-c26b102a-090e-4db4-ad94-822e71245f6f.png)
![000012 8c1ce340 124026834](https://user-images.githubusercontent.com/30648770/226068975-0da5bc0c-b320-4206-8dba-cc5724c9f49d.png)
![000014 85600f23 2542510870](https://user-images.githubusercontent.com/30648770/226068976-2e5abe52-4c6c-4927-8a10-37756a978532.png)
![000015 44718c03 3678496518](https://user-images.githubusercontent.com/30648770/226068978-1de471bd-2b96-41db-80ea-124168c6cf18.png)
![000016 ad5d4d39 2282383211](https://user-images.githubusercontent.com/30648770/226068981-e5296ee9-fca5-4f60-9180-31a0df660881.png)
![000017 847f9257 2189412237](https://user-images.githubusercontent.com/30648770/226068983-0a03752d-a5d9-44b2-8ca8-4b94b21b7954.png)
![000019 1c573708 191197667](https://user-images.githubusercontent.com/30648770/226068984-0bfcaf07-fde1-411b-8d90-653277fa822d.png)
![000021 d6f4ce5c 4264494823](https://user-images.githubusercontent.com/30648770/226068986-96369050-1450-4b98-94af-7718dfbcf28f.png)
![000023 5eab04be 1411039051](https://user-images.githubusercontent.com/30648770/226068988-2f5468ed-2f66-4245-89dc-e30df684de64.png)

Those are the images I got using a simple "portrait of a man" prompt mostly in stable diffusion 1.5 model.

### Contact Details

karolis.leipus@gmail.com

**Comment by mickr777** [comment]
Make sure seamless tiling isnt enabled, its right above high res optimisation under other options in th web ui.

I have bumped it once or twice when turning on hires

**Comment by psychedelicious** [comment]
I kinda like those generations :D

We need to add an indicator to the UI that shows if certain settings like this are enabled, because it is too easy to miss them and think something is wrong - I do this all the time with seamless and random seed.

**Comment by karolisleipus** [comment]
Thank you for the answers. Issue solved.

And yeah, I agree that some indicator of these settings being enabled would be helpful.
