### ISSUE TITLE
[enhancement]: Ability to rename models via the web UI

### ISSUE THREAD

**Issue by xaroth8088** [invoke-ai/InvokeAI#2979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Inside of the Model Manager, it'd be nice to be able to change the name of a model, the same way that any other attribute can be updated.

### Alternatives

Editing the `models.yaml` file in a text editor and hoping I don't accidentally break anything while I'm in there.

**Comment by SkyrimLL** [comment]
There is a workaround.. it is possible to edit the models.yaml file and rename the keys to each model. Editors like VS Studio code have extensions to sort yaml files by keys. 
Once renamed and sorted, the drop down menu looks much easier to navigate without breaking anything with the models (the file name remains the same so it is possible to update the models without losing the new name).

**Comment by xaroth8088** [comment]
Off-topic: it's a little odd that the bot would mark an enhancement request as inactive.  Like, the team works quickly to add new functionality, but they don't work _that_ quickly.  😆
