### ISSUE TITLE
[bug]: It seems to be searching for the Config at the Models location

### ISSUE THREAD

**Issue by subashc2023** [invoke-ai/InvokeAI#2980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

2.3.1

### What happened?

Trying to load the model RealisticVisionv1.3-inpainting.safetensor model.

Tried both as Diffuser and as Checkpoint.

### Screenshots

When running as Diffuser, this happens. 
![image](https://user-images.githubusercontent.com/120974338/226101505-b5fbc031-8025-4569-a3c3-485102d6a7d3.png)

When running as Checkpoint, this happens. it is a different error, but it fails because it cannot find the Personalization Config in the model. Not sure why this is, but it might be because im trying to load a safetensor as a checkpoint?
![image](https://user-images.githubusercontent.com/120974338/226101619-c760a2c3-cbee-4c3a-b15a-bfa80379a96d.png)

The config is the same, and I am trying to load the same model with the same VAE for both. The mode, VAE and Config work fine in other UI's. Other models continue to work fine on this UI. Not sure what to do.

**Comment by lstein** [comment]
Sorry for the delay but I was on vacation. I'll look into this ASAP.

**Comment by lstein** [comment]
I've just checked and this model seems to load and run just fine from either the WebUI or the CLI. I wonder whether you selected the "v1 inpainting" format when you did the import from the WebUI? If not, then I suggest you remove the model configuration (it won't delete the weights file itself) and re-import.

**Comment by subashc2023** [comment]
It was because I was loading these models as diffusers. Everything works fine if I load it as a checkpoint.
