### ISSUE TITLE
[bug]: Is not recognized as an internal or external comand, operable program or batch file.

### ISSUE THREAD

**Issue by keizergamer033** [invoke-ai/InvokeAI#2981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What version did you experience this issue on?

2.3.0

### What happened?

So I downloaded InvokeAI on itch.io and after waiting for 10-12 minutes i open and click launch and get greeted with this error

Standalone by Sunija.

Loading...
'C:\Users\Merc' is not recognized as an internal or external command,
operable program or batch file.
C:\Users\Merc Keiz\AppData\Roaming\itch\apps\invokeai\invokeai_2_3_0_standalone/env/python.exe: can't open file 'C:\\Users\\Merc': [Errno 2] No such file or directory
Press any key to continue . . .

### Screenshots

![image](https://user-images.githubusercontent.com/128230137/226106739-8d83bc58-564f-4a4d-b8b4-ae4b6d49a6d8.png)

### Contact Details

keizergamer033@gmail.com

**Comment by keizergamer033** [comment]
Hay :D fix it by moving it to another folder and added _ on spaces

e.g Root_Folder

**Comment by psychedelicious** [comment]
Glad you got it working.

Just for future reference, the distribution on itch.io is managed by Sunija, who you can get in touch with on [our discord](https://discord.gg/ZmtBAhwWhy). Their discord account is `Sunija#6598`.
