### ISSUE TITLE
[bug]: Upscale only upscale 4 tile

### ISSUE THREAD

**Issue by keizergamer033** [invoke-ai/InvokeAI#2982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What version did you experience this issue on?

2.3.0

### What happened?

So I click upscale and it only upscales 4 tile showed on the command prompt
it adds transparent black on the picture I tried maxing everything but that only make transparent black to pitch black

### Screenshots

before
![image](https://user-images.githubusercontent.com/128230137/226108694-97b7ffdc-90ae-452c-9daa-8dcc1df49058.png)

after
![image](https://user-images.githubusercontent.com/128230137/226108705-4b00cc76-bf58-4de5-8c69-45ec6c6f58a7.png)

CMD
![image](https://user-images.githubusercontent.com/128230137/226108773-d2746127-44c7-4a3a-9c98-32d20b758736.png)

### Contact Details

keizergamer033@gmail.com

**Comment by psychedelicious** [comment]
I think there is some confusion about what `Tile` means. `Tile` refers to how the upscaler works internally and it is common for it to break the image up into 4 tiles, this is the expected output.

I believe what you are seeing with a dark overlay is unrelated. Can you please right click the before and after images from the app, copy, and paste them into a reply here? Thanks

**Comment by alabsi91** [comment]
same issue here:

![image](https://user-images.githubusercontent.com/58077449/234231916-6aa8daa2-f9b3-4298-9520-6b41e4874ff9.png)

### Before
![image](https://user-images.githubusercontent.com/58077449/234231486-608fc9ab-1b30-4fd2-8a38-677df64c8cc0.png)
### After
![image](https://user-images.githubusercontent.com/58077449/234231600-8fe1cd44-0a3b-49ab-b3d5-8628f88eef92.png)
