### ISSUE TITLE
[enhancement]: Persistent Model On Restart 

### ISSUE THREAD

**Issue by Void2258** [invoke-ai/InvokeAI#2984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Currently is it only possible to specify a singular default model on start with `--model <model name>` in the init or leave it blank (this usually loads SD 1.5). Almost everything else in Invoke returns to the last-used state on restart (prompts, settings, even the mask on the unified canvas), but not the model. This can lead to mistakes when one sees everything else is the same and proceeds without realizing the model has reset. Also, on systems that have a harder time changing models (lower ram, low caching. HDD), it may be a significant improvement having the model you are using persist until you are ready to move on to using another. An option to persist the model on next open would aid in user experience consistency.

### Alternatives

A warning that pops up (with an "do not remind me again" option) the first time you click invoke after a restart, reminding you that the model has been reset to default (and list what the default is). This does not address the model change difficulty issue.

**Comment by psychedelicious** [comment]
In the next release, the initial model selection will effectively be managed by the UI and work like you suggest here. In fact when you use the settings from a past generation, it will automatically use that model. We don't have an ETA on the next release just yet.

**Comment by Void2258** [comment]
I wasn't going to put it here since it was a bit different, but I was going to suggest adding a "use model" and "use all and model" to the gallery right click (distinct from use all since changing model is a significant action and a common thing to do is to try the same gen parameters but on a different model).

**Comment by psychedelicious** [comment]
That's something we will be able to do on the new system 👍

**Comment by lstein** [comment]
If I can pipe in here, I would love to have a "use model" button in addition to the "use seed", "use prompt" and "use all" buttons. In addition, it would be very handy to have a checkbox that automatically loads all previous settings when scrolling around within the gallery so that I can quickly see the prompt and other settings used to generate an image.
