### ISSUE TITLE
[enhancement]: Sidecar Export, txt/JSON

### ISSUE THREAD

**Issue by AsaTyr2018** [invoke-ai/InvokeAI#2986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Contact via Github is ok

### What should this feature add?

Creation of a sidecar txt or JSON file with all nessesary Informations about the Image creation.
This would simplify the management of the created images and the Prompt Informations wouldn´t get lost.

Personally i manage all my creationg via a tool called Hydrus Client. Befor using InvokeAI i used Automatic1111. That creates said files. But the In-/Outpaint Feature is far far beyong. Reason why i use InvokeAI (Big compliment). Bit its lacks the said feature to store the creation information.

I found several old gits issues about this. But they are marked as Inactive/old. Correct me if i´m wrong.

### Alternatives

Storing the required Informations within the PNG Info itself. 
eg.: https://exiftool.org/TagNames/PNG.html

### Aditional Content

This feature could be Optional via Settings. A simple Checkbox "Enable generation of Sidecar File" as example.

**Comment by mickr777** [comment]
This data is already stored in the png in the exif data under sd-metadata, a program like exiftool or a website like https://linangdata.com/exif-reader/ can so you read this data.

**Comment by AsaTyr2018** [comment]
yes but only if you don´t work with unified canvas. then the png data is lost. for that: sidecar files would be the perfered way to store the data ;)
