### ISSUE TITLE
[bug]: error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by Ston3r420** [invoke-ai/InvokeAI#2988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cpu

### What version did you experience this issue on?

2.3.2

### What happened?

I'm New to Linux and dont know what Im doing at all, So  I was installing invokeai nd it just stopped. HELP! screenshots below.

### Screenshots

![Screenshot 2023-03-19 8 39 48 AM](https://user-images.githubusercontent.com/66495102/226175813-e78c3a7e-28be-4374-bf58-9c31fcd8e717.png)
![Screenshot 2023-03-19 8 40 03 AM](https://user-images.githubusercontent.com/66495102/226175814-151dc5cf-1250-4ae7-9eb3-2a5108f6c910.png)

**Comment by lstein** [comment]
@ebr - could you have a look at this? It seems to be an installer issue.

**Comment by ebr** [comment]
@Ston3r420 have you tried running the installer again? The error above might be a one-off failure to install a package.

What Linux distribution are you running?

**Comment by ebr** [comment]
@Ston3r420 are you still experiencing this issue?
