### ISSUE TITLE
[bug]: Trojan Win32/Casdet!rfn found

### ISSUE THREAD

**Issue by MattiJarvinen** [invoke-ai/InvokeAI#2989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

4

### What version did you experience this issue on?

2.3.0

### What happened?

Windows defender flags pytorch_model.bin as a Trojan virus.

### Screenshots

![image](https://user-images.githubusercontent.com/12794435/226191326-01470d52-8c22-4f74-b5bc-9a529304f61f.png)

**Comment by danieldunderfelt** [comment]
I am also seeing this. False alarm or something serious?

**Comment by mirobane** [comment]
got same issue while loading SD2.1 BASE here

win10 / CUDA / 3060Ti 8Gb Vram

**Comment by ekis93** [comment]
I've been getting the same flags for all my vae.pt files whenever I try to load a vae. It started about 2 hours ago. To clarify I'm using hte Automatic111 webUi, but thought this would be helpful here as well.

Windows Defender message: **Trojan:Win32/Casdet!rfn**
OS: **Windows 10**
Python version: **Python 3.10.6**
SD-WebUI revision: **3715ece0adce7bf7c5e9c5ab3710b2fdc3848f39**
torch version: **1.13.1+cu117**
torchvision version: **0.14.1+cu117**

**Comment by chuckkay** [comment]
me too

**Comment by chuckkay** [comment]
thought it might have been a bad model i imported, but i did a clean install without importing any other models but the ones offered in the install script. and got the same windows backdoor virus notification... WTF

**Comment by keenmouse** [comment]
> For me it is also the safety checker file of models--runwayml--stable-diffusion-v1-5 1d37ca6e57ace94e4c2f03ed0f67b6dc83e1ef1160892074917aa68b28e2afc1 Backdoor:Win32/Bladabindi!ml

I just started seeing this too.

**Comment by keenmouse** [comment]
This is also being discussed on [itch.io](https://itch.io/post/7509488). It looks like the latest pytorch_model.bin releases _may_ be triggering a false positive detection in Windows Defender. I'm waiting to hear more before I assume it's safe.

**Comment by keenmouse** [comment]
When I unzip pytorch_model.bin, I don't get a virus detection on any of the extracted files.

For reference, the hash of the release I downloaded is 9f3084c0600e544506a2d414647492a036fb1aa0, current as of 2023-03-20 18:45 UTC.

**Comment by keenmouse** [comment]
Where is blip-image-captioning-base being downloaded from? Because pytorch_model.bin it doesn't match the release currently [available on Hugging Face](https://huggingface.co/Salesforce/blip-image-captioning-base).

**Comment by suohongliu** [comment]
same issue with 9f3084c0600e544506a2d414647492a036fb1aa0\pytorch_model.bin

**Comment by keenmouse** [comment]
> same issue with 9f3084c0600e544506a2d414647492a036fb1aa0\pytorch_model.bin
> 
> "Backdoor:Win32/Bladabindi!ml" from windows defender.

Me too. But since nothing was detected in the extracted files when I unzipped it, does that mean Windows Defender just found a false-positive signature in the compressed data? pytorch_model.bin is actually just a zip file.

**Comment by suohongliu** [comment]
> > same issue with 9f3084c0600e544506a2d414647492a036fb1aa0\pytorch_model.bin
> > "Backdoor:Win32/Bladabindi!ml" from windows defender.
> 
> Me too. But since nothing was detected in the extracted files when I unzipped it, does that mean Windows Defender just found a false-positive signature in the compressed data? pytorch_model.bin is actually just a zip file.

Yeah, I think its just a false alarm from Windows Defender, but I'm gonna pause my work for a few days or try it on VM. This Bladabindi kinda scares me.

**Comment by pharmapsychotic** [comment]
ugh yeah it's a false positive, they are the model weights not an executable.

**Comment by lstein** [comment]
This is almost certainly a false positive because neither the safety model nor SD 1.5 have changed in the past month.

The most I can do is to put something in the documentation warning people about the issue. Could subscribers to this issue help me compile a comprehensive list of which models are causing the issue?

Here's what I gather from the thread:

- `CIDAS/clipseg-rd64-refined`
- `runwayml/stable-diffusion-v1-5`

The CIDAS model is always installed - it is used for text based masking in the CLI. The runwayml model is optional, but since it is the main stable-diffusion 1.5 model, you probably will want it.

All the diffusers models contain a file named `pytorch_model.bin`, so the important thing to know is the name of the directory that contains it.

**Comment by Juz10M** [comment]
> > > same issue with 9f3084c0600e544506a2d414647492a036fb1aa0\pytorch_model.bin
> > > "Backdoor:Win32/Bladabindi!ml" from windows defender.
> > 
> > 
> > Me too. But since nothing was detected in the extracted files when I unzipped it, does that mean Windows Defender just found a false-positive signature in the compressed data? pytorch_model.bin is actually just a zip file.
> 
> Yeah, I think its just a false alarm from Windows Defender, but I'm gonna pause my work for a few days or try it on VM. This Bladabindi kinda scares me.

Did it work on VM?

**Comment by Jamystere** [comment]
Personnally I got 5 alerts from Windows Defender, on these files : 

"models--CIDAS--clipseg-rd64-refined\snapshots\583b388deb98a04feb3e1f816dcdb8f3062ee205\pytorch_model.bin"
"models--stabilityai--stable-diffusion-2-1\snapshots\f7f33030acc57428be85fbec092c37a78231d75a\text_encoder\pytorch_model.bin"
"models--runwayml--stable-diffusion-v1-5\snapshots\ded79e214aa69e42c24d3f5ac14b76d568679cc2\safety_checker\pytorch_model.bin"
"

**Comment by Jamystere** [comment]
Personnally I got 5 alerts from Windows Defender, on these files : 

"models--CIDAS--clipseg-rd64-refined\snapshots\583b388deb98a04feb3e1f816dcdb8f3062ee205\pytorch_model.bin"
"models--stabilityai--stable-diffusion-2-1\snapshots\f7f33030acc57428be85fbec092c37a78231d75a\text_encoder\pytorch_model.bin"
"models--runwayml--stable-diffusion-v1-5\snapshots\ded79e214aa69e42c24d3f5ac14b76d568679cc2\safety_checker\pytorch_model.bin"
"models--runwayml--stable-diffusion-inpainting\snapshots\afeee10def38be19995784bcc811882409d066e5\safety_checker\pytorch_model.bin"
"models--CIDAS--clipseg-rd64-refined\snapshots\583b388deb98a04feb3e1f816dcdb8f3062ee205\pytorch_model.bin"

All alerts were for that Bladabindi!ml Trojan. Hope it can help

**Comment by Barafu** [comment]
I ran Kaspersky at maximum paranoid mode, and it stays silent about anything in my InvokeAI stuff.
