### ISSUE TITLE
[bug]: cross attention/.swap() producing strange output on MPS devices

### ISSUE THREAD

**Issue by gogurtenjoyer** [invoke-ai/InvokeAI#2990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

16gb

### What version did you experience this issue on?

main as well as latest/2.3.2

### What happened?

Example images (with hopefully their metadata) below. This has been verified by two MPS users so far, but I'll try to get some more to test it shortly.

![006715 c001a543 1147595307](https://user-images.githubusercontent.com/36354352/226204280-3b4bfcd8-3f37-4371-94d4-6197cbbe68df.png)
![006716 c74d80a4 431152674](https://user-images.githubusercontent.com/36354352/226204282-1bc0738e-b612-4536-b7fb-edcf9d902a80.png)
![006768 61516a4a 166271066](https://user-images.githubusercontent.com/36354352/226204290-020fe352-6ebd-4764-98c2-3159ff594674.png)

**Comment by Adreitz** [comment]
@damian0815 Not sure if this should be reopened or if it's a new issue, but on Sonoma with SDXL (using a nodes setup with the offset LoRA but no real weirdness), SDXL base runs for only seven of 35 steps with the prompt "Man runs (on a beach).swap(in Antarctica)". The preview shows blotchy gray noise similar to gogurt's images, but the process halts with a fatal error before generating a final image:

`[2023-10-10 07:25:15,932]::[InvokeAI]::ERROR --> Error while invoking:
linear(): input and weight.T shapes cannot be multiplied (77x768 and 2048x640)`
