### ISSUE TITLE
[enhancement]: Paint layer in Unified Canvas

### ISSUE THREAD

**Issue by Void2258** [invoke-ai/InvokeAI#2991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Currently, there is the mask layer and the base layer (original/last accepted image) in the Unified Canvas. To 'sketch and gen', you need to draw on the base layer, then mask that area and enter an appropriate prompt. Paint is applied over the base image destructively; erasure leaves empty space, not the pre-paint image. The only way to recover the unpainted image is to ctrl-z until you undo the problematic brush stroke; you cannot make refinements or remove mistakes in the paint job. 
A paint layer 'between' the base and the mask would allow for editing and correction of painting without compromising the underlying image. Also, the paint layer could be made semi-tranparent to check your paint job. It could also be hidden when performing before-after generation comparisons, which could be made to the original base image and not the post-paint base image (this should probably be the default).
A future feature could also allow you to copy-paste, scale, or move blobs around to other locations on the image and/or apply blobs to a new base image, allowing some reuse.  Far in the future, utilizing this layer could allow importation of a seed image for inpainting (ie load, scale and position another image on top of the one you are working on, then use it as the inpainting base).

**Comment by hipsterusername** [comment]
Going to track this request in #4466
