### ISSUE TITLE
[bug]: Backdoor:Win32/Bladabindi!ml

### ISSUE THREAD

**Issue by Nesho814** [invoke-ai/InvokeAI#2992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

NVIDIA GeForce RTX 2070 SUPER

### VRAM

8

### What version did you experience this issue on?

2.3.0 standalone

### What happened?

Windows Defender found a backdoor imbedded in the program

### Screenshots

![Zrzut ekranu 2023-03-19 231955](https://user-images.githubusercontent.com/95534907/226213720-7325ba13-17c5-4651-a927-2c931d6ace64.jpg)
It's after windows tried to eliminate it and also in polish so translation here:
Incomplete elimination (Serious)
Detected: Backdoor:Win32/Bladabindi!ml
State: Failure
This application may not have been fully eliminated
Date: ----
Details: This program allows for remote access to the computer on which it's installed.
Elements affected:
---

**Comment by Max-Basedaf** [comment]
got the same, deleted if for now

**Comment by insightler** [comment]
Also found it today, but not been using invokeai for a month, therefor guessing defender update today caused it to be found now for several of us. Below are from MS Defender logs: 

Backdoor:Win32/Bladabindi!ml in these 2 locations:
\invokeai\models\diffusers\models--naclbit--trinart_stable_diffusion_v2\snapshots\59d57b9119311cf59e98fd12927fc511239abfa1\text_encoder\pytorch_model.bin; \invokeai\models\diffusers\models--runwayml--stable-diffusion-v1-5\snapshots\ded79e214aa69e42c24d3f5ac14b76d568679cc2\safety_checker\pytorch_model.bin

Trojan:Win32/Casdet!rfn in these 3 locations: 
\invokeai\models\diffusers\models--runwayml--stable-diffusion-inpainting\snapshots\afeee10def38be19995784bcc811882409d066e5\safety_checker\pytorch_model.bin; \invokeai\models\diffusers\models--stabilityai--stable-diffusion-2-1\snapshots\f7f33030acc57428be85fbec092c37a78231d75a\text_encoder\pytorch_model.bin; \invokeai\models\hub\models--CIDAS--clipseg-rd64-refined\snapshots\583b388deb98a04feb3e1f816dcdb8f3062ee205\pytorch_model.bin

**Comment by lenase0077** [comment]
same here

**Comment by gwyong** [comment]
I also got this error. What is the actual problem?

**Comment by Ranteck** [comment]
Same Here

**Comment by lstein** [comment]
The problem is that Defender is flagging stable diffusion model files as being malware, even though they are not. The only thing you can do about this is to write to Microsoft and ask them to whitelist the affected models.

Note that the file identified as having malware is actually a model file downloaded from HuggingFace. It is not part of the InvokeAI source code.
