### ISSUE TITLE
[bug]: [3.0.0.0+a0] [Webui] option panel auto hides when using most options when unpinned 

### ISSUE THREAD

**Issue by mickr777** [invoke-ai/InvokeAI#2994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

windows

### GPU

cuda

### What version did you experience this issue on?

3.0.0.0+a0

### What happened?

Issue: option panel auto hides when clicking in the prompt box to type in it, opening any option and switching any option on, when unpinned.

expected: should only hide when clicking away from it

tested with chrome on android, and chrome, edge and Firefox on windows

**Comment by blessedcoolant** [comment]
Yep. There are some known issues with the new Drawer component. We'll have them sorted in the coming days.
