### ISSUE TITLE
[bug]: Model folder no longer being remembered in add model UI (2.3.2 vs 2.3.0)

### ISSUE THREAD

**Issue by Void2258** [invoke-ai/InvokeAI#2999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What version did you experience this issue on?

2.3.2.post1

### What happened?

In 2.3.0, under add safetensor/checkpoint model in the GUI (box icon), it remembered the model folder path, so all you had to do was click scan to find new models. In 2.3.2 this field is not remembered and has to be retyped every time before scanning for new models.

**Comment by lstein** [comment]
@blessedcoolant: I think this is a WebUI issue.

**Comment by blessedcoolant** [comment]
Can you reset your WebUI or delete local storage and try once more? Code seems to be fine but if the problem persists, I'll look into it deeper.

**Comment by Void2258** [comment]
Resetting webui fixed it.

**Comment by blessedcoolant** [comment]
Sweet. I'll mark this as resolved.
