### ISSUE TITLE
[bug]: ERROR: Package 'invokeai' requires a different Python: 3.11.0 not in '<3.11,>=3.9'

### ISSUE THREAD

**Issue by Darling-Lee** [invoke-ai/InvokeAI#3003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

amd

### VRAM

32GB

### What version did you experience this issue on?

2.3.2

### What happened?

unable to install.Just as the title said.

### Contact Details

lonelybboylonely@163.com

**Comment by agentx3** [comment]
Have you tried running the install with either Python 3.10 or Python 3.9? That's what the installation instructions say to use so the error makes sense. You can verify the python version by running `python -V`.

**Comment by m0d3rnX** [comment]
Will that change in the future?

**Comment by jameslanman** [comment]
I am also getting this error trying to install using Python v 3.10.12 as specifically recommended in the installation docs. On a Mac m1 Max, 32 GB, Ventura 13.3.1

If anyone has a fix I would love to be able to use InvokeAI again!

**Comment by jameslanman** [comment]
@Millu Yes, the version I installed was from here: https://invoke-ai.github.io/InvokeAI/installation/010_INSTALL_AUTOMATED/ I have an old version of Invoke but wanted to get the latest and will then port the files over from the old install to make sure I don't lose anything.

**Comment by Millu** [comment]
Weird, you shouldn't be seeing that on Invoke 3.x and on - can you double check this is the installer you're trying to use?

https://github.com/invoke-ai/InvokeAI/releases/tag/v3.5.1

**Comment by jameslanman** [comment]
@Millu That is indeed the installer I am using. v3.5.1
