### ISSUE TITLE
[bug]: invokeai-batch command creates a logfile incompatible with windows filenames and fails

### ISSUE THREAD

**Issue by EdSisson** [invoke-ai/InvokeAI#3005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12

### What version did you experience this issue on?

2.3.2

### What happened?

When in the developer CLI on windows, you should be able to call invokeai-batch according to the following syntax
`invokeai-batch example.yml --invoke`
where example.yml is a suitably formatted yaml, in this case, the output of
`invokeai-batch --example > example.yml`

When run without the --invoke command, the command creates a list of prompts from the combinations contained in the yaml, exactly as intended, but when called with invoke you get an error, an example of which is:
`(.venv) C:\Users\Administrator\invokeai>invokeai-batch example.yml --invoke
>> Spawning 1 invokeai processes across 1 CUDA gpus
>> Outputs will be written into default InvokeAI outputs directory, and error logs will be written to C:\Users\ADMINI~1\AppData\Local\Temp\invokeai-batch-logs
>> Process 10212 running on GPU 0; logging to C:\Users\ADMINI~1\AppData\Local\Temp\invokeai-batch-logs\2023-03-22-11:18:34-pid=10212.txt
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\invokeai\.venv\lib\site-packages\ldm\invoke\dynamic_prompts.py", line 169, in _run_invoke
    with open(logfile, "w") as stderr, redirect_stderr(stderr):
OSError: [Errno 22] Invalid argument: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\invokeai-batch-logs\\2023-03-22-11:18:34-pid=10212.txt'
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in               │
│ _run_module_as_main                                                                              │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code      │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from ldm.invoke.dynamic_prompts import main                                                  │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ C:\Users\Administrator\invokeai\.venv\lib\site-packages\ldm\invoke\dynamic_prompts.py:245 in     │
│ main                                                                                             │
│                                                                                                  │
│   242 │   │   parser.print_help()                                                                │
│   243 │   │   sys.exit(-1)                                                                       │
│   244 │                                                                                          │
│ ❱ 245 │   expand_prompts(                                                                        │
│   246 │   │   template_file=opt.template_file,                                                   │
│   247 │   │   run_invoke=opt.invoke,                                                             │
│   248 │   │   invoke_model=opt.model,                                                            │
│                                                                                                  │
│ C:\Users\Administrator\invokeai\.venv\lib\site-packages\ldm\invoke\dynamic_prompts.py:102 in     │
│ expand_prompts                                                                                   │
│                                                                                                  │
│    99 │   │   │   sequence = 0                                                                   │
│   100 │   │   │   for command in commands:                                                       │
│   101 │   │   │   │   sequence += 1                                                              │
│ ❱ 102 │   │   │   │   parent_conn.send(                                                          │
│   103 │   │   │   │   │   command + f' --fnformat="dp.{sequence:04}.{{prompt}}.png"'             │
│   104 │   │   │   │   )                                                                          │
│   105 │   │   │   parent_conn.close()                                                            │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\connection.py │
│ :206 in send                                                                                     │
│                                                                                                  │
│   203 │   │   """Send a (picklable) object"""                                                    │
│   204 │   │   self._check_closed()                                                               │
│   205 │   │   self._check_writable()                                                             │
│ ❱ 206 │   │   self._send_bytes(_ForkingPickler.dumps(obj))                                       │
│   207 │                                                                                          │
│   208 │   def recv_bytes(self, maxlength=None):                                                  │
│   209 │   │   """                                                                                │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\connection.py │
│ :280 in _send_bytes                                                                              │
│                                                                                                  │
│   277 │   │   │   _CloseHandle(self._handle)                                                     │
│   278 │   │                                                                                      │
│   279 │   │   def _send_bytes(self, buf):                                                        │
│ ❱ 280 │   │   │   ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)                │
│   281 │   │   │   try:                                                                           │
│   282 │   │   │   │   if err == _winapi.ERROR_IO_PENDING:                                        │
│   283 │   │   │   │   │   waitres = _winapi.WaitForMultipleObjects(                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
BrokenPipeError: [WinError 232] The pipe is being closed`

the key to the problem is that windows can't have ':' in filepaths, so the tool is trying to create a logfile that isn't permitted in Windows:
`OSError: [Errno 22] Invalid argument: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\invokeai-batch-logs\\2023-03-22-11:18:34-pid=10212.txt'`

The same service works very neatly indeed on Ubuntu and has no issues creating the logfile, as is expected because ':' is permitted in filepaths in Ubuntu.

### Contact Details

One Eye#3268

**Comment by lstein** [comment]
Arrrrgh. I'm sorry I didn't think of this and even sorrier I didn't test on Windows. A fix is forthcoming.

**Comment by EdSisson** [comment]
> Arrrrgh. I'm sorry I didn't think of this and even sorrier I didn't test on Windows. A fix is forthcoming.

Please don't apologise, you're all doing great work and we're all very grateful. Thanks for the swift attention!

**Comment by lstein** [comment]
This should now be fixed in the 2.3.3. release candidate.
