### ISSUE TITLE
[bug]: Not loading models keeps popping up new errors  

### ISSUE THREAD

**Issue by Lolagatorade** [invoke-ai/InvokeAI#3006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

6gb

### What version did you experience this issue on?

3.0 & 2.3

### What happened?

loaded as normal suspecting after a system update this occurred. Rolling release manjaro arch linux. 

invokeai --web --no-patchmatch                               ✔  5s   base  
2023-03-23 11:15:15.066206: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-23 11:15:15.194294: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-03-23 11:15:15.652897: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-03-23 11:15:15.652964: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-03-23 11:15:15.652975: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
* Initializing, be patient...
>> Initialization file /home/helios/invokeai/invokeai.init found. Loading...
>> Internet connectivity is False
>> InvokeAI, version 3.0.0+a0
>> InvokeAI runtime directory is "/home/helios/invokeai"
>> GFPGAN Initialized
>> CodeFormer Initialized
>> ESRGAN Initialized
>> Using device_type cuda
>> xformers not installed
>> NSFW checker is disabled
>> Current VRAM usage:  0.00G
>> Loading diffusers model from stabilityai/stable-diffusion-2-1-base
  | Using faster float16 precision
  | Default image dimensions = 512 x 512
>> Loading embeddings from /home/helios/invokeai/embeddings
** Notice: unrecognized embedding file format: /home/helios/invokeai/embeddings/token_identifier.txt
** Notice: embeddings/learned_embeds.bin was trained on a model with an incompatible token dimension: 1024 vs 768.
>> Textual inversion triggers: 
>> Model loaded in 1.32s
>> Max VRAM used to load the model: 0.00G 
>> Current VRAM usage:0.00G
>> Setting Sampler to k_lms (LMSDiscreteScheduler)

* --web was specified, starting web server...
Loading Python libraries...

* Initializing, be patient...
>> Initialization file /home/helios/invokeai/invokeai.init found. Loading...
>> Started Invoke AI Web Server
>> Default host address now 127.0.0.1 (localhost). Use --host 0.0.0.0 to bind any address.
>> Point your browser at http://127.0.0.1:9090

### Screenshots

![image](https://user-images.githubusercontent.com/42100725/227157950-2b1e6e82-d4d7-4f7a-94c5-30da9de157cc.png)

**Comment by lstein** [comment]
You don't actually say so, but I'm assuming that generation fails when you try to make an image?

The warning messages you are seeing have to do with NVidia's tensorflow library, which in fact InvokeAI doesn't use. Perhaps when the underlying `pytorch` machine learning library is loading, it probes tensorflow and triggers these warnings. However, these are just warnings and as far as I can tell they shouldn't affect InvokeAI's operations. Could you confirm?

I googled the problem and came up with this thread, which has a proposed solution: https://stackoverflow.com/questions/60368298/could-not-load-dynamic-library-libnvinfer-so-6

**Comment by Lolagatorade** [comment]
> You don't actually say so, but I'm assuming that generation fails when you try to make an image?
> 
> The warning messages you are seeing have to do with NVidia's tensorflow library, which in fact InvokeAI doesn't use. Perhaps when the underlying `pytorch` machine learning library is loading, it probes tensorflow and triggers these warnings. However, these are just warnings and as far as I can tell they shouldn't affect InvokeAI's operations. Could you confirm?
> 
> I googled the problem and came up with this thread, which has a proposed solution: https://stackoverflow.com/questions/60368298/could-not-load-dynamic-library-libnvinfer-so-6

It wasnt working for a few days... Today works 🤷🏾‍♂️. Thanks for the advice ille fix those warnings.

**Comment by Lolagatorade** [comment]
Theres other unexpected behavior when running invokeai-update or invokeai-configure

invokeai-configure                                                1 ✘  base  
2023-03-24 08:45:37.351463: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-24 08:45:37.474294: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-03-24 08:45:37.906799: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/helios/.local/lib/python3.10/site-packages/cv2/../../lib64:
2023-03-24 08:45:37.906869: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/helios/.local/lib/python3.10/site-packages/cv2/../../lib64:
2023-03-24 08:45:37.906879: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Loading Python libraries...

* Initializing, be patient...
>> Initialization file /home/helios/invokeai/invokeai.init found. Loading...
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /opt/anaconda/bin/invokeai-configure:8 in <module>                                               │
│                                                                                                  │
│   5 from invokeai.frontend.install import invokeai_configure                                     │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(invokeai_configure())                                                           │
│   9                                                                                              │
│                                                                                                  │
│ /home/helios/.local/lib/python3.10/site-packages/invokeai/backend/config/invokeai_configure.py:8 │
│ 31 in main                                                                                       │
│                                                                                                  │
│   828 │   │   │   │   precision="float32" if opt.full_precision else "float16"                   │
│   829 │   │   │   )                                                                              │
│   830 │   │   else:                                                                              │
│ ❱ 831 │   │   │   init_options, models_to_download = run_console_ui(opt, init_file)              │
│   832 │   │   │   if init_options:                                                               │
│   833 │   │   │   │   write_opts(init_options, init_file)                                        │
│   834 │   │   │   else:                                                                          │
│                                                                                                  │
│ /home/helios/.local/lib/python3.10/site-packages/invokeai/backend/config/invokeai_configure.py:6 │
│ 83 in run_console_ui                                                                             │
│                                                                                                  │
│   680 │                                                                                          │
│   681 │   set_min_terminal_size(MIN_COLS, MIN_LINES)                                             │
│   682 │   editApp = EditOptApplication(program_opts, invokeai_opts)                              │
│ ❱ 683 │   editApp.run()                                                                          │
│   684 │   if editApp.user_cancelled:                                                             │
│   685 │   │   return (None, None)                                                                │
│   686 │   else:                                                                                  │
│                                                                                                  │
│ /home/helios/.local/lib/python3.10/site-packages/npyscreen/apNPSApplication.py:30 in run         │
│                                                                                                  │
│   27 │   def run(self, fork=None):                                                               │
│   28 │   │   """Run application.  Calls Mainloop wrapped properly."""                            │
│   29 │   │   if fork is None:                                                                    │
│ ❱ 30 │   │   │   return npyssafewrapper.wrapper(self.__remove_argument_call_main)                │
│   31 │   │   else:                                                                               │
│   32 │   │   │   return npyssafewrapper.wrapper(self.__remove_argument_call_main, fork=fork)     │
│   33                                                                                             │
│                                                                                                  │
│ /home/helios/.local/lib/python3.10/site-packages/npyscreen/npyssafewrapper.py:41 in wrapper      │
│                                                                                                  │
│    38 │   │   wrapper_no_fork(call_function)                                                     │
│    39 │   else:                                                                                  │
│    40 │   │   if _NEVER_RUN_INITSCR:                                                             │
│ ❱  41 │   │   │   wrapper_no_fork(call_function)                                                 │
│    42 │   │   else:                                                                              │
│    43 │   │   │   wrapper_fork(call_function, reset=reset)                                       │
│    44                                                                                            │
│                                                                                                  │
│ /home/helios/.local/lib/python3.10/site-packages/npyscreen/npyssafewrapper.py:83 in              │
│ wrapper_no_fork                                                                                  │
│                                                                                                  │
│    80 │   if _NEVER_RUN_INITSCR:                                                                 │
│    81 │   │   _NEVER_RUN_INITSCR = False                                                         │
│    82 │   │   locale.setlocale(locale.LC_ALL, '')                                                │
│ ❱  83 │   │   _SCREEN = curses.initscr()                                                         │
│    84 │   │   try:                                                                               │
│    85 │   │   │   curses.start_color()                                                           │
│    86 │   │   except:                                                                            │
│                                                                                                  │
│ /opt/anaconda/lib/python3.10/curses/__init__.py:29 in initscr                                    │
│                                                                                                  │
│    26 │   import _curses, curses                                                                 │
│    27 │   # we call setupterm() here because it raises an error                                  │
│    28 │   # instead of calling exit() in error cases.                                            │
│ ❱  29 │   setupterm(term=_os.environ.get("TERM", "unknown"),                                     │
│    30 │   │   │     fd=_sys.__stdout__.fileno())                                                 │
│    31 │   stdscr = _curses.initscr()                                                             │
│    32 │   for key, value in _curses.__dict__.items():                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
error: setupterm: could not find terminfo database





&

invokeai-update                                              ✔  7s   base  
Traceback (most recent call last):
  File "/opt/anaconda/bin/invokeai-update", line 5, in <module>
    from invokeai.frontend.config import invokeai_update
ModuleNotFoundError: No module named 'invokeai.frontend.config


Other than this all else seems fine. running 3.0.0+a0

**Comment by lstein** [comment]
Two problems here:
1. invokeai-update -- this is a bug, fixed in #3059 
2. invokeai-configure -- Something the matter with your environment:
    - Check that your TERM environment variable is set; it should be something like `xterm`
    - Check that your TERMINFO environment variable is set. It should be something like `/etc/terminfo`
Here's a StackOverflow thread that may help: https://stackoverflow.com/questions/9485699/setupterm-could-not-find-terminal-in-python-program-using-curses
