### ISSUE TITLE
[bug]: WebUI: I think this is supposed to say "link to image"

### ISSUE THREAD

**Issue by Barafu** [invoke-ai/InvokeAI#3022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.0.0

### What happened?

I think this is supposed to say "get link to image" or something like that. Because that's what it does. 

### Screenshots

![image](https://user-images.githubusercontent.com/6612364/227531417-37951944-0325-4a02-b451-14b2a8758bf1.png)

**Comment by blessedcoolant** [comment]
Copy Image To Link makes sense to me? @psychedelicious thoughts?

**Comment by Barafu** [comment]
This button takes a link to the image, served by web server, and copies the link, as text, to the clipboard. It does not do anything with the image.

**Comment by Adreitz** [comment]
I think perhaps "Copy Image Link" makes more sense.
