### ISSUE TITLE
[enhancement]: Reuse previous seeds with -1, -2...

### ISSUE THREAD

**Issue by felixsanz** [invoke-ai/InvokeAI#3026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I know you can right click and select "Use seed", but can InvokeAI store previous seeds and access them when the selected seed is -1, -2, -3... etc?

**Comment by Void2258** [comment]
-1 is used by many programs to indicate a random number.

**Comment by felixsanz** [comment]
> -1 is used by many programs to indicate a random number.

It's not the case for InvokeAI, so we can use it.

**Comment by Void2258** [comment]
We might not use it like that, but using it differently from standard might cause confusion for users.

**Comment by felixsanz** [comment]
Then... what about a button near the random seed switch, that when you click it reuses the last seed? available in all tabs. currently in the canvas is impossible to get the last seed

**Comment by lstein** [comment]
The CLI actually lets you reuse previous seeds by providing -1, -2 etc, but this convention doesn't work on the WebUI and there are prettier ways of implementing this enhancement with, e.g. a popup menu containing the last ten seeds used.
