### ISSUE TITLE
[bug]: Odd UI error on startup, randomly during use

### ISSUE THREAD

**Issue by Void2258** [invoke-ai/InvokeAI#3027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6gb

### What version did you experience this issue on?

2.3.2.post1

### What happened?

Receiving this error message on startup (sometimes more than once), and randomly later during use. Note I am not using the green colored UI. 

### Screenshots

![Screenshot 2023-03-24 140251](https://user-images.githubusercontent.com/6126362/227605830-656c32d9-87ef-4c8d-b362-16c91622081a.jpg)

### Additional context

No idea what or if this is doing anything. Just reporting as it appears to be some kind of uncaught exception.

**Comment by hipsterusername** [comment]
This just reports a temporary timeout/disconnect between frontend and backend. Shouldn’t impact much, aye? All works still?

**Comment by Void2258** [comment]
The only thing I have is that sometimes (irregularly) `send to unified canvas` will change to the canvas but it will be empty and I have to click it a second time to have the image show up there. I have no idea if it is related to this in any way; I have been trying to pin down the conditions before I report that one but I suppose _maybe_ it's related to this?

**Comment by Yorzaren** [comment]
It's the same error message as https://github.com/invoke-ai/InvokeAI/issues/1685 the only change seems to be the "removing descriptor" part, so the root of the problem might be the same bug?

**Comment by Void2258** [comment]
Not sure the "removing descriptor" part has anything to do with things I just grabbed everything in the vicinity of the error message.

**Comment by Void2258** [comment]
Yup does appear to be the same bug.

**Comment by Void2258** [comment]
This error appears to be proliferating. I am now seeing it repeat dozens of times on startup with 2.3.3. Still dosen't appear to actually do anything, but it's making the console almost unreadable as it swamps all other messages.
