### ISSUE TITLE
[enhancement]: add Kandinsky 2.0 - the first multilingual text2image model

### ISSUE THREAD

**Issue by 0-NiK-0** [invoke-ai/InvokeAI#3044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Ability to write Prompt in more than 100 languages.

Kandinsky 2.0 
https://github.com/ai-forever/Kandinsky-2.0
https://huggingface.co/sberbank-ai/Kandinsky_2.0

Model architecture:
It is a latent diffusion model with two multilingual text encoders:

mCLIP-XLMR 560M parameters
mT5-encoder-small 146M parameters
These encoders and multilingual training datasets unveil the real multilingual text-to-image generation experience!

Kandinsky 2.0 was trained on a large 1B multilingual set, including samples that we used to train Kandinsky.

In terms of diffusion architecture Kandinsky 2.0 implements UNet with 1.2B parameters.

<img width="1428" alt="NatallE" src="https://user-images.githubusercontent.com/126181396/227801239-dbda0ef4-6d67-4325-a18a-c25e1e3709d0.png">

**Comment by patrickvonplaten** [comment]
Available in Diffusers now btw: https://huggingface.co/docs/diffusers/v0.19.3/en/api/pipelines/kandinsky#diffusers.KandinskyPriorPipeline

**Comment by hipsterusername** [comment]
This can be added as a custom node very easily, using Diffusers.
