### ISSUE TITLE
[bug]: Not able to load seek art mega v2 could not be loaded: LatentDiffusion.__init__() missing 1 required positional argument: 'personalization_config'

### ISSUE THREAD

**Issue by sooraj007** [invoke-ai/InvokeAI#3047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24GB

### What version did you experience this issue on?

2.3.3

### What happened?

when trying to run civitai  seek art mega 2 model i am getting this error.
 Loading seekArtMEGA_mega20 from E:/invokeai/models/seek/seekArtMEGA_mega20.ckpt
   | Forcing garbage collection prior to loading new model
** model seekArtMEGA_mega20 could not be loaded: LatentDiffusion.__init__() missing 1 required positional argument: 'personalization_config'
Traceback (most recent call last):
  File "E:\invokeai\.venv\lib\site-packages\ldm\generate.py", line 958, in set_model
    model_data = cache.get_model(model_name)
  File "E:\invokeai\.venv\lib\site-packages\ldm\invoke\model_manager.py", line 121, in get_model
    requested_model, width, height, hash = self._load_model(model_name)
  File "E:\invokeai\.venv\lib\site-packages\ldm\invoke\model_manager.py", line 351, in _load_model
    model, width, height, model_hash = self._load_ckpt_model(
  File "E:\invokeai\.venv\lib\site-packages\ldm\invoke\model_manager.py", line 452, in _load_ckpt_model
    model = instantiate_from_config(omega_config.model)
  File "E:\invokeai\.venv\lib\site-packages\ldm\util.py", line 93, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()), **kwargs)
TypeError: LatentDiffusion.__init__() missing 1 required positional argument: 'personalization_config'

**Comment by lstein** [comment]
This error usually results when you provide the wrong config file for a legacy checkpoint model. I've made various improvements to model loading in version 2.3.3, including more intelligent scanning and config file selection. If you can, please check out the release candidate at: https://github.com/invoke-ai/InvokeAI/releases/tag/v2.3.3-rc3

If suggest that you use the standalone model installer to import the checkpoint file. You can get this by selecting option [5] from the launcher menu and then dragging the .ckpt file into the box labeled "IMPORT LOCAL AND REMOTE MODELS".
