### ISSUE TITLE
[bug]: CUDA Blocking 

### ISSUE THREAD

**Issue by ghigna** [invoke-ai/InvokeAI#3049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

2.3.2

### What happened?

I can't produce images also with the 512 resolution. This is the error message:
mage generation requested: {"prompt":"un gatto","iterations":1,"steps":25,"cfg_scale":10,"threshold":0,"perlin":0,"height":512,"width":512,"sampler_name":"k_dpmpp_2","seed":1993931784,"progress_images":false,"progress_latents":true,"save_intermediates":5,"generation_mode":"txt2img","init_mask":"","hires_fix":false,"seamless":false,"variation_amount":0}

2023-03-27T15:23:15+0200:

Server error: CUDA error: the launch timed out and was terminated CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by lstein** [comment]
I've not encountered this issue before. @keturn ?
