### ISSUE TITLE
[bug]: automated bat installer fails because numba won't install 

### ISSUE THREAD

**Issue by benninkcorien** [invoke-ai/InvokeAI#3052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

2.3.2

### What happened?

Trying to run install.bat so I can outpaint.

First it failed on pip install xformers. Manually  going into the venv and running pip there fixed that.
But now it fails on trying to install numba 

      Collecting numba
     Downloading numba-0.56.4.tar.gz (2.4 MB)
        ---------------------------------------- 2.4/2.4 MB 77.7 MB/s eta 0:00:00
      Installing build dependencies ... done
      Getting requirements to build wheel ... error
      error: subprocess-exited-with-error

And when I try to run that manually in the the venv:

        # pip install numba
            Collecting numba
            Using cached numba-0.56.4.tar.gz (2.4 MB)
            Preparing metadata (setup.py) ... error

I already have StableDiffusion running so assume my video drivers are all good, and I chose option 1/GPU with CUDA at the first invokeAI installer prompt.

I think the cause of this failure might be that there doesn't seem to be a numba whl file for python 3.11 (I checked https://www.wheelodex.org/projects/numba/) and I think I saw the invoke AI telling me 'updating python'. venv is running python 3.11.x 

### Screenshots

![Screenshot 2023-03-27 174528](https://user-images.githubusercontent.com/9899593/227993383-6e28adf6-f5b7-4db5-9248-07398b9e5d7a.png)

**Comment by lstein** [comment]
I can't tell from the screenshot what version of python you are running, but be aware that InvokeAI only supports Python 3.9 and 3.10. If you are running 3.11 then this helps explain the issue. You *might* have more success by adding the magic incantation `--use-pep517` to your pip line.

Not sure why you need install.bat to do outpainting. It works fine in the Web UI.

**Comment by benninkcorien** [comment]
The automated installer installs the latest version of Python on it's own, which is 3.11 . I don't know how to make it install 3.10 in the venv instead.

I like to integrate outpainting into my local install of stable diffusion.

**Comment by lstein** [comment]
The automated installer does not attempt to install python because it is itself a python script. Are you perhaps using an old installer from pre 2.3?

**Comment by benninkcorien** [comment]
I thought I saw something about "updating python" but I may be mistaken.
Either way numba won't install so the automated installed script fails - not sure if this is for everyone on Win11 who's running python 3.11, or if it's just me.

I downloaded the installer from https://github.com/invoke-ai/InvokeAI/releases/tag/v2.3.2.post1 

And - oops - I now see that that readme file for the installer actually mentions I need a python version lower than 3.11 
Off to google how I can downgrade python inside a venv, or how to force a venv to use a certain python version when it's created, and then I'll try to run the thing again. 

I landed here via a not-yet-finished-watching YouTube tutorial. 

The Invoke AI web UI will work great for me - I don't need this to plug-in to Stable diffusion Web UI (i thought it was an extension). As long as I can outpaint I'm happy.

**Comment by benninkcorien** [comment]
Managed to downgrade to Python 3.10 in the Venv.

(downloaded and installed Python 3.10)
 c:\Python310\python.exe -m venv testvenv

then copy all folders from tetvenv into .venv and overwrite everything and double check the pyvenv.cfg has Python 3.10 info in it.

numba installed.

Ran the installer again, and it really does say it's updating Python (though it's now installing wheels for 3.10 so I guess it's going OK now) :  


![image](https://user-images.githubusercontent.com/9899593/228308069-e7d60a82-657a-48f8-bed3-cef4d0f5cdd8.png)

**Comment by benninkcorien** [comment]
And now it can't find 'ldm' even though I manually pip installed it.. (bottom blue window was done before running the installer again).

![image](https://user-images.githubusercontent.com/9899593/228312736-8c29d212-21a9-4765-a93e-2ec4c1198f8c.png)

Aaaaand it's because the stupid installer has upgraded the python version inside the venv to 3.11 again . (grr!)
Pretty sure this is a bug.

**Comment by benninkcorien** [comment]
Victory

![image](https://user-images.githubusercontent.com/9899593/228324216-0b02673e-1e1e-41bb-a780-0a6f6009dc41.png)
