### ISSUE TITLE
[bug]: FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by AshKxK** [invoke-ai/InvokeAI#3062]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6

### What version did you experience this issue on?

2.3.2

### What happened?

I can't install it. I have python install via the .exe. I have selected to put itself in PATH, but when I try to run the .bat file it goes to MSYS2/MinGW64 ( i use it for gcc) and it wont install gfiving the same error as in the title

P.S: if you want to contact me contact me here or on email, I;m not that active on other platforms.

### Screenshots

![image](https://user-images.githubusercontent.com/60347401/228166745-495f8840-0d37-41b5-aaa6-a6027711809c.png)

### Contact Details

thelightwolfro@gmail.com, Ash_#7555

**Comment by lionelintw** [comment]
When I wanna upscale image，it fails with error message below。

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\My_username\\invokeai\\models/realesrgan/realesr-general-wdn-x4v3.pth'
