### ISSUE TITLE
[bug]: Web-UI start with error

### ISSUE THREAD

**Issue by RedstonePfalz** [invoke-ai/InvokeAI#3066]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS

Windows

### GPU

cpu

### VRAM

4GB

### What version did you experience this issue on?

2.3.2

### What happened?

I've installed InvokeAI. If I try to start the WEB-UI, I get this error:
![image](https://user-images.githubusercontent.com/55254344/228338835-1cbd176a-71d7-4551-af03-675ae8feb819.png)
![image](https://user-images.githubusercontent.com/55254344/228338934-93f05587-84fa-4013-9430-e6db334b76ed.png)

I hope, someone can help.

**Comment by lstein** [comment]
There seems to be an extra space after the path to the outputs directory. Please use a text editor (such as Notepad) to edit the file `invokeai.init` located in the invokeai root directory (usually C:\Users\your-name\invokeai). Find this line and remove the whitespace you may find after the outputs directory name:

```
--outdir="C:/users/your-name/invokeai/outputs "
```
