### ISSUE TITLE
[bug]: Outpainting dont work

### ISSUE THREAD

**Issue by Beaglyy** [invoke-ai/InvokeAI#3067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

amd

### VRAM

16gb

### What version did you experience this issue on?

2.3.2

### What happened?

When I try to expand the image it draws me some random patterns

### Screenshots

![image](https://user-images.githubusercontent.com/129234935/228391572-788fab65-940c-417b-9908-7c3eecc9b1e5.png)

**Comment by Barafu** [comment]
What I see: 

- CFG may be too low
- Seed is locked
- I don't see prompt. Errors in prompt syntax may cause this.
