### ISSUE TITLE
[bug]: At max GPU load I lose my wifi connection

### ISSUE THREAD

**Issue by mertselimb** [invoke-ai/InvokeAI#3070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24

### What version did you experience this issue on?

2.3.2.post1

### What happened?

I have a MSI Ventux 3x rtx 4090 at max load wifi is shown "no internet connection". I am still connected but I just cant reach internet. It is being solved if I close invoke ai. It pulls around 350 watt but I have a 1000 watt psu so It should'nt be a issue.

**Comment by gsreeves** [comment]
I've never had laggy OS during full GPU usage, ever since 2.2.4, until this last release 2.3.3.
However I'm on MPS. Monitoring GPU and CPUs, I see full GPU like always, and plenty of unused CPU like always.
It's like it's attacking the kernel.

**Comment by wogam** [comment]
Hi, I think this is a hardware issue. The GPU produces an EM field when in use, which affects the Wi-Fi card. Is your Wi-Fi card shielded?
