### ISSUE TITLE
[bug]: new imported checkpoint models generate only black images

### ISSUE THREAD

**Issue by MarcoBlumenthal** [invoke-ai/InvokeAI#3071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12

### What version did you experience this issue on?

2.3.3-rc5

### What happened?

added 4 checkpoint models (based on SD1.5 from different content providers, downloaded from civitai) to the import folder, today. On start, InvokeAi imported these and converted them to diffuser models. Successfully, it said. After starting the browser GUI,  I switched to these models and tried to generate images (txt2img) . In all cases the generation started with a black image (instead of a noise image) and the images remained black. When switching to other checkpoint models imported a couple of days before, everything worked fine, images were generated as expected. I used exactly the same prompt and settings for the models imported today and the older ones. When switching back to the new imported models -> again black images. A Restart of my computer did not help, same behaviour afterwards.

### Contact Details

marco.blumenthal@gmx.de

**Comment by cwallen** [comment]
I'm seeing the same. It's apparently a Civitai bug. Some sort of file corruption on anything downloaded today.
