### ISSUE TITLE
[bug]: Saturation drops significantly in the final result

### ISSUE THREAD

**Issue by slavikshen** [invoke-ai/InvokeAI#3073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### What version did you experience this issue on?

2.3.3-rc6

### What happened?

Colors are lighter than the results from from 2.3.2, for the same model, vae, and other params.
It looks like pairing the wrong VAE with the model.
During the generating progress, the colors in the snapshots look vivid.  However the saturation drops significantly in the final result.

I have tested with 
VAEs: kl-f8-anime2 orangemix.vae.pt
Models: Anythingv4 abyssorangemix3AOM3_aom3a1b

### Screenshots

snapshots during decoding
![image](https://user-images.githubusercontent.com/606110/228910339-d0b47318-e4a6-4d32-8a78-634076fa4484.png)

![image](https://user-images.githubusercontent.com/606110/228911600-852ada1a-4658-43ff-a0b3-1e310c9c9cb5.png)

![image](https://user-images.githubusercontent.com/606110/228911557-03e47d65-cebc-444a-ab7a-a5cbae3179b3.png)

Here is the low saturation result
![007232 7af5d488 2351070486](https://user-images.githubusercontent.com/606110/228908524-640ad4d3-5374-44c1-8204-052d25e1cc9f.png)

**Comment by slavikshen** [comment]
> You are right that this is a VAE issue. However I think that what is happening is the opposite of an incorrect pairing. Due to a bug in VAE handling in 2.3.2, InvokeAI was frequently replacing the custom VAE with the standard stable diffusion VAE (i.e. `vae-ft-mse-840000-ema-pruned.ckpt`). This has been fixed in 2.3.3, and so you are now seeing the intended results.
> 
> I'm not 100% certain about this, however, and what you can do to confirm is to look at the log messages on the console when the model is first loaded. It should print out a message when the VAE is loaded. I'll also check on my end.
> 
> On a related topic, I've tried to make it easier to associate a custom VAE with checkpoint models in 2.3.3 by letting you put the VAE in the same directory as the checkpoint and giving it the same base name:
> 
> ```
> AnythingV4.ckpt
> AnythingV4.vae.pt
> ```
> 
> Thanks so much for the bug report!

I have been using the same pair of vae and models since 2.1.  They are in my models.yaml 
So I'm sure they are paired correctly.
I have also checked the terminal.
The log shows that the right vae is loaded.
<img width="629" alt="image" src="https://user-images.githubusercontent.com/606110/228919463-4ef70ff7-a120-48ac-a141-1fbc7f49023c.png">

**Comment by guyray** [comment]
Im having the same issue with the lastest version, vae is loaded in log but the output is low saturation.

**Comment by lstein** [comment]
I just checked this and you are right. Something in VAE handling broke between 2.3.2 and 2.3.3. Hopefully I will find and commit a fix tonight.

**Comment by n00mkrad** [comment]
> You are right that this is a VAE issue. However I think that what is happening is the opposite of an incorrect pairing. Due to a bug in VAE handling in 2.3.2, InvokeAI was frequently replacing the custom VAE with the standard stable diffusion VAE (i.e. `vae-ft-mse-840000-ema-pruned.ckpt`). This has been fixed in 2.3.3, and so you are now seeing the intended results.
> 
> I'm not 100% certain about this, however, and what you can do to confirm is to look at the log messages on the console when the model is first loaded. It should print out a message when the VAE is loaded. I'll also check on my end.
> 
> On a related topic, I've tried to make it easier to associate a custom VAE with checkpoint models in 2.3.3 by letting you put the VAE in the same directory as the checkpoint and giving it the same base name:
> 
> ```
> AnythingV4.ckpt
> AnythingV4.vae.pt
> ```
> 
> This works if you don't explicitly specify the VAE during model importing.
> 
> Thanks so much for the bug report!

Specifying VAE in models.json is still completely broken.

**Comment by lstein** [comment]
There's no `models.json` in InvokeAI. Do you mean `models.yaml`? If so, what did you do and what did you observe?

**Comment by lstein** [comment]
The bug has been found and fixed here in current release candidate (rc7).

**Comment by n00mkrad** [comment]
> There's no `models.json` in InvokeAI. Do you mean `models.yaml`? If so, what did you do and what did you observe?

My bad, of course I was referring to models.yaml.

The issue is/was that the following entry:

```yaml
StableDiffusion-v1.5.diff-vae-ft-mse-840000-ema-pruned:
    format: diffusers
    path: "../../models/StableDiffusion-v1.5.diff"
    vae: "../../models/vae/vae-ft-mse-840000-ema-pruned"
    width: 512
    height: 512
```

Did not load the specified VAE (no matter which one I specified). It would use the backed-in VAE still. The model is Diffusers, so is the VAE.
