### ISSUE TITLE
[enhancement]: when fixing a broken install, try detecting / fixing individual issues

### ISSUE THREAD

**Issue by ebr** [invoke-ai/InvokeAI#3087]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

for example, when selecting the launcher option to "fix a broken install", we unconditionally re-download support models (equivalent to the `--yes` flag). This is unexpected, and may be undesirable. instead, we should:

- attempt to fix various config issues first (missing/malformed files)
- decide if we want to re-download supporting models. those are rarely broken, but sometimes it is indeed the issue.
- ask if the user wants to download a *single* known-good model (sd1.5)

and ultimately, we should implement specific checks for known environment problems (are models present? are configs present? is the initfile malformed?), and only fix the issues that are detected.

**Comment by Void2258** [comment]
This would certainly be helpful. I had to do a full and reinstall in order to fix problems, and while this might have still been necessary it;'s possible that a different way of checking could have found the issue instead of just the whole process failing.
