### ISSUE TITLE
[bug]: no responding when auto install basicsr>=1.4.2 it's stop process intalling backend dependence

### ISSUE THREAD

**Issue by optemoy** [invoke-ai/InvokeAI#3113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8

### What version did you experience this issue on?

InvokeAI Version 2.3.3

### What happened?

i try to reinstall invoke ai multiply time.  always no response when install basicsr backend dependencs, my pc had install stable diffuse web ui. i'm not sure it's impact this install env.

**Comment by Raecaug** [comment]
I'm also having this issue at the moment, as are several others in the Discord.

**Comment by Raecaug** [comment]
@optemoy seems this is related to #3122

**Comment by lstein** [comment]
Please try this again in an hour or two. I think the HuggingFace server is having issues.

**Comment by optemoy** [comment]
after long time wait about 20mines , it's success install this package, idk what reason cause it.  but now have other problem, ModuleNotFoundError: No module named 'npyscreen'.  no matter i close this issue.
