### ISSUE TITLE
[enhancement]: Scripts for automatic generation

### ISSUE THREAD

**Issue by Doumor** [invoke-ai/InvokeAI#3114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Most of the work with neural networks is routine. First I generate 512x512 art, eliminate the bad ones, and then refine the good ones to the highest available resolution in img2img (like High Res Fix, which is 1536x1536 for me) several times with different samplers. I wish I didn't have to wait until I was done, I could just say "...when I'm done, run image N img2img with these settings 5 times, with these settings 5 times and with these 5 more times" and it would be like a queue of those commands.

I'm not immersed in the code of the project, so in terms of code I can hardly help (at most I could write a "wrapper" to perform such a task in the CLI), but it would be an extremely useful feature if it was in the web ui.

I see the scripts themselves as JSON strings stored in separate files, which would also record the results. For example:

```
scripts: [{prompt: {...}, general: {img: 5, steps: 20, cfg: 7, ...}, {...}],
result: [img1.png, ...], //after each finish```

### Alternatives

_No response_

### Aditional Content

_No response_

**Comment by Barafu** [comment]
You really should learn some Python. Or Powershell. Or Bash. With the existing API, this task is easily automated already.

**Comment by lstein** [comment]
This type of automation is coming in the 3.X branch, where we'll be providing you with a series of "nodes", each of which performs an operation. You can hook them up graphically to feed the output of one node into the input of another.

**Comment by Doumor** [comment]
> You really should learn some Python. Or Powershell. Or Bash. With the existing API, this task is easily automated already.

I know these languages and I'm not talking about APIs, I'm talking about automation right in the graphics.

**Comment by Doumor** [comment]
> This type of automation is coming in the 3.X branch, where we'll be providing you with a series of "nodes", each of which performs an operation. You can hook them up graphically to feed the output of one node into the input of another.

That's not quite it. I need a line to tell me what to do, for example:
This picture in img2img with such parameters and so many times, and afterwards make me 50 pictures with such parameters.

In short, I need to make sure that I'm always loading and generating only what I think is nice, and the nodes won't let me do that.

Automation, which is proposed above will be simply uncomfortable, because I need to work in a graphical mode.

**Comment by hipsterusername** [comment]
Node editor will allow for this type of interaction
