### ISSUE TITLE
[bug]: Invokeai-Batch on Windows, with long paths enabled a single filename can't be of unlimited length. process silently fails

### ISSUE THREAD

**Issue by EdSisson** [invoke-ai/InvokeAI#3115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8

### What version did you experience this issue on?

2.3.3

### What happened?

using rc 2.3.3 to test a recent issue with filepaths, batch works effectively using the example yml but fails with prompts of a certain length which would force the file saved to be longer than 246 characters. This is with longpathsenabled. A long-named file can be copied into another directory with a much longer name, implying that their is a max-limit on the filename itself, as long as on the full path.

Is it possible to either automatically shorten paths which are too long, or to add a switch that might allow us to provide an 'override' filename please?

Logs for prompts which are too long Simply show Generating 0% line after line:

>> Initialization file C:\Users\Administrator\invokeai\invokeai.init found. Loading...

Fetching 15 files:   0%|                                                                                                                                             | 0/15 [00:00<?, ?it/s]
Fetching 15 files: 100%|############################################################################################################################################| 15/15 [00:00<?, ?it/s]

Generating:   0%|                                                                                                                                                     | 0/1 [00:00<?, ?it/s]
Generating:   0%|                                                                                                                                                     | 0/1 [00:09<?, ?it/s]

Generating:   0%|                                                                                                                                                     | 0/1 [00:00<?, ?it/s]
Generating:   0%|                                                                                                                                                     | 0/1 [00:09<?, ?it/s]

Generating:   0%|                                                                                                                                                     | 0/1 [00:00<?, ?it/s]
Generating:   0%|                                                                                                                                                     | 0/1 [00:09<?, ?it/s]

Generating:   0%|                                                                                                                                                     | 0/1 [00:00<?, ?it/s]

### Contact Details

One Eye#3268

**Comment by Barafu** [comment]
This may be xformers problem. At least they had this problem a few weeks ago.

**Comment by lstein** [comment]
Thanks for drawing this to my attention. I am puzzled because Windows 10 with the long path registry patch applied is supposed to handle 32K filenames. I will either truncate the names or find another solution.

**Comment by lstein** [comment]
Could you see if this pull request fixes the problem? https://github.com/invoke-ai/InvokeAI/pull/3143

Thx

**Comment by jameswan** [comment]
invokeai-batch has been removed
