### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by leeleersun** [invoke-ai/InvokeAI#3119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What version did you experience this issue on?

latest version

### What happened?

The auto-installation is finished, but when I open http://127.0.0.1:9090/, the browser shows "{hello: clash}" on the page. It doesn't show the dashboard correctly

### Contact Details

leeleersun@163.com

**Comment by ebr** [comment]
could you please provide more details / screenshots? which version is this?
