### ISSUE TITLE
[bug]: RuntimeError: Attempting to deserialize object on a CUDA device but  torch.cuda.is_available() is False. If you are running on a CPU-only machine,  please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

### ISSUE THREAD

**Issue by ynwasd** [invoke-ai/InvokeAI#3121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What version did you experience this issue on?

2.3.3

### What happened?

when opening InvokeAI I get the error message
RuntimeError: Attempting to deserialize object on a CUDA device but 
torch.cuda.is_available() is False. If you are running on a CPU-only machine, 
please use torch.load with map_location=torch.device('cpu') to map your storages
to the CPU.

### Additional context

there is an existing but inactive report on this issue on a different version but the solution does not work for me.

**Comment by mindfu23** [comment]
I also have this error.
If I have to update the code to fix this, I can do that. Where and what should be updated in which script so this can worka/
