### ISSUE TITLE
[bug]: Installation Stuck on BERT Tokenizer Installation

### ISSUE THREAD

**Issue by bth117** [invoke-ai/InvokeAI#3122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

2.3.3 & 2.3.2.post1

### What happened?

Hello,

I had successfully installed and used v2.3.2.post1 several days ago. I decided to delete my installation folder and start with a clean install of 2.3.3 today.  After deleting my root folder (D:\0_InvokeAI), I have not been able to re-install 2.3.3 or 2.3.2.post1 versions. I cannot figure out why. All install steps proceed as normal until the "Downloading Support Models" step. Installer gets stuck on installing bert tokenizer. A folder called 'models--bert-base-uncased' is created in the models folder and the progress bar shows that the tokenizer_config.json file is 100% downloaded. I have let it sit for 4.5 hours like this but no progress.

Any help is greatly appreciated! I cannot find a similar issue to help me. I have already tried the following:

- delete/reinstall
- reinstall to new location
- followed the installation troubleshooting guide --> pip install InvokeAI --force-reinstall
- I also cloned the developer's source code but that still failed on the same step

Thanks!

### Screenshots

![Screenshot 2023-04-05 185845](https://user-images.githubusercontent.com/53540248/230230716-8f057b40-5b4c-4905-91f8-754e59cafdb7.png)

### Additional context

I am not very familiar with Python as I do most of my professional work in R. If there is an install log file etc that could be helpful, please let me know and I will upload it ASAP. The install simply fails to progress past this step. There is no error/termination/warning message etc. to show here. Installer simply gets to this point and that's it.

**Comment by DaveSanders** [comment]
I want to second this - I've run the installer three times in the past hour and also Bert just hangs.

I ran the bat anyway and tried to install models through there, but I've had it hang twice there too. Both with SD-2-base model, the first time it hung on the last file. The second time it hung even starting.

Annnnd, the web ui won't load for me. Python error. Don't know if tis related to me stopping the install on the Bert file or what. But can't seem to run it at all.

**Comment by lstein** [comment]
As of this afternoon (April 5, approximately 3 pm EDT) everybody with a Windows system started having this issue. It also affects the Windows test servers that the InvokeAI team uses on github. The symptom is that the BERT tokenizer file, which is required for InvokeAI to run, hangs indefinitely during download.

This appears to be a problem on the HuggingFace download server. The InvokeAI team has filed bug reports and expects the situation to resolve soon. Until then, there is no easy workaround unfortunately.

**Comment by HugoSart** [comment]
I was able to find a workaround by manually install missing references:

1. Download [this](https://huggingface.co/openai/clip-vit-large-patch14) repo and put it on the folder "openai/clip-vit-large-patch14" (create the folder if it does not exist);
2. Download codeformer.pth and put It on "models/codeformer";
3. Download GFPGANv1.4 and put it on "models/gfpgan";
4. Open invokeai;
5. Download a checkpoint from the internet and, using the web UI (or CLI), add the model using the local path;

If this doesn't work, I might have forgotten one or more steps I did, but this is a good start.

**Comment by GitchNZ** [comment]
I've got the same issue. Looks like it's failing because of an invalid filename. While it's in a hung state, process monitor just gives repeat 'NAME INVALID' errors for:
[install location]\models\hub\models--bert-base-uncased\blobs\W\"fb140275c155a9c7c5a3b3e0e77a9e839594a938.lock

Not sure whether it's the " in the filename causing the issue of if this is a red herring

**Comment by gigawolfo** [comment]
Same here

![2023_04 6-093752](https://user-images.githubusercontent.com/123992626/230308249-58be6208-b8af-4fa4-86a0-f4701697ab0b.png)

**Comment by emb3rn** [comment]
I believe there was a similar issue with Automatic1111's installer at some point, and as @GitchNZ mentioned this was due to invalid symbols. A simple name[3:] solved the issue.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7901#issuecomment-1497850222

**Comment by lstein** [comment]
This bug turned out to be an issue on the HuggingFace side and was fixed last night. Here's the thread in case anyone's interested: https://github.com/huggingface/transformers/issues/22598
