### ISSUE TITLE
[bug]: nodes does not free gpu memory

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#3125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

24GB

### What version did you experience this issue on?

nodes

### What happened?

nodes does not free GPU memory after generation

in the screenshot below, using nodes cli, displaying `nvtop` output during generation:

- green underline = 512x512
- yellow underline = 1024x1024
- reddish underline = 1536x1536
- blue underline = 512x512

![Screenshot 2023-04-06 at 16 30 57](https://user-images.githubusercontent.com/4822129/230290781-d681450d-f809-448f-9c21-fdba6a5dc138.png)

**Comment by Kyle0654** [comment]
Does it eventually even put? After e.g. 20 generations? Nodes does retain results in a cache, and caches the model, though I can't imagine why it would keep that much in memory.
________________________________
