### ISSUE TITLE
[bug]: Black image generation

### ISSUE THREAD

**Issue by dnash90** [invoke-ai/InvokeAI#3136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

10

### What version did you experience this issue on?

2.3.3

### What happened?

There are several posts already which have seemed to be resolved which may have been stemming from VAE related issues or od NSFW flags. Not sure if it is still the case - but I've found it still occasionally happening with one particular model "Counterfeit V2.5" even after converting it to a diffuser. 
Preview and image saved to disk seem to memory dump and turn black. I can provide screenshots if necessary!

**Comment by SkyrimLL** [comment]
I have seen this on a couple of models recently, and on plain SFW prompts.

**Comment by dnash90** [comment]
Right, this was the point I was trying to convey. I was under the
impression it was due to a faulty flag for srw/nsfw.
I found in the case of counterfeit 2.5 the image sizing affects how often
this happens. Anything over 512 x 512 more frequently.

**Comment by lstein** [comment]
I've seen this too; there are a small number of models out there that produce black images stochastically. I tried to track this behavior down at one point but lost the trail deep in the bowels of pytorch. I'll try again, but I suspect that this is a problem that occurs at a deeper layer than InvokeAI's code and will not be an easy fix.

The workaround that I found is to merge the model with a similar one, using a very very small fraction from the other model (like a weight of 0.05). This generates images that are almost identical with what the original model produces, but without the black images appearing.

**Comment by dnash90** [comment]
> I've seen this too; there are a small number of models out there that produce black images stochastically. I tried to track this behavior down at one point but lost the trail deep in the bowels of pytorch. I'll try again, but I suspect that this is a problem that occurs at a deeper layer than InvokeAI's code and will not be an easy fix.
> 
> The workaround that I found is to merge the model with a similar one, using a very very small fraction from the other model (like a weight of 0.05). This generates images that are almost identical with what the original model produces, but without the black images appearing.

Oh clever! I will give this a go. Very interesting
