### ISSUE TITLE
[bug]: Instruments scrolling with long lora names

### ISSUE THREAD

**Issue by StAlKeR7779** [invoke-ai/InvokeAI#3144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

10GB

### What version did you experience this issue on?

2.3.4-rc1

### What happened?

When adding lora with long name, loras list tries to fit this fully, but can't be fitted to right instruments column.
So, by clicking right arrow instruments scrolls out of screen.
@blessedcoolant 

### Screenshots

![image](https://user-images.githubusercontent.com/7768370/230687640-c7f6500c-7fb6-4f9b-92d3-f29287f8c479.png)

**Comment by blessedcoolant** [comment]
Ah. I'll have a look. Thanks for catching this.
