### ISSUE TITLE
[bug]: Running InvokeAI from Windows Subsystem for Linux doesn't allow remote access to webserver

### ISSUE THREAD

**Issue by Raecaug** [invoke-ai/InvokeAI#3145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24GB

### What version did you experience this issue on?

2.3.3

### What happened?

When executing Invoke natively through Windows Powershell, the remote webserver can be accessed from out of network if portforwarding is setup. This does not work when running Invoke through the Windows Subsystem for Linux. All other behavior is normal, and on-device access of the webserver is possible.

**Comment by przemoc** [comment]
On Windows host (assuming 192.168.1.90 here) where you have InvokeAI in WSL use Administrator Command Prompt or PowerShell and run following command to set up appropriate port forwarding:

```
netsh interface portproxy add v4tov4 listenport=9090 listenaddress=192.168.1.90 connectport=9090 connectaddress=127.0.0.1
```

Now you can use IP of the Windows host where you have InvokeAI in WSL on different host.

If it still doesn't work, you may want to open Windows Defender Firewall with Advanced Security, Win+R, `wf.msc`, Enter, and create new inbound rule to allow the connection for TCP ports that are forwarded to WSL (9090 for now, but you may need to remember to extend it in the future if needed for other services) in your private network (allowing it in any other network types is typically not what you want, unless you really know what you're doing).

---

When you want to delete this port forwarding, run following command:

```
netsh interface portproxy delete v4tov4 listenport=9090 listenaddress=192.168.1.90
```

If you want to see existing port forwarding, run following command:

```
netsh interface portproxy show all
```
