### ISSUE TITLE
[enhancement]: faster torch download source, like A1111

### ISSUE THREAD

**Issue by Lesani** [invoke-ai/InvokeAI#3146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I am doing a fresh install, and while the slow torch download was running decided to use sd-webui. saw it also wanted to update xformers and torch, and to my surprise the download there is 10 times the speed:
![image](https://user-images.githubusercontent.com/5182104/230709528-9aead9e6-82a2-4321-97cd-6ce54be150d3.png)

both do not use up my connection, but 5,4mb/s is better than a constant 0,5mb/s

The feature idea is to do whatever they are doing to download the same version of torch faster.

**Comment by lstein** [comment]
I get pretty good download speeds for torch (between 50 and 100 MB/s). Were you able to consistently reproduce this speed differential?

**Comment by ebr** [comment]
We are downloading torch from the same sources and using the same `pip install` call. I don't think there is anything we can improve here.

**Comment by Lesani** [comment]
ok, if you are dowloading the same way, then that source seems to allocate different total bandwidths that don't change over the course of the download, seeing as my invoke download was capped to the 450KB/s all the way through. Not idal for downloads of that size, but if it's outside of your control than I guess this issue is safe to be closed?

**Comment by lstein** [comment]
I don't have a ready explanation for this, but I think it is outside our control to fix.
