### ISSUE TITLE
[bug]:  my dedicated gpu (rx6800m) in my laptop is not being used ad instead the integrated gpu is being used

### ISSUE THREAD

**Issue by FADthe9yearold** [invoke-ai/InvokeAI#3153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

amd

### VRAM

12

### What version did you experience this issue on?

2.3.2

### What happened?

I recently downloaded invoke ai and when ever i load an ai image it takes a few minutes for the image to load ,so when i checked task manager it showed the integrated gpu being utilized instead of the dedicated gpu

**Comment by kriptolix** [comment]
There is no support to windows with AMD GPU yet. AMD GPUs just work on Linux and Mac.
