### ISSUE TITLE
[bug]: Some Textual Inversions from HF Concepts Library are unusable out-of-the-box and should be filtered out

### ISSUE THREAD

**Issue by przemoc** [invoke-ai/InvokeAI#3165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What version did you experience this issue on?

2.3.4

### What happened?

I went through all 148 TIs available in InvokeAI when turning on "Show Textual Inversions from HF Concepts Library" today, which are all that have >= 5 likes IIUC. Some failed and thus should be filtered out from the list.

```
grep 'Generation will continue without the concept.' ~/python/stable-diffusion-workspace/invokeai-deliberate-sd-concepts-generations.txt
>> Downloading sd-concepts-library/akitsuki...Failed to download akitsuki/learned_embeds.bin (HTTP Error 403: Forbidden. Generation will continue without the concept.)
>> Downloading sd-concepts-library/rain_and_monsters...This concept is not known to the Hugging Face library. Generation will continue without the concept.
>> Downloading sd-concepts-library/sam-yang...Failed to download sam-yang/learned_embeds.bin (HTTP Error 403: Forbidden. Generation will continue without the concept.)
>> Downloading sd-concepts-library/sd-concepts-library-lora...This concept is not known to the Hugging Face library. Generation will continue without the concept. 
```

Failing ones are:

- https://huggingface.co/sd-concepts-library/Akitsuki
  > You need to agree to share your contact informations to access this model
- https://huggingface.co/sd-concepts-library/Rain_and_Monsters
  Described as created for SD v2, but I was using Deliberate v1, which is based on SD v1.5, so maybe that's why it failed?
  Or rather that it has no `learned_embeds.bin` but `prue640v2.pt`.
- https://huggingface.co/sd-concepts-library/sam-yang
  > Access to this model has been disabled
  > given explicit "no consent" by artist. see: https://www.youtube.com/watch?v=5Viy3Cu3DLk
- https://huggingface.co/sd-concepts-library/sd-concepts-library-lora
  There is no such repo. I'm guessing that current HF filter somehow wrongly picks up:
  https://huggingface.co/swl-models/sd-concepts-library-lora
  and it doesn't have `learned_embeds.bin`.

**Comment by lstein** [comment]
Thanks for the detective work. I had hoped to avoid this by only keeping models with at least 5 likes. I guess even bad ones have friends.

I'll see if there's a way to create a blacklist that is easily maintainable.
