### ISSUE TITLE
[bug]: --no-ckpt_convert not working

### ISSUE THREAD

**Issue by jonathanljs** [invoke-ai/InvokeAI#3172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8

### What version did you experience this issue on?

2.3.4

### What happened?

When opening models, Invoke automatically converts checkpoints to diffusers. I don't want it to do this, as my system doesn't work with diffusers for some reason. How do I stop this on-the-fly conversion? The option is not selected in startup options (option 6) / invokeai.init and changing here doesn't help. Have --no-ckpt_convert in init. Still converts!

### Contact Details

jonathanljs#0290

**Comment by hipsterusername** [comment]
Invoke's support of CKPT pipelines is being deprecated, so I think the solve here would be figuring out what issues you have with diffusers vs. stopping conversion. Let us know what issues you're experiencing w/ Diffusers

**Comment by jonathanljs** [comment]
Hey, thanks for the response. Two reinstalls later followed by a couple of installation repairs, and now as if by magic diffusers seem to be working for the first time. Don't ask me why. I was getting beige / mostly blank images, but not any more.

**Comment by hipsterusername** [comment]
That's great! We'll call this closed for now.

**Comment by jonathanljs** [comment]
Hi @hipsterusername - an update: I found where the problem lies. Diffusers work for me as long as Noise Threshold and Perlin Noise are set to 0. As soon as they're given any value at all, I get the beige rubbish images.

**Comment by hipsterusername** [comment]
> Hi @hipsterusername - an update: I found where the problem lies. Diffusers work for me as long as Noise Threshold and Perlin Noise are set to 0. As soon as they're given any value at all, I get the beige rubbish images.

That's probably more of those features being prone to do that, more than anything. At high values of perlin, or low values (<4.0-5.0) for threshold, they tend to turn stuff to rubbish.

**Comment by jonathanljs** [comment]
Oh yes, that works too. I am learning! Thanks again
