### ISSUE TITLE
[bug]: Reported Server Error : invalid literal for int() with base 10: '\x00\ x00\ x00\ x00'

### ISSUE THREAD

**Issue by GreyLedger** [invoke-ai/InvokeAI#3181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

2.3.2.post1

### What happened?

While inpainting on the unified canvas, an error occurred right after the generating finished, stopping the generation. 

### Screenshots

<img width="1276" alt="Screenshot 2023-04-12 215525" src="https://user-images.githubusercontent.com/130574163/231480251-fc9ed04c-03fb-47f9-8375-1cf937116e8f.png">
<img width="1280" alt="Screenshot 2023-04-12 215508" src="https://user-images.githubusercontent.com/130574163/231480274-baf3c0ec-cb8e-44e8-80ec-5483f96e8a6e.png">

### Additional context

This happened the day after my computer restarted while generating using unified canvas.

### Contact Details

sharkliang1116@gmail.com

**Comment by Herdol** [comment]
I also got the same error today. Last time I was generating an image and it killed my PSU. Now it gives this error. If you find any solution I will be following.
