### ISSUE TITLE
[bug]:

### ISSUE THREAD

**Issue by CyberModer77** [invoke-ai/InvokeAI#3183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

amd

### VRAM

8GB

### What version did you experience this issue on?

2.3.2

### What happened?

every time I open app to the website it says connected but after a while it will say disconnected for some reason and I have the terminal open

**Comment by kriptolix** [comment]
Can you give more details? What errors are displayed in the terminal when this happens?
