### ISSUE TITLE
[bug]: Bounding box ignores 512px render size if box size is above 512px

### ISSUE THREAD

**Issue by erhan-** [invoke-ai/InvokeAI#3193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

2.3.4

### What happened?

Hey everyone,
I have an upscaled an inpainted image, which I want to outpaint. When I choose a big bounding box like 1024x1024, I would like it to render the content still with 512x512 because of my low GPU specs.
But if I choose 1024x1024 as bounding box, it still tries to render as 1024x1024 and the resolution area at the left is greyed out.
Is this possible?
Thanks for your help!
Best regards,

**Comment by erhan-** [comment]
@hipsterusername Hey Kent, is this fixed?

**Comment by hipsterusername** [comment]
Hey @erhan- - This isn't really a "bug" per se.

However, you should be able to manually control the resolution being generated at within the bounding box using the manual "Scaled Bounding Box" setting, and enforcing a 512x512 generation.

**Comment by erhan-** [comment]
Hey @hipsterusername,

I know. I have written about it and that it doesnt work like that:

"But if I choose 1024x1024 as bounding box, it still tries to render as 1024x1024 and the resolution area at the left is greyed out.
Is this possible?" So I cant set it to 512x512 then. Has this been changed in the meantime and fixed was my question basically.

Thanks for your work!
