### ISSUE TITLE
[bug]: Error 'self.size(-1) must be divisible by 4 to view Byte as Float (different element  sizes)' running invokeai-config

### ISSUE THREAD

**Issue by drwootton** [invoke-ai/InvokeAI#3209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

50eb02f68be912276a9c106d5e8038a5671a0386

### What happened?

I set up my Python environment as directed, opened a new terminal window, activated the environment, then ran invokeai-configure to run on a NVidia RTX3060 GPU and using automatic floating point mode. 

Since I have a bunch of Stable Diffusion checkpoint models already downloaded, I did not request automatic download of any models, just pointed to my checkpoints directory.

After answering the configuration questions, the script ran for a bit then failed with a RuntimeError exception as shown in the screenshot.

I tried this again specifying different floating point modes and downloading the default models with no success. 

I decided to ignore Stable Diffusion 2.1 for now, so I commented out line 841 in git/InvokeAI/venv/lib/python3.10/site-packages/ldm/invoke/config/invokeai_configure.py. Then the configure seems to complete, at least there were no more errors.

I have a Stable Diffusion 2.1 checkpoint model I downloaded a couple months ago for use on a Windows system. I had problems with that rand automatic1111 related to fp16 floating point format, don't remember the error now. OI'm not sure if that has anything to do with this error.

### Screenshots

** INITIALIZING INVOKEAI RUNTIME DIRECTORY **
* Initializing, be patient...
>> Initialization file /home/dave/invokeai/invokeai.init found. Loading...

** DOWNLOADING SUPPORT MODELS **
Installing bert tokenizer...
Installing SD1 clip model...
Installing SD2 clip model...
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /nvme/dave/git/InvokeAI/venv/bin/invokeai-configure:8 in <module>                                │
│                                                                                                  │
│   5 from ldm.invoke.config.invokeai_configure import main                                        │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(main())                                                                         │
│   9                                                                                              │
│                                                                                                  │
│ /nvme/dave/git/InvokeAI/venv/lib/python3.10/site-packages/ldm/invoke/config/invokeai_configure.p │
│ y:841 in main                                                                                    │
│                                                                                                  │
│   838 │   │   │   print("\n** DOWNLOADING SUPPORT MODELS **")                                    │
│   839 │   │   │   download_bert()                                                                │
│   840 │   │   │   download_sd1_clip()                                                            │
│ ❱ 841 │   │   │   download_sd2_clip()                                                            │
│   842 │   │   │   download_realesrgan()                                                          │
│   843 │   │   │   download_gfpgan()                                                              │
│   844 │   │   │   download_codeformer()                                                          │
│                                                                                                  │
│ /nvme/dave/git/InvokeAI/venv/lib/python3.10/site-packages/ldm/invoke/config/invokeai_configure.p │
│ y:205 in download_sd2_clip                                                                       │
│                                                                                                  │
│   202 │   version = 'stabilityai/stable-diffusion-2'                                             │
│   203 │   print("Installing SD2 clip model...", file=sys.stderr)                                 │
│   204 │   download_from_hf(CLIPTokenizer, version, subfolder='tokenizer')                        │
│ ❱ 205 │   download_from_hf(CLIPTextModel, version, subfolder='text_encoder')                     │
│   206                                                                                            │
│   207 # ---------------------------------------------                                            │
│   208 def download_realesrgan():                                                                 │
│                                                                                                  │
│ /nvme/dave/git/InvokeAI/venv/lib/python3.10/site-packages/ldm/invoke/config/model_install_backen │
│ d.py:285 in download_from_hf                                                                     │
│                                                                                                  │
│   282 │   model_class: object, model_name: str, cache_subdir: Path = Path("hub"), **kwargs       │
│   283 ):                                                                                         │
│   284 │   path = global_cache_dir(cache_subdir)                                                  │
│ ❱ 285 │   model = model_class.from_pretrained(                                                   │
│   286 │   │   model_name,                                                                        │
│   287 │   │   cache_dir=path,                                                                    │
│   288 │   │   resume_download=True,                                                              │
│                                                                                                  │
│ /nvme/dave/git/InvokeAI/venv/lib/python3.10/site-packages/transformers/modeling_utils.py:2560 in │
│ from_pretrained                                                                                  │
│                                                                                                  │
│   2557 │   │   if from_pt:                                                                       │
│   2558 │   │   │   if not is_sharded and state_dict is None:                                     │
│   2559 │   │   │   │   # Time to load the checkpoint                                             │
│ ❱ 2560 │   │   │   │   state_dict = load_state_dict(resolved_archive_file)                       │
│   2561 │   │   │                                                                                 │
│   2562 │   │   │   # set dtype to instantiate the model under:                                   │
│   2563 │   │   │   # 1. If torch_dtype is not None, we use that dtype                            │
│                                                                                                  │
│ /nvme/dave/git/InvokeAI/venv/lib/python3.10/site-packages/transformers/modeling_utils.py:440 in  │
│ load_state_dict                                                                                  │
│                                                                                                  │
│    437 │   │   │   raise NotImplementedError(                                                    │
│    438 │   │   │   │   f"Conversion from a {metadata['format']} safetensors archive to PyTorch   │
│    439 │   │   │   )                                                                             │
│ ❱  440 │   │   return safe_load_file(checkpoint_file)                                            │
│    441 │   try:                                                                                  │
│    442 │   │   return torch.load(checkpoint_file, map_location="cpu")                            │
│    443 │   except Exception as e:                                                                │
│                                                                                                  │
│ /nvme/dave/git/InvokeAI/venv/lib/python3.10/site-packages/safetensors/torch.py:101 in load_file  │
│                                                                                                  │
│    98 │   result = {}                                                                            │
│    99 │   with safe_open(filename, framework="pt", device=device) as f:                          │
│   100 │   │   for k in f.keys():                                                                 │
│ ❱ 101 │   │   │   result[k] = f.get_tensor(k)                                                    │
│   102 │   return result                                                                          │
│   103                                                                                            │
│   104                                                                                            │

**Comment by lstein** [comment]
The actual error message is missing. Could you repost?

I am assuming that you pointed to the existing checkpoint directory by selecting `Select a directory for models to import`. Is this correct?

**Comment by drwootton** [comment]
I tried to run invokeai-configure to get the error message, but can't get it to fail again. I had installed InvokeAI using the Linux 2.3.4.post1 installer and had that working, so I'm not sure I cleared all the state of that install. I did rename the **invokeai** directory in my home directory and that seemed to clear enough state that I could run thru invokeai-configure again.

I did backtrack to find the error message and found the partial text **self.size(-1) must be divisible by 4 to view Byte as Float (different element  sizes)** followed by a string SD2 and a number in the range of 700000, which I think was an odd number. This was after the messages that it was installing the SD2 clip model. Now that step works so I don't know what changed.

I did ask the invokeai-configure script to import existing models and also to keep the existing models.

**Comment by lstein** [comment]
This is a very odd error and I'm glad it seems to have gone away. It may have been a transient network error that created a truncated model file which, when loaded, caused the exception.

However, I did find a problem with the "import from directory" function and have made a fix for it. So your report was very helpful.
