### ISSUE TITLE
[bug]: CUDA out of memory when trying to start textual inversion training

### ISSUE THREAD

**Issue by FilipTrichkov** [invoke-ai/InvokeAI#3212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

4

### What version did you experience this issue on?

2.3.4.post1

### What happened?

I had some previous problems when trying to start textual inversion training - I have yet to make it work on my laptop, but now the current problem I am facing when i try to start it is that it says CUDA is out of memory. I lowered the batch size to 1/50 and I still get the same error. 
Is there a way to get this solved?
My GPU is NVIDIA GeForce RTX 3050 4GB.

### Screenshots

<img width="1274" alt="Screenshot 2023-04-16 133014" src="https://user-images.githubusercontent.com/61379159/232307194-1c57e30b-15ec-41ea-a862-361fd835fe00.png">
<img width="849" alt="Screenshot 2023-04-16 133223" src="https://user-images.githubusercontent.com/61379159/232307200-932e613d-0854-437e-a473-dfd426f18039.png">

**Comment by gogurtenjoyer** [comment]
Please read the documentation for the textual inversion training feature here: https://invoke-ai.github.io/InvokeAI/features/TEXTUAL_INVERSION/

As it states, at least 12 GB VRAM is required, and you've got 4.
