### ISSUE TITLE
[bug]: img2img does not consider base image at all

### ISSUE THREAD

**Issue by VinnyVicious** [invoke-ai/InvokeAI#3213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

2.3.4.post1

### What happened?

Trying to use img2img to remix a 2D texture into a different style, but the tool does not consider the base image at all. It's as if I was using promp2img. 

### Screenshots

![image](https://user-images.githubusercontent.com/184960/232321519-9ac912e1-0e0c-44a4-ae6e-84c8181709d7.png)

**Comment by gogurtenjoyer** [comment]
Could you please show your settings? Note: this is expected behavior if you have strength turned all the way to the right.

**Comment by VinnyVicious** [comment]
Oh, thank you. That was it. Strength controls how much input from left is taken.
