### ISSUE TITLE
[bug]: Using Invoke.bat and starting invoke Ai only brings up "list index out of range" error on the terminal

### ISSUE THREAD

**Issue by i-am-R00k** [invoke-ai/InvokeAI#3223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

4 GB

### What version did you experience this issue on?

2.3.4

### What happened?

I ran InvokeAI using the given bat file and it gave me a list index out of range error and it returns back to the menu

### Screenshots

Here is a screenshot of the cmd terminal

![image](https://user-images.githubusercontent.com/97873402/232783911-42e3f218-c35a-442c-ad7a-4c924abc6263.png)

**Comment by gogurtenjoyer** [comment]
This is caused when you do not have any models installed - the InvokeAI installer has some options to automatically download and install some models from huggingface.co, and it also has an option to supply a directory for your existing models. You can run option 5 from the launcher (and shown in the screenshot above) and do either/both of these things, which should sort your issue out.

**Comment by i-am-R00k** [comment]
Is there a way to import or make invoke ai access models from another folder then? I've already downloaded models that are located in the automatic 1111 webui folder and i don't want to waste space by copying those files again.

**Comment by gogurtenjoyer** [comment]
Yes, that's one of the two options I mentioned above.

**Comment by arshesney** [comment]
I've been facing the same issue on a fresh install:
Windows 10
Python 3.10.9 via anaconda
Nvidia 2070s

as a workaround I let the config download a model then autoimport kicked in
