### ISSUE TITLE
[enhancement]: Reuse seed when outpainting

### ISSUE THREAD

**Issue by Botoni** [invoke-ai/InvokeAI#3226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

When outpainting in the unified canvas, if using a random seed, it would be nice to retrive the last seed used in case one likes the result but want to give it more saples or do a minor promt ajustment.

**Comment by hipsterusername** [comment]
Seeds at different sizes would not extend the underlying noise, so don't think this would address the underlying ask
