### ISSUE TITLE
[bug]: extreme noise artifacts when inpainting

### ISSUE THREAD

**Issue by JaysonPhoenix** [invoke-ai/InvokeAI#3236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

2.3.4.post1

### What happened?

[edit: while initially this issue post was about weird looking faces and details of body features and backgrounds i decided to take that part back until further testing and split it into a seperate issue post if it persists and i can narrow it down more. thats because i found out some of my tests were flawed and a combination of factors possibly could have caused this behaviour.]

on inpainting every inpainted area at least looks dirty if not only consisting of extreme noise/grain. the smaller the inpainted area the more noise, the bigger the area its slowly becoming less noise till when the area reaches a certain size the problem completely disappears. the sampler or steps used doesnt seem to make a differencem its just different and mor or less noise, and the more noisy mask borders stay visible no matter the inpainting strength while the amount of noise visible differs with inpainting stregth i think. seam settings didnt help either, for the tests i kept em at a minimum.

if using inpainting models those problems dont happen, inpainted areas look perfectly fine and even tho most inpainting models cant produce proper txt2img images the broken faces and details dont happen there either. (and no thats not how its supposed to be, several non inpainting models always did a great job on inpainting before the update)

also i get forced to convert to diffusor even when using --no-ckpt_convert and i hope thats only a bug too, but because of this i cant test of its about the diffusor model version or the updated invoke itself.

### Screenshots

thats the original made with the deliberate1.0 (accidently using klms sampler which deliberate seems to bug out with, causing the artifacts on the arms)
![001627 3f541991 2519254454](https://user-images.githubusercontent.com/33604461/233271328-3611006b-7bc7-48bf-a2a2-6381d4712dea.png)
deliberate1.0 pre converted diffusor, small area
![003453 8ddea93b 538744185](https://user-images.githubusercontent.com/33604461/233271549-ac4119bc-4ece-44c5-9580-e3aed642d371.png)
deliberate1.0 medium area
![003452 448c1c39 1512053610](https://user-images.githubusercontent.com/33604461/233271633-eb3f2eea-d746-429d-b09f-d253754a11ec.png)
deliberate1.0 whole belly
![003454 4cab3973 473717345](https://user-images.githubusercontent.com/33604461/233271681-ac88656c-fee5-4db9-afcd-37fe4d172fc0.png)
deliberate inpainting small area
![003456 e9ab5ea4 2665098666](https://user-images.githubusercontent.com/33604461/233271742-5b2a390b-a850-4891-893a-af9f52ecf132.png)
sd1.5 diffusor version (not converted), small area
![003468 0b0cdc29 1653260612](https://user-images.githubusercontent.com/33604461/233272141-8c28922f-83e7-4f2d-bdac-9a9124cfaef1.png)
sd1.5 diffusor medium area
![003471 3aeb87ce 1489053684](https://user-images.githubusercontent.com/33604461/233272267-855022b1-d2da-4316-926d-29129bc413b8.png)
sd1.5 whole belly
![003474 e4d59d91 1027302561](https://user-images.githubusercontent.com/33604461/233272377-809ee691-5d66-4914-8628-b9a6a8105fe8.png)
sd1.5 inpainting diffusor small area
![003478 f6c7f2e5 3099831179](https://user-images.githubusercontent.com/33604461/233272490-b6cbaa39-3959-489d-807f-8e46d9b4cf28.png)

### Additional context

first off, even tho ive always been using --no-ckpt_convert, now i get forced to at least convert models on the fly (same issues if converted manually tho). i hope thats a bug too and i guess thats exactly the reason why im running into the problems now and didnt on the previous version. i never used diffusors format much so i dont know too much about it and cant really remember the exact behaviour and cant tell if with diffusors it would have been the same or if some issues would have been similar even before the update, i only remember i ran in too many issues with it before so after some trying i stopped using it. i would guess probably if i could still use the safetensors and ckpt format it would still work or i could at least tell if its about the update or the diffusor format in general, even tho i would rather want to have everything work on diffursors format as intended now that i got used to that, somebody clear that up please, is the forced convert on the fly and the not anymore working init argument intended?

for the testing i primarely used the models sd1.5 (both the diffusor version provided at invoke installation and the manually converted version), deliberate 1.0 and v1, liberty and lazy+ because all have an inpainting version available except for lazy+ which is one of the models i got some more experience with.
i would guess the problems are related to the forced diffusors convert, and probably since inpainting models still work as intended it would also be something about the yaml configs maybe.
i also successfully converted lazy+ to an inpainting model (using some merging technique described in some reddit post) since it has none available, before converting it to an inpainting model it has the same inpainting issues and after converting to inpainting the issue completely disappears like with all other inpainting models, 

i provided some inpainting pictures. i cut the amount of pics down because they basically all show the same anyway. i made each one pic of inpainting a very small area on the belly which causes heavy noise distortion especially at the borders of the mask, then one pic of a medium area of the lower belly causing visible noise (i think), then one of the whole belly which to me makes it seem like the issue almost would disappear and the more noisy area at the borders of the mask gets less, (but well, maybe thats only my old eyes and the issue still persists on whole belly inpainting and i just dont see it anymore because the whole area looks the same, could be an optical ilusion to my eyes that it disapeared). and then also one with the inpainting version of the models used for the other pictures, im inpainting only the small area from the first picture with it to show it works perfectly fine as intended with no noise at all no matter how big or small the area and no noise at the borders of the mask aswell.  
when trying to reproduce try to use skin texture or fabric objects and prompt the right thing to inpaint so it doesnt try to fill in some other objects, for example do a txt2img for the close up of a belly closeup of a woman with jeans and sportsbra and then keep the prompt during inpainting with medium inpainting strength, skin and especially women worked the best for me while on men some models kept trying to inpainted bodyhair even with negative prompts and when trying with a plain wall and without keeping the seed it often tried to paint different kind of walls so the test gets flawed too much and often only the more noisy borders of the mask stay visible. also try inpainting a whole head or something on different sized areas, like on a body shot compared to a portrait, it seemed to make the problem disappear as soon as the face was big enough pixelwise and not cause the noise on the face and/or around it anymore.

### Contact Details

this thread

**Comment by hipsterusername** [comment]
@JaysonPhoenix Please don't post NSFW in this Github repo.

**Comment by JaysonPhoenix** [comment]
yeah well... you kinda went a bit too delete happy there imo, i dont think clothed adults wearing a hoody and jeans in a park or even jeans and a sports top with a naked belly is considered nsfw, especially for the inpainting issue pics i posted where it was only a belly closeup of some random 30 year old wearing a normal jeans and i didnt even include the clothed breast that still wouldnt be nsfw, its a belly to get some skin texture to show the issue in different shaded textures my god ^^ i kinda can understand deleting 4 of the like 20 pics yoou deleted because i already figured somebody wouldnt like that no matter how soft nsfw it might be but for the rest, what time and age am i? ^^ guess if it would have been shirtless men from some adds it would have been ok? you never know. but yeah, i already said sry in advance in case it would cause problems... maybe i get the time to do all that again with some different pictures, even tho some cant be shown in any other way

**Comment by hipsterusername** [comment]
I don't have time to parse through the Github edit panel and images you posted to figure out which corresponded to each. 

You're welcome to repost anything that wasnt NSFW/nudity.

**Comment by JaysonPhoenix** [comment]
alright, then i'll just repost what i think is ok or i'll censor since you didnt specify which ones were wrong exactly

**Comment by JaysonPhoenix** [comment]
id also like ot add that when deleting a part of the inpainting image (without using a mask on the edges of the deleted part) the deleted area gets a white edge line. and for that issue using an inpainting model wont help as a workaround like for the other described issue. if seam correction is set to minimal (like 1pixel, 0 blur, 20 strength, 10 steps) the border is like a fine white or black line, if set to medium its a thicker blurred seam. that white line wasnt there in versions before this and the seam was less (probably because its inpainting from the generated edge). if i set a mask ontop of the edges of a deleted area and then invoke no edge line is visible on the end result if img2img strength is set to like 5 or above (below that the edge is still slightly visible), never had to mask the edges of a deleted area before this version tho. really annoying when working on small detailed areas where i wouldnt want to inpaint more then the already deleted area to solve the edge issue but cause other details to change aswell.
