### ISSUE TITLE
[bug]: AttributeError: module 'diffusers.models.attention' has no attribute 'CrossAttention'

### ISSUE THREAD

**Issue by cinemapara** [invoke-ai/InvokeAI#3239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### What version did you experience this issue on?

v2.3.4.post1

### What happened?

On macbook m2 ventura i still get **AttributeError: module 'diffusers.models.attention' has no attribute 'CrossAttention'**
I tried diffusers-0.15.0 and diffusers-0.14.0
I was using https://github.com/invoke-ai/InvokeAI/releases/tag/v2.3.4.post1

### Screenshots

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/59502516/233333974-301e82f5-d032-4c62-82b4-14a49f0b38ca.png">
<img width="671" alt="image" src="https://user-images.githubusercontent.com/59502516/233334005-c202b31a-3b91-4d4b-9b30-74134647435d.png">

**Comment by lstein** [comment]
Are you sure you didn't install `main` at some point, or play around with a 2.3 pull request that updated to diffusers 0.15? This is exactly what you see when running new code with the old diffusers 0.14 library.

Please try entering the developer's console and running the following:
```
pip install diffusers==0.14
pip install invokeai --upgrade
```
