### ISSUE TITLE
torch.cuda.OutofMemoryError

### ISSUE THREAD

**Issue by senorchipps** [invoke-ai/InvokeAI#3240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

2.3.4

### What happened?

Trying to run any model results in this error code. Ever since I updated to 2.3.4 I haven't been able to get it working.

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 6.00 GiB total capacity; 5.25 GiB already allocated; 0 bytes free; 5.32 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.

I'm really underexperienced with coded/python/all of this lol so I have zero clue what to do.

**Comment by Jasmin-777** [comment]
Hello, I have had the same problem when upgrading to 2.3.5. After much trial and error, I selected point 6 in the script and added the following to the settings: FREE GPU MEMORY AFTER EACH GENERATION. I also reduced the cache for models from 2 to 1. Now it runs again. I hope I can help you with this. Kind regards Jasmin

**Comment by Jasmin-777** [comment]
I have probably rejoiced too early. After it generated a picture including outpainting, it didn't work again. Error message: torch.cuda.OutOfMemoryError: CUDA is out of memory. Attempted to allocate 2.00 MiB (GPU 0; 4.00 GiB total capacity; 3.45 GiB already allocated; 0 bytes free; 3.51 GiB total reserved by PyTorch) If reserved memory >> allocated, try setting max_split_size_mb to avoid fragmentation.  See the documentation for memory management and PYTORCH_CUDA_ALLOC_CONF.  🙁
