### ISSUE TITLE
[bug]: LoRa is ignored when inpainting

### ISSUE THREAD

**Issue by rookMM** [invoke-ai/InvokeAI#3255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

16GB

### What version did you experience this issue on?

2.3.4rc1

### What happened?

When generating an image using Text to Image or Image to Image, any LoRas in the prompt are correctly applied. However, when inpainting an image, all LoRas are seemingly ignored (this issue does not exist with textual inversion embeddings).

### Screenshots

This is the base image:
![004682 490f4bd9 1137286035](https://user-images.githubusercontent.com/58738096/233863038-09b9d510-5396-4168-93cd-c03393d42a06.png)
Prompt: "portrait of a woman in a field"
Model: AnyLoRa

Using Image to Image, this is the result using the same seed and settings, but with the Studio Ghibli style LoRa added to the prompt:
![019931 f6fadd6d 1137286035](https://user-images.githubusercontent.com/58738096/233863040-2e816569-0b3e-4a7f-82bf-087aa2e6eb5e.png)
Prompt: "portrait of a woman in a field, withLora(studioGhibliStyle_offset)

For this result, I used all of the same settings as the second image (including the prompt with the LoRa), but instead of using Image to Image I painted a mask over the whole image in the Unified Canvas, which treats the generation as an inpainting:
![019932 533edc7e 1137286035](https://user-images.githubusercontent.com/58738096/233863031-cdf04d13-dfa1-4f9b-8b45-d5931d833031.png)
Prompt: "portrait of a woman in a field, withLora(studioGhibliStyle_offset)

**Comment by lstein** [comment]
I'm pretty sure this bug is fixed in the upcoming 2.3.5 release.
