### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by alexbespik** [invoke-ai/InvokeAI#3262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

4gb

### What version did you experience this issue on?

i dont know may be last

### What happened?

I tried to install invoke but installation is hung up
  Using cached psutil-5.9.4-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (280 kB)
Collecting basicsr>=1.4.2
  Using cached basicsr-1.4.2.tar.gz (172 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... \

### Screenshots

![image](https://user-images.githubusercontent.com/122635924/234021624-2a42e044-f545-4271-b551-2031558c239c.png)

### Contact Details

stotikandrej@gmail.com

**Comment by lcuis** [comment]
Got the exact same issue on my Ubuntu 22.04.1 on Intel i5 64 bits with a CUDA graphics card nvidia 2080 (12GB GPU RAM) and with 16GB RAM.
I have Python 3.10.6.
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu).
My internet connection is not very stable and I had to restart the installation approximately 10 times before finally reaching this issue.

I am running the following command as a non-root user:
```bash
pip3 install "InvokeAI[xformers]" --use-pep517 --extra-index-url https://download.pytorch.org/whl/cu117
```

And I end up with the following last lines right after the mention of `basicsr`:
```bash
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... -
```

Note: the last character doesn't rotate. It remains in this position ( or another one) for more than 30 minutes.

I have then to interrupt the installation with `ctrl-c` and InvokeAI is not installed.

Retrying 10 times doesn't solve anything.

It looks like a recurring issue:
https://github.com/invoke-ai/InvokeAI/issues/3113
https://www.reddit.com/r/invokeai/comments/12ycwnl/invokeai_installation_stuck/
https://www.reddit.com/r/StableDiffusion/comments/12zcvjl/invokeai_stable_diffusion_toolkit_installation/

I didn't find much content regarding this on discord installation issues dedicated thread.

I got this exact same issue with this installer:
https://github.com/invoke-ai/InvokeAI/releases/download/v2.3.5/InvokeAI-installer-v2.3.5.zip

I tried this command:
```bash
pip3 install basicsr --no-cache-dir
```
and got stuck in a very similar way:
```
Collecting basicsr
  Downloading basicsr-1.4.2.tar.gz (172 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.5/172.5 KB 537.9 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... -
```
This makes me think that this `basicsr` package is trying to do something for the installation in a non-reliable way causing this stuck situation.

I wonder whether this is related?
https://github.com/XPixelGroup/BasicSR/issues/575

I don't know where the mentioned files are located. I will try to find a solution and post here again if I find any additional information.

**Comment by lcuis** [comment]
I applied the solution mentioned here:
https://github.com/XPixelGroup/BasicSR/issues/575

This seems to have solved the stuck situation.

The install command finally gave the following result:
```
Successfully installed InvokeAI-2.3.5 accelerate-0.18.0 aiohttp-3.8.4 aiosignal-1.3.1 albumentations-1.3.0 altair-4.2.2 antlr4-python3-runtime-4.9.3 anyio-3.6.2 appdirs-1.4.4 async-timeout-4.0.2 attrs-23.1.0 bidict-0.22.1 blinker-1.6.2 boltons-23.0.0 clean-fid-0.1.35 click-8.1.3 clip-anytorch-2.5.2 compel-1.1.3 contourpy-1.0.7 cycler-0.11.0 datasets-2.12.0 decorator-5.1.1 diffusers-0.15.1 dill-0.3.6 dnspython-2.2.1 docker-pycreds-0.4.0 einops-0.6.1 entrypoints-0.4 eventlet-0.33.3 facexlib-0.3.0 fastapi-0.85.0 fastapi-events-0.6.0 fastapi-socketio-0.0.9 filterpy-1.4.5 flask-2.1.3 flask-cors-3.0.10 flask-socketio-5.3.0 flaskwebgui-1.0.3 fonttools-4.39.3 frozenlist-1.3.3 fsspec-2023.4.0 ftfy-6.1.1 getpass-asterisk-1.0.1 gfpgan-1.3.8 gitdb-4.0.10 gitpython-3.1.31 greenlet-2.0.2 huggingface-hub-0.14.1 imageio-ffmpeg-0.4.8 importlib-metadata-6.6.0 itsdangerous-2.1.2 jedi-0.18.2 joblib-1.2.0 jsonmerge-1.9.0 jsonschema-4.17.3 k-diffusion-0.0.14 kiwisolver-1.4.4 kornia-0.6.12 llvmlite-0.40.0 markdown-it-py-2.2.0 matplotlib-3.7.1 mdurl-0.1.2 multidict-6.0.4 multiprocess-0.70.14 mypy-extensions-1.0.0 npyscreen-4.10.5 numba-0.57.0 numpy-1.23.5 omegaconf-2.3.0 opencv-python-headless-4.7.0.72 pandas-2.0.1 parso-0.8.3 pathtools-0.1.2 peft-0.3.0 picklescan-0.0.9 prompt-toolkit-3.0.38 protobuf-3.20.3 psutil-5.9.4 pudb-2022.1.3 pyDeprecate-0.3.2 pyarrow-12.0.0 pydantic-1.10.7 pydeck-0.8.1b0 pygments-2.15.1 pympler-1.0.1 pyparsing-3.0.9 pypatchmatch-1.0.0 pyre-extensions-0.0.23 pyreadline3-3.4.1 pyrsistent-0.19.3 python-dateutil-2.8.2 python-engineio-4.4.1 python-multipart-0.0.5 python-socketio-5.8.0 pytorch-lightning-1.7.7 pytz-2023.3 pytz-deprecation-shim-0.1.0.post0 qudida-0.0.4 realesrgan-0.3.0 regex-2023.5.5 requests-2.28.2 resize-right-0.0.2 responses-0.18.0 rich-13.3.5 safetensors-0.3.1 scikit-learn-1.2.2 send2trash-1.8.2 sentry-sdk-1.21.1 setproctitle-1.3.2 smmap-5.0.0 sniffio-1.3.0 starlette-0.20.4 streamlit-1.22.0 taming-transformers-rom1504-0.0.6 tenacity-8.2.2 tensorboard-2.12.3 test-tube-0.7.5 threadpoolctl-3.1.0 tokenizers-0.13.3 toml-0.10.2 toolz-0.12.0 torch-1.13.1+cu117 torch-fidelity-0.3.0 torchdiffeq-0.2.3 torchmetrics-0.11.4 torchsde-0.2.5 torchvision-0.14.1+cu117 tornado-6.3.1 trampoline-0.1.2 transformers-4.28.1 typing-inspect-0.8.0 tzdata-2023.3 tzlocal-4.3 urwid-2.1.2 urwid-readline-0.13 validators-0.20.0 wandb-0.15.1 watchdog-3.0.0 wcwidth-0.2.6 xformers-0.0.16 xxhash-3.2.0 yarl-1.9.2 zipp-3.15.0
```

I was then able to move on to the configuration script.

**Comment by lcuis** [comment]
Just to clarify, I had to follow the git clone installation instructions of BasicSR:
https://github.com/XPixelGroup/BasicSR/blob/master/docs/INSTALL.md#install-from-a-local-clone

Right after the clone command, I adapted the `BasicSR/basicsr/utils/download_util.py` file as mentioned here:
https://github.com/XPixelGroup/BasicSR/issues/575#issue-1406022440

Then, I proceeded with the rest of the installations (BasicSR first and InvokeAI then).

I got InvokeAI to work with the following outcome examples:

![000026 2301882707](https://user-images.githubusercontent.com/32125299/236250933-5d231df8-abcb-4503-b7d2-162f0af2950b.png)

![000035 3496370467](https://user-images.githubusercontent.com/32125299/236251793-825553b8-94d4-41e7-b74c-25fb9bbd3415.png)
