### ISSUE TITLE
[bug]: invokeai_configure.py incorrectly sets the /home/$USER directory as the root

### ISSUE THREAD

**Issue by originates** [invoke-ai/InvokeAI#3264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

2.3.4.post1

### InvokeAI/invokeai/backend/config/invokeai_configure.py

On Ubuntu this appears to set the user home directory as the root directory of the project. 
Because of this, a new directory will be created:
> /home/$USER/invokeai

The following directories/files are then created here instead of the invokeai directory of the project.
- configs
- embeddings
- models
- text-inversion-output
- etc

**Comment by lstein** [comment]
Sorry, is it literally creating a `$USER` directory with the dollar sign?  

The intended behavior is to create a runtime `invokeai` directory in the user's home directory, as determined by `~/invokeai`. It is not supposed to create an invokeai directory in the sourcecode distribution.

**Comment by originates** [comment]
> is it literally creating a $USER directory with the dollar sign?

Thank you for your reply. No, it is not creating a $USER directory. I used that as a variable for the username. Sorry for the confusion.

> The intended behavior is to create a runtime invokeai directory in the user's home directory, as determined by ~/invokeai. 

I appreciate your clarification. I was not aware of this design decision. I thought it was an error because I expected the invokeai directory to be located within the project folder, not in the home folder.

This issue is resolved.
