### ISSUE TITLE
[bug]: Missing features on the Web UI

### ISSUE THREAD

**Issue by fnw** [invoke-ai/InvokeAI#3276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

Commit a3c5a664e597e694c71e654ac0a9689639e2952b on the main branch

### What happened?

(Running under Docker, latest commit on ```main``` as of the creation of this issue)

When using the Web UI, certain features described on the documentation appear to be missing.

On the Unified Canvas, under the "Infill and Scaling" tab, there is no slider for the "Inpaint Replace" setting.
On the text2img tool, there are no options for LoRA or LyCORIS.

I've tried:

- pulling the latest commit multiple times
- adding a line purging the pip cache to the Dockerfile
- forcing Docker to build the image with ```--no_cache``` by adding it to the build command in ```build.sh```

To no avail.

Furthermore, greping for ```inpaint_replace``` shows multiple .ts files with the string, indicating that maybe the code is present but somehow the build step for the .ts files is not executing correctly (?). This is unfortunately just a guess, as I am not very familiar with TypeScript, and could not progress any further with debugging.

**Comment by psychedelicious** [comment]
Hi, please see the announcement here: https://github.com/invoke-ai/InvokeAI/discussions/3246

In short, check out the tag `pre-nodes` to get a working UI.

I'll update the readme on `main` with an alert about this.

**Comment by fnw** [comment]
Thanks for the response :)
