### ISSUE TITLE
[bug]: single nodes instance generates multiple images at the same time

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#3289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

main

### What happened?

@Kyle0654 

It is possible for a single nodes instance to receive and process multiple nodes at once - so like, I can hit the invoke route any number of times and it tries to generate all of them at once. You get multiple progress bars and everything. Occasionally you get torch errors when this happens.

I think this should not be possible...

**Comment by ebr** [comment]
I believe the linked PR should fix this. I started out on the path to convert Invoker to use asyncio instead of threading, but that seems to be a much bigger job than i can delve into right now

**Comment by Kyle0654** [comment]
Weird.... I thought only one processor should be created, which should only create one thread. It might be worthwhile to look and see if multiples of things are being created.
