### ISSUE TITLE
[enhancement]: improved model selection dropdown menu

### ISSUE THREAD

**Issue by JaysonPhoenix** [invoke-ai/InvokeAI#3314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

this thread

### What should this feature add?

in the dropdown menu for selecting models it would be handy if models were sorted as loaded/cached and ckpt/safetensor or diffusors aswell as sd1.5 and 2.0/2.1 in some way so i dont have to open the model manager anyway. could have a seperator for diffusors like in the model manager so diffusors are at the bottom and could have colored tags for 2.0 in front of the model and the models name colored green for loaded and yellow for cached for example, also showing the full name if mouse hovered over would be nice because some names are too long for the small dropdown. 
just some ways to not accidently click on the wrong model and then wait forever to have it loaded and swapped back or even multiple times to get the right models back in cache (writing this while im waiting.. ^^). even tho for those issues it would be even nicer to have an optional confirmation dialog when switching models and getting asked which model i want to clear from cache in case switching would clear one of em instead of just the oldest one. ;)

**Comment by hipsterusername** [comment]
Improved in 3.0
