### ISSUE TITLE
[enhancement]: nodes queuing

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#3315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

The nodes server now does not generate multiple images at once (original issue #3289, fixed in #3312) but it still does let you create multiple sessions. The sessions are invoked synchronously, that is, the invoke of session 1 must complete before session 2 invoke is picked up. 

The CLI accidentally handles this by virtue of its UI being synchronous, but with the API it is possible to queue arbitrary numbers of sessions. 

This is why #3289 was about "arbitrary numbers" of invocations, and not just session counts limited to the number of threads. So this is a related but different issue.

The UI has no capabilities to manage and track multiple ongoing session invocations. Adding this will be a major effort. Until that is done, we probably want to prevent queuing multiple sessions. 

Also, I am concerned that in the commercial product, it would be possible to slam the create and invoke session routes and queue up indefinite generation, so I don't think a `async` or `use_queue` etc query parameter is good enough. Suggest that for now, we add an `async` flag to the app and reject create/invoke session routes if `async == False`.

**Comment by ebr** [comment]
Definitely valid concerns about abuse of the API (infinite sessions of arbitrary size), but we can address that separately.

I agree that limiting parallelism in session processing would be useful, though IMO we should still *accept* sessions into the queue, even if we process them synchronously. But the mechanisms for controlling this for single-user and multi-user scenarios would be different. Need to think about how to best address that. Perhaps the `InvocationProcessor` should send the remaining queue length back to the client with each "invocation complete" event, or the `InvocationQueue` should emit a separate "queue length" message anytime an item is popped off.

To improve feedback to the user, let's say if we did add some parallelism-limiting mechanism, could we bring back some equivalent of the previous `Processing (1/5)` status message? we've converted this indicator to a dot - could we add multiple dots to show the remaining queue length for the user? (just spitballing - UX folks might laugh me out of the room for this).

**Comment by psychedelicious** [comment]
I'm very pleased to say that this is in progress in https://github.com/invoke-ai/InvokeAI/pull/3995!

We have a few existing requests, going waaaaayyy back to https://github.com/invoke-ai/InvokeAI/issues/908. I'm closing this as a duplicate to keep things tidy.
