### ISSUE TITLE
[bug]: (nodes) two outputs connected to a single input should not be allowed

### ISSUE THREAD

**Issue by ebr** [invoke-ai/InvokeAI#3332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

main

### What happened?

This:

![image](https://user-images.githubusercontent.com/2433541/235934823-77a139ca-3228-49d6-9e0e-5926e7b13d6d.png)

Results in this:

![image](https://user-images.githubusercontent.com/2433541/235934934-a7cd83cd-7948-45b5-916c-0cf5d34ffa65.png)

Perhaps there might be future use cases where this could be possible (collecting outputs into a single input), but maybe even in that case there should be a "collector" node for that. Right now I think we should 1) disallow multiple connections to the same input in the UI, and 2) even if such a payload was sent to the API directly, we should instead of raising return a 400-type request, maybe a 422.

**Comment by psychedelicious** [comment]
This is actually already implemented, but to facilitate testing I've disabled the connection validation. There's an early return true in `useIsValidConnection` preventing the actual validation from occurring.

**Comment by ebr** [comment]
Awesome - thank you. We can close the issue then, or leave it open as a reminder to turn it back on :)
