### ISSUE TITLE
[enhancement]: Tag NSFW status in the output image

### ISSUE THREAD

**Issue by IanCassTwo** [invoke-ai/InvokeAI#3333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

The current NSFW check function should be decoupled from the blur function so that we would always run the NSFW checker and  store its output in the image as an additional tag. This would make it easier to detect and blur generated NSFW images downstream by inspecting metadata, e.g. on a personal website or a blog.

### Alternatives

Alternative would be to re-run some other (third party) NSFW check later at some later stage before publishing.

**Comment by hipsterusername** [comment]
The NSFW check is, unfortunately, not the highest quality or most effective. Given the overhead of it in the process, I would be fearful of it being noise (most people turn off the NSFW checker regardless of their intent)

If there were a better NSFW check, agree that it could be enabled to tag/monitor and handle that accordingly at a later step in the workflow.
