### ISSUE TITLE
[bug]: LoRa not taking effect?

### ISSUE THREAD

**Issue by rtgoodwin** [invoke-ai/InvokeAI#3342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What version did you experience this issue on?

2.3.5rc1

### What happened?

- Using the web interface
- adding a LoRA trained from Kohya_SS (default LoRA) type (located in Invoke's LoRAs folder)
- the "with" clause is added
- w/ or w/o adding the activation token ("rgd" in this case), the LoRA seems to have no effect

The same LoRA w/ "additional networks" plugin in Automatic1111 works wonderfully. (You will have to trust that it resembles the training subject, albeit somewhat more athletic and hero-like :) i.e. it's a real person not a cartoon)

- the link in the 2.3.5 release notes to the "Full LoRA instructions" leads to a 404, and all of the docs seem to be out of date, so perhaps I'm missing a fundamental step?
- If this is due to a tweak needed in the generation process, is it possible to perhaps detect that and warn the user?

### Screenshots

- Screen1 is invoke
- Screen2 is Automatic
- both using same LoRA file
- 
<img width="1016" alt="InvokeAI2023-05-04_093558AM@2x" src="https://user-images.githubusercontent.com/1183842/236241684-fc368b7f-9174-49de-9337-f98ec17b0abd.png">
![Google Chrome2023-05-04_093902AM](https://user-images.githubusercontent.com/1183842/236241722-68e400bc-6295-4a6e-853e-8af601de30b5.png)

![Google Chrome2023-05-04_093902AM](https://user-images.githubusercontent.com/1183842/236242400-2c63be31-a26f-40a3-bf2e-d222a1e57f62.png)

### Contact Details

Discord @Serenity_Nowver

**Comment by gogurtenjoyer** [comment]
I'd recommend updating to the 2.3.5 release version. There were 2 release candidates released after the one you're on, dealing with LoRA support, in addition to the final version - your problem may be fixed there.

**Comment by rtgoodwin** [comment]
1. Shame on me, I swear I looked and it was still rc1 for current
2. Same results after update. Tried `token`, `(token)`, `(token)++`
![InvokeAI2023-05-04_102307AM](https://user-images.githubusercontent.com/1183842/236254239-e9276786-38b1-43b5-8539-65370a492225.png)

**Comment by rtgoodwin** [comment]
Note: patchmatch never properly installs for me, but I don't think it's required. Just wanted to call it out.

**Comment by NeoLoger** [comment]
Same here, I think its jut taking the "withLora" as part of the prompt and not actually using the lora.
Maybe it will be better to separate it? make it a different tab similar to the negative prompts?

Not being able to use lora is the only think holding me back of using InvokeAI

**Comment by lstein** [comment]
There is a bug in the Lora parser when the Lora file name contains hyphens. Replace the hyphens with underscores and it will work.

**Comment by damian0815** [comment]
compel 1.1.4 now allows lora names with `-` in them - @rtgoodwin if you do `pip install -U compel` it should be fixed

**Comment by rtgoodwin** [comment]
Woo! Will give it a go. Need to train some more anyway, can't seem to find the best reliable trainer. (or the operator is unreliable 😀 )

**Comment by rtgoodwin** [comment]
I did confirm that the LoRA (LoRAs? LoRii?) are being used. Great catch on the name, who would have thought? 

The weighting seems a bit different than Automatic+the additional Networks plugin, but there are so many variables it's hard to say. Just excited to use my favorite UI for this again! :) 

Thanks!
