### ISSUE TITLE
[bug]: paste image in the canvas doesn't work

### ISSUE THREAD

**Issue by laurentopia** [invoke-ai/InvokeAI#3375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

2.3.5

### What happened?

normally when you paste an image on a canvas it pastes the image
the unified canvas of invokeai doesn't do anything

**Comment by trmusson** [comment]
I'm getting something similar - maybe related?

The first attempt to send an image to the Unified Canvas often fails for me. The canvas grid appears, but invoke doesn't load the image. When I try a 2nd time, the image then appears.

By "send an image to the UC", I mean via InvokeAI's web UI... both the "share" icon (in "Text to Image" and "Image to Image" mode), and the context menu in the thumbnail gallery.

I'm using 2.3.5.post2
