### ISSUE TITLE
[bug]:  nsfw filter  bugged

### ISSUE THREAD

**Issue by lolsea90** [invoke-ai/InvokeAI#3384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

2.5.2

### What happened?

invokeai  nsfw filter  is bugged, it filters a fine image,  so many times happened

### Additional context

happens any time

### Contact Details

thekingoffifa24@gmail.com

**Comment by hipsterusername** [comment]
This is not a bug, but simply the imperfection of the AI NSFW filter. You can turn it off if you feel it is ineffective for your needs, thoughz

**Comment by lolsea90** [comment]
> This is not a bug, but simply the imperfection of the AI NSFW filter. You can turn it off if you feel it is ineffective for your needs, thoughz

I see,  thx
