### ISSUE TITLE
[enhancement]: allow dynamic model configuration

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#3391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

(It's possible this is already possible w/ the rewrite but I just want to record this before I forget)

We have the seamless tiling feature which is currently a parameter on the inference nodes (eg TextToLatents, LatentsToLatents), but this is actually a model configuration thing. It would be nice if we can somehow configure the loaded model without needing to manually handle this within the node. The result is cleaner inference node code.

I think there's a puzzle to solve - doing this outside an inference node in a distributed system is tricky. We cannot configure the model outside the node.

My idea is to provide a model configuration kinda object to inference nodes - like a model plugin node - that the model loader receives and uses when it loads the model. This way we can keep this model-specific logic in the right place.

This is all just to the best of my understanding, may be some misunderstandings inherent in the request.

**Comment by lstein** [comment]
Wouldn't be hard to do this on a single node. In a distributed environment you'd need to propagate a message throughout the whole system. Is there a framework for doing this already? Nodes still seem pretty magic to me.

**Comment by psychedelicious** [comment]
My idea is to provide an optional, serializable configuration object along with the model identifier. This gets passed around between nodes, and when we load a model from memory, the config is applied. 

So in the case of seamless, it would apply the convolution matrix and padding (or whatever magic seamless does). 

The model manager would need to accept this config object and know what to do with it

**Comment by psychedelicious** [comment]
Well you'd just provide this serializable config to a model node. The model node does not actually load the model, it only allows the user to select it. 

I think it's the unet that is padded for seamless tiling? So a unet node identifies the unet and provides its config. 

Then the node that actually does the inference gets the unet model identifier and small config object, and when the model is loaded inside that node, it applies the config if it exists. 

The config would need to be wiped after the node finishes (ie when the model context is exited)
