### ISSUE TITLE
[bug]: expanded graphs may create invalid nodes

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#3412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

main

### What happened?

It's possible to soft-crash the engine by providing a graph that expands into an invalid graph. Two issues here:

1. When a graph is expanded, it is not validated. If it expands to an invalid graph, the invalid graph is stored to the DB, then deserialized during invocation causing pydantic to fail. 

2. The exceptions raised in eg `__process()` in `processory.py`, inside the `while` loop at ~L38, are not caught properly. The situation in `1` above thus breaks the execution engine; the API is responsive but no further generations work.

This should be a pretty rare case, but there's a problem with how the UI does iterations and explicit seeds. It's possible to provide an explicit seed equal to (or close enough to) the max seed value, then the seed is incremented by one during graph expansion, until it is greater than the max allowed value. That's how I found this edge case.

Feels like something that is gonna be basically impossible to fully safeguard against in the UI.

**Comment by psychedelicious** [comment]
@hipsterusername pls reopen

**Comment by psychedelicious** [comment]
I'm unsure if this is fully solved, I recall running into an issue where I soft-locked the processor recently, will try to repro

**Comment by Omarsmsm** [comment]
any luck?

**Comment by psychedelicious** [comment]
@Omarsmsm Is this an issue for you? If so please give some context.

If not I'll close this as we've improved this from a few angles
