### ISSUE TITLE
Server error: unsupported prompt type: Conjunction

### ISSUE THREAD

**Issue by AmericanPugX** [invoke-ai/InvokeAI#3415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

8gb

### What version did you experience this issue on?

3.0.0+a0

### What happened?

While testing limits of my GPU (lol) I tried to do a 1600x1600px prompt with a 4x upscale. 

While almost complete, like 80% of the way there, it finally crashed my whole docker. Upon reset everything seems fine, but if I try to do a prompt now I get

`2023-05-14T19:09:25-0300:
Loaded 50 images
2023-05-14T19:09:25-0300:
Loaded 0 images
2023-05-14T19:09:30-0300:
Image generation requested: {"prompt":"test [test]","iterations":1,"steps":25,"cfg_scale":15,"threshold":0,"perlin":0,"height":1280,"width":768,"sampler_name":"k_dpmpp_2","seed":2541855268,"progress_images":false,"progress_latents":true,"save_intermediates":5,"generation_mode":"txt2img","init_mask":"","hires_fix":false,"seamless":false,"variation_amount":0}
2023-05-14T19:09:30-0300:
Server error: unsupported prompt type: Conjunction`

I've tried resetting my server, docker, switching models, etc.

I am using InvokeAI through my unraid server.

### Screenshots

<img width="1512" alt="Screen Shot 2023-05-15 at 1 12 01 PM" src="https://github.com/invoke-ai/InvokeAI/assets/133684900/98e95ce0-1234-4efb-9a7d-3fff03fb53b2">

### Additional context
<img width="1512" alt="Screen Shot 2023-05-15 at 1 12 43 PM" src="https://github.com/invoke-ai/InvokeAI/assets/133684900/993bde03-0384-4aca-a5a6-5fafb5bfbf1a">

### Contact Details

klaushouse@gmail.com

**Comment by ebr** [comment]
A fix for this was merged today - please try to update your installation and respond here if still experiencing the issue.

**Comment by AmericanPugX** [comment]
> A fix for this was merged today - please try to update your installation and respond here if still experiencing the issue.

It seems like yes, I am back and able to prompt - but now it seems to have broken something in the actual process wherein now across all models it seems to butcher the images at the final step? Goes from looking fairly normal to warped ugly faces in final 2-3 steps?

Should I make a new issue?
![faces](https://github.com/invoke-ai/InvokeAI/assets/133684900/7c21c7ce-1e8a-4df2-820f-fb6ecb5e1036)

**Comment by psychedelicious** [comment]
@AmericanPugX Please make a new issue. 

FWIW I get this all the time but keep forgetting to report it. It seems to happen with faces - the rest of the image is typically just fine. It also happens with non-human faces eg I was making sweet robot tigers and their faces get messed up too. The `lms` sampler appears to be the most susceptible, and it happens just as often at high step counts as low.
