### ISSUE TITLE
[enhancement]: Logging Info

### ISSUE THREAD

**Issue by TrickBit** [invoke-ai/InvokeAI#3423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

ezgoen@gmail.com

### What should this feature add?

model info for reproducing a generation
For example:
[Generated] "/mnt/DEV/invokeai/outputs/000159.06195018.3480996169.png": "watercolor painting of two squirrels fighting over a post-it note [ more tan two arms, more than 2 legs, more than one tail]" -s 20 -S 3480996169 -W 512 -H 704 -C 9 -A k_euler  -model stable-diffusion-1.5

I generated this log line by adding 3 lines to "invoke_ai_web_server.py
However, I believe the ability to use or switch to the model in web ui would also be beneficial.
someting along the lines of "Copy Model", where "Copy All" might prompt the user if the ui should include changing the model to the one used in the source generation.

Hope that's clear enough?

### Alternatives

If the ui uses the log file to populate the prompt, and other setting , this would be the place to add the model

### Aditional Content

```
in invoke_ai_web server.py:

in  class InvokeAIWebServer: 
after  self.ALLOWED_EXTENSIONS = {"png", "jpg", "jpeg"} 
added  self.CurrentModel="Not Set: Keep hacking"
========================
in def handle_set_model(model_name: str):
after socketio.emit(
                        "modelChanged",
                        {"model_name": model_name, "model_list": model_list},
                    )
added self.CurrentModel = model_name
========================
in def get_system_config(self):
after or model_name, model_dict in model_list.items():
            if model_dict["status"] == "active":
                active_model_name = model_name
added self.CurrentModel = model_name
========================
in def write_log_message(self, message):
after try:
added modelinfo = f" -model {self.CurrentModel}"
changed message = f"{message}\n"
to  message = f"{message} {modelinfo}\n"

thats it!
This is probably not as elegant as it could be if I was more familiar with 
the code but its works for logging anyway, which is helpful to me at least.
```

**Comment by psychedelicious** [comment]
Hi, we won't be implementing this in the v2.3 - but we have this kind of functionality supported in v3. You can test it out in the `main` branch, but it's in alpha at the moment. More details here https://github.com/invoke-ai/InvokeAI/discussions/3246

**Comment by hipsterusername** [comment]
3.0
