### ISSUE TITLE
[enhancement]: Set Cache-Control headers on generated images in WebUI

### ISSUE THREAD

**Issue by hulknsmash** [invoke-ai/InvokeAI#3426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I'm using InvokeAI on a remote host with >200ms latency. Since the web ui doesn't set Cache-Control header switching images is very slow even though the image I'm switching to has already been loaded before, since the browser reaches out for a 304 first before switching.

Since each image can't be modified after generation, it should be ok to specify a reasonable max-age.

**Comment by psychedelicious** [comment]
Hi, I think you've raised this regarding the 2.3 version of the app. We've been working on the 3.0 release for a few months now. I've added `max-age` to 3.0 in #3711. Thanks for the suggestion.
