### ISSUE TITLE
[bug]: Run too long

### ISSUE THREAD

**Issue by VeyDlin** [invoke-ai/InvokeAI#3431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

80GB

### What version did you experience this issue on?

2.3.5

### What happened?

AMD EPYC™ 28 CPU
120GB RAM
 NVIDIA® Ampere® A100 80GB VRAM
 Fast 500GB SSD
 
 It runs for 5-10 minutes
 What is the problem? On my weaker laptop it takes about a minute

**Comment by ebr** [comment]
most likely it's using CPU instead of GPU. Verify that your GPU drivers are installed and that you have correctly chosen the NVIDIA GPU option during installation.
