### ISSUE TITLE
[bug]: Version 2.3.5.post1 Wrong Xformer version, switches to CPU

### ISSUE THREAD

**Issue by Void2258** [invoke-ai/InvokeAI#3434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6gb

### What version did you experience this issue on?

2.3.5.post1

### What happened?

After updating (option 9-1), torch updated  to 2.0.1 but Xformers mismatched. System switches to CPU without asking or being set in init.

### Screenshots
![image](https://github.com/invoke-ai/InvokeAI/assets/6126362/cce32565-5bb1-4e92-a1ef-595bb2c8193a)

![image](https://github.com/invoke-ai/InvokeAI/assets/6126362/a5887453-a12a-45e2-a115-65eac46a7d06)

**Comment by SauerCarey** [comment]
same issue here.

**Comment by Void2258** [comment]
Full reinstall (delete folder and fresh with installer) fixed it, so it's a problem with the updater script.

**Comment by Raecaug** [comment]
@Void2258 is correct, running the installer script over my current installation corrects this xformers mismatch.

**Comment by fe-c** [comment]
I've solve it by reinstall torch:

`pip uninstall torch && pip install torch --index-url https://download.pytorch.org/whl/cu118`

**Comment by SauerCarey** [comment]
reinstalling torch didn't work for me...  going to have to do full reinstall.

**Comment by lstein** [comment]
Hi, I have confirmed that the updater does not update optional dependencies when running on a remote zip file. I think we have bumped into a limitation in Pip here. I have updated the release notes and provide the following command-line recipe for those of you who have been left with a CPU-based system:

1. Start the launcher script and select option # 8 - Developer's console.
2. Give the following command:
```
pip install invokeai[xformers] --use-pep517 --upgrade
```
This should bring xformers up to date and get you up and running again. Apologies for the inconvenience!

**Comment by lstein** [comment]
> Full reinstall (delete folder and fresh with installer) fixed it, so it's a problem with the updater script.

Folks, you do not have to delete the folder. You can either reinstall on top of it (only the libraries will be updated, no changes to your models or settings), or follow the recipe in the post above.

Also, this is only an issue if you have the old version of `xformers` installed. The updater works properly on the mandatory dependencies, seems not to recognize optional ones.

**Comment by Void2258** [comment]
> I think we have bumped into a limitation in Pip here.

Is this going to be an issue going forward?

**Comment by lstein** [comment]
Here is another recovery recipe, posted in discord by KatanaXS:

1. Open the developer's console or use the command line to activate the invokeai environment.
2. Give the following command:
```
pip install torch==2.0.0+cu118 torchvision==0.15.1+cu118 torchaudio==2.0.1 --index-url https://download.pytorch/ .org/whl/cu118
```
Note that this will not update Xformers. To install Xformers run the following additional command after the previous one completes successfully:
```
pip install xformers==0.0.19
```

**Comment by lstein** [comment]
> > I think we have bumped into a limitation in Pip here.
> 
> Is this going to be an issue going forward?

I will find a way around this. Frankly, the performance of torch 2.0 (on CUDA systems at least) is quite good and Xformers no longer provides as much as a performance boost as it used to.

**Comment by fe-c** [comment]
> Here is another recovery recipe, posted in discord by KatanaXS:
> 
>     1. Open the developer's console or use the command line to activate the invokeai environment.
> 
>     2. Give the following command:
> 
> 
> ```
> pip install torch==2.0.0+cu118 torchvision==0.15.1+cu118 torchaudio==2.0.1 --index-url https://download.pytorch/ .org/whl/cu118
> ```
> 
> Note that this will not update Xformers. To install Xformers run the following additional command after the previous one completes successfully:
> 
> ```
> pip install xformers==0.0.19
> ```

Does InvokeAI uses torchvision and torchaudio?

**Comment by lstein** [comment]
It uses torchvision, but not torchaudio. However it doesn't hurt to install
torchaudio and might be useful later when we provide support for full-frame
surround-sound AI generated movies.

Lincoln

**Comment by hipsterusername** [comment]
> might be useful later when we provide support for full-frame
> surround-sound AI generated movies.

Literally spat my coffee out. Thanks for that

**Comment by fe-c** [comment]
> > Hi, I have confirmed that the updater does not update optional dependencies when running on a remote zip file. I think we have bumped into a limitation in Pip here. I have updated the release notes and provide the following command-line recipe for those of you who have been left with a broken system:
> > 
> > 1. Start the launcher script and select option # 8 - Developer's console.
> > 2. Give the following command:
> > 
> > ```
> > pip install invokeai[xformers] --use-pep517 --upgrade
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This will bring xformers up to date, update to `2.3.5.post1`, and get you up and running again. Apologies for the inconvenience!
> 
> hey I have the issues as well, I have used the line you provided:
> 
> ```
> pip install invokeai[xformers] --use-pep517 --upgrade
> ```
> 
> and it was indeed needed, but the issue still persists, I tried running the second line you provided:
> 
> ```
> pip install torch==2.0.0+cu118 torchvision==0.15.1+cu118 torchaudio==2.0.1 --index-url https://download.pytorch/ .org/whl/cu118
> ```
> 
> but I get this error:
> 
> ```
> ERROR: Invalid requirement: '.org/whl/cu118'
> ```
> 
> it wouldn't update torch like that, just for reference I will provide the error I get before trying generate with invoke ai:
> 
> ```
> InvokeAI\.venv\lib\site-packages\torchvision\transforms\functional.py:1603: UserWarning: The default value of the antialias parameter of all the resizing transforms (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to be consistent across the PIL and Tensor backends. To suppress this warning, directly pass antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - PIL will still use antialiasing). This also applies if you are using the inference transforms from the models weights: update the call to weights.transforms(antialias=True).
> ```

index-url must be^ https://download.pytorch.org/whl/cu118
