### ISSUE TITLE
[bug]: Textual Inversion triggers are often different to those published

### ISSUE THREAD

**Issue by IanCassTwo** [invoke-ai/InvokeAI#3438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

2.3.5

### What happened?

When using some textual inversion's the trigger words are different to those published (list below). It looks like the InvokeAI is using the name inside the TI data.pkl but the published trigger seems to be the filename. Sometimes the differences are trivial and obvious but other times, completely different. Perhaps we can have an option to trigger off filename or internal name?

e.g.

- InvokeAI trigger	Published Trigger and filename
- Fel10-400-1-Sta-1300-7-Lou-800-4	VeronicaCipher
- nbdy-celine-sd15-v4	nbdy-celeste-sd15
- nbdy-scarlet-sd15-2	nbdy-julia-sd15
- nbdy-scarlet-sd15-v2.2	nbdy-isabella-sd15
- optionalAIv4-590	optional_styleAI
- sarahgtm-120	evalyn_noexist

**Comment by hipsterusername** [comment]
We've noticed many creators not following the `training` trigger as well. 

We plan to transition to filename as trigger in 3.0.
