### ISSUE TITLE
[enhancement]: default VAE selection on settings dropdown

### ISSUE THREAD

**Issue by felixsanz** [invoke-ai/InvokeAI#3470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

When trying to use custom/specific VAE with models is a pain because you have to manually edit every single model entry with the `VAE:` key entry. Having a settings `<select>` for a default VAE would be insanely helpful.

![1685110680](https://github.com/invoke-ai/InvokeAI/assets/6182099/78efb141-741f-4072-8a02-d4e3d90ca367)

### Alternatives

An alternative is copy and pasting as if there were no tomorrow

### Aditional Content

`None`: don't use VAE
`Automatic`: use the one specified in models.yaml for that model, if available
`XXXXXX`: always use this one

**Comment by Millu** [comment]
what version of InvokeAI were you using?
