### ISSUE TITLE
[bug ?]: Unable to render, Mac M1, very strange

### ISSUE THREAD

**Issue by walt93** [invoke-ai/InvokeAI#3475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

32GB system

### What version did you experience this issue on?

2.3.5.post2

### What happened?

Using the web interface I was able to render about 5 images, I was changing model after each image. I hit one I wanted to run variants on, started it running 50 and went to do other things. When I came back all of the images generated were a brown-ish stain with a yellow warning icon. I've tried the main menu options for "Re-run the configure script" and "update invokeAI" and there is no change in behavior, neither with shutting down and restarting the script.

Looking for a debugging strategy.

I had deleted all of last nights images, tried again just now and behavior is slightly different - no warning icon.

### Screenshots

![Screen Shot 2023-05-27 at 12 13 06 PM](https://github.com/invoke-ai/InvokeAI/assets/11711050/02baaffe-ae29-4867-b597-c1a8bd3f027c)

**Comment by gogurtenjoyer** [comment]
The warning icon is the NSFW filter which you can disable - the brown/yellow featureless image is because of your noise threshold setting. Try setting that to 0 and trying again.

**Comment by walt93** [comment]
Thank you so much, how embarrassing to open a bug report for a user error 🤦‍♂️
