### ISSUE TITLE
[enhancement]: Use a different port automatically if the default 9090 is in use, instead of crashing on start

### ISSUE THREAD

**Issue by Cloudwalk9** [invoke-ai/InvokeAI#3515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Other SD web UIs would increment the port number automatically until an available port was found.

### Alternatives

Sucking it up and passing --port :sweat_smile: 

### Aditional Content

The Linux system management web GUI Cockpit also happens to use port 9090 by default, which is how I discovered this problem.

**Comment by psychedelicious** [comment]
Thanks, implemented in #3710
