### ISSUE TITLE
[bug]: NotADirectoryError [WinError 267]

### ISSUE THREAD

**Issue by alotazombies** [invoke-ai/InvokeAI#3542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

2.3.5 Post2

### What happened?

getting a directory error regarding charset-normalizer. see attached screenshot. 

### Screenshots

![image](https://github.com/invoke-ai/InvokeAI/assets/86981753/42f2b540-bc11-4c87-b946-faf9235fe5a2)

### Additional context

I have tried running as admin, disabling certain protections, changing install location, reinstalling python (3.9) C core, and ensured long path was enabled. I also uninstalled and reinstalled charset-normalizer. I have this same package running on my desktop but that is python 3.10.

### Contact Details

discord name: alotazombies#4906

**Comment by alotazombies** [comment]
seems to have been resolved by the following steps:
uninstalled python 3.9
installed python 3.10.11
only used default install directory (error occurred when using different install directory)
did not select any additional models for download beyond pre-selected models

**Comment by LolLord-xT** [comment]
can we reopen this? not everyone has or wants to allocate enough space in the user home on their system drive
