### ISSUE TITLE
[enhancement]: add a Q/quit option to the updater

### ISSUE THREAD

**Issue by TrickBit** [invoke-ai/InvokeAI#3543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

ezgoen@gmail.com

### What should this feature add?

Ad a quit/return to previous screen option to the updater

in `def welcome(versions: dict):`
add 

`[Q] Quit and return from whence you came`
directly after 

`[3] Manually enter the tag or branch name you wish to update`

in `main()`

change 
` choice = Prompt.ask("Choice:", choices=["1", "2", "3"], default="3")`

to 

`choice = Prompt.ask("Choice:", choices=["1", "2", "3", "Q"], default="Q")`

append 
`elif choice == "Q":
     return`

to the choice selector

I just realized I was in pre-nodes - this script is slightly different in main

I've tested this in both and it works fine

EDIT : I just realized that this script may be called directly
so to that end just a "Quit" text will meaningfully apply in both cases

### Aditional Content

Should I just offer a diff for this sort of thing rather than this in future?

**Comment by hipsterusername** [comment]
@TrickBit - You're welcome to make a PR contribution since it seems like you know what you think should be updated! Any reason you're hesitant to?
