### ISSUE TITLE
[bug]: InvokeAI/.venv/bin/invokeai-update    line 5

### ISSUE THREAD

**Issue by TrickBit** [invoke-ai/InvokeAI#3544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

pre-nodes

### What happened?

Selecting update from the menu fails with

_Update InvokeAI
Traceback (most recent call last):
  File "some path/InvokeAI/.venv/bin/invokeai-update", line 5, in <module>
    from invokeai.frontend.config import invokeai_update
ModuleNotFoundError: No module named 'invokeai.frontend.config'_

InvokeAI/.venv/bin/invokeai-update    line 5
`from invokeai.frontend.config import invokeai_update`
should read:
`from invokeai.frontend.install import invokeai_update`

### Additional context

Should I just offer a diff for this sort of thing rather than this in future?

### Contact Details

ezgoen@gmail.com

**Comment by hipsterusername** [comment]
@TrickBit - Would definitely encourage you to propose a PR in the future if you think something needs to be changed. We may provide insight on upcoming changes that make it unnecessary, or discuss further etc., but so long as the PR isn't harder than starting an issue, it's a good place to get attention from the right folks to merge it in.

Specifically, in this case, I believe that the installer/start script is being fully updated to work w/ the new backend (and as of the branch you experienced this on, was part of what was "broken"). @lstein can confirm

**Comment by TrickBit** [comment]
@hipsterusername - Being the troglodyte that I am, I'm not sure what is meant by  "a PR" - sorry.
Regarding what part was broken - well it could not actually load the "update" option from the menu because it was trying to import an non-existent  python library : ie  from invokeai.frontend.config import invokeai_update

This failed completely.

Changing the import line to  : from invokeai.frontend.install import invokeai_update made it work.
Am I missing something? I thought I'd made that clear in the bug report.
I apologize if I've misunderstood.
Cheers
:)

**Comment by hipsterusername** [comment]
Ah! A PR is just a proposed code change in GitHub (acronym for a “pull request”) that would be made to the repo. All is clear :)
