### ISSUE TITLE
[resolved][bug]:  Python version mismatch and could not find tb-nightly

### ISSUE THREAD

**Issue by 869Nitro** [invoke-ai/InvokeAI#3560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What version did you experience this issue on?

v2.3.5.post2

### What happened?

Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)] on win32

ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.0rc1 Requires-Python >=3.7,<3.10; 1.7.0rc2 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10
ERROR: Could not find a version that satisfies the requirement tb-nightly (from gfpgan) (from versions: none)
ERROR: No matching distribution found for tb-nightly

### Screenshots

![1](https://github.com/invoke-ai/InvokeAI/assets/126856313/78123dc6-ba7e-4ba1-899d-412f974d3c1e)

**Comment by 869Nitro** [comment]
The issue has been resolved. In the screenshot I submitted earlier, you can see the field “pypi.tuna.tsinghua.edu.cn”. Due to the special network environment in my area, I configured a network acceleration server in advance, but this caused problems during the deployment process of this project. The reason for the failure was that some files that needed to be downloaded could not be downloaded. 
I am not a professional, but the following steps are how I solved the problem: 
1. Delete the pip cache located at “C:\Users\username\AppData\Local\pip\Cache”; 
2. Cancel the network acceleration source in the configuration file located at “C:\Users\username\AppData\Roaming\pip\pip.ini”; 
3. I use Clash to open a proxy CMD and then perform the installation of InvokeAI (this requires you to have or purchase proxy server nodes from a proxy agent).

**Comment by StelleSand** [comment]
> The issue has been resolved. In the screenshot I submitted earlier, you can see the field “pypi.tuna.tsinghua.edu.cn”. Due to the special network environment in my area, I configured a network acceleration server in advance, but this caused problems during the deployment process of this project. The reason for the failure was that some files that needed to be downloaded could not be downloaded. I am not a professional, but the following steps are how I solved the problem:
> 
> 1. Delete the pip cache located at “C:\Users\username\AppData\Local\pip\Cache”;
> 2. Cancel the network acceleration source in the configuration file located at “C:\Users\username\AppData\Roaming\pip\pip.ini”;
> 3. I use Clash to open a proxy CMD and then perform the installation of InvokeAI (this requires you to have or purchase proxy server nodes from a proxy agent).

Thanks, it works for me!
Another option in step 3 is changing all https://github.com/ into https://ghproxy.com/https://github.com/ in stable-diffusion-webui/modules/launch.py;

**Comment by taichuai** [comment]
> 
i also have this problem and via chang the mirro url and install:
pip install tb-night -i https://mirrors.aliyun.com/pypi/simple
it's works for me
