### ISSUE TITLE
[bug]: starting web server fails with KeyError on __metadata__

### ISSUE THREAD

**Issue by keturn** [invoke-ai/InvokeAI#3578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

3ae996ebcbc2d4267aa47cda6d854177bbb3cdb7

### What happened?

Ran `invokeai-node-web` and it failed with:

>   File "InvokeAI/invokeai/backend/model_management/model_manager.py", line 261, in `__init__`                                                                                     
>    `self.config_meta = ConfigMeta(**config.pop("__metadata__"))`
>
> `omegaconf.errors.ConfigKeyError: Key not found: '__metadata__'`

### Additional context

presumably this is because my `models.yaml` is out-of-date?

Searching for `__metadata__` turned up a result in `migrate_models_to_3.0`, but I failed to find that imported anywhere and it didn't get installed as a script in my PATH, so not sure when that's supposed to be executed.

**Comment by ggeli** [comment]
how did you get that back to work?
