### ISSUE TITLE
[bug]: INFO:     127.0.0.1:17778 - "POST /api/v1/sessions/ HTTP/1.1" 422 Unprocessable Entity

### ISSUE THREAD

**Issue by YesThisIsMe007** [invoke-ai/InvokeAI#3628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

v3.0.0+a3

### What happened?

When trying to generate a photo, the 'Server Error' is displayed in GUI and ' INFO:     127.0.0.1:17778 - "POST /api/v1/sessions/ HTTP/1.1" 422 Unprocessable Entity' in error log console.

### Screenshots

![Posnetek zaslona 2023-07-02 132605](https://github.com/invoke-ai/InvokeAI/assets/126345134/169de75c-22e7-4940-8ebc-c06f1aec2aca)
![Posnetek zaslona 2023-07-02 132711](https://github.com/invoke-ai/InvokeAI/assets/126345134/b01ed492-bf01-4b0d-945a-e1be708e3821)

### Additional context

Windows 11, Edge Chromium, 64-bit.

**Comment by YesThisIsMe007** [comment]
Why closed as a problem is still present?

**Comment by hipsterusername** [comment]
Closed because this is most likely a configuration error. There is insufficient information to reproduce the reported issue

**Comment by YesThisIsMe007** [comment]
> Closed because this is most likely a configuration error. There is insufficient information to reproduce the reported issue

Error was active in  3.0.0-alpha 3 release and also after upgrading to alpha 4. After that I deleted the whole invokeai folder, reistalled Python and installed alpha 4 from zero. Now I have alpha 6 and problem is still present. At the moment I'm downloading models and will check for console error later.

**Comment by hipsterusername** [comment]
We have plenty of people using the alpha without this issue - I'm not proposing that you aren't experiencing the issue, but without more information to reproduce it reliably on other systems, we're not going to be able to "fix" it. 

An 'unprocessable entity" means that something that's being submitted to the graph/execution engine is invalid and not constructed correctly. We're planning on making this more explicitly detailed to provide visibility into what, exactly is invalid.

Can you share more about the settings you're using that result in this error?

**Comment by YesThisIsMe007** [comment]
LOL, I just had to download and install models...

**Comment by hipsterusername** [comment]
That would do it. :)
