### ISSUE TITLE
[fr]: Support for SDXL

### ISSUE THREAD

**Issue by simonfuhrmann** [invoke-ai/InvokeAI#3634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Support for the upcoming SDXL model

### Alternatives

There is no alternative.

### Aditional Content

I am sure you're all aware of the upcoming SDXL model which is about to get released soon. The excitement around it is real.

I am curious to learn how much effort it will be to add support for this model? Is this a trivial effort or are major features required to support this?

Is this something that can be back ported to the current v2 release, or will this have to wait for v3? I assume many people want to get their hands on this as soon as it is released, and I'd hate to use a1111 for this, because well, their UI is just meh.

Thanks

**Comment by hipsterusername** [comment]
Hey Simon - Thanks for the note!

We have heard about this so-called “SDXL”

It is not trivial to add, necessarily, but we have done a lot of work to effectively prepare to make it as easy as possible. This will be a 3.0 only feature (3.0 alpha is currently live) and we are hoping to offer day one support, if possible.
