### ISSUE TITLE
[bug]: Unable to import checkpoints, Unable to scale up image

### ISSUE THREAD

**Issue by TheElementSwe** [invoke-ai/InvokeAI#3670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What version did you experience this issue on?

InvokeAI-installer-v3.0.0+a8

### What happened?

Can't import checkpoints, the button, find models doesn't work, and scale 4x doesn't work press upscale image but nothing happens, have run Re-run the configure script to fix a broken install or to complete a major upgrade about 4 times and always is something it downloads or fixes, but it still doesn't work, it feels like InvokeAI-2.3.4rc1 was a bit more stable.

### Contact Details

zwedishprivat@outlook.com

**Comment by hipsterusername** [comment]
Please read the Readme, which states these things are not currently available in the 3.0 Alpha.

**Comment by TheElementSwe** [comment]
Okej tack för informationen, bra att veta, då är det värdelöst att använda den här versionen.

**Comment by hipsterusername** [comment]
I can understand your frustration. I'd encourage you to wait to upgrade until we release it for broader access unless you can spare the moment to read the accompanying documentation.
