### ISSUE TITLE
[bug]: Web UI uses `http`/`ws` behind a reverse proxy instead of `https`/`wss`

### ISSUE THREAD

**Issue by algj** [invoke-ai/InvokeAI#3693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

3.0.0+a8

### What happened?

Upgraded to 3.0.0-rc1, web UI says "Disconnected": socket.io websocket is not connecting because my reverse proxy does not support unsecure http/ws - it redirects automatically to https. Previous InvokeAI releases seemed to use https, if I'm not mistaken.

Tested 3.0.0-rc1 and 3.0.0+a8, both have the same problem.

Checked the code, seems that it is hard-coded to `ws://`.

### Screenshots

![Screenshot_20230708_124118](https://github.com/invoke-ai/InvokeAI/assets/33424336/0afe7194-6c6f-4216-8bf1-3799e6eaccac)

**Comment by tuxthepenguin84** [comment]
Recommend Nginx Proxy Manager for a quick way to test: https://nginxproxymanager.com/guide/#quick-setup

**Comment by ImMikeEmmett** [comment]
I have the same issue when running this of the reverse proxies I use work fine for 2.3.5.post2
Enabling "Insecure content" from the "site settings" in your browser allows connections for the "localtunnel" reverse proxy. - https://localtunnel.github.io/www/ 
However NGROK does not work with this workaround.

For a way to test - I am building a google colab project that uses a reverse proxy. [https://github.com/MikeEmmett/InvokeAI  ](https://github.com/MikeEmmett/InvokeAI  )

Errors from the browser console:



**NGROK - Insecure content blocked:**
index-078526aa.js:121 Mixed Content: The page at 'https://1583-34-171-200-172.ngrok-free.app/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://1583-34-171-200-172.ngrok-free.app/ws/socket.io/?EIO=4&transport=polling&t=ObA7BOk'. This request has been blocked; the content must be served over HTTPS.


**NGROK - Insecure content allowed:**
Access to XMLHttpRequest at 'https://1583-34-171-200-172.ngrok-free.app/ws/socket.io/?EIO=4&transport=polling&t=ObA7L0o' (redirected from 'http://1583-34-171-200-172.ngrok-free.app/ws/socket.io/?EIO=4&transport=polling&t=ObA7L0o') from origin 'https://1583-34-171-200-172.ngrok-free.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.


**Localtunnel - Insecure content blocked:**
Mixed Content: The page at 'https://funny-chicken-jump.loca.lt/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://funny-chicken-jump.loca.lt/ws/socket.io/?EIO=4&transport=polling&t=ObA7U1U'. This request has been blocked; the content must be served over HTTPS.


**Localtunnel - Insecure content allowed (Same error but it now works):**
Mixed Content: The page at 'https://funny-chicken-jump.loca.lt/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://funny-chicken-jump.loca.lt/ws/socket.io/?EIO=4&transport=polling&t=ObA7g3K&sid=no8iWN-sf2RRxNFwAAAA'. This content should also be served over HTTPS.

**Comment by ImMikeEmmett** [comment]
I have confirmed that this also happens with the "Serveo" reverse proxy, (Added to the GitHub project linked above)

**Comment by bani6809** [comment]
this seems to be a regression from 2.3.5

**Comment by josh900** [comment]
Same issue here running on runpod, with 3.0.0

**Comment by ImMikeEmmett** [comment]
@josh900 I don't know with runpod, but Localhost + Serveo you can unblock this by loading the page, Clicking the "Padlock" to the left of the address bar. choosing "Site settings" and "Allowing" insecure content.

If like the aforementioned reverse proxies you get a slightly different URL each time you run it, and you are using Google Chrome (or other chromium based browser) you can go to THIS URL in your browser ( chrome://settings/content/insecureContent ) and add a wildcard containing URL E.G.    [*.]serveo.net    to the "allowed to show" section.

Note: This may not work for runpod, as it does NOT work with "NGROK"

**Comment by dotgrid** [comment]
This issue I opened is related to the discussion here. I have made a first pass at a possible fix: https://github.com/invoke-ai/InvokeAI/issues/3970

**Comment by bani6809** [comment]
> This issue I opened is related to the discussion here. I have made a first pass at a possible fix: #3970

i dont think they are really related. your issue involves running the server standalone as https. the problem in this issue is that the webclient incorrectly uses insecure URLs when the server is behind a reverse https proxy.

**Comment by andzejsp** [comment]
i can confirm running this behind my nginxproxymanager over https is not possible, ws is not connecting.. come on, there should be a flag to turn https on or off.. this is some rookie mistake, jees.. do you really want me poking at the code and PR malicious code or you will do it yourself?

**Comment by reminisences** [comment]
When will this issue be fixed? it has been a few weeks, socketio is correctly identified as wss in version 2.3.5

**Comment by andzejsp** [comment]
idk, other than superb gallery that invoke has there is no reason to use it. automatic1111 works faster from my experince. but the gallery here is awsome.

**Comment by psychedelicious** [comment]
Thanks to @sohelzerdoumi for fixing this in #4116.

**Comment by andzejsp** [comment]
i updated to bleeding edge using that cli menu [9] then used fix [7] but it still using the old ws protocol.

**Comment by psychedelicious** [comment]
@andzejsp 
This change will be included in the next release.

**Comment by ImMikeEmmett** [comment]
Hello all, I have just done a small test using. 3.0.2a1 and this appears to be solved. I don't have access to my full environment at the weekends but it is looking good! 
Thank you all for not only this fix but the whole of Invoke!
