### ISSUE TITLE
[enhancement]: Add torchmetrics==0.11.4 in installer.py

### ISSUE THREAD

**Issue by xxxpabloxxx** [invoke-ai/InvokeAI#3700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

**add torchmetrics==0.11.4 in file /lib/installer.py** 

![image](https://github.com/invoke-ai/InvokeAI/assets/9170510/e0ffb610-95c3-4841-bd07-e10a0f28c6c7)

### Aditional Content

**"For ordinary users"**

After downloading the Invoke-Installer archive, unzip it, go to the **_`lib`_** folder, open the file **_`installer.py`_** using any text editor, find the line **`torch~=2.0.0`** (by pressing ctrl+f) and then add **`"torchmetrics==0.11.4"`**, (just as shown in the screenshot)

![image](https://github.com/invoke-ai/InvokeAI/assets/9170510/d7bad71c-7564-4bff-bf03-cfc198c72218)

**Comment by RebootedDuck** [comment]
Works well on my system and fixes #3658 :)

**Comment by prestonzen** [comment]
Make sure to restart your computer after the fix and install
