### ISSUE TITLE
[bug]: missing TensileLibrary.dat file in torch/lib/rocblas/library/

### ISSUE THREAD

**Issue by tbauknight** [invoke-ai/InvokeAI#3708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

amd

### What version did you experience this issue on?

3.0.0+b3

### What happened?

Having similar trouble to those who reported a constantly loading Gallery and the inability to add models via the model manager interface or to convert safetensor models to diffusers. In addition, the place where you select the number of images to generate is stuck where I first set it and is grayed out.

But hitting Invoke anyway went through a process that eventually ended with this:

[2023-07-09 03:03:38,515]::[InvokeAI]::DEBUG --> Locking /home/trevor/invokeai/models/.cache/ed330c648c7b787677bfb4c28029dee5:sd-1:main:vae in cuda
[2023-07-09 03:03:38,515]::[InvokeAI]::DEBUG --> Current VRAM/RAM usage: 0.16G/0.16G; cached_models/loaded_models/locked_models/ = 1/1/1

rocBLAS error: Cannot read /home/trevor/invokeai/.venv/lib/python3.10/site-packages/torch/lib/rocblas/library/TensileLibrary.dat: No such file or directory
./invoke.sh: line 51: 41226 Aborted                 (core dumped) invokeai --web $PARAMS

Doesn't seem to be related to which model I'm using.

### Contact Details

tzbauknight@icloud.com

**Comment by tbauknight** [comment]
my VRAM is 8GB - 6600XT

**Comment by centuryboy774** [comment]
bro I have the exat same things. When I try to load my AI models it says that this libary or whatever it may be is missing. I wish I had the answer as I am trying to seek it myself. but if someone smart enough finds it I'd like to know.

**Comment by psychedelicious** [comment]
We have a totally new model manager in v4.0.0. If this is still a problem on the latest version, please create a new issue.
