### ISSUE TITLE
[bug]: 3.0.0b4 - invokeai-migrate3 doesn't recurse into subdirectories for embeddings

### ISSUE THREAD

**Issue by panicsteve** [invoke-ai/InvokeAI#3718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What version did you experience this issue on?

3.0.0b4

### What happened?

Most of my embeddings for 2.x are stored in the root of the embeddings directory, but I have a few subdirectories under embeddings/ which historically has been supported by the web ui.  However, invokeai-migrate3 sees these subdirectories as files and logs an error trying to import them. 

For example:

```[2023-07-10 05:47:59,613]::[InvokeAI]::ERROR --> Unable to determine model type for /Volumes/Storage/AI/InvokeAI/embeddings/negative embeddings```

**Comment by lstein** [comment]
Looking into it now.
