### ISSUE TITLE
[bug]: I don't know, if is ti bug, but now don't work gfpgan and upscale

### ISSUE THREAD

**Issue by Sniza** [invoke-ai/InvokeAI#3723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

3.0.0.Beta-4

### What happened?

In old version for me not working Pic to Pic (writte me error) (last 2.3. version), after rebuild it to 3. beta-4 not working gfpgan and upscale. Is it on process, or it be kicked out from system? Sorry for your time, but I want just ask. Thank you very much.

### Contact Details

quantel@seznam.cz

**Comment by hipsterusername** [comment]
Hey Sniza - Thanks for thise! These features aren't wired up yet in the beta. We will likely be removing GFPGAN, as well. Thanks for reporting!
