### ISSUE TITLE
[bug]: Wrong Python Path

### ISSUE THREAD

**Issue by Yggdrah** [invoke-ai/InvokeAI#3736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

11GB

### What version did you experience this issue on?

3.0.0+b4

### What happened?

I have upgraded to the new 3.0 version of Invoke AI. When I want to update to the newest version, the program wants to use the python.exe from the old folder, which does not exist anymore. Unfortunately I couldn't find a way to change the path or instance of the installed Python. Is there a config file or something that contains the path information?
I installed the new Version with the normal installer.

![image](https://github.com/invoke-ai/InvokeAI/assets/134548306/92a3638c-47c0-4946-8df8-69ac34142f67)

Old Path: E:\Image AI\Invoke AI\.venv\Scripts\Python.exe
New Path: E:\Image AI\Invoke_AI_3\.venv\Scripts\Python.exe

**Comment by Yggdrah** [comment]
Edit (Typo) 
Old Path: E:\Image AI\Invoke AI\.venv\Scripts\Python.exe
New Path: E:\Image AI\Invoke_AI_3\.venv\Scripts\Python.exe

**Comment by hipsterusername** [comment]
@Yggdrah - Did you manually move the folder?

**Comment by Yggdrah** [comment]
> @Yggdrah - Did you manually move the folder?

No, i left the original folder as it is and installed the new Version in an new folder. As stated in the description for moving to the new Version 3. The old folder i renamed but then the Python instant is not found. It seems like the Python instance points to the wrong Path.

**Comment by hipsterusername** [comment]
Renaming the old folder likely caused this issue. Try renaming it back to the original name, to see if that works.

**Comment by Yggdrah** [comment]
Thanks for the quick reply

This would work, I have already tested it. However, the folder is no longer needed after the switch and would take up unnecessary space. The same problem would exist if you had to change the hard drive or location.

Also, this will affect the update routine. The Python files are updated in the old folder. Currently I manually copy them to the new folder and vice versa when I want to update. 

I'm not sure if this has the same origin, but as soon as I start InvokeAI, whether web or console, features like upscaling or face reconstruction are disabled (An info text appears accordingly). According to the documentation this can be done with manual parameters. But I did not find a call to do so.

**Comment by Yggdrah** [comment]
I solved the problem by following the manual installation documentation. Thanks for the ideas and help @hipsterusername.

Unfortunately, this did not fix the problem with disabled features. I will open a new ticket when the time comes, but first I will do some testing.

**Comment by hipsterusername** [comment]
> I solved the problem by following the manual installation documentation. Thanks for the ideas and help @hipsterusername.
> 
> Unfortunately, this did not fix the problem with disabled features. I will open a new ticket when the time comes, but first I will do some testing.

Great! 

Those disabled features are cited in the release notes as not currently wired up in the new beta. They will be available soon in an update.
