### ISSUE TITLE
[bug?/enhancement]: parameterization: "v" with SD1.x models is ignored

### ISSUE THREAD

**Issue by Cloudwalk9** [invoke-ai/InvokeAI#3737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Support for v-prediction mode when loading SD1.x models. `parameterization: "v"` seems sufficient in other WebUIs but it's either not implemented or ignored in InvokeAI

**Comment by hipsterusername** [comment]
Can you share any examples of SD1.x models using v-prediction?

**Comment by Cloudwalk9** [comment]
> Can you share any examples of SD1.x models using v-prediction?

https://huggingface.co/lodestones/polyfur/resolve/main/polyfur/polyfur-lion-e52-terminal-snr-e1.safetensors

This one in particular.
