### ISSUE TITLE
[bug]: Model not included in image metadata

### ISSUE THREAD

**Issue by davemedvitz** [invoke-ai/InvokeAI#3738]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.0.0+b5

### What happened?

When looking at metadata for a newly created image, the model reports as `null`

```
{
  "image_name": "9b6e0f9b-db11-47cf-9048-1d7c4eb69d25.png",
  "image_url": "api/v1/images/9b6e0f9b-db11-47cf-9048-1d7c4eb69d25.png",
  "thumbnail_url": "api/v1/images/9b6e0f9b-db11-47cf-9048-1d7c4eb69d25.png/thumbnail",
  "image_origin": "internal",
  "image_category": "general",
  "width": 896,
  "height": 896,
  "created_at": "2023-07-12T13:39:59.402000",
  "updated_at": "2023-07-12T13:39:59.402000",
  "deleted_at": null,
  "is_intermediate": false,
  "session_id": "5e7a76a3-21f6-4a42-a383-ef79364f946a",
  "node_id": "9362a5f6-fdb5-4b70-90e7-783a7baec662",
  "metadata": {
    "type": "t2l",
    "positive_conditioning": "scenery,absurdres,hyper realistic lifelike texture dramatic lighting unrealengine trending on artstation,award winning photo,nikon RAW photo,8k,Fujifilm XT3,masterpiece,no humans,\n,cold, winter, mountain, fog, lut, cinematic, dimmed colors, dark shot, muted colors, film grain, ice,iceland,aurora,",
    "negative_conditioning": "watermark,",
    "width": 896,
    "height": 896,
    "seed": 1814737142,
    "cfg_scale": 8,
    "steps": 70,
    "scheduler": "euler",
    "model": null,
    "strength": null,
    "latents": null,
    "vae": null,
    "unet": null,
    "clip": null,
    "extra": null
  },
  "board_id": null
}
```

**Comment by hipsterusername** [comment]
This is known open item to implement - Metadata will be changing in the next beta version.

**Comment by davemedvitz** [comment]
Is there a board / task list where we can see these things?  I don't want to open other issue for items on the todo list...

**Comment by hipsterusername** [comment]
We'll be sharing a more visible set of to-dos after 3.0 launches. In the meantime, feel free to open issues! I just wanted to respond with an update for visibility :)

**Comment by davemedvitz** [comment]
This does seem to be fixed w/ b6, however that also seems to be a breaking change with recalling promtps from previous versions (see #3794)

**Comment by hipsterusername** [comment]
This is a known breaking change. Metadata schema during betas was being updated/finalized
