### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by jtp3mac** [invoke-ai/InvokeAI#3745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### What version did you experience this issue on?

2.3.5

### What happened?

Generate images with a browser-based interface
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/johnperry/test/.venv/bin/invokeai:5 in <module>                                           │
│                                                                                                  │
│   2 # -*- coding: utf-8 -*-                                                                      │
│   3 import re                                                                                    │
│   4 import sys                                                                                   │
│ ❱ 5 from ldm.invoke.CLI import main                                                              │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│   8 │   sys.exit(main())                                                                         │
│                                                                                                  │
│ /Users/johnperry/test/.venv/lib/python3.10/site-packages/ldm/invoke/CLI.py:21 in <module>        │
│                                                                                                  │
│     18                                                                                           │
│     19 import ldm.invoke                                                                         │
│     20                                                                                           │
│ ❱   21 from ..generate import Generate                                                           │
│     22 from .args import (Args, dream_cmd_from_png, metadata_dumps,                              │
│     23 │   │   │   │   │   │   │    metadata_from_png)                                           │
│     24 from .generator.diffusers_pipeline import PipelineIntermediateState                       │
│                                                                                                  │
│ /Users/johnperry/test/.venv/lib/python3.10/site-packages/ldm/generate.py:32 in <module>          │
│                                                                                                  │
│     29 from omegaconf import OmegaConf                                                           │
│     30 from pathlib import Path                                                                  │
│     31 from PIL import Image, ImageOps                                                           │
│ ❱   32 from pytorch_lightning import logging, seed_everything                                    │
│     33                                                                                           │
│     34 import ldm.invoke.conditioning                                                            │
│     35 from ldm.invoke.args import metadata_from_png                                             │
│                                                                                                  │
│ /Users/johnperry/test/.venv/lib/python3.10/site-packages/pytorch_lightning/__init__.py:34 in     │
│ <module>                                                                                         │
│                                                                                                  │
│   31 │   _logger.addHandler(logging.StreamHandler())                                             │
│   32 │   _logger.propagate = False                                                               │
│   33                                                                                             │
│ ❱ 34 from pytorch_lightning.callbacks import Callback  # noqa: E402                              │
│   35 from pytorch_lightning.core import LightningDataModule, LightningModule  # noqa: E402       │
│   36 from pytorch_lightning.trainer import Trainer  # noqa: E402                                 │
│   37 from pytorch_lightning.utilities.seed import seed_everything  # noqa: E402                  │
│                                                                                                  │
│ /Users/johnperry/test/.venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/__init__.py │
│ :25 in <module>                                                                                  │
│                                                                                                  │
│   22 from pytorch_lightning.callbacks.model_checkpoint import ModelCheckpoint                    │
│   23 from pytorch_lightning.callbacks.model_summary import ModelSummary                          │
│   24 from pytorch_lightning.callbacks.prediction_writer import BasePredictionWriter              │
│ ❱ 25 from pytorch_lightning.callbacks.progress import ProgressBarBase, RichProgressBar, TQDMP    │
│   26 from pytorch_lightning.callbacks.pruning import ModelPruning                                │
│   27 from pytorch_lightning.callbacks.quantization import QuantizationAwareTraining              │
│   28 from pytorch_lightning.callbacks.rich_model_summary import RichModelSummary                 │
│                                                                                                  │
│ /Users/johnperry/test/.venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/progress/__ │
│ init__.py:22 in <module>                                                                         │
│                                                                                                  │
│   19                                                                                             │
│   20 """                                                                                         │
│   21 from pytorch_lightning.callbacks.progress.base import ProgressBarBase  # noqa: F401         │
│ ❱ 22 from pytorch_lightning.callbacks.progress.rich_progress import RichProgressBar  # noqa:     │
│   23 from pytorch_lightning.callbacks.progress.tqdm_progress import TQDMProgressBar  # noqa:     │
│   24                                                                                             │
│                                                                                                  │
│ /Users/johnperry/test/.venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/progress/ri │
│ ch_progress.py:20 in <module>                                                                    │
│                                                                                                  │
│    17 from datetime import timedelta                                                             │
│    18 from typing import Any, Dict, Optional, Union                                              │
│    19                                                                                            │
│ ❱  20 from torchmetrics.utilities.imports import _compare_version                                │
│    21                                                                                            │
│    22 import pytorch_lightning as pl                                                             │
│    23 from pytorch_lightning.callbacks.progress.base import ProgressBarBase                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name '_compare_version' from 'torchmetrics.utilities.imports' 
(/Users/johnperry/test/.venv/lib/python3.10/site-packages/torchmetrics/utilities/imports.py)

**Comment by not-a-rootkit** [comment]
I also have this issue, I think it’s a recent breaking change from torchmetrics. See here: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11648. Setting torchmetrics==0.11.4 should resolve it.

**Comment by jtp3mac** [comment]
I got around it by removing all models and downloading new ones. I tried using the model library from Invokeai (Which I can no longer run, separate issues there.) Does anyone a have great source for library models?

**Comment by BreakingPoint** [comment]
I had this error 

`ImportError: cannot import name '_compare_version' from 'torchmetrics.utilities.imports'`

at the end of installing using the `InvokeAI-installer-v2.3.5.post2` archive under Windows 10.

I solved it with this workaround:

1. Run `invoke.bat` in the installation folder of InvokeAI.
2. Run option 8 `open the developer console`.
3. Check if the correct Python version is printed (>= 3.9.1, < 3.11), like `Python version is: Python 3.10.11`.
4. Install the needed `torchmetrics` module using the command: `pip install torchmetrics==0.11.4`
5. Run `invoke.bat` again and chose option 7 `re-run the configure script to fix a broken install` to continue the installing process.
