### ISSUE TITLE
[enhancement]: NSFW Checker: Unblur button

### ISSUE THREAD

**Issue by LolLord-xT** [invoke-ai/InvokeAI#3769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

discord: bakusho_tentei

### What should this feature add?

Basically instead of the NSFW checker permanently saving blurred and attention-marked images in the output folder, it could instead also apply the blur on the browser and offer a switch to unblur, so people can selectively see NSFW images rather than just an all or nothing. platforms like pixai or civitai have been doing this and it's pretty useful.

**Comment by Barafu** [comment]
It is a safety issue. StableDiffusion can easily (and sometimes unrequested) generate images which are highly illegal to own in some jurisdictions. Simply having such images in some technical folder that a user does not know about can (and did in the past) grant the PC owner a lengthy jail time. 

With NSF checker on the "bad" images should not be saved to disk, and this is a requirement to produce the feature you ask. So I'd vote against it.

**Comment by LolLord-xT** [comment]
it shouldnt be a "highly technical" folder, also it might be possible to have both options, basically having a method to completely ax the image and one that allows to save them.
alternatively one could keep freshly generated nsfw images in ram, allow unblur from there where one can decide to save or not to save,
