### ISSUE TITLE
[bug]: scale before processing - menual doesnt work

### ISSUE THREAD

**Issue by omer-bar** [invoke-ai/InvokeAI#3777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

3.0.0.beta-5

### What happened?

Selecting a manual 'scale before processing' doesn't work, if the bounding box isn't the same as the scaling it throws an error once its done painting/inpainting with the DPM++ SDE Karras Scheduler
for example, a bounding box of 1024,1024 with a scale set to manual and set to 512,512 will throw this error:
> RuntimeError: The size of tensor a (128) must match the size of tensor b (64) at non-singleton dimension 3

a bounding box of 1024,1024 with a scale set to 764,764:
> RuntimeError: The size of tensor a (128) must match the size of tensor b (96) at non-singleton dimension 3

same goes for higher scaling just with different tensor sizes(1024,1024 to 1088,1088 gives tensor b(136))

**Comment by omer-bar** [comment]
is someone going to address this issue? in the 2.3.5 version, the DPM++ SDE Karras Scheduler worked fine no matter the bounding box and scale settings....

**Comment by omer-bar** [comment]
@blessedcoolant would love to get a response on the matter🙏... the DPM++ SDE Karras is by far giving me better results than any other Scheduler but I can't really use it in invokeai 2.3.5+ versions and on large pictures because of low VRAM...

**Comment by blessedcoolant** [comment]
We're reworking the inpaint stuff to use nodes but I'll tag @StAlKeR7779 here coz he would have a better idea about this. If he's busy, I'll take a look at it soon.

**Comment by omer-bar** [comment]
@blessedcoolant, @StAlKeR7779  Hey, bumping so this won't go unnoticed... still the same issue in 3.0.2rc1

**Comment by blessedcoolant** [comment]
Hey, the PR for the new inpaint backend is due to be merged. I'll tag @StAlKeR7779 @psychedelicious both here just so one of us gets around to it.

**Comment by omer-bar** [comment]
@blessedcoolant Issue is fixed as of 3.1.0, I will close this but there seems to be a new issue with the 'Compositing settings'
it out-paints even when I don't want it to/its not supposed to out-paint, The denoise at strength 1 behaves like it is set to 0.3 sometimes, overall 3.1.0 gives worse results for canvas unified than 3.0.0 at least in the inpaint part of things, in 3.0.0 It wasn't out-painting where it's not supposed to and a denoising of 1 was a denoising of 1 no matter what....
Yes i couldn't really use the DPM++ SDE Karras Scheduler properly but i managed to circumvent that limitation you guys fixed in this version...

**Comment by blessedcoolant** [comment]
> @blessedcoolant Issue is fixed as of 3.1.0, I will close this but there seems to be a new issue with the 'Compositing settings' it out-paints even when I don't want it to/its not supposed to out-paint, The denoise at strength 1 behaves like it is set to 0.3 sometimes, overall 3.1.0 gives worse results for canvas unified than 3.0.0 at least in the inpaint part of things, in 3.0.0 It wasn't out-painting where it's not supposed to and a denoising of 1 was a denoising of 1 no matter what.... Yes i couldn't really use the DPM++ SDE Karras Scheduler properly but i managed to circumvent that limitation you guys fixed in this version...

It's possible there is a 1 pixel displacement somewhere on the canvas saving that is forcing outpainting to occur. I'm trying to repro it so I can fix it. The temporary bypass for situations like this would be to unlock the snapping of the bounding box by pressing 'N' and then moving it every so lightly so it encompasses the image entirely.

There is another PR open for Inpainting & Outpainting where we are experimenting with more optimized graphs and edge based coherence passes. Showing good preliminary results. Hopefully as we keep releasing more patches, the inpainting and outpainting quality keeps improving.

The good news is that now that we have ControlNet on the canvas, you should be able to have absolute control on what you are trying to do.

**Comment by omer-bar** [comment]
> 

What I meant by out-painting is not getting out of the bounding box and painting something new, let's say I have a bounding box of 512x512 and the entire box is inside the picture which is let's say a 4K image, lets say I want to inpaint the guy nose, I paint it using the brush, and the result sometimes leaks outside of the places where I painted for example to the eyes of the guy or its mouth so it paints part of the mouth or the eyes even tho I didn't use the brush on those parts....
I'm guessing it has to do with the Compositing settings

maybe that is a better explanation than out-painting...

**Comment by blessedcoolant** [comment]
Check how big your mask blur size is, it could be that?

**Comment by omer-bar** [comment]
> Check how big your mask blur size is, it could be that?

it is set to 0
