### ISSUE TITLE
[bug]: can't upload images to unified canvas

### ISSUE THREAD

**Issue by RieGo** [invoke-ai/InvokeAI#3779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

3.0.0 Beta-5

### What happened?

When using upload button on unified canvas it looks like it's uploading the image, but after upload is finished, there's still an empty canvas.
it is working in img2img tab.

**Comment by psychedelicious** [comment]
This was fixed a day or two ago
