### ISSUE TITLE
[bug]: Canvas editor cuts off while gallery is pinned and using G hotkey to toggle gallery pane

### ISSUE THREAD

**Issue by ymgenesis** [invoke-ai/InvokeAI#3780]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

16gb

### What version did you experience this issue on?

13.4.1

### What happened?

The Canvas ui cuts off while gallery is pinned and using G hotkey to toggle gallery pane. It is fine while gallery is unpinned. Also noticed when you use the shift+G hotkey to unpin the gallery the ui cuts off.

### Screenshots

https://github.com/invoke-ai/InvokeAI/assets/25252829/e5ce86d8-fa64-4c44-9be3-7c3ebe57df13

### Additional context

Currently using main.

**Comment by Millu** [comment]
What InvokeAI version are you using?

**Comment by ymgenesis** [comment]
When I wrote this I was probably using an early beta. I’ve switched to main a while ago, but I still see this issue. On Jul 18, 2023, at 6:41 AM, Millun Atluri ***@***.***> wrote:﻿
What InvokeAI version are you using?

**Comment by blessedcoolant** [comment]
Fixed this in #3812

**Comment by ymgenesis** [comment]
Great!
