### ISSUE TITLE
[bug]: 3.0.0+b6  Cannot load prompts from gallery images from previous versions

### ISSUE THREAD

**Issue by davemedvitz** [invoke-ai/InvokeAI#3794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

3.0.0+b6

### What happened?

When using the web interface, and selecting an image from the gallery, I am no longer able to retrieve the prompt used in generating that image.  In the web UI the option is grayed out, and the `P` shortcut reports that it `Cannot load parameters`.  

This only appears to be an issue for images created with previous versions of InvokeAI

**Comment by davemedvitz** [comment]
The prompt data is still visible on the `Info` screen for the image, so it is obtainable.

**Comment by hipsterusername** [comment]
Yep - as mentioned in other comment, known beta change. Will be consistent going forward
