### ISSUE TITLE
[bug]: Can't copy images to clipboard anymore.

### ISSUE THREAD

**Issue by Barafu** [invoke-ai/InvokeAI#3802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24

### What version did you experience this issue on?

3.0.0+b6

### What happened?

In the 2.3.5, on the txt2img tab, I was able to right click the central image and choose "Copy image". That copied full image data to the clipboard. Then I could paste it into an external image editor. Edit, copy to clipboard again and paste back. 

In 3.0.0, the right click menu does not contain the entry "Copy image". I need to download image, then open the download folder, drag image to editor, edit it, save edited to the file, and not forget to delete the original downloaded file. Alternatively, I can copy image to clipboard by pressing F12 and messing with Chrome tools. That is not a healthy workflow. 

Please either get the entry back, or, maybe even better, create a button "Copy image **data** to clipboard".

P.S. I am marking it a bug because at least for me it is a clear regression. 

### Additional context

Win 11, Brave browser.

**Comment by hipsterusername** [comment]
A copy button in in an open PR for the next version

**Comment by psychedelicious** [comment]
This is resolved, I cannot remember which PR it was in. It's in the release now though.

**Comment by TheNore** [comment]
This is happening to me on a fresh install of 3.7.0 
![image](https://github.com/invoke-ai/InvokeAI/assets/16988567/c93c8fe0-1bb2-4bd7-9514-5a11628bbe4f)

**Comment by hipsterusername** [comment]
> This is happening to me on a fresh install of 3.7.0 ![image](https://private-user-images.githubusercontent.com/16988567/308020673-c93c8fe0-1bb2-4bd7-9514-5a11628bbe4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMDQzODQsIm5iZiI6MTcwOTAwNDA4NCwicGF0aCI6Ii8xNjk4ODU2Ny8zMDgwMjA2NzMtYzkzYzhmZTAtMWJiMi00YmQ3LTk1MTQtNWExMTYyOGJiZTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDAzMjEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNjAwZTQxY2UzMzhkN2E3MDY5MDhkOGFhOTZjYTc3ZWQzOWMwZWNiZDQxODQ2YjU1NjZiMmY3NzAyMTViY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5eVhqE4CRktEdXbz-TUuMzW1Zq-3qfckQOyt4COUauo)

This is a browser limitation - Context menus that are present in the app are limited from copying to the clipboard in certain browsers like Ffox. Open in a new tab, then copy.

sorry for the hassle - the internet (and browsers) seem to have left its golden era.

**Comment by psychedelicious** [comment]
@TheNore You can enable clipboard in Firefox:
- Go to `about:config` in the address bar
- Search for `dom.event.clipboardevents.enabled` and set it to `true`

Should be able to copy with this change.

**Comment by TheNore** [comment]
Awesome, thank you! 
Is there an equivalent functionality in chrome as well?

**Comment by psychedelicious** [comment]
@TheNore Chrome enables this clipboard API by default. You shouldn't need to change anything. Only FF has it disabled by default.

**Comment by trpipher** [comment]
> @TheNore You can enable clipboard in Firefox:
> 
>     * Go to `about:config` in the address bar
> 
>     * Search for `dom.event.clipboardevents.enabled` and set it to `true`
> 
> 
> Should be able to copy with this change.

This was enabled by default for me.

I found that `dom.events.asyncClipboard.clipboardItem` was set to `false` and setting it to `true` fixed it for me

**Comment by TheNore** [comment]
Thank you! Is there any way to enable this for chrome?

**Comment by psychedelicious** [comment]
@TheNore Unless something has changed recently, Chromium browsers enable this API by default.

**Comment by NilsMoller** [comment]
On a fresh install (docker), copying still doesn't work for me on a firefox fork (zen browser) with both of these options enabled in the config.
