### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by mirghiz** [invoke-ai/InvokeAI#3813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.0.0

### What happened?

When i updated invokeai to last version, it didn't work and come out these errors, i tried to install an another xformers but nothing changed.
What do i have to do?

### Screenshots

![Screenshot 2023-07-18 102316](https://github.com/invoke-ai/InvokeAI/assets/134858403/fbf3f53a-0068-4feb-97ef-958060271fdb)
![Screenshot 2023-07-18 102335](https://github.com/invoke-ai/InvokeAI/assets/134858403/68050e0c-8dba-4f5a-a975-ba5bbad645b2)
![Screenshot 2023-07-18 102350](https://github.com/invoke-ai/InvokeAI/assets/134858403/e6f4d376-1109-4a61-9e05-6cd87870bcb0)
![Screenshot 2023-07-18 102413](https://github.com/invoke-ai/InvokeAI/assets/134858403/61af6953-15d7-485e-ae4d-727a0490ef58)

**Comment by Millu** [comment]
Can you try option [7] in the Invoke run script?

**Comment by mirghiz** [comment]
i tried but nothing change, the same messaggio error comes out again.
