### ISSUE TITLE
[bug]: Add ControlNet greyed out

### ISSUE THREAD

**Issue by davemedvitz** [invoke-ai/InvokeAI#3828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

3.0.0+b6, 3.0.0+b8

### What happened?

With the ControlNet slider enabled, the Add (+) icon remains greyed out and inactive.  Clicking on it has no effect

**Comment by Millu** [comment]
I'm unable to reproduce this - mind sharing a screenshot?

**Comment by davemedvitz** [comment]
I figured it out this morning.  somewhere along the line the controlnet files were removed.  Replacing them resolved my issue.

Apologies.

**Comment by liony-hyh** [comment]
I have the same question. How did you solve it? I feel confused and don't know how to enable ControlNet.

**Comment by Zorgonaute84** [comment]
> I figured it out this morning. somewhere along the line the controlnet files were removed. Replacing them resolved my issue.
> 
> Apologies.

The same here. I don't understand what is the problem :-(

**Comment by pieterdd** [comment]
I have the same issue and noticed that `models/sd-1/controlnet` is empty. Is that expected behavior? If not, where do I get the required files?
