### ISSUE TITLE
[bug]: "Open in New Tab" opens two tabs

### ISSUE THREAD

**Issue by Raecaug** [invoke-ai/InvokeAI#3835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24GB

### What version did you experience this issue on?

3.0.0+b10

### What happened?

In the Img2Img or Text2Img panels, right clicking the generated image and selecting "Open in a New Tab" will open the generated image in two tabs, both pointing at the same image file.

**Comment by psychedelicious** [comment]
This is resolved in the a recent release.
