### ISSUE TITLE
[bug]: upload image not working

### ISSUE THREAD

**Issue by egoegoegoegoego** [invoke-ai/InvokeAI#3836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12gb

### What version did you experience this issue on?

3.0.0+b8

### What happened?

on inpaint canvas the upload function is bugged. it says image uploaded but there's no image uploaded. what a petty bug

**Comment by lstein** [comment]
I can reproduce this bug. What happens is that the uploaded image is sent to the gallery. You can then drag and drop it onto the Canvas, but this isn't the expected behavior.

**Comment by RieGo** [comment]
you're right! i had to switch to the assets tab, from there i can drag it onto the canvas.
Is this intended? on version 2 it was different.

**Comment by RieGo** [comment]
it's working on the latest version (3.0.0 and rc2)
thanks!
