### ISSUE TITLE
[bug]: Delete key not deleting currently viewed gallery image 

### ISSUE THREAD

**Issue by Fortyseven** [invoke-ai/InvokeAI#3846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

24gb

### What version did you experience this issue on?

- First seen: 3.0.0rc1 
- Currently: 3.0.0

### What happened?

In 2.x the delete key would delete whichever image was currently selected.

In 3.x, this is still listed as a hotkey, but it does not respond.

[Firefox 115, Ubuntu, etc]

**Comment by zopieux** [comment]
Can confirm. Neither Del nor Backspace works, be it while the gallery or the image output is in focus.
