### ISSUE TITLE
[bug]: invoke.bat menu default is wrong on consecutive commands. 

### ISSUE THREAD

**Issue by Barafu** [invoke-ai/InvokeAI#3864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24

### What version did you experience this issue on?

3.0.0+rc2

### What happened?

Let me just provide the steps, it will make things clear. 

1. Launch `invoke.bat`, see the menu. The bottom of the menu says `Please enter 1-10, Q: [1]`
2. Press 8 for developer console. Type `exit` to get back to menu. The bottom of the menu says `Please enter 1-10, Q: [1]`
3. Hit Enter. The developer console opens again, despite the hint that a web interface will be the default.

**Comment by Barafu** [comment]
I just checked on 3.6.3 and this bug is still there.

**Comment by psychedelicious** [comment]
We reworked the launcher in v4.0.0 (maybe it was v3.7.0). Just tested, the default option works as it should now.
