### ISSUE TITLE
[bug]: v3 frontend decreased max random seed and prevents reproducing 2.x outputs

### ISSUE THREAD

**Issue by cmawhorter** [invoke-ai/InvokeAI#3866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

24

### What version did you experience this issue on?

3.0.0-rc2

### What happened?

It's possible this isn't a bug and I just missed the announcement, but the v3 frontend reduced the [upper seed limit to `2147483647`](https://github.com/invoke-ai/InvokeAI/blob/8fdc8a8da53369f19bb608aac1b47a6c7302368d/invokeai/frontend/web/src/app/constants.ts#L64C31-L64C41). 

If you enter a value more than that into the seed input, it will set it to that max value when the input loses focus, which can lead to confusing output if you don't notice/expect it.  

With the lower upper limit, it is not possible to reproduce many 2.x outputs.

Somewhat related -- perhaps take another look at [this PR](https://github.com/invoke-ai/InvokeAI/pull/2843) which seeks to bump the upper limit.

**Comment by lillekemiker** [comment]
It looks like this was changed from 32 bit unsigned to 32 bit signed. I don't know why this was. Maybe to accommodate something on the frontend?
For reference, numpy defaults to pulling 128 bit unsigned from the system, and negative are not allowed.
If using the legacy `numpy.random.seed()` function, `Seed must be between 0 and 2**32 - 1`

@cmawhorter - if you change the number to `32 ** 2 - 1` locally, does anything break? Does it fix your problem?

**Comment by psychedelicious** [comment]
This is a known thing, the range wasn't reduced intentionally. We'll be updating this so that any value accepted by torch works. This is a *much* larger number space than we allowed in v2.3.

**Comment by zopieux** [comment]
All seed related code in the frontend should probably use a native BigInt, not Number. See: https://github.com/invoke-ai/InvokeAI/pull/2843#issuecomment-1646801106

**Comment by psychedelicious** [comment]
Fortunately, the frontend does nothing with the seed except allow the user to change the value, and then set that value when the graph is created. So once the backend is able to support the larger seeds, we can easily expose that to the UI.

@lstein @StAlKeR7779 would one of you be able to get the backend updated?

**Comment by lillekemiker** [comment]
@psychedelicious - Looks like the backend already supports seeds up to `2 ** 32 - 1`
https://github.com/invoke-ai/InvokeAI/blob/main/invokeai/app/util/misc.py#L17

All the places the places that the seeds are being used, lead to either numpy (np.random.seed, which accepts input between 0 and `2 ** 32 - 1`) and torch (manual_seed, which accepts positive values up to `2 ** 64` and maps negative values into the positive range). All your pydantic classes enforce the seed range to `[0, SEED_MAX]`. So basically, the backend is fine.

**Comment by psychedelicious** [comment]
Just to close the loop - this stems from what I believe is a typo on my part some time ago, where I left that very important `u` out of `uint32`. I've restored the `u` and updated both backend and UI to use the correct value.
