### ISSUE TITLE
A matching Triton is not available, some optimizations will not be enabled. Error caught was: No module named 'triton'[bug]: 

### ISSUE THREAD

**Issue by Kedaranatha** [invoke-ai/InvokeAI#3878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24

### What version did you experience this issue on?

3.0

### What happened?

A matching Triton is not available, some optimizations will not be enabled. Error caught was: No module named 'triton'

manual install doesn't work also 

PS C:\InvokeAI> .\.venv\Scripts\activate
(.venv) PS C:\InvokeAI> pip install triton-2.0.0-cp310-cp310-win_amd64.whl
WARNING: Requirement 'triton-2.0.0-cp310-cp310-win_amd64.whl' looks like a filename, but the file does not exist
Processing c:\invokeai\triton-2.0.0-cp310-cp310-win_amd64.whl
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\InvokeAI\\triton-2.0.0-cp310-cp310-win_amd64.whl'

[notice] A new release of pip available: 22.2.1 -> 23.2
[notice] To update, run: python.exe -m pip install --upgrade pip
(.venv) PS C:\InvokeAI> pip install triton
ERROR: Could not find a version that satisfies the requirement triton (from versions: none)
ERROR: No matching distribution found for triton

[notice] A new release of pip available: 22.2.1 -> 23.2
[notice] To update, run: python.exe -m pip install --upgrade pip
(.venv) PS C:\InvokeAI>  python.exe -m pip install --upgrade pip
Requirement already satisfied: pip in c:\invokeai\.venv\lib\site-packages (22.2.1)
Collecting pip
  Downloading pip-23.2-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 2.4 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.2.1
    Uninstalling pip-22.2.1:
      Successfully uninstalled pip-22.2.1
Successfully installed pip-23.2
(.venv) PS C:\InvokeAI> pip install triton
ERROR: Could not find a version that satisfies the requirement triton (from versions: none)
ERROR: No matching distribution found for triton
(.venv) PS C:\InvokeAI>  pip install triton-2.0.0-cp310-cp310-win_amd64.whl
WARNING: Requirement 'triton-2.0.0-cp310-cp310-win_amd64.whl' looks like a filename, but the file does not exist
Processing c:\invokeai\triton-2.0.0-cp310-cp310-win_amd64.whl
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\InvokeAI\\triton-2.0.0-cp310-cp310-win_amd64.whl'

### Screenshots

Desired action:
1. Generate images with the browser-based interface
2. Explore InvokeAI nodes using a command-line interface
3. Run textual inversion training
4. Merge models (diffusers type only)
5. Download and install models
6. Change InvokeAI startup options
7. Re-run the configure script to fix a broken install or to complete a major upgrade
8. Open the developer console
9. Update InvokeAI
10. Command-line help
Q - Quit
Please enter 1-10, Q: [1] 1
Starting the InvokeAI browser-based UI..
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
[2023-07-21 14:42:20,410]::[InvokeAI]::INFO --> Patchmatch initialized
C:\InvokeAI\.venv\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(

**Comment by barepixels** [comment]
I got the same error too when installing, but Invoke3 works

**Comment by cchance27** [comment]
Seems to not be getting installed during the main installation i get the same error during startup

**Comment by psychedelicious** [comment]
There's no Windows `triton`, and that warning does not mean anything is wrong. We need to suppress the warning message.

It's likely that your install was actually fine - did you try it?

**Comment by damadorPL** [comment]
https://huggingface.co/r4ziel/xformers_pre_built/resolve/main/triton-2.0.0-cp310-cp310-win_amd64.whl  you could use this and pip install it on win :)

**Comment by damadorPL** [comment]
 {  D: 易InvokeAI3 }  pip install .\triton-2.0.0-cp310-cp310-win_amd64.whl
Processing d:\invokeai3\triton-2.0.0-cp310-cp310-win_amd64.whl
Requirement already satisfied: filelock in d:\invokeai3\.venv\lib\site-packages (from triton==2.0.0) (3.12.2)
Collecting cmake
  Downloading cmake-3.27.0-py2.py3-none-win_amd64.whl (34.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.6/34.6 MB 65.1 MB/s eta 0:00:00
Requirement already satisfied: torch in d:\invokeai3\.venv\lib\site-packages (from triton==2.0.0) (2.0.1+cu117)
Requirement already satisfied: jinja2 in d:\invokeai3\.venv\lib\site-packages (from torch->triton==2.0.0) (3.1.2)
Requirement already satisfied: sympy in d:\invokeai3\.venv\lib\site-packages (from torch->triton==2.0.0) (1.12)
Requirement already satisfied: networkx in d:\invokeai3\.venv\lib\site-packages (from torch->triton==2.0.0) (3.1)
Requirement already satisfied: typing-extensions in d:\invokeai3\.venv\lib\site-packages (from torch->triton==2.0.0) (4.7.1)
Requirement already satisfied: MarkupSafe>=2.0 in d:\invokeai3\.venv\lib\site-packages (from jinja2->torch->triton==2.0.0) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in d:\invokeai3\.venv\lib\site-packages (from sympy->torch->triton==2.0.0) (1.3.0)
Installing collected packages: cmake, triton
Successfully installed cmake-3.27.0 triton-2.0.0

**Comment by gardunorr** [comment]
Same problem......

I have:

"A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
[2023-07-22 14:44:36,363]::[InvokeAI]::INFO --> Scanning G:\invokeai_3.0.0\models for new models
[2023-07-22 14:44:36,413]::[InvokeAI]::INFO --> Scanned 5 files and directories, imported 0 models
This window is too short for the user interface. Please make it taller.
Press any key to continue.."

"Press any key" give no results, installation was blocked to this step

The tip given by "damadorPL" does not improve anything !!!!

**Comment by psychedelicious** [comment]
@gardunorr Actually, the output makes a suggestion:
` This window is too short for the user interface. Please make it taller.`

Make your terminal window larger, then press a key to let it continue.

**Comment by gardunorr** [comment]
Thank you, after some runs, the installation proceed

**Comment by emilanderss0n** [comment]
I get the same thing. And the webui doesn't load anything except a dark background.

**Comment by psychedelicious** [comment]
@emilanderss0n 
Please follow these steps to reset the UI:
- Start the InvokeAI UI and open it in your browser
- Follow [these instructions](https://webmasters.stackexchange.com/a/77337) to open the browser's console 
- Copy and paste `localStorage.clear()` into the console and press `Enter` to run the command
- Refresh the page

**Comment by psychedelicious** [comment]
We'd love a contribution to suppress the triton warning message on Windows. See  #3954
