### ISSUE TITLE
[enhancement]: details on The New Approach To CLI ?

### ISSUE THREAD

**Issue by draconicfae** [invoke-ai/InvokeAI#3879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I'm a bit sad that the old CLI was retired, but I'm glad to hear there's a new one in the form of invokeai-node-cli.  I haven't been able to find any documentation on how to use it though.  The old CLI documentation was quite good so it would be great to have something similar for The New One.

**Comment by cwallen** [comment]
I asked about this in the discord Q&A they just did. The invokeai-node-cli is more of a way to build node pipelines form the cli, not really a way to do image generation like the old cli. They have a plan to bring back batch file generation eventually, but it's lower priority unless enough people speak up asking for it. 

My input on what I would like to see based on my use; I primarily run Invoke on a remote colab like server, so it's easier to run it in a non interactive mode, so I want to be able to download a model from a url (or at least be able to convert a downloaded model for the command line), and run a batch of prompts. I don't need an interactive prompt like the old cli. I'd also likely be able to adapt to being able to launch just the back end and hit the API, if that API is stable enough to be documented. 

I'd also be keen to see a way of building a node pipeline in the web ui on my local computer, then exporting that to a file which could be imported on the remote machine where I can run faster generations.

**Comment by daniellz** [comment]
Thumb up for batch file generation. Something like deprecated !replay

**Comment by KennethLj** [comment]
Read prompts from a file would be great for batch processing.

**Comment by xonoma** [comment]
The official statement is:

> ...The original "invokeai" command-line interface has been retired. The invokeai command will now launch a new command-line client that can be used by developers to create and test nodes. It is not intended to be used for routine image generation or manipulation.

It was a bit confusing to fire up InvokeAI and realize that you couldn't do batch processing from the command line anymore. That was such a convenient tool! I really hope that it'll be brought back. So from what I understand, the only true/easy way to image generation hereon after is through the browser interface?

**Comment by amolinasalazar** [comment]
I really want to use the new version and explore with SDXL, but I actually used more the CLI than the UI when I was using InvokeAI. Hope the InvokeAI team bring that feature back, I'll keep the old version as far as I can :/

**Comment by jjkalafut** [comment]
Yeah CLI and batches is the only way I can find to use multiple GPUs at once. It'd be nice to get back, even in a very basic form.

**Comment by ChrGriffin** [comment]
Literally the only reason I was even interested in InvokeAI was for the CLI, a feature that was missing from every other Stable Diffusion solution. I can't begin to express my utter disappointment that it's seemingly being left by the wayside. I very, very much hope it makes a return. Until it does, I simply cannot upgrade to 3.0.

**Comment by 64jcl** [comment]
If they do add CLI again, they should make it more of an API where you call the InvokeAI server through some kind of REST service so that it can be optimized by retaining the selected model like the UI frontend does now with the backend. This will make generation of images not spend time having to re-load the model which I see is a common problem with CLI type AI implementations.

**Comment by psychedelicious** [comment]
Sorry folks. A CLI is a bit too much to manage for us now and has been totally removed.

Indeed, if we were to support a CLI in the future, it would be a probably be lightweight REST client as suggested by @64jcl .

Closing this as we have no CLI to document now.
