### ISSUE TITLE
[enhancement]: multi-select in gallery would drastically improve usage.

### ISSUE THREAD

**Issue by cchance27** [invoke-ai/InvokeAI#3882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I feel like the gallery really needs the ability to shift or ctl select multiple items do delete, especially after finishing generating a crapton of images i want to clean things up and delete a bunch, deleting one at a time seems frustrating

Would be even better if we could just box select them with mouse to multi-select

**Comment by psychedelicious** [comment]
This was actually fully implemented a couple weeks ago. We updated some gallery internals and broke this in the process, so instead of delaying release to fix that, we disabled multi-select. IT will be available in an upcoming update.
