### ISSUE TITLE
[enhancement]: Node UI usability, and possibly missing basic functionality?

### ISSUE THREAD

**Issue by cchance27** [invoke-ai/InvokeAI#3884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I'm trying to get the feel for the nodeui in 3.0.0 because it seems powerful and would allow for complex operations, coming from comfy it seems that either I'm missing how to do some basic thing's or the UI is missing some basic ... usability items I sort of expected would make it even into an experimental version.

- Major: Removing nodes? Not via delete key on keyboard or right click
- Major: Remove edges? Not via delete key on keyboard or right click
- Minor: Highlight hint based on mouseover of input/output of valid targets (when mousing over the legend highlight all that match)
- Minor: Pins or Splitters for organization of edges (just blind passthroughs for cleaning things up)
- Minor: Ability to duplicate/clone a node, instead of having to search and add again, like for a text input
- Minor: Right click menu... Like seriously you guys have the UI element from the gallery it feels like a missed opportunity to not just have the right click menu here for shortcut to things.
- Minor: Quick add (focus and start searching) when you hit space so you can <space>prompt<enter> it really helps with dealing with node graphs

**Comment by psychedelicious** [comment]
Node editor is in an experimental, MVP state - hence being disabled by default. We've been using it for months and are painfully aware of what is missing. Rest assured, when an update includes the proper release of the node editor, we'll provide a polished user experience.

**Comment by hipsterusername** [comment]
Major: Removing nodes? Click > Backspace
Major: Remove edges? Click > Backspace

**Comment by zopieux** [comment]
One thing that I believe is super important if you want to increase adoption and get feedback from more (non particularly savvy) users which otherwise have no idea what to do in this tab:

* [ ] Add a "presets" button which (for now) loads a basic setup for sampling, basically replicating the normal txt2img without any advanced stuff like controlnet or LoRAs: model loader, pos/neg prompts, noise generation, text  to latents and image preview.

**Comment by hipsterusername** [comment]
We plan on supporting a graph library to store templates in the future.

**Comment by Mikec78660** [comment]
> One thing that I believe is super important if you want to increase adoption and get feedback from more (non particularly savvy) users which otherwise have no idea what to do in this tab:
> 
> * [ ]  Add a "presets" button which (for now) loads a basic setup for sampling, basically replicating the normal txt2img without any advanced stuff like controlnet or LoRAs: model loader, pos/neg prompts, noise generation, text  to latents and image preview.

Someone had suggested being able to load the current UI settings into the node editor. I think that would be a great approach to introducing people to the node editor.

**Comment by zopieux** [comment]
Yes, it's the obvious next step once the entire backend is neatly node-ified. The UI becomes a friendly "builder" for a given graph, so you can losslessly switch to Nodes in which you can do more tweaking and more advanced stuff. Ideally it'd also be possible to switch back to the UI if the graph is the right shape for the normal UI.

The step after that is Python code generation of the graph so you can take full control over the workflow. But it's definitely out of scope :-)

**Comment by psychedelicious** [comment]
@hipsterusername Just tying back to our previous convo, this is the kind of functionality we can achieve by making the linear UI a function of the graph. It's very similar to how the node editor works but we need another layer of data for UI nodes to support it. 

Right now reactflow handles this for us, we'd need a custom setup to dynamically populate the linear ui based on a graph template.

**Comment by hipsterusername** [comment]
@psychedelicious -  Hear you. Think we need to think through how to achieve this while not turning it into a longer term effort - The people need their nodes.
