### ISSUE TITLE
[bug]: Deleted model via the UI - entire models folder was deleted

### ISSUE THREAD

**Issue by emeleye** [invoke-ai/InvokeAI#3887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

3.0.0

### What happened?

I clicked the trash can icon in the model manager to remove a single model from the model list.  This action deleted the entire model folder and, naturally, its contents.

**Comment by Millu** [comment]
@blessedcoolant not ideal behavior 😅

**Comment by blessedcoolant** [comment]
I'll try to repro it. But this'd be a fix for @lstein on the backend if its a bug somewhere. First time I'm hearing of the entire models folder getting wiped.
