### ISSUE TITLE
[bug]: Installed only SDXL model and refiner, the appear in model list in model manager, but text2image tab complains about no models

### ISSUE THREAD

**Issue by alkemann** [invoke-ai/InvokeAI#3890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

16

### What version did you experience this issue on?

3.0.0

### What happened?

I installed a fresh install. I asked for only SDXL model and refiner. They are listed in the model manager. On the generation interfaces there are no models to select.

### Contact Details

alkemann on discord

**Comment by CyrilPaulus** [comment]
They are not yet available using the current UI.
You should use the node system, see the section [Getting Started with SDXL](https://github.com/invoke-ai/InvokeAI/releases/tag/v3.0.0#getting-started-with-sdxl) of the Readme for more detail.
