### ISSUE TITLE
[bug]: Tried to import nodes from Comfyui invoke no longer loads

### ISSUE THREAD

**Issue by freshlesh3** [invoke-ai/InvokeAI#3893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12

### What version did you experience this issue on?

3.0

### What happened?

I tried to install nodes created in comfyui and now the ui doesn't load at all.  I get a blank screen. I also have the Triton module error that seems to not install with the rest of the package. I've done a complete reinstall and still have the issue.

**Comment by blessedcoolant** [comment]
Clear local storage for now. It'll work again.  We'll do a fix for this when we're refining Node Editor.
