### ISSUE TITLE
[bug]: long model names render parts of the UI inaccessible 

### ISSUE THREAD

**Issue by peterAIML** [invoke-ai/InvokeAI#3897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

3.0.0

### What happened?

Long model names enlarge the left part of the UI and push other parts out of the accessible frame (see screenshot at the right; no scrollbar becomes visible)
Screen resolution is 1920x1080
Browser: Chrome 115.0.5790.99
OS: Windows 10

### Screenshots

![invokeai_UI](https://github.com/invoke-ai/InvokeAI/assets/113024619/e6a44905-ca15-46fd-9cb5-3654364d9712)

**Comment by hipsterusername** [comment]
Thanks for pushing the software to its limits (literally)! 🙃 

For now, until this truncates, would just recommend renaming (which can be done via UI or updating the models.yaml file)
