### ISSUE TITLE
[bug]: M1 MacOS Slowdown

### ISSUE THREAD

**Issue by justmammt** [invoke-ai/InvokeAI#3901]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

8GB

### What version did you experience this issue on?

3.0.0

### What happened?

On a fresh install of InvokeAI, image generation using inpainting and txt2img take 10 to 25 minutes of wait to have it totally generated.

### Screenshots

<img width="138" alt="image" src="https://github.com/invoke-ai/InvokeAI/assets/111395403/69664f4d-a9c8-46d4-aefa-47f9a946b602">

### Additional context

MacBook Air M1 8GB, using WebUI

**Comment by hipsterusername** [comment]
I'm not familiar with the speed you ought to expect with a Macbook Air, but that's close what I'd be expecting
