### ISSUE TITLE
[bug]: Controlnet install Downloads but does no show in UI

### ISSUE THREAD

**Issue by darthsnarkey** [invoke-ai/InvokeAI#3903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.0.0

### What happened?

When ysing invoke-model-install I check the controlnet models to install. I select 'Apply Changes' in UI, Model download successfully, I finish install and close invoke-model-install and launch invoke, contolnets do not show in UI as available.

Specific Model I have issue installing: Controlnet Inpaint

### Contact Details

darth.snrkey@gmail.com

**Comment by psychedelicious** [comment]
I don't think we list the controlnet inpaint model in the installer script, so I think you must be using the web ui - is that correct?

The model manager tab in the web ui does not support controlnet models yet - only "main" stable diffusion models. We are working on supporting all models via the ui, though!
