### ISSUE TITLE
[bug]: In 3.0 release, LoRAs behave differently than Beta 6

### ISSUE THREAD

**Issue by gogurtenjoyer** [invoke-ai/InvokeAI#3909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

16GB URAM

### What version did you experience this issue on?

3.0.0

### What happened?

I noticed that LoRAs (maybe just the ones I've tested, though I tested about 6-8) do not have their intended effect in 3.0. They do seem to have an effect on the image, but it mostly seems as though they 'weaken' the original image.

To test this (I still have beta 6 installed), I generated the same image in both versions, without the LoRA, and then with the LoRA set to 2.0 strength. I'm sorry, I know a lot has changed between the betas and release but hopefully this'll help pinpoint it.

I used this 'skin detail' LoRA here as a test: https://civitai.com/models/109043

### Without LoRA:
![f36ebe2e-4a8a-49ae-a482-da4328a21e26](https://github.com/invoke-ai/InvokeAI/assets/36354352/ae37311a-40ae-4287-b6f4-dbeeaa651c38)
### With LoRA at 2.0:
![1998b53f-115a-403c-8e4e-2f948b9dae4a](https://github.com/invoke-ai/InvokeAI/assets/36354352/a44ae97d-3b1f-41fb-8c61-413a20e3254e)

### Without LoRA:
![77138dd3-da5c-4f04-8e1e-682a3aa6cd38](https://github.com/invoke-ai/InvokeAI/assets/36354352/e713b7fb-b9a8-496b-a588-3fff3fe86332)
### With LoRA at 2.0:
![442dd32d-6338-46a5-8070-2a637e900d83](https://github.com/invoke-ai/InvokeAI/assets/36354352/e6e21f67-4470-4e24-b6e1-398913c29e59)

### Additional context

This was tested in both linear and nodes UIs - the examples above are from linear.

**Comment by hipsterusername** [comment]
@StAlKeR7779 is this when you made the Lora fix?

**Comment by gogurtenjoyer** [comment]
This is now resolved (for the record, we're not sure why!) so I'm closing. Thanks all!
