### ISSUE TITLE
[enhancement]: 3.0 - features_ some irritations

### ISSUE THREAD

**Issue by stevebphoto** [invoke-ai/InvokeAI#3918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

steve.idealcs@gmail.com

### What should this feature add?

Cache folder gets too big and switching Models - takes long, the cache generated is very large, I used just a few models and 40GB later, switching models takes long when using new models - but i have to keep clearing the cache - just way too big, makes using different models very painfull ( yes space is an issue, which is technically my issue, but I'm still - lol)

selecting multiple gallery items would be amazing -the gallery concept is excellent!

a better way to import Lora / Lycos / embeddings - I used model manager - it did import but when reloading Invokeai - i have to readd through model manager. ( used folders from Automatic 1111) perhaps using a select folder setting in model manager?

Civit link next to the git page would be great

Hotkeys - brilliant Idea - Please add for prompts (ie: strengthen) shortcuts etc

use seed button next to the seed box would be a nice to have as well 

lastly a BIG BIG BIG thank YOU to all who contributed - I just LOVE this new Version 3.0

**Comment by Millu** [comment]
Thanks for the feedback!

Multi-select in the gallery is coming! It was implemented but caused some other issues so was rolled back in favor of 3.0 being released

> Civit link next to the git page would be great
Could you expand on this?

**Comment by Millu** [comment]
Many of these have since been included in newer versions of Invoke, going to close out for now. Thank you for the feedback!
