### ISSUE TITLE
[bug]: "Smiley Face" icon for face reconstruction not visible

### ISSUE THREAD

**Issue by dsadsa897897r** [invoke-ai/InvokeAI#3919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

3.0.0

### What happened?

I don't appear to have the "Smiley Face" icon for face reconstruction shown here: https://invoke-ai.github.io/InvokeAI/features/POSTPROCESS/#upscaling

![image](https://github.com/invoke-ai/InvokeAI/assets/7852568/b26a16ab-bc76-4151-887d-e57276f60316)

The upscale icon appears fine.

Am I doing something wrong?

I have run invokeai-configure

**Comment by hipsterusername** [comment]
The is feature was removed in 3.0
