### ISSUE TITLE
[bug]: Unified Canvas (NSFW screenshot warning)

### ISSUE THREAD

**Issue by barepixels** [invoke-ai/InvokeAI#3920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.0.0

### What happened?

Tried to outpainting right side, but it place the rendered on the left side.  See screen capture (NSFW). Original image is 2048x3072

**Comment by hipsterusername** [comment]
Don’t paste NSFW content please.

**Comment by barepixels** [comment]
Sorry about that.  It work fine 2nd time.  Weird
