### ISSUE TITLE
Model Merging Restrictions

### ISSUE THREAD

**Issue by Millu** [invoke-ai/InvokeAI#3928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Invalid base models should not be able to be merged

**Comment by Millu** [comment]
@lstein @blessedcoolant @StAlKeR7779 wasn't sure if this is still relevant with the new model manager

**Comment by blessedcoolant** [comment]
Only the models that are capable of being merged should show up on the drop down. Did you face a situation where you could not merge something?

**Comment by Millu** [comment]
Ok makes sense - I haven't been able to reproduce but it was a bug reported a little while ago. Will close for now.
