### ISSUE TITLE
[enhancement]: Update Model Deletion to be simpler

### ISSUE THREAD

**Issue by Millu** [invoke-ai/InvokeAI#3930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

![image](https://github.com/invoke-ai/InvokeAI/assets/7254508/e5f3c7b3-0f94-4902-b284-c26efb7a8ed4)

I manually added a model to a folder inside my invoke ai root folder, but not in the "official" folder. I don't know if deleting the model will delete it from disk or not.

* The route should have a delete_from_disk parameter. If and only if this is true should it delete from disk. otherwise it should just remove the entry from the list.
* The promo text should be updated to be easier to understand

**Comment by blessedcoolant** [comment]
Yeah. I agree. If @lstein adds that backend functionality, I can update the UI to reflect the same.
