### ISSUE TITLE
[bug]: Image gallery fetches thumbnails twice

### ISSUE THREAD

**Issue by Millu** [invoke-ai/InvokeAI#3939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What version did you experience this issue on?

3.0.0rc1

### What happened?

Chrome hides this from you, but FF shows NS_BINDING_ABORTED errors in network tab for each occurrence. Looks like this is due to the gallery rendering twice when images are added to the list. maybe we can improve this.

**Comment by Harvester62** [comment]
Hi Millu, Is this still happening with v3.7 or latest v4.0 Release Candidate?

**Comment by psychedelicious** [comment]
This is a non-issue. The errors are just indicating that the same image was requested twice in succession. This happens during normal operation.
