### ISSUE TITLE
[enhancement]: Canvas image error image should be more descriptive

### ISSUE THREAD

**Issue by Millu** [invoke-ai/InvokeAI#3952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Currently when an image on the canvas does not load, a bright red box is drawn with no description. 

Instead, we want to have red hashed out image with text "Image did not load" so that the user understand the error.

**Comment by psychedelicious** [comment]
This is now implemented in canvas v2.
