### ISSUE TITLE
[enhancement]: De-duplicate Canvas toolbar UI

### ISSUE THREAD

**Issue by Millu** [invoke-ai/InvokeAI#3953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Almost all canvas UI toolbar components and their logic are duplicated for the "Beta" layout. So any change has to be done on both. We want to streamline this for usability and maintenance.

Options for Discussion:

* Choose one layout and stick with it. This gets my vote because even if we modularize the components and logic, it's still two different layouts to support and troubleshoot. 
* Modularize the components and logic and continue to support two different canvas layouts.

**Comment by psychedelicious** [comment]
This was done in #5084
