### ISSUE TITLE
[bug]: Autoimport doesn't work

### ISSUE THREAD

**Issue by andupotorac** [invoke-ai/InvokeAI#3965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

64

### What version did you experience this issue on?

3

### What happened?

I installed a brand new version if Invoke on my Mac, and did no migration. Because I already have the old invoke, and A1111, were my models, loras, controlnets, and textual inversions are, I skipped downloading anything - to set them manually to link to only one place.

I followed the instructions here, and replaced the folders in autoimport with folders with the same name, which are aliases to Stable Diffusion's current models/loras/checkpoints/textualinversions.

https://invoke-ai.github.io/InvokeAI/installation/050_INSTALLING_MODELS/#installation-via-the-autoimport-function

But nothing loads when I restart the app. I also don't know if I should move anything from the old version of Invoke here, or my models from A1111 are enough.

### Screenshots

<img width="716" alt="Screenshot 2023-07-24 at 22 19 52" src="https://github.com/invoke-ai/InvokeAI/assets/3269738/bf36cf88-36b7-41a1-a9ec-3a7d9053da20">

<img width="1625" alt="Screenshot 2023-07-24 at 22 20 40" src="https://github.com/invoke-ai/InvokeAI/assets/3269738/c5cc168a-67bd-402e-ac11-6892014e3523">

### Contact Details

@andupotorac

**Comment by Millu** [comment]
Have you tried auto importing with the actual models in the folder instead the aliases?

**Comment by andupotorac** [comment]
> Have you tried auto importing with the actual models in the folder instead the aliases?

What's the point of that? The idea of Auto-import is to prevent users from duplicating all these GB of files. If Autoimport is supposed to work as described, it currently doesn't.

**Comment by andupotorac** [comment]
Would appreciate knowing if this is being addressed, so I can give invokeAI a test.

**Comment by TechInterMezzo** [comment]
I am having the same problem.
Autoimport does not work with symbolic links to directories. But it works with file links.
ComfyUI for example works with directories.
That is much better as I won't have to link every single file, just the directory.

**Comment by ChristopherLafferty** [comment]
Same here. I tried adding symbolic inks to directories and the scanning does not see them.

**Comment by sa-shiro** [comment]
just confirmed this, symlink folders do not work (symlink the `models` folder nor organized folders do not work) however symlinking the files does work

would be great, if symlink folder would work!

**Comment by Millu** [comment]
This has been addressed!
