### ISSUE TITLE
[bug]: SDXL-0.9 installation halts

### ISSUE THREAD

**Issue by aykutkilic-avl** [invoke-ai/InvokeAI#3974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

24GB

### What version did you experience this issue on?

3.0.0

### What happened?

In invokeai/backend/install/model_install_backend.py/_download_hf_pipeline():
HF models are downloaded via DiffusionPipeline.from_pretrained() fn.
model = DiffusionPipeline.from_pretrained(repo_id,revision=revision,safety_checker=None)
The problem is without defining the variant as 'fp16' downloading SDXL-0.9 base model halts as below:

```
>>> DiffusionPipeline.from_pretrained('stabilityai/stable-diffusion-xl-base-0.9')
Fetching 18 files:   0%|                                                                                                                          | 0/18 [00:00<?, ?it/s]
Fetching 18 files:  28%|███████████████████████████████▋                                                                                  | 5/18 [00:10<00:26,  2.05s/it]
```

I made a dirty hack for my installation:
```
variant = 'fp16' if repo_id == 'stabilityai/stable-diffusion-xl-base-0.9' else None
model = DiffusionPipeline.from_pretrained(repo_id,revision=revision,safety_checker=None, variant=variant)
```
and this works.

### Additional context

Only happens when downloading the SDXL-0.9 base. For other models it works (including SDXL-0.9 refiner)

### Contact Details

aykutkilic80@gmail.com

**Comment by Millu** [comment]
Closing this as SDXL1.0 has been released
