### ISSUE TITLE
Variation Support

### ISSUE THREAD

**Issue by Millu** [invoke-ai/InvokeAI#3976]
## Summary 

Variations allow for a series of systematic variations of an image based on a prompt. From these variation, users can create a weighted combination of two variations of an image. 

Currently 3.x does not support variations

## Intended Outcome
* Users are able to generate variations with InvokeAI 3.x
* Variations are able to be combined along with weights to create a new output image

**Comment by hipsterusername** [comment]
This will not be considered, given the lack of demand for randomized noise shaping
