### ISSUE TITLE
Node Editor 1.0

### ISSUE THREAD

**Issue by Millu** [invoke-ai/InvokeAI#3978]
## Summary

Roadmap for rework of node editor in preparation for official release.

### Internal

- [ ] Improved python UI helper config classes (e.g. manually specify field types, UI components, input requirements, etc)
- [ ] Use node templates as source of truth for node UI rendering, not `reactflow` internal state; update stored `reactflow` state when node templates are changed
- [ ] Split up the single big node field value reducer; one reducer per field type
- [ ] Node versioning (?)
- [ ] User-definable node & edge attributes (label, notes, styles?)
- [ ] State history (for undo/redo)
- [ ] Enable field type & acyclic connection validation
- [ ] Minimal graph validation before invoke (check input requirements, that's probably it) 

### User Experience

- [ ] Hotkeys (delete, copy, paste, undo, redo, etc)
- [ ] Improved styles
- [ ] Collapsible nodes
- [ ] Expose `is_intermediate` in node settings
- [ ] Node outputs display in node
- [ ] Improve field type legend (shapes, icons, etc)
- [ ] Shareable workflow support (mark fields as exposed to display in side panel, abstracted representation of graph that parses into `reactflow` state)

### v1.1 / Stretch Goals

- [ ] Node grouping
- [ ] 

## Intended Outcome
The node editor is a frictionless user experience and allows users to intuitively build & share graphs using known controls.

**Comment by psychedelicious** [comment]
I think we can close this now that I've made a full on roadmap: https://github.com/orgs/invoke-ai/projects/9/views/1?layout=roadmap
