### ISSUE TITLE
Model & LoRA Training

### ISSUE THREAD

**Issue by Millu** [invoke-ai/InvokeAI#3979]
## Summary
Users currently have to train models elsewhere before importing them to invoke and being able to use them. 

InvokeAI has scripts for training custom Stable Diffusion models: https://github.com/invoke-ai/invoke-training

## Intended Outcome
* Users are able to train Models and LoRAs from within InvokeAI
* Leverage invoke-training library

**Comment by cfragkos** [comment]
Which scripts do you plan to use for lora training?

**Comment by Millu** [comment]
@cfragkos there's an Invoke library for training! 

https://github.com/invoke-ai/invoke-training

**Comment by cfragkos** [comment]
@Millu 
Do I access this by using the option 2? (Run textual inversion training?)

**Comment by pryadchenko** [comment]
This script for the LoRA training, not for textual inversion training

**Comment by rfbwhite** [comment]
Any thoughts when making this about adding support to merge lora's as well?

**Comment by hipsterusername** [comment]
This has been released in https://github.com/invoke-ai/invoke-training 

More advanced merging is something on the roadmap for the training repo, but will likely look for contributions there to accelerate it. If anyone is interested in contributing/enhancing merge capabilities, please feel free to ping about contributing!
