### ISSUE TITLE
Linear UI SDXL Support

### ISSUE THREAD

**Issue by Millu** [invoke-ai/InvokeAI#3986]
## Summary

SDXL x.x is currently only supported via a nodes graph. With the release of SDXL 1.0 imminent and the nodes editor being experimental , this will continue to be a major pain point for users who are new to Invoke AI and generative art.

## Intended Outcome
SDXL is able to be used to generate images through the Linear UI.

**Comment by blessedcoolant** [comment]
Almost there. Final touches being applied. SDXL will be usable in TextToImage and ImageToImage on launch. Canvas will be added after.

Reference PR: https://github.com/invoke-ai/InvokeAI/pull/3973
