### ISSUE TITLE
[bug]: "Use All" feature no longer keeps seeds between batches and skips LORAs

### ISSUE THREAD

**Issue by bth117** [invoke-ai/InvokeAI#3991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

3.0.0

### What happened?

I transitioned to 3.0.0 and really appreciate all of the new changes and updates so far. One issue I noticed is the new "use all" behavior. In 2.3.X versions, it was easy to test LORA/prompt tweaks using batch image generation. I'd start by generating 4-8 images and then select the first image in that batch and select the "use all" feature, tweak the prompt/LORA values and re-generate the same batch of images for comparison. In 3.0.0, the "use all" feature does not maintain the same seeds between batches. For example, batch 1 has seeds 100, 200, 300, 400 and after "use all" batch 2 will use 101, 201, 301, 401. It should keep original 100, 200, etc. seeds for each new batch as in the 2.3.x versions. 

Also, "use all" no longer automatically restores LORAs used in the original image. Took me a while to notice this and kept trying to figure out why images were so different. Seems like "use all" only reinstates the prompt, seed, cfg, steps, and sampler. LORAs and LORA settings are ignored.

I hope you can make it behave like 2.3.x versions for next update. I love the "use all" feature and find it really helpful for optimizing/testing various LORAs and prompt tweaks.

Thank you!

**Comment by psychedelicious** [comment]
We will get LoRAs loading from metadata in the near future.

I suspect the seed behavior you noticed is actually a different issue than what you think. If you look at your image outputs, you'll find they do not come out in order - so you may get seed 2 first, then 1, then 3. This is a known issue and we'll be fixing it also in the near future.

If you `use seed` from the first image in the gallery, it may be starting the batch from the second seed in the batch, leading to all of the seeds being offset.

To test this, you can generate 3 images, then inspect their metadata to find the one with the lowest seed value. If you do `use seed` for that one, you should get the same 3 images again, albeit out of order.

**Comment by TheBrinkOfTomorrow** [comment]
> 
> I suspect the seed behavior you noticed is actually a different issue than what you think. If you look at your image outputs, you'll find they do not come out in order - so you may get seed 2 first, then 1, then 3. This is a known issue and we'll be fixing it also in the near future.
> 
I've noticed this behavior too, and it's a problem for my workflow*, as I was using custom python scripts to created custom "grid" images of the generated images, for comparison purposes of different prompt/model/settings runs with same seed...    (I'm currently using v3.0.2post1 )
Is there a bug tracking it?  Any idea when it will be fixed?

(Detail*:  With the old behavior, the images in all the grids matched up between runs (since I renamed the files by creation data, which I do via a bash script, prior to using the python script)))
