### ISSUE TITLE
[bug]: New image output types not being added to Gallery until refresh

### ISSUE THREAD

**Issue by skunkworxdark** [invoke-ai/InvokeAI#3993]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24GB

### What version did you experience this issue on?

3.0.0

### What happened?

@psychedelicious 

I have written a new node the takes image collections and creates grids of images from it.   However when I save the grid images to the gallery '''context.services.images.create''' they don't appear in the gallery until the browser is refreshed.  I originally asked about this on discord in the dev-chat channel but @hipsterusername suggested it might be a broader issue with nodes and not something specific I am doing and I should file a bug report for it here. 

Work on my new node is on discord https://discord.com/channels/1020123559063990373/1133465385182699582 and in github https://github.com/skunkworxdark/InvokeAI/tree/ImageGrid. 

### Contact Details

skunkworxdark

**Comment by hipsterusername** [comment]
cc: @Millu

**Comment by hipsterusername** [comment]
Let's go ahead and track this as part of #3978 - as it's not really a bug, and more just the nature of non-"image" outputs. We can figure out how we want to allow certain nodes the ability to update the gallery (or standardize that process) as part of our node work.
