### ISSUE TITLE
[enhancement]: Add to Galley option for nodes that have image outputs

### ISSUE THREAD

**Issue by Millu** [invoke-ai/InvokeAI#3994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Summary: 

Any node that outputs an ImageOutput causes the output image to be added to the gallery. 

For example, rescaling an input image before passing it on to the rest of the graph causes the resized input to be added to the gallery.

This should only happen if a user has explicitly included that. 

## Intended Outcome
`add_to_gallery` boolean in the ImageOutput class. A node classes can then either hardcode True or False or pass it off as an input option on the node for a user to decide what the behavior should be

**Comment by psychedelicious** [comment]
The node editor has the support code for this. Every node has an `is_intermediate` boolean field. If an image-outputting node has that set to false, when that node finishes execution, it will be added to the gallery.

Currently, in the node editor, all nodes default to `false` for `is_intermediate`, and this field hidden.

--

To enable this functionality, remove `is_intermediate` from `RESERVED_FIELD_NAMES` in `invokeai/frontend/web/src/features/nodes/util/parseSchema.ts`.

All nodes will now show a toggle UI component that controls that node's `is_intermediate` field.

---

The intention was to present this particular field in a separate area in each node's UI - like inside a little settings popover. 

Happy for any contributor to either just make the simple change above, or implement a settings popover to hold that option, with the caveat that it may not survive the upcoming node editor refactor.
