### ISSUE TITLE
[bug]: After using the web UI, then logging out/in, browser extension corruption. 

### ISSUE THREAD

**Issue by Creare-d-arte** [invoke-ai/InvokeAI#4002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

3.0.0

### What happened?

Every time I use the web UI, 
log out, 
then log back in again, 
my browser extensions get corrupted.

**Comment by Millu** [comment]
What browser are you using? Also, what do you mean by corrupted?

**Comment by Creare-d-arte** [comment]
> What browser are you using? Also, what do you mean by corrupted?

Chrome

When I open the browser after login, the extensions are gone from the hotbar...

In the chrome extensions tab, it states under each extension that the "extension is corrupted"; with a repair & remove button adjacent.

Repairing the extension fails and removes the extension.

Attempting to reinstall also fails.

A login out/in is required to reinstall the extensions after.

**Comment by Creare-d-arte** [comment]
My guess, is that some setup process when the web UI is launched causes this.

**Comment by psychedelicious** [comment]
Sorry to hear your browser has some issues with the extensions.

The web UI is just a website - it doesn't have access to your browser or extensions any more than any other website. When you launch it, you are just opening a website.

Generally speaking, websites cannot break your browser extensions.

Can you provide steps to reproduce the issue?
