### ISSUE TITLE
[bug]: LORA weight range incompatible with many LORAs

### ISSUE THREAD

**Issue by bth117** [invoke-ai/InvokeAI#4008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

3.0.0

### What happened?

Hello,

Many LORAs on CivitAI, especially "slider" LORAs like age/saturation/detailers are created with LORA weight ranges beyond that allowed in 3.0.0. For example, the Zoom Slider LORA [https://civitai.com/models/114460/zoom-slider-lora](url) is created to use weights -7 to +7. Current 3.0.0 only allows -1 to +2. 

Thanks again!

### Additional context

I chose this as a bug because it breaks useability with around a dozen common LORAs. It might be a feature request but I'll let admin decide.

**Comment by Millu** [comment]
Thanks for sharing this! I've created a feature enhancement ticket for it here: #4022
