### ISSUE TITLE
[enhancement]: Hi-Res Fix

### ISSUE THREAD

**Issue by lukas-frml** [invoke-ai/InvokeAI#4014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Will the Hi-Res Fix feature return to InvokeAI 3.* ? Can't find it in 3.0 and used the feature a lot in the 2.* versions. It might be possible to implement that through the notes feature but it would be really nice to simply get the toggle back for the txt2img tab if possible.

**Comment by Millu** [comment]
Currently, this is only planned to be available through nodes - there's some example HRO graphs being shared in the Discord. 

Here's an example one you can try: https://discord.com/channels/1020123559063990373/1130642855342395452/1132821533539180615
