### ISSUE TITLE
Send generated images to selected board by default

### ISSUE THREAD

**Issue by Millu** [invoke-ai/InvokeAI#4018]
## Summary

Currently images that are generated are sent to the board that is designated as the auto-add destination. However, this can be confusing when a user has multiple boards they are using during a session. 

## Intended Outcome

Users are able to choose a setting: 
1. Images generated are sent to the board that is selected upon pressing "Invoke" (this should be the default)
2. Auto-add board remains constant

The first option would allow images to be sent to the currently selected board after generation
The second option would have images be sent to the board that is chosen as the auto-add board

**Comment by KevinBrack** [comment]
I would like to work on this issue.

**Comment by Millu** [comment]
That's great @KevinBrack! Feel free to jump right in - if you have any questions you can reach out to me on Discord (@imic) or in the [#dev-chat channel](https://discord.com/channels/1020123559063990373/1049495067846524939)

**Comment by psychedelicious** [comment]
To add a bit of context, option #1 ("lock in" the auto-add board when the invoke button is clicked) was how it worked initially, as implemented by @maryhipp . I changed the behavior to use a separate piece of state that the user controlled, and you could change it mid-generation.

@maryhipp 's implementation worked by adding a `board_id` property to the invoke redux actions, and using that when handling `socketInvocationComplete` to figure out which board to add the image to.

Feel free to ping me if you have any technical questions, here or on discord.
