### ISSUE TITLE
[enhancement]: LoRA weight range should be larger to accommodate more LoRAs

### ISSUE THREAD

**Issue by Millu** [invoke-ai/InvokeAI#4022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Summary

Many LORAs on CivitAI, especially "slider" LORAs like age/saturation/detailers are created with LORA weight ranges beyond that allowed in 3.0.0. 

For example, the Zoom Slider LORA [https://civitai.com/models/114460/zoom-slider-lora](https://github.com/invoke-ai/InvokeAI/issues/url) is created to use weights -7 to +7. Current 3.0.0 only allows -1 to +2.

## Intended Outcome

The LoRA weight takes into account the weight range a LoRA is created to use.

**Comment by hipsterusername** [comment]
Just for anyone looking at this - The number field _should_ be able to go above the capped 2.0. Sliders will likely not be able to adjust until LoRA metadata exists

**Comment by jaretburkett** [comment]
I make a lot of these (including the one listed in the example). I have a codebase for generating them as well that I know others are using. I am planning on adding metadata to them for maximum ranges. Does invoke looks for specific tags in it currently?

**Comment by hipsterusername** [comment]
We're actively discussing this now as we're writing the official Invoke LoRA training script/repo - @RyanJDick can share his latest thoughts on LoRA Metadata

**Comment by RyanJDick** [comment]
> I make a lot of these (including the one listed in the example). I have a codebase for generating them as well that I know others are using. I am planning on adding metadata to them for maximum ranges. Does invoke looks for specific tags in it currently?

As we build out the Invoke LoRA training repo, I expect that we will define and document a set of metadata tags that are officially supported by Invoke AI. The expected LoRA weight range sounds like it would make sense as an optional tag. We still need to work this out a little more, but I'll loop back once we have basic LoRA metadata support.

**Comment by jaretburkett** [comment]
If you guys want any help with your LoRA training system, let me know, I am more than happy to provide some assistance if needed

**Comment by hipsterusername** [comment]
You're welcome to contribute - There's not a formal contributor doc yet, but you'll find the repo here. 

https://github.com/invoke-ai/invoke-training

This is early days, and the GUI has not yet been built for it, but the intent is for this, like Invoke, to serve as an accessible way for people to get started.

**Comment by Millu** [comment]
@jaretburkett development is in full swing on the Invoke Training repo if you're still interested and would like to give it a test run!

**Comment by hipsterusername** [comment]
Feel free to propose a different cap!
