### ISSUE TITLE
[enhancement]: Update Documentation and installer to download SDXL 1.0 instead of 0.9

### ISSUE THREAD

**Issue by strouder** [invoke-ai/InvokeAI#4027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Instead of having 0.9 SDXL can we change it to 1.0 so we can update SDXL?

![image](https://github.com/invoke-ai/InvokeAI/assets/21327400/7415fd5d-a7bb-4351-a115-3fde01b53f90)

Also please update documentation on how to isntall SDXL 1.0

**Comment by coder543** [comment]
@strouder I'm fairly sure you downloaded 3.0.0, not the 3.0.1 (release candidate), since 3.0.1 does offer SDXL 1.0. (I downloaded it for the first time yesterday.)
