### ISSUE TITLE
[bug]: segmentation fault on AMD GPU (6600XT)

### ISSUE THREAD

**Issue by LoGiCa7** [invoke-ai/InvokeAI#4035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

amd

### VRAM

8GB

### What version did you experience this issue on?

3.0.0

### What happened?

I have tried version 3.0.0 and v3.0.1 Release Candidate 2.

I get the error ./invoke.sh: line 51: 36253 Segmentation fault      (core dumped) invokeai-web $PARAMS when trying to generate an image. I have Rocm 5.6 installed on my 6600XT.

Generate images with a browser-based interface
/home/sd/invokeai/.venv/lib/python3.10/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
[2023-07-27 18:06:32,690]::[InvokeAI]::INFO --> Patchmatch initialized
INFO:     Started server process [36253]
INFO:     Waiting for application startup.
[2023-07-27 18:06:33,047]::[InvokeAI]::INFO --> InvokeAI version 3.0.1rc2
[2023-07-27 18:06:33,047]::[InvokeAI]::INFO --> Root directory = /home/sd/invokeai
[2023-07-27 18:06:33,048]::[InvokeAI]::INFO --> GPU device = cuda AMD Radeon RX 6600 XT
[2023-07-27 18:06:33,050]::[InvokeAI]::INFO --> Scanning /home/sd/invokeai/models for new models
[2023-07-27 18:06:33,244]::[InvokeAI]::INFO --> Scanned 5 files and directories, imported 0 models
[2023-07-27 18:06:33,245]::[InvokeAI]::INFO --> Model manager service initialized
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:9090 (Press CTRL+C to quit)
INFO:     127.0.0.1:50288 - "GET /socket.io/?EIO=4&transport=polling&t=OcOKHM5 HTTP/1.1" 200 OK
INFO:     127.0.0.1:50288 - "POST /socket.io/?EIO=4&transport=polling&t=OcOKHMB&sid=KzafQo0oyxHCZipkAAAA HTTP/1.1" 200 OK
INFO:     ('127.0.0.1', 50304) - "WebSocket /socket.io/?EIO=4&transport=websocket&sid=KzafQo0oyxHCZipkAAAA" [accepted]
INFO:     connection open
INFO:     127.0.0.1:50290 - "GET /socket.io/?EIO=4&transport=polling&t=OcOKHMC&sid=KzafQo0oyxHCZipkAAAA HTTP/1.1" 200 OK
INFO:     127.0.0.1:50288 - "GET /socket.io/?EIO=4&transport=polling&t=OcOKHMJ&sid=KzafQo0oyxHCZipkAAAA HTTP/1.1" 200 OK
INFO:     127.0.0.1:50288 - "POST /socket.io/?EIO=4&transport=polling&t=OcOKHMN&sid=KzafQo0oyxHCZipkAAAA HTTP/1.1" 200 OK
INFO:     127.0.0.1:50288 - "GET /socket.io/?EIO=4&transport=polling&t=OcOKHMl&sid=KzafQo0oyxHCZipkAAAA HTTP/1.1" 200 OK
INFO:     127.0.0.1:50288 - "GET /socket.io/?EIO=4&transport=polling&t=OcOKHYf HTTP/1.1" 200 OK
INFO:     127.0.0.1:50288 - "POST /socket.io/?EIO=4&transport=polling&t=OcOKHYl&sid=zf24e1QzxwqNpt1GAAAC HTTP/1.1" 200 OK
INFO:     127.0.0.1:50288 - "GET /socket.io/?EIO=4&transport=polling&t=OcOKHYm&sid=zf24e1QzxwqNpt1GAAAC HTTP/1.1" 200 OK
INFO:     ('127.0.0.1', 50306) - "WebSocket /socket.io/?EIO=4&transport=websocket&sid=zf24e1QzxwqNpt1GAAAC" [accepted]
INFO:     connection open
INFO:     127.0.0.1:50288 - "GET /socket.io/?EIO=4&transport=polling&t=OcOKHYr&sid=zf24e1QzxwqNpt1GAAAC HTTP/1.1" 200 OK
INFO:     127.0.0.1:50288 - "POST /socket.io/?EIO=4&transport=polling&t=OcOKHZ8&sid=zf24e1QzxwqNpt1GAAAC HTTP/1.1" 200 OK
INFO:     127.0.0.1:50288 - "GET /socket.io/?EIO=4&transport=polling&t=OcOKHa0&sid=zf24e1QzxwqNpt1GAAAC HTTP/1.1" 200 OK
INFO:     127.0.0.1:50290 - "GET /api/v1/models/?base_models=sd-1&base_models=sd-2&base_models=sdxl&model_type=main HTTP/1.1" 200 OK
INFO:     127.0.0.1:50288 - "GET /api/v1/models/?model_type=controlnet HTTP/1.1" 200 OK
INFO:     127.0.0.1:50290 - "GET /api/v1/app/version HTTP/1.1" 200 OK
INFO:     127.0.0.1:50312 - "GET /api/v1/models/?model_type=lora HTTP/1.1" 200 OK
INFO:     127.0.0.1:50324 - "GET /api/v1/models/?model_type=vae HTTP/1.1" 200 OK
INFO:     127.0.0.1:50338 - "GET /api/v1/models/?model_type=embedding HTTP/1.1" 200 OK
[2023-07-27 18:06:40,323]::[InvokeAI]::INFO --> NSFW checker initialized
INFO:     127.0.0.1:50340 - "GET /api/v1/app/config HTTP/1.1" 200 OK
INFO:     127.0.0.1:35112 - "GET / HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:35112 - "GET /assets/index-5a784cdd.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:35118 - "GET /assets/MantineProvider-ea42d3d1.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:35112 - "GET /assets/ThemeLocaleProvider-13e3db3d.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:35130 - "GET /assets/ThemeLocaleProvider-5b992bc7.css HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:35130 - "GET /assets/logo-13003d72.png HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:35130 - "GET /locales/en.json HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:35130 - "GET /assets/App-58b095d3.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:35130 - "GET /assets/App-6125620a.css HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:35130 - "GET /assets/inter-latin-wght-normal-450f3ba4.woff2 HTTP/1.1" 200 OK
INFO:     127.0.0.1:35130 - "GET /socket.io/?EIO=4&transport=polling&t=OcOKJt3 HTTP/1.1" 200 OK
INFO:     127.0.0.1:35130 - "GET /api/v1/app/version HTTP/1.1" 200 OK
INFO:     127.0.0.1:35112 - "GET /api/v1/app/config HTTP/1.1" 200 OK
INFO:     127.0.0.1:35130 - "GET /api/v1/models/?base_models=sd-1&base_models=sd-2&base_models=sdxl&model_type=main HTTP/1.1" 200 OK
INFO:     127.0.0.1:35136 - "GET /api/v1/models/?model_type=embedding HTTP/1.1" 200 OK
INFO:     127.0.0.1:35112 - "POST /socket.io/?EIO=4&transport=polling&t=OcOKJtv&sid=9Sfizw4FXTmjVZa_AAAE HTTP/1.1" 200 OK
INFO:     127.0.0.1:35152 - "GET /api/v1/models/?model_type=vae HTTP/1.1" 200 OK
INFO:     127.0.0.1:35158 - "GET /api/v1/models/?model_type=controlnet HTTP/1.1" 200 OK
INFO:     127.0.0.1:35164 - "GET /api/v1/models/?model_type=lora HTTP/1.1" 200 OK
INFO:     127.0.0.1:35136 - "GET /api/v1/boards/?all=true HTTP/1.1" 200 OK
INFO:     127.0.0.1:35130 - "GET /socket.io/?EIO=4&transport=polling&t=OcOKJtv.0&sid=9Sfizw4FXTmjVZa_AAAE HTTP/1.1" 200 OK
INFO:     127.0.0.1:35152 - "GET /api/v1/images/?board_id=none&categories=general&is_intermediate=false&limit=0&offset=0 HTTP/1.1" 200 OK
INFO:     127.0.0.1:35158 - "GET /api/v1/images/?board_id=none&categories=control&categories=mask&categories=user&categories=other&is_intermediate=false&limit=0&offset=0 HTTP/1.1" 200 OK
INFO:     127.0.0.1:35164 - "GET /api/v1/images/?board_id=none&categories=general&is_intermediate=false&limit=100&offset=0 HTTP/1.1" 200 OK
INFO:     ('127.0.0.1', 35172) - "WebSocket /socket.io/?EIO=4&transport=websocket&sid=9Sfizw4FXTmjVZa_AAAE" [accepted]
INFO:     connection open
INFO:     127.0.0.1:35130 - "GET /socket.io/?EIO=4&transport=polling&t=OcOKJug&sid=9Sfizw4FXTmjVZa_AAAE HTTP/1.1" 200 OK
INFO:     127.0.0.1:35130 - "POST /socket.io/?EIO=4&transport=polling&t=OcOKJuj&sid=9Sfizw4FXTmjVZa_AAAE HTTP/1.1" 200 OK
INFO:     127.0.0.1:35158 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:35130 - "GET /socket.io/?EIO=4&transport=polling&t=OcOKJu-&sid=9Sfizw4FXTmjVZa_AAAE HTTP/1.1" 200 OK
INFO:     127.0.0.1:35158 - "POST /api/v1/sessions/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:35158 - "PUT /api/v1/sessions/f2fec1de-f2ed-4f9d-a4ec-863ce5250b59/invoke?all=true HTTP/1.1" 202 Accepted
[2023-07-27 18:06:52,150]::[InvokeAI]::INFO --> Loading model /home/sd/invokeai/models/sd-1/main/stable-diffusion-v1-5, type sd-1:main:tokenizer
[2023-07-27 18:06:52,389]::[InvokeAI]::INFO --> Loading model /home/sd/invokeai/models/sd-1/main/stable-diffusion-v1-5, type sd-1:main:text_encoder
./invoke.sh: line 51: 36253 Segmentation fault      (core dumped) invokeai-web $PARAMS

**Comment by seiqin** [comment]
Got the same problem, I have 6600xt as well

**Comment by tbauknight** [comment]
I'm having the same issue - same GPU, same VRAM size - all the way up through 3.0.1rc3. Seems like I had this problem with an earlier version and I just chalked it up to not doing one of the several things that I have to do to make it work. One thing that did happen was that Manjaro updated ROCM to 5.6.0 and I have an environment variable set as follows:

export ROCBLAS_TENSILE_LIBPATH=/opt/rocm/lib/rocblas/library/  

So that it can find a file (TensileLibrary.dat) that was missing from the install.

I don't know exactly how to obtain the dump you experts need to see why I'm dumping core, but it happens just at the moment that the image starts to be generated. Also happens in invokeai-ti at the moment of truth. Assuming the Manjaro update hosed something I was depending on the system version for. Just adding my $0.02.

**Comment by Benn1x** [comment]
Same on the 7900XT with ROcm 5.4.2 and 5.6.0

**Comment by arvenig** [comment]
Was experiencing this issue on my Ryzen 7950X / Radeon 6900XT desktop system running Arch Linux. I seem to have worked around it by disabling the 7950X's iGPU in BIOS. The GPU device reported by invokeai-web at startup both with and without the iGPU enabled is 'cuda AMD Radeon RX 6900 XT', but for whatever reason having the iGPU enabled seems to have been causing an issue. This issue has been present for me in all versions of invoke since the update to torch 2.0. Tested on a fresh InvokeAI 3.0.1post3 install.

**Comment by kontiko** [comment]
For me starting it with the command <HSA_OVERRIDE_GFX_VERSION=10.3.0 invokeai-web> fixed it

**Comment by LoGiCa7** [comment]
> For me starting it with the command <HSA_OVERRIDE_GFX_VERSION=10.3.0 invokeai-web> fixed it

That worked, thanks for sharing that :) I'm guessing it's a compatibility issue with rocm and some AMD GPU's rather than InvokeAI. Closing as resolved.

**Comment by aaashuai** [comment]
> For me starting it with the command <HSA_OVERRIDE_GFX_VERSION=10.3.0 invokeai-web> fixed it

It works for me, thanks.
