### ISSUE TITLE
[bug]: ERROR: Could not find a version that satisfies the requirement mediapipe (from invokeai) (from versions: none) ERROR: No matching distribution found for mediapipe

### ISSUE THREAD

**Issue by SamohtSirrom1** [invoke-ai/InvokeAI#4038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cpu

### What version did you experience this issue on?

3.0 and 3.0.1

### What happened?

I tried installing the program got to the part where it is initializing the invokeai application then got a message saying 
ERROR: Could not find a version that satisfies the requirement mediapipe (from invokeai) (from versions: none)
ERROR: No matching distribution found for mediapipe. After that the log goes on and gives me other errors in lines 50, 179, 235, 311, 145, 113, 252, 215, 299, 17, 27 (in that order) I expected installation to complete and to be able to use the program
![Screenshot_20230727-161821](https://github.com/invoke-ai/InvokeAI/assets/133946432/6bf4a0d0-099a-4673-a3b2-867abdd54558)

### Screenshots

![Screenshot_20230727-161821](https://github.com/invoke-ai/InvokeAI/assets/133946432/99ccc74d-48ea-488b-bdac-1b3b1cde6c49)

### Additional context

So far it happens EVERY single time I've tried to install it though 2.3.5.post2 worked fine

### Contact Details

samoht.eilsel.sirrom@gmail.com

**Comment by lstein** [comment]
Can you provide the following information:
1. Which Linux distribution (e.g. Ubuntu 22.04)
2. Output of `uname -a`
3. Output of `python -V`

**Comment by ebr** [comment]
@SamohtSirrom1 is there a reason you are installing invoke as a root user?

**Comment by SamohtSirrom1** [comment]
The first time I ever got it working it was under this same conditions.
