### ISSUE TITLE
[bug]: If number of images > 1, generated images are not saved to the gallery

### ISSUE THREAD

**Issue by apurtell** [invoke-ai/InvokeAI#4042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

amd

### VRAM

32GB

### What version did you experience this issue on?

3.0.1rc3

### What happened?

Using SDXL 1.0 and the web interface. For both txt2img and img2img if the number of images in the 'General' tab is greater than 1, the image is not saved to the gallery after generation. After sampling completes the Invoke button's progress indicator switches to the scanning behavior (this is VAE invocation?) and then immediately we jump to the start of a new image generation and nothing appears in the gallery. No PNG file is written anywhere under output/. This doesn't always reproduce with txt2img but always happens for me for img2img.

**Comment by apurtell** [comment]
GPU should be "mps" of course, not sure what happened there.

**Comment by psychedelicious** [comment]
Thanks for the report. If I understand the issue correctly, this is a duplicate of #3932.

I expect the images to appear in the gallery only at the very end of processing. Please set images to 2 and let it finish to confirm.

**Comment by apurtell** [comment]
> Please set images to 2 and let it finish to confirm.

Got it. The images did appear when the batch completed.

**Comment by caleidoscopio** [comment]
Absolute dealbreaker. I need to be able to see the images as they're being generated, so I can cancel it and not waste time.
