### ISSUE TITLE
[bug]: invokeai installs to the wrong directory

### ISSUE THREAD

**Issue by Kayliii** [invoke-ai/InvokeAI#4046]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

3.0.0

### What happened?

This bug happened during manual installation. I set the `INVOKEAI_ROOT` variable as described in the instructions:

```ps
Set-Variable -Name INVOKEAI_ROOT -Value D:/invokeai
```

After this I successfully installed invokeAI. I also made sure to point the autoimport and output folders to `D;/invokeai` during the configuration step.

InvokeAI did not install to `INVOKEAI_ROOT`. It installed to `%systemdrive%%homepath%/invokeai` instead. To be sure, I ran `$INVOKEAI_ROOT` to see whether its value had changed, but it still displayed `D:/invokeai` just as before.

No folders or files had been created in `INVOKEAI_ROOT`. No autoimport, no output, nothing. The only thing that was there was the `.venv` folder that I previously created to create the python environment.

This is a big problem. I happen to have enough room on my main drive for something like InvokeAI, but that wasn't the case not too long ago, in which case I would have been unable to install it at all.

### Additional context

The installed program does point to the correct location (e.g. the `invokeai.yaml` file does indeed refer to `INVOKEAI_ROOT` and not to `%systemdrive%%homepath%/invokeai`), but is just installed in the wrong place.

**Comment by Aenon1** [comment]
During the installation it asks you:
InvokeAI will be installed in C:\Users\{your name}\invokeai
Would you like to pick a different location? [y/n] (n):
You have to enter Y and then enter the location that you want it to install to.

**Comment by lstein** [comment]
INVOKEAI_ROOT is not respected by the installer. This is a bug.

**Comment by lstein** [comment]
Fixed in PR 4070.
