### ISSUE TITLE
[enhancement]: Select Board before image generation

### ISSUE THREAD

**Issue by Kingpin2557** [invoke-ai/InvokeAI#4047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Kingpin2557

### What should this feature add?

I would like to be able to select a board before I start generating an image, this way the image will automatically be imported in the correct board. for example in the node editor there could be a node where you select a board where the generated image will be imported in. for text2img, img2img and canvas this could be a new settings tab underneath the Invoke button. @psychedelicious 

### Alternatives

I also would like a option for the node editor where I can select the amount of images I can generate, rn I can only do one at a time

**Comment by bruno-c** [comment]
![image](https://github.com/invoke-ai/InvokeAI/assets/50042/2f8c99a4-7e3c-4a67-8c5a-4f1a97496538)

The "Auto-add board" setting does what you ask I believe.

**Comment by Kingpin2557** [comment]
I am aware of this, but for mostly the node editor it would be  nicer to have a node where you can select your board.

**Comment by mickr777** [comment]
for your multiple images you can setup this in nodes and connect to seed, the size is how many images you want to make

![Screenshot_20230729_081356_Chrome](https://github.com/invoke-ai/InvokeAI/assets/115216705/1ce4cbcc-60c0-4279-80ca-270fc10ba469)

**Comment by Kingpin2557** [comment]
hey, where would the IterateInvovationOutput go into?

**Comment by Millu** [comment]
There's a PR open that might address your need: https://github.com/invoke-ai/InvokeAI/pull/4086
