### ISSUE TITLE
[bug]: Error caught was: No module named 'triton'

### ISSUE THREAD

**Issue by tinyvan** [invoke-ai/InvokeAI#4055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6

### What version did you experience this issue on?

3.0.0

### What happened?

A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'

### Additional context

I downloaded a version(in https://huggingface.co/r4ziel/xformers_pre_built/blob/main/triton-2.0.0-cp310-cp310-win_amd64.whl) that might work online and installed it using pip in the developer console, but it doesn’t seem to work.

**Comment by hipsterusername** [comment]
Thanks for the report!

This isn't a bug :)

Windows doesn't support Triton, and this is just a warning about that.
