### ISSUE TITLE
[bug]: Settings reset on each launch or page refresh

### ISSUE THREAD

**Issue by mcbexx** [invoke-ai/InvokeAI#4064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8

### What version did you experience this issue on?

3.0.1

### What happened?

**Anytime** I launch 3.0.1 or refresh the UI page, **all** settings are reset to default.
It's a fresh install from scratch into a separate directory from 2.5.3p2, both installations are on the same drive and not the default installation location.

Any idea what could be causing this?
I assume it's not a common issue, since searching for "settings" or "reset" seems to not yield any results.

**Comment by psychedelicious** [comment]
The settings are stored in the browser's LocalStorage. This is similar to the browser cache but a bit deeper. I suspect the old version's stored data has filled up the allocated space and the new version isn't able to store its data.

You can reset this by going to the app settings and clicking Reset Web UI. This will delete all browser settings for both versions, but I think it's going to be necessary for this issue. It won't delete any images.

Does that solve the issue?

**Comment by mcbexx** [comment]
Looks like this solved it, thanks, although I am fairly certain I used localStorage.clear() in the browser console before in order to try to solve the issue.

Does that mean that the stored data of 2.5.3 and 3.0.1 are conflicting and it's not recommended to alternate between both versions as that would be likely recreate the issue?

**Comment by psychedelicious** [comment]
No, the settings do not conflict, but it's possible to use up the available space. v2 used a lot more than v3. 

Glad it's working for you now!
