### ISSUE TITLE
[bug]: Invoke opens to blank page (Resolved)

### ISSUE THREAD

**Issue by joehanner** [invoke-ai/InvokeAI#4075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

33.0.1

### What happened?

Steps to reproduce:

- Clean install of 3.0.1
- Custom install directory: E:\
- Chrome Version 115.0.5790.110 (Official Build) (64-bit)
- Launched Web UI - Blank.
- Reinstalled Web UI - same 
- Ran Automated fix - same
- Lots of googling...
- Found: https://stackoverflow.com/questions/23977690/setting-the-value-of-dataurl-exceeded-the-quota
- Ran command in _Chrome_ console:
- `localStorage.clear();`

**Issue Resolved**

_Screenshot of Windows Console below (Fixed and could not recreate Chrome Console error output)_
_Not necessarily a bug, but posting here for Dev's & community awareness._

### Screenshots

![image](https://github.com/invoke-ai/InvokeAI/assets/10224228/94ce1968-f2a4-42e7-9f94-c35bd90e1ccb)

### Additional context

Issue resolved

### Contact Details

discord: joehanner

**Comment by Millu** [comment]
Going to go ahead and close this as it's been resolved. Appreciate you calling it!
