### ISSUE TITLE
[bug]: Dependencies in `pyproject.toml` have module conflicts.

### ISSUE THREAD

**Issue by unsatisfying** [invoke-ai/InvokeAI#4078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

amd

### VRAM

8GB

### What version did you experience this issue on?

main

### What happened?

There are multiple dependencies mentioned in the `requirements.txt` file(the  -> means the indirect dependencies): 
```
opencv-python
mediapipe->opencv-contrib-python
albumentations->opencv-python-headless
basicsr->opencv-python
gfpgan->opencv-python
realesrgan->opencv-python
albumentations->qudida->opencv-python-headless

```

The official [spec](https://pypi.org/project/opencv-contrib-python/)  mentioned that the `opencv-python` package is for the desktop environment, while `opencv-python-headless` is for the server environment. The documentation also states that these packages (opencv-python,  opencv-contrib-python, opencv-python-headless) cannot be installed simultaneously (the exact wording is: “There are four different packages (see options 1, 2, 3, and 4 below) and you should SELECT ONLY ONE OF THEM.”). This is because they both use the same module name cv2.

During the installation process using pip, the package installed later will override the cv2 module from the previously installed package (specifically, the modules within the cv2 folders that exist in both packages). Furthermore, the dependency graph even includes different versions of these two packages. It is certain that the common files with the same path in these two packages contain different contents. Therefore, there may be functional implications when using them. However, without analyzing the specific code and function call hierarchy of this project, it can be stated that issues related to overwriting and module conflicts do exist. 

## Steps to Reproduce
`pip install InvokeAI`

## Desired Change
Indeed, it is not an ideal behavior for modules to be overwritten, even if they are not actively used or if the overwritten module is the one being called. It introduces uncertainty and can cause issues in the long run, especially if there are changes or updates to the overwritten modules in future development. It is generally recommended to avoid such conflicts and ensure that only the necessary and compatible dependencies are declared in the requirements to maintain a stable and predictable environment for the project. 

We believe that **although this project can only modify direct dependencies and indirect dependencies are a black box**, it is possible to add additional explanations rather than directly declaring both conflicting packages in the requirements.txt file. Or maybe you can check the dependencies and remove the redundant dependencies from the requirements.txt.

Adding extra explanations or documentation about the potential conflicts and the need to choose only one of the conflicting packages can help developers understand the issue and make informed decisions. Including a clear instruction or warning in the project’s documentation can guide users to choose the appropriate package based on their specific requirements.

**Comment by Millu** [comment]
@lstein some notes about dependency webs ^

**Comment by lstein** [comment]
There is no longer a `requirements.txt` file. Do you mean `pyproject.toml`?

**Comment by unsatisfying** [comment]
> `realesrgan`



> There is no longer a `requirements.txt` file. Do you mean `pyproject.toml`?
> 
> I'm not sure what to do about this, because some of the conflicts are out of our control. For example:
> 
> ```
> realesrgan->opencv-python
> albumentations->qudida->opencv-python-headless
> ```
> 
> We need both `realesrgan` and `albumentations`, but they're going to fight over opencv.
> 
> Suggestions to fix?

Thank you for your response. I mean in `pyproject.toml` and it's my fault. The conflict in the indirect dependency is really annoying, maybe you can fix it by uninstalling all four opencv related packages after installing the dependency and reinstalling one version of them. Of course, it's possible to leave it alone, since at least no related errors have been reported yet. But it's not a permanent solution, since other projects have encountered cases where the cv2.imshow() function doesn't work properly. Or you can follow the [spec](https://albumentations.ai/docs/getting_started/installation/#note-on-opencv-dependencies) that uses the `--no-binary` option.

**Comment by unsatisfying** [comment]
> Our dependencies have changed substantially since this issue was raised. I don't believe it is a problem now.

I don't think it's fixed. I tried to pip install it using the command `pip install "InvokeAI[xformers]" --use-pep517 --extra-index-url https://download.pytorch.org/whl/cu121
`
and it still downloaded and installed them at the same time.

![image](https://github.com/invoke-ai/InvokeAI/assets/19465692/b568db42-1263-4022-9e6b-78fb90a872d4)

**Comment by psychedelicious** [comment]
Sorry, I misunderstood the issue. Yes, it's still a problem, but I'm not sure if it has any functional impact, given the application should be run in its own venv and it hasn't caused problems for us.

To add a bit of detail, here is a representation of the dependency graph for the 3x opencv packages:

```
❯ pipdeptree -r -p opencv-python
opencv-python==4.9.0.80
├── controlnet_aux==0.0.7 [requires: opencv-python]
│ └── InvokeAI==4.0.1 [requires: controlnet_aux==0.0.7]
├── facexlib==0.3.0 [requires: opencv-python]
│ └── InvokeAI==4.0.1 [requires: facexlib]
├── invisible-watermark==0.2.0 [requires: opencv-python >=4.1.0.25]
│ └── InvokeAI==4.0.1 [requires: invisible-watermark==0.2.0]
└── InvokeAI==4.0.1 [requires: opencv-python==4.9.0.80]

❯ pipdeptree -r -p opencv-python-headless
opencv-python-headless==4.9.0.80
└── albumentations==1.4.3 [requires: opencv-python-headless >=4.9.0]
└── InvokeAI==4.0.1 [requires: albumentations]

❯ pipdeptree -r -p opencv-contrib-python
opencv-contrib-python==4.9.0.80
└── mediapipe==0.10.7 [requires: opencv-contrib-python]
└── InvokeAI==4.0.1 [requires: mediapipe==0.10.7]
```

I understand this could cause problems for users who have customized opencv installations but I don't think there's any way to really resolve the transitive dependency conflicts without making upstream changes.

In the end, invoke is a standalone application and if the conflicts don't cause functional issues for the us, there is fortunately no need to take action here.

**Comment by unsatisfying** [comment]
> Sorry, I misunderstood the issue. Yes, it's still a problem, but I'm not sure if it has any functional impact, given the application should be run in its own venv and it hasn't caused problems for us.
> 
> To add a bit of detail, here is a representation of the dependency graph for the 3x opencv packages:
> 
> ```
> ❯ pipdeptree -r -p opencv-python
> opencv-python==4.9.0.80
> ├── controlnet_aux==0.0.7 [requires: opencv-python]
> │ └── InvokeAI==4.0.1 [requires: controlnet_aux==0.0.7]
> ├── facexlib==0.3.0 [requires: opencv-python]
> │ └── InvokeAI==4.0.1 [requires: facexlib]
> ├── invisible-watermark==0.2.0 [requires: opencv-python >=4.1.0.25]
> │ └── InvokeAI==4.0.1 [requires: invisible-watermark==0.2.0]
> └── InvokeAI==4.0.1 [requires: opencv-python==4.9.0.80]
> 
> ❯ pipdeptree -r -p opencv-python-headless
> opencv-python-headless==4.9.0.80
> └── albumentations==1.4.3 [requires: opencv-python-headless >=4.9.0]
> └── InvokeAI==4.0.1 [requires: albumentations]
> 
> ❯ pipdeptree -r -p opencv-contrib-python
> opencv-contrib-python==4.9.0.80
> └── mediapipe==0.10.7 [requires: opencv-contrib-python]
> └── InvokeAI==4.0.1 [requires: mediapipe==0.10.7]
> ```
> 
> I understand this could cause problems for users who have customized opencv installations but I don't think there's any way to really resolve the transitive dependency conflicts without making upstream changes.
> 
> In the end, invoke is a standalone application and if the conflicts don't cause functional issues for the us, there is fortunately no need to take action here.

Yeah, you're right. Thank you for your reply. 
But it may also be because the call chain is particularly deep and there may be some implicit bugs. 
Anyway, we can leave it alone for now since it has not led to problems.

**Comment by psychedelicious** [comment]
No worries. I'm going to close this as a nofix. We can address issues if they arise.
