### ISSUE TITLE
[bug]: SDXL generated images are only black

### ISSUE THREAD

**Issue by jooray** [invoke-ai/InvokeAI#4083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

96GB

### What version did you experience this issue on?

3.0.1post3

### What happened?

When generating images, I see progress with some blunt image as usual, but then the saved image is pure black color.

Using SDXL with refiner on mps backend.

### Screenshots

Generating:

![Screenshot 2023-07-30 at 22 52 01](https://github.com/invoke-ai/InvokeAI/assets/1028688/140fb109-0e05-4460-ba79-6f52aee72abd)

Result:

![Screenshot 2023-07-30 at 22 51 14](https://github.com/invoke-ai/InvokeAI/assets/1028688/54078805-d7c9-47bf-99f0-a3207067d3f2)

**Comment by Vega-KH** [comment]
Since recent update / re-installation, I am also only getting pure black images on Windows.  Just mentioning that this is not a Mac OS issue.

**Comment by Millu** [comment]
@jooray @Vega-KH can you try with fp16 precision?

**Comment by KennethLj** [comment]
I experienced the same also with fp16, I'm on a MacBook Pro M1 16GB RAM

**Comment by jooray** [comment]
Same.

**Comment by psychedelicious** [comment]
With SDXL, if you use the default VAE, you need to select `fp32` for VAE Precision. If you use the custom VAE that has `fp16` in the name, you'll need to instead select `fp16` for VAE Precision. Can you please confirm you have these set correctly?

**Comment by KennethLj** [comment]
Ok, changing to VAE fp32 worked for me, thanks

**Comment by psychedelicious** [comment]
Great thanks for checking @KennethLj . I'll leave this open til we hear back from @jooray and @Vega-KH .

**Comment by jooray** [comment]
Yes, changing to VAE fp32 worked. Maybe a better user interface that would not allow or at least warn that this won't work?

**Comment by metal3d** [comment]
Just to mention that I have the problem with fp16 too. Setting the VAE precision to fp32 worked.
