### ISSUE TITLE
[bug]: FOREIGN KEY constraint failed

### ISSUE THREAD

**Issue by Earthshine17** [invoke-ai/InvokeAI#4088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

16

### What version did you experience this issue on?

3.0.1

### What happened?

I can't upload a file into the image to image or the unified canvas. I get this error "[2023-07-30 21:43:45,244]::[InvokeAI]::ERROR --> Problem saving image record and file: FOREIGN KEY constraint failed"

### Screenshots

![image](https://github.com/invoke-ai/InvokeAI/assets/102000251/04c5e6c7-634d-40b5-afe7-1a8745588927)

### Contact Details

drriotmd@gmail.com

**Comment by psychedelicious** [comment]
Did you install with the installer or are running the app from `main`?

**Comment by psychedelicious** [comment]
I was able to reproduce this and fixed it in #4032

**Comment by Earthshine17** [comment]
> I was able to reproduce this and fixed it in #4032

Thanks! I got it working.

I have my output file on a different drive and was lazy and referenced that same directory (with all old files)...
After created a fresh directory it worked.
