### ISSUE TITLE
[enhancement]: "Add All" option in Model Manager

### ISSUE THREAD

**Issue by Millu** [invoke-ai/InvokeAI#4089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

When using the "Scan For Models" functionality in the model manager, once models are found, each model needs to be added individually. 

For those with many models, this can be very cumbersome and difficult. Adding a "Add All Models" button would help speed this process up and allow users to start using Invoke more quickly. 

<img width="1440" alt="Screenshot 2023-07-31 at 2 57 41 PM" src="https://github.com/invoke-ai/InvokeAI/assets/7254508/b7555a34-b4d3-4853-85f5-95fbc936b152">

**Comment by yash013** [comment]
hello Millu, 
i want to work on this issue my setup is done. 
![ss2](https://github.com/invoke-ai/InvokeAI/assets/75071915/2d9b9c97-6cb0-46cd-8a82-29e91c70f7ca)

**Comment by Millu** [comment]
Hi @yash013! Feel free to assign yourself this - and tackle it. If you need help, you can post in the [#dev-chat](https://discord.com/channels/1020123559063990373/1049495067846524939) channel on Discord! 

Feel free to reach out to me (@imic) on Discord as well

**Comment by yash013** [comment]
i want to join discord. can you give me an invite?

**Comment by psychedelicious** [comment]
This is part of the new MM.

**Comment by yash013** [comment]
which one? can you explain?

**Comment by psychedelicious** [comment]
> which one? can you explain?

The latest version has a fully rewritten model manager backend and UI: https://github.com/invoke-ai/InvokeAI/releases/tag/v4.0.1

**Comment by yash013** [comment]
got it. thanks :)
