### ISSUE TITLE
[bug]: LoRAs are not loading

### ISSUE THREAD

**Issue by DiggyDre** [invoke-ai/InvokeAI#4090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

3.0.1

### What happened?

First off, the HD fix is missing, which is a shame for those who still enjoy using the 1.5 gen stuff. I was told to use the nodes to try to run a HD fix that way... I don't even have a node icon! What in the world did you guys do with this release? The way things used to work was PERFECT! I can't even get the thing to accept one of my LoRA files. I planned on doing some inpainting because Invoke had the best setup for that, but without an HD fix or the ability to load my LoRAs, there is no point. It's not even generating correctly from a few models. 

### Screenshots

![invoke nodes](https://github.com/invoke-ai/InvokeAI/assets/127576526/3f744784-2c60-4fef-8ecd-fba70ac08af8)

**Comment by DiggyDre** [comment]
Okay, I found out that the graphs need to be turned on in settings. Now if I can get a HD fix and have it actually load my LoRAs so that I can do some inpainting, I'll be happy. This release is NOWHERE near as user friendly to use as the past releases.

**Comment by Millu** [comment]
Hey, thank you for the feedback!

What's the issue you're having with your LoRAs?

Regarding the HD/HRO, take a look at [the #share-your-graphs section of the Discord](https://discord.com/channels/1020123559063990373/1130291608097661000) - there's some examples of image upscaling there.

**Comment by DiggyDre** [comment]
> Hey, thank you for the feedback!
> 
> What's the issue you're having with your LoRAs?
> 
> Regarding the HD/HRO, take a look at [the #share-your-graphs section of the Discord](https://discord.com/channels/1020123559063990373/1130291608097661000) - there's some examples of image upscaling there.

Wow! Don't get me wrong, the nodes are very cool as far as offering many different ways to accomplish something... but I'm not about to hook all of that up each time just to run a high res fix when it was just a few sliders and a button in the previous releases. I'll sit out on this release and come back to the software when the HD fix is back.

**Comment by Millu** [comment]
@DiggyDre HRO is back :)
