### ISSUE TITLE
[bug]: Files being sotred in unexpected places

### ISSUE THREAD

**Issue by Void2258** [invoke-ai/InvokeAI#4095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What version did you experience this issue on?

3.0.1post2

### What happened?

A gigantic cache folder from hugging face is appearing, usually in the user directory. It appears everything downloaded using the model installer script is living here permanently and being used by Invoke, rather than in the invoke folder, as deleting the cache deleted the models from invoke even though they appear to still be in the invoke folder (though not sure about control nets; I can;t find those at all). Note this folder is default hidden as well.

This is not easily under control of the user (requires making a windows Env Varible to move), and is causing unexpected drive filling (not easily disagnosable since the folder is hidden). It is also an issue for uninstallation and compartmentalization, as now simply deleting the Invoke folder no longer actually removes everything, and it causes issues with model management as it's unclear where things are located.

### Additional context

Discovered this when my system drive started to throw out of space errors and I couldn't track it down without windirstat.

**Comment by lstein** [comment]
This is an artifact of our using the HuggingFace interface to download their repo_ids. The .cache file can be safely deleted from time to time.

We are working on a new downloading mechanism that does not cause cache files to be stored.

**Comment by Void2258** [comment]
When I deleted this folder, all the things I had downloaded went with it. SDXL, all the control nets... All of them are no longer accessible in invoke after deleting the cache folder. However, there appears to be something in a folder marked SDXL in the models folder in the invoke directory. The controlnets folder is empty, though.

**Comment by Millu** [comment]
Closed by #5694

**Comment by psychedelicious** [comment]
Resolved in v4.0.0
