### ISSUE TITLE
[enhancement]: arrow keys only work in Uncategorized board

### ISSUE THREAD

**Issue by rpfile** [invoke-ai/InvokeAI#4124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

it seems that the keyboard arrow keys and UI L/R buttons to move between images only exist in the Uncategorized board. it would be nice if the arrow keys and LR buttons would work in user-created boards. currently the only way to move between images in a user-created board is to click on the image thumbnail.

not sure if this is a bug but if not, it's a feature request.

**Comment by Millu** [comment]
@psychedelicious Could this be stuck in with https://github.com/invoke-ai/InvokeAI/pull/4032 ?

**Comment by rpfile** [comment]
after playing around with this more, it seems like the arrow keys sometimes work and sometimes don't work. i can't detect a clear pattern, but it seems most prevalent when there are not very many images in a user-created board.
