### ISSUE TITLE
[bug]: model manager doesn't download 16-bit weights

### ISSUE THREAD

**Issue by keturn** [invoke-ai/InvokeAI#4127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

eb642653cb4e45acce0a433cb68815dc62db4f07

### What happened?

invokeai-configure downloaded only 32-bit safetensors, not 16-bit ones, even though the huggingface repo has `.fp16.safetensors` file available and I have precision set to `auto`. (I don't think setting the precision explicitly to `float16` helped either.)

Reproduction plan:
- run `invokeai-configure`
- let it install stable-diffusion-v1-5
- look in `models/sd-1/main/stable-diffusion-v1-5/unet/`, see it has the 3.4 GB safetensors file, not the 1.7 GB fp16.safetensors file.

**Comment by lstein** [comment]
Thanks for noticing this. The referenced PR should fix it.
