### ISSUE TITLE
[bug]: LoRA rename bug.

### ISSUE THREAD

**Issue by vkushnir** [invoke-ai/InvokeAI#4131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

64GB

### What version did you experience this issue on?

3.0.1post3

### What happened?

Hello.
Problem is:
When you rename LoRA in model manager, it renames the actual LoRA file, removing .safetensor extension. After that, you got error Invalid Model Extension.
If you manually fix file extension it works fine until next rename.

**Comment by Millu** [comment]
Closed by #5522
