### ISSUE TITLE
[bug]: sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by Sniza** [invoke-ai/InvokeAI#4136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

3.0.1 release3

### What happened?

Problem after migration to bigger disk in SDXL. I reinstal SDXL model, but still the same issue

### Screenshots

![Bez názvu](https://github.com/invoke-ai/InvokeAI/assets/135825589/ce4332d1-8fa0-4264-b64e-0037ced977a8)

### Contact Details

quantel@seznam.cz

**Comment by Sniza** [comment]
Just one more thing. SDXL stoped after one picture iteration. SD 1.5 working correct, no issues.

**Comment by psychedelicious** [comment]
Hi,
> Problem after migration to bigger disk in SDXL
Not sure what you mean by this - can you please elaborate a bit?

The error you encountered suggests you may have multiple instances of the application open at once. Can you please restart your computer and try again?

> Just one more thing. SDXL stoped after one picture iteration. SD 1.5 working correct, no issues.
Is this the same issue or different one, from the above error message? If it's different, could you please open a separate issue for it?

**Comment by Sniza** [comment]
Hi, thank you so much for reply. I try complete shutdown comp and make again reinstal SDXL model and now it working fine. Thank you again.

**Comment by psychedelicious** [comment]
No worries, glad you are up and running
