### ISSUE TITLE
feat(nodes): History / undo / redo

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#4137]
- What actions are undo-able?
  - Adding/removing nodes/edges
  - Setting node values
  - Moving nodes - probably use the dragEnd events to capture the final positions in history
-  How do we implement the history?
  - There's a manual implementation in Canvas for undo/redo for reference, though we'd be happy to use a library to manage this.
- After learning lessons with Canvas history and `localStorage`, we probably do not want to persist history across reloads.

**Comment by ymgenesis** [comment]
Requesting the ability to press the delete key to delete an image from the gallery while in the node editor, similar to how the delete key can delete images from the gallery while in the text to image pane.
