### ISSUE TITLE
Node editor: Hotkeys

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#4138]
Desired hotkeys
- [ ] delete
  - Backspace is used currently to delete nodes and edges - delete should also work for both.
- [ ] copy/pase
  - For now, I think copy/paste for a single node is the primary goal. As a stretch goal, copy/paste for multiple nodes (eg when you select multiples) which will need a bit more work to ensure the edges between them are copied correctly.
- [ ] ???

This is probably predicated on a larger rework of the hotkeys implementation. See #3959.

* In the future, once undo/redo is implemented internally, we would add hotkeys for it. See #4137 for details.

**Comment by KevinBrack** [comment]
Hi. can you assign this to me, please.

**Comment by psychedelicious** [comment]
Done, thanks Kevin!

**Comment by Millu** [comment]
Shift + click to select multiple nodes / edges could be a good one as well

**Comment by psychedelicious** [comment]
Done
