### ISSUE TITLE
[bug]: `delete` keypress does not operate on multi-select

### ISSUE THREAD

**Issue by keturn** [invoke-ai/InvokeAI#4143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Browser

Firefox 116 on Linux

### What version did you experience this issue on?

bf94412d1499e48d6bd9dfa415ff7f1aeead6710

### What happened?

Selected a handful of images in the gallery with shift-click.

Pushed the `Delete` key on the keyboard.

The confirmation dialog came up, I confirmed, 

it only deleted **one** item, not the whole selection.

(in contrast with right-click and clicking delete from the context menu. that _does_ work as expected.)

**Comment by ymgenesis** [comment]
Can confirm. When selecting multiple, delete key deletes the last one selected.

**Comment by radry** [comment]
+1 It only deletes the image you clicked last.

**Comment by psychedelicious** [comment]
This was resolved in #6216
