### ISSUE TITLE
[bug]: Mac M1: Cannot Import New SDXL model

### ISSUE THREAD

**Issue by twopiearr** [invoke-ai/InvokeAI#4151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### VRAM

16 gigs total RAM

### What version did you experience this issue on?

3.0.1

### What happened?

When I drop any new SDXL model into /invokeai/models/sdxl/main/ and attempt to launch using option 1, I get an error message like the one shown in the screenshot; since the console clears itself I unfortunately cannot copy/paste. This has happened consistently with 3 different SDXL models downloaded from civitai.com. The default diffusers-based SDXL model works without issue. for reference, the tested models are: 
- https://civitai.com/models/120127/altxl
- https://civitai.com/models/119202/talmendoxl-sdxl-uncensored-full-model
- https://civitai.com/models/112902/dreamshaper-xl10

### Screenshots

![Screenshot 2023-08-03 at 10 46 48 AM](https://github.com/invoke-ai/InvokeAI/assets/86857411/c1401ca4-8dc7-44fe-968b-d7d5d1560306)

### Additional context

Models have been tested in Draw Things and appeared to import and function as expected.

**Comment by Millu** [comment]
Does this same error occur if you add them to the auto-import folder?

**Comment by twopiearr** [comment]
> Does this same error occur if you add them to the auto-import folder?

Yes.

**Comment by twopiearr** [comment]
Still experiencing this issue after hotfix 3.

**Comment by twopiearr** [comment]
Issue appears to be gone in 3.0.2.
