### ISSUE TITLE
Civit model downloads not working as documented

### ISSUE THREAD

**Issue by BrianRosamilia** [invoke-ai/InvokeAI#4152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12

### What version did you experience this issue on?

3.0.1-main

### What happened?

According to this link

https://invoke-ai.github.io/InvokeAI/installation/050_INSTALLING_MODELS/#quick-links

You should be able to run

`invokeai-model-install --add http://civitai.com/2860`

However, I don't believe this will work.  It seems Civit has changed to download links as being a mask to another presigned URL that only lives for 24 hours.  I'm guessing in the past that when a request with no user-agent came in, these would requests would give you the model.  (I actually was not a Civit user before, so this is just my guess)

I think you will have to build more intelligence into this logic here https://github.com/invoke-ai/InvokeAI/blob/bf94412d1499e48d6bd9dfa415ff7f1aeead6710/invokeai/backend/install/model_install_backend.py#L252-L269

To detect and handle Civit (use their API?)

After debugging the code and checking Civit, I'm fairly confident the current code can't download Civit models

### Additional context

The only strange thing is that I am the only one noticing this and Civit is very popular.  I checked Discord too.

**Comment by lstein** [comment]
Yes, Civitai seems to have changed their URLs a bit, so the docs need to be fixed. 

If you go to a model you want on civitai and right click on "Download" to "copy link address". It will give you a download link that works. e.g. invokeai-model-install --add https://civitai.com/api/download/models/128713

I'll fix the documentation - thanks for noticing this.
