### ISSUE TITLE
[bug]: Loras don't work with SDXL

### ISSUE THREAD

**Issue by odragora** [invoke-ai/InvokeAI#4155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

16Gb

### What version did you experience this issue on?

Latest 3.0.1, can't find the exact version anywhere in the app or in the command line tool

### What happened?

When downloading an SDXL Lora and trying to use it in text2img, the Lora reference in the prompt is completely ignored and the result is just a generic image not affected by Lora in any way.

For example, I installed this Lora, copied the prompts and all the settings from the user submitted images, and the result is still just the normal SDXL image.

https://civitai.com/models/120096/pixel-art-xl

There is no Lora block in the text2img UI either.

**Comment by StAlKeR7779** [comment]
1) There no syntax to use lora from prompt(was in 2.3 as quick way to implement it, but it technically incorrect)
2) In this version lora not supported for sdxl yet, will be in future - #4097

**Comment by Millu** [comment]
Closing this bug as this is a feature request that is now implemented and will be available in the next point release
