### ISSUE TITLE
[bug?]:InvokeAI not generating image. Stuck at "Invoke" button constantly loading.

### ISSUE THREAD

**Issue by H-Paulet** [invoke-ai/InvokeAI#4172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.0.1.

### What happened?

I can open InvokeAI on a browser but once I try to generate anything, the "Invoke" button shows its loading animation but nothing happen. The cancel button doesn't work either and the command files doesn't display anything past the launch of the browser, from what I've understood.

### Contact Details

hadrienpaulet@gmail.com

**Comment by psychedelicious** [comment]
Can you please open the Javascript console in your web browser (usually opened with F12 on Windows) and see if there are any errors displayed? If so, please right click on the error(s), copy the object, and paste here.

**Comment by H-Paulet** [comment]
@psychedelicious Here is it:

![Java script](https://github.com/invoke-ai/InvokeAI/assets/141517796/b7777866-0692-4fe8-b788-2278bda7b296)

**Comment by psychedelicious** [comment]
Ahh ok. There is a bug where a model isn't selected by default - double check that you have one selected

**Comment by sirj91** [comment]
I have a similar issue on macOS and I found an error in Javascript console: "Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received", how do I fix it?
<img width="555" alt="Screenshot 2023-08-12 at 20 43 43" src="https://github.com/invoke-ai/InvokeAI/assets/141750515/e353cd12-ffef-482d-8e06-ba8bc645e632">
