### ISSUE TITLE
[bug]: Invoke fails to start after "Successful install"

### ISSUE THREAD

**Issue by etha302** [invoke-ai/InvokeAI#4173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24

### What version did you experience this issue on?

3.0.1post3

### What happened?

After successful installation of invoke ai, i get this error. When using option "1", also i cant re-run installation because i also get error, i have tried installing invoke ai probably 5 times last 2 weeks, in hope new update will actually make it work somehow. Still no luck however. Also this was a fresh install.

### Screenshots

<img width="1904" alt="Screenshot 2023-08-05 205633" src="https://github.com/invoke-ai/InvokeAI/assets/139644787/61dfb952-14c3-4282-b5da-27097cd337d4">
<img width="1775" alt="Screenshot 2023-08-05 210445" src="https://github.com/invoke-ai/InvokeAI/assets/139644787/31aaabe1-6c16-4291-b011-9259c3bf4f77">

**Comment by egoegoegoegoego** [comment]
delete the whole folder like me. no issues now

**Comment by etha302** [comment]
> 

haha which folder?

**Comment by etha302** [comment]
> delete the whole folder like me. no issues now

Which folder?

**Comment by egoegoegoegoego** [comment]
the whole invokeai folder.

**Comment by etha302** [comment]
> the whole invokeai folder.

oh yeah, getting rid of invoke altogether haha. i am using comfy anyway, but i havent used invoke in a very long time and i am curious what changed, guess i am not going to find out that anytime soon.

**Comment by egoegoegoegoego** [comment]
it's the unified canvas that keeps me using invokeai, apart from that there's really not much to it. haven't really got into comfy as I'm still holding back on sdxl.. tried dreamshaperxl and wasn't impressed a lot like I was expecting to be blown away, which didn't happen lmao. btw I asked everywhere for the problem I had with invokeai but got little to no response at all in many cases... not like A1111 where there's ton of information and willing bros to help you out in discord or reddit. I feel this invokeai was made for the elite class and not for plebs like me

**Comment by Millu** [comment]
Hey @etha302! Sorry for the difficulties you experienced - there's a new version of Invoke released that should solve this issue for you (3.0.2rc1). You can update it from the invoke.sh script with option [9]

@egoegoegoegoego, I'm extremely sorry you didn't get the help you needed with Invoke - our goal is to make Invoke accessible to everyone regardless of background. I hope you'll give us another shot in the future!

**Comment by etha302** [comment]
> Hey @etha302! Sorry for the difficulties you experienced - there's a new version of Invoke released that should solve this issue for you (3.0.2rc1). You can update it from the invoke.sh script with option [9]
> 
I got it working, with 3.0.1 later. It seems to be important to run cmd or powershell as administrator, even though it will successfully install it even just running it. After doing that it seems to work just fine. Is inpainting with sdxl supported with new 3.0.2 update?
