### ISSUE TITLE
[bug]: suddenly cpu being used instead of gpu

### ISSUE THREAD

**Issue by draconicfae** [invoke-ai/InvokeAI#4202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

3.0.1post3

### What happened?

the latest time I tried to do image generation, it's using cpu.  All the previous times it correctly used gpu.  I don't think I changed anything between last run and current run but something must have changed or it would still work.

### Additional context

I tried the "fix a broken install" option and it still uses cpu; also tried the "change startup options" and it still uses cpu.  I don't know how to tell it "please stop using cpu".

**Comment by draconicfae** [comment]
more context : I did a recursive grep on 'cpu' and found an always_use_cpu option in the main yaml, but, it's false, so that's not it

**Comment by draconicfae** [comment]
more context : I nuked the invokeai directory and installed from square one, still forces cpu

**Comment by draconicfae** [comment]
#4267

**Comment by trmusson** [comment]
I'm seeing the same thing. Immediately after upgrading from 3.0.2 to 3.0.2post1, rendering's done using the CPU. The upgrade was done via Invoke's terminal-based UI. The "fix a broken install" option made no difference for me either. (Ubuntu 22.04.2 LTS here.)

**Comment by trmusson** [comment]
**Update:** Ahem. Rebooting my PC seems to have solved the problem, at least for me. Doh!
draconicfae, sorry to ask, but have you tried rebooting?

**Comment by draconicfae** [comment]
> **Update:** Ahem. Rebooting my PC seems to have solved the problem, at least for me. Doh! draconicfae, sorry to ask, but have you tried rebooting?

I've tried everything short of re-installing the linux distro itself.  I kinda suspect there's some sort of conflicting software somewhere, and that a full distro re-install would fix it, but it would be great if invokeai could tell me why it's forcing cpu so I'd know what conflicts I need to uninstall.

**Comment by AshkoreDracson** [comment]
I have the same problem after upgrading from 3.0.2 to 3.0.2post1
YAML settings like so:
```
always_use_cpu: false
free_gpu_mem: true
max_cache_size: 16.0
max_vram_cache_size: 0
precision: auto
sequential_guidance: false
xformers_enabled: true
tiled_decode: true
``` 
AMD Ryzen 3600 with 32GB RAM and RTX 2070S.

I did notice that this problem only happens when trying to generate an image with an SDXL model, loading a SD 1.5 model and generating with that seems to use my GPU as expected with good performance as expected.

**Comment by lstein** [comment]
Some cpu-only troubleshooting things to try:
* https://invoke-ai.github.io/InvokeAI/installation/030_INSTALL_CUDA_AND_ROCM/
* https://invoke-ai.github.io/InvokeAI/installation/010_INSTALL_AUTOMATED/#invokeai-runs-extremely-slowly-on-linux-or-windows-systems

**Comment by draconicfae** [comment]
> Some cpu-only troubleshooting things to try:
> 
>     * https://invoke-ai.github.io/InvokeAI/installation/030_INSTALL_CUDA_AND_ROCM/
> 
>     * https://invoke-ai.github.io/InvokeAI/installation/010_INSTALL_AUTOMATED/#invokeai-runs-extremely-slowly-on-linux-or-windows-systems (scroll down to “InvokeAI Runs Extremely Slowly” if this link doesn’t take you there)

Thanks, I saw your suggestion for these two approaches in response to another posted issue and gave it a try, didn't help unfortunately.  At some point it might be cool to extend invokeai to explicitly state why it chose cpu, to enable the user to be certain where the problem point is.  To fix it for myself I'll probably end up making a virtual machine with no responsibilities other than invokeai so that there's no chance that other AI installs will mess it up (which is probably what happened to me).

**Comment by psychedelicious** [comment]
We've revamped how torch is installed and it is much harder to accidentally get CPU torch now. If you still have this issue on the latest release (v4.1.0), please comment on this issue.
