### ISSUE TITLE
[bug]: Server Error Exception

### ISSUE THREAD

**Issue by kadevin** [invoke-ai/InvokeAI#4206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

3.0.1

### What happened?

When I use the local model (realisticVisionV5, the model downloaded from Civitai, I have tried to use the built-in program to convert the format and the result is the same), the output error: Server Error Exception

### Screenshots

![1691552527504(1)](https://github.com/invoke-ai/InvokeAI/assets/1709751/27704086-2c01-4fee-894a-97d957f2a9d4)
![image](https://github.com/invoke-ai/InvokeAI/assets/1709751/ff53d8b3-e16c-44f0-88f6-d70d870ce991)

**Comment by Millu** [comment]
This should be fixed in the 3.0.2rc1 that was just released - could you update your InvokeAI install and give it a whirl again?

**Comment by RenNgu** [comment]
Im running it on colab and im getting the same issue..any fix? 
ps: the files are not saved on my drive its just on the runtime

**Comment by Millu** [comment]
@RenNgu what version of InvokeAI are you using?

**Comment by psychedelicious** [comment]
This was resolved with the new MMv2 in v4.
