### ISSUE TITLE
[bug]: Installer link for 3.0.2 on releases page gives 404 

### ISSUE THREAD

**Issue by quixot1c** [invoke-ai/InvokeAI#4207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12

### What version did you experience this issue on?

3.0.2

### What happened?

on https://github.com/invoke-ai/InvokeAI/releases link to 3.0.2 installer is not working. It links to https://github.com/invoke-ai/InvokeAI/files/12209782/InvokeAI-installer-v3.0.2.zip

**Comment by Millu** [comment]
Thanks for catching this! Just updated it
