### ISSUE TITLE
[bug]: Frontend: Model resets when switching to Canvas panel

### ISSUE THREAD

**Issue by lstein** [invoke-ai/InvokeAI#4215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

3.0.2rc1

### What happened?

Whenever switching to the Canvas pane, the selected model shifts to the alphabetically earliest in the list.

To reproduce:

1. Go to text2img
2. Select any model that isn't at the top of the list in the popup menu
3. Got to canvas
4. Watch the selected model change.

**Comment by blessedcoolant** [comment]
Resolved.
