### ISSUE TITLE
[bug]: Frontend: Valid LoRAs are always displayed at bottom of popup menu

### ISSUE THREAD

**Issue by lstein** [invoke-ai/InvokeAI#4217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

3.0.2rc1

### What happened?

The LoRA selection popup menu in the linear UI reorders the list of LoRAs such that the ones that are valid in the currently selected model are always at the **bottom** of the menu rather than where you expect them to be.

See screenshots for examples, but here is what I observe:

1. If a SD-1 model is selected, then the order of sections in the LoRA menu is:
     - Stable Diffusion 2.x (all inactive)
     - Stable Diffusion XL (all inactive)
     - Stable Diffusion 1.x (all active)
 2. If a SD-2 model is selected, then the order of sections becomes:
      - Stable Diffusion 1.x (all inactive)
      - Stable Diffusion XL (all inactive)
      - Stable Diffusion 2.x (all active)
 3. If a SDXL model is selected, then you get:
      - Stable Diffusion 1.x (all inactive)
      - Stable Diffusion 2.x (all inactive)
      - Stable Diffusion XL (all active)

The consequence of this is that when the user pulls down the menu, all the LoRAs they see are inactive ones and they have to know to scroll to the bottom of the menu to see the others.

What is the expected behavior? In order of preference:
1. Only show the LoRAs that apply to the current model. Don't show the ones for other model bases.
2. Rearrange the base model sections so that the currently applicable one is at the top. So when the user selects the menu, the first thing they sees are the loras they can select. _This is how the textual inversion pulldown works_
3. Keep the order of base model sections invariant.

### Screenshots

![sdxl-selected](https://github.com/invoke-ai/InvokeAI/assets/111189/e5a4380a-c817-414e-8ed0-543969b97213)
![sd-2-selected](https://github.com/invoke-ai/InvokeAI/assets/111189/6492b6ad-26ce-4d61-aafe-dc18711861aa)
![sd-1-selected](https://github.com/invoke-ai/InvokeAI/assets/111189/e5fde691-e2cb-4baa-b215-638c78b63869)

**Comment by hipsterusername** [comment]
#2 provides visibility into why others aren’t displayed - for example if someone adds a LoRA for 1.5 expecting it was an SDXL LoRA.
