### ISSUE TITLE
[bug]: Invoke AI is taking so long to generate an image

### ISSUE THREAD

**Issue by misaki1301** [invoke-ai/InvokeAI#4238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

3.0.2

### What happened?

Upgraded from [InvokeAI 3.0.1 (hotfix 3)](https://github.com/invoke-ai/InvokeAI/releases/tag/v3.0.1post3) and I'm getting bad results and performance issues with the image generation.
the debug menu doesn't show any adittional log to detect the issue.

### Screenshots

![image](https://github.com/invoke-ai/InvokeAI/assets/22973312/755ac4c3-5a65-4a3a-8a5a-292985eade84)
![image](https://github.com/invoke-ai/InvokeAI/assets/22973312/dd559c6b-ee22-4283-8774-f54d53434f0a)

**Comment by metal3d** [comment]
seems related to my issue #4197 - I had to set the cache size to 0 and stop swap (on Linux) - the latest version of InvokeAI seems to have made something that slows down the generation.

**Comment by Millu** [comment]
As @metal3d mentioned, try setting your VRAM to 0 to improve generation speeds

**Comment by misaki1301** [comment]
ok I'll try to setup that config in launch or maybe check the new update

**Comment by misaki1301** [comment]
some news:
updating to the new release of 3.0.2 kinda fixed this without tinker in the params and I moved to the Studio Drivers of Nvidia for stability
RTX 3070 user btw
