### ISSUE TITLE
[bug]: Can't Enable SDXL Refiner

### ISSUE THREAD

**Issue by twopiearr** [invoke-ai/InvokeAI#4239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### VRAM

16 gigs gotal system ram

### What version did you experience this issue on?

3.0.2

### What happened?

Invoke will allow me to use any SDXL model I have installed as long as the refiner is turned off. However, if the refiner is turned on, I get the message "Validation Error" every time I hit the Invoke button. The terminal offers messages like the below whenever this happens:

`[2023-08-11 01:59:42,444]::[uvicorn.access]::INFO --> 127.0.0.1:57506 - "POST /api/v1/sessions/ HTTP/1.1" 422`

**Comment by hipsterusername** [comment]
Can you hit F12 in your browser and share your expanded browser console error message for this?

You should probably clear your browser's local storage, as a troubleshooting step, in any case.

**Comment by twopiearr** [comment]
Screenshots below.

I haven't cleared cache, but I DID try this in Safari instead of Firefox, which is a browser that gets opened maybe once or twice a year, so there shouldn't be anything in cache related to Invoke, and got identical results.

These are from the Firefox console. Latest version as far as I know.

![Screenshot 2023-08-11 at 12 04 52 PM](https://github.com/invoke-ai/InvokeAI/assets/86857411/6c9ba66c-f878-4fdc-9bf8-5caa726907e7)
![Screenshot 2023-08-11 at 12 06 05 PM](https://github.com/invoke-ai/InvokeAI/assets/86857411/dc568e01-9c59-4a9c-a9a3-683a498dc5bf)
![Screenshot 2023-08-11 at 12 08 22 PM](https://github.com/invoke-ai/InvokeAI/assets/86857411/7d8c5c11-f208-422f-b8a4-b5ec4ff06e54)

**Comment by twopiearr** [comment]
cleared a gig of cache and about 1.3 gig of cookies and other site data. No change in behavior.

**Comment by hipsterusername** [comment]
Sorry - just to confirm, you did clear the **local storage** of your browser? (F12 > Storage Tab > Local Storage > Right-Click/Delete All

I'm not able to replicate this, which (given the nature of the 422 error response) suggests it's not a malformed graph in the code, but an issue in the graph that your local storage is attempting to pass in. 

Just want to verify before we troubleshoot any further - May be easier to discuss live on discord

**Comment by twopiearr** [comment]
I did not fully clear local storage because this is my primary browser and there are quite a few cookies I don't want to lose. I did clear 2.3 of the 2.5 gigs of local storage and am confident that all that remains is necessary and good.

I will completely clear from Safari and see what happens.

**Comment by twopiearr** [comment]
I cannot discuss live on Discord today because of work. I could do so tomorrow.

**Comment by twopiearr** [comment]
Fully clearing local storage in Safari seems to have done the trick. I did notice that there was saved data for 127.0.0.1. I'll try manually clearing that data from Firefox and see if that fixes it there.
