### ISSUE TITLE
[bug]: webgui inference steps input not being properly respected on img2img.

### ISSUE THREAD

**Issue by trontronicent** [invoke-ai/InvokeAI#4248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24GB

### What version did you experience this issue on?

3.0.2

### What happened?

Affecting Img2Img, Text2Img not affected.

Using the frontend to alter inference steps numbers, in my example: 500, is not being properly used. Inference steps (as show by the shell) are altered but to a different number (350 here). The same counts for other inference steps values being entered, the displayed numbers in the shell are altrered, but to different values then being set on the webgui. 
The info on the created image actually shows the entered number of steps (500), instead of the number of steps the shells shows.

### Screenshots

Entered on GUI     Displayed on Shell
500                        350
25                          17
16                          11

### Additional context

The selected model doesn't have any influence on this.

**Comment by hipsterusername** [comment]
This is not a bug! :)

This is how Image2Image works. Based on the denoising strength you use, Image2Image is inserting a noised image at a certain step in the generation process to produce the output.
