### ISSUE TITLE
[bug]: Hello, i have the InvokeAI 2.3.5 standalone installed on the computer, after running the update file to upgrade to the latest version, the app isnt working, and i receive the error message no such file in the directory, and the InvokeAI launcher stucks in loading screen

### ISSUE THREAD

**Issue by AhmadAl-Khatib** [invoke-ai/InvokeAI#4249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6

### What version did you experience this issue on?

update

### What happened?

stuck in the loading screen, no such file in the directory

**Comment by hipsterusername** [comment]
Download the latest installer, and run the install over your existing folder - This will keep your models, but you will need to run the image migration script provided in 3.0.2 to import your previous images into the database.
