### ISSUE TITLE
[bug]: chrome browser corruption 

### ISSUE THREAD

**Issue by Creare-d-arte** [invoke-ai/InvokeAI#4250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

10GB

### What version did you experience this issue on?

3.0.2rc1

### What happened?

On multiple occasions, at random intervals, my Chrome browser has had its extensions corrupted.

As of today, the issue temporarily resolved itself by restarting my PC.

However, the issue still persists.

Chrome is set as the default browser, and is what InvokeAI uses for the webUI.

It appears that either InvokeAI is writing bad data somehow, which is corrupting Chrome.

Or some kind of targeted information collection is taking place, which requires the extensions be modified.

Obviously this is concerning, and a resolution is necessary.

Note that I have tested that none of my downloaded models, loras, vaes, embeddings, etc. are the cause.

**Comment by hipsterusername** [comment]
Going to need a bit more information on what you mean by “corrupted”, and why you think Invoke is involved at all in that.

**Comment by Creare-d-arte** [comment]
> Going to need a bit more information on what you mean by “corrupted”, and why you think Invoke is involved at all in that.

(Note that I wish not to offend, nor make hurtful accusations; this issue is possibly a mistake or unrelated error.)

The browser extensions stop working; inside the Chrome browser extensions tab, there is a message under each extension, that states the extension is corrupted.

After reading up on the issues from various sources, the general consensus was that this is caused by data errors in Chrome, or extension data manipulation.


I've wiped my PC to be sure, and tried my best to isolate the issue.

It seems that only after installing InvokeAI (any version post 3.0.0), causes the issue.

This is just with the base diffuser models installed, nothing else.


It's possible that closing the command window pre-emptively, or the webpage, is causing the data corruption; or some UI error.

**Comment by hipsterusername** [comment]
All good! 

It’s unclear what exactly is even happening to isolate why your extensions are breaking. Which extensions are you using that are experiencing issues?

**Comment by psychedelicious** [comment]
This is very strange. Another user reported a similar issue not too long ago. The app is a simple website and uses standard browser APIs to store data. There's nothing that interacts with any extensions or related APIs. 

I suspect there is an extension that is trying to do something with the app, and they are not playing nicely together. 

To troubleshoot this, please provide as much detail as possible, including chromes version, a list of extensions that are installed and the specific extensions that say they are corrupted.

**Comment by Creare-d-arte** [comment]
> All good!
> 
> It’s unclear what exactly is even happening to isolate why your extensions are breaking. Which extensions are you using that are experiencing issues?

The affected extensions, as of yesterday where:

My bookmark manager, and password manager.

Previously my adblocker, pdf, and translate extensions where corrupted.


From testing, it appears that any/all extensions can be affected.


This issue occurs with any version of Chrome released in 2023, at least.

e.g. Version 115.0.5790.171 (Official Build) (64-bit)


Note that this extension corruption has only occurred after launching InvokeAI, closing it; followed by login/out and restarts.

**Comment by psychedelicious** [comment]
Both websites and extensions are sandboxed by default. Websites do not ever get access to extensions, but extensions can be granted access to a website's data. You'll recall giving extensions access to your data when installing them. That includes website data. 

This means that invokeai's web ui (which is just a website) cannot go and mess up your extensions. It does not have access to do that. 

My guess is one of your extensions is attempting to intercept `LocalStorage` API calls, and is encountering something it doesn't know how to handle. Or it is attempting to log all websocket messages and can't handle the rapid generation progress events. Maybe it's trying to inject JavaScript into the site - that's something translation extensions often do. 

(`LocalStorage` is a standard way to persist data across page reloads and is used by invokeai to persist your settings. To reiterate, this is not an exotic feature - it is ubiquitous and invokeai doesn't do anything out of the ordinary here.)

If you can reproduce the issue reliably, you can troubleshoot by disabling your extensions one by one, then testing if the issue occurs each time.

Odds are, you'll find that after you disable a particular extension, the corrupted extensions issue disappears and now you'll know that this extension is causing the problem. 

Another possibility is that your chrome profile has been corrupted (again - by an extension, not a website like invokeai) and that's actually the cause. This is very unlikely.

Finally, you may have a malicious extension installed, and it is either purposefully breaking your chrome or inadvertently breaking it as it tries to do something naughty.

**Comment by Creare-d-arte** [comment]
> Both websites and extensions are sandboxed by default. Websites do not ever get access to extensions, but extensions can be granted access to a website's data. You'll recall giving extensions access to your data when installing them. That includes website data.
> 
> This means that invokeai's web ui (which is just a website) cannot go and mess up your extensions. It does not have access to do that.
> 
> My guess is one of your extensions is attempting to intercept `LocalStorage` API calls, and is encountering something it doesn't know how to handle. Or it is attempting to log all websocket messages and can't handle the rapid generation progress events. Maybe it's trying to inject JavaScript into the site - that's something translation extensions often do.
> 
> (`LocalStorage` is a standard way to persist data across page reloads and is used by invokeai to persist your settings. To reiterate, this is not an exotic feature - it is ubiquitous and invokeai doesn't do anything out of the ordinary here.)
> 
> If you can reproduce the issue reliably, you can troubleshoot by disabling your extensions one by one, then testing if the issue occurs each time.
> 
> Odds are, you'll find that after you disable a particular extension, the corrupted extensions issue disappears and now you'll know that this extension is causing the problem.
> 
> Another possibility is that your chrome profile has been corrupted (again - by an extension, not a website like invokeai) and that's actually the cause. This is very unlikely.
> 
> Finally, you may have a malicious extension installed, and it is either purposefully breaking your chrome or inadvertently breaking it as it tries to do something naughty.

Thankyou for clarifying things; I agree with your evaluation.

I'll troubleshoot the issue and see how things go :)

**Comment by Creare-d-arte** [comment]
Closing this issue, as it appears from testing to indeed be caused by my chrome extensions.

**Comment by psychedelicious** [comment]
@Creare-d-arte Did you figure out which extension(s) were causing the corruption issue? Good to know if there are specific extensions that interact poorly
