### ISSUE TITLE
[bug]: Configuration stage error

### ISSUE THREAD

**Issue by Kureshik** [invoke-ai/InvokeAI#4263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

3.0.2

### What happened?

It fails on configure script stage with error: `RuntimeError: Unrecognized CachingAllocator option: 1024`

### Screenshots

![image](https://github.com/invoke-ai/InvokeAI/assets/79392961/13cecff0-4f8a-4a51-a715-39bd4215830f)

**Comment by Millu** [comment]
Are you still experiencing this issue?

**Comment by Kureshik** [comment]
Yes
