### ISSUE TITLE
[bug]: install.sh on 3.0.2.post1 fails with a Python error on M2 Mac Studio

### ISSUE THREAD

**Issue by panicsteve** [invoke-ai/InvokeAI#4270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What version did you experience this issue on?

3.0.2.post1

### What happened?

Historically, install.sh has not been a problem.  The last release I used was 3.0.0 and there was no issue with the installer.  I'm using python3.11 installed via Homebrew on a Mac Studio M2.  

Running install.sh on the 3.0.2.post1 release generates the following error:

```
[stevenf] InvokeAI-Installer-3.0.2.post1 % ./install.sh
Initializing the installer. This may take a minute - please wait...
Traceback (most recent call last):
  File "/Users/stevenf/Documents/AI Installers/InvokeAI-Installer-3.0.2.post1/./lib/main.py", line 48, in <module>
    inst = Installer()
           ^^^^^^^^^^^
  File "/Users/stevenf/Documents/AI Installers/InvokeAI-Installer-3.0.2.post1/lib/installer.py", line 43, in __init__
    self.bootstrap()
  File "/Users/stevenf/Documents/AI Installers/InvokeAI-Installer-3.0.2.post1/lib/installer.py", line 92, in bootstrap
    venv_dir = self.mktemp_venv()
               ^^^^^^^^^^^^^^^^^^
  File "/Users/stevenf/Documents/AI Installers/InvokeAI-Installer-3.0.2.post1/lib/installer.py", line 76, in mktemp_venv
    venv.create(venv_dir.name, with_pip=True)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/venv/__init__.py", line 468, in create
    builder.create(env_dir)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/venv/__init__.py", line 76, in create
    self._setup_pip(context)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/venv/__init__.py", line 358, in _setup_pip
    self._call_new_python(context, '-m', 'ensurepip', '--upgrade',
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/venv/__init__.py", line 354, in _call_new_python
    subprocess.check_output(args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/var/folders/sz/v914j14d0_n355m9l40s5td80000gn/T/invokeai-installer-tmpmalmow71/bin/python3.11', '-m', 'ensurepip', '--upgrade', '--default-pip']' died with <Signals.SIGABRT: 6>.
```

**Comment by panicsteve** [comment]
Well, I just tried re-running the 3.0.0 install.sh, and now that doesn't work either for some reason.  It definitely did before, so this seems to be something that has changed on my system, not in InvokeAI. :( 

(dyld is failing with a weird error when venv.create() is called in install.sh. But I can run the python3.10 interpreter from the command line and call venv.create() there with no issue.)

```
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @loader_path/../Python
Referenced from: <7295E559-55D4-3ACA-9820-D95D1F4AE151> /private/var/folders/*/python3.10
Reason: tried: '/private/var/folders/t0/04vc_6bs76n1s1v5nhgzychm0000gn/T/invokeai-installer-tmpc50uvdt5/bin/../Python' (no such file), '/usr/local/lib/Python' (no such file), '/usr/lib/Python' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x182591118 __abort_with_payload + 8
1   dyld                          	       0x18259cd7c abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x18259cdb0 abort_with_payload + 16
3   dyld                          	       0x1825288a8 dyld4::halt(char const*) + 328
4   dyld                          	       0x182525590 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4184
5   dyld                          	       0x182523e18 start + 1964
```

I'm not sure what is going on here. As the error notes, `invokeai-installer-tmpc50uvdt5 ` does not exist within `'/private/var/folders/t0/04vc_6bs76n1s1v5nhgzychm0000gn/T/`.  If TemporaryDirectory() on line 74 was supposed to create it, it would seem that it didn't.

This most likely is something that Homebrew blew up, but I have no idea what.  For now I guess I will just close this issue. Maybe will update if I ever figure out what is going on.

**Comment by panicsteve** [comment]
FWIW, I was able to install 3.0.2.post1 using the pip install / invokeai-configure method.

**Comment by skurovec** [comment]
I have same problem after brew update. Currently I am unable to install Invoke using installer on python 3.10 or 3.11 on mac. 

Could you please reopen this issue, so we can track for possible solutions?

**Comment by jooray** [comment]
Same here, with 3.10 and 3.11.

**Comment by skurovec** [comment]
Looks like homebrew python is broken. When removed and installed python from python.org, all is working as expected.

**Comment by Millu** [comment]
We've seen people running into issues with brew installed python

A fix is uninstall homebre's python, then install python via pyenv.

**Comment by panicsteve** [comment]
Can confirm that installing python from the binary installer package from python.org resolves the error with running InvokeAI's install.sh, and you can have it installed alongside Homebrew's python, but beware of possible python versioning hell afterward.

The python.org installer will install binaries in /Library/Frameworks/Python.framework and place symlinks for python3 and python3.11 in /usr/local/bin pointing to those.  So, if /usr/local/bin has precedence in your path, you will get the binaries installed by the python.org package rather than Homebrew's, and install.sh will succeed.

You can specifically invoke /opt/homebrew/bin/python3 or /opt/homebrew/bin/python3.11 to get Homebrew's binaries.  (These paths assume you are using Homebrew on Apple Silicon, which you would have to be to run InvokeAI anyway.)

If you have other versions of python installed through Homebrew (such as python3.10 or python3.9) you can also use their full /opt/homebrew/bin/* path to run them.  (I would imagine you'd also need to set the PYTHONPATH and PYTHONHOME environment variables to point to the right places before running those other python installs -- but I barely know what I'm talking about because I don't use python, and this is one of the reasons why. :D)

**Comment by lnlyssg** [comment]
> We've seen people running into issues with brew installed python
> 
> A fix is uninstall homebre's python, then install python via pyenv.

Not as easy as it sounds - I don't use python but a number of other homebrew packages I have installed do use it so I can't delete it without breaking those....

**Comment by spectrachrome** [comment]
Same problem here using the official Invoke shell installer, on first time installation.

**Comment by psychedelicious** [comment]
We have revamped the installer in v4.0.0 - if this is still a problem w/ v4.0.0, please create a new issue.
