### ISSUE TITLE
BUG  "Cancel after current iteration" does not add generated images to gallery after iteration cancelled 

### ISSUE THREAD

**Issue by phrkr2600** [invoke-ai/InvokeAI#4272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

3.0

### What happened?

BUG  

"Cancel after current iteration" does not add generated images to gallery after iteration cancelled.

Example:  

Images = 20 
- Cancelled at image 6.

No new images added to gallery!

 (Maybe they are only added to the database?)

### Contact Details

710.avfx@gmail.com

**Comment by Millu** [comment]
This is a known issue that will be resolved in the next release (3.1)!
