### ISSUE TITLE
[bug]: vpred SD 1.5 models don't convert to diffusers properly

### ISSUE THREAD

**Issue by Yo1up** [invoke-ai/InvokeAI#4277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

3.0.2

### What happened?

When importing a vpred sd 1.5 model safetensors file, the conversion doesn't work properly. the outputs appear the same as if the config file was not included on A1111. I know this is an issue with conversion because vpred models that don't need to be converted to diffusers (they are natively diffusers format) work without issue.

### Screenshots

![image](https://github.com/invoke-ai/InvokeAI/assets/121737934/5ba75bb1-6a2d-46db-8927-afc17d2b5146)

### Additional context

I tried on Windows 10 22H2 with a CUDA device with 24GB VRAM and the issue still occurs.

**Comment by Millu** [comment]
Thanks for flagging! Are you running into the same issue with SD2 vpred models as well? Some users have reported success with using the model manager to mark a SD1.5 vpred model as an SD2 model in Invoke

**Comment by Yo1up** [comment]
ah, I saw this forever ago but I guess I forgot to respond. As of when I wrote the initial issue, I had no success doing that. I was using that workaround successfully up until the 3.0.2 update when it stopped working, I decided to write the bug report. and it is still non-functioning in 3.1.0 this time attempting a conversion results in this traceback:
```[2023-09-12 20:10:21,715]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "C:\Users\artis\invokeai\.venv\lib\site-packages\invokeai\app\services\processor.py", line 95, in __process
    outputs = invocation.invoke_internal(
  File "C:\Users\artis\invokeai\.venv\lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 549, in invoke_internal
    return self.invoke(context)
  File "C:\Users\artis\invokeai\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\artis\invokeai\.venv\lib\site-packages\invokeai\app\invocations\compel.py", line 64, in invoke
    tokenizer_info = context.services.model_manager.get_model(
  File "C:\Users\artis\invokeai\.venv\lib\site-packages\invokeai\app\services\model_manager_service.py", line 373, in get_model
    model_info = self.mgr.get_model(
  File "C:\Users\artis\invokeai\.venv\lib\site-packages\invokeai\backend\model_management\model_manager.py", line 485, in get_model
    model_path = model_class.convert_if_required(
  File "C:\Users\artis\invokeai\.venv\lib\site-packages\invokeai\backend\model_management\models\stable_diffusion.py", line 235, in convert_if_required
    return _convert_ckpt_and_cache(
  File "C:\Users\artis\invokeai\.venv\lib\site-packages\invokeai\backend\model_management\models\stable_diffusion.py", line 286, in _convert_ckpt_and_cache
    convert_ckpt_to_diffusers(
  File "C:\Users\artis\invokeai\.venv\lib\site-packages\invokeai\backend\model_management\convert_ckpt_to_diffusers.py", line 1734, in convert_ckpt_to_diffusers
    pipe.save_pretrained(
  File "C:\Users\artis\invokeai\.venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 655, in save_pretrained
    save_method(os.path.join(save_directory, pipeline_component_name), **save_kwargs)
  File "C:\Users\artis\invokeai\.venv\lib\site-packages\transformers\modeling_utils.py", line 1845, in save_pretrained
    safe_save_file(shard, os.path.join(save_directory, shard_file), metadata={"format": "pt"})
  File "C:\Users\artis\invokeai\.venv\lib\site-packages\safetensors\torch.py", line 232, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
  File "C:\Users\artis\invokeai\.venv\lib\site-packages\safetensors\torch.py", line 394, in _flatten
    raise RuntimeError(
RuntimeError:
            Some tensors share memory, this will lead to duplicate memory on disk and potential differences when loading them again: [{'text_model.embeddings.token_embedding.weight', 'text_model.encoder.layers.0.mlp.fc1.weight', 'text_model.encoder.layers.0.self_attn.k_proj.weight', 'text_model.embeddings.position_embedding.weight', 'text_model.encoder.layers.0.self_attn.k_proj.bias', 'text_model.encoder.layers.0.mlp.fc1.bias'}].
            A potential way to correctly save your model is to use `save_model`.
            More information at https://huggingface.co/docs/safetensors/torch_shared_tensors


[2023-09-12 20:10:21,727]::[InvokeAI]::ERROR --> Error while invoking:

            Some tensors share memory, this will lead to duplicate memory on disk and potential differences when loading them again: [{'text_model.embeddings.token_embedding.weight', 'text_model.encoder.layers.0.mlp.fc1.weight', 'text_model.encoder.layers.0.self_attn.k_proj.weight', 'text_model.embeddings.position_embedding.weight', 'text_model.encoder.layers.0.self_attn.k_proj.bias', 'text_model.encoder.layers.0.mlp.fc1.bias'}].
            A potential way to correctly save your model is to use `save_model`.
            More information at https://huggingface.co/docs/safetensors/torch_shared_tensors```

**Comment by lstein** [comment]
I was unaware that there were any vpred 1.5 models. To fix this, place the proper .conf file next to the safetensors model and give it the same base name. If the model is `ducks.safetensors` then put `ducks.conf` next to it and when it is imported and converted the correct conf file will be used in conversion.

**Comment by Dibucci** [comment]
> I was unaware that there were any vpred 1.5 models. To fix this, place the proper .conf file next to the safetensors model and give it the same base name. If the model is `ducks.safetensors` then put `ducks.yaml` next to it and when it is imported and converted the ducks config file will be used in conversion.

I just started using InvokeAI and I mostly use V-Pred models and I did what you said and 
![image](https://github.com/invoke-ai/InvokeAI/assets/25534395/9e2773cf-c45a-4ae0-86b9-611762fe55fd)
that is the image I got... It should not do that cuz that is what happens when the config file is not used.

now, I do have it pointed to a folder where I put all my models and configs in and they are not separate by folders, so what I did was I deleted the conversion it made and I put the EasyfluffV11.1.safetensor and its yaml, both the same name btw, into a seperate folder inside the models folder so they were separated from everything else then I tried again, it converted the Safetensor and when I made the image again, well, I posted that image already, cuz the image I posted was from the 2nd attempt when I put them in their own folder.

idk if the cmd window is supposed to say somthing different when you convert a V-pred model or not but you get the same conversion output for V-pred as you do normal models so it doesn't say that its using the config, but again idk if its supposed to

**Comment by Dibucci** [comment]
Ok, I just tried something. Turns out that in the scheduler_config.json its not setting the "prediction_type" to "v-prediction"

once changing it, it starts to make the images... now if only we had CFG Rescale function in InvokeAI, I could get more detailed images... unless there is a similar feature in Invoke AI I don't know about.
