### ISSUE TITLE
[bug]: Black images with SD2.1 768 model in latest update

### ISSUE THREAD

**Issue by TijuanaKez** [invoke-ai/InvokeAI#4278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

amd

### VRAM

16GB

### What version did you experience this issue on?

3.0.2post1

### What happened?

Reinstalled a fresh InvokeAI 3.0.2post1 letting the installer download all the models.

SDXL looks great at 1024x1024
All the SD1.5 models work great at 512x512
stable-diffusion-v1-5 works great at 512x512. 768 x 768 works as expected.
stable-diffusion-2-1 at 768x768 just outputs a black image. Same with 512x512.

VAE precision set to fp32 in the UI, but tried fp16 aswell.

EDIT: switching from 'auto' to 'float32' in start-up options fixes this, but RX6900 XT shouldn't need it, and it's not needed for SD1.5 or SDXL to work. Switching to float32 prevents SDXL from working as there's not enough VRAM with float32 on SDXL.

### Screenshots

Seeing this in the output.
```
RuntimeWarning: invalid value encountered in cast
  images = (images * 255).round().astype("uint8")
```

**Comment by Millu** [comment]
@StAlKeR7779 was this issue fixed?

**Comment by Fortyseven** [comment]
Seeing this with SDXL, as well. I've been able to repeat it, so I'll dump that info here.

```
{
  "generation_mode": "sdxl_txt2img",
  "positive_prompt": "cave painting",
  "negative_prompt": "",
  "width": 1536,
  "height": 1024,
  "seed": 2693986872,
  "rand_device": "cpu",
  "cfg_scale": 10,
  "steps": 24,
  "scheduler": "euler_k",
  "model": {
    "model_name": "sdxl Unstable Diffusers",
    "base_model": "sdxl",
    "model_type": "main"
  },
  "t2iAdapters": [
    {
      "image": {
        "image_name": "ef164c24-9f79-4e43-9ad4-80f7a234628e.png"
      },
      "t2i_adapter_model": {
        "model_name": "zoedepth-sdxl",
        "base_model": "sdxl"
      },
      "weight": 1,
      "begin_step_percent": 0.1,
      "end_step_percent": 0.85,
      "resize_mode": "just_resize"
    }
  ],
  "vae": {
    "model_name": "sdxl-1-0-vae-fix",
    "base_model": "sdxl"
  },
  "positive_style_prompt": "",
  "negative_style_prompt": ""
}
```
...
```
{
  "image_name": "332311a7-5f89-44c5-b9c5-75bb36ae0e65.png",
  "image_url": "api/v1/images/i/332311a7-5f89-44c5-b9c5-75bb36ae0e65.png/full",
  "thumbnail_url": "api/v1/images/i/332311a7-5f89-44c5-b9c5-75bb36ae0e65.png/thumbnail",
  "image_origin": "internal",
  "image_category": "general",
  "width": 1536,
  "height": 1024,
  "created_at": "2023-11-01 15:54:43.238",
  "updated_at": "2023-11-01 15:54:43.238",
  "deleted_at": null,
  "is_intermediate": false,
  "session_id": "ce95385e-6009-4c7d-9ee5-01a6a9f26593",
  "node_id": "96f1ae83-c7a2-4f0b-add4-e6a7dc3d6a64",
  "starred": false,
  "board_id": null,
  "workflow_id": null
}
```

With this image for the controlnet stuff:
![image](https://github.com/invoke-ai/InvokeAI/assets/156409/337dc1c9-d0d2-41f0-ba44-f007ad264b2d)

I've been screwing around trying to learn how the settings work for each of the adapters and I was hitting this error like maybe ~3% of the time. Otherwise it worked fine.

**Comment by Fortyseven** [comment]
(For those curious. :sweat_smile:)
![image](https://github.com/invoke-ai/InvokeAI/assets/156409/87e9315f-972c-4097-b1d9-90b630acd468)

**Comment by psychedelicious** [comment]
You can set a default VAE precision with v4's model manager.
