### ISSUE TITLE
[bug]: Unable to lauch invokeai-web

### ISSUE THREAD

**Issue by Trenien** [invoke-ai/InvokeAI#4280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

3.0.2post1

### What happened?

After installing InvokeAI, I've run the script invoke.sh. When I try to start invokeai-web, the pc attempts to do something for a few seconds and then exits with the following message (the number ##### is a process id that changes every time) :
./invoke.sh : line 51 : ##### illegal instruction invokeai-web $PARAMS

### Additional context

This always happen even after a full update of the computer and doing the update and reconfig of InvokeAI from the invoke.sh menu.
This computer has just been completely reinstalled with ubuntu 22.04

**Comment by psychedelicious** [comment]
The error message means that your computer is attempting to execute a system call that is not compatible with its platform. It's a very low-level issue. It sounds like you've ended up with some libraries that are not compatible with your CPU.

Please help us by providing all messages output from the script, maybe there is a clue.
