### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by Cavista** [invoke-ai/InvokeAI#4282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.02post

### What happened?

- When putting a dynamic list into the Style Prompt the iteration of prompt does not happen. No matter how long the dynamic list is the invoke stops at one image i.e. Art style of {impressionist|Caravaggio|Pop Art|Picasso}  I will only get 1 image and it stops
- I can put the the style up in the Main Prompt and get all iterations but each Image is very similar whether concatenate is on or off
- This is only happening with SDLX

### Additional context

Seems to be consistent and you should be able to create this issue. 

### Contact Details

Discord Jordack

**Comment by psychedelicious** [comment]
Yes, it's a known issue. The dynamic prompts nodes are not hooked up to the style prompt yet.

**Comment by Millu** [comment]
This is captured in #4185
