### ISSUE TITLE
[bug]: Error downloading core tokenizers and text encoders.

### ISSUE THREAD

**Issue by jonebarker** [invoke-ai/InvokeAI#4283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12

### What version did you experience this issue on?

3.0.2

### What happened?

See screenshots.   Launch aborts due to missing vae file.  Running the installation repair script yields error about downloading core tokenizers and text encoders.

### Screenshots

<img width="854" alt="Screenshot 2023-08-15 130521" src="https://github.com/invoke-ai/InvokeAI/assets/271993/fa0b8d22-93f8-46b4-8177-b7c6acfb82ed">
<img width="859" alt="Screenshot 2023-08-15 130806" src="https://github.com/invoke-ai/InvokeAI/assets/271993/fcf90b04-c97c-4e00-8d76-08b6e54ae0df">

**Comment by Millu** [comment]
Could you try option [5] and re-download SD 1.5?

Another option to download the VAE from HF and drop it into the the models\core\convert\sd-vae-ft-mse folder: https://huggingface.co/stabilityai/sd-vae-ft-mse-original

**Comment by psychedelicious** [comment]
We have a new model manager in v4.0.0 with a new handling for core model downloads.

If you still have this problem on v4.0.0, please open a new issue.
