### ISSUE TITLE
[enhancement]: Render Commands

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#4289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

CLI Render Commands

### What should this feature add?

For context, I'm doing a C++ wrapper for Invokeai. I've migrated from 2.x to 3.x recently but I cant generate images as there is no example and/or it doesn't seem to be a straight forward way to render images via the CLI yet.

In the meantime, I guess my first step is to inverse engineer how the node graph is being populated on the fly for a simple generation that doesn't use a node graph. Any pointers would be appreciated. 

Is there plans to support "Render Commands" in the near future?

thank you,

**Comment by Millu** [comment]
@Neosettler closing this out as I believe you have been able to get generations working via graphs & the API. 

For anyone else, inspect the payload the browser is sending to the web server to understand the how to generate images with the Invoke server API
