### ISSUE TITLE
[bug]: list_sessions api not working?

### ISSUE THREAD

**Issue by philsmy** [invoke-ai/InvokeAI#4293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

3.0.2post1

### What happened?

We are trying to call the api endpoint `/api/v1/sessions` as a `GET` request. According to the code this should work.

invokeai/app/api/routers/sessions.py:40 has the code, but we get a 404 error.

We are calling it with curl:
```
curl "https://<server address>/api/v1/sessions"
```

Perhaps this is not being called anywhere, but we were hoping to get it. I thought it was working in 3.0.2pre2 but I might be mistaken.

**Comment by lstein** [comment]
I can reproduce this, except that I get a 500 error rather than 404.

```
curl -X 'GET' \
  'http://localhost:9090/api/v1/sessions/?page=0&per_page=10' \
  -H 'accept: application/json'

Internal Server Error
```
Log file shows this:

```
  No match for discriminator 'type' and value 'int_output' (allowed values: 'boolean_output', 
'boolean_collection_output', 'integer_output', 'integer_collection_output', 'float_output',
 'float_collection_output', 'string_output', 'string_collection_output', 'image_output', 
'image_collection_output', 'latents_output', 'latents_collection_output', 'color_output', 
'color_collection_output', 'conditioning_output', 'conditioning_collection_output', 'control_output', 'model_loader_output', 'lora_loader_output', 'sdxl_lora_loader_output', 'vae_loader_output', 
'metadata_accumulator_output', 'clip_skip_output', 'noise_output', 
'sdxl_model_loader_output', 'sdxl_refiner_model_loader_output', 'model_loader_output_onnx', 
'graph_output', 'iterate_output', 'collect_output') 
(type=value_error.discriminated_union.invalid_discriminator; discriminator_key=type; 
discriminator_value=int_output; allowed_values='boolean_output', 'boolean_collection_output',
 'integer_output', 'integer_collection_output', 'float_output', 'float_collection_output', 
'string_output', 'string_collection_output', 'image_output', 'image_collection_output', 'latents_output', 'latents_collection_output', 'color_output', 'color_collection_output', 'conditioning_output', 
'conditioning_collection_output', 'control_output', 'model_loader_output', 
'lora_loader_output', 'sdxl_lora_loader_output', 'vae_loader_output', 'metadata_accumulator_output',
 'clip_skip_output', 'noise_output', 'sdxl_model_loader_output', 'sdxl_refiner_model_loader_output', 
'model_loader_output_onnx', 'graph_output', 'iterate_output', '
collect_output')
__root__ -> results -> 8246e3bb-0df6-4688-b0e5-e5b2805190ca
```

**Comment by psychedelicious** [comment]
@philsmy Are you sure it's a 404?

You can browse to the OpenAPI swagger docs page and test the query there: http://localhost:9090/docs#/sessions/list_sessions

What happens when you use that website?

**Comment by philsmy** [comment]
I am running on a remote server. But, I think I have found the issue. I was using the wrong URL! 

If I do `curl https://<my server>/api/v1/sessions` I get a 404

If I do `curl https://<my server>/api/v1/sessions/` (note the trailing /) it works.

So in a sense, this is user error but I am not a fan of URLs that end in /. It is not a construct that is normal online, especially for APIs.

This issue can be closed, but I imagine I am not the only one to encounter this!

**Comment by philsmy** [comment]
@lstein I do NOT get a 500 error when I do that request with `page` and `per_page`. That works for me.
