### ISSUE TITLE
old and new training Embeddings are not working correctly or even showing up in the list of embeddings when typing <

### ISSUE THREAD

**Issue by WhatsUpInTheSky37** [invoke-ai/InvokeAI#4305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12

### What version did you experience this issue on?

3.0.2post1

### What happened?

Everytime I train something It is not showing up anymore as an embedding. I can only see th two that came with InvokeAI when I hit the < key

### Screenshots

This may already be a known bug but it really sucks not to be able to use the training anymore

### Contact Details

will@willfarrar.net or 302-222-5934

**Comment by lstein** [comment]
Have you tried pressing the little icon in the upper right that looks like `</>` ? It should show you a menu of all the embeddings installed.

**Comment by WhatsUpInTheSky37** [comment]
I went ahead and hit that button.  The only things that are in there are the stock ones that came with it when I installed the latest version.   Usually it picks up my old .pt and learnedembeddings.bin    I ran  a training and was able to complete all of the steps and then when I went to use the embedding it is nowhere to be found.   Anything that I can upload to help?  Anyone else having this issue?

**Comment by pryadchenko** [comment]
Have the same issue on linux. No embeddings loaded

**Comment by razerbeans** [comment]
Having the same issue here, even when attempting to add `learned_embeds.bin` via the model add UI and `invokeai-model-install` using current main branch.

**Comment by razerbeans** [comment]
Just some followup, I did find a potential solution. If I copy the resulting `learned_embeds.bin` file with the name of the embedding to the embeddings directory under the relevant model (e.g. `models/sd-1/embedding`) with the embedding name (e.g. `foo.bin`), it does appear (as an embedding `foo`). So that's kind of a hacky workaround.

**Comment by psychedelicious** [comment]
The model manager was rewritten for v4, if you still are unable to install and use embeddings there please update this issue and we can investigate further.
