### ISSUE TITLE
[bug]: Installation link points to 404

### ISSUE THREAD

**Issue by alfredo-f** [invoke-ai/InvokeAI#4322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cpu

### What version did you experience this issue on?

3.0.2post1

### What happened?

https://invoke-ai.github.io/InvokeAI/installation/ points to a 404

### Screenshots

![image](https://github.com/invoke-ai/InvokeAI/assets/22865959/d9d73136-2732-4f37-9600-8a30b2f40e46)

**Comment by Millu** [comment]
Do you remember how you got to that URL?

**Comment by huiguang-liang** [comment]
404 for me too.

Steps to reproduce:
1. Navigate to https://invoke-ai.github.io/InvokeAI/ ➡️ OK..
2. Click on top navbar to [Installation](https://invoke-ai.github.io/InvokeAI/installation/INSTALLATION/) ➡️ OK.
3. Click on [Docker Installation](https://invoke-ai.github.io/InvokeAI/installation/040_INSTALL_DOCKER/) inside the page (or subsection in left sidebar) ➡️ OK.
4. Top banner says this: 
![image](https://github.com/invoke-ai/InvokeAI/assets/4099058/a63cd2af-3033-438d-96aa-99b0a20ee2b7)
4. Click on "[these instructions](https://invoke-ai.github.io/InvokeAI/installation/040_INSTALL_DOCKER/index.md)" as advised ➡️ 404.

**Comment by alfredo-f** [comment]
Steps to reproduce:

1. Navigate to Quick Start section of the GitHub README (https://github.com/invoke-ai/InvokeAI#quick-start)
2. Click on [InvokeAI Installation Overview](https://invoke-ai.github.io/InvokeAI/installation/) ( https://invoke-ai.github.io/InvokeAI/installation/ )
![image](https://github.com/invoke-ai/InvokeAI/assets/22865959/52b21d75-b680-400f-84d6-a205b67b399d)
3. https://invoke-ai.github.io/InvokeAI/installation/ points to a 404

**Comment by Millu** [comment]
@huiguang-liang @alfredo-f thanks for that! I've updated both those links in #4318
