### ISSUE TITLE
[bug]: gallery reverts to latest image after deleting other images - makes it difficult to delete several images

### ISSUE THREAD

**Issue by tbauknight** [invoke-ai/InvokeAI#4323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

amd

### What version did you experience this issue on?

3.0.2post1

### What happened?

trying to delete multiple images is rendered a royal pain because selection reverts to most recent generation after each deletion - does the same thing using the delete button on each image, so that you have to click back to it to delete it

### Contact Details

tzbauknight@icloud.com

**Comment by Millu** [comment]
This has been fixed in `main` and will be released with 3.1!
