### ISSUE TITLE
[enhancement]: Turn off auto switch to the first top image in the gallery panel

### ISSUE THREAD

**Issue by suonnon** [invoke-ai/InvokeAI#4326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

After I deleted an image from gallery panel, it auto switches back to first image on the top. I think it should be the previous or the next image which nearly to the image that I deleted, instead of switching back to the first top image.

**Comment by psychedelicious** [comment]
This was a bug and fixed in next release
