### ISSUE TITLE
[enhancement]: Add queue for generations/prompts

### ISSUE THREAD

**Issue by 71cj34** [invoke-ai/InvokeAI#4332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

It would be nice to have a queue for generations. For those who make large batches at once or have slow computers that take minutes to make an image, it is essential to be able to queue them so the next queued prompt immediately starts generating. If generations take an exceptional amount of time (eg. very large resolutions, lots of steps, etc), this will allow the generations to be done idle, which is a great for efficiency.

This is the one thing preventing me from switching to InvokeAI- literally everything else is perfect (except that automatically upscaling images after generation would be very, very nice), all the advanced features, the docs, the ease of use, the QoL features, except this one thing. 

### Alternatives

I am new to InvokeAI, so if there is a feature that does this (or the other thing about the upscaling I mentioned), please let me know in the comments. 

### Aditional Content

This is EasyDiffusion's queue, which I was picturing when I write the suggestion:

![image](https://github.com/invoke-ai/InvokeAI/assets/84353892/74735b16-1b91-436c-b282-53bdbf27ea02)

**Comment by psychedelicious** [comment]
I'm very pleased to say that this is in progress in #3995!

We have a few existing requests, going waaaaayyy back to #908. I'm closing this as a duplicate to keep things tidy.
