### ISSUE TITLE
[enhancement]: Node Editor - Drag and drop generated image to auto generate nodes setup

### ISSUE THREAD

**Issue by suonnon** [invoke-ai/InvokeAI#4342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I think this feature will boost up workflow much more faster.
Imagine that I will get the node setup of a generated image by just "drag + drop" the image (from file explorer or invoke gallery) into the node editor (even the image was not generated from node editor UI).
Of course, the images must be generated by InvokeAI or compatible with InvokeAI

**Comment by psychedelicious** [comment]
This will be available in v1 of nodes
