### ISSUE TITLE
[enhancement]: Node Editor - Scrollable when open a list dropdown from a node instead of zooming

### ISSUE THREAD

**Issue by suonnon** [invoke-ai/InvokeAI#4343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I think this improvement would make the editor more user-friendly:
- Whenever opening a list dropdown from a node => Scroll by middle mouse will scroll the list (with mouse hover on it) instead of zooming the editor.

![image](https://github.com/invoke-ai/InvokeAI/assets/133345496/817447e0-4891-494f-9b0d-5d0ebbcdf81a)

**Comment by Millu** [comment]
thanks for the suggestion! @psychedelicious a quick nodes UI/UX improvement suggestion

**Comment by psychedelicious** [comment]
This is resolved in `main` and will be in the release
