### ISSUE TITLE
[bug]: Second pass inpaint/outpaint mask needs to be dilated before blurring

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#4349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

main

### What happened?

The new second pass in canvas inpaint/outpaint uses a blurred mask. The mask needs to be dilated by the blur radius before being blurred, else the infill data shows through at the boundary.

**Comment by blessedcoolant** [comment]
The main question being where do we dilate? If we do it in the color correct node, we save ourselves the pain of adding a couple of extra nodes for pasting back which can be big given how complex these graphs get. But this would mean the color correct node would have some extra functionality that is not exactly related to the node.

**Comment by psychedelicious** [comment]
We could extract the color correction logic to a function and then make a special inpaint correct node that does the dilation
