### ISSUE TITLE
[bug]: ERROR - patchmatch failed to load or compile (Command 'make clean && make' returned non-zero exit status 2.)

### ISSUE THREAD

**Issue by chaorenai** [invoke-ai/InvokeAI#4350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

24G

### What version did you experience this issue on?

 v3.0.2post1

### What happened?

I am using Ubuntu system and installed software through conda. Every time I start up, an error message appears: ERROR - patchmatch failed to load or compile (Command 'make clean && make' returned non-zero exit status 2.)

### Contact Details

yinghanzi@duck.com

**Comment by yinghanzi** [comment]
![Screenshot from 2023-08-24 12-13-23](https://github.com/invoke-ai/InvokeAI/assets/121802291/7c560024-28b5-4d6d-b2a2-002c2e698b6c)

**Comment by Millu** [comment]
If you haven't already, could you run through these steps? https://invoke-ai.github.io/InvokeAI/installation/060_INSTALL_PATCHMATCH/#linux

Note that patch match is not required to use Invoke, but improving inpainting quality and is recommended

**Comment by gardner** [comment]
This occurs on macOS as well. I successfully installed it via the command line:
```bash
$ python3 -m pip install pypatchmatch
Requirement already satisfied: pypatchmatch in ./.venv/lib/python3.11/site-packages (1.0.0)
Requirement already satisfied: numpy in ./.venv/lib/python3.11/site-packages (from pypatchmatch) (1.26.3)
Requirement already satisfied: pillow in ./.venv/lib/python3.11/site-packages (from pypatchmatch) (10.2.0)
Requirement already satisfied: tqdm in ./.venv/lib/python3.11/site-packages (from pypatchmatch) (4.66.1)
```

It still reports an error when loading:
```bash
$ invokeai-web
/Users/gardner/invokeai/.venv/lib/python3.11/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
>> patchmatch.patch_match: INFO - Compiling and loading c extensions from "/Users/gardner/invokeai/.venv/lib/python3.11/site-packages/patchmatch".
>> patchmatch.patch_match: ERROR - patchmatch failed to load or compile (Command 'make clean && make' returned non-zero exit status 2.).
>> patchmatch.patch_match: INFO - Refer to https://invoke-ai.github.io/InvokeAI/installation/060_INSTALL_PATCHMATCH/ for installation instructions.
[2024-01-07 15:20:50,815]::[InvokeAI]::INFO --> Patchmatch not loaded (nonfatal)
[2024-01-07 15:20:53,063]::[uvicorn.error]::INFO --> Started server process [73978]
```

**Comment by psychedelicious** [comment]
Closing as the OP hasn't reported back

**Comment by manumaan** [comment]
This link does not work :  https://invoke-ai.github.io/InvokeAI/installation/060_INSTALL_PATCHMATCH/#linux

**Comment by manumaan** [comment]
I am getting this error on MacOS 14.7 and I already have opencv installed. 

>> patchmatch.patch_match: INFO - Compiling and loading c extensions from "/Users/mansnitz/invokeai/.venv/lib/python3.11/site-packages/patchmatch".
>> patchmatch.patch_match: ERROR - patchmatch failed to load or compile (Command 'make clean && make' returned non-zero exit status 2.).
>> patchmatch.patch_match: INFO - Refer to https://invoke-ai.github.io/InvokeAI/installation/060_INSTALL_PATCHMATCH/ for installation instructions.
[2024-11-08 13:26:09,498]::[InvokeAI]::INFO --> Patchmatch not loaded (nonfatal)

**Comment by BenRoe** [comment]
I have the same problem. 
Mac M1 OSX15.3.1, InvokeAI v5.8.1 

Followed the instructions from the [docs](https://invoke-ai.github.io/InvokeAI/installation/patchmatch/#macintosh) and installed `brew install opencv`.
Also installed `brew install pkg-config` as mentioned [above](https://github.com/invoke-ai/InvokeAI/issues/4350#issuecomment-1879917319).

```
Starting up...
Started Invoke process with PID: 2805
>> patchmatch.patch_match: INFO - Compiling and loading c extensions from "/Users/ben/Documents/InvokeAI/.venv/lib/python3.11/site-packages/patchmatch".
>> patchmatch.patch_match: ERROR - patchmatch failed to load or compile (Command 'make clean && make' returned non-zero exit status 2.).
>> patchmatch.patch_match: INFO - Refer to https://invoke-ai.github.io/InvokeAI/installation/060_INSTALL_PATCHMATCH/ for installation instructions.
[2025-03-19 10:43:06,846]::[InvokeAI]::INFO --> Patchmatch not loaded (nonfatal)

```
