### ISSUE TITLE
[enhancement]: "Use All" should include VAE, precision & LoRA 

### ISSUE THREAD

**Issue by Millu** [invoke-ai/InvokeAI#4358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

The "Use All" feature should auto-fill all relevant parameters of the image generation process. 

This should include:

* VAE
* VAE precision
* LoRAs

Ideally ControlNets would also be captured, but this is more difficult as we do no currently store the processed control net image

**Comment by Malrama** [comment]
I have already reported this issue here https://github.com/invoke-ai/InvokeAI/issues/4167 2 weeks ago.
Sadly, I haven't received any reaction. I really hope this gets resolved soon because it's really hindering my work process :/

**Comment by Millu** [comment]
Thanks - I thought there was an issue but wasn't able to find it - I'll close this a duplicate of #4167
