### ISSUE TITLE
[bug]: Deleting an image when it is belongs to a board, won't delete from output the folder. 

### ISSUE THREAD

**Issue by BartaG512** [invoke-ai/InvokeAI#4368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

InvokeAI v3.0.2post1

### What happened?

When attempting to delete an image that is associated with a board, the image is removed from the board but remains present in the output folder. This inconsistency in the deletion process can lead to confusion and clutter in the output folder over time.

Steps to Reproduce:

1. Create a new board or access an existing board.
2. Add an image to the board.
3. Attempt to delete the image from the board.
4. Check the output folder where the images associated with the board are stored.

Expected Behavior:
When an image is deleted from a board, it should also be removed from the output folder to maintain consistency between the board interface and the physical storage location. This ensures that users can confidently manage their board's content without worrying about lingering files in the output directory.

Current Behavior:
Currently, when an image is deleted from a board, it is only removed from the board interface and not from the output folder where the images are stored. As a result, the deleted image remains in the output directory.

**Comment by BartaG512** [comment]
Sorry. My mistake I just realized that I had forgotten about the intermediary files located in the same folder, and I had mistakenly identified them as the image I intended to delete.

**Comment by Millu** [comment]
Glad to hear! Going to go ahead and close this.
