### ISSUE TITLE
[system crash]: startup crashes windows

### ISSUE THREAD

**Issue by dynatron832** [invoke-ai/InvokeAI#4373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24

### What version did you experience this issue on?

3.0.2 Post1

### What happened?

installed with the installer package. after that is the configuration/downloads.
if i start invoke via the bat and chose the web option the script came to "Starting the InvokeAI browser-based UI.." then the the window froze. after a few seconds the whole system freezes completly. and a few seconds after that windows produces a blue screen. "DPC_Watchdog_Violation"

edit:
an older version of invoke v2.3.5P2 still works. have tryed v3.0.2 same crash result

anybody any idea where this came from ? everything other works fine so far. A1111/Comfy

**Comment by psychedelicious** [comment]
From my searching, this error is typically related to corrupted or outdated drivers. Please update your GPU drivers, restart, and try again.

**Comment by dynatron832** [comment]
interesting idea ...the driver´s ...problem is ...theyre not to old.
had confirmed that on a other system. same driver version and it´s running. after that i asumed some hardware incompatibility with my main system. so i installed a full fresh windows on a secondary disk. installed the minimalist stuff to run invoke. drivers, (still old one) chipset driver, python, win runtime stuff and then invoke. and it works. there was a slightly issue with a missing packet. invoke wont download at startup. telling me something about certificates. turns out "certifi" has to be updated. done that and after that invoke get it´s last files and runs. no crash nothing. on the same hardware where it crashes with the other windows.

then on the "faulty" windows i cleaned the nvidia drivers. Display Driver Uninstaller DDU tool. then installed the same drivers again ...and tested invoke ...still crashing with the same behavior. so ...it´s still windows. thinking of it i deinstalled another tool which may be could have something todo with that. it´s an multi monitor manager. but this thing has ton´s of stuff inside which i dont need. it´s not starting with windows ...but it can potentially change a lot of stuff. all nearly related to gpu stuff. the only reason i have this is to change the monitor configuration (one off or on). but it turn´s out this was also not the problem candidate. and at the moment i have no other idea.

the only way seems to be install windows new. maybe i do that in a while. but if i do so ...and installed all the stuff again iam using ...maybe i reinstall some problem candidate again. and i dont know which one it is.

b.t.w. invoke 3.1.0 crashes also

**Comment by psychedelicious** [comment]
It's related to some configuration or whatever is installed with the affected install of windows. I know you said the drivers are not old, but a driver update and/or reinstall is as much help as we can give you.

**Comment by dynatron832** [comment]
okay ...i give it a try. installed the newest ...and that is v537.13 ...make a reboot and try invoke ...aaaaaaaaanddd ...no. it still crashes happily.
and if i already wasting my time with this annoying issue i got into the cleaner windows and try´ed to install a few "things" which might cause this issue because on my working windows i use them. aaaaaaaand ....no. nothing brings the same crash. invoke starts and it runs as it should be. it´s not everything i could install if i fully reinstall windows and everything i want to use.

is there no log function which i can activate and maybe see what exactly invoke try´s todo at the crash moment ? 

was the question i would like to ask ...but google was a little bit faster ...even if this seems not to work.
if found https://invoke-ai.github.io/InvokeAI/features/LOGGING/ this one. sounds nice ...but dont work ...or iam not able to bring it to work.

if i try this on my working windows (the crashy one) ...putting  "--log_handlers console syslog=/dev/log file=C:\temp\invokeai.log" to the start parameters ...i got ...a crash ...like all the other too. but thats interesting. sooooo ....i asking myself. what would a written log look like if invoke startup and dont crashes ? so i go to my testing windows (the working one) and try´ed that again. this time it vomit a bunch of errors an getting back to the startup choise. but theres some line that say´s syslog is not aviable on my system. yeah ...whatever. would be toooooo easy hmm ? but ...if invoke exited AND telling me theres an problem ...and not crashing to bluescreen ...why did the working pc version of invoke dont tells me that syslog is not aviable ? this one crashes and say nothing ? what did he even doing to crash "before" he is able to tell me syslog is not an option and exiting without crashing ?

so ...logging seems to be no help ? what now ? ...now. if invoke startup´s it tells me some "patchmatch" is loaded. one the crashing windows i never saw this message. so ...did it fail at loading patchmacht ? ahh ...okay ...and ...hey google ...what is patchmatch ? 

https://invoke-ai.github.io/InvokeAI/installation/060_INSTALL_PATCHMATCH/

interesting ...so ...what would invoke do if i delete the folder calles patchmatch ? vomit a bunch of errors again ? yeah ...ok. that was not nice. but ...on the invoke doku it say´s "It is not needed to run InvokeAI" ...ohh okay. and why it exitet happily with a bunch of errors ? now ...whatever.

i try´ed this on my crashing windows. delete that folder and hoping invoke would produce the same. exiting with a bunch of errors. but not crashing because it cant load it. but noooo ...invoke crashes as if nothing happened. but that tells me two thing. one ...it´s not the load of patchmatch which caused the crash. two ...it´s not the state where the invoke exe is able to exit correctly because it´s finaly noticed that it cant go on because syslog is not aviable.

so ...what try´es invoke todo before the loading of patchmatch ? and before the syslog fail exiting ?

**Comment by dynatron832** [comment]
okay ...i give it a try. installed the newest ...and that is v537.13 ...make a reboot and try invoke ...aaaaaaaaanddd ...no. it still crashes happily.
and if i already wasting my time with this annoying issue i got into the cleaner windows and try´ed to install a few "things" which might cause this issue because on my working windows i use them. aaaaaaaand ....no. nothing brings the same crash. invoke starts and it runs as it should be. it´s not everything i could install if i fully reinstall windows and everything i want to use.

is there no log function which i can activate and maybe see what exactly invoke try´s todo at the crash moment ? 

was the question i would like to ask ...but google was a little bit faster ...even if this seems not to work.
if found https://invoke-ai.github.io/InvokeAI/features/LOGGING/ this one. sounds nice ...but dont work ...or iam not able to bring it to work.

if i try this on my working windows (the crashy one) ...putting  "--log_handlers console syslog=/dev/log file=C:\temp\invokeai.log" to the start parameters ...i got ...a crash ...like all the other too. but thats interesting. sooooo ....i asking myself. what would a written log look like if invoke startup and dont crashes ? so i go to my testing windows (the working one) and try´ed that again. this time it vomit a bunch of errors an getting back to the startup choise. but theres some line that say´s syslog is not aviable on my system. yeah ...whatever. would be toooooo easy hmm ? but ...if invoke exited AND telling me theres an problem ...and not crashing to bluescreen ...why did the working pc version of invoke dont tells me that syslog is not aviable ? this one crashes and say nothing ? what did he even doing to crash "before" he is able to tell me syslog is not an option and exiting without crashing ?

so ...logging seems to be no help ? what now ? ...now. if invoke startup´s it tells me some "patchmatch" is loaded. one the crashing windows i never saw this message. so ...did it fail at loading patchmacht ? ahh ...okay ...and ...hey google ...what is patchmatch ? 

https://invoke-ai.github.io/InvokeAI/installation/060_INSTALL_PATCHMATCH/

interesting ...so ...what would invoke do if i delete the folder calles patchmatch ? vomit a bunch of errors again ? yeah ...ok. that was not nice. but ...on the invoke doku it say´s "It is not needed to run InvokeAI" ...ohh okay. and why it exitet happily with a bunch of errors ? now ...whatever.

i try´ed this on my crashing windows. delete that folder and hoping invoke would produce the same. exiting with a bunch of errors. but not crashing because it cant load it. but noooo ...invoke crashes as if nothing happened. but that tells me two thing. one ...it´s not the load of patchmatch which caused the crash. two ...it´s not the state where the invoke exe is able to exit correctly because it´s finaly noticed that it cant go on because syslog is not aviable.

so ...what try´es invoke todo before the loading of patchmatch ? and before the syslog fail exiting ?

**Comment by psychedelicious** [comment]
I'm sorry, that's a lot of text and it's not clear what is being asked. Can you please sum it up in a sentence or two?

**Comment by dynatron832** [comment]
at the startup of invoke web mode. what is the exe doing before the console is typing that he loads patchmatch ?

**Comment by psychedelicious** [comment]
If I understand your question, the application is attempting to compile the PatchMatch library, which is used for outpainting. There is no `exe`, it's a python script.

You've mentioned some errors. Please copy and paste any errors here so we can review them.

**Comment by psychedelicious** [comment]
Sorry for the late reply. The exe simply runs the python application. If you still have this same problem on the latest release (v4.1.0), please copy the terminal output including error messages and comment on this issue. We can investigate further with more information.
