### ISSUE TITLE
[enhancement]: Turn off the selecting newest image

### ISSUE THREAD

**Issue by DataJuggler** [invoke-ai/InvokeAI#4377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

corby@datajuggler.com

### What should this feature add?

Between version 3.0.0 and 3.0.1, you changed the (local) website to automatically select the most recent image.

If I want to delete all the old images, except the newest, I have to click each image separately, because you auto select the most recent. Sometimes you select the newest one after I select an old one to delete.

Also, a way to delete all images would be nice. If I want to delete 100 images, I ahve to click delete 100 times. Even deleting the images out of the output folder doesn't delete.

And finally, where do you store the last prompt, or prompt history? I sometimes want to delete everything, and you show the last prompt when I open the app again.

### Alternatives

There is no alternative, just stop selecting the last one. Or make it a checkbox 'Restore Last Image' and leave it off if not checked.

**Comment by psychedelicious** [comment]
What version of the application are you using? There was a bug that caused the most recent image to be selected, which was fixed in I believe 3.0.2, or 3.1.0 (latest). If you are not already on the latest version, please update and try again.

**Comment by DataJuggler** [comment]
OK, I will. Thank you.

**Comment by DataJuggler** [comment]
I upgraded, and now I get Server Error every time. I also ran 7 to fix install errors. How do I uninstall?

**Comment by psychedelicious** [comment]
To get the full error message, please:
- [Open your browser's JavaScript console](https://webmasters.stackexchange.com/a/77337)
- Find the red error message at the bottom of the console's output
- Right click the `Object` -> `Copy Object`
- Paste the object here

**Comment by DataJuggler** [comment]
Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
index-deaa1f26.js:136   error  [session]: Problem creating session Object
(anonymous) @ index-deaa1f26.js:136

**Comment by psychedelicious** [comment]
That's not the object. Make sure you right click object and select copy object. It includes the exact error message along with additional context.

**Comment by DataJuggler** [comment]
I don't see the word object anywhere.  I was happy 3.0.1.

**Comment by psychedelicious** [comment]
Here's where to click in Firefox:
https://github.com/invoke-ai/InvokeAI/assets/4822129/84c0cdd7-be1f-48f3-b6af-01c1ebcb6092

And in Chrome:
https://github.com/invoke-ai/InvokeAI/assets/4822129/1940d5ad-cac9-42b1-818e-27d0a6f20e90

Please provide a screenshot if you see something different.

Also, you are free of course to uninstall and re-install the older version, all of which are available here: https://github.com/invoke-ai/InvokeAI/releases

**Comment by DataJuggler** [comment]
I am using Edge. I already put 3.0.2 on, and it works. Something broke between 3.0.2 and 3.1.0.

**Comment by psychedelicious** [comment]
I understand. I'm trying to help but we need the full error message. Please provide a screenshot of your browser console so I can direct you on how to get the error.

**Comment by DataJuggler** [comment]
I already have a working version installed.

**Comment by DataJuggler** [comment]
Is this what you want?

![image](https://github.com/invoke-ai/InvokeAI/assets/26331133/834cd126-b0bf-4a79-b345-05f030f8aa32)

**Comment by psychedelicious** [comment]
Yes. I do see "Object". Maybe you missed it the first time. Right click that and click Copy Object. That gets the full error.

**Comment by DataJuggler** [comment]
I am just a few steps above blind. I do not see objects.
      
        
        
          On Sep 2 2023, at 11:14 pm, psychedelicious ***@***.***> wrote:
          
        
        
          
Yes. I do see "Object". Maybe you missed it the first time. Right click that and click Copy Object. That gets the full error.

**Comment by psychedelicious** [comment]
![image](https://github.com/invoke-ai/InvokeAI/assets/4822129/16b25450-159c-40af-9751-1e2c4d8fc0bb)

You should see a "copy object" option when right clicking this.

**Comment by DataJuggler** [comment]
I looked this morning, and it not longer shows me any errors, because I am using 3.0.2 now.

**Comment by psychedelicious** [comment]
Ok. I'm closing this then. If you have this issue in the future, please follow the instructions provided to give us the full error message.
