### ISSUE TITLE
[bug]: CMD path for suggested pip upgrade incorrect

### ISSUE THREAD

**Issue by itisnot-me** [invoke-ai/InvokeAI#4396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.0.2

### What happened?

When using the cmd to install there is a suggestion to upgrade the pip to the latest. But when the installer goes about to install the the upgraded pip its calling a different folder. See screenshots

In order to work around this i need to manually upgrade the pip in a different cmd window before continuing. 

### Screenshots

![pip](https://github.com/invoke-ai/InvokeAI/assets/711771/b9f0d4da-0d7a-43c4-a1ff-b17a749c7769)
![pip2](https://github.com/invoke-ai/InvokeAI/assets/711771/33cf655f-7976-4905-acda-c596f4db5b49)

**Comment by Sirachosur** [comment]
Have you tried to run the command under the 'developer prompt'?  Places you in the right python virtual environment.

**Comment by dashinja** [comment]
Same issue.

**Comment by itisnot-me** [comment]
> Same issue.

Short from copying the command in another cmd window it seems that the installer has a issue with other temp folders in the temp directory. You can manually go in and remove all temp folders for it to work correctly

**Comment by dashinja** [comment]
> > Same issue.
> 
> Short from copying the command in another cmd window it seems that the installer has a issue with other temp folders in the temp directory. You can manually go in and remove all temp folders for it to work correctly

Sorry, temp folders where exactly?

**Comment by itisnot-me** [comment]
> > > Same issue.
> > 
> > 
> > Short from copying the command in another cmd window it seems that the installer has a issue with other temp folders in the temp directory. You can manually go in and remove all temp folders for it to work correctly
> 
> Sorry, temp folders where exactly?

C:\Users\YOURUSERACCOUNT\AppData\Local\Temp\

Then delete any invoke folder. They should really fix this as it took a long time to figure out

**Comment by itisnot-me** [comment]
WHY IS IT CLOSING WITH EVERY COMMENT.

**Comment by dashinja** [comment]
Unfortunately still a fail for me. I also searched entire computer for all such directories, not just %AppData%\Local\Temp and even cleared the entire Temp folder in question. meh.

**Comment by psychedelicious** [comment]
You don't need to update pip unless there is a problem with pip during installation. You can ignore the warning.
