### ISSUE TITLE
[bug]: RangeError: Invalid array length

### ISSUE THREAD

**Issue by aniketgore** [invoke-ai/InvokeAI#4405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

24 GB

### What version did you experience this issue on?

3.1

### What happened?

Generated an image using a custom SDXL model, and when sent it to unified canvas from text to image facing this issue

### Screenshots

![image](https://github.com/invoke-ai/InvokeAI/assets/22811139/ddf4e9cc-f749-418e-856b-e65f4655d20d)

**Comment by psychedelicious** [comment]
Can you please click Copy Error and paste there error here?

**Comment by NeuralBlankes** [comment]
Got the same error with send image to unified canvas, this is the copy/paste of the error:

```
{
  "name": "RangeError",
  "message": "Invalid array length",
  "stack": "RangeError: Invalid array length\n    at PN (http://127.0.0.1:9090/assets/App-d1567775.js:1:6825)\n    at http://127.0.0.1:9090/assets/App-d1567775.js:1:7023\n    at http://127.0.0.1:9090/assets/App-d1567775.js:89:12214\n    at _f (http://127.0.0.1:9090/assets/App-d1567775.js:70:20938)\n    at pC (http://127.0.0.1:9090/assets/App-d1567775.js:70:27593)\n    at fC (http://127.0.0.1:9090/assets/App-d1567775.js:70:27449)\n    at K8 (http://127.0.0.1:9090/assets/App-d1567775.js:70:26990)\n    at Z8 (http://127.0.0.1:9090/assets/App-d1567775.js:70:38492)\n    at pi (http://127.0.0.1:9090/assets/App-d1567775.js:70:37859)\n    at xC (http://127.0.0.1:9090/assets/App-d1567775.js:70:34499)"
}
```
