### ISSUE TITLE
[bug]: The UI of invokeai deployment on GKE shows disconnected

### ISSUE THREAD

**Issue by YeYuanS** [invoke-ai/InvokeAI#4409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

32GB

### What version did you experience this issue on?

v3.0.1

### What happened?

The v3.0.1 Invokeai application deployed on GKE shows disconnected on the top right corner. I can see it's able to load the models and images while the `invoke` button greyed out. The same docker image I used to deploy on GCP VM works without issue. 

The pod on GKE is able to access the internet 
```
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: icmp_seq=0 ttl=114 time=0.821 ms
64 bytes from 8.8.8.8: icmp_seq=1 ttl=114 time=0.418 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=114 time=0.391 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=114 time=0.344 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=114 time=0.396 ms
64 bytes from 8.8.8.8: icmp_seq=5 ttl=114 time=0.364 ms
64 bytes from 8.8.8.8: icmp_seq=6 ttl=114 time=0.384 ms
```
I'm wondering anyone has experienced the same issue and is there anything else I should look into to debug? 
The v2.3 invokeai works fine on GKE

Here is what I have done:
1. Build the dockerfile locally on windows system, hardcode it to pip install [.xformers]
2. Deploy on GKE with the docker image built from step 1
![Screenshot 2023-08-31 144303](https://github.com/invoke-ai/InvokeAI/assets/41984177/828b6d82-975b-428e-b579-cdbec1051834)

**Comment by psychedelicious** [comment]
The disconnected status refers to the socket.io connectivity. I'm not sure how to help you troubleshoot further on a platform like GKE, sorry.

**Comment by YeYuanS** [comment]
My suspicion is the version of packages since v2.3 invokeai works on gke.  Just confirm socketio you mentioned are installed from these lines so I can do some experiments by changing the versions? 
```
"fastapi-socketio==0.0.10",
"flask_socketio==5.3.0",
````

**Comment by tylenwells** [comment]
Hello! 

Taking a look, but could you confirm if this is the same issue that was seen in the following? https://github.com/invoke-ai/InvokeAI/issues/3693

If so this should be solved by rebuilding your image to 3.0.2a1 or later.

**Comment by ebr** [comment]
Are you using a reverse proxy / ingress controller in your GKE deployment? as @tylenwells mentioned, support for secure websockets has been added in 3.0.2, but you do need to ensure that your ingress correctly terminates TLS connections

**Comment by ebr** [comment]
Closing this as stale; please open a new issue if the problem is still being experienced
