### ISSUE TITLE
[bug]: Output directory resetting

### ISSUE THREAD

**Issue by Void2258** [invoke-ai/InvokeAI#4410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12gb

### What version did you experience this issue on?

3.1.0

### What happened?

When using option 6 (startup config), output directory is always reset to the default (invoke folder/output). This breaks the gallery badly, even if fixed later.

### Additional context

Additionally, a simple way to fix the gallery is needed, since it seems to only be working with one folder at a time.

**Comment by badarotti** [comment]
This also happens in an Ubuntu 22.04 VM with 3060 12G GPU, InvokeAI v3.3.
Thanks.

**Comment by psychedelicious** [comment]
We no longer have a configure script. The outputs dir is configured in the `invokeai.yaml` file. Please create a new issue if the problem persisted with the latest release (v4.1.0)
