### ISSUE TITLE
[bug]: Error while finding module specification for 'invokeai.frontend.install.invokeai_update' (ModuleNotFoundError: No module named 'invokeai')

### ISSUE THREAD

**Issue by FRiMN** [invoke-ai/InvokeAI#4411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

8Gb

### What version did you experience this issue on?

3.0.2post1

### What happened?

Just tried to update InvokeAI by invoke.sh script. Choose 9 (Update InvokeAI), and then see next error:
```
Update InvokeAI
/home/frimn/stable_diffusion/InvokeAI/.venv/bin/python: Error while finding module specification for 'invokeai.frontend.install.invokeai_update' (ModuleNotFoundError: No module named 'invokeai')
```

**Comment by Millu** [comment]
Looks like it's not finding the previously installed version of InvokeAI. The easiest solve is to reinstall InvokeAI in the same location as the old one. This will retain all old images & models.

**Comment by HaraldWerner** [comment]
I did a reinstall into the same folder, but lost all metadata on the old images in the process (i can't use any of the "use seed", "use prompt", "upscale" options on images generated on the old install). Is there any way to restore those?

**Comment by FRiMN** [comment]
Thanks, it seems to be working, I reinstalled the new version. But I also ran 7 (fix installation) after reinstall.

**Comment by Millu** [comment]
@grunblatt-git what version did you reinstall from?

**Comment by grunblatt-git** [comment]
I installed version 3.1.0 over the existing 3.0.1 install.

By now i "fixed" the issue by doing a clean new install (to a new folder) of version 3.1.1 and copied the database and all output images and latents to the new location. That restored the metadata as well for some reason.

**Comment by AlexNolasco** [comment]
this worked for me 
```
pip install invokeai
```

be sure you have activated your env through `venv` or `anaconda`

**Comment by fat-tire** [comment]
FWIW I had this issue by updating to 4.0.0 rc6 or something and just replaced `invokeai_update.py` by doing this:

`cd /invokeai/.venv/lib/python3.10/site-packages/invokeai/frontend/install`

Then:

`wget https://raw.githubusercontent.com/invoke-ai/InvokeAI/v4.0.0rc5/invokeai/frontend/install/invokeai_update.py`

That puts the file back.  No clue why it disappeared to begin with but at that point I was able to do an update to 4.0.3 and it's up and running.
