### ISSUE TITLE
[bug]: Error in sys.excepthook

### ISSUE THREAD

**Issue by Asfandyar-Khan-2022** [invoke-ai/InvokeAI#4416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24GB

### What version did you experience this issue on?

3.1.0

### What happened?

I've been stuck on the last step of getting invokeAI to work. I've installed everything correctly but for some reason I keep getting the sys.excepthook error. I've reinstalled and reset my pc with different versions of python and still no success. I've also changed the directory of the installation file. At this point I'm out of ideas and the error does not tell me much to go off. I assume the problem is this python but i'm not sure.

I've also tried installing using both methods (through cmd and using installation file) described. They both end up giving me the same error.

### Screenshots

![image](https://github.com/invoke-ai/InvokeAI/assets/117299102/e79f28b6-577a-4e8e-b372-705ba4256a00)

**Comment by Millu** [comment]
Are you installing in a venv?

**Comment by Asfandyar-Khan-2022** [comment]
Yean I created a venv as instructed. Still had no luck.

**Comment by mgallacher-cbre** [comment]
I get this error as well.  I did an automatic install of 3.1.0 on Windows 11/CUDA/24GB.  I did the registry change and verified the C++ distro.  The installation had no issues.   I am calling invoke.bat and selecting option 1.

**Comment by wbecher** [comment]
> I get this error as well. I did an automatic install of 3.1.0 on Windows 11/CUDA/24GB. I did the registry change and verified the C++ distro. The installation had no issues. I am calling invoke.bat and selecting option 1.

I have the same scenario... only difference is the GPU RAM. I was using the old invokeai version without any problem.

**Comment by lstein** [comment]
It looks like a pretty low-level issue with your Python install, or possibly a broken library.

With the venv activated, could you run `python -V` to verify the python version (please paste it), and then `python -c "print('hello world')"` to verify basic functionality?

If these work, then try:

```
invokeai-web —log_level debug
```

Another potential cause of the problem is a broken library in the `pip` cache which keeps getting reinstalled. You could try clearing your pip cache by following the directions here: https://linuxhandbook.com/clear-pip-cache/ and then reinstalling.

**Comment by wbecher** [comment]
> It looks like a pretty low-level issue with your Python install, or possibly a broken library.
> 
> With the venv activated, could you run `python -V` to verify the python version (please paste it), and then `python -c "print('hello world')"` to verify basic functionality?
> 
> If these work, then try:
> 
> ```
> invokeai-web —log_level debug
> ```
> 
> Another potential cause of the problem is a broken library in the `pip` cache which keeps getting reinstalled. You could try clearing your pip cache by following the directions here: https://linuxhandbook.com/clear-pip-cache/ and then reinstalling.

THIS! I cleared the pip cache and reinstalled InvokeAI.

Thank you @lstein !

**Comment by Asfandyar-Khan-2022** [comment]
in venv

![Screenshot 2023-09-08 141842](https://github.com/invoke-ai/InvokeAI/assets/117299102/e6d22c4a-7ff4-4466-8b75-4ed8701d2bac)

Version of python.

![Screenshot 2023-09-08 144207](https://github.com/invoke-ai/InvokeAI/assets/117299102/0c8c2c85-5b6c-488d-9bae-25cf223889b1)

print hello

![Screenshot 2023-09-08 144301](https://github.com/invoke-ai/InvokeAI/assets/117299102/25ef3f25-c838-454b-95cb-157f6484fa83)

debug shows the following

![Screenshot 2023-09-08 144355](https://github.com/invoke-ai/InvokeAI/assets/117299102/b3282d1d-3aa9-4b8b-8e5c-70a8c6d0a7d3)

**Comment by Asfandyar-Khan-2022** [comment]
Finally got it working. Decided to use Conda to create my virtual env rather than following the steps as shown. 

Turns out it was the environment. For some reason creating an environment using Windows CMD just caused a lot of issues.

Conda is installed on my Git Bash. Operating system is windows 11. Tried with python 3.11 with InvokeAI version 3.1.0.
