### ISSUE TITLE
[bug]: Nodes: Collection Primitives don't have inputs

### ISSUE THREAD

**Issue by bldrnnr** [invoke-ai/InvokeAI#4422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### What version did you experience this issue on?

3.1.0

### What happened?

When adding any Collection Primitive, except the "Image Collection Primitive", to the Workflow Editor the Nodes don't have the collection input.
When changing the `ui_type` in the `InputField` to `UIType.Collection` the input is displayed with "Unknown field type" but cannot be connected to anything.

### Screenshots

<img width="636" alt="Bildschirmfoto 2023-09-01 um 11 56 10" src="https://github.com/invoke-ai/InvokeAI/assets/53077010/04cc5747-1896-4c6e-9914-1e1dde31d952">

**Comment by psychedelicious** [comment]
This is resolved in #4423
