### ISSUE TITLE
[bug]: Server Error Validation Error

### ISSUE THREAD

**Issue by VladimirPozdnyakov** [invoke-ai/InvokeAI#4428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.1.0

### What happened?

Error when I click on the Invoke button.

### Screenshots

![изображение](https://github.com/invoke-ai/InvokeAI/assets/49595925/9b4eb0cc-2f1f-49ce-bc44-59c99ac2f51e)

### Additional context

{
"graph": {
"graph": {
"id": "text_to_image_graph",
"nodes": {
"positive_conditioning": {
"type": "compel",
"id": "positive_conditioning",
"prompt": "masterpiece, high quality, best quality, 4k, super detail, potion in a glass bottle",
"is_intermediate": true
},
"negative_conditioning": {
"type": "compel",
"id": "negative_conditioning",
"prompt": "",
"is_intermediate": true
},
"noise": {
"type": "noise",
"id": "noise",
"width": 832,
"height": 832,
"use_cpu": true,
"is_intermediate": true
},
"text_to_latents": {
"type": "t2l",
"id": "text_to_latents",
"is_intermediate": true,
"cfg_scale": 7,
"scheduler": "dpmpp_2m_k",
"steps": 20
},
"main_model_loader": {
"type": "main_model_loader",
"id": "main_model_loader",
"is_intermediate": true,
"model": {
"model_name": "meinamix_meinaV11",
"base_model": "sd-1",
"model_type": "main"
}
},
"clip_skip": {
"type": "clip_skip",
"id": "clip_skip",
"skipped_layers": 2,
"is_intermediate": true
},
"latents_to_image": {
"type": "l2i",
"id": "latents_to_image",
"fp32": true
},
"metadata_accumulator": {
"id": "metadata_accumulator",
"type": "metadata_accumulator",
"generation_mode": "txt2img",
"cfg_scale": 7,
"height": 832,
"width": 832,
"positive_prompt": "masterpiece, high quality, best quality, 4k, super detail, potion in a glass bottle",
"negative_prompt": "",
"model": {
"model_name": "meinamix_meinaV11",
"base_model": "sd-1",
"model_type": "main"
},
"seed": 0,
"steps": 20,
"rand_device": "cpu",
"scheduler": "dpmpp_2m_k",
"vae": {
"model_name": "vae-ft-mse-840000-ema-pruned.vae",
"base_model": "sd-1"
},
"controlnets": [],
"loras": [
{
"lora": {
"model_name": "add_detail",
"base_model": "sd-1"
},
"weight": 1
}
],
"clip_skip": 2
},
"lora_loader_add_detail": {
"type": "lora_loader",
"id": "lora_loader_add_detail",
"is_intermediate": true,
"lora": {
"model_name": "add_detail",
"base_model": "sd-1"
},
"weight": 1
},
"vae_loader": {
"type": "vae_loader",
"id": "vae_loader",
"is_intermediate": true,
"vae_model": {
"model_name": "vae-ft-mse-840000-ema-pruned.vae",
"base_model": "sd-1"
}
},
"iterate": {
"id": "iterate",
"type": "iterate",
"is_intermediate": true
},
"range_of_size": {
"id": "range_of_size",
"type": "range_of_size",
"is_intermediate": true,
"size": 1,
"step": 1
},
"rand_int": {
"id": "rand_int",
"type": "rand_int",
"is_intermediate": true
}
},
"edges": [
{
"source": {
"node_id": "main_model_loader",
"field": "clip"
},
"destination": {
"node_id": "clip_skip",
"field": "clip"
}
},
{
"source": {
"node_id": "positive_conditioning",
"field": "conditioning"
},
"destination": {
"node_id": "text_to_latents",
"field": "positive_conditioning"
}
},
{
"source": {
"node_id": "negative_conditioning",
"field": "conditioning"
},
"destination": {
"node_id": "text_to_latents",
"field": "negative_conditioning"
}
},
{
"source": {
"node_id": "text_to_latents",
"field": "latents"
},
"destination": {
"node_id": "latents_to_image",
"field": "latents"
}
},
{
"source": {
"node_id": "noise",
"field": "noise"
},
"destination": {
"node_id": "text_to_latents",
"field": "noise"
}
},
{
"source": {
"node_id": "metadata_accumulator",
"field": "metadata"
},
"destination": {
"node_id": "latents_to_image",
"field": "metadata"
}
},
{
"source": {
"node_id": "main_model_loader",
"field": "unet"
},
"destination": {
"node_id": "lora_loader_add_detail",
"field": "unet"
}
},
{
"source": {
"node_id": "clip_skip",
"field": "clip"
},
"destination": {
"node_id": "lora_loader_add_detail",
"field": "clip"
}
},
{
"source": {
"node_id": "lora_loader_add_detail",
"field": "unet"
},
"destination": {
"node_id": "text_to_latents",
"field": "unet"
}
},
{
"source": {
"node_id": "lora_loader_add_detail",
"field": "clip"
},
"destination": {
"node_id": "positive_conditioning",
"field": "clip"
}
},
{
"source": {
"node_id": "lora_loader_add_detail",
"field": "clip"
},
"destination": {
"node_id": "negative_conditioning",
"field": "clip"
}
},
{
"source": {
"node_id": "vae_loader",
"field": "vae"
},
"destination": {
"node_id": "latents_to_image",
"field": "vae"
}
},
{
"source": {
"node_id": "range_of_size",
"field": "collection"
},
"destination": {
"node_id": "iterate",
"field": "collection"
}
},
{
"source": {
"node_id": "iterate",
"field": "item"
},
"destination": {
"node_id": "noise",
"field": "seed"
}
},
{
"source": {
"node_id": "iterate",
"field": "item"
},
"destination": {
"node_id": "metadata_accumulator",
"field": "seed"
}
},
{
"source": {
"node_id": "rand_int",
"field": "a"
},
"destination": {
"node_id": "range_of_size",
"field": "start"
}
}
]
}
},
"status": 422,
"error": {
"detail": [
{
"loc": [
"body",
"nodes",
"text_to_latents"
],
"msg": "No match for discriminator 'type' and value 't2l' (allowed values: 'boolean', 'boolean_collection', 'integer', 'integer_collection', 'float', 'float_collection', 'string', 'string_collection', 'image', 'image_collection', 'latents', 'latents_collection', 'color', 'conditioning', 'conditioning_collection', 'controlnet', 'image_processor', 'main_model_loader', 'lora_loader', 'sdxl_lora_loader', 'vae_loader', 'seamless', 'metadata_accumulator', 'range', 'range_of_size', 'random_range', 'compel', 'sdxl_compel_prompt', 'sdxl_refiner_compel_prompt', 'clip_skip', 'cv_inpaint', 'show_image', 'blank_image', 'img_crop', 'img_paste', 'tomask', 'img_mul', 'img_chan', 'img_conv', 'img_blur', 'img_resize', 'img_scale', 'img_lerp', 'img_ilerp', 'img_nsfw', 'img_watermark', 'mask_edge', 'mask_combine', 'color_correct', 'img_hue_adjust', 'img_luminosity_adjust', 'img_saturation_adjust', 'infill_rgba', 'infill_tile', 'infill_patchmatch', 'infill_lama', 'scheduler', 'create_denoise_mask', 'denoise_latents', 'l2i', 'lresize', 'lscale', 'i2l', 'lblend', 'add', 'sub', 'mul', 'div', 'rand_int', 'noise', 'prompt_onnx', 't2l_onnx', 'l2i_onnx', 'onnx_model_loader', 'float_range', 'step_param_easing', 'dynamic_prompt', 'prompt_from_file', 'sdxl_model_loader', 'sdxl_refiner_model_loader', 'esrgan', 'graph', 'iterate', 'collect', 'canny_image_processor', 'hed_image_processor', 'lineart_image_processor', 'lineart_anime_image_processor', 'openpose_image_processor', 'midas_depth_image_processor', 'normalbae_image_processor', 'mlsd_image_processor', 'pidi_image_processor', 'content_shuffle_image_processor', 'zoe_depth_image_processor', 'mediapipe_face_processor', 'leres_image_processor', 'tile_image_processor', 'segment_anything_processor')",
"type": "value_error.discriminated_union.invalid_discriminator",
"ctx": {
"discriminator_key": "type",
"discriminator_value": "t2l",
"allowed_values": "'boolean', 'boolean_collection', 'integer', 'integer_collection', 'float', 'float_collection', 'string', 'string_collection', 'image', 'image_collection', 'latents', 'latents_collection', 'color', 'conditioning', 'conditioning_collection', 'controlnet', 'image_processor', 'main_model_loader', 'lora_loader', 'sdxl_lora_loader', 'vae_loader', 'seamless', 'metadata_accumulator', 'range', 'range_of_size', 'random_range', 'compel', 'sdxl_compel_prompt', 'sdxl_refiner_compel_prompt', 'clip_skip', 'cv_inpaint', 'show_image', 'blank_image', 'img_crop', 'img_paste', 'tomask', 'img_mul', 'img_chan', 'img_conv', 'img_blur', 'img_resize', 'img_scale', 'img_lerp', 'img_ilerp', 'img_nsfw', 'img_watermark', 'mask_edge', 'mask_combine', 'color_correct', 'img_hue_adjust', 'img_luminosity_adjust', 'img_saturation_adjust', 'infill_rgba', 'infill_tile', 'infill_patchmatch', 'infill_lama', 'scheduler', 'create_denoise_mask', 'denoise_latents', 'l2i', 'lresize', 'lscale', 'i2l', 'lblend', 'add', 'sub', 'mul', 'div', 'rand_int', 'noise', 'prompt_onnx', 't2l_onnx', 'l2i_onnx', 'onnx_model_loader', 'float_range', 'step_param_easing', 'dynamic_prompt', 'prompt_from_file', 'sdxl_model_loader', 'sdxl_refiner_model_loader', 'esrgan', 'graph', 'iterate', 'collect', 'canny_image_processor', 'hed_image_processor', 'lineart_image_processor', 'lineart_anime_image_processor', 'openpose_image_processor', 'midas_depth_image_processor', 'normalbae_image_processor', 'mlsd_image_processor', 'pidi_image_processor', 'content_shuffle_image_processor', 'zoe_depth_image_processor', 'mediapipe_face_processor', 'leres_image_processor', 'tile_image_processor', 'segment_anything_processor'"
}
}
]
}
}

### Contact Details

pozdnyakov044@gmail.com

**Comment by Millu** [comment]
Could you share the terminal or Javascript console logs? Unfortunately the provided information is not enough to debug

**Comment by psychedelicious** [comment]
To get the full error message, please:
- [Open your browser's JavaScript console](https://webmasters.stackexchange.com/a/77337)
- Find the red error message at the bottom of the console's output
- Right click the `Object` -> `Copy Object`
- Paste the object here

**Comment by VladimirPozdnyakov** [comment]
> Could you share the terminal or Javascript console logs? Unfortunately the provided information alone is not enough to debug

{
  "graph": {
    "graph": {
      "id": "text_to_image_graph",
      "nodes": {
        "positive_conditioning": {
          "type": "compel",
          "id": "positive_conditioning",
          "prompt": "masterpiece, high quality, best quality, 4k, super detail, potion in a glass bottle",
          "is_intermediate": true
        },
        "negative_conditioning": {
          "type": "compel",
          "id": "negative_conditioning",
          "prompt": "",
          "is_intermediate": true
        },
        "noise": {
          "type": "noise",
          "id": "noise",
          "width": 832,
          "height": 832,
          "use_cpu": true,
          "is_intermediate": true
        },
        "text_to_latents": {
          "type": "t2l",
          "id": "text_to_latents",
          "is_intermediate": true,
          "cfg_scale": 7,
          "scheduler": "dpmpp_2m_k",
          "steps": 20
        },
        "main_model_loader": {
          "type": "main_model_loader",
          "id": "main_model_loader",
          "is_intermediate": true,
          "model": {
            "model_name": "meinamix_meinaV11",
            "base_model": "sd-1",
            "model_type": "main"
          }
        },
        "clip_skip": {
          "type": "clip_skip",
          "id": "clip_skip",
          "skipped_layers": 2,
          "is_intermediate": true
        },
        "latents_to_image": {
          "type": "l2i",
          "id": "latents_to_image",
          "fp32": true
        },
        "metadata_accumulator": {
          "id": "metadata_accumulator",
          "type": "metadata_accumulator",
          "generation_mode": "txt2img",
          "cfg_scale": 7,
          "height": 832,
          "width": 832,
          "positive_prompt": "masterpiece, high quality, best quality, 4k, super detail, potion in a glass bottle",
          "negative_prompt": "",
          "model": {
            "model_name": "meinamix_meinaV11",
            "base_model": "sd-1",
            "model_type": "main"
          },
          "seed": 0,
          "steps": 20,
          "rand_device": "cpu",
          "scheduler": "dpmpp_2m_k",
          "vae": {
            "model_name": "vae-ft-mse-840000-ema-pruned.vae",
            "base_model": "sd-1"
          },
          "controlnets": [],
          "loras": [
            {
              "lora": {
                "model_name": "add_detail",
                "base_model": "sd-1"
              },
              "weight": 1
            }
          ],
          "clip_skip": 2
        },
        "lora_loader_add_detail": {
          "type": "lora_loader",
          "id": "lora_loader_add_detail",
          "is_intermediate": true,
          "lora": {
            "model_name": "add_detail",
            "base_model": "sd-1"
          },
          "weight": 1
        },
        "vae_loader": {
          "type": "vae_loader",
          "id": "vae_loader",
          "is_intermediate": true,
          "vae_model": {
            "model_name": "vae-ft-mse-840000-ema-pruned.vae",
            "base_model": "sd-1"
          }
        },
        "iterate": {
          "id": "iterate",
          "type": "iterate",
          "is_intermediate": true
        },
        "range_of_size": {
          "id": "range_of_size",
          "type": "range_of_size",
          "is_intermediate": true,
          "size": 1,
          "step": 1
        },
        "rand_int": {
          "id": "rand_int",
          "type": "rand_int",
          "is_intermediate": true
        }
      },
      "edges": [
        {
          "source": {
            "node_id": "main_model_loader",
            "field": "clip"
          },
          "destination": {
            "node_id": "clip_skip",
            "field": "clip"
          }
        },
        {
          "source": {
            "node_id": "positive_conditioning",
            "field": "conditioning"
          },
          "destination": {
            "node_id": "text_to_latents",
            "field": "positive_conditioning"
          }
        },
        {
          "source": {
            "node_id": "negative_conditioning",
            "field": "conditioning"
          },
          "destination": {
            "node_id": "text_to_latents",
            "field": "negative_conditioning"
          }
        },
        {
          "source": {
            "node_id": "text_to_latents",
            "field": "latents"
          },
          "destination": {
            "node_id": "latents_to_image",
            "field": "latents"
          }
        },
        {
          "source": {
            "node_id": "noise",
            "field": "noise"
          },
          "destination": {
            "node_id": "text_to_latents",
            "field": "noise"
          }
        },
        {
          "source": {
            "node_id": "metadata_accumulator",
            "field": "metadata"
          },
          "destination": {
            "node_id": "latents_to_image",
            "field": "metadata"
          }
        },
        {
          "source": {
            "node_id": "main_model_loader",
            "field": "unet"
          },
          "destination": {
            "node_id": "lora_loader_add_detail",
            "field": "unet"
          }
        },
        {
          "source": {
            "node_id": "clip_skip",
            "field": "clip"
          },
          "destination": {
            "node_id": "lora_loader_add_detail",
            "field": "clip"
          }
        },
        {
          "source": {
            "node_id": "lora_loader_add_detail",
            "field": "unet"
          },
          "destination": {
            "node_id": "text_to_latents",
            "field": "unet"
          }
        },
        {
          "source": {
            "node_id": "lora_loader_add_detail",
            "field": "clip"
          },
          "destination": {
            "node_id": "positive_conditioning",
            "field": "clip"
          }
        },
        {
          "source": {
            "node_id": "lora_loader_add_detail",
            "field": "clip"
          },
          "destination": {
            "node_id": "negative_conditioning",
            "field": "clip"
          }
        },
        {
          "source": {
            "node_id": "vae_loader",
            "field": "vae"
          },
          "destination": {
            "node_id": "latents_to_image",
            "field": "vae"
          }
        },
        {
          "source": {
            "node_id": "range_of_size",
            "field": "collection"
          },
          "destination": {
            "node_id": "iterate",
            "field": "collection"
          }
        },
        {
          "source": {
            "node_id": "iterate",
            "field": "item"
          },
          "destination": {
            "node_id": "noise",
            "field": "seed"
          }
        },
        {
          "source": {
            "node_id": "iterate",
            "field": "item"
          },
          "destination": {
            "node_id": "metadata_accumulator",
            "field": "seed"
          }
        },
        {
          "source": {
            "node_id": "rand_int",
            "field": "a"
          },
          "destination": {
            "node_id": "range_of_size",
            "field": "start"
          }
        }
      ]
    }
  },
  "status": 422,
  "error": {
    "detail": [
      {
        "loc": [
          "body",
          "nodes",
          "text_to_latents"
        ],
        "msg": "No match for discriminator 'type' and value 't2l' (allowed values: 'boolean', 'boolean_collection', 'integer', 'integer_collection', 'float', 'float_collection', 'string', 'string_collection', 'image', 'image_collection', 'latents', 'latents_collection', 'color', 'conditioning', 'conditioning_collection', 'controlnet', 'image_processor', 'main_model_loader', 'lora_loader', 'sdxl_lora_loader', 'vae_loader', 'seamless', 'metadata_accumulator', 'range', 'range_of_size', 'random_range', 'compel', 'sdxl_compel_prompt', 'sdxl_refiner_compel_prompt', 'clip_skip', 'cv_inpaint', 'show_image', 'blank_image', 'img_crop', 'img_paste', 'tomask', 'img_mul', 'img_chan', 'img_conv', 'img_blur', 'img_resize', 'img_scale', 'img_lerp', 'img_ilerp', 'img_nsfw', 'img_watermark', 'mask_edge', 'mask_combine', 'color_correct', 'img_hue_adjust', 'img_luminosity_adjust', 'img_saturation_adjust', 'infill_rgba', 'infill_tile', 'infill_patchmatch', 'infill_lama', 'scheduler', 'create_denoise_mask', 'denoise_latents', 'l2i', 'lresize', 'lscale', 'i2l', 'lblend', 'add', 'sub', 'mul', 'div', 'rand_int', 'noise', 'prompt_onnx', 't2l_onnx', 'l2i_onnx', 'onnx_model_loader', 'float_range', 'step_param_easing', 'dynamic_prompt', 'prompt_from_file', 'sdxl_model_loader', 'sdxl_refiner_model_loader', 'esrgan', 'graph', 'iterate', 'collect', 'canny_image_processor', 'hed_image_processor', 'lineart_image_processor', 'lineart_anime_image_processor', 'openpose_image_processor', 'midas_depth_image_processor', 'normalbae_image_processor', 'mlsd_image_processor', 'pidi_image_processor', 'content_shuffle_image_processor', 'zoe_depth_image_processor', 'mediapipe_face_processor', 'leres_image_processor', 'tile_image_processor', 'segment_anything_processor')",
        "type": "value_error.discriminated_union.invalid_discriminator",
        "ctx": {
          "discriminator_key": "type",
          "discriminator_value": "t2l",
          "allowed_values": "'boolean', 'boolean_collection', 'integer', 'integer_collection', 'float', 'float_collection', 'string', 'string_collection', 'image', 'image_collection', 'latents', 'latents_collection', 'color', 'conditioning', 'conditioning_collection', 'controlnet', 'image_processor', 'main_model_loader', 'lora_loader', 'sdxl_lora_loader', 'vae_loader', 'seamless', 'metadata_accumulator', 'range', 'range_of_size', 'random_range', 'compel', 'sdxl_compel_prompt', 'sdxl_refiner_compel_prompt', 'clip_skip', 'cv_inpaint', 'show_image', 'blank_image', 'img_crop', 'img_paste', 'tomask', 'img_mul', 'img_chan', 'img_conv', 'img_blur', 'img_resize', 'img_scale', 'img_lerp', 'img_ilerp', 'img_nsfw', 'img_watermark', 'mask_edge', 'mask_combine', 'color_correct', 'img_hue_adjust', 'img_luminosity_adjust', 'img_saturation_adjust', 'infill_rgba', 'infill_tile', 'infill_patchmatch', 'infill_lama', 'scheduler', 'create_denoise_mask', 'denoise_latents', 'l2i', 'lresize', 'lscale', 'i2l', 'lblend', 'add', 'sub', 'mul', 'div', 'rand_int', 'noise', 'prompt_onnx', 't2l_onnx', 'l2i_onnx', 'onnx_model_loader', 'float_range', 'step_param_easing', 'dynamic_prompt', 'prompt_from_file', 'sdxl_model_loader', 'sdxl_refiner_model_loader', 'esrgan', 'graph', 'iterate', 'collect', 'canny_image_processor', 'hed_image_processor', 'lineart_image_processor', 'lineart_anime_image_processor', 'openpose_image_processor', 'midas_depth_image_processor', 'normalbae_image_processor', 'mlsd_image_processor', 'pidi_image_processor', 'content_shuffle_image_processor', 'zoe_depth_image_processor', 'mediapipe_face_processor', 'leres_image_processor', 'tile_image_processor', 'segment_anything_processor'"
        }
      }
    ]
  }
}

**Comment by DataJuggler** [comment]
I have the same issue after upgrading to 3.1. I think deleted everything and reinstalled 3.1 fresh, and it keeps happening. I am just subscribing to this thread is my reason for replying.

**Comment by psychedelicious** [comment]
@VladimirPozdnyakov 


To get the full error message, please:
- [Open your browser's JavaScript console](https://webmasters.stackexchange.com/a/77337)
- Find the red error message at the bottom of the console's output
- Right click the `Object` -> `Copy Object`
- Paste the object here

**Comment by XingyuFu** [comment]
I have the same problem, this is the object:
{
    "graph": {
        "graph": {
            "id": "text_to_image_graph",
            "nodes": {
                "positive_conditioning": {
                    "type": "compel",
                    "id": "positive_conditioning",
                    "prompt": "1girl",
                    "is_intermediate": true
                },
                "negative_conditioning": {
                    "type": "compel",
                    "id": "negative_conditioning",
                    "prompt": "",
                    "is_intermediate": true
                },
                "noise": {
                    "type": "noise",
                    "id": "noise",
                    "width": 768,
                    "height": 1024,
                    "use_cpu": true,
                    "is_intermediate": true
                },
                "text_to_latents": {
                    "type": "t2l",
                    "id": "text_to_latents",
                    "is_intermediate": true,
                    "cfg_scale": 6,
                    "scheduler": "euler",
                    "steps": 12
                },
                "main_model_loader": {
                    "type": "main_model_loader",
                    "id": "main_model_loader",
                    "is_intermediate": true,
                    "model": {
                        "model_name": "deliberate_v2",
                        "base_model": "sd-1",
                        "model_type": "main"
                    }
                },
                "clip_skip": {
                    "type": "clip_skip",
                    "id": "clip_skip",
                    "skipped_layers": 0,
                    "is_intermediate": true
                },
                "latents_to_image": {
                    "type": "l2i",
                    "id": "latents_to_image",
                    "fp32": true
                },
                "metadata_accumulator": {
                    "id": "metadata_accumulator",
                    "type": "metadata_accumulator",
                    "generation_mode": "txt2img",
                    "cfg_scale": 6,
                    "height": 1024,
                    "width": 768,
                    "positive_prompt": "1girl",
                    "negative_prompt": "",
                    "model": {
                        "model_name": "deliberate_v2",
                        "base_model": "sd-1",
                        "model_type": "main"
                    },
                    "seed": 0,
                    "steps": 12,
                    "rand_device": "cpu",
                    "scheduler": "euler",
                    "controlnets": [],
                    "loras": [],
                    "clip_skip": 0
                },
                "iterate": {
                    "id": "iterate",
                    "type": "iterate",
                    "is_intermediate": true
                },
                "range_of_size": {
                    "id": "range_of_size",
                    "type": "range_of_size",
                    "is_intermediate": true,
                    "size": 1,
                    "step": 1
                },
                "rand_int": {
                    "id": "rand_int",
                    "type": "rand_int",
                    "is_intermediate": true
                }
            },
            "edges": [
                {
                    "source": {
                        "node_id": "main_model_loader",
                        "field": "clip"
                    },
                    "destination": {
                        "node_id": "clip_skip",
                        "field": "clip"
                    }
                },
                {
                    "source": {
                        "node_id": "main_model_loader",
                        "field": "unet"
                    },
                    "destination": {
                        "node_id": "text_to_latents",
                        "field": "unet"
                    }
                },
                {
                    "source": {
                        "node_id": "clip_skip",
                        "field": "clip"
                    },
                    "destination": {
                        "node_id": "positive_conditioning",
                        "field": "clip"
                    }
                },
                {
                    "source": {
                        "node_id": "clip_skip",
                        "field": "clip"
                    },
                    "destination": {
                        "node_id": "negative_conditioning",
                        "field": "clip"
                    }
                },
                {
                    "source": {
                        "node_id": "positive_conditioning",
                        "field": "conditioning"
                    },
                    "destination": {
                        "node_id": "text_to_latents",
                        "field": "positive_conditioning"
                    }
                },
                {
                    "source": {
                        "node_id": "negative_conditioning",
                        "field": "conditioning"
                    },
                    "destination": {
                        "node_id": "text_to_latents",
                        "field": "negative_conditioning"
                    }
                },
                {
                    "source": {
                        "node_id": "text_to_latents",
                        "field": "latents"
                    },
                    "destination": {
                        "node_id": "latents_to_image",
                        "field": "latents"
                    }
                },
                {
                    "source": {
                        "node_id": "noise",
                        "field": "noise"
                    },
                    "destination": {
                        "node_id": "text_to_latents",
                        "field": "noise"
                    }
                },
                {
                    "source": {
                        "node_id": "metadata_accumulator",
                        "field": "metadata"
                    },
                    "destination": {
                        "node_id": "latents_to_image",
                        "field": "metadata"
                    }
                },
                {
                    "source": {
                        "node_id": "main_model_loader",
                        "field": "vae"
                    },
                    "destination": {
                        "node_id": "latents_to_image",
                        "field": "vae"
                    }
                },
                {
                    "source": {
                        "node_id": "range_of_size",
                        "field": "collection"
                    },
                    "destination": {
                        "node_id": "iterate",
                        "field": "collection"
                    }
                },
                {
                    "source": {
                        "node_id": "iterate",
                        "field": "item"
                    },
                    "destination": {
                        "node_id": "noise",
                        "field": "seed"
                    }
                },
                {
                    "source": {
                        "node_id": "iterate",
                        "field": "item"
                    },
                    "destination": {
                        "node_id": "metadata_accumulator",
                        "field": "seed"
                    }
                },
                {
                    "source": {
                        "node_id": "rand_int",
                        "field": "a"
                    },
                    "destination": {
                        "node_id": "range_of_size",
                        "field": "start"
                    }
                }
            ]
        }
    },
    "status": 422,
    "error": {
        "detail": [
            {
                "loc": [
                    "body",
                    "nodes",
                    "text_to_latents"
                ],
                "msg": "No match for discriminator 'type' and value 't2l' (allowed values: 'boolean', 'boolean_collection', 'integer', 'integer_collection', 'float', 'float_collection', 'string', 'string_collection', 'image', 'image_collection', 'latents', 'latents_collection', 'color', 'conditioning', 'conditioning_collection', 'controlnet', 'image_processor', 'main_model_loader', 'lora_loader', 'sdxl_lora_loader', 'vae_loader', 'seamless', 'metadata_accumulator', 'compel', 'sdxl_compel_prompt', 'sdxl_refiner_compel_prompt', 'clip_skip', 'scheduler', 'create_denoise_mask', 'denoise_latents', 'l2i', 'lresize', 'lscale', 'i2l', 'lblend', 'prompt_onnx', 't2l_onnx', 'l2i_onnx', 'onnx_model_loader', 'esrgan', 'float_range', 'step_param_easing', 'infill_rgba', 'infill_tile', 'infill_patchmatch', 'infill_lama', 'range', 'range_of_size', 'random_range', 'noise', 'cv_inpaint', 'add', 'sub', 'mul', 'div', 'rand_int', 'dynamic_prompt', 'prompt_from_file', 'sdxl_model_loader', 'sdxl_refiner_model_loader', 'show_image', 'blank_image', 'img_crop', 'img_paste', 'tomask', 'img_mul', 'img_chan', 'img_conv', 'img_blur', 'img_resize', 'img_scale', 'img_lerp', 'img_ilerp', 'img_nsfw', 'img_watermark', 'mask_edge', 'mask_combine', 'color_correct', 'img_hue_adjust', 'img_luminosity_adjust', 'img_saturation_adjust', 'graph', 'iterate', 'collect', 'canny_image_processor', 'hed_image_processor', 'lineart_image_processor', 'lineart_anime_image_processor', 'openpose_image_processor', 'midas_depth_image_processor', 'normalbae_image_processor', 'mlsd_image_processor', 'pidi_image_processor', 'content_shuffle_image_processor', 'zoe_depth_image_processor', 'mediapipe_face_processor', 'leres_image_processor', 'tile_image_processor', 'segment_anything_processor')",
                "type": "value_error.discriminated_union.invalid_discriminator",
                "ctx": {
                    "discriminator_key": "type",
                    "discriminator_value": "t2l",
                    "allowed_values": "'boolean', 'boolean_collection', 'integer', 'integer_collection', 'float', 'float_collection', 'string', 'string_collection', 'image', 'image_collection', 'latents', 'latents_collection', 'color', 'conditioning', 'conditioning_collection', 'controlnet', 'image_processor', 'main_model_loader', 'lora_loader', 'sdxl_lora_loader', 'vae_loader', 'seamless', 'metadata_accumulator', 'compel', 'sdxl_compel_prompt', 'sdxl_refiner_compel_prompt', 'clip_skip', 'scheduler', 'create_denoise_mask', 'denoise_latents', 'l2i', 'lresize', 'lscale', 'i2l', 'lblend', 'prompt_onnx', 't2l_onnx', 'l2i_onnx', 'onnx_model_loader', 'esrgan', 'float_range', 'step_param_easing', 'infill_rgba', 'infill_tile', 'infill_patchmatch', 'infill_lama', 'range', 'range_of_size', 'random_range', 'noise', 'cv_inpaint', 'add', 'sub', 'mul', 'div', 'rand_int', 'dynamic_prompt', 'prompt_from_file', 'sdxl_model_loader', 'sdxl_refiner_model_loader', 'show_image', 'blank_image', 'img_crop', 'img_paste', 'tomask', 'img_mul', 'img_chan', 'img_conv', 'img_blur', 'img_resize', 'img_scale', 'img_lerp', 'img_ilerp', 'img_nsfw', 'img_watermark', 'mask_edge', 'mask_combine', 'color_correct', 'img_hue_adjust', 'img_luminosity_adjust', 'img_saturation_adjust', 'graph', 'iterate', 'collect', 'canny_image_processor', 'hed_image_processor', 'lineart_image_processor', 'lineart_anime_image_processor', 'openpose_image_processor', 'midas_depth_image_processor', 'normalbae_image_processor', 'mlsd_image_processor', 'pidi_image_processor', 'content_shuffle_image_processor', 'zoe_depth_image_processor', 'mediapipe_face_processor', 'leres_image_processor', 'tile_image_processor', 'segment_anything_processor'"
                }
            }
        ]
    }
}

**Comment by XingyuFu** [comment]
![image](https://github.com/invoke-ai/InvokeAI/assets/19774938/8c96b708-c044-4691-b12c-3bcf8d36295c)

**Comment by VladimirPozdnyakov** [comment]
> ![image](https://user-images.githubusercontent.com/19774938/265605648-8c96b708-c044-4691-b12c-3bcf8d36295c.png)

The issue was solved by reinstalling via script over the already installed version.
