### ISSUE TITLE
[enhancement]: Import Model - Auto detect file name and auto fill that name into Model Name field

### ISSUE THREAD

**Issue by suonnon** [invoke-ai/InvokeAI#4443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

It could save more time when importing new model by auto detect file name and auto fill that file name into Model Name field.

![image](https://github.com/invoke-ai/InvokeAI/assets/133345496/4d761560-1a1f-4f80-8cd2-7726ec8213bd)

**Comment by blessedcoolant** [comment]
Added: #4445
