### ISSUE TITLE
[bug]: The Quick-links buttons not responsive

### ISSUE THREAD

**Issue by vedant-3010** [invoke-ai/InvokeAI#4455]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS

Windows

### GPU

cpu

### VRAM

8GB

### What version did you experience this issue on?

3.1.0

### What happened?

The buttons are overflowing and are not responsive in the quick link section of the website.
It is located in a button-container class and can be fixed.
This will help in improving the user experience.

### Screenshots

<img width="281" alt="image" src="https://github.com/invoke-ai/InvokeAI/assets/92071471/5128654b-7a8d-4224-8629-c74a97319a95">

**Comment by Millu** [comment]
Thanks for calling this out! Would you be willing to make the update to make the container responsive?

**Comment by vedant-3010** [comment]
Yeah, sure. I will do it
