### ISSUE TITLE
Unable to install canny controlnet for SDXL [bug]: 

### ISSUE THREAD

**Issue by singultus** [invoke-ai/InvokeAI#4472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.1.0

### What happened?

I fail to download the canny controlnet for SDXL. I suppose I should look here: models.invoke.ai. The canny model offers either this link "(https://huggingface.co/diffusers/diffuserscontrolnet-canny-sdxl-1.0)" or when you press the button "diffusers/diffuserscontrolnet-canny-sdxl-1.0". The first crashes the shell with a pipe error, the second aborts (I added a screenshot of the aborted install). I was able to install the zoe depth model without any issues.

### Screenshots

![Capture](https://github.com/invoke-ai/InvokeAI/assets/5405472/9f03b00b-5546-4f87-bf12-eee5d4e275e2)

**Comment by Millu** [comment]
Thanks for flagging, that link is wrong - try this: `diffusers/controlnet-canny-sdxl-1.0`
