### ISSUE TITLE
Tablet Pressure + Brush Size

### ISSUE THREAD

**Issue by Millu** [invoke-ai/InvokeAI#4473]
## Summary

Allow users to use tablet pressure to adjust brush size on the canvas to more easily edit images to suit their needs

## Intended Outcome
A user with a compatible tablet to draw on the canvas is able to use tablet pressure to dynamically adjust the brush size during drawing

**Comment by olegsatov** [comment]
Can't wait for it! 👍

**Comment by FloeHetling** [comment]
https://github.com/invoke-ai/InvokeAI/issues/6870
