### ISSUE TITLE
[bug]: Cannot start Invoke AI 3.1.0 on Mac M1 Max

### ISSUE THREAD

**Issue by caleidoscopio** [invoke-ai/InvokeAI#4486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### What version did you experience this issue on?

3.1.0

### What happened?

After installing Invoke AI 3.1.0, I ran the invoke.sh script in Terminal which opened the window below:

<img width="825" alt="image" src="https://github.com/invoke-ai/InvokeAI/assets/73276364/1f31bddd-6566-4d72-aef8-95420caba86b">

If I press ok the I get message **Exiting...** in Terminal.

**Comment by Millu** [comment]
This is a new one! Could you take a screen recording of this? 

Are there are any other logs that come up before this appears?

**Comment by caleidoscopio** [comment]
Here's the recording:
https://github.com/invoke-ai/InvokeAI/assets/73276364/791afef5-e851-4bc4-8cb6-c63431874f19

It also happens if I just run the script with no bash command preceding the filepath.
I don't think there are any other logs.

**Comment by Millu** [comment]
> It also happens if I just run the script with no bash command preceding the filepath.

Does this happen when you try `sh invoke.sh` or `./invoke.sh`?

**Comment by caleidoscopio** [comment]
> > It also happens if I just run the script with no bash command preceding the filepath.
> 
> Does this happen when you try `sh invoke.sh` or `./invoke.sh`?

Yes it does.

**Comment by lstein** [comment]
Completely mystified by this one.

**Comment by Millu** [comment]
@caleidoscopio Mind sharing the invoke.sh script here?

**Comment by lstein** [comment]
Try running `invoke.sh —no-tui`.  I suspect that you have a version of `dialog` installed which doesn’t behave the way the regular ones does.

**Comment by caleidoscopio** [comment]
@Millu Here's the file
[invoke.sh.zip](https://github.com/invoke-ai/InvokeAI/files/12556538/invoke.sh.zip)

@lstein, unfortunately adding the -no-tui flag didn't fix it
