### ISSUE TITLE
[bug]: InvokeAI 3.1.0: SDXL ControlNet Models cannot be imported

### ISSUE THREAD

**Issue by HaraldWerner** [invoke-ai/InvokeAI#4487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

amd

### VRAM

32

### What version did you experience this issue on?

3.1.0

### What happened?

The ControlNet Models for SDXL (see: https://huggingface.co/lllyasviel/sd_control_collection/tree/main ) can not be imported

### Screenshots

Adding these models to the `autoimport` folder prints a message like this:

```
[InvokeAI]::WARNING --> Unable to determine model type for /invokeai/autoimport/controlnet/diffusers_xl_canny_full.safetensors
```

The Model Manager in the UI does not seem to allow manual importing of controlnet models. Any auto-import me
<img width="1052" alt="Bildschirmfoto 2023-09-07 um 21 04 06" src="https://github.com/invoke-ai/InvokeAI/assets/30108765/ee278b56-ecae-4503-bd01-616b88225b79">
chanisms report an error.

**Comment by hipsterusername** [comment]
This repo is not correctly updated/formatted - It's a collection of other controlnet models that have been trained, and is not an "official source" -- It's likely that @lllyasviel uploaded this for use in an A1111 extension, and not for general use as a Diffusers repo.

For Thibaud's pose controlnet, I'd use thibaud/controlnet-openpose-sdxl-1.0 (which I've tested as working)

There are others (like the Diffusers team's and Sarge's models) uploaded on the Tools tab of models.invoke.ai
