### ISSUE TITLE
[bug]: One cannot update InvokeAI 3.1 if the session's username is called 'invokeai'

### ISSUE THREAD

**Issue by Sirachosur** [invoke-ai/InvokeAI#4500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12Gb

### What version did you experience this issue on?

3.1.0

### What happened?

I used 9 at the menu to update InvokeAI and it would fail stating that an instance is running.

Renaming the user will fix the problem.

The script thus does not look for the script but probably grep ps output to see if 'invokeai' exist in the process list.  Only it caps the user, not the process in this case.

**Comment by Millu** [comment]
@lstein not a edge case I had considered before

**Comment by psychedelicious** [comment]
We've redone how updates work (it's the same script for installing). I don't think this is still a problem. Please create a new issue if the problem persisted with the latest release (v4.1.0)
