### ISSUE TITLE
[bug]: using the pip version of invokeai instead of this installer

### ISSUE THREAD

**Issue by webmaster-exit-1** [invoke-ai/InvokeAI#4509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

amd

### VRAM

25

### What version did you experience this issue on?

latest

### What happened?

  File "/tmp/invokeai-installer-tmpqudz_o41/lib/python3.11/site-packages/plumbum/commands/processes.py", line 17, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/tmp/invokeai-installer-tmpqudz_o41/lib/python3.11/site-packages/plumbum/machines/base.py", line 27, in verify
    raise ProcessExecutionError(
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 1
Command line: | /mnt/alpha/invokeai/.venv/bin/pip install --require-virtualenv --use-pep517 '/mnt/alpha/InvokeAI/installer[onnx]' --extra-index-url https://download.pytorch.org/whl/rocm5.4.2

### Additional context

using the new 7900 XTX

### Contact Details

mrgofuckyourself@proton.me

**Comment by webmaster-exit-1** [comment]
ERROR: Directory '/mnt/alpha/InvokeAI/installer[onnx]' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

**Comment by webmaster-exit-1** [comment]
everytime i run the installer, same error, again and again

**Comment by webmaster-exit-1** [comment]
![image](https://github.com/invoke-ai/InvokeAI/assets/98633966/ae3489a0-dd2b-4080-acd4-c9e60a392fc2)

**Comment by webmaster-exit-1** [comment]
it installs what it needs, then errors thinking it didn't

**Comment by webmaster-exit-1** [comment]
update, after running the installer.sh.in (weird extension for a bash script btw) all pkgs are cached and install correctly, then it freaks out
![image](https://github.com/invoke-ai/InvokeAI/assets/98633966/53332d14-bf24-4744-8497-60703c4d734e)
you see, all good. then this.....
![image](https://github.com/invoke-ai/InvokeAI/assets/98633966/51409bc1-7c7f-477e-ab6c-e1be68795d5b)

**Comment by webmaster-exit-1** [comment]
even after choosing AMD it seems it still installes BS nvidia tools like onnx

**Comment by webmaster-exit-1** [comment]
/mnt/prod/invokeai/.venv/bin/pip install --require-virtualenv --use-pep517 '/mnt/alpha/InvokeAI/installer[onnx]' --extra-index-url https://download.pytorch.org/whl/rocm5.4.2


there is NO file named installer[onnx]!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by webmaster-exit-1** [comment]
looks like i'll have to edit /mnt/alpha/InvokeAI/installer/lib/installer.py myself

**Comment by webmaster-exit-1** [comment]
![image](https://github.com/invoke-ai/InvokeAI/assets/98633966/64e2d487-80fc-4698-b69e-6ee265c0d4e6)
![image](https://github.com/invoke-ai/InvokeAI/assets/98633966/241327a7-fb7e-449e-8668-151891346351)

**Comment by webmaster-exit-1** [comment]
made some edits, removed bs nvidia stuff

**Comment by webmaster-exit-1** [comment]
this should now bypass nvidia crap and install the correct torch

**Comment by webmaster-exit-1** [comment]
the installer is taking its time now, i think i fixed it

**Comment by webmaster-exit-1** [comment]
![image](https://github.com/invoke-ai/InvokeAI/assets/98633966/dc99de58-32ac-44ff-aaca-c1717c033566)
fixing
![image](https://github.com/invoke-ai/InvokeAI/assets/98633966/fa55e3c3-8893-4e66-9194-4976be049f5a)

**Comment by webmaster-exit-1** [comment]
![image](https://github.com/invoke-ai/InvokeAI/assets/98633966/b89209b9-4311-4eb0-8fac-217744ba146b)
fixed

**Comment by webmaster-exit-1** [comment]
rerunning installer.... again

**Comment by webmaster-exit-1** [comment]
![image](https://github.com/invoke-ai/InvokeAI/assets/98633966/47857f01-3122-44c3-8529-d1f83896bfa4)

**Comment by webmaster-exit-1** [comment]
running installer again.....

**Comment by webmaster-exit-1** [comment]
fuck this, using the pip version of invokeai, bypassing all this installer bs.

**Comment by webmaster-exit-1** [comment]
![image](https://github.com/invoke-ai/InvokeAI/assets/98633966/1ee7643b-814b-4521-9b47-a994e61d3dc8)

**Comment by webmaster-exit-1** [comment]
Using the pip versions seems to be working much better, but we'll see

**Comment by webmaster-exit-1** [comment]
It still try's to run nvidia bullshit and trying to map shit to my cpu even tho i have AMD top of the line GFX card 7900 XTX!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by webmaster-exit-1** [comment]
![image](https://github.com/invoke-ai/InvokeAI/assets/98633966/36a723cf-65ad-4e38-9b5c-241420aba8a3)

**Comment by webmaster-exit-1** [comment]
doesn't it suck when you buy AMD's top of the line graphics card, and software still wants you to use BS NVidia?

**Comment by webmaster-exit-1** [comment]
invokeai-web
>> patchmatch.patch_match: ERROR - patchmatch failed to load or compile (/home/mrgfy/.local/lib/python3.9/site-packages/torch/lib/libgomp-a34b3233.so.1: version `GOMP_5.0' not found (required by /usr/lib/libvtkCommonCore.so.1)).
>> patchmatch.patch_match: INFO - Refer to https://invoke-ai.github.io/InvokeAI/installation/060_INSTALL_PATCHMATCH/ for installation instructions.
[2023-09-11 04:57:57,449]::[InvokeAI]::INFO --> Patchmatch not loaded (nonfatal)
/home/mrgfy/.local/lib/python3.9/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Traceback (most recent call last):
  File "pydantic/utils.py", line 785, in pydantic.utils.get_discriminator_alias_and_values
AttributeError: 'tuple' object has no attribute 'type_'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mrgfy/.local/bin/invokeai-web", line 5, in <module>
    from invokeai.app.api_app import invoke_api
  File "/home/mrgfy/.local/lib/python3.9/site-packages/invokeai/app/api_app.py", line 26, in <module>
    from .api.dependencies import ApiDependencies
  File "/home/mrgfy/.local/lib/python3.9/site-packages/invokeai/app/api/dependencies.py", line 15, in <module>
    from invokeai.app.services.images import ImageService, ImageServiceDependencies
  File "/home/mrgfy/.local/lib/python3.9/site-packages/invokeai/app/services/images.py", line 37, in <module>
    from invokeai.app.util.metadata import get_metadata_graph_from_raw_session
  File "/home/mrgfy/.local/lib/python3.9/site-packages/invokeai/app/util/metadata.py", line 6, in <module>
    from invokeai.app.services.graph import Edge
  File "/home/mrgfy/.local/lib/python3.9/site-packages/invokeai/app/services/graph.py", line 693, in <module>
    class GraphExecutionState(BaseModel):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 758, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 808, in pydantic.fields.ModelField._create_sub_type
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 629, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 666, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 780, in pydantic.fields.ModelField.prepare_discriminated_union_sub_fields
  File "pydantic/utils.py", line 787, in pydantic.utils.get_discriminator_alias_and_values
TypeError: Type 'BooleanOutput' is not a valid `BaseModel` or `dataclass`

**Comment by webmaster-exit-1** [comment]
FML, i give up

**Comment by webmaster-exit-1** [comment]
good luck getting this to run, i give up. Gonna try some other gui software.

**Comment by Cool-and-Deadly** [comment]
On Apple M2 MacOS 13.5 I have the same issue:
`ERROR: Directory '<PATH>/InvokeAI/installer[onnx]' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.` 
.. when running the installer downloaded at https://github.com/invoke-ai/InvokeAI/releases/tag/v3.1.1

Any ideas?

**Comment by gustaveWPM** [comment]
> update, after running the installer.sh.in (weird extension for a bash script btw) all pkgs are cached and install correctly, then it freaks out ![image](https://user-images.githubusercontent.com/98633966/267002402-53332d14-bf24-4744-8497-60703c4d734e.png) you see, all good. then this..... ![image](https://user-images.githubusercontent.com/98633966/267002489-51409bc1-7c7f-477e-ab6c-e1be68795d5b.png)

Hello.
Maybe you're trying to install StableDiffusion the wrong way.

Did you clone the repo?
Something like `git clone https://github.com/invoke-ai/InvokeAI/`, or going on https://github.com/invoke-ai/InvokeAI/ and then click on "Code", then "Download ZIP"?

If yes, _I think_ you're missing the standard way to process the installation.

Instead of trying to clone the repository, just go on this page
https://github.com/invoke-ai/InvokeAI/releases

And then download an InvokeAI Installer. Either via the link provided in the descriptions of the releases, or by clicking on the "Assets" dropdown menu below each release, then clicking on the installer provided in the Assets of the release.
