### ISSUE TITLE
[bug]: "Python has stopped working"

### ISSUE THREAD

**Issue by fancellu** [invoke-ai/InvokeAI#4512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.1.0

### What happened?

Running on an GTX 1080, i7-4930k, windows 10

On trying to start the webui it says "Python has stopped working"

Using python 3.10.9

Anyone else seen this?

Its fine when installing, no errors etc. Was fine before with InvokeAI 2.x, just did a
clean install to 3.1.0

i.e. seems to be something going wrong with  .venv\Scripts\invokeai-web.exe

**Comment by Millu** [comment]
A quick and dirty solution for you would be to delete your .venv and reinstall Invoke in the same location - your models and outputs won't be affected

**Comment by fancellu** [comment]
That didn't fix it, but I found out what it was, some lunacy with some asio driver for foobar2000 (which I don't even use any more). I uninstalled the driver and then my invokeai was fine. V v odd.
