### ISSUE TITLE
[bug]: RangeError: invalid array length

### ISSUE THREAD

**Issue by pedropaf** [invoke-ai/InvokeAI#4515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

24

### What version did you experience this issue on?

3.1.0

### What happened?

generated image with SDXL, then right click and send to unified canvas, used the mouse wheel to zoom out, and the error happened

**Comment by maryhipp** [comment]
If you see this again, please provide screenshots of any console or network errors
