### ISSUE TITLE
Rocm for windows is available

### ISSUE THREAD

**Issue by xdlolpite** [invoke-ai/InvokeAI#4519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

AMD Rocm now available on windows . Would you like to add it for invoke installer and let them amd users to install it on windows, not just only on linux.

https://rocmdocs.amd.com/en/latest/deploy/windows/index.html

**Comment by Joly0** [comment]
Any news on this one? Would like to try InvokeAI on windows with rocm

**Comment by ldilov** [comment]
+1 Rocm is for  like 6 months  available for windows users

**Comment by ldilov** [comment]
Still nothing althought its been more than a year with rocm for windows

**Comment by ldilov** [comment]
Any news?
