### ISSUE TITLE
[enhancement]: Upload Custom Mask

### ISSUE THREAD

**Issue by wolfkingal2000** [invoke-ai/InvokeAI#4531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

add copy and past form clipboard windows and add upload custom mask for in painting because i use photoshop and invoke ai both them add can masked   photoshop can more stable and faster and cleaner and add multiple drag drop in assets panel thanks

**Comment by psychedelicious** [comment]
You may now upload alpha mask images and import them for use on the canvas.
