### ISSUE TITLE
[bug]: SDXL fails VAE pass when VAE Precision is set to fp16

### ISSUE THREAD

**Issue by radry** [invoke-ai/InvokeAI#4532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

3.1.1

### What happened?

When generating an image with SDXL and the VAE is set to default with the provided SDXL 1.0 model and the VAE precision is set to fp16, it fails with an error.

Solution: Automatically set VAE Precision to FP32 when VAE is set to Default and model is SDXL based.

**Comment by psychedelicious** [comment]
We can't make the proposed change, because there are sdxl models with fp16 vae baked in.

For now this is necessarily the user's responsibility. 

We are working on a model management refactor that should help though.

**Comment by radry** [comment]
So it can not autodetect which vae it is? That's a problem.

**Comment by Millu** [comment]
Not as of right now - model management is currently being re-worked, and this should be improved.

**Comment by psychedelicious** [comment]
You can now select the default VAE precision on a per-model basis.
