### ISSUE TITLE
[bug]: Model Manager errors with leading / trailing space in URL 

### ISSUE THREAD

**Issue by cgwers** [invoke-ai/InvokeAI#4536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12

### What version did you experience this issue on?

3.1.0

### What happened?

Model Manager Import

When adding an import URL, MM throws an "Undefined" error when there is a space character on either side of the URL.

I suggest using strip on the input.
-------------------
This is a UX/UI issue. Since InvokeAI does not store file information to a database, a strong basic assumption is that users keep usage notes for their downloaded files. Please help us poor copy/pasters work uninterrupted.

I'd love to see InvokeAI maintain a DB similar to AI Prompt studio (though without that Fisher-Price UI) to hold the source URL of the file and whatever usage metadata is available and the user's notes.

**Comment by lstein** [comment]
The new version of the model manager PR #4252 trims whitespace from URLs. It also expands the metadata associated with a model to the info provided by HuggingFace and Civitai, including author, license, source URL and various tags. These are editable.

**Comment by cgwers** [comment]
That's great Lincoln. Thanks for posting.  I wouldn't see it to know until
next weekend.
