### ISSUE TITLE
[bug]: Can not generate image with SDXL - Invoke 3.1.1

### ISSUE THREAD

**Issue by suonnon** [invoke-ai/InvokeAI#4539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

3.1.1

### What happened?

I can't generate any images with SDXL any more. After upgrading to 3.1.1, I got this issue. It happened with both 3.1.1 RC and Official release. This issue was not happened with previous Invoke versions.

All SD1.5 models are fine! But SDXL. The attached file below is the screenshot of the console log.

I tried to:
- Use option 7 on startup console to fix broken things => Not work
- Fresh install Invoke into new folder location. => Not work

My system:
AMD CPU, RTX 3060ti 8GB (Driver: 531.79), 32GB RAM, all other drivers are up to date.

### Screenshots

Console log:
![image](https://github.com/invoke-ai/InvokeAI/assets/133345496/f276c4cd-83ca-4d0d-8aa9-a776d8796614)

My startup option:
![image](https://github.com/invoke-ai/InvokeAI/assets/133345496/9d62c085-ae0c-469c-86ab-53e1e5e11ece)

**Comment by hipsterusername** [comment]
I suspect, based on the error you're getting, that you're using a model that is not fully converted into diffusers.

Can you check your model manager and see if the model has the "Convert to Diffusers" option on the top right?

**Comment by hipsterusername** [comment]
That suggests an issue with conversion… either of that model or generally.

Do you have a different XL model to test?

**Comment by Millu** [comment]
@suonnon where are your custom models stored?

**Comment by lstein** [comment]
@suonnon Can you show your `invokeai.yaml` file? The part I'm interested in is the `Paths:` section. What do you mean by "custom models folder"? Is this the `autoimport_dir` folder, or is it `models_dir`?

Last question: Are you using diffusers-style SDXL models (folders containing a bunch of submodels), or safetensors-style SDXL models (a single file ending in `.safetensors`.

**Comment by greatwolf** [comment]
I think I'm running into the same issue as you except this is on google colab. Where did you put your SDXL model so that successfully converts into diffuser?

**Comment by psychedelicious** [comment]
The model manage was rewritten for v4. Please create a new issue if the problem persisted with the latest release (v4.1.0)
