### ISSUE TITLE
[enhancement]: Not degrade resolution/quality existing image when outpainting

### ISSUE THREAD

**Issue by vrubzov1957** [invoke-ai/InvokeAI#4556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Please, add the possibility that when we do outpainting and if scaling is turned on, then the detail of the area that already exists before outpainting does not will bee changed.

Currently - when we do outpainting with scaling turned on (lowering the resolution, for example for 512*512 for faster SD 1.5) -  what was previously was detailed becomes blurry.

(!!!) WHY? 
For correct outpainting, we need to take into account the entire scene (which, for example, is done in Photoshop in a generative fill). In high resolution (more than 512 or 1024) - SD cannot generate correctly. And if a new generation degrade the previous one, then it’s impossible to use outpainting correctly in Invoke AI.
As a result, it turns out that such a technically simple for fix thing (just don’t change the resolution/quality of areas that are not generated in a current generation) makes outpainting in Invoke AI much worse in quality to the same Photoshop (even if we could use exactly the same models).

### Alternatives

As in Generative Fill in Photosop. Maybe by adding layers and managing them (so that the new generation does not affect the previous one), more stricted masked result of current generation,  or in any other way

**Comment by hipsterusername** [comment]
To track in #5767 5767
