### ISSUE TITLE
[enhancement]: Canvas: Ability to draw straight lines

### ISSUE THREAD

**Issue by vrubzov1957** [invoke-ai/InvokeAI#4559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Add the ability to draw straight lines on the canvas (by pressing Shift or using a separate tool).

WHY?
Since SD cannot correctly take into account perspective, when some foreground object blocks the visibility of the background perspective lines, we hace have to complete and correct the lines manually (and do new generation on it). 
It would be convenient if it were possible to draw them straight, and like a ruler to extend the existing lines of the scene (and then may be erasing the extra parts of the line)

**Comment by psychedelicious** [comment]
This is now implemented in canvas v2.
