### ISSUE TITLE
[bug]: Canvas: Artifacts in generation position after pressing some UNDO command

### ISSUE THREAD

**Issue by vrubzov1957** [invoke-ai/InvokeAI#4561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

11

### What version did you experience this issue on?

3.1.1

### What happened?

When we press some UNDO command in Canvas, and then to start generation - then generation appears in a different location, or generates incorrect highlighted areas.

If there is no way to fix this, then at least please add a pop-up like “A command UNDO was pressed, if there are artifacts in the generation, refresh the page”.

### Additional context

Browser: Edge 117.0.2045.31

**Comment by Millu** [comment]
Does this appear on a different browser as well?

**Comment by vrubzov1957** [comment]
> Does this appear on a different browser as well?

In other browser I cant work with Canvas - I have problems:
* Safari 16.6 ARM -  I cant open Canvas, it completly frozen
* Chrome 116.0.5845.188 64bit - got "RangeError: Invalid array length"

**Comment by Millu** [comment]
Does the Chrome issue persist after you reload the UI?

**Comment by vrubzov1957** [comment]
> Does the Chrome issue persist after you reload the UI?

Yes. And after reload and even after "Reset UI".

PS. My Chrome was updated to 117.0.5938.89 - I not tried it yet.

**Comment by psychedelicious** [comment]
Invoke v5 features a full rewrite of the canvas.. Please create a new GH issue if the problem still exists in the new canvas UI.
