### ISSUE TITLE
[bug]: canvas ravenously gobbling browser memory

### ISSUE THREAD

**Issue by keturn** [invoke-ai/InvokeAI#4562]
### What version did you experience this issue on?

d94d4ef83f5be5dd10cbec3050a6b3a862ab9718

### What happened?

When using Canvas with SDXL (1024x1024 bounding box), it has a seemingly limitless appetite for memory. I generate in batches of 3, and memory usage shoots up by ten or twenty megabytes. I hit _Discard All_, generate more, and it uses _more_ memory rather than reclaiming memory from the last batch.

To some extent this might be expected behavior if the system had plenty of RAM free, but it continues to the point where it forces other applications to swap out. Here it got up to 567 MB before it closed the terminal application that was running my SSH tunnel, disconnecting me from the server.

### Screenshots

![Screenshot of Chrome Task Manager showing InvokeAI tab using 567 MB](https://cdn.discordapp.com/attachments/1152746603195674625/1152746870456713256/invokeai-canvas-memory-usage.webp)

### Additional context

chrome 116.0.5845.168 (Official Build) (32-bit)

**Comment by psychedelicious** [comment]
Invoke v5 features a full rewrite of the canvas. Please create a new GH issue if the problem still exists in the new canvas UI.
