### ISSUE TITLE
[bug]: yarn install Could not resolve "@chakra-ui/react"

### ISSUE THREAD

**Issue by keturn** [invoke-ai/InvokeAI#4563]
### OS

Linux

### What version did you experience this issue on?

d94d4ef83f5be5dd10cbec3050a6b3a862ab9718

### What happened?

`yarn install` results in numerous errors of the form

```
✘ [ERROR] Could not resolve "@chakra-ui/react"

    src/theme/components/button.ts:1:47:
      1 │ import { defineStyle, defineStyleConfig } from '@chakra-ui/react';
        ╵                                                ~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@chakra-ui/react" here because it's not listed as a dependency of this package:

    ../../../.pnp.cjs:38:33:
      38 │           "packageDependencies": [\
         ╵                                  ~~

  You can mark the path "@chakra-ui/react" as external to exclude it from the bundle, which will remove this error.
```

I've grown used to seeing _some_ warnings about resolving chakra fly by in the frontend build, but sometime in the last few days it's gotten much louder and now ends in

```
✖ UNHANDLED ERROR
✖ ERROR → Error
ℹ REASON → Build failed with 49 errors:
src/theme/components/accordion.ts:1:42: ERROR: Could not resolve "@chakra-ui/anatomy"
src/theme/components/accordion.ts:5:7: ERROR: Could not resolve "@chakra-ui/styled-system"
src/theme/components/accordion.ts:6:21: ERROR: Could not resolve "@chakra-ui/theme-tools"
src/theme/components/button.ts:1:47: ERROR: Could not resolve "@chakra-ui/react"
src/theme/components/button.ts:2:21: ERROR: Could not resolve "@chakra-ui/theme-tools"
...
```

Full log: https://gist.github.com/keturn/ddf7f755c9909487a8eb67669c3d93a1

**Comment by maryhipp** [comment]
Have you tried deleting your node_modules and re-running? I am not seeing these errors locally

**Comment by keturn** [comment]
Removing `node_modules` was not sufficient, but somehow I had `yarn.lock`, `package-lock.json`, and `package.json` in my top-level git directory (not `invokeai/frontend/web`). Removing those cleared things up.
