### ISSUE TITLE
[bug]: Inpainting with SDXL at low denoising strength produces blocky results

### ISSUE THREAD

**Issue by filiptrplan** [invoke-ai/InvokeAI#4565]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

3.1.1

### What happened?

When I tried inpainting an image with SDXL at 0.3 denoising strength, only 3-4 iterations are executed instead of the specified 20 steps. This results in a blocky result.

### Screenshots

![](https://cdn.discordapp.com/attachments/1152726476387528724/1152726476593037353/image.png)

![](https://cdn.discordapp.com/attachments/1152726476387528724/1152726476932780032/image.png)

**Comment by hipsterusername** [comment]
This isn’t a bug! :)

When you use a denoising strength, you’re specifically setting a % of your input steps to be used. In the case of a .3 strength, you’d want to ensure you set your steps to something like 30 or 40 so that you have sufficient steps to avoid the noise artifacts.
