### ISSUE TITLE
[bug]: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by bigmouth-GD** [invoke-ai/InvokeAI#4579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.1.1

### What happened?

The image is generated after resetting the UI interface, and it will be generated again

### Screenshots

![Snipaste_2023-09-18_22-33-28](https://github.com/invoke-ai/InvokeAI/assets/134496440/018a245a-eef6-4f02-aac3-627ec8915620)

### Additional context

```
{
  "stack": "Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.\n    at EM (http://127.0.0.1:9090/assets/index-f83c2c5c.js:40:26100)\n    at _l (http://127.0.0.1:9090/assets/index-f83c2c5c.js:40:25787)\n    at EM (http://127.0.0.1:9090/assets/index-f83c2c5c.js:40:26536)\n    at gs (http://127.0.0.1:9090/assets/index-f83c2c5c.js:40:27391)\n    at TM (http://127.0.0.1:9090/assets/index-f83c2c5c.js:40:27851)\n    at gs (http://127.0.0.1:9090/assets/index-f83c2c5c.js:40:27541)\n    at TM (http://127.0.0.1:9090/assets/index-f83c2c5c.js:40:27654)\n    at gs (http://127.0.0.1:9090/assets/index-f83c2c5c.js:40:27541)\n    at TM (http://127.0.0.1:9090/assets/index-f83c2c5c.js:40:27654)\n    at gs (http://127.0.0.1:9090/assets/index-f83c2c5c.js:40:27541)",
  "name": "NotFoundError",
  "message": "Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.",
  "code": 8
}
```

### Contact Details

2468076000@qq.com

**Comment by Millu** [comment]
Do you remember what you were doing when you got this error?

**Comment by bigmouth-GD** [comment]
If I still have a problem and then feedback to you, I try to turn off VPN and anti-virus software.



---Original---
From: "Millun ***@***.***&gt;
Date: Tue, Sep 19, 2023 06:56 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [invoke-ai/InvokeAI] [bug]: NotFoundError: Failed to execute'removeChild' on 'Node': The node to be removed is not a child of this node.(Issue #4579)




 
Do you remember what you were doing when you got this error?

**Comment by Millu** [comment]
Thank you!

**Comment by bigmouth-GD** [comment]
Last night's research solved this problem. Changing browsers or switching users' original browsers may keep some previous configuration files, causing errors.



---Original---
From: "Millun ***@***.***&gt;
Date: Wed, Sep 20, 2023 08:30 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [invoke-ai/InvokeAI] [bug]: NotFoundError: Failed to execute'removeChild' on 'Node': The node to be removed is not a child of this node.(Issue #4579)




 
Thank you!

**Comment by mirghiz** [comment]
I have the same problem, but i didn't understand how you fixed the error.
