### ISSUE TITLE
[bug]: Can't import `Vhey/action-sdxl` from models.invoke.ai

### ISSUE THREAD

**Issue by RyanJDick** [invoke-ai/InvokeAI#4580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

24GB

### What version did you experience this issue on?

18698744339fe98d0707e6d769d23ed6ad5a93cc

### What happened?

Invoke AI failed to import https://models.invoke.ai/Vhey/action-sdxl from the 'Import Model' UI.

The logs contained the following:
```bash
[2023-09-18 14:20:07,306]::[InvokeAI]::WARNING --> Could not determine type of repo Vhey/action-sdxl. Skipping install.
[2023-09-18 14:20:07,388]::[InvokeAI]::ERROR --> Import failed
```

**Comment by psychedelicious** [comment]
Looks like this model no longer exists.
