### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by etiennevee** [invoke-ai/InvokeAI#4584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### VRAM

16GB

### What version did you experience this issue on?

3.1.1

### What happened?

hey guys, 

First of all, I'm not a tech guy at all. So excuse me if my language is very simple in this message.
Note also that I tried for 8 hours yesterday to solve my issue going through the internet. I uninstalled everything including python and stable-diffusion to reinstall everything after. My python version is 3.10.6. 

I tried to install stable diffusion and when I'm doing the last step of the process in the terminal: 

cd stable-diffusion-webui/
./webui.sh

When I do this command, here is what I receive:  (note that for anonymous reason I remove my username to USERNAME)

I would appreciate your help ! Thanks

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on USERNAME user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.10.13 (main, Aug 24 2023, 22:25:01) [Clang 13.0.0 (clang-1300.0.29.30)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Installing requirements for CodeFormer
Traceback (most recent call last):
  File "/Users/USERNAME/stable-diffusion-webui/launch.py", line 48, in <module>
    main()
  File "/Users/USERNAME/stable-diffusion-webui/launch.py", line 39, in main
    prepare_environment()
  File "/Users/USERNAME/stable-diffusion-webui/modules/launch_utils.py", line 389, in prepare_environment
    run_pip(f"install -r \"{os.path.join(repo_dir('CodeFormer'), 'requirements.txt')}\"", "requirements for CodeFormer")
  File "/Users/USERNAME/stable-diffusion-webui/modules/launch_utils.py", line 138, in run_pip
    return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
  File "/Users/USERNAME/stable-diffusion-webui/modules/launch_utils.py", line 115, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install requirements for CodeFormer.
Command: "/Users/USERNAME/stable-diffusion-webui/venv/bin/python3.10" -m pip install -r "/Users/USERNAME/stable-diffusion-webui/repositories/CodeFormer/requirements.txt" --prefer-binary
Error code: 1
stdout: Collecting addict (from -r /Users/USERNAME/stable-diffusion-webui/repositories/CodeFormer/requirements.txt (line 1))
  Using cached addict-2.4.0-py3-none-any.whl (3.8 kB)
Collecting future (from -r /Users/USERNAME/stable-diffusion-webui/repositories/CodeFormer/requirements.txt (line 2))
  Using cached future-0.18.3.tar.gz (840 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting lmdb (from -r /Users/USERNAME/stable-diffusion-webui/repositories/CodeFormer/requirements.txt (line 3))
  Using cached lmdb-1.4.1.tar.gz (881 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: numpy in ./venv/lib/python3.10/site-packages (from -r /Users/USERNAME/stable-diffusion-webui/repositories/CodeFormer/requirements.txt (line 4)) (1.26.0)
Collecting opencv-python (from -r /Users/USERNAME/stable-diffusion-webui/repositories/CodeFormer/requirements.txt (line 5))
  Obtaining dependency information for opencv-python from https://files.pythonhosted.org/packages/32/a6/4321f0f30ee11d6d85f49251d417f4e885fe7638b5ac50b7e3c80cccf141/opencv_python-4.8.0.76-cp37-abi3-macosx_11_0_arm64.whl.metadata
  Using cached opencv_python-4.8.0.76-cp37-abi3-macosx_11_0_arm64.whl.metadata (19 kB)
Requirement already satisfied: Pillow in ./venv/lib/python3.10/site-packages (from -r /Users/USERNAME/stable-diffusion-webui/repositories/CodeFormer/requirements.txt (line 6)) (10.0.1)
Requirement already satisfied: pyyaml in ./venv/lib/python3.10/site-packages (from -r /Users/USERNAME/stable-diffusion-webui/repositories/CodeFormer/requirements.txt (line 7)) (6.0.1)
Requirement already satisfied: requests in ./venv/lib/python3.10/site-packages (from -r /Users/USERNAME/stable-diffusion-webui/repositories/CodeFormer/requirements.txt (line 8)) (2.31.0)
Collecting scikit-image (from -r /Users/USERNAME/stable-diffusion-webui/repositories/CodeFormer/requirements.txt (line 9))
  Using cached scikit_image-0.21.0.tar.gz (22.7 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): still running...
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting scipy (from -r /Users/USERNAME/stable-diffusion-webui/repositories/CodeFormer/requirements.txt (line 10))
  Using cached scipy-1.11.2.tar.gz (56.0 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'

stderr:   error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      + meson setup /private/var/folders/hh/ch4zx9617_s8r52k3dgxqcj00000gn/T/pip-install-xs4rfpyy/scipy_6c398efb352246e28abc782ffb31d37d /private/var/folders/hh/ch4zx9617_s8r52k3dgxqcj00000gn/T/pip-install-xs4rfpyy/scipy_6c398efb352246e28abc782ffb31d37d/.mesonpy-b856wlfx/build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/private/var/folders/hh/ch4zx9617_s8r52k3dgxqcj00000gn/T/pip-install-xs4rfpyy/scipy_6c398efb352246e28abc782ffb31d37d/.mesonpy-b856wlfx/build/meson-python-native-file.ini
      The Meson build system
      Version: 1.2.1
      Source dir: /private/var/folders/hh/ch4zx9617_s8r52k3dgxqcj00000gn/T/pip-install-xs4rfpyy/scipy_6c398efb352246e28abc782ffb31d37d
      Build dir: /private/var/folders/hh/ch4zx9617_s8r52k3dgxqcj00000gn/T/pip-install-xs4rfpyy/scipy_6c398efb352246e28abc782ffb31d37d/.mesonpy-b856wlfx/build
      Build type: native build
      Project name: SciPy
      Project version: 1.11.2
      C compiler for the host machine: cc (clang 13.0.0 "Apple clang version 13.0.0 (clang-1300.0.29.30)")
      C linker for the host machine: cc ld64 711
      C++ compiler for the host machine: c++ (clang 13.0.0 "Apple clang version 13.0.0 (clang-1300.0.29.30)")
      C++ linker for the host machine: c++ ld64 711
      Cython compiler for the host machine: cython (cython 0.29.36)
      Host machine cpu family: aarch64
      Host machine cpu: aarch64
      Program python found: YES (/Users/USERNAME/stable-diffusion-webui/venv/bin/python3.10)
      Found pkg-config: /opt/homebrew/bin/pkg-config (0.29.2)
      Run-time dependency python found: YES 3.10
      Program cython found: YES (/private/var/folders/hh/ch4zx9617_s8r52k3dgxqcj00000gn/T/pip-build-env-mwkwhdq9/overlay/bin/cython)
      Compiler for C supports arguments -Wno-unused-but-set-variable: NO
      Compiler for C supports arguments -Wno-unused-function: YES
      Compiler for C supports arguments -Wno-conversion: YES
      Compiler for C supports arguments -Wno-misleading-indentation: YES
      Library m found: YES
      
      ../../meson.build:82:0: ERROR: Unknown compiler(s): [['gfortran'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['ifx'], ['g95']]
      The following exception(s) were encountered:
      Running `gfortran --version` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `gfortran -V` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `flang --version` gave "[Errno 2] No such file or directory: 'flang'"
      Running `flang -V` gave "[Errno 2] No such file or directory: 'flang'"
      Running `nvfortran --version` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `nvfortran -V` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `pgfortran --version` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `pgfortran -V` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `ifort --version` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `ifort -V` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `ifx --version` gave "[Errno 2] No such file or directory: 'ifx'"
      Running `ifx -V` gave "[Errno 2] No such file or directory: 'ifx'"
      Running `g95 --version` gave "[Errno 2] No such file or directory: 'g95'"
      Running `g95 -V` gave "[Errno 2] No such file or directory: 'g95'"
      
      A full log can be found at /private/var/folders/hh/ch4zx9617_s8r52k3dgxqcj00000gn/T/pip-install-xs4rfpyy/scipy_6c398efb352246e28abc782ffb31d37d/.mesonpy-b856wlfx/build/meson-logs/meson-log.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

### Contact Details

epmarketing02@gmail.com

**Comment by gogurtenjoyer** [comment]
Hi, this is the github repo for InvokeAI, which is a Stable Diffusion implementation, but it's either not the one you're using, or you're using some install script that's not InvokeAI's.

**Comment by etiennevee** [comment]
thank you I will go directly into the Stable DIffusion github !

**Comment by Millu** [comment]
In any case, feel free to give InvokeAI a try :)
