### ISSUE TITLE
[bug]:  Installer writes outside install directory

### ISSUE THREAD

**Issue by ghost** [invoke-ai/InvokeAI#4585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

3.1.1

### What happened?

Installer writes outside install directory (the final part with models download).

This can cause install crash, and a lot of Windows crashes if C: drive becomes full.

Seems to write into C:\Users\xxxx\.cache instead of writing directly on install directory.
C:\Users\xxxx\.cache files are not deleted.

### Contact Details

jvachez@free.fr

**Comment by Millu** [comment]
This is the HuggingFace cache I believe - you should be able to delete this without issue

**Comment by psychedelicious** [comment]
Resolved in v4.0.0
