### ISSUE TITLE
[bug]: ip Adapter DND Zone disabled when toggled off

### ISSUE THREAD

**Issue by hipsterusername** [invoke-ai/InvokeAI#4590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24

### What version did you experience this issue on?

Main

### What happened?

Unable to drag and drop an image to the DND zone of IP adapter when the toggle is disabled.

Should be allowed, or that zone hidden if IP adapter toggled off,

**Comment by psychedelicious** [comment]
resolved in #4627

you can dnd/upload on controlnet and ipadapter at any time. doing so, if they are disabled, enables them
