### ISSUE TITLE
[bug]: 3.x consumes much more RAM with LoRA and LyCORIS than 2.3.5

### ISSUE THREAD

**Issue by toyo-chi** [invoke-ai/InvokeAI#4601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cpu

### What version did you experience this issue on?

3.1.0

### What happened?

When using any LoRA (and especially any LyCORIS), InvokeAI 3.x consumes much more RAM than 2.3.5. This makes it much more difficult to generate with LoRAs and nearly impossible with LyCORIS on 8 GB RAM!

### Screenshots

Graphs recorded with [psrecord](https://github.com/astrofrog/psrecord), 5 seconds interval.

3.1.0:
![invokeai-3 1-together-lora-edit](https://github.com/invoke-ai/InvokeAI/assets/52622517/4c915d43-43d2-42c5-9d4f-69519950437c)

(with LoRA memory consumption doesn't really reduce after a while, InvokeAI just constantly swapping.)

2.3.5, for reference:
![invokeai-2 3 5 post2-alltogether-edit](https://github.com/invoke-ai/InvokeAI/assets/52622517/69eb7b63-4c25-46ec-95bf-bd1fdd47ba05)

(I can't record generating with LyCORIS on 3.1, as the memory consumption dramatically rises after `loading lora` log message. My system just starts freezing even with swap, and I have to kill InvokeAI before it even starts generating.)

### Additional context

Not sure, but may be this issue is related to #4340? But I'm using only SD 1.5 models.

Also cannot manage to find existing package of InvokeAI 3.x for my distro (NixOS), and have to fork [this](https://github.com/gbtb/nix-stable-diffusion) outdated overlay. Maybe I just doing something [terribly wrong](https://github.com/toyo-chi/nix-stable-diffusion/tree/invokeai_3x)!

**Comment by toyo-chi** [comment]
And also... Hello, is this a bugtracker of a famous Stable Diffusion toolkit? Why not add some AIllustrations to the bug reports?

<details>
<summary>LyCORIS on 2.3.5: nice and easy!</summary>

![01-Tanoshii!](https://github.com/invoke-ai/InvokeAI/assets/52622517/2e10f9c3-f3e7-49e6-a629-60c93ae8fd97)
</details>
<details>
<summary>LyCORIS on 3.x: Too heavy...</summary>

![02-O-omoi](https://github.com/invoke-ai/InvokeAI/assets/52622517/d9159e78-ed58-4fe0-92de-20152e3d585e)
</details>

([MeinaMix](https://civitai.com/models/7240/meinamix) + [Lycoris LoRA](https://civitai.com/models/120274/manjusaka-or-spider-lily-or-lycoris-radiata-flower-or), if you want to know.)

**Comment by psychedelicious** [comment]
Hi, sorry for the very late response. Model loading has been rewritten for v4. Please create a new issue if there is a problem after updating the latest version.

BTW thanks for the funny pics hehe
