### ISSUE TITLE
[enhancement]: Save to board node/option to save to different boards

### ISSUE THREAD

**Issue by ymgenesis** [invoke-ai/InvokeAI#4604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

The ability for different image outputs in a workflow to save to different boards. For example, your main output goes to a "Finals" board, while you paste some text overtop with some params you changed to get the result, and save that in "Params", or something like that.

**Comment by psychedelicious** [comment]
I think this is provided by the `Save Image` node now?

**Comment by ymgenesis** [comment]
Yes, thanks!
