### ISSUE TITLE
[bug]: Queue with a Shared Setting that causes Errors produce large number of error messages

### ISSUE THREAD

**Issue by hipsterusername** [invoke-ai/InvokeAI#4637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24

### What version did you experience this issue on?

3.2rc2

### What happened?

If a large number of queue items are added which share a model that is found to be invalid (e.g., model config exists, but the model is gone or malformed, etc.), then the front-end is hit with a rapid succession of error messages.

**Comment by psychedelicious** [comment]
Related: #5136
