### ISSUE TITLE
[bug]: deleting images seems to not remove them from the board

### ISSUE THREAD

**Issue by keturn** [invoke-ai/InvokeAI#4646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### What version did you experience this issue on?

b152fbf72f163e4a60bda7a54747d0a752d63ca1

### What happened?

I select several images in the board (with Click and then Shift-Click), right-click, select Delete, Confirm and … they do not seem to be removed from the board.

It's only after I reload the page that they no longer appear.

### Screenshots

[deleting-doesnt.webm](https://github.com/invoke-ai/InvokeAI/assets/83819/6ac5d17b-9fb9-4de7-8c03-d5b3e07098ee)

### Additional context

Firefox 118.0 on Linux

**Comment by psychedelicious** [comment]
In #4790, I've fixed a couple bugs related to cache invalidation (who would have guessed that would be the source of the issue?) during image deletion, which I am hopeful will resolve this. This will be in this week's release in case you are running the proper release version.
