### ISSUE TITLE
Make new panel for inpainting

### ISSUE THREAD

**Issue by wolfkingal2000** [invoke-ai/InvokeAI#4648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I want you to make a panel just for inpainting. I want the new panel to be simpler and suitable for inpainting and have a mask effect. In order to remove people from the image or make anything, I think inpainting needs to be done inside so that it doesn't need to be in the desired shape.  And be able to use controlnet well like Lama Cleaner

**Comment by Millu** [comment]
What would be the use case of a new inpainting tab instead of using the unified canvas?

**Comment by Kingal20000** [comment]
> What would be the use case of a new inpainting tab instead of using the unified canvas? 

Well, you are right, but I want the Bounding Box to stay on the photo and not go outside. Add some settings. I don't want to paint outside, and I want it to have a great effect when it becomes a mask. When I want to dress a part of the body, even if I add a prompt  Clothes always cover the color of the body, I don't want to and for controlnet add settings add photo form Bounding Box Not the whole unified canvas, and you can do this by saving only the Bounding Box, but it is good if it is in the controlnet itself 

I wanted another panel for this, if possible, unified canvas for inpainting is better

**Comment by Millu** [comment]
Take a look at our new Canvas [tutorial video](https://www.youtube.com/watch?v=kzRL88ffv1o&t=1428s&pp=ygUNY2FudmFzIGludm9rZQ%3D%3D) - it might help with some of the difficulties you're experiencing. 

We appreciate the feedback, and will keep it in mind, but going to close this for now and this isn't something that we'd implement soon.
