### ISSUE TITLE
[bug]: not all the Ratio controls fit in their container

### ISSUE THREAD

**Issue by keturn** [invoke-ai/InvokeAI#4656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

60b3c6a2011ecbcb2fd2cd07140d10d1d1cca330

### What happened?

on this chromebook, not all the buttons for the the image size Ratio control fit in their container.

### Screenshots

![image](https://github.com/invoke-ai/InvokeAI/assets/83819/7d5eb6f9-2c36-42c8-baff-554d511c6284)

### Additional context

chrome 116.0.5845.168 (Official Build) (32-bit)

**Comment by psychedelicious** [comment]
UI has been totally redesigned since this issue was created
