### ISSUE TITLE
[bug]: Images option not selectable, grayed out in General section

### ISSUE THREAD

**Issue by TimEyerish** [invoke-ai/InvokeAI#4663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### What version did you experience this issue on?

3.11

### What happened?

I'm unable to choose number of images to generate, defaulted at 1.  Unable to select as it's grayed out. 

### Screenshots

<img width="1080" alt="Screenshot 2023-09-22 at 11 14 37 PM" src="https://github.com/invoke-ai/InvokeAI/assets/129996490/cf75eb83-407e-4a50-a9bf-a8e894d2276b">

### Contact Details

tgallagherhi@gmail.com

**Comment by gogurtenjoyer** [comment]
It sounds like you have dynamic prompts enabled. This disables the Images field because it itself generates a certain number of images. Disable it, and you should be able to use that field.
