### ISSUE TITLE
[enhancement]: CivitAI models info

### ISSUE THREAD

**Issue by vrubzov1957** [invoke-ai/InvokeAI#4666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Geting info from CivitAI for installed models.
Info like this:
* Full name of this model
* Screenshots
* TriggerWords
* BaseModel (ex. 1.5 or XL)
* New versions of this model
* ...

Searching by comparing sha256, as in "sd_civitai_extension" for Automatic.

---

Also, it would be nice (although not necessary) to have some kind of browser, the ability to install and delete CivitAI models directly in InvokeAI

### Alternatives

"sd_civitai_extension" for Automatic

**Comment by Millu** [comment]
> Also, it would be nice (although not necessary) to have some kind of browser, the ability to install and delete CivitAI models directly in InvokeAI

This is possible by using the download link from CivitAI in the Model Manager UI

**Comment by vrubzov1957** [comment]
This is good) 
But I am more about "interactive browser" of it

**Comment by Millu** [comment]
Something similar is on our radar, but not sure we'd implement a full browser like that extension in the near future. Going to close this for now, but thank you for the feedback and suggestions!

**Comment by vrubzov1957** [comment]
Ok, we will wait)
If not browser of CivitAI - but at least gettian a base info from CivitAI of installed model - it is really useful and really simplifies the user experience
