### ISSUE TITLE
[enhancement]: Retain currently selected colour when opening the UC brush options

### ISSUE THREAD

**Issue by RetroBum** [invoke-ai/InvokeAI#4667]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Stretch (villainstretch) on Discord

### What should this feature add?

When opening the Brush Options in the Unified Canvas the colour selector defaults to full black.
It would be much more usable and more in line with other applications if the current brush colour was already selected.

### Alternatives

The only alternative is to try and find the colour you already have selected manually which is less than ideal.

**Comment by psychedelicious** [comment]
This must have been broken for aeons - definitely a bug. Will be fixed in next release. Thanks for reporting.
