### ISSUE TITLE
[bug]: 3.2.0 - Recalling LoRa Settings does not remove additional LoRas

### ISSUE THREAD

**Issue by grunblatt-git** [invoke-ai/InvokeAI#4670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

32

### What version did you experience this issue on?

3.2.0

### What happened?

In 3.2.0 the following Feature was added:
> LoRAs are now able to be recalled with the "Use All" function

However restoring Settings this way will not remove any LoRas from the current selection, thus leading to a different 
LoRa setup if additional/ different LoRas were used previously.

**Comment by chainchompa** [comment]
https://github.com/invoke-ai/InvokeAI/pull/4639
