### ISSUE TITLE
[bug]: use of `match` keyword breaks Python 3.9

### ISSUE THREAD

**Issue by dreness** [invoke-ai/InvokeAI#4678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

64

### What version did you experience this issue on?

0e53b27655594b36d5565168998a8701a45e2c1f

### What happened?

ReadMe says:

https://github.com/invoke-ai/InvokeAI/blob/6d821b32d3ba550624dce3f764c20b05c2af2afb/README.md?plain=1#L126-L127

However, the [`match` keyword is used in a couple places](https://github.com/search?q=repo%3Ainvoke-ai%2FInvokeAI+path%3A*.py+%2F%5E%5Cs*match%5Cs.*%3F%3A%24%2F&type=code), which is new in Python 3.10. Those two places are:

https://github.com/invoke-ai/InvokeAI/blob/6d821b32d3ba550624dce3f764c20b05c2af2afb/invokeai/app/services/session_processor/session_processor_default.py#L50

https://github.com/invoke-ai/InvokeAI/blob/6d821b32d3ba550624dce3f764c20b05c2af2afb/invokeai/app/services/session_queue/session_queue_sqlite.py#L62

Running this code causes Python 3.9 to bail. Please consider either deprecating 3.9 and updating the docs, or re-writing this to avoid `match`.

I'll just use newer Python - cheers :)

Perhaps you, like me, didn't know GH's code search has supported regex since May or so. Well, now you know :) [This search](https://github.com/search?q=repo%3Ainvoke-ai%2FInvokeAI+path%3A*.py+%2F%5E%5Cs*match%5Cs.*%3F%3A%24%2F&type=code) does the trick, returning only `match` keywords as used in Python, using the regex `/^\s*match\s.*?:$/`.

### Contact Details

dre@mac.com

**Comment by lstein** [comment]
Sorry about this. I do test every release against 3.9, but this one slipped past me. I'll make the fix now.
