### ISSUE TITLE
[bug]: Node editor iteration slider doesn't sync correctly

### ISSUE THREAD

**Issue by lstein** [invoke-ai/InvokeAI#4681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

main

### What happened?

In the nodes editor, when I drag the iterations slider's indicator, the text field updates as expected. However, when I type into the text field and change the iteration count, the indicator stays at 1. Rendering uses the value in the text field.

**Comment by psychedelicious** [comment]
I can't reproduce this, the values are in sync no matter what I do. Can you make a screen recording?
