### ISSUE TITLE
[bug]: Series of image generation sometimes cannot be stopped

### ISSUE THREAD

**Issue by vrubzov1957** [invoke-ai/InvokeAI#4707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

11

### What version did you experience this issue on?

3.1.1

### What happened?

Sometimes the generation of a series of images cannot be stopped. It shows in the interface that generation is in progress (but there is no specific image progress), you can see the progress in the console. But to see the created images, you need to refresh the interface page.

And until all the images are generated (usually I set 8 images), or until I reset the console, the generation is constantly going on. 
A new series of generations may even start (maybe by pressing Enter in the interface) - and although nothing is shown in the interface, generation is going on in the console, but in the interface before the update no progress or images are visible. And until it finishes everything, it will craft new images.

For everything to work normally, we need to restart the console-app.

**Comment by Millu** [comment]
This should be fixed in 3.2 with the addition of the queue manager

**Comment by psychedelicious** [comment]
This sounds like a network issue - the socket events are not being received.

Is this an issue on the latest release?

**Comment by vrubzov1957** [comment]
With the Queue manager this will be fixed.

Queue manager is 🔥

Issue can be closed.
