### ISSUE TITLE
[enhancement]: Set Img2Img Ratio based on Initial Image Dimensions

### ISSUE THREAD

**Issue by Millu** [invoke-ai/InvokeAI#4714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Summary 
If a user is generating using image to image with an outpointed or upscaled image it can be cumbersome to find & input the initial image's dimensions in the ratio field

## Intended Outcome
* On the Image to Image tab, a ratio option is the "Initial Image" size
* Pressing this will change the ratio to the dimensions of the initial image

**Comment by Malrama** [comment]
Good idea! I like that.

My question would be: What do we do about initial images that are not a multiple of X? (2, 8, 64, whatever)?
Let's say a custom created image with a ratio of 511x837.
Or will we automatically round them up/down to be the multiple of X?

(Btw, what is not now? a minimum of a multiple of 8, right?)

**Comment by Millu** [comment]
Closed by #5161
