### ISSUE TITLE
[bug]: 2 same pic from every iteration

### ISSUE THREAD

**Issue by Sniza** [invoke-ai/InvokeAI#4719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

3.2.0rc2

### What happened?

After finish render txt2pic, it making in output two same pictures with different names. (so if I delete it from UI, where is only one, second be still on disk) It start after updating to last version. Restart, reinstall atp. - nothing happend, it still the same

### Contact Details

quantel@seznam.cz

**Comment by Millu** [comment]
One image is the final generated image, and one is an intermediate image - you can clear the intermediate image by going to settings -> "Clear Intermediates"

**Comment by Sniza** [comment]
Oh, I see, thank you very much for the reply

**Comment by Millu** [comment]
You're welcome!
