### ISSUE TITLE
[bug]: Model manager cannot parse model with name containing "/"

### ISSUE THREAD

**Issue by samsze0** [invoke-ai/InvokeAI#4727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

main branch

### What happened?

As title. Just need to rename a model inside the model manager to some string containing the "/" symbol

**Comment by Millu** [comment]
Do you have an example of a model you ran into this issue with?

**Comment by psychedelicious** [comment]
The model manager was rewritten for v4. Please create a new issue if the problem persisted with the latest release (v4.1.0).
