### ISSUE TITLE
[bug]: Crash after window resize on invokeai-configure

### ISSUE THREAD

**Issue by CrypticWit** [invoke-ai/InvokeAI#4734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8gb

### What version did you experience this issue on?

main branch

### What happened?

When attempting to call invokeai-configure with a terminal window that was too small, you receive the 
```This window is too small for the interface. InvokeAI requires 150x40 (w x h) characters, but window is 146x39
Maximize the window and/or decrease the font size then press any key to continue. Type [Q] to give up..
```
 prompt.

After resizing the window and hitting enter, I encountered this error:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\invokeai\.venv\Scripts\invokeai-configure.exe\__main__.py", line 7, in <module>
  File "D:\invokeai\invokeai\backend\install\invokeai_configure.py", line 927, in main
    init_options, models_to_download = run_console_ui(opt, new_init_file)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\invokeai\invokeai\backend\install\invokeai_configure.py", line 746, in run_console_ui
    torch.multiprocessing.set_start_method("spawn")
  File "C:\Python311\Lib\multiprocessing\context.py", line 247, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
NativeCommandExitException: Program "invokeai-configure.exe" ended with non-zero exit code: 1.
```

Everything worked as expected once invoke-configure was called a second time, with a correctly sized window.

### Additional context

Using Python 3.11.

**Comment by ctrueden** [comment]
I had a very similar problem with Python 3.10 on Ubuntu Linux 23.10. I got the `RuntimeError: context has already been set` error upon running `invokeai-configure --root .` from the terminal, although I did not see any prompt about resizing the window. Running `invokeai-configure --root .` a second time worked as expected without resizing any terminal windows.

**Comment by psychedelicious** [comment]
The configure script was removed in v4.
