### ISSUE TITLE
[bug]: Loras are not cached between image generations

### ISSUE THREAD

**Issue by grunblatt-git** [invoke-ai/InvokeAI#4739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

32

### What version did you experience this issue on?

3.2.0

### What happened?

Image generation takes several seconds to start when loras are applied. 
Removing all LoRas also removes this delay.

### Additional context

- the delay seems to be about 5-20 seconds for SD1.5 models and correlates to the number and size of the applied loras
- Even if loras were marked as "cached" in the workflow editor, the delay between image generation stays the same.
- #4340 states the same issue for SDXL models, where it seems to have an even higher impact due to model size

Surprisingly the delay is reduced by a few seconds when adding several "denoise latents" nodes with identical input to a workflow instead of running the same workflow several times.

**Comment by psychedelicious** [comment]
We've made a lot of improvements since this issue was logged, including for LoRA patching and model loading in general. If this is still a problem in v4 please create a new issue.
