### ISSUE TITLE
[bug]: Canvas pencil shortcuts 

### ISSUE THREAD

**Issue by Afraskai** [invoke-ai/InvokeAI#4740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8

### What version did you experience this issue on?

3.2.0RC3

### What happened?

Hello! 

for me the shortcuts for resizing the brush tool stop working in WebUI --> Unified Canvas when I switch from base to mask and vice versa.

This is just a little issue but would speed up the process if it would work.

Feel free to contact me!

**Comment by StefanTobler** [comment]
Hmm, I am unable to replicate this issue. Would it be possible to share a video?

**Comment by Afraskai** [comment]
Hi @StefanTobler,
when you open the canvas and choose base or mask and use the shortcuts (ü/* on german keyboard) for changing the size of the tool you have to klick once till you can change the size with the shortcut keys.

1. choose mask
2. use the shortcut to resize the tool
3. change to base
4. use the shortcut to resize the tool (shortcuts dont work)
5. click once with the mouse
6. shortcut will work

Normally it should work without click.

https://github.com/invoke-ai/InvokeAI/assets/82087345/d57683cd-5810-47ff-a1a6-0d0134594fbc

**Comment by clsn** [comment]
What I've seen happen with this using the keyboard shortcuts at any rate is that it acts like you're typing `[` and `]` in the Layer name field.  That field seems to have the focus, which is why the shortcuts aren't making it to the canvas tool.

**Comment by psychedelicious** [comment]
This is expected, you cannot use keyboard shortcuts in a field that allows character inputs of the same type.
