### ISSUE TITLE
[bug]: When using Dynamic Prompt mode, a batch of images always uses the same seed

### ISSUE THREAD

**Issue by gaspesla** [invoke-ai/InvokeAI#4747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cuda

### VRAM

32GB

### What version did you experience this issue on?

3.1.1

### What happened?

My goal is to generate a collection of images, (say 100 images), with different random seeds. I can do this by simply entering **100** into the **Images** field in the **General** section. Works fine.  However, as soon as I turn on **Dynamic Prompts** mode to get a bit of variety, the batch _no longer uses random seeds_. All 100 images have the same seed. I think this a bug, as if I wanted to use a non-random seed I could just turn off the **Random** toggle. 

Note that I'm not using the **Combinatorial Generation** option.

### Contact Details

plugtwo@gmail.com

**Comment by hipsterusername** [comment]
Not a bug. Functions explicitly with setting in 3.2
