### ISSUE TITLE
[bug]: unable to use controlnet on invoke ai

### ISSUE THREAD

**Issue by jjiikkkk** [invoke-ai/InvokeAI#4751]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

a notebook

### What happened?

unable to add controlnet, seeming the function blocked

### Screenshots

![image](https://github.com/invoke-ai/InvokeAI/assets/73511302/db7d3169-dfcb-47ab-99dc-bdd684d6a4fb)

**Comment by Millu** [comment]
Have you installed any ControlNets? That will only be available if you have installed some

**Comment by JWBWork** [comment]
I'm also having this problem. I downloaded a couple of (these control nets)[https://civitai.com/models/9251?modelVersionId=10971], dropped them in `InvokeAI/autoimport/checkpoints/`, then imported them using the model manager in the web GUI.

I still have the `Add Controlnet` button disabled. Weirdly enough the controlnets are showing up under my models dropdown.

**Comment by JWBWork** [comment]
I've resolved this issue on my end - you need to actually download the control-nets via InvokeAI's CLI using the download models option (option 5)

After installing control-nets from there the interface is enabled

**Comment by jjiikkkk** [comment]
actually download the control-nets via InvokeAI's CLI using the download models option (option 5), what is this? i am using a notebook, and I do not see any CLI
I added from the command lines

**Comment by Millu** [comment]
The easiest way to use ControlNet is by downloading the models with the model manager (the last icon in the sidebar) 

You can paste the HuggingFace repo ID in the Add Model field - for example to use: https://huggingface.co/lllyasviel/sd-controlnet-canny 

The repo ID is `lllyasviel/sd-controlnet-canny`

**Comment by jjiikkkk** [comment]
okay i will try again, thanks a lot
in fact under the same repo ID, there are several types of canny

https://huggingface.co/lllyasviel/sd-controlnet-canny/resolve/main/diffusion_pytorch_model.bin
https://huggingface.co/lllyasviel/sd-controlnet-canny/resolve/main/diffusion_pytorch_model.safetensors

**Comment by jjiikkkk** [comment]
so simply one repo ID will determine which model to download, bin or safetensors?

**Comment by Millu** [comment]
Yep - the model manager will handle the downloading and organization for you

**Comment by psychedelicious** [comment]
You mentioned you are running InvokeAI in a notebook. Do you mean Google Colab? We don't really support that, you don't have access to the actual system to configure it.

**Comment by psychedelicious** [comment]
Because we don't maintain a colab notebook we can't provide much support beyond directing you to try using the model manager to install models via repo id.

**Comment by XingyuFu** [comment]
well, I want to know, how can I download the reference-only controlnet model? Or we can use others instead of it?

**Comment by psychedelicious** [comment]
@XingyuFu It sounds like you need help with installing a model. Please join our [discord](https://discord.gg/ZmtBAhwWhy) to ask for help.
