### ISSUE TITLE
[bug]: how to solve this, unable to open http://localhost:9090/

### ISSUE THREAD

**Issue by jjiikkkk** [invoke-ai/InvokeAI#4752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

notebook

### What happened?

http://localhost:9090/ unable to open

### Screenshots

http://localhost:9090/

**Comment by Millu** [comment]
Could you provide more detail please?

**Comment by jjiikkkk** [comment]
okay, i have got an idea from youtube. I will try. BTW still unable to upload controlnet
how to do that? possible to show some screenshots?

**Comment by psychedelicious** [comment]
We don't maintain a notebook version of invoke, we can't really help you there.

If you need help with anything else please make a thread on discord.
