### ISSUE TITLE
[bug]: permission denied on mac

### ISSUE THREAD

**Issue by power9799** [invoke-ai/InvokeAI#4756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

16

### What version did you experience this issue on?

3.1.1

### What happened?

It says the installation is successful, but when i tried to open it on a m2 mac, it permission denied.  The script:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tempfile.py:895: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/var/folders/wb/b2d5r7yj3jsf7ftrw595lfjw0000gn/T/tmp_enfhq2v'>
  _warnings.warn(warn_message, ResourceWarning)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tempfile.py:895: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/var/folders/wb/b2d5r7yj3jsf7ftrw595lfjw0000gn/T/invokeai-installer-tmpx7efy5po'>
  _warnings.warn(warn_message, ResourceWarning)
?@MacBook-Pro invoke-install % 
?@MacBook-Pro invoke-install % 2
zsh: command not found: 2
?@MacBook-Pro invoke-install % /Use                                                          
zsh: no such file or directory: /Use
?@MacBook-Pro invoke-install % invokeai-web
zsh: command not found: invokeai-web
?@MacBook-Pro invoke-install %    invokeai
zsh: command not found: invokeai
?@MacBook-Pro invoke-install % /Users/?/Downloads/InvokeAI-Installer/templates/invoke.sh.in 
zsh: permission denied: /Users/?/Downloads/InvokeAI-Installer/templates/invoke.sh.in

**Comment by Millu** [comment]
What kind of install did you do?

**Comment by power9799** [comment]
> What kind of install did you do?

I used automated installation

**Comment by Millu** [comment]
You'll want to run invoke by running the `invoke.sh` script in your invokeai installation location

**Comment by power9799** [comment]
Thanks a lot!
