### ISSUE TITLE
[bug]: Uneditable canvas after cleared queue

### ISSUE THREAD

**Issue by vrubzov1957** [invoke-ai/InvokeAI#4764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

11

### What version did you experience this issue on?

3.2.0rc3

### What happened?

After pressing of "Cancel full queue" runnging from canvas - then buttons of Canvas is Unactive. I cannot paint on it, and even cant save a current canvas image to gallery. To continue my work - I need send to Canvas a other image.

### Screenshots

<img width="614" alt="but" src="https://github.com/invoke-ai/InvokeAI/assets/54937209/ee10fff5-ac1d-4a06-afa2-80d1c1053462">

**Comment by hipsterusername** [comment]
Did you have a generated inpainting image waiting for approval?

**Comment by vrubzov1957** [comment]
It is not shown. 
But all other elements works as if "inpainting image waiting for approval" pop-up is showing.

**Comment by rpfile** [comment]
this behavior could be related to my bug here:

https://github.com/invoke-ai/InvokeAI/issues/4760

i have also seen what you are describing in this ticket.

**Comment by JWBWork** [comment]
I've seen this as well. I think it happens when I clear the queue while it's still "warming up" before I see any noise/image generation on the canvas

**Comment by hipsterusername** [comment]
cc: @psychedelicious

**Comment by psychedelicious** [comment]
I've reproduced the issue on `main` and identified the cause. I'll need to add some additional events related to batch processing status to resolve this correctly.

As a reminder for myself, we need to let the canvas know when a all items in a batch have finished processing ('completed', 'failed' or 'canceled').
