### ISSUE TITLE
[bug]: Gratuitous, parasitic, endlessly repeated, pointless menu in version 3.2.0

### ISSUE THREAD

**Issue by lutusp** [invoke-ai/InvokeAI#4768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

24gb

### What version did you experience this issue on?

3.2.0

### What happened?

During launch, the following inquiry appears, each and every time, without fail, perpetually:

`
Please select the type of the V2 checkpoint named v1-5-pruned-emaonly.safetensors:
[1] A model based on Stable Diffusion v2 trained on 512 pixel images (SD-2-base)
[2] A model based on Stable Diffusion v2 trained on 768 pixel images (SD-2-768)
[3] Skip this model and come back later.

select> 
`

After this menu appears, regardless of what entry is made, the program ignores the response and asks the same question again on the next launch. There is no escape from this menu, no remedy, no "never show this menu ever again", no command-line argument to prevent its appearance.

### Additional context

There should be a way to prevent the appearance of parasitic and pointless menus during launch. Just saying.

### Contact Details

lutusp@gmail.com

**Comment by psychedelicious** [comment]
Can you please share your `models.yaml` file here? Typically in `invokeai/config/models.yaml`, where `invokeai/` is your install directory.

**Comment by lutusp** [comment]
In 3.2.0, the path is now invokeai/configs/models.yaml. Note the plural. Here it is:

`
# This file describes the alternative machine learning models
# available to InvokeAI script.
#
# To add a new model, follow the examples below. Each
# model requires a model config file, a weights file,
# and the width and height of the images it
# was trained on.
__metadata__:
  version: 3.0.0
sd-1/main/v1-5-pruned-emaonly:
  path: /netbackup/home/lutusp/invokeai/autoimport/link/v1-5-pruned-emaonly.ckpt
  description: sd-1 main model v1-5-pruned-emaonly
  config: configs/stable-diffusion/v1-inference-v.yaml
  variant: normal
  format: checkpoint
sd-1/lora/openjourneyLora:
  path: /netbackup/home/lutusp/invokeai/autoimport/link/openjourneyLora.safetensors
  description: sd-1 lora model openjourneyLora
  format: lycoris
sdxl/main/sd_xl_base_1.0:
  path: /netbackup/home/lutusp/invokeai/autoimport/link/SDXL/sd_xl_base_1.0.safetensors
  description: sdxl main model sd_xl_base_1.0
  config: configs/stable-diffusion/sd_xl_base.yaml
  variant: normal
  format: checkpoint
sdxl-refiner/main/sd_xl_refiner_1.0:
  path: /netbackup/home/lutusp/invokeai/autoimport/link/SDXL/sd_xl_refiner_1.0.safetensors
  description: sdxl-refiner main model sd_xl_refiner_1.0
  config: configs/stable-diffusion/sd_xl_refiner.yaml
  variant: normal
  format: checkpoint
sdxl/lora/sd_xl_offset_example-lora_1.0:
  path: /netbackup/home/lutusp/invokeai/autoimport/link/SDXL/sd_xl_offset_example-lora_1.0.safetensors
  description: sdxl lora model sd_xl_offset_example-lora_1.0
  format: lycoris

`

During installation, to avoid re-downloading everything, I create a symlink to my existing archive of models, at invokeai/autoimport/link.

After any response to the prompt above, this message appears:

`
[2023-10-03 06:17:00,902]::[InvokeAI]::WARNING --> Failed to process '/netbackup/home/lutusp/invokeai/autoimport/link/v1-5-pruned-emaonly.safetensors': A model named "v1-5-pruned-emaonly" is already installed.
`

Then, on the next launch, the process repeats.

I hope this helps.

**Comment by RetroBum** [comment]
This is happening for me with every autoimported SD1.5 model. They're all detected as SD2 and each pop this message. Skipping them all and launching shows them all in the model manager, correctly labelled as 1.5.
