### ISSUE TITLE
[bug]: FaceTools font not bundled with app

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#4771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

3.2.0

### What happened?

The `FaceIdentifier` node uses a font, stored at `invokeai/assets/fonts/inter/Inter-Regular.ttf`.

It looks like `pyproject.toml` wants to know about it else it won't include it in the build.

Said config file is a mystery to me, so I'm hoping someone else can fix this. By "someone else", I mean Lincoln 😇

**Comment by lstein** [comment]
Ok, I’ll add it to the bundle.

**Comment by lstein** [comment]
Fixed in #4775
