### ISSUE TITLE
[bug]: Nodes skips ONNX model input field due to no template

### ISSUE THREAD

**Issue by ymgenesis** [invoke-ai/InvokeAI#4776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

16gb

### What version did you experience this issue on?

main

### What happened?

JS console debug message shows nodes skips loading the ONNX model loader model input field due to no template

### Screenshots

<img width="744" alt="Screenshot 2023-10-03 at 1 32 39 PM" src="https://github.com/invoke-ai/InvokeAI/assets/25252829/310c9f9f-6c95-46d6-b5fe-bee60f3aef19">

**Comment by psychedelicious** [comment]
ONNX support has been removed.
