### ISSUE TITLE
[enhancement]: Keep Selected in View within Gallery

### ISSUE THREAD

**Issue by Oflrnos** [invoke-ai/InvokeAI#4778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

steinn on discord

### What should this feature add?

A way to easily know and find the selected image in the gallery. As you browse the gallery using ← & → arrow keys, as one can quickly lose track of where in the list the selected one is. Auto-scrolling to follow along the selected as it goes down or up, always keeping it in view, or some button to scroll to where it is.

I found myself wanting to drag multiple images in a row onto another board only to drag the wrong image(s) or else hard to find where I am / was.

Currently if you repeatedly click the right arrow to view previous images the selected border quickly moves down and out of view depending on screen resolution and zoom %.

Might be worth it to have it as a toggleable setting to have it always in view.

### Alternatives

one could have a little indicator on the scroll where like a circle or something next to it indicating where one would scroll to to find it.

**Comment by psychedelicious** [comment]
Thanks! We use [react-virtuoso](https://github.com/petyosi/react-virtuoso/) for the gallery. It provides support for this kind of feature.

This would be a good first issue for someone who wants to work on the UI.

**Comment by rohinish404** [comment]
can i take is up? It seems a bit complicated but will try! :)

**Comment by psychedelicious** [comment]
@rohinish404 Sure, I've assigned the issue to you.
