### ISSUE TITLE
[bug]: IP-Adapter Model Installation not working

### ISSUE THREAD

**Issue by schoenid** [invoke-ai/InvokeAI#4783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

3.2.0

### What happened?

Following the instructions at https://github.com/invoke-ai/InvokeAI/releases:

> Image Encoders:
> 
> [InvokeAI/ip_adapter_sd_image_encoder](https://huggingface.co/InvokeAI/ip_adapter_sd_image_encoder)
> [InvokeAI/ip_adapter_sdxl_image_encoder](https://huggingface.co/InvokeAI/ip_adapter_sdxl_image_encoder)
> IP-Adapter Models:
> 
> [InvokeAI/ip_adapter_sd15](https://huggingface.co/InvokeAI/ip_adapter_sd15)
> [InvokeAI/ip_adapter_plus_sd15](https://huggingface.co/InvokeAI/ip_adapter_plus_sd15)
> [InvokeAI/ip_adapter_plus_face_sd15](https://huggingface.co/InvokeAI/ip_adapter_plus_face_sd15)
> [InvokeAI/ip_adapter_sdxl](https://huggingface.co/InvokeAI/ip_adapter_sdxl)
> These can be installed from the Model Manager by choosing "Import Models" and pasting in the following list of repo_ids:

Pasted this in (to Model Manager / Add Model):
`InvokeAI/ip_adapter_sd_image_encoder InvokeAI/ip_adapter_sdxl_image_encoder InvokeAI/ip_adapter_sd15 InvokeAI/ip_adapter_plus_sd15 InvokeAI/ip_adapter_plus_face_sd15 InvokeAI/ip_adapter_sdxl`

Resulting message:
"**Undefined**".

Can't install this way.

**Comment by hipsterusername** [comment]
did you pass these in one at a time, or as the long string you just posted?

**Comment by schoenid** [comment]
> did you pass these in one at a time, or as the long string you just posted?

Just as 1 long string ...
