### ISSUE TITLE
[bug]: Unable to install 3.2.0: InvokeAI-Installer[onnx]' is not installable.

### ISSUE THREAD

**Issue by Neeqstock** [invoke-ai/InvokeAI#4792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What version did you experience this issue on?

3.2.0

### What happened?

Install crashes after a while, giving me this weird error...
I'm doing a clean install, having deleted a previous version of InvokeAI.
pip 23.2.1 is installed in my system's global pip installation, for some reason it doesn't detect it...

### Screenshots

![immagine](https://github.com/invoke-ai/InvokeAI/assets/15343295/ef2fec89-b902-4349-b94b-83f3270ec450)

### Contact Details

niqscr@gmail.com

**Comment by Shal-Ziar** [comment]
Ive had the same issue, when installing from the Invokeai/installer directory.
For me I could fix it by running:
```
/home/<USER>/invokeai/.venv/bin/pip install --require-virtualenv --use-pep517 '/home/<USER>InvokeAI-3.2.0[onnx]' --extra-index-url https://download.pytorch.org/whl/rocm5.4.2
```
As it seems that it was linking to the InvokeAI/installer directory instead of the InvokeAi directory which houses the pyproject.toml needed for the install.

**Comment by joshistoast** [comment]
> Ive had the same issue, when installing from the Invokeai/installer directory. For me I could fix it by running:
> 
> ```
> /home/<USER>/invokeai/.venv/bin/pip install --require-virtualenv --use-pep517 '/home/<USER>InvokeAI-3.2.0[onnx]' --extra-index-url https://download.pytorch.org/whl/rocm5.4.2
> ```
> 
> As it seems that it was linking to the InvokeAI/installer directory instead of the InvokeAi directory which houses the pyproject.toml needed for the install.

Helping someone with this issue, any idea what this would look like for windows??
Thanks in advance!

**Comment by psychedelicious** [comment]
The installer and install docs have been redone for v4. Please create a new issue if the problem persisted with the latest release (v4.1.0).
