### ISSUE TITLE
[bug]: VAE is not changing when "Use all"

### ISSUE THREAD

**Issue by vrubzov1957** [invoke-ai/InvokeAI#4796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

11

### What version did you experience this issue on?

3.2.0rc3

### What happened?

When we press "Use All" on generated image - VAE what was used for generating of image is not setting.

But in different situations need either use old VAE from generated image or new VAE. It also will be good if there will flag like [FIX-VAE] - so that we can optionally enable or disable the VAE changing.
If it is hard for add - then let it changing as in generated image, please)

**Comment by psychedelicious** [comment]
Good first issue for a UI/frontend contributor:
- The logic will all live in `invokeai/frontend/web/src/features/parameters/hooks/useRecallParameters.ts`
- To recall the VAE, we need to check if the VAE model is available before setting it. There's existing logic for recalling a LoRA, ControlNet, etc that you could use as a reference. Generally, we need to:
  - use `mainModelsAdapter` to 
- On review, we don't check if the main model is available on the system before setting it, so it'd be create if this was fixed at the same time

**Comment by psychedelicious** [comment]
(accidentally closed sorry!)

**Comment by StefanTobler** [comment]
You can assign to me, I am gonna try and get this in this weekend. 

I did notice that precision was not in the metadata for the image, I have not looked through the issues but this may be something we want to add to the VAE metadata.

**Comment by vrubzov1957** [comment]
In versions >3.3.0 it has been fixed as I tested it. 
Check it out please, and if all good - issue can be closed

**Comment by StefanTobler** [comment]
I just tested on 3.3.0post3 and it doesn't look to be working. Correct me if I am misunderstanding the issue. ![vae_recall](https://github.com/invoke-ai/InvokeAI/assets/22108632/0e4594cc-c4b5-4f77-9d3f-a6c12ff8ec90)

**Comment by psychedelicious** [comment]
Thanks @StefanTobler , feel free to @ me here or on discord if you have any questions.
