### ISSUE TITLE
[bug]: VAE convert fails for SDXL models

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#4798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.1.1

### What happened?

@lstein Using 3.1.1 - Copying vea models into the sdxl/vae folder does show up in the web UI but cough this error when generating:

Error while invoking:
Vae conversion not supported for model type: BaseModelType.StableDiffusionXL

Note: same pattern works with sd-1 vae models

based on vae.py _convert_vae_ckpt_and_cache doesnt support diffuser conversion for sdxl models:
if base_model in {BaseModelType.StableDiffusion1, BaseModelType.StableDiffusion2}:

What is the proper mechanic to support  custom vea models?

Also, I don't see any vae in the models.yaml, in that normal?

### Additional context
[sdxl_vae.safetensors](https://huggingface.co/stabilityai/sdxl-vae/blob/main/sdxl_vae.safetensors)
_No response_

**Comment by psychedelicious** [comment]
The model manager was rewritten for v4 and conversion logic moved to diffusers. Please create a new issue if the problem persisted with the latest release (v4.1.0).
