### ISSUE TITLE
[bug]: HotKey "Use All" on key "A" not works

### ISSUE THREAD

**Issue by vrubzov1957** [invoke-ai/InvokeAI#4800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

11

### What version did you experience this issue on?

3.2.0rc3

### What happened?

Hotkey "Use All (A)" for apply config of a early generated image not works.

Other HotKeys - UseSeed (S) and UsePromt (P) - works good

**Comment by Millu** [comment]
Thanks for reporting! Can confirm this still exists in 3.2.0, but there are other bug fixes included in the actual since 3.2.0rc3 if you'd like to update

**Comment by vrubzov1957** [comment]
> Thanks for reporting! Can confirm this still exists in 3.2.0, but there are other bug fixes included in the final release since 3.2.0rc3 if you'd like to update

<img width="246" alt="set" src="https://github.com/invoke-ai/InvokeAI/assets/54937209/44f330a6-0ea1-42d2-aa23-d74750483866">


In 3.2.0 any hotkeys for apply data from generated image not work at all. 
I see pop-up "Parameter note set" when press keys A, S, or P. 

Web-buttons for apply data from generated images - works normally.

**Comment by psychedelicious** [comment]
Thanks, fixed in next release
