### ISSUE TITLE
[bug]: Automated installer doesn't work for installing outside of `C:` directory?

### ISSUE THREAD

**Issue by nopeless** [invoke-ai/InvokeAI#4802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

10GB

### What version did you experience this issue on?

3.2.0

### What happened?

It appears that drive letter is changed to C at some point. I am not sure where this is from though

```txt
Please make your selection: 1
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Installing PyTorch 🔥 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Fatal error in launcher: Unable to create process using '"C:\invokeai\.venv\Scripts\python.exe"  "N:\invokeai\.venv\Scripts\pip.exe" install --require-virtualenv numpy~=1.24.0 urllib3~=1.26.0 requests~=2.28.0 torch~=2.0.0 torchmetrics==0.11.4 torchvision>=0.14.1 --force-reinstall --extra-index-url https://download.pytorch.org/whl/cu118': The system cannot find the file specified.
```

### Screenshots

![image](https://github.com/invoke-ai/InvokeAI/assets/38830903/b7144d7f-aef7-4fcb-a2bf-d0feb659ba93)

**Comment by Millu** [comment]
What was your targeted installation location?

**Comment by nopeless** [comment]
I might have found the issue. Let me verify it when I go back. I'll mention you when I get more clues

**Comment by nopeless** [comment]
Closing this issue because of two issues

1. I was unable to replicate this behavior with version 3
2. The old version installed on my computer was version 2

I believe this is some kind of compatibility issue that isn't worth looking into. Thanks for the interest though @Millu
