### ISSUE TITLE
[enhancement]: High Resolution Fix in Linear Flow (SD. 1.5)

### ISSUE THREAD

**Issue by marict** [invoke-ai/InvokeAI#4820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

marict (discord)

### What should this feature add?

This issue proposes the addition of a High-Resolution Fix (HRF), also known as High-Resolution Optimization (HRO), to the Linear Text-to-Image flow for stable diffusion 1.5. The HRF technique generates images at a lower resolution and subsequently upscales them using img2img to align more closely with the model's trained image dimensions. This helps to mitigate issues like object duplication or other high-resolution artifacts.

The HRF approach in this feature consists of bilinear upscaling of the initial latents, followed by high-resolution denoising. The upscale denoiser replicates settings such as the model, VAE, control nets, LORAs, IP controller, steps, scheduler, and cfg_scale from the previous denoise step seen in the linear flow.

NOTE: This is my inaugural contribution to this project and my first foray into open-source. I'm eager to hear your thoughts and feedback, as I've been keen on having this feature in InvokeAI since I started using the platform.

### Alternatives

I have tried using the node editor- the combinatorial complexities of LORAs, ControlNets, and Ip-nets made me want to try to implement this in Linear Flow since it would probably be just as much work.

### Additional Content

<img width="1086" alt="image" src="https://github.com/invoke-ai/InvokeAI/assets/11934340/3279f8a4-a87b-4efe-9e26-20a2d5df9b15">

**Comment by Mejnun333** [comment]
How can I add "high resolution fix" mode?

**Comment by psychedelicious** [comment]
resolved in #4905

@Mejnun333 The feature is in the next release.
