### ISSUE TITLE
[enhancement]: Implement ROOP similar to Automatic1111 for face swap

### ISSUE THREAD

**Issue by ghzgod** [invoke-ai/InvokeAI#4824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

This [extension](https://github.com/s0md3v/sd-webui-roop) for automatic1111  utilizes [roop](https://github.com/s0md3v/roop) which is a faceswap application.  Images are generated and then the users uploaded face (within the roop box) are swapped onto the generated image.  The results are simply incredible.  It also has an API.  Is there a way we can utilize this?  It is the single thing keeping me holding onto automatic1111.  I noticed there are ip_adapters for face on SD1.5 but it is nothing near the results of roop.

Thank you.

### Alternatives

ip_adapters

**Comment by ghzgod** [comment]
Actually I think I might close this issue.  I found https://github.com/ymgenesis/NodeUtilities  which includes a custom face_swapper node.

**Comment by Millu** [comment]
Going to close this for now - roop / faceswap allows for 128px images, which is not large enough for high quality. In the interim, the YMGenesis node is your best bet.
