### ISSUE TITLE
[enhancement]: Convert txt2img metadata/graph into workflow

### ISSUE THREAD

**Issue by peterdandreti** [invoke-ai/InvokeAI#4834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

petecats

### What should this feature add?

Nodes are great, but there is a learning curve, below are some suggestions to make nodes more useful for beginners, but also image adjustment.

1. Providing a default node set that mirrors the basic txt2img function, and potentially also img2img function.
2. Providing a contextual menu option to convert an existing txt2img job into a node representation (with all fields filled with the relevant prompt data, chained up loras, control net etc.)

The usefulness of (2) is two-fold, not only does it offer a learning opportunity for each of the various features of stablediffusion (controlnet, IP adapter etc), but it also provides a way to tightly control the output  by adjusting the nodal representation of the workflow.

**Comment by psychedelicious** [comment]
1. We provide default workflows to do this, but we don't ship them inside the UI. We'll work on this in #4686 
2. Expect this functionality soon after #4686
