### ISSUE TITLE
[bug]: Patchmatch initializing and failed to load

### ISSUE THREAD

**Issue by RaphaelDreams** [invoke-ai/InvokeAI#4847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

3.1 and 3.2

### What happened?

Patch-match initializing but for some reason I get this error, have no clue what it means: 
---------------------------------------------------------------------
2023-10-10 22:02:01,557]::[InvokeAI]::INFO --> Patchmatch initialized
/media/Raphael/Storage/InvokeAI_WebUI/InvokeAI 3.1.0 WebUI/.venv/lib/python3.9/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Traceback (most recent call last):
  File "/media/Raphael/Storage/InvokeAI_WebUI/InvokeAI 3.1.0 WebUI/.venv/bin/invokeai-web", line 7, in <module>
    from invokeai.app.api_app import invoke_api
  File "/media/Raphael/Storage/InvokeAI_WebUI/InvokeAI 3.1.0 WebUI/.venv/lib/python3.9/site-packages/invokeai/app/api_app.py", line 26, in <module>
    from .api.dependencies import ApiDependencies
  File "/media/Raphael/Storage/InvokeAI_WebUI/InvokeAI 3.1.0 WebUI/.venv/lib/python3.9/site-packages/invokeai/app/api/dependencies.py", line 15, in <module>
    from invokeai.app.services.images import ImageService, ImageServiceDependencies
  File "/media/Raphael/Storage/InvokeAI_WebUI/InvokeAI 3.1.0 WebUI/.venv/lib/python3.9/site-packages/invokeai/app/services/images.py", line 37, in <module>
    from invokeai.app.util.metadata import get_metadata_graph_from_raw_session
  File "/media/Raphael/Storage/InvokeAI_WebUI/InvokeAI 3.1.0 WebUI/.venv/lib/python3.9/site-packages/invokeai/app/util/metadata.py", line 6, in <module>
    from invokeai.app.services.graph import Edge
  File "/media/Raphael/Storage/InvokeAI_WebUI/InvokeAI 3.1.0 WebUI/.venv/lib/python3.9/site-packages/invokeai/app/services/graph.py", line 154, in <module>
    class GraphInvocationOutput(BaseInvocationOutput):
  File "/media/Raphael/Storage/InvokeAI_WebUI/InvokeAI 3.1.0 WebUI/.venv/lib/python3.9/site-packages/invokeai/app/invocations/baseinvocation.py", line 618, in wrapper
    cls.__annotations__.update({"type": output_type_annotation})
AttributeError: type object 'GraphInvocationOutput' has no attribute '__annotations__'
-----------------------------------------
End Log

### Screenshots

![image](https://github.com/invoke-ai/InvokeAI/assets/147578531/df17094a-e219-477f-8f45-79532719962a)

**Comment by Lolagatorade** [comment]
Honestly man I been running arch even reinstalled the system at one point I think patchmatch isn't a thing anymore it hasn't been updated or looked after in ages. Couldn't get tj to work for the life of me.

**Comment by Millu** [comment]
Believe it's a Python version issue: https://github.com/invoke-ai/InvokeAI/issues/4440

Try updating to Python 3.10 to solve the error. 

For patchmatch, take a look at these docs: https://invoke-ai.github.io/InvokeAI/installation/060_INSTALL_PATCHMATCH/

**Comment by psychedelicious** [comment]
Patchmatch is successfully initialized according to the terminal output, this isn't a patchmatch issue.

It looks like you are just on an outdated version, which is missing the fix for this issue. You don't need to upgrade from python 3.9 actually, we've handled this specific issue. Please update your install of invoke.

**Comment by RaphaelDreams** [comment]
How would I update from 3.9 to 3.10?

**Comment by RaphaelDreams** [comment]
> Patchmatch is successfully initialized according to the terminal output, this isn't a patchmatch issue.
> 
> It looks like you are just on an outdated version, which is missing the fix for this issue. You don't need to upgrade from python 3.9 actually, we've handled this specific issue. Please update your install of invoke.

I updated to the 3.3 version and am still having the same issue, I also installed 3.2 then updated to the 3.3 branch through the terminal.

**Comment by RaphaelDreams** [comment]
I think it has to do with something in python3.19 but I have no clue and I need this version of python.

**Comment by psychedelicious** [comment]
@RaphaelDreams Dang, that's unfortunate. I'm surprised we haven't gotten more issues about this.

I created a new venv with python 3.9.6 and I have the same issue there.

A workaround is to use [`pyenv`](https://github.com/pyenv/pyenv) to install a more up-to-date version of python, then use that to install InvokeAI. That will leave your existing python installation alone. The updated python would automatically be used by InvokeAI.

I should also mention we have decided to deprecate python 3.9 in an upcoming release, so this still will probably be necessary anyways. Sorry for the hassle.

**Comment by RaphaelDreams** [comment]
It worked it was just a older version of python that was not compatible with invokeai, I really appreciate the help.

Here is a guide for to install pyenv with anyone with the same issue needing a newer version but not willing to give up their anaconda install: https://www.k0nze.dev/posts/install-pyenv-venv-vscode/ also need python3-openssl instead of the one listed in that list or it won't work otherwise.

Thanks for the help now I can go back to making AI generated goodness.

**Comment by psychedelicious** [comment]
Good to hear and thanks for that link. Have fun!
