### ISSUE TITLE
[bug]: [Invoke v.3.3.0] - Error when using SDXL model

### ISSUE THREAD

**Issue by suonnon** [invoke-ai/InvokeAI#4871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

3.3.0

### What happened?

I imported SDXL models from a folder by Invoke webui. But when I generate image, Invoke keeps showing "Server Error" message.

After that. I tried to:
- Delete the model from the webui.
- Using custom path for SDXL models in "invokeai.yaml" file
-> Same! Still error.

This issue has been happening since v.3.1.

### Screenshots

![Screenshot 2023-10-13 150231](https://github.com/invoke-ai/InvokeAI/assets/133345496/b76469b0-56f0-4253-bed4-3634f9eb0371)
![Screenshot 2023-10-13 150345](https://github.com/invoke-ai/InvokeAI/assets/133345496/ac42b46a-c03e-4516-b28d-5544be928702)
![Screenshot 2023-10-13 145606](https://github.com/invoke-ai/InvokeAI/assets/133345496/493c3dd0-2d77-4daa-bd1e-06b1d496b4ad)

### Additional context

This issue was not happen when:
- Copy the SDXL models into folder: *\models\sdxl\main or *\autoimport instead of import from custom folder location.
- Invoke 3.0

**Comment by Millu** [comment]
If /autoimport works, you can create a symlink to your A111 models folder to import them

**Comment by BobaSweat** [comment]
I'm having the same issue.

**Comment by psychedelicious** [comment]
The model manager was rewritten for v4. You can install models in-place (i.e. from a shared location) in the MM UI. Please create a new issue if the problem persisted with the latest release (v4.1.0).
