### ISSUE TITLE
[bug]: KDPM 2 / KDPM 2 Ancestral schedulers don't produce expected output on M1

### ISSUE THREAD

**Issue by peterdandreti** [invoke-ai/InvokeAI#4872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

15

### What version did you experience this issue on?

3.3.0

### What happened?

KDPM 2 / KDPM 2 Ancestral schedulers output visual noise on M1, (see example) from the below specs:

Generation Mode: txt2img
Positive Prompt: an astronaught riding a unicorn in space
Seed: 1
Model: stable-diffusion-v1-5
Width: 512
Height: 512
Scheduler: kdpm_2_a
Steps: 10
CFG scale: 7

Changing these specs doesn't improve the output however.

### Screenshots

![a51805f4-8922-480f-8ff2-85e9d1676a24](https://github.com/invoke-ai/InvokeAI/assets/56002693/4e520b83-b3ac-459c-b6bb-f667677356eb)

### Additional context

Predates 3.3.0

### Contact Details

petecats

**Comment by Adreitz** [comment]
There is a behavioral difference between KDPM2 and KDPM2 Ancestral. Base KDPM2 produces a black image, while Ancestral produces color noise. In any case, I can confirm that these schedulers do not work on Apple Silicon.

M2 Max, Sonoma, Torch(Vision) nightlies October 14

**Comment by Vargol** [comment]
https://github.com/pytorch/pytorch/issues/111374

**Comment by peterdandreti** [comment]
Just looping back in to say that this has been resolved.

**Comment by niffrig** [comment]
This appears to be reintroduced/regressed in 5.0 at least when doing upscale operations. 
<img width="1016" alt="Screenshot 2024-10-01 at 11 04 26 AM" src="https://github.com/user-attachments/assets/876c4467-363d-4117-8e7b-37b45e4c4e2d">
