### ISSUE TITLE
[bug]: Command-Line Interface not working, SQLite problem?

### ISSUE THREAD

**Issue by StudEu** [invoke-ai/InvokeAI#4874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

3.2.0

### What happened?

Once I run "invoke.bat" and select to use _"2. Explore InvokeAI nodes using a command-line interface"_ it doesn't work, while the web-interface runs and outputs just fine (v3.2.0 on a fresh Win10 machine) 

_**In-depth Explanation**_
A couple months ago I programmed an installation that auto-runs the command-line interface of InvokeAI and it works nicely within version 2.3.4

Yesterday I've downloaded v3.2.0 on another PC with the exact same components _(i7-13700K, RTX 4070ti (updated drivers), 64GB RAM DDR5)_ and, although the browser-based interface works, the command-line interface doesn't, meaning once I select it in the "Desired action" list that appears once you run "invoke.bat" it gives me an error starting up something and I get back to the "Desired action" selection.
Downloading and installing v2.3.4 nowadays doesn't work either.

I have formatted a machine to Windows 10 Pro and followed the installation guide in the Github meticulously, but ended up exactly as before; I could use the web interface but not the command-line one.
This PC isn't particularly powerful, but as I said the web interface runs and outputs images, so I suppose we can rule out the PC not performing enough.
The specifics are: i7-2700K, GTX 1650, 32GB RAM (not sure which DDR)

The error message that the v3.2.0 displays seems to point to problems with "sqlite", although updating it individually didn't solve the problem.
I haven't found any documentation online.
The error message the CMD gives me is this one:

_Desired action:_
_1. Generate images with the browser-based interface_
_2. Explore InvokeAI nodes using a command-line interface_
_3. Run textual inversion training_
_4. Merge models (diffusers type only)_
_5. Download and install models_
_6. Change InvokeAI startup options_
_7. Re-run the configure script to fix a broken install or to complete a major upgrade_
_8. Open the developer console_
_9. Update InvokeAI_
_10. Run the InvokeAI image database maintenance script_
_11. Command-line help_
_Q - Quit_
_Please enter 1-11, Q: [1] 2_

_Starting the InvokeAI command-line..
[2023-10-13 16:25:22,924]::[InvokeAI]::INFO --> Patchmatch initialized
C:\InvokeAI\.venv\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be removed in 0.17. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(_
_[2023-10-13 16:25:24,065]::[InvokeAI]::INFO --> InvokeAI version 3.2.0_
_[2023-10-13 16:25:24,142]::[InvokeAI]::INFO --> GPU device = cuda NVIDIA GeForce GTX 1650_
_[2023-10-13 16:25:24,160]::[InvokeAI]::INFO --> Scanning C:\InvokeAI\models for new models_
_[2023-10-13 16:25:24,710]::[InvokeAI]::INFO --> Scanned 8 files and directories, imported 0 models_
_[2023-10-13 16:25:24,722]::[InvokeAI]::INFO --> Model manager service initialized_
_[2023-10-13 16:25:24,725]::[InvokeAI]::INFO --> InvokeAI database location is "C:\InvokeAI\databases\invokeai.db"_
_Traceback (most recent call last):_
  _File "C:\Users\Valentina\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,_
  _File "C:\Users\Valentina\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)_
  _File "C:\InvokeAI\.venv\Scripts\invokeai.exe\main.py", line 7, in <module>_
  _File "C:\InvokeAI\.venv\lib\site-packages\invokeai\frontend\legacy_launch_invokeai.py", line 18, in main
    invoke_cli()_
  File "C:\InvokeAI\.venv\lib\site-packages\invokeai\app\cli_app.py", line 257, in invoke_cli
    graph_execution_manager = SqliteItemStorage[GraphExecutionState](conn=db_conn, table_name="graph_executions")
  File "C:\Users\Valentina\AppData\Local\Programs\Python\Python310\lib\typing.py", line 957, in call
    result = self.origin(*args, **kwargs)
TypeError: SqliteItemStorage.init() missing 1 required positional argument: 'lock'_

Thanks for your time, I'm here for any additional question

### Screenshots

![image (4)](https://github.com/invoke-ai/InvokeAI/assets/147846713/4130365e-3fd2-4689-975b-709725ceeaab)

### Contact Details

e.cinalli@studeogroup.it

**Comment by Millu** [comment]
Try clearing the queue from via the WebUI and then using the CLI

**Comment by max-privatevoid** [comment]
This doesn't look like a state problem. In `cli_app.py`, `SqliteItemStorage` is constructed with an argument `conn`, but everywhere else in the code `db` is used instead. Someone probably missed a spot when refactoring `SqliteItemStorage` and the test suite didn't catch it.

https://github.com/invoke-ai/InvokeAI/blob/d7edf5aaadfec2fbec0eda2d9318a5a9980d2658/invokeai/app/cli_app.py#L257

This affects both `invokeai` and `invokeai-node-cli`.

**Comment by Millu** [comment]
Good eye! In any case, the CLI app is a deprecated feature that will be removed from the launcher script in an upcoming version.
