### ISSUE TITLE
[enhancement]: Add a node to extract metadata from previously generated images

### ISSUE THREAD

**Issue by TheCulprit** [invoke-ai/InvokeAI#4896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Stretch (villainstretch) on Discord

### What should this feature add?

A node to allow the extraction of metadata from an image so that images generated in txt2img can be dropped in to a workflow and the various parameters can be pulled out for use in other nodes.

Use case:
I wish to create a workflow for upscaling images generated in txt2img. 
A workflow can be created for doing it but that requires manually transferring not just the image but also all the generation parameters, one by one for every image I wish to upscale.  
With a node like this, a workflow can be created that will a user to only drop in the generated low res image and everything needed for the upscale can be extracted from it.

### Alternatives

Perhaps adding outputs to the existing Image Primitive node will suffice but may unnecessarily complicate the node.

**Comment by marict** [comment]
This doesn't extract all metadata, but I wrote this node a bit ago and could be a good starting off point
https://discord.com/channels/1020123559063990373/1155281573952897114
