### ISSUE TITLE
[bug]: seeming your repo does not work for several days

### ISSUE THREAD

**Issue by jjiikkkk** [invoke-ai/InvokeAI#4903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

16

### What version did you experience this issue on?

colab and kaggle

### What happened?

does not work
no response, and automatically disconnect
no image comes out

### Additional context

![image](https://github.com/invoke-ai/InvokeAI/assets/73511302/b620e5cd-9dea-4d93-a0b0-b56a6e986f16)
always stuck here

**Comment by Millu** [comment]
There are other users able to run InvokeAI 3.x with Collab - not sure what the specific issue is here, as it appears the image generation graph executed successfully.

**Comment by jjiikkkk** [comment]
you have upgraded your repo to 3.x?
