### ISSUE TITLE
[enhancement]: High Resolution Fix- Add automatic resolution toggle

### ISSUE THREAD

**Issue by marict** [invoke-ai/InvokeAI#4907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

marict (discord)

### What should this feature add?

A toggle should be added to the High Resolution Fix feature that allows the user to specify whether they want to manually set their high resolution fix resolution or have it automatically set. This is because those two hyperparameters can be confusing to new users, and determining an automatic setting that will work in most cases is fast and trivial.

### Alternatives

We could go with no toggle and automatically set the resolution in all cases. This would have the benefit of a less cluttered UI, but wouldn't work for power users who wish to increase their initial/height width to get away with greater fidelity at the cost of higher chances of high resolution artifacts.

### Additional Content

<img width="1050" alt="image" src="https://github.com/invoke-ai/InvokeAI/assets/11934340/f8ab39fb-8ea8-4076-b42f-5953a2721cf5">

**Comment by marict** [comment]
NOTE: Based on code owner feedback, this has been changed to have HRF automatically chose its initial resolution, not letting the user specify the height/width. This has the slight drawback of less customizability, but greatly simplifies the use of HRF, and keeps it in line with previous behavior.

**Comment by psychedelicious** [comment]
Resolved in #4905
