### ISSUE TITLE
[enhancement]: High Resolution update UI logic

### ISSUE THREAD

**Issue by Dunc4n1dah0** [invoke-ai/InvokeAI#4908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.3.0.post3

### What happened?

New **High Resolution Fix** is great, but UI is not intuitive and resolutions should be reversed. Original resolution should be in General tab, and when we want to use High Res Fix, we turn it on and set new (upscaled/higher) resolution there. When we turn it off, we get rest of UI as it was before. Now we set starting res in General tab, then when we want to use feature we turn it on, set (same) res we just set again, and new res in General tab. When we turn it off even worse, as we have to set res again in General Tab.
Feature isn't working as complete and independent. Too many clicks, when my idea of reversing resolutions solves all.

### Screenshots

<img width="334" alt="image" src="https://github.com/invoke-ai/InvokeAI/assets/104938323/0487419a-5873-45dd-9839-7cccddc86516">

**Comment by RetroBum** [comment]
This would make better workflow when generating a bunch of lowres/standard size images and then upscaling nice ones by genning same seed with hires fix on. 
Currently you have to set the general size up and then set it back down afterwards to keep genning lowres. 
I'd also suggest a scale factor, rather than just an explicit size. I'd just whack it to 2x and it would most likely stay there forever.

**Comment by marict** [comment]
Hey! I'm the person who is working on re-implementing HRF.
@Dunc4n1dah0 I agree that way works! Although, the next commit to the feature removes the manual height and width scaling sliders, this was suggested by a code owner. Intead HRF will automatically generate at 2/3rds the resolution. This matches the previous behavior of HRF in the application. 

https://github.com/invoke-ai/InvokeAI/pull/4905

I think overall it ends up being a more intiuitive UX and I've gotten quite used to it. There is a trade off of configurability though.

**Comment by psychedelicious** [comment]
Resolved in #4905
