### ISSUE TITLE
[bug]: Images get written to disk twice/duplicate output

### ISSUE THREAD

**Issue by mcbexx** [invoke-ai/InvokeAI#4911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.3.0 post 3

### What happened?

Probably has been discovered, but since I could not find an issue for this ...

Images get written to disk twice (but show up in the gallery just once).

Deleting images from the gallery of course leaves one copy in the file directory.

Edit: Going through my folder, this must have also been an issue in post2, since I found lots of duplicates that were created before updating to post3 just now.

**Comment by Millu** [comment]
This is expected behavior when generating images with the standard UI - one of the images is an "Intermediate" image and one is the final generated image. You can clear the intermediate image with `Settings -> Clear Intermediates`
