### ISSUE TITLE
[ask]:  ip adapter sd image encoder address download in folder where?

### ISSUE THREAD

**Issue by wolfkingal2000** [invoke-ai/InvokeAI#4912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

[ask]:  ip adapter sd image encoder address for download in folder where?

**Comment by Millu** [comment]
Are you looking to install the ip adapter image encoder? 

You can install it via the model manager by entering the Repo ID from models.invoke.ai: 

<img width="576" alt="Screenshot 2023-10-17 at 9 04 50 AM" src="https://github.com/invoke-ai/InvokeAI/assets/7254508/a093b106-8b31-4527-91da-54caa94d6ec5">

**Comment by wolfkingal2000** [comment]
> Are you looking to install the ip adapter image encoder?
> 
> You can install it via the model manager by entering the Repo ID from models.invoke.ai:
> 
> <img alt="Screenshot 2023-10-17 at 9 04 50 AM" width="576" src="https://user-images.githubusercontent.com/7254508/275660304-a093b106-8b31-4527-91da-54caa94d6ec5.png">

Thank you, I knew this, I wanted to know where it is located in the Windows Manager file, download it later.

**Comment by Millu** [comment]
It's not stored on your local system until you install it. Once it's installed, you can find it in `models/any/clip_vision`
