### ISSUE TITLE
[bug]: Can not  add any Boards with name of UTF8 words like Chinese 

### ISSUE THREAD

**Issue by Aittor** [invoke-ai/InvokeAI#4913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cpu

### What version did you experience this issue on?

3.2

### What happened?

I can not  add any Boards with name of UTF8 words like Chinese 

### Contact Details

ydlbull@gmail.com

**Comment by psychedelicious** [comment]
Hi, it works for me:
![image](https://github.com/invoke-ai/InvokeAI/assets/4822129/1a01203c-bd1c-4635-bd55-057f5c3594a5)

What error or behaviour do you see when you try?

**Comment by Aittor** [comment]
Yes, I got the tips of it. thanks.
