### ISSUE TITLE
[bug]: In Safari, tooltips on disabled buttons never hide

### ISSUE THREAD

**Issue by gaspesla** [invoke-ai/InvokeAI#4915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cuda

### VRAM

32GB

### What version did you experience this issue on?

3.3.0post3

### What happened?

When using invokeai web interface with the Safari web browser on a Mac, any tooltip that shows up for a disabled button (for example the **Cancel Current Item** button when there's nothing in the queue) never disappears.

### Screenshots

<img width="908" alt="image" src="https://github.com/invoke-ai/InvokeAI/assets/470563/180638d6-7b93-4d8a-a3ea-40208ca3696e">

### Additional context

Happens with Safari 17 but isn't new in Safari 17.
This issue isn't new in 3.3. It also happened in 3.2.
Chrome works fine.
Pressing the escape key clears all of the stuck tooltips.

### Contact Details

plugtwo@gmail.com

**Comment by Millu** [comment]
Unfortunately, this is a bug caused by the charka-ui library - other tooltips will display the same behavior as well.
