### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by xeinebiu** [invoke-ai/InvokeAI#4919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What version did you experience this issue on?

3.3.0post3

### What happened?

Images seems broken and not following the prompts. If you look at other images on the below screenshot, you can see broken faces

### Screenshots

![image](https://github.com/invoke-ai/InvokeAI/assets/50703441/5c7ac67b-36a2-4f5e-89d7-2c13ca20ad2d)

**Comment by Millu** [comment]
SD1.5 base model does not create great faces - try other models such as Deliberate. Alternatively, you can use the Unified Canvas's inpainting feature to inpaint better faces
