### ISSUE TITLE
[bug]: unclear uninstallation procedure

### ISSUE THREAD

**Issue by iapicca** [invoke-ai/InvokeAI#4928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### What version did you experience this issue on?

3.3.0post3

### What happened?

I need to uninstall invokeAI to make space on the hard drive (I'll attempt again the installation on an external hdd)
the space occupied by the folder `invokeai` doesn't match the space taken by the whole installation 
similarly to what has been reported [here](https://github.com/invoke-ai/InvokeAI/issues/2004#issuecomment-1764123525))

In the same issue mentioned above as been [commented](https://github.com/invoke-ai/InvokeAI/issues/2004#issuecomment-1352846537)

> 1. Delete the folder you installed into.
> 2. Delete the folder in your user profile where models and settings are stored.
> That's all, it does not leave any other trails on the system.

how do I know `where models and settings are stored.`?

### Additional context

```console
                    'c.          francesco@Francescos-Air.lan
                 ,xNMM.          ----------------------------
               .OMMMMo           OS: macOS 14.0 23A344 arm64
               OMMM0,            Host: MacBookAir10,1
     .;loddo:' loolloddol;.      Kernel: 23.0.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 56 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 56 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.9
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1440x900
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Dark)
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: WarpTerminal
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   CPU: Apple M1
    kMMMMMMMMMMMMMMMMMMMMMMd     GPU: Apple M1
     ;KMMMMMMMWXXWMMMMMMMk.      Memory: 1283MiB / 8192MiB
       .cooc,.    .,coo:.


```

**Comment by Millu** [comment]
There might be files in the `.cache` folder from HuggingFace - you can delete these as well. 

Models and settings are stored in the invokeai root directory

**Comment by iapicca** [comment]
> There might be files in the `.cache` folder from HuggingFace - you can delete these as well.
> 
> Models and settings are stored in the invokeai root directory

```console
du -sh ~/.cache/huggingface/
 35G	/Users/francesco/.cache/huggingface/
```

yep, that's the spot :) 
thanks, closing now

cc @devingfx

**Comment by devingfx** [comment]
thx
