### ISSUE TITLE
[bug]: Always Pending during image generation, gives finished image after re-launch.

### ISSUE THREAD

**Issue by LimboImbo** [invoke-ai/InvokeAI#4932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

3.3.0post2

### What happened?

When trying to generate image, it's always "pending". After re-launching, the image appears, and looks perfectly fine. No matter the amount of images, always stuck until relaunch. While "pending", keeps spamming this: `[2023-10-18 00:40:14,156]::[uvicorn.access]::INFO --> 127.0.0.1:50951 - "GET /socket.io/?EIO=4&transport=polling&t=Oi_bGhA&sid=lwnPo42pZHDkEf-gAAAA HTTP/1.1" 200` in the CMD.

### Screenshots

![Снимок экрана (521)](https://github.com/invoke-ai/InvokeAI/assets/87034271/4374c5aa-5451-431b-a547-4bba0f4436ea)

**Comment by Millu** [comment]
Could you update to 3.3.0post3 and see if the same behavior persists?

**Comment by LimboImbo** [comment]
Says:

`Collecting invokeai[xformers]@ https://github.com/invoke-ai/InvokeAI/archive/v3.3.0post3.zip
  WARNING: Certificate did not match expected hostname: codeload.github.com. Certificate: {'subject': ((('commonName', 'dns.google'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', 'Google Trust Services LLC'),), (('commonName', 'GTS CA 1C3'),)), 'version': 3, 'serialNumber': '124731335CCC16A710CD0CDA29BCBC22', 'notBefore': 'Sep 28 05:32:40 2023 GMT', 'notAfter': 'Dec 21 05:32:39 2023 GMT', 'subjectAltName': (('DNS', 'dns.google'), ('DNS', 'dns.google.com'), ('DNS', '*.dns.google.com'), ('DNS', '8888.google'), ('DNS', 'dns64.dns.google'), ('IP Address', '8.8.8.8'), ('IP Address', '8.8.4.4'), ('IP Address', '2001:4860:4860:0:0:0:0:8888'), ('IP Address', '2001:4860:4860:0:0:0:0:8844'), ('IP Address', '2001:4860:4860:0:0:0:0:6464'), ('IP Address', '2001:4860:4860:0:0:0:0:64')), 'OCSP': ('http://ocsp.pki.goog/gts1c3',), 'caIssuers': ('http://pki.goog/repo/certs/gts1c3.der',), 'crlDistributionPoints': ('http://crls.pki.goog/gts1c3/QqFxbi9M48c.crl',)}
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'codeload.github.com' doesn't match either of 'dns.google', 'dns.google.com', '*.dns.google.com', '8888.google', 'dns64.dns.google', '8.8.8.8', '8.8.4.4', '2001:4860:4860:0:0:0:0:8888', '2001:4860:4860:0:0:0:0:8844', '2001:4860:4860:0:0:0:0:6464', '2001:4860:4860:0:0:0:0:64'"))': /invoke-ai/InvokeAI/zip/refs/tags/v3.3.0post3
  WARNING: Certificate did not match expected hostname: codeload.github.com. Certificate: {'subject': ((('commonName', 'dns.google'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', 'Google Trust Services LLC'),), (('commonName', 'GTS CA 1C3'),)), 'version': 3, 'serialNumber': '124731335CCC16A710CD0CDA29BCBC22', 'notBefore': 'Sep 28 05:32:40 2023 GMT', 'notAfter': 'Dec 21 05:32:39 2023 GMT', 'subjectAltName': (('DNS', 'dns.google'), ('DNS', 'dns.google.com'), ('DNS', '*.dns.google.com'), ('DNS', '8888.google'), ('DNS', 'dns64.dns.google'), ('IP Address', '8.8.8.8'), ('IP Address', '8.8.4.4'), ('IP Address', '2001:4860:4860:0:0:0:0:8888'), ('IP Address', '2001:4860:4860:0:0:0:0:8844'), ('IP Address', '2001:4860:4860:0:0:0:0:6464'), ('IP Address', '2001:4860:4860:0:0:0:0:64')), 'OCSP': ('http://ocsp.pki.goog/gts1c3',), 'caIssuers': ('http://pki.goog/repo/certs/gts1c3.der',), 'crlDistributionPoints': ('http://crls.pki.goog/gts1c3/QqFxbi9M48c.crl',)}
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'codeload.github.com' doesn't match either of 'dns.google', 'dns.google.com', '*.dns.google.com', '8888.google', 'dns64.dns.google', '8.8.8.8', '8.8.4.4', '2001:4860:4860:0:0:0:0:8888', '2001:4860:4860:0:0:0:0:8844', '2001:4860:4860:0:0:0:0:6464', '2001:4860:4860:0:0:0:0:64'"))': /invoke-ai/InvokeAI/zip/refs/tags/v3.3.0post3
  WARNING: Certificate did not match expected hostname: codeload.github.com. Certificate: {'subject': ((('commonName', 'dns.google'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', 'Google Trust Services LLC'),), (('commonName', 'GTS CA 1C3'),)), 'version': 3, 'serialNumber': '124731335CCC16A710CD0CDA29BCBC22', 'notBefore': 'Sep 28 05:32:40 2023 GMT', 'notAfter': 'Dec 21 05:32:39 2023 GMT', 'subjectAltName': (('DNS', 'dns.google'), ('DNS', 'dns.google.com'), ('DNS', '*.dns.google.com'), ('DNS', '8888.google'), ('DNS', 'dns64.dns.google'), ('IP Address', '8.8.8.8'), ('IP Address', '8.8.4.4'), ('IP Address', '2001:4860:4860:0:0:0:0:8888'), ('IP Address', '2001:4860:4860:0:0:0:0:8844'), ('IP Address', '2001:4860:4860:0:0:0:0:6464'), ('IP Address', '2001:4860:4860:0:0:0:0:64')), 'OCSP': ('http://ocsp.pki.goog/gts1c3',), 'caIssuers': ('http://pki.goog/repo/certs/gts1c3.der',), 'crlDistributionPoints': ('http://crls.pki.goog/gts1c3/QqFxbi9M48c.crl',)}
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'codeload.github.com' doesn't match either of 'dns.google', 'dns.google.com', '*.dns.google.com', '8888.google', 'dns64.dns.google', '8.8.8.8', '8.8.4.4', '2001:4860:4860:0:0:0:0:8888', '2001:4860:4860:0:0:0:0:8844', '2001:4860:4860:0:0:0:0:6464', '2001:4860:4860:0:0:0:0:64'"))': /invoke-ai/InvokeAI/zip/refs/tags/v3.3.0post3
  WARNING: Certificate did not match expected hostname: codeload.github.com. Certificate: {'subject': ((('commonName', 'dns.google'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', 'Google Trust Services LLC'),), (('commonName', 'GTS CA 1C3'),)), 'version': 3, 'serialNumber': '124731335CCC16A710CD0CDA29BCBC22', 'notBefore': 'Sep 28 05:32:40 2023 GMT', 'notAfter': 'Dec 21 05:32:39 2023 GMT', 'subjectAltName': (('DNS', 'dns.google'), ('DNS', 'dns.google.com'), ('DNS', '*.dns.google.com'), ('DNS', '8888.google'), ('DNS', 'dns64.dns.google'), ('IP Address', '8.8.8.8'), ('IP Address', '8.8.4.4'), ('IP Address', '2001:4860:4860:0:0:0:0:8888'), ('IP Address', '2001:4860:4860:0:0:0:0:8844'), ('IP Address', '2001:4860:4860:0:0:0:0:6464'), ('IP Address', '2001:4860:4860:0:0:0:0:64')), 'OCSP': ('http://ocsp.pki.goog/gts1c3',), 'caIssuers': ('http://pki.goog/repo/certs/gts1c3.der',), 'crlDistributionPoints': ('http://crls.pki.goog/gts1c3/QqFxbi9M48c.crl',)}
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'codeload.github.com' doesn't match either of 'dns.google', 'dns.google.com', '*.dns.google.com', '8888.google', 'dns64.dns.google', '8.8.8.8', '8.8.4.4', '2001:4860:4860:0:0:0:0:8888', '2001:4860:4860:0:0:0:0:8844', '2001:4860:4860:0:0:0:0:6464', '2001:4860:4860:0:0:0:0:64'"))': /invoke-ai/InvokeAI/zip/refs/tags/v3.3.0post3
  WARNING: Certificate did not match expected hostname: codeload.github.com. Certificate: {'subject': ((('commonName', 'dns.google'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', 'Google Trust Services LLC'),), (('commonName', 'GTS CA 1C3'),)), 'version': 3, 'serialNumber': '124731335CCC16A710CD0CDA29BCBC22', 'notBefore': 'Sep 28 05:32:40 2023 GMT', 'notAfter': 'Dec 21 05:32:39 2023 GMT', 'subjectAltName': (('DNS', 'dns.google'), ('DNS', 'dns.google.com'), ('DNS', '*.dns.google.com'), ('DNS', '8888.google'), ('DNS', 'dns64.dns.google'), ('IP Address', '8.8.8.8'), ('IP Address', '8.8.4.4'), ('IP Address', '2001:4860:4860:0:0:0:0:8888'), ('IP Address', '2001:4860:4860:0:0:0:0:8844'), ('IP Address', '2001:4860:4860:0:0:0:0:6464'), ('IP Address', '2001:4860:4860:0:0:0:0:64')), 'OCSP': ('http://ocsp.pki.goog/gts1c3',), 'caIssuers': ('http://pki.goog/repo/certs/gts1c3.der',), 'crlDistributionPoints': ('http://crls.pki.goog/gts1c3/QqFxbi9M48c.crl',)}
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'codeload.github.com' doesn't match either of 'dns.google', 'dns.google.com', '*.dns.google.com', '8888.google', 'dns64.dns.google', '8.8.8.8', '8.8.4.4', '2001:4860:4860:0:0:0:0:8888', '2001:4860:4860:0:0:0:0:8844', '2001:4860:4860:0:0:0:0:6464', '2001:4860:4860:0:0:0:0:64'"))': /invoke-ai/InvokeAI/zip/refs/tags/v3.3.0post3
  WARNING: Certificate did not match expected hostname: codeload.github.com. Certificate: {'subject': ((('commonName', 'dns.google'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', 'Google Trust Services LLC'),), (('commonName', 'GTS CA 1C3'),)), 'version': 3, 'serialNumber': '124731335CCC16A710CD0CDA29BCBC22', 'notBefore': 'Sep 28 05:32:40 2023 GMT', 'notAfter': 'Dec 21 05:32:39 2023 GMT', 'subjectAltName': (('DNS', 'dns.google'), ('DNS', 'dns.google.com'), ('DNS', '*.dns.google.com'), ('DNS', '8888.google'), ('DNS', 'dns64.dns.google'), ('IP Address', '8.8.8.8'), ('IP Address', '8.8.4.4'), ('IP Address', '2001:4860:4860:0:0:0:0:8888'), ('IP Address', '2001:4860:4860:0:0:0:0:8844'), ('IP Address', '2001:4860:4860:0:0:0:0:6464'), ('IP Address', '2001:4860:4860:0:0:0:0:64')), 'OCSP': ('http://ocsp.pki.goog/gts1c3',), 'caIssuers': ('http://pki.goog/repo/certs/gts1c3.der',), 'crlDistributionPoints': ('http://crls.pki.goog/gts1c3/QqFxbi9M48c.crl',)}
ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='codeload.github.com', port=443): Max retries exceeded with url: /invoke-ai/InvokeAI/zip/refs/tags/v3.3.0post3 (Caused by SSLError(CertificateError("hostname 'codeload.github.com' doesn't match either of 'dns.google', 'dns.google.com', '*.dns.google.com', '8888.google', 'dns64.dns.google', '8.8.8.8', '8.8.4.4', '2001:4860:4860:0:0:0:0:8888', '2001:4860:4860:0:0:0:0:8844', '2001:4860:4860:0:0:0:0:6464', '2001:4860:4860:0:0:0:0:64'")))`

**Comment by LimboImbo** [comment]
So yeah, can't update...

**Comment by psychedelicious** [comment]
@LimboImbo That's a problem with either your machine or github. Please restart your computer and try again.
