### ISSUE TITLE
[bug]:  field control already exists error in session processor

### ISSUE THREAD

**Issue by kevadiyasmt** [invoke-ai/InvokeAI#4939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

15

### What version did you experience this issue on?

3.3.0

### What happened?

I am getting the "field control already exists" error in session when I am trying to use the unified canvas. find attached a screenshot below.

### Screenshots

![image](https://github.com/invoke-ai/InvokeAI/assets/138682831/3656c71d-ea03-423b-b8b2-23fb3366e84f)

**Comment by kevadiyasmt** [comment]
this appears to be an issue when I am trying to use Control Net in Unified Canvas.

**Comment by psychedelicious** [comment]
I can't recreate this on canvas. Can you please take a screenshot of your settings?

**Comment by kevadiyasmt** [comment]
![image](https://github.com/invoke-ai/InvokeAI/assets/138682831/7d671631-4ccc-41e3-92c6-3c7302a70b55)
![image](https://github.com/invoke-ai/InvokeAI/assets/138682831/d88b8e95-3c76-47bc-8f31-1bdd2ee2907f)
![image](https://github.com/invoke-ai/InvokeAI/assets/138682831/6b54ab79-ce46-4d42-89a6-f05ef4e0ee85)
![image](https://github.com/invoke-ai/InvokeAI/assets/138682831/64e5f263-a6f8-4425-9ee4-5f30ed3cc4c1)
![image](https://github.com/invoke-ai/InvokeAI/assets/138682831/ed2c3835-17d3-4c87-8b47-785215723eb9)

**Comment by kevadiyasmt** [comment]
usage of multiple control nets is causing some issues for me. using a single control net is working fine. I tried turning one controlnet off and it worked. but if I turn it on, it causes the error mentioned above.

**Comment by kevadiyasmt** [comment]
okay, thank you for the quick responses.
