### ISSUE TITLE
[bug]: ControlNet Error

### ISSUE THREAD

**Issue by AbedAchai1** [invoke-ai/InvokeAI#4943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cpu

### VRAM

12GB

### What version did you experience this issue on?

3.3.0

### What happened?

When I uploaded an image on Controlnet suddenly the image was loading continuously in the history, it looked like it was in a loop continuously loading the image

### Screenshots

![image](https://github.com/invoke-ai/InvokeAI/assets/136920434/0d4a8156-a580-498f-9308-491e7ee9c03d)
![image2](https://github.com/invoke-ai/InvokeAI/assets/136920434/eaeba5e5-3791-425c-9411-7a0fd05194da)
![image3](https://github.com/invoke-ai/InvokeAI/assets/136920434/f2986d7e-3a7b-4cb2-a5ea-23d62f5f6e3c)
![image4](https://github.com/invoke-ai/InvokeAI/assets/136920434/490f1b7a-acbf-40bf-9bc3-352ec0847236)

### Contact Details

abedachai@gmail.com

**Comment by Millu** [comment]
I'm not able to replicate this - is it causing any errors or issues with generation?

**Comment by AbedAchai1** [comment]
Don't know for sure, but this problem has been around for 4 days, usually I use Google Collab, it's not like this, but a few days ago when I uploaded a sample image to the controlnet, the image was uploaded successfully but the image on the controlnet was loading continuously and on The kernel history is looping continuously uploading

**Comment by This-is-New1** [comment]
Same issue here. When running invokeai via google colab I often stumble upon this kind of error/bug.
It just perpetually on "loading" state within logs history whenever I tried to upload an image into the controlNet form.
I've tried changing the processor, such as midas & other while in depth controlNet but to no avail.

Also weirdly enough, whenever I'm done generating an image it won't shows up and stay on loading unless I refreshed the UI page while in logs history it just shows the same loop as if I was try to load the controlNet.
This force me to generate one image at a time & can't generate in a batch.

Hope these issue can be resolved.

**Comment by Van-wise** [comment]
Failed to queue graph

**Comment by AbedAchai1** [comment]
what is the solutions?

**Comment by Van-wise** [comment]
I solved the issue with < InvokeAI 3.3.0post3 >.
https://github.com/invoke-ai/InvokeAI/tree/v3.3.0post3

**Comment by This-is-New1** [comment]
Will try, & thanks for the reply.

**Comment by This-is-New1** [comment]
@Van-wise Unfortunately, still experiencing the same error for me

**Comment by psychedelicious** [comment]
Sorry but we can't offer support for colab.
