### ISSUE TITLE
[bug]: Update from 3.1.0 to 3.3.0post3 fried the installation

### ISSUE THREAD

**Issue by walt93** [invoke-ai/InvokeAI#4945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

32GB system

### What version did you experience this issue on?

3.3.0post3

### What happened?

When using commandline interface to update to latest (3.3.0post3), the installation is now crashing on all menu options. Output was difficult to capture so I recorded a movie in case it is of value.

https://github.com/invoke-ai/InvokeAI/assets/11711050/83ca3fb3-4502-4e86-8f22-f9dc06ac6bc6

### Additional context

Log this and perhaps with enough data the AI can sense a pattern:

![Screen Shot 2023-10-18 at 2 26 05 PM](https://github.com/invoke-ai/InvokeAI/assets/11711050/07d64236-1bd8-46a2-aa3f-1899fee09db0)

**Comment by psychedelicious** [comment]
Thanks for the star chart :D

It looks like the startup is getting hung up on a checkpoint safetensors model - or something it thinks is a safetensors model. Did you make any changes to models?

**Comment by walt93** [comment]
No, I hadn't. I just sort of leave it running on my machine and connect to the web interface when I want to render something. I wanted to see if there were new models to play with today so hit ctrl-c to go back to the menu, got a crash in the add models interface (which I didn't record), then I the updated to the latest version of invokeai - and that's the state it's left in.  Previously I had been on civitai and huggingface installing a few Loras to play with, so I definitely had some extras installed - perhaps thats the source of the crash.

Probably it seems like I'm blowing the directory away and re-installing. I haven't checked - do the docs have instructions as to what directory(ies) to save to keep ones data?

**Comment by Millu** [comment]
You can reinstall in the existing location without deleting any data - it should keep everything intact for you

**Comment by walt93** [comment]
Clearing the models was the ticket. :)
