### ISSUE TITLE
[bug]: Input should be 'txt2img', 'img2img', 'inpaint' or 'outpaint'

### ISSUE THREAD

**Issue by coder543** [invoke-ai/InvokeAI#4959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

latest main

### What happened?

This error pops up trying to generate any images using sdxl:

```
Input should be 'txt2img', 'img2img', 'inpaint' or 'outpaint'
Path: body.batch.graph.nodes.core_metadata.core_metadata.generation_mode
```

The network request appears to be using `sdxl_txt2img`.

**Comment by Millu** [comment]
Try rebuilding the front end: 

```
cd invokeai/frontend/web
yarn build
```

Then starting the server
