### ISSUE TITLE
[bug]: Code improvement, using switch statement instead of multiple if statements in (DragPreview.tsx)

### ISSUE THREAD

**Issue by vedant-3010** [invoke-ai/InvokeAI#4964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cpu

### VRAM

8GB

### What version did you experience this issue on?

3.4.0

### What happened?

I was going through the codebase looking for some improvements or errors, and I found that the code in "DragPreview.tsx" uses multiple if statements, and it is not a good practice to have multiple if statements.
Instead, we can use Switch statements, which go well with that code.
We can put a switch case for all three conditions {'NODE_FIELD', 'IMAGE_DTO', 'IMAGE_DTOS'} and set Default to NULL.
It makes the code more readable and easier to understand.

### Screenshots

const DragPreview = (props: OverlayDragImageProps) => {
  if (!props.dragData) {
    return null;
  }

  if (props.dragData.payloadType === 'NODE_FIELD') {
    const { field, fieldTemplate } = props.dragData.payload;
    return (
      <Box
        sx={{
          position: 'relative',
          p: 2,
          px: 3,
          opacity: 0.7,
          bg: 'base.300',
          borderRadius: 'base',
          boxShadow: 'dark-lg',
          whiteSpace: 'nowrap',
          fontSize: 'sm',
        }}
      >
        <Text>{field.label || fieldTemplate.title}</Text>
      </Box>
    );
  }

  if (props.dragData.payloadType === 'IMAGE_DTO') {
    const { thumbnail_url, width, height } = props.dragData.payload.imageDTO;
    return (
      <Box
        sx={{
          position: 'relative',
          width: 'full',
          height: 'full',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
        }}
      >
        <Image
          sx={{
            ...STYLES,
          }}
          objectFit="contain"
          src={thumbnail_url}
          width={width}
          height={height}
        />
      </Box>
    );
  }

  if (props.dragData.payloadType === 'IMAGE_DTOS') {
    return (
      <Flex
        sx={{
          position: 'relative',
          alignItems: 'center',
          justifyContent: 'center',
          flexDir: 'column',
          ...STYLES,
        }}
      >
        <Heading>{props.dragData.payload.imageDTOs.length}</Heading>
        <Heading size="sm">Images</Heading>
      </Flex>
    );
  }

### Contact Details

vedantdandgepro@gmail.com

**Comment by psychedelicious** [comment]
Happy to review a PR to tidy this up.

**Comment by vedant-3010** [comment]
Yeah, I will be happy to make a PR. On it.
