### ISSUE TITLE
[bug]: Launching invoke from Stability Matrix

### ISSUE THREAD

**Issue by LadyFlames** [invoke-ai/InvokeAI#4969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6gb

### What version did you experience this issue on?

3.3.0 and 3.4.1

### What happened?

when launching invoke from stability matrix all i get is D:\StabilityMatrix\Packages\InvokeAI\venv\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn( and Error for Failed Process Header is too long 

### Screenshots

![Näyttökuva (11)](https://github.com/invoke-ai/InvokeAI/assets/137729901/3435c540-810b-4352-8493-355527f33b0c)
![Näyttökuva (12)](https://github.com/invoke-ai/InvokeAI/assets/137729901/621c5bbe-f4fd-43f4-9068-840db3e4da19)
that happens i already have all the models in there but i still get that error i dont know if thats an invoke Error or its Stability matrix issue

**Comment by CreationStory** [comment]
I'm sure you are beyond this by now but if you are still not able to launch, well good news! You have nearly launched. Click the send input button on the top right and input 1 or 2 or 3 to decide which way to vectorize the checkpoint. As for the API warning, yes this is stability AI running various configs and launch params that have changed name or changed function, nothing to worry about except certain things like control net and other stuff may run into issues with

It seems like you haven't read the full console. It doesnt say it won't launch it's waiting for you to tell it what to do. Scan read broadly very quickly and interpret as fast as you can to take away the intimidation of large blocks of text and eventually it will create a second nature scan read at least that's me lol

**Comment by Aptronymist** [comment]
Same thing is happening to me, just reinstalled it and it is insisting on slowly scanning thousands of embeddings and loras, and I had to hit a 3 for every single checkpoint. Whatever that is, it shouldn't happen on a first run without giving the user an option to control it, as it takes a long time.

**Comment by psychedelicious** [comment]
Do you have the same issue when installing Invoke directly?

**Comment by LadyFlames** [comment]
yea sadly even with stability matrix 2.6 the issue is still there

**Comment by psychedelicious** [comment]
The model manager was rewritten for v4 - none of the errors in this issue exist any more. Please create a new issue if the problem persisted with the latest release (v4.1.0).
