### ISSUE TITLE
[bug]: Pydantic2 PydanticDeprecatedSince20: The `json` method is deprecated; use `model_dump_json` instead.

### ISSUE THREAD

**Issue by Malrama** [invoke-ai/InvokeAI#4970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

3.4.0 RC1

### What happened?

Since 3.4.0 RC1 and the move to Pydantic2 I get the following message before each workflow invokation:

```
D:\invokeai\.venv\Lib\site-packages\invokeai\app\services\workflow_records\workflow_records_sqlite.py:60: PydanticDeprecatedSince20: The `json` method is deprecated; use `model_dump_json` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.4/migration/
  (workflow.json(),),
D:\invokeai\.venv\Lib\site-packages\pydantic\main.py:988: PydanticDeprecatedSince20: The `json` method is deprecated; use `model_dump_json` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.4/migration/
  warnings.warn('The `json` method is deprecated; use `model_dump_json` instead.', DeprecationWarning)
```

This has already been reported on Discord, and @psychedelicious asked me to create a GH report about it.
I assume this is not breaking anything atm, but we should consider not using deprecated functions and they may break in the future. It's also quite annoying to get spammed with this message in the CMD
(The same applies for the Tokenizers deprecation message on each startup, but that a different issue.)

**Comment by psychedelicious** [comment]
This is a good first issue - the change required is very simple. Just use `model_dump_json()` instead of `json()` on the line indicated in the error message.
