### ISSUE TITLE
[enhancement]: A unique tag for community nodes

### ISSUE THREAD

**Issue by VeyDlin** [invoke-ai/InvokeAI#4983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I suggest in the documentation to strongly recommend developers to use a special tag for their node repositories (for example Invoke-community-node), this can give several advantages 

1) You can easily use github to search only for repositories of community nodes
2) In the future it will be possible to add a function for parsing github search results directly from the Invoke

**Comment by Millu** [comment]
Added to the docs :) Thank you for the suggestion!
