### ISSUE TITLE
[bug]: prompt2prompt produces nonsense output on M1 Max

### ISSUE THREAD

**Issue by riisemichi** [invoke-ai/InvokeAI#4985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

64GB (unified)

### What version did you experience this issue on?

3.4.0rc1

### What happened?

When using the `swap()` feature in the prompt, it produces strange grey images which have nothing to do with the prompt (see attached screenshots with prompts).

I tried multiple schedulers, different CFG scales (2 - 20), steps, the output is always like this.

### Screenshots

`(dog).swap(cat, t_start=0, t_end=1)`
![image](https://github.com/invoke-ai/InvokeAI/assets/7499458/06252a5c-aec8-49e0-b39d-885e4b7d6237)

`a dog.swap(cat, t_start=0, t_end=0.2) drinking milk`
![image](https://github.com/invoke-ai/InvokeAI/assets/7499458/a6d7c547-1ddd-4993-9308-56414e833865)

`(cat).swap(dog, t_start=0, t_end=0.7)`
![image](https://github.com/invoke-ai/InvokeAI/assets/7499458/3a57d382-9abf-4bb8-8c66-5f9492ee7b53)

### Additional context

Reproducible, happens every time. Also happened with previous version 3.3.0.

### Contact Details

discord: michi8434

**Comment by psychedelicious** [comment]
`swap` was removed in v4.
