### ISSUE TITLE
[bug]: sorry not a bug but, congrats people invoke ai also banned from colab

### ISSUE THREAD

**Issue by ShashwatDubey99** [invoke-ai/InvokeAI#4988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

3.4..Orc1

### What happened?

I think because of the so called you tuber who promoted invoke colab the invoke ai colab got also banned, it was already suspected as the sd webui and comfy ui 

### Screenshots

![IMG-20231026-WA0001](https://github.com/invoke-ai/InvokeAI/assets/90603919/b3f08d31-49bd-49b8-aa50-43216cfafdb8)

**Comment by Millu** [comment]
Thanks for flagging!
