### ISSUE TITLE
[bug]: Doubled Disk Space Consumption

### ISSUE THREAD

**Issue by lydianb79** [invoke-ai/InvokeAI#4991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

16

### What version did you experience this issue on?

Current and below

### What happened?

This kept me busy for quite a while...
Is it normal that /Users/blub/.cache is not emptied?
Especially after installing additional models, can it be that the same data is being kept twice as it is in /Users/blub/invokedir?
This leads to massive disk consumption, especially when you don't have TB's of Storage.

**Comment by Millu** [comment]
This is the caused by the HuggingFace cache: https://huggingface.co/docs/transformers/installation#cache-setup

You can delete the `.cache/huggingface` folder if desired to save space
