### ISSUE TITLE
[bug]: Button text incorrect after updating to v3.4.Orc1

### ISSUE THREAD

**Issue by Spippy23** [invoke-ai/InvokeAI#4994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

v3.4.Orc1

### What happened?

The text in all the buttons is replaced with script names.
I tried to reset everything, but the text won't update to the correct names.

### Screenshots

![Screenshot 2023-10-27 123918](https://github.com/invoke-ai/InvokeAI/assets/124404491/bcc0027d-6015-4c22-8d4f-5eae2941fcaf)
![Screenshot 2023-10-27 123848](https://github.com/invoke-ai/InvokeAI/assets/124404491/451df253-d915-4d7e-a4eb-f8b774ad9cf9)

### Contact Details

kloemel@hotmail.com

**Comment by Millu** [comment]
Try clearing your local storage / browser cache. This is caused by your browser caching an old version of the UI - it should also appear as normal if you open it in different browser
