### ISSUE TITLE
New 3.4 version doesnt' work. error Input tag 'metadata_accumulator' found using 'type' does not match any of the expected tags: 'leres_image_processor', 'condit... Path: body.batch.graph.nodes.metadata_accumulator[bug]: 

### ISSUE THREAD

**Issue by gman9500** [invoke-ai/InvokeAI#4998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

3.4

### What happened?

after upgrading to 3.4 I can no longer invoke an image. I get this error on the bottom in a red window
input tag 'metadata_accumulator' found using 'type' does not match any of the expected tags: 'leres_image_processor', 'condit...
Path: body.batch.graph.nodes.metadata_accumulator

### Additional context

Whenever I try to invoke a new prompt. Any prompt

**Comment by Armaye1** [comment]
Same 
on windows 
3060 12GB GPU

**Comment by Jasongenius** [comment]
Same, on windows 3080 12GB GPU

**Comment by Millu** [comment]
@gman9500 @Armaye1 @Jasongenius could you please try resetting the Web UI by going to Settings -> Reset Web UI? Once the UI is reset, try generating an image

**Comment by chozabu** [comment]
> @gman9500 @Armaye1 @Jasongenius could you please try resetting the Web UI by going to Settings -> Reset Web UI? Once the UI is reset, try generating an image
I have the same issue, tried "Settings -> Reset Web UI" , still getting the error

Input tag 'metadata_accumulator' found using 'type' does not match any of the expected tags: 'string_join_three', 'float', 'c...
Path: body.batch.graph.nodes.metadata_accumulator

Installed using StabilityMatrix in portable mode, geforce 4090 laptop 16gb, win11

**Comment by chozabu** [comment]
Altering request (using firefox) to remove all objects in the request that mention "metadata_accumulator" caused InvokeAI to generate an image.

**Comment by Armaye1** [comment]
It Worked for me Thanks

**Comment by Armaye1** [comment]
it Worked for me THX

> @gman9500 @Armaye1 @Jasongenius could you please try resetting the Web UI by going to Settings -> Reset Web UI? Once the UI is reset, try generating an image

it Worked for me THX

**Comment by chozabu** [comment]
pulled latest, reset webui, still not working on my end.
Should I perhaps try a non-stabilityMatrix install?

**Comment by Millu** [comment]
@chozabu worth a shot!

**Comment by JaysonPhoenix** [comment]
similar problem (different after expected tags), installed with stability matrix, browser edge and firefox.
> Altering request (using firefox) to remove all objects in the request that mention "metadata_accumulator" caused InvokeAI to generate an image.
can confirm fetching and editing the network request with dev tools and deleting the whole bracket part containing metadata_accumulator and send again works. 
but thats only to help devs find the problem and fix it, thats no workaround for users since you would have to repeat that process for each image.

**Comment by chozabu** [comment]
> @chozabu worth a shot!

Hmm, followed windows CLI instructions to install InvokeAI, and it seems to work correctly.

Though I don't know exact cause, I'll bring this issue to the attention of StabilityMatrix

**Comment by chozabu** [comment]
This seems to be resolved (see backlinked issue above for details) sounds like it was a stability matrix issue "UI build was not changed, but the backend was updated to [this] RC release"

For anyone currently encountering this issue through stability matrix, fix should be to ensure stability matrix is updated, then remove and reinstall invokeAI

**Comment by DataJuggler** [comment]
Reset Web UI Worked. Yay!
