### ISSUE TITLE
[bug]: No Option of Inpaint Replace or Image to Image Strength

### ISSUE THREAD

**Issue by HG2407** [invoke-ai/InvokeAI#5000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

16GB

### What version did you experience this issue on?

v3.3.0

### What happened?

In the web ui, there is no option of Inpaint Replace to use for generating an entirely new object in a masked area in inpainting (as suggested by the documentation). Similarly there is no option of Image To Image strength.

**Comment by hipsterusername** [comment]
@Millu - Seems like documentation may be out of date

**Comment by HG2407** [comment]
@hipsterusername Are there any direct alternatives to inpaint replace or do we just adjust the base and mask layers ?

**Comment by hipsterusername** [comment]
Just can erase the base layer to have it infill.

**Comment by HG2407** [comment]
@hipsterusername  I tried erasing the original object in the base layer but after that since the model doesn't have any reference of the angle and pose of the original object, the new generation has different angle and pose. Is there a workaround for that ?

**Comment by hipsterusername** [comment]
> @hipsterusername I tried erasing the original object in the base layer but after that since the model doesn't have any reference of the angle and pose of the original object, the new generation has different angle and pose. Is there a workaround for that ?

Can draw in rough coloring of what you want to see where.
