### ISSUE TITLE
[enhancement]: Hires fix (more wanted i think)

### ISSUE THREAD

**Issue by KontolCinaSerbia** [invoke-ai/InvokeAI#5004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

hires fix sounds good to detail or fix error :)

### Alternatives

for fix image, like make detail is good 

### Additional Content

i think you alr know that hmm

**Comment by Millu** [comment]
HiRes fix is available as of InvokeAI 3.3.0post3
