### ISSUE TITLE
[install issues]: ImportError: cannot import name 'widget' from 'npyscreen' (unknown location)

### ISSUE THREAD

**Issue by Thaiquannguyen** [invoke-ai/InvokeAI#5011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24 gb

### What version did you experience this issue on?

3.2.0

### What happened?

When i try to install Invoke AI from install.bat. i have face this problem ImportError: cannot import name 'widget' from 'npyscreen' (unknown location)

### Screenshots

![image](https://github.com/invoke-ai/InvokeAI/assets/149496702/0994fb69-300f-414a-bb4e-42221085e636)
![image](https://github.com/invoke-ai/InvokeAI/assets/149496702/2effd8e7-de97-411d-bf1b-8fcc58cbdb2f)

**Comment by hipsterusername** [comment]
Is there a failure earlier on in the install for npyscreen?

**Comment by Thaiquannguyen** [comment]
> Is there a failure earlier on in the install for npyscreen?

Yes, i have encounter the failure on earlier for the npyscreen

**Comment by hipsterusername** [comment]
Can you share why that errored? You can probably get help to go through this issue in Discord, but this seems to be an install issue not a Bug

**Comment by Thaiquannguyen** [comment]
> Can you share why that errored? You can probably get help to go through this issue in Discord, but this seems to be an install issue not a Bug

Hi i think maybe i am wrong from the start, when i installed Pythong 3.10.11 . And when i add the path to the environment account also it doesn't find the location.

**Comment by psychedelicious** [comment]
This script no longer exists. All configuration occurs in the config file or UI.
