### ISSUE TITLE
WARNING --> Not a valid model: sdxl\ip_adapter\ip-adapter-plus-face_sdxl_vit-h.bin. Unexpected IP-Adapter model format: sdxl\ip_adapter\ip-adapter-plus-face_sdxl_vit-h.bin

### ISSUE THREAD

**Issue by FurkanGozukara** [invoke-ai/InvokeAI#5012]
WARNING --> Not a valid model: sdxl\ip_adapter\ip-adapter-plus-face_sdxl_vit-h.bin. Unexpected IP-Adapter model format: sdxl\ip_adapter\ip-adapter-plus-face_sdxl_vit-h.bin

trying new model from here

https://huggingface.co/h94/IP-Adapter/tree/main/sdxl_models

did a fresh new install of InvokeAI today latest version

RTX 3090 TI - windows 10 - Python 3.10.11

**Comment by hipsterusername** [comment]
This is not a bug. Please download using models.invoke.ai (tools) or the configuration options.

**Comment by FurkanGozukara** [comment]
> This is not a bug. Please download using models.invoke.ai (tools) or the configuration options.

it is not there though i can't see it

**Comment by FurkanGozukara** [comment]
> Please check again :)

hello. i just updated invoke ai and entered this screen

still missing?

![image](https://github.com/invoke-ai/InvokeAI/assets/19240467/63c288df-8397-4b20-8f33-c75653e70820)

**Comment by FurkanGozukara** [comment]
testing from import model got an error but testing again with let you know ty

**Comment by FurkanGozukara** [comment]
thank you i made it work

result is terrible

![image](https://github.com/invoke-ai/InvokeAI/assets/19240467/276f3ebc-ca1d-4c27-89c6-d43077136dee)

**Comment by bitcoinvsalts** [comment]
what about this error? is it related?

`RuntimeError: Error(s) in loading state_dict for Resampler:
Nov 04 20:42:21 ip-172-31-7-28.us-west-1.compute.internal startup.sh[59971]:         size mismatch for proj_in.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1664]).
`
