### ISSUE TITLE
[bug]: UI text labels not displaying localization or not available for translation

### ISSUE THREAD

**Issue by Harvester62** [invoke-ai/InvokeAI#5015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

3.3.0

### What happened?

Several text labels in the UI are not converted to the related localized version, or are not available on Weblate for translation. I am reporting this relatively to the Italian localization, but this seems to happen also with other localizations.

I took screenshots of the UI highlighting the labels that don’t show up correctly for one of the two above reasons.

Compiled InvokeAI with “main” branch and used the latest it.json file available on Weblate.

MAIN UI - SETTINGS

![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/4920894d-2d77-44fa-8448-24b939ea4a95)

All the above three strings are not available on Weblate.

MAIN UI – IMAGE VIEWER

![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/3457c217-b1f2-4adc-9304-bd95e8743510)
 
The above is not available on Weblate.

MAIN UI – IMAGE ACTIONS MENU

![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/b9024285-d578-4c59-9cb6-1f5d0c51d220)

“Change Board” is not displaying the translation, while “Unstar Image” isn’t available on Weblate.

 

“ESRGAN Model” isn’t available on Weblate.

![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/c808f04e-a4d0-45e8-869e-37df35ad1b21)

MAIN UI – BOARDS

![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/9ab92bd6-2acb-4b25-9753-9b3ae116fdc3)
 
“Delete Board” is missing from Weblate.

![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/9966c7f2-9cc7-4a81-8294-a32741662487)
 
“Delete” doesn’t show the localized text.
“Deleted boards cannot be restored.”, “Delete Board Only”, and “Delete Board and Images”  are not available on Weblate.

MAIN UI - GENERATION PARAMETERS

![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/232c11ae-7535-4ec1-a0c3-f5d47aed0965)
 
“Drop” isn’t available on Weblate.

![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/4bd77d16-c31f-4419-af80-2b0e5155be55) 

“Add LoRA” isn’t available on Weblate.

![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/a9851b61-b551-423f-8050-0df4ef3e700f)

“Prompts Preview” isn’t available on Weblate.

![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/a9353fb7-f9b8-4e7c-8580-5ef7f3fbbb63)
 
The entire “High Resolution Fix” panel is missing on Weblate.

IMAGE TO IMAGE

![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/22084e2d-487a-4d7a-92e7-b36047419292)
 
“Initial Image”, “No initial image selected” are not using the localized text.
The labels of the two buttons on the top right corner, “Upload Initial Image” and “Reset Initial Image”, are not available on Weblate.

UNIFIED CANVAS

 
![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/fa7fbe33-5bcc-4010-8bbd-8cdede151b8b)

Both “Mode” and “Text to Image” are not using the localized texts.

![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/3cfc5fb6-1a95-4df7-a4dc-5769a1cdd8b0)

“Unmasked”, “Mask” and “Mask Edge” are not available on Weblate.

WORKFLOW EDITOR

![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/32f55217-01ef-4527-97cb-006738831f48)

Not sure if the key settings.general is being reused. In the affirmative, then it doesn’t display the localized text. The same for “Advanced” and the common.advanced key. If these are instead different keys, then these two labels are missing on Weblate.

 
![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/3917842f-2e6d-4a62-811d-738b22f1af92)

“Linear”, “Details”, “Outputs”, “Data” and “Template” aren’t available on Weblate.

MODELS MANAGER

![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/d82b4123-3342-4f17-a81d-dfe9a828a49b)

All the highlighted labels are not displaying the localized text. Not sure about “No Model Selected” because the only key is related to the generation parameters and not the Model Manager.

IMPORT MODELS

![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/0439f6cf-6299-495e-a4d8-6522d2d1d664)

“Simple” is missing from Weblate, “Advanced” doesn’t show the localized text.

MERGE MODELS

![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/499d27b8-82a5-4631-917b-a9e67b0eb0fb)

“Model Type” doesn’t display the localized text.

MODELS SETTINGS

![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/bb55c233-bff1-4dd4-b74f-208bb041c649)

“Sync Models” isn’t displaying the localized text.

QUEUE MANAGEMENT

 
![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/1c2b19bc-32b1-41ae-a891-41f58c4b8cf5)

“STATUS” and “BATCH” don’t display the localized text.

“TIME” and “BATCH FIELS VALUES” aren’t available on Weblate.

**Comment by psychedelicious** [comment]
This is a good first issue for a frontend contributor. It will involve:
- locate the strings identified in the issue in code
- add the strings to the `invokeai/frontend/web/public/locales/en.json` file (note this is in the **`public/`** directory, not `dist/`)
- if the string is used in a React component, use the `useTranslation` hook to use the strings
- if the string is used outside a React component, use `i18next` directly e.g. `import i18n from 'i18next'; i18n.t('translation.key')`
- if the string is composed dynamically, logic changes or `i18n`'s composition functionality may be needed

**Comment by rohinish404** [comment]
can i take up this issue?

**Comment by psychedelicious** [comment]
I've assigned to both @Harvester62 and @rohinish404 - both of you were interested in working on this (thanks!), so I'll leave it to you two to organize

**Comment by Harvester62** [comment]
I have just found another one, from the action to delete an image from the gallery or the generation result

![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/0ba99708-335d-48b0-a9a0-487e66fc2bc9)

These labels seem to be missing from Weblate.

**Comment by Harvester62** [comment]
Found another one, when you drag and drop an image from the gallery into the Canvas
![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/d1fa75f7-2969-4730-b686-f7911cc688cf)
and it has a translation available
![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/a8b59038-d34f-42bd-890a-0f980ce53a4d)

**Comment by Harvester62** [comment]
I found another case where the localization is not applied in the UI, related to the Unified Canvas, when you drag and drop an image from the gallery into the canvas
![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/ae441439-b8b9-4075-b341-0346381814cf)
On Weblate I found the label text but it doesn't match with what is displayed, 
![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/bcf39719-c27a-44a7-bf24-12bdbb3dedcb)
