### ISSUE TITLE
[enhancement]: Hex or RGB brush values.

### ISSUE THREAD

**Issue by ItsWritt** [invoke-ai/InvokeAI#5018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

@It's Writt

### What should this feature add?

I'd like there to be a text value to the color picker for the brush tool. I feel that this would drastically improve the use of the unified canvas.

### Alternatives

Maybe a drop down menu of different value methods would also be neat, that way people wouldn't need to translate the values from what they're used to. I.E. HSL RGB and Hexidecimal just to name a few.

### Additional Content

![image](https://github.com/invoke-ai/InvokeAI/assets/98681452/4fb891c5-c730-4b1b-af07-1f4e88b4c21a)

**Comment by rohinish404** [comment]
Hey, this issue seems intersting! How do i get started with this?

**Comment by Millu** [comment]
Hey @rohinish404! Thanks the interest! Feel free to go ahead and open a draft PR for it :) 

A couple things to get you started:
1. Take a look at our Contribution docs: https://invoke-ai.github.io/InvokeAI/contributing/CONTRIBUTING/
2. Join our Discord: https://discord.gg/ZmtBAhwWhy

As far as technical direction, @psychedelicious can help point you in the right direction!

**Comment by rohinish404** [comment]
@Millu yeah sure i will ask my doubts in the discord!

**Comment by psychedelicious** [comment]
@rohinish404 in the future, when you make a PR, you can include `Closes #XZY` in the PR description and github will close #XZY for ya. just a tip

**Comment by rohinish404** [comment]
> @rohinish404 in the future, when you make a PR, you can include `Closes #XZY` in the PR description and github will close #XZY for ya. just a tip

Yeah actually at that time i haven't made all the changes so i thought its not closing the pr rn. Will keep that in mind from now!
