### ISSUE TITLE
[bug]: impossible to add controlnets again

### ISSUE THREAD

**Issue by jjiikkkk** [invoke-ai/InvokeAI#5023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

3.0

### What happened?

![image](https://github.com/invoke-ai/InvokeAI/assets/73511302/e7a4873d-73e0-41e1-af0a-dd870b25f659)
i have added controlnets, sure
but unable to add from this image

### Screenshots

![image](https://github.com/invoke-ai/InvokeAI/assets/73511302/e7a4873d-73e0-41e1-af0a-dd870b25f659)
i have added controlnets, sure
but unable to add from this image

### Additional context

![image](https://github.com/invoke-ai/InvokeAI/assets/73511302/e7a4873d-73e0-41e1-af0a-dd870b25f659)
i have added controlnets, sure
but unable to add from this image

**Comment by psychedelicious** [comment]
Sorry, it's not clear what the problem is. You're on a rather old version too. Please create a new issue if you still have a problem on the latest release.
