### ISSUE TITLE
[bug]: Board thumbnails incorrectly show intermediate file thumbnails if the intermediate file is the most recent member of the board

### ISSUE THREAD

**Issue by f412design** [invoke-ai/InvokeAI#5024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24GB

### What version did you experience this issue on?

3.2.0

### What happened?

Sometimes board thumbnails will appear to show an image that is not visible in the gallery for that board. I looked in the database and this happens when an intermediate file is a member of the board and files created after the intermediate were used are deleted or moved to another board. This leaves the intermediate as the most recent member of the board and thus its thumbnail is show.

Intermediate files should be excluded from the query for the most recent image to show the board thumbnail.

This can be reproduced by generating an image in the board, then send to unified canvas. Generate a subset of the image in a masked area. Do not bother to accept or save the masked area generation, just refresh the ui to see that the masked area generation is now the board thumbnail. Deleting the source image and clearing the unified canvas do not remove this intermediate and it remains the board thumbnail until a new image is generated or intermediates are cleared followed by reloading the browser.

**Comment by Millu** [comment]
Thanks for catching! 

@psychedelicious seems the underlying bug is intermediates being added to boards

**Comment by f412design** [comment]
> Thanks for catching!
> 
> @psychedelicious seems the underlying bug is intermediates being added to boards

Having intermediates as a member of the board could be a bug, but also I believe regardless if they get added to the board or not, the query for board_images to choose for the thumbnail should include a join to images and then a filter of "WHERE is_intermediate=0" The query fix would retroactivately resolve this, while preventing future adds would only stop it from happenning again. Regardless, clearing intermediates should be a resolution for retroactive fix.

I recommend a fix where the query for getting thumbnail image by board_id could be:

```
SELECT bdimg.image_name
FROM board_images AS "bdimg"
INNER JOIN images AS "img" ON bdimg.image_name=img.image_name
WHERE
    bdimg.board_id='01ff93ca-5cc0-4d45-84b6-d95bdeef7ab9'
    AND img.is_intermediate=0
ORDER BY bdimg.updated_at DESC
LIMIT 1
```

If someone could direct me to where the sql queries for this are built up in source, I could propose a fix. I think this should be made even if its also not desired for intermediates to be members of boards at all.

As another note, sometimes Assets appear as the thumbnail as well if they are the latest image. I am not a fan of this, but it is probably intentional and not a bug. If there was desire to change this, then adding is image_origin='internal' would resolve that.

**Comment by psychedelicious** [comment]
This is fixed as of v5
