### ISSUE TITLE
[bug]: Can't access webui from iPhone

### ISSUE THREAD

**Issue by iChristGit** [invoke-ai/InvokeAI#5025]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24GB

### What version did you experience this issue on?

latest

### What happened?

I can run the webui just fine on my Windows11 machine, but after editing the yaml file and changeing to host 0.0.0.0 and port forwarding allowing 9090.
But still the page in my phone wont load.
In automatic1111 for example it does work.
What more can be done?

**Comment by iChristGit** [comment]
Anyone? :O

**Comment by Millu** [comment]
Have you tried asking in the Discord? There's multiple folks who have it setup successfully

**Comment by Pfannkuchensack** [comment]
- Are the PC and the iphone in the same network. (Not all Router let the wifi devices talk to cable devices)
- allow_origins needs to be set right (IP or *)
