### ISSUE TITLE
[bug]: Downloading models using the invoke.bat (option 5) commandline interface results in dual-downloads

### ISSUE THREAD

**Issue by BunnCode** [invoke-ai/InvokeAI#5029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.4.0rc2

### What happened?

While adding _any_ model from any repo with the commandline interface, the model is downloaded twice concurrently. This error does not appear when using the GUI web interface to install models. Every model that I have tried resulted in this behavior, but for replication purposes, the huggingface repo ID "thibaud/controlnet-sd21-normalbae-diffusers" can be used to trigger this behavior. It does not seem to result in file corruption, but downloads do occur at half speed.

### Screenshots

![image](https://github.com/invoke-ai/InvokeAI/assets/17638042/bccf33e7-fd4e-481d-84e8-e6b226324b06)

### Additional context

This appears to happen with all remote repos regardless of content

**Comment by Millu** [comment]
@lstein this seems to be limited to using the "Additional URLs..." field

**Comment by psychedelicious** [comment]
Resolved in v4.0.0
