### ISSUE TITLE
[enhancement]: Workflow improvement templates and 

### ISSUE THREAD

**Issue by empessah** [invoke-ai/InvokeAI#5045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I would love to see in the workspace Presets chunks/templates example. I should be able to open in the workspace area and, from a drop-down menu or something, click I want Text to image for SDXL, and it drops in a basic flow for that. Then, I could click image to image, and it would drop it into the same project. This will allow a faster way to build out an automated and repetitive task someone would do with the base tools. This could also help speed up making a new workflow.

**Comment by Millu** [comment]
Agreed! this is on our roadmap: #4481
