### ISSUE TITLE
[bug]: canny-sdxl t2i-adapter fails

### ISSUE THREAD

**Issue by keturn** [invoke-ai/InvokeAI#5047]
### Is there an existing issue for this?

-  ✅ I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

935e4632c243ceb101381a0b7959c7a116f2135d

### What happened?

- model: SDXL v1, precision: fp16
- dimensions: 1024×1024
- Add Control Adapter: T2I-Adapter [canny-sdxl](https://huggingface.co/TencentARC/t2i-adapter-canny-sdxl-1.0)
- Weight: 1, Begin/End: 0/100 (defaults)
- Resize Mode: Resize
- Processor: Canny
- Python 3.11

Fails in unet forward call with "The size of tensor a (64) must match the size of tensor b (32) at non-singleton dimension 3"

<details>
<summary>traceback</summary>

```
  File "InvokeAI/invokeai/backend/stable_diffusion/diffusion/shared_invokeai_diffusion.py", line 267, in do_unet_step
    ) = self._apply_standard_conditioning(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "InvokeAI/invokeai/backend/stable_diffusion/diffusion/shared_invokeai_diffusion.py", line 380, in _apply_standard_conditioning
    both_results = self.model_forward_callback(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "InvokeAI/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 657, in _unet_forward
    return self.unet(
           ^^^^^^^^^^
  File "…/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "…/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "…/site-packages/diffusers/models/unet_2d_condition.py", line 1078, in forward
    sample += down_intrablock_additional_residuals.pop(0)
RuntimeError: The size of tensor a (64) must match the size of tensor b (32) at non-singleton dimension 3

[2023-11-06 15:35:46,754]::[InvokeAI]::ERROR --> Error while invoking:
The size of tensor a (64) must match the size of tensor b (32) at non-singleton dimension 3
```

</details>

### Additional context

similar problems with other SDXL t2i-adapters I've tried.

the SD 1.4 t2i-adapters work okay.

**Comment by GreggHelt2** [comment]
I'm seeing the same issue, and same error message.
@RyanJDick have you had a chance to look into this issue? I
I implemented some of the recent modifications to allow mixed use of ControlNet and T2I-Adapters. So it's _possible_ that some of those modifications are causing this issue. I don't have time to debug today, but could look into it later in the week.

**Comment by GreggHelt2** [comment]
Just tested PR #5060, and it fixes this issue. Once it's merged into main, should be able to use SDXL T2I-Adapters again.
