### ISSUE TITLE
[bug]: LCM LoRA not probed successfully.

### ISSUE THREAD

**Issue by hipsterusername** [invoke-ai/InvokeAI#5059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24

### What version did you experience this issue on?

LCM Branch

### What happened?

On importing `latent-consistency/lcm-lora-sdxl` received "Import Failed" error.

**Comment by hipsterusername** [comment]
This may just be because it's a Repo. The file itself on download imports fine

**Comment by lstein** [comment]
Fixed in PR#5068
