### ISSUE TITLE
[enhancement]: compy with the openapi specs

### ISSUE THREAD

**Issue by Yvonne-Aizawa** [invoke-ai/InvokeAI#5078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

discord: inori_aizawa

### What should this feature add?

considering this project has an API that has swagger docs. and an openapi.json
is it possible to make it comply with the openapi specs 
that way tools like [this](https://swagger.io/tools/swagger-codegen ) could be used. which would speed up api development to integrate invokeai with other projects. in case the API changes a bit the tool could be ran again to update the libary

### Alternatives

an alternative would be for every developer to manually create a library for their project. this is error prone and when the api changes it needs fixing

**Comment by psychedelicious** [comment]
We use openapi codegen on the project already (we generate typescript types and a backup HTTP client, and have used two different codegens without issue).

What isn't in spec? What doesn't work?

**Comment by Yvonne-Aizawa** [comment]
What are you using to generate them? Maybe it is an error on my part.

**Comment by psychedelicious** [comment]
@Yvonne-Aizawa
The project currently uses https://github.com/drwpow/openapi-typescript but we also have used https://github.com/ferdikoomen/openapi-typescript-codegen in the past.

https://apitools.dev/swagger-parser/online/ reports the schema as valid, FWIW

**Comment by Yvonne-Aizawa** [comment]
in that case i will look further. i will close this issue. sorry for taking your time

**Comment by psychedelicious** [comment]
@Yvonne-Aizawa No worries, please @ me if you find any problems, we can definitely fix any issues.
