### ISSUE TITLE
[enhancement]: Move toasts to somewhere else

### ISSUE THREAD

**Issue by ufuksarp** [invoke-ai/InvokeAI#5079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Move toasts to somewhere else. They are distracting in the middle and block the image.

Some ideas about where it can go, best to worst:

- Move to "Load More" button, one row only. Requires restyling and recoding. "Load More" text changes to whatever the toast says, needs to be more visible on change.
- Move to top bar. It's empty space. Requires restyling and recoding.
- Move to bottom right. May block some images at the bottom of gallery and cause interference. Needs only restyling.
- Move to bottom left, over generation settings. Can cause interference. Needs only restyling.

**Comment by psychedelicious** [comment]
Thanks for raising this, it's bothered me too.

This is a good first issue. It should be very simple to move the toasts around: https://chakra-ui.com/docs/components/toast#configuring-toast-globally

I agree that bottom-right is the best place.

**Comment by Pfannkuchensack** [comment]
#5181 here a pull request for the change :)
