### ISSUE TITLE
[bug]: LoRA + CLIP Skip fails: ModuleList has no attribute `11_mlp_fc1`

### ISSUE THREAD

**Issue by keturn** [invoke-ai/InvokeAI#5081]
### Is there an existing issue for this?

- I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

1c7ea57492802eaf19f81ada9ed545a2e618add8

### What happened?

Using an SD 1.5 model (such as InvokeAI Fantasy and Art by Zovya):
- LoRA like `add detail` works fine
- CLIP Skip advanced option works fine on its own
- but when CLIP Skip is used ***with*** a LoRA, it is errortime:

```
  File "invokeai/backend/model_management/lora.py", line 76, in apply_lora_text_encoder
    with cls.apply_lora(text_encoder, loras, "lora_te_"):
  File "python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "invokeai/backend/model_management/lora.py", line 123, in apply_lora
    module_key, module = cls._resolve_lora_key(model, layer_key, prefix)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "invokeai/backend/model_management/lora.py", line 54, in _resolve_lora_key
    module = module.get_submodule(submodule_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.11/site-packages/torch/nn/modules/module.py", line 686, in get_submodule
    raise AttributeError(mod._get_name() + " has no "
AttributeError: ModuleList has no attribute `11_mlp_fc1`
```

not sure if this is a regression or not as I haven't been using LoRAs often.

**Comment by Millu** [comment]
Same issue here: https://github.com/invoke-ai/InvokeAI/issues/5077

**Comment by psychedelicious** [comment]
This kinda makes sense to me. CLIP skip is literally popping layers off the text encoder, but then the LoRA attempts to modify that layer.
