### ISSUE TITLE
[bug]: i have added openpose controlnets to duffuser parts of INVOKE 2.3.5, but after refreshing the interface, I do not see the controlnet sections. How can I make them out? 

### ISSUE THREAD

**Issue by wingofstar** [invoke-ai/InvokeAI#5094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

amd

### VRAM

6gb

### What version did you experience this issue on?

2.3.5

### What happened?

i have added openpose controlnets to duffuser parts of INVOKE 2.3.5, but after refreshing the interface, I do not see the controlnet sections. How can I make them out? 

### Screenshots

![微信图片_20231114153536](https://github.com/invoke-ai/InvokeAI/assets/7867104/5804cc79-16b5-4130-9c36-ce81a8c18926)

### Contact Details

wuxianpu2022@gmail.com

**Comment by Millu** [comment]
I'm not quite sure what the issue here - did you get any errors while importing it? 

Is there a reason you're using 2.3.5 instead of InvokeAI 3.x?

**Comment by wingofstar** [comment]
There are too many problems with this version. I want to upgrade to the latest version 3.4 of the Windows system. But my English is not very good, and I haven’t found a way to upgrade to the latest version. I’m not sure if I’m using the official version. This integration package can be installed with one click. Could you please provide me with the latest version download link?

**Comment by Millu** [comment]
I would suggest installing InvokeAI 3.3.0post3: https://github.com/invoke-ai/InvokeAI/releases/tag/v3.3.0post3

You can download the installer from this link: https://github.com/invoke-ai/InvokeAI/releases/download/v3.3.0post3/InvokeAI-Installer-v3.3.0post3.zip


It is recommended to install InvokeAI 3.x in a separate location from InvokeAI 2.3.5 

We provide a script, invokeai-migrate3, which will copy your models and settings from a 2.3-format root directory to a new 3.0 directory. To run it, execute the launcher and select option [8] "Developer's console". This will take you to a new command line interface. On the command line, type:

```invokeai-migrate3 --from <path to 2.3 directory> --to <path to 3.0 directory>```

Provide the old and new directory names with the --from and --to arguments respectively. This will migrate your models as well as the settings inside invokeai.init. You may provide the same --from and --to directories in order ot upgrade a 2.3 root directory in place. (The original models and configuration files will be backed up.)

**Comment by Millu** [comment]
Also, your prompt syntax is wrong - that's A111 syntax not InvokeAI syntax

**Comment by Millu** [comment]
Closing as support 2.3.5 has been replaced by InvokeAI 3.x

Hope the installation instructions helped
