### ISSUE TITLE
How can I find out controlnets and loras sections for my current version 2.3.5

### ISSUE THREAD

**Issue by jjiikkkk** [invoke-ai/InvokeAI#5095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

2.3.5

### What happened?

please see my previous older version 2.3.2 below
![008953de820ce02dc3c75fc30a89f62](https://github.com/invoke-ai/InvokeAI/assets/73511302/d92207e8-e9cc-4370-bab7-7118d2bf5ac6)
![3b2a8d328331b740fe26df9ad3f4107](https://github.com/invoke-ai/InvokeAI/assets/73511302/edb4b901-c6d0-419b-a90c-777cd39c0f44)

now I am using 2.3.5, but unable to find out loras and controlnets sections like above
![614257cd20ca183cbaa18bf12d40e7c](https://github.com/invoke-ai/InvokeAI/assets/73511302/bb7f3224-80a9-46b9-a819-e08630dd18b0)

how to do?
i am unwilling to install the latest version, thanks a lot

### Screenshots

please see my previous older version 2.3.2 below
![008953de820ce02dc3c75fc30a89f62](https://github.com/invoke-ai/InvokeAI/assets/73511302/d92207e8-e9cc-4370-bab7-7118d2bf5ac6)
![3b2a8d328331b740fe26df9ad3f4107](https://github.com/invoke-ai/InvokeAI/assets/73511302/edb4b901-c6d0-419b-a90c-777cd39c0f44)

now I am using 2.3.5, but unable to find out loras and controlnets sections like above
![614257cd20ca183cbaa18bf12d40e7c](https://github.com/invoke-ai/InvokeAI/assets/73511302/bb7f3224-80a9-46b9-a819-e08630dd18b0)

how to do?
i am unwilling to install the latest version, thanks a lot

### Additional context

please see my previous older version 2.3.2 below
![008953de820ce02dc3c75fc30a89f62](https://github.com/invoke-ai/InvokeAI/assets/73511302/d92207e8-e9cc-4370-bab7-7118d2bf5ac6)
![3b2a8d328331b740fe26df9ad3f4107](https://github.com/invoke-ai/InvokeAI/assets/73511302/edb4b901-c6d0-419b-a90c-777cd39c0f44)

now I am using 2.3.5, but unable to find out loras and controlnets sections like above
![614257cd20ca183cbaa18bf12d40e7c](https://github.com/invoke-ai/InvokeAI/assets/73511302/bb7f3224-80a9-46b9-a819-e08630dd18b0)

how to do?
i am unwilling to install the latest version, thanks a lot

**Comment by Millu** [comment]
Why are you unwilling to install the latest version?

**Comment by Millu** [comment]
Closing as support 2.3.5 has been replaced by InvokeAI 3.x
