### ISSUE TITLE
[bug]:   error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by GreyLedger** [invoke-ai/InvokeAI#5099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

v3.3.0

### What happened?

<img width="1002" alt="屏幕截图 2023-11-15 201405" src="https://github.com/invoke-ai/InvokeAI/assets/130574163/cbf9ae06-0720-4a52-95ca-5d7c6c6bb25a">
<img width="1264" alt="屏幕截图 2023-11-15 201349" src="https://github.com/invoke-ai/InvokeAI/assets/130574163/6bef155d-4176-4650-a681-de479c552ec3">

When using the automated installer to install version 3.3.0, the installation stopped. I found a similar issue that happened on Linux but it didn't really provide a solution.

### Screenshots

<img width="1264" alt="屏幕截图 2023-11-15 201349" src="https://github.com/invoke-ai/InvokeAI/assets/130574163/e4cdf8cc-08f8-4120-8dd6-ba06db05c676">

### Contact Details

sharkliang1116@gmail.com

**Comment by psychedelicious** [comment]
The error is saying there is a network issue - a package download was interrupted.

This could either be an issue with your internet, or a problem with the python package repositories.

Either way, not an issue with InvokeAI. Probably you'll just need to try again later. If the issue persists, it may be a problem with your internet.
