### ISSUE TITLE
[bug]: LCM models fail to load - 'UNet2DConditionModel is not one of the supported classes'

### ISSUE THREAD

**Issue by sammcj** [invoke-ai/InvokeAI#5116]
First of all - love your work InvokeAI folks! ❤️ 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

24GB

### What version did you experience this issue on?

3.4.0

### What happened?

When downloading a LCM model via the model mananger, or when trying to import it from a file - InvokeAI fails to load (or save) the model.

For example, using the popular [lcm-sdxl model](https://huggingface.co/latent-consistency/lcm-sdxl):

1. Model manager
2. Paste in `latent-consistency/lcm-sdxl`
3. Wait for the download <go make a coffee>
4. Return to machine to check the status - the UI has no error messages or warnings displaying, but the model is not installed, I suspect an error might pop up and go away by itself without leaving a hint / warning.
5. Check the logs:

```
config.json: 100% 1.83k/1.83k [00:00<00:00, 31.5MiB/s]
diffusion_pytorch_model.safetensors: 100% 10.3G/10.3G [01:40<00:00, 102MiB/s]
[2023-11-17 12:37:29,715]::[InvokeAI]::ERROR --> Unable to determine model type for /invokeai/models/tmp2_u67ytk/lcm-sdxl; class UNet2DConditionModel is not one of the supported classes [StableDiffusionPipeline, StableDiffusionInpaintPipeline, StableDiffusionXLPipeline, StableDiffusionXLImg2ImgPipeline, StableDiffusionXLInpaintPipeline, AutoencoderKL, AutoencoderTiny, ControlNetModel, CLIPVisionModelWithProjection, T2IAdapter]
```

I did read the release notes and saw that LCM use a node connector (not quite sure from the wording of this what the impact is to the user) - but also that they should be installable via the model mananger.

### Screenshots

<img width="1149" alt="image" src="https://github.com/invoke-ai/InvokeAI/assets/862951/4bb942af-0fae-469d-b3d9-1b07807ca5d9">

### Additional context

- Linux (Container)
- Nvidia
- 3.4.0 release
- No other relevant errors in the console logs

**Comment by Millu** [comment]
Only LCM-LoRAs are supported through the model manager at the moment

**Comment by sammcj** [comment]
Ohhhhh I see, I'm sorry I didn't realise that!

**Comment by sammcj** [comment]
So in theory this should work? https://huggingface.co/latent-consistency/lcm-lora-sdxl

**Comment by sammcj** [comment]
Ah yeah I'll try a few from https://huggingface.co/jakedahn/sdxl-isometric-geology which I think should work.

I'll close this issue for now.

**Comment by Millu** [comment]
That should work - sorry, it's a little confusing! I've clarified the release notes

**Comment by sammcj** [comment]
np, love your work! :)

**Comment by Vargol** [comment]
If you want to try latent-consistency/lcm-sdxl   which is basically a unet model  not a complete SD model, you can use my 
cut and paste job Vargol/lcm_sdxl_full_model which adds all the other bits require and loads via the Model Manager or at least did in the last release candidate.

I haven't compared results properly yet but I find it a bit faster per step that the LCM LoRA, but obviously the LoRA can be used with any compatible model, where lcm_sdxl_full_model  is a one off.

**Comment by sammcj** [comment]
Thanks @Vargol I'll give it a shot 😄
