### ISSUE TITLE
[bug]: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by SimonLuoshiping** [invoke-ai/InvokeAI#5118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

11GB

### What version did you experience this issue on?

3.4

### What happened?

[bug]: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### Screenshots

[bug]: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### Additional context

[bug]: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### Contact Details

han737045265@126.com

**Comment by psychedelicious** [comment]
Please include some context about how this error occurred. 

Also, the error is not the full error and doesn't provide enough information.
