### ISSUE TITLE
[bug]: Value error, Edge destination field metadata does not exist in node image_to_latents Path: body.batch.graph

### ISSUE THREAD

**Issue by rthami** [invoke-ai/InvokeAI#5124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cpu

### VRAM

16GB

### What version did you experience this issue on?

3.4.0

### What happened?

When i try to use image to image in push invoke button

**Comment by GucciPants** [comment]
same problem!

**Comment by greatwolf** [comment]
I'm experiencing the same issue.

**Comment by psychedelicious** [comment]
This is resolved in the `3.4.0post1` release: https://github.com/invoke-ai/InvokeAI/releases/tag/3.4.0post1

Please update.

**Comment by greatwolf** [comment]
seems to be working again. thanks for the fix!

**Comment by psychedelicious** [comment]
@greatwolf No worries!
