### ISSUE TITLE
[bug]: npyscreen not installed with automatic installer

### ISSUE THREAD

**Issue by Lesani** [invoke-ai/InvokeAI#5127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24

### What version did you experience this issue on?

3.4.0post1

### What happened?

This has been reported before and was falsly marked as "fixed".

────────────────────────────── InvokeAI Configuration Section ───────────────────────────────

  Libraries are installed and InvokeAI will now set up its root directory and
  configuration. Choose between:

    * AUTOMATIC configuration:  install reasonable defaults and a minimal set of starter
  models.
    * MANUAL configuration: manually inspect and adjust configuration options and pick from
  a larger set of starter models.

  Later you can fine tune your configuration by selecting option [6] 'Change InvokeAI
  startup options' from the invoke.bat/invoke.sh launcher script.

Choose <a>utomatic or <m>anual configuration [a/m] (a): a
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Traceback (most recent call last):
  File "F:\InvokeAI\InvokeAI-Installer\lib\main.py", line 52, in <module>
    inst.install(**args.__dict__)
  File "F:\InvokeAI\InvokeAI-Installer\lib\installer.py", line 183, in install
    self.instance.configure()
  File "F:\InvokeAI\InvokeAI-Installer\lib\installer.py", line 348, in configure
    from invokeai.frontend.install.invokeai_configure import invokeai_configure
  File "F:\InvokeAI\.venv\Lib\site-packages\invokeai\frontend\install\invokeai_configure.py", line 4, in <module>
    from ...backend.install.invokeai_configure import main as invokeai_configure  # noqa: F401
  File "F:\InvokeAI\.venv\Lib\site-packages\invokeai\backend\install\invokeai_configure.py", line 24, in <module>
    import npyscreen
ModuleNotFoundError: No module named 'npyscreen'
Press any key to continue . . .

F:\InvokeAI\InvokeAI-Installer>`

Short term manual fix:
in your install dir go to:

cd .venv
cd Scripts
activate
pip install -I --no-cache-dir npyscreen==4.10.5

**Comment by Millu** [comment]
For anyone who is running into this issue, the fix is: 

Open the developer console (option 7) from your invoke.sh or invoke.bat file and run: 

`pip install npyscreen`

**Comment by galvedro** [comment]
> For anyone who is running into this issue, the fix is:
> 
> Open the developer console (option 7) from your invoke.sh or invoke.bat file and run:
> 
> `pip install npyscreen`

No, that command is not enough. The command in the bug description does the trick. You do need to override the cache.

`pip install -I --no-cache-dir npyscreen==4.10.5`

**Comment by psychedelicious** [comment]
This is no longer an issue with the latest release. The installer was rewritten.
