### ISSUE TITLE
[bug]: controlnet_aux missing when installing with  the automatic installer

### ISSUE THREAD

**Issue by Lesani** [invoke-ai/InvokeAI#5128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24gb

### What version did you experience this issue on?

3.4.0post1

### What happened?

![image](https://github.com/invoke-ai/InvokeAI/assets/5182104/c2899e45-69ae-4ac4-a795-6fcae53edac2)

Activating the venv and doing a
pip install controlnet-aux
seems to fix the issue, the webui now starts, but then it runs on CPU instead of my 4090...

god this automatic installer is a mess at the moment...

**Comment by hipsterusername** [comment]
You need to install the updated torch - Follow the directions in the release guidance. 

These issues are a function of pip installation and dependency updating.

**Comment by Lesani** [comment]
What is this „release guidance“ you speak of? I downloaded the installer and read the notes on the latest release page https://github.com/invoke-ai/InvokeAI/releases/tag/3.4.0post1
And followed the instructions on how to install fron the readme.md „quick install“ instructions… https://github.com/invoke-ai/InvokeAI

**Comment by Millu** [comment]
To have Invoke run on your GPU, open the developer console and run: 

`pip install --force-reinstall torch==2.1.0 --index-url https://download.pytorch.org/whl/cu121`

This should update your torch installation to run on GPU
