### ISSUE TITLE
all images created are in errors , due to diffusers? 

### ISSUE THREAD

**Issue by jjiikkkk** [invoke-ai/InvokeAI#5129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

16

### What version did you experience this issue on?

3.0

### What happened?

very poor image quality
see 
![image](https://github.com/invoke-ai/InvokeAI/assets/73511302/c4e7e1ec-f227-4d7a-972f-5ddd9914cbe7)
![image](https://github.com/invoke-ai/InvokeAI/assets/73511302/88aee41a-f623-4422-896e-13b2c0a37df5)
due your updates?

### Screenshots

very poor image quality
see 
![image](https://github.com/invoke-ai/InvokeAI/assets/73511302/c4e7e1ec-f227-4d7a-972f-5ddd9914cbe7)
![image](https://github.com/invoke-ai/InvokeAI/assets/73511302/88aee41a-f623-4422-896e-13b2c0a37df5)
due your updates?

### Additional context

very poor image quality
see 
![image](https://github.com/invoke-ai/InvokeAI/assets/73511302/c4e7e1ec-f227-4d7a-972f-5ddd9914cbe7)
![image](https://github.com/invoke-ai/InvokeAI/assets/73511302/88aee41a-f623-4422-896e-13b2c0a37df5)
due your updates?

**Comment by jjiikkkk** [comment]
!pip install 'InvokeAI[xformers]' --use-pep517 --extra-index-url https://download.pytorch.org/whl/cu118 --break-system-packages
due to cu version?

**Comment by Millu** [comment]
Could you try updating to 3.4 and seeing if the issue persists?
