### ISSUE TITLE
[bug]: Fallback to CPU after upgrade

### ISSUE THREAD

**Issue by vrubzov1957** [invoke-ai/InvokeAI#5130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

11

### What version did you experience this issue on?

3.4.0post1

### What happened?

After upgrading from 3.4.0rc2 to 3.4.0post1 in CLI - was fallback to using CPU instead of GPU CUDA.

As I found - while upgrading was installed PyTorch version for CPU

When start InvokeAI Web - in cmd i see
```
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.0+cu121 with CUDA 1201 (you have 2.1.0+cpu)
    Python  3.10.11 (you have 3.10.11)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
```

I tried reistall  a correct CUDA Xformers and PyTorch manually with cmd with global PIP of my system - but I see same error and same CPU fallback

---

PS: After this I tried to download new installer from https://github.com/invoke-ai/InvokeAI/releases/download/v3.4.0post1/InvokeAI-installer-v3.4.0post1.zip to reinstall InvokeAI.
But I see "Not found"
<img width="1132" alt="nf" src="https://github.com/invoke-ai/InvokeAI/assets/54937209/2e493a14-0ad3-481e-a597-44a2093cfce8">

**Comment by Millu** [comment]
Try this: 

Launch your invoke.bat / invoke.sh and select the option to open the developer console
1. Run: `pip install --force-reinstall torch==2.1.0 --index-url https://download.pytorch.org/whl/cu121`
2.If you run into an error with typing_extensions, re-open the developer console and run:  `pip install -U typing-extensions`
