### ISSUE TITLE
[bug]: "Use Seed" gives the seed of the image that was selected before the current one

### ISSUE THREAD

**Issue by ufuksarp** [invoke-ai/InvokeAI#5131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12

### What version did you experience this issue on?

3.4.0post1

### What happened?

"Use Seed" gives the seed of the image that is behind the current one selected in the gallery. Is there an index error or an invisible entry maybe?

**Comment by ufuksarp** [comment]
After some testing, it actually gives the seed of the image that was selected from the gallery before the current one, not the one right behind the selected one.

**Comment by psychedelicious** [comment]
I can reproduce this using the hotkey but not the buttons. Is that the same behaviour you are seeing?

I've fixed the hotkey issue in #5135.

**Comment by ufuksarp** [comment]
> I can reproduce this using the hotkey but not the buttons. Is that the same behaviour you are seeing?

Yes.

**Comment by psychedelicious** [comment]
Thanks for confirming. I'll close this issue when the fix is merged then. Will be in the next release.
