### ISSUE TITLE
[enhancement]: Output node metadata

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#5133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I'd suggest adding "metadata" field to all output nodes (ie: "ersgan" node in particular) as we have no info besides file "name" and "pixel data" coming through DiskImageFileStorage "save" for instance

**Comment by psychedelicious** [comment]
This node already has metadata available to it.

If you have the image name, you can use the images service to pull metadata for that image. Does that get you everything you need?

**Comment by Neosettler** [comment]
I should have mentioned that I'm still on 3.1. My bad, all good then thank you.
