### ISSUE TITLE
[enhancement]: use eslint plugin for i18next to enforce translations

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#5138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

`eslint-plugin-i18next` has a rule `'i18next/no-literal-string': 2` that enforces translations by preventing literal strings from being used in JSX.

We should use this rule to reduce the creep of untranslated strings

**Comment by rohinish404** [comment]
Can you assign me?
