### ISSUE TITLE
installation error [bug]: 

### ISSUE THREAD

**Issue by kakachiex2** [invoke-ai/InvokeAI#5145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.4 3.3 3.2 

### What happened?

I follow the install process and give me the following error on windows
![Screenshot 2023-11-21 042830](https://github.com/invoke-ai/InvokeAI/assets/1762112/da21b6cd-80af-413d-9e66-cf63a7fb4d33)
![Screenshot 2023-11-21 042752](https://github.com/invoke-ai/InvokeAI/assets/1762112/7aceebd6-8032-4495-8f5f-583e82ccec32)

### Contact Details

nolascokiko@gmail.com

**Comment by Millu** [comment]
What version of python are you using?

**Comment by kakachiex2** [comment]
I have 3.12 and 3.11 installed

**Comment by kakachiex2** [comment]
when I verify version number PowerShell it says 3.12

**Comment by Millu** [comment]
That's the issue - InvokeAI only supports Python 3.10 or 3.11

**Comment by kakachiex2** [comment]
It is possible to make 3.11 default...?

**Comment by kakachiex2** [comment]
Thanks Millu I' already solve the python 3.11 environment variable by default
