### ISSUE TITLE
[bug]:possible to tell me how to choose branch or a certain old version in command lines

### ISSUE THREAD

**Issue by jjiikkkk** [invoke-ai/InvokeAI#5146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

16

### What version did you experience this issue on?

2.3.X

### What happened?

before I use cuda 117, everything goes well
later I use cuda 118, images created become poorer, blurry

how can I choose certain branch or version of invoke ai from below 

import os
import subprocess

env = os.environ.copy()

!pip install 'InvokeAI[xformers]' --use-pep517 --extra-index-url https://download.pytorch.org/whl/cu117 --break-system-packages

!pip install tensorflow
!pip install --no-deps tensorflow-io 

your installation does not start from git clone.....so I do not know how to choose branch

### Screenshots

before I use cuda 117, everything goes well
later I use cuda 118, images created become poorer, blurry

how can I choose certain branch or version of invoke ai from below 

import os
import subprocess

env = os.environ.copy()

!pip install 'InvokeAI[xformers]' --use-pep517 --extra-index-url https://download.pytorch.org/whl/cu117 --break-system-packages

!pip install tensorflow
!pip install --no-deps tensorflow-io 

your installation does not start from git clone.....so I do not know how to choose branch

### Additional context

before I use cuda 117, everything goes well
later I use cuda 118, images created become poorer, blurry

how can I choose certain branch or version of invoke ai from below 

import os
import subprocess

env = os.environ.copy()

!pip install 'InvokeAI[xformers]' --use-pep517 --extra-index-url https://download.pytorch.org/whl/cu117 --break-system-packages

!pip install tensorflow
!pip install --no-deps tensorflow-io 

your installation does not start from git clone.....so I do not know how to choose branch

**Comment by Millu** [comment]
You can do pip install invokeai==<desired version number>

**Comment by jjiikkkk** [comment]
import os
import subprocess

env = os.environ.copy()

!pip install invokeai==2.3.5 --use-pep517 --extra-index-url https://download.pytorch.org/whl/cu118 --break-system-packages

!pip install tensorflow
!pip install --no-deps tensorflow-io   like this?

**Comment by jjiikkkk** [comment]
but no need to git?

**Comment by jjiikkkk** [comment]
how to change this !pip install 'InvokeAI[xformers]' --use-pep517 --extra-index-url https://download.pytorch.org/whl/cu117 --break-system-packages?

I need to use  2.3.5  and cu118

**Comment by Millu** [comment]
This should work: 

`!pip install 'InvokeAI[xformers]'==2.3.5 --use-pep517 --extra-index-url https://download.pytorch.org/whl/cu118 --break-system-packages`

**Comment by jjiikkkk** [comment]
okay thanks a lot
