### ISSUE TITLE
[bug]: using cuda 117, image creation is too slow, using cuda 121, too slow.   using cuda 118, faster but image quality blurry and poor

### ISSUE THREAD

**Issue by jjiikkkk** [invoke-ai/InvokeAI#5147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

16

### What version did you experience this issue on?

2.3.

### What happened?

[bug]: using cuda 117, image creation is too slow, using cuda 121, too slow.   using cuda 118, faster but image quality blurry and poor

### Screenshots

[bug]: using cuda 117, image creation is too slow, using cuda 121, too slow.   using cuda 118, faster but image quality blurry and poor

### Additional context

[bug]: using cuda 117, image creation is too slow, using cuda 121, too slow.   using cuda 118, faster but image quality blurry and poor

**Comment by Millu** [comment]
Not sure what the issue is, but InvokeAI 2.3.x has been deprecated in favor of InvokeAI 3.x.
