### ISSUE TITLE
No module named 'basicsr'

### ISSUE THREAD

**Issue by KenLubin** [invoke-ai/InvokeAI#515]
I get the following error with GFPGAN, it's installed in sister directory as per instructions.

`>> Error loading GFPGAN:
Traceback (most recent call last):
  File "c:\users\anibu\stable-diffusion\ldm\gfpgan\gfpgan_tools.py", line 28, in run_gfpgan
    from gfpgan import GFPGANer
  File "C:\Users\anibu\GFPGAN\gfpgan\__init__.py", line 2, in <module>
    from .archs import *
  File "C:\Users\anibu\GFPGAN\gfpgan\archs\__init__.py", line 2, in <module>
    from basicsr.utils import scandir
ModuleNotFoundError: No module named 'basicsr'`

However, when I pip install basicsr it says that everything is satisfied completely. I went through instructions and re-installed gfpgan, still doesn't work.

**Comment by KenLubin** [comment]
Yep. Did that three times. All dependencies satisfied. No errors when
installing.

**Comment by blessedcoolant** [comment]
> Yep. Did that three times. All dependencies satisfied. No errors when installing.

Can you check if you are able to perform inference directly using the GFPGAN inference scripts without any errors?

**Comment by psychedelicious** [comment]
We have refactored our GFPGAN implementation since you had this error. I'm going to close this now - please create a new issue if you still have this problem on the main or development branch.
