### ISSUE TITLE
how to skip this?

### ISSUE THREAD

**Issue by wolfkingal2000** [invoke-ai/InvokeAI#5158]
### What happened?

Please select the scheduler prediction type of the checkpoint named tmndMix_tmndMixSPRAINBOW.safetensors:
 [1] "epsilon" - most v1.5 models and v2 models trained on 512 pixel images 
[2] "vprediction" - v2 models trained on 768 pixel images and a few v1.5 models 
[3] Accept the best guess; you can fix it in the Web UI later select 
[3]>

show me this went installed model how can skip this  any commend  to skip this question?

### OS
Linux
### GPU
cuda
### VRAM
16
### What version did you experience this issue on?
2.4.0

**Comment by Millu** [comment]
This has been fixed in newer versions of InvokeAI (v3.3+)

**Comment by pengtb** [comment]
Latest version v3.6.0 still got this when importing checkpoints. It could be quite annoying when migrating and importing hundreds of models from other webui. Honestly a non-interactive option is needed for this.

**Comment by d8ahazard** [comment]
Came here to agree with everybody else. Hopefully, the refactor of the model manager takes this into account, and also speeds up the overall loading process. InvokeAI is the only app like this that I've used where adding or changing models outside of the app is so painful.

**Comment by tetsuoo-online** [comment]
I came to search about the same issue, I've been using lots of UI, A1111, SDNext, ComfyUI, Fooocus and so on, none of them have been dumb to do something like this. I have 540 models in my folder, am I suppose to hit 3 for each, one by one ? That's ridiculous. This is how you get people to simply delete and forget about it

**Comment by Cad5z5** [comment]
It's still happening. Version 3.6.3

**Comment by psychedelicious** [comment]
This part of the app has been rewritten. You will never get prompts like this. Please update to the latest release.
