### ISSUE TITLE
Translating stable-diffusion to another language

### ISSUE THREAD

**Issue by gakowalski** [invoke-ai/InvokeAI#516]
Hello, is it possible to introduce support for a language other than English? If so, how? Is it necessary to retrain on the entire dataset with translated image labels?

**Comment by hipsterusername** [comment]
Because the model is trained by learning the semantic connection between labels and images, I have to imagine the only way to truly create "support" for other languages would to retrain on the entire dataset.

**Comment by bmaltais** [comment]
Write prompt in any language, Google translate to English and use result as prompt.

**Comment by lstein** [comment]
@hipsterusername has it right. To train the model on another language would be incredibly time- and labor-intensive. Basically the same effort as the original work.

On the other hand, @bmaltais has the germ of a great idea. We could stick in calls to the Google Translation AI (or something similar) and if the user enters their access token for payment, we could autodetect the prompt language and convert it to English behind the scenes.

**Comment by hipsterusername** [comment]
I'd have folks interested in that use Google Translate manually for a time to see how effective it is and report back. My concern would be that the game of "semantic telephone" played between input, google translation, and output might mean that it ends up not getting used as much as a result - Especially since so much of "good prompt engineering" involves just tossing in a bunch of qualifiers + stylistic terms.

**Comment by Any-Winter-4079** [comment]
> I'd have folks interested in that use Google Translate manually for a time to see how effective it is and report back. My concern would be that the game of "semantic telephone" played between input, google translation, and output might mean that it ends up not getting used as much as a result - Especially since so much of "good prompt engineering" involves just tossing in a bunch of qualifiers + stylistic terms.

@hipsterusername I think there would be things that are definitely lost, but something like "a photo of Emma Stone in Grand Theft Auto" is going to be pretty simple to translate.
Here's an example, writing it in Spanish. The translation to English is perfect.
<img width="674" alt="Screenshot 2022-09-16 at 01 05 14" src="https://user-images.githubusercontent.com/50542132/190523660-be0cbfe6-52c9-4411-9830-0663fbfe4924.png">

What you say about stylistic terms is an important part to consider, though. Maybe those would need a different treatment (like choosing options from a menu in their own language, to make sure the right words are used in English)?

What I don't know is how demanded/used the feature would be as most people that use this repo need to understand English, right? To get the environment set up, sort out errors & performance issues... [I'm assuming people that know programming know English to some degree]

The more we go into making an executable / app / Docker image, with less and less setup for the user (which right now is documented only in English I believe), the more people with lower tech knowledge that can use it, removing the barrier to somewhat understand English. But maybe not and for many people, their own language is more convenient. I really don't know :)

**Comment by Any-Winter-4079** [comment]
The idea itself doesn't seem difficult however. I'm sure there's free libraries that let you translate.
