### ISSUE TITLE
[bug]: No Add difference option in the merge models section

### ISSUE THREAD

**Issue by HG2407** [invoke-ai/InvokeAI#5168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

16gb

### What version did you experience this issue on?

v3.3.0

### What happened?

There is no option of add difference interpolation in the merge models section while it is mentioned in the document.

### Screenshots

![Screenshot (37)](https://github.com/invoke-ai/InvokeAI/assets/132276798/e401fe3c-c422-4ffb-b269-ffdd1fd9dd3d)

**Comment by Millu** [comment]
Add difference is only available for merging 3 models

**Comment by HG2407** [comment]
@Millu thanks!
