### ISSUE TITLE
[enhancement]: SDXL-turbo support

### ISSUE THREAD

**Issue by OrbitalExplorer** [invoke-ai/InvokeAI#5193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

obe.willaert@icloud.com / @gmail.com, Discord: @orbitalexplorer Telegram: https://t.me/Obe_Willaert Twitter/X: @ExplorerOrbital

### What should this feature add?

Real time generation as you type and support for [sdxl turbo](https://huggingface.co/stabilityai/sdxl-turbo) because now the images I get with sdxl turbo (configured to let it think it's sdxl) get very incorrect images: 
![c23a0c87-49db-4909-91f6-efaf090506a0](https://github.com/invoke-ai/InvokeAI/assets/75388592/5da82133-dac1-4761-a8ce-9ad6bc514873)
and this is sdxl with refiner
![2b227127-02f9-4382-81e3-3994f5e350ca](https://github.com/invoke-ai/InvokeAI/assets/75388592/b007022e-3cee-4dd9-a19b-d02440e6f677)
![398a0b16-e401-4708-b8cc-d074a7c01a6e](https://github.com/invoke-ai/InvokeAI/assets/75388592/5057cd3b-da14-4c5a-9a23-667338fc44db)

**Comment by hipsterusername** [comment]
We have support for SDXL Turbo already. You need to ensure your CFG and steps are at 1. You also likely want to use a specific set of schedulers (like Euler Ancestral) as some have issues.

**Comment by OrbitalExplorer** [comment]
Oh I see I did not see my CFG to 1, thanks for the response. But am I once again missing something because the quality is way worse than the normal version.

**Comment by hipsterusername** [comment]
If the image is coherent you are probably not missing anything. The image quality of turbo is going to worse than the full model.

**Comment by OrbitalExplorer** [comment]
No, it's not coherent, some parts of the image are duplicate and the style is totally different.

These are the ones I get now, totally different from the ones above.
![b8c57257-3f70-468b-9f5f-ce4d5afa2fd0](https://github.com/invoke-ai/InvokeAI/assets/75388592/d87b5c6a-908f-4e2c-bc33-87640443f175)
![8e210d77-ccfa-425f-865a-05b19eb79448](https://github.com/invoke-ai/InvokeAI/assets/75388592/fe27d349-3d63-4f6f-9d8b-3353cfb298cb)

**Comment by hipsterusername** [comment]
Turbo can only generate images at 512x512.

**Comment by OrbitalExplorer** [comment]
Oh I thought Emad tweeted it can do 786, but that still doesn't explain the style difference, maybe it's just a bit worse and doesn't know the style so well.

**Comment by OrbitalExplorer** [comment]
Oh yeah I see it now on their page, I read this [tweet](https://x.com/emostaque/status/1729718341491712240?s=46&t=V_ILNDVWpo7OQVjI2_qyNA) and assumed it was without upscaling

**Comment by hipsterusername** [comment]
Yep - It's just worse.
