### ISSUE TITLE
[enhancement]: add metadata to canvas graphs

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#5203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Canvas Inpaint and Outpaint graphs do not have metadata. We should include at least the basics here.

This is a good first issue:
- Check out the one of the other graph building functions in `invokeai/frontend/web/src/features/nodes/util/graph` for an example of adding metadata to a graph. 
- Implement this for the Inpaint and Outpaint graphs

The images will have metadata, but you'll need to enable "Auto Save to Gallery" to see them in the gallery:
![image](https://github.com/invoke-ai/InvokeAI/assets/4822129/067e56b7-68bf-4691-a009-ebaf6d070d16)

**Comment by YulienPohl** [comment]
I can't remember if it worked before or if I did something different back then, but my old images from version 2.3.4 contain the metadata.

**Comment by psychedelicious** [comment]
This is implemented in canvas v2
