### ISSUE TITLE
[bug]: Pip dependency error when trying to force reinstall rocm torch

### ISSUE THREAD

**Issue by FinnRG** [invoke-ai/InvokeAI#5219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

amd

### VRAM

8Gb

### What version did you experience this issue on?

v3.4.0post2

### What happened?

After using the automated installer, invokeai defaulted to using the cpu, which obviously caused very slow image generation.
I tried running [the command from the docs](https://invoke-ai.github.io/InvokeAI/installation/010_INSTALL_AUTOMATED/#invokeai-runs-extremely-slowly-on-linux-or-windows-systems) to reinstall rocm torch, but this errored with a pip dependency error:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
invokeai 3.4.0.post2 requires requests~=2.28.2, but you have requests 2.31.0 which is incompatible.
invokeai 3.4.0.post2 requires torch==2.1.0, but you have torch 2.1.1 which is incompatible.
invokeai 3.4.0.post2 requires torchvision==0.16.0, but you have torchvision 0.16.1 which is incompatible.
```

I've also tried the `pip install InvokeAI --force-reinstall` command from the docs.

**Comment by FinnRG** [comment]
I managed to get around this bug by explicitly specifying the dependency versions: `pip install "torch==2.1.0+rocm5.6" "torchvision==0.16.0+rocm5.6" "requests~=2.28.2" --force-reinstall --extra-index-url https://download.pytorch.org/whl/rocm5.6`.

**Comment by Millu** [comment]
@FinnRG that would be great if you could open a PR!

**Comment by psychedelicious** [comment]
The installer has been rewritten to avoid problems like this. Please create a new issue if the problem persists on the latest release.
