### ISSUE TITLE
[enhancement]: display app dependencies in UI

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#5223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

In #5206 an endpoint was added to report the versions of the app's dependencies (only the big ones are included). This data should be available somewhere in the UI.

We don't have any place for this kind of information yet. Maybe the settings modal? Maybe a new tab? Maybe the settings modal gets converted into a tab?

**Comment by rohinish404** [comment]
Can i take this up?
