### ISSUE TITLE
[bug]:invokeai.sh: line 55: invokeai: command not found

### ISSUE THREAD

**Issue by MRNAUW** [invoke-ai/InvokeAI#5242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

amd

### What version did you experience this issue on?

v3.4

### What happened?

Hey,

I receive the following message :line 55: invokeai: command not found' after trying to run the web version of invoke ai ( invoka.sh) 

Line 5 seems in virtual study code the following :     invokeai web $PARAMS

Running 7 : rerun the configured script did not work;

Can someone help me?

**Comment by Millu** [comment]
Was this a fresh install or an update?

**Comment by lidlesseye** [comment]
> Was this a fresh install or an update?

I hit this too on macOS 14.1.2 (23B92) after performing an update.

**Comment by MRNAUW** [comment]
> Was this a fresh install or an update?

This was the result of an update of Invokeai. :) I can't get it work.

**Comment by MRNAUW** [comment]
> > Was this a fresh install or an update?
> 
> This was the result of an update of Invokeai. :) I can't get it work.

did you found a solution?

**Comment by psychedelicious** [comment]
The installer has been rewritten to avoid problems like this. Please create a new issue if the problem persists on the latest release.
