### ISSUE TITLE
[bug]: Unable to connect to web ui via SSH, error ({"detail": "Not Found"})

### ISSUE THREAD

**Issue by netrunner-exe** [invoke-ai/InvokeAI#5269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12

### What version did you experience this issue on?

3.4.0post2

### What happened?

I usually connect to InvokeAI using SSH. Example command: ssh -R 80:127.0.0.0.1:9090 -o StrictHostKeyChecking=no -i id_rsa remote.moe. Next, I run **python scripts/invokeai-web.py --xformers** and successfully access the web ui using the generated link, for example http://bdavvbfyzaqbdavvbfyzaqbdavvbfyzaqbdavvbfyzaq.remote.moe  via **remote.moe**. After commit **bbcd58e681e4915e906c0797ac17c8e5ddad729b**, I keep getting the error `{"detail": "Not Found"}`.
Rolling back to commit **36043bf38b710b8be378d9c890cc7feb697fa608** solves the problem and everything works. The latest commits currently do not solve the problem.

### Screenshots

![1](https://github.com/invoke-ai/InvokeAI/assets/81887288/337fe635-e9e5-4745-ae9c-737f2d550db5)

### Additional context

**Latest working commit**: **36043bf38b710b8be378d9c890cc7feb697fa608**
**Commit, after which the problems started:** **bbcd58e681e4915e906c0797ac17c8e5ddad729b**

### Contact Details

netrunner.exe@gmail.com

**Comment by psychedelicious** [comment]
@netrunner-exe Mobile support is something we are definitely want, but don't have a specific timeline yet, sorry! That's a pretty good-lookin reskin you've linked there. Well done to whoever cooked that up.
