### ISSUE TITLE
[bug]: unable to install on linux

### ISSUE THREAD

**Issue by Bobcatie** [invoke-ai/InvokeAI#5271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

3.4.0

### What happened?

ERROR: Directory '/home/user/Downloads/InvokeAI-3.4.0post2/installer[xformers,onnx-cuda]' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

**Comment by Millu** [comment]
How did you run the installer?

**Comment by tddschn** [comment]
Same issue on linux, I tried to installed by `./installer/install.sh.in`

**Comment by Millu** [comment]
@tddschn you shouldn't be running the `install.sh.in` file - download the automated installer from here: https://github.com/invoke-ai/InvokeAI/releases/tag/v3.6.0 and run the `install.sh` file to install Invoke

**Comment by psychedelicious** [comment]
The installer has been rewritten to avoid problems like this. Please create a new issue if the problem persists on the latest release.
