### ISSUE TITLE
[bug]: 安装时报错，版本问题

### ISSUE THREAD

**Issue by alsjdnh** [invoke-ai/InvokeAI#5303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

NONE

### What happened?

安装时报错，显示如下
ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5
ERROR: Could not find a version that satisfies the requirement triton (from versions: none)
ERROR: No matching distribution found for triton
直接在系统环境下运行，未启动Anaconda或CUDA

### Screenshots

![屏幕截图 2023-12-16 214346](https://github.com/invoke-ai/InvokeAI/assets/131505167/d3e7faa7-802e-4821-8804-e18707db75bd)

### Contact Details

3394077460@qq.com

**Comment by Millu** [comment]
Make sure you have Python 3.10 or 3.11 installed, but outside of that error, there's no triton build available for windows. You can ignore that error

**Comment by alsjdnh** [comment]
> 确保您安装了 Python 3.10 或 3.11，但除了该错误之外，没有适用于 Windows 的 triton 版本。您可以忽略该错误

安装的的确是Python 3.11
![Uploading 屏幕截图 2023-12-18 120251.png…]()

**Comment by psychedelicious** [comment]
The installer has been rewritten to avoid problems like this. Please create a new issue if the problem persists on the latest release.
