### ISSUE TITLE
[bug]: UI text labels not being localized or missing from Weblate

### ISSUE THREAD

**Issue by Harvester62** [invoke-ai/InvokeAI#5308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

3.4.0post2 (main)

### What happened?

Several text labels in the UI are not converted to the related localized version, or are not available on Weblate for translation. I am reporting this relatively to the Italian localization, but this seems to happen also with other localizations.

I took screenshots of the UI highlighting the labels that don’t show up correctly for one of the two above reasons.

MAIN UI - GENERATION PARAMETERS

![279465358-232c11ae-7535-4ec1-a0c3-f5d47aed0965](https://github.com/invoke-ai/InvokeAI/assets/29801031/08e269fc-7834-4d3a-b8d2-e0623d9eb6e2)

“Drop” is not using the localized text on Weblate.
![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/176e97b9-fa9a-4113-8dd0-f98d964a4c0c)

IMAGE TO IMAGE

![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/bda05791-e598-4847-bb62-948965d56299)

“No initial image selected” is not using the localized text.
![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/5ba84ac5-4392-4aeb-a2cd-2e5032c52b8e)

The labels of the two highlighted buttons on the top right corner, “Upload Initial Image” and “Reset Initial Image”, are not available on Weblate for translation.
![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/42e27a07-e616-461f-8eb8-722cec7b4816)

"Set as initial image" is not using the localized text.
![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/fa605ea2-b36d-463d-92ce-8a078499d00b)

In Unified Canvas, the labels for blur effects in the Compositing Settings are not available on Weblate for translation:
![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/095246cd-68c6-4674-8b30-57afb7bf88c5)

**Comment by rohinish404** [comment]
I would like to get assigned on this!
