### ISSUE TITLE
[bug]: v3.5.0rc2: WebUI not starting - displays message: {"detail":"Not Found"}

### ISSUE THREAD

**Issue by grunblatt-git** [invoke-ai/InvokeAI#5317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cuda

### VRAM

32GB

### What version did you experience this issue on?

v3.5.0rc2

### What happened?

After Updating to v3.5.0rc1 (and later v3.5.0rc2) the WebUI is not starting anymore when running `sh invoke.sh`.
The server returns HTTP 404 status codes (see log below) and the browser (Chrome and Firefox) displays `{"detail":"Not Found"}`

> [ModelInstallService]::INFO --> 0 new models registered
[ModelInstallService]::INFO --> Model installer (re)initialized
[uvicorn.error]::INFO --> Application startup complete.
[uvicorn.error]::INFO --> Uvicorn running on http://127.0.0.1:9090 (Press CTRL+C to quit)
[uvicorn.access]::INFO --> 127.0.0.1:49246 - "GET / HTTP/1.1" 404
[uvicorn.access]::INFO --> 127.0.0.1:49246 - "GET /favicon.ico HTTP/1.1" 404
[uvicorn.access]::INFO --> 127.0.0.1:51591 - "GET / HTTP/1.1" 404
[uvicorn.access]::INFO --> 127.0.0.1:51591 - "GET /favicon.ico HTTP/1.1" 404

I am not quite sure why a different port appears in the log on each reload - the browser is opened at `http://127.0.0.1:9090`.

### Additional context

I didn't have issues with running v3.4.0.
Is it safe to downgrade back to v3.4.0 even after the database migration that happened when installing v3.5.0rc1?

**Comment by Millu** [comment]
To fix this, run the installer linked in the release: https://github.com/invoke-ai/InvokeAI/releases/tag/v3.5.0rc2

There will be an updated RC today with this resolved

**Comment by zeegaix** [comment]
Had the Same issue, I was able to fix it by deleting the venv folder and reinstalling in same folder.

**Comment by rugabunda** [comment]
> To fix this, run the installer linked in the release: https://github.com/invoke-ai/InvokeAI/releases/tag/v3.5.0rc2
> 
> There will be an updated RC today with this resolved

Same problem, used the installer linked in the release

**Comment by rugabunda** [comment]
Yikes, reinstalling via auto once again and it redownloads all the models already downloaded, only to say:

![2023-12-18_19-41-31_E8tBEsMaL7](https://github.com/invoke-ai/InvokeAI/assets/38260267/b2e8f340-e588-4fab-90d5-5a6ce7abf107)

**Comment by rugabunda** [comment]
deleting venv and reinstalling fixed the problem

**Comment by Millu** [comment]
@rugabunda @zeegaix @grunblatt-git the latest 3.5.0rc3 should have fixed this issue - could you give it a try please?

**Comment by Mohsyn** [comment]
3.6.0 same issue
