### ISSUE TITLE
[bug]: InvokeAI  canvas..

### ISSUE THREAD

**Issue by gece7** [invoke-ai/InvokeAI#5320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

4gb

### What version did you experience this issue on?

3.5.0rc1

### What happened?

[2023-12-19 18:19:50,522]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "H:\Program\Invoke.ai\.venv\lib\site-packages\invokeai\app\services\invocation_processor\invocation_processor_default.py", line 104, in __proce
ss
    outputs = invocation.invoke_internal(
  File "H:\Program\Invoke.ai\.venv\lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 669, in invoke_internal
    output = self.invoke(context)
  File "H:\Program\Invoke.ai\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "H:\Program\Invoke.ai\.venv\lib\site-packages\invokeai\app\invocations\latent.py", line 1077, in invoke
    latents = latents.to("cpu")
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[2023-12-19 18:19:50,549]::[InvokeAI]::ERROR --> Error while invoking:
CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

I'm having problems when I increase the canvas resolution. Please help.

**Comment by hipsterusername** [comment]
"I'm having problems when I increase the canvas resolution. Please help."

Can you expand on that @gece7 ? What do you mean by that - increasing the size of your generation?

**Comment by gece7** [comment]
![Screenshot_6](https://github.com/invoke-ai/InvokeAI/assets/140728763/4f85ba67-889f-478d-939a-33d4ee843979)
![Screenshot_7](https://github.com/invoke-ai/InvokeAI/assets/140728763/9417f280-da65-4235-9513-158de7dd663c)

[hipsterusername](https://github.com/hipsterusername)

**Comment by hipsterusername** [comment]
You have only 4gb of vram on your GPU. This is your computer tapping out.

**Comment by gece7** [comment]
There are people who can achieve this with 4 GB vram. I hope I can solve the possible problem elsewhere.

**Comment by Millu** [comment]
@gece7 sorry you're having trouble with this - going to close this out as there isn't much Invoke can do to help.
