### ISSUE TITLE
[enhancement]: Option to password protect or hide an image board

### ISSUE THREAD

**Issue by Nate82** [invoke-ai/InvokeAI#5334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

All image boards show in the main work space, so if you create nsfw content, horror, gore, or other content you don't want people to see, you can't show anyone your other work because of this.

What _prompted_ this idea was I had my sister and nieces over recently, I would've loved to let the girls make some images but I have tons of boards with gore/horror stuff that they don't need to see. I could've minimized the Gallery but one accidental click and the boards would've shown with the thumbnails.

I suggest adding an option so we can password protect a board (and blur the thumbnail if it's protected) or hide a board from view and create a separate section for those hidden boards. Any thoughts on this?

**Comment by RicoRaw** [comment]
This is a great idea. I've been dealing with the same issue with providing access so my kids can learn how to use InvokeAI. I typically remove all the sensitive boards before granting them access, but that's a bit cumbersome at times.
A "hide" or "lock" feature for boards would be great.

**Comment by psychedelicious** [comment]
Hi, thanks for the suggestion. We don't plan to implement this kind of functionality.

If you want only certain images to be visible, you can create a second app data folder (say, "invokeai_kids") and point the app at that new folder, as described here: https://invoke-ai.github.io/InvokeAI/features/CONFIGURATION/#invokeai-root-directory

On startup, go to the model manager tab > add models > scan folder. Paste in the path to the models directory from your main install and scan. Install the models you want to be available, **being sure to enable in-place install so the files are not moved from your main install's models dir to "invokeai_kids".**

That'll give you a second installation with separate list of safe models, its own gallery, boards settings, etc. The model weights and application packages will be shared between the installs so it's not going to take up oodles of disk space.
