### ISSUE TITLE
[bug]: .env.sample refers to non-existent GPU_DRIVER

### ISSUE THREAD

**Issue by coder543** [invoke-ai/InvokeAI#5336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

main

### What happened?

The InvokeAI Docker directory contains a .env.sample. This file demonstrates using `GPU_DRIVER=cuda`, which I tried in my .env file. This does not work. There is no container in `docker-compose.yml` that ends in `-cuda`, which is what the `run.sh` script tries to run when `GPU_DRIVER=cuda`. Looking at the docker-compose file, it is clear that the `GPU_DRIVER` is supposed to be `nvidia`. The sample file needs to be updated to be correct.

**Comment by ebr** [comment]
Thanks for catching this. Fixed in the linked PR.
