### ISSUE TITLE
[bug]: Error loading models

### ISSUE THREAD

**Issue by PsypmP** [invoke-ai/InvokeAI#5337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12

### What version did you experience this issue on?

3.4.0 post2

### What happened?

I downloaded other models. I downloaded the Invoke from the HuggingFace repository. I threw them into auto-import, threw them into folders. The program does not accept models downloaded by yourself. Do I have to manually create folders and text files for each damn model? Where do your hands grow from?

### Screenshots

<img width="1273" alt="image" src="https://github.com/invoke-ai/InvokeAI/assets/54102981/720929c5-6a19-4bc7-b0ef-ab901d2cceaf">

**Comment by Millu** [comment]
It's hard to tell exactly why the auto import is not working as expected - the easiest way to install IP adapters is to use the model manager, pasting the Repo ID in the "Add model section". You can find all the Repo IDs on the respective model pages at https://models.invoke.ai


For example: 
IP-Adapter Image Encoder: `InvokeAI/ip_adapter_sd_image_encoder`
IP-Adapter: `InvokeAI/ip_adapter_sd15`
<img width="326" alt="Screenshot 2023-12-26 at 5 13 02 PM" src="https://github.com/invoke-ai/InvokeAI/assets/7254508/79e5e5a3-4a4a-41b9-ba43-8db1ff6e7a87">


As for the ControlNets, Invoke only works with diffusers format SDXL ControlNets.
