### ISSUE TITLE
[enhancement]: Support to up to 300 Loras and many Checkpoints like also 100 - 300

### ISSUE THREAD

**Issue by alfi4000** [invoke-ai/InvokeAI#5345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

alfziterbacke@gmail.com

### What should this feature add?

Support to up to 300 Loras and many Checkpoints like also 100 - 300

### Alternatives

Support to up to 300 Loras and many Checkpoints like also 100 - 300

### Additional Content

Support to up to 300 Loras and many Checkpoints like also 100 - 300

**Comment by alfi4000** [comment]
i have the problem that the web lags so I think it is because I have 150 Loras and 10 Checkpoints is that maybe the cause I use Dell PowerEdge r730xd with Nvidia Tesla p40

**Comment by alfi4000** [comment]
I would be happy for a Update where the lag will stop!

**Comment by Millu** [comment]
What version of Invoke are you using? Invoke supports an unlimited number of models

**Comment by alfi4000** [comment]
Oh um I use latest I just updated the version because I thought it is a version problem but I just recognized before it loaded the content when just the guy is loaded all works fine but when it loads all Loras and checkpoints it lags! give me a sec to boot invoke then I tell you the version!

**Comment by alfi4000** [comment]
3.4.0post2 is the version

**Comment by alfi4000** [comment]
shell I make a screen recording?

**Comment by Millu** [comment]
A screen recording would be great!

**Comment by alfi4000** [comment]
here is the Link :  https://youtu.be/VH2nvvGzpz0

**Comment by alfi4000** [comment]
it just looks like it is overloaded from too many Loras!

**Comment by alfi4000** [comment]
I have a different question does InvokeAi Use 2 Gpus for image generating when I have 2 gpus to the system connected?
To clarify I want to create 1 image in the size of 1088 x 704 and I have 2 gpus connected to the system but the speed is 1.5its  that is slow, does it use both gpus then for the image or just one to generate the image?

**Comment by alfi4000** [comment]
Let me know when I should try something because of the Problem with the lag or if you need some more information!

**Comment by alfi4000** [comment]
now with the update to 3.5.1 its a bit better Model Manager and Queue works like normal on a app or so but the other ones are still laggy! look here at a new screen recording:  https://youtu.be/wT5HIHUCuw4    I hope you guys get this problem solved!

**Comment by alfi4000** [comment]
I just remember that I have forgot to record and to say the process bar on some state lags also ill upload for that problem a screen recording the next days! I have today no more time for that! :)

**Comment by alfi4000** [comment]
here is the screen recording from the lagging prompt status bar:   https://youtu.be/l3kEmdt_PIw

**Comment by alfi4000** [comment]
I just removed al Loras so only the loading bar was a bit laggy and the other thing is after adding the 29 checkpoint it started to lag the hole system maybe a different loading way of the checkpoints and Loras is might be better like only load on the moment when the chosen model is choosed that I want to use that should Improve the performance if you guys haven't done that already!
