### ISSUE TITLE
[bug]: Update to 3.5.0 and not working

### ISSUE THREAD

**Issue by SoyLevelMax** [invoke-ai/InvokeAI#5358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12gb

### What version did you experience this issue on?

3.5.0

### What happened?

I Just update and stop working, the Eternal "QUEUE"

### Screenshots

![image](https://github.com/invoke-ai/InvokeAI/assets/98112689/4526ccbc-c812-42c6-9026-c4b3478b8812)

### Contact Details

vmxtunner@hotmail.com

**Comment by Millu** [comment]
I'm not sure I understand the issue - are queue items not being processed?

**Comment by angeloshredder** [comment]
same thing happened to me

**Comment by Millu** [comment]
@angeloshredder could you describe the behavior you're experiencing?

**Comment by Harvester62** [comment]
Is this bug report still relevant to be kept open? We're on v3.7 soon switching to v4.0 and we don't maintain older versions, right? Furthermore none of the users provided any feedback from December 2023.

**Comment by angeloshredder** [comment]
> @angeloshredder could you describe the behavior you're experiencing?

It was an old issue, now it's solved .. thanks
