### ISSUE TITLE
[bug]: The web UI regularly loses connection to the backend when working on the workflow page and hangs/blocks for several seconds

### ISSUE THREAD

**Issue by MarcoBlumenthal** [invoke-ai/InvokeAI#5373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

3.5.1

### What happened?

The web UI regularly loses connection to the backend when working on the workflow page and hangs/blocks for several (sometimes >20!!) seconds.
I see this line in the console window often:
[2024-01-02 01:18:58,555]::[uvicorn.error]::INFO --> connection closed
this happens in both Edge and Chrome browser.
(By the way, WebUI doesn't work in Firefox at all)
Usually, the connection reestablishes in Edge after a while, in Chrome it sometimes does not and a restart of the invoke.bat is necessary.
I observed this behaviour after the update to 3.5.1, the previous versions 3.4.x worked fluently.
It is quite annoying and nearly impossible to work efficiently in 3.5.1

### Contact Details

marco.blumenthal@gmx.de

**Comment by psychedelicious** [comment]
We've made a number of substantial performance improvements and will be releasing them (along with other goodies) in 3.6. Should be at least back to normal, and hopefully even better!
