### ISSUE TITLE
[bug]: combo boxes without scrollbar

### ISSUE THREAD

**Issue by MarcoBlumenthal** [invoke-ai/InvokeAI#5376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

3.6.0rc1

### What happened?

the item selection lists of all combo boxes appear without scrollbar.

please add such scrollbars to the combo boxes and also to the image gallery

### Contact Details

marco.blumenthal@gmx.de

**Comment by Millu** [comment]
Could you share examples of "Combo Boxes" ?

Also, thank you for all of the feedback! It's very helpful as we work through the new UI/UX

**Comment by psychedelicious** [comment]
What operating system and browser are you using?

**Comment by MarcoBlumenthal** [comment]
it happens in all the combo boxes. e.g. model and scheduler combo boxes in text-to-image page and also in all the combo boxes within the nodes in the workflow page. I tried it with Chrome (Version 120.0.6099.130) and Edge (Version 120.0.2210.91), Windows 10 Pro 22H2
I cannot take screenshots anymore because meanwhile I downgraded back to v3.4.0post2
