### ISSUE TITLE
[bug]:  new theme  ui color of  hurts eyes

### ISSUE THREAD

**Issue by wolfkingal2000** [invoke-ai/InvokeAI#5377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

15

### What version did you experience this issue on?

v3.6.0rc1

### What happened?
new theme ui color of hurts eyes , it is good to change the color as before or add an option that has the previous theme as well.

**Comment by MarcoBlumenthal** [comment]
especially the yellow of the invoke button appears extremely aggressive

**Comment by Void2258** [comment]
I have to agree after using it for a few days. I am generally a dark-mode user and the bright yellow/green is unpleasent for me, especially when the rest of the interface is effectively in dark mode (uncomfortably high contrast).

**Comment by sammcj** [comment]
Yeah the yellow and green are pretty brutal, feels like I'm having an energy drink advertised to me each time I see them!

**Comment by Millu** [comment]
Going to close this one as it's going to be Invoke dayglow for the foreseeable future :) 

The feedback is appreciated though!
