### ISSUE TITLE
[bug]: no "invoke"-button in workflow page if sidebar is collapsed

### ISSUE THREAD

**Issue by MarcoBlumenthal** [invoke-ai/InvokeAI#5378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

3.6.0rc1

### What happened?

up to version 3.5.x, a "invoke" button was accessible on the left side of the workflow page, if the side bar was collapsed.
in 3.6.0rc1, there is no such button, the side bar needs to be opened to start generations

### Contact Details

marco.blumenthal@gmx.de

**Comment by psychedelicious** [comment]
You can use Ctrl/Cmd + Enter to start a generation when the panel is collapsed.

**Comment by psychedelicious** [comment]
The buttons have been restored thanks to user feedback
