### ISSUE TITLE
[bug]: "Invoke" and "Show options" hotkeys no longer work

### ISSUE THREAD

**Issue by lstein** [invoke-ai/InvokeAI#5379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

5.3.1

### What happened?

Since upgrading to 3.5.1 the "ctrl-enter" hotkey no longer starts a generation, and the "o" hotkey does not open or close the options panel.

### Additional context

Observed on Linux Chrome and Firefox. The gallery keys, including "g", are still working.

**Comment by Millu** [comment]
Couple of other hotkeys not working either: 

- Ctrl+Enter / Cmd + Enter
- O
- Shift+X
- Alt+A
- 1-5 (to switch tabs)
