### ISSUE TITLE
[bug]: prompt text fields in "text-to-image", "image-to-image" and "unified canvas" pages cannot be resized.

### ISSUE THREAD

**Issue by MarcoBlumenthal** [invoke-ai/InvokeAI#5380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

3.6.0rc1

### What happened?

The prompt text fields in the "text-to-image", "image-to-image" and "unified canvas" pages appear without resize handle in the lower right corner and thus cannot be resized anymore.

please consider to add a scrollbar, too.

### Contact Details

marco.blumenthal@gmx.de

**Comment by psychedelicious** [comment]
The prompt boxes auto-resize now.

https://github.com/invoke-ai/InvokeAI/assets/4822129/7c26f193-301c-4cd2-8c68-906189de5a0e

**Comment by MarcoBlumenthal** [comment]
ok, i did not recognize this, but nevertheless this is a degradation compared to previous versions, in which it was possible to stretch the field vertically such that the complete prompt text was visible. now, the text field grows, but after a couple of lines it stops growing and don't show the complete text anymore. And it has no scrollbar for convenient text positioning.
