### ISSUE TITLE
[bug]: in workflow page: lora nodes: it's impossible to enter negative values for the weight

### ISSUE THREAD

**Issue by MarcoBlumenthal** [invoke-ai/InvokeAI#5383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

3.6.0rc1

### What happened?

it's impossible to enter negative value for the weight in Lora nodes

### Contact Details

marco.blumenthal@gmx.de

**Comment by Millu** [comment]
Noted!
