### ISSUE TITLE
[enhancement]: Remember what the user had open when switching between linear views/canvas/workflows

### ISSUE THREAD

**Issue by JPPhoto** [invoke-ai/InvokeAI#5397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

InvokeAI currently resets all opened advanced options when going between linear views, workflows, and canvas. It would be great if it could recall what was opened and return to that state.

Secondarily, it would be great if workflows kept the exact view that it held when going to linear and then back to workflows.

**Comment by Millu** [comment]
Handled as of 3.6.0!

**Comment by psychedelicious** [comment]
This isn't implemented yet

**Comment by skunkworxdark** [comment]
I agree with the sentiment of 

> Secondarily, it would be great if workflows kept the exact view that it held when going to linear and then back to workflows.

**Comment by psychedelicious** [comment]
This is implemented now

**Comment by psychedelicious** [comment]
@JPPhoto 
Yes please, I think I misunderstood that part of the issue - not sure what exactly you mean by "view". Pls add a bit more detail in a few ticket

**Comment by JPPhoto** [comment]
> @JPPhoto Yes please, I think I misunderstood that part of the issue - not sure what exactly you mean by "view". Pls add a bit more detail in a few ticket

See #5657!
