### ISSUE TITLE
[enhancement]: keyboard shortcuts to select/delete images

### ISSUE THREAD

**Issue by MylesCroft** [invoke-ai/InvokeAI#5429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Feedback for the UI: you can select all images with shift + mouse click only but you can only batch delete by right clicking on the image(s) then select delete. The delete key (not backspace) is not recognised nor is ctrl + a to select all images (or cmd in OS X presumably).

### Additional Content

This is  best tied into a confirmatory message preventing mass deletion or move images to a dummy 'delete' gallery to replicate a recycle bin which can have an auto-delete period set by end use.

**Comment by ChrisTop700** [comment]
I totally need this feature. I can't seem to learn that delete key doesn't delete the selection but only deletes the single image.

**Comment by psychedelicious** [comment]
Related: 
- https://github.com/invoke-ai/InvokeAI/issues/4885
- https://github.com/invoke-ai/InvokeAI/issues/4543

Making the delete key delete the full selection should be pretty straightforward. Good first issue for a frontend contributor.

If you want to take this issue and need any guidance, I'm happy to help.
