### ISSUE TITLE
Allow CLI like input from web interface

### ISSUE THREAD

**Issue by SMUsamaShah** [invoke-ai/InvokeAI#543]
**Is your feature request related to a problem? Please describe.**
Currently can not just copy paste the command from log file or other place in web interface

**Describe the solution you'd like**
Ideally a checkbox which let us write the command in the same format as CLI. Marking this checkbox can disable other dropdowns. We can keep browse image enabled.

As an added benefit, this will allow having any new functionality immediately available in webui without any modification.

**Describe alternatives you've considered**

**Additional context**
It should allow something like this
![image](https://user-images.githubusercontent.com/385283/189947691-cab3fca8-83dd-4e76-b264-fb3253f8a18b.png)

**Comment by TemmieDola** [comment]
absolutely agree. When I used the web interface I liked everything except there is no --grid and --upscale I can't add them myself because I don't understand how the program interacts in html
