### ISSUE TITLE
img2img -v parameter must be 0 or 1?

### ISSUE THREAD

**Issue by BrentOzar** [invoke-ai/InvokeAI#544]
**Describe your environment**
- GPU: mps
- CPU arch: arm
- OS: macOS
- Python: miniconda
- Branch: development

**Describe the bug**
The documentation here: https://github.com/lstein/stable-diffusion/blob/development/docs/features/IMG2IMG.md

Says "You may also pass a -v<count> option to generate count variants on the original image."

But when I pass in -v2, I get:

`-v --variation_amount must be in [0.0, 1.0]`

The source code of dream.py has this:

```
    parser.add_argument(
        '-v',
        '--variation_amount',
        default=0.0,
        type=float,
        help='If > 0, generates variations on the initial seed instead of random seeds per iteration. Must be between 0 and 1. Higher values will be more different.'
    )
```

So I'm guessing the documentation is wrong? If that's the case, I don't mind correcting the docs to say that only 1 variation can be produced, but something seems odd here, like it isn't a doc thing.

**Expected behavior**
To either be able to pass in 2 variations, or have the documentation say only 1 variation can be done.

**Comment by RobertBolender** [comment]
It must be a float in the range of >= 0.0 to <= 1.0, 2.0 is too high.

**Comment by BrentOzar** [comment]
> It must be a float in the range of >= 0.0 to <= 1.0, 2.0 is too high. 0.2, 0.5 would be acceptable examples.

I might be a little slow on the uptake, but can you describe to me how you can generate 0.5 variants of an image?

The documentation linked above says ""You may also pass a -v option to generate count variants on the original image." Do I misunderstand what the word "variants" means there? Variants sounds like a plural, but your reply makes it sound like we're generating *a variant*, singular.

**Comment by RobertBolender** [comment]
> The documentation linked above says ""You may also pass a -v option to generate count variants on the original image."

That does appear to be incorrect/misleading, I think this is what was intended?

https://github.com/lstein/stable-diffusion/pull/551
