### ISSUE TITLE
[enhancement]: Ctrl Scroll Up/Down to increase/decrease the size of the brush

### ISSUE THREAD

**Issue by suonnon** [invoke-ai/InvokeAI#5443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I think using Ctrl (or Commnand on Mac) + Scroll Up/Down to increase/decrease the size of the brush would help user work faster when using the Unified Canvas, instead of using '[' or ']'

**Comment by rohinish404** [comment]
Can i take it up?
