### ISSUE TITLE
Compatible models?

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#545]
Greetings,

Is there a reference list that as been put together for compatible models to be used with this repo?

**Comment by Neosettler** [comment]
Thank you Tingin, 

Yes, I just found out from another post that there is more models being trained that focus on different things, like this one:
https://huggingface.co/hakurei/waifu-diffusion

I think it would be nice to make so kind of repertoire.

**Comment by Neosettler** [comment]
It would be interesting to find a model that aims for an artistic style like midjourney.

**Comment by n00mkrad** [comment]
> It would be interesting to find a model that aims for an artistic style like midjourney.

Then train one :)

**Comment by Neosettler** [comment]
Hell yeah, seems like a very good challenge!
