### ISSUE TITLE
[enhancement]: Asset Upload should switch to Assets Tab

### ISSUE THREAD

**Issue by hipsterusername** [invoke-ai/InvokeAI#5455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

When uploading an asset to the studio, the Assets tab should be navigated and the uploaded image brought into focus

### Alternatives

Alternatively, user could be prompted with an action to navigate to the image in the "Image upload successful" toast

**Comment by maryhipp** [comment]
Not sure when exactly but this is now implemented
