### ISSUE TITLE
[bug]: Double Right Clicking on image in Image Viewer breaks the context menu

### ISSUE THREAD

**Issue by hipsterusername** [invoke-ai/InvokeAI#5457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24gb

### What version did you experience this issue on?

3.6rc5

### What happened?

Right clicking twice on image in image viewer breaks the Context menu (won't show up again without left clicking somewhere)

**Comment by psychedelicious** [comment]
Please make a screen recording

**Comment by hipsterusername** [comment]
https://github.com/invoke-ai/InvokeAI/assets/31807370/891bc7ce-708e-4fe4-8991-f33bbd3dda1d

It's minor, has workaround. Just logging for sake of capturing wonk. 

Firefox.
