### ISSUE TITLE
[enhancement]: Font Size of new UI 3.6.0 is too small. Bad for accessibility.

### ISSUE THREAD

**Issue by SalmanMunawar** [invoke-ai/InvokeAI#5489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

smunawar100@gmail.com

### What should this feature add?

Allow users to change default font size (12px is too small) or change default font size to 14px by default.

**Comment by SalmanMunawar** [comment]
Also icon / button sizes were much more comfortable in the 3.5.1 version, while i love the new dark scheme. due to smaller UI elements like buttons and icons in new version are harder to use. Also not to sure about nested tabs in accordions design. 3.5.1 felt cozy while 3.6.0 seem very compact.

**Comment by hipsterusername** [comment]
For context, are you opposed to using the browsers zoom function?

**Comment by SalmanMunawar** [comment]
This is not a huge issue but On larger 2k, 4k monitors at 100% ui and text looks small. zooming does help but also zooms the artwork, so ui gets clearer but image gets slightly blurry. Again not a big issues. 3.6 looks awesome.
