### ISSUE TITLE
[enhancement]: Models Description pop-up info accessible from main working UI

### ISSUE THREAD

**Issue by Harvester62** [invoke-ai/InvokeAI#5493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I just noticed in v3.6.0 that the informational pop-up message in the Generation properties panel (available in v3.5.1) no longer shows the model's Description text from the Models Manager when you hover over the Model's name. This feature was really helpful in previous versions of the program because it was the only way to see model information in the main working UI (t2i, i2i, canvas) without having to go into the Models Manager.

For instance, I added usage information for all my loaded models in their configuration parameters. This made it easy for me to quickly access setup information and hints for each model by simply hovering the mouse over the model's name in the main working UI. 

Furthermore, because a Description field is available in Models Manager also for LoRAs, it would be useful to have such a informational popup info available for them too.

I hope this convenient feature can be brought back in the future or replaced with something similarly useful. Thank you.

### Additional Content

![model-info1](https://github.com/invoke-ai/InvokeAI/assets/29801031/8e540495-e451-40e1-a7d2-2fdc1f88b7cb)
This shows the previous behavior in v3.5.1 where it uses the model's description text from Models Manager
![model-info2](https://github.com/invoke-ai/InvokeAI/assets/29801031/d96316d1-8489-4fb8-9630-737c85abce1e)

**Comment by Pfannkuchensack** [comment]
i will try to do this.

**Comment by Millu** [comment]
@Pfannkuchensack assigned it to you!

**Comment by Harvester62** [comment]
Hi @Pfannkuchensack , in case it might be useful to you, if you go to the Model Manager (v3.6.0) and hover the mouse on the Model's name in the list of models, an informational pop-up message displays the model's description text.
![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/a22e0266-f58b-4c35-8d23-253354ab4aa8)
That is exactly what is missing from the main workspaces, as described in my report above. So, perhaps, you might reuse some code from there.

**Comment by Pfannkuchensack** [comment]
Thank you, i will look into it at the weekend.

**Comment by Pfannkuchensack** [comment]
#5541 done.
