### ISSUE TITLE
pip reverting to old ver in 3.6 release Why? [bug]: 

### ISSUE THREAD

**Issue by KaligarPrime** [invoke-ai/InvokeAI#5495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.6 .0

### What happened?

I went from 3.5 to 3.6 and this happened

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. 
This behaviour is the source of the following dependency conflicts.
datasets 2.16.1 requires fsspec[http]<=2023.10.0,>=2023.1.0, 
but you have fsspec 2023.12.2 which is incompatible.

### Additional context

If this error is my fault please jusat delete the notation and bug report.

### Contact Details

kaligarprime@gmail.com

**Comment by Millu** [comment]
We'll be working to overhaul the install process - if you don't run into any issues you can ignore this message :)

**Comment by Harvester62** [comment]
Hi @Millu 
Is this bug report still relevant considering that we're on v3.7 and approaching v4.0 release, and the user didn't provide any further feedback after submitting the report?

**Comment by Millu** [comment]
This can be closed. The update process has since changed
