### ISSUE TITLE
[bug]: No Trash Icon For Loras 

### ISSUE THREAD

**Issue by cip300** [invoke-ai/InvokeAI#5496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

3.6.0

### What happened?

No trash icon for loras with long name 

### Screenshots

Exemple : The Dreamyvibes Lora
![image (5)](https://github.com/invoke-ai/InvokeAI/assets/29658728/a77639a1-d468-4e53-a946-545b3559419b)

**Comment by psychedelicious** [comment]
This is resolved in #5538
