### ISSUE TITLE
[bug]: 3.6.0 UI changes feedback - lack of UI hinting/flow, commonly used parameters are harder to find

### ISSUE THREAD

**Issue by sammcj** [invoke-ai/InvokeAI#5504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

24

### What version did you experience this issue on?

3.6.0

### What happened?

Some feedback on 3.6.0's UI changes.

Personally I feel like some of the 3.6.0 UI changes are a bit of a step backwards in terms of usability and flow.

- Commonly used parameters such as the scheduler, steps and cfg scale are now buried within an "advanced" drop down.

I don't see how these are at all advanced, they're very frequently tweaked and tuned depending on your desired outcome and previous attempt iterations.

Having them hidden away means more clicks to get work done and the "advanced" drop downs lack obvious UI hinting and do not always stay opened between browser sessions, clients etc....

- There is a lack of 'hinting' in the UI (colour/flow), this seems worse or perhaps is just more obvious with the UI changes in 3.6.0.

Section titles, Option titles, parameter names, input fields and drop down boxes all have the same styling. This means as a user your eyes aren't naturally drawn to specific areas of the UI which helps to create a sense of "flow" when using an application.

I've annotated a screenshot below which hopefully makes sense 😅.

To be clear, I'm not having a whinge - I really appreciate everything InvokeAI has brought to the table. This is purely intended as constructive feedback.

### Screenshots

![SCR-20240114-iwfh-3](https://github.com/invoke-ai/InvokeAI/assets/862951/ceda96b7-dd27-40e0-9dac-7583db18ae51)

![image](https://github.com/invoke-ai/InvokeAI/assets/862951/9fc5e1f4-7df1-45dd-881e-d26ab1771bab)

**Comment by ufuksarp** [comment]
I agree. New UI needs more contrast. It's the same gray everywhere without any real shading.

**Comment by ufuksarp** [comment]
I agree. New UI needs more contrast. It's too similar grays everywhere without any real shading.

**Comment by sammcj** [comment]
3.6.2 doesn't appear to have resolved many (any?) of the UI issues.

For example, after selecting "use all" or "use seed" from an image - the seed is still buried (missing / hidden) in the parameters:

<img width="506" alt="image" src="https://github.com/invoke-ai/InvokeAI/assets/862951/7de9f5a6-a14b-49cd-9267-20c3ae74f91d">

**Comment by psychedelicious** [comment]
Sorry for the lack of response here. Appreciate the feedback @sammcj (which has been largely echoed by many users). It's clear we need to do another pass at the UI.

> Having them hidden away means more clicks to get work done and the "advanced" drop downs lack obvious UI hinting and do not always stay opened between browser sessions, clients etc....

We've fixed the not-staying open issue, I think it's not released yet. The accordions and expanders state is persisted across reloads (and tab switches).

**Comment by Harvester62** [comment]
Is this "bug report" still relevant after almost one year of development and UI changes, and more than 27 releases of Invoke? Perhaps, the user might verify with a current version of Invoke if any of the things he highlighted are still relevant today.
