### ISSUE TITLE
[bug]: UI Displays `{"detail":"Not Found"}` after upgrading to 3.6.x

### ISSUE THREAD

**Issue by Millu** [invoke-ai/InvokeAI#5506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cuda

### What version did you experience this issue on?

3.6.0

### What happened?

After upgrading to 3.6.0 via the updater script from invoke.sh or invoke.bat, the UI displays and error: `{"detail":"Not Found"}`

<img width="506" alt="Screenshot 2024-01-14 at 2 41 09 PM" src="https://github.com/invoke-ai/InvokeAI/assets/7254508/48ce29b7-5da5-4d66-9035-7f5eedfc1815">

### Contact Details

millun@invoke.ai

**Comment by Millu** [comment]
To fix this error, open the developer console from the invoke.bat / invoke.sh  menu and run: `pip install --use-pep517 --upgrade  --force-reinstall InvokeAI==v3.6.0` 


This is due to the removal of the frontend build from the repo, and modifying the way the updater script functions.

**Comment by Harvester62** [comment]
Is this still a relevant bug report to keep it open?

**Comment by Millu** [comment]
@Harvester62 nope, we should be able to close it!
