### ISSUE TITLE
[enhancement]: Control/resize mode for IP and T2I adapters

### ISSUE THREAD

**Issue by aolko** [invoke-ai/InvokeAI#5511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Can we have control/resize mode options for IP/T2I adapters?
![image](https://github.com/invoke-ai/InvokeAI/assets/581458/15577ecf-b0f5-47fb-8d3c-0569b6b6183f)

**Comment by Millu** [comment]
T2I Adapters have resize settings, and IP-Adapters don't need them as the concepts in the image are important, not the image itself.

**Comment by aolko** [comment]
What if i want to lower/increase the control while retaining the weight?
