### ISSUE TITLE
[bug]: Left/Right arrow losing context

### ISSUE THREAD

**Issue by erwin1234777** [invoke-ai/InvokeAI#5521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8gb

### What version did you experience this issue on?

3.6.0

### What happened?

Pressing left/right arrow ends up going through both inpainting and gallery at the same time. This also happens with the tabs (nodes, canvas, etc, the left most icons). Default behavior in canvas should be to target the inpainting (bottom) one if theres any, if not default, to gallery.

### Screenshots

https://github.com/invoke-ai/InvokeAI/assets/29512349/33a30ffa-be9d-4db0-8f6c-577142ae5965

### Additional context

Reproducing steps:
- create 5 items in gallery/assets 
- go to canvas
- inpaint one item with 10 iterations
- use left/right arrow after its done
- notice it goes to next/previous image in both gallery and canvas

Small quirk but can be an annoyance, case being: generating 100 images in canvas, when going through them, generally you'd use right arrow, which in turn will keep loading more and more images on the gallery, increasing mem usage on browser for no good reason caching those images

### Contact Details

discord: home.depot

**Comment by psychedelicious** [comment]
I *think* this could be fairly easily solved by adding some constraints to the gallery navigation hotkeys, disabling them if the active tab is canvas and we are staging images. There are redux selectors for both of these booleans.

**Comment by codedealer** [comment]
@psychedelicious 👋 I'd like to take it
