### ISSUE TITLE
[bug]: png_compress_level variable in the config service has no effect on image compression level

### ISSUE THREAD

**Issue by omer-bar** [invoke-ai/InvokeAI#5529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

3.6.0

### What happened?

I'm doing some work on the upload process and while testing the code I noticed that the save method of PIL takes a long time to save a new image so I tested a change of the compress_level variable coming from the configuration service, the value is called 'png_compress_level' and its between 0 and 9. I found out that changing this value doesn't affect the compression level of PIL, only hardcoding it does.

"invokeai/app/services/image_files/image_files_disk.py"
`image.save(
image_path,
"PNG",
pnginfo=pnginfo,
compress_level=self.__invoker.services.configuration.png_compress_level,
)`
            
"invokeai/app/services/config/config_default.py"
`png_compress_level  : int = Field(default=6, description="The compress_level setting of PIL.Image.save(), used for PNG encoding. All settings are lossless. 0 = fastest, largest filesize, 9 = slowest, smallest filesize", json_schema_extra=Categories.Generation)
`

**Comment by psychedelicious** [comment]
I think you have a problem with your local configuration. This definitely works.

Please either run app in a python debugger and set a breakpoint when saving to inspect the value coming from the config (or just print it). I imagine you'll find that it is the default 6 and not whatever you have set to the config.

Your PR for multiple image uploads appears to have an invoke root dir (your user data) in the repo itself (and a lot non-codebase files are committed in that PR). The root dir should be in a separate folder, not in the repo hierarchy. Probably you are setting the config in the wrong yaml file.

**Comment by omer-bar** [comment]
> I think you have a problem with your local configuration. This definitely works. To double check, I tried setting it to 0 and 3 and uploading the same image. I get a 23mb image w/ 0, and a <1mb image with 3.
> 
> Please either run app in a python debugger and set a breakpoint when saving to inspect the value coming from the config (or just print it). I imagine you'll find that it is the default 6 and not whatever you have set to the config.
> 
> Your PR for multiple image uploads appears to have an invoke root dir (your user data) in the repo itself (and a lot non-codebase files are committed in that PR). The root dir should be in a separate folder, not in the repo hierarchy. Probably you are setting the config in the wrong yaml file.

cant reproduce it now and you are correct it is working for me now so I'm closing this bug.
As for the PR - fixed.
