### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by klement** [invoke-ai/InvokeAI#5533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cuda

### What version did you experience this issue on?

3.6.0

### What happened?

On Safari interface shows stuff like accordions.image.title instead of proper UI image. Doesn't seem to manifest in Firefox or Chrome. Manifests on both clean 3.6.0 install and upgrade to 3.6.0. from 3.5.0. I cleaned cookies and that didn't help.

### Screenshots

<img width="488" alt="Screenshot 2024-01-19 at 20 12 13" src="https://github.com/invoke-ai/InvokeAI/assets/1701853/f3f2b75c-8e24-4856-a271-f5ae588ed72b">

**Comment by klement** [comment]
I tried Safari-Privaci-Manage website data-cleared everything (all hosts). Are you aware of some other place where this needs to be done?

**Comment by Millu** [comment]
Try this: https://superuser.com/questions/236558/how-to-clear-all-html5-local-storage-from-safari

**Comment by klement** [comment]
Interesting!

Doing localStorage.clear() in javascript console for invoke-ai window did the trick.

Thanks.
