### ISSUE TITLE
[bug]: The LoRA node will not select LoRAs if the filename ends in a space

### ISSUE THREAD

**Issue by TheCulprit** [invoke-ai/InvokeAI#5556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.6.0

### What happened?

If a LoRA filename ends in a space the LoRA node will not select it when clicked and the dropdown menu shows the red border and placeholder text.
This problem also shows in the workflow linear view but not in the t2i/i2i/canvas tabs.

### Contact Details

Stretch (villainstretch) on Discord

**Comment by Millu** [comment]
@psychedelicious will this be fixed by the new selector component?
