### ISSUE TITLE
A nice feature to make it more user friendly! :) To edit the WEBUI's colors! Not so important!!!!     Update Added Draft files!!!

### ISSUE THREAD

**Issue by alfi4000** [invoke-ai/InvokeAI#5561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Description:
I have got the idea to make it possible to edit the color of all buttons and background of each page to make it more customizable for end users! That would a nice feature not necessary but nice feature!

QA Instructions, Screenshots, Recordings:

Please provide steps on how to test changes, any hardware or 
software specifications as well as any other pertinent information. 

A new settings page where is descripted wich buttons color will be changed and wich pages background.

 Alternatives

Example merge plans:
- "Check if it is possible instead of set color for each button a python function to connect the setup page with the color function on the webui"
- "Test phase"
- "Check Quality and if it works in any situation right without performance issues"
- "Release"

 Additional Content

What type of PR is this? (check all applicable)

- [ no] Refactor
- [yes ] Feature
- [ no] Bug Fix
- [ maybe] Optimization
- [maybe ] Documentation Update
- [ maybe] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [ ] No, because: I don't know how

      
## Have you updated all relevant documentation?
- [ ] No

**Comment by alfi4000** [comment]
Here some drafts my painting skills are bad!!!:  
[Prototype 1.pdf](https://github.com/invoke-ai/InvokeAI/files/14045912/Prototype.1.pdf)
[Prototype 2.pdf](https://github.com/invoke-ai/InvokeAI/files/14045913/Prototype.2.pdf)
[Prototype 3.pdf](https://github.com/invoke-ai/InvokeAI/files/14045914/Prototype.3.pdf)

**Comment by alfi4000** [comment]
(https://github.com/invoke-ai/InvokeAI/files/14045915/Prototype.1.pdf)

**Comment by alfi4000** [comment]
![Prototype 1](https://github.com/invoke-ai/InvokeAI/assets/149228038/16c90f52-36fb-4aaf-95b5-61ec82863cd2)
![Prototype 2](https://github.com/invoke-ai/InvokeAI/assets/149228038/62e3ef42-281e-4b1a-8e89-703f022e465f)
![Prototype 3](https://github.com/invoke-ai/InvokeAI/assets/149228038/bda72e25-e399-4f43-9d96-4d5dc467b6ab)

**Comment by alfi4000** [comment]
Here are some draft files of my idea it might be give a idea of what I am meaning!

**Comment by psychedelicious** [comment]
Hi, thanks for the feature request. We don't plan to implement this. 

There are browser extensions that can do this kind of customization for you. 

I suggest [stylus](https://github.com/openstyles/stylus/) as an actively maintained and very feature-rich extension. You can create and share style overrides with it.

**Comment by psychedelicious** [comment]
Hi, thanks for the feature request. We don't plan to implement this. 

There are browser extensions that can do this kind of customization for you. 

I suggest [stylus](https://github.com/openstyles/stylus/) as an actively maintained and very feature-rich extension. You can create and share style overrides with it.
