### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by Unfortunatetoaster** [invoke-ai/InvokeAI#5569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8gb

### What version did you experience this issue on?

Any

### What happened?

Traceback (most recent call last):
  File "E:\InvokeAI\lib\main.py", line 52, in <module>
    inst.install(**args.__dict__)
  File "E:\InvokeAI\lib\installer.py", line 173, in install
    self.instance.install(
  File "E:\InvokeAI\lib\installer.py", line 226, in install
    self.install_torch(extra_index_url, find_links)
  File "E:\InvokeAI\lib\installer.py", line 241, in install_torch
    pip[
  File "C:\Users\Lloyd\AppData\Local\Temp\invokeai-installer-tmpe5ihxsbp\Lib\site-packages\plumbum\commands\modifiers.py", line 145, in __rand__
    cmd(
  File "C:\Users\Lloyd\AppData\Local\Temp\invokeai-installer-tmpe5ihxsbp\Lib\site-packages\plumbum\commands\base.py", line 113, in __call__
    return self.run(args, **kwargs)[1]
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lloyd\AppData\Local\Temp\invokeai-installer-tmpe5ihxsbp\Lib\site-packages\plumbum\commands\base.py", line 252, in run
    return p.run()
           ^^^^^^^
  File "C:\Users\Lloyd\AppData\Local\Temp\invokeai-installer-tmpe5ihxsbp\Lib\site-packages\plumbum\commands\base.py", line 215, in runner
    return run_proc(p, retcode, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lloyd\AppData\Local\Temp\invokeai-installer-tmpe5ihxsbp\Lib\site-packages\plumbum\commands\processes.py", line 299, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lloyd\AppData\Local\Temp\invokeai-installer-tmpe5ihxsbp\Lib\site-packages\plumbum\commands\processes.py", line 17, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "C:\Users\Lloyd\AppData\Local\Temp\invokeai-installer-tmpe5ihxsbp\Lib\site-packages\plumbum\machines\base.py", line 27, in verify
    raise ProcessExecutionError(
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 2
Command line: | 'E:\InvokeAI\.venv\Scripts\pip.exe' install --require-virtualenv numpy==1.26.3 'urllib3~=1.26.0' 'requests~=2.28.0' torch==2.1.2 torchmetrics==0.11.4 torchvision==0.16.2 --force-reinstall --extra-index-url https://download.pytorch.org/whl/cu121
Press any key to continue . . .

### Additional context

Had Invokeai installed for quite some time, couldn't update, so opted to remove it and reinstall entirely, attempted to use different python versions, attempted to run as admin, dunno what else to do.

### Contact Details

lloyd.ingram1996@gmail.com

**Comment by Millu** [comment]
What python version are you using?

**Comment by Unfortunatetoaster** [comment]
I tried both 3.10 and 3.11.

**Comment by Millu** [comment]
Wondering if your virtual environment is using a different version of Python somehow - could you try activating it with `source venv/bin/activate` and then run `python --version`?

The other solution I'd suggest is a manual install: https://invoke-ai.github.io/InvokeAI/installation/020_INSTALL_MANUAL/#installation-walkthrough

**Comment by Unfortunatetoaster** [comment]
I don't have a bin folder in the .venv file that gets made, but activate is
right in there.
I get this in cmd when running the command.
python --version
Python 3.11.7

**Comment by Unfortunatetoaster** [comment]
Attempted to use the manual install as well, but it says the line with
xformers is incorrect.

**Comment by Millu** [comment]
Could you share the error?

**Comment by Unfortunatetoaster** [comment]
ERROR: Invalid requirement: 'invokeai{xformers}' is the manual install
error, I also attempted downloading the 3.6.2 last night and trying that as
well, still no results beyond the error code. I've noticed it says
something about netcode and timing out, do you think it may be because I
have satellite internet and live out in the boonies?

**Comment by Unfortunatetoaster** [comment]
Checking in on the thread, any further information you could possibly give? It starts downloading pytorch and gets to around 5 percent then gives me the netcode error.

**Comment by Unfortunatetoaster** [comment]
Alright, so made some progress just now, the download doesn't specify which version of Python 10 is needed and also says 11 is okay, but 11 does not support pytorch from my limited knowledge, according to the auto1111 github only 10.6 supports pytorch. However though I did get further I still got a failure. 

 File "E:\InvokeAI\InvokeAI-Installer\lib\main.py", line 52, in <module>
    inst.install(**args.__dict__)
  File "E:\InvokeAI\InvokeAI-Installer\lib\installer.py", line 173, in install
    self.instance.install(
  File "E:\InvokeAI\InvokeAI-Installer\lib\installer.py", line 229, in install
    self.install_app(extra_index_url, optional_modules, find_links)
  File "E:\InvokeAI\InvokeAI-Installer\lib\installer.py", line 308, in install_app
    pip[
  File "C:\Users\-\AppData\Local\Temp\invokeai-installer-tmpmpsmkmks\Lib\site-packages\plumbum\commands\modifiers.py", line 145, in __rand__
    cmd(
  File "C:\Users\Lloyd\AppData\Local\Temp\invokeai-installer-tmpmpsmkmks\Lib\site-packages\plumbum\commands\base.py", line 113, in __call__
    return self.run(args, **kwargs)[1]
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\AppData\Local\Temp\invokeai-installer-tmpmpsmkmks\Lib\site-packages\plumbum\commands\base.py", line 252, in run
    return p.run()
           ^^^^^^^
  File "C:\Users\-\AppData\Local\Temp\invokeai-installer-tmpmpsmkmks\Lib\site-packages\plumbum\commands\base.py", line 215, in runner
    return run_proc(p, retcode, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\AppData\Local\Temp\invokeai-installer-tmpmpsmkmks\Lib\site-packages\plumbum\commands\processes.py", line 299, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\AppData\Local\Temp\invokeai-installer-tmpmpsmkmks\Lib\site-packages\plumbum\commands\processes.py", line 17, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "C:\Users\-\AppData\Local\Temp\invokeai-installer-tmpmpsmkmks\Lib\site-packages\plumbum\machines\base.py", line 27, in verify
    raise ProcessExecutionError(
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 2
Command line: | 'E:\InvokeAI\.venv\Scripts\pip.exe' install --require-virtualenv --use-pep517 'E:\InvokeAI\InvokeAI-Installer\lib\InvokeAI-3.6.2-py3-none-any.whl[onnx]'
Press any key to continue . . .

**Comment by Millu** [comment]
Alas it might be due to the internet connection - both Python 3.10 & 3.11 support PyTorch 2.0, not sure why the A111 repo says that

**Comment by ebr** [comment]
Reading this thread, the latest messages indeed point to the internet connection instability, because strange intermittent failures keep happening in the `pip` internals.

however these also caught my eye:
```ERROR: Invalid requirement: 'invokeai{xformers}' is the manual install```

this has curly braces around `xformers`, but it needs to be in square brackets.

we see `File "C:\Users\Lloyd\AppData\` in some log lines, and `File "C:\Users-\AppData\` in others. Also there's `E:\InvokeAI.venv\Lib\site-packages\` - `InvokeAI.venv` is really weird here.

a lot going on here. @Unfortunatetoaster could you please try either the manual or automated installs again (or both), and attach the entire log output, **including** the commands you typed and directory paths you selected during installation? Screenshots or video would be even better, if you're able.

Thank you for helping us troubleshoot this!

**Comment by Unfortunatetoaster** [comment]
Sure thing, I messed up and included my user name in some of them, so I
attempted to remove it for others for standard internet paranoia reasons
lol, I didn't realize it slipped through in some. Whatever though lol,
here's the logs unedited.

Please select the destination directory for the installation:
[C:\Users\Lloyd]:
>>> e:\InvokeAI

❗ Directory E:\InvokeAI already exists ❗
🛑 (re)install in this location? [y/n] (n): y

───────────────────────────────────────── 👾 GPU (Graphics Card) selection
👾 ─────────────────────────────────────────


  Detected the Windows-AMD64 platform

  See https://invoke-ai.github.io/InvokeAI/#system to ensure your system
meets the minimum requirements.

  🠶  Your GPU drivers must be correctly installed before using InvokeAI!
🠴

  Please select the type of GPU installed in your computer.

    1 🢒 an NVIDIA GPU (using CUDA™)

    2 🢒 an NVIDIA GPU (using CUDA™, and DirectML™ for ONNX) -- ALPHA

    3 🢒 no compatible GPU, or specifically prefer to use the CPU

    4 🢒 I'm not sure what to choose




Please make your selection: 1

Looking in indexes: https://pypi.org/simple,
https://download.pytorch.org/whl/cu121
Collecting numpy==1.26.3
  Downloading
https://download.pytorch.org/whl/numpy-1.26.3-cp310-cp310-win_amd64.whl
(15.8 MB)
     ---------------------------------------- 15.8/15.8 MB 184.1 kB/s eta
0:00:00
Collecting urllib3~=1.26.0
  Using cached urllib3-1.26.18-py2.py3-none-any.whl (143 kB)
Collecting requests~=2.28.0
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting torch==2.1.2
  Downloading
https://download.pytorch.org/whl/cu121/torch-2.1.2%2Bcu121-cp310-cp310-win_amd64.whl
(2473.9 MB)
      --------------------------------------- 0.0/2.5 GB 217.4 kB/s eta
3:06:35
ERROR: Exception:
Traceback (most recent call last):
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_vendor\urllib3\response.py", line
435, in _error_catcher
    yield
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_vendor\urllib3\response.py", line
516, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py",
line 90, in read
    data = self.__fp.read(amt)
  File
"C:\Users\Lloyd\AppData\Local\Programs\Python\Python310\lib\http\client.py",
line 465, in read
    s = self.fp.read(amt)
  File
"C:\Users\Lloyd\AppData\Local\Programs\Python\Python310\lib\socket.py",
line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Lloyd\AppData\Local\Programs\Python\Python310\lib\ssl.py",
line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Lloyd\AppData\Local\Programs\Python\Python310\lib\ssl.py",
line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_internal\cli\base_command.py",
line 167, in exc_logging_wrapper
    status = run_func(*args)
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_internal\cli\req_command.py",
line 247, in wrapper
    return func(self, options, args)
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_internal\commands\install.py",
line 369, in run
    requirement_set = resolver.resolve(
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py",
line 92, in resolve
    result = self._result = resolver.resolve(
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py",
line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py",
line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py",
line 172, in _add_to_criteria
    if not criterion.candidates:
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_vendor\resolvelib\structs.py",
line 151, in __bool__
    return bool(self._sequence)
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py",
line 155, in __bool__
    return any(self)
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py",
line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py",
line 47, in _iter_built
    candidate = func()
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py",
line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py",
line 297, in __init__
    super().__init__(
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py",
line 162, in __init__
    self.dist = self._prepare()
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py",
line 231, in _prepare
    dist = self._prepare_distribution()
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py",
line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq,
parallel_builds=True)
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_internal\operations\prepare.py",
line 438, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_internal\operations\prepare.py",
line 483, in _prepare_linked_requirement
    local_file = unpack_url(
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_internal\operations\prepare.py",
line 165, in unpack_url
    file = get_http_url(
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_internal\operations\prepare.py",
line 106, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_internal\network\download.py",
line 147, in __call__
    for chunk in chunks:
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_internal\cli\progress_bars.py",
line 53, in _rich_progress_bar
    for chunk in iterable:
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_internal\network\utils.py", line
63, in response_chunks
    for chunk in response.raw.stream(
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_vendor\urllib3\response.py", line
573, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_vendor\urllib3\response.py", line
509, in read
    with self._error_catcher():
  File
"C:\Users\Lloyd\AppData\Local\Programs\Python\Python310\lib\contextlib.py",
line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File
"E:\InvokeAI\.venv\lib\site-packages\pip\_vendor\urllib3\response.py", line
440, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='
download.pytorch.org', port=443): Read timed out.

[notice] A new release of pip available: 22.2.1 -> 23.3.2
[notice] To update, run: E:\InvokeAI\.venv\Scripts\python.exe -m pip
install --upgrade pip
Traceback (most recent call last):
  File "E:\InvokeAI\InvokeAI-Installer\lib\main.py", line 52, in <module>
    inst.install(**args.__dict__)
  File "E:\InvokeAI\InvokeAI-Installer\lib\installer.py", line 173, in
install
    self.instance.install(
  File "E:\InvokeAI\InvokeAI-Installer\lib\installer.py", line 226, in
install
    self.install_torch(extra_index_url, find_links)
  File "E:\InvokeAI\InvokeAI-Installer\lib\installer.py", line 241, in
install_torch
    pip[
  File
"C:\Users\Lloyd\AppData\Local\Temp\invokeai-installer-tmpqq27th02\Lib\site-packages\plumbum\commands\modifiers.py",
line 145, in __rand__
    cmd(
  File
"C:\Users\Lloyd\AppData\Local\Temp\invokeai-installer-tmpqq27th02\Lib\site-packages\plumbum\commands\base.py",
line 113, in __call__
    return self.run(args, **kwargs)[1]
  File
"C:\Users\Lloyd\AppData\Local\Temp\invokeai-installer-tmpqq27th02\Lib\site-packages\plumbum\commands\base.py",
line 252, in run
    return p.run()
  File
"C:\Users\Lloyd\AppData\Local\Temp\invokeai-installer-tmpqq27th02\Lib\site-packages\plumbum\commands\base.py",
line 215, in runner
    return run_proc(p, retcode, timeout)
  File
"C:\Users\Lloyd\AppData\Local\Temp\invokeai-installer-tmpqq27th02\Lib\site-packages\plumbum\commands\processes.py",
line 299, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File
"C:\Users\Lloyd\AppData\Local\Temp\invokeai-installer-tmpqq27th02\Lib\site-packages\plumbum\commands\processes.py",
line 17, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File
"C:\Users\Lloyd\AppData\Local\Temp\invokeai-installer-tmpqq27th02\Lib\site-packages\plumbum\machines\base.py",
line 27, in verify
    raise ProcessExecutionError(
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 2
Command line: | 'E:\InvokeAI\.venv\Scripts\pip.exe' install
--require-virtualenv numpy==1.26.3 'urllib3~=1.26.0' 'requests~=2.28.0'
torch==2.1.2 torchmetrics==0.11.4 torchvision==0.16.2 --force-reinstall
--extra-index-url https://download.pytorch.org/whl/cu121
Press any key to continue . . .

**Comment by SimonLuoshiping** [comment]
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    torch==2.1.2 from https://download.pytorch.org/whl/cu121/torch-2.1.2%2Bcu121-cp310-cp310-win_amd64.whl#sha256=9925143dece0e63c5404a72d59eb668ef78795418e96b576f94d75dcea6030b9:
        Expected sha256 9925143dece0e63c5404a72d59eb668ef78795418e96b576f94d75dcea6030b9
             Got        9237a65b51221bdd0e8dccf3425a9c5cbe9f6fdc1c30494718abf611c1b4c114

**Comment by graz68a** [comment]
Similar issue here , I have Python 3.12 and followed all 3 pre-installation points 

***** Checking and Updating Python *****
Initializing the installer. This may take a minute - please wait...
Traceback (most recent call last):
  File "E:\InvokeAI-installer-v3.6.2\InvokeAI-Installer\lib\main.py", line 49, in <module>
    inst = Installer()
           ^^^^^^^^^^^
  File "E:\InvokeAI-installer-v3.6.2\InvokeAI-Installer\lib\installer.py", line 43, in __init__
    self.bootstrap()
  File "E:\InvokeAI-installer-v3.6.2\InvokeAI-Installer\lib\installer.py", line 98, in bootstrap
    res = subprocess.check_output(cmd).decode()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5]

**Comment by ebr** [comment]
@graz68a your problem is Python 3.12. Invoke only supports up to and including 3.11.

**Comment by ebr** [comment]
@Unfortunatetoaster a similar issue came up in Discord recently, and the cause turned out to be the antivirus blocking download if some python package. Maybe try disabling your antivirus at installation time? As sketchy as that sounds, false positives are often a real problem.

**Comment by Unfortunatetoaster** [comment]
I think I stated earlier, but I already resolved my issue by using my
mobile Hotspot instead of the internet here, thank you anyways though.

**Comment by ebr** [comment]
Ah, must have missed that. Glad you got it working.

**Comment by graz68a** [comment]
in my case it was Avast antivirus blocking pip.exe !
