### ISSUE TITLE
base64 image

### ISSUE THREAD

**Issue by svumme** [invoke-ai/InvokeAI#557]
is it possible to load a base64 image?

**Comment by lstein** [comment]
Not at present. Why do you want to?

**Comment by svumme** [comment]
thanks for the reply, i am creating a uxp panel for photoshop and i would like to send and receive images in base64

**Comment by ausbitbank** [comment]
it is possible using the web api's "initimg" property, this is how I deal with image attachments via discord bot https://github.com/ausbitbank/stable-diffusion-discord-bot/blob/main/index.js#L239

**Comment by lstein** [comment]
I need a bit more information:
- Are you saving the base64 image to disk and then using the command-line client?
- Do you want to load the image into the Web GUI?
- Are you making API calls against the web server backend?

Thanks for clarifying.

**Comment by svumme** [comment]
hi, I have created an electron panel, which works both independently with one click and am working on a photoshop panel that connects as a client. I would love to be able to write to you on an email, if you like we could collaborate together. I have the same goal as you of making everything free and I'd like to see if that's possible with licensing. sorry for my english.
![sdiamonds2](https://user-images.githubusercontent.com/71202047/190975099-43ddfbb1-0768-4bea-b840-5449177c6a45.jpg)
![Capture777](https://user-images.githubusercontent.com/71202047/190975189-0c09ecdf-3251-49b2-99ec-3d8e27bf52da.JPG)

**Comment by svumme** [comment]
hello, as I wrote above I have created an electron panel that has the function of server and a panel for photoshop that connects to it. I had thought about sending base 64 images from electron to photoshop. Then I found that the new UXPs don't import base 64 files ... so the image is exported locally and then imported.
the handy thing is that i created an exe to start electron panel, so it can work without any installation. I have little time in this period and I would like to be able to share it with everyone so that we can develop it together if you like the idea. I would have to tweak the code a bit first which is a bit messed up at the moment as I work on it at night after working all day: =).

**Comment by psychedelicious** [comment]
Gotcha - so you have another solution for the base64 request sounds like?

You may want to hop onto discord and check out this conversation, were work is ongoing to make a portal one-click installer for InvokeAI: https://discord.com/channels/1020123559063990373/1029269452207960064

Discord is also a good place to chat about the project and any ideas.

Are you happy to close this GH issue?

**Comment by svumme** [comment]
thanks!

**Comment by psychedelicious** [comment]
No worries, glad InvokeAI is doing some work for you!
