### ISSUE TITLE
[enhancement]: A hotkey that increases/decreases weight of selected text

### ISSUE THREAD

**Issue by MartyMcStarfox** [invoke-ai/InvokeAI#5585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

A hotkey that increases or decreases the weight of selected text in a prompt, like ComfyUI.

**Comment by ufuksarp** [comment]
I think this is going to come with [Prompt Builder](https://github.com/invoke-ai/InvokeAI/issues/4475#issue-1883078508).

**Comment by psychedelicious** [comment]
Yes, thanks @ufuksarp this is part of that feature request. Closing as a duplicate.
