### ISSUE TITLE
[bug]: The "Model" drop down scrolls, but has no scroll bar

### ISSUE THREAD

**Issue by DavidCWGA** [invoke-ai/InvokeAI#5609]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

macOS

### GPU vendor

Apple Silicon (MPS)

### GPU model

M1 Max

### GPU VRAM

32GB

### Version number

3.6.2

### Browser

Safari 17.2

### What happened

I clicked on the "Model" drop-down UI element to change the model, and several of my models were missing. It took me a while to figure out that the list *scrolls*. It has no scroll bar, and I can only scroll it with the mouse wheel. Presumably, if I did not have a mouse wheel, those models would be locked away.

### What you expected to happen

I expect scrolling UI elements to have scroll bars.

### How to reproduce the problem

Install more than 11 models, then click on the "Model" drop-down UI element.

**Comment by psychedelicious** [comment]
There's some bug with the dropdown component - previously reported in #5376

Closing this as a duplicate, will try to fix this week
