### ISSUE TITLE
[bug]: Weblate translation: Some missing keys and some confusing key-title mismatch

### ISSUE THREAD

**Issue by ufuksarp** [invoke-ai/InvokeAI#5610]
### Is there an existing issue for this problem?
- [X] I have searched the existing issues

### Version number
3.6.2

- "Opened" order type in Workflow library has no key.
- Some confusing key-title mismatch with **keys** starting with [toast.problem](https://hosted.weblate.org/translate/invokeai/web-ui/tr/?checksum=29f99dc627a39552&sort_by=-priority,position).
" `toast.problemImportingMaskDesc` Unable to export mask" for example
- [Node Editor?](https://hosted.weblate.org/translate/invokeai/web-ui/tr/?q=node+editor&sort_by=-priority%2Cposition&checksum=) (5 results) Isn't it the same thing as the Workflow Editor? 
- "`hotkeys.closePanels.desc` Closes open panels" and "`hotkeys.closePanels.title` Close Panels" are unused unless changed after 3.6.2.
- "`hotkeys.consoleToggle.desc` Open and close console" and "`hotkeys.consoleToggle.title` Console Toggle" are unused.
- "`hotkeys.pinOptions.desc` Pin the options panel" and "`hotkeys.pinOptions.title` Pin Options" are unused.

### Discord username
ufuksarp

**Comment by hippalectryon-0** [comment]
**Still relevant:**
> Node Editor? (5 results) Isn't it the same thing as the Workflow Editor?

------------

**Obolete:**

> "Opened" order type in Workflow library has no key.

Doesn't exist anymore
> Some confusing key-title mismatch with keys starting with toast.problem.

Not relevant anymore  / already fixed
> "hotkeys.closePanels.desc Closes open panels" and "hotkeys.closePanels.title Close Panels" are unused unless changed after 3.6.2.

Doesn't exist anymore
> "hotkeys.consoleToggle.desc Open and close console" and "hotkeys.consoleToggle.title Console Toggle" are unused.

Doesn't exist anymore
> "hotkeys.pinOptions.desc Pin the options panel" and "hotkeys.pinOptions.title Pin Options" are unused.

Doesn't exist anymore
