### ISSUE TITLE
[bug]: Workflows show as Unsaved when they shouldn't

### ISSUE THREAD

**Issue by clsn** [invoke-ai/InvokeAI#5621]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 3060

### GPU VRAM

12GB

### Version number

3.6.2

### Browser

Firefox 120.0.1

### What happened

In the Workflow Editor, if you save a workflow (`...` menu, Save Workflow), then click on, say, the image-to-text icon, and then immediately back to the Workflow Editor, the title on the top already shows "(Unsaved)" even though you haven't changed anything.

### What you expected to happen

I would expect the "(Unsaved)" message in the title on the top only to appear when something in the Workflow had changed since the last save

### How to reproduce the problem

See above.  Open a workflow, save it, move out of the Workflow Editor and back in.

**Comment by psychedelicious** [comment]
Hi, this should be resolved in the next released. Fixed in #5607
