### ISSUE TITLE
`Generate` argument deprecations prevent absolute path model loading

### ISSUE THREAD

**Issue by carson-katri** [invoke-ai/InvokeAI#563]
The refactors in `generate.py` (e6179af46a75afb5118ba1981da0e6594d910803) deprecated the `weights` and `config` arguments. If a script running outside of the `stable_diffusion` folder uses the `Generate` class, it will try to load from its root not the root of the `stable_diffusion` folder, leading to a broken file path.

For instance, take the following folder structure:
```
- root
  - stable_diffusion (submodule)
  - myscript.py
```
When `myscript.py` uses `Generate`, it will try to load weights from `root/models/ldm/stable-diffusion-v1/model.ckpt` instead of `root/stable_diffusion/models/ldm/stable-diffusion-v1/model.ckpt`.

Is the correct replacement creating a custom `models.yml` file with the correct relative paths?

**Comment by lstein** [comment]
The right thing to do is to pass the path to the models.yaml file when  you initialize the Generate object:
~~~~
gr = Generate(-conf=>'/path/to/config/file/models.yaml'
~~~~

I'm doing more refactoring and once the dust settles I will write a full API guide.

**Comment by carson-katri** [comment]
The issue I had was when passing the `model.yaml` file, it was trying to pull the weights from the wrong directory because it searches relative to the stable-diffusion folder, not the script that created the generator. And in my case that script was outside the stable-diffusion folder. So maybe a working directory path could be passed and prepended to the paths found in `model.yaml`, or `Generator` could be updated to check from the current working directory.

Just something to consider during the redactor 🙂

**Comment by tildebyte** [comment]
So, in this example

```python
gr = Generate(
               conf=>'/path/to/config/file/models.yaml',
               model=>'stable-diffusion-v1.5'
)
```

you passed an absolute path in `conf` and it did NOT find the model?

**Comment by carson-katri** [comment]
@tildebyte 
Correct. I gave it this path in `conf`:
```
/Users/***/dream_textures/stable_diffusion/configs/models.yaml
```

And it failed it fails to find the `v1-inference.yaml` file references from there because its searching relative to the `dream_textures` folder not the `stable_diffusion` submodule folder.

```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/***/dream_textures/configs/stable-diffusion/v1-inference.yaml'
```

It should be loaded from:

<pre>/Users/***/dream_textures/<b>stable_diffusion</b>/configs/stable-diffusion/v1-inference.yaml</pre>

**Comment by unreleased** [comment]
I am also struggling with this same issue, even if the conf is set correctly, it won't start due to issues with `v1-inference.yaml` not being found Hoping this bump will draw more attention to it.

**Comment by carson-katri** [comment]
@unreleased Not really, I just kept using the deprecated parameters to pass the correct absolute paths.

**Comment by carson-katri** [comment]
@unreleased In the latest commits, the deprecated parameters no longer work. So instead, I just created my own `config.yml` with the correct relative paths, which you can see here: https://github.com/carson-katri/dream-textures/pull/324/commits/f3bf259e6dba4139ae44bef73b8244600a6d69ee#diff-8ae208d2e4c753550bb9a731a692bfb2a9961e7706d5d9b6527af162e3c57ade
