### ISSUE TITLE
[enhancement]: AI Prompt Generator

### ISSUE THREAD

**Issue by PierrunoYT** [invoke-ai/InvokeAI#5652]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

pierrebruno@hotmail.ch

### What should this feature add?

AI Prompt Generator which can generate prompts or improve them for people with less knowledge

**Comment by hipsterusername** [comment]
This is available as a community node. Inclusion as a core node may be considered in the future.

**Comment by PierrunoYT** [comment]
> This is available as a community node. Inclusion as a core node may be considered in the future.

What is a community node or where can I get them?
