### ISSUE TITLE
Allow multiple prompts (similar to --from_file) in the web UI

### ISSUE THREAD

**Issue by frankiboi** [invoke-ai/InvokeAI#566]
I love the web UI and the recent improvements to it are great. I also love to have multiple prompts running because you can try out multiple ideas and let it run as long as you want. I did that with the --from_file parameter before. In the file, you set multiple prompts separated by a line break.

It would be great to be able to enter multiple prompts in the same format in the WEB UI text area. The field is already big and expandable.

So entering the following should be 3 prompts:

Portrait of Jack Skellington, in the style of Hieronymus Bosch
Portrait of Jack Skellington, in the style of Leonardo Davinci
Portrait of Jack Skellington, in the style of Pablo Picasso

The behaviour of from_file was to alternate between the prompts which is good, it should keep behaving that way. 

Obviously, pressing "enter" from the text area should no longer trigger the start of the generating process. Instead, it should just do a line break.

This feature could be exposed by a small text somewhere reading "You can enter multiple prompts by changing line." (or something similar)

An alternative that I think would be less easy to use would be to let us pick a text file in the WEB UI.

**Comment by SMUsamaShah** [comment]
This might be simpler to do if something like #543 is implemented.

**Comment by lstein** [comment]
> I love the web UI and the recent improvements to it are great. I also love to have multiple prompts running because you can try out multiple ideas and let it run as long as you want. I did that with the --from_file parameter before. In the file, you set multiple prompts separated by a line break.

Development on the current Web UI is going to stop soon as we phase in the new flask-based interface #429. Your idea of allowing multiple line-separated prompts in the prompt textarea is a good one, and I'm tagging @psychedelicious on this issue for his consideration.

**Comment by psychedelicious** [comment]
This isn't completed, reopening

**Comment by Neosettler** [comment]
This is closely related to "or" or "|" operator,

https://github.com/invoke-ai/InvokeAI/discussions/473

@psychedelicious Any plan to support this?

**Comment by hipsterusername** [comment]
Dynamic Prompting is in 3.0
