### ISSUE TITLE
[bug]: Control Z does not work when Undo in Canvas

### ISSUE THREAD

**Issue by PierrunoYT** [invoke-ai/InvokeAI#5660]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 3080

### GPU VRAM

10GB

### Version number

3.6.2

### Browser

Firefox

### What happened

Control Z does not work when Undo in Canvas. 

### What you expected to happen

To use undo like the button

### How to reproduce the problem

Use Canvas. Then use the Mask to inpaint and Invoke it and then try to click ctrl z

### Discord username

PierrunoYT

**Comment by Millu** [comment]
What type of keyboard do you use? We've seen some users have issues when using non-English keyboards

**Comment by psychedelicious** [comment]
Closing as we haven't heard back from the user in some time and I cannot reproduce the problem. If this is still a problem on v4, please @ me and we can re-open this issue.

**Comment by PierrunoYT** [comment]
> Closing as we haven't heard back from the user in some time and I cannot reproduce the problem. If this is still a problem on v4, please @ me and we can re-open this issue.

I use Swiss Layout
