### ISSUE TITLE
[bug]: stuck at Installing backend dependencies ... /

### ISSUE THREAD

**Issue by ardipahlawan88** [invoke-ai/InvokeAI#5668]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 4080

### GPU VRAM

12GB

### Version number

3.6.2

### Browser

122.0

### Python dependencies

Installing backend dependencies ... /

### What happened

Installing backend dependencies ... /

### What you expected to happen

after waiting for a half hour still nothing change

### Discord username

ardipahlawan88

**Comment by Millu** [comment]
How long does it appear to be stuck? Sometime the installation can take a while, especially depending on internet speeds

**Comment by hipsterusername** [comment]
Closing without additional detail reproducing the issue.
