### ISSUE TITLE
[bug]: Disabling a LoRA in the Linear UI does not disable the LoRA

### ISSUE THREAD

**Issue by Vargol** [invoke-ai/InvokeAI#5689]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

macOS

### GPU vendor

Apple Silicon (MPS)

### GPU model

M3 base 10 GPU revision

### GPU VRAM

24

### Version number

v3.6.3rc1

### Browser

Safari 17.2.1

### Python dependencies

{
  "accelerate": "0.26.1",
  "compel": "2.0.2",
  "cuda": null,
  "diffusers": "0.26.2",
  "numpy": "1.26.4",
  "opencv": "4.9.0.80",
  "onnx": "1.15.0",
  "pillow": "10.0.1",
  "python": "3.10.13",
  "torch": "2.1.2",
  "torchvision": "0.16.2",
  "transformers": "4.37.2",
  "xformers": null
}

### What happened

I generated a image using the LCM LoRA , LCM scheduler, steps 6, CFG 1.5 which generated as expected.
I then disabled the LoRA using the toggle switch, changed the scheduler to UniPCand Invoked with Steps 40, CFG 8.
I got an image that had the classic over the top burn filter or very , very over sharpened effect you
 get from using too high a CFG with an LCM model or LCM LoRA.

Checked the Setting and the LoRA was disabled, but the image metadata had
```
LoRA: lcm-lora-sdxl - 0.75
```
in it.

I had to remove the LoRA using the bin icon to get the image to render correctly.

### What you expected to happen

I expected the second image to redner correctly without using the disabled LoRA,

### How to reproduce the problem

Generated a image using the LCM LoRA , LCM scheduler, steps 6, CFG 1.5.
Go to the Concepts tab, use the toggle to disable the LoRA
Set the scheduler to UniPC, steps to 40, CFG to 8.
Invoke the image to get the bad image.

### Additional context

In case in matters I was using the Proteus v0.2 model.

**Comment by psychedelicious** [comment]
This was fixed in https://github.com/invoke-ai/InvokeAI/pull/5684 and will be in the next release
