### ISSUE TITLE
[enhancement]: RPG-DiffusionMaster Support

### ISSUE THREAD

**Issue by PierrunoYT** [invoke-ai/InvokeAI#5693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

pierrebruno@hotmail.ch

### What should this feature add?

Can you add this to InvokeAI https://github.com/YangLing0818/RPG-DiffusionMaster/issues/32

**Comment by hipsterusername** [comment]
RPG Diffusion master isn't so much a feature as much as it is an integrated multi-model workflow. I'm going to close this, as I think there are a few separate features (some already WIP) that would compose into this
