### ISSUE TITLE
[bug]: Concepts are recalled as turned off/disabled in 3.6.3

### ISSUE THREAD

**Issue by ufuksarp** [invoke-ai/InvokeAI#5698]
### Is there an existing issue for this problem?
- [X] I have searched the existing issues

### Version number
3.6.3

### Browser
Edge 121.0.2277.112

### What happened

Concepts used in iamges are recalled in disabled state if you recall with Use All or Remix.

**Comment by Yaruze66** [comment]
+

**Comment by Yaruze66** [comment]
\+
