### ISSUE TITLE
[bug]: [v3.6.3] 'Remix Image' and 'Use All‘ disable all applied LoRAs

### ISSUE THREAD

**Issue by grunblatt-git** [invoke-ai/InvokeAI#5701]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

macOS

### GPU vendor

Apple Silicon (MPS)

### Version number

3.6.3

### Browser

Chrome (latest)

### What happened

In version 3.6.3 LoRAs in the Concept section received a Toggle to enable/ disable individual LoRAs.

When using the 'Remix Image' or 'Use All‘ features to recall settings of previously generated images, all added LoRAs are disabled by default. If the LoRA was already added before, it gets displayed as "disabled" even though the toggle indicates that it is active.

Because of this you have to click on every individual LoRA to actually recall the image settings.

### What you expected to happen

The expected behaviour would be a one-click recall, meaning exactly the LoRAs used in the original image are applied and active.

**Comment by hipsterusername** [comment]
A fix for this is merged but not yet released. Thanks for the report.

**Comment by Millu** [comment]
Closed by #5699
