### ISSUE TITLE
[bug]: Download image strips metadata, workflow

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#5706]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### Version number

daa780940b12edae78ebf5351c624e9c031bda4b

### Browser

123.0b9

### What happened

Download image strips out metadata and workflow.

### What you expected to happen

Metadata and workflow shouldn't be stripped out from the downloaded images.

### Additional context

Introduced in https://github.com/invoke-ai/InvokeAI/pull/5625/commits/d42de6404c710a930ae48d5bf46d452df90dabb6 when we set the download image hook to write image data to canvas, then download the blob from there. This strips everything out but the pixel data.

**Comment by Harvester62** [comment]
Just noticed, this bug report should have been closed by committed PR https://github.com/invoke-ai/InvokeAI/pull/5720. Am I wrong?

**Comment by psychedelicious** [comment]
@Harvester62 Thanks, you are correct, this is resolved now.
