### ISSUE TITLE
[enhancement]: Pagination for gallery

### ISSUE THREAD

**Issue by ufuksarp** [invoke-ai/InvokeAI#5710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

While infinite scroll is nice for boards with small number of images, as the board gets bigger scrolling time gets longer as well. This causes tab to start lagging and causes frustration.

Add pagination for the gallery so the user can jump into the desired place in the board faster. Give option in the gallery settings for this type of navigation and amount of images per page. Replace Load More button with page numbers.

In my simple test with 1000~ images, it took me 30~ seconds to reach the end, (gets slower and laggier after each load) with pagination this would take assumably 2 seconds. Also if folders are planned for the gallery, this will also help combat this build-up.

Related info: Ryzen 5600, Samsung SSD, Edge latest

**Comment by joshistoast** [comment]
I'd much prefer to have infinite scroll so I can easily find gens for workflows and metadata to re-use, if page-based pagination were used instead I'd be miserable. Instead, a simple button to show less might be much preferable.

**Comment by ufuksarp** [comment]
This doesn't suggest replacing the infinite scroll, but giving an option for pagination as I posted in the first post:
> Give option in the gallery settings for this type of navigation and amount of images per page
