### ISSUE TITLE
[enhancement]: add a option to install from local torch whl

### ISSUE THREAD

**Issue by EaglePPP** [invoke-ai/InvokeAI#5721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

when installing please let user has a possibility to use already downloaded torch ,
its painful that using pip to download it, time wasting. when we want multiple apps like Invoke and automatic111, its 2x time wasting.

**Comment by hipsterusername** [comment]
Different apps can not be guaranteed to operate using the same dependencies. This is a function of how Python app/dependency management works, so not something that can really change. Sorry!

**Comment by ebr** [comment]
You can download it, use pip to install it anywhere, and then it *should* be cached in your pip cache for the future. There are very few users who would go this route, so we can't possibly support it in the installer. But it's definitely an option for you if it suits your use case.
