### ISSUE TITLE
[bug]: 'argument of type 'NoneType' is not iterable' for training embeddings with SDXL

### ISSUE THREAD

**Issue by SkyrimLL** [invoke-ai/InvokeAI#5723]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX3090

### GPU VRAM

24GB

### Version number

3.6.3

### Browser

Chrome (up to date)

### What happened

Running a textual inversion with the non SDXL models is working fine but the process fails with 'sdxl/main/stable-diffusion-xl-base-1-0'.

Trying to launch textual inversion from the default menu (option 2).
I select the SDXL model, enter a name for my embedding and select Use xformers.
Training fails at the first step with this output and error message.
----------
{'model': 'sdxl/main/stable-diffusion-xl-base-1-0', 'resolution': 768, 'lr_scheduler': 'constant', 'mixed_precision': 'fp16', 'learnable_property': 'object', 'initializer_token': 'xxx', 'placeholder_token': '<newstyle>', 'train_data_dir': 'E:\\Tools\\InvokeAI-3.6.2\\text-inversion-training-data\\newstyle', 'output_dir': 'E:\\Tools\\InvokeAI-3.6.2\\text-inversion-output\\newstyle', 'scale_lr': True, 'center_crop': False, 'enable_xformers_memory_efficient_attention': True, 'train_batch_size': 8, 'gradient_accumulation_steps': 4, 'num_train_epochs': 200, 'max_train_steps': 5000, 'lr_warmup_steps': 0, 'learning_rate': 0.0005, 'only_save_embeds': True}
02/14/2024 23:49:10 - INFO - invokeai.backend.training.textual_inversion_training - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: fp16

[2024-02-14 23:49:10,778]::[InvokeAI]::INFO --> Initializing database at E:\Documents\GenerativeAI\InvokeAI-3.6.2\databases\invokeai.db
02/14/2024 23:49:10 - INFO - InvokeAI - Initializing database at E:\Documents\GenerativeAI\InvokeAI-3.6.2\databases\invokeai.db
{'dynamic_thresholding_ratio', 'variance_type', 'thresholding', 'clip_sample_range'} was not found in config. Values will be initialized to default values.
02/14/2024 23:49:14 - INFO - invokeai.backend.training.textual_inversion_training - ***** Running training *****
02/14/2024 23:49:14 - INFO - invokeai.backend.training.textual_inversion_training -   Num examples = 10600
02/14/2024 23:49:14 - INFO - invokeai.backend.training.textual_inversion_training -   Num Epochs = 16
02/14/2024 23:49:14 - INFO - invokeai.backend.training.textual_inversion_training -   Instantaneous batch size per device = 8
02/14/2024 23:49:14 - INFO - invokeai.backend.training.textual_inversion_training -   Total train batch size (w. parallel, distributed & accumulation) = 32
02/14/2024 23:49:14 - INFO - invokeai.backend.training.textual_inversion_training -   Gradient Accumulation steps = 4
02/14/2024 23:49:14 - INFO - invokeai.backend.training.textual_inversion_training -   Total optimization steps = 5000
Steps:   0%|  
02/14/2024 23:49:15 - ERROR - InvokeAI - Traceback (most recent call last):
  File "E:\Tools\InvokeAI-3.6.2\.venv\lib\site-packages\invokeai\frontend\training\textual_inversion.py", line 413, in do_front_end
    do_textual_inversion_training(config, **my_args)
  File "E:\Tools\InvokeAI-3.6.2\.venv\lib\site-packages\invokeai\backend\training\textual_inversion_training.py", line 840, in do_textual_inversion_training
    model_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "E:\Tools\InvokeAI-3.6.2\.venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Tools\InvokeAI-3.6.2\.venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Tools\InvokeAI-3.6.2\.venv\lib\site-packages\diffusers\models\unets\unet_2d_condition.py", line 1013, in forward
    if "text_embeds" not in added_cond_kwargs:
TypeError: argument of type 'NoneType' is not iterable

-------

### What you expected to happen

I expected the textual inversion training to proceed like it does when I am using the non SDXL models

### How to reproduce the problem

1- Launch the menu with the ,bat file
2- Select option 2
3- Select the 'sdxl/main/stable-diffusion-xl-base-1-0' model and a name for the textual inversion (my files are in a folder called 'newstyle' in the right 'text-inversion-training-data' folder)
4- I also select xformers but the error happens regardless of that choice.
5- Leave everything else as default and press OK

**Comment by hipsterusername** [comment]
Please use the new Invoke-training repo instead of the built-in TI training on the InvokeAI repo.

https://github.com/invoke-ai/invoke-training

**Comment by hipsterusername** [comment]
Going to close this as it's now handled in Training repo.
