### ISSUE TITLE
[enhancement]: Controlnet - Depth Hand Refiner

### ISSUE THREAD

**Issue by suonnon** [invoke-ai/InvokeAI#5729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Depth HandRefiner controlnet is just amazing for fixing hands on SD. Is it possible to use it on Invoke? I hope "yes" 
Related links:
https://github.com/wenquanlu/HandRefiner
https://huggingface.co/hr16/ControlNet-HandRefiner-pruned

**Comment by hipsterusername** [comment]
This has been added as a community node. Until an openly licensed hand model (i.e., not MANO) is available, we won't be incorporating this into the core.
