### ISSUE TITLE
[bug]: dw open pose  don't work

### ISSUE THREAD

**Issue by wolfkingal2000** [invoke-ai/InvokeAI#5733]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU VRAM

15

### Version number

3.7.0

### Browser

Opera GX Browser

### What happened

i use dw open pose model give this error all time 

### What you expected to happen

i use dw open pose model give this error all time 

[2024-02-16 15:25:40,411]::[uvicorn.access]::INFO --> 142.202.51.56:0 - "POST /api/v1/queue/default/enqueue_batch HTTP/1.1" 200
[2024-02-16 15:25:41,139]::[uvicorn.access]::INFO --> 142.202.51.56:0 - "GET /api/v1/queue/default/status HTTP/1.1" 200
[2024-02-16 15:25:41,579]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "/content/InvokeAI/invokeai/app/services/invocation_processor/invocation_processor_default.py", line 134, in __process
    outputs = invocation.invoke_internal(
  File "/content/InvokeAI/invokeai/app/invocations/baseinvocation.py", line 677, in invoke_internal
    return self.invoke(context)
  File "/content/InvokeAI/invokeai/app/invocations/controlnet_image_processors.py", line 155, in invoke
    processed_image = self.run_processor(raw_image)
  File "/content/InvokeAI/invokeai/app/invocations/controlnet_image_processors.py", line 630, in run_processor
    processed_image = dw_openpose(
  File "/content/InvokeAI/invokeai/backend/image_util/dw_openpose/__init__.py", line 52, in __call__
    candidate, subset = self.pose_estimation(np_image)
  File "/content/InvokeAI/invokeai/backend/image_util/dw_openpose/wholebody.py", line 51, in __call__
    det_result = inference_detector(self.session_det, oriImg)
  File "/content/InvokeAI/invokeai/backend/image_util/dw_openpose/onnxdet.py", line 103, in inference_detector
    img, ratio = preprocess(oriImg, input_shape)
  File "/content/InvokeAI/invokeai/backend/image_util/dw_openpose/onnxdet.py", line 94, in preprocess
    padded_img[: int(img.shape[0] * r), : int(img.shape[1] * r)] = resized_img
ValueError: could not broadcast input array from shape (640,426,4) into shape (640,426,3)

[2024-02-16 15:25:41,579]::[InvokeAI]::ERROR --> Error while invoking:
could not broadcast input array from shape (640,426,4) into shape (640,426,3)
[2024-02-16 15:25:41,627]::[InvokeAI]::INFO --> Graph stats: c68dfae5-3b8b-4c2d-b8ac-894ce5b67c78
                          Node   Calls   Seconds  VRAM Used
   dw_openpose_image_processor       1    1.084s     2.834G
TOTAL GRAPH EXECUTION TIME:   1.084s
TOTAL GRAPH WALL TIME:   1.084s
RAM used by InvokeAI process: 5.11G (+0.275G)
RAM used to load models: 0.00G
VRAM in use: 2.834G
RAM cache statistics:
   Model cache hits: 0
   Model cache misses: 0
   Models cached: 0
   Models cleared from cache: 0
   Cache high water mark: 0.00/0.00G

**Comment by nelsonre** [comment]
Also experiencing this issue on MacOS Sonoma.

**Comment by nelsonre** [comment]
I did more testing, and the error seems to only appear when I feed the DW preprocessor an image with a transparent background. I edited the png I was using and put a solid white background, and the error disappeared.

**Comment by wolfkingal2000** [comment]
> I did more testing, and the error seems to only appear when I feed the DW preprocessor an image with a transparent background. I edited the png I was using and put a solid white background, and the error disappeared. 

You are right, it doesn't cause any problems in the others, but I think this problem should be solved, it causes a lot of inconvenience for Unified Canvas.

**Comment by blessedcoolant** [comment]
There should have been a check for transparency on this. But there wasn't. I'll fix it up.

**Comment by ybarka25** [comment]
Sorry but the detection is not good at all with the current implementation.
Here is the code to restore the old one as custom node if someone what to do a side by side comparison:
```python
from controlnet_aux import OpenposeDetector

from invokeai.app.shared.fields import FieldDescriptions
from invokeai.app.invocations.baseinvocation import (
    invocation,
    InputField,
)

from invokeai.app.invocations.controlnet_image_processors import ImageProcessorInvocation

@invocation(
    "openpose_image_processor",
    title="Openpose Processor",
    tags=["controlnet", "openpose", "pose"],
    category="controlnet",
    version="1.2.1",
)
class OpenposeImageProcessorInvocation(ImageProcessorInvocation):
    """Applies Openpose processing to image"""

    hand_and_face: bool = InputField(default=False, description="Whether to use hands and face mode")
    detect_resolution: int = InputField(default=512, ge=0, description=FieldDescriptions.detect_res)
    image_resolution: int = InputField(default=512, ge=0, description=FieldDescriptions.image_res)

    def run_processor(self, image):
        openpose_processor = OpenposeDetector.from_pretrained("lllyasviel/Annotators")
        processed_image = openpose_processor(
            image,
            detect_resolution=self.detect_resolution,
            image_resolution=self.image_resolution,
            include_hand=self.hand_and_face,
            include_face=self.hand_and_face
        )
        return processed_image

```

**Comment by blessedcoolant** [comment]
@ybarka25 What do you mean exactly when you say the detection is not good at all? Can you provide some examples? So far, every image I have tested DWPose with has worked and has been better.

If it's to do with the alpha channel images failing, that bug has been fixed and should be a part of the next release.

**Comment by ybarka25** [comment]
Sorry never mind, since I changed my workflow, it's a lot harder to reproduce it. I was thinking that it was an implementation issue (DW pose is known to be better) but the detection issue happen with a contrasted image with specific colors so I think it's due to the model. I upload two examples with one illustrate an annoying issue: I think it's better if it detect nothing than something completely wrong
[poses.zip](https://github.com/invoke-ai/InvokeAI/files/14359190/poses.zip)
