### ISSUE TITLE
[bug]: UI doesn't show labels

### ISSUE THREAD

**Issue by tdpires** [invoke-ai/InvokeAI#5739]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

A10G

### GPU VRAM

24GB

### Version number

3.7.0

### Browser

Chrome latest

### What happened

When trying to deploy with Docker, the UI comes up but all the labels are showing what seems to be non localized strings. Can't generate images with Invoke button. It was working before for version 3.6. Saw an issue where it stated deleting local store cache could fix but it did not. Replicated on another browser.

### What you expected to happen

Expected a usable UI.

### Additional context

Screenshot:
![Screenshot 2024-02-17 at 2 05 13 PM](https://github.com/invoke-ai/InvokeAI/assets/90480825/283c9ef8-e588-4c1a-9b8a-07abce57721f)

**Comment by psychedelicious** [comment]
What happens when you click the invoke button? Any errors?

**Comment by tdpires** [comment]
I get a red queue error in the bottom right corner.

**Comment by psychedelicious** [comment]
Sorry, I should have been more clear. Do you see any errors in the JavaScript console and or terminal? 

Please copy and paste the full terminal output with startup messages.

**Comment by tdpires** [comment]
That button actually doesn't do anything now: 
![Screenshot 2024-02-18 at 4 21 07 PM](https://github.com/invoke-ai/InvokeAI/assets/90480825/36bbd461-9fea-4424-aabe-d7688308946d)

**Comment by tdpires** [comment]
These are my console errors:

![Screenshot 2024-02-18 at 4 38 54 PM](https://github.com/invoke-ai/InvokeAI/assets/90480825/8fd5a6ff-5b82-438f-94b5-fbfbe34883de)

**Comment by tdpires** [comment]
Here is my build output in Docker, which is successful:
[docker output.txt](https://github.com/invoke-ai/InvokeAI/files/14325454/docker.output.txt)

**Comment by tdpires** [comment]
Invokeai.yaml file:
`InvokeAI:
  Web Server:
    host: 0.0.0.0
    port: 9090
    allow_origins: ['mckinney-invokeai.hf.space']
    allow_credentials: true
    allow_methods:
    - '*'
    allow_headers:
    - '*'
  Features:
    esrgan: true
    internet_available: true
    log_tokenization: false
    patchmatch: true
  Memory/Performance:
    always_use_cpu: false
    free_gpu_mem: false
    max_cache_size: 6.0
    max_vram_cache_size: 5.0
    precision: auto
    sequential_guidance: false
    xformers_enabled: true
    tiled_decode: false
  Paths:
    autoimport_dir: autoimport
    lora_dir: null
    embedding_dir: null
    controlnet_dir: null
    conf_path: configs/models.yaml
    models_dir: models
    legacy_conf_dir: configs/stable-diffusion
    db_dir: databases
    outdir: /data/outputs # set to /data/outputs if you have persistent storage
    use_memory_db: true
  Logging:
    log_handlers:
    - console
    log_format: color
    log_level: warning`

**Comment by psychedelicious** [comment]
Thanks. Just to confirm, are you using the process outlined in the `docker/` dir in the repo root?

**Comment by tdpires** [comment]
Yes, I am. This used to work; however, after updating to 3.6, it stopped. I tried 3.7 when it came out but it has the same issue. More info: we ran this on a private huggingface space with persistent storage and an A10G (24GB VRAM) space and it would run very fast for us.

This is failed request example. Fetching an asset (en.json) that exists in the dist folder on the container.

![Screenshot 2024-02-19 at 4 20 36 PM](https://github.com/invoke-ai/InvokeAI/assets/90480825/b44b9293-574d-455f-89cf-d02bf2a06ffe)

**Comment by tdpires** [comment]
It looks like the url is swapped when building using fetchBaseQuery. Instead of putting the asset after the URL, it's putting it after the __sign parameter:
`https://yoursite.com/locale/en.json?__sign=XXXXXXXXXXXXXX`
it's outputting
`https://yoursite.com/?__sign=XXXXXXXXXXXXXXlocale/en.json`

**Comment by tdpires** [comment]
I don't get a 404 when i swap the parameter and the asset it's trying to fetch. How do I fix this in the source?

**Comment by tdpires** [comment]
OK I think i figured it out. A private space requires a signed call to fetch and looks like the code is just inserting the the path to the end of the URL with the query instead of between the URL and the query.

**Comment by tdpires** [comment]
If there was a way to accommodate these types of URLs carrying extra params that would be great

**Comment by psychedelicious** [comment]
Good catch! I tried docker locally and didn't have this issue, and I didn't make the connection with the URL.

Ok, we can definitely support these URLs. There are a few places where we'll need to fix the URLs. I'll take care of it.

**Comment by psychedelicious** [comment]
@hipsterusername  which issue? This is the one afaik

**Comment by ijussit** [comment]
I updated Invoke to 3.7 today and had the same problem as in the picture above, in my case it was the browser.
![bug](https://github.com/invoke-ai/InvokeAI/assets/86885923/fcc490c3-8277-4a18-8aa5-b07cde5f96c3)

**Comment by ebr** [comment]
Not reproducible on latest version.
