### ISSUE TITLE
[2024-02-19 17:47:19,003]::[InvokeAI]::WARNING --> Failed to get graph state for 6bc4c6f8-f70d-451d-98e0-3fb05387d4e5.[bug]: 

### ISSUE THREAD

**Issue by BeeMeeN** [invoke-ai/InvokeAI#5750]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 2080

### GPU VRAM

16GB

### Version number

3.7.0

### Browser

Firefox, Chrome, ... Doesn't matter

### Python dependencies

```python
{
  "accelerate": "0.27.2",
  "compel": "2.0.2",
  "cuda": "12.1",
  "diffusers": "0.26.3",
  "numpy": "1.26.4",
  "opencv": "4.9.0.80",
  "onnx": "1.15.0",
  "pillow": "10.1.0",
  "python": "3.11.6",
  "torch": "2.1.2+cu121",
  "torchvision": "0.16.2",
  "transformers": "4.37.2",
  "xformers": "0.0.23.post1"
}
``` 
### What happened

After many many image generations, this strange warning appears, first only once each generation, then more and more of the warnings come one after the other!

```python
[2024-02-19 17:47:19,003]::[InvokeAI]::WARNING --> Failed to get graph state for 230d4ce7-46ce-45a6-aca7-749911fe8780.
[2024-02-19 17:47:19,003]::[InvokeAI]::WARNING --> Failed to get graph state for 6bc4c6f8-f70d-451d-98e0-3fb05387d4e5.
``` 

The image generation is still possible even with the warnings but I think the image quality suffers somehow, but I'm not sure.

### What you expected to happen

Nothing, I mean I expected not to see any of these warnings.

### How to reproduce the problem

Start creating images, no matter which kind or method (inpaint, just generate, outpaint...) After half an hour or more it begins.

### Additional context

Only after many image generations! But then all the time, with the warnings getting more and more lines with different "for 230d4ce7-46ce-45a6-aca7-749911fe8780" values.

**Comment by BeeMeeN** [comment]
Here the additional info!

```python
{
  "accelerate": "0.27.2",
  "compel": "2.0.2",
  "cuda": "12.1",
  "diffusers": "0.26.3",
  "numpy": "1.26.4",
  "opencv": "4.9.0.80",
  "onnx": "1.15.0",
  "pillow": "10.1.0",
  "python": "3.11.6",
  "torch": "2.1.2+cu121",
  "torchvision": "0.16.2",
  "transformers": "4.37.2",
  "xformers": "0.0.23.post1"
}
```

**Comment by psychedelicious** [comment]
Thanks, this is a known issue, related to the graph stats service. It will be fixed in the next release. You can safely ignore the message. It doesn't affect generation at all.

**Comment by BeeMeeN** [comment]
👍  thx!
