### ISSUE TITLE
[enhancement]: Support Download Name & Location for Bulk Downloads

### ISSUE THREAD

**Issue by blessedcoolant** [invoke-ai/InvokeAI#5757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Allow users in the UI to supply a file name and a download location for bulk downloads.

**Comment by psychedelicious** [comment]
How about this, the toast gives you a link to click. You can do save as or just click to download w/ the default: 
![image](https://github.com/invoke-ai/InvokeAI/assets/4822129/0d0151ae-2b8f-496d-8d44-71724ad90ab5)

**Comment by blessedcoolant** [comment]
> How about this, the toast gives you a link to click. You can do save as or just click to download w/ the default: ![image](https://private-user-images.githubusercontent.com/4822129/306559608-0d0151ae-2b8f-496d-8d44-71724ad90ab5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MjUxNDMsIm5iZiI6MTcwODUyNDg0MywicGF0aCI6Ii80ODIyMTI5LzMwNjU1OTYwOC0wZDAxNTFhZS0yYjhmLTQ5NmQtOGQ0NC03MTcyNGFkOTBhYjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjFUMTQxNDAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjkxNDYxOGI2ZjMyZmM3Y2VkMzY4ODI1ZGM4MTBkMDcyOGQ5YzVjZTk4ZjY1NzcxOWU4YzQzOGYzYmI0YjAzMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0CG5Ke-4ojSM1yHk-9Qr4kJ1ZylCTW0X5UNwj0q28Pk)

The `Save As` as in the browser save window?

**Comment by psychedelicious** [comment]
Yep

**Comment by psychedelicious** [comment]
I mean you can right c click to save as

**Comment by psychedelicious** [comment]
implemented in #5763
