### ISSUE TITLE
[Suggestion] better option for upscaling images

### ISSUE THREAD

**Issue by BookWyrm114** [invoke-ai/InvokeAI#577]
**Is your feature request related to a problem? Please describe.**
This fork is amazing, and it's what I use most of the time, but for generating high-resolution images https://github.com/jquesnelle/txt2imghd is much better, but doesn't have all the options of this fork
**Describe the solution you'd like**
an implementation of the system https://github.com/jquesnelle/txt2imghd uses to make higher-res images (generate image, upscale to desired size, run img2img on smaller pieces of the image, blend it all back together), which would allow us to generate much better-looking high-res images at the cost of faster generation speeds

**Describe alternatives you've considered**
just using txt2imghd, or using the built-in GFPGAN and Real-ESRGAN Support, which is great for things like seamless textures, but for other prompts, like landscapes, it doesn't end up nearly as good as txt2imghd's solution.

**Additional context**
upscaled landscape image with this fork:
![000017 2927298014](https://user-images.githubusercontent.com/79489385/190274263-ac70df2d-12d8-4a97-a86e-6ef15d6d7766.png)

example of a txt2imghd image: 
initial image:

![00000](https://user-images.githubusercontent.com/79489385/190261412-acc9d94c-2685-4c15-8ec7-d952d8b52449.png)
upscale:
![00000u](https://user-images.githubusercontent.com/79489385/190261468-43adcd30-d76b-4bd4-85cd-4568151c0557.png)
after img2img:
![00000ud](https://user-images.githubusercontent.com/79489385/190261542-7a424bc8-9b2a-405a-8ec7-00155b71699e.png)

example 2:
![00031](https://user-images.githubusercontent.com/79489385/190261637-4d7b625a-10f4-44b1-b6a2-3ff6e6330443.png)
![00031u](https://user-images.githubusercontent.com/79489385/190261650-c94d268b-75f3-4f95-81f1-54530302b4d7.png)
![00031ud](https://user-images.githubusercontent.com/79489385/190261668-4ee8f03c-e844-49f5-8230-54edb72eebef.png)

**Comment by Any-Winter-4079** [comment]
I tried that option with the https://github.com/lowfuel/progrock-stable repo and it caused me issues with some inputs (e.g. if you say person, it will be incentivized to create a person in every tile).
I haven't looked at the repo you mention or how they implement it, so from my side it's worth exploring!

**Comment by BookWyrm114** [comment]
Yeah, I've run into that issue too sometimes, but with txt2imghd they have a "--strength" argument, which decides the strength for noising/unnoising, on default values you won't run into that issue thankfully, but 0.5-0.6 and higher sometimes causes that issue.

**Comment by n00mkrad** [comment]
Embiggen (=txt2imghd) is being implemented on the dev branches right now.

**Comment by blessedcoolant** [comment]
General upscaling and img2imghd are two very different features.

Upscaling is just basically enlarging the existing image with the help of AI models. In regards to that, there are very few models at the moment that provide better general results than ESRGAN. And we have that implemented.

As for img2imghd, this a feature where the canvas is enlarged, the image is split into tiles and then resampled with the diffusion model per each tile hence providing a larger image with seemingly more detail.

We have this feature too. Currently in development branch and it's called `embiggen`. Feel free to check it out. Works great. It would have made the latest release but stuff got delayed to the last day and we pushed to the next release.

if you don't want to try the `development` branch, you can make use of this feature with the help of `embiggen` in the next release.

**Comment by BookWyrm114** [comment]
Closing the issue since embiggen is now in the latest release. (Also yay 2.0.0 release!)
