### ISSUE TITLE
[enhancement]: The ControlNet preview should accurately display the image as it will be sent to AI model when ControlNet is set to crop or resize the input image.

### ISSUE THREAD

**Issue by StellarBeing25** [invoke-ai/InvokeAI#5771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

When you input a image in the ControlNet, the preview image after preprocessing maintains the dimensions of the input image. However, the image actually sent to the AI model will be cropped or resized according to generation parameters set when ControlNet is set to crop or resize the input image. This leads to a mismatch between what is previewed and the final output. The correct behavior is to show the final processed image in the preview so that user can see what AI see.

**Comment by psychedelicious** [comment]
I don't think this is feasible with the current implementation. The crop/resize logic is dependent on dynamic attributes like the size of the noise tensor, which isn't known at the time the control image is processed.

**Comment by StellarBeing25** [comment]
Ok... then please add basic image editing features like cropping or resizing of the asset images in invoke's gallery itself.

**Comment by psychedelicious** [comment]
It's something we've wanted to do for a long time, but I don't see a feature request for it. Please do make one

**Comment by StellarBeing25** [comment]
Added new feature request, closing this one.
