### ISSUE TITLE
[bug]:  Embedding Training selects incorrect model

### ISSUE THREAD

**Issue by solosails** [invoke-ai/InvokeAI#5787]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX2080

### GPU VRAM

8GB

### Version number

3.7.0

### Browser

Chrome

### What happened

Running Textual Inversion Training from the startup menu does not respect the model selection.

For example, if I choose an SD1.5 model, the config file saves with an SD2 model and the resultant embedding wont work.

The embedding does work however with the model that was in the config file.

### What you expected to happen

I expected choosing a specific model would result in that model being chosen! 

### How to reproduce the problem

start the .bat file, chose option 2, make slections for model etc and start training. 

The config file doesnt have the correct model settings

### Discord username

plan8

**Comment by hipsterusername** [comment]
TI in the startup menu should be marked as deprecated - sorry for the trouble!

A more advanced training application has been released in the https://github.com/invoke-ai/invoke-training repo.
