### ISSUE TITLE
[bug]: Unable to download models from CivitAI

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#5808]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### Version number

next

### Browser

FF

### What happened

I cannot seem to download most models from CivitAI. I get an error like this:

![image](https://github.com/invoke-ai/InvokeAI/assets/4822129/f54fc0a9-d8f9-4e38-9146-306770598a09)

Test install URLs, all seem to be parsed by the installer properly but all give the same kind of error:
https://civitai.com/models/323284/mandelbrot-fractal-style-sdxl
https://civitai.com/models/5952/experience?modelVersionId=137204
https://civitai.com/api/download/models/362448?type=Model&format=SafeTensor

### What you expected to happen

Models install from CivitAI

**Comment by psychedelicious** [comment]
It appears the CivitAI API has changed and now returns an array for this value instead of a string. This breaks our pydantic models. I didn't realize that we were implementing CivitAI's API schemas internally. That's bound to cause issues, we'll have to continually update our models as their API changes. Maybe metadata should just be a `dict[str, Any]`?

**Comment by lstein** [comment]
Civitai hasn’t changed its API documentation, so this is a bit annoying. I didn’t attempt to copy the API schema, but just pulled out a subset of fields that would be useful. I do not think we want to pull the entire JSON from Civitai because it is HUGE and filled with images and (sometimes ugly) comments.
