### ISSUE TITLE
add ksampler support for img2img

### ISSUE THREAD

**Issue by czyz** [invoke-ai/InvokeAI#581]
**Is your feature request related to a problem? Please describe.**
The dream.py code seems to indicate that k_lms is the default sampler, yet when run, with or without k_lms specified, the message "sampler 'KSampler' is not yet supported. Using DDIM sampler" shows up in the output, and the DDIM sampler is used.

It appears that k_lms works for text2img, but dream.py switches to DDIM for img2img.

**Describe the solution you'd like**
Would be great to be able to use the k_lms and other ksamplers with img2img.

**Describe alternatives you've considered**
N/A

**Additional context**
dream.py output:
'''
(ldm) C:\Users\skype\Downloads\stable-diffusion>python scripts/dream.py --full_precision --outdir "C:\Users\skype\Resilio Sync\Blender\stablediffusion_outputs"
* Initializing, be patient...

>> Loading model from models/ldm/stable-diffusion-v1/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
>> Using slower but more accurate full-precision math (--full_precision)
>> Model loaded in 9.23s
>> Max VRAM used to load the model: 4.28G
>> Current VRAM usage:4.28G
>> Setting Sampler to k_lms

* Initialization done! Awaiting your command (-h for help, 'q' to quit)
dream> coarse pencil sketch by Escher:1.00 -I "C:\Users\skype\Resilio Sync\Blender\stablediffusion_jobs\diffusion_test10\diffusion_test10_00059.png" --strength=0.50 --cfg_scale=25.00 --steps=100 -U 2 75 -G 75 -S 1111111111 --sampler=k_lms
>> loaded input image of size 464x752 from C:\Users\skype\Resilio Sync\Blender\stablediffusion_jobs\diffusion_test10\diffusion_test10_00059.png
>> This input is larger than your defaults. If you run out of memory, please use a smaller image.
>> sampler 'KSampler' is not yet supported. Using DDIM sampler
Generating:   0%|                                                                                                                                                          | 0/1 [00:00<?, ?it/s]Running DDIM Sampling with 50 timesteps
Decoding image: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:04<00:00, 10.32it/s]
Generating: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.17s/it]
>> Real-ESRGAN Upscaling seed:1111111111 : scale:2x
        Tile 1/2
        Tile 2/2
>> GFPGAN - Restoring Faces for image seed:1111111111
>> Usage stats:
>>   1 image(s) generated in 11.31s
>>   Max VRAM used for this generation: 5.58G. Current VRAM utilization:4.37G
>>   Max VRAM used since script start:  5.58G
Outputs:
[1] C:\Users\skype\Resilio Sync\Blender\stablediffusion_outputs\000064.1111111111.png: "coarse pencil sketch by Escher:1.00" -s100 -W512 -H512 -C25.0 -Ak_lms -IC:\Users\skype\Resilio Sync\Blender\stablediffusion_jobs\diffusion_test10\diffusion_test10_00059.png -f0.5 -G75.0 -U 2.0 75.0 -S1111111111

dream>

'''

**environment**
- GPU: cuda
- VRAM: 12288MB
- CPU arch: x86/arm
- OS: windows
- Python: miniconda
- Branch:
- Commit: 9b28c65e4b0526956fd90ad86e2118536e4eaa9b (HEAD -> main, tag: release-1.14.1, origin/main, origin/HEAD)

**Comment by n00mkrad** [comment]
+1, it seems like other forks support this.

**Comment by lstein** [comment]
This feature has been on the TODO list for a long time as a high priority item, but unfortunately nobody knowledgeable enough to implement the changes has volunteered to work on them. They've been quite consumed with optimizing memory footprint, performance, and getting everything running on M1/M2 Macs.

If they haven't diverged too much, we can "borrow" from another fork. Is there one in particular that you recommend, @n00mkrad ?

**Comment by n00mkrad** [comment]
> If they haven't diverged too much, we can "borrow" from another fork. Is there one in particular that you recommend, @n00mkrad ?

Automatic's fork seems to support it.

https://github.com/AUTOMATIC1111/stable-diffusion-webui
