### ISSUE TITLE
[enhancement]:  unified canvas, change the priority from transparent to mask

### ISSUE THREAD

**Issue by wolfkingal2000** [invoke-ai/InvokeAI#5810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

unified canvas, change the priority from transparent to mask , I don't want to outpainting my photo, but when I want to edit the edges, it is very difficult to do it

**Comment by psychedelicious** [comment]
Sorry but I'm having trouble visualizing what you are asking for. Please elaborate, maybe a picture will help.

**Comment by wolfkingal2000** [comment]
> Sorry but I'm having trouble visualizing what you are asking for. Please elaborate, maybe a picture will help.

![image](https://github.com/invoke-ai/InvokeAI/assets/131250049/e1b1f0fa-1083-4345-bcfd-797b777d20fb)

Like the picture above, when it is in mask mode, I want it to edit only the mask, not the empty purple part and on the edge of the photo.

**Comment by psychedelicious** [comment]
Thanks. The bounding box can function as the bounds for your mask editing. You may need to enable the "restrict strokes" option in the canvas setting popover.
