### ISSUE TITLE
[bug]: apiUrl not used for image fetching

### ISSUE THREAD

**Issue by Ery4z** [invoke-ai/InvokeAI#5834]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### Version number

3.7

### Browser

/

### What happened

When setting a apiUrl to the InvokeAIUI component the calls to fetch the images /api/v1/images/i/{id}/full and /api/v1/images/i/{id}/thumbnail are not using apiUrl as excepted. The other endpoint use it well.

The first image show that apiUrl is well used for some endpoint but not for the /thumbnail
/full is exactly the same
![image](https://github.com/invoke-ai/InvokeAI/assets/48215561/e4070009-5b12-497a-bb7d-55c415a3207b)
![image](https://github.com/invoke-ai/InvokeAI/assets/48215561/c17b3186-3fa5-4790-984b-475216b5bbdc)

The call seems to be made by a different part of the app and this may explain the issue

![image](https://github.com/invoke-ai/InvokeAI/assets/48215561/06b863d8-d325-4633-9bba-847f0f2989d3)

The problem prevent from using a remote backend not hosted on the same server than the frontend.

### What you expected to happen

I expected the /full and /thumbnail to use apiUrl

### Discord username

ery4z

**Comment by psychedelicious** [comment]
Image URLs are provided by the backend: https://github.com/invoke-ai/InvokeAI/blob/main/invokeai/app/services/urls/urls_default.py

You'll need to implement your own version of this service to change the image URLs.

**Comment by psychedelicious** [comment]
Closing this as nofix, the behaviour is expected
