### ISSUE TITLE
Error when attempting to enter prompt: "ValueError: too many values to unpack (expected 2)"

### ISSUE THREAD

**Issue by Xoduz** [invoke-ai/InvokeAI#585]
**Describe your environment**
- GPU: GeForce GTX 2080 Super
- VRAM: 8 GB
- CPU arch: x86/x64
- OS: Windows 10
- Python: Anaconda3 (2022.05) / python 3.9.12
- Branch: main
- Commit: 89da371f4841f7e05da5a1672459d700c3920784

**Describe the bug**
When attempting to enter a prompt via the dream python script running in Anaconda prompt, the script crashes with an error saying "ValueError: too many values to unpack (expected 2)". This happens regardless of how many words I enter into the actual prompt.  Full prompt & error message log:
```
* Initialization done! Awaiting your command (-h for help, 'q' to quit)
dream> test
Traceback (most recent call last):
  File "scripts\dream.py", line 685, in <module>
    main()
  File "scripts\dream.py", line 112, in main
    main_loop(t2i, opt.outdir, opt.prompt_as_dir, cmd_parser, infile)
  File "scripts\dream.py", line 299, in main_loop
    t2i.prompt2image(image_callback=image_writer, **vars(opt))
  File ".\ldm\generate.py", line 319, in prompt2image
    results = generator.generate(
  File ".\ldm\dream\generator\base.py", line 41, in generate
    device_type,scope   = choose_autocast_device(self.model.device)
ValueError: too many values to unpack (expected 2)
```

**To Reproduce**
Steps to reproduce the behavior (on my computer):
1. Follow manual installation guide for Windows, git clone the repo, create environment file, preload models, download weights (1.4)
2. Run `conda activate ldm`
3. Run `python scripts\dream.py`
4. Enter any prompt (I tried **"test"** and **"man standing on flat ground"**
5. Observe the abovementioned error.

**Expected behavior**
The expected behaviour would be that the tool generated an image based on my input.

**Additional context**
I have an older version of Stable Diffusion from this fork (_**v1.13 (in process)**_) running in a separate folder (manually downloaded from GitHub as zip), which works without any issue. However, I wanted to be able to easily update to newer versions of the fork, so I followed the manual installation instructions for Windows to clone the repo using git. Experienced no other issues than the abovementioned error when attempting to actually enter a prompt.

**Comment by lstein** [comment]
This is puzzling. It looks like the current code (version 1.14) is calling old code from 1.13. This is a bit brute-force-y but I think it will work.

While you are in the stable-diffusion directory from the 1.14 release:
~~~~
conda deactivate
conda env remove -n ldm
rmdir src /s
conda env create -f environment.yaml
~~~~ 

This is basically cleaning everything up from the previous install and starting from scratch. The "rmdir" line is removing the "src" directory just in case. I think I've got the syntax right for recursively removing a directory and its contents on Windows, but if this isn't right, you can use remove the src directory using the desktop GUI.

**Comment by lstein** [comment]
Any luck?

**Comment by Xoduz** [comment]
Hi @lstein, sorry for the delay. Running the commands you suggested (minus the rmdir one, since there was no src folder in the 1.14 release) seemed to do the trick. I can now use the 1.14 release.
