### ISSUE TITLE
[bug]: Connection Aborted during Install

### ISSUE THREAD

**Issue by NillieZilla** [invoke-ai/InvokeAI#5858]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 3080 

### GPU VRAM

8GB

### Version number

3.7.0

### Browser

Opera 107.0.5045.37

### What happened

Automatic Installation, Fired: [2024-03-03 08:42:26,310]::[InvokeAI]::ERROR --> (ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)), '(Request ID: 1624766e-1399-4a9e-9bdf-901ac4d8e890)')
[2024-03-03 08:42:26,311]::[InvokeAI]::WARNING --> Skipping diffusion weights download per user request

It was downloading the tokenizer and text encoders and then fired this.

### What you expected to happen

Complete the install. 

### How to reproduce the problem

Download the installer for 3.7.0. Extract the files, run the installer like normal.

### Discord username

nilliezilla

**Comment by hipsterusername** [comment]
This typically happens if the download is taking a long time and the remote provider cuts off the connection. How long was this taking?

**Comment by NillieZilla** [comment]
> This typically happens if the download is taking a long time and the remote provider cuts off the connection. How long was this taking?

It was immediate, even when attempting the re-install after. Every single time, the moment it got to that section it would take 1 second, then that error would fire and the installation would end saying it was successful.

**Comment by glytchwytch** [comment]
I'm having the same issue exactly as described here. The only differences with my setup are a RTX 4080, and I'm running chrome as my default browser.

**Comment by hipsterusername** [comment]
@lstein Think this just means we need to package and distribute core support models aye?

**Comment by psychedelicious** [comment]
This script no longer exists; models can be downloaded in the UI now.
