### ISSUE TITLE
[bug]: Slow autoimport

### ISSUE THREAD

**Issue by aolko** [invoke-ai/InvokeAI#5867]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

NVIDIA GeForce GTX 1060

### GPU VRAM

6GB

### Version number

3.7.0

### Browser

Thorium 121.0.6167.204 / Chrome 122.0.6261.95 / Mercury 121.0.2 / Firefox Developer 124.0b7

### What happened

Autoimports are being very slow every time invoke decides to load/reload models

### What you expected to happen

Reasonable autoimport load speed

### How to reproduce the problem

Have a bunch of models and controlnets patched through `autoload` folder

### Additional context

<details><summary>Trace</summary>

### Watch the timestamps to estimate the average load time

[Get the trace](https://github.com/invoke-ai/InvokeAI/files/14500766/message.2.txt)

</details> 

### Discord username

aolko (PM only)

**Comment by psychedelicious** [comment]
Autoimport is pretty simple - it uses the same logic as the main model scanning.

That said, I would like to drop it, instead directing users to the scan folder functionality in the model manager.

**Comment by aolko** [comment]
and basically shit all over launchers that try to maintain compatibility and allow to sync models globally? GG

**Comment by hipsterusername** [comment]
Autoimport has been removed - we don’t have any communications or support from any of the launcher teams, and can’t maintain multiple channels for model ingestion on the behalf of others without it.

As is, we are confident that models will be more consistently managed in a single place.

**Comment by psychedelicious** [comment]
Note for anyone who finds themselves here wondering about sharing models between other applications or with the "launcher" apps like pinokio or stability matrix:

We haven't removed the ability to do that. You just need to use the scan folder tab in the model manager to install the models instead of the autoimport folder.
