### ISSUE TITLE
TextToImage Generation Failed

### ISSUE THREAD

**Issue by wzgdesigntech** [invoke-ai/InvokeAI#588]
- GPU: NVIDIA GeForce GTX 1650
- VRAM: 8 GB
- CPU arch: x86/x64
- OS: Windows 10
- Python: 3.9
Branch: main

I want to implement the function of textToImage through dream.py, but I get this result；
[
![企业微信截图_20220915095404](https://user-images.githubusercontent.com/112833981/190337880-e4910814-e6b3-4129-a943-211aebc5775b.png)
](url)
Is it because this GPU is not supported?Can someone help with the answer?

**Comment by lstein** [comment]
Can you try starting dream.py with the option **--full_precision** ? The green image is a bug that appears on some video cards when running in half precision.

**Comment by wzgdesigntech** [comment]
After debugging, it was found that my local folder: ”.cache\huggingface\hub\models--openai--clip-vit-large-patch14 “was missing in the folder: added_tokens.json.I created this file although it is empty.
Then another problem arose.
![企业微信截图_20220916182547](https://user-images.githubusercontent.com/112833981/190618714-4f251bcd-454a-46dd-998c-86f4369fe7a2.png)

**Comment by ArDiouscuros** [comment]
As an owner of GTX 1660 Ti with 6 GB of VRAM could propose following solution:
(as found in the end of #526)
Option one:
1. Use latest development branch which automatically select precision or manually set precision=float32
    As you have 8GB VRAM you should be fine
2.  Use latest development branch and manually set precision=float16
2.1 If you get a green image - download latest cudnn binaries from NVIDIA site, and replace them in folder 
conda\envs\ldm\Lib\site-packages\torch\lib
2.2 If you get now black image - place line 
torch.backends.cudnn.benchmark = True
after model init code

If you could give some feedback it would help to implement it in more nice manner...
