### ISSUE TITLE
[enhancement] [UI]: Sync model after download is complete 

### ISSUE THREAD

**Issue by Malrama** [invoke-ai/InvokeAI#5907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Currently, when a download is finished, the ModelUI won't update until you click "sync model". This is not a problem itself, it just feels weird. You would expect the downloaded model to show up in the model list once the download is "finished".
I expect a lot of people will not click that "sync model" button and are confused until they restart the App.

Thanks and greetings

**Comment by maryhipp** [comment]
What version is this on? 4.0rc?

**Comment by Malrama** [comment]
@maryhipp 4.0RC2. Maybe I should add, that I download it of citivitai via the API key in the config directly in Invoke.
Even pressing "Sync models" doesn't show the model. I have to refresh (F5) the page for it to show up in the model list as a checkpoint.
Haven't tried it with local models yet. Everything works, it just doesn't show up in the model list unless I refresh.
