### ISSUE TITLE
[bug]: UI text labels not being localized or missing from Weblate

### ISSUE THREAD

**Issue by Harvester62** [invoke-ai/InvokeAI#5917]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

GTX 1070

### GPU VRAM

8GB

### Version number

3.7dev (hash 9376b134352cf4c177099cc63b445692db4dd4b9)

### Browser

Firefox 123.0.1

### What happened

Some labels in the UI are not being properly localized, or the related strings are not available for translation on Weblate.

**T2i, i2i and Unified Canvas**

The “Advanced Options” labels in T2i, i2i and Unified Canvas aren’t properly converted into the localized string, available on Weblate

![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/3753ff5e-11f3-4671-8194-754338a1f401)
![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/958e75ae-5f9f-4dee-9758-223dd98a9b7f)

**Unified Canvas**

In the Unified Canvas’ Image Advanced Options, the value selection bar for Scaled W and H should shrink to the right, if the panel is enlarged, as in the fields above (see screenshot), so to be able to read the label’s text.

![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/0bb41e11-6c5e-4ded-bbe6-4feb1d89deb2)
![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/6859eaa4-b026-4655-909b-82aeb0637ff2)

**Workflow Editor**

In the Data tab the text is not using the localized version, while available on Weblate
![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/aebbe97d-84ef-4ab3-ab00-7689bba6e0e4)
![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/a236dc27-4f66-4ef0-8d9a-7abc4aa41fb9)

**Model Manager**

The categories names of the models aren’t available for translation on Weblate. I might possibly do not translate some technical terms but I’d like to have the option to do it.

![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/099baa71-bdf4-472f-93c0-4eaf03e60780)
![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/e427a1df-d1d8-46ff-a35e-658a5f9e6130)

### What you expected to happen

The localized text should be used in the UI or available on Weblate for translation if missing.

**Comment by rohinish404** [comment]
Can i get assigned to this?

**Comment by Harvester62** [comment]
I found a few more strings that should be also added in Weblate for translation. A check on those strings might be needed to verify if they are currently available on Weblate but the localization code might not be properly set within the scripts.

**Workflow Editor**

![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/1edd1e99-8a5b-4e66-9a0e-737a645cd711)

![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/adb137d6-48e4-4f1b-9798-f567ee6541d6)
