### ISSUE TITLE
[bug]: invokeai-model-install.py download from https://civitai.com  dont work  in Invoke 4.0rc1

### ISSUE THREAD

**Issue by wolfkingal2000** [invoke-ai/InvokeAI#5932]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU VRAM

15

### Version number

4.0rc1

### Browser

Opera GX Browser

### What happened

%cd /content/InvokeAI/
!python /content/InvokeAI/scripts/invokeai-model-install.py --root_dir /content/db --yes --add  https://civitai.com/api/download/models/119057 
I want to install the model with this command, but it gives me an error. There was no problem in the previous version, but this new version, I don't know what the problem is, please help and give this error
invokeai-model-install: error: unrecognized arguments: --add https://civitai.com/api/download/models/119057 

### What you expected to happen

.

**Comment by lstein** [comment]
I can reproduce this and will fix.
