### ISSUE TITLE
[enhancement]: Add more image data to queue API

### ISSUE THREAD

**Issue by Shaosil** [invoke-ai/InvokeAI#5933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Ideally, when querying queue items (perhaps even after enqueuing a request?), the response would contain more data about any image generation data. Currently, we have to rely on socket events to get the image name, for example.

**Comment by psychedelicious** [comment]
This is resolved in #6408. The session object in the queue item is updated after it finishes executing (successfully or not). You can extract node outputs, including images, from `session.results`.

Might not be in the next release, but it's pending.

In case you are not familiar with this part of the system, when a graph is executed, its initial state is stored as `session.graph`, but execution is tracked in `session.execution_graph`. The node ids in the execution graph are different from those in the initial graph. 

You can use `session.source_prepared_mapping` to map the initial graph node ids to execution graph node ids, then use those to access the corresponding results, which are keys against the execution graph node ids.

For example, if, in your initial graph, you had an `l2i` (VAE decode node) with id "my_l2i_node", you could access its output with `session.results[session.source_prepared_mapping['my_l2i_node']]`.
