### ISSUE TITLE
[enhancement]: support non-mmap BLAKE3 hashing

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#5938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Add a configuration for model hashing to support non-mmap, non-threaded BLAKE3.

This vastly improves performance on spinning disks: https://discord.com/channels/1020123559063990373/1217051407543435344

I think the best way is to remove `skip_model_hash: bool` and make it `hashing: 'blake3' | 'blake3-no-mmap' | 'none'`.

**Comment by lstein** [comment]
I'm happy to add this enhancement. It will take a couple of days as I'm on a family vacation.
