### ISSUE TITLE
Implement support for incoming LAION Large OpenCLIP H/14

### ISSUE THREAD

**Issue by tildebyte** [invoke-ai/InvokeAI#595]
**Is your feature request related to a problem? Please describe.**
LAION released new Large OpenCLIP models; we should implement support for the big one.

**Describe the solution you'd like**
Support for LAION Large OpenCLIP H/14 (specifically H/14; "go big or go home" 😆 )

**Describe alternatives you've considered**
No alternatives

**Additional context**
- Announcement: https://twitter.com/emostaque/status/1570501470751174656?s=46&t=jTh68A_YCxdzuaOxZyJB5g
- Details: https://laion.ai/blog/large-openclip/

**Comment by lstein** [comment]
Is it the same as this one? https://huggingface.co/openai/clip-vit-large-patch14-336

If so, I just need to change one line of code to bring it in. Would we want to replace the previous CLIP model with this one, or provide both models as options?

**Comment by tildebyte** [comment]
Definitely not, OpenAI CLIP != LAION OpenCLIP

I’ve seen some talk that the SD model itself would have to be trained to use this?

IDK, it’s not clear to me.

**Comment by tildebyte** [comment]
This one https://huggingface.co/laion/CLIP-ViT-H-14-laion2B-s32B-b79K, although it doesn't seem like the actual model is available (admittedly I _always_ have trouble with the HF website).

**Comment by Vargol** [comment]
It really needs to be optional if it has to stay resident in memory and is significantly larger,

 I'm already seeing failures at 1024x1024 in the main branch that were not there in the 1.14.3 optimisation branch. I've not raised this as an issue as I've also moved macOS 12.6 between running those versions so not quite convinced its SD issue yet.

**Comment by tildebyte** [comment]
Yeah, I might close this one out. I'd forgotten that part of the SD "magic" is a super-optimized "frozen" CLIP model somehow embedded in the SD model.

**Comment by eous** [comment]
I got the clip h model running within this fork by changing import clip to open_clip and a few other things including hacking the clip transformers package. The coherency improvement between prompt and resulting images is massive. You can check the stable diffusion discord general and general-with-images for my notes and some sample images. https://discord.com/channels/1002292111942635562/1002292112739549196/1020520084587954206

One caveat is it increased my memory utilization from about 9gb to about 13gb.

**Comment by tildebyte** [comment]
Ouch 😣 That's not gonna happen on my laptop. 

I wonder if there would be any benefit in trying to use one of the smaller OpenCLIP models…

**Comment by thelemuet** [comment]
Here is code + colab that were released today: https://github.com/huggingface/diffusers/tree/main/examples/community
