### ISSUE TITLE
[bug]: Black Images NVIDIA T1000 8GB

### ISSUE THREAD

**Issue by creakyrock08847** [invoke-ai/InvokeAI#5971]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

NVIDIA T1000

### GPU VRAM

8GB

### Version number

v4.0.0rc1

### Browser

Google Chrome 122.0.6261.113

### What happened

Hello, everything I try to generate an image it just turns out as a black image. I am running invoke in a docker on unraid.

I have tried tried lowing my steps and setting my steps to an odd number suggested by others. I'm using  model 1-5.

I have tried a few different schedulers with no luck.

I have switched the VAE Precision between 16 and 32 with nothing changing.

When an image first starts it shows up some pixles and then goes black a second or 2 after.
![image (1)](https://github.com/invoke-ai/InvokeAI/assets/61040516/aa4c4f21-874e-4f5e-b035-5660883e0d1c)
![image](https://github.com/invoke-ai/InvokeAI/assets/61040516/c3f52573-6804-4f34-9949-14487cd1dcb8)
[log.txt](https://github.com/invoke-ai/InvokeAI/files/14620328/log.txt)

### What you expected to happen

I expected images to generate.

### Discord username

creakyrock

**Comment by psychedelicious** [comment]
Did it work previously? If so, what was the last app version where it worked?

**Comment by creakyrock08847** [comment]
> Did it work previously? If so, what was the last app version where it worked?
> 
> This line is interesting:
> ```
> /home/invokeuser/venv/lib/python3.10/site-packages/diffusers/image_processor.py:90: RuntimeWarning: invalid value encountered in cast
>   images = (images * 255).round().astype("uint8")
> ```
> 
> That's in the [`VaeImageProcessor` class](https://github.com/huggingface/diffusers/blame/main/src/diffusers/image_processor.py#L85-L99), as it tries to convert the numpy image into a PIL image. This code hasn't been changed in some time, but maybe something around it has been.

It has never worked.

**Comment by psychedelicious** [comment]
Ok. I believe this issue is related to the GPU and its supported precision settings.

Let's try forcing fp32 precision for the whole app.

In the `invokeai.yaml` file, add a `Device:` section if it doesn't already exist. Then, add `precision: float32` under it:

```yaml
InvokeAI:
  Device:
    precision: float32
```

You could also try `precision: autocast`.

Do either of those fix the issue?

**Comment by B4D5YN74X** [comment]
fwiw, i was having the same issue on a T1000, and setting the precision to float32 as @psychedelicious directed did, indeed, correct the problem.

**Comment by psychedelicious** [comment]
Thanks @B4D5YN74X. Closing this old issue.
