### ISSUE TITLE
[bug]: Model manager requires web page refresh to show the newly added models.

### ISSUE THREAD

**Issue by StellarBeing25** [invoke-ai/InvokeAI#5975]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 3060

### GPU VRAM

12

### Version number

4.0.0 RC2

### Browser

Firefox

### What happened

The newly installed model won't appear in the Model Manager until the web page has been refreshed. Changing and saving the model settings also requires a web page refresh.

https://github.com/invoke-ai/InvokeAI/assets/152368658/006bd8c2-e2b8-4e8d-a885-100b31fca497

### What you expected to happen

The Model Manager should update without refreshing the web page.

**Comment by ChrisTop700** [comment]
Was just about to report the same thing

**Comment by Harvester62** [comment]
I can confirm this issue.

**Comment by Malrama** [comment]
See https://github.com/invoke-ai/InvokeAI/issues/5907
