### ISSUE TITLE
[enhancement]: is there an update to case: #2600

### ISSUE THREAD

**Issue by alfi4000** [invoke-ai/InvokeAI#5978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Api Image Generation!

### Alternatives

None Yet as far I know!

### Additional Content

Hi is there an update to case: #2600 about Api Image generation because I was contacting [Open Webui](https://github.com/open-webui/open-webui) for adding the ability to create images over api from invoke but they told me it isn't possible and gave me the link to case: #2600 and they forks were talking about soon there will be a new api is that the case or still in development?

**Comment by psychedelicious** [comment]
I've replied to your question in that discussion. We've had a REST API for quite a while now.

**Comment by alfi4000** [comment]
Thanks for taking time to clarify that! :)
