### ISSUE TITLE
[bug]: Error: Permission denied to access property "getAttribute"

### ISSUE THREAD

**Issue by Core420** [invoke-ai/InvokeAI#5983]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

AMD (ROCm)

### GPU model

RTX 6800XT

### GPU VRAM

16GB

### Version number

4.0.2 (but also in the latest 3 release)

### Browser

Firefox 123.0.1

### What happened

Anytime I go into settings, or make a change that might be related to settings, that error pops up and I have to reset the UI. Im guessings its a file/settings on disk permissions issue -maybe?

### What you expected to happen

settings to pop up or settings to be applied

### How to reproduce the problem

click on the settings icon

**Comment by psychedelicious** [comment]
Hi @Core420 , can you please take a screen shot? If the screenshot can't fit the full error, please also copy and paste it here.

**Comment by Core420** [comment]
Hi psychedelicious, 

Well after 3 days of consistently hitting the issue, this morning when I started the pc to take a screenshot the error has gone and I can access the settings..... so for now mark the case closed.

I will let you know if it ever pops up again.

Thanks for getting back to me so quickly too.

Have a good weekend :)
