### ISSUE TITLE
[bug]: T2I linear giving a node error

### ISSUE THREAD

**Issue by lstein** [invoke-ai/InvokeAI#5984]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 4070

### GPU VRAM

12GB

### Version number

main (essentially 4.0rc2)

### Browser

Google chrome for ios

### Python dependencies

{
  "accelerate": "0.28.0",
  "compel": "2.0.2",
  "cuda": "12.1",
  "diffusers": "0.27.0",
  "numpy": "1.26.4",
  "opencv": "4.9.0.80",
  "onnx": "1.15.0",
  "pillow": "10.0.0",
  "python": "3.10.12",
  "torch": "2.1.2+cu121",
  "torchvision": "0.16.2",
  "transformers": "4.38.2",
  "xformers": null
}

### What happened

When I add a T2I adapter to the linear generation, add a control image, and then attempt to generate an image, the following error message pops up in the UI: 
```
Value Error, invalid collector node t2i_adapter_collect. Path: body.batch.collect
```
There are no errors in the server log. I have tried rebuilding the front end, clearing the browser cache, etc.

### What you expected to happen

I expected image generation to start.

### How to reproduce the problem

1. In the linear view, select an sd-1.5 model.
2. Press `+ T2I Adapter`
3. Select the `canny-sd15` T2I processor
4. Drag and drop an image into the control image panel (keep default settings)
5. Type a prompt and press “Invoke”

### Discord username

l.stein

**Comment by psychedelicious** [comment]
I fixed this issue a few days ago. It was a race condition resulting from some async code not being awaited, no ambiguity as to the cause. I can't seem to reproduce it locally, is it possible you were a few commits behind?

**Comment by psychedelicious** [comment]
I think this was just related to stale UI build.
