### ISSUE TITLE
[bug]: can't disable the nsfw filter

### ISSUE THREAD

**Issue by sammcj** [invoke-ai/InvokeAI#5988]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 3090

### GPU VRAM

24

### Version number

4.0.0-rc2

### Browser

Firefox 123.0.1

### What happened

the invokeai docs state that to disable the nsfw filter you pass the parameter `--no-nsfw_filter`, however this doesn't work:

```yaml
command: ["invokeai-web", "--host", "0.0.0.0", "--no-nsfw_checker"]
```

```text
[2024-03-19 09:56:32,072]::[InvokeAI]::INFO --> NSFW checker initialized
```

When running interactively it seems this flag is not recognised:

```
invokeai-web --no-nsfw_checker
Unknown args: ['--no-nsfw_checker']
```

### What you expected to happen

- The NSFW checker not to be loaded (this is desired to improve performance)
- A config parameter in invokeai.yaml that can be set to disable it so that the container entrypoint command doesn't have to be overridden.

### How to reproduce the problem

- Launch invokeai via docker/docker-compose.
- Set the command to include the --no-nsfw_checker
- Check the logs after starting the container and load the app

### Additional context

[docs](https://invoke-ai.github.io/InvokeAI/installation/010_INSTALL_AUTOMATED/#out-of-memory-issues)

<img width="680" alt="image" src="https://github.com/invoke-ai/InvokeAI/assets/862951/f40e43f5-49f9-491b-818e-8d83bec3b4cf">

### Discord username

protoporpoise

**Comment by sammcj** [comment]
Oh neat, thanks @psychedelicious , so do we just add `--config no-nsfw_filter` now?

**Comment by psychedelicious** [comment]
@sammcj Sorry - I thought I had replied to this thread yesterday to explain the solution.

No, you don't need to do anything. The NSFW model download is now deferred until it is first requested. If you never enable it explicitly in the UI settings, it will never be downloaded or loaded.

Same goes for some of the other "support" models, like the upscalers or checkpoint-to-diffusers conversion models. They are downloaded when first requested.

**Comment by sammcj** [comment]
Oh in Discord - sorry I missed that. Thanks for clarifying!
