### ISSUE TITLE
[bug]: TypeError: Cannot read properties of undefined (reading 'maxClip')

### ISSUE THREAD

**Issue by daweishen** [invoke-ai/InvokeAI#6000]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### Version number

4.0.0rc2

### Browser

edge

### What happened

this page popped up when I visited http://127.0.0.1:9090

### What you expected to happen

load the page normally

**Comment by psychedelicious** [comment]
Thanks, I've run into this too but was doing some other fancy dev stuff and assumed it was not a problem with the actual app.
