### ISSUE TITLE
[bug]: [4.0.0] Hotkeys interfere with Model Selection

### ISSUE THREAD

**Issue by grunblatt-git** [invoke-ai/InvokeAI#6011]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

macOS

### GPU vendor

Apple Silicon (MPS)

### GPU VRAM

16

### Version number

4.0.0rc4

### Browser

Chrome

### What happened

In the v4.0.0 release candidates the dropdown menus for Model- and ControlNet selection do not allow to filter/ search for the model anymore.
These dropdowns used to behave like the dropdowns for LoRA and Scheduler selection: After opening the selection, you could type in part of the modelname to filter (and press enter to confirm) the selection. However with the 4.0.0 release candidates, typing with these dropdowns open will trigger the hotkeys of the Invoke UI (i.e "T" will hide the side panel, "A" will apply all settings of the selected image etc.).

### What you expected to happen

The Model (and ControlNet) selection should provide a way to search/ filter the available models. Imho the behavior of the LoRA/ Scheduler Selection is perfect.

### How to reproduce the problem

Click on the model selection and start typing the name of any model.

### Additional context

It seems like another kind of dropdown was introduced to display meta-information of the models. I assume changing the filter-functionality was not intentional

**Comment by psychedelicious** [comment]
You are correct, a different component was used in an attempt to fix some issues with the other component. The new component doesn't support text entry and also has another weird technical issue. I'll revert to the other component.

The new component also doesn't have a scrollbar, so that's another ding against it.

**Comment by ufuksarp** [comment]
I guess this also fixes the slight lag on dropdowns?
