### ISSUE TITLE
[bug]: Symlinked models cannot be deleted in Model Manager

### ISSUE THREAD

**Issue by Harvester62** [invoke-ai/InvokeAI#6034]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

GTX 1070

### GPU VRAM

8GB

### Version number

4.0.0rc5

### Browser

Firefox 123.0.1

### What happened

I had several models symlinked in InvokeAI and noticed that if I try to delete such a symlinked model using the delete button in the Model Manager beside the model, InvokeAI fails complaining not to be able to rmtree on a symbolic link.
To circumvent such complain, I shutdown the application, delete the symbolic links in IAI, then restart the app to refresh its database.
Here follow a screenshot of the console traceback errors:

![image](https://github.com/invoke-ai/InvokeAI/assets/29801031/56a809ce-db87-4459-899c-b02173f3e678)

### What you expected to happen

In theory, it should delete the symbolic link.

### How to reproduce the problem

In the specific, I symlinked the SD1.5 diffusers model inside C:\invokeai4\models\sd-1\main, then tried to delete it from MM.

![image](https://github.com/invoke-ai/InvokeAI/assets/29801031/867bdac6-355b-49e0-880f-34a8470e1af3)

**Comment by hipsterusername** [comment]
Not a blocker for 4.0, but should be tracked and fixed as a lower priority bug.

**Comment by Harvester62** [comment]
Sure, that's fine.

**Comment by lstein** [comment]
I'm assuming that the source of the symlink is in the `models` directory?

**Comment by Harvester62** [comment]
The source of the symlinked models is in my second HDD
![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/95cbf04f-4fb1-4490-aebf-30ecfb65b7e7)
