### ISSUE TITLE
Variations feature with k_euler_a sampler gives radically different results each call

### ISSUE THREAD

**Issue by spezialspezial** [invoke-ai/InvokeAI#604]
Just wanted to check if the variations feature is supposed to not really work with the k_euler_a and k_dpm_2_a samplers. At the moment the tiniest amount value gives radically different results, unlike other sampler like k_lms that works fine. 

To reproduce run for example: 

`a portrait of a woman standing on the street, art by James Gilleard -n4 -Ak_euler_a -W512 -H768 -s25 -C9 -S2823357340 -v0.000000000001`

and check the rendered images.

Though k_euler_a seems very dynamic, looking at changing step count, so I was wondering if this is either the expected behavior or might be an issue in the noise generation. Any ideas?

**Environment**
- GPU: cuda
- VRAM: 10GB
- CPU arch: x86
- OS: Linux
- Python: miniconda
- Branch: main 
- Commit: 89da37

**Comment by blessedcoolant** [comment]
I think this is because k_euler_a never really converges as other samplers do. If you do different steps with k_euler_a, you will find that it produces entirely different images as the steps go on rather than just refining the image. That's why noise variation with k_euler_a ends up creating drastically different images. Or so is my understanding of it.

The variation system itself works fine because it does what it is supposed to on most of the samplers.

**Comment by lstein** [comment]
As an aside, I think it would be a community service for someone to write up a "samplers for dummies" one-pager that explains from an end-users' perspective what they can expect from the different samplers. They each seem to have their special advantages and quirks.

**Comment by Any-Winter-4079** [comment]
One thing I have figured out, is that for nature and simple things, k_euler and low number of steps work just fine and is representative of results at larger step values.
<img width="1190" alt="Screenshot 2022-09-16 at 16 20 41" src="https://user-images.githubusercontent.com/50542132/190661282-356cdca4-2d04-47bb-9704-ced21ec300af.png">

You can do e.g. 8 steps and if you like the base concept, you can increase steps to improve details. Saves a lot of computation time.

**Comment by tildebyte** [comment]
@Any-Winter-4079; Following on to @lstein's suggestion, would you mind turning your last post into a Markdown doc in a PR? It's at least a start at making a "samplers tips" page

**Comment by Any-Winter-4079** [comment]
> @Any-Winter-4079; Following on to @lstein's suggestion, would you mind turning your last post into a Markdown doc in a PR? It's at least a start at making a "samplers tips" page

Will do. For example in `docs/help` called `Samplers_tips.md`?

**Comment by tildebyte** [comment]
Judgement call... I'm going to say `docs/help` (make sure that you're working in the 'development' branch!)

**Comment by Any-Winter-4079** [comment]
> Judgement call... I'm going to say `docs/help` (make sure that you're working in the 'development' branch!)

Yeah, that was my initial thought, but when I saw there was a `TROUBLESHOOT.md` in `docs/help` it made me question my choice, as they are not super related.

In any case, it can be easily moved (and probably will be as it grows with more content)
I'll go with `docs/help` for now :)

**Comment by blessedcoolant** [comment]
@Any-Winter-4079 k_euler converges pretty well. The discussion in this thread is about k_euler_a which produces pretty different results at various steps.

**Comment by Any-Winter-4079** [comment]
I'm close to finishing the document. Hopefully it'll be ready by tonight

**Comment by Any-Winter-4079** [comment]
> @Any-Winter-4079 k_euler converges pretty well. The discussion in this thread is about k_euler_a which produces pretty different results at various steps.

I know, I know. We kinda got off topic :)
