### ISSUE TITLE
[bug]:  4.0.0rc5 Cancelling Pending queue item force in progress item to incorrectly complete

### ISSUE THREAD

**Issue by Vargol** [invoke-ai/InvokeAI#6049]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

macOS

### GPU vendor

Apple Silicon (MPS)

### GPU model

M3

### GPU VRAM

24Gb

### Version number

4.0.0rc5

### Browser

Safari 17.4

### Python dependencies

{
  "accelerate": "0.28.0",
  "compel": "2.0.2",
  "cuda": null,
  "diffusers": "0.27.0",
  "numpy": "1.26.4",
  "opencv": "4.9.0.80",
  "onnx": "1.15.0",
  "pillow": "10.2.0",
  "python": "3.10.13",
  "torch": "2.3.0",
  "torchvision": "0.18.0",
  "transformers": "4.38.2",
  "xformers": null
}

### What happened

Set up a Text 2 Image render
Change the Invoke count next to the invoke button to 5.
Pressed Invoke
Went to the Queue Manager
Canceled one of the pending items (can use either pressing the 'x' and the Cancel Item button)
The selected Item canceled but the In Progress item completes after a short time (assuming at the end of the current step) despite have many steps left to go

### What you expected to happen

The pending item gets cancels the In Progress item continues to iterate until it is totally finished.

### How to reproduce the problem

Set up a Text 2 Image render
Change the Invoke count next to the invoke button to 5.
Pressed Invoke
Went to the Queue Manager
Cancel one of the pending items (can use either pressing the 'x' and the Cancel Item button)
The selected Item will cancel but the In Progress item will also complete after a short time (assuming at the end of the current step) despite have many steps left to go.

### Additional context

Also the same happen fir inpainting, I haven't tried all the other but I guess its a queue management issue or would occurs for all.

**Comment by hipsterusername** [comment]
@Vargol - Is this just a visual bug in the queue manager or is it returning a broken image?

**Comment by hipsterusername** [comment]
NVM - Just read the discord message :)

**Comment by Vargol** [comment]
Thats okay, but just for the record, the In Progress render just disappears into the ether and I get 3 images out of 5  added to the  Gallery.
