### ISSUE TITLE
[bug]: Cancelling an item from the Queue also cancels the current generation

### ISSUE THREAD

**Issue by grunblatt-git** [invoke-ai/InvokeAI#6089]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

macOS

### GPU vendor

Apple Silicon (MPS)

### Version number

4.0.0rc6

### Browser

Chrome

### What happened

Cancelling an item in the "Queue" tab also cancels the current generation in addition to the selected item.

### What you expected to happen

When cancelling an item from the queue, no other generations should be affected - i.e. only that single item gets cancelled,

### How to reproduce the problem

Queue up several generations, go to the "Queue" Tab and cancel an item from the middle of the list. The Item that is currently in progress will never show up in the gallery.

### Additional context

There might be additional issues with cancelling items in the queue since 4.0.0. However i could not properly reproduce these yet:

I had the impression that sometimes more items than just the current generation get cancelled and sometimes it seems that all steps of the current generation still complete, but the image just never shows up in the gallery.

**Comment by psychedelicious** [comment]
#6078 should fix this, did not make it into RC6 though
