### ISSUE TITLE
[bug]: Unable to resume after pausing the processor 

### ISSUE THREAD

**Issue by grunblatt-git** [invoke-ai/InvokeAI#6090]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

macOS

### GPU vendor

Apple Silicon (MPS)

### Version number

4.0.0rc6

### Browser

Chrome

### What happened

Generation gets stuck when pausing the processor from the "Queue" tab:
After pausing generation the generation cannot be resumed. I was not able to resolve this in the UI and it seems like there is no way to restart the generation on the items that are already in the queue. After restarting invoke, these items get cleared from the queue. 

### What you expected to happen

The image generation can be paused and resumed via the UI

### How to reproduce the problem

1. Queue up any amount of generations
2. Go to the Queue tab
3. Click "Pause Processor"
4. Wait for the current generation to complete
5. -> all leftover items automatically switch to the status "In Progress"
6. Click "Resume Processor"
7. The Generation does not start

Any Items that are added to the queue afterwards will generate properly again.

**Comment by psychedelicious** [comment]
Thanks, fixed in #6091
