### ISSUE TITLE
[bug]: Image data not saved

### ISSUE THREAD

**Issue by fable0301** [invoke-ai/InvokeAI#6092]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

1080 TI

### Version number

3.7.0

### Browser

Brave

### What happened

Hello, I've been having a problem for a while now, the generations I make don't record any data. As a result, I can no longer use these options: Remix Image, Use prompt, use seed, use all...

I've tried different models (1.5 and XL) and nothing changes.

Thanks for your help.

### What you expected to happen

That all generations have their own integrated data.

### How to reproduce the problem

No idea

**Comment by psychedelicious** [comment]
Please download one of the affected images, add it to a zip file, and upload to this issue.

**Comment by hipsterusername** [comment]
For the sake of clarity, do you have either NSFW Image checking or Watermarking on?

**Comment by fable0301** [comment]
Thank you for your reply, the problem was indeed with the invisible watermark option... I couldn't find any information on google and I didn't think this option concerned the data generated for each image... Thank you for your help.

**Comment by psychedelicious** [comment]
Should still have metadata on it - reopening for a future fix

**Comment by fable0301** [comment]
Yes, and this option is activated by default as soon as I reopen invokeai, even though I deactivated it the previous session.

**Comment by psychedelicious** [comment]
This was recently resolved in #6360.
