### ISSUE TITLE
[enhancement]:  add Render Density like leonardo.ai

### ISSUE THREAD

**Issue by wolfkingal2000** [invoke-ai/InvokeAI#6093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

 add Render Density like  https://app.leonardo.ai/canvas make high details like  Scale Before Processing but scale and can make low scale for  high image resolution can make vr less
![opera_BQvnofSbT0](https://github.com/invoke-ai/InvokeAI/assets/131250049/72bc93fa-fae0-4d1f-b144-747278133975)
![opera_nbpc4ZAUx4](https://github.com/invoke-ai/InvokeAI/assets/131250049/65ecc067-93e7-4d4f-99d9-99542ece09e9)

**Comment by psychedelicious** [comment]
Invoke v5 features a full rewrite of the canvas. Please create a new GH issue if the problem still exists in the new canvas UI.
