### ISSUE TITLE
[bug]: 4.0.0rc6 - Configuration fails with "ModuleNotFoundError: No module named 'invokeai.frontend.install.invokeai_configure'"

### ISSUE THREAD

**Issue by RebootedDuck** [invoke-ai/InvokeAI#6094]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 3060 Max-Q

### GPU VRAM

6GB

### Version number

4.0.0rc6

### Browser

Firefox

### What happened

I try to select manual configuration and the error "ModuleNotFoundError: No module named 'invokeai.frontend.install.invokeai_configure'" is thrown

### What you expected to happen

Configuration is successful

### How to reproduce the problem

Run 4.0.0rc6 installer and select manual configuration

**Comment by psychedelicious** [comment]
There is no configuration script in v4. Please review the release notes for RC6, which have links to documentation: https://github.com/invoke-ai/InvokeAI/releases/tag/v4.0.0rc6

To fix your launcher (which erroneously attempts to load the non-existent configure script), download the latest installer from the linked release and use it to install. You won't lose any data, but it should update the old launcher script. The new one only has 4 options.

**Comment by RebootedDuck** [comment]
Oh sorry, I didn't see that note, thanks :)

**Comment by psychedelicious** [comment]
No worries :)

**Comment by sergeiissaev** [comment]
I have the same issue trying to install 4.2.0 on mac. I get to the step where it asks automatic or manual, I select automatic then I get the error: 
```
Choose <a>utomatic or <m>anual configuration [a/m] (a): a
Traceback (most recent call last):
  File "/Users/sergei.issaev/Downloads/InvokeAI-Installer/./lib/main.py", line 52, in <module>
    inst.install(**args.__dict__)
  File "/Users/sergei.issaev/Downloads/InvokeAI-Installer/lib/installer.py", line 153, in install
    self.instance.configure()
  File "/Users/sergei.issaev/Downloads/InvokeAI-Installer/lib/installer.py", line 271, in configure
    from invokeai.frontend.install.invokeai_configure import invokeai_configure
ModuleNotFoundError: No module named 'invokeai.frontend.install.invokeai_configure'
```

**Comment by psychedelicious** [comment]
@sergeiissaev Please carefully read and follow the `Installation and Updating` instructions on the [release page](https://github.com/invoke-ai/InvokeAI/releases/tag/v4.2.0).
