### ISSUE TITLE
[bug]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 59: invalid continuation byte

### ISSUE THREAD

**Issue by cmensah** [invoke-ai/InvokeAI#6105]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 3050

### GPU VRAM

8GB

### Version number

4.0.0

### Browser

Chrome

### What happened

I was trying to update to the latest version.. then this error : 
***** Checking and Updating Python *****
Initializing the installer. This may take a minute - please wait...
Actual environment location may have moved due to redirects, links or junctions.
  Requested location: "C:\Users\SOMBRE~1\AppData\Local\Temp\invokeai-installer-tmpwb2fytyg\Scripts\python.exe"
  Actual location:    "C:\Users\Sombre Clarté\AppData\Local\Temp\invokeai-installer-tmpwb2fytyg\Scripts\python.exe"
Traceback (most recent call last):
  File "C:\Users\Sombre Clarté\Downloads\InvokeAI-installer-v4.0.0\InvokeAI-Installer\lib\main.py", line 50, in <module>
    inst = Installer()
           ^^^^^^^^^^^
  File "C:\Users\Sombre Clarté\Downloads\InvokeAI-installer-v4.0.0\InvokeAI-Installer\lib\installer.py", line 48, in __init__
    self.bootstrap()
  File "C:\Users\Sombre Clarté\Downloads\InvokeAI-installer-v4.0.0\InvokeAI-Installer\lib\installer.py", line 88, in bootstrap
    res = upgrade_pip(Path(venv_dir.name))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sombre Clarté\Downloads\InvokeAI-installer-v4.0.0\InvokeAI-Installer\lib\installer.py", line 319, in upgrade_pip
    result = subprocess.check_output([python, "-m", "pip", "install", "--upgrade", "pip"]).decode()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 59: invalid continuation byte
Appuyez sur une touche pour continuer...

### What you expected to happen

Version 4.0.0

### How to reproduce the problem

Start the install.bat

**Comment by hipsterusername** [comment]
@lstein - Do you think this might be system specific?

**Comment by cmensah** [comment]
Maybe i need to add this :  
-my system is in French
- my python version is 3.11.5
- my pip version is 24.0
Previous InvokeAI version was working great

**Comment by hipsterusername** [comment]
> Maybe i need to add this : -my system is in French
> 
>     * my python version is 3.11.5
> 
>     * my pip version is 24.0
>       Previous InvokeAI version was working great

Yes, that seems to be the case - But that's an issue _we_ need to fix I think

**Comment by psychedelicious** [comment]
It appears the `é` character in `Sombre Clarté` is the issue. 

Please open a command line window and try this command. Does it error?
```cmd
python -c "import subprocess; print(subprocess.check_output('echo Sombre Clarté', shell=True).decode())"
```

Next, try this command. Does it error?
```cmd
python -c "import subprocess; print(subprocess.check_output('echo Sombre Clarté', shell=True).decode("utf-8"))"
```

**Comment by cmensah** [comment]
Okay,.
First : 
`C:\Users\Sombre Clarté>python -c "import subprocess; print(subprocess.check_output('echo Sombre Clarté', shell=True).decode())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 12: invalid start byte

C:\Users\Sombre Clarté>python -c "import subprocess; print(subprocess.check_output('echo Sombre Clarté', shell=True).decode())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 12: invalid start byte`


Second :


`C:\Users\Sombre Clarté>python -c "import subprocess; print(subprocess.check_output('echo Sombre Clarté', shell=True).decode("utf-8"))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'utf' is not defined
`

**Comment by psychedelicious** [comment]
@cmensah I apologize, I had a typo in the second command - please try this one:

```
python -c "import subprocess; print(subprocess.check_output('echo Sombre Clarté', shell=True).decode('utf-8'))"
```

Hopefully this works without an error, and we can update the installer to handle `é`.

**Comment by cmensah** [comment]
> @cmensah I apologize, I had a typo in the second command - please try this one:
> 
> ```
> python -c "import subprocess; print(subprocess.check_output('echo Sombre Clarté', shell=True).decode('utf-8'))"
> ```
> 
> Hopefully this works without an error, and we can update the installer to handle `é`.

-----
Microsoft Windows [version 10.0.19045.3693]
(c) Microsoft Corporation. Tous droits réservés.

C:\Users\Sombre Clarté>python -c "import subprocess; print(subprocess.check_output('echo Sombre Clarté', shell=True).decode('utf-8'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 12: invalid start byte

C:\Users\Sombre Clarté>

**Comment by psychedelicious** [comment]
Oh boy, fun. 

We have another related issue with an unexpected encoding here: https://discord.com/channels/1020123559063990373/1020123559831539744/1225085570032865291

In this case, the user (also with French characters) is getting an error when we attempt to read their config file into memory:

![image](https://github.com/invoke-ai/InvokeAI/assets/4822129/54672895-8f95-49c4-b3b1-7e6ecc7c2330)
