### ISSUE TITLE
No clear way to update from CLI install 

### ISSUE THREAD

**Issue by Lolagatorade** [invoke-ai/InvokeAI#6125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

lolagatorade@icloud.com

### What should this feature add?

No clear way to update from a install

cd invokeai 
Source .venv/bin/active 
InvokeAI-update

https://invoke-ai.github.io/InvokeAI/features/UTILITIES/

according to the prior document it should work and was updated pretty recently.  I get the latest release does not have that as a feature anymore but there is absolutely no clear cut way to do an update anymore as it’s impossible to do it by CLI and it looks like it’s forcing me to do a full reinstallatuin to use the future updated versions.   

### Alternatives

Return the cli for updating, or a GUI update tool. Something intuitive. Now it’s a dead end with no way to update.

**Comment by hipsterusername** [comment]
The installer is an updater. If you use the installer, it'll provide you the ability to install updates into the same folder - nothing will be overwritten.

**Comment by Lolagatorade** [comment]
> The installer is an updater. If you use the installer, it'll provide you the ability to install updates into the same folder - nothing will be overwritten.

attempted with the 4.0.4 installer gave following error tried with and without elevating permissions still gave same error. no way to update with the new method other than deleting the current install from what i see.







![image](https://github.com/invoke-ai/InvokeAI/assets/42100725/b48360a6-c2dc-4562-b6ec-b647a56ed104)


sudo sh install.sh                                                                                                                         ✔  16s  
[sudo] password for deadbolt: 
Initializing the installer. This may take a minute - please wait...
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
╔═════════════════════════════════════════════════════════════════════════════ Welcome to the InvokeAI Installer ═════════════════════════════════════════════════════════════════════════════╗
║                                                                                                                                                                                             ║
║        Some of the installation steps take a long time to run. Please be patient. If the script appears to hang for more than 10 minutes, please interrupt with Control-C and retry.        ║
║                                                                                                                                                                                             ║
║                                                                        🠶 Latest stable release (recommended): 4.0.4                                                                         ║
║                                                                       🠶 Last published pre-release version: 4.0.0rc6                                                                        ║
║                                                                                                                                                                                             ║
╚═══════════════════════════════════════════════════════════════════════════════════════ Linux-x86_64 ════════════════════════════════════════════════════════════════════════════════════════╝

❔ Please choose an Invoke version to install.
   <Enter> to install the recommended release (4.0.4). <Tab> or type to pick a version:
   Version 4.0.4 will be installed.


❔ Please select the install destination: [/root/invokeai]: 
>>> /home/deadbolt/invokeai

🛑 Directory /home/deadbolt/invokeai already exists!
   Is this location correct?
   Please confirm: [y/n] (n): y

Traceback (most recent call last):
  File "/home/deadbolt/Downloads/InvokeAI-Installer/./lib/main.py", line 53, in <module>
    inst.install(**args.__dict__)
  File "/home/deadbolt/Downloads/InvokeAI-Installer/lib/installer.py", line 153, in install
    self.venv = self.app_venv(venv_parent=destination)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deadbolt/Downloads/InvokeAI-Installer/lib/installer.py", line 113, in app_venv
    venv.create(venv_dir, with_pip=True)
  File "/usr/local/lib/python3.11/venv/__init__.py", line 468, in create
    builder.create(env_dir)
  File "/usr/local/lib/python3.11/venv/__init__.py", line 74, in create
    self.setup_python(context)
  File "/usr/local/lib/python3.11/venv/__init__.py", line 292, in setup_python
    copier(context.executable, path)
  File "/usr/local/lib/python3.11/venv/__init__.py", line 235, in symlink_or_copy
    shutil.copyfile(src, dst)
  File "/usr/local/lib/python3.11/shutil.py", line 258, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
OSError: [Errno 26] Text file busy: '/home/deadbolt/invokeai/.venv/bin/python3.11'
