### ISSUE TITLE
Breaking change in GFPGAN refactoring

### ISSUE THREAD

**Issue by santisbon** [invoke-ai/InvokeAI#614]
**Describe your environment**
- GPU: [cuda/amd/mps/cpu] CPU
- CPU arch: [x86/arm] arm64
- OS: [Linux/Windows/macOS] Linux
- Python: [Anaconda/miniconda/miniforge/pyenv/other (explain)] Miniconda only to create env and use `CONDA_SUBDIR`. Reqs installed from txt file with pip.
- Branch: [if `git status` says anything other than "On branch main" paste it here] main

**Describe the bug**
This seems to affect only linux/**arm**64 which I need for local testing of [#491 ](https://github.com/lstein/stable-diffusion/pull/491) on M1/M2. I'm using CPU here because Docker can't access the GPU cores in Apple silicon. If you have Apple silicon you'll need to run the Linux container on M1/M2 for local testing before building for and shipping to a production environment with linux/**amd**64.

On a branch I have before the refactoring of how GFPGAN is installed, it works.

On main, it breaks. First I get this warning on startup of the dream script (with full precision) as it can't load `image`. On file `/usr/local/lib/python3.9/dist-packages/torchvision/io/image.py`:

`from ..extension import _load_library
...
try:
    _load_library("image")
except (ImportError, OSError) as e:
    warn(f"Failed to load image Python extension: {e}")`

Then when I try to generate an image:
`File "/usr/local/lib/python3.9/dist-packages/torch/nn/functional.py", line 2516, in group_norm
    return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: expected scalar type BFloat16 but found Float`

What I already know:
- The reqs file for this scenario (linux/arm64) needs lstein/k-diffusion instead of Birch-san/k-diffusion.git@mps.
- torchvision went from 0.12.0 to 0.13.0
- GFPGAN now comes from lstein/GFPGAN@fix-dark-cast-images.
- The BFloat16 error used to appear to people running it without --full_precision. I'm using full precision.
- You now need to download GFPGANv1.3.pth. That one and sd-v1-4.ckpt (as model.ckpt) are in the correct place.
- If I switch to installing dependencies with a conda .yaml file instead of pip-only, I'll need to figure out which channels/dependencies/pip section/env variables to use for that file to work on linux/arm64. With the .txt file and pip I already have it working pre-GFPGAN refactor. But if you have suggestions for the .yaml I'll try them out.

What I don't know:
- What else do I need to account for in my reqs or when setting up?

Any ideas for something I may be missing? It'd probably be related to pytorch or something introduced at the same time as the GFPGAN refactoring.

**Comment by nullbuddy1243** [comment]
am facing something similar, watching
