### ISSUE TITLE
[enhancement]: Colour picker should be able to pick colours from outside the bounding box by default without a switch

### ISSUE THREAD

**Issue by ufuksarp** [invoke-ai/InvokeAI#6169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Currently you can't pick colours from outside the bounding box without turning off the canvas setting `Limit Strokes to Box`. This setting shouldn't dictate the colour picker behaviour.

**Comment by ufuksarp** [comment]
I see that it actually can, but the picker cursor disappears, signaling otherwise.

**Comment by psychedelicious** [comment]
This is implemented in Canvas v2, color picker works anywhere
