### ISSUE TITLE
[bug]: Referencing SDXL model causes program exceptions

### ISSUE THREAD

**Issue by chen-io** [invoke-ai/InvokeAI#6185]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX4070s

### GPU VRAM

12GB

### Version number

ex.4.0.4

### Browser

ex.Google Chrome 123.0.6312.59

### What happened

Adding and importing SDXL models from external sources (WebUI) cannot load and run normally. If the model is placed in the InvokeAI default model directory, it can be loaded and run normally.

### What you expected to happen

Hope to run normally

### How to reproduce the problem

Scan external directories to install SDXL models and use them

**Comment by psychedelicious** [comment]
> Adding and importing SDXL models from external sources (WebUI) cannot load and run normally. If the model is placed in the InvokeAI default model directory, it can be loaded and run normally.

Please include detail about exactly how your are importing the model, and the exceptions.
