### ISSUE TITLE
Merge two existing images [enhancement]: 

### ISSUE THREAD

**Issue by ciriguaya** [invoke-ai/InvokeAI#6192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

ciriguaya@me.com

### What should this feature add?

I know it is possible to generate two images inside of the unified canvas and merge them, but what would be great is to be able to merge two existing images either imported or generated before. It would give more flexibility in combining work done in seperate sections of InvokeAI. 

But in general i have to say I'm super impressed with InvokeAI! Most polished and fun to use interface out there!

**Comment by psychedelicious** [comment]
This is implemented in Invoke v5
