### ISSUE TITLE
[bug]: Can't convert checkpoints to diffusers formats

### ISSUE THREAD

**Issue by Togi1234** [invoke-ai/InvokeAI#6199]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

2080 Ti

### GPU VRAM

11

### Version number

4.0.4

### Browser

Chrome 123.0.6312.106

### What happened

I can't generate images. When I click "Invoke", the console say  : [ModelLoadService]::INFO --> Converting E:\invokeai\models\sdxl\main\ANYMODEL.safetensors to diffusers format

I don't have any errors, it just get stuck there for life. If I try to do it from the mod manager, it does the same. I click convert, the conseol give me the line and then it remain stuck. 

### What you expected to happen

It used to work before, I have no idea how to fix. I used to click "Invoke", to pass the convert step and to get my images. 

### How to reproduce the problem

Start the app, try to generate an image with any models, get stuck

### Additional context

I tried to install from scratch (python and invoke), to update to 4.0.4, to download the models again, to clear my disk... nothing work

**Comment by psychedelicious** [comment]
Please share an example model that doesn't convert. We'll need to test with it.

**Comment by Togi1234** [comment]
That one, but I have the problem with all the models. 
https://civitai.com/models/257749/pony-diffusion-v6-xl?modelVersionId=290640
