### ISSUE TITLE
[bug]: Can't start webUI: Can't pass 127.0.0.1:9090

### ISSUE THREAD

**Issue by fuzy4d** [invoke-ai/InvokeAI#6206]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### Version number

4.0.4

### Browser

Firefox 124.0.2

### What happened

I just installed invokeAI 4.0.4. Everything is OK, But when i start invoke.bat, I get some red error:

[2024-04-12 13:01:28,799]::[uvicorn.error]::ERROR --> [Errno 13] error while attempting to bind on address ('127.0.0.1', 9090): an attempt was made to access a socket in a way forbidden by its access permissions:

I use tcpview to make sure that none app occupy the 9090 port.
I add  firewall new rules to open 9090 port in inbound rules and outbound rules. 
But it still doesn't work. 
How can I do, Please help.

### What you expected to happen

Just get it work.

**Comment by fuzy4d** [comment]
Here is the snapshot
![2024-04-12_132456](https://github.com/invoke-ai/InvokeAI/assets/95534786/5bbbc59c-bac0-44ec-90db-e0bf131253b1)

**Comment by psychedelicious** [comment]
This means your OS cannot bind to the address. Maybe restarting would fix it. Could also edit your `invokeai.yaml` file and use a different port if that doesn't work.

**Comment by fuzy4d** [comment]
Thank you for your reply, It's work! I didn't realize it could be solved this way.

**Comment by psychedelicious** [comment]
No worries :)
