### ISSUE TITLE
Upload multiple images as assets [enhancement]: 

### ISSUE THREAD

**Issue by shanedk** [invoke-ai/InvokeAI#6207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Discord: shanedk

### What should this feature add?

The ability to drag-and-drop multiple images to a board and have them import as assets. As it is, only individual PNG or JPEG files can be imported.

### Additional Content

I've run into this annoyance several times. Here's my latest experience, for a real-world example:

I downloaded an OpenPose collection so I could have ready-made poses to use: https://civitai.com/models/22214/openposes-collection

This is a collection of 47 poses. I'd like to put them into a "Poses" board as Assets so I can go to it any time I want and just grab the pose. As it is, I have to drag each of the 47 poses individually into Invoke to get them in as assets.

I should be able to just drag them all in at once. It would add them all as Assets for the current board and I could start using them, in ControlNets, IP Adapters, or whatever.

**Comment by maryhipp** [comment]
Closed with https://github.com/invoke-ai/InvokeAI/pull/7123
