### ISSUE TITLE
How to uninstall InvokeAI

### ISSUE THREAD

**Issue by caoyuanlianni** [invoke-ai/InvokeAI#6208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

How to uninstall InvokeAI？
I don’t know where InvokeAI is installed. I looked at the specified installation directory, but there are only startup scripts and some configuration files.

**Comment by psychedelicious** [comment]
Invoke uses a python virtual environment. It's in the installation directory, but is typically hidden. If you enable hidden files in your file browser, you will see it.

To uninstall Invoke, just delete the whole installation folder.

**Comment by yuekatoang** [comment]
I installed in E: but now i have 20 gb in C:

there are hidden files?
