### ISSUE TITLE
Enabling unconditional_conditioning for prompts.

### ISSUE THREAD

**Issue by rabidcopy** [invoke-ai/InvokeAI#621]
**Is your feature request related to a problem? Please describe.**
Several forks I've come across have discovered that an existing string known as unconditional_conditioning is unused by default. When enabled and passed onto the sampling process it acts as an inhibitor of vectors that come from the words provided to unconditional_conditioning.

**Describe the solution you'd like**
Enabling of unconditional_conditioning and an option in dream that can be passed like this as an example.
```dream> a picture of a pet -u "dog"```
```dream> a picture of a pet -u "cat"```

**Describe alternatives you've considered**
There is the existing weights functionality but from my understanding, while it can reduce the emphasis of a subject, it can't negatively bias the appearance of a subject and in some cases positively influences it's presence in a result by being introduced at all.

**Additional context**
Here is a result using https://github.com/AUTOMATIC1111/stable-diffusion-webui which has implemented unconditional_conditioning as the feature known as  "Negative prompt."
![xy_grid-0069-1-a picture of a pet](https://user-images.githubusercontent.com/8052832/190726757-53955e65-b667-46de-b718-5f0de7836745.png)
The prompt was "a picture of a pet" using a seed of 1.
The top result is that prompt as is. (technically an asterisk is being biased)
The middle result is the same prompt with the inclusion of "dog" in the negative prompt field.
The bottom result is the same prompt with the inclusion of "cat" in the negative prompt field.

Amusingly I saw another user trying to get pictures of the animal pika, and not the Pokemon Pikachu.
![xy_grid-0071-1-a photograph of a pika outdoors](https://user-images.githubusercontent.com/8052832/190727960-25313b51-cc2e-4adf-ab43-096e775e359c.png)
By negatively conditioning the word "pikachu" the pika has become less yellow and has lost some redness around its cheeks.

**Comment by lstein** [comment]
How is this related to textual inversion?

**Comment by rabidcopy** [comment]
> How is this related to textual inversion?

It.. isn't? I understand this repo also provides a script for textual inversion training, but I was under the impression that the dream script was also a part of it? The asterisk isn't an embedding being used. The web ui I was using offers a x/y plot feature and the asterisk with dog, and then cat.

**Comment by lstein** [comment]
I see. It was I who was confused. I'll go ahead and add this to the wishlist. I can't give an expected ETA at the moment. I'll need a volunteer to work on this feature.

**Comment by rabidcopy** [comment]
> I see. It was I who was confused. I'll go ahead and add this to the wishlist. I can't give an expected ETA at the moment. I'll need a volunteer to work on this feature.

All good, I should of just painted out the asterisk in the result images as it could easily be confused with calling an embedding.

**Comment by tildebyte** [comment]
There's probably some overlap here with the incoming Cross-attention features, but tbh this looks quite nice for when one wants a quick and easy negative prompt

**Comment by rabidcopy** [comment]
> This seems to be a duplicate of #505 ?

The feature put on the todo list for that issue was Cross Attention Control. This is a different solution that uses code that's already present.

**Comment by psychedelicious** [comment]
This was implemented in #661 .
