### ISSUE TITLE
nvokeAI 4.0.4version  controlnet,  IP adapter T2i adapter and ability to change /add VAE are disableid, circle with line through middle

### ISSUE THREAD

**Issue by gman9500** [invoke-ai/InvokeAI#6212]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

M4000

### Version number

4.04

### Browser

firefox  121

### Python dependencies

InvokeAI 4.0.4version  controlnet,  IP adapter T2i adapter and ability to change /add VAE are disableid, circle with line through 

### What happened

InvokeAI 4.0.4version  controlnet,  IP adapter T2i adapter and ability to change /add VAE are disableid, circle with line through   
I can't click on them to activate them.  when mouse arrow goes over the, it changes to circle with line . like its disablled, but Idon't see in settings where to enable it

### What you expected to happen

to open up so I can use them

### How to reproduce the problem

just move the mouse arrow over them. for me , they don't open up or let me click on them to open them up.

**Comment by psychedelicious** [comment]
Do you have controlnet, ip adapter, t2i adapter and VAE models installed?

**Comment by gman9500** [comment]
I had a VAE model installed on previous version before upgrade.   But I can't add a copntrolnet pose  because it doesn't open up to let me add one.

**Comment by hipsterusername** [comment]
You need to check the Model Manager to see if they're there. If not, please check the FAQ  https://invoke-ai.github.io/InvokeAI/help/FAQ/ for guidance on reconnecting your old models.

**Comment by gman9500** [comment]
ok, I figured it out after you said check model manager  REscanned where I had VAE located. thanks. and just realized that the reason why control nets wasn't opening up is because I have to add it from the starter models.  I thought that was only for adding starter models , not everything.
