### ISSUE TITLE
[bug]: Unified Canvas - Invoke saves generated image on box selection area automatically

### ISSUE THREAD

**Issue by sonny4723** [invoke-ai/InvokeAI#6230]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 3060ti (Asus)

### GPU VRAM

8GB

### Version number

4.0.4

### Browser

Chrome, Edge, Brave

### What happened

Whenever I use Shift + S to save the generated image on Unified Canvas, beside saving the fullsize of generate image, Invoke also saves the generated image that in the box selection area to Gallery automatically. (I'm sure I uncheck the option "Save Box Region Only" on settings.

### What you expected to happen

I expected that Invoke save only the generate image full size only and not including save the image in the box region selection

### Discord username

sonny04723

**Comment by psychedelicious** [comment]
The staging area has a `shift+s` hotkey which seems to be getting triggered at the same time as the main `shift+s` hotkey. Will need to ensure that only one of these is active at a time.

**Comment by psychedelicious** [comment]
Invoke v5 features a full rewrite of the canvas. Please create a new GH issue if the problem still exists in the new canvas UI.
