### ISSUE TITLE
[bug]: Seed increments by one during iterations, regardless of other settings

### ISSUE THREAD

**Issue by fredkrampe** [invoke-ai/InvokeAI#6236]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 4090

### GPU VRAM

24

### Version number

4.0.4

### Browser

Firefox 124.0.2

### What happened

Seed increments by one during iterations.  If seed is non-random, the entered seed would increment every time a new image is generated.  If seed is random, the random seed is incremented every image.  

### What you expected to happen

I expect random seeds every image.  

### How to reproduce the problem

Not sure how to reproduce.

### Additional context

This started happening after I canceled a large batch.  Things I tried:
1. Rebooting PC.
2. Changing "Use CPU noise"
3. Upgrading to latest version of Invoke
4. Resetting WebUI
5. Clearing Intermediates

**Comment by psychedelicious** [comment]
Yes, that's how it works. It allows you to start from one seed and get the same series of noise tensors for a given batch.

Every seed produces a random noise tensor. A seed of 1 produces noise that is just as different from a seed of 2 as it is from a seed of 251056107. There's no relationship between seeds.

With that in mind, is there still some use case for non-incrementing seeds when queuing multiple generations?

**Comment by psychedelicious** [comment]
If you have a use case for non-incrementing seeds, please create a feature request for it.
