### ISSUE TITLE
[bug]: No more model merger?

### ISSUE THREAD

**Issue by rking2981** [invoke-ai/InvokeAI#6241]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 3060

### GPU VRAM

12gb

### Version number

4.0.4

### Browser

Firefox

### What happened

When visiting the Model Manager, I no longer see the Model Merging option. Where did it go? If it was removed, why?

### What you expected to happen

To be able to merge my models.

### Discord username

kingsman

**Comment by psychedelicious** [comment]
Yes, it was removed from the main app. We plan to add merging to https://github.com/invoke-ai/invoke-training but haven't gotten to it yet.

**Comment by rking2981** [comment]
Darn, ok. For some reason, when using that merge, I had no issues, but when I try using Automatic1111 model merging, it always says it runs out of memory. Never had that issue with Invokes model Merging. Hope it come back soon!

**Comment by psychedelicious** [comment]
Glad to hear it worked well for you. I've created a feature request on the training app to add merging: https://github.com/invoke-ai/invoke-training/issues/110

I'll close this issue in favor of the training repo issue once @RyanJDick confirms model merging is still in scope for the training app.

**Comment by psychedelicious** [comment]
Please see the linked feature request for the training app if you want model merging.
