### ISSUE TITLE
Image2Image fit option blends pixels when scaling down which ruins mask edges

### ISSUE THREAD

**Issue by mavispuford** [invoke-ai/InvokeAI#625]
**Describe your environment**
- GPU: RTX 3080 founders edition with i9 9900k
- VRAM: 12
- CPU arch: x86
- OS: Windows
- Python: miniconda
- Branch: main
- Commit: 89da371f4841f7e05da5a1672459d700c3920784

**Describe the bug**
When passing a masked image with "fit" enabled, it scales down the image and blends the pixels in the process.  This causes artifacts near the edges in the output.  Maybe there should be a "nearest neighbor" scaling option?

**To Reproduce**
Images:
Source image: 
![person-girl-woman-hair-photography-portrait-108386-pxhere com (1)](https://user-images.githubusercontent.com/2214272/190747828-8f36e598-b1b5-4c60-9457-923ddaec2e6a.jpg)
Large masked image (2496x1664):
![Mask-637989379517936043](https://user-images.githubusercontent.com/2214272/190756479-9e0b76eb-ea92-49d0-a0c0-564692cbfc25.png)
Small masked image (960x640):
![Mask-637989379593202687](https://user-images.githubusercontent.com/2214272/190756842-8d721d35-f909-4b87-9a01-1bacff00534a.png)

1. Enter a prompt ("a frowning woman") using the large masked image above, default settings (50 steps, strength .75) but with width at 960 and height at 640
2. Notice the seams around the masked area
3. Now try it with the small masked image
4. Notice that it is seamless

**Expected behavior**
There should be no seams/artifacts in the masked area.  The resulting image should be seamless

**Screenshots**
Large image output:
![000374 3113900562-artifacts](https://user-images.githubusercontent.com/2214272/190767569-c733bc38-0d12-4811-9006-88a4b1096cea.png)

Small image output:
![000375 820978995-seamless](https://user-images.githubusercontent.com/2214272/190767983-257bdf3c-36ba-4bc0-aab2-caef33933c2e.png)

**Additional context**
Could you add a nearest neighbor/non-filtered scaling option so the pixels don't get blurred?  I like the "fit" option because I don't have to resize images on my own, so it would be nice if it handled masked images well.

**Comment by lstein** [comment]
I see the problem. Would the [PIL.Image.Resampling.NEAREST](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Resampling.NEAREST) resampling filter be the best choice here?

**Comment by mavispuford** [comment]
@lstein Seems like that would do it.  There's definitely a quality difference when using nearest neighbor vs the other methods, though, so it'd probably be best as a parameter.  Either that or I suppose you could switch to nearest neighbor when transparent pixels/inpainting is detected.

**Comment by lstein** [comment]
I'll give it a try as soon as I get access to my development environment again. (It's an HPC cluster down for maintenance over the weekend). In the meantime, if you'd like to swap the nearest resampling in, just open the file ldm/dream/image_util.py, look for the line `resized_image = self.image.resize((rw,rh),resample=Image.Resampling.LANCZOS)` and change the resampling method to `Image.Resampling.NEAREST`

**Comment by mavispuford** [comment]
Seems to work for me. Here's my output using the large masked image with 960x960 chosen as the size:
![a_sad_woman-1228974340-637991001671014705-0](https://user-images.githubusercontent.com/2214272/190922377-1c2f51e2-8286-4f01-b9bd-fadf269378a0.png)

**Comment by lstein** [comment]
This should be fixed now.
