### ISSUE TITLE
[bug]: random disconnects 4.1.0

### ISSUE THREAD

**Issue by Lucretius0000** [invoke-ai/InvokeAI#6251]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

other

### GPU vendor

Nvidia (CUDA)

### GPU model

Google T4

### GPU VRAM

16

### Version number

4.1.0

### Browser

Chrome 

### What happened

Instances randomly disconnects casually, sometimes it disconnects altogether, other times only the instance forcing me to reboot

### What you expected to happen

Instances randomly disconnects casually, sometimes it disconnects altogether, other times only the instance forcing me to reboot

**Comment by psychedelicious** [comment]
It looks like you are using a cloud service. We can't troubleshoot issues there.

If you have this problem locally, please copy logs from the browsers network tab, JavaScript console and terminal.

Also please describe your network setup and what settings you are using on the host.

**Comment by psychedelicious** [comment]
Please create a new issue if you have this problem when running invoke locally on your own computer.
