### ISSUE TITLE
[bug]: NSFW checker is not working

### ISSUE THREAD

**Issue by shotgunner42** [invoke-ai/InvokeAI#6252]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

NVIDIA GeForce RTX 2060

### GPU VRAM

6GB

### Version number

4.1

### Browser

124.0.6367.60 (Official Build) (64-bit) (cohort: M124 Rollout) 

### What happened

The NSWF checker is not working, the button to activate it is greyed out in the UI. When I click on it nothing happens.

![image](https://github.com/invoke-ai/InvokeAI/assets/167733263/87b5ea70-abde-4db7-9413-38614c5a7868)

### What you expected to happen

I expected that when I click on the NSFW checker button that it will activate.

### How to reproduce the problem

Start the app, go to the web interface, click on settings and try to activate the NSFW cheker.

### Additional context

when I put in the command prompt the folder the invoke.bat is in this line: invoke.bat --nsfw_checker
I get this error: invokeai-web: error: unrecognized arguments: --nsfw_checker

so it does not work in the commands either.

### Discord username

shotgunner42

**Comment by psychedelicious** [comment]
This was inadvertently broken in #5991. The NSFW checker model isn't downloaded unless it is requested, but if it isn't downloaded yet, the app reports it is unavailable - catch 22.

Just out of curiosity, what is your goal for the NSFW checker? Do you use it often or did you just want to try it? This has been broken for a while now, and I think this is the first person reporting an issue with it.

**Comment by shotgunner42** [comment]
Thanks for the reply! to answer your question: I used it a often a couple of months ago (I think it was the version 3.6 or 3.4), and just recently downloaded the newest version. Is there a way to download the NSFW checker model?

**Comment by shotgunner42** [comment]
Thanks for your reply! to answer your question: I used it often a few months ago (I think it was invoke ai version 3.6 or 3.4) and recently downloaded the new version and tried to use it again. 

Where can I stay updated on the status of the NSFW checker? if its removed or gets fixed and becomes downloadable I would like to know. 
(should I just close this issue and look at the features evey update? or should I not close this issue and wait for you to comment on it? or something else?)

**Comment by psychedelicious** [comment]
Leave this open and you'll get notifications when it's fixed (or if we end up removing it).

Actually, I already fixed it but my strategy had some issues. You can see that in the linked PR just above your comment.

**Comment by shotgunner42** [comment]
Great, thank you! I now added notifications for that pull request too.
