### ISSUE TITLE
Custom placeholder for textual inversion doesn't work

### ISSUE THREAD

**Issue by kirylfb** [invoke-ai/InvokeAI#627]
**Describe the bug**
Setting placeholder_strings in configs/stable-diffusion/v1-finetune.yaml to something other than ["*"] (for example, to ["brian"]) doesn't work: the new placeholder doesn't work when trying to generate "a good photo of brian".

**To Reproduce**
1. vi configs/stable-diffusion/v1-finetune.yaml 
2. change placeholder_strings to ["brian"], save.
3. Add 3 png photos (512x512) of some person to ./train/brian 
4. Fine tune the model with  python main.py --base configs/stable-diffusion/v1-finetune.yaml  -t --actual_resume ./models/ldm/stable-diffusion-v1/model.ckpt -n brian --gpus 0, --data_root ./train/brian --init_word 'person'

5. Observe images generated in logs folder. The condition still says "a good photo of *", and generated samples do not show the desired object.
6. Finish tuning, start the script with generated embeddings, run prompt "a good photo of brian", the photo does not contain the desired object. "*" placeholder doesn't work either.

**Comment by rabidcopy** [comment]
I'm not certain, but I'm positive that the placeholder string is limited to character like *,#,$,@, and so forth.
Another issue is even if you could use the word "brian" as a placeholder string, you would need to also edit the placeholder strings in personalized.py
https://github.com/lstein/stable-diffusion/blob/2b9f8e7218e090947ec3139519ff0e593acf5e47/ldm/data/personalized.py#L109
