### ISSUE TITLE
[bug]: Some T2I Adapter settings are not preserved as metadata

### ISSUE THREAD

**Issue by trmusson** [invoke-ai/InvokeAI#6272]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### Version number

4.1.0

### Browser

Firefox 124.0.2 (64-bit)

### What happened

I tried to recreate a previously generated image via Invoke's "Use All" feature. The new image differed substantially from the original. The images were generated on the same PC, with the same version of Invoke. It turns out, certain T2I Adapter settings I'd used weren't being recalled.

### What you expected to happen

The new image should've been identical, or at least extremely close, to the original.

### How to reproduce the problem

Create an initial image using a T2I Adapter:

1. Prompt for whatever you like in Invoke's "Text to Image" UI.
2. Add a T2I adapter. For this example, use the canny-sdxl adapter.
3. Set a control image for that adapter.
4. Adjust its "Low Threshold" and "High Threshold" settings (i.e. don't use the automatic/default values).
5. Generate the image.
6. Select the newly generated image.
7. Press "I" for Info.
8. In the Metadata tab, the values from step 4 will be missing from the T2I Adapter's metadata.
9. In the "Recall Parameters" tab, recalling the T2I Adapter will also omit those settings.

For this reason, it'll be hard to regenerate the exact same image in future (once the cached control image data is eventually deleted).

### Additional context

I've only played with the canny-sdxl T2I adapter, but it looks like others (e.g. lineart, sketch, zoedepth) also have parameters specific to them, that perhaps aren't saved as metadata.

[**Edit:** These adapter-specific settings (e.g. "Low Threshold" and "High Threshold") don't seem to be preserved for the SD 1.0 ControlNet adapters either, which makes me wonder if there might be a reason for it, rather than it being a bug.]

Thanks :)

**Comment by psychedelicious** [comment]
The threshold values you are referring to aren't actually part of the generation. They are a pre-processing of the input control image. They are not saved to the metadata and I don't anticipate saving them.

What _is_ saved to the metadata is the reference to the processed control image. This is what is actually used during generation. When I follow your steps, I do get exactly the same image after using recall all.

I think there's something missing from your steps to reproduce. Perhaps a different piece of metadata isn't recorded.

But - even if the metadata is perfectly saved and recalled and used, recreated a previous generation is _best-effort only_. We cannot guarantee reproducibility for image generation. Why not?

1. Changes to dependencies (e.g. `torch`, `diffusers` - things we use, but don't maintain) may mean generating again with the exact same settings yields a different image.
2. A bugfix can drastically alter image outputs.
3. Changes to how settings are handled from version to version may drastically alter image outputs.

**Comment by psychedelicious** [comment]
With the [v4.2.0](https://github.com/invoke-ai/InvokeAI/releases/tag/v4.2.0) release, control adapters have been reworked and the full state of a control layer (including the processor config) is persisted/recalled to/from metadata.
