### ISSUE TITLE
Host remote 22 issue connecting refuse

### ISSUE THREAD

**Issue by gcoox** [invoke-ai/InvokeAI#6282]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

other

### GPU vendor

Nvidia (CUDA)

### GPU model

google T4

### GPU VRAM

8GB

### Version number

3.1.0

### Browser

Chrome

### What happened

i have connect all of the steps normally,but today in step 3 the connecting refuse ,no connecting link to get in the invokeai.

### What you expected to happen

is that any updating code to settle this problem?pls!!!....or cloud version is gonna be banned already...?i just want to have a know!

### How to reproduce the problem

is today,when i trying to start the invoke

### Additional context

is today becoming refuse, i yesterday still can start it normally！

**Comment by psychedelicious** [comment]
Google colab is not a supported platform. If you have the same problem running invoke on your own computer, please create a new issue.
