### ISSUE TITLE
[bug]: [v4.2.0a4] Error: Wrong assertion encountered: "Control adapter with id {someUUID} not found"

### ISSUE THREAD

**Issue by grunblatt-git** [invoke-ai/InvokeAI#6297]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

macOS

### GPU vendor

Apple Silicon (MPS)

### Version number

4.2.0a4

### Browser

Chrome

### What happened

When navigating to the "Control Layers" tab the UI crashes with the Error

> Error: Wrong assertion encountered: "Control adapter with id {someUUID} not found"

When this error appears I seem to have to reset the WebUI before i can navigate to the "Control Layers" Tab again. Recalling image settings of other images or restarting Invoke does not resolve the issue.

### What you expected to happen

Recalling generation settings of old images works without crashes

### How to reproduce the problem

I am not 100% sure which constellation leads to this error.
I ran into the issue after using "Remix Image" on images that i generated (in 4.2.0a4 as well) which were using a global IP-Adapter or Control-Adapter. Recalling the settings worked on some images (except for the IP- and Control-Adapter settings which do not show up in the UI). Recalling the settings of others leads to the error above.

### Additional context

I think all "corrupt" images that i recalled used a global IP-Adapter

**Comment by psychedelicious** [comment]
This is a known issue as pointed out in the alpha release notes. It's resolved in the current dev branch.
