### ISSUE TITLE
[enhancement]: Model name column in queue

### ISSUE THREAD

**Issue by Vanok179** [invoke-ai/InvokeAI#6308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

The generation queue tab lacks a column to quickly find the model on the basis of which generation is carried out

**Comment by psychedelicious** [comment]
Invoke works internally on graphs. A graph can have _any_ number of models. It's not possible to have a single model column. We don't even know where all of the models are in a graph.

While it is technically possible to show a model column for a limited subset of graphs, that is still a _substantial_ amount of work and there's no general solution. Sorry, but this is out of scope and not something we will attempt to implement.
