### ISSUE TITLE
[enhancement]: Bundle the Model merger "again" with the InvokeAi base build ....

### ISSUE THREAD

**Issue by R0TEAM** [invoke-ai/InvokeAI#6325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

As i have read, the option to merge models have removed and will only be available in an seperate build where is for user to train models ....
I think this is a bad move.
Most InvokeAI user dont train models ... but merge a model is an basic function to wider the options to generate the picture that is seeked ....
I as example, have realy not an desire to train models .... but i use frequently the Model merger to merge models i think will give me an better result as the one model alone ... and model merging is an easy to understand and realative error free option.
So i hope model merging will get back in the main code of InvokeAI and i dont need to download/install many additional stuff i dont need and dont care if i need only an simply model merge ...

**Comment by psychedelicious** [comment]
We've already discussed this quite a bit, and have made the decision to not have model merging in the generation UI. I don't think we are open to reversing that decision, but I'll defer to @hipsterusername for their perspective.

If you have some feedback for how you'd like to see merging implemented, you could add that to https://github.com/invoke-ai/invoke-training/issues/110.

**Comment by hipsterusername** [comment]
There is talk of community models that would allow for merging in workflows, but it won’t be part of the core set.

The individual interested in building that might be contactable in Discord
