### ISSUE TITLE
[enhancement]: Add `auto_start_queue` or `empty_queue_on_startup` config setting

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#6333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Add a config setting `auto_start_queue` to `invokeai.yaml` to control whether the queue starts processing immediately on startup, and/or `empty_queue_on_startup` to empty the queue on startup.

### Additional Content

https://discord.com/channels/1020123559063990373/1237801079459287150/1237801079459287150

In this discord bug report, the application had a catastrophic failure with a particular kind of queue item. This failure didn't give the app a chance to handle the error, it just immediately crashed. On next startup, that one queue item was pruned. The user would need to restart the app N number of times, where N is the number of problematic queue items, to clear the queue.

The proposed `auto_start_queue` would give the user a chance to inspect and clear the queue on startup before a crash-inducing queue item would be executed.

Or, `empty_queue_on_startup` would let the user get a fresh start.

I'm not sure which I prefer.

**Comment by steffy-lo** [comment]
Can I take this up?

**Comment by psychedelicious** [comment]
Hi @steffy-lo, sure. Do you have any thoughts on which of the proposed solutions is best? Or maybe some other approach?

**Comment by steffy-lo** [comment]
@psychedelicious Hmm, I believe because this seems like a very edge case scenario, a simple `empty_queue_on_startup` should do the trick. If we can consistently replicate the issue, then maybe we could explore another approach that fixes the underlying issue as well

**Comment by psychedelicious** [comment]
Sounds good to me!
