### ISSUE TITLE
[enhancement]: Retain set denoise strength when changing the image

### ISSUE THREAD

**Issue by Moardread** [invoke-ai/InvokeAI#6351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

When changing the image used for image to image it resets the denoising strength to 0.75 regardless of what was set previously.
Ideally there should be an option to keep this at the currently set value, something like a checkbox.

### Alternatives

Alternatively it could be possible to have a feature that allows you to select a batch of images (either manually select or select a whole board) and then perform a single action on them such as running each image through image to image at 0.25 denoising strength with a prompt "Detailed photograph of an ogre" which could be used to turn a batch of cartoon style ogres into realistic looking ones.

**Comment by psychedelicious** [comment]
Let's stick to the simpler request here - retain the currently-set value when using an image as an initial image.

---

Notes for a contributor who wants to implement this fairly straightforward change:
- All changes would be in this reducer: https://github.com/invoke-ai/InvokeAI/blob/main/invokeai/frontend/web/src/features/controlLayers/store/controlLayersSlice.ts#L616-L638
- The strength is an property of the initial image layer.
- Currently, there can be only 1 initial image layer. We are deleting the existing layer if one exists and creating an new layer. You'll need copy the strength from the existing layer, if it exists, and use that with the new layer.

**Comment by psychedelicious** [comment]
Merging #6399 into this request.

In addition to retaining the strength parameter, the layer opacity should be retained.

**Comment by steffy-lo** [comment]
Will take a look at this issue as discussed on discord :)
