### ISSUE TITLE
[bug]: ModuleNotFoundError: No module named 'controlnet_aux'

### ISSUE THREAD

**Issue by Cyanex1702** [invoke-ai/InvokeAI#6365]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 3070

### GPU VRAM

8GB

### Version number

4.2.0

### Browser

Google Chrome

### What happened

I have been trying to run invoke ai for weeks now i keep getting this error: "ModuleNotFoundError: No module named 'controlnet_aux' ". I tried the dev option and used the command "pip install controlnet-aux," and after that, I even activated the virtual environment and downloaded the library. After installation, it says the requirement is satisfied. But still, whenever ever i try to run it again, it doesnt work and gives me the same error. I tried many things and saw a post saying to reinstall Python with Cuda because sometimes it helps. I did that as well, but nothing worked. I even deleted and installed the whole invoke ai multiple times both by using installer and git but i am still getting this error

### What you expected to happen

How can i fix this error and run the program?

**Comment by psychedelicious** [comment]
Hi, did you fix this?

If not, I think I've figured out the a workaround.

The `controlnet_aux` package has had some issues with how it is distributed. Sometimes a broken version of it is installed. We don't have control over this, it's the python packaging system (`pip`) that is causing the issue.

When this happens, the broken version of `controlnet_aux` is cached by `pip` and subsequent reinstalls will re-use the pip cache. We can clear the pip cache for `controlnet_aux` and/or all packages:

1. Run the Invoke launcher.
2. Select the option for developer console.
3. Run `pip cache remove controlnet_aux` to remove it from the cache.
4. Close the launcher window.
5. Run the installer. A fresh `controlnet_aux` package will be downloaded and used.

If this doesn't fix the issue, do the same thing but at step 3, run this command to empty the whole `pip` cache:
```sh
pip cache purge
```
