### ISSUE TITLE
[bug]:  Error Dependencies

### ISSUE THREAD

**Issue by SaucierMusic** [invoke-ai/InvokeAI#6369]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

GEForce GTX 1060

### GPU VRAM

?

### Version number

HP Omen

### Browser

Google

### Python dependencies

  Installing backend dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install backend dependencies did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu121
      Collecting cython
        Using cached Cython-3.0.10-cp310-cp310-win32.whl.metadata (3.2 kB)
      ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
      ERROR: No matching distribution found for torch
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Error: Unexpected exit code: 1
Command line: | 'C:\Users\M249_\invokeai\.venv\Scripts\pip.exe' install --require-virtualenv --force-reinstall --use-pep517 'invokeai[xformers,onnx-cuda]' --extra-index-url https://download.pytorch.org/whl/cu121
Could not install InvokeAI. Please try downloading the latest version of the installer and install again.

### What happened

..

### What you expected to happen

..

### How to reproduce the problem

..

### Additional context

..

### Discord username

sauciermusic

**Comment by psychedelicious** [comment]
Hi, can you please confirm that you have installed by following the install instructions on the [latest release](https://github.com/invoke-ai/InvokeAI/releases/tag/v4.2.1) to download and run the installer?

**Comment by psychedelicious** [comment]
Also, please paste the output of `python --version`.

**Comment by SaucierMusic** [comment]
Hi thank you so much for responding!! C:\Users\M249_>py --version
Python 3.10.9

yes followed and am at the very last stage of install when it fails.. chat gpt said something about torch?? I am so new to all of this im so sorry lol

**Comment by psychedelicious** [comment]
It's unexpected that the installer is attempting to install `cython`:
```
 Collecting cython
Using cached Cython-3.0.10-cp310-cp310-win32.whl.metadata (3.2 kB)
```

I don't think that is in our dependency graph at all. I just did a fresh install to double-check - no cython. Do you have any ideas why it might be attempting to install cython (e.g. you manually installed a specific build of python)?

Is this a new install or an update of an existing install?

**Comment by SaucierMusic** [comment]
Hello! This is a new install following the link from the Helium X guide...I did install 32 bit and 64 bit because I wasn't sure which I needed

**Comment by SaucierMusic** [comment]
After using chat gpt (which recommend I try to update some stuff or something) I now see I went from 5 output errors to 3? lol not sure if this whole thing helps...

Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu121
Collecting invokeai[onnx-cuda,xformers]
  Using cached InvokeAI-4.2.1-py3-none-any.whl.metadata (23 kB)
Collecting accelerate==0.29.2 (from invokeai[onnx-cuda,xformers])
  Using cached accelerate-0.29.2-py3-none-any.whl.metadata (18 kB)
Collecting clip-anytorch==2.5.2 (from invokeai[onnx-cuda,xformers])
  Using cached clip_anytorch-2.5.2-py3-none-any.whl.metadata (8.1 kB)
Collecting compel==2.0.2 (from invokeai[onnx-cuda,xformers])
  Using cached compel-2.0.2-py3-none-any.whl.metadata (12 kB)
Collecting controlnet-aux==0.0.7 (from invokeai[onnx-cuda,xformers])
  Using cached controlnet_aux-0.0.7.tar.gz (202 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting diffusers==0.27.2 (from diffusers[torch]==0.27.2->invokeai[onnx-cuda,xformers])
  Using cached diffusers-0.27.2-py3-none-any.whl.metadata (18 kB)
Collecting invisible-watermark==0.2.0 (from invokeai[onnx-cuda,xformers])
  Using cached invisible_watermark-0.2.0-py3-none-any.whl.metadata (8.2 kB)
INFO: pip is looking at multiple versions of invokeai[onnx-cuda,xformers] to determine which version is compatible with other requirements. This could take a while.
Collecting invokeai[onnx-cuda,xformers]
  Using cached InvokeAI-4.2.0-py3-none-any.whl.metadata (23 kB)
  Using cached InvokeAI-4.1.0-py3-none-any.whl.metadata (34 kB)
  Using cached InvokeAI-4.0.4-py3-none-any.whl.metadata (34 kB)
Collecting accelerate==0.28.0 (from invokeai[onnx-cuda,xformers])
  Using cached accelerate-0.28.0-py3-none-any.whl.metadata (18 kB)
Collecting invokeai[onnx-cuda,xformers]
  Using cached InvokeAI-4.0.3-py3-none-any.whl.metadata (34 kB)
  Using cached InvokeAI-4.0.2-py3-none-any.whl.metadata (34 kB)
  Using cached InvokeAI-4.0.1-py3-none-any.whl.metadata (34 kB)
  Using cached InvokeAI-4.0.0-py3-none-any.whl.metadata (34 kB)
INFO: pip is still looking at multiple versions of invokeai[onnx-cuda,xformers] to determine which version is compatible with other requirements. This could take a while.
  Using cached InvokeAI-3.7.0-py3-none-any.whl.metadata (33 kB)
Collecting accelerate==0.27.2 (from invokeai[onnx-cuda,xformers])
  Using cached accelerate-0.27.2-py3-none-any.whl.metadata (18 kB)
Collecting diffusers==0.26.3 (from diffusers[torch]==0.26.3->invokeai[onnx-cuda,xformers])
  Using cached diffusers-0.26.3-py3-none-any.whl.metadata (19 kB)
Collecting invokeai[onnx-cuda,xformers]
  Using cached InvokeAI-3.6.3-py3-none-any.whl.metadata (33 kB)
Collecting accelerate==0.26.1 (from invokeai[onnx-cuda,xformers])
  Using cached accelerate-0.26.1-py3-none-any.whl.metadata (18 kB)
Collecting diffusers==0.26.2 (from diffusers[torch]==0.26.2->invokeai[onnx-cuda,xformers])
  Using cached diffusers-0.26.2-py3-none-any.whl.metadata (18 kB)
Collecting invokeai[onnx-cuda,xformers]
  Using cached InvokeAI-3.6.2-py3-none-any.whl.metadata (33 kB)
Collecting basicsr==1.4.2 (from invokeai[onnx-cuda,xformers])
  Using cached basicsr-1.4.2.tar.gz (172 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install backend dependencies did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu121
      ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
      ERROR: No matching distribution found for torch
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Error: Unexpected exit code: 1
Command line: | 'C:\Users\M249_\invokeai\.venv\Scripts\pip.exe' install --require-virtualenv --force-reinstall --use-pep517 'invokeai[xformers,onnx-cuda]' --extra-index-url https://download.pytorch.org/whl/cu121
Could not install InvokeAI. Please try downloading the latest version of the installer and install again.
Press any key to continue . . .

**Comment by psychedelicious** [comment]
> Hello! This is a new install following the link from the Helium X guide...I did install 32 bit and 64 bit because I wasn't sure which I needed : from this link https://www.python.org/downloads/release/python-3109/

What is the Helium X guide? 

You don't need both 32 and 64 bit pythons - who knows what trouble that might cause.

I'd suggest to uninstall everything you've installed so far to get a fresh start, then follow the simple instructions from our own docs to install python and Invoke. You'll need to delete the `invokeai` folder in your home folder too.

Installation guide: https://invoke-ai.github.io/InvokeAI/installation/010_INSTALL_AUTOMATED/

Be sure to review the requirements and follow the instructions there.

**Comment by SaucierMusic** [comment]
sorry I'm not seeing a download to python?

**Comment by psychedelicious** [comment]
The installation requirements are here: https://invoke-ai.github.io/InvokeAI/installation/INSTALL_REQUIREMENTS/

**Comment by SaucierMusic** [comment]
Thank you so much I beleive it's working!! Got to the stage of installing models now! Thank you SO MUCH!

**Comment by psychedelicious** [comment]
Sweet, glad you are up and running. Have fun!

**Comment by haltingstate** [comment]
I have the same problem.

ERROR: Could not find a version that satisfies the requirement invokeai[onnx-cuda,xformers] (from versions: none)
ERROR: No matching distribution found for invokeai[onnx-cuda,xformers]

My computer is setup for nvidia-smi and machine learning workflows. All other applications work.

**Comment by psychedelicious** [comment]
@haltingstate Please review the [installation requirements](https://invoke-ai.github.io/InvokeAI/installation/requirements/). Python 3.12 is not supported.

**Comment by ruthan** [comment]
I have this problem too i installed all by the book, some better code practice, exception handling, like at least report that something is wrong with Python, not with downloading or not existing of version, would be nice.
  My suspect is old school PATH problem, afaik is not really clever way use Windows PATH in 2025, its better to use registry..
because afaik is PATH limited to 2048 characters and lots of programs still really on it.. with some older stuff i understand it.

 But for new SW with some modern software practice.. workflow should be check if Python is installed, check its version, check if its in the PATH, if not ask user to input Python path manually and after use it as hardcoded. I Python really does not use Windows registry itself its part of problem too. 

   To be honest, i was really suprised that you are in  1 hand using some cutting edge GPU acceleration, but in other hand, you are using slowest possible Programming language - Python, is even slow as programming language its even slow for scripting language and it evens needs runtime and could be bundled as stand alone portable version, because otherwise i dont get why is not such version used in the first place.

Sorry for mentoring, but its annoying enough that all is not done through Win 95+ installer but through some command line / terminal Linux hell, its not  thing why we are using Windows or MacOS..
