### ISSUE TITLE
[bug]: Model's "default width/height" settings are not applied in Canvas mode

### ISSUE THREAD

**Issue by Svyaga** [invoke-ai/InvokeAI#6371]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 3070

### GPU VRAM

8GB

### Version number

4.2.1

### Browser

Chrome 124.0.6367.158

### Python dependencies

{
  "accelerate": "0.29.2",
  "compel": "2.0.2",
  "cuda": "12.1",
  "diffusers": "0.27.2",
  "numpy": "1.26.4",
  "opencv": "4.9.0.80",
  "onnx": "1.15.0",
  "pillow": "10.2.0",
  "python": "3.10.11",
  "torch": "2.2.2+cu121",
  "torchvision": "0.17.2+cu121",
  "transformers": "4.39.3",
  "xformers": "0.0.25.post1"
}

### What happened

I set default width/height for a model, and if I use this button in "Generation" tab then it's applied correctly:
![1](https://github.com/invoke-ai/InvokeAI/assets/143509676/e550752b-4756-4306-8a04-88fa2417fdbd)
But if I do the same thing in "Canvas" tab, then it's not applied:
![2](https://github.com/invoke-ai/InvokeAI/assets/143509676/6fb1a8c3-1da2-45ea-bca3-4286bad3fdd8)
Other settings are applied correctly, the problem is only with width/height.

### What you expected to happen

Default settings should be applied correctly in Canvas mode.

### How to reproduce the problem

1. Start the app.
2. Open "Models" tab.
3. Choose any model and apply default width/height.
4. Open "Canvas" tab.
5. Choose model you edited in step "3".
6. Click on "Default settings" button.

### Discord username

svyaga

**Comment by psychedelicious** [comment]
Invoke v5 features a full rewrite of the canvas. Please create a new GH issue if the problem still exists in the new canvas UI.
