### ISSUE TITLE
[enhancement]: increasing LoRA weight cap

### ISSUE THREAD

**Issue by PhantomKojima** [invoke-ai/InvokeAI#6373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I would like the LoRA weight range to be wider as some LoRAs can be used at values above 5 and below -5.

**Comment by psychedelicious** [comment]
This is a really simple fix. Edit the min and max values in this component: https://github.com/invoke-ai/InvokeAI/blob/main/invokeai/frontend/web/src/features/lora/components/LoRACard.tsx

**Comment by H0onnn** [comment]
@psychedelicious Can I resolve this issue ?

**Comment by psychedelicious** [comment]
@H0onnn Sure! I've assigned the issue to you.
