### ISSUE TITLE
[bug]: installation if Python higher then 3.11

### ISSUE THREAD

**Issue by VitaliyAT** [invoke-ai/InvokeAI#6377]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows 10

### GPU vendor

Nvidia (CUDA)

### GPU model

4090

### GPU VRAM

24

### Version number

4.2.1

### Browser

no yet

### What happened

installation is not going well - error ending

### What you expected to happen

Expect that installer organize normal VENV, install Python version that need for work inside VENV, and after that install all libs from VENV. And will not touch any of my main OS Python and Libs.

### How to reproduce the problem

Install Python 3.12 in OS and run installer

### Additional context

Do you think you are alone in the OS? Do you know that Python's IT staff will not be employed even as Junior, if it will install libs in main OS and will not create normal VENV for project? You mast learn lesson and do normal installer. Such cool product, such cool ideas and such childish installer.

**Comment by psychedelicious** [comment]
We don't support python 3.12 because some of our dependencies either don't support it or don't support it fully. You _must_ use 3.10 or 3.11 with invoke until all of the dependencies are updated and confirmed stable on python 3.12.

**Comment by VitaliyAT** [comment]
So that why you not created venv in project for be shure that everythong will be ok. You know that you are not alone in OS. Usualli Ai-divers have a lot of Ai products. And most of them work in Pythons virtual environment, why you no?

**Comment by psychedelicious** [comment]
It's common practice to have multiple python versions installed, for example using pyenv. You can have a specific python installed only for invoke (I often do this for testing). Invokes dependencies are not compatible with python 3.12, it's not our choice.
