### ISSUE TITLE
[bug]: Control Layer opacity resets back to 100%, and Denoising Strength to 0.75 via Send to Image to Image

### ISSUE THREAD

**Issue by ufuksarp** [invoke-ai/InvokeAI#6399]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Version number

4.2.1

### Browser

Edge latest

### What happened

**Send to Image to Image** should not reset the layer opacity back to 100% or denoising strength to 0.75, making user to constantly set it back to preference. It should keep the user-set values. Drag-and-drop doesn't reset it, works correctly.

**Comment by psychedelicious** [comment]
merged into #6399
