### ISSUE TITLE
[bug]: Load More button disappears when it shouldn't

### ISSUE THREAD

**Issue by magnusviri** [invoke-ai/InvokeAI#6406]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

macOS

### GPU vendor

Apple Silicon (MPS)

### GPU model

MacBook Air M1 2020

### GPU VRAM

16GB

### Version number

v4.2.1

### Browser

Brave

### What happened

I deleted all of my images in image browser and the "Load More" button continually updated until it said it was showing 1 out of 52 ("1/52"). After I deleted the last image in the image browser the "Load More" button simply disappeared instead of showing "0/51". After reloading the web page, it then correctly showed "51/51". See images.

![Screenshot 2024-05-19 at 23 02 24](https://github.com/invoke-ai/InvokeAI/assets/711269/29e5677f-d1b2-4cb3-ac49-0df9302fa3de)

Delete image

![Screenshot 2024-05-19 at 23 02 29](https://github.com/invoke-ai/InvokeAI/assets/711269/1986b925-88d9-4d0c-be10-585b14d89904)

Reload

![Screenshot 2024-05-19 at 23 02 33](https://github.com/invoke-ai/InvokeAI/assets/711269/81ab8072-69af-483c-971c-fe94f5f6a5a9)

### What you expected to happen

It should have shown 0/51 when I deleted the 1/52 image in the image browser.

### How to reproduce the problem

Generate a lot of images so that it shows the "Load More" button. Then delete all the images on the first page.

### Discord username

magnusviri

**Comment by psychedelicious** [comment]
This is a problem with the convoluted infinite scroll implementation, which is on its way out. Refreshing syncs the frontend state with the backend and is the solution until we redo the gallery pagination.
