### ISSUE TITLE
[bug]: Can't install on Mac

### ISSUE THREAD

**Issue by eyetest42** [invoke-ai/InvokeAI#6414]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

macOS

### GPU vendor

Apple Silicon (MPS)

### GPU model

M2 Pro

### GPU VRAM

32gb

### Version number

4.2.2

### Browser

Firefox 115.11.0esr

### What happened

Attempting to install via Terminal results in this error:

> A suitable Python interpreter could not be found
> Please install Python 3.9 or higher before running this script.

### What you expected to happen

I expected Invoke to be installed

**Comment by Vargol** [comment]
> Attempting to install via Terminal results in this error:
> 
> A suitable Python interpreter could not be found
> Please install Python 3.9 or higher before running this script.

You need to install a 3.10 or 3.11 version of Python from Python.org at  https://www.python.org/downloads/macos/
(or use pyenv, or MacPorts, basically anyway other than Brew, Brew isn't recommended as for some reason there is/was something broke in the brew's install of Python).

**Comment by psychedelicious** [comment]
I'm confused by the error message. That verbiage doesn't exist in the codebase, which suggests that you are using an outdated installer. Please delete any installer directories or files you may have and download the latest installer from https://github.com/invoke-ai/InvokeAI/releases/tag/v4.2.2post1.

**Comment by eyetest42** [comment]
I've already installed the latest version of Python, and the Invoke installer I used was the latest version as well.

**Comment by psychedelicious** [comment]
You shouldn't have the _latest_ version of python, you must have python 3.10 or 3.11. 

Also, please do the troubleshooting I suggested - delete any existing installer files , download the one from the releases page and try again. 

The message you are seeing is from a very outdated installer.

**Comment by eyetest42** [comment]
Again, I was already using the latest Invoke installer.
Installing Python 3.11 specifically seems to have fixed it.

**Comment by psychedelicious** [comment]
I understand that you downloaded and ran the latest installer.

The message you got - about python 3.9 - does not exist in the codebase. That's very much unexpected. You must be using an outdated installer somehow.

We've seen this happen when users unzip the different versions of the installer - specifically on macOS. Depending on how the archive is unzipped, the installer may copy into an old folder, and running the script may reference the outdated files. Hence my request that you delete all installer files and try again.

Anyways, glad you got it working.

**Comment by eyetest42** [comment]
This was an entirely new install, I've never tried this program before.

**Comment by psychedelicious** [comment]
> This was an entirely new install, I've never tried this program before.

I'm really puzzled then. I double-checked the v4.2.2 installer and the string "3.9" doesn't exist there. Maybe I'm missing something. Very strange.
