### ISSUE TITLE
[bug]: Delete hotkey doesn't delete gallery images while editing workflows

### ISSUE THREAD

**Issue by Ar7ific1al** [invoke-ai/InvokeAI#6421]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 3080Ti

### GPU VRAM

12GB

### Version number

4.2.2post1

### Browser

Google Chrome 124.0.6367.208

### What happened

When editing workflows, the Delete hotkey will not delete gallery images. If a noodle or node is selected, that will be deleted instead. If nothing is selected, nothing happens.
You must switch to a different mode, e.g. Generation or Canvas, for the delete key to delete a gallery image, or switch the Workflow view to Use In Linear View to delete gallery images.

### What you expected to happen

If I'm editing a workflow and I move my cursor over the gallery, I expect the Delete hotkey to delete the currently selected gallery image.

### How to reproduce the problem

- In Workflows tab, edit a workflow. Select a gallery image and press Delete. The image won't be deleted.
- In Workflows tab, edit a workflow. Select a noodle or node, move your cursor over the Gallery, and press Delete. The node or noodle will be deleted, but the image will be unaffected.

### Discord username

\_cirius\_

**Comment by psychedelicious** [comment]
I have an idea of what's happened, classic fix one bug and cause another 😅 I fixed an issue with the node editors delete hotkey but I think I made it too powerful.
