### ISSUE TITLE
Small docu issue: -s for strength

### ISSUE THREAD

**Issue by GothaB** [invoke-ai/InvokeAI#643]
Documentation falsely claims "-s" is shortcut for "--strength", in fact it is "-f". "-s" is for steps.
https://github.com/lstein/stable-diffusion/blob/development/docs/features/CLI.md

(Small side note: The documentation is really neat and easy to read. ❤️ )

**Comment by BrentOzar** [comment]
I think you might be mixing up two different sections of the document. 

With txt2img, -s represents steps, and that's around line 127 of the docs.

With img2img, -s represents strength, and that's around line 163.

If you do a text search on the page for --steps, you'll see the part that refers to txt2img.

**Comment by GothaB** [comment]
But -s still won't work for strength, right? 🤔 

Because when I use img2img, I can still use -s for steps. Or is there some way to tell the command line, that one "-s" is for steps and the other "-s" is for the img2img argument?

E.g.
beautiful person -I./images/person.png -s 30   ---> works (runs 30 steps)
beautiful person -I./images/person.png -s 0.7 ---> breaks

Also, when I use
beautiful person -I./images/peson.png --strength 0.7 
it rewrites ist as
beautiful person -I./images/peson.png -f 0.7
