### ISSUE TITLE
[bug]: InvokeAI incorrectly recognizes the model type

### ISSUE THREAD

**Issue by DeXtmL** [invoke-ai/InvokeAI#6444]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

4090

### GPU VRAM

24GB

### Version number

4.2.0

### Browser

Edge latest

### Python dependencies

InvokeAI incorrectly recognizes the model type

### What happened

InvokeAI refuses to load some models (unselectable). 
Editing the model type gives an error.

### What you expected to happen

Non-standard models are not uncommon,
InvokeAI should at least allow user to forcibly override the base model type.
Better if InvokeAI provides a button to go back to the default in case the user messes up.

### How to reproduce the problem

Let's take the WildCardX-XL lora as an example:

1. download and import the lora from: [https://civitai.com/models/264681?modelVersionId=298448](https://civitai.com/models/264681?modelVersionId=298448)
2. Note that InvokeAI recognizes the model as SD-1 Lora, where it is actually a SDXL Lora. (screenshot 1)
3. Trying to edit the model type gives an error: "**Model Update Failed**" then forcibly revert back to Sd-1 (screenshot 2, screenshot 3)

![s1](https://github.com/invoke-ai/InvokeAI/assets/13725477/df279a41-0b25-4d1c-a208-0f2d24a04390)

![s2](https://github.com/invoke-ai/InvokeAI/assets/13725477/f6b41601-ba31-4bcd-90ef-bab514718410)

![s3](https://github.com/invoke-ai/InvokeAI/assets/13725477/340230eb-8115-4402-b10c-2a8bd04f3822)

**Comment by DeXtmL** [comment]
Error message:
`[InvokeAI]::ERROR --> 1 validation error for LoRALyCORISConfig
variant
  Object has no attribute 'variant' [type=no_such_attribute, input_value=<ModelVariantType.Normal: 'normal'>, input_type=ModelVariantType]
    For further information visit https://errors.pydantic.dev/2.6/v/no_such_attribute`

**Comment by DeXtmL** [comment]
Error message: 
`[InvokeAI]::ERROR --> 1 validation error for LoRALyCORISConfig
variant
  Object has no attribute 'variant' [type=no_such_attribute, input_value=<ModelVariantType.Normal: 'normal'>, input_type=ModelVariantType]
    For further information visit https://errors.pydantic.dev/2.6/v/no_such_attribute`

**Comment by frankvegastudio** [comment]
[2024-12-11 18:09:12,490]::[ModelInstallService]::ERROR --> Model install error: black-forest-labs/FLUX.1-schnell
InvalidModelConfigException: Unknown base model for /Volumes/frankXmini/frankmini/invokeai/models/tmpinstall_7z13gb4r/FLUX.1-schnell
