### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by ZERO28822** [invoke-ai/InvokeAI#6457]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

rtx 3060 

### GPU VRAM

16

### Version number

423

### Browser

edge 

### What happened

I started invokeAI and it didn't start and wrote this error:
![Снимок экрана 2024-05-29 175210](https://github.com/invoke-ai/InvokeAI/assets/155769483/872a25d0-61fa-42d9-8a7b-6aa8aa0cd811)

### What you expected to happen

I was expecting the page to launch in the browser

**Comment by psychedelicious** [comment]
Hi, please follow these instructions:

- Run the Invoke launcher
- Choose the developer console option
- Run this command: `pip cache remove controlnet_aux`
- Close the terminal window
- Download and run the [installer](https://github.com/invoke-ai/InvokeAI/releases/latest), selecting your current install location

In the future, please include some more detail in issue title, like an error message.
