### ISSUE TITLE
[bug]: Wrong labels found on Weblate for the English language

### ISSUE THREAD

**Issue by Harvester62** [invoke-ai/InvokeAI#6465]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

GTX 1070

### GPU VRAM

8GB

### Version number

4.2.3

### Browser

Firefox 126.0.1

### Python dependencies

N/A

### What happened

I found a few labels, descriptions in the Weblate ENGLISH language text that might not be consistent (see the screenshot below). 
![immagine](https://github.com/invoke-ai/InvokeAI/assets/29801031/87a76f00-c057-4671-8599-4d07a444d27c)

About the two last rows, I simply suggest a possible renaming for the sending to Image2Image, now being incorporated inside the Generation tab, while the very last should reflect the current naming of Canvas in the UI. 

### What you expected to happen

I would expect the English keys descriptions to be in the following order as follows:

- Unable to Copy Canvas
- Unable to Download Canvas
- Unable to Import Mask
- Unable to Merge Canvas
- Unable to Save Canvas
- Unable to Save Mask
- Sent to Generation from Image (Optional)
- Sent to Canvas

### How to reproduce the problem

N/A

### Additional context

This bug report is an updated version of my previous similar bug report https://github.com/invoke-ai/InvokeAI/issues/4762 which I will close being outdated and superseded by the current one.

**Comment by JorgeR81** [comment]
@Harvester62, sorry for this unrelated question:

Can you run InvokeAI 4 properly with a GTX 1070 ?

I have the same GPU and I use the Comfy UI with no issues. 

I was looking at InvokeAI, but they don't recommend this card. 

https://invoke-ai.github.io/InvokeAI/installation/INSTALL_REQUIREMENTS/

Can you run SDXL models with it ?

**Comment by Harvester62** [comment]
Yes, I can, but SDXL runs only without any CN, IP Adapter, etc. (use instead SD1.B The GTX 1070 is a barely minimum to be able to run Invoke, but it works, at least for me. I read that page and I can confirm you that my GTX1070 IS able to run models at FP16 and HAS enough VRAM (8GB) to run without problems any SD1.5/2.X model with any CN adapter.

If not already done, I would recommend you to join the Discord channel of InvokeAI, where you can interact with other users and developers, ask question, receive help/suggestions, etc.
