### ISSUE TITLE
[enhancement]: keyboard shortcut for resizing brush/eraser

### ISSUE THREAD

**Issue by MylesCroft** [invoke-ai/InvokeAI#6466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Add the Ps shortcut of [ ] (along with shift + [ ]  to increase by 10) to resize the brush from keyboard.

### Alternatives

Alternatively, create the ability to map keys to Invoke commands within the webapp.

**Comment by jstnlowe** [comment]
@MylesCroft "[" to decrease and "]" to increase brush/eraser size is already implemented - isn't it?

**Comment by MylesCroft** [comment]
Not working here if so, just tried again. I keep trying to use it when doing masks from habit, hence the request and assumption it's not working on v4.2.3 and was requested over on Discord to raise it as a request.

**Comment by MylesCroft** [comment]
Win 10 and 11, Vivaldi and Edge on both. Vivaldi is a bare install with no extensions.

**Comment by jstnlowe** [comment]
I just figured out what you're talking about - I was testing in the Canvas but you're encountering this when working with Control Layers (e.g., regional guidance masks). Oops! Seconding this request.

**Comment by psychedelicious** [comment]
This is implemented in Invoke v5
