### ISSUE TITLE
preload_models.py downloads gfpgan model even if it exists

### ISSUE THREAD

**Issue by BrentOzar** [invoke-ai/InvokeAI#647]
Thanks so much for what y'all are doing! Really loving this fork.

**Describe your environment**
- GPU: mps
- CPU arch: arm
- OS: macOS
- Branch: development

**Describe the bug**
Starting with this pull request: https://github.com/lstein/stable-diffusion/commit/31daf1f0d794cac1eba526d2e4c17fc8ea1f4867

preload_models.py downloads GFPGANv1.3.pth even if the file already exists. If the file already exists, can we skip that step? Pulling 350MB is a little painful over airplane wifi, heh.

**To Reproduce**
1. Run preload_models.py, which causes the file to download. Note the date/time on the file.
2. Exit the terminal, go back in.
3. Run preload_models.py, note that the download is kicked off again with a new date/time on the file.

**Expected behavior**
Skip the download if the file already exists.

**Comment by lstein** [comment]
Right. I'll fix that.

**Comment by lstein** [comment]
Just committed a fix. Should go into development soon.

**Comment by BrentOzar** [comment]
You rock! Thanks!
