### ISSUE TITLE
[bug]: Unable to Delete Image if Graph JSON has been Downloaded

### ISSUE THREAD

**Issue by jstnlowe** [invoke-ai/InvokeAI#6470]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### Version number

4.2.3

### Browser

Edge 125, Chrome 127

### What happened

Unable to delete an image if the graph JSON has been downloaded for that image during the current session. Results in log message: `[InvokeAI]::ERROR --> Failed to delete image file`

### What you expected to happen

Image should be deleted without error.

### How to reproduce the problem

1. Start InvokeAI
2. Generate an image or select a previously-generated image
3. Go to "Info"
4. Download the graph JSON file
5. Attempt to delete the image via any method in interface

### Additional context

- Does not occur with other JSON downloads (e.g., metadata, workflow).
- Requires restart of Invoke to resolve.

**Comment by psychedelicious** [comment]
I cannot reproduce this issue. I can generate an image, download its graph, and delete it. I can also delete older images (from previous sessions) after downloading the graph JSON.

Downloading the graph JSON is a wholly clientside operation. The JSON already exists in the browser memory and downloading it doesn't make any additional server requests. I'm very skeptical that this is the cause of the error.

Any other clues you can think of?

**Comment by jstnlowe** [comment]
I will investigate further - based on your comment, I will set up a second, entirely separate installation of 4.2.3 and see if I can reproduce it there.

**Comment by jstnlowe** [comment]
Closing  - unable to reproduce in a separate install.

**Comment by psychedelicious** [comment]
Ok, thanks for following up. You could try re-installing (i.e. updating the app dependencies) - maybe something in there went pear-shaped.

We use a cross-platform python library called [send2trash](https://github.com/arsenetar/send2trash) to delete images. It moves images to the OS-provided "trash bin" container. If this library fails to do its job, it could cause the error you saw. Could be a clue.
