### ISSUE TITLE
[enhancement]: Update re-downloads Pytorch and others every time

### ISSUE THREAD

**Issue by BeeMeeN** [invoke-ai/InvokeAI#6489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

info@nieschalk.com

### What should this feature add?

Would it be possible to let the update routine recognise previously installed identical (!) versions of big files like pytorch?
Every time I install the latest update, it downloads the same big files again and again, though they are already available on HD.
Updates could be so much faster...
Maybe I'm wrong and there's a reason for the re-downloads.

### Alternatives

---

### Additional Content

For example. Lots of other **big/giant files** are affected:

`Collecting torch==2.2.2 (from invokeai[onnx-cuda,xformers])
  Downloading https://download.pytorch.org/whl/cu121/torch-2.2.2%2Bcu121-cp311-cp311-win_amd64.whl (2454.8 MB)`

**Comment by hipsterusername** [comment]
There is indeed a reason for the re-downloads - Previously, when using updates, many users would have Torch redownload a CPU-only version of Torch. This is due to poor packaging on the Torch side for Windows.

Forcing the download of the GPU version resolves this issue, but obviously creates some bloat.

**Comment by psychedelicious** [comment]
Actually, it is unexpected that the packages are re-downloaded.

We use `--force-reinstall` in the installer, but that still uses the `pip` cache, which is managed entirely by `pip`. We don't interact with it.

If `pip` is re-downloading packages, I don't think there is anything we can do about it. My understanding is that `pip` will periodically empty the cache, but I don't know what triggers this. You empty do it manually using `pip cache purge`, optionally providing a package name, but again - we do not do this.
