### ISSUE TITLE
[bug]: Unable to connect via LAN

### ISSUE THREAD

**Issue by ha7rock** [invoke-ai/InvokeAI#6500]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX4090

### GPU VRAM

24GB

### Version number

4.2.4

### Browser

Arc

### What happened

invokeai-web --host 0.0.0.0
usage: invokeai-web [-h] [--root ROOT] [--config CONFIG_FILE] [--version]
invokeai-web: error: unrecognized arguments: --host 0.0.0.0

### What you expected to happen

Listening on 0.0.0.0 for access by network devices

**Comment by psychedelicious** [comment]
Edit the `invokeai.yaml` file as described here: https://invoke-ai.github.io/InvokeAI/features/CONFIGURATION/#invokeai-configuration-file
