### ISSUE TITLE
Error encountered upon updating to version 4.2.4: XL models fail to execute.

### ISSUE THREAD

**Issue by zero2999** [invoke-ai/InvokeAI#6506]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

NVIDIA GeForce RTX 3060 Mobile

### GPU VRAM

6GB

### Version number

4.2.4

### Browser

Edge 125.0.2535.92

### Python dependencies

{
  "accelerate": "0.30.1",
  "compel": "2.0.2",
  "cuda": "12.1",
  "diffusers": "0.27.2",
  "numpy": "1.26.4",
  "opencv": "4.9.0.80",
  "onnx": "1.15.0",
  "pillow": "10.3.0",
  "python": "3.10.12",
  "torch": "2.2.2+cu121",
  "torchvision": "0.17.2",
  "transformers": "4.41.1",
  "xformers": "0.0.25.post1"
}

### What happened

Hello, previously you were utilizing version 4.2.3 featuring XL models intended for installation (Juggernaut-XL-v9 and dreamshaper-xl-v2-turbo), encountering no issues except for model installations. However, upon upgrading to version 4.2.4, which purportedly includes optimizations addressing the model installation issue, the problem persists. Now, there's an additional error when executing Juggernaut-XL-v9 and dreamshaper-xl-v2-turbo. Instead of the expected improvements, these optimizations seem to have adversely affected functionality, compelling me to revert to the prior version. I urge you to address this issue promptly, as the anticipated resolution for Civitai model installation errors has not materialized; in fact, functionality has been compromised entirely

![error01](https://github.com/invoke-ai/InvokeAI/assets/3674609/06ea35a3-9962-47be-85b1-c8a09f93de23)

![error](https://github.com/invoke-ai/InvokeAI/assets/3674609/6e62aa9d-8188-43ef-beae-397f736ff343)

### What you expected to happen

I was hoping that with this update, the issue of being unable to generate images with models downloaded from Civitai would have been resolved.

### How to reproduce the problem

downlad models of civitai

**Comment by psychedelicious** [comment]
This error isn't related to model installation. It's saying your GPU does not have enough VRAM. We don't expect SDXL models to work with a 6GB card - you need 8GB VRAM.

**Comment by zero2999** [comment]
but in the previous version, I could use it with 6 GB of VRAM, and now I can't. That's the point. This is forcing me to install the previous version, which does give me results.
