### ISSUE TITLE
[enhancement]: Inpainting node

### ISSUE THREAD

**Issue by thnake** [invoke-ai/InvokeAI#6507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

It would be great if there existed a node for inpainting similar to the unified canvas. Also, I would like to do some  processing on the masks. E.g. dilating a version of the mask and apply the original to the base layer and a dilated version to the mask area.

I assume that a big part of the necessary code already exists for the unified canvas.

Thanks!

**Comment by hipsterusername** [comment]
It may not be apparent, but everything (including the canvas) already runs on nodes!

Inpainting is done by creating a "Gradient Denoise Mask" and passing that into the Denoise Mask field. Then, you use the resulting mask to "Paste back" the new image on top of the base image.

Hope that helps! :)
