### ISSUE TITLE
[enhancement]: Copy description from Starter Models tab into models table

### ISSUE THREAD

**Issue by lstein** [invoke-ai/InvokeAI#6528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

lincoln.stein@gmail.com

### What should this feature add?

When you install a model from the Starter Models tab, the description that gets written to the models table is the default one "<base> main model <name>". I would like to see the descriptions from the starter model data structure copied into the  database by passing a suitably initiated model `config`.

**Comment by psychedelicious** [comment]
Good call out, definitely makes sense to populate the description
