### ISSUE TITLE
[enhancement]: Is there a way to make API calls?

### ISSUE THREAD

**Issue by DataJuggler** [invoke-ai/InvokeAI#6581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

corby@datajuggler.com

### What should this feature add?

I am trying to build an automate Story Teller, and I have the pieces for story creation and text to speech for narration. I would like to automate image creation if  there is an API? I couldn't find anything in the documentation about this.

Thank you if I missed it.

### Alternatives

I could write a chrome or edge web driver, but I would prefer to not have to go that route.

### Additional Content

Just the ability to add items to the que to be processed while the console app is running. I can monitor the outputs directory to get the results.

Thanks,

**Comment by ausbitbank** [comment]
Yes there is an api, visit http://127.0.0.1:9090/docs in your local invoke install for more info

**Comment by DataJuggler** [comment]
Thank for the prompt reply.

**Comment by DataJuggler** [comment]
I know I closed this already, but after spending a day reading the docs, what method is the same as clicking the Invoke button? I successfully called the DynamicPrompts method, but that just seems to give me back a payload result of the prompt.

There is a little too much information on the page I don't understand, but I think the most basic question most developers would want is a simple 'Invoke' example. If it is there, I couldn't find it, but I have bad vision, so it could be obvious.

Thanks

**Comment by psychedelicious** [comment]
Hi @DataJuggler,

The application has the REST API, but is designed for the client, not external consumption. The API is thus not fully documented except in code. That said, you _can_ use it. Keep in mind we also use socket.io (websocket) for critical server-to-client communication. For example, when a node finishes execution, that is communicated via websocket. The client does not poll for results.

To see how it works, I'd suggest to inspect the network request that is sent when you click the invoke button. Enable the websocket monitor in your browser dev tools to see the socket messages. You can reverse-engineer it like this, or dig into the code to see how it works.

**Comment by DataJuggler** [comment]
Thanks for the reply. I don't even know how to open the entire project. I only work in Visual Studio.

**Comment by psychedelicious** [comment]
In case you were responding to my suggestion to "inspect the network request", I mean use the network tab if your browser's dev tools and take a look at the payload.

To get a more detailed picture of the API, you'd need to clone the repo and dig in. I'm sure VS can open the project just fine.

**Comment by Trismegiste** [comment]
@DataJuggler 

> I know I closed this already, but after spending a day reading the docs, what method is the same as clicking the Invoke button? I successfully called the DynamicPrompts method, but that just seems to give me back a payload result of the prompt.

Some insight here, since I'm currently working on the same problem to connect my RPG webapp to InvokeAI. 
I'm already using the API to make search in pictures boards but never tried picture generation.

The "Invoke documentation" is in the `queue` section at http://127.0.0.1:9090/docs#/queue
Specifically, a new image generation is added to the queue with the http://127.0.0.1:9090/docs#/queue/enqueue_batch entry point. It's a POST query with a bunch of JSON in the body.

If you look at the log of ./invoke.sh, you'll find this kind of messages at the end of generation :
```
[2024-08-17 10:43:39,226]::[uvicorn.access]::INFO --> 192.168.43.202:37098 - "POST /api/v1/queue/default/enqueue_batch HTTP/1.1" 200
[2024-08-17 10:43:39,330]::[uvicorn.access]::INFO --> 192.168.43.202:37098 - "GET /api/v1/queue/default/status HTTP/1.1" 200
[2024-08-17 10:43:39,571]::[uvicorn.access]::INFO --> 192.168.43.202:37098 - "GET /assets/images/invoke-alert-favicon.svg HTTP/1.1" 200
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 40/40 [00:26<00:00,  1.52it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:07<00:00,  1.43it/s]
[2024-08-17 10:44:16,376]::[InvokeAI]::INFO --> Graph stats: 26b8a276-480c-4f44-bda0-fb93f5ceb73e
                          Node   Calls   Seconds  VRAM Used
             sdxl_model_loader       1    0.000s     0.303G
            sdxl_compel_prompt       2    0.653s     1.311G
```

It's only by looking at the logs I figured out that the key parameter `{queue_id}` in /api/v1/queue/{queue_id}/enqueue_batch is equal to "**default**"

Then you make a GET query against `/api/v1/queue/default/current` to get the current job.
After that it's a websocket thing to know when the generation is complete.

Here is a start, I hope this helps. 
( DynamicPrompt is just an utility to generate prompts with the bracket syntax like `{man|woman} wearing {technician|pilot|scientist} outfit` which will give you 6 prompts for example )

**Comment by DataJuggler** [comment]
Thanks for all the info.

**Comment by KeesGeerligs** [comment]
Thanks for all the help. If any of you still struggle, this is what I got:

### Dockerfile with stable-diffusion-v1-5 in it: `k1llahkeezy/sd-invoke-bench:0.0.0`

```dockerfile
FROM ghcr.io/invoke-ai/invokeai

WORKDIR /invokeai

RUN mkdir -p /invokeai/models/stable-diffusion

COPY ./v1-5-pruned-emaonly.safetensors /invokeai/models/stable-diffusion/v1-5-pruned-emaonly.safetensors

EXPOSE 9090
```
### Running the Docker

You can run the Docker container using the following command:
```
docker run --runtime=nvidia --gpus=all --publish 9090:9090 docker.io/k1llahkeezy/sd-invoke-bench:0.0.0
```
### Python Script for Image Generation

This is the script I used. It installs the model and then runs an image generation POST request:
```
import requests
import json
import time

# API endpoints
scan_url = "http://localhost:9090/api/v2/models/scan_folder"
install_url = "http://localhost:9090/api/v2/models/install"
list_models_url = "http://localhost:9090/api/v2/models/"
enqueue_url = "http://localhost:9090/api/v1/queue/default/enqueue_batch"

# Model directory in Docker
model_dir = "/invokeai/models/stable-diffusion/"

# Step 1: Scan folder for models
scanned_models = requests.get(scan_url, params={"scan_path": model_dir}).json()

for model in scanned_models:
    model_key, model_hash = None, None
    if not model.get("is_installed"):
        install_response = requests.post(install_url, params={"source": model["path"], "inplace": True}, json={
            "name": "v1-5-pruned-emaonly", "description": "Stable Diffusion v1.5 model"})

        if install_response.status_code in [201, 409]:
            while True:
                time.sleep(.2)
                models = requests.get(list_models_url).json().get("models", [])
                installed_model = next((m for m in models if m["name"] == "v1-5-pruned-emaonly"), None)
                if installed_model:
                    model_key, model_hash = installed_model.get("key"), installed_model.get("hash")
                    break
        else:
            print(f"Installation failed: {install_response.status_code}")
    else:
        # Get the model information from the list of models
        models = requests.get(list_models_url).json().get("models", [])
        installed_model = next((m for m in models if m["name"] == "v1-5-pruned-emaonly"), None)
        if installed_model:
            model_key, model_hash = installed_model.get("key"), installed_model.get("hash")

    if model_key and model_hash:
        # Step 2: Enqueue image generation
        payload = {
            "batch": {
                "batch_id": "batch_001",
                "origin": "api",
                "destination": "gallery",
                "graph": {
                    "id": "graph_001",
                    "nodes": {
                        "model_loader": {
                            "id": "model_loader",
                            "type": "main_model_loader",
                            "model": {
                                "model_id": "ce4d5902-cc32-46f8-878a-0572c88459f8",
                                "model_type": "main",
                                "key": model_key,
                                "hash": model_hash,
                                "name": "v1-5-pruned-emaonly",
                                "base": "sd-1",
                                "type": "main"
                            }
                        },
                        "clip_skip": {
                            "id": "clip_skip",
                            "type": "clip_skip",
                            "skipped_layers": 0
                        },
                        "pos_cond": {
                            "id": "pos_cond",
                            "type": "compel",
                            "prompt": "a futuristic city at sunset"
                        },
                        "neg_cond": {
                            "id": "neg_cond",
                            "type": "compel",
                            "prompt": ""
                        },
                        "noise": {
                            "id": "noise",
                            "type": "noise",
                            "seed": 2812773272,
                            "width": 512,
                            "height": 512,
                            "use_cpu": False
                        },
                        "denoise_latents": {
                            "id": "denoise_latents",
                            "type": "denoise_latents",
                            "steps": 50,
                            "cfg_scale": 7.5,
                            "denoising_start": 0.0,
                            "denoising_end": 1.0,
                            "scheduler": "dpmpp_3m_k"
                        },
                        "core_metadata": {
                            "id": "core_metadata",
                            "type": "core_metadata",
                            "generation_mode": "txt2img",
                            "positive_prompt": "a futuristic city at sunset",
                            "negative_prompt": "",
                            "width": 512,
                            "height": 512,
                            "seed": 2812773272,
                            "rand_device": "cpu",
                            "cfg_scale": 7.5,
                            "steps": 50
                        },
                        "canvas_output": {
                            "id": "canvas_output",
                            "type": "l2i",
                            "width": 512,
                            "height": 512,
                            "fp32": True
                        }
                    },
                    "edges": [
                        {"source": {"node_id": "model_loader", "field": "unet"}, "destination": {"node_id": "denoise_latents", "field": "unet"}},
                        {"source": {"node_id": "model_loader", "field": "clip"}, "destination": {"node_id": "clip_skip", "field": "clip"}},
                        {"source": {"node_id": "clip_skip", "field": "clip"}, "destination": {"node_id": "pos_cond", "field": "clip"}},
                        {"source": {"node_id": "clip_skip", "field": "clip"}, "destination": {"node_id": "neg_cond", "field": "clip"}},
                        {"source": {"node_id": "pos_cond", "field": "conditioning"}, "destination": {"node_id": "denoise_latents", "field": "positive_conditioning"}},
                        {"source": {"node_id": "neg_cond", "field": "conditioning"}, "destination": {"node_id": "denoise_latents", "field": "negative_conditioning"}},
                        {"source": {"node_id": "noise", "field": "noise"}, "destination": {"node_id": "denoise_latents", "field": "noise"}},
                        {"source": {"node_id": "denoise_latents", "field": "latents"}, "destination": {"node_id": "canvas_output", "field": "latents"}},
                        {"source": {"node_id": "model_loader", "field": "vae"}, "destination": {"node_id": "canvas_output", "field": "vae"}}
                    ]
                },
                "runs": 1
            }
        }
        response = requests.post(enqueue_url, headers={"Content-Type": "application/json"}, data=json.dumps(payload))
        print("Image generation task enqueued successfully!" if response.status_code == 200 else f"Failed: {response.status_code}")
```

**Comment by psychedelicious** [comment]
Thanks @KeesGeerligs - I'll just note that the HTTP API is not intended for public consumption. We don't often make breaking changes to it, but we don't hesitate to do so when it serves the needs of the application.

I'm closing this issue as it's a "stable" public HTTP/socket API is not planned.

**Comment by VimukthiLakmal** [comment]
@KeesGeerligs I try this code . but the thing is when i try this code , the image generation request pass to the queue. but always it failed. Do you have any suggestion . 

it shows this error .

Server Error
ValueError: Only Transformer submodels are currently supported. Received: tokenize
