### ISSUE TITLE
ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11  ERROR: Could not find a version that satisfies the requirement python==3.12.4 (from versions: none)  ERROR: No matching distribution found for python==3.12.4   [notice] A new release of pip is available: 24.0 -> 24.1.2[bug]: 

### ISSUE THREAD

**Issue by Lovely-logesh** [invoke-ai/InvokeAI#6586]
![Screenshot 2024-07-07 225354](https://github.com/invoke-ai/InvokeAI/assets/146011778/a94a5142-8ddb-4271-a252-698d82fe36ad)
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

None (CPU)

### Version number

3.12.4

### Browser

chrome

### What happened

i am deploying an app in streamlit using github

### What you expected to happen

 i have to seen a output

### Discord username

logesh612003@gmail.com

**Comment by ebr** [comment]
We don't support Python 3.12 yet due to some of the dependencies not supporting it. This is in the works. Please use Python v3.11 or lower. **Use the installer from python.org, not from the Windows App Store**
