### ISSUE TITLE
[bug]:  Failed to delete image file

### ISSUE THREAD

**Issue by sanihaq** [invoke-ai/InvokeAI#6598]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

L4

### Version number

4.2.6a1

### Browser

Ms Edge

### What happened

[InvokeAI]::ERROR --> Failed to delete image file

### What you expected to happen

Image supposed to be deleted

### How to reproduce the problem

I was using a [lightning.ai](https://lightning.ai) instance and yes i have full access to the system and able to delete, create file. using a1111, comfyui with no problem

### Additional context

problem happened in previous version also, if you delete the files from outside, then you can delete file from ui without any problem. my guess it's a database issue. also, it happens with single and multiple delete.

**Comment by mickr777** [comment]
![Animation-1](https://github.com/user-attachments/assets/a07f920c-77db-46af-82fd-05947dea6466)
Sounds related to my issues so will add it here,

Strangely for me it seems to only effect large images and only on my windows install, mu linux one seems fine.

if I restart invoke I can then delete the ones that I failed to delete before

**Comment by hipsterusername** [comment]
Similar issue - on Windows.

**Comment by psychedelicious** [comment]
I think this has been an issue for a while but with some of the UI changes to the gallery it is now visible to the user. Investigating.
