### ISSUE TITLE
[enhancement]: Ability to edit the queue

### ISSUE THREAD

**Issue by 19wolf** [invoke-ai/InvokeAI#6637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I'd like the ability to edit items in the queue. Features like, changing the prompt, seed, etc. Basically the ability to pick an item or items from the queue and update the parameters before they run. Also the ability to sort the queue, which is a slightly different feature request I suppose.
On a similar thought, when using multiple phrases like {hot|cold}, it'd be useful to recall not only the prompt of an image but also the whole prompt string including what the dynamic prompt was

**Comment by psychedelicious** [comment]
Queue items are not easily editable. Each queue item is a dynamically generated graph plus some other data. While we technically could allow you to edit the graph, it would be _very_ easy to break things.

This would require a substantial amount of effort to implement and test, but only be useful for very niche use-cases.

Sorry, but this isn't something we will implement.

---

Sorting the view is something we could do - I think there may already be a request for that. And we could embed the whole dynamic prompt in the metadata.

Can you please do a quick search to see if we already have feature requests for these features, and if not, create individual feature requests for each? Ty!

**Comment by 19wolf** [comment]
6656, 6657

**Comment by psychedelicious** [comment]
Thanks for making the other issues @19wolf !
