### ISSUE TITLE
Better separator in dream-web.log

### ISSUE THREAD

**Issue by BunnyViking** [invoke-ai/InvokeAI#666]
**Is your feature request related to a problem? Please describe.**
It is difficult to parse the dream-web.log in a regular spreadsheet editor as all common delineators (except tab )are used in the regular syntax for dream.py prompts.

**Describe the solution you'd like**
adding a specific delineator (or some sort of post processing parser) to make it easier to separate dream-web.log into a more readable format.

**Additional context**
Ideally it would be a single unusual character not used in CLIP (i think thats the right word for here :D ) but a multi-character would be fine as that'd just add a manual step.

**Comment by cwallen** [comment]
Seems like this could be solved by https://github.com/lstein/stable-diffusion/pull/663

**Comment by mefengl** [comment]
Add a CSV format may help parse
