### ISSUE TITLE
[bug]: "No diffusers pipeline" known for base=sdxl-refiner, variant=normal

### ISSUE THREAD

**Issue by ghazel** [invoke-ai/InvokeAI#6666]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

macOS

### GPU vendor

Apple Silicon (MPS)

### GPU model

M2 Max

### GPU VRAM

96 GB

### Version number

v4.2.6post1

### Browser

Safari Version 17.5 (19618.2.12.11.6)

### Python dependencies

{
  "accelerate": "0.30.1",
  "compel": "2.0.2",
  "cuda": null,
  "diffusers": "0.27.2",
  "numpy": "1.26.4",
  "opencv": "4.9.0.80",
  "onnx": "1.15.0",
  "pillow": "10.3.0",
  "python": "3.10.11",
  "torch": "2.2.2",
  "torchvision": "0.17.2",
  "transformers": "4.41.1",
  "xformers": null
}

### What happened

Running txt2img, I get an error.  `"No diffusers pipeline" known for base=sdxl-refiner, variant=normal`

### What you expected to happen

Image generated

### How to reproduce the problem

Use sdxl-refiner

### Additional context

I decided to add this code, speculatively, and it seems to prevent the error. Though, I'm not sure it's the right answer:

```
diff --git a/invokeai/backend/model_manager/load/model_loaders/stable_diffusion.py b/invokeai/backend/model_manager/load/model_loaders/stable_diffusion.py
index d90352f0e..473695d38 100644
--- a/invokeai/backend/model_manager/load/model_loaders/stable_diffusion.py
+++ b/invokeai/backend/model_manager/load/model_loaders/stable_diffusion.py
@@ -98,6 +98,10 @@ class StableDiffusionDiffusersModel(GenericDiffusersLoader):
                 ModelVariantType.Normal: StableDiffusionXLPipeline,
                 ModelVariantType.Inpaint: StableDiffusionXLInpaintPipeline,
             },
+            BaseModelType.StableDiffusionXLRefiner: {
+                ModelVariantType.Normal: StableDiffusionXLPipeline,
+                ModelVariantType.Inpaint: StableDiffusionXLInpaintPipeline,
+            }
         }
         assert isinstance(config, MainCheckpointConfig)
         try:
```

**Comment by psychedelicious** [comment]
Hi, yep that's the fix. I just submitted a PR with it, then saw this issue. Was I chatting with you on discord about this? Will be sorted in the next release.

**Comment by ghazel** [comment]
I don’t use discord. Glad everyone came to the same conclusion.
