### ISSUE TITLE
[enhancement]: Directly call the content on the canvas for controlNet input

### ISSUE THREAD

**Issue by MOzhi327** [invoke-ai/InvokeAI#6672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I often use canvas selection to enhance the details of the picture. I hope to keep the structure of the picture but add more rich details. At this time, the tile model is very useful, but I need to save the contents of the selection first and then put it into the input of tile, which is not very convenient, especially I often use flat panel to work. 

### Alternatives

It would be great if an option could be added to the ControlNet of the canvas to directly read the contents of the selection on the canvas as the image input of the ControlNet.

**Comment by dunkeroni** [comment]
The "Import Image From Canvas" button will copy the bounding box area as the ControlNet input.
![Screenshot_20240726-153220.png](https://github.com/user-attachments/assets/71304225-b8fa-4e13-8c30-4a8045ebb786)

**Comment by MOzhi327** [comment]
@dunkeroni Thank you very much
