### ISSUE TITLE
[enhancement]: In Unified Canvas auto update imported images used in Control Adapters when the image or bounding box changes.

### ISSUE THREAD

**Issue by magnusviri** [invoke-ai/InvokeAI#6697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

magnusviri on discord

### What should this feature add?

In the Unified Canvas, if I have Control Adapers and I click "Import image from Canvas", it would be nice to be able to have a button that says to always update the image if I change the source image or if I change the bounding box. Or at least to notify. I frequently forget to update them and then the generated image is almost always garbage.

**Comment by MOzhi327** [comment]
Perhaps when the control image is empty, automatically using the selection area as the input is a better choice

**Comment by magnusviri** [comment]
5.0.0a5 solves this problem.
