### ISSUE TITLE
[enhancement]:on send2trash exception there should be a force delete option

### ISSUE THREAD

**Issue by sanihaq** [invoke-ai/InvokeAI#6709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I've previously submitted #6598 for this same issue. but the fix didn't solve it for me.
this solution does
```py
if image_path.exists():
                try:
                    send2trash(image_path)
                except Exception as e:
                    os.remove(image_path)
if thumbnail_path.exists():
                try:
                    send2trash(thumbnail_path)
                except Exception as e:
                    os.remove(thumbnail_path)
```

I'm not sure what approach you want to take, but this solves it for me. so please take a look. thanks

**Comment by psychedelicious** [comment]
Thanks, that seems like a reasonable fix. 

However, I think we should just remove send2trash entirely. The original intent for using this utility was to allow you to easily restore images. At the time we added it, there was no database, and we listed images by scanning the folder. We no longer do this, so restoring the image from trash does not restore it in the gallery. 

This utility and the message when you delete seems to imply you can undo the delete easily - which is not true. So I think we should remove this and just call os.remove (or Path.unlink). 

What do you think?

**Comment by sanihaq** [comment]
@psychedelicious I think making it more Stright forward is better. deleting should delete the image there shouldn't be any confusion. so "os.remove" would be the best choice, i think.
