### ISSUE TITLE
[enhancement]: Canvas - Zoom 100% (actual size) of the image/canvas

### ISSUE THREAD

**Issue by sonny4723** [invoke-ai/InvokeAI#6711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

The current reset view does not make the canvas zoom to 100% **if the image is too lagre**.
Sometimes, user wants to view the actual of the image with large size, a button or a hotkey for zooming actual size (100%) should help?

**Comment by psychedelicious** [comment]
IIRC if you double click the button it goes to exactly 100%.
