### ISSUE TITLE
[enhancement]: Please support FLUX.1

### ISSUE THREAD

**Issue by DavidCWGA** [invoke-ai/InvokeAI#6712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

david@gloveraoki.net

### What should this feature add?

Please support the new open-weights models from Black Forest Labs, FLUX.1.

https://huggingface.co/black-forest-labs

**Comment by AlgorithmicKing** [comment]
yes please really really need it

**Comment by sammcj** [comment]
Flux is _super_ impressive, can't wait!

**Comment by rufeng0411** [comment]
Flux is super impressive, can't wait!

**Comment by DualProphecy** [comment]
🙏yes please

**Comment by Chiaki** [comment]
Can't wait to see fulx support in InvokeAi

**Comment by rufeng0411** [comment]
please add flux，thanks alot

**Comment by ChibiChiii** [comment]
After extensively testing the versatility and accuracy of the Flux 1 model I can confidently say adding this model to Invoke AI would be a very large +. The quality of this model is like none other, creating accurate text at 98% times of the requests, having the prompt accuracy of Dall-E yet the versatality of Midjourney supporting Art-mediums from Watercolor painting to Anime/Manga Sketches. A rather impressive creation of Black Forrest indeed.

**Comment by jvnte** [comment]
Having that would be awesome!!!

**Comment by jameswan** [comment]
I already have Flux working in an InvokeAI workflow

**Comment by ChibiChiii** [comment]
> I already have Flux working in an InvokeAI workflow

would you be able & willing to create instructions as to how you did this? I think it would be very useful for other users as well as Flux is a very high-end model but at the moment most people need to use ComfyUI to use it.

**Comment by jameswan** [comment]
> > I already have Flux working in an InvokeAI workflow
> 
> would you be able & willing to create instructions as to how you did this? I think it would be very useful for other users as well as Flux is a very high-end model but at the moment most people need to use ComfyUI to use it.

<img width="939" alt="image" src="https://github.com/user-attachments/assets/df885767-f1db-4e75-a4e6-bf6d535db97a">

**Comment by jvnte** [comment]
New Diffusers release now supports `FluxPipeline` now: https://github.com/huggingface/diffusers/releases/tag/v0.30.0

**Comment by jameswan** [comment]
If that didn't work for you, then this:

<img width="934" alt="image" src="https://github.com/user-attachments/assets/be902bd4-d021-4f3a-b050-c6349691bc58">

**Comment by X13X** [comment]
> If that didn't work for you, then this:
> <img alt="image" width="934" src="https://private-user-images.githubusercontent.com/1128151/355784936-be902bd4-d021-4f3a-b050-c6349691bc58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNjQ4ODQsIm5iZiI6MTcyMzA2NDU4NCwicGF0aCI6Ii8xMTI4MTUxLzM1NTc4NDkzNi1iZTkwMmJkNC1kMDIxLTRmM2EtYjA1MC1jNjM0OTY5MWJjNTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDdUMjEwMzA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODM1ZjRlNWE1ZmNjMWQ1NjA1MjI3MjM4ZWUwY2M2MzhiMjI3MTUxNWI0MGE0OTAzMDhkMmQ1ZTRlM2U1NTI1NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.isuK4Vu3_wBQa7_eD1fl9DdxxS9nAIqe2xHRamuDmGE">

I can't do either.

I downloaded models from Civit and Hugginface and when it tries to import them via scan folder, invoke just crashes in the commandline.  

I can't import it from hugging face since you have to sign in.

**Comment by rufeng0411** [comment]
please support flux ！

**Comment by yescine** [comment]
didn' t worked downloading form HF black-forest-labs/FLUX.1-schnell

**Comment by MDsniper** [comment]
> > > I already have Flux working in an InvokeAI workflow
> > 
> > 
> > would you be able & willing to create instructions as to how you did this? I think it would be very useful for other users as well as Flux is a very high-end model but at the moment most people need to use ComfyUI to use it.
> 
<img width="1417" alt="Screenshot 2024-08-09 at 5 32 21 PM" src="https://github.com/user-attachments/assets/25efffe8-8959-45ce-866a-ac861e5a0565">

**Comment by MDsniper** [comment]
yeah Lies

**Comment by sammcj** [comment]
Howdy folks, I have no doubt that the Invoke team will be more than aware of Flux, what a leap forward it is and how the community is very keen to get it working with their favourite tool.

Although it's great to see the enthusiasm in the comments I would suggest showing your interest with an emoji reaction on the post, freeing up the comments for folks that have suggestions on how to help implement it.

This will help keep the signal to noise ratio high and although I'm not a maintainer - I could imagine I might find it a little stressful or feel like it's being demanded / expected (although I'm sure that's not the case).

Just my 2c and a ❤️ out to the maintainers of such a great open source tool.

**Comment by MDsniper** [comment]
Fair point

**Comment by X13X** [comment]
> I already have Flux working in an InvokeAI workflow

so was this a lie?

**Comment by airtonix** [comment]
> > I already have Flux working in an InvokeAI workflow
> 
> so was this a lie?

Yes because they didn't screenshot the import outcome like @MDsniper  did. (╯°□°)╯︵ ┻━┻

**Comment by airtonix** [comment]
Error is 

```
[2024-08-10 13:49:18,230]::[ModelInstallService]::ERROR --> Model install error: black-forest-labs/FLUX.1-dev
InvalidModelConfigException: Unable to determine model type for /mnt/Store/Applications/InvokeAi/models/tmpinstall_dd9x7x7x/FLUX.1-dev; class FluxPipeline is not one of the supported classes [StableDiffusionPipeline, StableDiffusionInpaintPipeline, StableDiffusionXLPipeline, StableDiffusionXLImg2ImgPipeline, StableDiffusionXLInpaintPipeline, LatentConsistencyModelPipeline, AutoencoderKL, AutoencoderTiny, ControlNetModel, CLIPVisionModelWithProjection, T2IAdapter]
```

**Comment by brhndursun** [comment]
bump!

**Comment by rufeng0411** [comment]
UP！

**Comment by X13X** [comment]
Any updates would be great!

**Comment by kwal559** [comment]
This is why we use other interfaces  The devs here dont care that you want it.  Nor do they care about Playground 2.5, or Kolors, or Aura, Flux, SD 3, or presets for Pony, or for so much, so much, because you aren't a paying customer.   Search all you like, there is no guide to install these major models.  So, download pinokio and choose from several different UI's to use them.. Even if you have 4 gigs of vram.. Some people just care enough to get things to work (and in 1 click installs). pinokio.computer (web site/download the app) will only give you one problem.. harddrive space.

**Comment by DavidCWGA** [comment]
For what it's worth, I've been using "Draw Things" on my Mac, which already supports Flux. The UI is a little quirky, but it's a native app and runs very well. And it's free.

**Comment by sammcj** [comment]
Folks, come on it's ok to be excited and even a little impatient at times but there's no need to rip out open source maintainers that write software for you for free. They owe you nothing.

**Comment by brhndursun** [comment]
We're thinking in the simple way. If other apps can run flux with a little research and upgrades, why anybody in community not making a PR for flux?

**Comment by sammcj** [comment]
I'm fairly sure there are PRs underway to get Flux working, e.g. https://github.com/invoke-ai/InvokeAI/pull/6739 - it just seems they're not ready yet.

When you compare InvokeAI to some of the other tools out there that have implemented it - InvokeAI is more of a product, it's large and is generally held to high standards, this is quite different from something like Comfy which is esentially a lot of different peoples scripts and packages that can be glued together in various ways - people can make great things due to the flexibility but - it's also a lot harder and much less refined.

I'm sure that if it was as simple as simply supporting the model, invoke would already have flux, but while I have no insider knowledge I'm assuming it's probably included as part of a larger piece of work with the intent of a better integrated outcome. (I'm just guessing here).

**Comment by brhndursun** [comment]
You're right. I think I got a little too exited about flux. Also that pr was opened 2 days ago. I've subscribed now and will keep a close eye on it.

**Comment by dbent** [comment]
> > bump!
> 
> well, 4 thumbs down from devs I guess. Deleting invokeAI. I'll will try pinokio as @kwal559 mentioned
> 
> Thank you @sammcj

From the record, I am one of the people that downvoted you and I am neither a developer of nor contributor to Invoke. The reason being that when you're subscribed to an issue GitHub sends an email for each comment. Your comment of "bump!" is not constructive and amounts to nothing more than spam in however many people's inboxes who have subscribed. There isn't even anything to "bump" since this isn't a classic forum thread where visibility is affected by the most recent comment. It's also especially glaring in light of the *extremely kind and patient* comment from @sammcj earlier informing people that the proper way to express interest in an issue on GitHub is via reaction emojis.

Now, I have to apologize to everyone I have further spammed for simply making this comment, but I wished to clarify things in case passerbys were left with the wrong impression due to your misattributed slight.

**Comment by hipsterusername** [comment]
@sammcj - Thanks. :)

For all, please recognize that unlike many other UIs, we have a much wider maintenance and development mandate. I appreciate people voicing their interest in it.

We’re aware of Flux, and we’re actively looking at setting up the foundation to support it long term, but that is a rapidly changing landscape. 

In addition to building this application, we’re actively spearheading work with the Open Model Initiative (joined the Linux Foundation this week), working to develop stronger IP protection for creators using these tools, and working on one of the biggest updates there has ever been to the canvas. We’re doing a lot for the ecosystem.

If you’re interested in seeing the process of adopting new features speed up, consider participating as a contributor. Else, I’d ask that you serve as an active cheerleader and vocal evangelist of our efforts as opposed to an entitled user of free and open source software.

Thanks to all who’ve been patient advocates - I hope you’ll be pleased with what we’ve got planned for you.

**Comment by Trismegiste** [comment]
> We're thinking in the simple way. If other apps can run flux with a little research and upgrades, why anybody in community not making a PR for flux?

If it's so simple, what are you waiting for to contribute to this repo ? :roll_eyes:

**Comment by rufeng0411** [comment]
we need flux,please

**Comment by brhndursun** [comment]
> @sammcj - Thanks. :)
> 
> For all, please recognize that unlike many other UIs, we have a much wider maintenance and development mandate. I appreciate people voicing their interest in it.
> 
> We’re aware of Flux, and we’re actively looking at setting up the foundation to support it long term, but that is a rapidly changing landscape.
> 
> In addition to building this application, we’re actively spearheading work with the Open Model Initiative (joined the Linux Foundation this week), working to develop stronger IP protection for creators using these tools, and working on one of the biggest updates there has ever been to the canvas. We’re doing a lot for the ecosystem.
> 
> If you’re interested in seeing the process of adopting new features speed up, consider participating as a contributor. Else, I’d ask that you serve as an active cheerleader and vocal evangelist of our efforts as opposed to an entitled user of free and open source software.
> 
> Thanks to all who’ve been patient advocates - I hope you’ll be pleased with what we’ve got planned for you.

So you mean flux is not your first priority. I dont think you guys care ppls thoughts on this platform. Even though you removed upgrade section cuz it is not working and we must download new installer. Dude just forget everything and make flux your first priority.

> > We're thinking in the simple way. If other apps can run flux with a little research and upgrades, why anybody in community not making a PR for flux?
> 
> If it's so simple, what are you waiting for to contribute to this repo ? 🙄

It is not about me. It is about even simple apps have managed to work with flux so why not invoke? Also it's been 2 weeks(18 days) since flux released. Enough said, up! bump! you guys have to make this one for your first priority. 

Feel free to thumbsdown this comment. I'll thank you later

**Comment by AlgorithmicKing** [comment]
> > @sammcj - Thanks. :)
> > For all, please recognize that unlike many other UIs, we have a much wider maintenance and development mandate. I appreciate people voicing their interest in it.
> > We’re aware of Flux, and we’re actively looking at setting up the foundation to support it long term, but that is a rapidly changing landscape.
> > In addition to building this application, we’re actively spearheading work with the Open Model Initiative (joined the Linux Foundation this week), working to develop stronger IP protection for creators using these tools, and working on one of the biggest updates there has ever been to the canvas. We’re doing a lot for the ecosystem.
> > If you’re interested in seeing the process of adopting new features speed up, consider participating as a contributor. Else, I’d ask that you serve as an active cheerleader and vocal evangelist of our efforts as opposed to an entitled user of free and open source software.
> > Thanks to all who’ve been patient advocates - I hope you’ll be pleased with what we’ve got planned for you.
> 
> So you mean flux is not your first priority. I dont think you guys care ppls thoughts on this platform. Even though you removed upgrade section cuz it is not working and we must download new installer. Dude just forget everything and make flux your first priority.
> 
> > > We're thinking in the simple way. If other apps can run flux with a little research and upgrades, why anybody in community not making a PR for flux?
> > 
> > 
> > If it's so simple, what are you waiting for to contribute to this repo ? 🙄
> 
> It is not about me. It is about even simple apps have managed to work with flux so why not invoke? Also it's been 2 weeks(18 days) since flux released. Enough said, up! bump! you guys have to make this one for your first priority.
> 
> Feel free to thumbsdown this comment. I'll thank you later

+1

**Comment by rufeng0411** [comment]
> > > @sammcj - Thanks. :)
> > > For all, please recognize that unlike many other UIs, we have a much wider maintenance and development mandate. I appreciate people voicing their interest in it.
> > > We’re aware of Flux, and we’re actively looking at setting up the foundation to support it long term, but that is a rapidly changing landscape.
> > > In addition to building this application, we’re actively spearheading work with the Open Model Initiative (joined the Linux Foundation this week), working to develop stronger IP protection for creators using these tools, and working on one of the biggest updates there has ever been to the canvas. We’re doing a lot for the ecosystem.
> > > If you’re interested in seeing the process of adopting new features speed up, consider participating as a contributor. Else, I’d ask that you serve as an active cheerleader and vocal evangelist of our efforts as opposed to an entitled user of free and open source software.
> > > Thanks to all who’ve been patient advocates - I hope you’ll be pleased with what we’ve got planned for you.
> > 
> > So you mean flux is not your first priority. I dont think you guys care ppls thoughts on this platform. Even though you removed upgrade section cuz it is not working and we must download new installer. Dude just forget everything and make flux your first priority.
> > 
> > > > We're thinking in the simple way. If other apps can run flux with a little research and upgrades, why anybody in community not making a PR for flux?
> > > 
> > > 
> > > If it's so simple, what are you waiting for to contribute to this repo ? 🙄
> > 
> > It is not about me. It is about even simple apps have managed to work with flux so why not invoke? Also it's been 2 weeks(18 days) since flux released. Enough said, up! bump! you guys have to make this one for your first priority.
> > 
> > Feel free to thumbsdown this comment. I'll thank you later
> 
> +1

+1

**Comment by brhndursun** [comment]
> @brhndursun
> 
> > Deleting invokeAI. I'll will try pinokio as @kwal559 mentioned
> 
> This is not an airport, no need to announce your departure

Thank you for your funny joke but I think I can tell anything except hurting your feelings. Did that hurt you?

Also I made my own way to use flux. I told you, it is not that hard. I guess invoke core system makes it harder to implement. I can use comfy too but I just want to use it in invoke that's all.

**Comment by X13X** [comment]
> > @brhndursun
> > > Deleting invokeAI. I'll will try pinokio as @kwal559 mentioned
> > 
> > 
> > This is not an airport, no need to announce your departure
> 
> Thank you for your funny joke but I think I can tell anything except hurting your feelings. Did that hurt you?
> 
> Also I made my own way to use flux. I told you, it is not that hard. I guess invoke core system makes it harder to implement. I can use comfy too but I just want to use it in invoke that's all.

So if you found your own way, you could of found a way to implement it into invokes codebase and shared it.

The only reason I'm not attempting it is because I have the time, but you had enough time to make your own implementation of it....

So why not just fork and push and share it with us?

**Comment by brhndursun** [comment]
> > > @brhndursun
> > > > Deleting invokeAI. I'll will try pinokio as @kwal559 mentioned
> > > 
> > > 
> > > This is not an airport, no need to announce your departure
> > 
> > 
> > Thank you for your funny joke but I think I can tell anything except hurting your feelings. Did that hurt you?
> > Also I made my own way to use flux. I told you, it is not that hard. I guess invoke core system makes it harder to implement. I can use comfy too but I just want to use it in invoke that's all.
> 
> So if you found your own way, you could of found a way to implement it into invokes codebase and shared it.
> 
> The only reason I'm not attempting it is because I don't have the time, but you had enough time to make your own implementation of it....
> 
> So why not just fork and push and share it with us?

It is working on pure python without front end or invoke. I don't have time to work with invoke system. You can use ComfyUI or huggingface spaces too.

**Comment by deepblue96** [comment]
As much as I love comfyUI I would also like to be able to use invoke with Flux, so please add support.

**Comment by mirek190** [comment]
I am also waiting for it!

**Comment by brandonrising** [comment]
An initial experimental implementation of Flux is now available on [v4.2.9rc1](https://github.com/invoke-ai/InvokeAI/releases/tag/v4.2.9rc1)! We will be working on extending it to support different formats of the base model as well as loras/img2img/etc over the next week or two. Please refer to the release notes to see how flux is installed and used in its current form within Invoke if you choose to install this release candidate. Thank you everyone for your patience!

**Comment by sammcj** [comment]
Love your work! ❤️ 

> Thank you everyone for your patience
...
> **everyone**
👀
🤣 😅 

Seriously, looking at your changes that was quite an effort - well done!

**Comment by dlsniper** [comment]
@brandonrising and everyone else who contributed to that PR, Thank you!

**Comment by MDsniper** [comment]
So today I  saw flux in invoke to downlaod but I can't select it to use:

![Screenshot 2024-08-28 192912](https://github.com/user-attachments/assets/695ac943-2e92-4d1a-9e43-5b87700f471e)

**Comment by MDsniper** [comment]
If any one knows how to use it please let me know

**Comment by MDsniper** [comment]
https://github.com/invoke-ai/InvokeAI/releases/tag/v4.2.9rc1

https://private-user-images.githubusercontent.com/6750888/361906910-474d2f8a-cc72-4c09-8a82-fe434afbc37e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4ODg4MjksIm5iZiI6MTcyNDg4ODUyOSwicGF0aCI6Ii82NzUwODg4LzM2MTkwNjkxMC00NzRkMmY4YS1jYzcyLTRjMDktOGE4Mi1mZTQzNGFmYmMzN2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMjM0MjA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGNiZTM5Y2FhMTBiZWMyYTdmNWE0NGIxMDNhZGQyYjI4MDQ4MDViM2MyYTM1NjYzYTVhNWYwOWJjN2U4Mzk1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aaxXlOdJfvgTIce_uRFJEBj0ijL1-KDGGTegwebS8NI

**Comment by JorgeR81** [comment]
> Below are additional details on which model to use based on your system:
> 
> - FLUX dev quantized starter model: non-commercial, >16GB RAM, ≥12GB VRAM
> - FLUX schnell quantized starter model: commercial, faster inference than dev, >16GB RAM, ≥ 12GB VRAM
> - FLUX dev starter model: non-commercial, >32GB RAM, ≥24GB VRAM, linux OS
> - FLUX schnell starter model: commercial, >32GB RAM, ≥24GB VRAM, linux OS


Are these minimum requirements ? 
Or recommendations for better performance ?

**Comment by damiano1996** [comment]
Hi @JorgeR81, by enabling CPU offloading I'm able to run FLUX.1-dev on my laptop with Nvidia RTX 500 Ada Generation (4094MiB) and it takes around 260 seconds to generate an image 1024x1024.
But currently I'm not able to run it with InvokeAI since (in the best of my knowledge) CPU offloading is not configurable. In case, it would be awesome to make it configurable

**Comment by TheBarret** [comment]
> I'm fairly sure there are PRs underway to get Flux working, e.g. #6739 - it just seems they're not ready yet.
> 
> When you compare InvokeAI to some of the other tools out there that have implemented it - InvokeAI is more of a product, it's large and is generally held to high standards, this is quite different from something like Comfy which is esentially a lot of different peoples scripts and packages that can be glued together in various ways - people can make great things due to the flexibility but - it's also a lot harder and much less refined.
> 
> I'm sure that if it was as simple as simply supporting the model, invoke would already have flux, but while I have no insider knowledge I'm assuming it's probably included as part of a larger piece of work with the intent of a better integrated outcome. (I'm just guessing here).

"Glued together" one way of saying its unprofessional. geesh lol
