### ISSUE TITLE
[bug]:  UserWarning: 1Torch was not compiled with flash attention.

### ISSUE THREAD

**Issue by KagaroNakaza** [invoke-ai/InvokeAI#6722]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX3050

### GPU VRAM

6gb

### Version number

4.2.7post1

### Browser

Chrome 127.0.6533.89

### Python dependencies

C:\Users\joaom\ia\invokeai\.venv\lib\site-packages\diffusers\models\attention_processor.py:1279: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)

### What happened

This warning appears when using the new upscaler function. Each iteration takes approximately 200 seconds to perform, whereas in the previous mode it only takes a few seconds to upscale the image.

### What you expected to happen

That the image was generated quickly.

**Comment by psychedelicious** [comment]
- When you say "new upscaler", do you mean the upscaling tab or the upscale button rendered above the viewer image?
- When you say "previous mode", what do you mean?

**Comment by KagaroNakaza** [comment]
When I say "new upscaler", I mean the new tab, and when I said "previous mode", I mean the button above the viewer image. Sorry, I'm using a translator.

**Comment by psychedelicious** [comment]
No worries just want to understand the issue.

The button above the viewer image still exists and is the most performant and efficient way to upscale.

The new upscale tab is doing a fancy img2img. It uses a Stable Diffusion model and 2 ControlNets, so it has much higher VRAM requirements than the button above the viewer. Such slowness is the same cause as in #6723.

With 6GB I think you should be able to use the upscaling tab with a SD1.5 model without triggering the very slow GPU Sharing. SDXL definitely needs too much VRAM.

From my testing (included in the release notes for the upscaling tab):
> The main SD model architecture has the biggest impact on VRAM usage. For example, SD1.5 @ 2k needs just under 4GB, while SDXL @ 2k needs just under 9GB. VRAM usage increases a small amount as output size increases - SD1.5 @ 8k needs ~4.5GB while SDXL @ 8k needs ~10.5GB.

**Comment by KagaroNakaza** [comment]
I understand. I'm an AI enthusiast, not at all professional. In my case, I use a notebook with these configurations, so there is no way to upgrade components. I was using ForgeUi with SDXL with controlnets and ipadapters without any delay problems. Even the automatic1111 with low-vram managed to run smoothly. But, definitely none of them compare to InvokeAi, both in terms of aesthetics and functionalities. I'm sad to know that I won't be able to go beyond SDXL without adding controlnets or ipadapters to InvokeAi. Thank you for taking the time to respond to me.

**Comment by psychedelicious** [comment]
You're welcome, hopefully we can reduce the system requirements in the future so Invoke can be more useful for you and others without big GPUs!
