### ISSUE TITLE
[bug]: Images saved as full.png rather than the actual file name

### ISSUE THREAD

**Issue by tsinik55** [invoke-ai/InvokeAI#6730]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 4090

### GPU VRAM

24

### Version number

v4.2.7post1

### Browser

Chrome 127.0.6533.89

### What happened

When an image is opened in a new tab and dragged to the Desktop or a folder, it is saved as full.png rather than the actual file name.

### What you expected to happen

The file is copied to the desktop or to a folder with it's full file name, i.e. df7c40d5-6f1e-48f8-bd65-d49603c95d45.png

### How to reproduce the problem

1. Right-click the image thumbnail in the Images tab.
2. In the context menu, select "Open in New Tab"
3. Switch to the newly opened tab and drag the image to the desktop or to a folder

### Additional context

The bug is present in version 4.2.6 and later

### Discord username

jackofallbrakes

**Comment by psychedelicious** [comment]
I have a feeling this is caused by #6607.
