### ISSUE TITLE
[bug]: Skeleton images are not converted correctly in openpose-sdxl

### ISSUE THREAD

**Issue by tsinik55** [invoke-ai/InvokeAI#6732]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 4090

### GPU VRAM

24

### Version number

v4.2.7post1

### Browser

Chrome 127.0.6533.89

### What happened

Skeleton images are not converted correctly in openpose-sdxl: all bone information is lost, only two points are generated.

Image used (generated in openposeai.com):
![mothman_1](https://github.com/user-attachments/assets/63c7c008-fe99-4b0f-9dc7-ea1ce980383f)

Uploaded to the Assets tab
![Assets](https://github.com/user-attachments/assets/395ea8c8-2785-46f3-bdcd-9e3c22d41a0b)

Converted image
![Converted](https://github.com/user-attachments/assets/a6021f4b-695b-436f-90b2-e4da451c917a)

### What you expected to happen

Skeleton images are correctly converted in openpose-sdxl, including all bones

### How to reproduce the problem

1. Install openpose-sdxl from the official sources via the Models interface
2. Switch to the Generation interface and upload the attached image to the Assets tab
4. Switch to the Control Layers tab and add a new Global Control Adapter
5. Change control adapter to openpose-sdxl
6. Drag the attached image to the adapter reference image

### Discord username

jackofallbrakes

**Comment by hipsterusername** [comment]
User error.

You are passing in a pre-processed image, which means you need to expand the advanced controls of the controlnet and turn off the processor. You'll note that your image is all black on the control layer (indicating it tried to re-analyze the already processed pose, and found nothing.)

**Comment by tsinik55** [comment]
Thank you!
