### ISSUE TITLE
[enhancement]:  Alphabetical board sorting.

### ISSUE THREAD

**Issue by DustyShoe** [invoke-ai/InvokeAI#6757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

In my personal humble opinion there should be an alphabetical order for boards as an addition to sorting by time created. It will add an ability to customise boards order by adding leading number or letter. To someone like me with 30+ boards it will greatly improve board management.

**Comment by mickr777** [comment]
I will add to this maybe also board pinning
