### ISSUE TITLE
Portable Verison?

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#676]
Greetings,

In the spirit of having a portable version of the sd project and by that I mean, empower to copy and paste the entire project to other PCs without having all the install shenanigan. That said, the steps I've taken seems like a good start but nonetheless, it's partially working.

steps on dev pc:
removed python if any
Install git
Install miniconda3
run Anaconda Powershell Prompt (miniconda3)
cd C:\
git clone https://github.com/lstein/stable-diffusion.git
cd C:\stable-diffusion
conda env create -f environment.yaml
I do NOT "conda activate ldm"
copy the envs/ldm to stable-diffusion directory
Uninstall miniconda3 and git
remove any python environment variable, if any

Prior to start dream.py, I set python environment variable to "stable-diffusion/envs/ldm" on the fly and boom, it works beautifully.  The problem is that when copied over another PC, I get:

dream.py", line 12, in <module>
    import ldm.dream.readline
ModuleNotFoundError: No module named 'ldm'

So, somewhere in the process something seems to remain on my dev pc that it is not porting over the vanilla PC. Any idea what that might be?

**Comment by tildebyte** [comment]
It's not going to work without conda. All virtual environment tools (conda, pew, etc.) rely on setting environment variables, and other tricks to redirect the OS to use the "wrapped" Python.

There *are* ways to make portable Python apps, but we're not anywhere near there yet.

**Comment by Neosettler** [comment]
Thank you tildebyte, 

I see no env variables. Any explanation why it does work after uninstalling conda? What are the other tricks in question?

**Comment by tildebyte** [comment]
I don't know; I don't use conda.

pew does the following to the environment on Windows:

- PATH=/c/Users/USER/.virtualenvs/stable-diffusion-stable/Scripts;REST_OF_EXISTING_PATH
- VIRTUAL_ENV=C:\Users\USER\.virtualenvs\stable-diffusion-stable

but it's possible that the `pew workon` command does other things which I don't know about.

**Comment by Neosettler** [comment]
thank you tildebyte, I'd like to move this OP as an official feature request. It should be pretty basic since Conda encapsulate the entire Python environment into a single folder. All that remains is to figure what `conda activate ldm` really does. I'm guessing environment variables are set on the fly and that's pretty much it.

**Comment by Dschogo** [comment]
Its very doable. I personally like my venv's directly next to my app, and makes them kind of portable.
Do the following for that:

1. Open a Terminal in the root of the project
2. execute `python -m venv /path/to/new/virtual/environment` (python can be python3, depends on your setup; path would be for me: `/root_of_app/.venv/`)
3. Activate the venv by the correct activation script inside the `venv/scripts/`
4. Install the requirements.txt for your OS directly via `pip install -r requirements-xxx.txt` or make one yourself out of the conda environment.yaml

Done, now you can run the app just normally. You can copy the whole project (including the venv folder ofc) and it'll still work, as long as you activate the venv first.

Also with every start of the terminal, you have to activate the venv again. (VS code does that automatically so i dont have to). 
You can also create a shortcut for that, just google for your OS (+ auto start the dream server also possible, with a little bash/batch)

**Comment by Neosettler** [comment]
I should have mentioned that I'm on Windows 10. By venv, did you mean "Environment variables"? I have no idea what step 3 entails... 
In all cases, the goal is the start dream.py with command line/batch file where all the Python registering is done in one go, setting environment variables included. I mean, that should be easy enough... 

A bit of background, I'm running a QT C++ app to start a Python process like so:

```
	QStringList l_arguments;
	l_arguments << "-E";
	l_arguments << QString("%1/scripts/dream.py").arg(m_ApiPath);
	l_arguments << "--model" << l_model;
	l_arguments << "--sampler" << l_sampler;

	QStringList l_paths;
	l_paths << "PythonRoot";
	l_paths << QString("PythonRoot/Scripts").arg(l_pathPython);
	l_paths << QString("PythonRoot/Library/bin").arg(l_pathPython);
	l_paths << QString("PythonRoot/Lib").arg(l_pathPython);

	QProcessEnvironment l_env = QProcessEnvironment::systemEnvironment();
	l_env.insert("Path", QString("%1;%2").arg(l_paths.join(";")).arg(QString(qgetenv("Path"))));

	m_QtProcess->setProgram(l_command);
	m_QtProcess->setArguments(l_arguments);
	m_QtProcess->setProcessEnvironment(l_env);
	m_QtProcess->start();
```

Is there anything missing that Conda does under the hood that would solve the OP error?

**Comment by Neosettler** [comment]
Thank you Scchogo. The idea is not to have anything to point anywhere, portable! Copy/paste folder and it works! Everything should be solved running a batch file or a python script inside the root folder. For the sake of distributing the thing for the common user and collectively stop the shenanigan madness.

**Comment by Neosettler** [comment]
I'm getting at the end of my rope with this. Would anyone know how would the environment variables be set using a batch file to launch dream.py?

**Comment by Neosettler** [comment]
@Dschogo, maybe the venv works on your machine but the venv config file has a hardcoded path to where python is installed and the default is under the user account. It wont work on another machine. Also, the fact that venv requires to install Python on your machine is not a portable solution. Targeting the pyhton.exe straight from the venv folder does create a endless loop launching several python.exe to infinity and beyond.
