### ISSUE TITLE
[bug]: 2.4.8 update is still 2.4.7.post1 after update

### ISSUE THREAD

**Issue by evilduck1** [invoke-ai/InvokeAI#6768]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

rtx 3090 ti

### GPU VRAM

24

### Version number

2.4.7.post1

### Browser

firefox 129.0.2

### What happened

after installing 2.4.8 update and restarting invokeai and refreshing the page 2.4.7.post1 is still installed.

### What you expected to happen

to have invokeai 2.4.8 installed

**Comment by athpg** [comment]
Same issue happen to me.

**Comment by evilduck1** [comment]
im thinking, they just uploaded 2.4.7.post1 and not 2.4.8

**Comment by athpg** [comment]
good, thanks for sharing

**Comment by psychedelicious** [comment]
The release workflow hadn't completed fully and the package wasn't published to pypi. It's fixed now.
