### ISSUE TITLE
Pip failing with No matching distribution found for opencv-python==4.6.0

### ISSUE THREAD

**Issue by shaposhnyk** [invoke-ai/InvokeAI#677]
**Describe your environment**
- CPU arch: Apple M1 Pro
- RAM: 16G
- OS: MacOs 12.4
- Python: miniconda
- Branch: development, main
- Commit: commit d1a2c4cd8cf4e5b743300d9eab77da0a044213a7 (HEAD -> development)
Author: psychedelicious <4822129+psychedelicious@users.noreply.github.com>
Date:   Sat Sep 17 03:18:15 2022 +1000
React web UI with flask-socketio API (#429)

**Describe the bug**
A following command 'PIP_EXISTS_ACTION=w CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac.yaml' fails with an error: 

Collecting flask_cors==3.0.10
  Using cached Flask_Cors-3.0.10-py2.py3-none-any.whl (14 kB)
Collecting dependency_injector==4.40.0
  Using cached dependency-injector-4.40.0.tar.gz (912 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting eventlet
  Using cached eventlet-0.33.1-py2.py3-none-any.whl (226 kB)

Pip subprocess error:
  Running command git fetch -q --tags
  Running command git reset --hard -q 24268930bf1dce879235a7fddd0b2355b84d7ea6
  Running command git fetch -q --tags
  Running command git reset --hard -q d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
  Running command git fetch -q --tags
  Running command git reset --hard -q 3e976ef2508a7173240a897d2a4f5113124f5029
  Running command git fetch -q --tags
  Running command git reset --hard -q 65034f83e732e18add4a033ff39440617b5c5c6a
ERROR: Could not find a version that satisfies the requirement opencv-python==4.6.0 (from versions: 3.4.0.14, 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.15.55, 3.4.16.57, 3.4.16.59, 3.4.17.61, 3.4.17.63, 3.4.18.65, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.3.56, 4.5.4.58, 4.5.4.60, 4.5.5.62, 4.5.5.64, 4.6.0.66)
ERROR: No matching distribution found for opencv-python==4.6.0

failed

CondaEnvException: Pip failed

**Expected behavior**
Environment setup finishes correctly

**Comment by tildebyte** [comment]
As a stopgap, edit environment-mac.yaml and replace `opencv-python==4.6.0` with `opencv-python==4.6.*`

**Comment by lstein** [comment]
I had the same problem in an HPCC environment. Fortunately I found that the admins had compiled an opencv version and made it available in a private wheel.

**Comment by psychedelicious** [comment]
Having successfully created our env several times over the past few days, and considering the substantial changes made since this issue was created, I am closing this. Please create a new issue if you still have this problem on the main or development branch.
