### ISSUE TITLE
Disconnected after trying to install flux.dev

### ISSUE THREAD

**Issue by Nicholasvoador** [invoke-ai/InvokeAI#6782]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 2070 SUPER

### GPU VRAM

8GB

### Version number

4.2.8

### Browser

Opera

### What happened

I try to install local models with safetensors extension, I tried a few ones but I especially want to use FLUX and when I try to install with the model already downloaded on my computer, it gets an error or it just disconnects from the UI when trying to install any local models

### What you expected to happen

I expected the models to be installed succesfully

### How to reproduce the problem

Start the app, scan folders to install local models, error shows up or UI disconnects

### Discord username

nicholasvoador

**Comment by brandonrising** [comment]
Flux currently only has prototype support on [this new release candidate](https://github.com/invoke-ai/InvokeAI/releases/tag/v4.2.9rc1). Any previous version of the app will be unable to handle flux models. If you choose to install the new release candidate, please follow the instructions in the release notes to learn how to install and use flux models within the workflow editor.
