### ISSUE TITLE
[bug]: Language Setting & Sudden Crashes

### ISSUE THREAD

**Issue by BoyX69** [invoke-ai/InvokeAI#6790]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

None (CPU)

### GPU model

---

### GPU VRAM

---

### Version number

4.2.8

### Browser

M. Edge

### Python dependencies

I also had some crashes while generating the image.
![3](https://github.com/user-attachments/assets/bd1d63f0-ba24-481b-901d-08fd77413e5a)

### What happened

I started experimenting with Invoke Ai today. When I try to set the program to Italian (in the settings) there is no way to change it (even if I restart the program several times). In the settings there is a function for NSFW images but it doesn't work: I can't find a way to view NSFW images (a yellow triangle appears that prevents both viewing and editing them in the program). Apart from the extreme slowness (about 20 minutes to generate an image of (512x 512 even if this is due to my lack of a dedicated graphics card) I have already had several crashes with the appearance of a warning that I don't understand (warning shown in the image in this message). Thank.

![3](https://github.com/user-attachments/assets/2fc24cfc-8244-4a1e-aec9-6d51aaa882fb)

### What you expected to happen

Having already installed on the computer (3 models and I am already at more than 17 GB of occupied space) I would expect a greater speed in the creation of the image. If I have to wait 20 - 30 minutes (for a single image) I would say that I would willingly want to go back to M. Copilot which, in less than a minute, generates the beauty of 4 images. It would be useful (and interesting) to have the possibility of adjusting the image dpi (starting from a minimum of 96 - 192 - 288 dpi). I think that there are too many models to install, they take up a lot of space (too much space) and, in my opinion, they should be grouped together more (that is, a model that can interpret more types of creative style) and perhaps be able to create greater compression (so that with 500 MB of space you get results like those that currently take up double and a half the space).

### How to reproduce the problem

---

### Additional context

---

**Comment by BoyX69** [comment]
Furthermore, when it crashes, I lose all the photo's programming data (prompt) with all the photo's settings with loss of the graphic preview... 
![5](https://github.com/user-attachments/assets/9fa733b0-587a-4ee1-96a0-26c3ec4007ee)

**Comment by BoyX69** [comment]
I'm making a small correction because now it seems that the NSFW filter works correctly. Thanks.

**Comment by BoyX69** [comment]
Even the language now seems to work. I rebooted after changing the settings but probably the reboot resets the original setting... And when you reopen the program everything goes back to the initial settings. Maybe there is a system to save (or create) presets to save the settings (maybe there is but I have to find it...).

**Comment by BoyX69** [comment]
One thing I've noticed is that when I reopen the program I get old prompts with old searches and I don't know where to go to reset the prompts I've set up until now... Then I don't understand why this program should work from the browser and not like any other portable program...

**Comment by BoyX69** [comment]
Sorry but, how do you download the package from GitHub so, inside the package, there can very well be the portable version bootable from a compatible PC (and available) for Windows - Mac and Linux... I saved the IP address so as not to have to open it every time from the command prompt (.cmd) but the program does not open and seems not to be there. So, every time, I have to start it from a file (.bat for Windows...).

**Comment by psychedelicious** [comment]
Hi,

You have raised many unrelated questions/comments here. Sorry, but it is not possible to address them like this.

For general questions, please use our [discord](https://discord.gg/ZmtBAhwWhy).

Because it is not clear if there is actually a problem at this point, and because this issue is too scattered to support meaningful troubleshooting, I am closing it.

If you want to report problems, please create individual GH issues for each problem. We are happy to help with any problems you may have, but please keep the issue focused on a single problem, else we cannot have a clear conversation about the issue.

Thank you.

**Comment by BoyX69** [comment]
Ok, well, thanks for the suggestions but I deleted the Invoke folders.. too much effort, too many PC slowdowns.. Yet having a 2021 i7 10500 PC... I was very disappointed... Greetings...

**Comment by psychedelicious** [comment]
Without a GPU you cannot expect anything but abysmal performance with _any_ local image generation application.

Best to stick with online services, where you essentially pay to rent a GPU from the service provider.
