### ISSUE TITLE
[enhancement]: FLUX copy&paste

### ISSUE THREAD

**Issue by kalle07** [invoke-ai/InvokeAI#6792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

FLUX

maybe copy & paste from webforge-ui
https://github.com/lllyasviel/stable-diffusion-webui-forge

ItS  SOOO EASY ^^

**Comment by ebr** [comment]
https://github.com/invoke-ai/InvokeAI/releases/tag/v4.2.9rc1
