### ISSUE TITLE
Textual Inversion doesn't work on colab

### ISSUE THREAD

**Issue by krummrey** [invoke-ai/InvokeAI#680]
Trying to get textual inversion to work using colab pro: Stable diffusion has no idea what the german foreign secretary looks like. ;)

Started the notebook from the repository (which works great with dream.py)

```
python3 ./main.py --base ./configs/stable-diffusion/v1-finetune.yaml \
>                   --actual_resume ./models/ldm/stable-diffusion-v1/model.ckpt \
>                   -t \
>                   -n AnnalenaBaerbock \
>                   --gpus 0 \
>                   --data_root /content/drive/MyDrive/sd/train/Bundesregierung/AnnalenaBaerbock/images  \
>                   --init_word 'woman'
```

This is the error I get:
```
Unexpected Keys: ['model_ema.decay', 'model_ema.num_updates']
Traceback (most recent call last):
  File "./main.py", line 759, in <module>
    trainer_kwargs['logger'] = instantiate_from_config(logger_cfg)
  File "/content/stable-diffusion/ldm/util.py", line 89, in instantiate_from_config
    return get_obj_from_str(config['target'])(
  File "/content/stable-diffusion/ldm/util.py", line 99, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
AttributeError: module 'pytorch_lightning.loggers' has no attribute 'TestTubeLogger'
```

It would be great to be able to use it on colab, training on my MacBook would take ages if it worked.

**Comment by BassJMagan** [comment]
seems like textual inversion is broke on local too when trying to use a .pt file.

**Comment by lstein** [comment]
My guess is that this is a versioning problem, probably involved pytorch-lighting. What happens if you do a `pip install --upgrade pytorch-lightning`?

I'm tagging a few people who worked on the textual inversion implementation to see if they can offer any assistance: @Oceanswave @nicolai256 @chromaticist @david-ford

**Comment by krummrey** [comment]
This is the version that is installed:
```
Name: pytorch-lightning
Version: 1.7.6
Summary: PyTorch Lightning is the lightweight PyTorch wrapper for ML researchers. Scale your models. Write less boilerplate.
Home-page: https://github.com/Lightning-AI/lightning
Author: Lightning AI et al.
Author-email: pytorch@lightning.ai
License: Apache-2.0
Location: /usr/local/lib/python3.7/dist-packages
Requires: fsspec, numpy, packaging, pyDeprecate, PyYAML, tensorboard, torch, torchmetrics, tqdm, typing-extensions
Required-by: taming-transformers-rom1504
```

**Comment by krummrey** [comment]
For the time being I'm using the [Notebook from Hugginface](https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/sd_textual_inversion_training.ipynb). Importing the .bin files from there works!
