### ISSUE TITLE
[bug]: Can't install now

### ISSUE THREAD

**Issue by DataJuggler** [invoke-ai/InvokeAI#6802]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 3090

### GPU VRAM

23

### Version number

4.2.8

### Browser

Edge

### Python dependencies

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com, https://download.pytorch.org/whl/cu121
ERROR: Ignored the following versions that require a different python version: 2.2.4.5 Requires-Python <3.11,>=3.9; 2.2.4.6 Requires-Python <3.11,>=3.9; 2.2.4.7 Requires-Python <3.11,>=3.9; 2.2.5 Requires-Python <3.11,>=3.9; 2.3.0 Requires-Python <3.11,>=3.9; 2.3.0a0 Requires-Python <3.11,>=3.9; 2.3.0a1 Requires-Python <3.11,>=3.9; 2.3.0a2 Requires-Python <3.11,>=3.9; 2.3.0a3 Requires-Python <3.11,>=3.9; 2.3.0rc3 Requires-Python <3.11,>=3.9; 2.3.0rc4 Requires-Python <3.11,>=3.9; 2.3.0rc5 Requires-Python <3.11,>=3.9; 2.3.0rc6 Requires-Python <3.11,>=3.9; 2.3.0rc7 Requires-Python <3.11,>=3.9; 2.3.1 Requires-Python <3.11,>=3.9; 2.3.1.post1 Requires-Python <3.11,>=3.9; 2.3.1.post2 Requires-Python <3.11,>=3.9; 2.3.1rc4 Requires-Python <3.11,>=3.9; 2.3.2 Requires-Python <3.11,>=3.9; 2.3.2.post1 Requires-Python <3.11,>=3.9; 2.3.3 Requires-Python <3.11,>=3.9; 2.3.3rc1 Requires-Python <3.11,>=3.9; 2.3.4 Requires-Python <3.11,>=3.9; 2.3.4.post1 Requires-Python <3.11,>=3.9; 2.3.4a0 Requires-Python <3.11,>=3.9; 2.3.4rc1 Requires-Python <3.11,>=3.9; 2.3.5 Requires-Python <3.11,>=3.9; 2.3.5.post1 Requires-Python <3.11,>=3.9; 2.3.5.post2 Requires-Python <3.11,>=3.9; 2.3.5rc1 Requires-Python <3.11,>=3.9; 3.0.0 Requires-Python <3.11,>=3.9; 3.0.1 Requires-Python <3.12,>=3.9; 3.0.1.post1 Requires-Python <3.12,>=3.9; 3.0.1.post2 Requires-Python <3.12,>=3.9; 3.0.1.post3 Requires-Python <3.12,>=3.9; 3.0.1rc1 Requires-Python <3.11,>=3.9; 3.0.1rc2 Requires-Python <3.12,>=3.9; 3.0.2 Requires-Python <3.12,>=3.9; 3.0.2.post1 Requires-Python <3.12,>=3.9; 3.0.2a1 Requires-Python <3.12,>=3.9; 3.0.2rc1 Requires-Python <3.12,>=3.9; 3.1.0 Requires-Python <3.12,>=3.9; 3.1.1 Requires-Python <3.12,>=3.9; 3.1.1rc1 Requires-Python <3.12,>=3.9; 3.2.0 Requires-Python <3.12,>=3.9; 3.3.0 Requires-Python <3.12,>=3.9; 3.3.0.post1 Requires-Python <3.12,>=3.9; 3.3.0.post2 Requires-Python <3.12,>=3.9; 3.3.0.post3 Requires-Python <3.12,>=3.9; 3.4.0 Requires-Python <3.12,>=3.10; 3.4.0.post1 Requires-Python <3.12,>=3.10; 3.4.0.post2 Requires-Python <3.12,>=3.10; 3.4.0rc2 Requires-Python <3.12,>=3.10; 3.4.0rc3 Requires-Python <3.12,>=3.10; 3.4.0rc4 Requires-Python <3.12,>=3.10; 3.5.0 Requires-Python <3.12,>=3.10; 3.5.0rc1 Requires-Python <3.12,>=3.10; 3.5.0rc2 Requires-Python <3.12,>=3.10; 3.5.0rc3 Requires-Python <3.12,>=3.10; 3.5.1 Requires-Python <3.12,>=3.10; 3.6.0 Requires-Python <3.12,>=3.10; 3.6.0rc1 Requires-Python <3.12,>=3.10; 3.6.0rc2 Requires-Python <3.12,>=3.10; 3.6.0rc3 Requires-Python <3.12,>=3.10; 3.6.0rc4 Requires-Python <3.12,>=3.10; 3.6.0rc5 Requires-Python <3.12,>=3.10; 3.6.0rc6 Requires-Python <3.12,>=3.10; 3.6.1 Requires-Python <3.12,>=3.10; 3.6.2 Requires-Python <3.12,>=3.10; 3.6.3 Requires-Python <3.12,>=3.10; 3.6.3rc1 Requires-Python <3.12,>=3.10; 3.7.0 Requires-Python <3.12,>=3.10; 4.0.0 Requires-Python <3.12,>=3.10; 4.0.0rc1 Requires-Python <3.12,>=3.10; 4.0.0rc2 Requires-Python <3.12,>=3.10; 4.0.0rc4 Requires-Python <3.12,>=3.10; 4.0.0rc5 Requires-Python <3.12,>=3.10; 4.0.0rc6 Requires-Python <3.12,>=3.10; 4.0.1 Requires-Python <3.12,>=3.10; 4.0.2 Requires-Python <3.12,>=3.10; 4.0.3 Requires-Python <3.12,>=3.10; 4.0.4 Requires-Python <3.12,>=3.10; 4.1.0 Requires-Python <3.12,>=3.10; 4.2.0 Requires-Python <3.12,>=3.10; 4.2.0a1 Requires-Python <3.12,>=3.10; 4.2.0a2 Requires-Python <3.12,>=3.10; 4.2.0a3 Requires-Python <3.12,>=3.10; 4.2.0a4 Requires-Python <3.12,>=3.10; 4.2.0b1 Requires-Python <3.12,>=3.10; 4.2.0b2 Requires-Python <3.12,>=3.10; 4.2.1 Requires-Python <3.12,>=3.10; 4.2.2 Requires-Python <3.12,>=3.10; 4.2.2.post1 Requires-Python <3.12,>=3.10; 4.2.3 Requires-Python <3.12,>=3.10; 4.2.4 Requires-Python <3.12,>=3.10; 4.2.5 Requires-Python <3.12,>=3.10; 4.2.6 Requires-Python <3.12,>=3.10; 4.2.6.post1 Requires-Python <3.12,>=3.10; 4.2.6a1 Requires-Python <3.12,>=3.10; 4.2.6rc1 Requires-Python <3.12,>=3.10; 4.2.7 Requires-Python <3.12,>=3.10; 4.2.7.post1 Requires-Python <3.12,>=3.10; 4.2.7rc1 Requires-Python <3.12,>=3.10; 4.2.8 Requires-Python <3.12,>=3.10; 4.2.8rc1 Requires-Python <3.12,>=3.10; 4.2.8rc2 Requires-Python <3.12,>=3.10; 4.2.9.dev10 Requires-Python <3.12,>=3.10; 4.2.9.dev20240823 Requires-Python <3.12,>=3.10; 4.2.9.dev20240824 Requires-Python <3.12,>=3.10; 4.2.9.dev3 Requires-Python <3.12,>=3.10; 4.2.9.dev4 Requires-Python <3.12,>=3.10; 4.2.9.dev5 Requires-Python <3.12,>=3.10; 4.2.9.dev6 Requires-Python <3.12,>=3.10; 4.2.9.dev7 Requires-Python <3.12,>=3.10; 4.2.9.dev8 Requires-Python <3.12,>=3.10; 4.2.9.dev9 Requires-Python <3.12,>=3.10; 4.2.9rc1 Requires-Python <3.12,>=3.10
ERROR: Could not find a version that satisfies the requirement invokeai==4.2.7 (from versions: none)
ERROR: No matching distribution found for invokeai==4.2.7
Error: Unexpected exit code: 1
Command line: | 'E:\InvokeAI\.venv\Scripts\pip.exe' install --require-virtualenv --force-reinstall --use-pep517 'invokeai[xformers,onnx-cuda]==4.2.7' --extra-index-url https://download.pytorch.org/whl/cu121
Could not install InvokeAI. Please try downloading the latest version of the installer and install again.
Press any key to continue . . .

### What happened

This used to work. I upgraded Python to 3.12.5, and now I get all the following errors.

### What you expected to happen

The app to install. 

### How to reproduce the problem

Install version 4.2.8. I also tried to install 4.2.7, which used to work.

**Comment by leder11011** [comment]
Python 3.12 is unsupported by invokeai ATM. I tried to downgrade to 3.11
with pyenv without success.

Data Juggler ***@***.***> schrieb am Mo., 2. Sept. 2024,
09:37:

**Comment by DataJuggler** [comment]
I discovered Python 3.11 is required. I uninstalled 3.12.5 and put 3.11.9 on and it worked.

Sorry to bother you.
