### ISSUE TITLE
[bug]:  NOT INSTALL

### ISSUE THREAD

**Issue by HCOSCARELLI** [invoke-ai/InvokeAI#6807]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

3060 

### GPU VRAM

12 GB

### Version number

4.2.8

### Browser

EDGE 

### What happened

[
![Captura de tela 2024-09-03 161235](https://github.com/user-attachments/assets/1cbb5b58-88af-44c5-83ac-505afb999d0f)
](url)

### What you expected to happen

I DONT KNOW

**Comment by psychedelicious** [comment]
You don't have the right version of python installed. You need 3.10 or 3.11. There are some instructions here on how to install python: https://invoke-ai.github.io/InvokeAI/installation/INSTALL_REQUIREMENTS/#python
