### ISSUE TITLE
[enhancement]: Gallery - Double click the thumbnail to open the image in new tab

### ISSUE THREAD

**Issue by sonny4723** [invoke-ai/InvokeAI#6809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

An alternative way to open the image in new tab from the gallery panel. I prefer double click the thumbnail of the image. Is it possible or make sense?

**Comment by psychedelicious** [comment]
Double-clicking the image opens the image in the viewer. I don't think we will change that. The other modifier keys also do something to the images, so we cannot do ctrl+click -> open in new tab.

However, middle-mouse click is free, and it is fairly conventional for that to mean "open this thing in a new tab", so I'm adding that functionality.
