### ISSUE TITLE
[bug]: TypeError: a.map is not a function

### ISSUE THREAD

**Issue by Chovanec** [invoke-ai/InvokeAI#6817]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

3060

### GPU VRAM

12

### Version number

4.2.8

### Browser

chrome

### What happened

after open http://127.0.0.1:9090/ i get this error:

common.somethingWentWrong
TypeError: a.map is not a function

### What you expected to happen

run

**Comment by psychedelicious** [comment]
- Did clicking the reset button fix it?
- Can you reproduce the issue?
