### ISSUE TITLE
[bug]: TypeError: a.map is not a function

### ISSUE THREAD

**Issue by Crowswave** [invoke-ai/InvokeAI#6828]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 3070 (laptop)

### GPU VRAM

8 GB GDDR6

### Version number

v4.2.9

### Browser

Opera GX

### What happened

Program won't start, it says: "TypeError: a.map is not a function"

### What you expected to happen

I expected the program to start after reinstalling

### How to reproduce the problem

no idea

**Comment by psychedelicious** [comment]
- Did clicking the reset button fix?
- Can you reproduce the issue? If so, how?

**Comment by Crowswave** [comment]
I will try and update you

Den lör 14 sep. 2024 11:29psychedelicious ***@***.***> skrev:
