### ISSUE TITLE
[bug]: the shortcut keys '[' and ']' have dual functions

### ISSUE THREAD

**Issue by MOzhi327** [invoke-ai/InvokeAI#6829]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX3060

### GPU VRAM

12GB

### Version number

5.0.0.a1

### Browser

Vivaldi	6.9.3447.41 (Stable channel)

### What happened

The shortcut keys '[' and ']' are shortcut keys for adjusting the brush size. Ctrl + [ / ] is a shortcut key for switching the selected layer. However, when I press [ / ] alone to adjust the brush, the selected layer will be switched synchronously.
I ruled out keyboard problems and restarted the UI, browser, and InvokeAI, but none of these could solve the problem. Then after testing, I found another situation. When I press shift, it will switch between the following two states:
1. The [ / ] key is ineffective and cannot adjust the brush size, but Ctrl + [ / ] can switch the selected layer.
2. When pressing [ / ] alone, it will switch the selected layer while adjusting the brush.

**Comment by MOzhi327** [comment]
I test it on pad and still had the same problem. However, the situation regarding shift only occurred on the computer for a period of time and did not occur on either the computer or the tablet later.

**Comment by psychedelicious** [comment]
What language keyboard do you use?

**Comment by MOzhi327** [comment]
> What language keyboard do you use?

@psychedelicious Chinese and English keyboards both have this problem.

**Comment by MOzhi327** [comment]
@psychedelicious 

https://github.com/user-attachments/assets/abec18c9-486c-4a8a-836a-a93fc3b51826
I took a video to see if it helped,
