### ISSUE TITLE
[bug]: Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

### ISSUE THREAD

**Issue by devonghopkins** [invoke-ai/InvokeAI#6835]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

macOS

### GPU vendor

None (CPU)

### Version number

5.0.0.a2

### Browser

Chrome

### What happened

(running main branch on tailscale)

I had a Control Layer loaded with an image in it, 1024x1024. I pressed Filter, then selected the Image-to-Image Model as Filter Type and it errors out every time.

### What you expected to happen

No error. Expect the visual to show on the canvas

**Comment by psychedelicious** [comment]
Until the linked fix is merged, you can work around the error by installing an image-to-image model in the model manager before clicking the filter.
