### ISSUE TITLE
[bug]: PytorchStreamReader can't find file constants.pkl when trying to load an aDetailer

### ISSUE THREAD

**Issue by moda20** [invoke-ai/InvokeAI#6836]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

4060

### GPU VRAM

8GB

### Version number

4.2.7

### Browser

Chrome 

### What happened

I tried to load an aDetailer (https://huggingface.co/Bingsu/adetailer/blob/main/face_yolov8s.pt) but wasn't able due to missing package called `ultralytics`, i installed that package but then got an error : ` PytorchStreamReader can't locate file constants.pkl` 

i opened the aDetailer as a zip and didn't fine the constant.pkl file indeed. 

### What you expected to happen

aDetailer loaded successfully and able to use for better rendering of faces

**Comment by hipsterusername** [comment]
What you've attempted to upload is not a feature or model that is supported in isolation.

You can use Invoke's workflows if you're looking for automated/masked regeneration capabilities
