### ISSUE TITLE
[bug]: Regarding the compatibility issue of pad with stylus.

### ISSUE THREAD

**Issue by MOzhi327** [invoke-ai/InvokeAI#6839]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX3060

### GPU VRAM

12GB

### Version number

5.0.0.a3

### Browser

Vivaldi	6.9.3447.41 

### What happened

On version 4, I can use a stylus to draw patterns on my pad. In this version 5 now, when I use a stylus on my pad, I can only draw one dot at a time. I cannot draw a straight line. When I try to draw a straight line, it will drag the entire web page to scroll up and down. However, in View mode, the canvas can be dragged and moved separately.

### What you expected to happen

When used on a pad, a stylus can be used for drawing if the pad usage scenario is in the plan.

**Comment by MOzhi327** [comment]
By the way, on the pad, even with fingers, one cannot draw a straight line. It will also drag the webpage to scroll up and down.

**Comment by psychedelicious** [comment]
This will be something we tackle for a v5.1 update. Handling tablet input correctly needs a separate system from the mouse. We'll also add pressure sensitivity at the same time.

**Comment by zavio76** [comment]
This could be an incredible setup for industrial designers, especially when working on an iPad. I can already envision it being able to directly compete with Vizcom and similar services.
