### ISSUE TITLE
[bug]: Error: Wrong assertion encountered: "useEntityAdapter must be used within a CanvasRasterLayerAdapterGate"

### ISSUE THREAD

**Issue by magnusviri** [invoke-ai/InvokeAI#6852]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

macOS

### GPU vendor

Apple Silicon (MPS)

### GPU model

M1 MacBook Air 2020

### GPU VRAM

16GB

### Version number

5.0.0at

### Browser

Safari 17.6

### Python dependencies

{
  "accelerate": "0.30.1",
  "compel": "2.0.2",
  "cuda": null,
  "diffusers": "0.27.2",
  "numpy": "1.26.4",
  "opencv": "4.9.0.80",
  "onnx": "1.15.0",
  "pillow": "10.4.0",
  "python": "3.11.6",
  "torch": "2.2.2",
  "torchvision": "0.17.2",
  "transformers": "4.41.1",
  "xformers": null
}

### What happened

I was trying to add an image to an IP Adapter from the Image Viewer. I clicked "Close Viewer" and it died. Unfortunately, I hadn't saved my progress and I lost a lot of (useless) work. :(

### What you expected to happen

Not crash

### How to reproduce the problem

I tried to reproduce it but couldn't.

### Discord username

magnusviri

**Comment by psychedelicious** [comment]
This will be fixed in a6. Sorry you lost some work!

For future reference, when you get a big error like that, it's worth refreshing - I _think_ it would have recovered in this case.

**Comment by magnusviri** [comment]
I do this for fun so it wasn't a big deal for me. It is an alpha release. I said that more to indicate someone else might hit it and get upset. I love the changes!
