### ISSUE TITLE
[enhancement]: 5.0.0a5 viewer interface confusion

### ISSUE THREAD

**Issue by magnusviri** [invoke-ai/InvokeAI#6857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

magnusviri

### What should this feature add?

The controls for switching between the gallery image viewer, the currently rendering image, and the canvas are very confusing and spread out (the hour glass, 2 versions of "Close Viewer").

<img width="962" alt="Screenshot 2024-09-14 at 11 37 53" src="https://github.com/user-attachments/assets/6b034b8b-f0a4-49e4-b85e-1a3f9b69c2a8">

It would be great if there was a pop-up or something to switch between them. macOS Finder example:

<img width="142" alt="Screenshot 2024-09-14 at 11 40 31" src="https://github.com/user-attachments/assets/7b9feeb3-b0c1-4b46-b70f-d5eada0324e2">

**Comment by psychedelicious** [comment]
This UI is slightly changed now, but we don't have any _current_ plans to change it more. Once the dust settles from the v5 release and people have had a chance to learn the new UI, we will see if any further changes are needed.

FWIW, there are two separate binary choices:
- Where to send your images (gallery or canvas) - this is the switch next to the Invoke button.
- What you are looking at (viewer or canvas) - this is the button you've pointed out.

The layout we have now is the result of a lot of testing and feedback.
