### ISSUE TITLE
[enhancement]: Windows Ink support

### ISSUE THREAD

**Issue by park-dev123** [invoke-ai/InvokeAI#6870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I'm using a Surface pen and it seems that it doesn't work correctly on the canvas. If I tap the screen with the pen it draws, but when I try to draw a line it just scrolls the page. I've tried on Photopea, just to see if there was an issue with my device, but it works correctly there.
I've also tried multiple browsers (Edge, Firefox and Arc) but the issue is still there. I've seen other people being able to use drawing tablets so I guess it should be related to the Windows Ink API.

**Comment by hipsterusername** [comment]
Thanks for the context! We're holding off on full tablet landscape evaluation & support for a follow-on iteration

**Comment by Z16SE** [comment]
Is there a known workaround for the browser problem with canvas?
If I have time, I will test it under Ubuntu and Android.

**Comment by hipsterusername** [comment]
The issue with a number of tablets and the canvas seems to be having Windows Ink on. Please feel free to test other OS - it’ll help us understand the landscape better!
