### ISSUE TITLE
[bug]: [5.0.0.a8] Hotkey for navigate-left is mapped to arrow-key up

### ISSUE THREAD

**Issue by adoermenen** [invoke-ai/InvokeAI#6883]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### Version number

5.0.0.a8

### Browser

Edge 128.0.2739.67

### What happened

Hotkey for navigating left in the gallery ("Navigate Left") is mapped to arrow-key up. Causes weird movements since arrow-key up is also mapped to "Navigate Up". Don't think I experienced this on 5.0.0.a7

### What you expected to happen

Expected "Navigate Left" to be mapped to arrow-key left, or at least a separate key from "Navigate Up".

### How to reproduce the problem

Open a gallery with multiple images and press arrow-key left, result will be that nothing happens. 
Open a gallery with multiple rows of images and press arrow-key up, result will be that the selection moves diagonally up and to the left

**Comment by psychedelicious** [comment]
This is fixed in `main`
