### ISSUE TITLE
[enhancement]: Option to disable bbox changing size when changing model

### ISSUE THREAD

**Issue by mickr777** [invoke-ai/InvokeAI#6911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Option to disable bbox changing size when changing model (I know this is related to the model optimized size, but maybe the user should be able to disable it for canvas work)
![Animation](https://github.com/user-attachments/assets/e92fa065-6714-4bc1-a080-2e70b26a8203)

**Comment by FloeHetling** [comment]
Currently working on this, nearing PR.

**Comment by FloeHetling** [comment]
Fixed in https://github.com/invoke-ai/InvokeAI/commit/c4737379d6e74746cf50f421f7f835e3a1921a86

**Comment by mickr777** [comment]
> Fixed in [c473737](https://github.com/invoke-ai/InvokeAI/commit/c4737379d6e74746cf50f421f7f835e3a1921a86)

Yes, just updated main and was testing and it is
