### ISSUE TITLE
[bug]: Model Manager can not import LoRa made by FluxGym

### ISSUE THREAD

**Issue by Barafu** [invoke-ai/InvokeAI#6916]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### Version number

5.0.0

### Browser

Brave

### What happened

I crerated a LoRa using FlexGym, carefully leaving all settings on default, except for epochs. When importing this LoRa with model manager, it produces the error.
```
[2024-09-23 12:28:05,823]::[ModelInstallService]::ERROR --> Model install error: D:/AI/webui_forge/webui/models/Lora/blue-ball.safetensors
InvalidModelConfigException: Unknown LoRA type: D:\AI\webui_forge\webui\models\Lora\blue-ball.safetensors
```

### What you expected to happen

Lora be imported.

### How to reproduce the problem

LoRa here: https://zippyshare.day/0kDGvKITOanFlBt/file
Download and try to import. 

### Additional context

This LoRa works successfully in Forge. Has to set mode manually to "bnb-nf4 (fp16 LoRa)". And in Comfy. 

### Discord username

barafu_albino

**Comment by Barafu** [comment]
These now work. I will reopen if I find particular settings that cause LoRa to not work again.

**Comment by arturgromenkov** [comment]
So, It does not still work in InvokeUI? I've just encountered this error again.

**Comment by Barafu** [comment]
@arturgromenkov It just worked when I closed the issue. Didn't do anything. Default settings on FluxGym.

**Comment by arturgromenkov** [comment]
@Barafu  Did you retrain lora?
