### ISSUE TITLE
[enhancement]: Install In-Place - Model Manager - Retain last state

### ISSUE THREAD

**Issue by Ayelwen** [invoke-ai/InvokeAI#6947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I would like for the checkbox in the Model Manager, when installing from local path or scan folder, to remember whether you have unchecked or checked it rather than resetting.

### Alternatives

An alternative would be to allow some button somewhere, to click for an In-Place model to get converted/copied into an Invoke folder, essentially undoing an In-Place install if you accidentally forgot to uncheck the box.

**Comment by psychedelicious** [comment]
Implemented in #7167
