### ISSUE TITLE
TextToImage Generation Failed

### ISSUE THREAD

**Issue by lstein** [invoke-ai/InvokeAI#696]
### Discussed in https://github.com/lstein/stable-diffusion/discussions/584

<div type='discussions-op-text'>

<sup>Originally posted by **wzgdesigntech** September 14, 2022</sup>
I want to implement the function of textToImage through dream.py, but I get this result；
![企业微信截图_20220915095404](https://user-images.githubusercontent.com/112833981/190295065-7d4abb84-abe1-4aa0-9d5d-2b2552c5ed2d.png)
My GPU：NVIDIA GeForce GTX 1650 .Is it because this GPU is not supported?Can someone help with the answer?</div>

(edit by lstein: This was originally posted in Discussion, so I moved it here)

**Comment by jspraul** [comment]
Dupe of [Green image on 1660 Ti even with full precision](https://github.com/invoke-ai/InvokeAI/issues/526)

**Comment by jspraul** [comment]
Poke 👉 @lstein recommending this be closed.

Keep up the good work!
