### ISSUE TITLE
Heads up - big architecture change coming to development branch

### ISSUE THREAD

**Issue by lstein** [invoke-ai/InvokeAI#698]
Hi Developers,

This is a heads up that sometime in the next 48 hours I plan to merge in PR https://github.com/lstein/stable-diffusion/pull/685 . This is work done by @Kyle0654 which modularizes the system and uses dependency-injector (https://python-dependency-injector.ets-labs.org/) to provide a flexible framework for scheduling tasks and managing their dependencies.

I'm afraid this may disrupt unmerged PRs that touch the dream.py or generate.py files. I will do my best to rebase affected PRs, but in some cases they may need to be closed and reworked. It's going to be a bit painful, but the end result will be a system that is much easier to extend. You may also wish to wait until the dust settles before making any more PRs.

I will update this message when the ETA is firmer.

**Comment by lstein** [comment]
So it looks like I may wait until the weekend to do the merge. I'm leaving for a conference in Barcelona on Wednesday, and I don't want to make big changes just before I go offline. So a reprieve for the moment!

**Comment by psychedelicious** [comment]
Closing; we are long past this by now.
