### ISSUE TITLE
[enhancement]: Add a button for uploading images into assets as an alternative to drag&drop

### ISSUE THREAD

**Issue by asagi4** [invoke-ai/InvokeAI#6982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

There should be an alternative to dragging and dropping images into invokeai. Currently the only way to do it seems to be rather well hidden.

On my system, drag and drop is completely broken; now, I don't consider that an invokeai bug (it's probably because I have a weird Linux system), but even if it did work, I would prefer to just be able to open a file upload dialog to upload images, because most of the time I don't have a file browser open to drag images from.

### Alternatives

There is a workaround; you can upload images by creating a control layer, uploading an image into it, and then creating a raster layer from it. I don't think it's very good UX though, and without that workaround I think I would be completely unable to use InvokeAI.

### Additional Content

This is somewhat related to #6840

**Comment by psychedelicious** [comment]
This keeps slipping through the cracks- it's definitely something we should add, and it's pretty simple to add.

Hardest part is deciding where should the upload button should be. Any ideas?

**Comment by asagi4** [comment]
I think to me the most obvious place would be in the gallery UI somewhere, but I probably wouldn't hide it behind the assets tab.

If you add an upload button to the row of small icons below the tabs (next to the settings icon), you could also add the same upload button in the layers tab for uploading an image directly into a layer.

**Comment by maryhipp** [comment]
Closed with https://github.com/invoke-ai/InvokeAI/pull/7123
