### ISSUE TITLE
[enhancement]: ControlNet Union models support (Flux, SDXL)

### ISSUE THREAD

**Issue by vrubzov1957** [invoke-ai/InvokeAI#6986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Please add support Union ControlNet models and for SDXL and Flux, like:
- FLUX.1-dev-Controlnet-Union 
- controlnet-union-sdxl-1.0

Union models combines the functionality of all ControlNet models in one. With it we don’t need to download all ControlNet models -  Union is enough for most tasks that ControlNet can do

**Comment by AllyourBaseBelongToUs** [comment]
works but hella slow :/
