### ISSUE TITLE
[bug]: duplicating regional guidance layers does not provide unique colour

### ISSUE THREAD

**Issue by Kelztergit** [invoke-ai/InvokeAI#6995]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

4070ti

### GPU VRAM

12GB

### Version number

5.0.1

### Browser

firefox 130.0.1

### What happened

I duplicated a Regional Guidance layer, which duplicated it as expected, However it did not assign it a new colour.

### What you expected to happen

I expected it to duplicate it with all the same settings except provide it with a new unique colour.
Currently i am not sure how i am supposed to tell them apart. 

### How to reproduce the problem

by right clicking on a regional guidance layer and clicking duplicate

### Discord username

Keldingull

**Comment by psychedelicious** [comment]
You can change the color (and pattern) with this button:
<img width="415" alt="image" src="https://github.com/user-attachments/assets/03ff80b3-c478-4d62-8d79-f949ef145da2">

**Comment by Kelztergit** [comment]
thanks for the reply, But i reported it more so because i thought it was unintended behavior, Is there ever a reason why you would want to have it not get a unique colour? it doesn't function if it has the same colour in my experience, i assumed it'd create a new regional guidance layer and copy only the settings (reference image, weight, method etc)


Further testing with the mask fill changed after the fact it was duplicated with right click duplicate on an existing regional guidance layer shows that this does not resume functionality, Duplicating the layers this way does therefore not only not save time but it also breaks it.  
![image](https://github.com/user-attachments/assets/c5b38c3b-2da8-4fd8-a138-af22c85752c8)

Creating a new one and setting it up manually is required.
![image](https://github.com/user-attachments/assets/01fc7bf7-5077-4eb4-b907-b3cd94399062)


I originally thought the colour itself was used as a unique identifier of sorts but whatever it does behind the scenes is likely being duplicated as well causing it to not be able to continue when two or more exist simultaneously like that. 

Therefore this has evolved into technically a new bug "Duplicating regional guidance layers prevents image generation"

**Comment by psychedelicious** [comment]
The color is just there to help you - it's not used internally.

I'm not sure I fully understand the issue with generation not working. Can you please clarify what exactly doesn't work, and list the steps I should take to reproduce the issue?

**Comment by Kelztergit** [comment]
how to replicate : duplicate a regional guidance layer that has an ip adapter image, i've tried both for sd-1 and sdxl, it doesn't make a difference for this.

error messages : clicking the invoke button causes absolutely nothing to happen, **zero errors, it is as if it disables it.**

What happens : If a duplicated regional guidance layer **using ip adapter** exists (regional reference image) and is enabled and you press the invoke button, nothing happens, 
You can edit is how you wish, change the image, change the settings, right-click and add a prompt etc, it will not fix it.
You can disable one and regain functionality, 
You can create another manually rather than duplicate and it will work, proving it's not an issue with multiple regional guidance ip-adapter using layers.
but it does not work with duplicated ones. 

How i found out : Trying to find a quick workflow for myself i thought i'd duplicate a regional guidance layer that used an ip-adapter to maintain the settings, thinking i could just swap out the image and paint up a new area, this ended up not working. I assumed incorrectly that the colour was the issue since it was the most obvious thing that remained the same and theorized it was used for id internally and that borked things up, Later tests revealed it doesn't impact prompt only regional guidance layers so it's specific to ones having ip-adapters /regional reference images.  
(i've tested it with text prompts, same colour, and it works even if duplicated) 

Theorized cause : Some kind of unique identifier for the ip-adapters gets duplicated along with the rest when it shouldn't perhaps?

**Comment by psychedelicious** [comment]
Thanks for the detail. Yes, you are exactly correct, the ref image (ip adapter)'s ID was erroneously duplicated. I've just fixed this.

I think the mask color should not be changed when duplicating the layer. Consider this user flow:
- I have a regional guidance layer w/ whichever settings.
- I want to make a variation of it, without losing the original, so I duplicate.
- I generate w/ the variation and decide I want to go back to the original, so I delete the clone.

In this case, I think we want to leave the mask the same.
