### ISSUE TITLE
[bug]: [5.0.2] Recall LoRA causes duplicate LoRA entries

### ISSUE THREAD

**Issue by adoermenen** [invoke-ai/InvokeAI#7004]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 4090

### GPU VRAM

24

### Version number

5.0.2

### Browser

Chrome 129.0.6668.70 

### What happened

Using the image-info view to recall LORA's ("Recall LoRA" button under "Recall parameters" tab) causes duplicate entries instead of just changing the LORA's weight if it already exists in your concepts-list 

### What you expected to happen

If the LORA already exists in the concept-list then I expect its weight to be adjusted to the weight used for generating the "reference"-image 
If the LORA doesn't exist in the concept list then I expect it to be added with the same weight used for generating the "reference"-image

### How to reproduce the problem

1. Remove all concepts 
2. Select an existing image in your gallery and open its info-view
3. Recall one LORA, note that it gets added to your concept-list
4. Recall that same LORA once more, note that a duplicate entry gets added. Can be repeated multiple times 
![image](https://github.com/user-attachments/assets/9fbe6f34-09d8-47d2-bcdc-d88dd4a4b3e0)

**Comment by psychedelicious** [comment]
Thanks, fixed
