### ISSUE TITLE
[enhancement]: Batch Processing for Assets

### ISSUE THREAD

**Issue by BieHDC** [invoke-ai/InvokeAI#7034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I would like the option to batch process images over a certain workflow.
Right now i have to upload the image, drag it on the adapters, hit invoke and then download it, all manually. This is not viable for 100s of assets. There is no option right now to range over assets and apply the same workflow on them. Also no option to bulk import images.

### Alternatives

Due to lack of that feature i made myself a [program](https://github.com/BieHDC/batchoid) that will do exactly that in case this is not something Invoke wants to target.

**Comment by hipsterusername** [comment]
We're looking at this in the coming weeks.

**Comment by maryhipp** [comment]
Bulk upload implemented with https://github.com/invoke-ai/InvokeAI/pull/7123
