### ISSUE TITLE
[bug]: ModuleNotFoundError: No Module Named Requests upon update attempt

### ISSUE THREAD

**Issue by Boosh214** [invoke-ai/InvokeAI#7050]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

Nvidia GeForce RTX 2080 Super with Max-Q

### GPU VRAM

32 

### Version number

4.2.0

### Browser

Brave Version 1.70.123 Chromium: 129.0.6668.89 

### What happened

Attempted to update to the most recent 5.2, followed instructions to do so. Error seems to be preventing the update, but doesnt interfere with the current installation's functionality. Does seem to mention other errors that occur during this, but naming this one based on last line mentioned.
![error1](https://github.com/user-attachments/assets/8a8abb6a-8478-4ec9-8bba-39d38d9c725a)

### What you expected to happen

I expected the update for 5.2 to successfully install, followed by me being able to open it using the same bat file as before.

### How to reproduce the problem

Started up the install bat, went through the standard install procedures, but did not successfully update to 5.2. Tried the install again, led to image provided.

### Additional context

Python is within requested parameters. Tried all other necessary updates accordingly as though it was a new install not including completely removing the previous installation, thinking that may fix the issue, no results. Current installation still works without issue, but update refuses to occur.

Apologies if I've made any errors in all this, I'm still a bit of a noob with this programming.

**Comment by psychedelicious** [comment]
The root problem is actually the first error, which says a file is in use by another process. Did you maybe have Invoke running while attempting to install the latest version? If not, restarting your computer ought to fix that.

Make sure to install using the [latest release's installer](https://github.com/invoke-ai/InvokeAI/releases/tag/v5.0.2) when installing.

**Comment by Boosh214** [comment]
Tried that, did seem to fix THAT issue but turns out I was making several different mistakes, lol. One of them for example was the improper file coordination, but overall, issue resolved.
