### ISSUE TITLE
Announcement: lstein/stable-diffusion is becoming invoke-ai/InvokeAI

### ISSUE THREAD

**Issue by lstein** [invoke-ai/InvokeAI#707]
Hi All,

Given the exponential growth of the activity on this repository, it no longer makes sense for it to be maintained by a single individual. After consultation with the collaborator team, I am happy to announce that the repository is being be relaunched under the name:

* **InvokeAI: A Stable Diffusion Tookit**

This repository is being transferred to a new organization named "invoke-ai". From September 20 forward, the new URL for this repository will be:

<p align="center"><b><a href="https://github.com/invoke-ai/InvokeAI">https://github.com/invoke-ai/InvokeAI</a></b></p>

The old URL will redirect to the new one, but If you have made a local clone of the old https://github.com/lstein/stable-diffusion repository, you are strongly advised to update your .git/config files with the new repository URL in order to avoid confusion.

Thank you for your support!

**Comment by blessedcoolant** [comment]
Let's go!!

**Comment by jroxendal** [comment]
I'm glad to see the longevity of the project is being assured!

**Comment by krummrey** [comment]
Great to see that you are not clinging to your initial creation. Good news to widen the effort!

**Comment by thraxus2000** [comment]
OK, I'm going to ask the worlds most boring and silly question. I update my repository with git pull, what is the git command I need to enter to tell it, "Go get the files from this new place now and remember that place instead"

**Comment by thraxus2000** [comment]
Thanks CapableWeb, I guess I will just leave it alone then provided it keeps updating. I do small coding tasks for local data analysis, so I'm not very familiar with these collaborative tools. I tend to use coding languages as if they were the worlds fanciest graphing calculator ;)

**Comment by psychedelicious** [comment]
This is complete :)
