### ISSUE TITLE
[enhancement]: OFFLINE USAGE

### ISSUE THREAD

**Issue by someaccount1234** [invoke-ai/InvokeAI#7098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Id like the local config files to be used and not re-downloaded every time you switch models or wish to convert to diffusers.

The online-only feature is no good!

**Comment by psychedelicious** [comment]
Hi, this is a known issue with one of our dependencies (`diffusers`). There's an existing issue for this: https://github.com/invoke-ai/InvokeAI/issues/6623
