### ISSUE TITLE
[enhancement]: LESS Releases !!! EVERY DAY !!!

### ISSUE THREAD

**Issue by kalle07** [invoke-ai/InvokeAI#7102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

i mean hello every day a new release ?!?

make that as fixes or whatever
every EVERY one that have Subscribe to your costune "new release" get a notification ...

### Alternatives

new category for you VERY NEW VERSIONS every day

**Comment by psychedelicious** [comment]
You don't need to update the app or subscribe to updates if you don't want them.

**Comment by kalle07** [comment]
that is the lowest level of beeing watching you !

is like spam !
