### ISSUE TITLE
[bug]: Error Message after Launching missing xformers

### ISSUE THREAD

**Issue by Maisman** [invoke-ai/InvokeAI#7112]
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 3060

### GPU VRAM

12 GB

### Version number

v5.2.0rc1

### Browser

Firefox 131.0.2 (64-Bit)

### What happened

After starting InvokeAI I get an error. It says it cannot find an xFormers file. I wanted to try torch sdp as stated in the changelog, so I updated to the latest version. The image generation still works, but it feels slower. I dont have any proof that it is slower unfortunately, but other than that its just the error message. 

![Screenshot 2024-10-12 232154](https://github.com/user-attachments/assets/6e3a5d8e-f54d-407a-b373-d0eba90bdd66)
![grafik](https://github.com/user-attachments/assets/117d7d2d-2888-42ae-aa8c-d09daeeb9a79)

### What you expected to happen

Starting without an error

### How to reproduce the problem

Start the app. 

### Additional context

I updated from the first new release of Invoke AI 5.0 with the new Canvas

### Discord username

maisman

**Comment by ebr** [comment]
If you had xformers installed already, it wouldn't be uninstalled when you upgraded.
With your virtual environment activated, try `pip uninstall xformers`, and then launch invoke again.
Hope this helps!

**Comment by Maisman** [comment]
> If you had xformers installed already, it wouldn't be uninstalled when you upgraded. With your virtual environment activated, try `pip uninstall xformers`, and then launch invoke again. Hope this helps!

Thank you, it worked ❤️

**Comment by ebr** [comment]
Out of curiosity, does `torch-sdp` feel fast for you now?

**Comment by Maisman** [comment]
> Out of curiosity, does `torch-sdp` feel fast for you now?

It's a little faster, but barely noticeable. The reason it was slower was because I was watching a discord stream... so the update was a success :)
