### ISSUE TITLE
[bug]: Flux runs out of memory when using Host 0.0.0.0

### ISSUE THREAD

**Issue by Cavista** [invoke-ai/InvokeAI#7116]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

Nvidia 4060 TI 

### GPU VRAM

16

### Version number

v5.2.0rc1 

### Browser

Version 129.0.6668.100 (Official Build) (64-bit)

### Python dependencies

{
  "accelerate": "0.30.1",
  "compel": "2.0.2",
  "cuda": "12.4",
  "diffusers": "0.27.2",
  "numpy": "1.26.4",
  "opencv": "4.9.0.80",
  "onnx": "1.17.0",
  "pillow": "10.4.0",
  "python": "3.11.0",
  "torch": "2.4.1+cu124",
  "torchvision": "0.19.1+cu124",
  "transformers": "4.41.1",
  "xformers": "0.0.28.post1"
}

### What happened

when setting host 0.0.0.0 on my invoke PC which is the Linux one. I can connect fine and run SD 1.5 or SDXL images. When I try to run Flux quantized model dev or schnell I get an out of memory error. 

The issue will happen on a remote or the hosting pc when host is 0.0.0.0

### What you expected to happen

I expected to be able to invoke an image

### How to reproduce the problem

My Yaml file only has the host 0.0.0.0 line

I would assume if you have this line and default to everything else it will abend.

### Additional context

I only had 16gb ram and it would hang an just crash while loading shards message came up. It would load 50% and timeout. I upgraded my ram to 32 and got an abend message now

Here is a file where i capture the error
[OOM.txt](https://github.com/user-attachments/files/17371888/OOM.txt)

### Discord username

Jordack

**Comment by ebr** [comment]
The host setting has nothing to do with this. As per the `WARNING --> Insufficient GPU memory to load model. Aborting` log, the model won't fit into 16GB. Please make sure you're trying to use the quantized model, and try again.
