### ISSUE TITLE
[enhancement]: Use Arrow keys to "nudge" layer in Canvas

### ISSUE THREAD

**Issue by shanedk** [invoke-ai/InvokeAI#7120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

shanedk

### What should this feature add?

When working with layers in the Canvas, in addition to moving the layer with the mouse or ctrl-mouse, you should be able to nudge the layer 1 pixel in any direction using the arrow keys, like the Move tool offers in Photoshop.

### Alternatives

If there is some sort of issue with the arrow keys, perhaps ctrl-arrow keys would do.

**Comment by psychedelicious** [comment]
Implemented in  #7368
