### ISSUE TITLE
[bug]: `xformers` not uninstalled when using new installer option that excludes xformers

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#7142]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### Version number

v5.20

### Browser

n/a

### What happened

In #7065 (v5.2.0), we added a new install option for 30xx and 40xx series GPUs that excludes `xformers`.

Unfortunately this causes an issue for users who already had `xformers` installed, because the version is incompatible with the version of torch we are using in v5.2.0.

For example, the user may have `xformers==0.0.25post1` installed. It's compatible with `torch==2.2.2`. User attempts to install v5.2.0, which installs `torch==2.4.1`. `pip` cannot resolve the dependency graph with the conflicting `torch` and `xformers` versions.

Options:
- Roll back the new install option that excludes `xformers`.
- Add a step to the install when using the option that excludes `xformers` that uninstalls it.

### What you expected to happen

Smooth updates

### Additional context

There are a number of discord discussions about this issue. Here's one: https://discord.com/channels/1020123559063990373/1149510134058471514/1296574307744354325

**Comment by hipsterusername** [comment]
Don’t think we roll back the option.

Do we have a clean way to uninstall xformers?
