### ISSUE TITLE
Multi-GPU Selection

### ISSUE THREAD

**Issue by thelamedia** [invoke-ai/InvokeAI#715]
It would be AWESOME if we could implement a script launch param that would allow us to define specific, or multiple GPUS to use when running.  For example, if I have 2 cards available, I could run 2 different instances with each utilizing a different card, or could choose for both cards to run in parallel on one instance.  Same would apply for 4x and 8x configs.  Not sure if this is possible, but it would be a killer feature if so!

**Comment by tildebyte** [comment]
Please check open issues first #656 (also, in future use the issue template)
