### ISSUE TITLE
[enhancement]: Ability to send Auto Mask to a inpaint mask layer

### ISSUE THREAD

**Issue by skunkworxdark** [invoke-ai/InvokeAI#7171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

skunkworxdark

### What should this feature add?

Add the ability to send an Auto Mask to an inpaint mask layer instead of masking in the image.

**Comment by hipsterusername** [comment]
Aye - Figuring out what the UX is here, but this will be in release.
