### ISSUE TITLE
[bug]: [v5.3.0rc1] Cannot install invoke: ERROR: No matching distribution found for torch==2.4.1

### ISSUE THREAD

**Issue by grunblatt-git** [invoke-ai/InvokeAI#7176]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

macOS

### GPU vendor

Nvidia (CUDA)

### Version number

5.3.0rc1

### Browser

Chrome

### What happened

The newest release candidate could not be installed - the installer failed with the error:

```
ERROR: Could not find a version that satisfies the requirement torch==2.4.1 (from invokeai) (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2)
ERROR: No matching distribution found for torch==2.4.1
```

Apparently the newest pytorch versions are not bundled for x86 Macs anymore (https://github.com/pytorch/pytorch/issues/114602). 

Is there any way to fallback to older torch versions or getting the installer to work after building & installing 2.4.1 manually?

### What you expected to happen

The newest Installer should be able to install the current invoke versions

**Comment by ebr** [comment]
> ...after building & installing 2.4.1 manually

If you are able to do that, you could install the CPU version of Invoke and then install the custom built `torch` wheel into the same virtual environment. It would be amazing to see that working. I would have low expectations of success though.

**Comment by ebr** [comment]
@grunblatt-git - it just occurred to me that if you're able to use Nvidia container toolkit on  macOS x86, or otherwise give docker access to your GPU, you might be able to run Invoke in a container.

**Comment by grunblatt-git** [comment]
> Unfortunately, you won't be able to use older Torch with modern image generation pipelines.

@ebr i was actually surprised by this statement, since I can run Comfy and Automatic1111 without issues and up to the latest stable release of invoke, i was able to install invoke without any issues as well. I assumed that this issue only appeared due to a version bump in the current release candidate, or the installer upgrade.

Could you double check if it is possible to run invoke on torch 2.2.2 as it seems to have been up to this version? It would be really great if we can keep updating invoke on MPS :/

**Comment by ebr** [comment]
I thought there was a mention of torch v1.11.x when I first replied - that's what I meant by "older" versions. Must have misread - sorry!

So just to make sure I understand correctly - you were able to use Invoke on an Intel mac with an Nvidia GPU up to and including v5.2.0?
That's pretty cool actually.
Sorry to hear that the new version breaks for you.

We had to bump Torch to 2.4.1 when we released Flux support. If you aren't using Flux, I wonder if you could `pip uninstall torch torchvision` and install the older version (torch 2.2.2 and torchvision 0.18, if i'm not mistaken) with `pip` manually, and see if 5.3.x starts working?

To be sure, this is probably not going to be supportable long-term, even if you do manage to find a workable configuration or build the appropriate version of torch yourself. 

<details>
<summary> Some ideas </summary>

(upon further research I don't think this is possible. Leaving here anyway in case you want to explore further)

I'd still recommend trying the Docker route, as long as you can pass-through the GPU to the hypervisor. Another option might be to run the Invoke backend in a Linux virtual machine (again, as long as GPU can be passed through to it), expose port 9090 from the VM to the host, and connect to it from the host for better front-end performance.

</details>

No easy solutions, unfortunately - we do need Torch 2.4 and higher. But if you do find a combo of dependencies that works by manually installing them with `pip` or building from source, we could consider making that an `[extra]` set for this specific use case, and/or documenting the approach in the official docs.

**Comment by grunblatt-git** [comment]
Your change in 5.4.0 seems to fix this for now, since i can keep using the same (old) torch installation as in previous versions! 
I could successfully install 5.4.0 and generation runs without issues so far.

Thank you! :)

> Pin torch to <2.5.0 to prevent unnecessary downloads

**Comment by ebr** [comment]
Oh cool, so actually maybe the problem was not with torch 2.4.1 itself, but some co-dependency that was preventing resolution of a valid combination of packages. We unpinned some other dependencies and looks like that had a beneficial side effect on mac os x86. Great - very happy it worked for you! (Tempted to bust out my old Intel Mac to give this a try 😄)
