### ISSUE TITLE
[bug]: GIT installer.sh.in and python 3.12

### ISSUE THREAD

**Issue by leder11011** [invoke-ai/InvokeAI#7194]
### Is there an existing issue for this problem?

https://github.com/invoke-ai/InvokeAI/pull/6539

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 4090

### GPU VRAM

24GB

### Version number

c1008146525d0a8fb1f49a5e07c9c808cae14910

### Browser

chrome, FF, vivaldi

### What happened

Hello all,

thank you for InvokeAI!

The readme states that python version should be >= 3.10

But python 3.12 gives an error with onnx-cuda, xformers:
```
ERROR: Could not find a version that satisfies the requirement invokeai[onnx-cuda,xformers] (from versions: none)
ERROR: No matching distribution found for invokeai[onnx-cuda,xformers]
Error: Unexpected exit code: 1
Command line: | /home/leder/invokeai/.venv/bin/pip install --require-virtualenv --force-reinstall --use-pep517 'invokeai[xformers,onnx-cuda]'
Could not install InvokeAI. Please try downloading the latest version of the installer and install again.

```

### What you expected to happen

I expect invokeai to install properly

### How to reproduce the problem

```
./installer.sh.in
latest stable version
NVidia support
```

### Additional context

I read about the installer switch `--skip-xformers`, but it is unknown to the installer!

### Discord username

leder11011

**Comment by ebr** [comment]
Don't run that script directly from the repo. 
Download installer from the latest release, unzip, and run.
Also, we don't support python 3.12 yet. (Soon). You need 3.11 for now. `pyenv` is a good way of getting that sorted.

**Comment by leder11011** [comment]
Thanks for the heads up!
pyenv is mixing 3.12 and 3.11 up for me...
Please take care!

**Comment by ebr** [comment]
I usually just do `pyenv shell 3.11` before running anything that requires 3.11. works quite well on Ubuntu 24.04.
We aim to support 3.12 as soon as all the dependencies catch up and we've had a chance to test it.
Going to close this issue for now. Take care as well.
