### ISSUE TITLE
[bug]: Visit the Model Manager to install the required models Tile ControlNet model for the chosen main model architecture

### ISSUE THREAD

**Issue by jvachez** [invoke-ai/InvokeAI#7239]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

4090 Mobile

### GPU VRAM

16GB

### Version number

5.3.0

### Browser

Edge

### What happened

In Upscale Menu I have the message "Visit the Model Manager to install the required models Tile ControlNet model for the chosen main model architecture"

FLUX.1-dev-Controlnet-Union is installed but I still have the message

### What you expected to happen

Not having this message

### How to reproduce the problem

Use Flux Dev Quantized and go to upscale menu

**Comment by arraylabs** [comment]
Seeing the same issue.

**Comment by LazyLama** [comment]
same
