### ISSUE TITLE
[bug]: Workflow load fron file not working 

### ISSUE THREAD

**Issue by VeyDlin** [invoke-ai/InvokeAI#7240]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 2080 TI

### GPU VRAM

11GB

### Version number

5.3.0

### Browser

firefox developer edition v126.0b9

### What happened

Workflow load fron file not working 

### What you expected to happen

Workflow loaded

**Comment by psychedelicious** [comment]
Please provide more information about the problem, it's not clear what the problem is.

**Comment by quaranji** [comment]
![22](https://github.com/user-attachments/assets/2d72b8ad-49a6-4180-8433-56e767ca94d0) same, on the tab workflow when trying to add workflow from file nothing happens

**Comment by VeyDlin** [comment]
> Please provide more information about the problem, it's not clear what the problem is.

Go to the workflow, there will be a menu on the top right - try clicking "Load from file" and select some json workflow

Nothing will happen.
