### ISSUE TITLE
[bug]: ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by youxiandeduguo** [invoke-ai/InvokeAI#7249]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### Version number

5.3.1

### Browser

Microsoft Edge

### What happened

I want to download an editable invoice version that uses CPU, and then I will follow the instructions in the document，I first created a virtual environment using Anaconda，then
`git clone https://github.com/invoke-ai/InvokeAI.git `
`cd ./InvokeAI`
`pip install -e ".[dev,test,xformers]" --use-pep517 --extra-index-url https://download.pytorch.org/whl/cpu` 

An error occurred during the process
![image](https://github.com/user-attachments/assets/8a417c5b-90b6-4d6f-bb15-793eaf08b201)

Afterwards, I tried to manually execute 
`pip install torch`

But it has no effect

### What you expected to happen

I hope it can avoid reporting this error

### How to reproduce the problem

`git clone https://github.com/invoke-ai/InvokeAI.git `
`cd ./InvokeAI`
`pip install -e ".[dev,test,xformers]" --use-pep517 --extra-index-url https://download.pytorch.org/whl/cpu`

**Comment by thiagojramos** [comment]
try:

`pip install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cu124`
