### ISSUE TITLE
ImportError: cannot import name 'Restoration'

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#726]
**Describe your environment**
- Branch: development
- Commit: b93f04ee38519c8a437b12e3c5989c4d11901dea (post Restoration refactor)

It looks like the Restoration class was moved from `ldm.restoration` (`restoration.py`) to `ldm.dream.restoration.base` (`base.py`) in cd69d258aa6f17a4f8450a683882cb28beb04bcc

But in `dream.py` the import is `from ldm.dream.restoration import Restoration`

This needs to be `from ldm.dream.restoration.base import Restoration` - works like that. Or maybe there is a better file structure to choose. I'll defer to another contributor on which way to fix it.

**Comment by lstein** [comment]
This is probably my python ignorance showing, but I tried to turn ldm.dream.restoration into a package by creating this structure:
~~~
base ldm/dream

restoration/
├── base.py
├── codeformer
│   └── weights
│       ├── codeformer.pth
│       └── README
├── codeformer_arch.py
├── codeformer.py
├── gfpgan.py
├── __init__.py
├── realesrgan.py
└── vqgan_arch.py
~~~

The Restoration class lives in ldm/dream/restoration/base.py . The same restoration folder contains an __init__.py file with this code:

~~~~
from .base import Restoration
~~~~

The python package docs say that this is sufficient to load ldm.dream.restoration.base when importing from ldm.dream.restoration. Indeed, from either the script or the REPL, I can do this and it works:

~~~~
from ldm.dream.restoration import Restoration
~~~~

I've no objection to doing an import from ldm.dream.restoration.base, but I don't understand why it works for me and not for @psychedelicious. Could it be the python version? I am using 3.9.13, as specified in `environment.yaml`

**Comment by psychedelicious** [comment]
@lstein I do not have an `__init__.py` in my restoration folder (I have `gh pr checkout 725`'d, on commit [72dd5b1](https://github.com/invoke-ai/InvokeAI/pull/725/commits/72dd5b18ee070e2bfedd209615973785dde41e7d)):
```shell
(base) ~/D/C/s/l/d/restoration ❯❯❯ ls -la                 development ⬆ ✭ ✚ ✱ ◼
total 88
drwxr-xr-x  10 spencer  staff    320 21 Sep 21:57 .
drwxr-xr-x  13 spencer  staff    416 21 Sep 21:57 ..
drwxr-xr-x   6 spencer  staff    192 21 Sep 22:02 __pycache__
-rw-r--r--   1 spencer  staff   1231 21 Sep 21:57 base.py
drwxr-xr-x   3 spencer  staff     96 21 Sep 16:52 codeformer
-rw-r--r--   1 spencer  staff   3737 21 Sep 16:52 codeformer.py
-rw-r--r--   1 spencer  staff  10965 21 Sep 16:52 codeformer_arch.py
-rw-r--r--   1 spencer  staff   2522 21 Sep 16:52 gfpgan.py
-rw-r--r--   1 spencer  staff   3218 21 Sep 16:52 realesrgan.py
-rw-r--r--   1 spencer  staff  15482 21 Sep 16:52 vqgan_arch.py
```

Maybe just need that file added... tho in #725 @blessedcoolant has changed the import to `ldm.dream.restoration.base`

**Comment by blessedcoolant** [comment]
I didn't see an init either. I'll add it up.
