### ISSUE TITLE
[enhancement]: PBR Brush Tool

### ISSUE THREAD

**Issue by johnwickstyle** [invoke-ai/InvokeAI#7266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

This is my simple idea for invoke ai to give more freedome using PBR Brush to create easy things using PBR Brush because some time it is very hard to draw something witch is very easy in other app using PBR but with this power many creative person can do thair job easily using this tool and it is very usefull in my opinioun . what do you thing about this idea ? if you apply my idea please add my name "Hemant Chauhan" in credit for giving this best solution for everyone. sorry for my bad english but i know you understand my concept and use it for better creative people. Thank you i love invoke ai and i miss this fuction in invoke ai.
I have Attached my idea hope you will add this feature in next update .

![PBR](https://github.com/user-attachments/assets/04aa54e5-9a69-4f3d-866a-a433dd287719)

**Comment by psychedelicious** [comment]
Invoke is a 2D Canvas. We don't plan to attempt to implement PBR brushes - or any brushes, at least for the foreseeable future.

**Comment by johnwickstyle** [comment]
Thnal you for your reply . i do some lab research and coding to impliment this feature in other way . if i sucess i'll pull the request to add it if you like.

**Comment by johnwickstyle** [comment]
> Invoke is a 2D Canvas. We don't plan to attempt to implement PBR brushes - or any brushes, at least for the foreseeable future.

Thank you for your reply . i do some lab research and coding to impliment this feature in other way . if i sucess i'll pull the request to add it if you like.
