### ISSUE TITLE
[bug]:  FLUX model install - Model install error: InvokeAI/clip-vit-large-patch14-text-encoder::bfloat16

### ISSUE THREAD

**Issue by OreoMev** [invoke-ai/InvokeAI#7267]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX

### GPU VRAM

24

### Version number

v5.4.0

### Browser

Chrome

### What happened

When I tried installing FLUX Schnell (Quantized) model via starter models I get this error, which makes it impossible to use FLUX:

[ModelInstallService]::ERROR --> Model install error: InvokeAI/clip-vit-large-patch14-text-encoder::bfloat16
ValidationError: 1 validation error for tagged-union[MainDiffusersConfig,MainCheckpointConfig,MainBnbQuantized4bCheckpointConfig,MainGGUFCheckpointConfig,VAEDiffusersConfig,VAECheckpointConfig,ControlNetDiffusersConfig,ControlNetCheckpointConfig,LoRALyCORISConfig,LoRADiffusersConfig,T5EncoderConfig,T5EncoderBnbQuantizedLlmInt8bConfig,TextualInversionFileConfig,TextualInversionFolderConfig,IPAdapterInvokeAIConfig,IPAdapterCheckpointConfig,T2IAdapterConfig,SpandrelImageToImageConfig,CLIPVisionDiffusersConfig,CLIPEmbedDiffusersConfig,CLIPLEmbedDiffusersConfig,CLIPGEmbedDiffusersConfig]
`clip_embed.diffusers`.variant
  Input should be 'large' or 'gigantic' [type=enum, input_value=<ModelVariantType.Normal: 'normal'>, input_type=ModelVariantType]
    For further information visit https://errors.pydantic.dev/2.7/v/enum

### What you expected to happen

I would excpect that starter models work out of the box.

**Comment by hackerbytermux** [comment]
same problem

**Comment by agrossano** [comment]
I'm having the same problem too

**Comment by posLop** [comment]
I am also having this issue with importing any clip model such as 
ViT-L-14-TEXT-detail-improved-hiT-GmP-TE-only-HF.safetensors
on HF and the original openai clip.

**Comment by zanknaf** [comment]
I am pretty sure this is the commit that broke the logic:

https://github.com/invoke-ai/InvokeAI/commit/b87f4e59a52c6481ce59a5cd980c947cda68aadd

<img width="1013" alt="image" src="https://github.com/user-attachments/assets/5a6fe645-2895-4fdc-a1c3-ae688f1a7a1a">

My suggestion would be to add "normal" to types and it should resolve the problem, but do not have time to actually test it today...

**Comment by psychedelicious** [comment]
This is fixed by #7275 and #7283.

**Comment by psychedelicious** [comment]
@rrandrews the v5.4.0 release was marked as a prerelease and pulled because of this issue. The fix will be in the next stable release.

**Comment by tampadesignr** [comment]
still broke 5.4.1
download with invokeai system everything works
then i take same stuff downloaded move to my shared model folder
point invoke at the files it just downloaded and doesnt work
