### ISSUE TITLE
[bug]: Stable Diffusion 3.5 not listed under models after install

### ISSUE THREAD

**Issue by aakropotkin** [invoke-ai/InvokeAI#7271]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 4080 Super

### GPU VRAM

16GB

### Version number

5.4.0

### Browser

Chromium

### What happened

After successfully installing Stable Diffusion 3.5 Medium from "Starter Models" panel, I cannot select/see the model in text2img model selection dropdown.

### What you expected to happen

I expect it to appear in the model selection dropdown.

**Comment by psychedelicious** [comment]
As described in the [release notes](https://github.com/invoke-ai/InvokeAI/releases/tag/v5.4.0), SD 3.5 is not yet supported in the Canvas UI. It's workflows-only at the moment.
