### ISSUE TITLE
[bug]: can not install Medium SD3.5 Model 15GB

### ISSUE THREAD

**Issue by evilduck1** [invoke-ai/InvokeAI#7322]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

rtx 4090

### GPU VRAM

16

### Version number

5.4.1

### Browser

firefox 132.0.2 64-bit

### What happened

trying to install Medium SD3.5 Model: ~15GB from the Starter models and get this

You do not have access to this HF model

We recommend visiting the repo page on HuggingFace.com. The owner may require acceptance of terms in order to download.
[stabilityai/stable-diffusion-3.5-medium](https://huggingface.co/stabilityai/stable-diffusion-3.5-medium)

### What you expected to happen

to be able to install it

### How to reproduce the problem

install Medium SD3.5 Model: ~15GB from the Starter models

**Comment by dashinja** [comment]
You must have a HF account.
You must go to the page mentioned and sign the agreement.
You must then make an HF token with that same account.
You must enter that HF token in the 'models' section of InvokeAI under HuggingFace (token section)
Then you can try again.

**Comment by evilduck1** [comment]
> You must have a HF account. You must go to the page mentioned and sign the agreement. You must then make an HF token with that same account. You must enter that HF token in the 'models' section of InvokeAI under HuggingFace (token section) Then you can try again. 

Thank you,
I had done that, but your comment made me go and look at my Token as I have never needed to use them before, and worked out I had used the Fine-grained Token type and not ticked any of the boxes so I made a new one under the wright Token type and all works now.
Again thank you

**Comment by dashinja** [comment]
> > You must have a HF account. You must go to the page mentioned and sign the agreement. You must then make an HF token with that same account. You must enter that HF token in the 'models' section of InvokeAI under HuggingFace (token section) Then you can try again.
> 
> Where is the token section? In the model manager there is a HuggingFace tab under the Add Model section. I am not seeing any token option there, I see only the "HuggingFace Repo ID"
> 
> Edit: I managed to do it from the developer console. Is there a token option in the UI?

I had that issue also. Before you enter a HF Token - there is an option to do it via the UI.
After you do it for the first time... it disappeared for me.

I had to the wrong token in, and could only fix it from the developer console with this:
https://invoke-ai.github.io/InvokeAI/faq/?h=token#huggingface-install-failed-due-to-invalid-access-token
