### ISSUE TITLE
[bug]: Installation fails (Python not found or too new?)

### ISSUE THREAD

**Issue by BorisBrock** [invoke-ai/InvokeAI#7334]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

AMD (ROCm)

### GPU model

7900 XTX

### GPU VRAM

24 GB

### Version number

5.4.1

### Browser

Firefox

### What happened

Installation fails with the following error:

A suitable Python interpreter could not be found
Please install Python 3.10.0 or higher (maximum 3.11.100) before running this script. See instructions at  for help.
Press any key to exit

On my machine Python 3.12.7 is installed:

InvokeAI-Installer python --version
Python 3.12.7

➜  InvokeAI-Installer pip --version
pip 24.3.1 from /usr/lib/python3.12/site-packages/pip (python 3.12)

### What you expected to happen

I would have expected the installer to work with Python 3.12.
Is there a reason 3.11 is the maximum supported version (according to error message)?

### How to reproduce the problem

Start ./install.sh

**Comment by hipsterusername** [comment]
Python 3.12 is not currently supported. Not a bug.
