### ISSUE TITLE
[bug]: Deleting files circumvents Recycle Bin

### ISSUE THREAD

**Issue by mcbexx** [invoke-ai/InvokeAI#7345]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### Version number

5.4.1

### Browser

Firefox 132

### What happened

I accidentally hit the delete button next to the "previous image" caret (tangentially, I think those UI elements should not be that close to another -  see screenshot below for clarification -, given that the deletion appears to be permanent). I wanted to retrieve the deleted image, but it was not in my Windows Recycle Bin.

Deleted some other expendable images to confirm and none of them went to the Recycle Bin but were irretrievably removed from the file system. And since there is no undo function for file deletion in the UI (I suggested it once, see Issue #4543), I don't see a way to get the image back. Seems like an oversight.

Bummer. 

![grafik](https://github.com/user-attachments/assets/efeb13d7-c7f5-4b3b-9e1c-69a807c45042)

### What you expected to happen

I expected images that are deleted from within the Invoke UI to get moved to the Windows Recycle Bin.

### How to reproduce the problem

Delete file from board, either by any of the various trashbin icons or by hitting the DEL key.

**Comment by psychedelicious** [comment]
We previously used `send2trash` for this, but have dropped it:
- It doesn't work correctly on all platforms, sometimes causing either fatal crashes or failing silently. 
- It encourages uses to fiddle with their image files directly, which causes issues where the database gets out of sync with the filesystem.

While we will not restore the trash/recycle bin handling, we're still happy to accept a contribution for soft-delete as described in my response #4543.
