### ISSUE TITLE
[bug]: DepthAnything has outliers

### ISSUE THREAD

**Issue by simonfuhrmann** [invoke-ai/InvokeAI#7358]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 4070

### GPU VRAM

12GB

### Version number

5.4.2

### Browser

Chrome

### What happened

When running DepthAnything processor (model size "base", but other model sizes are also affected), I get a depth map with many outliers. See attached image. In particular, there are white pixels (not all at 255, some have smaller values) in places where they don't make sense.

![depthanything](https://github.com/user-attachments/assets/686cbcc2-005a-4492-a664-272869cb329b)
![depthanything-color](https://github.com/user-attachments/assets/b9d51ee4-647d-4c7e-bcf6-461b7d8988ab)

### What you expected to happen

Get a depth map without outliers.

### How to reproduce the problem

Create trivial workflow with "Image Primitive" -> "Depth Anything Processor" and check "save to gallery" on the depth processor.

**Comment by psychedelicious** [comment]
We run the depth model directly via `transformers`. 

If I run the same Depth Anything v2 small model using the non-`transformers` implementation via [this script](https://github.com/DepthAnything/Depth-Anything-V2/blob/main/run.py), I do not get the artifacts.

This might be a bug with `transformers`: https://github.com/huggingface/transformers/issues/28292

**Comment by hipsterusername** [comment]
Hey @simonfuhrmann - are these impacting generation when you use them as a control?

I’ve not found them to be super deleterious in my use, as the outlines occur on object edges, but I’ve not done explicit testing

**Comment by simonfuhrmann** [comment]
I've not been using Depth Anything for control, but Stereogram generation (https://github.com/simonfuhrmann/invokeai-stereo), and for this use-case, these artifacts are super detrimental and cause unpleasant artifacts when viewing.

It's also worth nothing that these artifacts only appear in situations where there is a large depth disparity between foreground and background (such as portraits), thus not on all scenes.

**Comment by hipsterusername** [comment]
Makes sense for the use case! As noted above, we’ll have to look upstream for specific fixes.

An alternative to look into is seeing about enhancing depth processing to a newer model like lotus.

**Comment by simonfuhrmann** [comment]
I appreciate the effort of the team to look into this.

Transformers also seems to support Depth Anything v2. Is it worth giving this a shot? This is potentially the most straightforward path to updating the depth model? There is also [this issue](https://github.com/invoke-ai/InvokeAI/issues/6536), to it would be a feed-two-birds-with-one scone situtation.

**Comment by psychedelicious** [comment]
@simonfuhrmann We support both actually - well, only the small v2 variant due to licensing. Both have the same issue in my testing.

**Comment by simonfuhrmann** [comment]
The root cause for this seems to be bicubic interpolation which can generate values outside of the input domain and can causes an overflow issues. The solution is to use bilinear interpolation, or clamp before discretizing, as [described here](https://github.com/huggingface/transformers/issues/34300).

Is this something that can be done as part of InvokeAI's code?

**Comment by RyanJDick** [comment]
@simonfuhrmann Thanks for tracking down that discussion. It turns out that this has already been fixed upstream , so bumping transformers fixes the issue: https://github.com/invoke-ai/InvokeAI/pull/7386
