### ISSUE TITLE
[bug]: i tried to install invoke-ai on linux but install file doesnt exists

### ISSUE THREAD

**Issue by gabriel-batistuta** [invoke-ai/InvokeAI#7404]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### Version number

5.4.2

### Browser

Firefox Developer Edition 134.0b1 64 bits

### What happened

i tried to search in repo and the pull requests but i'm not able to find the instalation on linux but in the documentation on: https://invoke-ai.github.io/InvokeAI/installation/installer/#running-the-installer
https://github.com/invoke-ai/InvokeAI/blob/main/README.md 
theses docs gives a commando to install but the file ".sh" to install doesnt exists

### What you expected to happen

i expected to install in linux via 
```shell
install.sh #or
invoke.sh
```

### How to reproduce the problem

download release or the source code repository

**Comment by gogurtenjoyer** [comment]
The install.sh is in the zip file that's at the bottom of the release notes on the Releases page here on the repo.

**Comment by gabriel-batistuta** [comment]
Is there any specific reason why install.sh is not in the .tar.gz file?

**Comment by gogurtenjoyer** [comment]
Yes, because the automated installer is a whole separate thing; one of a few ways to install invokeai - the source for the installer is in the .tar.gz though.

**Comment by gabriel-batistuta** [comment]
Thanks a lot
