### ISSUE TITLE
`--device` missing from `development` branch

### ISSUE THREAD

**Issue by CapableWeb** [invoke-ai/InvokeAI#743]
In `main`, you're able to select which CUDA device to use, helpful in setups where multiple GPUs exists and you want to use a specific one, or you wanna run multiple instances of `dream.py` but on different GPUs.

This is the output from runnning `python3 -u scripts/dream.py --help` on `main`:

<details>
<pre><code>
usage: dream.py [-h] [--laion400m] [--from_file INFILE] [-n ITERATIONS] [-F]
                [-g] [-A SAMPLER_NAME] [--outdir OUTDIR] [--seamless]
                [--embedding_path EMBEDDING_PATH] [--prompt_as_dir]
                [--gfpgan_bg_upsampler GFPGAN_BG_UPSAMPLER]
                [--gfpgan_bg_tile GFPGAN_BG_TILE]
                [--gfpgan_model_path GFPGAN_MODEL_PATH]
                [--gfpgan_dir GFPGAN_DIR] [--web] [--host HOST] [--port PORT]
                [--weights WEIGHTS] [--device DEVICE] [--model MODEL]
                [--config CONFIG]

Generate images using Stable Diffusion. Use --web to launch the web interface.
Use --from_file to load prompts from a file path or standard input ("-").
Otherwise you will be dropped into an interactive command prompt (type -h for
help.) Other command-line arguments are defaults that can usually be
overridden prompt the command prompt.

optional arguments:
  -h, --help            show this help message and exit
  --laion400m, --latent_diffusion, -l
                        Fallback to the latent diffusion (laion400m) weights
                        and config
  --from_file INFILE    If specified, load prompts from this file
  -n ITERATIONS, --iterations ITERATIONS
                        Number of images to generate
  -F, --full_precision  Use more memory-intensive full precision math for
                        calculations
  -g, --grid            Generate a grid instead of individual images
  -A SAMPLER_NAME, -m SAMPLER_NAME, --sampler SAMPLER_NAME
                        Set the initial sampler. Default: k_lms. Supported
                        samplers: ddim, k_dpm_2_a, k_dpm_2, k_euler_a,
                        k_euler, k_heun, k_lms, plms
  --outdir OUTDIR, -o OUTDIR
                        Directory to save generated images and a log of
                        prompts and seeds. Default: outputs/img-samples
  --seamless            Change the model to seamless tiling (circular) mode
  --embedding_path EMBEDDING_PATH
                        Path to a pre-trained embedding manager checkpoint -
                        can only be set on command line
  --prompt_as_dir, -p   Place images in subdirectories named after the prompt.
  --gfpgan_bg_upsampler GFPGAN_BG_UPSAMPLER
                        Background upsampler. Default: realesrgan. Options:
                        realesrgan, none.
  --gfpgan_bg_tile GFPGAN_BG_TILE
                        Tile size for background sampler, 0 for no tile during
                        testing. Default: 400.
  --gfpgan_model_path GFPGAN_MODEL_PATH
                        Indicates the path to the GFPGAN model, relative to
                        --gfpgan_dir.
  --gfpgan_dir GFPGAN_DIR
                        Indicates the directory containing the GFPGAN code.
  --web                 Start in web server mode.
  --host HOST           Web server: Host or IP to listen on. Set to 0.0.0.0 to
                        accept traffic from other devices on your network.
  --port PORT           Web server: Port to listen on
  --weights WEIGHTS     Indicates the Stable Diffusion model to use.
  --device DEVICE, -d DEVICE
                        device to run stable diffusion on. defaults to cuda
                        `torch.cuda.current_device()` if available
  --model MODEL         Indicates which diffusion model to load. (currently
                        "stable-diffusion-1.4" (default) or "laion400m")
  --config CONFIG       Path to configuration file for alternate models.
</code></pre>
</details>

And this is the output from runnning `python3 -u scripts/dream.py --help` on `development`:

<details>
<pre><code>
usage: dream.py [-h] [--laion400m LAION400M] [--weights WEIGHTS] [--conf CONF]
                [--model MODEL] [--sampler SAMPLER_NAME] [-F]
                [--from_file INFILE] [--outdir OUTDIR] [--prompt_as_dir]
                [--grid] [--embedding_path EMBEDDING_PATH]
                [--gfpgan_bg_upsampler GFPGAN_BG_UPSAMPLER]
                [--gfpgan_bg_tile GFPGAN_BG_TILE]
                [--gfpgan_model_path GFPGAN_MODEL_PATH]
                [--gfpgan_dir GFPGAN_DIR] [--web] [--host HOST] [--port PORT]

Generate images using Stable Diffusion. Use --web to launch the web interface.
Use --from_file to load prompts from a file path or standard input ("-").
Otherwise you will be dropped into an interactive command prompt (type -h for
help.) Other command-line arguments are defaults that can usually be
overridden prompt the command prompt.

optional arguments:
  -h, --help            show this help message and exit

Model selection:
  --conf CONF, -c CONF, -conf CONF
                        Path to configuration file for alternate models.
  --model MODEL         Indicates which diffusion model to load. (currently
                        "stable-diffusion-1.4" (default) or "laion400m")
  --sampler SAMPLER_NAME, -A SAMPLER_NAME, -m SAMPLER_NAME
                        Switch to a different sampler. Supported samplers:
                        ddim, k_dpm_2_a, k_dpm_2, k_euler_a, k_euler, k_heun,
                        k_lms, plms
  -F, --full_precision  Use more memory-intensive full precision math for
                        calculations

Input/output:
  --from_file INFILE    If specified, load prompts from this file
  --outdir OUTDIR, -o OUTDIR
                        Directory to save generated images and a log of
                        prompts and seeds. Default: outputs/img-samples
  --prompt_as_dir, -p   Place images in subdirectories named after the prompt.

Web server:
  --web                 Start in web server mode.
  --host HOST           Web server: Host or IP to listen on. Set to 0.0.0.0 to
                        accept traffic from other devices on your network.
  --port PORT           Web server: Port to listen on

Rendering:
  --grid, -g            generate a grid
  --embedding_path EMBEDDING_PATH
                        Path to a pre-trained embedding manager checkpoint -
                        can only be set on command line

Postprocessing:
  --gfpgan_bg_upsampler GFPGAN_BG_UPSAMPLER
                        Background upsampler. Default: realesrgan. Options:
                        realesrgan, none.
  --gfpgan_bg_tile GFPGAN_BG_TILE
                        Tile size for background sampler, 0 for no tile during
                        testing. Default: 400.
  --gfpgan_model_path GFPGAN_MODEL_PATH
                        Indicates the path to the GFPGAN model, relative to
                        --gfpgan_dir.
  --gfpgan_dir GFPGAN_DIR
                        Indicates the directory containing the GFPGAN code.

Deprecated options:
  --laion400m LAION400M
  --weights WEIGHTS
</code></pre>
</details>

Notice how `development` is missing the `--device` flag. 

Using the `--device` flag in `development` also makes `dream.py` return a error:

```
dream.py: error: unrecognized arguments: --device cuda:1
```

Seems like a regression where maybe the argument got lost in the latest refactorings that have been happening as of late.

**Comment by lstein** [comment]
Good pickup! This was an inadvertent regression, and hopefully just adding the option back in will restore the functionality.

**Comment by n00mkrad** [comment]
> Good pickup! This was an inadvertent regression, and hopefully just adding the option back in will restore the functionality.

I don't think so, seems intentional:

```
        # Note that in previous versions, there was an option to pass the
        # device to Generate(). However the device was then ignored, so
        # it wasn't actually doing anything. This logic could be reinstated.
```
