### ISSUE TITLE
WebUI img2img got an unexpected keyword argument 'first_seed'

### ISSUE THREAD

**Issue by RobertBolender** [invoke-ai/InvokeAI#747]
**Describe your environment**
- GPU: mps
- VRAM: [if known]
- CPU arch: arm
- OS: macOS
- Python: miniconda
- Branch: `development`
- Commit: `0ab5f2159d5d7b25cffd96b03fed0ecd305db5b6`

**Describe the bug**

```
Error happened
DreamServer.do_POST.<locals>.image_done() got an unexpected keyword argument 'first_seed'
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 57099)
Traceback (most recent call last):
  File "/Users/robertbolender/miniconda3/envs/ivk/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/Users/robertbolender/miniconda3/envs/ivk/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/robertbolender/miniconda3/envs/ivk/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/Users/robertbolender/miniconda3/envs/ivk/lib/python3.10/http/server.py", line 425, in handle
    self.handle_one_request()
  File "/Users/robertbolender/miniconda3/envs/ivk/lib/python3.10/http/server.py", line 413, in handle_one_request
    method()
  File "/Users/robertbolender/code/InvokeAI/ldm/dream/server.py", line 267, in do_POST
    raise e
  File "/Users/robertbolender/code/InvokeAI/ldm/dream/server.py", line 252, in do_POST
    self.model.prompt2image(**vars(opt1), step_callback=image_progress, image_callback=image_done)
  File "/Users/robertbolender/code/InvokeAI/ldm/generate.py", line 411, in prompt2image
    results = generator.generate(
  File "/Users/robertbolender/code/InvokeAI/ldm/dream/generator/base.py", line 75, in generate
    image_callback(image, seed, first_seed=first_seed)
TypeError: DreamServer.do_POST.<locals>.image_done() got an unexpected keyword argument 'first_seed'
```

**To Reproduce**
1. Start `python script/dream.py --web`
2. Add an initial image
3. Attempt to generate a new image
4. See error when the progress bar finishes, the process stops and no file is created

**Expected behavior**
Images can be created from images without errors.

**Additional context**

I know that the `first_seed` was added recently, the Web UI may need to be updated to accommodate the new argument?

**Comment by ioma8** [comment]
I also get this error when running from webUI. And not only for image2image but also for regular just text prompts:
```  File "/Users/jakubkolcar/custom/InvokeAI/ldm/generate.py", line 411, in prompt2image
    results = generator.generate(
  File "/Users/jakubkolcar/custom/InvokeAI/ldm/dream/generator/base.py", line 75, in generate
    image_callback(image, seed, first_seed=first_seed)
TypeError: DreamServer.do_POST.<locals>.image_done() got an unexpected keyword argument 'first_seed'
```

When I enter some seed number into the seed input I get this another error:
```  File "/Users/jakubkolcar/custom/InvokeAI/ldm/generate.py", line 753, in _sample_to_image
    self.base_generator = Generator(self.model)
TypeError: Generator.__init__() missing 1 required positional argument: 'precision'
```

**Comment by kriptolix** [comment]
I can also confirm this error in the development branch. But --web is the suffix of the old web interface, and the new interface should be releasing any time now and I believe the old web interface is no longer being updated.

**Comment by RobertBolender** [comment]
> But --web is the suffix of the old web interface, and the new interface should be releasing any time now

Is the new interface available in the `development` branch or still on a different branch?

**Comment by timdesrochers** [comment]
> I also get this error when running from webUI. And not only for image2image but also for regular just text prompts:
> 
> ```
>     results = generator.generate(
>   File "/Users/jakubkolcar/custom/InvokeAI/ldm/dream/generator/base.py", line 75, in generate
>     image_callback(image, seed, first_seed=first_seed)
> TypeError: DreamServer.do_POST.<locals>.image_done() got an unexpected keyword argument 'first_seed'
> ```
> 
> When I enter some seed number into the seed input I get this another error:
> 
> ```
>     self.base_generator = Generator(self.model)
> TypeError: Generator.__init__() missing 1 required positional argument: 'precision'
> ```

I fixed the precision issue in my env by changing lines 169-170 in generate.py to
```
full_precision = True,
precision = 'float32',

**Comment by jspraul** [comment]
FYI: The fix has been merged into the development branch.
