### ISSUE TITLE
[bug]: Masses of 'access denied' messages when trying to backup files

### ISSUE THREAD

**Issue by fbauer-kunbus** [invoke-ai/InvokeAI#7479]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

4090

### GPU VRAM

notebook version with only 16GB

### Version number

5.5.0

### Browser

Firefox 127.0

### What happened

I use Beyond Compare to backup my AI software installation to an external HDD. Only Invoke causes troubles here with over 1200 error messages like this one:

21/12/2024 15:23:54  Unable to copy C:\MyProg\StabilityMatrix\Data\Packages\InvokeAI\invokeai\frontend\web\node_modules\.pnpm\@atlaskit+pragmatic-drag-and-drop@1.4.0\node_modules\@babel\runtime: Access is denied

Why do you guys at Invoke think you need to do everything with other ways than everybody else. It is totally annoying having to deal with such unnecessary problems ... WTF

### What you expected to happen

I want to simply be able to backup ALL of my Invoke.AI local installation to an external HDD

**Comment by psychedelicious** [comment]
This is not an Invoke problem. It's a StabilityMatrix problem. You'll need to take it up with them.

The files referenced in the error message are part of Invoke's source code, and are not distributed as part of an Invoke installation, nor are they needed for to install the app. If you install Invoke using our legacy install scripts, with our new launcher, manually as a python package, or as a docker container, those files are not included.

It looks like SM has cloned the _entire_ Invoke repo and done it with weird permissions. I have no idea why they would do that.
