### ISSUE TITLE
[bug]: Raster layer denoising strength appears to do nothing when there is "empty" space

### ISSUE THREAD

**Issue by lerocox** [invoke-ai/InvokeAI#7486]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

Tesla T40 & 3090

### GPU VRAM

24 & 24

### Version number

5.5.0

### Browser

Firefox

### What happened

Initially, I believed that denoising strength was broken. 

As far as I could tell invoke was using my image 1:1 and only filling out the top/bottom of the picture.

However, I figured out that if I run a generation before resizing the image to bounding box (which creates void space) the de-noising strength appears to begin working.  The existence of any "void" (transparency made by the eraser) results in denoising strength no longer applying to the image.

### What you expected to happen

I would expect the denoising strength to apply regardless of if there is "void" space in the raster layer, or for some sort of super clear warning or indication to appear indicating that the image will be treated as a "inset" instead of a image-to-image when there is void space in the raster

**Comment by hipsterusername** [comment]
This isn’t a bug, but does highlight a less than intuitive behavior of the application with respect to outpainting.

By default, transparent areas are treated similar to an “inpaint mask” in that they focus the area of generation there if it exists.
