### ISSUE TITLE
Face Correction & Upscaling Model Optionality

### ISSUE THREAD

**Issue by hipsterusername** [invoke-ai/InvokeAI#749]
**Is your feature request related to a problem? Please describe.**
Currently, face correction & upscaling models are required to start the server (in dev.)

**Describe the solution you'd like**
Launching the server without these models should be supported - Relevant areas of the UI should be disabled.

**Describe alternatives you've considered**
None.

**Additional context**
Users may not wish to download these models, or in the event of sudden model unavailability, all new installs would fail. These should not be critical dependencies for Invoke

**Comment by wbecher** [comment]
I agree with that. I believe it should show a warning on startup, not just block with an error.

**Comment by blessedcoolant** [comment]
Agreed. I updated this change in my next bug fix patch.

**Comment by jspraul** [comment]
For anyone searching, here is the error message at 413064cf4536760cf3f92f3fd49166b394ae0634 if `--no_restore` is not used to disable face restoration and the model hasn't been downloaded:
```
Traceback (most recent call last):
  File "scripts/dream.py", line 454, in <module>
    main()
  File "scripts/dream.py", line 53, in main
    gfpgan, codeformer = restoration.load_face_restore_models()
  File "…\downloads\stable-diffusion\ldm\dream\restoration\base.py", line 9, in load_face_restore_models
    gfpgan = self.load_gfpgan()
  File "…\downloads\stable-diffusion\ldm\dream\restoration\base.py", line 23, in load_gfpgan
    return GFPGAN(self.gfpgan_dir, self.gfpgan_model_path)
  File "…\downloads\stable-diffusion\ldm\dream\restoration\gfpgan.py", line 20, in __init__
    raise Exception(
Exception: GFPGAN model not found at path ./src/gfpgan\experiments/pretrained_models/GFPGANv1.3.pth
```

[Installation instructions](https://github.com/invoke-ai/InvokeAI/blob/development/docs/features/UPSCALE.md) for those who wish to use face restoration.

**Comment by lstein** [comment]
I agree as well. If the libraries can't be loaded we issue non-blocking errors. If the `--no_restore` and/or `--no_upscale` options are present, we suppress the warning(s).

**Comment by blessedcoolant** [comment]
> I agree as well. If the libraries can't be loaded we issue non-blocking errors. If the `--no_restore` and/or `--no_upscale` options are present, we suppress the warning(s).
> 
> The PR is still marked as draft, but I think @blessedcoolant is planning to complete work on it soon.

It's done. Restoration Modules are fully optional now. And I think I covered every use case without the app crashing.

**Comment by lstein** [comment]
Merged into development. Thanks for the quick work!
