### ISSUE TITLE
[bug]: A few models will not download due to hugging face token error

### ISSUE THREAD

**Issue by ghostmonster-bb** [invoke-ai/InvokeAI#7490]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 3080Ti

### GPU VRAM

12

### Version number

5.5

### Browser

edge

### What happened

I clicked the add model button and it fails

### What you expected to happen

to get the models listed

**Comment by ghostmonster-bb** [comment]
![Screenshot 2024-12-22 215122](https://github.com/user-attachments/assets/9f1b34e9-679f-4b91-9197-8c6ea19fb5c9)

**Comment by fcoreveles** [comment]
I have the same problem

**Comment by ghost** [comment]
@ghostmonster-bb 
Have this problem today with 5.13.0.
I accepted everything at hugging face page.

Even `vae FLUX FLUX.1-schnell_ae` does not work.
On the webpage i see "Gated model You have been granted access to this model"
