### ISSUE TITLE
Problem loading custom embeddings with the new WebUI on Windows

### ISSUE THREAD

**Issue by wbecher** [invoke-ai/InvokeAI#750]
**Describe your environment**
- GPU: Nvidia Geforce RTX 3060 Laptop
- VRAM: 6GB
- CPU arch: Intel Core i7 11800H
- OS: Windows 11
- Python: Anaconda
- Branch: development
- Commit: f1d4862b132a3c604db9632862192f24fe01b3bd

**Describe the bug**
I'm running the new WebUI without problems. But when I've tried to use the `--embedding_path parameter`, I got this error:

```
(ldm) C:\stable-diffusion-lstein>python backend\server.py --host 0.0.0.0 --port 9090 --embedding_path C:\stable-diffusion\embeddings
* Initializing, be patient...

>> GFPGAN Initialized
>> CodeFormer Initialized
>> ESRGAN Initialized
>> Loading model from models/ldm/stable-diffusion-v1/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
>> Using faster float16 precision
>> Model loaded in 24.00s
>> Max VRAM used to load the model: 2.17G
>> Current VRAM usage:2.17G
Traceback (most recent call last):
  File "C:\stable-diffusion-lstein\backend\server.py", line 147, in <module>
    generate.load_model()
  File "c:\stable-diffusion-lstein\ldm\generate.py", line 667, in load_model
    model.embedding_manager.load(
  File "c:\stable-diffusion-lstein\ldm\modules\embedding_manager.py", line 222, in load
    ckpt = torch.load(ckpt_path, map_location='cpu')
  File "c:\Users\wbech\anaconda3\envs\ldm\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "c:\Users\wbech\anaconda3\envs\ldm\lib\site-packages\torch\serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "c:\Users\wbech\anaconda3\envs\ldm\lib\site-packages\torch\serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
PermissionError: [Errno 13] Permission denied: 'C:\\stable-diffusion\\embeddings'
```

I've already have tried to change the folder, add some permissions, even give Everyone FULL CONTROL permission. Am I doing something wrong?

**To Reproduce**
1. Go to repository folder, and run `python backend\server.py --host 0.0.0.0 --port 9090 --embedding_path C:\stable-diffusion\embeddings`
2. See error

**Expected behavior**
Load custom embeddings.

**Screenshots**
Permissions of the embeddings folder:
![image](https://user-images.githubusercontent.com/1504625/191829812-064758d9-5f2e-415c-926e-5c6f13a2ea59.png)

**Additional context**

**Comment by lstein** [comment]
To help isolate whether this is a WebGUI-specific issue or a more general issue, could you try the command-line interface (`scripts\dream.py`) with the same embedding file?

Tagging @psychedelicious for comments on the WebGUI.

**Comment by psychedelicious** [comment]
Hi @wbecher , it looks like `embeddings` is a folder, not an embeddings file. I tested only with an individual file, and that worked. Should it work with a folder?

**Comment by lstein** [comment]
I missed that! I think that is your problem. You need to point at the .bin or .pt file, not its directory.

**Comment by wbecher** [comment]
Oh, I see! Thank you.

Is there any way of loading two embeddings file? I was fiddling around with automatic1111`s fork, and there we can load a folder containing any number of files, and use any of the embeddings.

**Comment by psychedelicious** [comment]
We don't have that capability yet but once it is implemented I'd like to allow managing models, embedding files, etc in the web UI.

**Comment by wbecher** [comment]
Closing because I was using the wrong syntax to load the embeddings.
