### ISSUE TITLE
How to see metadata from an external app?

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#755]
Greetings, 

it seems that there is metadata being saved to the grid, if any. Is there a way to see what's been written to the file with Photoshop and/or any other image reader? If yes, would someone care to explain a quick how to?

Thank you,

**Comment by lstein** [comment]
I use the Imagemagick application on Linux. Not sure how to do it on windows. 

From within the InvokeAI distribution, there are two ways to get the metadata. At the command line, we have a script named `scripts/sd-metadata.py` in the `development` branch. Point it at the file and it will print out the metadata.

Second, within the **new** WebGUI (`backend/server.py`) you can load up an image and click the *Details* button to display the metadata.

**Comment by n00mkrad** [comment]
pngcheck can do it, my [GUI](https://github.com/n00mkrad/text2image-gui) can do it

**Comment by tildebyte** [comment]
On Windows, [TweakPNG](http://entropymine.com/jason/tweakpng) can both read and write arbitrary metadata, and has a nicely minimal-but-functional GUI (yes, it's ancient, but runs for me without issues on WIndows 10/11)

**Comment by timdesrochers** [comment]
Also the handy `exiftool`

**Comment by Daves1277** [comment]
fix it michele

**Comment by Neosettler** [comment]
TweakPNG does works but it would be handy if a common field would be used. A field like "Comment" that any image reader would pick up.

**Comment by Neosettler** [comment]
looking at pngwriter.py:
`info.add_text('Dream', prompt)`

Still digging but I'll find a way to override "Comment" instead of adding a new entry.

**Comment by tildebyte** [comment]
PNG metadata is still basically a Wild West in terms of standardization. That's why we have what we have here.

**Comment by Neosettler** [comment]
hehe, indeed. After investigation, I was thinking the exact same thing!!! A standard/all in one solution for metadata would be sexy.

**Comment by psychedelicious** [comment]
Question answered a few different ways - closing.
