### ISSUE TITLE
Request: Switch to enable step checks/progress images on CLI

### ISSUE THREAD

**Issue by timdesrochers** [invoke-ai/InvokeAI#769]
I'm curious about what's going on under the hood with this magic stuff. Beyond that, I suspect it might be useful for identifying how many steps you need for a given prompt or set of prompts — I've seen comparisons of the different samplers at different step counts online and it's remarkable how much the output can change from even just one step to the next (I think it was k_euler_a that was called out for this). 

Is there a way to generate these without the GUI?

**Comment by psychedelicious** [comment]
Hi @timdesrochers , work on this very feature is underway in #694.

**Comment by timdesrochers** [comment]
Just saw that. Hooray!
