### ISSUE TITLE
All model files loaded instead of just the latest revisions

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#770]
**Is your feature request related to a problem? Please describe.**
I'd like to have all valid models/checkpoints for the various technologies available to the CLI/UI, including "outdated" ones, in case I want to compare the models' output, or use an old model which gives a certain desired quality to its outputs.

**Describe the solution you'd like**
`preload_models.py` could have the option to download all models, even old ones. The CLI/UI would need options to use whichever model.

**Describe alternatives you've considered**
Manually managing model files

**Additional context**
This is a low-priority, rainy day feature request.

**Comment by lstein** [comment]
Keep it on your list. Someday!
