### ISSUE TITLE
New WebUI - load concepts files

### ISSUE THREAD

**Issue by ioma8** [invoke-ai/InvokeAI#771]
**Describe the solution you'd like**
I want to be able one (or) more concepts finetune files to be loaded to the new webui (throught cmdline parameter at start would be ok). The functionality used before in dream.py shown eg in #620

**Comment by wbecher** [comment]
You can use the same syntax used by dream.py to load with the parameter on command line.

**Comment by psychedelicious** [comment]
Note only a single embedding file is supported at this time, multiples and a UI to manage are planned.

**Comment by psychedelicious** [comment]
I’ll close this as resolved (feature is implemented) and planned (for multiple embeddings) but please tag me if I have misunderstood your issue.
