### ISSUE TITLE
Implement Flash Attention for 50% speedup

### ISSUE THREAD

**Issue by n00mkrad** [invoke-ai/InvokeAI#781]
Check out this reddit post:

https://www.reddit.com/r/StableDiffusion/comments/xmr3ic/speed_up_stable_diffusion_by_50_using_flash/

Claims to achieve a 50% speedup by using Flash Attention.

Is it possible to implement this into this repo?

**Comment by n00mkrad** [comment]
See here for a reference implementation:

https://github.com/TheLastBen/fast-stable-diffusion

**Comment by Any-Winter-4079** [comment]
Yep, I had just read that post. I'll take a look.

**Comment by Any-Winter-4079** [comment]
Repo for Flash Attention https://github.com/HazyResearch/flash-attention

**Comment by krummrey** [comment]
The pace at which SD is maturing is unbelievable. The true power of going Open Source.

**Comment by tildebyte** [comment]
The only issue I see, at least in the  "official" paper-accompaniment repo, is that there's a CUDA-side c++ binary library (I guess? I don't see how it's being built) - building binaries via conda/pip is a non-starter in this repo. We have enough trouble with pure-Python installs 😂

If **they** are going to be releasing binaries for the Big Three platforms, then OK, otherwise...

**Comment by nguyenkm** [comment]
There's am active thread on how to get it to work for non-Linux systems.  https://github.com/huggingface/diffusers/pull/532

**Comment by Any-Winter-4079** [comment]
> There's am active thread on how to get it to work for non-Linux systems. [huggingface/diffusers#532](https://github.com/huggingface/diffusers/pull/532)

That looks interesting. I couldn't get it to work on MPS, but curious to see if it works on CUDA.

**Comment by tildebyte** [comment]
@Any-Winter-4079;

I'm guessing that's because, as I said, "there's a CUDA-side c++ binary library" which has to be built per-platform; I doubt that it has been built for macOS/M* systems yet.

**Comment by Any-Winter-4079** [comment]
@tildebyte I was testing https://github.com/huggingface/diffusers/pull/532/files, with
`pip install git+https://github.com/facebookresearch/xformers@51dd119#egg=xformers`
and
`export USE_MEMORY_EFFICIENT_ATTENTION=1`
plus updating `attention.py` but got the error from above.

That seemed to be another repo different from the C++ one initially mention (this one is using `xformers`), although I might be tripping and internally be using the C++ lib, cause it's very late here, and I'm half awake/half asleep already  :)

**Comment by tildebyte** [comment]
There's a "Fast Attention" as well, different thing...

**Comment by blefaudeux** [comment]
> There's a "Fast Attention" as well, different thing...

No it’s the same idea actually, the xformers repo dispatches to the flash attention kernels when applicable, else uses it’s own kernels

**Comment by i3oc9i** [comment]
@Any-Winter-4079 
Here is an implemetation of xfromer from facebook research
https://github.com/facebookresearch/xformers

looking at the README, it can be compiled on MacOs. Read build from source section.
`MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ pip install -e .`

**Comment by Any-Winter-4079** [comment]
I installed via `MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ pip install -e git+https://github.com/facebookresearch/xformers.git#egg=xformers`
Now let's try to use it!

**Comment by Any-Winter-4079** [comment]
Update to say I tried ignoring the `triton` part, and searching a bit where the AttentionOpDispatch error comes from, it seems to come from `import xformers.ops` and `ops.py` file. There is a bunch of cuda stuff there so not sure how we would run it with mps.

Commenting out / replacing some cuda stuff, the furthers I could come is
`NotImplementedError: Could not run 'xformers::efficient_attention_forward_cutlass' with arguments from the 'CPU' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'xformers::efficient_attention_forward_cutlass' is only available for these backends: [Metal, UNKNOWN_TENSOR_TYPE_ID, QuantizedXPU, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, SparseCPU, SparseCUDA, SparseHIP, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, SparseVE, UNKNOWN_TENSOR_TYPE_ID, NestedTensorCUDA, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID].
`

**Comment by mauwii** [comment]
I am not rly sure what I am testing there 🙈, but with `python3 benchmarks/benchmark_encoder.py --activations relu --plot -emb 256 -bs 32 -heads 16` things are realy slow without even utilizing cpu/gpu, also canot get the missing packages installed (and sorry for this long codeblock, 


```py
python3 xformers/benchmarks/benchmark_encoder.py --activations gelu --plot -emb 256 -bs 32 -heads 16
Triton is not available, some optimizations will not be enabled.
This is just a warning: No module named 'triton'
Either FairScale or torch distributed is not available, MixtureOfExperts will not be exposed. Please install them if you would like to use MoE
Testing the following parameters: 
 {
    "activation": [
        "gelu"
    ],
    "attention_name": [
        "favor",
        "global",
        "linformer",
        "local",
        "nystrom",
        "orthoformer",
        "random",
        "scaled_dot_product",
        "compositional",
        "pooling",
        "lambda",
        "fourier_mix",
        "visual"
    ],
    "autocast": [
        true
    ],
    "batch_size": [
        32
    ],
    "causal": [
        false
    ],
    "embed_dim": [
        256
    ],
    "feedforward_name": [
        "MLP"
    ],
    "heads": [
        16
    ],
    "sequence_length": [
        576,
        1024
    ]
}
  0%|                                                                                                                                                                                                  | 0/26 [00:00<?, ?it/s]Testing: xFormerEncoderBlock(
  (pose_encoding): SinePositionalEmbedding()
  (wrap_att): PostNorm(
    (norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    (sublayer): Residual(
      (layer): MultiHeadDispatch(
        (attention): FavorAttention(
          (attn_drop): Dropout(p=0.1, inplace=True)
          (feature_map): SMReg()
        )
        (in_proj_container): InputProjection(
          (q_proj): Linear(in_features=256, out_features=256, bias=True)
          (k_proj): Linear(in_features=256, out_features=256, bias=True)
          (v_proj): Linear(in_features=256, out_features=256, bias=True)
        )
        (resid_drop): Dropout(p=0.1, inplace=False)
        (proj): Linear(in_features=256, out_features=256, bias=True)
      )
    )
  )
  (wrap_ff): PostNorm(
    (norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    (sublayer): Residual(
      (layer): MLP(
        (mlp): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate=none)
          (2): Dropout(p=0.1, inplace=False)
          (3): Linear(in_features=1024, out_features=256, bias=True)
          (4): Dropout(p=0.1, inplace=False)
        )
      )
    )
  )
) 32 576 256 True cpu favor
/Users/mauwii/.pyenv/versions/miniconda3-latest/envs/xformer_env/lib/python3.8/site-packages/torch/amp/autocast_mode.py:198: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
/Users/mauwii/git/facebookresearch/xformers/xformers/components/positional_embedding/sine.py:39: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  div = torch.exp(-math.log(10000) * (2 * (dim // 2) / self.dim_model))
  4%|███████▏                                                                                                                                                                                  | 1/26 [00:07<02:56,  7.05s/it]Testing: xFormerEncoderBlock(
  (pose_encoding): SinePositionalEmbedding()
  (wrap_att): PostNorm(
    (norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    (sublayer): Residual(
      (layer): MultiHeadDispatch(
        (attention): FavorAttention(
          (attn_drop): Dropout(p=0.1, inplace=True)
          (feature_map): SMReg()
        )
        (in_proj_container): InputProjection(
          (q_proj): Linear(in_features=256, out_features=256, bias=True)
          (k_proj): Linear(in_features=256, out_features=256, bias=True)
          (v_proj): Linear(in_features=256, out_features=256, bias=True)
        )
        (resid_drop): Dropout(p=0.1, inplace=False)
        (proj): Linear(in_features=256, out_features=256, bias=True)
      )
    )
  )
  (wrap_ff): PostNorm(
    (norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    (sublayer): Residual(
      (layer): MLP(
        (mlp): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate=none)
          (2): Dropout(p=0.1, inplace=False)
          (3): Linear(in_features=1024, out_features=256, bias=True)
          (4): Dropout(p=0.1, inplace=False)
        )
      )
    )
  )
)

.....

62%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                       | 16/26 [06:51<06:13, 37.33s/it]Testing: xFormerEncoderBlock(
  (pose_encoding): SinePositionalEmbedding()
  (wrap_att): PostNorm(
    (norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    (sublayer): Residual(
      (layer): MultiHeadDispatch(
        (attention): CompositionalAttention(
          (in_proj_container): InputProjection(
            (q_proj): Linear(in_features=256, out_features=256, bias=True)
            (k_proj): Linear(in_features=256, out_features=256, bias=True)
            (v_proj): Linear(in_features=256, out_features=256, bias=True)
          )
          (dropout_module): Dropout(p=0.1, inplace=False)
          (out_proj): Linear(in_features=256, out_features=256, bias=True)
          (value_q): Linear(in_features=256, out_features=256, bias=True)
          (score_network): Linear(in_features=32, out_features=1, bias=True)
        )
        (in_proj_container): InputProjection(
          (q_proj): Linear(in_features=256, out_features=256, bias=True)
          (k_proj): Linear(in_features=256, out_features=256, bias=True)
          (v_proj): Linear(in_features=256, out_features=256, bias=True)
        )
        (resid_drop): Dropout(p=0.1, inplace=False)
        (proj): Linear(in_features=256, out_features=256, bias=True)
      )
    )
  )
  (wrap_ff): PostNorm(
    (norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    (sublayer): Residual(
      (layer): MLP(
        (mlp): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate=none)
          (2): Dropout(p=0.1, inplace=False)
          (3): Linear(in_features=1024, out_features=256, bias=True)
          (4): Dropout(p=0.1, inplace=False)
        )
      )
    )
  )
) 32 576 256 True cpu compositional

........
```

but hey - at least everything is responding superslow while runing this :godmode: 


Wow - Swap-memory is >40GB now, going to die soon

**Comment by mauwii** [comment]
Ok, it crashed the script (would have bet that the mac will die ....). These where the last lines:

```py
65%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                | 17/26 [10:06<12:41, 84.59s/it]Testing: xFormerEncoderBlock(
  (pose_encoding): SinePositionalEmbedding()
  (wrap_att): PostNorm(
    (norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    (sublayer): Residual(
      (layer): MultiHeadDispatch(
        (attention): CompositionalAttention(
          (in_proj_container): InputProjection(
            (q_proj): Linear(in_features=256, out_features=256, bias=True)
            (k_proj): Linear(in_features=256, out_features=256, bias=True)
            (v_proj): Linear(in_features=256, out_features=256, bias=True)
          )
          (dropout_module): Dropout(p=0.1, inplace=False)
          (out_proj): Linear(in_features=256, out_features=256, bias=True)
          (value_q): Linear(in_features=256, out_features=256, bias=True)
          (score_network): Linear(in_features=32, out_features=1, bias=True)
        )
        (in_proj_container): InputProjection(
          (q_proj): Linear(in_features=256, out_features=256, bias=True)
          (k_proj): Linear(in_features=256, out_features=256, bias=True)
          (v_proj): Linear(in_features=256, out_features=256, bias=True)
        )
        (resid_drop): Dropout(p=0.1, inplace=False)
        (proj): Linear(in_features=256, out_features=256, bias=True)
      )
    )
  )
  (wrap_ff): PostNorm(
    (norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    (sublayer): Residual(
      (layer): MLP(
        (mlp): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate=none)
          (2): Dropout(p=0.1, inplace=False)
          (3): Linear(in_features=1024, out_features=256, bias=True)
          (4): Dropout(p=0.1, inplace=False)
        )
      )
    )
  )
) 32 1024 256 True cpu compositional
[1]    19942 killed     python3 xformers/benchmarks/benchmark_encoder.py --activations gelu --plot   
/Users/mauwii/.pyenv/versions/miniconda3-latest/envs/xformer_env/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown  
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by blefaudeux** [comment]
hey there, this benchmark tests a really big chunk of all the building blocks available on xformers and is mostly run on production GPUs, no worries if that does not work for you (you can see the options [here](https://github.com/facebookresearch/xformers/blob/main/xformers/benchmarks/benchmark_encoder.py#L317), if you limit it to a given attention mechanism or activation if should run a lot less options, and have a chance to finish). You can see it run [here](https://app.circleci.com/pipelines/github/facebookresearch/xformers/2974/workflows/490b46b9-cb72-4272-b016-a9226db414d0/jobs/8267/parallel-runs/0/steps/0-111) on a CUDA gpus for sanity checking, but really if you're interested in mem efficient attention you should not bother.

What you *can* run though is [this one](https://github.com/facebookresearch/xformers/blob/main/xformers/benchmarks/benchmark_mem_eff_attention.py) (may not make too much sense outside of cuda), else just focus on running it in your particular case

**Comment by dillfrescott** [comment]
Wait, so if i install Flash Attention 2, invokeai can utilize it right?
