### ISSUE TITLE
Usage of GFPGAN fails silently if not downloaded

### ISSUE THREAD

**Issue by pigubaoza** [invoke-ai/InvokeAI#782]
If a user does not download the GFPGAN model, but adds the `-G` argument into the dream CLI, GFPGAN is not used, but the user is not notified. 

It's probably good to add a message to notify the user, and add a link in `docs/features/CLI.md` to `docs/features/UPSCALE.md`, where the instructions to download the model can be found.

**Comment by blessedcoolant** [comment]
Are you trying this on the latest dev version? I added checks and notification messages for that.

**Comment by Any-Winter-4079** [comment]
I do get a message
```
WARNING: GFPGAN not initialized.
>> Download https://github.com/TencentARC/GFPGAN/releases/download/v1.3.0/GFPGANv1.4.pth to ./src/gfpgan/experiments/pretrained_models/GFPGANv1.4.pth, 
or change GFPGAN directory with --gfpgan_dir.
>> Error running RealESRGAN or GFPGAN. Your image was not upscaled.
'NoneType' object has no attribute 'enhance'
>> Usage stats:
>>   1 image(s) generated in 28.36s
Outputs:
[6] outputs/img-samples/001457.1580484038.png: "taylor swift" -s 50 -S 1580484038 -W 512 -H 512 -C 7.5 -A k_lms -G 0.9
```
Try pulling the latest changes from dev branch and let us know if it works!

**Comment by pigubaoza** [comment]
verified that it's there on dev branch! would be great if the warning was printed before the generation step though, as generating could take quite long

**Comment by blessedcoolant** [comment]
> verified that it's there on dev branch! would be great if the warning was printed before the generation step though, as generating could take quite long

On the dev branch, it makes a check when you load. If it's not found, it'll throw the warning right at the very beginning.

**Comment by pigubaoza** [comment]
thank you! hoping to see this in the next release!
