### ISSUE TITLE
openh264 2.3.1 breaks OpenCV dependencies

### ISSUE THREAD

**Issue by jdries3** [invoke-ai/InvokeAI#787]
**Describe your environment**
- GPU: [mps]
- CPU arch: [arm64]
- OS: [macOS]
- Python: [miniconda]
- Branch: [development]

**Describe the bug**
openh264 2.3.1 breaks OpenCV dependencies. Version 2.3.1 increments libopenh264 to `libopenh264.7.dylib` while the 4.6.0 release of OpenCV is expecting `libopenh264.6.dylib`. Without pinning to 2.3.0, running `python scripts/preload_models.py` will result in the following error message:

```shell
File "/opt/homebrew/Caskroom/miniconda/base/envs/ldm/lib/python3.10/site-packages/basicsr/utils/img_process_util.py", line 1, in <module>
    import cv2
ImportError: dlopen(/opt/homebrew/Caskroom/miniconda/base/envs/ldm/lib/python3.10/site-packages/cv2.cpython-310-darwin.so, 0x0002): Library not loaded: @rpath/libopenh264.6.dylib
  Referenced from: <815C7689-BED4-3214-B070-7F78BCED3B68> /opt/homebrew/Caskroom/miniconda/base/envs/ldm/lib/libavcodec.58.134.100.dylib
  Reason: tried: '/opt/homebrew/Caskroom/miniconda/base/envs/ldm/lib/libopenh264.6.dylib' (no such file)
```

**To Reproduce**
1. Follow installation instructions on M1 / Apple Silicon Mac (running macOS 13)
2. Run `python scripts/preload_models.py`

**Expected behavior**
OpenCV to be able to run. It is used by the `python scripts/preload_models.py` script (and elsewhere, I suspect).

**Screenshots**
N/A

**Additional context**
Will submit a PR to `environment-mac.yml` to address.

**Comment by timcassidykoverse** [comment]
This fix worked for me

**Comment by johnpenny** [comment]
Had this issue. Committed fix worked.
