### ISSUE TITLE
Init image is not fitted correctly

### ISSUE THREAD

**Issue by spezialspezial** [invoke-ai/InvokeAI#795]
**Describe the bug**
I think _load_img is not completely working as expected. First it stretches the image and other than that it does not work by contract, fitting inside the target resolution box

image size: 896x640
target resolution: 768x384
result: 768x512

>> loaded input image of size 896x640
>> image will be resized to fit inside a box 768x384 in size.
>> after adjusting image dimensions to be multiples of 64, init image is 768x512
<PIL.Image.Image image mode=RGB size=768x512 at 0x7F9E16AFCF10>

I haven't looked at the implementation very thoroughly but I would first scale fitting inside the box (where target resolution is a multiple of 64) and then crop anything that is not a multiple of 64 after the scale

**Expected behavior**
Result should fit target resolution

**Comment by daveschumaker** [comment]
Were you able to resolve this issue (with custom code or something else)? I'm encountering this problem as well.

**Comment by daveschumaker** [comment]
Side note: A way I've gotten around this issue is to create an init_img of the desired size first.

e.g., if I want a 768 x 512 image and my source material is something like 600 x 600, I open up Gimp for my desired image size, paste my desired image as a new layer and resize as appropriate.

**Comment by spezialspezial** [comment]
Hi, sorry for the late reply, 
no, didn't really find a good resolve. I'm doing it like you, resizing myself and saving to disk. I think there might be an option soon to supply an image object, so one could resize to taste without io operation.
