### ISSUE TITLE
Add delete option to gallery

### ISSUE THREAD

**Issue by lalalune** [invoke-ai/InvokeAI#808]
**Is your feature request related to a problem? Please describe.**
Right now it seems like every image that gets generated stays there. It'd be nice to be able to delete and curate the gallery a bit.

**Describe the solution you'd like**
A delete button that removes images which are not good.

Could build upon the work here: https://github.com/invoke-ai/InvokeAI/pull/807

**Comment by psychedelicious** [comment]
Hi @lalalune , 
If you are using the new UI, there are these delete buttons:
<img width="1512" alt="Screen Shot 2022-09-26 at 15 07 36" src="https://user-images.githubusercontent.com/4822129/192198013-cbb2bb16-1d7a-4c64-b5b5-9205621bb3f2.png">

If you are not using the new UI, I'm not sure if we will plan to add them bc the new UI will replace it soon.
