### ISSUE TITLE
Masking features in webUI fór inpainting

### ISSUE THREAD

**Issue by ioma8** [invoke-ai/InvokeAI#812]
I am frontend specialist myself. Would it be ok if I created a merge request where (in new webUI) there would be button to open popup with simple brush style editor, where you would directly create the inpainting transparency mask right in the browser after uploading the initial image? Any ideas?

@lstein

**Comment by JakeHL** [comment]
Do you have a fork with this feature currently? I also started work doing something similar but I've not got very far.

**Comment by ioma8** [comment]
@JakeHL not yet - if you got some fork with work in progress and want to pass it on to me, could you send a link?

**Comment by JakeHL** [comment]
If I get it to a spot where it's worth sharing I'll update here and make a PR.

**Comment by psychedelicious** [comment]
That's very helpful ioma8, would welcome a PR.
