### ISSUE TITLE
[New UI] Exception thrown when click on the Generate button

### ISSUE THREAD

**Issue by burakkurkcu** [invoke-ai/InvokeAI#813]
**Describe your environment**
- GPU: mps
- VRAM: 16GB M1 Pro
- CPU arch: arm
- OS: macOS
- Python: miniconda
- Branch: development
- Commit: Merge: 4247e75 61b19d4 Merge branch 'development' into patch-1

**Describe the bug**

When you run to python backend/server.py for the new UI it runs successfully on localhost:9090, but when you get on the site and enter a prompt then click Generate, nothing happens and it throws exception below on the console:

Here is the full log of the process I described above:

```
(ldm) burakkurkcu@Buraks-MacBook-Pro stable-diffusion % python backend/server.py
* Initializing, be patient...

>> GFPGAN Initialized
>> CodeFormer Initialized
>> ESRGAN Initialized
>> Loading model from models/ldm/stable-diffusion-v1/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
>> Using more accurate float32 precision
>> Model loaded in 10.97s
>> Setting Sampler to k_lms
>> Starting server at http://localhost:9090
>> Latest images requested
>> System config requested
>> System config requested
>> Page 1 of images requested (page size 50 offset 0)
>> Image generation requested: {'prompt': 'blade runner istanbul', 'iterations': 1, 'steps': 50, 'cfg_scale': 7.5, 'height': 512, 'width': 512, 'sampler_name': 'k_lms', 'seed': 3035487579, 'seamless': False, 'progress_images': False, 'variation_amount': 0}
ESRGAN parameters: False
GFPGAN parameters: False
/Users/burakkurkcu/stable-diffusion/ldm/modules/embedding_manager.py:155: UserWarning: The operator 'aten::nonzero' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at  /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1659484612588/work/aten/src/ATen/mps/MPSFallback.mm:11.)
  placeholder_idx = torch.where(


Traceback (most recent call last):
  File "/Users/burakkurkcu/stable-diffusion/backend/server.py", line 792, in generate_images
    generate.prompt2image(
  File "/Users/burakkurkcu/stable-diffusion/ldm/generate.py", line 407, in prompt2image
    generator = self._make_txt2img()
  File "/Users/burakkurkcu/stable-diffusion/ldm/generate.py", line 655, in _make_txt2img
    self.generators['txt2img'].free_gpu_mem = self.free_gpu_mem
AttributeError: 'Generate' object has no attribute 'free_gpu_mem'
```

**To Reproduce**
1. Get into the repo folder (ex. "stable-diffusion" folder for me at home directory)
2. Pull the referenced commit on development (at this time of writing, it's latest commit on development branch)
3. run "conda activate ldm" to activate ldm environment
4. run "python backend/server.py" to get the new UI running at localhost:9090
5. go over at localhost:9090, enter a prompt and click the Generate button
6. see the error

**Expected behavior**
It should generate image like the old ui generates successfully.

**Additional context**
I discussed this bug on discord with @psychedelicious, and it seems broken on his side as well.

**Comment by wbecher** [comment]
I've getting the same error, I think it have something to do with that commit: https://github.com/invoke-ai/InvokeAI/commit/485fe67c92f1ab6be3c96c9d7da20c2c9ebb1d7b

**Comment by 19wolf** [comment]
Reverting just that commit fixed it for me `git revert 485fe67c92f1ab6be3c96c9d7da20c2c9ebb1d7b`

**Comment by HugoSega** [comment]
> Reverting just that commit fixed it for me `git revert 485fe67c92f1ab6be3c96c9d7da20c2c9ebb1d7b`

fatal: not a git repository (or any of the parent directories): .git

**Comment by holstvoogd** [comment]
It is due to Generate having a new option free_gpu_mem, it is settable via an argument for dream.py, but not added to the server.

as a work-around i added `generate.free_gpu_mem = False` backend/server.py, line 151
It ought to be passed from an argument as it is with dream.py, I can make a PR for that tomorrow!

**Comment by lstein** [comment]
This is now fixed in dev. My apologies, but I was sight-seeing today and only checked back now.

**Comment by wbecher** [comment]
Hi @lstein, thank you very much. Can you link here the commit that fixes this problem? I've already ran `git pull` on my development branch, but cannot get to work...

**Comment by 19wolf** [comment]
Looks like it's in this branch: https://github.com/invoke-ai/InvokeAI/commits/improve-metadata-retrieval

**Comment by wbecher** [comment]
This is solved now!
