### ISSUE TITLE
I can"t set the environment-mac yaml, it"s always terminated with an unknown error.

### ISSUE THREAD

**Issue by TroySeins** [invoke-ai/InvokeAI#821]
**Describe your environment**
- GPU: [cuda/amd/mps/cpu] Apple M1Ultra64
- VRAM: [if known] 128GB
- CPU arch: [x86/arm] M1 Ultra
- OS: [Linux/Windows/macOS] 12.5
- Python: [Anaconda/miniconda/miniforge/pyenv/other (explain)] miniconda3
- Branch: [if `git status` says anything other than "On branch main" paste it here]
- Commit: [run `git show` and paste the line that starts with "Merge" here]

**Describe the bug**
When I run PIP_EXISTS_ACTION=w CONDA_SUBDIR=osx-arm64  conda env create  -f environment-mac.yaml  && conda activate ldm I"ll get:

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=root
                CONDA_EXE=/Users/lxg/.pyenv/versions/anaconda3-2022.05/bin/conda
             CONDA_PREFIX=/Users/lxg/.pyenv/versions/anaconda3-2022.05
           CONDA_PREFIX_1=/Users/lxg/miniconda
    CONDA_PROMPT_MODIFIER=(root)
         CONDA_PYTHON_EXE=/Users/lxg/.pyenv/versions/anaconda3-2022.05/bin/python
               CONDA_ROOT=/Users/lxg/.pyenv/versions/anaconda3-2022.05
              CONDA_SHLVL=2
             CONDA_SUBDIR=osx-arm64
           CURL_CA_BUNDLE=<not set>
                 INFOPATH=/opt/homebrew/share/info:
                  MANPATH=/opt/homebrew/share/man::
                     PATH=/Users/lxg/.pyenv/versions/anaconda3-2022.05/bin:/Users/lxg/.pyenv/shi
                          ms:/Users/lxg/miniconda/envs/ldm/bin:/Users/lxg/miniconda/condabin:/op
                          t/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sb
                          in:/sbin:/Users/lxg/.cargo/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /Users/lxg/.pyenv/versions/anaconda3-2022.05
            shell level : 2
       user config file : /Users/lxg/.condarc
 populated config files : 
          conda version : 22.9.0
    conda-build version : 3.21.9
         python version : 3.9.12.final.0
       virtual packages : __osx=12.5=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/lxg/.pyenv/versions/anaconda3-2022.05  (writable)
      conda av data dir : /Users/lxg/.pyenv/versions/anaconda3-2022.05/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/lxg/.pyenv/versions/anaconda3-2022.05/pkgs
                          /Users/lxg/.conda/pkgs
       envs directories : /Users/lxg/.pyenv/versions/anaconda3-2022.05/envs
                          /Users/lxg/.conda/envs
               platform : osx-arm64
             user-agent : conda/22.9.0 requests/2.27.1 CPython/3.9.12 Darwin/21.6.0 OSX/12.5
                UID:GID : 501:20
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

**To Reproduce**

**Expected behavior**
Expected to setup the environment name, variable and activates the environment called ldm.

**Screenshots**

**Additional context**

**Comment by psychedelicious** [comment]
Hi @TroySeins , we need to know which branch/commit you are working from. When you run `git show` in the terminal, there will be a line that looks like this: `commit 28951da46e0410e9ed4e962cd6da98e3aa852b7d`

Please paste that line and we will be able to tell what version of the repo you are using.

**Comment by TroySeins** [comment]
Thx @psychedelicious , here it is:
commit d87bd29a6862996d8a0980c1343b6f0d4eb718b4

**Comment by lstein** [comment]
Any progress on this?

**Comment by psychedelicious** [comment]
@lstein @TroySeins Sorry for the delay, I have checked out the repo at the commit you provided (`HEAD detached at d87bd29`) and am able to create an environment from that and generate images with no issues. I don't think the issue is on our end.

There may be an issue with your conda setup. Unfortunately I'm not sure what troubleshooting steps are appropriate here - I suppose reinstalling conda is a start, but I'm not sure how best to do that even. I'm tagging a couple others for guidance. @tildebyte

**Comment by tildebyte** [comment]
Apologies, but my Mac skillz have long since faded. All I can offer is to delete the virtual environment and everything related to miniconda and try again from scratch.

**Comment by R-Josef** [comment]
Are you using v2RayN or some other proxy/VPN? v2rayN cause pip can not connect to net, see https://github.com/2dust/v2rayN/issues/1315. I used have similar problem, then i turned v2rayN off, and it works well now, hope this will help for you.
