### ISSUE TITLE
last_print_t error!

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#824]
I don't have much to go with but once in a while, I get this error in a middle of a text2image sequence:

Traceback (most recent call last):
  File "\stable-diffusion\envs\ldm\lib\site-packages\tqdm\std.py", line 1162, in __del__
    self.close()
  File "\stable-diffusion\envs\ldm\lib\site-packages\tqdm\std.py", line 1291, in close
    if self.last_print_t < self.start_t + self.delay:
AttributeError: 'tqdm_asyncio' object has no attribute 'last_print_t'
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='cp1252'>
OSError: [Errno 22] Invalid argument

**Comment by lstein** [comment]
See if you can find a formula to reproduce the error. I've not seen this one.

**Comment by raday-divergent** [comment]
Error may be caused by a sys.stdout.close() before the tdqm.
