### ISSUE TITLE
What are the valid and useful ranges for each parameter?

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#830]
I'd like to have a table that shows each parameter for txt2img, img2img, gfpgan, etc along with both the valid ranges and most commonly used ranges for each.

For both valid and useful ranges:
- Minimum / exclusive minimum
- Maximum / exclusive maximum
- Integer / float / step (e.g. width must be multiples of 64)
- One-of-a-list type parameters (e.g. sampler)

**Comment by lstein** [comment]
Yah, I hear you. I need to return to my original programme of creating an API guide. Will do.
