### ISSUE TITLE
Add a "Run in Colab" button

### ISSUE THREAD

**Issue by krummrey** [invoke-ai/InvokeAI#833]
Add a "Run in Colab" button so that it is even easier to try out Invoke-AI

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/invoke-ai/InvokeAI/blob/main/notebooks/Stable_Diffusion_AI_Notebook.ipynb)

`[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/invoke-ai/InvokeAI/blob/main/notebooks/Stable_Diffusion_AI_Notebook.ipynb)`

The Notebokk is broken right now. Needs fixing the current paths. I don't know how to do pull requests. Someone needs to change all the references to the old lstein repo name to the new InvokeAI.

Then dream.py works. Textual inversion doesn't and just quits with a `killed` notice

**Comment by lstein** [comment]
Textual inversion is dying for me with a SIGKILL, as well.

**Comment by lstein** [comment]
Thanks for the suggestion. I have just updated the development branch with the Colab badge, and fixed the notebook to run.
