### ISSUE TITLE
WEB UI on COLAB

### ISSUE THREAD

**Issue by jedidiahgamaliel** [invoke-ai/InvokeAI#838]
Is the WebUI working on Google Colab? My browser refuses to connect when I open the host address. Sorry, I'm a newbie.

**Comment by tildebyte** [comment]
Sadly it's unsupported, and technically a violation of Colab T.O.S (running a server). There are workarounds, but for obvious reasons we won't discuss them here.

**Comment by jedidiahgamaliel** [comment]
> 

Thank you for answering. Now, I won't be trying to find a fix that is not available.
