### ISSUE TITLE
Textual Inversion Training FileNotFoundError

### ISSUE THREAD

**Issue by DoLife** [invoke-ai/InvokeAI#839]
**Describe your environment**
- GPU: CUDA - RTX3070
- VRAM: [if known]
- CPU arch: [x86/arm]
- OS: [Windows 10]
- Python: [Anaconda]
- Branch: [On branch main]

**Describe the bug**
FileNotFoundError 

**To Reproduce**
python main.py \ --base configs/stable-diffusion/v1-finetune.yaml \ -t true \ --actual_resume models/ldm/stable-diffusion/model.ckpt \ -n demi \ --gpus 1, \ --data_root /training_data/key \ --init_word ? \ --no-test

**Expected behavior**
Start Training session

**Screenshots**

**Additional context**
Can`t understand what file it is not finding or hat path is not specified.
I believe the path is correct for where it should find the images to train on --data_root /training_data/key

It seems the problem lies with OmegaConf package, did redownload it, did and update, nothing work.
[https://pastebin.com/is9X78WJ](https://pastebin.com/is9X78WJ)

**Comment by lstein** [comment]
Do you really have the training data located in the root of the filesystem?

**Comment by DoLife** [comment]
This is the directory as I understand what root implies 
This is the directory of the installation as per windows
C:\Diffusion\InvokeAI
Invokeai is the root correct ?

This is the directory under the root where the training files are.
/training_data/key

Or do I misunderstand the meaning of root?

**Comment by DoLife** [comment]
Hi, I solved the problem. My path was incorrect to the model file.
