### ISSUE TITLE
Integrate "Hires Fix" from AUTOMATIC1111 to generate >512px images without repeating patterns

### ISSUE THREAD

**Issue by n00mkrad** [invoke-ai/InvokeAI#840]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features#highres-fix

Not sure how exactly it works, but it seems to allow >512x512 resolutions without repeating patterns.

It seems to work somewhat similarly to Embiggen, but way faster, easier to use, and more reliable.

**Comment by lstein** [comment]
How does it compare to real-esrgan? The new version of this tool seems plenty fast and good.

**Comment by n00mkrad** [comment]
> How does it compare to real-esrgan? The new version of this tool seems plenty fast and good.

It is not an upscaler in the traditional sense from what I understand, it actually generates more details.

RealESRGAN has a strong tendency to remove textures or oversharpen things.

**Comment by hipsterusername** [comment]
It sounds like this is a sequencing feature - 
“ partially render your image at lower resolution, upscale it, and then add details at high resolution”.

**Comment by netsvetaev** [comment]
Is this different from img2imghd / Gobig?

**Comment by ArDiouscuros** [comment]
> Is this different from img2imghd / Gobig?

I am probably missing something, what is that? Is it a feature of InvokeAI? How could I run it from cli?

**Comment by netsvetaev** [comment]
> > Is this different from img2imghd / Gobig?
> 
> I am probably missing something, what is that? Is it a feature of InvokeAI? How could I run it from cli? P.S. I see now that it is probably called Embiggen in our repo. Difference is - do not split generated image to the tiles, and do not convert from latent space and back. Just calculate the size of initial picture with the same ratio as requested, but limited to 512x512 surface. Interpolate it in latent space to requested size, and run sampler over it as in img2img.

This https://github.com/lowfuel/progrock-stable#gobig-what-it-is-and-how-to-use-it
Or this https://github.com/jquesnelle/txt2imghd 
Or this https://github.com/invoke-ai/InvokeAI/pull/437

**Comment by lstein** [comment]
Thanks for the heads up. I'll have to look into this more carefully because
I'm not sure how to make the image larger in latent space without
increasing the VRAM memory requirements proportionately. Can you confirm
that the VRAM requirements for "HiRes fix" are lower than generating a
1280x768 image directly?

If I've misunderstood and you do need the same amount of VRAM for the HiRes
fix as you would for any 1280x768 image, then I understand how to implement
this.

**Comment by PutUsernameHere** [comment]
This is based on what I observed in windows task manager so it's not too precise. This is also the GPU I use for display so its inclusive of other stuff running:
When HiRes fix is enabled for 1280x768 and latent space is disabled, I saw 7gb during the smaller image, and 10.2 in the main pass.
When latent space is enabled, it was 7gb again in the smaller image and 10.2 again in the main pass.
Without the HiRes setting enabled, it was also 10.2gb, so unless there is a VERY brief spike in VRAM usage, then it seems to have no effect.

**Comment by michaelezra** [comment]
"New --hires option on invoke>" does not seem to work on the command line in v2.0.0
python3 ./scripts/invoke.py --web --hires

Is it supposed to be used differently?

**Comment by hipsterusername** [comment]
Yes - it’s a flag for individual invocations on the CLI

so you would add it to a CLI prompt, and then it would utilize that process during generation.

A flag will be in WebUI soon - keep track of  #987

**Comment by michaelezra** [comment]
Thank you for the explanation, just tried and it definitely helps to avoid multiplication of subjects in the image. Looking forward to the WebUI option!
