### ISSUE TITLE
Request: Write generation date and time into EXIF metadata

### ISSUE THREAD

**Issue by timdesrochers** [invoke-ai/InvokeAI#851]
In cases where the filesystem being written to does not support DateCreated or similar file information, there is little clue as to when the image was generated. 

It would be helpful, when organizing batches of images afterwards, to be able to sort by generation date and time. 

Even better would be for all of this metadata to wind up in the standard EXIF fields for compatibility with other programs. "DateTimeOriginal", "Software", "Caption"... I've been running a script to copy the Dream metadata into the Caption EXIF for better compatibility.

**Comment by psychedelicious** [comment]
During the metadata RFC #266 it was decided we need to put the metadata where it is now. I believe the reasons are:
- You can't put structured metadata into caption (at least not legally)
- There are size limits for the standard fields
- We don't want to prevent users from adding their own captions

Regarding the standard EXIF fields, that sounds like a good idea to me.

**Comment by tildebyte** [comment]
@timdesrochers;

> it would be useful to allow for custom filename prefixes/suffixes on prompts (at least for CLI).

Note the similar `--prompt_as_dir` in [features/CLI.md](https://github.com/invoke-ai/InvokeAI/blob/development/docs/features/CLI.md) - not *exactly* what you're looking for, but...

**Comment by psychedelicious** [comment]
> Beyond the date/time, though, perhaps it would be useful to allow for custom filename prefixes/suffixes on prompts (at least for CLI).

that's a great idea, I think it makes sense for all clients of the back end.

**Comment by psychedelicious** [comment]
@timdesrochers , this is still planned but on the backburner. 

I thought all OSes provide a modified timestamp (e.g. what `os.path.getmtime()` gives you), but it sounds like the system you are using does not... Can you please confirm that this file attribute is not present on your system?

**Comment by psychedelicious** [comment]
We now have a db to manage images and the image records include time stamps.
