### ISSUE TITLE
requirements-colab.txt not found

### ISSUE THREAD

**Issue by kitsune-exe** [invoke-ai/InvokeAI#863]
**Describe your environment**
Google Colab with the latest version of colab notebook (1.13)
https://github.com/invoke-ai/InvokeAI/blob/main/docs/features/OTHER.md#google-colab

**Describe the bug**
When executing the command`!wget https://raw.githubusercontent.com/lstein/stable-diffusion/development/requirements-colab.txt`, the file was not found (404).

**To Reproduce**
Simply run the colab notebook file.

**Screenshots**
![截圖 2022-09-30 下午5 36 05](https://user-images.githubusercontent.com/28575110/193216791-4deff259-f9d2-4dcd-9a3d-96ff0ac0c5c7.png)

**Comment by lstein** [comment]
The repository name needs fixing. It’s no longer under lstein. Change the line to point to invoke-AU/InvokeAI.
