### ISSUE TITLE
Request: Brace expansion in prompts

### ISSUE THREAD

**Issue by timdesrochers** [invoke-ai/InvokeAI#864]
I like to set things up to generate batches while I'm working, sleeping, or doing anything other than sitting at the computer. Generating txt files for prompts can be a little more labor intensive than ideal.

Would it be possible to implement brace expansion in CLI prompts? For example:
``` dream> an astronaut riding a horse {at the mall, in a snowstorm, at the beach, on a football field, at the Battle of Gettysburg}``` etc. 

This would make it much easier to set SD up to generate a much wider variety of images than is possible with the simple -v flag. 

Ideally one could choose the order of generation, too, when -n > 1. For example if -n=3:

Linear: 
```{mall, storm, beach, football, battle} --> {mall 1, 2, 3; storm 1, 2, 3; beach 1; 2; 3; [...]```

Round-robin[?]: 
```{mall, storm, beach} --> {mall 1, storm 1, beach 1; mall 2, storm 2, beach 2; [...]```

Does this make sense?

**Comment by RobertBolender** [comment]
Some earlier discussion: https://github.com/invoke-ai/InvokeAI/discussions/473

**Comment by damian0815** [comment]
hi, i'm new to SD and AI/ML in general :wave: but i just wanted to say that this sort of thing suggests a blocking HTTP UI. on a local branch i've been hacking around with `backend/server.py`, and one of the first things i did was add a flask route `/dream` that takes a json string as `POST` and then feeds it to the same generator that the backend is using:
```
@app.route("/dream", methods=["POST"])
def dream():
    data = json.loads(request.data)
    # augment JSON keys so they're in the format the generate_images() expects
    if "iterations" not in data:
        data["iterations"] = 1
    if "progress_images" not in data:
        data["progress_images"] = False
    if data["prompt"] is dict:
        print("multiple weights not supported, use single string prompt")
        data["prompt"] = data["prompt"]["prompt"]
    if "init_image_path" in data:
        data["init_img"] = data["init_image_path"]
    if "sampler_name" not in data:
        data["sampler_name"] = data["sampler"] if "sampler" in data else "k_euler"
    generation_parameters = data
    esrgan_parameters = None
    gfpgan_parameters = None
    try:
        generate_images(generation_parameters=generation_parameters, esrgan_parameters=esrgan_parameters, gfpgan_parameters=gfpgan_parameters)
    except Exception as e:
        print("failed to generate image:", e)
        return "fail"

    return "ok"
```

then it's pretty easy to setup up a `for` loop on the terminal that makes `curl` requests one by one. relying on the OS's built-in script programming always seems smarter to me than trying to build a fancy parsing language into the core application.

**Comment by lstein** [comment]
The Python API is actually very easy to learn. You can generate images with about three lines of code. See the examples in ldm/generate.py

**Comment by damian0815** [comment]
you're right, it is straightforward to use the python api directly. two things make a HTTP API more convenient for me though. * the first is batched remote invocations. it's easier to make a bash `for` loop on my mac laptop than to ssh into my windows CUDA machine and hack the python with vim or something. 
* the second is quick iterations. with a client/server pattern like this i can load the model once and then quickly iterate all day. if i have to spin up a whole python session and load the model each time, it puts a drag on creativity.

**Comment by Millu** [comment]
Closing this as the 2.x.x CLI has been deprecated in favor of the invoke-nodes-cli. 

Brace expansion has been implemented in the WebUI
