### ISSUE TITLE
Implement on-the-fly model merging/weighting

### ISSUE THREAD

**Issue by n00mkrad** [invoke-ai/InvokeAI#865]
**Is your feature request related to a problem? Please describe.**
Model merging is possible and relatively fast, however it takes up a lot of disk space especially when experimenting.

**Describe the solution you'd like**
As far as I know, model merging can be done completely on-the-fly (in RAM). This would be a much nicer solution and saves disk space.

**Additional context**
Reference implementation of model merging:
https://gist.github.com/n00mkrad/c471012904f2936d0ec7c2bdfde01652

**Comment by lstein** [comment]
Looks very straightforward. Are there any public model repositories on which I could test the code?

**Comment by Millu** [comment]
Closing as this has been addressed in 3.0 via the Model Manager
