### ISSUE TITLE
[WebUI] "[IP] is not an accepted origin"

### ISSUE THREAD

**Issue by 19wolf** [invoke-ai/InvokeAI#867]
**Describe your environment**
- GPU: mps
- VRAM: [if known]
- CPU arch: arm
- OS: macOS
- Python: [Anaconda/miniconda/miniforge/pyenv/other (explain)]
- Branch: development
- Commit: commit 779422d01b848e5643a5d8727e5568002b936937 (HEAD -> development, origin/development)
- Merge: f8bd1e9 38a9f72

**Describe the bug**
Cannot access the WebUI from local network when running from `scripts/dream.py --host=0.0.0.0` but it does work when running from `backend/server.py --host=0.0.0.0`

**Comment by psychedelicious** [comment]
Hi @19wolf , 
- Guessing you are not running `python scripts/dream.py --host=0.0.0.0`  but actually running `python scripts/dream.py --web --host=0.0.0.0`, right?
- If you are attempting to access from another device on local network, you need to add the IP of the host as an allowed origin. So if the local network IP of the server is `192.168.1.123`, you'd run this `python scripts/dream.py --web --host=0.0.0.0 --cors http://192.168.1.123:9090` and should then be able to access the app from any machine on the local network.

**Comment by 19wolf** [comment]
1. Yeah
2. That worked, thanks!

**Comment by psychedelicious** [comment]
Sweet, thanks for marking closed.

**Comment by 19wolf** [comment]
Of course. Needs a "not a bug" label
