### ISSUE TITLE
WebUI Quirks with Deleting

### ISSUE THREAD

**Issue by hipsterusername** [invoke-ai/InvokeAI#869]
**Describe your environment**
- Dev

**Describe the bug**
A few issues with deleting occur:
- Using the single file face correction (potentially upscale, although haven't tested extensively), followed by repeated image deletions, can result in the wrong context being passed into future single file face correction processes.
- When pagination occurs, deleting all images removes the 'load more' button, requiring a refresh to repopulate the gallery.

Issue 1
**To Reproduce**
- Use the single file fix face on a file
- Delete 3-5 other images. 
- Select a different image, and use the single file fix face button.
- Note that GFPGAN was run on an image other than the one selected.
**Expected behavior**
- The selected image is used for the GFPGAN action.

Issue 2
**To Reproduce**
- With >50 images in outputs folder, delete all previewed images.
- Note the `load more` button disappears and the "No images to display" message is displayed.
**Expected behavior**
- Either Load More is still actionable, or the next page is displayed automatically.

**Comment by psychedelicious** [comment]
I couldn't ever recreate the first issue, but the second should be fixed now. Is there still some work to do @hipsterusername ?

**Comment by hipsterusername** [comment]
This may have been fixed - 20 days is like an eternity. 😝 

I'm ok closing and if I run into it again I'll recreate issue!
