### ISSUE TITLE
A "just do more steps" option

### ISSUE THREAD

**Issue by whosawhatsis** [invoke-ai/InvokeAI#871]
I just got this running a day or two ago, so I haven't had a chance to try everything yet. I haven't played with img2img at all yet, but I haven't been able to find any indication that it can do something like this. If this option already exists and I just haven't found it, let me know.

What would be nice would be an option to select an image (ideally a folder full of images) and retrieve the prompt, seed, and other settings used from the EXIF data. Then, (ideally working from the existing image, but I can see how it might be more efficient to just start the image generation over) and run them again, with the ability to override some of the settings used.

The primary application for this would be to run a large number of generations using a small number of steps. You could then go through the folder and cull the images (at a minimum removing the ones with two faces and similar anatomy problems, as well as the all-black ones, but you might also select for things like composition, color palette, etc.), then run the successful ones with more steps to increase the quality. This would allow you to generate many more usable high-quality images in much less time. If working from images, you could also potentially fix some of these problems (extra limbs come to mind) using traditional photo editing software early enough in the process to save an otherwise perfect image before those breaking features are fully resolved.

You might also want to change other settings, like switching samplers, or of course changing the -G and -U options.

I bet I could get this to work with a little scripting of my own that invokes the existing dream script, but it seems useful enough to consider building in, and I'm sure you guys could make it work more efficiently than I would.

**Comment by 19wolf** [comment]
Are you thinking something similar to MidJourney's way of doing things? Where like you put in a prompt and it gives you four items to choose from to modify/enhance/enlarge/whatever?

**Comment by whosawhatsis** [comment]
Sort of. What I had in mind was more along the lines of for example, generating 500 images with only around 5-10 steps. Enough to see what kind of composition, color scheme, pose, etc. you will get, but not enough to fully resolve details. Then you select the ones from that set that might work, and run them through 50 more steps, plus GFPGAN and ESRGAN.

**Comment by 19wolf** [comment]
Well at the very least you can generate a bunch of images in the WebUI and then when you select it, click "use all", and it'll input the parameters it used to generate and you can then change the number of steps (and number of images to make).

**Comment by whosawhatsis** [comment]
That's cool. I hadn't figured out how to launch the web ui yet. Trying its "display in progress" option, I can see fairly early in the process that some images aren't going to work for me. What I'd like is a good way to run a bunch of generations to that point, then filter out the ones that I can tell won't work before continuing to process them to full quality.

**Comment by whosawhatsis** [comment]
I've been experimenting with `dream.py --web`, which presumably runs that. The development branch's webui is a big improvement. What I'm suggesting is very close to its "use all parameters" function, with the exception that I'd like to be able to pull those parameters from the exif data of an imported image, rather than using the log file.

This would even make it possible to download an image from a site like http://lexica.art and (assuming it was generated with a version of the software that saves the prompt in the exif data) start creating variations on it in ways that give you a lot of control that img2img doesn't.

The "use all parameters" function also doesn't help with the batch processing issue.

**Comment by 19wolf** [comment]
Are you perhaps looking for the images2prompt script? https://github.com/invoke-ai/InvokeAI/blob/development/scripts/images2prompt.py

**Comment by lstein** [comment]
Thanks for all the ideas. When the release is out I’ll design a script to do what you want. It’ll be command line though.
