### ISSUE TITLE
Web UI: Postprocessed images have 'unknown_seed' in the file name

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#883]
Web UI: Postprocessed images have 'unknown_seed' in the file name

**Comment by psychedelicious** [comment]
If a one-off upscale/face-correction is requested, the provided image's metadata isn't retained. Furthermore, the metadata format currently in use only provides a place for a single run of GFPGAN or ESRGAN, but we support arbitrary numbers of postprocessing steps.

This is not in line with the metadata RFC #689 , which proposed a 'postprocessing' attribute that contains a list of all postprocessing steps. I will refactor the metadata to work as the metadata RFC suggests.

We need to diverge to handle the case where an image doesn't have generation metadata, either because it was made before the spec or if it was just dropped into the app from an external source (something I want to support).

To that end, the 'type' field will have an additional possible value 'external' in addition to 'txt2img' and 'img2img'. This indicates the image wasn't generated within InvokeAI and won't have generation metadata, but can still have postprocessing metadata. 

This will all come out in the wash when we migrated to node-based processing, but we need to provide something that works for now.

**Comment by lstein** [comment]
Yeah, I haven’t Implemented that part of the metadata spec. I’d be happy to do so.

**Comment by psychedelicious** [comment]
@lstein Our metadata formats are different right now :/ because I needed more data for the web UI, and I couldn't make Args() works as needed with a dict. 

Once I update my handling maybe we can merge the two. Will need some changes to Args(), or maybe it should just be a separate Metadata module.

**Comment by psychedelicious** [comment]
This issue is resolved in #879
