### ISSUE TITLE
Mac M1 - Can't use HuggingFace Concept .bin files

### ISSUE THREAD

**Issue by twopiearr** [invoke-ai/InvokeAI#887]
**Describe your environment**
- GPU: Apple M1
- VRAM: 16 gigs RAM total in system
- CPU arch: arm
- OS: Mac OS 12.6
- Python: miniconda
- Branch: (new to this and unsure; installed 9/30/2022)
- Commit: (new to this and unsure; installed 9/30/2022)

**Describe the bug**
I have cloned 2 .bin concepts from the Hugging Face website and I believe invoked them correctly, but I get an error when attempting to load them.

**To Reproduce**
1. Created a "concepts" directory
2. cd into concepts
3. cloned the spider-gwen and cat-toy concepts
4. attempted to run with either library:  python scripts/dream.py --embedding_path concepts/cat-toy/learned_embeds.bin
5. After initializing, run fails with the following error:
* Initializing, be patient...

>> cuda not available, using device mps
>> Loading model from models/ldm/stable-diffusion-v1/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
>> Using slower but more accurate full-precision math (--full_precision)
>> Model loaded in 14.87s
Traceback (most recent call last):
  File "/Users/richpizor/stable-diffusion/scripts/dream.py", line 685, in <module>
    main()
  File "/Users/richpizor/stable-diffusion/scripts/dream.py", line 101, in main
    t2i.load_model()
  File "/Users/richpizor/stable-diffusion/ldm/generate.py", line 428, in load_model
    model.embedding_manager.load(
  File "/Users/richpizor/stable-diffusion/ldm/modules/embedding_manager.py", line 220, in load
    ckpt = torch.load(ckpt_path, map_location='cpu')
  File "/Users/richpizor/miniconda3/envs/ldm/lib/python3.10/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/richpizor/miniconda3/envs/ldm/lib/python3.10/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Expected behavior**
Invoke-AI runs with concept file loaded

**Additional context**
Identical results when attempting to load spider-gwen/learned_embeds.bin

**Comment by psychedelicious** [comment]
Double-check the size of your .bin files vs what is on the website. That error often occurs when you don't have the actual full file.

**Comment by twopiearr** [comment]
Huh - that resolved it. For some reason the .bin file that downloaded with the clone command was only 129 bytes. Any idea why that might happen?

**Comment by psychedelicious** [comment]
No clue, but it's happened to me a couple times - same file size if I recall. Really confusing!
