### ISSUE TITLE
我已经在intel架构平台的macbookpro上运行成功

### ISSUE THREAD

**Issue by bigplumtree** [invoke-ai/InvokeAI#896]
hi 我已经在intel架构平台的macbookpro上运行成功。我的MacBook Pro配置如下
```
MacBook Pro (16-inch, 2019)
2.3 GHz 八核Intel Core i9
16 GB 2667 MHz DDR4
AMD Radeon Pro 5500M 4 GB
Intel UHD Graphics 630 1536 MB
Monterey 12.6 (21G115)
```
> 中国大陆内的飞行员需要全程保持飞行状态，并设置为全局代理模式，大概消耗10gb流量

安装步骤需要改动如下：
- 在原教程中，miniconda是arm平台的，需要更改成x86-64，地址在下面。如果网络不好的话可以手动下载后直接/bin/bash安装
> # install miniconda (M1 arm64 version):
> curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh -o Miniconda3-latest-MacOSX-arm64.sh
> /bin/bash Miniconda3-latest-MacOSX-arm64.sh

**这个是x86平台的安装脚本**
https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh

- 还需要更改这个地方
> # install packages
> PIP_EXISTS_ACTION=w CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac.yaml
> conda activate ldm

**将    CONDA_SUBDIR=osx-arm64**
**更改为CONDA_SUBDIR=osx-64**

- 其他操作不需要更改，大多数问题都是网络导致，请各位飞行员检查好飞机状态

**Comment by psychedelicious** [comment]
Thanks for providing the needed changes. We will update the installation docs with separate instructions for Intel Macs. Also thanks for keeping note of the data usage of installation, we can add a note that the expected bandwidth is around 10GB (this roughly matches my disk usage).

**Comment by bigplumtree** [comment]
no thanks!
