### ISSUE TITLE
Real-ESRGAN upscale image input?

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#906]
Greetings,

Is there a way to upscale an existing image? Not having to go through txt2image or image2image.

Thank you,

**Comment by psychedelicious** [comment]
On the development branch (which will soon be the main branch), you can use the `!fix` command to do this:
```
dream> !fix /path/to/image/000200.12345.png -U 4 0.75
```

We'll have support for this in the web UI in the near future.

**Comment by psychedelicious** [comment]
> @psychedelicious also, I just added the images I want to upscale to the outputs folder, renamed them after ones I already have, and got them in the gallery after gui refresh :-)

Sneaky!

@beepopRUS

You'll need to pull in and checkout the `development` branch e.g. `git pull origin development` followed by `git checkout development`. The new features there will be released to the `main` branch in the coming days, so you could also wait for that. 

Note that the `development` branch is under very active development and things are not guaranteed to work.

Closing as resolved.
