### ISSUE TITLE
New WebUI - Generation queue/delayed batch processing 

### ISSUE THREAD

**Issue by griffwill** [invoke-ai/InvokeAI#908]
**Is your feature request related to a problem? Please describe.**
I find I am often using webUI to explore variation branches and vague prompts, so I am usually creating 3+ images a generation in a  MidJourney-esque workflow. This is fine, but I often see different branches I want to revisit. digging through past results can be difficult to find the specific image out of all the variations.  

**Describe the solution you'd like**
An optional Generate mode that will save all of the settings for the image generation, but added to a queue that could be executed at a later time (say the end of the day or when I have to work on other things) as one large batch process. This queue could use the average generation time to also give an approximate compute time for the queued images so generation can be managed.

This may also need a separate 'queue manager' view in the UI so an overflowing queue can be effectively managed in selected batches

**Additional context**
In my head, I see this as a dropdown option on the 'Generate'

**Comment by EricBintner** [comment]
Queued jobs are the most important feature request for me too.

**Comment by EivindArvesen** [comment]
Additionally, maybe having the option to "add to queue" once a batch is running would be great as well.
