### ISSUE TITLE
next/previous keyboard navigation in web ui

### ISSUE THREAD

**Issue by whosawhatsis** [invoke-ai/InvokeAI#918]
I've been using the development web ui, and it's really nice. One thing that is missing is an easy way to navigate to the next/previous image (rather than needing to click on them in sequence in the sidebar). On-screen buttons would be nice, but making it possible to use the keyboard (the arrow keys, for example) would be even more convenient.

**Comment by psychedelicious** [comment]
Buttons and hotkeys Implemented in #947

**Comment by whosawhatsis** [comment]
Works great, thanks!
