### ISSUE TITLE
Have samplers changed recently? Seeing different results

### ISSUE THREAD

**Issue by Any-Winter-4079** [invoke-ai/InvokeAI#920]
Looking at https://github.com/invoke-ai/InvokeAI/issues/917 I'm realising there has been some (major?) change in the behavior of the samplers recently (?).
`"mountain man" -s10 -S3254369738 -W512 -H384 -A"k_euler"`
His
<img width="508" alt="Screenshot 2022-10-04 at 20 58 58" src="https://user-images.githubusercontent.com/50542132/193903347-72219a80-6a98-4b12-ba2e-8c40afaa7e21.png">
Mine (just pulled latest changes from dev)
<img width="516" alt="Screenshot 2022-10-04 at 21 03 33" src="https://user-images.githubusercontent.com/50542132/193904130-01baf15e-d14b-489b-97b2-810c8514fa90.png">

I'm on Mac too.

If changes have indeed been introduced, have we tested / compared both options regarding output quality?

_Originally posted by @Any-Winter-4079 in https://github.com/invoke-ai/InvokeAI/issues/917#issuecomment-1267458284_

**Comment by damian0815** [comment]
oh i was confused by that too - got different outputs on my trusty GTX1060 and my Mac. i'm assuming it's a fp16 vs fp32 thing.

**Comment by Any-Winter-4079** [comment]
Cuda and mps have never been able to reproduce each other. But now it seems there have been changes between https://github.com/invoke-ai/InvokeAI/commit/2cbf1e6f4bc7176c010cfb0e613edc5fa2d88d8c and latest, so that it produces different results even for the same device type (at least for mps)

Do you mean between https://github.com/invoke-ai/InvokeAI/commit/2cbf1e6f4bc7176c010cfb0e613edc5fa2d88d8c and latest that you also get different results on cuda?

I'm not sure it's precision as I've always been `Using more accurate float32 precision` as far as I know

**Comment by damian0815** [comment]
Interesting - my Windows `server.py` says "using fast fp16 math" or something every time it starts up, the mac is always `float32`.

**Comment by psychedelicious** [comment]
there are two potentially reproducibility-affecting changes (copied from my comment [here](https://github.com/invoke-ai/InvokeAI/discussions/914#discussioncomment-3799287)):
- #902 (which is in response to #900) may be a factor given you used a k* sampler
- per @lstein , #878 changes the noise schedule, which makes results different. this also introduced the issues with low-strength img2img being all blurry-mud-soup-y

**Comment by Any-Winter-4079** [comment]
@damian0815 Here's some more details after some digging
https://github.com/invoke-ai/InvokeAI/discussions/914#discussioncomment-3799516

And here's the guide I wrote on sampler convergence https://github.com/invoke-ai/InvokeAI/blob/development/docs/help/SAMPLER_CONVERGENCE.md

**Comment by Any-Winter-4079** [comment]
Fixed now in https://github.com/invoke-ai/InvokeAI/pull/925
