### ISSUE TITLE
Request: WebUI - Add keyboard navigation/hotkeys

### ISSUE THREAD

**Issue by griffwill** [invoke-ai/InvokeAI#921]
After playing with the new WebUI, I'm finding navigation/continuous iterations can be a little time consuming. Hotkeys or keyboard shortcuts would be a great quality of life improvement, even if limited. 

Specific shortcuts that come to mind:
- Gallery/results navigation with arrow keys when in focus
- "Use seed" for current/selected image
- "Use All" for current/selected image
- "Generate/Invoke" hotkey
- "Cancel" hotkey
- Restore faces with current/default settings
- Upscale with current/default settings
- Delete current/selected image
- Show details for current/selected image (and bring focus to the details panel so arrow keys can be used to page up/down)
- Use current/selected image as img2img init
- hotkey/key combo to bring focus to prompt input field

**Comment by blessedcoolant** [comment]
I've implemented hotkeys in this branch. Test them out and tell me how they feel.
https://github.com/blessedcoolant/InvokeAI/tree/webui-hotkeys

**Hotkeys:**

Ctrl + Enter = Invoke
Shift + X = Cancel
S = Set Seed
A = Set Parameters
R = Restore Faces
U = Upscale Image
I = Show Metadata
Shift + I = Set Init Image
Del = Delete
Alt + A = Prompt Focus

There is a modal in the UI now that can help you with all the set hotkeys.

![firefox_0Hr2NVh1PA](https://user-images.githubusercontent.com/54517381/194230101-e0102066-7cbc-4aa3-ac6f-92b4ce8aeee8.png)

As for the gallery focus and scroll, I believe @psychedelicious is doing some work related to that. I didn't want to override that. I'll wait and see what he says.

**Comment by psychedelicious** [comment]
These features have all been implemented now.
