### ISSUE TITLE
Commit introduces file names incompatible with Windows systems

### ISSUE THREAD

**Issue by ArDiouscuros** [invoke-ai/InvokeAI#937]
In the commit 95c7742 : [95c7742](https://github.com/invoke-ai/InvokeAI/commit/95c7742c9cf321087e58cd9f51b60dcfb4c0d0cf) files with : in names were added. 

In is not possible to use in names on windows systems:
The following reserved characters:

< (less than)
> (greater than)
: (colon)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
* (asterisk)

As a result, I could not pull the changes and I think it could affect normal usage too.

**Comment by lstein** [comment]
Just fixed in b2cd98259d445490b65a79eda42aec9282ce9527 (tag 2.0.0-rc3)
