### ISSUE TITLE
Interactively load prompts from a file from the `dream>` prompt

### ISSUE THREAD

**Issue by damian0815** [invoke-ai/InvokeAI#938]
It would be super-handy to be able to do like

```
dream> --from_file /path/to/prompts.txt
```

(from within `dream.py`) and have them all rendered one by one!

**Comment by ArDiouscuros** [comment]
Was proposed here #882 as !replay command

**Comment by lstein** [comment]
It didn’t quite make it into the release candidate. Will appear in dev RSN.
