### ISSUE TITLE
Dark image after upscaling

### ISSUE THREAD

**Issue by ArDiouscuros** [invoke-ai/InvokeAI#939]
**Describe your environment**
- GPU: cuda, GTX 1660 Ti
- VRAM: 6 GB
- CPU arch: x86
- OS: [Windows]
- Python: [miniconda]

**Describe the bug**
Image after upscale with realesrgan is very dark.

**Additional context**
On my system it works if I set use_half_precision = False
Should we take over precision value from main program?

```
        if not torch.cuda.is_available():  # CPU or MPS on M1
            use_half_precision = False
        else:
            use_half_precision = True

    def load_esrgan_bg_upsampler(self):
        if not torch.cuda.is_available():  # CPU or MPS on M1
            use_half_precision = False
        else:
            use_half_precision = True
```

**Comment by lstein** [comment]
Which branch is this happening on?

**Comment by ArDiouscuros** [comment]
Found it during test of RC2 but it looks like the same general issue with my GTX 1660 and half precision.

**Comment by lstein** [comment]
Thanks. Looks like an easy fix.

**Comment by lstein** [comment]
Phooey. I omitted including the fix in rc4. I'll send you a comment when I make the relevant commit.

**Comment by lstein** [comment]
Ok, if you checkout `release-candidate-2` HEAD (not the tagged version), you'll find the proposed fix for the realesrgan issue.

**Comment by ArDiouscuros** [comment]
> Ok, if you checkout `release-candidate-2` HEAD (not the tagged version), you'll find the proposed fix for the realesrgan issue.

I am on commit 911c99f125b5e92a7e5bc9e36e185f473af07645 (HEAD -> release-candidate-2, upstream/release-candidate-2)
run command !fix 000403.1.png -U 4
Still have dark output:
![image](https://user-images.githubusercontent.com/72071512/194375268-a926e525-d723-447f-99e3-654d95484b0a.png)

Am I missing something? 
Started with command python ``` scripts\dream.py --free_gpu_mem ```
Autodetected full precision: >> Using more accurate float32 precision

**Comment by lstein** [comment]
I turns out to be a challenging problem to fix, but I will work on it when the release is out.

**Comment by H445** [comment]
Confirmed the same:

Describe your environment
GPU: cuda, GTX 1660 Ti
VRAM: 6 GB
CPU arch: x86
OS: [Windows]
Python: [anaconda]

Additional context
- Upscaling with DreamTextures in Blender (Based on Invoke) works correctly, tested with multiple image sizes. However they are dark when upscaled in InvokeAI

**Comment by BastienX8** [comment]
Similar issue here, images are very dark after upscale, except the bottom right corner for an unknown reason

**Describe your environment**
GPU: cuda, GTX 1660 super
VRAM: 6 GB
CPU arch: x86
OS: [Windows]
Python: [miniconda]

**Additional context**
Example output and the upscaled version :

![000008 2990360949](https://user-images.githubusercontent.com/67980966/199236708-6acc1052-7a81-48ad-bce4-32bdfaf51891.png)
![000008 2990360949 upscale](https://user-images.githubusercontent.com/67980966/199236731-0f1cbc4a-3870-4677-a016-5c3c1bbac1b5.png)

**Comment by MasterIO02** [comment]
Having the same issue here, also on a 1660 (super) with 6gb VRAM, running on Linux Mint. Installed InvokeAI using the bundled install script.

**Comment by lstein** [comment]
Have you tried changing between --precision="float16" vs --precision="float32" ?

**Comment by MasterIO02** [comment]
Changing to precision float16 just makes Invoker output black images, it seems it's an issue with this specific GPU that is fixable by using `--precision full --no-half`, it works on Automatic's webui but Invoker doesn't recognize those arguments.

**Comment by goodwin74** [comment]
> Changing to precision float16 just makes Invoker output black images, it seems it's an issue with this specific GPU that is fixable by using `--precision full --no-half`, it works on Automatic's webui but Invoker doesn't recognize those arguments.

I also have a GTX 1660 6gb installed(Windows platform). However, "Automatic" works successfully without any additional arguments. Including the "Upscale" function with the "realesrgan" model.
The problem with "Upscale" is observed only in InvokeAI.

**Comment by JohnyTesla** [comment]
I don't know if this helps, but there's a slight delay in "the darkening", image upscales normally and after a half a sec image gets dark.

**Comment by tomi0911** [comment]
I have a GTX 1660 super 6gb and the same issue. 
Anyone found a solution?

**Comment by noname9312** [comment]
Same for me. Are they any know fixes?

**Comment by JSK333** [comment]
I have this issue as well, 1660 Ti.  Does not happen with EasyDiffusion or A1111 installs.  As said above, seems like a need to allow for a command argument "--precision full --no-half" like is used with the others. Attached image rendered at 512x512 and upscaled 4x.
![000003 9a92eff2 4185472284 postprocessed](https://github.com/invoke-ai/InvokeAI/assets/115677238/83e925b9-de2e-43a0-ab80-06f8c12956a4)

**Comment by noname9312** [comment]
Why is it closed as completed? This bug is still there

**Comment by noname9312** [comment]
still the same bug in april 2024

**Comment by hsm207** [comment]
happens in Apple M1 max too (5.10.0dev4). Used to work in an earlier release
