### ISSUE TITLE
Bad input with treshold in UI

### ISSUE THREAD

**Issue by ioma8** [invoke-ai/InvokeAI#954]
**Describe your environment**
- Branch: development
- Commit: c7ccb9dacd35d2195315b079af84b772e6782f47

**Describe the bug**
The input for treshold is holds decimal value but is so small that it shows only the leading zero all the time, so I dont se the actual decimal value. See first screenshot. So maybe shorten the label to "Tresh." ?

Also related bug  - when I tried to read the docs (in dev branch), the link to visual demonstration returns "Page not found": 
https://github.com/invoke-ai/InvokeAI/blob/development/docs/features/OTHER.md#thresholding-and-perlin-noise-initialization-options. See second screenshot.

**Screenshots**
<img width="366" alt="image" src="https://user-images.githubusercontent.com/6624752/194372416-4ba2fe3f-342c-4f44-8ed4-18cd87350797.png">

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/6624752/194373152-89d3c6d1-a885-4ebe-a906-7a29eb3b03f9.png">

**Comment by blessedcoolant** [comment]
Yep. Known issue. I'm gonna fix it in bit. Need a couple of other PR's to go live first.

**Comment by blessedcoolant** [comment]
This is fixed in the latest rc build for the frontend.
