### ISSUE TITLE
Environment.yml has too old numpy version

### ISSUE THREAD

**Issue by GothaB** [invoke-ai/InvokeAI#962]
**Describe your environment**
- GPU: cuda
- VRAM: 12 GB
- CPU arch: x86
- OS: Windows
- Python: Anaconda + conda-pack
- Branch: release-candidate-2
- Commit: 82481a6f9c5a1cea291666503e8f056a7c6a10d4

**Describe the bug**
Running dream.py from a conda-pack version (which is like a fresh install) results in `ImportError: this version of pandas is incompatible with numpy < 1.20.3
your numpy version is 1.19.2.`
1.19.2 is also specified in the environment.yaml

Can be fixed by changing the numpy line in the environment.yaml is changed to `- numpy=1.20.3`.

**Comment by tildebyte** [comment]
@GothaB; I really don't know how to help with this, but for one thing, you should really update to the actual release 2

**Comment by GothaB** [comment]
What I wanted to say is:
The conda environment won't work on a clean system (= that has no previous python/numpy installs on it), because the environment.yaml sets the wrong numpy version as dependency. :) The dependency needs to be `numpy=1.20.3`.

I'll test it later again with the main branch, in case whatever needed the newer numpy version was removed. :3

**Comment by tildebyte** [comment]
> The conda environment won't work on a clean system (= that has no previous python/numpy installs on it), because the environment.yaml sets the wrong numpy version as dependency

:confounded:

**Comment by GothaB** [comment]
Stupid question: Does that maybe hint at a bigger problem?

Because apparently the scripts don't use the python/pytorch/etc from the environment, but any python/pytorch/etc that they find. And I guess the reason for an environment is that it deploys exactly the python/pytorch/etc that you want, and not use anything outside of it. :X

I think a lot of my users get problems from that. Errors are stuff like "cached model not found" (even though they are correctly deployed) or "pytorch cannot find cuda" (even though the libraries are correctly installed). I guess they got some old python/pytorch/etc installations flying around that the system finds first, but those are missing requirements.

**Comment by tildebyte** [comment]
Yeah, this torch thing is really worrisome because 1) We have no control over it (i.e. from inside a running script or what have you) 2) The *virtual environment* is supposed to handle that ***absolutely*** - this kind of "leakage" should **never** happen

**Comment by GothaB** [comment]
Atm, when I run my deployed environment (= it is packed with conda-pack), I already change some paths. I'm on Windows.

To be exact, my tool has to set two temporary environment paths:
`set "TRANSFORMERS_CACHE={Application.dataPath}/../ai_cache/huggingface/transformers"`
`set "TORCH_HOME={Application.dataPath}/../ai_cache/torch"`

And (most likely unrelated) I have to edit the paths in `E:\aiimages_112\aiimages_standalone\env\Lib\site-packages\easy_install.pth` (to fit whereever the user put the tool).

I already tried to also set other path variables of python/torch, but didn't have much luck yet. But I also didn't try much (because I didn't reproduce the bug on my system yet, so I always had to instruct a poor user that just wanted to use my one-click-installer q.q).

**Comment by psychedelicious** [comment]
We've changed the install/env setup enough from this issue that any problems here are no longer relevant.
