### ISSUE TITLE
Generation stopped working

### ISSUE THREAD

**Issue by ioma8** [invoke-ai/InvokeAI#970]
**Describe your environment**
- GPU: mps
- CPU arch: arm
- OS: macOS
- Branch: development
- Commit: 4f247a3672474bd9c46060bab6087dbf9e2531f3

**Describe the bug**
Generating just now produces noise for ddim sampler. See Screenshot for detailed parameters of the prompt.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/6624752/194511426-6a2877e0-6539-4a6a-8647-7dfadd84e52c.png">

**Comment by lstein** [comment]
This is fixed in current `development` and `release-candidate-2`
