### ISSUE TITLE
Missing CSS file in rc6?

### ISSUE THREAD

**Issue by ThatParticularSteveGraham** [invoke-ai/InvokeAI#975]
Apologies if I'm missing something, delurking on GitHub.

**Describe your environment**
- GPU: mps
- VRAM: M1 Pro
- CPU arch: arm
- OS: macOS
- Python: miniconda
- Branch: 2.0.0-rc6
- Commit: commit 9f34ddfcea021836c0f71584fdc04be00fb2cff7 (HEAD, tag: 2.0.0-rc6)

**Describe the bug**
Clean install of 2.0.0-rc6, Apparently missing a CSS asset, entire web UI appears in a single column

**To Reproduce**
1. New clone
2. Switch to 2.0.0-rc6
3. Install (following docs for macOS)
4. Run dream.py --web
5. Inspect site in browser (Safari & Edge so far)

**Expected behavior**
Web UI presented in 3 columns; fits in the browser window

**Screenshots**
<img width="1505" alt="image" src="https://user-images.githubusercontent.com/115261993/194583326-d7a6e7de-b44b-493d-b9d8-4ae86b0d4bee.png">

The UI was working for me on rc3.

**Comment by lstein** [comment]
Could you check rc7? If that doesn't solve the problem, try `release-candidate-2` HEAD. I just rebuilt the front end and that should resolve missing files.

**Comment by ThatParticularSteveGraham** [comment]
> Could you check rc7? If that doesn't solve the problem, try `release-candidate-2` HEAD. I just rebuilt the front end and that should resolve missing files.

Resolved! Did another clean checkout with rc7 - no issues this time.
