### ISSUE TITLE
[m1] [ti] textual inversion embedding loaded but * doesn't work

### ISSUE THREAD

**Issue by ppogorze** [invoke-ai/InvokeAI#980]
GPU: M1
CPU arch: arm
OS: MacOS
Python: miniconda
Branch: development / release-candidate-2
Commit: [b296933] / [3d7bc07]

`ugly-sonic.bin loaded:`
`>> Model loaded in 10.24s`
`Added terms: *, <ugly-sonic>`
`>> Setting Sampler to k_lms`

then:
`dream> photo of <ugly-sonic>`
produces:
`RuntimeError: Tensors must have same number of dimensions: got 2 and 1`
`>> Could not generate image.`

OR:
`dream> photo of *`
produces: photo of random guy.

the same for other models or styles from hugging face. bin size is correct.

**Comment by Any-Winter-4079** [comment]
It works for me.
`photo of <ugly-sonic>`
<img width="200" alt="Screenshot 2022-10-07 at 22 14 33" src="https://user-images.githubusercontent.com/50542132/194645717-ef4fc513-477a-43d5-bd8e-8f01e2c5b709.png">

**Comment by ppogorze** [comment]
ok @Any-Winter-4079  i will start from scratch. Testing right now...

**Comment by Any-Winter-4079** [comment]
CLI

**Comment by Any-Winter-4079** [comment]
@ppogorze does it work?
[uglysonic.bin.zip](https://github.com/invoke-ai/InvokeAI/files/9737384/uglysonic.bin.zip)

**Comment by ppogorze** [comment]
@Any-Winter-4079 same sh...
1. when I use web ui and type: photo of <ugly-sonic> = stuck on preparing...
2. cli = RuntimeError: Tensors must have same number of dimensions: got 2 and 1 >> Could not generate image.
3. PS. your sonic is not ugly ;) it's regular sonic (!) Is it working?

**Comment by Any-Winter-4079** [comment]
Oh, I just downloaded it from the website, suggested from someone here! Never knew it was not the ugly version.
If you point me to the url with your ugly sonic I can test it

**Comment by ppogorze** [comment]
@Any-Winter-4079 this will be more obvious: 
[https://huggingface.co/sd-concepts-library/cat-toy]

**Comment by Any-Winter-4079** [comment]
@ppogorze Sorry, long day. I did it so fast I forgot to load the embedding lol.
Yes, you are right.
In my bin it runs without error, but the output is not correct.
In your bin, it throws an error

**Comment by Any-Winter-4079** [comment]
I'm going to try with some trained concepts on my computer.

**Comment by Any-Winter-4079** [comment]
This functionality worked here https://github.com/invoke-ai/InvokeAI/issues/513#issuecomment-1244850160

**Comment by Any-Winter-4079** [comment]
Update: The embedding seems to work, because if I use the same seed from above without the embedding
`"a photo of <ugly-sonic>" -s 50 -S 1015307476 -W 512 -H 512 -C 7.5 -A k_lms`
I get the real sonic
<img width="150" alt="Screenshot 2022-10-08 at 01 07 55" src="https://user-images.githubusercontent.com/50542132/194673866-19674144-bc1a-4261-bf72-34aa32b1ef4a.png">

and not ugly sonic
<img width="150" alt="Screenshot 2022-10-08 at 01 08 02" src="https://user-images.githubusercontent.com/50542132/194673875-f8255a8f-0f76-4cab-a7ab-f362d2021107.png">

@lstein But there seems to be an error running a command with the embedding loaded.
```
new_embed_row = torch.cat(
RuntimeError: Tensors must have same number of dimensions: got 2 and 1
```

**Comment by Any-Winter-4079** [comment]
@ppogorze try setting `num_vectors_per_token: 1` in `v1-inference.yaml`
The behavior looked super weird, but I guess depending on the prompt (whether it detects e.g. `<cat-toy>` or `*`) it goes one route or another in `embedding_manager.py` and when using those concepts, it failed because num vectors did not match.

**Comment by Any-Winter-4079** [comment]
So the first fix seems to be `num_vectors_per_token: 1` in `v1-inference.yaml`
This seems to work.
<img width="200" alt="Screenshot 2022-10-08 at 01 32 14" src="https://user-images.githubusercontent.com/50542132/194675313-15206fbf-b15f-4200-8067-28aefb65a17f.png">
A second fix may be necessary, to get `*` to work.

**Comment by ppogorze** [comment]
Thank you guys, testing...

**Comment by ppogorze** [comment]
Works.

cat-toy
![000333 3969801327](https://user-images.githubusercontent.com/338572/194676684-d79fe5d2-eadc-426a-a8fd-1474eaa4be9f.png)

vs <cat-toy>
![000334 3969801327](https://user-images.githubusercontent.com/338572/194676687-747c1949-4de7-4cda-8195-818b46d7b9ad.png)

**Comment by Any-Winter-4079** [comment]
@lstein please include the fix in the release. Otherwise embeddings won't work on main.

**Comment by skurovec** [comment]
M1 Mac, 32GB

I looks like fix broke it for me.

```"a painting of a * as batmans joker" -s 50 -S 3673222724 -W 512 -H 512 -C 7.5 -A k_lms```

where * is my photo

produces random guy

When reverted ```num_vectors_per_token``` to 6 here am I again

**Comment by Any-Winter-4079** [comment]
Yes, the file should be manually edited depending on the `num_vectors_per_token` the concept was trained on. We changed back to 1 because it's more of a default value, but if you used 6 to train, you have to update to 6.

**Comment by skurovec** [comment]
interesting thing is, that I have trained on 1, but it is not working until I change it here to 6
