### ISSUE TITLE
training dies after first epoch (2.0.0-rc7)

### ISSUE THREAD

**Issue by rpfile** [invoke-ai/InvokeAI#984]
**Describe your environment**
- GPU: mps
- VRAM: 128GB unified
- CPU arch: arm
- OS: macOS
- Python: miniconda
- Branch: HEAD detached at 2.0.0-rc7
- Commit: commit 7a701506a4f1344d1d5125800da512407c5a03f5 (HEAD, tag: 2.0.0-rc7)

**Describe the bug**
training results in crash after first epoch with: 

AttributeError: 'DDIMSampler' object has no attribute 'ddim_timesteps'

```
| invoke-ai-dev-rc/InvokeAI/ldm/models/diffusion/sampler.py:397 in get_timesteps   │
│                                                                                                  │
│   394 │   │   ddim_timesteps are created in make_schedule(), and selects the portion of          │
│   395 │   │   timesteps that will be used for sampling, depending on the t_enc in img2img.       │
│   396 │   │   '''                                                                                │
│ ❱ 397 │   │   return self.ddim_timesteps[:ddim_steps]                                            │
│   398 │                                                                                          │
│   399 │   def q_sample(self,x0,ts):                                                              │
│   400 │   │   '''                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**To Reproduce**
1.  attempt to train an embedding

**Expected behavior**

training proceeds thru epochs making training and validation images.

**Screenshots**

**Additional context**

just looking around at the code it seems like make_schedule() might never be called. is there a way to switch samplers for training?

**Comment by rpfile** [comment]
also - i see this same error if i try to run txt2img.py

**Comment by lstein** [comment]
Could you post a full stack trace? This should be easy to fix.

Thanks!

**Comment by lstein** [comment]
Never mind. I've just pushed a commit that I think will fix the issue. Please check.

**Comment by rpfile** [comment]
thanks, i will update and check.

**Comment by skurovec** [comment]
I had same problem and https://github.com/invoke-ai/InvokeAI/commit/318eb35ea0d3f9aa30762b4dfa2368ae1ebbb0f3 fixed it

**Comment by rpfile** [comment]
yes, this appears to be fixed. thank you.
