### ISSUE TITLE
error: argument -t/--train: boolean value expected.

### ISSUE THREAD

**Issue by furkangercek** [invoke-ai/InvokeAI#992]
![image](https://user-images.githubusercontent.com/38816094/194704405-48518b06-81b5-40b5-bd16-d4f1fa9dcf8a.png)

**Comment by furkangercek** [comment]
even if I put -t true as a boolean value I get following error. 

C:\Users\Scy\Downloads\aiimages-win\stable-diffusion>py ./main.py --base ./configs/stable-diffusion/v1-finetune.yaml \                                            -t true \  --actual_resume ./models/ldm/stable-diffusion-v1/model.ckpt \ -n scyrindo \  --gpus 0, \ --data_root ./scyrindo_train \ -init_word 'scyrindo'

Global seed set to 23
Traceback (most recent call last):
  File "C:\Users\Scy\Downloads\aiimages-win\stable-diffusion\main.py", line 691, in <module>
    configs = [OmegaConf.load(cfg) for cfg in opt.base]
  File "C:\Users\Scy\Downloads\aiimages-win\stable-diffusion\main.py", line 691, in <listcomp>
    configs = [OmegaConf.load(cfg) for cfg in opt.base]
  File "C:\Users\Scy\AppData\Local\Programs\Python\Python310\lib\site-packages\omegaconf\omegaconf.py", line 183, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\'

**Comment by lstein** [comment]
`--train` (`-t`) doesn't take any arguments. It is a boolean flag.

Your issue is coming from the argument  `-b ./configs/stable-diffusion/v1-finetune.yaml`. This is not supposed to point to a file, but to a directory of config files, so I believe that `-b ./configs/stable-diffusion/` is what you intend.
