### ISSUE TITLE
Speculative UI feature: tool to visualize feature space in 2D

### ISSUE THREAD

**Issue by damian0815** [invoke-ai/InvokeAI#993]
It should be easy enough to collapse the 77x768 feature vector to a 2D vector (eg using PCA), meaning we could have a tool that visualizes the spatial relationship between the last N prompts on a 2D plane. This could be super helpful for testing out how prompt changes might alter the feature vector. 

It would need, accessible to the frontend: 

* a backend call that returned a 77x768 CLIP feature vector for a requested prompt, and
* a backend call that returned 2D vectors by doing eg PCA on a passed-in array of CLIP feature vectors

Needs research to figure out a) feasibility and b) best way to do it

**Comment by tildebyte** [comment]
Or maybe a 3D cube, to give an extra dimension? WebGL FTW...

**Comment by TheImunityGamer** [comment]
I'm new here but I'm interested in this. Do you know where I could find where the CLIP feature vectors for prompts are generated? Also, do you have any general tips? What files would someone add the backend calls in? Thanks.

**Comment by damian0815** [comment]
the high-level prompt → embeddings happens in `get_uc_and_c_and_ec()` in `conditioning.py`, which calls through to lower level functions in class `WeightedFrozenCLIPEmbedder` as well as its `forward()` method. have fun, this stuff is a deep dive :)
