### ISSUE TITLE
Greenlet ImportError on M1 Architecture ( incompatible architecture (have (x86_64), need (arm64e))

### ISSUE THREAD

**Issue by craftfortress** [invoke-ai/InvokeAI#994]
**Describe your environment**
- VRAM: [if known]
- CPU arch: [x86/arm]
- OS: [macOS]
- Python: [miniconda]
**Describe the bug**

**To Reproduce**
1. Pip Install

**Comment by Any-Winter-4079** [comment]
Is there a reason why you use `x86_64` and don't switch to `arm64e` ?

**Comment by Raymonf** [comment]
@craftfortress You probably have to install the proper miniconda, listed as "Miniconda3 macOS Apple M1 64-bit" and make sure Terminal isn't running in Rosetta 2 (the `arch` command should return `arm64`).

**Comment by rwade42** [comment]
I'm not sure if it's exactly the same issue or if I should file a new one, but I get this same error _after_ install when trying to run any of the scripts. Everything was working fine before the most recent update, and I've tried completely resetting conda, deleting the repo, recloning and following the install instructions from scratch.

VRAM: No idea, but have the M1 pro
CPU arch: arm (see terminal output)
OS: macOS
Python: miniconda

<img width="1057" alt="Screen Shot 2022-10-10 at 9 34 41 AM" src="https://user-images.githubusercontent.com/10729572/194913760-0006cc9e-bf1c-4c48-aa70-644510075018.png">

**Comment by rwade42** [comment]
I did see the issue below was closed, but uninstalling and reinstalling with conda both the tokenizer and greenlet libraries doesn't seem to work for me.

 https://github.com/invoke-ai/InvokeAI/issues/753

**Comment by craftfortress** [comment]
Yes it hasn’t worked for me either

**Comment by rwade42** [comment]
@craftfortress I spoke too soon, I found the issue for me by looking reading this: https://github.com/invoke-ai/InvokeAI/issues/730

`
Until I discovered that pip is quite agressive in caching. So it caches the build even if the architecture changed. Solution: pip cache purge. Or remove the whole cache directory which you find with pip cache info
`

So if you had it working before too, maybe your pip cache is also broke. I cleared it, deleted the conda env and recreated it and I'm up and running now! 🚀

**Comment by benjifriedman** [comment]
I was getting the same error message. reset pip cache, but what finally ended up working was re-downloading the `sd-v1-4.ckpt`

**Comment by psychedelicious** [comment]
No response, closing (also we have new install methods which hopefully take care of any platform-related dep issues)

**Comment by craftfortress** [comment]
No longer an issue after new install scripts thank you keep up the great work
