### ISSUE TITLE
Dreambooth support

### ISSUE THREAD

**Issue by Any-Winter-4079** [invoke-ai/InvokeAI#995]
This issue is to discuss Dreambooth (whether fully integrating it in this repo -training and inference-, or training via 3rd party, for example Colab, and doing inference in this repo).
Discussion and comparison with regular Textual Inversion is also encouraged.

**Comment by hipsterusername** [comment]
+1

Will also note there have been discussions of making it easy to generate (or import) new concepts from the WebUI. Should support both textual inversion & dreambooth, and plans include having a "library" of these for ongoing use.

I think, given the purpose and intent of this repo, full integration should be the aim.

**Comment by Any-Winter-4079** [comment]
Interesting comparison:
https://www.reddit.com/r/StableDiffusion/comments/xjlv19/comparison_of_dreambooth_and_textual_inversion/

> What I've noticed:
> Textual inversion:
> 
> Excels at style transfer. "[elephant in the style of Marsey](https://i.imgur.com/HbUX4Xh.jpg)"
> 
> May benefit from more images. My run with [74 images](https://i.imgur.com/CrJAKYc.png) performed better than the [one with 3](https://i.imgur.com/VsSAArJ.png)
> 
> Best results (both in terms of style transfer and character preservation) at ~25,000 steps
> 
> DreamBooth ([model download](https://mega.nz/file/FxclSKoL#EFSM4nLlXMuOvBLkoZNmtOH4Y8oycjrU7h2Hn6mKl1k)):
> 
> Far, far better for my use case. The character is more editable and the composition improves. It doesn't match the art style quite as well, though.
> 
> 3 images worked better than 72
> 
> works [extremely well](https://i.imgur.com/RBfcAMS.png) with cross-attention prompt2prompt (the "img2img alternative test" script in automatic1111's UI)
> 
> 1,000 steps (~30min on an A6000) is sufficient for good results
> 
> Worth mentioning - it's usable with deforum for [animations](https://imgur.com/hm3JJg6)
> 
> Combining the two doesn't seem to work, unfortunately. The next step might be either to directly finetune the network itself and apply one of these techniques afterwards, or possibly training the [classifier](https://github.com/Jack000/glid-3-xl-stable/wiki/Classifier-guided-stable-diffusion).

**Comment by Any-Winter-4079** [comment]
My best success at Textual Inversion was with 3-5 images, so I'll try with many more.
Also, it seems Dreambooth may better preserve the character.
Results from post above:
Dreambooth
<img width="500" alt="Screenshot 2022-10-09 at 16 55 18" src="https://user-images.githubusercontent.com/50542132/194763779-88c28bdc-4787-41fa-bef4-0c75247196f3.png">
Textual Inversion
<img width="500" alt="Screenshot 2022-10-09 at 16 55 32" src="https://user-images.githubusercontent.com/50542132/194763791-b35b4344-2956-4daa-91b9-f40193142c58.png">

**Comment by tildebyte** [comment]
Even better, an actual implementation in 10G VRAM https://www.reddit.com/r/StableDiffusion/comments/xtc25y/dreambooth_stable_diffusion_training_in_10_gb/?context=3

**Comment by tildebyte** [comment]
If you're me (or like me), and you're wondering about the difference between the two, AFAUI (big caveat), TI *can't* do things like taking a fine-tuned (Dreambooth) model which is capable of creating these

![image](https://user-images.githubusercontent.com/337875/194767651-6e861b97-2384-4ad8-bd61-c21a0c8f750c.png)

and creating this

![image](https://user-images.githubusercontent.com/337875/194767681-87752f4b-95de-433e-9818-030ae07f94e7.png)

which is just utterly amazing

**Comment by Any-Winter-4079** [comment]
@tildebyte I tried [this Colab](https://colab.research.google.com/github/ShivamShrirao/diffusers/blob/main/examples/dreambooth/DreamBooth_Stable_Diffusion.ipynb) (the one in the reddit post you share), but in the free tier, you have to pass `--use_8bit_adam` and not use full precision, which seemingly affects quality (I tried training with images of myself and it performed worse than TI).

It was a few days ago, so I may try again, just to see if they've introduced any other improvement.
Did you have any success with that Colab?

**Comment by tildebyte** [comment]
Colab doesn't have a free tier anymore (AFAIU); I haven't touched it since the change.

**Comment by Any-Winter-4079** [comment]
I think there is potential in TI, but I want to get Dreambooth to work, and compare them.

@tildebyte Here are some TI results, for comparison with what you refer to in https://github.com/invoke-ai/InvokeAI/issues/995#issuecomment-1272576376
Original images:  https://github.com/invoke-ai/InvokeAI/issues/517#issuecomment-1259486440. I used 5 of the 7 images to train.
After training TI with this repo (changing to `num_vectors_per_token: 6` in `v1-inference.yaml`), these are some of the results I can achieve.

### Workflow 1
Use `txt2img` playing with prompt weighting (N)

`txt2img`
`"a painting of * :N on the beach in the style of van gogh" -s 50 -S 989419747 -W 512 -H 512 -C 7.5 -A k_lms` for several `N` values.
![image](https://user-images.githubusercontent.com/50542132/194777898-51092a28-4ca2-48d4-b65e-e0bab7ba1074.png)


### Workflow 2
Obtain a concept with `txt2img` and swap it with `*` using `img2img` playing with different `-f` (strength) values

`txt2img`
`"close-up of a man low poly" -s 50 -S 3319463269 -W 512 -H 512 -C 7.5 -A k_lms`
<img width="160" alt="Screenshot 2022-10-09 at 20 15 00" src="https://user-images.githubusercontent.com/50542132/194772884-ddd60524-15d5-4a3e-a717-8c8c2f2f2220.png">
`img2img`
`"close-up of * low poly" -I outputs/preflight/000310.3319463269.png -S3319463269` for several `-f` values
<img width="1441" alt="image" src="https://user-images.githubusercontent.com/50542132/194772407-a7975225-37e4-47f9-b049-c9b21c15a352.png">

`txt2img`
`"Funky pop african man face figurine, product studio shot, on a white background, diffused lighting, centered" -s 50 -S 3231549968 -W 512 -H 512 -C 7.5 -A k_lms`
<img width="160" alt="Screenshot 2022-10-09 at 22 19 47" src="https://user-images.githubusercontent.com/50542132/194777786-376b23b9-21fe-4517-8ba4-5f4904f348e5.png">
inspired by https://publicprompts.art/funky-pop/
`img2img`
`Funky pop * face figurine, product studio shot, on a white background, diffused lighting, centered -I outputs/preflight/000384.3231549968.png -S3231549968` for several `-f` values
<img width="1635" alt="image" src="https://user-images.githubusercontent.com/50542132/194777751-0db0100c-dbbc-40b8-a33e-4017cd2d69a5.png">




(By the way, the training images in https://github.com/invoke-ai/InvokeAI/issues/517#issuecomment-1259486440 were personally created by the author of the comment, and the character  will appear on some project -which I find pretty cool- so you can use them to test TI but don't share them as training set)

I've also managed to train using a couple other concepts (hamburger, dog cartoon and myself), but results weren't that good. For people, I wonder if using some 'beautify' filter on the training set wold help, to make sure the face looks closer to a 3D character -very smooth, so it doesn't have to learn patterns inside the face, e.g. cheek colors, smiles, wrinkles, etc. and can focus on learning more generally the face shape).

**Comment by Any-Winter-4079** [comment]
All in all, I tend to prefer the "`txt2img` then `img2img`" workflow

**Comment by Any-Winter-4079** [comment]
@tildebyte But yeah, the word out there seems to be Dreambooth is better at styling. For example, this is a quick attempt (using `txt2img` && `img2img`) at your pictures above, and you can see how the style is a bit lost, and colors start to appear.
<img width="413" alt="image" src="https://user-images.githubusercontent.com/50542132/194779158-c0465c32-60ac-4747-8abd-e3166b7769dc.png">

It may still be possible to do these things with Textual Inversion, but it may require a more complex workflow, while Dreambooth may be easier to use.

Still, if someone has successfully used free Colab for Dreambooth and has had success, you are encouraged to share it here! The more info we have (what Colab, obviously, but also number of training images, lighting, closeness...), the better.

**Comment by bbecausereasonss** [comment]
Dreambooth is INCREDIBLE. No contest.

**Comment by Any-Winter-4079** [comment]
A 2nd Colab option.
https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb

**Comment by Any-Winter-4079** [comment]
Update: I've tried https://colab.research.google.com/github/ShivamShrirao/diffusers/blob/main/examples/dreambooth/DreamBooth_Stable_Diffusion.ipynb a bunch of times and I can't get it to work well. It does run, and the result has some resemblance, but that's all.

Last attempt was with 50 training images and 150 reg images. `--use_8bit_adam` and `--gradient_checkpointing` as well for the free Colab.
