### ISSUE TITLE
New txt2img image generation?

### ISSUE THREAD

**Issue by Any-Winter-4079** [invoke-ai/InvokeAI#998]
Right now, in `ldm/models/diffusion/ksampler.py`, we have
```
if x_T is not None:
     if x0 is not None:
           x = x_T + torch.randn_like(x0, device=self.device) * sigmas[0]
     else:
          x = x_T * sigmas[0]
else:
      x = torch.randn([batch_size, *shape], device=self.device) * sigmas[0]
```
which for `txt2img` uses 
`x = x_T * sigmas[0]`
creating e.g.
<img width="150" alt="Screenshot 2022-10-08 at 18 10 07" src="https://user-images.githubusercontent.com/50542132/194716943-6a8aef20-edb4-4e2e-a397-d920bd24372b.png">
for `"an anime girl" -W512 -H512 -C7.5 -S3031912972`
This is the current behavior and the one that lets you reproduce all of your old generations.

For `img2img` we use
`x = x_T + torch.randn_like(x0, device=self.device) * sigmas[0]`

The additional feature I propose is to allow users to optionally use
`x = x_T + torch.randn_like(x_T, device=self.device) * sigmas[0]` for `txt2img` creating
<img width="150" alt="Screenshot 2022-10-08 at 18 12 39" src="https://user-images.githubusercontent.com/50542132/194717052-3392f403-33a5-4275-8075-3d5c4a02aad2.png">

This is basically the behavior for `img2img` applied to `txt2img` (note we can't overwrite the `txt2img` behavior or old generations won't be reproducible).

A pseudo answer is:
```
if x_T is not None:
     if x0 is not None:
           x = x_T + torch.randn_like(x0, device=self.device) * sigmas[0]
     else:
           if X_prompt_arg:
                     # new txt2img behavior
                     x = x_T + torch.randn_like(x_T, device=self.device) * sigmas[0]
           else:
                     # old txt2img behavior for reproducibility
                     x = x_T * sigmas[0]
else:
      x = torch.randn([batch_size, *shape], device=self.device) * sigmas[0]
```

This could be passed as an argument to the `dream>` command (what I make reference to with `X_prompt_arg` in `ksampler.py`)

**Comment by Any-Winter-4079** [comment]
Note that that logs after the image is generated should reflect this new argument for reproducibility.

**Comment by Any-Winter-4079** [comment]
One thing I must add is that I'm not sure if `x = x_T + torch.randn_like(x_T, device=self.device) * sigmas[0]` adds something meaningful, vs.` x = x_T * sigmas[0]`. By meaningful I mean e.g. a new noise pattern that can't be obtained the other way, and thus those results are new and can't be reproduced using ` x = x_T * sigmas[0]`.

If that is not the case, then I don't think this request is useful. Someone more knowledgeable let me know.

**Comment by Any-Winter-4079** [comment]
Actually, doing some tests with variations:
These are variations using `img2img`
<img width="990" alt="image" src="https://user-images.githubusercontent.com/50542132/194728660-1d53c988-452e-4a02-b4da-ee4c8b123b0f.png">
These are variations using `txt2img` and `x = x_T * sigmas[0]`
<img width="990" alt="image" src="https://user-images.githubusercontent.com/50542132/194728736-e59c3030-1cb3-479a-a254-b43a5ef5e63e.png">
These are variations with txt2img and `x = x_T + torch.randn_like(x_T, device=self.device) * sigmas[0]`
<img width="990" alt="image" src="https://user-images.githubusercontent.com/50542132/194728920-cb4f196f-8a07-44b0-8519-c0f16806040f.png">

So while `x = x_T + torch.randn_like(x_T, device=self.device) * sigmas[0]` works for txt2img, it doesn't seem to work for variations.

**Comment by Any-Winter-4079** [comment]
Also, I'm seeing that maybe we need to fine-tune how we do our variations, both for `img2img` and `txt2img`.
`txt2img` seems to go random too soon, by around -v0.5
`img2img` seems to very closely follow the source image, at all `-v` options, although that is in part helped by the source image not being a sketch / rough image.

**Comment by lstein** [comment]
I think we need to take a careful look at how the choice of sampler affects variation. I see a huge amount of variation when using `k_euler_a`, for example.

**Comment by Any-Winter-4079** [comment]
k_euler_a doesn't converge afaik, so I'm not even sure if we can do variations. We may need a different technique (same for k_dpm_2_a)
